### ISSUE TITLE
Problem for downloading torrent with YGGCookie

### ISSUE THREAD

**Issue by bossovitch** [Jackett/Jackett#10013]
Hello
I have a problem, I configured YGGCookie last week, it passed the test.
Tuesday, the indexer automatically grabs a file with no problem, I haven't touched anything, and since yesterday I have an error for download torrent file ... but search works fine
Any idea to solve this problem?

### Environment

**OS**: Ubuntu 16.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Environment version: 3.1.9

**.Net Version**:

**Jackett Version**: Jackett variant: CoreLinuxAmdx64 0.16.933

**Last Working Jackett Version**: the version of last Tuesday

**Are you using a proxy or VPN?** [yes/no] no

### Description

Search and download with the integrated search or via Sonarr or Radarr produce the error

### Logged Error Messages

2020-10-29 12:18:02 | Info | Manual search for "starwars" on yggcookie with 6 results.
-- | -- | --
2020-10-29 12:18:01 | Info | Fetching: https://www2.yggtorrent.si/engine/search?category=all&name=starwars&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date
2020-10-29 12:18:01 | Info | Fetching: https://www2.yggtorrent.si/engine/search?category=all&name=%22starwars%22&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date
2020-10-29 12:17:55 | Error | Error downloading. indexer: yggcookie path: https://www2.yggtorrent.si/engine/download_torrent?id=279636 System.Exception: BencodeParser failed  ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found 'V' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'    at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)    at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)    at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 78    --- End of inner exception stack trace ---    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 85
2020-10-29 12:17:55 | Error | Vous devez vous connecter pour télécharger un torrent
2020-10-29 12:17:53 | Info | Manual search for "starwars" on yggcookie with 6 results

and Also this error when i'have updated to 0.16.1933 this morning

2020-10-29 11:49:38 | Error | Error while parsing Cardigann definition /home/user1/Jackett/Definitions/ygg-cookie.yml YamlDotNet.Core.YamlException: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization  ---> System.Runtime.Serialization.SerializationException: Property 'site' not found on type 'Jackett.Common.Models.IndexerDefinition'.    at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)    at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)    --- End of inner exception stack trace ---    at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)    at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)    at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)    at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)    at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)    at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass15_0.<InitCardigannIndexers>b__3(FileInfo file) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 163
-- | -- | --

**Comment by garfield69** [comment]
Session cookies expire and need to be renewed periodically so try fetching a fresh cookie and update the YGGCookie config.
Also, check your account at YGGTorrent and confirm you have not reached a DL limit and that your ratio is good, your downloads may be being blocked.
BTW, starting with Jackett 0.16.1922 you should be able to make use of the YGGTorrent indexer again.

**Comment by bossovitch** [comment]
ok, i will try to renew my cookie
My account has not reach any limit, i can grab some torrent normally when i browse and connect on yggtorrent website

**Comment by bossovitch** [comment]
OK, seems to work fine, i renew my cookie, and all return to normal

Do you know the validity period of these cookies?

Thanks for your help, and sorry for this stupid "problem" that wasn't really a problem ...

**Comment by garfield69** [comment]
session cookies expiry dates are determined by the web site operators. 
Some sites expire cookies daily, others weekly, fortnightly, monthly, and some don't expire at all. 
looking at the session cookie on my browser just after login into yggtorrent, I would hazard a guess that the cookie expires after 7 day, I see a `"max_age":604800` which is `7 * 24 * 60 * 60`
