### ISSUE TITLE
[tenyardtracker] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by PrimetimeFluff** [Jackett/Jackett#10020]
### Environment

**OS**:
Docker on debian

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
Jackett Version 0.16.1933.0

**Are you using a proxy or VPN?** [yes/no]
no

### Description
Add TYT and then test

### Logged Error Messages

System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 273
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

**Comment by bearsandbears** [comment]
> No one on the team has an account on the site so we cannot investigate independently.
> Do you have an invite?
Sign ups appear to be open

**Comment by garfield69** [comment]
Registration and Login successful. Cheers.

So from what I can see, TYT appear to have moved to a new web engine which appears to be forum based, without a torrent listing page, but topics posts with free form attachments of torrents?

However, there is a notice sticked at the top stating the old site will be returning soon.
Then again, in the discussion threads, the FAQ topic suggests this happened back in Oct 2019 so the switch back from this forum based to the old tracker engine is yet to happen.

So should I invest time trying to rewrite the indexer to cope with this new layout or just wait until the old site is reloaded?

Can anyone one in the loop advise?

**Comment by ngosang** [comment]
ping @garfield69

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/10020#issuecomment-728414560

**Comment by ngosang** [comment]
After several months this indexer is still not working in Jackett and no one is complaining. We can add the "rewrite in C#" label or remove the tracker. As you wish.

**Comment by garfield69** [comment]
I'll do both. remove the indexer that is not working and flag the ticket as a needs c# rewrite.

**Comment by garfield69** [comment]
closing in favour of #795
