### ISSUE TITLE
kickasstorrent-kathow: error while parsing row 

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10035]
query: 720p
```
CardigannIndexer (kickasstorrent-kathow): Error while parsing row '
<tr class="even" id="torrent_latest_torrents">
	<td>
		<div class="iaconbox center floatright">
			<a class="icommentjs kaButton smallButton rightButton">0<i class="ka ka-comment"></i>
			</a>
			<a rel="nofollow, noreferrer" data-nop="" title="Torrent magnet link" href="https://mylink.cx/?url=magnet%3A%3Fxt%3Durn%3Abtih%3A80B1BD6E9CD39FD311271E0F86762C6F9F6E6D45%26dn%3DSeven%2BSeconds%2B-%2BTemporada%2B1%2B%255BHDTV%2B720p%255D%255BCap.101_110%255D%255BAC3%2B5.1%2BEspa%25C3%25B1ol%2BCastellano%255D%26tr%3Dudp%253A%252F%252Ftracker.openbittorrent.com%253A80%26tr%3Dudp%253A%252F%252Fopen.demonii.com%253A1337%26tr%3Dudp%253A%252F%252Ftracker.coppersurfer.tk%253A6969%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce" class="icon16">
				<i class="ka ka16 ka-magnet"></i>
			</a>
			<a rel="nofollow, noreferrer" data-download="" title="Download torrent file" href="https://mylink.cx/?url=magnet%3A%3Fxt%3Durn%3Abtih%3A80B1BD6E9CD39FD311271E0F86762C6F9F6E6D45%26dn%3DSeven%2BSeconds%2B-%2BTemporada%2B1%2B%255BHDTV%2B720p%255D%255BCap.101_110%255D%255BAC3%2B5.1%2BEspa%25C3%25B1ol%2BCastellano%255D%26tr%3Dudp%253A%252F%252Ftracker.openbittorrent.com%253A80%26tr%3Dudp%253A%252F%252Fopen.demonii.com%253A1337%26tr%3Dudp%253A%252F%252Ftracker.coppersurfer.tk%253A6969%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce" target="_blank" class="icon16">
				<i class="ka ka16 ka-arrow-down"></i>
			</a>
			
			<!--<a data-download title="Download torrent file" href="http://itorrents.org/torrent/80b1bd6e9cd39fd311271e0f86762c6f9f6e6d45.torrent?title=%5Bkickass.ws%5DSeven+Seconds+-+Temporada+1+%5BHDTV+720p%5D%5BCap.101_110%5D%5BAC3+5.1+Espa%C3%B1ol+Castellano%5D" target="_blank" class="icon16"><i class="ka ka16 ka-arrow-down"></i></a>-->
		</div>
		<div class="torrentname">
			<a href="/t2-Seven-Seconds-Temporada-1-HDTV-720pCap-101-110AC3-5-1-Espaol-Castellano.html" class="torType film"></a>
			<a href="/t2-Seven-Seconds-Temporada-1-HDTV-720pCap-101-110AC3-5-1-Espaol-Castellano.html" class="normalgrey font12px plain bold"></a>
			<div class="markeredBlock torType filmType">
				<a href="/t2-Seven-Seconds-Temporada-1-HDTV-720pCap-101-110AC3-5-1-Espaol-Castellano.html" class="cellMainLink">Seven Seconds - Temporada 1 [HDTV 720p][Cap.101_110][AC3 5.1 Español Castellano]</a>
				
				<!--<span class="font11px lightgrey block">-->
			</div>
		</div>
	</td>
	<td class="nobr center">21.76 GB</td>
	<td class="center" title="2 years ago">2 years ago</td>
	<td class="green center">N/A</td>
	<td class="red lasttd center">N/A</td>
</tr>':

System.Exception: Error while parsing field=category, selector=span[id^="cat_"] > strong > a, value=<null>: Selector "span[id^="cat_"] > strong > a" didn't match 
<tr class="even" id="torrent_latest_torrents">
	<td>
		<div class="iaconbox center floatright">
			<a class="icommentjs kaButton smallButton rightButton">0<i class="ka ka-comment"></i>
			</a>
			<a rel="nofollow, noreferrer" data-nop="" title="Torrent magnet link" href="https://mylink.cx/?url=magnet%3A%3Fxt%3Durn%3Abtih%3A80B1BD6E9CD39FD311271E0F86762C6F9F6E6D45%26dn%3DSeven%2BSeconds%2B-%2BTemporada%2B1%2B%255BHDTV%2B720p%255D%255BCap.101_110%255D%255BAC3%2B5.1%2BEspa%25C3%25B1ol%2BCastellano%255D%26tr%3Dudp%253A%252F%252Ftracker.openbittorrent.com%253A80%26tr%3Dudp%253A%252F%252Fopen.demonii.com%253A1337%26tr%3Dudp%253A%252F%252Ftracker.coppersurfer.tk%253A6969%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce" class="icon16">
				<i class="ka ka16 ka-magnet"></i>
			</a>
			<a rel="nofollow, noreferrer" data-download="" title="Download torrent file" href="https://mylink.cx/?url=magnet%3A%3Fxt%3Durn%3Abtih%3A80B1BD6E9CD39FD311271E0F86762C6F9F6E6D45%26dn%3DSeven%2BSeconds%2B-%2BTemporada%2B1%2B%255BHDTV%2B720p%255D%255BCap.101_110%255D%255BAC3%2B5.1%2BEspa%25C3%25B1ol%2BCastellano%255D%26tr%3Dudp%253A%252F%252Ftracker.openbittorrent.com%253A80%26tr%3Dudp%253A%252F%252Fopen.demonii.com%253A1337%26tr%3Dudp%253A%252F%252Ftracker.coppersurfer.tk%253A6969%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce" target="_blank" class="icon16">
				<i class="ka ka16 ka-arrow-down"></i>
			</a>
			
			<!--<a data-download title="Download torrent file" href="http://itorrents.org/torrent/80b1bd6e9cd39fd311271e0f86762c6f9f6e6d45.torrent?title=%5Bkickass.ws%5DSeven+Seconds+-+Temporada+1+%5BHDTV+720p%5D%5BCap.101_110%5D%5BAC3+5.1+Espa%C3%B1ol+Castellano%5D" target="_blank" class="icon16"><i class="ka ka16 ka-arrow-down"></i></a>-->
		</div>
		<div class="torrentname">
			<a href="/t2-Seven-Seconds-Temporada-1-HDTV-720pCap-101-110AC3-5-1-Espaol-Castellano.html" class="torType film"></a>
			<a href="/t2-Seven-Seconds-Temporada-1-HDTV-720pCap-101-110AC3-5-1-Espaol-Castellano.html" class="normalgrey font12px plain bold"></a>
			<div class="markeredBlock torType filmType">
				<a href="/t2-Seven-Seconds-Temporada-1-HDTV-720pCap-101-110AC3-5-1-Espaol-Castellano.html" class="cellMainLink">Seven Seconds - Temporada 1 [HDTV 720p][Cap.101_110][AC3 5.1 Español Castellano]</a>
				
				<!--<span class="font11px lightgrey block">-->
			</div>
		</div>
	</td>
	<td class="nobr center">21.76 GB</td>
	<td class="center" title="2 years ago">2 years ago</td>
	<td class="green center">N/A</td>
	<td class="red lasttd center">N/A</td>
</tr>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1607

```

**Comment by ngosang** [comment]
"query": "silicon valley"
```
CardigannIndexer (kickasstorrent-kathow): Error while parsing row '
<tr class="even" id="torrent_latest_torrents">
	<td>
		<div class="iaconbox center floatright">
			<a class="icommentjs kaButton smallButton rightButton">12<i class="ka ka-comment"></i>
			</a>
			<a class="icon16" href="/t3-Silicon-Valley-S00E04-1080p-AMZN-WEB-DL-x265-HEVC-10bit-AC3-5-1-Qman-UTR-tt4189665.html" title="Verified Torrent">
				<i class="ka ka16 ka-verify ka-green"></i>
			</a>
			<a rel="nofollow, noreferrer" data-nop="" title="Torrent magnet link" href="https://mylink.cx/?url=magnet%3A%3Fxt%3Durn%3Abtih%3AB021772F443FEFAFD67F04B3FACE50BE45F5328E%26dn%3DSilicon%2BValley%2BS00E04%2B%25281080p%2BAMZN%2BWEB-DL%2Bx265%2BHEVC%2B10bit%2BAC3%2B5.1%2BQman%2529%2B%255BUTR%255D%26tr%3Dudp%253A%252F%252F9.rarbg.com%253A2710%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.torrent.eu.org%253A451%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.coppersurfer.tk%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.zer0day.to%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fcoppersurfer.tk%253A6969%252Fannounce" class="icon16">
				<i class="ka ka16 ka-magnet"></i>
			</a>
			<a rel="nofollow, noreferrer" data-download="" title="Download torrent file" href="https://mylink.cx/?url=magnet%3A%3Fxt%3Durn%3Abtih%3AB021772F443FEFAFD67F04B3FACE50BE45F5328E%26dn%3DSilicon%2BValley%2BS00E04%2B%25281080p%2BAMZN%2BWEB-DL%2Bx265%2BHEVC%2B10bit%2BAC3%2B5.1%2BQman%2529%2B%255BUTR%255D%26tr%3Dudp%253A%252F%252F9.rarbg.com%253A2710%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.torrent.eu.org%253A451%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.coppersurfer.tk%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.zer0day.to%253A1337%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.leechers-paradise.org%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Fcoppersurfer.tk%253A6969%252Fannounce" target="_blank" class="icon16">
				<i class="ka ka16 ka-arrow-down"></i>
			</a>
			
			<!--<a data-download title="Download torrent file" href="http://itorrents.org/torrent/b021772f443fefafd67f04b3face50be45f5328e.torrent?title=%5Bkickass.ws%5DSilicon+Valley+S00E04+%281080p+AMZN+WEB-DL+x265+HEVC+10bit+AC3+5.1+..." target="_blank" class="icon16"><i class="ka ka16 ka-arrow-down"></i></a>-->
		</div>
		<div class="torrentname">
			<a href="/t3-Silicon-Valley-S00E04-1080p-AMZN-WEB-DL-x265-HEVC-10bit-AC3-5-1-Qman-UTR-tt4189665.html" class="torType Video"></a>
			<a href="/t3-Silicon-Valley-S00E04-1080p-AMZN-WEB-DL-x265-HEVC-10bit-AC3-5-1-Qman-UTR-tt4189665.html" class="normalgrey font12px plain bold"></a>
			<div class="markeredBlock torType VideoType">
				<a href="/t3-Silicon-Valley-S00E04-1080p-AMZN-WEB-DL-x265-HEVC-10bit-AC3-5-1-Qman-UTR-tt4189665.html" class="cellMainLink">Silicon Valley S00E04 (1080p AMZN WEB-DL x265 HEVC 10bit AC3 5.1 ...</a>
				
				<!--<span class="font11px lightgrey block">-->                   Posted by
				<i title="Trusted Uploader" class="ka ka-verify" style="font-size: 16px;color:orange;"></i>
				UTRCorp                          in
				<span id="cat_12975568">
					<strong>
						<a href="/tv" target="_blank">TV</a>
					</strong>
				</span>
			</div>
		</div>
	</td>
	<td class="nobr center">1.014.2 MB</td>
	<td class="center" title="9 months ago">9 months ago</td>
	<td class="green center">9</td>
	<td class="red lasttd center">0</td>
</tr>':

System.Exception: Error while parsing field=size, selector=td:nth-child(2), value=1.014.2 MB: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1607
```
