### ISSUE TITLE
[exkinoray] Login failed: Selector

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10030]
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 815
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 984
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26****

**Comment by garfield69** [comment]
the indexer is working for me which suggests the problem is at your end.
unfortunately the stack trace you provided simply reports that the indexer was not able to find the logout link on the next page after the login, which implies that the login failed for some reason.
it could be that your account credentials are invalid (suspended, deleted, bad password, bad ratio, unread alerts, unread notices, unread PM) something.
we could possibly see more clues if you provided an **enhanced** log 
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-turn-on-enhanced-logging for details.

**Comment by berat1397** [comment]
My logs: 
[log.txt](https://github.com/Jackett/Jackett/files/5470048/log.txt)

**Comment by garfield69** [comment]
@berat1397  this is not a **enhanced** log, its a regular one, it just has **info** and **error** messages.
you can spot the enhanced one, it contains **debug** and **html** messages
be aware that if you restart jackett the enhanced switched is turned off.
on the dashboard set the switch, click the apply server settings button and repeat the test.

**Comment by berat1397** [comment]
I dont login and add this site in my jackett. So I cant test.
I just getting this error. My username and password is right.
[log.txt](https://github.com/Jackett/Jackett/files/5470604/log.txt)
![Log_error](https://user-images.githubusercontent.com/36575395/97801065-2099b000-1c4b-11eb-95ee-4bf4b4229a19.JPG)
![Login_error](https://user-images.githubusercontent.com/36575395/97801068-21cadd00-1c4b-11eb-8a09-b23f91e406fa.JPG)

**Comment by garfield69** [comment]
Hmm.
the only clue in the enhanced log is
```
2020-11-01 14:07:41.0484 Debug WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: http://exkinoray.tv/takelogin.php) 
2020-11-01 14:07:41.9106 Debug WebClient(HttpWebClient2): Returning Forbidden => 0 bytes 
```
So the web site is rejecting your attempt to login sending a http 403 error

is this the first time you are setting up the exkinoray indexer, or was it working previously?

the indexer is set up to supports only the UTF-8 character set https://www.utf8-chartable.de/ since this is what the web site specifies
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>ExKinoRay.TV :: Главная</title>
```
but this means that if your username and password contain Russian letters and symbols then your credentials are not stored by the indexer correctly.
Could this apply to you?

**Comment by berat1397** [comment]
Yes I first time try add this site.

Haven't russian character my password. All characters is normal.

**Comment by garfield69** [comment]
ok then.
so the browser you are using is on the same system that is running jackett?
what platform is jackett running on?

**Comment by berat1397** [comment]
I'm using Firefox for jackett.
My OS Windows 10.

**Comment by garfield69** [comment]
Well I have no clue why you can not use the exkinoray indexer. I do not know why you are seeing a forbidden message when you can login to this semi-private web site ok.
@ngosang  @ilike2burnthing  any thoughts on this issue?

**Comment by ilike2burnthing** [comment]
Incorrect login details, including those with Russian or special characters, should just return: `Error: Ошибка входаВы не зарегистрированы в системе.` - `Error: Login failed You are not logged in.`

Can you test using Firefox, Chrome (or anything Chromium), and Internet Explorer if you can specifically open http://exkinoray.tv/takelogin.php in all 3?

It should give you a completely blank page, no error.

Are you using either a proxy or VPN?

**Comment by berat1397** [comment]
I dont use vpn or proxy.

**Comment by ilike2burnthing** [comment]
Any luck accessing that link on different browsers?

**Comment by berat1397** [comment]
I find problem. Problem is my security software. I add this site exception and problem is fixed. Thank you for your help.
