### ISSUE TITLE
indexer exception error 

### ISSUE THREAD

**Issue by cooper7692** [Jackett/Jackett#10043]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1989.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
no

### Description

just click search all missing on sonarr does the trick sonarr log shows similar error

''' sonnar log for reference --
 NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (iptorrents): TimeAgo parsing failed, unknown unit: k
 ---> System.Exception: Parse error
 ---> System.Exception: TimeAgo parsing failed, unknown unit: k
   at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 77
   at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 224
   --- End of inner exception stack trace ---

'''

### Logged Error Messages

2020-11-01 04:24:36 | Error | Jackett.Common.IndexerException: Exception (iptorrents): TimeAgo parsing failed, unknown unit: k  ---> System.Exception: Parse error  ---> System.Exception: TimeAgo parsing failed, unknown unit: k    at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 77    at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 224    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 650    at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 267    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 627    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 448
-- | -- | --
2020-11-01 04:24:36 | Error | Error on 20201101092436 for IPTorrents.txtSystem.Exception: TimeAgo parsing failed, unknown unit: k    at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 77    at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 224

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ngosang** [comment]
Fixed by #10054

**Comment by ngosang** [comment]
Jackett v0.16.1996
