### ISSUE TITLE
[iptorrents] Your cookie did not work: Found 0 results in the tracker (Config)

### ISSUE THREAD

**Issue by cooper7692** [Jackett/Jackett#10042]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: ubuntu

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1673.0

**Last Working Jackett Version**: 0.16.1673.0

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
unkown just stopped working

### Logged Error Messages

"""

2020-11-01 03:42:10 | Error | System.Exception: Your cookie did not work: Found 0 results in the tracker    at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 164    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
-- | -- | --

"""

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by cooper7692** [comment]
> If you look at the IPtorrents website, they changed the HTML of the page, and the view is slightly different.
> 
> I had IPTorrents set up and working fine just an hour ago, it looks like the new website broke jackett scraper

agreed worked fine since i added it, not sure completely whats up, seems to be going in and out working when it wants too

**Comment by garfield69** [comment]
upgrade your Jackett to 0.16.1989 to pick up the fix

**Comment by cooper7692** [comment]
updated to newest version still getting some errors this is the main one

Jackett.Common.IndexerException: Exception (iptorrents): TimeAgo parsing failed, unknown unit: k
 ---> System.Exception: Parse error
 ---> System.Exception: TimeAgo parsing failed, unknown unit: k
   at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 77
   at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 224
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 650
   at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 267
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 627
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 448

&&&&&&


Error on 20201101091421 for IPTorrents.txtSystem.Exception: TimeAgo parsing failed, unknown unit: k
   at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 77
   at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 224

this one ^^^ is followed by the whole html doc type. in the log.

**Comment by cooper7692** [comment]
> upgrade your Jackett to 0.16.1989 to pick up the fix
already did and jacket still having issues.



> updated to newest version still getting some errors this is the main one
> 
> Jackett.Common.IndexerException: Exception (iptorrents): TimeAgo parsing failed, unknown unit: k
> ---> System.Exception: Parse error
> ---> System.Exception: TimeAgo parsing failed, unknown unit: k
> at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 77
> at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 224
> --- End of inner exception stack trace ---
> at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 650
> at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 267
> at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
> --- End of inner exception stack trace ---
> at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
> at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 627
> at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 448
> 
> &&&&&&
> 
> Error on 20201101091421 for IPTorrents.txtSystem.Exception: TimeAgo parsing failed, unknown unit: k
> at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 77
> at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 224
> 
> this one ^^^ is followed by the whole html doc type. in the log.

**Comment by cooper7692** [comment]
@garfield69

**Comment by BanditTech** [comment]
ok, awesome the linuxserver jackett container just got an update to 16.1989! :)

**Comment by BanditTech** [comment]
Updated to latest, and this is the error message I feel is where its going wrong:

```
Error on 20201101013131 for IPTorrents.txtSystem.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)
   at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)
   at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 239
```

**Comment by BanditTech** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5470493/log.txt)

**Comment by BanditTech** [comment]
If you look at the IPtorrents website, they changed the HTML of the page, and the view is slightly different.

**Comment by cooper7692** [comment]
i did note that, however the newest version of jackett worked i just ran the updater re added ipt and all good again

**Comment by cooper7692** [comment]
make sure you go to the browse tab hit f5 then grab your cookie.

**Comment by ngosang** [comment]
Jackett v0.16.1996
