### ISSUE TITLE
[iptorrents] Your cookie did not work: Parse error (Config)

### ISSUE THREAD

**Issue by tomnta** [Jackett/Jackett#10069]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:  Windows 8.1 Enterprise

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] 4

**.Net Version**: 4.8.03761

**Jackett Version**:

**Last Working Jackett Version**:  Jackett Version 0.16.1989.0

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Jackett was working great, now suddenly it's not working anymore with IPT.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

System.Exception: Your cookie did not work: Parse error
   at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\IPTorrents.cs:line 176
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/12528743/97816949-8475a600-1c56-11eb-9a1f-2d470e9f7859.png)

**Comment by tomnta** [comment]
I did a search and existing issue didn't show up.

Admins, please delete my issue, thank you.

**Comment by garfield69** [comment]
no worries. 
upgrade your Jackett to 0.16.1999 to resolve your iptorrents issue.
