### ISSUE TITLE
[trezzor] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by theerror** [Jackett/Jackett#10071]
### Environment

**OS**: Docker image

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: Embedded in docker image (do not know, but may find, if related)

**Jackett Version**: Jackett Version 0.16.1964.0

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** [no]

### Description

Add trezzor tracker. It's added successful, but there aren't any results. 

![image](https://user-images.githubusercontent.com/4508328/97820971-e531cc80-1cb0-11eb-839b-3abed7bcaf6b.png)

**Comment by theerror** [comment]
Error message found in logs.
```
System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 274
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by theerror** [comment]
Looks it's related to authorisation. I found in debug logs the html page, what appears the same when I would try to visit search site without authorisation.

```
...
 <td valign=top><div align="center"><br /><table border="0" width="500" cellspacing="0" cellpadding="0"><tr>
<td bgcolor="#FFFFFF" align="center" style="border-style: dotted; border-width: 1px" bordercolor="#CC0000">
<font color="#CC0000"><b>ERRORNOT_AUTHORIZED Torrenty!</b><br />Sorry...<br /></font></td>
</tr></table></div><br />
...
```

and here page in browser without login

![image](https://user-images.githubusercontent.com/4508328/97821762-e3b5d380-1cb3-11eb-8f7c-44f40b858f84.png)

so, question is, what is issue with login :/

**Comment by theerror** [comment]
Hmm... I think I found the reason... looks tracker not accepting two different session and as soon as I login to tracker in UI, it stop working, but after remove and re-add, it's working fine, until I will try to login in browser. 

I can live, with, but would it be possible to enhance login process, that it will "reauthentificate" by some way, in case of invalided session the other way, that adding and removing tracker conf?

**Comment by garfield69** [comment]
The only way (short of rewriting the indexer in C#) to handle this in yaml, is to avoid the login process by using the cookie method.
The caveat is that this only works for users that can run a browser on the same machine that is running Jackett, since the web site is using cloudflare services and if the web site's cookie is session specific it will probably want not only the same session id but the same ip and possible other system details.

We are not going to rewrite into C# because this indexer was C# back in 2017 and was converted to yaml #1860, don't know why, its not clear from ticket details.

IF you want me to switch this indexer to using the cookie method let me know or close the ticket if not.

**Comment by theerror** [comment]
So it will in principal the same as used to be for CZTracker then (filling in the cookies data get from browser)? In it's case it were working quite fine and only the IP had to match, so using ex. ssh socks proxy were working quite fine. If it would work the same way here it would be awesome. 

However if there would be some nasty session checking, wondering if it makes any sense to steal your time on it, if it won't work much better than then now anyway. 

Are you wiling to spend some time on give a try how session login will work?

**Comment by garfield69** [comment]
yes no problem. switching to cookie is a standard 6 line change, I'll code it shortly and it will be ready for tomorrow's release.

**Comment by theerror** [comment]
Thank you!

**Comment by garfield69** [comment]
try out 0.16.2040 and let us know how it goes.

**Comment by theerror** [comment]
Work like charm! I can now access tracker in browser as well as using in Jackett. Perfect. :)
Thank you!
