### ISSUE TITLE
rutracker-ru: error while parsing row 

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10126]
Empty search
```
CardigannIndexer (rutracker-ru): Error while parsing row '
<tr class="tCenter hl-tr" id="tor_305275">
	<td class="row1">
		<img src="./styles/templates/under/images/icon_minipost.gif" class="icon1" alt="Post">
	</td>
	<td class="row1 tCenter" title="checked">
		<span class="tor-icon tor-approved">√</span>
	</td>
	<td class="row1">
		<a class="gen" href="tracker.php?f=1632">Отечественный Рэп, Хип-Хоп (lossless)</a>
	</td>
	<td class="row4 med tLeft">
		<a class="genmed tLink" href="./viewtopic.php?t=149008">
			<b>(Rap, Hip-Hop) [STREAM] KREC - коллекция ( 5 альбомов, 20 синглов ), 2014-2020, FLAC, (tracks), lossless</b>
		</a>
	</td>
	<td class="row1">
		<a class="med" href="tracker.php?pid=1265597">
			<span title="Администратор" class="colorAdmin">MAGNAT</span>
		</a>
	</td>
	<td class="row4 small nowrap">
		<u>1821098026</u>
		<a class="small tr-dl" title="Download" href="./dl.php?id=147850">1.7&nbsp;GB</a>
		<span title="Magnet">
			<a href="magnet:?xt=urn:btih:1193c8d1ab05d841091a441b484c3d61420b41cf&amp;tr=http%3A%2F%2Frutracker.ru%2Fbt%2Fannounce.php%3Fuk%3D56WtM1NE1U">
				<img src="./styles/images/magnet.png" width="12" height="12" border="0">
			</a>
		</span>
	</td>
	<td class="row4 seedmed" title="Seeder not seen:
 Never">
		<b>0</b>
	</td>
	<td class="row4 leechmed" title="Leechers">
		<b>0</b>
	</td>
	<td class="row4 small" title="Replies: 0">0</td>
	<td class="row4 small nowrap" style="padding: 1px 3px 2px;" title="Added">
		<u>1604596743</u>
		<p>Yesterday 20:19</p>
		<p>5-Nov-20</p>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="tracker.php?f="], value=1632: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1540
```

**Comment by ngosang** [comment]
New cats 1640, 1643

**Comment by ngosang** [comment]
Jackett v0.16.2118

**Comment by ngosang** [comment]
New Cat 1655
Empty search

**Comment by ngosang** [comment]
@ilike2burnthing 
Empty query
```
CardigannIndexer (rutracker-ru): Error while parsing row '
<tr class="tCenter hl-tr" id="tor_309144">
	<td class="row1">
		<img src="./styles/templates/under/images/icon_minipost.gif" class="icon1" alt="Post">
	</td>
	<td class="row1 tCenter" title="checked">
		<span class="tor-icon tor-approved">√</span>
	</td>
	<td class="row1">
		<a class="gen" href="tracker.php?f=1657">Российские новинки в 1080р (2021)</a>
	</td>
	<td class="row4 med tLeft">
		<a class="genmed tLink" href="./viewtopic.php?t=151616">
			<b>Мажор. Фильм (Максим Полинский, Николай Булыгин) [2021, Боевик, комедия, WEBRip 1080p] [RUS]</b>
		</a>
	</td>
	<td class="row1">
		<a class="med" href="tracker.php?pid=771758">
			<span title="Администратор" class="colorAdmin">WOLF1245</span>
		</a>
	</td>
	<td class="row4 small nowrap">
		<u>4114588002</u>
		<a class="small tr-dl" title="Download" href="./dl.php?id=150502">3.83&nbsp;GB</a>
		<span title="Magnet">
			<a href="magnet:?xt=urn:btih:857b213a51933a5f578e92aa63662d9fc451d6d5&amp;tr=http%3A%2F%2Frutracker.ru%2Fbt%2Fannounce.php%3Fuk%3D56WtM1NE1U">
				<img src="./styles/images/magnet.png" width="12" height="12" border="0">
			</a>
		</span>
	</td>
	<td class="row4 seedmed" title="Seeders">
		<b>48</b>
	</td>
	<td class="row4 leechmed" title="Leechers">
		<b>82</b>
	</td>
	<td class="row4 small" title="Replies: 0">15</td>
	<td class="row4 small nowrap" style="padding: 1px 3px 2px;" title="Added">
		<u>1609571373</u>
		<p>Today 10:09</p>
		<p>2-Jan-21</p>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="tracker.php?f="], value=1657: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522

CardigannIndexer (rutracker-ru): Error while parsing row '
<tr class="tCenter hl-tr" id="tor_309146">
	<td class="row1">
		<img src="./styles/templates/under/images/icon_minipost.gif" class="icon1" alt="Post">
	</td>
	<td class="row1 tCenter" title="checked">
		<span class="tor-icon tor-approved">√</span>
	</td>
	<td class="row1">
		<a class="gen" href="tracker.php?f=1661">Российские новинки (2021)</a>
	</td>
	<td class="row4 med tLeft">
		<a class="genmed tLink" href="./viewtopic.php?t=151618">
			<b>Мажор. Фильм (Максим Полинский, Николай Булыгин) [2021, Боевик, комедия, WEBRip] [RUS]</b>
		</a>
	</td>
	<td class="row1">
		<a class="med" href="tracker.php?pid=771758">
			<span title="Администратор" class="colorAdmin">WOLF1245</span>
		</a>
	</td>
	<td class="row4 small nowrap">
		<u>1567782912</u>
		<a class="small tr-dl" title="Download" href="./dl.php?id=150504">1.46&nbsp;GB</a>
		<span title="Magnet">
			<a href="magnet:?xt=urn:btih:4b8f9a77d8c39d984b7cfde49a3602d3a07db0ab&amp;tr=http%3A%2F%2Frutracker.ru%2Fbt%2Fannounce.php%3Fuk%3D56WtM1NE1U">
				<img src="./styles/images/magnet.png" width="12" height="12" border="0">
			</a>
		</span>
	</td>
	<td class="row4 seedmed" title="Seeders">
		<b>37</b>
	</td>
	<td class="row4 leechmed" title="Leechers">
		<b>58</b>
	</td>
	<td class="row4 small" title="Replies: 0">11</td>
	<td class="row4 small nowrap" style="padding: 1px 3px 2px;" title="Added">
		<u>1609573177</u>
		<p>Today 10:39</p>
		<p>2-Jan-21</p>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="tracker.php?f="], value=1661: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522

CardigannIndexer (rutracker-ru): Error while parsing row '
<tr class="tCenter hl-tr" id="tor_309158">
	<td class="row1">
		<img src="./styles/templates/under/images/icon_minipost.gif" class="icon1" alt="Post">
	</td>
	<td class="row1 tCenter" title="checked">
		<span class="tor-icon tor-approved">√</span>
	</td>
	<td class="row1">
		<a class="gen" href="tracker.php?f=1661">Российские новинки (2021)</a>
	</td>
	<td class="row4 med tLeft">
		<a class="genmed tLink" href="./viewtopic.php?t=151630">
			<b>Мажор. Фильм (Максим Полинский, Николай Булыгин) [2021, Боевик, комедия, WEBRip-AVC] [RUS]</b>
		</a>
	</td>
	<td class="row1">
		<a class="med" href="tracker.php?pid=771758">
			<span title="Администратор" class="colorAdmin">WOLF1245</span>
		</a>
	</td>
	<td class="row4 small nowrap">
		<u>781694267</u>
		<a class="small tr-dl" title="Download" href="./dl.php?id=150516">745&nbsp;MB</a>
		<span title="Magnet">
			<a href="magnet:?xt=urn:btih:0cb6c8a5a4f816d49d43c05ef799121344e984e3&amp;tr=http%3A%2F%2Frutracker.ru%2Fbt%2Fannounce.php%3Fuk%3D56WtM1NE1U">
				<img src="./styles/images/magnet.png" width="12" height="12" border="0">
			</a>
		</span>
	</td>
	<td class="row4 seedmed" title="Seeders">
		<b>14</b>
	</td>
	<td class="row4 leechmed" title="Leechers">
		<b>37</b>
	</td>
	<td class="row4 small" title="Replies: 0">7</td>
	<td class="row4 small nowrap" style="padding: 1px 3px 2px;" title="Added">
		<u>1609578183</u>
		<p>Today 12:03</p>
		<p>2-Jan-21</p>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="tracker.php?f="], value=1661: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522
```
