### ISSUE TITLE
[scenetime] Your cookie did not work: Clearance failed after 10 attempt(s). (Config) (Does not work with proxy)

### ISSUE THREAD

**Issue by hyperhydra98** [Jackett/Jackett#10149]
### Environment

**OS**: Unraid 6.9.0-beta30 Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: ?

**Jackett Version**: 0.16.2080.0

**Last Working Jackett Version**: ? (I don't remember but probably around 2-3 months ago)

**Are you using a proxy or VPN?** Yes

### Description

I am not able to successfully get scenetime working on Jackett. I have tried to follow all the guidelines described in the guide and obtained the cookie while connected to the same VPN server/IP as the Jackett docker is using (through HTTP proxy). I am only able to get it working if I disable my proxy. When the proxy is active, I get an error when testing or adding a new scenetime instant. However, I am able to get other indexers that use cookies with my proxy turned on so I am unclear why it would be causing an issue here.

### Logged Error Messages

Keep getting this error: **Your cookie did not work: Clearance failed after 10 attempt(s).**

```
System.Exception: Your cookie did not work: Clearance failed after 10 attempt(s).
   at Jackett.Common.Indexers.SceneTime.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 151
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://user-images.githubusercontent.com/68359921/98511250-74e7f580-2232-11eb-9ae7-1dfbe9a9f41a.png)

**Comment by garfield69** [comment]
@ilike2burnthing @ngosang  can you take a look at this ticket?

**Comment by ilike2burnthing** [comment]
Unfortunately I think this links back to my first ever issue - https://github.com/Jackett/Jackett/issues/7325

If SceneTime drops the Cloudflare check, using cookies should work again with a proxy. Till then, it's either use SceneTime or the proxy (or set up a second instance of Jackett just for SceneTime without the proxy).
