### ISSUE TITLE
[scenefz] Parse error: Invalid URI: The hostname could not be parsed. (Config)

### ISSUE THREAD

**Issue by sadyque** [Jackett/Jackett#10151]
## Environment

**OS**: Unix 5.4.72.7

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: CoreLinuxArm32 v0.16.2124.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

System.Exception: Parse error
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Jackett.Common.Indexers.Abstract.XtremeZoneTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/XtremeZoneTracker.cs:line 134
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 686
   at Jackett.Common.Indexers.Abstract.XtremeZoneTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/XtremeZoneTracker.cs:line 165
   at Jackett.Common.Indexers.Abstract.XtremeZoneTracker.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/XtremeZoneTracker.cs:line 63
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

Error on 20201109094004 for Xtreme Zone.txtSystem.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Jackett.Common.Indexers.Abstract.XtremeZoneTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/XtremeZoneTracker.cs:line 134

**Comment by garfield69** [comment]
@RoloSoze  is SceneFZ working for you?

**Comment by RoloSoze** [comment]
@garfield69 No it's not. I'm getting the same error.

**Comment by garfield69** [comment]
@sadyque  please provide a full **enhanced** log. Hopefully the debug and HTML included will provide a clue to what may be going on. 
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
@RoloSoze  thanks for the info.
@ngosang  ping.

**Comment by sadyque** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5509758/log.txt)

**Comment by garfield69** [comment]
Jackett 0.16.2131

**Comment by sadyque** [comment]
resolved thx
