### ISSUE TITLE
Couldn't process tracked download For Invalid Windows Filename Characters

### ISSUE THREAD

**Issue by joshhazel** [Jackett/Jackett#10191]
### Environment
prod

**OS**:
Win 10

**Jackett Version**:
Jackett Version 0.16.2096.0

### Description
Couldn't process tracked download 311 - Universal Pulse (2011) <320kbs>: value [C:\Users\myusername\Downloads\311 - Universal Pulse (2011) <320kbs>]  is not a valid Windows path. paths must be a full path eg. C:\Windows
Parameter name: path

System.ArgumentException: value [C:\Users\myusername\Downloads\311 - Universal Pulse (2011) <320kbs>]  is not a valid Windows path. paths must be a full path eg. C:\Windows
Parameter name: path
   at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsValidPath(Param`1 param) in D:\a\1\s\src\NzbDrone.Common\EnsureThat\EnsureStringExtensions.cs:line 106
   at NzbDrone.Common.Disk.DiskProviderBase.FolderExists(String path) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 102
   at NzbDrone.Core.MediaFiles.DownloadedTracksImportService.ProcessPath(String path, ImportMode importMode, Artist artist, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedTracksImportService.cs:line 77
   at NzbDrone.Core.Download.CompletedDownloadService.Import(TrackedDownload trackedDownload) in D:\a\1\s\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 107
   at NzbDrone.Core.Download.CompletedDownloadService.Process(TrackedDownload trackedDownload, Boolean ignoreWarnings) in D:\a\1\s\src\NzbDrone.Core\Download\CompletedDownloadService.cs:line 101
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItems(IDownloadClient downloadClient, DownloadClientItem downloadItem) in D:\a\1\s\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 136

[List steps to reproduce the error and details on what happens and what you expected to happen]
1. Add the above album to your download list, let it auto search/download
2. Downlopad completes, The file gets saved on Windows filesystem without invalid characters <> 
311 - Universal Pulse (2011) _320kbs_
3. Check  System > Events, you will see the above error Couldn't process tracked download xxxx is not a valid Windows path.

**Comment by garfield69** [comment]
the download filenames are specific to the indexer that produces them.
please specify the indexer(s) you are using that generate this issue so we can add the parse-title-to-filename filter.

**Comment by joshhazel** [comment]
> the download filenames are specific to the indexer that produces them.
> please specify the indexer(s) you are using that generate this issue so we can add the parse-title-to-filename filter.

Using Torznaab > Jacket to search indexers: 
1337x
isohunt2, 
kickasstorrents.to, 
limetorrents, 
torrentparadise

Is there a log to tell me which indexer it actually took the file from ?

**Comment by garfield69** [comment]
>Is there a log to tell me which indexer it actually took the file from ?

If the app you are using does not tell you which Jackett indexer it used to download a torrent I would be very surprised.

What torznab app are you using?

Have you defined each Jackett indexer individually in your torznab app (recommended), or are you (Gasp! Horror! Cringe!) using the Jackett aggregate indexer **ALL** with your app?
If you are using the aggregate indexer, then if the regular Jackett log does not show the download, you may need to turn on the **Enhanced** logging via the Jackett dashboard. Tick the **Enhanced logging** checkbox, and click on the **Apply Server Settings** button.

This enables debug and HTML logging, and should include the download request in most cases.
Be aware that if you restart the Jackett service the _enhanced logging_ is turned off.

**Comment by joshhazel** [comment]
I will turn on the enhanced logging for both apps and if it occurs repost the issue, wont keep this open if i dont have good logs for you.
