### ISSUE TITLE
puntorrent / puntotorrent: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10276]
Empty search
```
CardigannIndexer (puntorrent): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=142">
			<img src="https://xbt.puntotorrent.com/style/xbtit_default/images/categories/2020_EBOOKS_Audiolibros.png" border="0" alt="Audiolibros">
		</a>
	</td>
	<td class="lista" valign="middle" style="padding-left:10px;overflow:auto;">
		<a class="enlace" id="195" href="javascript:void();">César Mallorquí - (El coleccionista de sellos)[voz humana](mp3)
		</a><div id="detalles195" class="detalles"></div>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="https://foros.puntotorrent.com/index.php?topic=166194.0" target="_blank">Foro</a>
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=7f0099a6db14d580cefb4b719b69ee2a150576a4&amp;f=C%C3%A9sar+Mallorqu%C3%AD+-+%28El+coleccionista+de+sellos%29%5Bvoz+humana%5D%28mp3%29.torrent">
			<img src="images/download.gif" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">13/11/2020</td>
	<td align="center" width="80" class="lista" style="white-space:wrap; text-align:center;">755,62 MB</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">
		<a href="index.php?page=userdetails&amp;id=918">
			<span style="color:#54D0FF">alfagumar</span>
		</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=7f0099a6db14d580cefb4b719b69ee2a150576a4" title="Click aqui para ver los detalles de los peers">13</a>
	</td>
	<td align="center" width="30" class="#FF0000" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=7f0099a6db14d580cefb4b719b69ee2a150576a4" title="Click aqui para ver los detalles de los peers">0</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=7f0099a6db14d580cefb4b719b69ee2a150576a4" title="History - César Mallorquí - (El coleccionista de sellos)[voz humana](mp3)">35</a>
	</td>
	
	<!-- <td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].average /></td> -->                      
	<!--<td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].agradecer /></td> -->
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=142: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531

CardigannIndexer (puntorrent): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=142">
			<img src="https://xbt.puntotorrent.com/style/xbtit_default/images/categories/2020_EBOOKS_Audiolibros.png" border="0" alt="Audiolibros">
		</a>
	</td>
	<td class="lista" valign="middle" style="padding-left:10px;overflow:auto;">
		<a class="enlace" id="180" href="javascript:void();">Nora Roberts - (El coleccionista)[voz humana](mp3)
		</a><div id="detalles180" class="detalles"></div>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="https://foros.puntotorrent.com/index.php?topic=166230.0" target="_blank">Foro</a>
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=61e01c9798b23442a8b3ef1355b99766e60da146&amp;f=Nora+Roberts+-+%28El+coleccionista%29%5Bvoz+humana%5D%28mp3%29.torrent">
			<img src="images/download.gif" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">14/11/2020</td>
	<td align="center" width="80" class="lista" style="white-space:wrap; text-align:center;">441,16 MB</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">
		<a href="index.php?page=userdetails&amp;id=918">
			<span style="color:#54D0FF">alfagumar</span>
		</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=61e01c9798b23442a8b3ef1355b99766e60da146" title="Click aqui para ver los detalles de los peers">9</a>
	</td>
	<td align="center" width="30" class="#FF0000" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=61e01c9798b23442a8b3ef1355b99766e60da146" title="Click aqui para ver los detalles de los peers">0</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=61e01c9798b23442a8b3ef1355b99766e60da146" title="History - Nora Roberts - (El coleccionista)[voz humana](mp3)">22</a>
	</td>
	
	<!-- <td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].average /></td> -->                      
	<!--<td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].agradecer /></td> -->
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=142: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531

CardigannIndexer (puntorrent): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=142">
			<img src="https://xbt.puntotorrent.com/style/xbtit_default/images/categories/2020_EBOOKS_Audiolibros.png" border="0" alt="Audiolibros">
		</a>
	</td>
	<td class="lista" valign="middle" style="padding-left:10px;overflow:auto;">
		<a class="enlace" id="101" href="javascript:void();">César Pérez Gellida - (Sarna con gusto)[voz humana](mp3)
		</a><div id="detalles101" class="detalles">NUEVO</div>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="https://foros.puntotorrent.com/index.php?topic=166289.0" target="_blank">Foro</a>
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=7049be75fbb27f08daf4339f82b950b3ae0b227d&amp;f=C%C3%A9sar+P%C3%A9rez+Gellida+-+%28Sarna+con+gusto%29%5Bvoz+humana%5D%28mp3%29.torrent">
			<img src="images/download.gif" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">18/11/2020</td>
	<td align="center" width="80" class="lista" style="white-space:wrap; text-align:center;">334,64 MB</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">
		<a href="index.php?page=userdetails&amp;id=918">
			<span style="color:#54D0FF">alfagumar</span>
		</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=7049be75fbb27f08daf4339f82b950b3ae0b227d" title="Click aqui para ver los detalles de los peers">14</a>
	</td>
	<td align="center" width="30" class="#FF0000" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=7049be75fbb27f08daf4339f82b950b3ae0b227d" title="Click aqui para ver los detalles de los peers">0</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=7049be75fbb27f08daf4339f82b950b3ae0b227d" title="History - César Pérez Gellida - (Sarna con gusto)[voz humana](mp3)">22</a>
	</td>
	
	<!-- <td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].average /></td> -->                      
	<!--<td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].agradecer /></td> -->
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=142: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531

CardigannIndexer (puntorrent): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=142">
			<img src="https://xbt.puntotorrent.com/style/xbtit_default/images/categories/2020_EBOOKS_Audiolibros.png" border="0" alt="Audiolibros">
		</a>
	</td>
	<td class="lista" valign="middle" style="padding-left:10px;overflow:auto;">
		<a class="enlace" id="100" href="javascript:void();">Fernando Aramburu - (Autorretrato sin mí)[voz humana](mp3)
		</a><div id="detalles100" class="detalles">NUEVO</div>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="https://foros.puntotorrent.com/index.php?topic=166317.0" target="_blank">Foro</a>
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=ed4ceb8ef922e18ad9cca03e7b87861458cd4c47&amp;f=Fernando+Aramburu+-+%28Autorretrato+sin+m%C3%AD%29%5Bvoz+humana%5D%28mp3%29.torrent">
			<img src="images/download.gif" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">18/11/2020</td>
	<td align="center" width="80" class="lista" style="white-space:wrap; text-align:center;">74,74 MB</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">
		<a href="index.php?page=userdetails&amp;id=918">
			<span style="color:#54D0FF">alfagumar</span>
		</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=ed4ceb8ef922e18ad9cca03e7b87861458cd4c47" title="Click aqui para ver los detalles de los peers">14</a>
	</td>
	<td align="center" width="30" class="#FF0000" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=ed4ceb8ef922e18ad9cca03e7b87861458cd4c47" title="Click aqui para ver los detalles de los peers">0</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=ed4ceb8ef922e18ad9cca03e7b87861458cd4c47" title="History - Fernando Aramburu - (Autorretrato sin mí)[voz humana](mp3)">22</a>
	</td>
	
	<!-- <td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].average /></td> -->                      
	<!--<td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].agradecer /></td> -->
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=142: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531

CardigannIndexer (puntorrent): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=142">
			<img src="https://xbt.puntotorrent.com/style/xbtit_default/images/categories/2020_EBOOKS_Audiolibros.png" border="0" alt="Audiolibros">
		</a>
	</td>
	<td class="lista" valign="middle" style="padding-left:10px;overflow:auto;">
		<a class="enlace" id="93" href="javascript:void();">César Pérez Gellida - (Memento mori)[voz humana](mp3)
		</a><div id="detalles93" class="detalles">NUEVO</div>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="https://foros.puntotorrent.com/index.php?topic=147320.0" target="_blank">Foro</a>
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=0b620e27974081e8d327f8a44fa98a96e2267a60&amp;f=C%C3%A9sar+P%C3%A9rez+Gellida+-+%28Memento+mori%29%5Bvoz+humana%5D%28mp3%29.torrent">
			<img src="images/download.gif" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">19/11/2020</td>
	<td align="center" width="80" class="lista" style="white-space:wrap; text-align:center;">392,07 MB</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">
		<a href="index.php?page=userdetails&amp;id=918">
			<span style="color:#54D0FF">alfagumar</span>
		</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=0b620e27974081e8d327f8a44fa98a96e2267a60" title="Click aqui para ver los detalles de los peers">13</a>
	</td>
	<td align="center" width="30" class="#FF0000" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=0b620e27974081e8d327f8a44fa98a96e2267a60" title="Click aqui para ver los detalles de los peers">0</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=0b620e27974081e8d327f8a44fa98a96e2267a60" title="History - César Pérez Gellida - (Memento mori)[voz humana](mp3)">27</a>
	</td>
	
	<!-- <td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].average /></td> -->                      
	<!--<td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].agradecer /></td> -->
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=142: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531

CardigannIndexer (puntorrent): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=142">
			<img src="https://xbt.puntotorrent.com/style/xbtit_default/images/categories/2020_EBOOKS_Audiolibros.png" border="0" alt="Audiolibros">
		</a>
	</td>
	<td class="lista" valign="middle" style="padding-left:10px;overflow:auto;">
		<a class="enlace" id="73" href="javascript:void();">Mario Alonso Puig - Ahora yo [voz humana](mp3)
		</a><div id="detalles73" class="detalles">NUEVO</div>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="https://foros.puntotorrent.com/index.php?topic=166344.0" target="_blank">Foro</a>
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=6d90fea161a213b4abbc2b58233395de0c9eaf50&amp;f=Mario+Alonso+Puig+-+Ahora+yo+%5Bvoz+humana%5D%28mp3%29.torrent">
			<img src="images/download.gif" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">20/11/2020</td>
	<td align="center" width="80" class="lista" style="white-space:wrap; text-align:center;">182,41 MB</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">
		<a href="index.php?page=userdetails&amp;id=918">
			<span style="color:#54D0FF">alfagumar</span>
		</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=6d90fea161a213b4abbc2b58233395de0c9eaf50" title="Click aqui para ver los detalles de los peers">9</a>
	</td>
	<td align="center" width="30" class="#FF0000" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=6d90fea161a213b4abbc2b58233395de0c9eaf50" title="Click aqui para ver los detalles de los peers">0</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=6d90fea161a213b4abbc2b58233395de0c9eaf50" title="History - Mario Alonso Puig - Ahora yo [voz humana](mp3)">26</a>
	</td>
	
	<!-- <td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].average /></td> -->                      
	<!--<td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].agradecer /></td> -->
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=142: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531

CardigannIndexer (puntorrent): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=142">
			<img src="https://xbt.puntotorrent.com/style/xbtit_default/images/categories/2020_EBOOKS_Audiolibros.png" border="0" alt="Audiolibros">
		</a>
	</td>
	<td class="lista" valign="middle" style="padding-left:10px;overflow:auto;">
		<a class="enlace" id="35" href="javascript:void();">César Pérez Gellida - A grandes males [voz humana](mp3)
		</a><div id="detalles35" class="detalles">NUEVO</div>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="https://foros.puntotorrent.com/index.php?topic=147473.0" target="_blank">Foro</a>
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=73427db2ab9a5d011696a4f701b35477f24e46be&amp;f=C%C3%A9sar+P%C3%A9rez+Gellida+-+A+grandes+males+%5Bvoz+humana%5D%28mp3%29.torrent">
			<img src="images/download.gif" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">21/11/2020</td>
	<td align="center" width="80" class="lista" style="white-space:wrap; text-align:center;">421,06 MB</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">
		<a href="index.php?page=userdetails&amp;id=918">
			<span style="color:#54D0FF">alfagumar</span>
		</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=73427db2ab9a5d011696a4f701b35477f24e46be" title="Click aqui para ver los detalles de los peers">5</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=73427db2ab9a5d011696a4f701b35477f24e46be" title="Click aqui para ver los detalles de los peers">2</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=73427db2ab9a5d011696a4f701b35477f24e46be" title="History - César Pérez Gellida - A grandes males [voz humana](mp3)">8</a>
	</td>
	
	<!-- <td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].average /></td> -->                      
	<!--<td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].agradecer /></td> -->
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=142: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531

CardigannIndexer (puntorrent): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=142">
			<img src="https://xbt.puntotorrent.com/style/xbtit_default/images/categories/2020_EBOOKS_Audiolibros.png" border="0" alt="Audiolibros">
		</a>
	</td>
	<td class="lista" valign="middle" style="padding-left:10px;overflow:auto;">
		<a class="enlace" id="3" href="javascript:void();">Toti Martínez de Lezea - Muerte en el Priorato [voz humana](mp3)
		</a><div id="detalles3" class="detalles">NUEVO</div>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="https://foros.puntotorrent.com/index.php?topic=166400.0" target="_blank">Foro</a>
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=d20028b73533fe018a47908c2502955d0daff41b&amp;f=Toti+Mart%C3%ADnez+de+Lezea+-+Muerte+en+el+Priorato+%5Bvoz+humana%5D%28mp3%29.torrent">
			<img src="images/download.gif" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">22/11/2020</td>
	<td align="center" width="80" class="lista" style="white-space:wrap; text-align:center;">242,51 MB</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">
		<a href="index.php?page=userdetails&amp;id=918">
			<span style="color:#54D0FF">alfagumar</span>
		</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=d20028b73533fe018a47908c2502955d0daff41b" title="Click aqui para ver los detalles de los peers">6</a>
	</td>
	<td align="center" width="30" class="#FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=d20028b73533fe018a47908c2502955d0daff41b" title="Click aqui para ver los detalles de los peers">1</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=d20028b73533fe018a47908c2502955d0daff41b" title="History - Toti Martínez de Lezea - Muerte en el Priorato [voz humana](mp3)">5</a>
	</td>
	
	<!-- <td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].average /></td> -->                      
	<!--<td align="center" width="45" class="lista" style="text-align: center;"><tag:torrents[].agradecer /></td> -->
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=142: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531
```

**Comment by garfield69** [comment]
puntotorrent registration is closed and I don't have an account for this one.
if you provide a dump of the torrent search page I can add the new cats, or you could do it yourself ;-)
