### ISSUE TITLE
linuxtracker: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10274]
Empty search
```
CardigannIndexer (linuxtracker): Error while parsing row '
<tr>
	<td width="125" class="lista" align="center">
		<center>
			<a href="index.php?page=torrents&amp;category=316">Livecd</a>
		</center>
		<p>
			<a href="/torrentimg/s1b65f5a1109d652221c71e0d086d182da665be006.jpg" title="view image" rel="lightbox">
				<img src="thumbnail.php?size=150&amp;path=torrentimg/s1b65f5a1109d652221c71e0d086d182da665be006.jpg">
			</a>
			<br>
			<a href="index.php?page=torrent-details&amp;id=b65f5a1109d652221c71e0d086d182da665be006">
				<img src="/images/more_details_icon.png">
			</a>
		</p>
	</td>
	<td class="lista">
		<font size="4">
			<strong>
				<a href="index.php?page=torrent-details&amp;id=b65f5a1109d652221c71e0d086d182da665be006" title="View details: Catbird Linux 1.0.0">Catbird Linux 1 0 0</a>
			</strong>
		</font>
		<br>
		[b]Catbird Linux 1.0.0[/b]   [i]Turn on, tune in, observe, measure, and understand.[/i]      catbirdlinux-1.0.0.iso (Release Date 11/15/2020):   sha256sum: 279f85173a39453a2543d9bbd908a58c12893f9650eb012e1e1a40a4fcaecfad    Welcome to Catbird Linux, an operating system built for people who use automation to retrieve and analyze data from websites and online databases. It centers on Python and Go, with numerous packages for web scraping or downloading data via API calls. Using Catbird Linu<br>
		<hr>
		<table width="100%">
			<tbody>
				<tr>
					<td>
						<strong>Added On:</strong>
						16/11/2020</td>
					<td>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Size:</strong>
						3.11 GB
					</td>
					<td></td>
				</tr>
				<tr>
					<td>
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;order=5&amp;by=2">Seeds</a>
						</strong>
						<a href="index.php?page=peers&amp;id=b65f5a1109d652221c71e0d086d182da665be006" title="Click here to view peers details">5</a>
					</td>
					<td></td>
				</tr>
				<tr>
					<td>
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;order=6&amp;by=2">Leechers</a>
						</strong>
						<a href="index.php?page=peers&amp;id=b65f5a1109d652221c71e0d086d182da665be006" title="Click here to view peers details">0</a>
					</td>
					<td></td>
				</tr>
				<tr>
					<td width="90%">
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;order=7&amp;by=1">Completed</a>
						</strong>
						<a href="index.php?page=torrent_history&amp;id=b65f5a1109d652221c71e0d086d182da665be006" title="History - Catbird Linux 1.0.0">10</a>
					</td>
					<td align="right">
						<a href="magnet:?xt=urn:btih:WZPVUEIJ2ZJCEHDR4DIINUMC3JTFXYAG">
							<img src="images/azureus.gif" border="0" alt="Magnet Link">
						</a>
						<a href="index.php?page=downloadcheck&amp;id=b65f5a1109d652221c71e0d086d182da665be006">
							<img src="images/download.gif" border="0" alt="torrent">
						</a>
					</td>
				</tr>
			</tbody>
		</table>
		<hr>
		<table width="100%">
			<tbody>
				<tr>
					<td>
						---</td>
					<td>
						<a href="index.php?page=userdetails&amp;id=12200">
							<span style="color:green">powderfinger</span>
						</a>
					</td>
					<td>
						N/A
					</td>
					<td>
						100%<br>
						<img src="images/health/health_10.gif">
					</td>
					<td align="center" width="20" class="lista" style="text-align: center;">---</td>
					<td>
						<tag:torrents[].recommended></tag:torrents[].recommended>
					</td>
					<td>
						<strong>
						</strong>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="index.php?page=torrents&category="], value=316: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531
```

**Comment by ngosang** [comment]
"query": "up"
```
CardigannIndexer (linuxtracker): Error while parsing row '
<tr>
	<td width="125" class="lista" align="center">
		<center>
			<a href="index.php?page=torrents&amp;category=531"></a>
		</center>
		<p>
			<a href="/torrentimg/s134a256ec86bee876434cdf375e7591bf8d23d464.png" title="view image" rel="lightbox">
				<img src="thumbnail.php?size=150&amp;path=torrentimg/s134a256ec86bee876434cdf375e7591bf8d23d464.png">
			</a>
			<br>
			<a href="index.php?page=torrent-details&amp;id=34a256ec86bee876434cdf375e7591bf8d23d464">
				<img src="/images/more_details_icon.png">
			</a>
		</p>
	</td>
	<td class="lista">
		<font size="4">
			<strong>
				<a href="index.php?page=torrent-details&amp;id=34a256ec86bee876434cdf375e7591bf8d23d464" title="View details: supergrub1_09799_complete">supergrub1 09799 complete</a>
			</strong>
		</font>
		<br>
		[b]Short explanation[/b]  Super Grub Disk is outdated.  Please use one of the following tools:  Rescatux ( http://www.supergrubdisk.org/rescatux/ ) . Tool for fixing Grub. Super Grub2 Disk ( http://www.supergrubdisk.org/super-grub2-disk/ ) . Tool for booting into your system.  [b]Long explanation[/b]  Super Grub Disk was outdated on July 21, 2011. People still are downloading it because either they don't know that Super Grub2 Disk is there (just using old links) or because it is stil<br>
		<hr>
		<table width="100%">
			<tbody>
				<tr>
					<td>
						<strong>Added On:</strong>
						14/02/2014</td>
					<td>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Size:</strong>
						23.38 MB
					</td>
					<td></td>
				</tr>
				<tr>
					<td>
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;search=up&amp;&amp;order=5&amp;by=2">Seeds</a>
						</strong>
						<a href="index.php?page=peers&amp;id=34a256ec86bee876434cdf375e7591bf8d23d464" title="Click here to view peers details">4</a>
					</td>
					<td></td>
				</tr>
				<tr>
					<td>
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;search=up&amp;&amp;order=6&amp;by=2">Leechers</a>
						</strong>
						<a href="index.php?page=peers&amp;id=34a256ec86bee876434cdf375e7591bf8d23d464" title="Click here to view peers details">1</a>
					</td>
					<td></td>
				</tr>
				<tr>
					<td width="90%">
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;search=up&amp;&amp;order=7&amp;by=1">Completed</a>
						</strong>
						<a href="index.php?page=torrent_history&amp;id=34a256ec86bee876434cdf375e7591bf8d23d464" title="History - supergrub1_09799_complete">2820</a>
					</td>
					<td align="right">
						<a href="magnet:?xt=urn:btih:GSRFN3EGX3UHMQ2M343V45MRX6GSHVDE">
							<img src="images/azureus.gif" border="0" alt="Magnet Link">
						</a>
						<a href="index.php?page=downloadcheck&amp;id=34a256ec86bee876434cdf375e7591bf8d23d464">
							<img src="images/download.gif" border="0" alt="torrent">
						</a>
					</td>
				</tr>
			</tbody>
		</table>
		<hr>
		<table width="100%">
			<tbody>
				<tr>
					<td>
						---</td>
					<td>
						<a href="index.php?page=userdetails&amp;id=1222">
							<span style="color:green">adrian15</span>
						</a>
					</td>
					<td>
						N/A
					</td>
					<td>
						100%<br>
						<img src="images/health/health_10.gif">
					</td>
					<td align="center" width="20" class="lista" style="text-align: center;">---</td>
					<td>
						<tag:torrents[].recommended></tag:torrents[].recommended>
					</td>
					<td>
						<strong>
						</strong>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="index.php?page=torrents&category="], value=531: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531

CardigannIndexer (linuxtracker): Error while parsing row '
<tr>
	<td width="125" class="lista" align="center">
		<center>
			<a href="index.php?page=torrents&amp;category=531"></a>
		</center>
		<p>
			<a href="/torrentimg/s1cfe0039beab844210dc4bf8fae764ae8576bfc37.png" title="view image" rel="lightbox">
				<img src="thumbnail.php?size=150&amp;path=torrentimg/s1cfe0039beab844210dc4bf8fae764ae8576bfc37.png">
			</a>
			<br>
			<a href="index.php?page=torrent-details&amp;id=cfe0039beab844210dc4bf8fae764ae8576bfc37">
				<img src="/images/more_details_icon.png">
			</a>
		</p>
	</td>
	<td class="lista">
		<font size="4">
			<strong>
				<a href="index.php?page=torrent-details&amp;id=cfe0039beab844210dc4bf8fae764ae8576bfc37" title="View details: Super Grub2 Disk 2.00s2">Super Grub2 Disk 2 00s2</a>
			</strong>
		</font>
		<br>
		May 17th, 2014  This is: Super Grub2 Disk 2.00s2 stable, an special edition for Torrent users that as always are able to download it before than anyone else.  This is newest the stable release. The former Super Grub2 Disk stable release was 1.98s1 version and released on October 2010.  Check: http://www.supergrubdisk.org/super-grub2-disk/ for videos, tutorials, howtos and more information.  Super GRUB2 Disk helps you to boot into most any Operating System (OS) even if you cannot boot int<br>
		<hr>
		<table width="100%">
			<tbody>
				<tr>
					<td>
						<strong>Added On:</strong>
						17/05/2014</td>
					<td>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Size:</strong>
						65.09 MB
					</td>
					<td></td>
				</tr>
				<tr>
					<td>
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;search=up&amp;&amp;order=5&amp;by=2">Seeds</a>
						</strong>
						<a href="index.php?page=peers&amp;id=cfe0039beab844210dc4bf8fae764ae8576bfc37" title="Click here to view peers details">1</a>
					</td>
					<td></td>
				</tr>
				<tr>
					<td>
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;search=up&amp;&amp;order=6&amp;by=2">Leechers</a>
						</strong>
						<a href="index.php?page=peers&amp;id=cfe0039beab844210dc4bf8fae764ae8576bfc37" title="Click here to view peers details">0</a>
					</td>
					<td></td>
				</tr>
				<tr>
					<td width="90%">
						<strong>
							<a href="/index.php?page=torrents&amp;active=1&amp;search=up&amp;&amp;order=7&amp;by=1">Completed</a>
						</strong>
						<a href="index.php?page=torrent_history&amp;id=cfe0039beab844210dc4bf8fae764ae8576bfc37" title="History - Super Grub2 Disk 2.00s2">1134</a>
					</td>
					<td align="right">
						<a href="magnet:?xt=urn:btih:Z7QAHG7KXBCCCDOEX6H245SK5BLWX7BX">
							<img src="images/azureus.gif" border="0" alt="Magnet Link">
						</a>
						<a href="index.php?page=downloadcheck&amp;id=cfe0039beab844210dc4bf8fae764ae8576bfc37">
							<img src="images/download.gif" border="0" alt="torrent">
						</a>
					</td>
				</tr>
			</tbody>
		</table>
		<hr>
		<table width="100%">
			<tbody>
				<tr>
					<td>
						---</td>
					<td>
						<a href="index.php?page=userdetails&amp;id=1222">
							<span style="color:green">adrian15</span>
						</a>
					</td>
					<td>
						N/A
					</td>
					<td>
						100%<br>
						<img src="images/health/health_10.gif">
					</td>
					<td align="center" width="20" class="lista" style="text-align: center;">---</td>
					<td>
						<tag:torrents[].recommended></tag:torrents[].recommended>
					</td>
					<td>
						<strong>
						</strong>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="index.php?page=torrents&category="], value=531: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531
```
