### ISSUE TITLE
[Beyond-HD-OneURL] Search Failure - Index out of range

### ISSUE THREAD

**Issue by Ayfteyd7Od** [Jackett/Jackett#10288]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
LSIO Docker

**Jackett Version**:
 Jackett Version 0.16.2229.0 

**Last Working Jackett Version**:
Unknown

**Are you using a proxy or VPN?** [yes/no]
no

### Description

Search using Beyond-HD OneURL. Failure with Error.

### Logged Error Messages

```
11-23 22:12:34 Error Jackett.Common.IndexerException: Exception (beyond-hd-oneurl): Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
 ---> System.Exception: Parse error
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1333
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 686
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1629
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 394
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 394
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 663
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 223 Jackett.Common.IndexerException: Exception (beyond-hd-oneurl): Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
 ---> System.Exception: Parse error
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1333
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 686
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1629
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 394
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 394
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 663
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 223
11-23 22:12:34 Info Manual search for "his dark materials" on beyond-hd-oneurl with 0 results. 
```

### Screenshots

N/A

**Comment by garfield69** [comment]
Please provide a **full enhanced** log so we can see the debug and HTML that precedes the error.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by Ayfteyd7Od** [comment]
[jackett.log](https://github.com/Jackett/Jackett/files/5590747/jackett.log)

**Comment by garfield69** [comment]
There has been some changes to the beyond-hd search results page.
I've made what I think are the correct indexer alterations, but without an active account I cannot interactively test my changes.
So try out Jackett after the new release is published in about 11 hours or so (I'll post the version once it's published) and let me know if I got it right.

**Comment by garfield69** [comment]
Please try out jackett 0.16.2236 and report. Thanks.

**Comment by Ayfteyd7Od** [comment]
Working great. You can mark it as resolved. Thanks!
