### ISSUE TITLE
[dmhy] Exception (dmhy): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

### ISSUE THREAD

**Issue by hdlineage** [Jackett/Jackett#10302]
### Description

Simply add the indexer and run the test will give you the error

### Logged Error Messages

Exception (dmhy): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
11-26 09:37:54 Info Found 90 releases from EZTV
11-26 09:37:57 Error Jackett.Common.IndexerException: Exception (dmhy): Clearance failed after 10 attempt(s).

---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).

**Comment by ilike2burnthing** [comment]
The site is using Cloudflare DDoS protection, which Jackett can't currently bypass. There is an experimental method to use such indexers if you want to try it - https://github.com/Jackett/Jackett/issues/9029
