### ISSUE TITLE
MagnetDL disappeared?

### ISSUE THREAD

**Issue by yiveynod** [Jackett/Jackett#10354]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: macOS Catalina 10.15.7

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Version 0.16.2291.0

**Last Working Jackett Version**: Version 0.16.2291.0

**Are you using a proxy or VPN?** Yes (VPN)

### Description
MagnetDL stopped working in Sonarr/Radarr and when I checked in Jackett it had disappeared from my list and can't be found in the "add indexer" drop down either. The website is still working and active so what happened? 

### Logged Error Messages

[System.Exception: Unknown indexer: magnetdl
   at Jackett.Common.Services.IndexerManagerService.GetIndexer(String name) in /Users/runner/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 256
   at Jackett.Server.Controllers.RequiresConfiguredIndexer.OnActionExecuting(ActionExecutingContext context) in /Users/runner/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 58
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61]

### Screenshots

<img width="894" alt="Skärmavbild 2020-12-03 kl  14 55 46" src="https://user-images.githubusercontent.com/60571329/101026811-a5902600-3577-11eb-9055-ddfabf20ed37.png">

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/pull/10347
