### ISSUE TITLE
[speedcd] Exception of type 'System.Exception' was thrown. (Config)

### ISSUE THREAD

**Issue by wazerstar** [Jackett/Jackett#10397]
OS: Microsoft Windows NT 6.2.9200.0 (64bit OS)
[edit] one of Windows 8 , 8 pro, 8 ent, or Windows Server 2012 https://en.wikipedia.org/wiki/Windows_NT#Releases

.Net Runtime: [.Net-Core/.Net-Framework/Mono]
N/A
.Net Version:
N/A
Jackett Version:
0.16.2299.0

Last Working Jackett Version:
N/A

Are you using a proxy or VPN? [yes/no]
No

[List steps to reproduce the error and details on what happens and what you expected to happen]

Simple try to add account, and this will show up right away.

An error occurred while updating this indexer
Exception of type 'System.Exception' was thrown.

[Place any relevant error messages you noticed from the logs here.]
```
System.Exception: Exception of type 'System.Exception' was thrown.
   at Jackett.Common.Indexers.SpeedCD.<>c__DisplayClass14_0.<DoLogin>b__0() in D:\a\1\s\src\Jackett.Common\Indexers\SpeedCD.cs:line 140
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 260
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\SpeedCD.cs:line 133
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\SpeedCD.cs:line 109
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

**Comment by wazerstar** [comment]
OS: Microsoft Windows NT 6.2.9200.0 (64bit OS)

.Net Runtime: [.Net-Core/.Net-Framework/Mono]
N/A
.Net Version:
N/A
Jackett Version:
0.16.2299.0

Last Working Jackett Version:
N/A

Are you using a proxy or VPN? [yes/no]
No

[List steps to reproduce the error and details on what happens and what you expected to happen]

Simple try to add account, and this will show up right away.

An error occurred while updating this indexer
Exception of type 'System.Exception' was thrown.





[Place any relevant error messages you noticed from the logs here.]
System.Exception: Exception of type 'System.Exception' was thrown.
   at Jackett.Common.Indexers.SpeedCD.<>c__DisplayClass14_0.<DoLogin>b__0() in D:\a\1\s\src\Jackett.Common\Indexers\SpeedCD.cs:line 140
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 260
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\SpeedCD.cs:line 133
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\SpeedCD.cs:line 109
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

**Comment by garfield69** [comment]
The indexer works for me, so the issue would appear to be at your end.
Please provide a full **enhanced** log with the debug and HTML included and maybe we can figure out what is going on.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by wazerstar** [comment]
@garfield69 i hope this is enough

[log.txt](https://github.com/Jackett/Jackett/files/5648281/log.txt)

**Comment by garfield69** [comment]
The log shows that you are failing the login with incorrect credentials.
Did you change your password recently?

Access the web site directly with a browser running on the same machine as Jackett, and confirm your credentials.
Then log out to ensure the web site credentials cache is reset.
As an overkill belt and braces, shutdown your Jackett service and start it up again.
Then access your Jackett dashboard and edit your speedcd config and re-enter your credentials afresh.
Does that help?

**Comment by wazerstar** [comment]
@garfield69 I just did a 100% clean installation and added all sites again, speed.cd still fails, i cleared all cookies and data related, changed password, and still no success :(

**Comment by garfield69** [comment]
So you used a browser to login to the web site manually, and you did not have any problems logging in?
Then edited the Jackett config and used the same username and password, and you get the error?
Beyond my skills to diagnose, the indexer is written in C#.

@ngosang  can you take a look at this ticket please?

**Comment by wazerstar** [comment]
@garfield69 @ngosang I figured it out, apparently their site is broken when you use firefox.

I tried removing geoblocking/whitelist IP with firefox browser, it would say wrong password on their site, however I was fine able to change password.....

So my default browser is firefox.


I now did a test with geoblocking/whitelist ip on chrome and it said succesfull.

I tested jackett in chrome and I could now add speed.cd/speed.click :)

So their site is broken with firefox, maybe there needs to be added another user-agent or something to force it to chrome?

Can you test with firefox and confirm?

Just try use jackett with firefox and try to add speed.cd/speed.click

**Comment by garfield69** [comment]
yes, I cannot use the latest firefox to login to speed.cd, I get the `Incorrect username or Password. Please try again.` error.
