### ISSUE TITLE
[cinemamovies] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by dolohow** [Jackett/Jackett#10402]
### Environment

**OS**: hotio Docker on Linux

**Jackett Version**: 0.16.2299.0

**Are you using a proxy or VPN?** no

### Description

Can't add cinemamovies indexer using cookie method

### Logged Error Messages
```
2020-12-06 13:14:16   Debug
Connection id "0HM4OVVF2H96B" sending FIN because: "The Socket transport's send loop completed gracefully."

2020-12-06 13:14:16   Debug
Connection id "0HM4OVVF2H96B" stopped.

2020-12-06 13:14:16   Debug
Connection id "0HM4OVVF2H96B" disconnecting.

2020-12-06 13:14:16   Info
Request finished in 237.8724ms 500 application/json

2020-12-06 13:14:16   Debug
The response will be compressed with 'gzip'.

2020-12-06 13:14:16   Error
Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 767
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 919
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

2020-12-06 13:14:16   Info
Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'

2020-12-06 13:14:16   Info
Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 234.8535ms

2020-12-06 13:14:16   Debug
WebClient(HttpWebClient2): Returning Redirect => https://cinemamovies.pl/login.php?returnto=%2Findex.php 0 bytes

2020-12-06 13:14:16   Debug
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://cinemamovies.pl/index.php)

2020-12-06 13:14:16   Debug
CardigannIndexer (cinemamovies): Cookies after login: uid=12257; pass=06b3f17e2f541267e61befc0d15401d3; hashv=df648397af6f728c6ec8f952c628fbdb

2020-12-06 13:14:16   Debug
Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.

2020-12-06 13:14:16   Debug
Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...

2020-12-06 13:14:16   Debug
Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.

2020-12-06 13:14:16   Debug
Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.

2020-12-06 13:14:16   Debug
Connection id "0HM4OVVF2H96B", Request id "0HM4OVVF2H96B:00000001": done reading request body.

2020-12-06 13:14:16   Debug
Connection id "0HM4OVVF2H96B", Request id "0HM4OVVF2H96B:00000001": started reading request body.

2020-12-06 13:14:16   Debug
Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'.

2020-12-06 13:14:16   Debug
Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'.

2020-12-06 13:14:16   Debug
Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ...

2020-12-06 13:14:16   Debug
Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...

2020-12-06 13:14:16   Debug
Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)

2020-12-06 13:14:16   Debug
Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)

2020-12-06 13:14:16   Info
Authorization was successful.

2020-12-06 13:14:16   Debug
Execution plan of result filters (in the following order): None

2020-12-06 13:14:16   Debug
Execution plan of exception filters (in the following order): None

2020-12-06 13:14:16   Debug
Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer

2020-12-06 13:14:16   Debug
Execution plan of resource filters (in the following order): None

2020-12-06 13:14:16   Debug
Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter

2020-12-06 13:14:16   Info
Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett).

2020-12-06 13:14:16   Info
Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'

2020-12-06 13:14:16   Debug
Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'

2020-12-06 13:14:16   Debug
Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/cinemamovies/config'

2020-12-06 13:14:16   Debug
1 candidate(s) found for the request path '/api/v2.0/indexers/cinemamovies/config'

2020-12-06 13:14:16   Debug
AuthenticationScheme: Cookies was successfully authenticated.

2020-12-06 13:14:16   Debug
POST requests are not supported

2020-12-06 13:14:16   Debug
Request is continuing in applying rules. Current url is http://[removed]/api/v2.0/indexers/cinemamovies/config

2020-12-06 13:14:16   Debug
Request is continuing in applying rules. Current url is http://[removed]/api/v2.0/indexers/cinemamovies/config

2020-12-06 13:14:16   Debug
Request is continuing in applying rules. Current url is http://[removed]/api/v2.0/indexers/cinemamovies/config

2020-12-06 13:14:16   Info
Request starting HTTP/1.0 POST http://[removed]/api/v2.0/indexers/cinemamovies/config application/json 440

2020-12-06 13:14:16   Debug
Connection id "0HM4OVVF2H96B" started.

2020-12-06 13:14:16   Debug
Connection id "0HM4OVVF2H96B" accepted.

2020-12-06 13:14:13   Debug
Connection id "0HM4OVVF2H96A" sending FIN because: "The Socket transport's send loop completed gracefully."

2020-12-06 13:14:13   Debug
Connection id "0HM4OVVF2H96A" stopped.

2020-12-06 13:14:13   Debug
Connection id "0HM4OVVF2H96A" disconnecting.

2020-12-06 13:14:13   Info
Request finished in 1.9055ms 200 application/json; charset=utf-8

2020-12-06 13:14:13   Info
Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'

2020-12-06 13:14:13   Info
Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 0.7503ms

2020-12-06 13:14:13   Debug
The response will be compressed with 'gzip'.

2020-12-06 13:14:13   Info
Executing ObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'.

2020-12-06 13:14:13   Debug
Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response.

2020-12-06 13:14:13   Debug
Attempting to select the first formatter in the output formatters list which can write the result.

2020-12-06 13:14:13   Debug
Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.

2020-12-06 13:14:13   Debug
No information found on request to perform content negotiation.

2020-12-06 13:14:13   Debug
List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter

2020-12-06 13:14:13   Debug
Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)

2020-12-06 13:14:13   Debug
Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)

2020-12-06 13:14:13   Info
Authorization was successful.

2020-12-06 13:14:13   Debug
Execution plan of result filters (in the following order): None

2020-12-06 13:14:13   Debug
Execution plan of exception filters (in the following order): None

2020-12-06 13:14:13   Debug

Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer

2020-12-06 13:14:13   Debug
Execution plan of resource filters (in the following order): None

2020-12-06 13:14:13   Debug
Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter

2020-12-06 13:14:13   Info
Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (jackett).

2020-12-06 13:14:13   Info
Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'

2020-12-06 13:14:13   Debug
Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'

2020-12-06 13:14:13   Debug
Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/cinemamovies/config'

2020-12-06 13:14:13   Debug
1 candidate(s) found for the request path '/api/v2.0/indexers/cinemamovies/config'

2020-12-06 13:14:13   Debug
AuthenticationScheme: Cookies was successfully authenticated.

2020-12-06 13:14:13   Debug
The request path /api/v2.0/indexers/cinemamovies/config does not match a supported file type

2020-12-06 13:14:13   Debug
Request is continuing in applying rules. Current url is http://[removed]/api/v2.0/indexers/cinemamovies/config?_=1607256399805

2020-12-06 13:14:13   Debug
Request is continuing in applying rules. Current url is http://[removed]/api/v2.0/indexers/cinemamovies/config?_=1607256399805

2020-12-06 13:14:13   Debug
Request is continuing in applying rules. Current url is http://[removed]/api/v2.0/indexers/cinemamovies/config?_=1607256399805

2020-12-06 13:14:13   Info
Request starting HTTP/1.0 GET http://[removed]/api/v2.0/indexers/cinemamovies/config?_=1607256399805

2020-12-06 13:14:13   Debug
Connection id "0HM4OVVF2H96A" started.

2020-12-06 13:14:13   Debug
Connection id "0HM4OVVF2H96A" accepted.
```

**Comment by garfield69** [comment]
The cookie method for cinemamovies works for me on my win10 so the issue is likely how you implemented your solution.
Using a Docker will complicate things.
Have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work and see if it helps you figure out what to do.

**Comment by dolohow** [comment]
Ok, perhaps cookie is IP locked, since I am not running it on same machine.  I need to confirm that.
