### ISSUE TITLE
[teamhd] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by jarmery** [Jackett/Jackett#10401]
I tried the steps listed in https://github.com/Jackett/Jackett/issues/6070#issuecomment-545607603 but I still get the same error.

### Environment

**OS**: unRAID 6.8.3

**Jackett Version**: binhex/arch-jackett (Version 0.16.2240.0)

**Are you using a proxy or VPN?** No

### Description

Installed Firefox VNC container
Followed steps listed here https://github.com/Jackett/Jackett/issues/6070#issuecomment-545607603
Entered cookie, Jackett reported Login Failed error

### Logged Error Messages

`2020-12-07 00:40:04,724 DEBG 'jackett' stdout output:
12-07 00:40:04 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.`

`at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /tmp/makepkg/jackett/src/Jackett-0.16.2240/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 767
at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /tmp/makepkg/jackett/src/Jackett-0.16.2240/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 917
at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /tmp/makepkg/jackett/src/Jackett-0.16.2240/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)`

`at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

`2020-12-07 00:40:04,728 DEBG 'jackett' stdout output:
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /tmp/makepkg/jackett/src/Jackett-0.16.2240/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.`

`at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /tmp/makepkg/jackett/src/Jackett-0.16.2240/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 767
at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /tmp/makepkg/jackett/src/Jackett-0.16.2240/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 917`

`2020-12-07 00:40:04,728 DEBG 'jackett' stdout output:
at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /tmp/makepkg/jackett/src/Jackett-0.16.2240/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)`

`at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /tmp/makepkg/jackett/src/Jackett-0.16.2240/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26`

**Comment by garfield69** [comment]
Spoofing the user-agent on my win10 is still working for me for the TeamHD indexer, so it is likely something about how you implemented your solution that is not quite right.
@Lonli-Lokli or @SuberSeb Can you try to help this user figure out the teamhd useragent spoofing on their unRAID 6.8.3 ?
Thanks.

**Comment by Lonli-Lokli** [comment]
@jarmery I believe you should use newer user agent value, see this issue for reference https://github.com/Jackett/Jackett/issues/7819#issuecomment-604076114

**Comment by jarmery** [comment]
> @jarmery I believe you should use newer user agent value, see this issue for reference [#7819 (comment)](https://github.com/Jackett/Jackett/issues/7819#issuecomment-604076114)

This worked, thank you for the quick response!

**Comment by tsenilov** [comment]
Did as mentioned in other post: log in the same ip, copy cookie, use user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
But since yesterday having this error.

I'm using docker linuxserver/jackett:latest

What is the current user-agent of Jackett?

Log of the error:

Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected. at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 766 at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 919 at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by SuberSeb** [comment]
I have same issue too

**Comment by Lonli-Lokli** [comment]
Obviously, new UserAgent has been introduced.
In future, copy value from there
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Utils/BrowserUtil.cs

Right now it's 
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

**Comment by tsenilov** [comment]
Thanks
That works.

Hope for user-agent settings in future releases.

**Comment by Lonli-Lokli** [comment]
@tsenilov you can subscribe to https://github.com/Jackett/Jackett/issues/7786
Once done, we will be able to setup static UserAgent.
