### ISSUE TITLE
Jackett and tixati

### ISSUE THREAD

**Issue by Shooshka** [Jackett/Jackett#10400]
### Environment

**OS**: Windows 10 20H2

**Jackett Version**: 0.16.2299.0

**Last Working Jackett Version**: 0.16.2299.0

**Are you using a proxy or VPN?** yes

### Description

Using tixati torrent client (2.77) all other rss feeds (not from jackett) works fine.
With jackett links I got these error:

```
 *** 06.12.2020 ***
[9:50:55]  created
[9:50:55]  started
[9:50:55]  starting update > http://127.0.0.1:9117/api/v2.0/indexers/kinozal/results/torznab/api?apikey=MyKey&t=search&cat=&q=MyQuery
[9:50:55]  update failed: server responded with code 505 > http://127.0.0.1:9117/api/v2.0/indexers/kinozal/results/torznab/api?apikey=MyKey&t=search&cat=&q=MyQuery
```

And working example:

```
[9:53:21]  starting update > http://newstudio.tv/rss.php
[9:53:21]  item filtered > Сестра (Сезон 1) / The Sister (2020) WEBDL 720p
...
[9:53:21]      20 items from server
[9:53:21]      20 items blocked by filter
[9:53:21]      0 items passed filter
[9:53:21]      0 items already in feed
[9:53:21]      0 items created
[9:53:21]  update complete > http://newstudio.tv/rss.php
```

### Logged Error Messages

No errors from jackett side in "View logs"

**Comment by garfield69** [comment]
tixati 2.77 with a Jackett RSS feed from the kinozal indexer works for me on my win10 home 20H2
![image](https://user-images.githubusercontent.com/6933240/101274834-2f552300-3806-11eb-99ed-4e7c176600a6.png)

so the issue appears to be at your end.
Possibly a problem with your vpn/proxy?
have you tried using the RSS link you loaded on tixati directly on your browser via the VPN/proxy, does that work there?

**Comment by Shooshka** [comment]
Hm.. really strange :| But I have problem only with Jackett's rss feeds.
My setup is: Localhost with tixati and Jackett (Jackett uses proxy in options to avoid provider blocks, so no proxy between tixati and jackett).
Sure, I tried to open this link in browser, got correct xml there.

**Comment by garfield69** [comment]
And I take it that if you use the kinozal indexer from your jackett dashboard to do a search you get results on the dashboard?
Have you tried enabling the Jackett **enhanced** log to see if Jackett recorded the torznab request coming from tixati, or does that not show up in the enhanced log? (Jackett dashboard, scroll to bottom, check the **enhanced logging** and press the **apply server settings) and kick off a tixati rss event.

**Comment by Shooshka** [comment]
> And I take it that if you use the kinozal indexer from your jackett dashboard to do a search you get results on the dashboard?
Yes.

Here's the full debug log:

```
2020-12-06 11:55:14.0687 Debug Connection id "0HM4P21BBDRE6" accepted. 
2020-12-06 11:55:14.0687 Debug Connection id "0HM4P21BBDRE6" started. 
2020-12-06 11:55:14.0687 Debug Connection id "0HM4P21BBDRE6" bad request data: "Unrecognized HTTP version: ''" Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unrecognized HTTP version: ''
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectUnknownVersion(Byte* version, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.IHttpParser<TRequestHandler>.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
2020-12-06 11:55:14.0687 Debug Connection id "0HM4P21BBDRE6" disconnecting. 
2020-12-06 11:55:14.0687 Debug Connection id "0HM4P21BBDRE6" received FIN. 
2020-12-06 11:55:14.0687 Debug Connection id "0HM4P21BBDRE6" stopped. 
2020-12-06 11:55:14.0799 Debug Connection id "0HM4P21BBDRE6" sending FIN because: "The Socket transport's send loop completed gracefully." 
2020-12-06 11:55:16.1889 Info Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/server/logs?_=1607244834795   
2020-12-06 11:55:16.1889 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/server/logs?_=1607244834795 
2020-12-06 11:55:16.1889 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/server/logs?_=1607244834795 
2020-12-06 11:55:16.1889 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/server/logs?_=1607244834795 
2020-12-06 11:55:16.1889 Debug The request path /api/v2.0/server/logs does not match a supported file type 
2020-12-06 11:55:16.1889 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2020-12-06 11:55:16.1889 Debug 1 candidate(s) found for the request path '/api/v2.0/server/logs' 
2020-12-06 11:55:16.1889 Debug Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs' 
2020-12-06 11:55:16.2037 Debug Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)' 
2020-12-06 11:55:16.2037 Info Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)' 
2020-12-06 11:55:16.2037 Info Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole). 
2020-12-06 11:55:16.2037 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2020-12-06 11:55:16.2037 Debug Execution plan of resource filters (in the following order): None 
2020-12-06 11:55:16.2037 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter 
2020-12-06 11:55:16.2037 Debug Execution plan of exception filters (in the following order): None 
2020-12-06 11:55:16.2037 Debug Execution plan of result filters (in the following order): None 
2020-12-06 11:55:16.2037 Info Authorization was successful. 
2020-12-06 11:55:16.2037 Debug Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole) 
2020-12-06 11:55:16.2037 Debug Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole) 
2020-12-06 11:55:16.2037 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter 
2020-12-06 11:55:16.2037 Debug No information found on request to perform content negotiation. 
2020-12-06 11:55:16.2193 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response. 
2020-12-06 11:55:16.2193 Debug Attempting to select the first formatter in the output formatters list which can write the result. 
2020-12-06 11:55:16.2193 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response. 
2020-12-06 11:55:16.2193 Info Executing ObjectResult, writing value of type 'System.Collections.Generic.List`1[[Jackett.Common.Models.CachedLog, Jackett.Common, Version=0.16.2299.0, Culture=neutral, PublicKeyToken=null]]'. 
2020-12-06 11:55:16.2467 Debug The response will be compressed with 'br'. 
2020-12-06 11:55:16.2547 Info Executed action Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole) in 40.798ms 
2020-12-06 11:55:16.2547 Info Executed endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)' 
2020-12-06 11:55:16.2547 Debug Connection id "0HM4P21BBDRE1" completed keep alive response. 
2020-12-06 11:55:16.2547 Info Request finished in 74.3033ms 200 application/json; charset=utf-8 
```
**Unrecognized HTTP version: '**
Seems my tixati with same version as yours doing smth wrong...

**Comment by Shooshka** [comment]
UPD: If I use query only with english letters all fine, so problem in Russian letters =\

**Comment by garfield69** [comment]
if I use http://127.0.0.1:9117/api/v2.0/indexers/kinozal/results/torznab/api?apikey=mykey&t=search&cat=&q=%D0%92%D1%81%D0%B5%D0%BC
instead of 
http://127.0.0.1:9117/api/v2.0/indexers/kinozal/results/torznab/api?apikey=mykey&t=search&cat=&q=Всем
then it works.

I basically used the dashboard to copy the rss feed and pasted it in the browser, added the russian search, and after the browser completed the request I copy/pasted the address into tixati which turned the russian into the escaped url equivalent.

**Comment by Shooshka** [comment]
Yep, I already testing this right now too ;)
So, tyvm for replying and helping, will open issue on tixati forum for this problem and will use workaround until fix.
