### ISSUE TITLE
[pier720] Login failed: Selector

### ISSUE THREAD

**Issue by cfilomena** [Jackett/Jackett#10424]
### Environment

**OS**: Linux

**.Net Runtime**: Mono

**Jackett Version**: v0.16.2347

**Are you using a proxy or VPN?** no

### Description

- Add 720pier indexer
- setup cookie/login
- confirm

Popup error:
Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match

### Logged Error Messages

Jackett.Common.ExceptionWithConfigData: Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 778
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 919
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by cfilomena** [comment]
I cannot see any error on 10218 and this error Is more recent than 10218. The cookie Is ok. The error started 2 weeks ago.

**Comment by garfield69** [comment]
The indexer works for me so the issue would appear to be at your end.
The cookie does not last forever, it needs to be refresh regularly whenever the web site decides it has expired.
I tested this just now, and I got the same error. I just used my browser to login to the web site, and copied the new cookie to replace the old one and the indexer works for me again.

**Comment by cfilomena** [comment]
Already retry to login again... But same error even with "fresh" cookie

**Comment by garfield69** [comment]
take a careful read of https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work and see if that helps you with this problem.
Especially the notes section.
