### ISSUE TITLE
[redacted] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Winblackka** [Jackett/Jackett#10469]
### Logged Error Messages

[System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 303
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 98
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by ilike2burnthing** [comment]
Please post enhanced logs - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Also add the originally requested details.

**Comment by tannhauserg8** [comment]
I'm seeing the same behavior. Here's my log from a test I just ran.
```
2020-12-11 15:13:49.7096 Info Request starting HTTP/1.1 POST http://***/api/v2.0/indexers/redacted/test - 0
2020-12-11 15:13:49.7096 Debug Request is continuing in applying rules. Current url is http://***/api/v2.0/indexers/redacted/test
2020-12-11 15:13:49.7096 Debug Request is continuing in applying rules. Current url is http://***/api/v2.0/indexers/redacted/test
2020-12-11 15:13:49.7096 Debug Request is continuing in applying rules. Current url is http://***/api/v2.0/indexers/redacted/test
2020-12-11 15:13:49.7096 Debug POST requests are not supported
2020-12-11 15:13:49.7120 Debug AuthenticationScheme: Cookies was successfully authenticated.
2020-12-11 15:13:49.7120 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/redacted/test'
2020-12-11 15:13:49.7120 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/redacted/test'
2020-12-11 15:13:49.7120 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-12-11 15:13:49.7120 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-12-11 15:13:49.7120 Info Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2020-12-11 15:13:49.7120 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2020-12-11 15:13:49.7120 Debug Execution plan of resource filters (in the following order): None
2020-12-11 15:13:49.7120 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2020-12-11 15:13:49.7120 Debug Execution plan of exception filters (in the following order): None
2020-12-11 15:13:49.7120 Debug Execution plan of result filters (in the following order): None
2020-12-11 15:13:49.7159 Info Authorization was successful.
2020-12-11 15:13:49.7159 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2020-12-11 15:13:49.7159 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2020-12-11 15:13:49.7159 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://redacted.ch/ajax.php?action=browse&order_by=time&order_way=desc)
2020-12-11 15:13:53.1883 Debug WebClient(HttpWebClient2): Returning OK => 64 bytes
{"status":"success","response":{"results":[],"youMightLike":[]}}
2020-12-11 15:13:53.1883 Info Found 0 releases from Redacted
2020-12-11 15:13:53.1883 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 3475.0357ms
2020-12-11 15:13:53.1883 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-12-11 15:13:53.1919 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 303
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 303
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2020-12-11 15:13:53.1996 Debug The response will be compressed with 'gzip'.
2020-12-11 15:13:53.1996 Debug Connection id "0HM4U1RE8UEOP" completed keep alive response.
2020-12-11 15:13:53.1996 Info Request finished HTTP/1.1 POST http://***/api/v2.0/indexers/redacted/test - 0 - 500 - application/json 3490.7969ms
```

**Comment by tannhauserg8** [comment]
As some additional background, I had this same behavior with this tracker a few days ago and it resolved itself when I stopped using the development branch.

**Comment by ilike2burnthing** [comment]
Can you provide the following information as well? Thanks.
```
OS:

.Net Runtime: [.Net-Core/.Net-Framework/Mono]

.Net Version:

Jackett Version:

Last Working Jackett Version:

Are you using a proxy or VPN? [yes/no]
```

**Comment by tannhauserg8** [comment]
Sure. Is there an easy way to get the .Net info when I'm running it in a Docker container? 
```
OS: Docker on Ubuntu 20.04 

.Net Runtime: [.Net-Core/.Net-Framework/Mono]

.Net Version:

Jackett Version: v0.17.20

Last Working Jackett Version: v0.17.15 (I tried falling back to this version and it didn't fix the problem)

Are you using a proxy or VPN? No
```

**Comment by ngosang** [comment]
I see the same. This is not Jackett's fault. If you browse the torrents in the site there is the same issue.

**Comment by tannhauserg8** [comment]
Confirmed this looks to not be Jackett related. I'm not the creator but you can probably close this issue.

**Comment by ilike2burnthing** [comment]
If you (or anyone with access) can update when the site issue is resolved, we can close this.

**Comment by ngosang** [comment]
It's working again
