### ISSUE TITLE
[yts] The SSL connection could not be established, see inner exception.: Cannot determine the frame size or a corrupted frame was received. (Config)

### ISSUE THREAD

**Issue by connormorse** [Jackett/Jackett#10471]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

**OS**:
windows

**Jackett Version**:
latest

**Are you using a proxy or VPN?** [yes/no]
pia split tunnel

### Description

Not sure what's happened but I seem to have an issue with certificates as caddy server is also having issues renewing certs. Any advice?

### Logged Error Messages

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 473
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in D:\a\1\s\src\Jackett.Common\Indexers\YTS.cs:line 102
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\YTS.cs:line 76
   at Jackett.Common.Indexers.YTS.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\YTS.cs:line 68
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

**Comment by garfield69** [comment]
The yts indexer is working for me on my win10 20H2 and Jackett 0.17.20

This could be a .net5 issue with PIA.
As an experiment, shutdown the Jackett service and systray, manually downgrade Jackett by installing https://github.com/Jackett/Jackett/releases/download/v0.16.2374/Jackett.Installer.Windows.exe and see if the yts indexer starts working again.

**Comment by connormorse** [comment]
downgrading seems to have fixed it! thanks for the suggestion, any idea why this would be the case?

**Comment by garfield69** [comment]
Jackett 0.17.* started using .net5, earlier versions were on .net 3.1
So when you upgrade back to 0.17, if you temporality do without PIA can you get jackett 0.17 YTS indexer to work or you get the same error?

**Comment by connormorse** [comment]
sorry for the delay, when vpn is turned off I get the SSL error with 0.17. It upgraded itself and broke. I've always had to have jackett running through the vpn to get YTS though.

**Comment by ilike2burnthing** [comment]
Well I was about to suggest that you try out the latest stable release, as it has some proxies for YTS added, but I've just seen that there was no new build published this morning, for whatever reason.

Either try the pre-release v0.17.48 and select the proxies, or v0.17.29 and enter these for YTS:
https://yts.unblockit.dev/
https://yts.unblockninja.com/
https://yts.root.yt/

Do those work with and without PIA enabled? Are you able to use other indexers with PIA enabled? Are you using PIA external to Jackett, or via Jackett's proxy setting?
