### ISSUE TITLE
[yggcookie] Exception (yggcookie): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: TimeoutError: Navigation timeout of 30000 ms exceeded: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: TimeoutError: Navigation timeout of 30000 ms exceeded (Test)

### ISSUE THREAD

**Issue by vic1997** [Jackett/Jackett#10537]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:  ARM64 Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] (idk on docker)

**.Net Version**: (idk on docker)

**Jackett Version**: v0.17.87

**Last Working Jackett Version**: v0.17.87

**Are you using a proxy or VPN?** yes I use FlareSolverr

### Description

- Adding FlareSolverr.
- Adding new tracker.
- Error

### Logged Error Messages

`
2020-12-16T16:35:49.744Z ERROR REQ-5 TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/node/flaresolverr/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
  -- ASYNC --
    at Frame.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:53)
    at Page.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:95:27)
    at resolveChallenge (/home/node/flaresolverr/dist/routes.js:74:31)
    at browserRequest (/home/node/flaresolverr/dist/routes.js:290:28)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async request.get (/home/node/flaresolverr/dist/routes.js:330:9)
    at async Object.Router [as default] (/home/node/flaresolverr/dist/routes.js:351:16)
2020-12-16T16:35:50.228Z ERROR REQ-5 Unable to process browser request. Error: TimeoutError: Navigation timeout of 30000 ms exceeded`

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

https://i.imgur.com/1r6LiZB.png

**Comment by ilike2burnthing** [comment]
Does this always happen or just a one off?

**Comment by vic1997** [comment]
@ilike2burnthing Always, I can't use FlareSolverr... :(

**Comment by ilike2burnthing** [comment]
Are any other indexers working with FlareSolverr? You can find a list of those sites known to use Cloudflare here - FlareSolverr/FlareSolverr#25

**Comment by vic1997** [comment]
@ilike2burnthing After some clean and reboot, I finally managed to get an response, but only on google. I made an issue on the FlareSolverr github for the new error because I think it come from them, here: [https://github.com/FlareSolverr/FlareSolverr/issues/41](https://github.com/FlareSolverr/FlareSolverr/issues/41)
