### ISSUE TITLE
[crazyspirits] Login failed: Selector

### ISSUE THREAD

**Issue by saitoh183** [Jackett/Jackett#10557]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: n/a

**Jackett Version**: 0.17.101

**Last Working Jackett Version**:  unknown

**Are you using a proxy or VPN?** [yes/no] no

### Description

Error when trying to add tracker. Cookies were refreshed

### Logged Error Messages

```
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 780
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 919
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]
![image](https://user-images.githubusercontent.com/1534197/102625397-6c2cee00-4113-11eb-8aa8-7344b53245bd.png)

**Comment by saitoh183** [comment]
Why is the ticket getting referred to a closed ticket that was closed because of lack of information...

**Comment by garfield69** [comment]
the indexer works for me which suggests the problem is at your end.
see if https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work helps you figure out the problem.

**Comment by saitoh183** [comment]
> the indexer works for me which suggests the problem is at your end.
> see if https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work helps you figure out the problem.

Merci, SSH a regler le tout 👍

**Comment by maxcore** [comment]
Est-ce c’est dur avoir un invitation ?

**Comment by BK-STAR77** [comment]
> > the indexer works for me which suggests the problem is at your end.
> > see if https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work helps you figure out the problem.
> 
> Merci, SSH a regler le tout

Hello pourrais tu m'expliquer la marche à suivre stp?; j'ai essayer mais j'ai surement pas tout compris, notamment ce qu'il faut insérer par la suite sur Jackett. Merci
