### ISSUE TITLE
AniLibria search returned unexpected result. Expected 200 OK but got InternalServerError

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10580]
query: "2020"  (empty query is working)
```
Jackett.Common.IndexerException: Exception (AniLibria): AniLibria search returned unexpected result. Expected 200 OK but got InternalServerError.
 ---> System.Net.WebException: AniLibria search returned unexpected result. Expected 200 OK but got InternalServerError.
   at Jackett.Common.Indexers.AniLibria.PerformSearch(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/AniLibria.cs:line 76
   at Jackett.Common.Indexers.AniLibria.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/AniLibria.cs:line 63
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 379
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 379
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 648
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 223
```

**Comment by garfield69** [comment]
works for me.
![image](https://user-images.githubusercontent.com/6933240/102720215-ed74c280-4357-11eb-801e-6fcf6c494d4d.png)

perhaps a genuine temp error at the web site?

**Comment by ngosang** [comment]
The indexer is AniLibria but it's working now. It was temporary.

**Comment by ilike2burnthing** [comment]
Happening again. https://api.anilibria.tv/v2//getUpdates?limit=100&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year in browser shows the same, likewise (at least currently) when the limit is set to anything over 6.

**Comment by ngosang** [comment]
Working fine from here

**Comment by ilike2burnthing** [comment]
Temp site issue 🤷

**Comment by kekal** [comment]
Not so temp...
![image](https://user-images.githubusercontent.com/13663141/104127067-bdbe4680-5368-11eb-8f14-44280e0b99e2.png)

**Comment by kekal** [comment]
I wrote to their support, and they quickly raised the API back.
Brave new world.
![image](https://user-images.githubusercontent.com/13663141/104132212-6d54e200-5384-11eb-9dc9-7a5d4cf33819.png)
