### ISSUE TITLE
[gimmepeers] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by tlyons24** [Jackett/Jackett#10611]
### Environment

**OS**: windows server 2016 standard

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:
.NET Framework 4.8
.NET Framework 3.5 service pack 1
.NET Framework 3.0 service pack 2
.NET Framework 2.0 service pack 2

**Jackett Version**:

**Last Working Jackett Version**:
Current version: v0.17.153

**Are you using a proxy or VPN?** [yes/no] no

### Description

When adding GimmiePeers as an indexer, input credentials, hit save, error displayes.

### Logged Error Messages

System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.GimmePeers.<>c__DisplayClass8_0.<ApplyConfiguration>b__0() in D:\a\1\s\src\Jackett.Common\Indexers\GimmePeers.cs:line 117
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 240
   at Jackett.Common.Indexers.GimmePeers.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\GimmePeers.cs:line 114
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

**Comment by ilike2burnthing** [comment]
Please provide an enhanced log for the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by tlyons24** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5733409/log.txt)

**Comment by tlyons24** [comment]
[GP Jackett log.txt](https://github.com/Jackett/Jackett/files/5733412/GP.Jackett.log.txt)

**Comment by ilike2burnthing** [comment]
`Username or password incorrect!`
Double-check that your credentials are correct and you can access the site in browser using them. If so, does your password have any special characters?

Supported characters for ISO-8859-1 - https://www.w3schools.com/charsets/ref_html_8859.asp

**Comment by tlyons24** [comment]
Just a ~, I will try to change it and test again.

**Comment by ilike2burnthing** [comment]
Any luck?

**Comment by tlyons24** [comment]
Removing the ~ from the password resolved the issue
