### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Failed to launch the browser process!/home/alex/FlareSolverr/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Failed to launch the browser process!/home/alex/FlareSolverr/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directoryTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md (Test)

### ISSUE THREAD

**Issue by silveralextv** [Jackett/Jackett#10634]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu Server

**.Net Runtime**:

**.Net Version**:

**Jackett Version**: v0.17.159

**Last Working Jackett Version**: v0.17.159

**Are you using a proxy or VPN?** [no]

### Logged Error Messages

2020-12-26T23:34:19.955Z INFO REQ-1 Incoming request: POST /v1
2020-12-26T23:34:19.957Z INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www2.yggtorrent.si/new_search/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
Error: Failed to launch the browser process!
/home/alex/FlareSolverr/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/alex/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.helper_1.helper.addEventListener (/home/alex/FlareSolverr/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2020-12-26T23:34:20.006Z ERROR REQ-1 Failed to launch the browser process!
/home/alex/FlareSolverr/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

**Comment by ilike2burnthing** [comment]
Please post this to https://github.com/FlareSolverr/FlareSolverr/issues
