### ISSUE TITLE
xthor bad search results

### ISSUE THREAD

**Issue by onedaywegonnabegood** [Jackett/Jackett#10635]
hi all,

i use radarr/sonarr with jackett, and i get a lot of errors.

for example, when i search a movie with radarr i can get all good results but sometimes (50% of time), jackett results are just the last posted torrents and not the search, so to fix it, sometimes i just retry the search by removing one category and the results work.

sometimes i just remove "&extended=1" and it's work too.
all my research are based on what a manual search on jackett and debug files on radarr gives me.

and all this things make just no senses...

can someone help me with that ?

**Comment by ilike2burnthing** [comment]
Please post the requested information:
```
OS:
.Net Runtime: [.Net-Core/.Net-Framework/Mono]
.Net Version:
Jackett Version:
Last Working Jackett Version:
Are you using a proxy or VPN? [yes/no]
```
Also post an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by onedaywegonnabegood** [comment]
OS: debian 10
.Net Runtime: do not know
.Net Version: do not know
Jackett Version: v0.17.87
Last Working Jackett Version: v0.17.87
Are you using a proxy or VPN? no

and log do not contain anything : 
2020-12-27 00:50:04.5236 Info Torznab search in Xthor for Mulan => Found 32 releases

and for example, in logs i have : 
2020-12-27 00:51:15.6909 Info Torznab search in Xthor for Source Code 2011 => Found 6 releases
2020-12-27 00:51:22.5293 Info Torznab search in Xthor for Last Airbender 2010 => Found 6 releases

and what the search get : https://i.imgur.com/hI8JQBK.png

**Comment by ilike2burnthing** [comment]
> Also post an **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by onedaywegonnabegood** [comment]
log.txt 

https://i.imgur.com/OjdfIFL.png

there is nothing

**Comment by ilike2burnthing** [comment]
That's not an enhanced log, please see the link

**Comment by onedaywegonnabegood** [comment]
https://zerobin.net/?2b0753fd6a604212#HKFgKKGDVS3vAyKNmKbuCBj7K/O9V/HHomYTGNwaU74=

**Comment by ilike2burnthing** [comment]
Thanks.

Did you search for `Avengers` but the results were for something else (your last search?), or did you search for something else and got the results for `Avengers` (which was a previous search)?

Looks like an issue with the cache (which shouldn't be happening with enhanced logging on anyway, so that's a second issue).

Disable the cache in Jackett, apply settings, and attempt to repeat the issue. Let us know if the issue stops. If not, please provide a new enhanced log of the issue with caching disabled.

**Comment by onedaywegonnabegood** [comment]
hi, i disable cache from jackett configuration (not from xthor directly, do not know how to do this)

i get more precise results now but when i make multiple search in small period of time i get the last search results, but it's more precise now without cahce.

https://zerobin.net/?4cdb08a98bb17074#/AJq9ircppye3E5sRtNrU8Db0vWgmNUpMArhDRVJF78=

**Comment by onedaywegonnabegood** [comment]
on sonarr i get last releases not what a search again

**Comment by onedaywegonnabegood** [comment]
hi, i disable cache from jackett configuration (not from xthor directly, do not know how to do this)

i get more precise results now but when i make multiple search in small period of time i get the last search results, but it's more precise now without cache.

https://zerobin.net/?50660595389a2c0f#5blP7jesxpS9iaX25nj4HEz0gIL+NxXHenjatNBAfGI=

**Comment by onedaywegonnabegood** [comment]
but i have a lot more "All indexers are unavailable due to failures" to radarr or sonarr when i search lot of episodes in short period of time

**Comment by ilike2burnthing** [comment]
Do you have the development options for xthor unticked?
If so then it's disabled (or should be, I think).

![xthor](https://user-images.githubusercontent.com/59480337/103163127-bf78fd80-47f1-11eb-8e8a-5fe800867b64.png)

@ngosang could these options cause issues with the new cache? See also: Abnormal and NorBits.

**Comment by onedaywegonnabegood** [comment]
i have it disabled, can be "keep cached files for ms" ? do i need to put it to 0 ?

**Comment by ilike2burnthing** [comment]
Feel free to try it, but it shouldn't make a difference, as a HDD cache isn't being kept in the first place.

**Comment by Robertocarlos14** [comment]
Same issue for me with debian 10 + radarr.

**Comment by ilike2burnthing** [comment]
If you do multiple searches one after the other in Jackett (waiting for the results before running the next one), does the same/similar issue occur?

**Comment by Robertocarlos14** [comment]
I did more tests and perhaps this is linked to the movie name (32 releases is when the result is wrong) :
`2020-12-31 19:12:25	Info	Torznab search in Xthor for Sound of Metal 2020 => Found 2 releases
2020-12-31 19:11:46	Info	Torznab search in Xthor for Ready Player One 2018 => Found 32 releases
2020-12-31 19:11:03	Info	Torznab search in Xthor for Sound of Metal 2020 => Found 2 releases
2020-12-31 19:09:50	Info	Torznab search in Xthor for Ready Player One 2018 => Found 32 releases
2020-12-31 19:04:17 Info	Torznab search in Xthor for Sound of Metal 2020 => Found 2 releases
2020-12-31 19:04:15	Info	Torznab search in Xthor for Tenet 2020 => Found 16 releases
2020-12-31 19:03:49	Info	Manual search in xthor for tenet => Found 16 releases
2020-12-31 19:03:38	Info	Manual search in xthor for star wars the last jedi => Found 13 releases
2020-12-31 19:03:16	Info	Torznab search in Xthor for Star Wars Les Derniers Jedi 2017 => Found 13 releases
2020-12-31 19:03:10	Info	Torznab search in Xthor for Star Wars The Last Jedi 2017 => Found 13 releases
2020-12-31 19:02:47	Info	Torznab search in Xthor for Tenet 2020 => Found 16 releases
2020-12-31 19:02:38	Info	Manual search in xthor for enola holmes => Found 11 releases
2020-12-31 19:02:21	Info	Torznab search in Xthor for Enola Holmes 2020 => Found 4 releases
2020-12-31 19:02:01	Info	Torznab search in Xthor for Mulan 2020 => Found 5 releases
2020-12-31 19:01:55	Info	Manual search in xthor for mulan => Found 18 releases
2020-12-31 19:01:30	Info	Manual search in xthor for ready player one => Found 17 releases
2020-12-31 19:01:06	Info	Torznab search in Xthor for Ready Player One 2018 => Found 32 releases
2020-12-31 18:58:44	Info	Torznab search in Xthor => Found 32 releases
2020-12-31 18:53:46	Info	Torznab search in Xthor => Found 32 releases`

and for the manual search in jackett, I have this error when I execute several requests in few seconds :
`
2020-12-31 19:15:36 | Info | Manual search in xthor for Sound of Metal 2020 => Found 0 releases
2020-12-31 19:15:36 | Error | Jackett.Common.IndexerException: Exception (xthor): Unknown state, aborting querying  ---> System.Exception: Parse error  ---> System.Exception: Unknown state, aborting querying    at Jackett.Common.Indexers.Xthor.CheckApiState(XthorError state) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Xthor.cs:line 536    at Jackett.Common.Indexers.Xthor.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Xthor.cs:line 299    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 682    at Jackett.Common.Indexers.Xthor.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Xthor.cs:line 299    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 659    at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 223
2020-12-31 19:15:36 | Error | Error on 20201231191536 for Xthor.txtSystem.Exception: Unknown state, aborting querying    at Jackett.Common.Indexers.Xthor.CheckApiState(XthorError state) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Xthor.cs:line 536    at Jackett.Common.Indexers.Xthor.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Xthor.cs:line 299     Unable to parse result     at Jackett.Common.Indexers.Xthor.CheckApiState(XthorError state) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Xthor.cs:line 536    at Jackett.Common.Indexers.Xthor.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Xthor.cs:line 299
2020-12-31 19:15:35 | Info | Manual search in xthor for Sound of Metal 2020 => Found 2 releases
2020-12-31 19:15:32 | Info | Manual search in xthor for Sound of Metal 2020 => Found 2 releases
`
but when I search from radarr, I don't have this error in jackett logs

**Comment by ngosang** [comment]
The source code of this indexer is really old and complex. They have implemented their own cache (apart from Jackett's cache) and there are a lot of options that increases the complexity.

I don't have time to register, investigate and rewrite the code. Maybe one of the previous contributors can help: @Tawagot0 @Tawagoto @AthAshino @mrhydejc @Mystere98

**Comment by onedaywegonnabegood** [comment]
@ngosang yes, this is the issue, since radarr or sonarr use alternative names, the make like 2 search in same time, so only the first search work.

example : 

2021-1-4 19:45:48.4|Debug|Torznab|Downloading Feed https://HOST/jackett/api/v2.0/indexers/xthor/results/torznab/api?t=movie&cat=2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=(removed)&offset=0&limit=100&q=Harry%20Potter%20and%20the%20Goblet%20of%20Fire 2005

2021-1-4 19:45:48.6|Debug|Torznab|Downloading Feed https://HOST/jackett/api/v2.0/indexers/xthor/results/torznab/api?t=movie&cat=2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=(removed)&offset=0&limit=100&q=Harry%20Potter%20et%20la%20Coupe%20de%20feu 2005

this will only return the results for : Harry%20Potter%20and%20the%20Goblet%20of%20Fire 2005.
you can give a try, you can open two tabs with two different search in same time (or 2 seconds after the first one) and you will see only the results of the first one

**Comment by onedaywegonnabegood** [comment]
i just checked the xthor api, and it's working fine (making 2 search in the same time).

https://api.xthor.tk/?passkey=PASSKEY&search=SEARCHNAME

**Comment by Robertocarlos14** [comment]
I did more tests and I have the issue for movies  which have many alternative titles but also with a single title.
I noticed also the issue from sonarr.

**Comment by onedaywegonnabegood** [comment]
@Robertocarlos14 yes, waiting a fix cause this just block me to see my movies and tv shows

**Comment by TupacDas** [comment]
still waiting :/

**Comment by JigSawFr** [comment]
Will review this indexer, still in analysis phase

**Comment by JigSawFr** [comment]
@Robertocarlos14 for error:
`Unknown state, aborting querying`
It's due to Xthor API DDoS protection (1 query per 2s)

**Comment by ilike2burnthing** [comment]
Worth adding a delay akin to RARBG?
https://github.com/Jackett/Jackett/blob/db6a8d89a80e3f0dccbeee3b4a280232aebd4a6c/src/Jackett.Common/Indexers/RarBG.cs#L70

**Comment by JigSawFr** [comment]
> Worth adding a delay akin to RARBG?
> 
> https://github.com/Jackett/Jackett/blob/db6a8d89a80e3f0dccbeee3b4a280232aebd4a6c/src/Jackett.Common/Indexers/RarBG.cs#L70

Yes totally, already done in my dev env!
Case was not implemented in past because it's not documented on their website api page and today it's still missing...
But, I handle now it correctly.

**Comment by JigSawFr** [comment]
I've mode some enhancement and now successfully handle api limit with delay.
you can take a look at: https://github.com/Jackett/Jackett/pull/11665
but i don't know why there is some errors as said before on results.
i will try to search more, but it's very strange.

**Comment by garfield69** [comment]
v0.17.996

**Comment by JigSawFr** [comment]
> v0.17.996

I've not referenced this issue as the main problem is not solved

**Comment by JigSawFr** [comment]
So after many digging, it seems that there are bad results because we include too manies categories in request (.tk/forums.php?action=view_topic&topic_id=5456&page=2#225081).

**Comment by JigSawFr** [comment]
There is definitely a problem with their API:
If I'm searching for NCIS as en e.g. (with Jackett or without - browser/postman)
https://api.<removed>/?passkey=<removed>&search=ncis&page=1 - I'm getting 32 results, so ok
https://api.<removed>/?passkey=<removed>&search=ncis&page=2 - 32 results too but same as p1 !
etc continously.

**Comment by JigSawFr** [comment]
So i've implemented a multiple page function to return 4x32 results (128 in total) and not more as torznab has a cap of 100.
Even if we don't know how many pages for a request, as there is only 32 rows max, i assume that i continue until i've followed 4 pages or if on page returned less than 32 rows. So it should be ok.
For series, request search is now different (last change after my initial build is reverted), we will see if it's better.
And anyway, i'm deduplicate results returned, just in case of.
