### ISSUE TITLE
Exception (hdbitsapi): Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by adamwinn** [Jackett/Jackett#10653]
### Environment

**Jackett Version**:
Jackett Version v0.17.159

**Last Working Jackett Version**:
n/a

**Are you using a proxy or VPN?** [yes/no]
no

### Description
I tried to search for something using HDBits (API) and no results were returned.

### Logged Error Messages

```
2020-12-28 19:18:16.2074 Info Request starting HTTP/1.1 GET http://diskstation.local:9117/api/v2.0/indexers/all/results?apikey=&Query=Bill%20Nye%20Saves%20the%20World%20S01&Tracker%5B%5D=hdbitsapi&_=1609207651323 - -
2020-12-28 19:18:16.2079 Debug Request is continuing in applying rules. Current url is http://diskstation.local:9117/api/v2.0/indexers/all/results?apikey=&Query=Bill%20Nye%20Saves%20the%20World%20S01&Tracker%5B%5D=hdbitsapi&_=1609207651323
2020-12-28 19:18:16.2090 Debug Request is continuing in applying rules. Current url is http://diskstation.local:9117/api/v2.0/indexers/all/results?apikey=&Query=Bill%20Nye%20Saves%20the%20World%20S01&Tracker%5B%5D=hdbitsapi&_=1609207651323
2020-12-28 19:18:16.2090 Debug Request is continuing in applying rules. Current url is http://diskstation.local:9117/api/v2.0/indexers/all/results?apikey=&Query=Bill%20Nye%20Saves%20the%20World%20S01&Tracker%5B%5D=hdbitsapi&_=1609207651323
2020-12-28 19:18:16.2101 Debug The request path /api/v2.0/indexers/all/results does not match a supported file type
2020-12-28 19:18:16.2119 Debug AuthenticationScheme: Cookies was successfully authenticated.
2020-12-28 19:18:16.2119 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/all/results'
2020-12-28 19:18:16.2128 Debug Endpoint 'Jackett.Server.Controllers.ResultsController.Results (jackett)' with route pattern 'api/v2.0/indexers/{indexerId}/results' is valid for the request path '/api/v2.0/indexers/all/results'
2020-12-28 19:18:16.2128 Debug Request matched endpoint 'Jackett.Server.Controllers.ResultsController.Results (jackett)'
2020-12-28 19:18:16.2140 Info Executing endpoint 'Jackett.Server.Controllers.ResultsController.Results (jackett)'
2020-12-28 19:18:16.2147 Info Route matched with {action = "Results", controller = "Results"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Results(Jackett.Common.Models.DTO.ApiSearch) on controller Jackett.Server.Controllers.ResultsController (jackett).
2020-12-28 19:18:16.2147 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2020-12-28 19:18:16.2159 Debug Execution plan of resource filters (in the following order): None
2020-12-28 19:18:16.2159 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresApiKey, Jackett.Server.Controllers.RequiresConfiguredIndexer, Jackett.Server.Controllers.RequiresValidQuery
2020-12-28 19:18:16.2170 Debug Execution plan of exception filters (in the following order): None
2020-12-28 19:18:16.2170 Debug Execution plan of result filters (in the following order): None
2020-12-28 19:18:16.2183 Debug Executing controller factory for controller Jackett.Server.Controllers.ResultsController (jackett)
2020-12-28 19:18:16.2191 Debug Executed controller factory for controller Jackett.Server.Controllers.ResultsController (jackett)
2020-12-28 19:18:16.2198 Debug Attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch' ...
2020-12-28 19:18:16.2198 Debug Attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch' using the name '' in request data ...
2020-12-28 19:18:16.2209 Debug Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Query' of type 'System.String' using the name 'Query' in request data ...
2020-12-28 19:18:16.2209 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Query' of type 'System.String'.
2020-12-28 19:18:16.2220 Debug Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]' using the name 'Category' in request data ...
2020-12-28 19:18:16.2220 Debug Could not find a value in the request with name 'Category' for binding property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]'.
2020-12-28 19:18:16.2230 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]'.
2020-12-28 19:18:16.2230 Debug Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Tracker' of type 'System.String[]' using the name 'Tracker' in request data ...
2020-12-28 19:18:16.2238 Debug Could not bind to collection using a format like Tracker=value1&Tracker=value2
2020-12-28 19:18:16.2335 Debug Attempting to bind model using indices. Example formats include: [0]=value1&[1]=value2, Tracker[0]=value1&Tracker[1]=value2, Tracker.index=zero&Tracker.index=one&Tracker[zero]=value1&Tracker[one]=value2
2020-12-28 19:18:16.2344 Debug Attempting to bind model of type 'System.String' using the name 'Tracker[0]' in request data ...
2020-12-28 19:18:16.2349 Debug Could not find a value in the request with name 'Tracker[0]' of type 'System.String'.
2020-12-28 19:18:16.2349 Debug Done attempting to bind model of type 'System.String' using the name 'Tracker[0]'.
2020-12-28 19:18:16.2358 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Tracker' of type 'System.String[]'.
2020-12-28 19:18:16.2358 Debug Done attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch'.
2020-12-28 19:18:16.2358 Debug Done attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch'.
2020-12-28 19:18:16.2398 Debug Attempting to validate the bound parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch' ...
2020-12-28 19:18:16.2398 Debug Done attempting to validate the bound parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch'.
2020-12-28 19:18:16.2422 Debug CACHE PruneCacheByTtl / Pruned queries: 0
2020-12-28 19:18:16.2429 Debug CACHE Status / Total cached results: 1724
2020-12-28 19:18:16.2441 Error On attempt 1 downloading from HDBits (API): Value cannot be null. (Parameter 'source') System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 496
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 457
2020-12-28 19:18:16.7470 Error On attempt 2 downloading from HDBits (API): Value cannot be null. (Parameter 'source') System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 496
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 457
2020-12-28 19:18:17.2514 Error On attempt 3 downloading from HDBits (API): Value cannot be null. (Parameter 'source') System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 496
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 457
2020-12-28 19:18:17.7544 Error Jackett.Common.IndexerException: Exception (hdbitsapi): Value cannot be null. (Parameter 'source')
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 470
   at Jackett.Common.Indexers.HDBitsApi.MakeApiRequest(String url, JObject requestData) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDBitsApi.cs:line 218
   at Jackett.Common.Indexers.HDBitsApi.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDBitsApi.cs:line 131
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 659
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 223 Jackett.Common.IndexerException: Exception (hdbitsapi): Value cannot be null. (Parameter 'source')
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 470
   at Jackett.Common.Indexers.HDBitsApi.MakeApiRequest(String url, JObject requestData) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDBitsApi.cs:line 218
   at Jackett.Common.Indexers.HDBitsApi.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDBitsApi.cs:line 131
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 659
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 223
2020-12-28 19:18:17.7594 Info Manual search in hdbitsapi for Bill Nye Saves the World S01 => Found 0 releases
2020-12-28 19:18:17.7620 Info Executing JsonResult, writing value of type 'Jackett.Common.Models.DTO.ManualSearchResult'.
2020-12-28 19:18:17.7620 Debug The response will be compressed with 'gzip'.
2020-12-28 19:18:17.7628 Info Executed action Jackett.Server.Controllers.ResultsController.Results (jackett) in 1544.8593ms
2020-12-28 19:18:17.7628 Info Executed endpoint 'Jackett.Server.Controllers.ResultsController.Results (jackett)'
2020-12-28 19:18:17.7628 Debug Connection id "0HM5AQEAUAS9V" completed keep alive response.
2020-12-28 19:18:17.7642 Info Request finished HTTP/1.1 GET http://diskstation.local:9117/api/v2.0/indexers/all/results?apikey=&Query=Bill%20Nye%20Saves%20the%20World%20S01&Tracker%5B%5D=hdbitsapi&_=1609207651323 - - - 200 - application/json;+charset=utf-8 1556.7499ms
```

**Comment by ngosang** [comment]
I don't have account. If someone invites me I can take a look.
Meanwhile maybe past contributor can help: @jyggen

**Comment by jyggen** [comment]
Don't have any invites sadly, but I'll try to take a look at it.

**Comment by jyggen** [comment]
Not really sure why `Value cannot be null. (Parameter 'source')` is thrown, because `source` is not used anywhere in the C# code for HDBitsApi nor is it a valid parameter according to HDBits' API docs. Adding `"source": null` to the request payload makes no difference, HDBits merely ignores it.

I'll try to dig deeper later, but my knowledge of Jackett's internal workings and C# is quite limited.

@adamwinn: How are you searching? Through Jackett's UI or something that uses the API (e.g. Sonarr)? A screenshot of how you've configured HDBitsApi could be helpful as well.

**Comment by adamwinn** [comment]
This might have been from when I was using `cross-seed` (https://github.com/mmgoodnow/cross-seed) but I can't remember for certain.  I'll keep an eye out for it in the future.


![Web capture_2-1-2021_221618_diskstation local](https://user-images.githubusercontent.com/3028964/103472224-5725a100-4d48-11eb-9bf2-60c28de5e0dd.jpeg)

**Comment by ilike2burnthing** [comment]
Another API with the same error - https://github.com/Jackett/Jackett/issues/10817

**Comment by ngosang** [comment]
You have to debug Jackett source code. If you set a breakpoint in this line you will see the URL and the POST parameters => https://github.com/Jackett/Jackett/blob/69125add3e6c8c686c318629b65eecad8875494c/src/Jackett.Common/Indexers/HDBitsApi.cs#L195
It looks like they changed the API and now we have to include a new parameter in the request called "source" but I can't do more without access to the site.

**Comment by jyggen** [comment]
They did not change the API. I've checked both the documentation and tried making actual requests to it. There's no reference to `source` and I haven't been able to get the error message. Since #10817 is the same error but from another tracker, it's most likely something within Jackett itself.

**Comment by ilike2burnthing** [comment]
That ended up being an issue on BTN's end which they fixed a few hours ago -https://github.com/Jackett/Jackett/issues/10817#issuecomment-761804479

**Comment by garfield69** [comment]
closing as stale. a user as recently as 12th May 2022 used this indexer without issues. #12753
