### ISSUE TITLE
[orpheus] Exception (orpheus): Error reading JObject from JsonReader. Path '', line 0, position 0.: Parse error (Config)

### ISSUE THREAD

**Issue by octophetus** [Jackett/Jackett#10701]
### Environment

**OS**:

Gentoo Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

.NET Core

**.Net Version**:

5.0.101

**Jackett Version**:

v0.16.1054.0

**Last Working Jackett Version**:

N/A, never tried adding this indexer before

**Are you using a proxy or VPN?** [yes/no]

No

### Description

I'm trying to add Orpheus as an indexer but I can't get it to work. Here's what I'm doing:

- Click `Add Indexer`
- Search for Orpheus
- Click the wrench icon
- Enter site link, username, password
- Submit form

At this point I get an error dialog saying

```
An error occured while updating this indexer
**Exception (orpheus): Error reading JObject from JsonReader. Path '', line 0, position 0.: Parse error (Config)**
```

Here is the JSON payload being sent on form submission:

```
[{"id":"sitelink","value":"https://orpheus.network/"},{"id":"username","value":"<redacted>"},{"id":"password","value":"<redacted>"},{"id":"cookiehint"},{"id":"cookie","value":""},{"id":"usefreeleechtokenswhenavailable","value":true},{"id":""},{"id":"cookieheader","value":""},{"id":"lasterror","value":""}]
```

I don't have 2FA enabled on Orpheus so I'm not using the cookie field.

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (orpheus): Error reading JObject from JsonReader. Path '', line 0, position 0.
 ---> System.Exception: Parse error
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Jackett.Common.Indexers.Abstract.GazelleTracker.PerformQuery(TorznabQuery query)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)
   at Jackett.Common.Indexers.Abstract.GazelleTracker.PerformQuery(TorznabQuery query)
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer)
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer)
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name)
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext)
```

### Screenshots

![orpheuserror](https://user-images.githubusercontent.com/23619016/103444568-446f7700-4c37-11eb-9621-fbe39ec4b98b.jpg)

**Comment by ilike2burnthing** [comment]
First thing I'd suggest would be updating your Jackett to the latest version (currently v0.17.181).

If that doesn't help, please reply over on #10700
