### ISSUE TITLE
Parsing Error from tracker Arenabg

### ISSUE THREAD

**Issue by eevlogiev** [Jackett/Jackett#10707]
### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.168

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

Happy New Year, folks!

All queries to tracker arenabg.com are failing with parsing error. This started happen yesterday. See the output below:

### Logged Error Messages

``
System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
 CardigannIndexer (arenabg): Error while parsing row ' <tr> 	<td class="category p-0 align-middle"> 		<a href="/en/torrents/?category=52" data-toggle="tooltip" title="Porn"> 			<img src="/share/default/img/icons/xxx/svg/xxx.svg" class="img-fluid" alt="Porn"> 		</a> 	</td> 	<td class="filename align-middle"> 		<div class="position-relative"> 			<div class="d-block"> 				<a href="/en/torrents/dk9aRUZnZXYvejhvWlN0VmpJTjJVQT09OjoW7pnDHvtyHwWmuWrjyBYY/" onmouseover="hovershow(&quot;https:\/\/cdn.arenabg.com\/resize\/200\/-\/var\/torrents\/2020-12\/7a0facd514d81e1dcff6d974021a156192a4fbc3\/poster.jpg&quot;);" onmouseout="hoverhide();" class="title"> 					LegalPorno - Blanche Bradburry &amp; Paola Hard SZ2584 12.31 				</a> 				<a href="/en/player/?key=dk9aRUZnZXYvejhvWlN0VmpJTjJVQT09OjoW7pnDHvtyHwWmuWrjyBYY" target="_blank" class="text-white"> 					<i class="fa fa-play-circle"></i> 				</a> 			</div> 			<div class="row no-gutters"> 				<div class="w-90"> 					<small> 						31 December 2020, Thursday @ 14:39 									  											from 						<a href="/en/users/ivanesko261-4060618.html">ivanesko261</a> 						» 						<a href="/en/torrents/?category=6">XXX</a> 						» 						<a href="/en/torrents/?category=52">Porn</a> 					</small> 				</div> 				<div class="w-10 text-right text-muted"> 				</div> 			</div> 		</div> 	</td> 	<td class="align-middle text-center">0.91 GB</td> 	<td class="align-middle seeders">2</td> 	<td class="align-middle leechers">1</td> </tr>':  System.Exception: Error while parsing field=date, selector=div.row, value= +02:00: DateTime parsing failed for "+02:00": System.Exception: FromFuzzyTime parsing failed    at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 98    at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 205    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522
2021-01-02 11:58:07 | Error | CardigannIndexer (arenabg): Error while parsing row ' <tr> 	<td class="category p-0 align-middle"> 		<a href="/en/torrents/?category=53" data-toggle="tooltip" title="XXX HD"> 			<img src="/share/default/img/icons/xxx/svg/hd.svg" class="img-fluid" alt="XXX HD"> 		</a> 	</td> 	<td class="filename align-middle"> 		<div class="position-relative"> 			<div class="d-block"> 				<a href="/en/torrents/OGsvYy8vOCtaM2d6RjhVaWdZUHdJdz09OjpDQNai6nExpo8FnCFalS1p/" onmouseover="hovershow(&quot;https:\/\/cdn.arenabg.com\/resize\/200\/-\/var\/torrents\/2020-12\/b4ec2b6f3100d56b631433e82d14e2d97a92a934\/poster.jpg&quot;);" onmouseout="hoverhide();" class="title"> 					Mz Dani made me Cum 2 Times (12.28.20) 				</a> 				<a href="/en/player/?key=OGsvYy8vOCtaM2d6RjhVaWdZUHdJdz09OjpDQNai6nExpo8FnCFalS1p" target="_blank" class="text-white"> 					<i class="fa fa-play-circle"></i> 				</a> 			</div> 			<div class="row no-gutters"> 				<div class="w-90"> 					<small> 						31 December 2020, Thursday @ 14:41 									  											from 						<a href="/en/users/ivanesko261-4060618.html">ivanesko261</a> 						» 						<a href="/en/torrents/?category=6">XXX</a> 						» 						<a href="/en/torrents/?category=53">XXX HD</a> 					</small> 				</div> 				<div class="w-10 text-right text-muted"> 				</div> 			</div> 		</div> 	</td> 	<td class="align-middle text-center">622.1 MB</td> 	<td class="align-middle seeders">9</td> 	<td class="align-middle leechers">0</td> </tr>':  System.Exception: Error while parsing field=date, selector=div.row, value= +02:00: DateTime parsing failed for "+02:00": System.Exception: FromFuzzyTime parsing failed    at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 98    at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 205    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522
``

### Screenshots

<img width="1285" alt="Screenshot 2021-01-02 at 11 59 27" src="https://user-images.githubusercontent.com/27862102/103455005-fff4e180-4cf1-11eb-84ca-1d4c2329a67e.png">

**Comment by ilike2burnthing** [comment]
Site is currently down - https://github.com/Jackett/Jackett/issues/3989#issuecomment-753272728

**Comment by ilike2burnthing** [comment]
Back up, and the issue is the date.

**Comment by ilike2burnthing** [comment]
v0.17.197

**Comment by eevlogiev** [comment]
Confirmed working good. Thank you!
