### ISSUE TITLE
[orpheus] Exception (orpheus): Error reading JObject from JsonReader. Path '', line 0, position 0.: Parse error (Config)

### ISSUE THREAD

**Issue by maxcountryman** [Jackett/Jackett#10700]
### Environment

**OS**:

Docker (Linux)

**Jackett Version**:

Jackett Version v0.17.166

**Are you using a proxy or VPN?**

No.

### Description

Jackett fails to connect using valid credentials. Credentials have not enabled 2FA/MFA; i.e. no cookie is used.

### Logged Error Messages
```
Jackett.Common.IndexerException: Exception (orpheus): Error reading JObject from JsonReader. Path '', line 0, position 0.
 ---> System.Exception: Parse error
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Jackett.Common.Indexers.Abstract.GazelleTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 200
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 682
   at Jackett.Common.Indexers.Abstract.GazelleTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 261
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 380
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 388
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 656
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 302
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Please upload an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by maxcountryman** [comment]
Here's [the enhanced log](https://gist.github.com/maxcountryman/c2b75782cd8b6e8d5a1d5be68f40dae7).

**Comment by ilike2burnthing** [comment]
@ngosang / @bool- is this cookie related even though 2FA isn't being used?

@maxcountryman / @octophetus can you try enabling 2FA and using the cookie method, see if that works?

**Comment by ngosang** [comment]
I don't have account to test deeply. In the traces I can see the URL:
https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc
Returns an error. Could you open it in the browser to see what happens?
Another thing you can try is to remove the indexer, restart Jackett and configure it again.

**Comment by gergtreble** [comment]
> I don't have account to test deeply. In the traces I can see the URL:
> https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc
> Returns an error. Could you open it in the browser to see what happens?
> Another thing you can try is to remove the indexer, restart Jackett and configure it again.

Just FYI there is a thread on the Orpheus site about this. Last comment on that thread:

> Debugged it a bit and noticed it wasn't reading the config file.
> Just passed it --config config and it worked properly.

**Comment by maxcountryman** [comment]
> I don't have account to test deeply. In the traces I can see the URL:
> https://orpheus.network/ajax.php?action=browse&order_by=time&order_way=desc
> Returns an error. Could you open it in the browser to see what happens?
> Another thing you can try is to remove the indexer, restart Jackett and configure it again.

That resource is returning a 500 in the browser for me.

**Comment by maxcountryman** [comment]
> @maxcountryman / @octophetus can you try enabling 2FA and using the cookie method, see if that works?

Will give 2FA a shot, altho it seems like there may be an issue with the resource itself.

**Comment by gergtreble** [comment]
> Will give 2FA a shot, altho it seems like there may be an issue with the resource itself.

Check out the thread on OPH:

https://orpheus.network/forums.php?action=viewthread&threadid=8451

Maybe lend your voice there and see if its its something they need to resolve?

**Comment by gergtreble** [comment]
Just to add to this the Gazelle API option in Lidarr is also broken so this looks very much like an API issue on the OPH side:

`21-1-2 16:53:17.6|Warn|LidarrErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
21-1-2 16:53:50.1|Warn|HttpClient|HTTP Error - Res: [GET] https://orpheus.network/ajax.php?action=browse&searchstr=: 500.InternalServerError

21-1-2 16:53:50.1|Warn|Gazelle|Unable to connect to indexer

[v0.7.2.1878] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://orpheus.network/ajax.php?action=browse&searchstr=]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00130] in <224ef6e62dba4024aa79163f9973ff23>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchIndexerResponse (NzbDrone.Core.Indexers.IndexerRequest request) [0x00058] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00000] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x00024] in <ba5b0adcad2b4f8581c8b6a11d5ba171>:0`

**Comment by maxcountryman** [comment]
That Lidarr error looks like what I'm seeing in the browser as well.

**Comment by maxcountryman** [comment]
This has been resolved upstream, but as was pointed out: Lidarr should probably be checking for 5xx and giving the user a more helpful error message, e.g. "The server appears to be having difficulty processing the request" or some such to make it clear that it's not a client error.

**Comment by ngosang** [comment]
@ilike2burnthing it can be closed?

**Comment by ilike2burnthing** [comment]
Oh, whoops, yea.
