### ISSUE TITLE
Error with a VPN

### ISSUE THREAD

**Issue by Zazou89** [Jackett/Jackett#10740]
### Environment

**OS**: unRAID

**Docker Version**

 **Jackett Version v0.17.197** 

**Last Working Jackett Version**:  v0.17.197 

**Are you using a proxy or VPN?** YES

### Description

I use UnRAID as OS, Jackett with FlareSolverr work perfectly, but when I root both dockers to OpenVPN dockers, FlareSolverr can't pass the test on Jackett. When I check an indexer on Jackett with Flaresolverr it returns after a minut or two an error. 

### Logged Error Messages

```
01-02 16:56:11 Error Jackett.Common.IndexerException: Exception (yggtorrent): The operation was canceled.
---> System.OperationCanceledException: The operation was canceled.
at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 184
at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 492
at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1271
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 380
--- End of inner exception stack trace ---
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 388
at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 656
at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 302
at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (yggtorrent): The operation was canceled.
---> System.OperationCanceledException: The operation was canceled.
at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 184
at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 492
at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1271
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 380
--- End of inner exception stack trace ---
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 388
at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 656
at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 302
at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

Thank you !

**Comment by ilike2burnthing** [comment]
Have a look at the troubleshooting steps here, see if any help - https://github.com/Jackett/Jackett/wiki/Troubleshooting#the-operation-was-cancelled

Try some of the other indexers which use Cloudflare DDoS Protection, see if the issue also extends to them - https://github.com/Jackett/Jackett/search?l=YAML&q=flaresolverr (also DivxTotal and MejorTorrent)

**Comment by Zazou89** [comment]
Thank you for your answer, 

Both DivxTotal and MejorTorrent work (but seems no cloudflare before access). I saw on another thread it was worked on YGGtorrent but not for me. 

I tested Torrentkitty, Doesn't work,

**Comment by ilike2burnthing** [comment]
If it's not working for any of those which currently have Cloudflare DDoS protection enabled, then please disable FlareSolverr (delete the API URL from Jackett's settings) and apply server settings. Then run the test for an affected indexer (e.g. yggtorrent), and see if you get the same error in roughly the same amount of time, or if you get an error about FlareSolverr not being configured, in a shorter amount of time.

If you get the same error, provide an enhanced Jackett log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

If however it gives an error about FlareSolverr not being configured, re-enable FlareSolverr in Jackett, and change FlareSolverr's `LOG_LEVEL` to `debug` and `LOG_HTML` to `true`. Re-run the test, get the error, and provide the FlareSolverr debug log.

**Comment by ilike2burnthing** [comment]
Well scratch that - https://github.com/FlareSolverr/FlareSolverr/issues/55

Post your Docker run/compose for FlareSolverr.

Are you able to access the API URL in a browser? You should see something like:
```
{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1610010715280,"endTimestamp":1610010715588,"version":"v1.2.1"}
```

**Comment by Zazou89** [comment]
> 
> 
> Well scratch that - [FlareSolverr/FlareSolverr#55](https://github.com/FlareSolverr/FlareSolverr/issues/55)
> 
> Post your Docker run/compose for FlareSolverr.
> 
> Are you able to access the API URL in a browser? You should see something like:
> 
> ```
> {"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1610010715280,"endTimestamp":1610010715588,"version":"v1.2.1"}
> ```
My docker command : 
```root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='FlareSolverr' -e TZ="Europe/Paris" -e HOST_OS="Unraid" -e 'LOG_LEVEL'='debug' -e 'LOG_HTML'='true' --net=container:OpenVPN-Client 'flaresolverr/flaresolverr' d59046a6e24a4ac321ca2f140f21d431c4c82d515b023153bda8875a1dc90922```

Yes it's displayed : 
`{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1610019131383,"endTimestamp":1610019131384,"version":"v1.2.1"}`

**Comment by Zazou89** [comment]
> 
> 
> If it's not working for any of those which currently have Cloudflare DDoS protection enabled, then please disable FlareSolverr (delete the API URL from Jackett's settings) and apply server settings. Then run the test for an affected indexer (e.g. yggtorrent), and see if you get the same error in roughly the same amount of time, or if you get an error about FlareSolverr not being configured, in a shorter amount of time.
> 
> If you get the same error, provide an enhanced Jackett log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
> 
> If however it gives an error about FlareSolverr not being configured, re-enable FlareSolverr in Jackett, and change FlareSolverr's `LOG_LEVEL` to `debug` and `LOG_HTML` to `true`. Re-run the test, get the error, and provide the FlareSolverr debug log.

If I disable FlareSolverr I have instantaneously this error : `Exception (yggtorrent): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured`

I already enable debug / html on FlareSolverr but it returned nothing for me.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/55#issuecomment-756125141
