### ISSUE TITLE
[karagarga]

### ISSUE THREAD

**Issue by cinico-gmail** [Jackett/Jackett#10757]
Environment

**OS**:
Unraid 6.8.3 Docker
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
N/A
**.Net Version**:
N/A
**Jackett Version**:
v0.17.181
**Last Working Jackett Version**:
N/A
**Are you using a proxy or VPN?** [yes/no]
NO
### Description

When adding Karagarga as an indexer a captcha is presented. Entering the login credentials and captcha correctly and clicking "okay" yields the error. Subsequently editing the indexer and clicking "okay" yields the same result.
Using a browser to login to the site presents a captcha but the credentials and captcha are accepted and logged in properly.

### Logged Error Messages
```
`2021-01-07 10:50:43.4237 Info Request starting HTTP/1.1 POST http://192.168.88.101:9117/api/v2.0/indexers/karagarga/test - 0 
2021-01-07 10:50:43.4248 Debug Request is continuing in applying rules. Current url is http://192.168.88.101:9117/api/v2.0/indexers/karagarga/test 
2021-01-07 10:50:43.4258 Debug Request is continuing in applying rules. Current url is http://192.168.88.101:9117/api/v2.0/indexers/karagarga/test 
2021-01-07 10:50:43.4266 Debug Request is continuing in applying rules. Current url is http://192.168.88.101:9117/api/v2.0/indexers/karagarga/test 
2021-01-07 10:50:43.4275 Debug POST requests are not supported 
2021-01-07 10:50:43.4289 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2021-01-07 10:50:43.4299 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/karagarga/test' 
2021-01-07 10:50:43.4307 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/karagarga/test' 
2021-01-07 10:50:43.4317 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2021-01-07 10:50:43.4327 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2021-01-07 10:50:43.4336 Info Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2021-01-07 10:50:43.4345 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2021-01-07 10:50:43.4355 Debug Execution plan of resource filters (in the following order): None 
2021-01-07 10:50:43.4362 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2021-01-07 10:50:43.4372 Debug Execution plan of exception filters (in the following order): None 
2021-01-07 10:50:43.4372 Debug Execution plan of result filters (in the following order): None 
2021-01-07 10:50:43.4388 Info Authorization was successful. 
2021-01-07 10:50:43.4398 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2021-01-07 10:50:43.4407 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2021-01-07 10:50:43.4417 Debug CACHE PruneCacheByTtl / Pruned queries: 0 
2021-01-07 10:50:43.4426 Debug CACHE Status / Total cached results: 244 
2021-01-07 10:50:43.4452 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://karagarga.in/browse.php?search_type=title&search=&cat=0&genre=&subgenre=&country=0&hdrip=&incldead=&source=&fl=&sort=added&d=DESC) 
2021-01-07 10:50:43.5517 Debug lasthere=2021-01-07+15%3A50%3A43; expires=Wed, 27-Jan-2021 15:50:43 GMT; Max-Age=1728000; path=/; domain=.karagarga.in 
2021-01-07 10:50:43.5531 Debug WebClient(HttpWebClient2): Returning Redirect => https://karagarga.in/login.php?returnto=%2Fbrowse.php%3Fsearch_type%3Dtitle%26search%3D%26cat%3D0%26genre%3D%26subgenre%3D%26country%3D0%26hdrip%3D%26incldead%3D%26source%3D%26fl%3D%26sort%3Dadded%26d%3DDESC 0 bytes 
2021-01-07 10:50:43.5546 Debug updating Cookies __cfduid=d0505806060b006e55a103e3eeb2c302c1610034583; PHPSESSID=ohmcfiiui11u6mftpa4rqgq3q3 => __cfduid=d0505806060b006e55a103e3eeb2c302c1610034583; PHPSESSID=ohmcfiiui11u6mftpa4rqgq3q3; lasthere=2021-01-07+15%3A50%3A43 
2021-01-07 10:50:43.5564 Debug Saving new config file: /config/Jackett/Indexers/karagarga.json.af0c87e7007c44b18bddcb8dfa41a02f.tmp 
2021-01-07 10:50:43.5626 Info CardigannIndexer (karagarga): Relogin required 
2021-01-07 10:50:43.5638 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://karagarga.in/login.php) 
2021-01-07 10:50:43.9036 Debug __cfduid=dcc40cf75fdac3cb7a9730ee2d1d2b89f1610034643; expires=Sat, 06-Feb-21 15:50:43 GMT; path=/; domain=.karagarga.in; HttpOnly; SameSite=Lax 
2021-01-07 10:50:43.9050 Debug WebClient(HttpWebClient2): Returning OK => 2446 bytes
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html><head>
<title>KG - Login</title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon"> 
<link rel="stylesheet" href="default.css?v=8" type="text/css" media="all">

<script type="text/javascript" src="/jquery-1.10.2.min.js" language="javascript"></script>
<script type="text/javascript" src="/default.js?v=3" language="javascript"></script>
 </head>
<body style="background-image:url(2.jpg?ver=1&newbanner=1); background-repeat: no-repeat;"  onLoad="makecolor(document.searchform.search);">

<div id="lightbox"></div>
<div id="curtain"></div>
<div id="lightbox-instructions">Use left/right arrow keys, ESC to close</div>

<div style="float:right; padding-top:10px; padding-right:5px; text-align:right; background-position: right 0%; background-repeat: no-repeat;">
<!--<a title="Click here to login to the tracker" href="login.php"><img border="0" title="Click here to login to the tracker" src="login.png" width="22" height="22"></a>-->
        

</div>

<table width="100%" cellspacing="0" cellpadding="0" align="center" style="background-color: transparent;">
<tr><td class="clear" valign="bottom" style="background-color: transparent; height:170px;">
<div id="ddimagetabs">
<a href="/login.php">Login</a>
</div>

</tr>
</table>
<!--[if lt IE 7.]>
<div style="position: relative; top: -80px;"><![endif]-->
<table class="main" width="100%" border="0" cellspacing="0" cellpadding="0" align="center" style="background-color: transparent;">

<!-- ~~~~~~~~~~- MENU ~~~~~~~~~ -->
<tr>
<td align="center" class="outer">

<form method="post" action="takelogin.php">
<table border="0" cellpadding=5>
<tr><td class=rowhead>Username:</td><td align=left><input type="text" size=40 name="username" /></td></tr>
<tr><td class=rowhead>Password:</td><td align=left><input type="password" size=40 name="password" /></td></tr>

	<tr><td class=rowhead></td><td align=center>
		<img id="captcha_img" src="captcha.php?a=893004303">
		<br> Enter the code shown: 
		<input type="text" size=6 name="captcha" />
	</td></tr>
	
<tr><td colspan="2" align="center"><input type="submit" value="Log in!" class=btn>
<br><br>
<a href="recover.php">Forgot your password?</a>

</td></tr>
</table>
</form>


</td></tr></table><!--[if lt IE 7.]></div><![endif]-->
</body></html> 
2021-01-07 10:50:43.9063 Debug updating Cookies  => __cfduid=dcc40cf75fdac3cb7a9730ee2d1d2b89f1610034643 
2021-01-07 10:50:43.9077 Debug Saving new config file: /config/Jackett/Indexers/karagarga.json.00ab5f20a0694c3f9309d1a4b2dfeaaf.tmp 
2021-01-07 10:50:43.9154 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://karagarga.in/captcha.php?a=893004303) 
2021-01-07 10:50:44.3561 Debug PHPSESSID=2vbu2rst9641m96g9fa4gi85o1; path=/ 
2021-01-07 10:50:44.3579 Debug WebClient(HttpWebClient2): Returning OK => 28690 bytes <BINARY> 
2021-01-07 10:50:44.3597 Debug updating Cookies __cfduid=dcc40cf75fdac3cb7a9730ee2d1d2b89f1610034643 => __cfduid=dcc40cf75fdac3cb7a9730ee2d1d2b89f1610034643; PHPSESSID=2vbu2rst9641m96g9fa4gi85o1 
2021-01-07 10:50:44.3610 Debug Saving new config file: /config/Jackett/Indexers/karagarga.json.7e84382c5f21427ea8df825864acb72a.tmp 
2021-01-07 10:50:44.3668 Error CardigannIndexer (karagarga): Found captcha during automatic login, aborting 
2021-01-07 10:50:44.3686 Error Error on 20210107105044 for Karagarga.txtSystem.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1292




 
2021-01-07 10:50:44.3707 Debug Saving new config file: /config/Jackett/Indexers/karagarga.json.72476dd6c2e0410fae2a7039ca818bc9.tmp 
2021-01-07 10:50:44.3772 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 938.4026ms 
2021-01-07 10:50:44.3783 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2021-01-07 10:50:44.3796 Error Jackett.Common.IndexerException: Exception (karagarga): Relogin failed
 ---> System.Exception: Parse error
 ---> System.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1292
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/BaseIndexer.cs:line 682
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1620
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/BaseIndexer.cs:line 380
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/BaseIndexer.cs:line 388
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/BaseIndexer.cs:line 656
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Services/IndexerManagerService.cs:line 302
   at Jackett.Server.Controllers.IndexerApiController.Test() in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (karagarga): Relogin failed
 ---> System.Exception: Parse error
 ---> System.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1292
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/BaseIndexer.cs:line 682
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1620
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/BaseIndexer.cs:line 380
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/BaseIndexer.cs:line 388
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Indexers/BaseIndexer.cs:line 656
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Common/Services/IndexerManagerService.cs:line 302
   at Jackett.Server.Controllers.IndexerApiController.Test() in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /tmp/makepkg/jackett/src/Jackett-0.17.181/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2021-01-07 10:50:44.3893 Debug The response will be compressed with 'gzip'. 
2021-01-07 10:50:44.3905 Debug Connection id "0HM5J3POI4JG5" completed keep alive response. 
2021-01-07 10:50:44.3914 Info Request finished HTTP/1.1 POST http://192.168.88.101:9117/api/v2.0/indexers/karagarga/test - 0 - 500 - application/json 967.7415ms `
```

**Comment by ilike2burnthing** [comment]
Check in the log that the username and password are as you had typed them, in particular that any special characters haven't been changed.

**Comment by cinico-gmail** [comment]
There is no username or password anywhere in the log file.

**Comment by cinico-gmail** [comment]
Okay, I updated to 0.17.197 and now I see username and password + captcha submittal in the logs. Credentials are correct on comparison. Page back from Karagarga says "You did not enter the correct CAPTCHA code."

Seems like maybe there is misalignment between the captcha image presented in the config dialog and the one expected when credentials are submitted. I will try to get a new CAPTCHA to be generated and submit as quickly as possible after seeing it update.

**Comment by ilike2burnthing** [comment]
Possible browser cache issue? Try using Jackett in a private/incognito window.

**Comment by cinico-gmail** [comment]
Nope, tried Firefox and on Chrome in a separate profile and using incognito. Same behavior. It doesn't like the captcha submitted right off the bat when adding the indexer for the first time, nor subsequently.

**Comment by ilike2burnthing** [comment]
Ah, looks like they've changed the input name for the captcha from `imagestring` to `captcha`. Can you change that in your karagarga.yml file, restart Jackett, try logging in again with the new captcha, and run a test and search?
https://github.com/Jackett/Jackett/blob/2f476008eb9ab50faa335a2a831b543c55893884/src/Jackett.Common/Definitions/karagarga.yml#L45

I don't have an account, otherwise I'd just check it myself.

**Comment by cinico-gmail** [comment]
Yep, that fixes it. I'll manage it while I wait for updated code to trickle down to my env.

**Comment by ilike2burnthing** [comment]
Thanks! Will be included in the next release in a few hours.

**Comment by ilike2burnthing** [comment]
[v0.17.231](https://github.com/Jackett/Jackett/releases/tag/v0.17.231)
