### ISSUE TITLE
[REQ] DanishBytes.org

### ISSUE THREAD

**Issue by piratkongen** [Jackett/Jackett#10758]
https://danishbytes.org/

Private tracker. (has open registration undtil 10/01/21)

Looking forward. Really hope you can help us out! Peace and thank you!

**Comment by piratkongen** [comment]
[danishbytes.zip](https://github.com/Jackett/Jackett/files/5791944/danishbytes.zip)

Did it ourselves.
Is it possible to add it officially? Thank you very much!
Cheers

**Comment by ilike2burnthing** [comment]
Thanks! Submit it as a PR and I'll look it over tomorrow (I'm very much in need of sleep).

**Comment by ilike2burnthing** [comment]
Oh, one quick suggested edit:
```
id: danishbytes
name: DANISH BYTES
description: "DANISH BYTES is a Private Danish Tracker"
```
(I think that's how they've stylised it, though I was only on the site for 2mins)

**Comment by piratkongen** [comment]
[danishbytes.zip](https://github.com/Jackett/Jackett/files/5792401/danishbytes.zip)

Aight, thank you. This is the final one, with a small change to categories also.

EDIT: I don't have push access, can you please :)

**Comment by labaland** [comment]
Still missing in Jackett Version v0.17.261

**Comment by ilike2burnthing** [comment]
Yep, fix is already in place https://github.com/Jackett/Jackett/commit/9a2ab09f16784d7cd06de7b6b6b49a21a812dcfe, will publish a new build shortly

**Comment by ilike2burnthing** [comment]
[v0.17.284](https://github.com/Jackett/Jackett/releases/tag/v0.17.284)

**Comment by piratkongen** [comment]
Hi
Can you change minimum ratio to 1.1 instead of 1.0

And also it is reported that the magnet link is not quite working, so people comment it for temporary solution:
```
﻿#    magnet:
#      selector: a[href^="magnet"]
#      attribute: href
```

**Comment by ilike2burnthing** [comment]
Is the magnet issue with the site/tracker or the indexer (I just tried a few and was able to download fine)? Does making magnets optional resolve the issue?
```
﻿    magnet:
      optional: true
      selector: a[href^="magnet"]
      attribute: href
```

**Comment by ilike2burnthing** [comment]
https://danishbytes.org/ - Error 522 - Connection timed out

**Comment by piratkongen** [comment]
Server IP was changed. It is back up.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by piratkongen** [comment]
Categories are changed to a more simple interface:

![image](https://user-images.githubusercontent.com/77119791/109956252-bb7ec580-7ce3-11eb-9e05-9afcd2f77d07.png)


https://danishbytes.org/categories/1 Movies
https://danishbytes.org/categories/2 TV
https://danishbytes.org/categories/5 Appz
https://danishbytes.org/categories/4 Games
https://danishbytes.org/categories/3 Music
https://danishbytes.org/categories/8 Bookz

**Comment by garfield69** [comment]
v0.17.627

**Comment by piratkongen** [comment]
To fix it, because many users reports that it keeps downloading junk meta files, one suggest to:
Find the magnet part and change to:

```
﻿#    magnet:
#      selector: a[href^="magnet"]
#      attribute: href**

```

**Comment by ilike2burnthing** [comment]
Available in next version

**Comment by b0r0mir** [comment]
DanishBytes is not working in Sonarr via jackett anymore. Searches don't return any results. Many users report this.
It's working Radarr and medusa via jackett.
I'll be happy to provide any additional info if needed.

**Comment by garfield69** [comment]
@b0r0mir  yes it appears the indexer did not have the tvsearch season&ep definitions so Sonarr could not search.
The next release of Jackett due out in about 11 hours or so should fix.

**Comment by garfield69** [comment]
v0.18.541

**Comment by b0r0mir** [comment]
Yup DanishBytes is working in sonarr with DBy now.

**Comment by kekec777** [comment]
> 
> 
> Yup DanishBytes is working in sonarr with DBy now.

Can you please explain how you did it to work?
It seems i still get an error

**Comment by garfield69** [comment]
@kekec777  you may need to restart Sonarr, in order to force the app to reset its in memory view of the indexer config.
Then after restarting Sonarr, edit the Sonarr indexer definition and save it to ensure Sonarr is aware of the changed tv-search parameters.

**Comment by garfield69** [comment]
https://danishbytes.org/ returning DNS_PROBE_FINISHED_NXDOMAIN

**Comment by piratkongen** [comment]
https://danishbytes.org/ is down for a few days.
Use [https://danishbytes.club/](https://danishbytes.org/) e.g.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by garfield69** [comment]
v0.20.197

**Comment by ilike2burnthing** [comment]
https://danishbytes.club/ & https://danishbytes2.org/ - 403 Forbidden

**Comment by piratkongen** [comment]
Server migration. Downtime ~1-2 hours

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://danishbytes.club/ - Connection timed out Error code 522

**Comment by garfield69** [comment]
working for me.

**Comment by garfield69** [comment]
https://danishbytes.club/ DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://danishbytes.club/login HTTP ERROR 500

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://danishbytes.club/ > HTTP ERROR 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by Sveske-Juice** [comment]
Danishbytes has stopped working for me. On they website they have said they are doing a refactor of the code so they might have changed something that makes this fail?

i get this error:
```
Error downloading. indexer: danishbytes-api path: https://danishbytes.club/torrent/download/112167.(removed)
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 85
```

**Comment by garfield69** [comment]
I can initiate a download with the danishbytes indexer without issue, so the problem appears to be at your end.
Check on the web site that you have the necessary ratio, and that you are not being blocked from downloading.
If you cannot figure it out, then raise a fresh ticket with an enhanced Jackett log of your download attempt.

**Comment by Sveske-Juice** [comment]
Yes i'm sorry, i fell under the minimum required ratio so i can't download longer. False alarm
Thank you:)

**Comment by garfield69** [comment]
https://danishbytes.club/ > cloudflare  Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by piratkongen** [comment]
DanishBytes is changing name, domain and the tracker itself (Based on the unit3d 8.2 API). What is the best way to go forward without causing to much headache for the users?

API keys, RSS keys and such remain the same and stay functional. Category ID's change but the category names remain the same.

**Comment by ilike2burnthing** [comment]
If you'll briefly have both sites active, then you could give us early access to update the indexer in time. Otherwise, just let us know in advance when the changeover is happening, and we'll make sure to have it done quickly. We generally just do one release a day (~6am UTC, with Docker updates usually within an hour of that), so that's the main thing that will determine how long users have to wait.

**Comment by piratkongen** [comment]
The new site is online, running in production mode, but with demo data and not the real data, gives us time to make sure everything is correct and at the same time giving us minimal downtime as all that's needed is migrating the DB and moving any files.

Does this help? We plan to migrate within 3-14 days, without any exact date in mind except that we want it done before April. If it does, where could I send you the new site and demo user?

**Comment by garfield69** [comment]
`jacketttest [at] gmail [dot] com`

**Comment by piratkongen** [comment]
We are migrating today / now.

**Comment by garfield69** [comment]
- https://nordicbytes.org/ > Maintenance Cool stuff is happening! Please bear with us as we do something something. 
- Bad gateway Error code 502
- Web server is down Error code 521

**Comment by piratkongen** [comment]
Migration complete. We are going to have some downtime here and there. But things seem to somewhat be running ok now.

**Comment by ilike2burnthing** [comment]
Updated. Next release out in a few hours. Prowlarr will merge definition soon (few hours to a few days).

---

Few notes:
- Is there a version number for NBy anywhere on the site? I think DBy had v0.96 at the bottom of the page.
- `perPage` is currently restricted to 21, anything higher returns an error page. 100 is the normal.
- The API key on https://nordicbytes.org/account/apikey is cut off, so while current users are fine, new ones won't be able to add the indexer.

**Comment by garfield69** [comment]
>    The API key on https://nordicbytes.org/account/apikey is cut off, so while current users are fine, new ones won't be able to add the indexer.

while the display may show an truncated api key, double clicking it to select and then copy/paste does fetch the complete key.
So we could update the indexer config accordingly.
Also, since we have the direct link for the api key, why not update the indexer info to show this link  ;-)
557eb58e403eb1480ecbc5060e82bea7ee67c80e

**Comment by garfield69** [comment]
I'm getting 500 internal server error when using the new indexer. just me?

**Comment by piratkongen** [comment]
Don't know, we had some issues in the first few hours with a massive amount of 500 errors due to how the traffic was handled, but it was resolved 10 hours ago. You get 500 on all pages or a specific page?

**Comment by garfield69** [comment]
I'm referring to our indexer which uses the NBy API.
example
`https://nordicbytes.org/api/torrents/filter?name=greenland&sortField=created_at&sortDirection=desc&perPage=21` 
returns 
`500 - Internal Error Uh oh. The pokemons has gone on a break it seems! Something went horribly wrong.`

**Comment by piratkongen** [comment]
Please try now? Should be fixed.

**Comment by garfield69** [comment]
Excellent. Online. And you've also fixed the perPage problem so I can update the indexer back to 100. Thanks.

**Comment by garfield69** [comment]
v0.24.1427

**Comment by RedSnt** [comment]
I should probably create a new issue, but because I had changed the URL on the previously existing DanishBytes entry in Jackett, now that it has been renamed to NordicBytes I actually have duplicates, and I can't get remove either of them. Really weird issue.

**Comment by KHoegh93** [comment]
> I should probably create a new issue, but because I had changed the URL on the previously existing DanishBytes entry in Jackett, now that it has been renamed to NordicBytes I actually have duplicates, and I can't get remove either of them. Really weird issue.

If this dosent help, just ignore it. But i have a folder thats called "Indexers" where the config are stored for each indexer. Maybe you can delete the onces thats "stuck" ?

**Comment by ilike2burnthing** [comment]
This would only happen if you created a custom indexer (in which case you'd need to delete the custom definition file), or there's some sort of permissions issue preventing the old definition file from being deleted.

If the solution in the comment above doesn't help, open a new issue and provide the information requested.

**Comment by RedSnt** [comment]
Appreciate the help, deleting the definition `danishBytes-api.yml` and restarting jackett did the trick 👍

**Comment by ilike2burnthing** [comment]
Announcement up that they're reverting, but I have my doubts ;)
