### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r756035 is guaranteed to work.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r756035 is guaranteed to work. (Test)

### ISSUE THREAD

**Issue by nicovan** [Jackett/Jackett#10765]
### Description
Hello,
I got the message : An error occurred while testing this indexer
Exception (yggtorrent): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r756035 is guaranteed to work.: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r756035 is guaranteed to work.

Is it possible to increase the timeout value ?

Thanks.

**Comment by ngosang** [comment]
I think the timeout is not the issue here.
Try to reinstall FlareSolverr following the documentation or use Docker instead if you can.

**Comment by Alandil35** [comment]
Hi,
I have the same issue...

**Comment by CyberPoison** [comment]
Same issue here, Docker installation both (Jackett and flaresolverr) and both have been pulled with the newest version of the tag latest

**Comment by CyberPoison** [comment]
More information about Flaresolverr

```

  -- ASYNC --
    at Frame.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:53)
    at Page.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:95:27)
    at resolveChallenge (/home/node/flaresolverr/dist/routes.js:44:31)
    at resolveChallengeWithTimeout (/home/node/flaresolverr/dist/routes.js:25:25)
    at browserRequest (/home/node/flaresolverr/dist/routes.js:149:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async request.get (/home/node/flaresolverr/dist/routes.js:189:9)
    at async Object.Router [as default] (/home/node/flaresolverr/dist/routes.js:202:16)
2021-01-10T17:42:39.566Z ERROR REQ-7 Unable to process browser request. Error: TimeoutError: Navigation timeout of 30000 ms exceeded
2021-01-10T17:42:39.591Z INFO REQ-8 Incoming request: POST /v1
2021-01-10T17:42:39.592Z INFO REQ-8 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.yggtorrent.si/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-01-10T17:42:39.987Z INFO REQ-8 Cloudflare detected
2021-01-10T17:43:22.864Z INFO REQ-8 Successful response in 43.273 s
2021-01-10T17:43:22.877Z INFO REQ-9 Incoming request: POST /v1
2021-01-10T17:43:22.877Z INFO REQ-9 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.yggtorrent.si/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-01-10T17:43:53.115Z ERROR REQ-9 TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/node/flaresolverr/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
    at async FrameManager.navigateFrame (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:70:21)
    at async Frame.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:295:16)
    at async Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:16)
    at async resolveChallenge (/home/node/flaresolverr/dist/routes.js:44:20)
    at async resolveChallengeWithTimeout (/home/node/flaresolverr/dist/routes.js:26:16)
    at async browserRequest (/home/node/flaresolverr/dist/routes.js:149:22)
    at async request.get (/home/node/flaresolverr/dist/routes.js:189:9)
    at async Object.Router [as default] (/home/node/flaresolverr/dist/routes.js:202:16)
  -- ASYNC --
    at Frame.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:53)
    at Page.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:95:27)
    at resolveChallenge (/home/node/flaresolverr/dist/routes.js:44:31)
    at resolveChallengeWithTimeout (/home/node/flaresolverr/dist/routes.js:25:25)
    at browserRequest (/home/node/flaresolverr/dist/routes.js:149:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async request.get (/home/node/flaresolverr/dist/routes.js:189:9)
    at async Object.Router [as default] (/home/node/flaresolverr/dist/routes.js:202:16)
2021-01-10T17:43:53.115Z ERROR REQ-9 Unable to process browser request. Error: TimeoutError: Navigation timeout of 30000 ms exceeded
2021-01-10T17:43:53.119Z INFO REQ-10 Incoming request: POST /v1
2021-01-10T17:43:53.120Z INFO REQ-10 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.yggtorrent.si/new_search/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-01-10T17:43:53.656Z INFO REQ-10 Cloudflare detected
2021-01-10T17:43:57.828Z INFO REQ-10 Successful response in 4.709 s
2021-01-10T17:46:58.974Z INFO REQ-11 Incoming request: POST /v1
2021-01-10T17:46:58.974Z INFO REQ-11 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.yggtorrent.si/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-01-10T17:47:29.160Z ERROR REQ-11 TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/node/flaresolverr/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
    at async FrameManager.navigateFrame (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:70:21)
    at async Frame.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/FrameManager.js:295:16)
    at async Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:16)
    at async resolveChallenge (/home/node/flaresolverr/dist/routes.js:44:20)
    at async resolveChallengeWithTimeout (/home/node/flaresolverr/dist/routes.js:26:16)
    at async browserRequest (/home/node/flaresolverr/dist/routes.js:149:22)
    at async request.get (/home/node/flaresolverr/dist/routes.js:189:9)
    at async Object.Router [as default] (/home/node/flaresolverr/dist/routes.js:202:16)
  -- ASYNC --
    at Frame.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/home/node/flaresolverr/node_modules/puppeteer/lib/Page.js:485:53)
    at Page.<anonymous> (/home/node/flaresolverr/node_modules/puppeteer/lib/helper.js:95:27)
    at resolveChallenge (/home/node/flaresolverr/dist/routes.js:44:31)
    at resolveChallengeWithTimeout (/home/node/flaresolverr/dist/routes.js:25:25)
    at browserRequest (/home/node/flaresolverr/dist/routes.js:149:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async request.get (/home/node/flaresolverr/dist/routes.js:189:9)
    at async Object.Router [as default] (/home/node/flaresolverr/dist/routes.js:202:16)
2021-01-10T17:47:29.161Z ERROR REQ-11 Unable to process browser request. Error: TimeoutError: Navigation timeout of 30000 ms exceeded
2021-01-10T17:47:38.420Z INFO REQ-12 Incoming request: POST /v1
2021-01-10T17:47:38.420Z INFO REQ-12 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.yggtorrent.si/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-01-10T17:47:38.989Z INFO REQ-12 Cloudflare detected
2021-01-10T17:47:45.013Z INFO REQ-12 Successful response in 6.593 s
```

**Comment by ilike2burnthing** [comment]
Can you provide the version numbers for each (e.g. v1.2.3 & v0.17.123)?

'latest' does not really help, and when it comes to Docker can actually be misleading if you haven't pulled new images.

**Comment by nicovan** [comment]
Jackett Version v0.17.284 
and for FlareSolver I see in the docker logs : FlareSolverr v1.2.0

**Comment by ilike2burnthing** [comment]
Update FlareSolverr, current version v1.2.3

**Comment by Zazou89** [comment]
Same error since today, FL 1.2.3 / Jackett 0.17.261

**Comment by powatt** [comment]
same issues with flare solver 1.2.3 i run it on windows and all the other thiing are runniong on my nas maybe the issues but they are all on the same local network

**Comment by ilike2burnthing** [comment]
If a site's cookies are dependent on system information (e.g. user-agent, screen resolution, etc.) then that could be the cause of the issue. Can you not run FlareSolverr on your NAS? If not, test by running Jackett on your computer, see if that solves your issue so you at least know the cause.

**Comment by nicovan** [comment]
Ok now I know what happened, I used the docker image zhuxiaole1992/flaresolverr:latest instead of flaresolverr/flaresolverr:latest.
Now it's working well again ;)
I hope this topic will help other people in the same situation than me.
Many thanks.
Regards.

**Comment by ngosang** [comment]
Just one note for future readers: "latest" tag means nothing.
When you download the latest image from Docker the fist time it work as expected. Latest tag point to latest release. The thing is Docker is not going to update or download new releases. You have to:
1. Stop the container `docker stop ..`
2. Remove the container `docker rm ...`
3. Remove the image `docker rmi ..`
4. Download the latest image again `docker pull ...`
