### ISSUE TITLE
[1337x] Exception (1337x):  Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by gamegem** [Jackett/Jackett#10777]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows 10 (x64 bit) (Build 19042)

**.Net Runtime**: Net.Core - 3.1.302 (x64)

**.Net Version**: Framework Version - 4.0

**Jackett Version**: v0.17.213

**Last Working Jackett Version**: (Never tried before)

**Are you using a proxy or VPN?** No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

1. Install latest Windows release version from repo.
2. Install Jackett as an windows service.
3. Start up Jackett and open WEB UI.
4. Add any public indexer and test the connection.
5. Come across this error

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (1337x):  Received an unexpected EOF or 0 bytes from the transport stream.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 184
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 492
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1271
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 380
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 388
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 656
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 302
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

### Screenshots

No picture to add really just a normal error

**Comment by ilike2burnthing** [comment]
Something is very wrong with your Windows installation if it's using .net framework 4.0, update to 4.8 - https://dotnet.microsoft.com/download/dotnet-framework

**Comment by gamegem** [comment]
After checking it again, it was an error on my part. These are the currently installed .NET frameworks I have installed:

```
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084
```

Just in-case that was still the issue I tried downloading the latest one and on install it mentions that I have the latest version already. Any idea how I can get Jackett running? 
Thanks a lot :)

**Comment by ilike2burnthing** [comment]
Can you access 1337x in browser using the same link, on the same device, from the same IP address?

**Comment by gamegem** [comment]
Yes I can, never had any issue with accessing any of these sites on this and other devices with my home network.

**Comment by ilike2burnthing** [comment]
Please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by gamegem** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5799346/log.txt)

Did a restart and tested again. Let me know if you need anything else.

**Comment by ilike2burnthing** [comment]
Can you specifically access the page https://1337x.to/cat/Movies/time/desc/1/ in browser?

Run a search (e.g. `720p 2020`) rather than a test, see if that gives you results or a different error.

Remove 1337x from Jackett, restart Jackett, add it again and try running a test, see if that makes any difference.

**Comment by gamegem** [comment]
> Can you specifically access the page https://1337x.to/cat/Movies/time/desc/1/ in browser?

Yup, works on both Firefox and Chrome.

> Run a search (e.g. 720p 2020) rather than a test, see if that gives you results or a different error.

Searching in the browser works, searching as an indexer doesn't. ( no new error )

> Remove 1337x from Jackett, restart Jackett, add it again and try running a test, see if that makes any difference.

Remove , restarted and added it back , same result :/

**Comment by ilike2burnthing** [comment]
Sorry, just re-read your initial post, specifically, "Add any public indexer and test the connection." This is happening on all indexers?

**Comment by gamegem** [comment]
Tried adding the following public trackers (just a randomly selected set of them) :

- 1337x  [The same exception error]

- Zooqle [The same exception error]

- RARBG [The same exception error]

- TPB [The same exception error]
 
- Torrentz2 [The same exception error]

Safe to safe that it happens for all if not most of them

**Comment by ilike2burnthing** [comment]
Thanks, seems like it.

Try temporarily disabling any antivirus and/or firewall you have running, in case that is causing a problem. If so, you'd need to look at making an exception/trusted rule for Jackett.

If that's not the cause, and you're up for trying [Docker for Windows](https://hub.docker.com/editions/community/docker-ce-desktop-windows) with the [Jackett image](https://github.com/linuxserver/docker-jackett/releases), that might be a way to get you up and running for now, but I'm kinda stumped.

@ngosang / @garfield69 any ideas?

**Comment by ngosang** [comment]
I have no ideas, but I'm sure this issue is not affecting all Jackett's users. It has to be something in his computer or network. 

> Try temporarily disabling any antivirus and/or firewall you have running, in case that is causing a problem. If so, you'd need to look at making an exception/trusted rule for Jackett.

That is what I would try.

**Comment by gamegem** [comment]
Yeah tried disabling Firewall, Windows defender, checking router level firewall if there was anything but still nada, I'll see if I want to get into windows docker atm. If not I guess I'll just have to wait and try it out after future updates. 

Thanks for you time and help @ilike2burnthing and @ngosang Cheers 👍
