### ISSUE TITLE
[broadcasthenet aka BTN] Testing returned no results! (Config)

### ISSUE THREAD

**Issue by vember31** [Jackett/Jackett#10817]
### Environment

**OS**: Ubuntu 16.04

**.Net Runtime**: .NET Core

**.Net Version**:  Unsure of how to find out :(

**Jackett Version**: v0.17.261

**Last Working Jackett Version**: Not version based; any recent version of Jackett will fail.  It is / was a change on BTN's side.  If it helps, Sonarr's integration with BTN is working still.

**Are you using a proxy or VPN?** No

### Description: 

Either try to add BTN as a tracker in Jackett, or if you have it added already, try testing it.  You'll receive this error and be recommended to submit an issue here on Github.  BTN made their change yesterday, Jan 11.  Errors also show up in the logs, described / shown below.

### Logged Error Messages

The full error stack from the log is here:

Jackett.Common.ExceptionWithConfigData: Testing returned no results!    at Jackett.Common.Indexers.BroadcasTheNet.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BroadcasTheNet.cs:line 80    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
--

### Screenshots
**Error from the logs:**
![image](https://user-images.githubusercontent.com/17370796/104543126-73e49300-55ea-11eb-8ba3-97e5eace9d73.png)

**Error received when trying to add BTN as a tracker or test it if already added:**
![image](https://user-images.githubusercontent.com/17370796/104543344-e48baf80-55ea-11eb-848e-80d564c6bfdf.png)

**Comment by vember31** [comment]
Should add too that folks in BTNs forums mention that using the api over https takes care of this, though this error occurs in Jackett whether using http or https for the URL.

**Comment by ilike2burnthing** [comment]
Seems this is an issue for Sonarr as well - https://forums.sonarr.tv/t/invalid-torrent-file-specified-monotorrent-bencoding-bencodingexception-could-not-find-what-value-to-decode/27476

We're already using HTTPS for the API, so unfortunately it's not as simple a fix for us - https://github.com/Jackett/Jackett/blob/b28def09d680b28c2ff43bd949265b7b4fd2835e/src/Jackett.Common/Indexers/BroadcasTheNet.cs#L22

**Comment by ilike2burnthing** [comment]
@seeyabye could you have a look at this as well?

**Comment by vember31** [comment]
Yeah :( thanks though @ilike2burnthing.  I did peek over at your post [here](https://forums.sonarr.tv/t/invalid-torrent-file-specified-monotorrent-bencoding-bencodingexception-could-not-find-what-value-to-decode/27476/2), where you were hoping to validate the download URL.  I can confirm confirm that BTN still follows this schema:

http://broadcasthe.net/torrents.php?action=download&id=(id)&authkey=(ak)&torrent_pass=(tp)

**Comment by ilike2burnthing** [comment]
Can you post an enhanced log of the issue?
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by vember31** [comment]
Sure! See below or go [here ](https://pastebin.com/ZpsXmCjx)(using qDG4MfLdEm).  I've also copied & pasted the key parts of the error below.  Might've redacted some silly things but I wasn't sure whether to or not.



``2021-01-14 12:36:32.0004 Error On attempt 1 downloading from BroadcasTheNet: Value cannot be null. (Parameter 'source') System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 176
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 492
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 457
2021-01-14 12:36:32.5052 Error On attempt 2 downloading from BroadcasTheNet: Value cannot be null. (Parameter 'source') System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 176
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 492
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 457
2021-01-14 12:36:33.0055 Error On attempt 3 downloading from BroadcasTheNet: Value cannot be null. (Parameter 'source') System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 176
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 492
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 457
2021-01-14 12:36:33.5069 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 1505.0893ms 
2021-01-14 12:36:33.5069 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2021-01-14 12:36:33.5069 Error Jackett.Common.ExceptionWithConfigData: Value cannot be null. (Parameter 'source')
   at Jackett.Common.Indexers.BroadcasTheNet.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BroadcasTheNet.cs:line 80
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.ExceptionWithConfigData: Value cannot be null. (Parameter 'source')
   at Jackett.Common.Indexers.BroadcasTheNet.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BroadcasTheNet.cs:line 80
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2021-01-14 12:36:33.5069 Debug The response will be compressed with 'gzip'. 
2021-01-14 12:36:33.5069 Debug Connection id "[redacted connection ID in case]" completed keep alive response. 
2021-01-14 12:36:33.5069 Info Request finished HTTP/1.1 POST http://192.168.2.2:9117/api/v2.0/indexers/broadcasthenet/config application/json 176 - 500 - application/json 1510.7269ms ``

**Comment by Tumtum2814** [comment]
getting the same issue using the Https. I can upload my logs if it's helpful.

**Comment by vember31** [comment]
@Tumtum2814 do you get the same null source parameter error that I do once you turn on enhanced logging?

**Comment by Tumtum2814** [comment]
> 
> 
> @Tumtum2814 do you get the same null source parameter error that I do once you turn on enhanced logging?

I do indeed.
![image](https://user-images.githubusercontent.com/24609930/104785213-ff2f6700-5757-11eb-94ae-59513c282767.png)

**Comment by ilike2burnthing** [comment]
Another API with the same error - https://github.com/Jackett/Jackett/issues/10653

**Comment by zepx** [comment]
I'm currently taking a look into this, but the error from https://github.com/Jackett/Jackett/issues/10817#issue-785631186 and https://github.com/Jackett/Jackett/issues/10817#issuecomment-760407258 appears to be separate problems.

The first error is saying that no results are returned from BTN's end and upon further investigation, it seems like BTN might have removed the general search. I'm trying to confirm this with BTN's staff before any changes can be made. Without the general search capability, the results returned would be very poor.

As for the second error, I cannot replicate it at the moment, so I can't comment on it.

**Comment by seeyabye** [comment]
I'm currently taking a look into this, but the error from https://github.com/Jackett/Jackett/issues/10817#issue-785631186 and https://github.com/Jackett/Jackett/issues/10817#issuecomment-760407258 appears to be separate problems.

The first error is saying that no results are returned from BTN's end and upon further investigation, it seems like BTN might have removed the general search. I'm trying to confirm this with BTN's staff before any changes can be made. Without the general search capability, the results returned would be very poor.

As for the second error, I cannot replicate it at the moment, so I can't comment on it.

**Comment by vember31** [comment]
@seeyabye thanks for the help! I do think they're the same problem... The issue described in the first post is the error I get without enhanced logging on. Once I have enhanced logging on (see my latest post) I have the exact  same error as the one reported by @Tumtum2814 - the null source error.

Thanks for checking it!

**Comment by ngosang** [comment]
None of the Jackett's developers have account in BTN. If someone invites me I can take a look.
It looks like they made changes in the API or website layout. Someone has to take a look at the source code and fix it => https://github.com/Jackett/Jackett/blob/69125add3e6c8c686c318629b65eecad8875494c/src/Jackett.Common/Indexers/BroadcasTheNet.cs

**Comment by seeyabye** [comment]
I just got a reply from the staff and as it seems to be an issue on BTN's end that has been resolved.

@vember31 can you confirm if it's working?

**Comment by vember31** [comment]
@seeyabye yep! All fixed - thank you for reaching out to them!  I'll close out this issue, really appreciate it everyone 😄

**Comment by vember31** [comment]
@seeyabye looks like this issue started happening again this morning after BTN was down for a bit. Guessing they made some API changes and maybe the same thing happened. When you have a moment, would you mind checking with the same staff from before? I'm also happy to do it if you want to message or email me directly for what path to take :) going to leave the github issue closed though since it's probably on the BTN end again. Sonarr BTN integration works fine

**Comment by shakil1819** [comment]
> ### Environment
> **OS**: Ubuntu 16.04
> 
> **.Net Runtime**: .NET Core
> 
> **.Net Version**: Unsure of how to find out :(
> 
> **Jackett Version**: v0.17.261
> 
> **Last Working Jackett Version**: Not version based; any recent version of Jackett will fail. It is / was a change on BTN's side. If it helps, Sonarr's integration with BTN is working still.
> 
> **Are you using a proxy or VPN?** No
> 
> ### Description:
> Either try to add BTN as a tracker in Jackett, or if you have it added already, try testing it. You'll receive this error and be recommended to submit an issue here on Github. BTN made their change yesterday, Jan 11. Errors also show up in the logs, described / shown below.
> 
> ### Logged Error Messages
> The full error stack from the log is here:
> 
> ## Jackett.Common.ExceptionWithConfigData: Testing returned no results! at Jackett.Common.Indexers.BroadcasTheNet.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BroadcasTheNet.cs:line 80 at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
> ### Screenshots
> **Error from the logs:** ![image](https://user-images.githubusercontent.com/17370796/104543126-73e49300-55ea-11eb-8ba3-97e5eace9d73.png)
> 
> **Error received when trying to add BTN as a tracker or test it if already added:** ![image](https://user-images.githubusercontent.com/17370796/104543344-e48baf80-55ea-11eb-848e-80d564c6bfdf.png)

can you please invite me at broadcasthenet please? i have excellent ratios,and top tier trackers reputation

**Comment by ilike2burnthing** [comment]
This isn't an invite forum, don't use it as one.
