### ISSUE TITLE
lepornoinfo: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10856]
query: black bulls
```
lepornoinfo): Error while parsing row '
<tr class="tCenter hl-tr" id="tor_74120">
	<td class="row1">
		<img src="./styles/templates/gray/images/icon_minipost.gif" class="icon1" alt="Post">
	</td>
	<td class="row1 tCenter" title="checked">
		<span class="tor-icon tor-approved">√</span>
	</td>
	<td class="row1">
		<a class="gen" href="tracker.php?f=18">Incest and Taboo</a>
	</td>
	<td class="row1 med tLeft">
		<span title=" (: )"></span>
		<a class="genmed" href="./viewtopic.php?t=73404">
			<b>[PervMom.com / TeamSkeet.co<wbr>m] Lillith Morningstar - Stepmom Helps Me Focus (17.01.21) [2021 г., Big Ass, Big Tits, Black Hair, Blowjob, Boy / Girl, Bra, Casual Wear, Caucasian, Cinematic - Story, Creampie, Curvy, Cute, Dining Room, Doggystyle)</b>
		</a>
	</td>
	<td class="row1">
		<a class="med" href="tracker.php?pid=2445">
			<span title="Uploader" class="colorUploader">PornLover</span>
		</a>
	</td>
	<td class="row1 small nowrap">
		<u>4421440243</u>
		<a class="small tr-dl" title="Download" href="./dl.php?id=73360">4.12&nbsp;GB</a>
		<span title="Magnet">
			<a href="magnet:?xt=urn:btih:d0d4e0b148b7bc9034ebbcb3034fe9bf9c7c1705&amp;tr=https%3A%2F%2Fleporno.info%2Fbt%2Fannounce.php%3Fuk%3DKO721mO3Wj">
				<img src="./styles/images/magnet.png" width="12" height="12" border="0">
			</a>
		</span>
	</td>
	<td class="row1 seedmed" title="Seeders">
		<b>1</b>
	</td>
	<td class="row1 leechmed" title="Leechers">
		<b>0</b>
	</td>
	<td class="row1 small" title="Replies: 0">0</td>
	<td class="row1 small nowrap" style="padding: 1px 3px 2px;" title="Added">
		<u>1610888657</u>
		<p>Yesterday 13:04</p>
		<p>17-Jan-21</p>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="tracker.php?f="], value=18: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522
```

**Comment by ilike2burnthing** [comment]
[v0.17.324](https://github.com/Jackett/Jackett/releases/tag/v0.17.324)

**Comment by ngosang** [comment]
query 720p
```
CardigannIndexer (lepornoinfo): Error while parsing row '
<tr class="tCenter hl-tr" id="tor_82419">
	<td class="row1">
		<img src="./styles/templates/gray/images/icon_minipost.gif" class="icon1" alt="Post">
	</td>
	<td class="row1 tCenter" title="checked">
		<span class="tor-icon tor-approved">√</span>
	</td>
	<td class="row1">
		<a class="gen" href="tracker.php?f=19">Femdom &amp; Strapon</a>
	</td>
	<td class="row1 med tLeft">
		<span title=" (: )"></span>
		<a class="genmed" href="./viewtopic.php?t=81590">
			<b>[BratPrincess<wbr>.us] Goddess Alexandra Snow (Alexandra - Humiliates Her Step Son / 18.10.2013) [2013 г., Femdom, Humiliation,<wbr>
				Brunette, High Heels, Step Son Domination, Sissy, Chastity, 720p, HDRip]</b>
		</a>
	</td>
	<td class="row1">
		<a class="med" href="tracker.php?pid=10">
			<span title="Moderator" class="colorMod">Raneianal</span>
		</a>
	</td>
	<td class="row1 small nowrap">
		<u>602138189</u>
		<a class="small tr-dl" title="Download" href="./dl.php?id=81552">574&nbsp;MB</a>
		<span title="Magnet">
			<a href="magnet:?xt=urn:btih:6cfb94e3cebf1ea1679003b6639feb65ad227540&amp;tr=https%3A%2F%2Fleporno.info%2Fbt%2Fannounce.php%3Fuk%3DKO721mO3Wj">
				<img src="./styles/images/magnet.png" width="12" height="12" border="0">
			</a>
		</span>
	</td>
	<td class="row1 seedmed" title="Seeders">
		<b>1</b>
	</td>
	<td class="row1 leechmed" title="Leechers">
		<b>0</b>
	</td>
	<td class="row1 small" title="Replies: 0">0</td>
	<td class="row1 small nowrap" style="padding: 1px 3px 2px;" title="Added">
		<u>1617820811</u>
		<p>18:40</p>
		<p>7-Apr-21</p>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="tracker.php?f="], value=19: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568
```
