### ISSUE TITLE
subsplease: object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10857]
Related  #10784
@CodeMonkey626 could yo take a look?

Size is always 0. I know the site doesn't provide this info but some tools like Sonarr refuses to download when the size is 0.
Could you add fixed sizes?
480p => 350MB
720p => 700MB
1080p => 1300MB

The error is with these queries
"query": "720p"
"query": "1234abcdf"
```
Jackett.Common.IndexerException: Exception (subsplease): Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.SubsPlease.ParseApiResults(String json) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SubsPlease.cs:line 141
   at Jackett.Common.Indexers.SubsPlease.PerformSearch(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SubsPlease.cs:line 85
   at Jackett.Common.Indexers.SubsPlease.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SubsPlease.cs:line 65
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 659
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 223
```

**Comment by CodeMonkey626** [comment]
Checking...

**Comment by CodeMonkey626** [comment]
Found the null reference, apparently in some cases for certain no result queries their API returns empty array and in other it returns empty string.

In all cases where a resolution is specified, the API is going to return zero results because it's not part of the title or a searchable property. 

In terms of file size, my Sonarr has been more then happy to download files with zero size, Sonarr just doesn't like RSS feeds where the size isn't supplied.

I'm reluctant to do anything that involves trying to manually parse the query  search terms for resolution sizes unless Jackett has existing  functionality for this.

**Comment by CodeMonkey626** [comment]
Fixed the NullReference exception and had the indexer supply a guess at size based on the release resolution using the values provided and 1GB as a fallback. That fixes all the issues identified.

One thing I'm thinking over though is the API will always return no results if you supply a resolution as it only searches on title it appears. I'm wondering if I can make the indexer a bit more clever and search for discrete terms of "480p, 720p, and 1080p", not pass them to the API, but filter the results afterward.

@ngosang does Jackett have any built-in query / search term parsing functionality for resolutions?

**Comment by ngosang** [comment]
Merged, thank you!

> does Jackett have any built-in query / search term parsing functionality for resolutions?

No, but there are several indexers implementing a similar logic for resolutions and years.
You can use regex to match known resolutions in the title, save them for later use and remove from the search term.
Perform the search and parse the results.
Remove results without matching resolution.

Anyway I see this as an enhancement. Most users don't search for a resolution. You can use the filter in the Jackett UI to refine the results by resolution.

**Comment by ilike2burnthing** [comment]
[v0.17.324](https://github.com/Jackett/Jackett/releases/tag/v0.17.324)
