### ISSUE TITLE
yourbittorrent: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10850]
There are errors in categories and in other column:
Empty search
```
CardigannIndexer (yourbittorrent): Error while parsing row '
<tr class="table-default">
	<td style="padding:0 4px" class="c1" onclick="if (!window.__cfRLUnblockHandlers) return false; document.location.href='/movie.html'" data-cf-modified-051479534145467958b98508-=""></td>
	<td colspan="2">
		<a href="http://gdb5z4u.directyb.xyz/torrent/2714445/2021.2z7.html">
			<b>2021</b>
			- Latest Movie</a>
	</td>
	<td class="text-center" style="white-space: nowrap;">
		<a href="http://gdb1z3u.directyb.xyz/torrent/4867969/2021.4z1.html">
			<i class="fas fa-info-square" style="color:red"></i>
		</a><a href="http://gdb1z1u.directyb.xyz/torrent/4893473/2021.9z5.html">
			<i class="fa fa-fw fa-magnet"></i>
		</a>
	</td>
	<td class="text-center">
		<a href="http://gdb4z4u.directyb.xyz/torrent/4552598/2021.4z5.html">275.7 MB</a>
	</td>
	<td class="text-center" "="">
		<a href="http://gdb8z6u.directyb.xyz/torrent/255037/2021.4z6.html">Today</a>
	</td>
	<td class="text-center" style="color:green">
		<a href="http://gdb4z1u.directyb.xyz/torrent/2868014/2021.4z7.html">543</a>
	</td>
	<td class="text-center" style="color:red">
		<a href="http://gdb7z9u.directyb.xyz/torrent/332524/2021.5z5.html">1077</a>
	</td>
	<td class="text-center">
		<picture class="th">
			<source type="image/webp" srcset="https://yourbittorrent.com/images/health6.webp">
			<img src="https://yourbittorrent.com/images/health6.png" class="th" alt="">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), value=movie: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522
```

"query": "silicon valley"
```
CardigannIndexer (yourbittorrent): Error while parsing row '
<tr class="table-default">
	<td style="padding:0 4px" class="c10" onclick="if (!window.__cfRLUnblockHandlers) return false; document.location.href='/other.html'" data-cf-modified-5e3e722829b4d04ac32f7fa3-=""></td>
	<td colspan="2">
		<a href="http://xui6p1z.directyb.xyz/torrent/2183542/silicon+valley.3y4.html">
			<b>Silicon Valley</b>
			- Latest Other</a>
	</td>
	<td class="text-center" style="white-space: nowrap;">
		<a href="http://xui6p6z.directyb.xyz/torrent/4616964/silicon+valley.3y1.html">
			<i class="fas fa-info-square" style="color:red"></i>
		</a><a href="http://xui8p3z.directyb.xyz/torrent/3375436/silicon+valley.2y6.html">
			<i class="fa fa-fw fa-magnet"></i>
		</a>
	</td>
	<td class="text-center">
		<a href="http://xui7p3z.directyb.xyz/torrent/4650430/silicon+valley.5y6.html">822.6 MB</a>
	</td>
	<td class="text-center" "="">
		<a href="http://xui6p2z.directyb.xyz/torrent/2270108/silicon+valley.9y9.html">Today</a>
	</td>
	<td class="text-center" style="color:green">
		<a href="http://xui5p6z.directyb.xyz/torrent/2822261/silicon+valley.2y5.html">540</a>
	</td>
	<td class="text-center" style="color:red">
		<a href="http://xui9p6z.directyb.xyz/torrent/1401718/silicon+valley.3y3.html">1001</a>
	</td>
	<td class="text-center">
		<picture class="th">
			<source type="image/webp" srcset="https://yourbittorrent.com/images/health6.webp">
			<img src="https://yourbittorrent.com/images/health6.png" class="th" alt="">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=size, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522
```

**Comment by ilike2burnthing** [comment]
[v0.17.311](https://github.com/Jackett/Jackett/releases/tag/v0.17.311)
