### ISSUE TITLE
[acgrip] Exception (acgrip): Cannot assign requested address: Cannot assign requested address (acg.rip:443) (Test)

### ISSUE THREAD

**Issue by zx900930** [Jackett/Jackett#10877]
### Environment

**OS**: debian linux docker arm64

**Jackett Version**: v0.17.333

**Are you using a proxy or VPN?** no

### Description

The indexer acg.rip is not working.
You can reproduce this error simply by adding acg.rip indexer and click Test.

### Logged Error Messages
```
Jackett.Common.IndexerException: Exception (acgrip): Cannot assign requested address
 ---> System.Net.Http.HttpRequestException: Cannot assign requested address (acg.rip:443)
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 496
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1271
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 659
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 302
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

```

The indexer acg.rip is online and the dnsresolve on the host server is working correctely. 
Other indexers are working fine.

ping info
```
 ping acg.rip
PING acg.rip(2605:6400:20:c::beef (2605:6400:20:c::beef)) 56 data bytes
64 bytes from 2605:6400:20:c::beef (2605:6400:20:c::beef): icmp_seq=1 ttl=48 time=151 ms
64 bytes from 2605:6400:20:c::beef (2605:6400:20:c::beef): icmp_seq=2 ttl=48 time=151 ms
64 bytes from 2605:6400:20:c::beef (2605:6400:20:c::beef): icmp_seq=3 ttl=48 time=151 ms
64 bytes from 2605:6400:20:c::beef (2605:6400:20:c::beef): icmp_seq=4 ttl=48 time=151 ms
64 bytes from 2605:6400:20:c::beef (2605:6400:20:c::beef): icmp_seq=5 ttl=48 time=151 ms
64 bytes from 2605:6400:20:c::beef (2605:6400:20:c::beef): icmp_seq=6 ttl=48 time=152 ms
^C
--- acg.rip ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 10ms
rtt min/avg/max/mdev = 151.060/151.277/151.501/0.521 ms
```
```
ping4 acg.rip
PING acg.rip (209.141.39.35) 56(84) bytes of data.
64 bytes from acg.kp (209.141.39.35): icmp_seq=1 ttl=51 time=153 ms
64 bytes from acg.kp (209.141.39.35): icmp_seq=2 ttl=51 time=153 ms
64 bytes from acg.kp (209.141.39.35): icmp_seq=3 ttl=51 time=153 ms
64 bytes from acg.kp (209.141.39.35): icmp_seq=4 ttl=51 time=154 ms
64 bytes from acg.kp (209.141.39.35): icmp_seq=5 ttl=51 time=154 ms
64 bytes from acg.kp (209.141.39.35): icmp_seq=6 ttl=51 time=153 ms
^C
--- acg.rip ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 11ms
rtt min/avg/max/mdev = 152.722/153.241/153.719/0.568 ms
```

dig info
```
dig acg.rip

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Debian <<>> acg.rip
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48376
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;acg.rip.                       IN      A

;; ANSWER SECTION:
acg.rip.                300     IN      A       209.141.39.35

;; Query time: 4 msec
;; SERVER: 192.168.1.254#53(192.168.1.254)
;; WHEN: Wed Jan 20 12:11:08 CET 2021
;; MSG SIZE  rcvd: 52
```

**Comment by ilike2burnthing** [comment]
Working ok here. Are those tests being run from within the container?

**Comment by zx900930** [comment]
> Working ok here. Are those tests being run from within the container?

![image](https://user-images.githubusercontent.com/734749/105227752-f973c000-5b61-11eb-9ba0-2ba073515b05.png)
yes the test is inside the container

**Comment by ilike2burnthing** [comment]
Thanks. Can you try changing the DNS of the container (e.g. 1.1.1.1 and 1.0.0.1 or 8.8.8.8 and 8.8.4.4), see if that helps?

Other indexers are working ok?

**Comment by zx900930** [comment]
Those DNS servers(8.8.8.8 8.8.4.4 1.1.1.1 etc) are all returning the same dns response(The IP address is correct but the connection is refused, my IP is not banned by the server and this indexer is not using  an antibot protection like cloudflare)
![image](https://user-images.githubusercontent.com/734749/105242920-9c323b80-5b6e-11eb-98d1-c1ca6199ec4d.png)

Other indexers are working fine
![image](https://user-images.githubusercontent.com/734749/105243220-0e0a8500-5b6f-11eb-84dd-3545ed071cbc.png)

**Comment by ilike2burnthing** [comment]
Using any kind of adblocking solution like pi-hole? If so, you may need to add the site to your whitelist.

Looking at similar issues, changing network mode to host (https://github.com/Jackett/Jackett/issues/7942) and fixing a faulty reverse proxy config (https://github.com/Jackett/Jackett/issues/6690) can be solutions, in case either apply to you.

**Comment by zx900930** [comment]
Switch the network mode from bridge to host might be the solution. I need to test it later.

**Comment by ilike2burnthing** [comment]
Glad you solved it!
