### ISSUE TITLE
Cinemaz/Avistaz always Failed

### ISSUE THREAD

**Issue by Paul5656** [Jackett/Jackett#10884]
**OS**:
Linux

**Jackett Version**:
0.17.333

**Are you using a proxy or VPN?** [yes/no]
No

### Description
Not sure if I'm the only one having this issue but it's been on for months where the indexer is _**always**_ disabled in the *arrs but in Jackett, it works perfectly. So every time I want to search through Radarr, I have to manually test them on the radarr indexers page for it to work again. They work for the duration of the search and then go back to the below message on the Radarr Health page.

```
Indexers unavailable due to failures: Cinemaz |  
-- | --
| Indexers unavailable due to failures for more than 6 hours: Avistaz
```

### Logged Error Messages

Cinemaz
```
Jackett.Common.IndexerException: Exception (cinemaz): Unknown error: {"current_page":1,"data":[],"from":null,"last_page":0,"next_page_url":null,"path":"https:\/\/cinemaz.to\/api\/v1\/jackett\/torrents","per_page":100,"prev_page_url":null,"to":null,"total":0}
 ---> System.Exception: Unknown error: {"current_page":1,"data":[],"from":null,"last_page":0,"next_page_url":null,"path":"https:\/\/cinemaz.to\/api\/v1\/jackett\/torrents","per_page":100,"prev_page_url":null,"to":null,"total":0}
   at Jackett.Common.Indexers.Abstract.AvistazTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs:line 169
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 659
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 427
```

Avistaz

```
Jackett.Common.IndexerException: Exception (avistaz): Unknown error: {"current_page":1,"data":[],"from":null,"last_page":0,"next_page_url":null,"path":"https:\/\/avistaz.to\/api\/v1\/jackett\/torrents","per_page":100,"prev_page_url":null,"to":null,"total":0}
 ---> System.Exception: Unknown error: {"current_page":1,"data":[],"from":null,"last_page":0,"next_page_url":null,"path":"https:\/\/avistaz.to\/api\/v1\/jackett\/torrents","per_page":100,"prev_page_url":null,"to":null,"total":0}
   at Jackett.Common.Indexers.Abstract.AvistazTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs:line 169
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 659
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 427

```

**Comment by ilike2burnthing** [comment]
Try removing the 2 indexers from the *arrs and Jackett, restart the programs, add those indexers back, and see if there's any improvement.

If not, please provide an enhanced log of the issue for either one - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Paul5656** [comment]
Tried...same story.

https://mega.nz/file/oMUGCRJB#XVpZCCrPqyRp_F40DE0fkv0V7Dpy2zQH1M_24PJpobs

**Comment by ilike2burnthing** [comment]
Try accessing the failed link `https://cinemaz.to/api/v1/jackett/torrents?in=1&type=1&imdb=ttREDACTED` in browser (obviously replacing `REDACTED` with the IMDB ID of the relevant film). Post the response.

Also try searching Cinemaz normally for the IMDB ID and film title. Does it give results?

If neither give results, we may need to accommodate for an empty response.

If the site does but the API doesn't, we might need to change something to do with the search parameters (or it could be an issue with the API).

If both give results, the issue is definitely on our end.

**Comment by Paul5656** [comment]
https://cinemaz.to/api/v1/jackett/torrents?in=1&type=1&imdb=ttREDACTED
`Whoops, looks like something went wrong.`

Not sure what u mean 2nd part. From the tracker or from Jackett?
If from inside Jackett both IMDB and Name work.
If from the tracker, I have to go to advanced search to search IMDb because the basic search only searches the title aka keywords, but otherwise IMDb also works.
The search works well, its just it keeps on disconnecting from Sonarr.

**Comment by ilike2burnthing** [comment]
Oh sorry, from the tracker, but it's good to know both, thanks.

Do any IMDB IDs work using the above URL format? I don't have an account, but I just tried `https://cinemaz.to/api/v1/jackett/torrents?in=1&type=1&imdb=tt7286456` (The Joker) and got the same result `Whoops, looks like something went wrong.` I take it you were signed into Cinemaz on the same browser when you tried that?

**Comment by Paul5656** [comment]
Yes, I was signed in. That format gives me errors regardless.

**Comment by ilike2burnthing** [comment]
Thanks.

@ngosang if you still have accounts for these, can you have a look?

**Comment by dsara** [comment]
I am having this same issue and it seems that it's specific to whether or not the imdb entry exists for the tracker in this network of trackers. PrivateHD, AvistaZ, and CinemaZ all have the same issue, but only error out like this when imdb doesn't exist for the tracker. As long as there is an imdb entry for any of these trackers they won't error out. They all give the same error and if you remove the imdb query string parameter from the call they don't fail anymore, which is why testing it and doing manual searches in Jackett always succeed.

**Comment by ilike2burnthing** [comment]
[v0.17.437](https://github.com/Jackett/Jackett/releases/tag/v0.17.437)

**Comment by Paul5656** [comment]
Working perfectly now, thanks for the fix.
