### ISSUE TITLE
Yggtorrent report "not Found no results while trying to browse this tracker"

### ISSUE THREAD

**Issue by Bastien42** [Jackett/Jackett#10892]
### Environment

**OS**: Windows 10 pro 20H2

**.Net Version**: v4.0 / v4 / v3.5 / v3.0 / v2.0.50727

**Jackett Version**: v0.17.337

**Last Working Jackett Version**: v0.17.337

**Are you using a proxy or VPN?** no

### Description

Add YGGtorrent or YGGcookie and test them you should get that error ATM the Tracker and website is up either the main website and the search engine URL 
![YGG uptime](https://user-images.githubusercontent.com/37946663/105414945-740f0f00-5c38-11eb-94d1-4ea6b9e2b2f7.png)
![YGG uptime 2](https://user-images.githubusercontent.com/37946663/105414946-740f0f00-5c38-11eb-8acb-6c0622b7a85d.png)

### Logged Error Messages

```
System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 308
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
The current Jackett version (v0.17.337) should only have the `Site Link` (https://www2.yggtorrent.si/), not the `Search and download URL`.

If you have both and are definitely on v0.17.337, you need to reinstall Jackett. If that doesn't help, remove yggtorrent and yggcookie from Jackett, restart Jackett, and add those indexers again (though I think only yggtorrent works at the moment).

**Comment by Bastien42** [comment]
I actually only have the site link i just pinned those screenshot because YGG uses two different URL that were used before by jackett actually couldn't it be an issue now that jackett doesn't precise the URL for the search engine that maybe why it report no torrent on the tracker or am i missing smth

**Comment by Bastien42** [comment]
okay so i just fixed that myself it's not too obvious but you gotta put that url https://www2.yggtorrent.si/ rather than the main https://ww3.yggtorrent.si/

**Comment by ilike2burnthing** [comment]
Change it to https://www2.yggtorrent.si/

ww3.* has never been used by Jackett

**Comment by ilike2burnthing** [comment]
Jinx 😋
