### ISSUE TITLE
[sharewood] Login failed: No form found on http://www.sharewood.tv/login using form selector form[action$=

### ISSUE THREAD

**Issue by Sirko94** [Jackett/Jackett#10919]
Hello,

I have this message : `Login failed: No form found on http://www.sharewood.tv/login using form selector form[action$="/login"]`

Can you help me please ?

Log : 
```
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on http://www.sharewood.tv/login using form selector form[action$="/login"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 524
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 919
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /Users/runner/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware
```

**Comment by ilike2burnthing** [comment]
Check you can access and log into the site from the same device and IP.

Please provide the information which was originally requested:
```
OS:
.Net Runtime: [.Net-Core/.Net-Framework/Mono]
.Net Version:
Jackett Version:
Last Working Jackett Version:
Are you using a proxy or VPN? [yes/no]
```

**Comment by Sirko94** [comment]
Yes I can acces to the site from the same divice and ip.
OS: MacOs
.Net Runtime: Mono
.Net Version: 3.1.201
Jackett Version: v0.17.348
Last Working Jackett Version: v0.17.348
Are you using a proxy or VPN? no

**Comment by ilike2burnthing** [comment]
Please provide an **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Sirko94** [comment]
Sorry, you can close, I don't know why but it's work now.

Thx for your help.
