### ISSUE TITLE
[pier720] Login failed: Selector

### ISSUE THREAD

**Issue by eoghain** [Jackett/Jackett#10913]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Raspberry Pi OS

**.Net Runtime**: 5.18.0.240

**.Net Version**: 5.18.0.240

**Jackett Version**:  v0.17.348

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** yes

### Description
Tried to add 720pier.

### Logged Error Messages

Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by eoghain** [comment]
I just walked through the chain of Duplicates from here 10913 -> #10621 -> #10424 -> #10218 which was closed as a "Works for me".  Since there are 4 tickets now reporting this same issue I would say that it's not fixed and that this one isn't a duplicate anymore since none of the others actually solved anything.

**Comment by eoghain** [comment]
FYI, here is what the HTML currently looks like:

Not Logged In:
```
<a href="./ucp.php?mode=login&amp;redirect=index.php" title="Login" accesskey="x" role="menuitem">
				<i class="icon fa fa-sign-in" aria-hidden="true"></i><span>Login</span>
			</a>
```

Logged In:
```
<a href="./ucp.php?mode=logout&amp;sid=05c48f32dc02df6912c5acf45ab6128e" title="Logout" accesskey="x" role="menuitem">
								<i class="icon fa fa-sign-out icon-red" aria-hidden="true"></i><span>Logout</span>
							</a>
```
Logged In XPath:
```
//*[@id="username_logged_in"]/div/div/ul/li[4]/a
```
or
```
/html/body/div[1]/div[1]/div[2]/div/ul/li[5]/div/div/ul/li[4]/a
```

**Comment by ilike2burnthing** [comment]
Are you getting the cookie in browser while using the same VPN server?

As was mentioned in the other issues, see https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work particularly the Notes.

**Comment by eoghain** [comment]
Thank you for the reply.  I missed the notes about the VPN, especially since all of the other sites I added in the same way worked.  I do have Jackett running on a headless server and was pulling the cookie from another machine.  I'll correct my mistake, and report if it's still not working.

**Comment by eoghain** [comment]
Ok, I setup a tunnel and verified that my browser and RaspberryPi (where Jackett is running) have the same IP address.  Logged in to 720Pier and grabbed the cookie, and got the same error from Jackett.  I don't know if this is still my problem or if it actually something wrong with Jackett.  Any help would be appreciated.  Is there anyway to get Jackett to output the HTML that it's attempting to parse.  I'm more that willing to troubleshoot this and either fix my own issues or provide any needed information for you to be able to fix it.

Here is the log entry for the failure:
```
Jackett.Common.ExceptionWithConfigData: Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 777
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 920
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket - that will include the HTML dump.

**Comment by eoghain** [comment]
One thing I've noticed when trying to get this working is that 720pier seems to have a JavaScript check in place.  When I attempted to login to get the cookie using elinks from the pi's command line, that was the error it displays.

**Comment by eoghain** [comment]
After reviewing the logs I don't see much that is helpful other than the cookie getting re-set.  Specifically the `phpbb3_h6m7i_u=1;` cookie keeps having it's value reset to 1 instead of keeping the one I entered in the form. The `phpbb3_h6m7i_sid` cookie value also changes, but I'd expect that to change if it's the sessionId I think it is.

**Comment by ilike2burnthing** [comment]
`1` being guest rather than an account. It's working ok here.

Cookie should look something like:
> phpbb3_h6m7i_lang=en; phpbb3_h6m7i_track=tf%3A%28xx%3A%28tal%3A4%3B%29%3B%29%3Bt%3A%28tal%3Axxxxxx%3B%29%3B; phpbb3_h6m7i_u=12345; phpbb3_h6m7i_k=xxxxxxxxxxxxxxxxx; phpbb3_h6m7i_sid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Please provide the enhanced log, just redact your cookies.

Also try it without your VPN to make sure it's not some other issue.

**Comment by eoghain** [comment]
Interesting my `phpbb3_h6m7i_k` cookie is always empty.  The others all seem to populate correctly but that one is always empty.

**Comment by eoghain** [comment]
Ok, so the `phpbb3_h6m7i_k` cookie gets set if I check the remember me box when logging in.  Still didn't work for Jackett though.  I'll get the enhanced logs and post them as soon as I can.
