### ISSUE TITLE
[fouducinema] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by Nokcom** [Jackett/Jackett#10975]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: macOs 10.13.6

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  Jackett Version v0.17.405 

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] yes

### Description

setting : https://fou-du-cinema.net/ 
Fou-Du-Cinema (FdC) is a FRENCH Semi-Private Torrent Tracker for MOVIES / TV / GENERAL

### Logged Error Messages

2021-01-31 09:29:40 | Error | Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 781    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 925    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /Users/runner/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 113    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
-- | -- | --
2021-01-31 09:29:39 | Error | CardigannIndexer (fouducinema): Found captcha during automatic login, aborting
2021-01-31 09:29:26 | Error | Jackett.Common.ExceptionWithConfigData: Error: L'adresse IP que vous utilisez est déjà utilisée par un autre utilisateur! Les comptes doubles ne sont autorisés qu'après consultation de l'équipe.    at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 471    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 688    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 925    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /Users/runner/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 113    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

[Place any relevant error messages you noticed from the logs here.]

1- An error occurred while updating this indexer
Error: L'adresse IP que vous utilisez est déjà utilisée par un autre utilisateur! Les comptes doubles ne sont autorisés qu'après consultation de l'équipe.
Click here to open an issue on GitHub for this indexer.

2-  An error occurred while updating this indexer
Login Failed, got redirected.
Click here to open an issue on GitHub for this indexer.

[log.txt](https://github.com/Jackett/Jackett/files/5899397/log.txt)

### Screenshots

![Capture d’écran 2021-01-31 à 09 42 27](https://user-images.githubusercontent.com/33286549/106378968-f28e4e00-63a8-11eb-92c5-e85035ac9170.png)
![Capture d’écran 2021-01-31 à 09 43 35](https://user-images.githubusercontent.com/33286549/106378969-f326e480-63a8-11eb-8a50-48e89f204c3b.png)

**Comment by ilike2burnthing** [comment]
Try changing your VPN/proxy server

**Comment by Nokcom** [comment]
Bonjour,

J'ai tester et cela me donne le message d’erreur "Login Failed" et je ne parviens pas à l'ajouter, mais cela fonctionne quand je clic sur le lien de Jackett et en direct dans un navigateur web.

Merci

Hello,

I have tested and it gives me the error message 'Login Failed' and I am unable to add it, but it works when I click on Jackett's link and live in a web browser.

Thank you!

**Comment by ilike2burnthing** [comment]
If another user on the site is using the same VPN server, that would cause this issue, so you might just have to find a server not already in use - trial and error.

As a test, try it without any VPN.

**Comment by Nokcom** [comment]
Merci pour l'idée,

Effectivement je n'ai pas penser a désactiver le VPN.

Donc, installation sans VPN et admis dans la liste des tracker, en suite réactivation du VPN et apparemment cela fonctionne bien avec Jackett, Sonarr et Radarr.

Merci
-
Thanks for the idea,

Indeed I did not think of deactivating the VPN.

So, installation without VPN and admitted to the tracker list, then reactivate the VPN and apparently it works well with Jackett, Sonarr and Radarr.

Thank you
