### ISSUE TITLE
[subsplease] Exception (subsplease): The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by DevYukine** [Jackett/Jackett#11034]
SubsPlease is currently in Cloudflares "Under Attack" mode, i've setup FlareSolverr which does work on other trackers (demonoid for example), looking at the logs it does successful return a Cookie but that one seems invalid? not sure if thats a FlareSolverr or Jackett issue tho

### Environment

**OS**: Docker Release

**.Net Runtime**: Docker Release version

**.Net Version**: Docker Release version

**Jackett Version**: https://hub.docker.com/layers/linuxserver/jackett/latest/images/sha256-fd3ed8146b174126b3f917da4691c9c825de316fe3eb5b24159b84eafc07b31e

**Last Working Jackett Version**: None

**Are you using a proxy or VPN?** No

### Description

Try using FlareSolverr on SubsPlease while Cloudflare "Under Attack" mode is active

### Logged Error Messages

```
flaresolverr_1  | 2021-02-08T01:16:15.089Z INFO REQ-32 Incoming request: POST /v1
flaresolverr_1  | 2021-02-08T01:16:15.090Z INFO REQ-32 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://subsplease.org//api/?f=latest&tz=America%2FNew_York","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
flaresolverr_1  | 2021-02-08T01:16:15.509Z INFO REQ-32 Cloudflare detected
flaresolverr_1  | 2021-02-08T01:16:19.593Z INFO REQ-32 Successful response in 4.504 s
jackett_1       | 02-08 02:16:19 Error On attempt 1 downloading from SubsPlease: The cookies provided by FlareSolverr are not valid FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
jackett_1       |    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
jackett_1       |    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
jackett_1       |    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
jackett_1       |    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
jackett_1       |    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 496 jackett_1       |    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 457
```

**Comment by ilike2burnthing** [comment]
The site isn't showing any use of CloudFlare at the moment and is working fine for me in Jackett. Is this still an issue for you or was it just temporary?

**Comment by DevYukine** [comment]
They are still behind Cloudflare but the "Under Attack" mode went off again so there is no cloudflare challange, i would keep this open until it happens next time so this can be investigated 👍

**Comment by ilike2burnthing** [comment]
I'll add the `More information needed` label, which will close the the issue after 7 days if you haven't responded. If the issue occurs again after that time you can reopen the issue.
