### ISSUE TITLE
[partis] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by pinkflozd** [Jackett/Jackett#11116]
### Environment

**OS**:
Arch Linux
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
Mono
**.Net Version**:
6.10.0
**Jackett Version**:
0.17.546
**Last Working Jackett Version**:
don't know
**Are you using a proxy or VPN?** [yes/no]
no
### Description
Add partis tracker

### Logged Error Messages

```
Feb 17 00:00:37 bazdara.com jackett[2294149]: 02-17 00:00:37 Error System.NullReferenceException: Object reference not set to an instance of an object.
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Common.Indexers.Partis.<>c__DisplayClass8_0.<ApplyConfiguration>b__0() in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Common/Indexers/Partis.cs:line 128
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Common/Indexers/BaseIndexer.cs:line 240
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Common.Indexers.Partis.ApplyConfiguration(JToken configJson) in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Common/Indexers/Partis.cs:line 124
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 System.NullReferenceException: Object reference not>
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Common.Indexers.Partis.<>c__DisplayClass8_0.<ApplyConfiguration>b__0() in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Common/Indexers/Partis.cs:line 128
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Common/Indexers/BaseIndexer.cs:line 240
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Common.Indexers.Partis.ApplyConfiguration(JToken configJson) in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Common/Indexers/Partis.cs:line 124
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 17 00:00:37 bazdara.com jackett[2294149]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /var/www/media/pinkflozd/jackett/src/Jackett-0.17.546/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Working ok here. Are you able to access the site in browser from the same device and IP? If not, you may need to use a proxy or VPN. If you can, and other indexers are working, then upload and **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by pinkflozd** [comment]
Thanks, this helped me narrow it down! Closing This!
Seems that it was a error because i was using a 4to6 tunnel, with the endpoint not in Slovenia.
