### ISSUE TITLE
[yggcookie] Exception (yggcookie): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid (Test)

### ISSUE THREAD

**Issue by harry4152** [Jackett/Jackett#11127]
### Environment

**OS**: Debian GNU/Linux 10 (buster) arm64

**.Net Runtime**: Mono version 5.18.0.240

**Jackett Version**: Version v0.17.562 

**Last Working Jackett Version**: Version v0.17.562 

**Are you using a proxy or VPN?** : No

### Description

Jacket is running directly on my Debian host. FlareSolverr is runing within a docker on the same exact host. This is the latest version as of today v1.2.3

Both application share the same ip Address. I followed the steps provided in a previous issue #10828 to get the ip from within the FlareSolverr container.

Other indexers which are using CloudFlare are getting the same error (tried with pirateiro)

FlareSolverr is up and running and do not provided any error message :

```json
{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1613642054530,"endTimestamp":1613642054530,"version":"v1.2.3"}
```
While trying to connect to YGG the following log is provided by FlareSolverr by doing `docker logs flaresolverr`

```
2021-02-18T09:54:14.530Z INFO REQ-7 FlareSolverr is ready!
2021-02-18T10:00:47.060Z INFO REQ-8 Incoming request: POST /v1
2021-02-18T10:00:47.061Z INFO REQ-8 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-02-18T10:00:48.180Z INFO REQ-8 Cloudflare detected
2021-02-18T10:00:55.151Z INFO REQ-8 Successful response in 8.091 s
```

### Logged Error Messages

```
Exception (yggcookie): The cookies provided by FlareSolverr are not valid: 
The cookies provided by FlareSolverr are not valid
```

```
Jackett.Common.IndexerException: Exception (yggcookie): The cookies provided by FlareSolverr are not valid
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 184
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 492
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1271
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 380
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 388
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 656
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```
### Comments

Thank you in advance for your time !

Cheers

**Comment by ilike2burnthing** [comment]
Can you confirm with another indexer which requires FlareSolverr, e.g. 7Torrents? Pirateiro has its own long standing issues with Cloudflare - https://github.com/Jackett/Jackett/issues/7973

Is this the first time you've tried using FlareSolverr, or was it previously working?

**Comment by HpNoTiQ56** [comment]
Same problem here.
Was working before on ygg (3 days ago so after ygg updates).
I've tried updating Jackett and Flaresolverr with no sucess. Can submit logs if needed.

**Comment by Pranksous** [comment]
Same problem, worked 1 week ago, since 3 days, i have this issues. Updated Jackett and reinstalled Flaresolverr done, nothing changed.

> Can you confirm with another indexer which requires FlareSolverr, e.g. 7Torrents? Pirateiro has its own long standing issues with Cloudflare.

-> does not work either

thanking you

**Comment by Lily971** [comment]
I also have the same issues, tried with other indexers and no change

**Comment by harry4152** [comment]
> 
> 
> Can you confirm with another indexer which requires FlareSolverr, e.g. 7Torrents? Pirateiro has its own long standing issues with Cloudflare - #7973
> 
> Is this the first time you've tried using FlareSolverr, or was it previously working?

Hello ! Just tried with 7 Torrent and i have the exact same issue !

**Comment by ilike2burnthing** [comment]
What are you using as your FlareSolverr API URL? If you visit that URL in browser, what do you get?

YGG wasn't using Cloudflare DDoS Protection again until a few days ago, hence why it was all working before.

**Comment by harry4152** [comment]
I'm using the following url in jackett : http://127.0.0.1:8191. If i go to this link i get the following answer :

![image](https://user-images.githubusercontent.com/79253378/108432237-57202880-7244-11eb-9722-eeaea35e5907.png)

All my services are hosted on the same machine !

**Comment by Seidel76** [comment]
The same here... And 7torrents works with FlareSolverr.

**Comment by ilike2burnthing** [comment]
@Seidel76 if other indexers which use Cloudflare DDoS Protection are working, then try YGGtorrent instead of YGGcookie. If it still doesn't work, open a separate issue here.

Everyone else, if no other indexers which use Cloudflare DDoS Protection are working, your API URL is set correctly (see above), and Jackett, FlareSolverr, and your browser all have the same public IP, then open a new issue over at https://github.com/FlareSolverr/FlareSolverr/issues (after checking if someone already has), and then post a link to it here.

Unless you're adding additional information, don't post 'same here' comments on that new issue, just use a thumbs up reaction on the post to show that you're also affected, and subscribe for notifications if you want to keep track of it.

**Comment by harry4152** [comment]
Thank you @ilike2burnthing , i've open an issue on FlareSolverr https://github.com/FlareSolverr/FlareSolverr/issues/89

I'll keep this issue updated for those who have the same problem !

Have a nice day :)

**Comment by havocked** [comment]
Hi!

I have the same problem but I think I know how to solve it:

When using YGGCookie indexer, you specify the User Agent. This User agent **needs** to be the one that comes with the cookies. Why? Cloudfare configure its __cfduid to be linked with the user agent although they are going to depreciate it. (source: https://blog.cloudflare.com/deprecating-cfduid-cookie/)

Let's say I configure the YGGCookie indexer in Jackett with the following userAgent:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36`

Now, when we look at FlareSolverr logs when testing YGGCookie I get the following:

```
> Incoming request: POST /v1
> Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www4.yggtorrent.li/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"} 

> Cloudflare detected

> Successful response in 5.718 s
```

Notice the userAgent value `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

It should have been the one I've specified in YGGCookie indexer configuration.

So looking into the code:
https://github.com/Jackett/Jackett/blob/bf8cae6a48839f9fb42c2e30a9f5832667b072c5/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs#L134

It looks like its detecting the settings but fall into the condition of EmulateBrowser == true, and it doesn't take the right user agent.

What do you think?

**Comment by Sevea** [comment]
Same here...don't work with ygg

**Comment by ilike2burnthing** [comment]
@havocked I'll linked to your comment on https://github.com/FlareSolverr/FlareSolverr/issues/89 so ngosang can take a look.

**Comment by havocked** [comment]
![image](https://user-images.githubusercontent.com/7999585/108627940-519b2c00-7458-11eb-8257-f65c9a609962.jpeg)
