### ISSUE TITLE
[yggtorrent] Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (XX.XXX.XXX.XX:8191)

### ISSUE THREAD

**Issue by Samhot** [Jackett/Jackett#11122]
### Environment

**OS**: Debian

**.Net Runtime**: Mono

**.Net Version**:

**Jackett Version**: v0.17.562

**Last Working Jackett Version**: v0.17.562

**Are you using a proxy or VPN?** no

### Description

Jackett is runing on docker-compose with traefik, FlareSolverr is runing on docker-compose too. Both containers are up to date.
FlareSolverr is ok.

![image](https://user-images.githubusercontent.com/7148311/108194024-699c4400-7116-11eb-8671-d37b68d155ff.png)

 Everything used to work perfectly till YggTorrent DNS migration last week. The indexer configuration in Jackett is updated correctly.

```yml
  flaresolverr:
  # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - xxxxxx-web

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    hostname: jackett
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.jackett.rule=Host(`jackett.xxxxxxxxxx.fr`)"
       - "traefik.http.routers.jackett.entrypoints=websecure"
       - "traefik.port=9117"
       - "traefik.http.routers.jackett.tls.certresolver=myresolver"
    environment:
       - TZ=Europe/Paris
       - PUID=1000
       - PGID=1000
    ports:
       - "9117:9117"
    expose:
       - 9117
    volumes:
       - /home/xxxxxx/Jackett/config:/config
       - /home/xxxxxx/Jackett/downloads:/downloads
    networks:
       - xxxxxx-web
```

### Logged Error Messages
```
Jackett.Common.IndexerException: Exception (yggtorrent): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (XX.XXX.XXX.XX:8191)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (XX.XXX.XXX.XX:8191)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 184
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable1 data, Dictionary2 headers, String rawbody, Nullable1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 492
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1271
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 380
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 388
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 656
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```
### Screenshots

[REMOVED - displayed user IP]

**Comment by mathchab** [comment]
Same here!

**Comment by ilike2burnthing** [comment]
What are you using as your FlareSolverr API URL?

Do any other indexers which require FlareSolverr work (examples [here](https://github.com/Jackett/Jackett/search?l=YAML&q=flaresolverr))?

**Comment by Samhot** [comment]
As my FlareSolverr API URL I use my IP address with port 8191. When I access it directly in my browser everything looks good
![image](https://user-images.githubusercontent.com/7148311/108324586-62ce0980-71c8-11eb-8028-a521ae799e8d.png)

I don't use any other indexer so I don't know if they would work...

**Comment by ilike2burnthing** [comment]
Try 7Torrents as a test.

Try switching the API URL to http://jackett:8191

**Comment by ramuskay** [comment]
Same problem here.
When I add 7Torrents it displayed the same error
What do you mean when you said switching the API URL ?

**Comment by ilike2burnthing** [comment]
As in changing what you typed in the Jackett's settings. That solution is specific to this Docker setup.

**Comment by ramuskay** [comment]
Ok i can confirm that it resolved the issue. Thank you!

**Comment by Samhot** [comment]
I'm not sure to understand what you mean by changing the API URL in Jackett's settings to "http://jackett:8191". Is it the "FlareSolverr API URL" ? If yes it does not work for me

**Comment by ilike2burnthing** [comment]
@ramuskay given that you got it working, can you take a look the OP and see if there's anything in the compose file which differs from yours, and which might be causing the issue (or post your for comparison)? I would guess ports.

**Comment by ramuskay** [comment]
Here my docker-compose : 

`jackett:
  image: linuxserver/jackett
  container_name: jackett
  volumes:
    - ./src/jackett/config:/config
    - ./src/jackett/downloads:/downloads
  networks:
     static-network-bis:
      ipv4_address: 192.168.20.19
  restart: unless-stopped
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.jackett.rule=Host(`jackett.XXXXXXX`)"
   - "traefik.http.routers.jackett.entrypoints=web"
   - "traefik.http.routers.jackett.middlewares=https-redirect@file"
   - "traefik.http.routers.jackett-secure.middlewares=security@file, compression@file"
   - "traefik.http.routers.jackett-secure.rule=Host(`jackett.XXXXXXXXX`)"
   - "traefik.http.routers.jackett-secure.entrypoints=websecure"
   - "traefik.http.routers.jackett-secure.tls.certresolver=myresolver"
   - "traefik.port=9117"
   - 'traefik.http.routers.jackett-secure.middlewares=authelia'
   - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.XXXXXXXXXX/'
   - "com.centurylinklabs.watchtower.enable=true"

flaresolverr:
  # DockerHub mirror flaresolverr/flaresolverr:latest
  image: ghcr.io/flaresolverr/flaresolverr:latest
  container_name: flaresolverr
  networks:
     static-network-bis:
      ipv4_address: 192.168.20.22
  environment:
    # Used to change the verbosity of the logging
    - LOG_LEVEL=info
    # Enables hcaptcha-solver => https://github.com/JimmyLaurent/hcaptcha-solver
    - CAPTCHA_SOLVER=hcaptcha-solver
    # Enables CaptchaHarvester => https://github.com/NoahCardoza/CaptchaHarvester
    #- CAPTCHA_SOLVER=harvester
    #- HARVESTER_ENDPOINT=https://127.0.0.1:5000/token
  ports:
    - 8191:8191
  restart: unless-stopped`

**Comment by ramuskay** [comment]
Here my docker-compose :

```
jackett:
  image: linuxserver/jackett
  container_name: jackett
  volumes:
    - ./src/jackett/config:/config
    - ./src/jackett/downloads:/downloads
  networks:
     static-network-bis:
      ipv4_address: XXXXXXXXX
  restart: unless-stopped
  labels:
   - "traefik.enable=true"
   - "traefik.http.routers.jackett.rule=Host(`jackett.XXXXXXX`)"
   - "traefik.http.routers.jackett.entrypoints=web"
   - "traefik.http.routers.jackett.middlewares=https-redirect@file"
   - "traefik.http.routers.jackett-secure.middlewares=security@file, compression@file"
   - "traefik.http.routers.jackett-secure.rule=Host(`jackett.XXXXXXXXX`)"
   - "traefik.http.routers.jackett-secure.entrypoints=websecure"
   - "traefik.http.routers.jackett-secure.tls.certresolver=myresolver"
   - "traefik.port=9117"
   - 'traefik.http.routers.jackett-secure.middlewares=authelia'
   - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.XXXXXXXXXX/'
   - "com.centurylinklabs.watchtower.enable=true"

flaresolverr:
  # DockerHub mirror flaresolverr/flaresolverr:latest
  image: ghcr.io/flaresolverr/flaresolverr:latest
  container_name: flaresolverr
  networks:
     static-network-bis:
      ipv4_address: XXXXXXXX
  environment:
    # Used to change the verbosity of the logging
    - LOG_LEVEL=info
    # Enables hcaptcha-solver => https://github.com/JimmyLaurent/hcaptcha-solver
    - CAPTCHA_SOLVER=hcaptcha-solver
    # Enables CaptchaHarvester => https://github.com/NoahCardoza/CaptchaHarvester
    #- CAPTCHA_SOLVER=harvester
    #- HARVESTER_ENDPOINT=https://127.0.0.1:5000/token
  ports:
    - 8191:8191
  restart: unless-stopped
```
