### ISSUE TITLE
[rarbg] Could not find releases from this URL (Config)

### ISSUE THREAD

**Issue by asiajason** [Jackett/Jackett#11141]
Attempting to add "Rarbg" indexer.

### Environment

**OS**: Windows 10 10.0.19042.0

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**Environment Version**:  5.0.3 (C:\ProgramData\Jackett\)

**Jackett Version**:   v0.17.562

**Are you using a proxy or VPN?** [yes/no] ExpressVPN

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages
`

System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.RarBG.<>c.<ApplyConfiguration>b__10_0() in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 127
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 240
   at Jackett.Common.Indexers.RarBG.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 126
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

`

**Comment by asiajason** [comment]
Hi, This has been marked as duplicate of 11020, but:

11020 was duplicate of #10869
<https://github.com/Jackett/Jackett/issues/10869>
while #10869 is duplicate of #10631
<https://github.com/Jackett/Jackett/issues/10631>.
while #10631 <https://github.com/Jackett/Jackett/issues/10631> was closed
due to no available info on the bug track.

I've given info on the track for you to follow up on, unlike the other.

I would suggest keeping this one open, unless there's been another issue
not mentioned above.

Regards,

**Comment by ilike2burnthing** [comment]
RARBG's API is constantly up and down, you may need to try multiple times before it works.
