### ISSUE TITLE
[theempire] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by newhollandaus** [Jackett/Jackett#11167]
### Environment

**OS**:
Binhex Docker on Unriad

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
v0.17.570

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
Yes VPN, VPN works fine in browser

### Description

An error occurred while updating this indexer
Login Failed, got redirected.
Click here to open an issue on GitHub for this indexer.

### Logged Error Messages

```
Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /tmp/makepkg/jackett/src/Jackett-0.17.570/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 767
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /tmp/makepkg/jackett/src/Jackett-0.17.570/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 920
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /tmp/makepkg/jackett/src/Jackett-0.17.570/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /tmp/makepkg/jackett/src/Jackett-0.17.570/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Do you have account privileges on TheEmpire to use a VPN? Without them you can be banned.

Are you using the same VPN server for Jackett as you do for your browser?
