### ISSUE TITLE
[torrentheaven] Exception (torrentheaven): Input string was not in a correct format.: Parse error (Test)

### ISSUE THREAD

**Issue by SkalCore** [Jackett/Jackett#11172]
### Environment

**OS**: docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.17.584

**Last Working Jackett Version**: an very old Version from mid 2020

**Are you using a proxy or VPN?** [no]

### Description

logged in, Running Test, then an Error message appear: 

An error occurred while testing this indexer
Exception (torrentheaven): Input string was not in a correct format.: Parse error

### Logged Error Messages
```
Jackett.Common.IndexerException: Exception (torrentheaven): Input string was not in a correct format.
 ---> System.Exception: Parse error
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jackett.Common.Indexers.TorrentHeaven.PerformQuery(TorznabQuery query)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 682
   at Jackett.Common.Indexers.TorrentHeaven.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentHeaven.cs:line 266
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 390
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 659
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
When was the last time you used TorrentHeaven in the `very old [Jackett] version from mid 2020`? Last week or mid 2020?

Are you able to login to and search on the site in browser from the same IP?

**Comment by ilike2burnthing** [comment]
@HaraldWeber are you having the same issue?

**Comment by SkalCore** [comment]
> When was the last time you used TorrentHeaven in the very old [Jackett] version from mid 2020? Last week or mid 2020?
  middle of january

> Are you able to login to and search on the site in browser from the same IP?
unable to login, clared cookies and changed pw, still the same error message: "An error occurred while updating this indexer
Exception (torrentheaven): Input string was not in a correct format.: Parse error"

**Comment by ilike2burnthing** [comment]
I meant logging into the site itself, but if you're able to change the password I guess you can. No special characters in your password, and it's not overly long?

I take it other indexers are working fine?

Please provide an **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by SkalCore** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/6042868/log.txt)

here is my log. hope everything is fine and help you

**Comment by ilike2burnthing** [comment]
Looks like you're logged in fine, and the site is returning results, Jackett just isn't able to identify them.

Just need to wait on Harald being able to confirm the issue (so likely a change to the site), and make the necessary updates, or if they don't have the same issue, it's possibly due to your account settings for the site layout have affected things.

**Comment by HaraldWeber** [comment]
Hi
sorry for the late answer. I'm using Version v0.17.611 and everything works like expected.
Maybe you have changed the default layout in the Layout Manager?

**Comment by SkalCore** [comment]
i tried many thins, delete all cookies, create a new user profile in FireFox/Chrome...changed Layout on TH to Black&White, tried a private Tab...nothing works
Tried my Username and diffent (wrong) pass, this was noticed by TH. Counted down. In Jackett this Info text with wrong pass is shown: 
> The string did not match the expected pattern.``
`[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://newheaven.nl/"
  },
  {
    "id": "username",
    "type": "inputstring",
    "name": "Username",
    "value": "####"
  },
  {
    "id": "password",
    "type": "inputstring",
    "name": "Password",
    "value": "CfDJ8FRKf2SPuqFCtPmajuyF_WnWP1zM9knTmjw0dAgFJ0C4cYkLo0eWEOUbPqGvoX2_8z8OKmOideGJI8w2O_G6CXQbeDAoIhEsmAzTJii7Ht_Z88AJgUjU2hCnEcP14bjYcw"
  },
  {
    "id": "captchatext",
    "type": "inputstring",
    "name": "Captcha Text",
    "value": "KKH92M"
  },
  {
    "id": "captchacookie",
    "type": "hiddendata",
    "name": "Captcha Cookie",
    "value": "PHPSESSID=njh048qu6jj2uhnnq7giadsod0;"
  },
  {
    "id": "",
    "type": "displayinfo",
    "name": "",
    "value": null
  },
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "uid=29708; pass=fec16043467413fe010d1c8c9ed13e79;"
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": "Exception (torrentheaven): Input string was not in a correct format.: Parse error"`

**Comment by ilike2burnthing** [comment]
It seems like the layout is the issue, so you'll need to restore all layout settings to default. Once you have it working again, if you want you can play about with them one by one to find out what specifically was causing the issue.

**Comment by SkalCore** [comment]
I give up ... I've tested all the layouts ... nothing works. I tested a new Docker container with a jacket without traefik ... no success either ... I don't know what to do next

**Comment by SkalCore** [comment]
my last try gave my now the error 

> `Didn't get a user/pass cookie`

**Comment by HaraldWeber** [comment]
My Layout Settings

![image](https://user-images.githubusercontent.com/1271056/109828080-9aaf6500-7c3c-11eb-9dcd-59c7d8964c3a.png)

**Comment by SkalCore** [comment]
unbelievable...after all that it works....many thanks @HaraldWeber @ilike2burnthing
