### ISSUE TITLE
Access to the path '/var/lib/jackett' is denied.

### ISSUE THREAD

**Issue by bphd** [Jackett/Jackett#11264]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Arch

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] dotnet-runtime-preview 

**.Net Version**: 6.0.0.sdk100+preview.1.21103.13-2

**Jackett Version**: v0.17.655

**Last Working Jackett Version**: never

**Are you using a proxy or VPN?** [yes/**no**]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

```sh
systemctl start jackett.service
```

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

```
systemd[1]: jackett.service: Scheduled restart job, restart counter is at 22.
systemd[1]: Condition check resulted in systemd-cron minutely script service being skipped.
systemd[1]: Reached target systemd-cron minutely target.
systemd[1]: Starting [Cron] "* * * * * cd /home/user/process-wallpaper && ./updateWallpaper.sh > /tmp/wallpaper.log 2>&1"...
systemd[1]: Stopped Jackett Service.
audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jackett comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jackett comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
systemd[1]: Started Jackett Service.
audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jackett comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
systemd[1]: Stopped target systemd-cron minutely target.
kernel: kauditd_printk_skb: 1 callbacks suppressed
kernel: audit: type=1130 audit(1615150263.459:395): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jackett comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
kernel: audit: type=1131 audit(1615150263.459:396): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jackett comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
kernel: audit: type=1130 audit(1615150263.459:397): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jackett comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
systemd[1]: cron-user-user-0.service: Succeeded.
systemd[1]: Finished [Cron] "* * * * * cd /home/user/process-wallpaper && ./updateWallpaper.sh > /tmp/wallpaper.log 2>&1".
audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=cron-user-user-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=cron-user-user-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
kernel: audit: type=1130 audit(1615150263.666:398): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=cron-user-user-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
kernel: audit: type=1131 audit(1615150263.666:399): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=cron-user-user-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
jackett[7038]: 03-07 21:51:03 Info Starting Jackett v0.17.655
jackett[7038]: 03-07 21:51:03 Info Jackett Data will be stored in: /var/lib/jackett
jackett[7038]: Unhandled exception. System.Exception: Could not create settings directory. Access to the path '/var/lib/jackett' is denied.
jackett[7038]:    at Jackett.Common.Services.ConfigurationService.CreateOrMigrateSettings() in /home/user/.cache/paru/clone/jackett/src/Jackett-0.17.655/src/Jackett.Common/Services/ConfigurationService.cs:line 52
jackett[7038]:    at Jackett.Common.Services.ConfigurationService..ctor(ISerializeService s, IProcessService p, Logger l, RuntimeSettings settings) in /home/user/.cache/paru/clone/jackett/src/Jackett-0.17.655/src/Jackett.Common/Services/ConfigurationService.cs:line 29
jackett[7038]:    at Jackett.Server.Program.Main(String[] args) in /home/user/.cache/paru/clone/jackett/src/Jackett-0.17.655/src/Jackett.Server/Program.cs:line 78
audit[7038]: ANOM_ABEND auid=4294967295 uid=951 gid=951 ses=4294967295 pid=7038 comm="jackett" exe="/usr/lib/jackett/jackett" sig=6 res=1
kernel: audit: type=1701 audit(1615150263.712:400): auid=4294967295 uid=951 gid=951 ses=4294967295 pid=7038 comm="jackett" exe="/usr/lib/jackett/jackett" sig=6 res=1
audit: BPF prog-id=75 op=LOAD
systemd[1]: Started Process Core Dump (PID 7050/UID 0).
audit: BPF prog-id=76 op=LOAD
audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@24-7050-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
kernel: audit: type=1334 audit(1615150263.719:401): prog-id=75 op=LOAD
kernel: audit: type=1334 audit(1615150263.719:402): prog-id=76 op=LOAD
kernel: audit: type=1130 audit(1615150263.719:403): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@24-7050-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
systemd-coredump[7051]: [🡕] Process 7038 (jackett) of user 951 dumped core.
                        
                        Stack trace of thread 7038:
                        #0  0x00007f12afe6aef5 raise (libc.so.6 + 0x3cef5)
                        #1  0x00007f12afe54862 abort (libc.so.6 + 0x26862)
                        #2  0x00007f12af7542be n/a (libcoreclr.so + 0x4e52be)
                        #3  0x00007f12af75420c n/a (libcoreclr.so + 0x4e520c)
                        #4  0x00007f12af53647d n/a (libcoreclr.so + 0x2c747d)
                        #5  0x00007f12af536506 n/a (libcoreclr.so + 0x2c7506)
                        #6  0x00007f12af494c6b n/a (libcoreclr.so + 0x225c6b)
                        #7  0x00007f1237d52fc4 n/a (n/a + 0x0)
                        #8  0x00007f1237d527b1 n/a (n/a + 0x0)
                        #9  0x00007f12360f9f23 n/a (n/a + 0x0)
                        #10 0x00007f12af5d8c97 n/a (libcoreclr.so + 0x369c97)
                        #11 0x00007f12af4278ab n/a (libcoreclr.so + 0x1b88ab)
                        #12 0x00007f12af2fafea n/a (libcoreclr.so + 0x8bfea)
                        #13 0x00007f12af2fb339 n/a (libcoreclr.so + 0x8c339)
                        #14 0x00007f12af339783 n/a (libcoreclr.so + 0xca783)
                        #15 0x00007f12af2e42ad coreclr_execute_assembly (libcoreclr.so + 0x752ad)
                        #16 0x00007f12af982c1a n/a (libhostpolicy.so + 0x17c1a)
                        #17 0x00007f12af983081 n/a (libhostpolicy.so + 0x18081)
                        #18 0x00007f12af983abd corehost_main (libhostpolicy.so + 0x18abd)
                        #19 0x00007f12afbe3422 n/a (libhostfxr.so + 0x1d422)
                        #20 0x00007f12afbe1b7b n/a (libhostfxr.so + 0x1bb7b)
                        #21 0x00007f12afbde434 hostfxr_main_startupinfo (libhostfxr.so + 0x18434)
                        #22 0x000056470a211415 n/a (jackett + 0x11415)
                        #23 0x000056470a211940 n/a (jackett + 0x11940)
                        #24 0x00007f12afe55b25 __libc_start_main (libc.so.6 + 0x27b25)
                        #25 0x000056470a204f8a n/a (jackett + 0x4f8a)
                        
                        Stack trace of thread 7046:
                        #0  0x00007f12b03539ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                        #1  0x00007f12b034d574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
                        #2  0x00007f12af74c416 n/a (libcoreclr.so + 0x4dd416)
                        #3  0x00007f12af74c0e1 n/a (libcoreclr.so + 0x4dd0e1)
                        #4  0x00007f12af751279 n/a (libcoreclr.so + 0x4e2279)
                        #5  0x00007f12af40fd9d n/a (libcoreclr.so + 0x1a0d9d)
                        #6  0x00007f12af40fc75 n/a (libcoreclr.so + 0x1a0c75)
                        #7  0x00007f12af7577ae n/a (libcoreclr.so + 0x4e87ae)
                        #8  0x00007f12b0347299 start_thread (libpthread.so.0 + 0x9299)
                        #9  0x00007f12aff2d053 __clone (libc.so.6 + 0xff053)
                        
                        Stack trace of thread 7042:
                        #0  0x00007f12aff2237f __poll (libc.so.6 + 0xf437f)
                        #1  0x00007f12af64703e n/a (libcoreclr.so + 0x3d803e)
                        #2  0x00007f12af488aa4 n/a (libcoreclr.so + 0x219aa4)
                        #3  0x00007f12af44ea57 n/a (libcoreclr.so + 0x1dfa57)
                        #4  0x00007f12af7577ae n/a (libcoreclr.so + 0x4e87ae)
                        #5  0x00007f12b0347299 start_thread (libpthread.so.0 + 0x9299)
                        #6  0x00007f12aff2d053 __clone (libc.so.6 + 0xff053)
                        
                        Stack trace of thread 7044:
                        #0  0x00007f12b03539ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                        #1  0x00007f12b034d260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                        #2  0x00007f12af74c42b n/a (libcoreclr.so + 0x4dd42b)
                        #3  0x00007f12af74c0e1 n/a (libcoreclr.so + 0x4dd0e1)
                        #4  0x00007f12af750ac2 n/a (libcoreclr.so + 0x4e1ac2)
                        #5  0x00007f12af750dd1 n/a (libcoreclr.so + 0x4e1dd1)
                        #6  0x00007f12af63df69 n/a (libcoreclr.so + 0x3cef69)
                        #7  0x00007f12af63ddd5 n/a (libcoreclr.so + 0x3cedd5)
                        #8  0x00007f12af63db1d n/a (libcoreclr.so + 0x3ceb1d)
                        #9  0x00007f12af7577ae n/a (libcoreclr.so + 0x4e87ae)
                        #10 0x00007f12b0347299 start_thread (libpthread.so.0 + 0x9299)
                        #11 0x00007f12aff2d053 __clone (libc.so.6 + 0xff053)
                        
                        Stack trace of thread 7043:
                        #0  0x00007f12b0350fe4 __open (libpthread.so.0 + 0x12fe4)
                        #1  0x00007f12af6475cf n/a (libcoreclr.so + 0x3d85cf)
                        #2  0x00007f12af640688 n/a (libcoreclr.so + 0x3d1688)
                        #3  0x00007f12af63f7c9 n/a (libcoreclr.so + 0x3d07c9)
                        #4  0x00007f12af7577ae n/a (libcoreclr.so + 0x4e87ae)
                        #5  0x00007f12b0347299 start_thread (libpthread.so.0 + 0x9299)
                        #6  0x00007f12aff2d053 __clone (libc.so.6 + 0xff053)
                        
                        Stack trace of thread 7047:
                        #0  0x00007f12b03539ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                        #1  0x00007f12b034d574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
                        #2  0x00007f12af74c416 n/a (libcoreclr.so + 0x4dd416)
                        #3  0x00007f12af74c0e1 n/a (libcoreclr.so + 0x4dd0e1)
                        #4  0x00007f12af750ac2 n/a (libcoreclr.so + 0x4e1ac2)
                        #5  0x00007f12af750c84 n/a (libcoreclr.so + 0x4e1c84)
                        #6  0x00007f12af507a62 n/a (libcoreclr.so + 0x298a62)
                        #7  0x00007f12af40d36d n/a (libcoreclr.so + 0x19e36d)
                        #8  0x00007f12af7577ae n/a (libcoreclr.so + 0x4e87ae)
                        #9  0x00007f12b0347299 start_thread (libpthread.so.0 + 0x9299)
                        #10 0x00007f12aff2d053 __clone (libc.so.6 + 0xff053)
                        
                        Stack trace of thread 7048:
                        #0  0x00007f12b03539ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                        #1  0x00007f12b034d574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
                        #2  0x00007f12af74c416 n/a (libcoreclr.so + 0x4dd416)
                        #3  0x00007f12af74c0e1 n/a (libcoreclr.so + 0x4dd0e1)
                        #4  0x00007f12af751279 n/a (libcoreclr.so + 0x4e2279)
                        #5  0x00007f12af4754af n/a (libcoreclr.so + 0x2064af)
                        #6  0x00007f12af40f484 n/a (libcoreclr.so + 0x1a0484)
                        #7  0x00007f12af7577ae n/a (libcoreclr.so + 0x4e87ae)
                        #8  0x00007f12b0347299 start_thread (libpthread.so.0 + 0x9299)
                        #9  0x00007f12aff2d053 __clone (libc.so.6 + 0xff053)
                        
                        Stack trace of thread 7045:
                        #0  0x00007f12b03539ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                        #1  0x00007f12b034d574 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf574)
                        #2  0x00007f12af74c416 n/a (libcoreclr.so + 0x4dd416)
                        #3  0x00007f12af74c0e1 n/a (libcoreclr.so + 0x4dd0e1)
                        #4  0x00007f12af750ac2 n/a (libcoreclr.so + 0x4e1ac2)
                        #5  0x00007f12af750cf9 n/a (libcoreclr.so + 0x4e1cf9)
                        #6  0x00007f12af50707a n/a (libcoreclr.so + 0x29807a)
                        #7  0x00007f12af46c64f n/a (libcoreclr.so + 0x1fd64f)
                        #8  0x00007f12af46c807 n/a (libcoreclr.so + 0x1fd807)
                        #9  0x00007f12af3f05fa n/a (libcoreclr.so + 0x1815fa)
                        #10 0x00007f12af3f0cad n/a (libcoreclr.so + 0x181cad)
                        #11 0x00007f12af46c9f8 n/a (libcoreclr.so + 0x1fd9f8)
                        #12 0x00007f12af7577ae n/a (libcoreclr.so + 0x4e87ae)
                        #13 0x00007f12b0347299 start_thread (libpthread.so.0 + 0x9299)
                        #14 0x00007f12aff2d053 __clone (libc.so.6 + 0xff053)
                        
                        Stack trace of thread 7041:
                        #0  0x00007f12aff2237f __poll (libc.so.6 + 0xf437f)
                        #1  0x00007f12af74c75e n/a (libcoreclr.so + 0x4dd75e)
                        #2  0x00007f12af74e0ef n/a (libcoreclr.so + 0x4df0ef)
                        #3  0x00007f12af7577ae n/a (libcoreclr.so + 0x4e87ae)
                        #4  0x00007f12b0347299 start_thread (libpthread.so.0 + 0x9299)
                        #5  0x00007f12aff2d053 __clone (libc.so.6 + 0xff053)
systemd[1]: systemd-coredump@24-7050-0.service: Succeeded.
audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@24-7050-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
systemd[1]: jackett.service: Main process exited, code=dumped, status=6/ABRT
systemd[1]: jackett.service: Failed with result 'core-dump'.
audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jackett comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
kernel: audit: type=1131 audit(1615150263.896:404): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@24-7050-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
audit: BPF prog-id=76 op=UNLOAD
audit: BPF prog-id=75 op=UNLOAD
```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
I'm not a linux/arch expert, but since no one has provided any suggestions, and presuming you have a .config folder in your home directory, then based on the log you provided:
Try using the `-d /home/user/.config/Jackett` or `--DataFolder="/home/user/.config/Jackett" in your systemd jackett start up profile, to point Jackett to using a data folder that the system has default read/write access to.

**Comment by ilike2burnthing** [comment]
If this is still an issue please comment and reopen.
