### ISSUE TITLE
Download from YGG fails with a 404

### ISSUE THREAD

**Issue by BancarelValentin** [Jackett/Jackett#11311]
### Environment

**OS**: Docker

All latest version

### Description

When trying to download from ygg (via radarr, sonnar or even jackett UI) the link to the torrent seems wrong. In radarr this result in a `Getting release from indexer failed` error. In my radarr logs i have the stacktrace  belox.

From Jackett UI with a different torrent, i get rediirected to another 404 url: `https://jackett.vba.ovh/dl/yggcookie/?jackett_apikey=o68mf1xnlxbjdpc4ni21ci0dak0762lv&path=Q2ZESjhJNi01R0t2aHZsSm5ubFFaQThEMEFBdU5LTHR0WGdWMkZCLXM4aXp1YkF3elYxTTJ4V3llTS1IVHFOSmZNWXhlREJwTjdtMkhpRDc0T2ltbTJRdm5TVDZqaUNoUng0bVpJb282QnRiQ0YybDlSbnlYSmdqR1JtTmRrcjV1U2NMNVZNLThEWklYNl9jQkVPcGZycFZYNnBfaW8tdnBuek5mN0hCUF82N3d0XzBKZ3RKdlprUTNnRkw2X0RLQXJLc3lB&file=Parasite+2019+MULTi+VFi+1080p+BluRay+E-AC3+x265-Winks`

### Logged Error Messages

```
2021-3-14 00:36:46.0|Warn|HttpClient|HTTP Error - Res: [GET] https://jackett.vba.ovh/dl/yggcookie/?jackett_apikey=(removed)&path=Q2ZESjhJNi01R0t2aHZsSm5ubFFaQThEMEFDMEE4clYybDM1OW55ZTc1eU55Ul9RUGVQVzl3azFQUHY5ZDkyMndnMy1sb2NnUzNNMThsa3BIcktBVkthMXQ3OTkzb2tmU29kUjczSzloaEc1M2g4aU1IWTQtX2k1TWdhVnI4enlpQmRmSTFpSklGTFVyZHJSLWxmNTh3bmtsMm5XRHZBNEhyV2g2Q29QazJ2Uko0NEhRUWJndk1pN0NiSTZleTBaNm90SmJR&file=Parasite+(2019)+MULTi+%5BVFF%2CCoreen%5D+WEBrip+1080p+x265+EAC3+AAC-JiHeff+(Gisaengchung): 404.NotFound
2021-3-14 00:36:46.0|Error|QBittorrent|Downloading torrent file for movie 'Parasite (2019) MULTi [VFF,Coreen] WEBrip 1080p x265 EAC3 AAC-JiHeff (Gisaengchung)' failed since it no longer exists (https://jackett.vba.ovh/dl/yggcookie/?jackett_apikey=(removed)&path=Q2ZESjhJNi01R0t2aHZsSm5ubFFaQThEMEFDMEE4clYybDM1OW55ZTc1eU55Ul9RUGVQVzl3azFQUHY5ZDkyMndnMy1sb2NnUzNNMThsa3BIcktBVkthMXQ3OTkzb2tmU29kUjczSzloaEc1M2g4aU1IWTQtX2k1TWdhVnI4enlpQmRmSTFpSklGTFVyZHJSLWxmNTh3bmtsMm5XRHZBNEhyV2g2Q29QazJ2Uko0NEhRUWJndk1pN0NiSTZleTBaNm90SmJR&file=Parasite+(2019)+MULTi+%5BVFF%2CCoreen%5D+WEBrip+1080p+x265+EAC3+AAC-JiHeff+(Gisaengchung))

[v3.0.2.4552] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://jackett.vba.ovh/dl/yggcookie/?jackett_apikey=(removed)&path=Q2ZESjhJNi01R0t2aHZsSm5ubFFaQThEMEFDMEE4clYybDM1OW55ZTc1eU55Ul9RUGVQVzl3azFQUHY5ZDkyMndnMy1sb2NnUzNNMThsa3BIcktBVkthMXQ3OTkzb2tmU29kUjczSzloaEc1M2g4aU1IWTQtX2k1TWdhVnI4enlpQmRmSTFpSklGTFVyZHJSLWxmNTh3bmtsMm5XRHZBNEhyV2g2Q29QazJ2Uko0NEhRUWJndk1pN0NiSTZleTBaNm90SmJR&file=Parasite+(2019)+MULTi+%5BVFF%2CCoreen%5D+WEBrip+1080p+x265+EAC3+AAC-JiHeff+(Gisaengchung)]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 135



2021-3-14 00:36:46.0|Error|ReleaseModule|Downloading torrent failed

[v3.0.2.4552] NzbDrone.Core.Exceptions.ReleaseUnavailableException: Downloading torrent failed
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://jackett.vba.ovh/dl/yggcookie/?jackett_apikey=(removed)&path=Q2ZESjhJNi01R0t2aHZsSm5ubFFaQThEMEFDMEE4clYybDM1OW55ZTc1eU55Ul9RUGVQVzl3azFQUHY5ZDkyMndnMy1sb2NnUzNNMThsa3BIcktBVkthMXQ3OTkzb2tmU29kUjczSzloaEc1M2g4aU1IWTQtX2k1TWdhVnI4enlpQmRmSTFpSklGTFVyZHJSLWxmNTh3bmtsMm5XRHZBNEhyV2g2Q29QazJ2Uko0NEhRUWJndk1pN0NiSTZleTBaNm90SmJR&file=Parasite+(2019)+MULTi+%5BVFF%2CCoreen%5D+WEBrip+1080p+x265+EAC3+AAC-JiHeff+(Gisaengchung)]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 96
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 135

   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteMovie, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 170
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 123
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 73
   at Radarr.Api.V3.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in D:\a\1\s\src\Radarr.Api.V3\Indexers\ReleaseModule.cs:line 84
```

**Comment by BancarelValentin** [comment]
I haven't noticed the `since it no longer exists` part of the error. That's why i thought it differs from https://github.com/Jackett/Jackett/issues/10655. But I will go over ther.

**Comment by PleXi00** [comment]
Mate, your jackett.vba.ovh is publish on internet without restriction

**Comment by ilike2burnthing** [comment]
Removed now, but @BancarelValentin you should really add an admin password if your Jackett is going to be externally accessible, and given how long it's been up, reset your Redacted API key.

**Comment by BancarelValentin** [comment]
Thanks a lot @PleXi00 and @ilike2burnthing ! I once had a password on my Jackett and must have forget to set it back after some reinstall ! Still a dumb move from me; but thanks to you too !

To be clear; the problem was that I had my jackett url in the issue description and it was not password protected ? @PleXi00 proceeded to paste it in his comment so @ilike2burnthing removed it from both the issue description and the comment section ?

**Comment by ilike2burnthing** [comment]
Yes, that is correct.
