### ISSUE TITLE
 Exception (tracker): Specified method is not supported.

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#11328]
seeing many public/semi/private indexers fail after 0.17.724
Public trackers:
7torrents, anirena, btdb, btdigg, btsow, cpasbienclone, dmhy, epizod, exttorrents, frozenlayer, idope, limetorrents, mactorrents, magnet4you, myportclub, onejav, pirateiro, rutor, skytorrents.to, tjangto, torrent4you, torrent9, torrent9clone, torrentkitty, torrentmax, torrentproject, torrentqq, torrentsir, torrentwhiz, torrentz2k, zetorrents.
Private trackers:
52pt, abtorrent, aidoru!online, amigoshareclub, beitai, bithorlo, bitspyder, bittorrentfiles, bitturk, boxingtorrents, brasiltracker, cartoonchaos, cinemamovies_zt, crazyhd, crazyspirits, crnaberza, dariustracker, darkshadow, desitorrents, ebookparadijs, filmpaleis, finvip, galeriens, gaytorrent.ru, gigatorrents, girotorrent, greekdiamond, haidan, hdme, hdtime, 
hdzone, hellastz, lastfiles, learnflakes, lechaudron, majomparade, mesevilag, mnv, musiekfabriek, netcosmo, oshenpt, p2pbg, 720pier, proaudiotorrents, pterclub, ptmsg, puurhollands, scenepalace, scenerush, siambit, sportscult, teamhd, teamos, teracod, theaudioscene, theleachzone, tjupt, torrentturk, torrentbd, torrentccf, torrentlt, totallykids, turkseed, turktorrents, uhdbits, wdt, ydypt, zamunda.net
Semi-Private trackers:
bootytape, demonoid, exkinoray, ilcorsaroblu, ivtorrent, kinorun, mvgroupmain, nethd, prostylex, rustorka, torrentdownload, torrentslocal, yggtorrent

 with
```
Jackett.Common.IndexerException: Exception (zetorrents): Specified method is not supported.
 ---> System.NotSupportedException: Specified method is not supported.
   at Jackett.Common.Indexers.CardigannIndexer.GetBaseTemplateVariables() in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 241
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1150
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 381
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 724
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\Services\IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.Test() in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

related to PR #11104

**Comment by garfield69** [comment]
@XYZJR  can you look into this, is it related to #11104 ? CardigannIndexer seems to be impacted, probably in this area of code
https://github.com/Jackett/Jackett/blob/eaf0513605c3f8e982c36617ca43555f2ac7a5e4/src/Jackett.Common/Indexers/CardigannIndexer.cs#L223-L244

**Comment by XYZJR** [comment]
My lunch break is in a few hours. I'll take a look then.

**Comment by XYZJR** [comment]
With #11104 I changed this original code:
`CheckboxItem checkbox => checkbox.Values,
                    BoolItem boolItem => variables[boolItem.Value ? ".True" : ".False"],
                    SelectItem selectItem => selectItem.Value,
                    StringItem stringItem => stringItem.Value,
                    // Throw exception here to match original functionality.
                    // Currently this will only throw for ImageItem.
                    _ => throw new NotSupportedException()`

What we're hitting against now are `DisplayInfoConfigurationItem` and `DisplayImageConfigurationItem`, these are throwing the exception because they're not in the switch. I'm trying to find out if I can add them to the switch without any impact to the rest of the code.

**Comment by SkalCore** [comment]
using docker, manually switched back to Version v0.17.710, this Version works

**Comment by garfield69** [comment]
v0.17.728
