### ISSUE TITLE
[yggtorrent] The operation was canceled. (Config)

### ISSUE THREAD

**Issue by TechaY** [Jackett/Jackett#11341]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Synology - Docker - Linuxserver

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 

**Last Working Jackett Version**: 

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

- Unable to add YGG torrent.
- Flaresolverr is running, latest version,
- I was abble to add YGG torrent few days ago without problem. Today my test in Radarr failed. Same in Jackett. Since i delete YGG in Jackett i can't add it anymore. 

Thanks.

### Logged Error Messages
`

  | System.OperationCanceledException: The operation was canceled.    at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 184    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 559    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 560    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 965    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
-- | --

`

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
YGGTorrent works for me on my win 10. @ilike2burnthing ?

**Comment by garfield69** [comment]
@TechaY  please access the Jackett dashboard and scroll to the bottom and report the Jackett version.

**Comment by TechaY** [comment]
@garfield69 Sorry, i forgot to paste my Jackette version ...

Version v0.17.728

I was the same problem with my last version. I  updated Jackett Few hours ago in order to see if the problem was there.

(sorry for my english).

**Comment by garfield69** [comment]
Are you using FlareSolverr with Jackett, and is FlareSolverr configured and working?
Do other French indexers work for you?

**Comment by TechaY** [comment]
@garfield69 Yes iam using FlareSloverr (screenshot)

Other french indexer in Jackett : C pas bien clone ; Sharewood ; Torrent9
![Capture d’écran 2021-03-18 à 00 51 12](https://user-images.githubusercontent.com/4441707/111553329-6e3f3100-8784-11eb-898b-28d14ef95259.png)

**Comment by ilike2burnthing** [comment]
Sorry for the delay, was catching up on what I'd missed earlier (that looked like fun).

Working fine here with Docker Jacket v0.17.728 on my NAS. Can remove, re-add, and search with both yggtorrent and yggcookie.

If you look at FlareSolverr's log after the failed attempt to add YGG, does it show a request being made for YGG?

Can you log into YGG in browser?

**Comment by TechaY** [comment]
@ilike2burnthing i posted FlareSolverr's screenshot ;)

**Comment by TechaY** [comment]
Sorry I misunderstand. How i can go to the Flaresolver Log ?

**Comment by ilike2burnthing** [comment]
I'm not familiar with Synology's DiskStation Manager, but try following the instructions in the `If you successfully start a container but it stops unexpectedly or does not function properly` section of https://www.synology.com/en-us/knowledgebase/DSM/tutorial/Virtualization/How_can_I_debug_and_fix_common_Docker_container_issues

**Comment by TechaY** [comment]
`When i try to open YGG windows config, i have to wait maybe 2 min or more before windows appear. (is to normal ?). 
When i try to validate YGG windows config in order to add this indexer, i have to wait 1 min maybe more before error message. 

In ssh with command docker logs --follow flaresolverr 
No logs was add when i tried to add YGG

`> flaresolverr@1.2.3 start
> node ./dist/index.js

2021-03-17T23:16:47.377Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191
2021-03-17T23:47:37.309Z INFO REQ-1 Incoming request: GET /
2021-03-17T23:47:37.310Z INFO REQ-1 Successful response in 0.001 s
2021-03-17T23:47:37.310Z INFO REQ-1 FlareSolverr is ready!`

I only can see this log

**Comment by ilike2burnthing** [comment]
Add 7torrents to Jackett and run a test. It should require FlareSolverr and appear in your logs.

If so (and YGG isn't) then we know the issue lies with either Jackett or your setup, not FlareSolverr.

**Comment by TechaY** [comment]
is it strange. I have no logs... still the same even if i run test on 7torrents

**Comment by TechaY** [comment]
```
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
```
@ilike2burnthing Is it ok for you ?

**Comment by ilike2burnthing** [comment]
Yea, that looks fine. If it still doesn't work, you can simplify your environment and ports:
```
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    ports:
      - "8191:8191"
```

Was the 7torrents test successful, even though it didn't appear in the FlareSolverr logs?

**Comment by TechaY** [comment]
Ok thanks, i simplified the code.

Before delete FlareSolverr, 7torrents test was ok. 
After delete FlareSolverr, 7torrents test was logicaly not ok (screenshot)
Now i just re add Flaresolver and test is still not ok....

It was the same with YGG. The first time i add it, everything was ok (test). I didn't check directly beacause i didn't use radarr just after...

```
Jackett.Common.IndexerException: Exception (7torrents): The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1317
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 391
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 391
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 727
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```


![Capture d’écran 2021-03-18 à 01 49 16](https://user-images.githubusercontent.com/4441707/111557813-ae56e180-878d-11eb-83d6-36e7e9ae4a3c.png)

**Comment by ilike2burnthing** [comment]
If you access http://192.168.1.30:8191 in browser, what do you get?

**Comment by TechaY** [comment]
@ilike2burnthing 

![Capture d’écran 2021-03-18 à 00 51 12](https://user-images.githubusercontent.com/4441707/111558637-72bd1700-878f-11eb-828a-09f75754ee14.png)

**Comment by ilike2burnthing** [comment]
Well that's annoying.

Try replacing the FlareSolver API URL in Jackett with http://flaresolverr:8191 (that won't work in browser), apply settings, and test 7torrents again.

There was an issue a while back which found changing the network mode from host to bridge (or the other way round, I forget) for Jackett on Synology worked for them as well.

**Comment by TechaY** [comment]
@ilike2burnthing 

with  http://flaresolverr:8191 
7torrents : test ok ! 
YGG : test failure (screeshot)

![Capture d’écran 2021-03-18 à 02 30 37](https://user-images.githubusercontent.com/4441707/111560202-4d7dd800-8792-11eb-91b8-bac48ccb9fd9.png)

**Comment by TechaY** [comment]
@ilike2burnthing **EDIT** !

When i add 7torrents, the first test was ok. but now : 

![Capture d’écran 2021-03-18 à 02 34 35](https://user-images.githubusercontent.com/4441707/111560411-b49b8c80-8792-11eb-89cf-d4fe3387969f.png)

**Comment by ilike2burnthing** [comment]
Try changing the network mode of the containers and try both http://192.168.1.30:8191/ and http://flaresolverr:8191/

**Comment by hot22shot** [comment]
Hi, I had the same issue (in #11340) I solved it by configuring the flaresolverr true container IP in jackett configuration.
For me it is something like 172.17.0.x in my bridge network.

**Comment by TechaY** [comment]
@ilike2burnthing @hot22shot @garfield69 

All my container are in Host mode. I was sure to be in host mode for FlareSolverr but no... without _network_mode: host_ Brigde mode was by default. 
I can't access right now to Jackett (the only docker app, i can't acess with my domain name, reverse proxy doesn't work.. don't know why). I did all the change with ssh but i have to wait to access to my internal network for running Jackett. I'am sure the problem was there. 

I will tell you soon if everything is back to normal.

Thanks a lot !!

**Comment by TechaY** [comment]
Indeed it was the Bridge mode that was the problem!  Thank you so much for your help ! 

One last question. What is the difference between YGGtorrent and YGGtorrent cookie? is it useful to use both? 
If you have other FR indexers that work well, I'm interested! 

Thanks again

**Comment by ilike2burnthing** [comment]
One uses login credentials, the other cookies. Currently, while the site uses Cloudflare DDoS Protection, downloading doesn't work with YGGcookie, so use YGGtorrent. When they were using captcha challenges, YGGcookie was the only one that worked.
