### ISSUE TITLE
movietorrent: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11359]
```
CardigannIndexer (movietorrent): Error while parsing row '
<article class="post-1896 type-post format-standard has-post-thumbnail   listing-item listing-item-grid listing-item-grid-1 main-term-53">
	<div class="item-inner">
		<div class="featured clearfix">
			<div class="term-badges floated">
				<span class="term-badge term-53">
					<a href="https://movietorrent.co/web-series-movies-download/">Web Series</a>
				</span>
			</div>
			<a alt="Sacred Games Full Web Series Season 02 Download 2019 – Hindi HD" title="Sacred Games Full Web Series Season 02 Download 2019 – Hindi 720p" data-src="https://movietorrent.co/wp-content/uploads/2019/08/Sacred-Games-Full-Web-Series-Season-02-Download-2019-–-Hindi-HD-357x210.jpg" data-bs-srcset="{&quot;baseurl&quot;:&quot;https:\/\/movietorrent.co\/wp-content\/uploads\/2019\/08\/&quot;,&quot;sizes&quot;:{&quot;210&quot;:&quot;Sacred-Games-Full-Web-Series-Season-02-Download-2019-\u2013-Hindi-HD-210x136.jpg&quot;,&quot;279&quot;:&quot;Sacred-Games-Full-Web-Series-Season-02-Download-2019-\u2013-Hindi-HD-279x220.jpg&quot;,&quot;357&quot;:&quot;Sacred-Games-Full-Web-Series-Season-02-Download-2019-\u2013-Hindi-HD-357x210.jpg&quot;,&quot;620&quot;:&quot;Sacred-Games-Full-Web-Series-Season-02-Download-2019-\u2013-Hindi-HD.jpg&quot;}}" class="img-holder" href="https://movietorrent.co/sacred-games-full-hindi-series-season-02-download-2019-hindi-720p/"></a>
		</div>
		<h2 class="title">
			<a href="https://movietorrent.co/sacred-games-full-hindi-series-season-02-download-2019-hindi-720p/" class="post-title post-url">
				Sacred Games Full Web Series Season 02 Download 2019 – Hindi 720p
			</a>
		</h2>
		<div class="post-meta">
			<a href="https://movietorrent.co/author/movieadmin/" title="Browse Author Articles" class="post-author-a">
				<i class="post-author author">
					Movies
				</i>
			</a>
			<span class="time">
				<time class="post-published updated" datetime="2020-04-26T04:53:20+00:00">Apr 26, 2020</time>
			</span>
		</div>
	</div>
</article>':

System.Exception: Error while parsing field=category, selector=span.term-badge, value=53: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568

CardigannIndexer (movietorrent): Error while parsing row '
<article class="post-6671 type-post format-standard has-post-thumbnail   listing-item listing-item-grid listing-item-grid-1 main-term-59">
	<div class="item-inner">
		<div class="featured clearfix">
			<div class="term-badges floated">
				<span class="term-badge term-59">
					<a href="https://movietorrent.co/2019-movies-download/">2019</a>
				</span>
			</div>
			<a alt="First Look of Movie Naukar Vahuti Da 2020 Poster" title="Naukar Vahuti Da Full Movie Download 2020 Punjabi 720p" data-src="https://movietorrent.co/wp-content/uploads/2020/05/First-Look-of-Movie-Naukar-Vahuti-Da-2020-Poster-357x210.jpg" data-bs-srcset="{&quot;baseurl&quot;:&quot;https:\/\/movietorrent.co\/wp-content\/uploads\/2020\/05\/&quot;,&quot;sizes&quot;:{&quot;210&quot;:&quot;First-Look-of-Movie-Naukar-Vahuti-Da-2020-Poster-210x136.jpg&quot;,&quot;279&quot;:&quot;First-Look-of-Movie-Naukar-Vahuti-Da-2020-Poster-279x220.jpg&quot;,&quot;357&quot;:&quot;First-Look-of-Movie-Naukar-Vahuti-Da-2020-Poster-357x210.jpg&quot;,&quot;640&quot;:&quot;First-Look-of-Movie-Naukar-Vahuti-Da-2020-Poster.jpg&quot;}}" class="img-holder" href="https://movietorrent.co/naukar-vahuti-da-full-movie-download-2020-punjabi-720p/"></a>
		</div>
		<h2 class="title">
			<a href="https://movietorrent.co/naukar-vahuti-da-full-movie-download-2020-punjabi-720p/" class="post-title post-url">
				Naukar Vahuti Da Full Movie Download 2020 Punjabi 720p
			</a>
		</h2>
		<div class="post-meta">
			<a href="https://movietorrent.co/author/movieadmin/" title="Browse Author Articles" class="post-author-a">
				<i class="post-author author">
					Movies
				</i>
			</a>
			<span class="time">
				<time class="post-published updated" datetime="2020-05-28T09:54:07+00:00">May 28, 2020</time>
			</span>
		</div>
	</div>
</article>':

System.Exception: Error while parsing field=category, selector=span.term-badge, value=59: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568

CardigannIndexer (movietorrent): Error while parsing row '
<article class="post-5402 type-post format-standard has-post-thumbnail   listing-item listing-item-grid listing-item-grid-1 main-term-8758">
	<div class="item-inner">
		<div class="featured clearfix">
			<div class="term-badges floated">
				<span class="term-badge term-8758">
					<a href="https://movietorrent.co/2020-magnet-full-movies-download/">2020</a>
				</span>
			</div>
			<a alt="First Look of Movie Dheet Patangey 2020 Poster" title="Dheet Patangey Full Movie Magnet Download 2020 – Hindi 720p" data-src="https://movietorrent.co/wp-content/uploads/2020/03/First-Look-of-Movie-Dheet-Patangey-2020-Poster-357x210.png" data-bs-srcset="{&quot;baseurl&quot;:&quot;https:\/\/movietorrent.co\/wp-content\/uploads\/2020\/03\/&quot;,&quot;sizes&quot;:{&quot;210&quot;:&quot;First-Look-of-Movie-Dheet-Patangey-2020-Poster-210x136.png&quot;,&quot;279&quot;:&quot;First-Look-of-Movie-Dheet-Patangey-2020-Poster-279x220.png&quot;,&quot;357&quot;:&quot;First-Look-of-Movie-Dheet-Patangey-2020-Poster-357x210.png&quot;,&quot;500&quot;:&quot;First-Look-of-Movie-Dheet-Patangey-2020-Poster.png&quot;}}" class="img-holder" href="https://movietorrent.co/dheet-patangey-full-movie-download-magnet-2020-hindi-720p/"></a>
		</div>
		<h2 class="title">
			<a href="https://movietorrent.co/dheet-patangey-full-movie-download-magnet-2020-hindi-720p/" class="post-title post-url">
				Dheet Patangey Full Movie Magnet Download 2020 – Hindi 720p
			</a>
		</h2>
		<div class="post-meta">
			<a href="https://movietorrent.co/author/movieadmin/" title="Browse Author Articles" class="post-author-a">
				<i class="post-author author">
					Movies
				</i>
			</a>
			<span class="time">
				<time class="post-published updated" datetime="2020-05-28T12:40:19+00:00">May 28, 2020</time>
			</span>
		</div>
	</div>
</article>':

System.Exception: Error while parsing field=category, selector=span.term-badge, value=8758: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568
```

**Comment by ngosang** [comment]
```
CardigannIndexer (movietorrent): Error while parsing row '
<article class="post-1724 type-post format-standard has-post-thumbnail   listing-item listing-item-grid listing-item-grid-1 main-term-36">
	<div class="item-inner">
		<div class="featured clearfix">
			<div class="term-badges floated">
				<span class="term-badge term-36">
					<a href="https://movietorrent.co/religious-movies-download/">Religious</a>
				</span>
			</div>
			<a alt="Arjun Patiala Movie First Poster" title="Arjun Patiala Full Movie Download 2019 – Punjabi HD" data-src="https://movietorrent.co/wp-content/uploads/2019/07/Arjun-Patiala-Movie-First-Poster-357x210.jpg" data-bs-srcset="{&quot;baseurl&quot;:&quot;https:\/\/movietorrent.co\/wp-content\/uploads\/2019\/07\/&quot;,&quot;sizes&quot;:{&quot;210&quot;:&quot;Arjun-Patiala-Movie-First-Poster-210x136.jpg&quot;,&quot;279&quot;:&quot;Arjun-Patiala-Movie-First-Poster-279x220.jpg&quot;,&quot;357&quot;:&quot;Arjun-Patiala-Movie-First-Poster-357x210.jpg&quot;,&quot;500&quot;:&quot;Arjun-Patiala-Movie-First-Poster.jpg&quot;}}" class="img-holder" href="https://movietorrent.co/arjun-patiala-full-movie-download-2019-punjabi-bb/"></a>
		</div>
		<h2 class="title">
			<a href="https://movietorrent.co/arjun-patiala-full-movie-download-2019-punjabi-bb/" class="post-title post-url">
				Arjun Patiala Full Movie Download 2019 – Punjabi HD
			</a>
		</h2>
		<div class="post-meta">
			<a href="https://movietorrent.co/author/movieadmin/" title="Browse Author Articles" class="post-author-a">
				<i class="post-author author">
					Movies
				</i>
			</a>
			<span class="time">
				<time class="post-published updated" datetime="2019-07-27T15:53:14+00:00">Jul 27, 2019</time>
			</span>
		</div>
	</div>
</article>':

System.Exception: Error while parsing field=category, selector=span.term-badge, value=36: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568


CardigannIndexer (movietorrent): Error while parsing row '
<article class="post-6182 type-post format-standard has-post-thumbnail   listing-item listing-item-grid listing-item-grid-1 main-term-14">
	<div class="item-inner">
		<div class="featured clearfix">
			<div class="term-badges floated">
				<span class="term-badge term-14">
					<a href="https://movietorrent.co/comedy-movies-download/">Comedy</a>
				</span>
			</div>
			<a alt="First Look of Movie Poster Girlfriend Chor 2020 Hindi TV Series Season 01" title="Girlfriend Chor Full Season 1 Hindi Web Series Download 2020 HD" data-src="https://movietorrent.co/wp-content/uploads/2020/04/First-Look-of-Movie-Poster-Girlfriend-Chor-2020-Hindi-TV-Series-Season-01-357x210.jpg" data-bs-srcset="{&quot;baseurl&quot;:&quot;https:\/\/movietorrent.co\/wp-content\/uploads\/2020\/04\/&quot;,&quot;sizes&quot;:{&quot;210&quot;:&quot;First-Look-of-Movie-Poster-Girlfriend-Chor-2020-Hindi-TV-Series-Season-01-210x136.jpg&quot;,&quot;279&quot;:&quot;First-Look-of-Movie-Poster-Girlfriend-Chor-2020-Hindi-TV-Series-Season-01-279x220.jpg&quot;,&quot;357&quot;:&quot;First-Look-of-Movie-Poster-Girlfriend-Chor-2020-Hindi-TV-Series-Season-01-357x210.jpg&quot;,&quot;750&quot;:&quot;First-Look-of-Movie-Poster-Girlfriend-Chor-2020-Hindi-TV-Series-Season-01-750x430.jpg&quot;,&quot;833&quot;:&quot;First-Look-of-Movie-Poster-Girlfriend-Chor-2020-Hindi-TV-Series-Season-01.jpg&quot;}}" class="img-holder" href="https://movietorrent.co/girlfriend-chor-full-season-1-hindi-web-series-download-2020-hd/"></a>
		</div>
		<h2 class="title">
			<a href="https://movietorrent.co/girlfriend-chor-full-season-1-hindi-web-series-download-2020-hd/" class="post-title post-url">
				Girlfriend Chor Full Season 1 Hindi Web Series Download 2020 HD
			</a>
		</h2>
		<div class="post-meta">
			<a href="https://movietorrent.co/author/movieadmin/" title="Browse Author Articles" class="post-author-a">
				<i class="post-author author">
					Movies
				</i>
			</a>
			<span class="time">
				<time class="post-published updated" datetime="2020-04-17T10:55:54+00:00">Apr 17, 2020</time>
			</span>
		</div>
	</div>
</article>':

System.Exception: Error while parsing field=category, selector=span.term-badge, value=14: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568
```
