### ISSUE TITLE
object reference not set to an instance of an object error - IPtorrents [Windows]

### ISSUE THREAD

**Issue by crimsonking19** [Jackett/Jackett#11358]
**Environment**
OS: Windows Server 2012 R2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] 4.8

**.Net Version**: 4.8

**Jackett Version:** v0.17.743

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN**? no

**Description**

Hi, i am currently using the latest version of Jackett for Windows (v0.17.743).  The tracker i am using is IPtorrents.  For some reason I have been getting the following error quite a bit. Not sure what the issue is?

**Logged Error Messages**

```
Jackett.Common.IndexerException: Exception (iptorrents): Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass7_0.<get_RetryPolicy>b__2(DelegateResult`1 exception, TimeSpan timeSpan, Context context) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 464
   at Polly.AsyncRetryTResultSyntax.<>c__DisplayClass22_0`1.<<WaitAndRetryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 535
   at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\IPTorrents.cs:line 204
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 381
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 724
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 397
```

**Screenshots**
[Place any screenshots of the issue here if needed]

**Comment by 6cUbi57z** [comment]
This is a bug in the error handling code for retrying web requests when they fail. I've opened a merge request to fix the null reference exception but this is probably be hiding another issue as it generally occurs when a request is made but no response is received (e.g. a network issue or wrong address). Once the fix is in, the underlying error message should be displayed.

**Comment by garfield69** [comment]
@crimsonking19  Please upgrade to v0.17.794 and enable enhanced logging and try iptorrents again.
The latest version should allow us to see the underling error and give us something to work with.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details on providing the enhanced log.
