### ISSUE TITLE
nitro: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11396]
"query": "rings"
```
CardigannIndexer (nitro): Error while parsing row '
<tr>
	<td align="center">25/12/2020</td>
	<td align="left" class="lista">
		<a href="/torrent/wladca_pierscieni_dwie_wieze_-_the_lord_of_the_rings_the_two_towers_2002_extended_4k_2160p-uhd-bluray-remux-hevc-hdr-truehd-7-1_lektor_i_napisy_pl_982502" title="Przeglądasz detale: Władca Pierścieni: Dwie Wieże - The Lord of the Rings: The Two Towers (2002) [EXTENDED] [4K] [2160p.UHD.BluRay.REMUX.HEVC.HDR.TrueHD.7.1] [Lektor i Napisy PL]" class="list_title_name">Władca Pierścieni: Dwie Wieże - The Lord of the Rings: The Two Towers (2002) [EXTENDED] [4K] [2160p.UHD.BluRay.REMUX.HEVC.HDR.TrueHD.7.1] [Lektor i Napisy PL]</a>
		<br>
		<span class="tag_list">Kat.:
			<a rel="tag" href="/tags.php?tags=119#Filmy 4K / 2160p">Filmy 4K / 2160p</a>
			»
			<a rel="tag" href="/tags.php?tags=119,95#Wersja PL">Wersja PL</a>
			»
			<a rel="tag" href="/tags.php?tags=119,95,16#Fantasy / Sci-Fi">Fantasy / Sci-Fi</a>
			»
			<a rel="tag" href="/tags.php?tags=119,95,16,2#Filmy">Filmy</a>
		</span>
	</td>
	<td align="center" class="lista">
		<a href="/torrent/wladca_pierscieni_dwie_wieze_-_the_lord_of_the_rings_the_two_towers_2002_extended_4k_2160p-uhd-bluray-remux-hevc-hdr-truehd-7-1_lektor_i_napisy_pl_982502#comments" title="Przeglądasz detale: Władca Pierścieni: Dwie Wieże - The Lord of the Rings: The Two Towers (2002) [EXTENDED] [4K] [2160p.UHD.BluRay.REMUX.HEVC.HDR.TrueHD.7.1] [Lektor i Napisy PL]">4</a>
	</td>
	<td align="center" class="lista">105.90 GB</td>
	<td align="center" class="lista">Anonim</td>
	<td align="center" class="green">4</td>
	<td align="center" class="green">15</td>
	<td align="center" style="white-space: nowrap;">
		<a href="javascript:void(0)" onclick="getTorrent(this)" title="/pobierz/IDXXX/W%C5%82adca%20Pier%C5%9Bcieni%3A%20Dwie%20Wie%C5%BCe%20-%20The%20Lord%20of%20the%20Rings%3A%20The%20Two%20Towers%20%282002%29%20%5BEXTENDED%5D%20%5B4K%5D%20%5B2160p.UHD.BluRay.REMUX.HEVC.HDR.TrueHD.7.1%5D%20%5BLektor%20i%20Napisy%20PL%5D_982502.torrent">
			<img src="/img/style/bright/icons/download_icon.png" border="0" alt="Pobierz Torrent" title="Pobierz Torrent">
		</a>
		<a href="javascript:void(0)" onclick="getMagnet(this)" title="/__DWNMAGNET__?id=982502">
			<img src="/img/style/bright/icons/magnet-icon.png" border="0" alt="Pobierz [Magnet]" title="Pobierz [Magnet]">
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="/tags.php?tags="], value=119: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568
```

**Comment by garfield69** [comment]
stupid site does not conform to the standards it started with. 
apparently tags can now be listed in reverse order which is a monumental pain in the ass
we've been grabbing the first tab for the category, now we cant rely on that anymore.
I'll have to rework the detection.

**Comment by ngosang** [comment]
"query": "silicon valley"
```
CardigannIndexer (nitro): Error while parsing row '
<tr>
	<td align="center">03/10/2017</td>
	<td align="left" class="lista">
		<a href="/torrent/silicon_valley_2016_s03e04_480p-hdtv-xvid-kit_lektor_pl_575116" title="Przeglądasz detale: Silicon Valley *2016* S03E04 [480p.HDTV.XviD-KiT] [Lektor PL]" class="list_title_name">Silicon Valley *2016* S03E04 [480p.HDTV.XviD-KiT] [Lektor PL]</a>
		<br>
		<span class="tag_list">Kat.:
			<a rel="tag" href="/tags.php?tags=144#Nieposortowane">Nieposortowane</a>
		</span>
	</td>
	<td align="center" class="lista">
		<a href="/torrent/silicon_valley_2016_s03e04_480p-hdtv-xvid-kit_lektor_pl_575116#comments" title="Przeglądasz detale: Silicon Valley *2016* S03E04 [480p.HDTV.XviD-KiT] [Lektor PL]">0</a>
	</td>
	<td align="center" class="lista">413.83 MB</td>
	<td align="center" class="lista">
		<a class="nickname" href="/user/44650.html">
			<span class="nickspan" style="color:#232323;border-top:1px solid #232323">andromedos (1)</span>
		</a>
	</td>
	<td align="center" class="red">0</td>
	<td align="center" class="red">0</td>
	<td align="center" style="white-space: nowrap;">
		<a href="javascript:void(0)" onclick="getTorrent(this)" title="/pobierz/IDXXX/Silicon%20Valley%20%2A2016%2A%20S03E04%20%5B480p.HDTV.XviD-KiT%5D%20%5BLektor%20PL%5D_575116.torrent">
			<img src="/img/style/bright/icons/download_icon.png" border="0" alt="Pobierz Torrent" title="Pobierz Torrent">
		</a>
		<a href="javascript:void(0)" onclick="getMagnet(this)" title="/__DWNMAGNET__?id=575116">
			<img src="/img/style/bright/icons/magnet-icon.png" border="0" alt="Pobierz [Magnet]" title="Pobierz [Magnet]">
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=span.tag_list, value=<null>: None of the case selectors "[a:contains("Seriale"), 1],[a:contains("Filmy"), 2],[a:contains("Muzyka"), 3],[a:contains("Gry"), 4],[a:contains("Anime"), 5],[a:contains("Programy"), 6],[a:contains("Książki"), 7],[a:contains("Booki"), 8],[a:contains("PDA"), 9],[a:contains("Inne"), 10],[a:contains("XXX"), 11]" matched 
<span class="tag_list">Kat.:
	<a rel="tag" href="/tags.php?tags=144#Nieposortowane">Nieposortowane</a>
</span>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568

CardigannIndexer (nitro): Error while parsing row '
<tr>
	<td align="center">03/10/2017</td>
	<td align="left" class="lista">
		<a href="/torrent/dolina_krzemowa_-_silicon_valley_2015_s02e10_hdtv-xvid-kit_lektor_pl_626690" title="Przeglądasz detale: Dolina Krzemowa - Silicon Valley *2015* S02E10 [HDTV.XviD-KiT] [Lektor PL]" class="list_title_name">Dolina Krzemowa - Silicon Valley *2015* S02E10 [HDTV.XviD-KiT] [Lektor PL]</a>
		<br>
		<span class="tag_list">Kat.:
			<a rel="tag" href="/tags.php?tags=144#Nieposortowane">Nieposortowane</a>
		</span>
	</td>
	<td align="center" class="lista">
		<a href="/torrent/dolina_krzemowa_-_silicon_valley_2015_s02e10_hdtv-xvid-kit_lektor_pl_626690#comments" title="Przeglądasz detale: Dolina Krzemowa - Silicon Valley *2015* S02E10 [HDTV.XviD-KiT] [Lektor PL]">0</a>
	</td>
	<td align="center" class="lista">249.51 MB</td>
	<td align="center" class="lista">
		<a class="nickname" href="/user/43716.html">
			<span class="nickspan" style="color:#666666;border-top:1px solid #666666">
				<b style="color:#BFBFBF;border-top:1px solid #BFBFBF">SYSTEM-AURY (1</b>)</span>
		</a>
	</td>
	<td align="center" class="red">0</td>
	<td align="center" class="red">0</td>
	<td align="center" style="white-space: nowrap;">
		<a href="javascript:void(0)" onclick="getTorrent(this)" title="/pobierz/IDXXX/Dolina%20Krzemowa%20-%20Silicon%20Valley%20%2A2015%2A%20S02E10%20%5BHDTV.XviD-KiT%5D%20%5BLektor%20PL%5D_626690.torrent">
			<img src="/img/style/bright/icons/download_icon.png" border="0" alt="Pobierz Torrent" title="Pobierz Torrent">
		</a>
		<a href="javascript:void(0)" onclick="getMagnet(this)" title="/__DWNMAGNET__?id=626690">
			<img src="/img/style/bright/icons/magnet-icon.png" border="0" alt="Pobierz [Magnet]" title="Pobierz [Magnet]">
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=span.tag_list, value=<null>: None of the case selectors "[a:contains("Seriale"), 1],[a:contains("Filmy"), 2],[a:contains("Muzyka"), 3],[a:contains("Gry"), 4],[a:contains("Anime"), 5],[a:contains("Programy"), 6],[a:contains("Książki"), 7],[a:contains("Booki"), 8],[a:contains("PDA"), 9],[a:contains("Inne"), 10],[a:contains("XXX"), 11]" matched 
<span class="tag_list">Kat.:
	<a rel="tag" href="/tags.php?tags=144#Nieposortowane">Nieposortowane</a>
</span>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568
```
