### ISSUE TITLE
[cinecalidad] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by Manuel5cc** [Jackett/Jackett#11392]
### Environment

**OS**:  Docker version 20.10.5, build 55c4c88, Raspbian GNU/Linux 10 (buster), linuxserver/jackett:development

**Jackett Version**: v0.17.775

**Last Working Jackett Version**: v0.17.775

**Are you using a proxy or VPN?** no

### Description

Can't add the indexer to my list. All is working as usual.
Other indexers can be added without problems.

### Logged Error Messages

System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass7_0.<get_RetryPolicy>b__2(DelegateResult`1 exception, TimeSpan timeSpan, Context context) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 464
   at Polly.AsyncRetryTResultSyntax.<>c__DisplayClass22_0`1.<<WaitAndRetryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 538
   at Jackett.Common.Indexers.Cinecalidad.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 114
   at Jackett.Common.Indexers.Cinecalidad.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 85
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by garfield69** [comment]
the indexer works for me which suggests the issue is at your end.
Your ISP may be blocking your access to the site.
Try using the Jackett Dashboard to edit the indexer config and try out any of the alternate site links to see if they work for you.

**Comment by Manuel5cc** [comment]
> the indexer works for me which suggests the issue is at your end.
> Your ISP may be blocking your access to the site.
> Try using the Jackett Dashboard to edit the indexer config and try out any of the alternate site links to see if they work for you.

Yes, my ISP is definitely blocking the main domain but not the alternates. I have tried configuring the indexer with them and the result is the same, even when they work from my explorer.

**Comment by garfield69** [comment]
@ilike2burnthing  Docker + Rasp + C# indexer ... not my cup of tea. Can you assist?

**Comment by ilike2burnthing** [comment]
Tried changing the DNS for your container (e.g. 1.1.1.1 and 1.0.0.1)?

If that doesn't help, please provide enhanced logs of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Manuel5cc** [comment]
> Tried changing the DNS for your container (e.g. 1.1.1.1 and 1.0.0.1)?
> 
> If that doesn't help, please provide enhanced logs of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Yes, I did try changing the dns of my container and also the host system to public ones (google, cloudflare, etc.) but that didn't do it. 
Here's the enhanced log wit the relevant information:
[new 1.txt](https://github.com/Jackett/Jackett/files/6187447/new.1.txt)

**Comment by ilike2burnthing** [comment]
Do you have [FlareSolverr](https://hub.docker.com/r/flaresolverr/flaresolverr/) installed and configured in Jackett? If not, do so.

**Comment by Manuel5cc** [comment]
> Do you have [FlareSolverr](https://hub.docker.com/r/flaresolverr/flaresolverr/) installed and configured in Jackett? If not, do so.

Well that definitely did make the alternate sites work.
