### ISSUE TITLE
[immortalseed] Exception (immortalseed): String '2021-03-28 10:00 PM' was not recognized as a valid DateTime.: Parse error (Test)

### ISSUE THREAD

**Issue by labrown** [Jackett/Jackett#11427]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu  (via the linuxserver/jackett docker container)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] ??

**.Net Version**: ??

**Jackett Version**: Version v0.17.797

**Last Working Jackett Version**:   Not sure

**Are you using a proxy or VPN?** [yes/no] no

### Description

Noticed tonight that my searches into Immortalseed are no longer working.  Testing jackett turned up the error in the title string.

Looking at the Immortalseed.cs code I see line 179: https://github.com/Jackett/Jackett/blob/69125add3e6c8c686c318629b65eecad8875494c/src/Jackett.Common/Indexers/ImmortalSeed.cs#L179
attemps to parse the date/time as "MM-dd-yyyy hh:mm tt" but immortalseed is showing me date/times like "2021-03-17 03:39 AM" in the search results now.

### Logged Error Messages

Jackett.Common.IndexerException: Exception (immortalseed): String '2021-03-28 10:00 PM' was not recognized as a valid DateTime.
 ---> System.Exception: Parse error
 ---> System.FormatException: String '2021-03-28 10:00 PM' was not recognized as a valid DateTime.
   at Jackett.Common.Indexers.ImmortalSeed.PerformQuery(TorznabQuery query)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 757
   at Jackett.Common.Indexers.ImmortalSeed.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/ImmortalSeed.cs:line 215
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 381
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 731
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

**Comment by garfield69** [comment]
I don't have an account on the site, so I cannot test.
Does your account profile setting have a language selection, or a date format selection?

If the answer is no, then I can readily change the indexer's date format to `yyyy-MM-dd` as soon as you confirm.

**Comment by labrown** [comment]
I went looking a language or date format selection but didn't find anything.

**Comment by labrown** [comment]
I went looking again and found a language setting, but none of them change the format of the date/time string in the search results.

**Comment by labrown** [comment]
Now that's what I call service!

**Comment by garfield69** [comment]
v0.17.810

**Comment by labrown** [comment]
Confirmed operational!
