### ISSUE TITLE
selezen: Error: Ошибка авторизации

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#11476]
Any query
```
Jackett.Common.IndexerException: Exception (selezen): Error: Ошибка авторизации
    Внимание! Вход на сайт не был произведён. Возможно, Вы ввели неверное имя пользователя или пароль.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Error: Ошибка авторизации
    Внимание! Вход на сайт не был произведён. Возможно, Вы ввели неверное имя пользователя или пароль.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 517
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 734
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1336
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 757
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1666
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 391
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 391
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 734
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 228

Error on 20210405063930 for seleZen.txtJackett.Common.ExceptionWithConfigData: Error: Ошибка авторизации
    Внимание! Вход на сайт не был произведён. Возможно, Вы ввели неверное имя пользователя или пароль.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 517
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 734
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1336
```

**Comment by garfield69** [comment]
you are seeing **Ошибка авторизации** == Authorisation Error
The indexer works for me so check your credentials.
