### ISSUE TITLE
[orpheus] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by brianredbeard** [Jackett/Jackett#11543]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Using the LinuxServer.io container (linuxserver/jackett):
```bash
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**.Net Runtime**: Unknown (They utilize the compiled Linux release binaries directly):

https://github.com/linuxserver/docker-jackett/blob/eaa5a900d142098de6b06dc3ca8f3134ab96bd08/Dockerfile#L32

**.Net Version**:  Unknown

**Jackett Version**:  Tested in the following versions:

Jackett v0.17.883 

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?**: No

### Description

Attempting to add the Gazelle based tracker "Orpheus" fails throwing the following exception:

```
Error System.NullReferenceException: Object reference not set to an instance of an object.
```

Other trackers are able to be added correctly.

There is a forum post stating that the code base had some updates to the login page ~13 days ago, but I don't see any relevant commits in github.com/OPSnet/Gazelle to verify.  There is an unmerged dependabot PR [updating y18n](https://github.com/OPSnet/Gazelle/pull/143), but this doesn't _seem_ to be the source of the problem.  Similarly, I've confirmed that from the server side the character set is being specified as UTF-8:

```html
...
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
...
```

Additionally, to rule out potential symbol/encoding errors the password was changed to a value conforming to strict ISO-8859-1 encoding utilizing no values outside of the PCRE set `[:alnum:]` (i.e., `[A-Za-z0-9]`).

### Logged Error Messages

```
04-14 19:05:14 Error System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Abstract.GazelleTracker.<>c__DisplayClass16_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 138
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 241
   at Jackett.Common.Indexers.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 132
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Abstract.GazelleTracker.<>c__DisplayClass16_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 138
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 241
   at Jackett.Common.Indexers.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 132
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

Full logs attached.
[log.txt](https://github.com/Jackett/Jackett/files/6314890/log.txt)

### Additional information

Searching the issue tracker this does **not** appear to be the same as #8383 as this is is occurring on the validation of the user defined input in the web interface.

cc @itismadness

**Comment by garfield69** [comment]
@RoloSoze  as an independent check for this ticket, does the orpheus indexer work for you?
And are you using the username/password combo or the 2FA/cookie fields?
Thanks.

**Comment by garfield69** [comment]
@brianredbeard  this indexer is written in C#, and uses the GazalleTracker abstract.
From what I can tell looking at the code, after the login attempt it checks for a response that contains `logout.php` as a way of confirming that the login was successful, and throws an exception if it is not found.

Can you use your browser to login to the site, and on the first page you land on after login, capture the HTML and post it here so I can have a look at what you get.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source
Thanks.

**Comment by brianredbeard** [comment]
@garfield69 I'm using the username / password fields (trying to minimize the complexity until #9860 lands).

As requested, `https://orpheus.network/index.php`: 

[News __ Orpheus.txt](https://github.com/Jackett/Jackett/files/6315134/News.__.Orpheus.txt)

**Comment by garfield69** [comment]
well the index page has `<a href="https://orpheus.network/logout.php?auth=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX">Logout</a>` so that should have been a match.

which can only mean that we did not get that index page after jackett attempted the login. :-(
unfortunately, this is where my contribution to this ticket ends, as I am not a C# dev and don't know how to change the indexer to dump what was actually returned by the site instead of that useless object-reference exception.
I'll assign the ticket to our resident C# dev, but @ngosang  has not been available recently so any C# devs who want to pitch in please do so and welcome!

**Comment by ngosang** [comment]
@ilike2burnthing is this fixed by your pr?

**Comment by ilike2burnthing** [comment]
No, my PR was for https://github.com/Jackett/Jackett/issues/11728 and _should_ only allow downloading torrents (which now require a passkey), but according to the comments there it somehow managed to get the user temporarily locked out of their account when trying to configure the indexer, and I have no idea how.

**Comment by garfield69** [comment]
v0.18.255
