### ISSUE TITLE
Exception (kickasstorrents-to): FlareSolverr was unable to process the request

### ISSUE THREAD

**Issue by jriggz** [Jackett/Jackett#11586]
### Environment
Docker

**OS**:
Docker

**Jackett Version**:
0.17.931

**Last Working Jackett Version**:
Unsure. This has been the case for about a month

**Are you using a proxy or VPN?** [yes/no]
no

### Description

Do a search. Test kickass.to. It's infinitely repeatable because, apparently, kickass.to stopped using Captcha some time ago. Maybe I'm dumb, but I can't find a way to turn off the use of Flaresolverr in Jackett for just one indexer.

### Logged Error Messages

> Jackett.Common.IndexerException: Exception (kickasstorrents-to): FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: No challenge selectors found, unable to proceed
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: No challenge selectors found, unable to proceed
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 207
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 570
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1317
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 391
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 391
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 734
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 228

**Comment by garfield69** [comment]
You should not need to turn off Flaresolverr for an individual  indexer, even if this was possible.
I am not certain about the following, but I believe that when Flaresolverr is configured and connected to Jackett, it is called for all indexers, and its up to Flaresolverr to decide if it has any work to do.

I suspect that the issue is that Flaresolverr thinks it sees signatures that indicate that there should be a Cloudflare challenge to process, but gets flummoxed when it cant find the rest of the challenge.

This is an issue that should be posted on the Flaresolverr support site, it is not a Jackett issue.

**Comment by garfield69** [comment]
BTW I just tested this indexer will all the alternate site links 
```
https://kickasstorrents.to/
https://kickasstorrent.cr/
https://katcr.to/
https://kickasstorrents.unblockninja.com/
```
and I do not have any issues.

**Comment by jriggz** [comment]
They say it's a Jackett problem, you say it's a Flaresolverr problem, so I'm left with the problem. Thanks.

**Comment by gingerbeardman** [comment]
Thanks @garfield69 I just changed to a different URL that works OK.
