### ISSUE TITLE
[yggtorrent] The operation was canceled. (Config)

### ISSUE THREAD

**Issue by Cosa67** [Jackett/Jackett#11584]
### Environment

**OS**: Synology (Jackett directly installed from Synology Community Packages, not using Docker)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.17.931

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

• Unable to add YGG torrent.
• Flaresolverr is running, latest version 

When I try to access to Flaresolverr in brower, everything seems to be OK 

`{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1618992847244,"endTimestamp":1618992847244,"version":"v1.2.5"}`

### Logged Error Messages

 System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 184
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 566
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 959
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 560
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 965
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by Cosa67** [comment]
I opened this new issue because the others I found have been fixed "by configuring the flaresolverr true container IP in jackett configuration" & host mode, but in my case I'm not running Jackett from Docker and I really don't know how to find/set this host mode...

**Comment by garfield69** [comment]
To get your Jackett to talk to your flaresolver proxy all you do is plug in the full flaresolverr address you used in your browser to test with, into the Jackett dashboard **flaresolverr api url** box and then click on the dashboard **apply server settings** button.

**Comment by Cosa67** [comment]
> To get your Jackett to talk to your flaresolver proxy all you do is plug in the full flaresolverr address you used in your browser to test with, into the Jackett dashboard **flaresolverr api url** box and then click on the dashboard **apply server settings** button.

It's already done : http://flaresolverr:8191/

**Comment by garfield69** [comment]
The reason for the delay is likely the flaresolverr proxy trying to figure out the cloudflare protection that yggtorrent have activated.
If you have the flaresolverr proxy shell window open you can see what flaresolverr is up to.
Which should confirm that jackett is talking to flaresolverr because you will see activity.
If you need to see more debug info on the flaresolverr side, turn on the debug logging, see https://github.com/FlareSolverr/FlareSolverr#environment-variables

**Comment by Cosa67** [comment]
Really strange... I try to fix it since yesterday evening and now, without doing something special since my post here, it works... Really don't understand why but it works !
