### ISSUE TITLE
[unionfansub] Login failed: Selector

### ISSUE THREAD

**Issue by Janco2049** [Jackett/Jackett#11609]
Environment

OS: Windows 10 x64 20H2 19042.928

.Net Runtime: .Net-Framework

.Net Version: 4.8.0.20190930

Jackett Version: v0.17.946

Are you using a proxy or VPN? NO

Description

Adding an account to the tracker.

Logged Error Messages

Login failed: Selector "div#statusbar" didn't match

Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#statusbar" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 823
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 966
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

**Comment by garfield69** [comment]
yes I get this too. It appears the login for the wen site has had a few changes.
I'll update the indexer.

**Comment by garfield69** [comment]
v0.17.952

**Comment by Janco2049** [comment]
Solved, thank you
