### ISSUE TITLE
[torrentleech] Error:  Please click on the reCAPTCHA box. (Config)

### ISSUE THREAD

**Issue by PatenDan** [Jackett/Jackett#11647]
All has been working fine, had to rest password, updated but seem to be getting error no matter what I do, sorry new to this so any help would be great.

### Logged Error Messages

Jackett.Common.ExceptionWithConfigData: Error:  Please click on the reCAPTCHA box.
   at Jackett.Common.Indexers.TorrentLeech.<>c__DisplayClass12_0.<DoLogin>b__0() in D:\a\1\s\src\Jackett.Common\Indexers\TorrentLeech.cs:line 146
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 241
   at Jackett.Common.Indexers.TorrentLeech.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\TorrentLeech.cs:line 141
   at Jackett.Common.Indexers.TorrentLeech.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentLeech.cs:line 129
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

**Comment by PatenDan** [comment]
reboot LOL and edit passwords again
