### ISSUE TITLE
[ShizaProject] Value cannot be null. (Parameter 'node') (Config)

### ISSUE THREAD

**Issue by kekal** [Jackett/Jackett#11712]
### Environment

**OS**: synology

**Jackett Version**: linuxserver/jackett:version-v0.18.22

**Are you using a proxy or VPN?**: no

### Description

Shiza indexer cannot be added with the error similar to #11659 

### Logged Error Messages

```
System.ArgumentNullException: Value cannot be null. (Parameter 'node')
   at AngleSharp.Dom.NodeExtensions.Text(INode node)
   at Jackett.Common.Indexers.ShizaProject.<>c__DisplayClass11_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/ShizaProject.cs:line 87
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 245
   at Jackett.Common.Indexers.ShizaProject.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/ShizaProject.cs:line 85
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
this web site is such a PitA
There is a cloudflare reCaptcha on the login page so this now breaks Jackett.
Also I think the site has switched from using `https://shiza-project.com/accounts/login` to using ` https://shiza-project.com/users/signin`

I could try to switch to using a cookie method to duplicate the session from a browser, but I am not a C# dev so it will take me some time while using an existing C# cookie indexer as a template to wrap my head around what code is required.
I would welcome a C# dev to contribute a PR to speed this up. @dm3ch can you work on this?

**Comment by dm3ch** [comment]
I can take a look on weekends.

As far as I know @ngosang is familiar with CloudFlare things. @ngosang Could you please consult if solution proposed by @garfield69 would work?

P.S. As far as I see right now download links are also shown to unauthenticated users. Maybe this traker switched from semi-private to public model or maybe I was wrong when added it as semi-private

**Comment by dm3ch** [comment]
@kekal TY, I would try to rewrite indexer using API on weekends. And if I would have free time tomorrow I would check if there's a quick way to make current code work with as less changes as possible

**Comment by kekal** [comment]
> @garfield69 Also now updated site uses Nuxt.js framework. Traffic analyse during site usage showed me that it works using graphql api now. So it seems that this indexer would be better to rewrite from scratch.
> 
> P.S. It looks like they are using isomorphic rendering now. It's SPA (Single Page Application) with dynamic data loading via graphql api, but it's also able to response with fully pre-rendered page (it's using when you opens link directly)

**Comment by dm3ch** [comment]
@garfield69 GraphQL api based indexer ready for tests but not fully finished yet.
https://github.com/Jackett/Jackett/pull/11715

**Comment by ilike2burnthing** [comment]
[v0.18.169](https://github.com/Jackett/Jackett/releases/tag/v0.18.169)

**Comment by kekal** [comment]
Indexer readded successfully.
