### ISSUE TITLE
Error: Value cannot be null. while setting socks5 proxy

### ISSUE THREAD

**Issue by n0rdik** [Jackett/Jackett#11726]
### Environment

**OS**: Ubuntu 20.04 LTS

**.Net Runtime**: [Mono]

**.Net Version**:

**Jackett Version**: 0.18.59

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes]

### Description

Hi! I'm trying to set a socks5 proxy server for jackett in config. I set "socks5" in type, "127.0.0.1" in url and "9050" in port. Then apply and get "Error: Value cannot be null." Click again and then accepts this configuration, but if I restart I get this error in log:

(see attached log)

Am I doing something wrong? Thanks in advance.

### Logged Error Messages

```
2021-05-14 11:21:16.7705 Info Starting Jackett v0.18.59
2021-05-14 11:21:17.3792 Error Autofac.Core.DependencyResolutionException: An exception was thrown while activating Jackett.Server.Services.ServerSer
vice -> Jackett.Common.Services.IndexerManagerService -> Jackett.Common.Utils.Clients.HttpWebClient2.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfac
es.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient2'.
 ---> System.ArgumentNullException: Value cannot be null.
   at Org.Mentalis.Proxy.Listener.set_ListenSocket(Socket value)
   at Org.Mentalis.Proxy.Listener.Start()
   at com.LandonKey.SocksWebProxy.SocksWebProxy.GetListener(ProxyConfig config, Boolean allowBypass)
   at com.LandonKey.SocksWebProxy.SocksWebProxy..ctor(ProxyConfig config, Boolean allowBypass)
   at Jackett.Common.Utils.Clients.WebClient.InitProxy(ServerConfig serverConfig) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 83
   at Jackett.Common.Utils.Clients.WebClient..ctor(IProcessService p, Logger l, IConfigurationService c, ServerConfig sc) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 121
   at lambda_method66(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__8_0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
```

**Comment by ilike2burnthing** [comment]
You have to use the IP address and port of the proxy, which presumably isn't localhost (127.0.0.1), i.e. your device.

If it is however, then what are you using as your proxy?

**Comment by n0rdik** [comment]
Well, I want to try TOR proxy service (localhost:9050), because some indexers are banned in my country. As you say, I put the IP addres and port en each field... so I don't know if its my fault or it is a program bug.

**Comment by ilike2burnthing** [comment]
I have zero experience with Tor, so unfortunately I can't help you with whether your setup is correct.

Are you able to use the same proxy with other applications, e.g. a web browser?

**Comment by n0rdik** [comment]
Yes, the tor service is working properly. I think it doesn't totally matter if its tor or not, it could be a Dante proxy, or simply a socks proxy generated by a SSH connection, the point is that the option to configure a socks4-5 proxy behind jackett is there and it is not working (or maybe is not intended for that, correct me please).  I think the problem is that the configuration of a relay proxy in jackett (at least in my environment) is breaking the installation, so I could not even launch jackett. It is not that i can launch jackett and then none of the indexers work, the program doesn't work anymore until I restore the last config without proxy.

**Comment by n0rdik** [comment]
Well, I've tested with this approach: jackett->privoxy->tor, in other words, jackett->http proxy->socks5 proxy and it works. As I said, I think the problem is that the socks config is not working or is not configured the same way as http proxies.

**Comment by ilike2burnthing** [comment]
Strange. I'm using a socks5 proxy and it's working ok, but it's an external IP address, not relying on a loopback interface.

@qg0 and @JeeDeWee you have both previously said you're using a tor socks5 proxy. Was this using Jackett's own proxy settings, or some other method (e.g. system wide, or forwarding Jackett's traffic through a Docker container)?

**Comment by n0rdik** [comment]
Well, because of that I'm asking, it could be my fault. I've configured this parameters:

Proxy type: SOCKS5
Proxy URL: 127.0.0.1
Proxy port: 9050

In the front panel of Jackett. Maybe I'm missing something?

P.S. I've also tried configuring an external socks5 proxy and the error thrown is the same.

**Comment by ilike2burnthing** [comment]
Changes your Proxy URL to `http://127.0.0.1`

**Comment by n0rdik** [comment]
No luck, same error.

**Comment by ilike2burnthing** [comment]
Try using the local IP of your device rather than localhost, e.g. http://192.168.0.2

But if no SOCKS5 proxies are working for you then I'm kinda stumped, because they're definitely working for me. Could be an issue with your device or network. I'd suggest looking at port forwarding and firewall rules.

@garfield69 any ideas?

**Comment by garfield69** [comment]
>any ideas?

None. Its not-windows, its secure sockets, its proxies, none of which I have much experience with.
the Jacket Github is full of sock5 issues, most of which have a happy ending. Perhaps scrolling through some of them will yield you options?
