### ISSUE TITLE
[danishbytes] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Reconos87** [Jackett/Jackett#11730]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker - 19.03.13

**.Net Runtime**: Mono

**.Net Version**:

**Jackett Version**: v0.18.59

**Last Working Jackett Version**: not sure,  but stopped working on 0.17, and tried updating to see if it resolved it

**Are you using a proxy or VPN?** no

### Description

1. press test
2. wait for test to fail and show message

### Logged Error Messages

CardigannIndexer (danishbytes): Error while parsing row '
*random stuff here about a release*

System.Exception: Error while parsing field=category, selector=a[href*="/categories/"], value=<null>: Selector "a[href*="/categories/"]" didn't match 
*random stuff here about a release*
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1585

**Comment by CandiMiiS** [comment]
Same problem here. Think they changed some stuff on the site

**Comment by garfield69** [comment]
those random bits in the log you subsequently removed in the post were the only useful bits in the error message, as they show the source HTML that Jackett needs to process. 
next time leave it in place please.
fortunately I have an account on the site so I can proceed with my investigation regardless.

**Comment by Reconos87** [comment]
> those random bits in the log you subsequently removed in the post were the only useful bits in the error message, as they show the source HTML that Jackett needs to process.
> next time leave it in place please.
> fortunately I have an account on the site so I can proceed with my investigation regardless.

Im deeply sorry about that, all it showed when adding it here was links to downloadable torrents, and pictures from the website. Wouldn't want to link directly to the torrents.

**Comment by garfield69** [comment]
you can encapsulate the HTML on a code block to show the HTML as raw instead of it being *displayed*.
for example:
```html
<html>
<body>
<!--StartFragment-->

CardigannIndexer (danishbytes): Error while parsing row ' <tr> 	<td style="width: 1%;"> 		<div class="torrent-poster pull-left"> 			<img loading="lazy" style="height:80px; width:52px; object-fit:cover;" src="https://images.weserv.nl/?url=https://via.placeholder.com/52x80&amp;w=52&amp;h=80" class="show-poster torrent-poster-img-small " data-image="<img src=&quot;https://images.weserv.nl/?url=https://via.placeholder.com/600x900&quot; alt=&quot;                                         torrent.poster&quot; style=&quot;height: auto; width:100%;&quot;>" alt="Poster"> 		</div> 	</td> 	<td style="width: 1%;"> 		<div class="text-center"> 			<i class="fas fa-gamepad torrent-icon" data-toggle="tooltip" data-original-title="Games torrent" style="padding-top: 10px;"></i> 		</div> 	</td> 	<td style="width: 1%;"> 		<div class="text-center" style="padding-top: 15px;"> 			<span class="label label-success" data-toggle="tooltip" data-original-title="Type"> 				Windows 			</span> 		</div> 	</td> 	<td style="width: 60px; vertical-align:middle;" class="text-center"> 		<img src="https://danishbytes.org/files/img/flags/gb-32.png" data-toggle="tooltip" data-original-title="gb" alt="gb" style="margin-left:2px; margin-right:2px;"> 	</td> 	<td style="width: 60px; vertical-align:middle;" class="text-center"> 		<span data-toggle="tooltip" data-original-title="No language" alt="No language" style="margin-left:2px; margin-right:2px;"></span> 	</td> 	<td> 		<a class="view-torrent view-torrent-green" style="color:darkgreen;" href="https://danishbytes.org/torrents/19332"> 			Subnautica.Below.Zero.PC-CODEX 		</a> 		<a href="https://danishbytes.org/torrents/19332" target="_blank"> 			<span style="font-size:x-small; color:lightyellow; background-color:rgba(0, 0, 0, 0.4);"> 				<b>(<i>Åben i nyt vindue</i>)</b> 			</span> 		</a> 		<br> 		<span class="badge-extra text-bold"> 			<i class="fas fa-upload" data-toggle="tooltip" data-original-title="Uploader"></i> 			Anonymous 		</span> 		<button value="19332" class="like badge-extra text-bold text-pink" style="margin-bottom:5px;" title="LIKE"> 			<i class="fas fa-heart"></i> 			<span id="like19332">0</span> 		</button> 		<a href="https://danishbytes.org/torrents/19332#comments"> 			<span class="badge-extra text-bold text-green"> 				<i class="fas fa-comment" data-toggle="tooltip" data-original-title="Comments"></i> 				0 			</span> 		</a> 		<span class="badge-extra text-bold" style="background-image:url(/img/sparkels.gif); background-color:darkgreen; color:mediumseagreen;" data-toggle="tooltip" title="" data-original-title="GRØN: Freeleech, men der tælles kun 1/2 upload og ingen PARA i perioden."> 			<i class="fas fa-seedling text-green"></i> 		</span> 		<span class="badge-extra text-bold"> 			<i class="fas fa-globe text-blue" data-toggle="tooltip" title="" data-original-title="Global Freeleech"></i> 		</span> 		<span class="badge-extra text-bold"> 			<i class="fas fa-tachometer text-red" data-toggle="tooltip" title="" data-original-title="High Speeds"></i> 		</span> 		 		<!-- !! --> 		<br> 	</td> 	<td> 		<a href="https://danishbytes.org/torrents/download/19332"> 			<button class="btn btn-primary btn-circle" type="button" data-toggle="tooltip" style="max-width:30px;" data-original-title="Download"> 				<i class="fas fa-download"></i> 			</button> 		</a> 		<a href="magnet:?dn=Subnautica.Below.Zero.PC-CODEX&amp;xt=urn:btih:722433b0c2d6069b8c4a0b98b34c6e337d3ed469&amp;as=https://danishbytes.org/torrent/download/19332.4e70df170b8b0f99712d5301d8ffb525&amp;tr=https://danishbytes.org/announce/f7c2b71f3a595a9553cbd2d4a3812868&amp;xl=6601332869"> 			<button class="btn btn-primary btn-circle" type="button" data-toggle="tooltip" style="max-width:30px;" data-original-title="Magnet"> 				<i class="fas fa-magnet"></i> 			</button> 		</a> 	</td> 	<td> 		<button value="19332" class="bookmark btn btn-primary btn-circle" style="max-width:30px;"> 			<i class="fas fa-bookmark"></i> 		</button> 	</td> 	<td> 		<time>15 hours ago</time> 	</td> 	<td> 		<span class="badge-extra text-blue text-bold">6.15 GiB</span> 	</td> 	<td> 		<a href="https://danishbytes.org/torrents/19332/peers"> 			<span class="badge-extra text-green text-bold" data-toggle="tooltip" data-original-title="Seeders"> 				11 			</span> 		</a> 	</td> 	<td> 		<a href="https://danishbytes.org/torrents/19332/peers"> 			<span class="badge-extra text-red text-bold" data-toggle="tooltip" data-original-title="Leechers"> 				0 			</span> 		</a> 	</td> 	<td> 		<a href="https://danishbytes.org/torrents/19332/history"> 			<span class="badge-extra text-black text-bold" data-toggle="tooltip" data-original-title="Antal gange Fuldført"> 				11 			</span> 		</a> 	</td> </tr>':  System.Exception: Error while parsing field=category, selector=a[href*="/categories/"], value=<null>: Selector "a[href*="/categories/"]" didn't match  <tr> 	<td style="width: 1%;"> 		<div class="torrent-poster pull-left"> 			<img loading="lazy" style="height:80px; width:52px; object-fit:cover;" src="https://images.weserv.nl/?url=https://via.placeholder.com/52x80&amp;w=52&amp;h=80" class="show-poster torrent-poster-img-small " data-image="<img src=&quot;https://images.weserv.nl/?url=https://via.placeholder.com/600x900&quot; alt=&quot;                                         torrent.poster&quot; style=&quot;height: auto; width:100%;&quot;>" alt="Poster"> 		</div> 	</td> 	<td style="width: 1%;"> 		<div class="text-center"> 			<i class="fas fa-gamepad torrent-icon" data-toggle="tooltip" data-original-title="Games torrent" style="padding-top: 10px;"></i> 		</div> 	</td> 	<td style="width: 1%;"> 		<div class="text-center" style="padding-top: 15px;"> 			<span class="label label-success" data-toggle="tooltip" data-original-title="Type"> 				Windows 			</span> 		</div> 	</td> 	<td style="width: 60px; vertical-align:middle;" class="text-center"> 		<img src="https://danishbytes.org/files/img/flags/gb-32.png" data-toggle="tooltip" data-original-title="gb" alt="gb" style="margin-left:2px; margin-right:2px;"> 	</td> 	<td style="width: 60px; vertical-align:middle;" class="text-center"> 		<span data-toggle="tooltip" data-original-title="No language" alt="No language" style="margin-left:2px; margin-right:2px;"></span> 	</td> 	<td> 		<a class="view-torrent view-torrent-green" style="color:darkgreen;" href="https://danishbytes.org/torrents/19332"> 			Subnautica.Below.Zero.PC-CODEX 		</a> 		<a href="https://danishbytes.org/torrents/19332" target="_blank"> 			<span style="font-size:x-small; color:lightyellow; background-color:rgba(0, 0, 0, 0.4);"> 				<b>(<i>Åben i nyt vindue</i>)</b> 			</span> 		</a> 		<br> 		<span class="badge-extra text-bold"> 			<i class="fas fa-upload" data-toggle="tooltip" data-original-title="Uploader"></i> 			Anonymous 		</span> 		<button value="19332" class="like badge-extra text-bold text-pink" style="margin-bottom:5px;" title="LIKE"> 			<i class="fas fa-heart"></i> 			<span id="like19332">0</span> 		</button> 		<a href="https://danishbytes.org/torrents/19332#comments"> 			<span class="badge-extra text-bold text-green"> 				<i class="fas fa-comment" data-toggle="tooltip" data-original-title="Comments"></i> 				0 			</span> 		</a> 		<span class="badge-extra text-bold" style="background-image:url(/img/sparkels.gif); background-color:darkgreen; color:mediumseagreen;" data-toggle="tooltip" title="" data-original-title="GRØN: Freeleech, men der tælles kun 1/2 upload og ingen PARA i perioden."> 			<i class="fas fa-seedling text-green"></i> 		</span> 		<span class="badge-extra text-bold"> 			<i class="fas fa-globe text-blue" data-toggle="tooltip" title="" data-original-title="Global Freeleech"></i> 		</span> 		<span class="badge-extra text-bold"> 			<i class="fas fa-tachometer text-red" data-toggle="tooltip" title="" data-original-title="High Speeds"></i> 		</span> 		 		<!-- !! --> 		<br> 	</td> 	<td> 		<a href="https://danishbytes.org/torrents/download/19332"> 			<button class="btn btn-primary btn-circle" type="button" data-toggle="tooltip" style="max-width:30px;" data-original-title="Download"> 				<i class="fas fa-download"></i> 			</button> 		</a> 		<a href="magnet:?dn=Subnautica.Below.Zero.PC-CODEX&amp;xt=urn:btih:722433b0c2d6069b8c4a0b98b34c6e337d3ed469&amp;as=https://danishbytes.org/torrent/download/19332.4e70df170b8b0f99712d5301d8ffb525&amp;tr=https://danishbytes.org/announce/f7c2b71f3a595a9553cbd2d4a3812868&amp;xl=6601332869"> 			<button class="btn btn-primary btn-circle" type="button" data-toggle="tooltip" style="max-width:30px;" data-original-title="Magnet"> 				<i class="fas fa-magnet"></i> 			</button> 		</a> 	</td> 	<td> 		<button value="19332" class="bookmark btn btn-primary btn-circle" style="max-width:30px;"> 			<i class="fas fa-bookmark"></i> 		</button> 	</td> 	<td> 		<time>15 hours ago</time> 	</td> 	<td> 		<span class="badge-extra text-blue text-bold">6.15 GiB</span> 	</td> 	<td> 		<a href="https://danishbytes.org/torrents/19332/peers"> 			<span class="badge-extra text-green text-bold" data-toggle="tooltip" data-original-title="Seeders"> 				11 			</span> 		</a> 	</td> 	<td> 		<a href="https://danishbytes.org/torrents/19332/peers"> 			<span class="badge-extra text-red text-bold" data-toggle="tooltip" data-original-title="Leechers"> 				0 			</span> 		</a> 	</td> 	<td> 		<a href="https://danishbytes.org/torrents/19332/history"> 			<span class="badge-extra text-black text-bold" data-toggle="tooltip" data-original-title="Antal gange Fuldført"> 				11 			</span> 		</a> 	</td> </tr>    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1585
--


<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

**Comment by garfield69** [comment]
v0.18.67
