### ISSUE TITLE
[mejortorrent] Could not find releases from this URL (Config)

### ISSUE THREAD

**Issue by enigmat14** [Jackett/Jackett#11788]
### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.106

**Last Working Jackett Version**: v0.18.106

**Are you using a proxy or VPN?** yes

### Description

The test for this crawler does not pass because the page has no results. Otherwise, if you have this tracker added, you can search and jackett retrieves the results correctly. I have a FlareSolverr correctly configured and working, would it be possible to add a tracker without the check?

### Logged Error Messages

System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.MejorTorrent.<>c.<ApplyConfiguration>b__12_0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 106
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 245
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 105
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

### Screenshots
![image](https://user-images.githubusercontent.com/75588701/119256450-1a582a80-bbc1-11eb-88c5-adcd521314a4.png)
![image](https://user-images.githubusercontent.com/75588701/119256476-39ef5300-bbc1-11eb-9525-e29a6b87bd3b.png)

**Comment by ilike2burnthing** [comment]
Currently their Últimos Torrents pages has 0 results, that happens occasionally, just a matter of waiting.

If you want to add it now, copy this to your Indexers folder, rename from `.txt` to `.json`, and restart Jackett - [mejortorrent.txt](https://github.com/Jackett/Jackett/files/6527974/mejortorrent.txt)

**Comment by enigmat14** [comment]
Thank you very much! I didn't know I could do that. Now, it works :D
