### ISSUE TITLE
[yggtorrent] FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Captcha detected but no automatic solver is configured. (Config)

### ISSUE THREAD

**Issue by thegrunge36** [Jackett/Jackett#11830]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: linux ubuntu 20.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:0.18.171

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

Exception in GetConfigurationForSetup (yggtorrent): FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Captcha detected but no automatic solver is configured.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 574
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 868

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#flaresolverr-was-able-to-process-the-request-but-a-captcha-was-detected-captcha-detected-but-no-automatic-solver-is-configured
but
https://github.com/FlareSolverr/FlareSolverr#captcha-solvers
and
https://github.com/Jackett/Jackett/issues/11825

**Comment by thegrunge36** [comment]
Thanks I'll try Captcha Solvers. I never needed it until the day before yesterday

**Comment by thegrunge36** [comment]
I've been watching for a few minutes, and I'm not sure what to do with it. I am not very familiar with linux.

**Comment by ilike2burnthing** [comment]
From the 2nd link above:
> At this time none of the captcha solvers work. You can check the status in the open issues.

**Comment by thegrunge36** [comment]
I already have flaresolverr, but I don't understand what to do with Captcha Solvers or hcaptcha-solver...
Thanks

**Comment by ilike2burnthing** [comment]
"At this time **none** of the captcha solvers work."

**Comment by thegrunge36** [comment]
I know I read that right too. I will wait and see what ygg will do with it is captcha
