### ISSUE TITLE
[torrentseeds] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by diemade** [Jackett/Jackett#11878]
### Environment

**OS**: Windows Server 2019 Ver. 1809

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] 4.7.03190

**.Net Version**:

**Jackett Version**:  v0.18.255

**Last Working Jackett Version**: never

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Edit config

### Logged Error Messages

2021-06-06 16:59:05 	Error 	

System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.TorrentSeeds.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentSeeds.cs:line 136
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

2021-06-06 16:53:51 	Error 	

Jackett.Common.IndexerException: Exception (torrentseeds): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.TorrentSeeds.ParseSingleResult(WebResult response, Uri detailsLink) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentSeeds.cs:line 213
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 761
   at Jackett.Common.Indexers.TorrentSeeds.ParseSingleResult(WebResult response, Uri detailsLink) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentSeeds.cs:line 246
   at Jackett.Common.Indexers.TorrentSeeds.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentSeeds.cs:line 194
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 395
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 395
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 738
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 432

2021-06-06 16:53:51 	Error 	

Error on 20210606165351 for TorrentSeeds.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.TorrentSeeds.ParseSingleResult(WebResult response, Uri detailsLink) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentSeeds.cs:line 213
```




<!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
        
  <head>
 
    <meta name="referrer" content="same-origin" />
    <!--<meta charset="UTF-8" />-->
    <meta charset="utf-8" />
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
	<meta http-equiv="Content-Security-Policy" content="plugin-types application/x-shockwave-flash">
    <meta name="viewport" content="width=device-width, initial-scale=0.35, maximum-scale=1" />
    <title>TorrentSeeds :: TorrentSeeds</title>
		<!-- favicon  -->
    	<link rel="shortcut icon" href="/favicon.ico" />
	<link rel="stylesheet" href="css/bootstrap.css" type="text/css">
	<link type="text/css" rel="stylesheet" href="templates/1/css/forums.css" />
<!-- Template CSS-->
    	<link rel="stylesheet" href="templates/1/1.css?ts=1613748947" />
       	<link rel="stylesheet" href="css/font-awesome.min.css?v=0" />
    	<script src="scripts/jquery-3.3.1.js"></script>
      	<script src="scripts/bootstrap.js"></script>
	    <link rel="stylesheet" href="css/global_media.css" type="text/css" />
    <!-- global javascript-->
	<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
	<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
	<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
	<!--[if gt IE 8]> <![endif]-->
	<!--[if lt IE 9]><meta http-equiv="X-UA-Compatible" content="IE=9"><![endif]-->
    <!-- <script src="scripts/html5shiv.js"  async></script>  -->
    <script src="scripts/respond.min.js"  async></script> <!-- used for IE8 and below-->
    <!-- <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE8.js"></script>  -->    
    <script type="application/rss+xml" title="Latest Torrents" src="/rss.php?torrent_pass=00007c675a5dca6aeeb1a6fa73695efa"></script>
    <!-- javascript goes here or in footer --><!-- css goes in header -->
        </head>
    <body class='background-5 skin-1 nb-1 panelhead-1 bootpanel-1 btable-1 btr-1 listgrp-1 buttonS-1 text-1'>
  <nav class='cb navbar-default navbar-fixed-top' role='navigation'>
   <div class='container'>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-exl-collapse'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
         <span class='icon-bar'></span>
      </button> 
     <a class='navbar-brand' href='https://torrentseeds.org/index.php'>TorrentSeeds</a>
    </div>
 <!-- Collect the nav links, forms, and other content for toggling -->
<div class='collapse navbar-collapse navbar-exl-collapse'>
        <ul class='nav navbar-nav navbar-right'>
		<div class='btn-group role=group'>
        <a class='btn btn-primary btn-success btn-sm type='button'' href='https://torrentseeds.org/donate.php'><i class='fa fa-eur fa-lg aria-hidden='true''></i>  Donate</a>
		
<a class='btn btn-primary btn-success btn-sm type='button'' href='https://torrentseeds.org/main.php' role='button'><i class='fa fa-home fa-lg aria-hidden='true''></i>  Home</a>

<div class='btn-group'>
<button class='btn btn-primary btn-sm dropdown-toggle' type='button' data-toggle='dropdown'>Browse
<span class='caret'></span></button>
 <!-- dropdown menu links -->
 <ul class='dropdown-menu pull-right'>
 <li><a class='dropdown-item' href='https://torrentseeds.org/browse.php?c2=1&c12=1&c8=1&c30=1&c7=1&c16=1&c29=1&c17=1&c47=1&c59=1&c60=1&c63=1&c66=1&c70=1&c71=1&search=&searchin=title&incldead=0'><i class='fa fa-gamepad' aria-hidden='true'></i> Games</a></li>
            <li><a class='dropdown-item' href='https://torrentseeds.org/browse.php?c31=1&c3=1&c19=1&c25=1&c39=1&c49=1&c50=1&c62=1&c69=1&c74=1&c76=1&search=&searchin=title&incldead=0'><i class='fa fa-film' aria-hidden='true'></i> Movies</a></li>
            <li><a class='dropdown-item' href='https://torrentseeds.org/browse.php?c33=1&c28=1&c34=1&c4=1&c20=1&search=&searchin=title&incldead=0'><i class='fa fa-music' aria-hidden='true'></i> Music</a></li>
            <li><a class='dropdown-item' href='https://torrentseeds.org/browse.php?c11=1&c23=1&c24=1&c18=1&c26=1&c61=1&c64=1&c36=1&c86=1&c35=1&c87=1&search=&searchin=title&incldead=0'><i class='fa fa-television fa-lg' aria-hidden='true'></i> TV Series</a></li>
            <li><a class='dropdown-item' href='https://torrentseeds.org/browse.php?c37=1&c9=1&c72=1&search=&searchin=title&incldead=0'>Anime</a></li>
            <li><a class='dropdown-item' href='https://torrentseeds.org/browse.php?c13=1&c1=1&c27=1&c32=1&search=&searchin=title&incldead=0'>Apps</a></li>
            <li><a class='dropdown-item' href='https://torrentseeds.org/browse.php?c35=1&c36=1&search=&searchin=title&incldead=0'>Sport</a></li>
            <li><a class='dropdown-item' href='https://torrentseeds.org/browse.php?c6=1&c53=1&c55=1&c=1&c88=1&c57=1&search=&searchin=title&incldead=0'>Porn</a></li>
			<li><a class='dropdown-item' href='https://torrentseeds.org/browse.php?c77=1&c78=1&c80=1&c81=1&c79=1&c82=1&c83=1&c84=1&c85=1&c68=1&c67=1&c65=1&search=&searchin=title&incldead=0'>Packs</a></li>
</ul>
</div>
  <a class='btn btn-primary btn-sm' href='https://torrentseeds.org/forums.php'>Forums</a>
<a class='btn btn-primary btn-sm' href='https://torrentseeds.org/tv_guide.php'><i class='fa fa-television fa-lg' aria-hidden='true'></i> TV Guide</a>

 <div class='btn-group'>
 <button class='btn btn-primary btn-sm dropdown-toggle' type='button' data-toggle='dropdown'>General
 <span class='caret'></span></button>
                                          
                                                <!-- dropdown menu links -->
												 <ul class='dropdown-menu pull-right'>

                        <li><a href='https://torrentseeds.org/faq.php'>FAQ</a></li>
                        <li><a href='https://torrentseeds.org/rules.php'>Rules</a></li>
                        <li><a href='https://torrentseeds.org/chat.php'>IRC</a></li>
                        <li><a href='https://torrentseeds.org/staff.php'>Staff</a></li>
                        <li><a href='https://torrentseeds.org/wiki.php'>Wiki</a></li>
                        <li><a href='https://torrentseeds.org/getrss.php'>Get Rss</a></li>
										</ul>
										</div>
                                <div class='btn-group'>
<button class='btn btn-primary btn-sm dropdown-toggle' type='button' data-toggle='dropdown'>Torrent
                                                <span class='caret'></span></button>

					  <ul class='dropdown-menu pull-right'>
						<!-- dropdown menu links -->
 	    <li><a href='https://torrentseeds.org/browse.php'>Torrents</a></li>
	    <li><a href='https://torrentseeds.org/needseed.php?needed=seeders'>Need Seeds</a></li>
		
		
        <li><a href='https://torrentseeds.org/bookmarks.php'>Bookmarks</a></li>
					  </ul>
					</div>
				<!-- <div class='btn-group'>
					  <button class='btn btn-primary btn-sm dropdown-toggle' type='button' data-toggle='dropdown'>Games
						<span class='caret'></span>
					  </button>
					  
					</div> -->
				<div class='btn-group'>
					  <button class='btn btn-primary btn-sm dropdown-toggle' type='button' data-toggle='dropdown'>Staff Tools
						<span class='caret'></span>
					  </button>
					  <ul class='dropdown-menu pull-right'>
						<!-- dropdown menu links -->
						   <li> <a class='brand' href='https://torrentseeds.org/bugs.php?action=add'>Report a bug</a></li>
							<li><a class='brand' href='https://torrentseeds.org/contactstaff.php'>Contact Staff</a></li>
							
					  </ul>
					</div>
				<div class='btn-group'>
					  <button class='btn btn-primary btn-sm dropdown-toggle' type='button' data-toggle='dropdown'>Pers Tools
						<span class='caret'></span>
					  </button>
					  <ul class='dropdown-menu pull-right'>
						<!-- dropdown menu links -->
		<li><a href='https://torrentseeds.org/pm_system.php'>Messages</a></li>
		<li><a href='https://torrentseeds.org/usercp.php?action=default'>Usercp</a></li>
 	    <!-- <li><a href='https://torrentseeds.org/friends.php'>Friends</a></li> -->
		<li class='divider'></li>
		<li>:: User Blocks Config<a href='./user_blocks.php'>My Blocks</a></li>
					  </ul>
					</div>
		<a class='btn btn-warning btn-sm' href='https://torrentseeds.org/logout.php?hash_please=f4c8a3da85a3cc556ad5cd6c106a4e37'><i class='fa fa-sign-out' aria-hidden='true'></i> Sign Out</a>
</div>
     </ul>
    </div><!-- /.navbar-collapse -->
</div></nav><div class="" style="background:rgba(0, 0, 0, 0.2);"><div class='text-center'><div class='text-left container'>Welcome <span style="white-space: nowrap;"><a class="user_31847" href="https://torrentseeds.org/userdetails.php?id=3xxxx" target="_blank"><span style="color:#8e35ef;"><strong></strong></span></a></span>
[USER]&nbsp;Achievements&nbsp;<a href='./achievementhistory.php?id=31847'>1</a>&nbsp;HnR: <a href='/my_snatches.php'>0</a>&nbspInvites: <a href='https://torrentseeds.org/invite.php'>0</a>&nbsp;Share Ratio&nbsp;<span style="color:#00ff00;">34.475</span>&nbsp;Uploaded:25.00 GB Downloaded:742.56 MB&nbsp;<span>Grab Seedbox:&nbsp;<a href='https://rentrapidbox.com/index.php/store/shared-seedbox'><i class='fa fa-desktop' style='color:lawngreen'></i>&nbsp;</a></span></div><div class='text-left container'></div></div></div>
    <!-- U-232 Source - Print Global Messages Start -->
    <div class='container'>
    <div class='sa-gm_taps_left'><ul class='sa-gm_taps'><li><b>Current Site Alerts:</b></li><li><a class='sa-tooltip' href='#'><b class='btn btn-info btn-sm'>Freeleech</b>
	<span class='custom info alert alert-info'><em>Freeleech sections now are:</em>Anime/SD, Apps/0DAY, Console/NSW, Console/PS3, Console/PSV, E-books, Games/DOX, Games/Rips, Movies/SD, Movies/SD-Foreign, Music/MVID, TV/SD, TV/SD-Retail, TV/SD-Sport, XXX/SD
	   </span></a></li></ul></div></div><br /><div class="container"> 
    <div id="control_panel"><a href="#" id="control_label"></a></div><table class='main' width='750' border='0' cellpadding='0' cellspacing='0'><tr><td class='embedded'>
<h2>No torrent with that ID</h2>
<table width='90%' border='1' cellspacing='0' cellpadding='10'><tr><td class='colhead2'>
We are sorry, but the torrent you are looking for has been deleted.</td></tr></table><p></p><p></p></td></tr></table>

        </div><!--  End main outer container -->
        <!-- Ends Footer -->
		<!-- localStorage for collapse -->
        <script src="scripts/jquery.collapse.localstorage.js"></script>
        </body></html>
```
2021-06-06 16:53:50 	Info 	

Torznab search in 1337x for Neo Magazin Royale S08E05 => Found 0 releases (from cache)

2021-06-06 16:53:50 	Info 	

Torznab search in HDME for Neo Magazin Royale S08E05 => Found 0 releases (from cache)

2021-06-06 16:53:50 	Info 	

Torznab search in TorrentLeech for Neo Magazin Royale S08E05 => Found 0 releases (from cache)

2021-06-06 16:53:50 	Info 	

Torznab search in IPTorrents for Neo Magazin Royale S08E05 => Found 0 releases (from cache)

2021-06-06 16:53:50 	Warn 	

Some of the categories provided are unsupported in HDME: 5030

2021-06-06 16:53:13 	Info 	

Test search in TorrentSeeds => Found 100 releases

2021-06-06 16:53:08 	Info 	

Test search in TorrentSeeds => Found 100 releases

2021-06-06 16:52:02 	Error 	

System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.TorrentSeeds.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentSeeds.cs:line 136
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Hmm. Looks like the indexer needs to be updated to handle the web site returning `We are sorry, but the torrent you are looking for has been deleted.` rather than the usual `Not Found`

**Comment by garfield69** [comment]
v0.18.259
