### ISSUE TITLE
[Retroflix] Exception (retroflix): Unknown error in search

### ISSUE THREAD

**Issue by Jerrk** [Jackett/Jackett#11881]
### Environment

**OS**: Unraid 6.9.2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.255

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes]

### Description
going to the url works as expected with no errors showing up but it does not work within jackett and it appears that the error message within jackett is also messed up.
Clicking "test" throws me the error.

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (retroflix): Unknown error in search: <!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="robots" content="noindex,nofollow,noarchive" />
    <title>An Error Occurred: Internal Server Error</title>
    <style>body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
.container { margin: 30px; max-width: 600px; }
h1 { color: #dc3545; font-size: 24px; }
h2 { font-size: 18px; }</style>
</head>
<body>
<div class="container">
    <h1>Oops! An Error Occurred</h1>
    <h2>The server returned a "500 Internal Server Error".</h2>

    <p>
        Something is broken. Please let us know what you were doing when this error occurred.
        We will fix it as soon as possible. Sorry for any inconvenience caused.
    </p>
</div>
</body>
</html>
 ---> System.Exception: Unknown error in search: <!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="robots" content="noindex,nofollow,noarchive" />
    <title>An Error Occurred: Internal Server Error</title>
    <style>body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
.container { margin: 30px; max-width: 600px; }
h1 { color: #dc3545; font-size: 24px; }
h2 { font-size: 18px; }</style>
</head>
<body>
<div class="container">
    <h1>Oops! An Error Occurred</h1>
    <h2>The server returned a "500 Internal Server Error".</h2>

    <p>
        Something is broken. Please let us know what you were doing when this error occurred.
        We will fix it as soon as possible. Sorry for any inconvenience caused.
    </p>
</div>
</body>
</html>
   at Jackett.Common.Indexers.Abstract.SpeedAppTracker.PerformQuery(TorznabQuery query) in /tmp/makepkg/jackett/src/Jackett-0.18.255/src/Jackett.Common/Indexers/Abstract/SpeedAppTracker.cs:line 114
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.18.255/src/Jackett.Common/Indexers/BaseIndexer.cs:line 385
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.18.255/src/Jackett.Common/Indexers/BaseIndexer.cs:line 393
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.18.255/src/Jackett.Common/Indexers/BaseIndexer.cs:line 735
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /tmp/makepkg/jackett/src/Jackett-0.18.255/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.Test() in /tmp/makepkg/jackett/src/Jackett-0.18.255/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /tmp/makepkg/jackett/src/Jackett-0.18.255/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

![](https://i.imgur.com/Uqg6Kdl.png)

**Comment by garfield69** [comment]
The RetroFlix indexer uses the SpeedAppTracker abstract to use site's API for its queries, which is why checking the web site using the regular browse page (https://retroflix.club/browse) is not a true check on the state of the service.
This is the keywordless search (which is also used when you press the Jackett TEST button)
```
https://retroflix.club/api/torrent?itemsPerPage=100&sort=torrent.createdAt&direction=desc&search=
```
IF the Site's API server is responding 500 then most likely something is wrong at the RetroFlix API end.

The SpeedApp indexer which uses the same SpeedAppTracker abstract is working fine using the same API parameters but on the SpeedApp site's API.

@ngosang  are you having issues using the RetroFlix indexer, can you assist in determining the issue?

**Comment by ngosang** [comment]
@costyglx we are having issues with RetroFlix API. The itemsPerPage param can't be set to 100 as we need for Jackett. Could you take a look?

KO => https://retroflix.club/api/torrent?itemsPerPage=100&sort=torrent.createdAt&direction=desc&search=
OK => https://retroflix.club/api/torrent?itemsPerPage=90&sort=torrent.createdAt&direction=desc&search=

**Comment by ngosang** [comment]
@garfield69 If this is fixed by @costyglx you can revert the temporary fix => #11914

**Comment by garfield69** [comment]
v0.18.317

**Comment by ilike2burnthing** [comment]
@costyglx are you able to resolve this?

@Jerrk may be worth contacting site admins to make them aware of the issue.

**Comment by garfield69** [comment]
v0.20.1250
