### ISSUE TITLE
[lostfilm] Exception (lostfilm): The operation was canceled.: Parse error (Test)

### ISSUE THREAD

**Issue by minduxntep** [Jackett/Jackett#11908]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:v0.18.259

**Last Working Jackett Version**:v0.18.259

**Are you using a proxy or VPN?** [yes/no] yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Add indexer Lostfilm.tv , with site link "www.lostfilm.tv".  Set correct FlareSolverr API URL.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]
```
Jackett.Common.IndexerException: Exception (lostfilm): The operation was canceled.
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 570
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 658
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 478
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 761
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 490
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 437
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 761
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 443
   at Jackett.Common.Indexers.LostFilm.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 234
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 385
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 393
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 735
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

===============================================================
Error on 20210612233649 for LostFilm.tv.txtSystem.Exception: Parse error
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 570
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 658
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 478
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 761
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 490
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 437
```
**After that going full html of www.lostfilm.tv**

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
try switching to other alternate silt links. I use https://www.lostfilmtv.site/
Note, when switching sites, you are going to fail the captcha text challenge as it will have been loaded from the prior site.
so after failure, close and open the config again in order to load a fresh challenge on the new site.

**Comment by minduxntep** [comment]
I`ve try every sitelink. From PC it works fine.

**Comment by garfield69** [comment]
>From PC it works fine.

you mean, from a browser on the PC it works fine, but from your Docket Jackett its does not?

**Comment by minduxntep** [comment]
> > From PC it works fine.
> 
> you mean, from a browser on the PC it works fine, but from your Docket Jackett its does not?

Yes, that right

**Comment by garfield69** [comment]
@ilike2burnthing  another one for your specialty area... not my cup of tea. Can you help?

**Comment by ilike2burnthing** [comment]
Are you using your email address or username?

**Comment by minduxntep** [comment]
> Are you using your email address or username?

email

**Comment by ilike2burnthing** [comment]
Are other indexers working for you in your Docker Jackett install?

Have you tested installing Jackett on your PC to see if it works there?

**Comment by minduxntep** [comment]
Other indexers are working. On my PC, with installed Jackett i can`t even add Lostfilm indexer

`



2021-06-13 05:17:18 | Error | System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.  ---&gt; System.IO.IOException: Unable to read data from the transport connection: Удаленный хост принудительно разорвал существующее подключение..  ---&gt; System.Net.Sockets.SocketException (10054): Удаленный хост принудительно разорвал существующее подключение.    --- End of inner exception stack trace ---    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)    at System.Net.Security.SslStream.&lt;FillHandshakeBufferAsync&gt;g__InternalFillHandshakeBufferAsync\|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)    at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 185    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 570    at Jackett.Common.Indexers.LostFilm.GetConfigurationForSetup() in D:\a\1\s\src\Jackett.Common\Indexers\LostFilm.cs:line 143    at Jackett.Server.Controllers.IndexerApiController.Config() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 79    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeInnerFilterAsync&gt;g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeFilterPipelineAsync&gt;g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeAsync&gt;g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.&lt;Invoke&gt;g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
-- | -- | --




`

**Comment by ilike2burnthing** [comment]
Does it work in Jackett without the VPN? Can you access it from your PC using the same VPN server?

Also see - https://github.com/Jackett/Jackett/wiki/Troubleshooting#authentication-failed-because-the-remote-party-has-closed-the-transport-stream

**Comment by minduxntep** [comment]
Another indexer is Rutracker.org, it works fine from PC and from linux docker.
Indexer Lostfilm.tv with sitelink lostfilm.tv doesnt work without VPN neither on win PC nor linux docker.
Indexer Lostfilm.tv with sitelink lostfilmtv.site work on win PC without VPN, and from linux host.

Now indexer Lostfilm.tv with sitelink lostfilm.tv give me this exception:
`



2021-06-13 14:16:06 | Error | Jackett.Common.ExceptionWithConfigData: {"error":1,"result":"ok"}    at Jackett.Common.Indexers.LostFilm.&lt;&gt;c__DisplayClass26_0.&lt;ApplyConfiguration&gt;b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 197    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 245    at Jackett.Common.Indexers.LostFilm.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 190    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.&lt;InvokeInnerFilterAsync&gt;g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeFilterPipelineAsync&gt;g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.&lt;InvokeAsync&gt;g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.&lt;Invoke&gt;g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
-- | -- | --




`

**Comment by ilike2burnthing** [comment]
Using the same VPN server on your computer, access the site links in your browser to see if they work. If not, that's your issue, and you should try changing the server. If they do work in browser, but not for Jackett, provide enhanced logs of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by minduxntep** [comment]
They work with VPN on my PC.
Logs https://pastebin.com/dyvJuWKX

**Comment by ilike2burnthing** [comment]
Is FlareSolverr behind the same VPN? If not, it needs to be for the cookies to be valid.

**Comment by minduxntep** [comment]
VPN on my router. Everyone in my network behind vpn.

**Comment by ilike2burnthing** [comment]
In that case you'll need to disable IPv6 for the Jackett and FlareSolverr containers - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

**Comment by minduxntep** [comment]
Did it yesterday.

**Comment by ilike2burnthing** [comment]
As a test of FlareSolverr, add the indexer BTDB and see if you can successfully run a test on it.

**Comment by minduxntep** [comment]
Exception (btdb): Connection reset by peer: The SSL connection could not be established, see inner exception.

**Comment by minduxntep** [comment]
with sitelink https://btdb.unblockit.li/ it works

**Comment by minduxntep** [comment]
If btdb behind firewall then "Exception (btdb): The cookies provided by FlareSolverr are not valid: The cookies provided by FlareSolverr are not valid"

**Comment by ilike2burnthing** [comment]
To confirm the issue lies with FlareSolverr, add 1337x (if you don't have it already), change the site link to the *.unblockit.li proxy, and run a test.

**Comment by ilike2burnthing** [comment]
What do you mean about BTDB behind your firewall?

**Comment by minduxntep** [comment]
> What do you mean about BTDB behind your firewall?

Not all my traffic goes to VPN, just DNS and some sites that are blocked in my country

**Comment by minduxntep** [comment]
1337x work.

**Comment by ilike2burnthing** [comment]
Where cookies are needed (probably just semi-private and private indexers, as well those using FlareSolverr), all traffic to and from Jackett and FlareSolverr will either need to go through the VPN or not, not just selective parts.

As a test I'd suggest either disabling the VPN completely, or use a separate network (e.g. mobile data from your phone hotspot if your computer has WiFi), and see if your issue stops. If so, connect to the VPN on your computer (e.g. using a local client or OVPN file), and again see if the issue stops. If so, the issue lies in your current setup.
