### ISSUE TITLE
jackett + flaresolver doesn't work with vpn

### ISSUE THREAD

**Issue by alant54** [Jackett/Jackett#11939]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: debian 10 

**.Net Runtime**: 

**.Net Version**:

**Jackett Version**: v0.18.359

**Last Working Jackett Version**: no one

**Are you using a proxy or VPN?** yes

image docker : linuxserver/jackett:latest

### Description

Hi, i try to use ygg with a vpn. When i set up jackett + flaresolver without vpn its working perfectly, 
but when i try to use flaresolver and jackett with a vpn it doesn't work and i have all the time the error "The operation was cancelled.".

For the vpn, i use flaresolver and jakcett with docker and then i route my traffic with gluetun 

All indexer without need of flaresolver is working with a vpn.
I have already tried to use ygg with my browser + the vpn i use with jackett and it is working.
An other strange things is that with the vpn up when i make a request from jackett, flaresolver has no logs of requests.

I'dont know if i have missed some things with the setup of jackett with vpn but i thing it's a bug.
I hope someone can help me.

### Logged Error Messages

Exception in GetConfigurationForSetup (yggtorrent): System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 570
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 868

**Comment by ilike2burnthing** [comment]
What are you using for your FlareSolver API URL in Jackett? Is it accessible when you use your VPN?

**Comment by alant54** [comment]
I use my server local device IP and yes when i use the vpn and try to access it with my browser i still have the message "FlareSolverr is ready!"

**Comment by ilike2burnthing** [comment]
Try changing to container IP (e.g. 172.17.0.2) or container name (depending on how you have it set up).

**Comment by alant54** [comment]
I have switch to the container ip and now it's working. I don't know why I didn't think of it before... thanks for your help !
