### ISSUE TITLE
[demonoid] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by baldeaglejrk** [Jackett/Jackett#11967]
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] .Net Framework

**.Net Version**: 4.8

**Jackett Version**: v0.18.372

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?** [yes/no] Yes, Nord VPN

### Description

Added Demonoid using the instructions to get cookie. Get "Found no results while trying to browse this tracker" when clicking Test. 

Demonoid has updated its website, so that may potentially be a factor. Willing to give an invite code if needed, for testing.

### Logged Error Messages

Found no results while trying to browse this tracker

System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 312
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

**Comment by garfield69** [comment]
the indexer is working for me, although the download needs fixing as that has changed.
I expect you are having issues with your cookie because of your vpn.
are you fetching the cookie via the vpn on a browser running on the same os that is running jackett?

**Comment by garfield69** [comment]
ok, so today the site has made `Demonoid - v5` the **default** theme, which the indexer currently does not support, causing 0 results.
I will update the indexer to support v5 and drop v3 (cannot support both).

**Comment by baldeaglejrk** [comment]
Yeah, I think that's what caused it
________________________________

**Comment by garfield69** [comment]
v0.18.386
