### ISSUE TITLE
[broadcasthenet] Exception (broadcasthenet): Error connecting to FlareSolverr server: FlareSolverrSharp.Exceptions.FlareSolverrException: Unimplemented POST Content-Type: application/json-rpc

### ISSUE THREAD

**Issue by lyz-code** [Jackett/Jackett#11975]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Linuxserver Docker in Debian with id 8aa16aabb603

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.385 and v0.18.383

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

BTN started using cloudflare, so I configured Flaresolverr to bypass it. I also used docker to deploy it, but when I `Test` the tracker an error is returned.

The `FlareSolverr API URL: ` configuration is set to `http://flaresolverr:8191`, and if I get into the jackett docker with `docker exec -it jackett bash` the connection works as expected:

```
root@ff5ec0308566:/# curl http://flaresolverr:8191
{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1624958322986,"endTimestamp":1624958322986,"version":"v1.2.8"}

root@ff5ec0308566:/# curl http://172.20.1.35:8191
{"status":"ok","message":"FlareSolverr is ready!","startTimestamp":1624958895968,"endTimestamp":1624958895968,"version":"v1.2.8"}
```

I've tried setting it to `http://172.20.1.35:8191` (the flaresolverr docker's IP) and `http://127.0.0.1:8191` but had the same error.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

```
Jackett.Common.IndexerException: Exception (broadcasthenet): Error connecting to FlareSolverr server: FlareSolverrSharp.Exceptions.FlareSolverrException: Unimplemented POST Content-Type: application/json-rpc
   at FlareSolverrSharp.Solvers.FlareSolverr.GenerateFlareSolverrRequest(HttpRequestMessage request)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Error connecting to FlareSolverr server: FlareSolverrSharp.Exceptions.FlareSolverrException: Unimplemented POST Content-Type: application/json-rpc
   at FlareSolverrSharp.Solvers.FlareSolverr.GenerateFlareSolverrRequest(HttpRequestMessage request)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 588
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass11_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 565
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 564
   at Jackett.Common.Indexers.BroadcasTheNet.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BroadcasTheNet.cs:line 128
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 399
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 411
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 753
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
Add 1337x, change the site link to `https://1337x.unblockit.li/`, click okay and run a test. Do you get the same FlareSolverr error?

**Comment by lyz-code** [comment]
Thanks for the quick answer @ilike2burnthing , nope, configuring 1337x that way returned a successful answer

**Comment by ilike2burnthing** [comment]
@RoloSoze / @janot / @seeyabye can you confirm this issue?

@ngosang I'd assume this is an issue for FlareSolverr rather than something which needs to be resolved with the indexer here:
https://github.com/Jackett/Jackett/blob/2e4a164f08588fb445fac9e0e1cd414dfdfcc233/src/Jackett.Common/Indexers/BroadcasTheNet.cs#L128-L134

**Comment by garfield69** [comment]
i'm seeing
![image](https://user-images.githubusercontent.com/6933240/123860217-b8d26b00-d979-11eb-96c1-7ad465e0b5a2.png)

**Comment by garfield69** [comment]
the site is back up (or at least the login page is now present).
Please check that the indexer is working or if you still get the same failure as reported at the beginning of this ticket.

**Comment by seeyabye** [comment]
Just tested it and there're no issues on my end.

I'm not using FlareSolverr and I'm not encountering any Cloudflare checks, so I can't verify this part.

**Comment by lyz-code** [comment]
I can confirm it, thank you :)
