### ISSUE TITLE
[ShizaProject] Exception (ShizaProject): Index was outside the bounds of the array.: Index was outside the bounds of the array. (Test)

### ISSUE THREAD

**Issue by kekal** [Jackett/Jackett#11989]
### Environment

**Jackett Version**: v0.18.390  (docker)

**Are you using a proxy or VPN?**: no

### Description

@ngosang, looks like Shizaproject has another issue. Simple HTTP queries like https://shiza-project.com/releases?query=2 still work fine.
If it is a temporal problem, I will close the ticket.

#### In case of query:
```
Jackett.Common.IndexerException: Exception (ShizaProject): Index was outside the bounds of the array.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Jackett.Common.Indexers.ShizaProject.PerformQuery(TorznabQuery query)
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 756
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 432
```
#### In case of test:
```
Jackett.Common.IndexerException: Exception (ShizaProject): Index was outside the bounds of the array.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Jackett.Common.Indexers.ShizaProject.PerformQuery(TorznabQuery query)
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 756
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
it appears to me that the indexer is expecting all results to be fully populated, such as 
```json
{"node":{"name":"Моя геройская академия 5","originalName":"Boku no Hero Academia 5th Season","alternativeNames":["僕のヒーローアカデミア","My Hero Academia 5"],"publishedAt":"2021-07-04T07:01:41.279Z","slug":"boku-no-hero-academia-5th-season-tv-5","posters":[{"preview":{"url":"https://cdn.shiza-project.com/resize/PImGVB2fUAy54vYIsM17Vg/rs:fit:360:500/bG9jYWw6Ly8vMGMvMDYvNTAvMGMwNjUwZWJiZmM3NTlkNmRjYTBiMDNjNmZmMjdmZDExZTkyYzk4ZS53ZWJw.webp"}}],"torrents":[{"downloaded":40,"seeders":4,"leechers":3,"size":"7297184445","magnetUri":"magnet:?xt=urn:btih:e20c4995cf5ee2555f17c1d79de5da3d576ec782&tr=udp%3A%2F%2Ftr.shiza-project.com%3A6881%2Fannounce&tr=http%3A%2F%2Ftr.shiza-project.com%3A6881%2Fannounce","updatedAt":"2021-07-04T07:00:09.036Z","file":{"url":"https://cdn.shiza-project.com/files/453a214c308c8eb29a114e4c9a2564e0a8321a26.torrent?filename=[SHIZA Project] Boku no Hero Academia TV5 [WEBRip 1080p].torrent"},"videoQualities":["WEB_RIP","RESOLUTION_1080P"]}]}},
```
but one of the records returned by the sites api is 
```json
{"node":{"name":"Дракон-горничная госпожи Кобаяси 2","originalName":"Kobayashi-san Chi no Maid Dragon S","alternativeNames":[],"publishedAt":null,"slug":"kobayashi-san-chi-no-maid-dragon-s-other","posters":[],"torrents":[]}},
```
so the indexer may need recoding to handle incomplete records.

**Comment by garfield69** [comment]
v0.18.402

**Comment by kekal** [comment]
`Test search in ShizaProject => Found 44 releases`

Tested successfully

@garfield69 thanks!
