### ISSUE TITLE
[REQ] animeworld

### ISSUE THREAD

**Issue by oekos** [Jackett/Jackett#12022]
https://animeworld.cx/   is  inside  the jackett 

can you add the option for api login ?

**Comment by garfield69** [comment]
None of the current team have an account on animeworld.
Now that Jackett's cardigann can support processing API responses that return JSON (which this site's unit3d 5.3.0 engine should be genrating),
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go building a cardigann indexer API.

**Comment by rakuri255** [comment]
Its not working.

An error occurred while testing this indexer
Exception (animeworld-api): Error while parsing field=category, selector=category, value=Anime Serien: Object reference not set to an instance of an object.: Error while parsing field=category, selector=category, value=Anime Serien: Object reference not set to an instance of an object.

**Comment by ilike2burnthing** [comment]
Please provide the HTML of https://animeworld.cx/torrents - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by rakuri255** [comment]
2021-12-04 01:48:02.9335 Error Jackett.Common.IndexerException: Exception (animeworld-api): Error while parsing field=category, selector=category, value=Anime Serien: Object reference not set to an instance of an object.
 ---> System.Exception: Error while parsing field=category, selector=category, value=Anime Serien: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1448
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 758
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.IndexerException: Exception (animeworld-api): Error while parsing field=category, selector=category, value=Anime Serien: Object reference not set to an instance of an object.
 ---> System.Exception: Error while parsing field=category, selector=category, value=Anime Serien: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1448
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 758
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by ilike2burnthing** [comment]
> Please provide the HTML of https://animeworld.cx/torrents - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

Please read the instructions provided.

**Comment by garfield69** [comment]
@oekos  , @rakuri255 we cannot make any progress with this unless one of you  provides the HTML from the web site's torrent search page. Once we have that then we can bring the categories in the indexer up to date.

so:
- access the web site's torrent page at https://animeworld.cx/torrents
- Right click, and select save page as HTML, (use txt extension)
- Remove personal information (username, password, passkey, hashes, IP address etc) from the HTML file (without breaking the code)
- Drag/drop the txt file into the body of this ticket

**Comment by ilike2burnthing** [comment]
@oekos / @rakuri255 ping

**Comment by fnk93** [comment]
It could probably be the mismatch of category names.
| Category ID | Category Name |
| ------------ | ---------------- |
| 1 | "Anime Filme" |
| 2 | "Anime Serien" |
| 3 | "Anime Musik / OSTs" |
| 4 | "Anime Spiele" |
| 5 | "Anime Hentai" |
| 6 | "Software" |
| 7 | "Sonstiges" |
| 8 | "Filme" |
| 9 | "Serien" |
| 10 | "Spiele" |
| 11 | "Musik" |
| 12 | "Manga" |
| 13 | "Cartoon Filme" |
| 14 | "Cartoon Serie" |
| 15 | "H-Manga / Doujinshi" |

**Comment by garfield69** [comment]
@fnk93  Excellent. Finally some one provided the list I have been wanting for!
I'll update the indexer based on the category names you provided. Thanks.

**Comment by garfield69** [comment]
v0.20.266

**Comment by ilike2burnthing** [comment]
https://animeworld.cx/ - Maintenance

**Comment by ilike2burnthing** [comment]
back up
