### ISSUE TITLE
[lostfilm] Exception (lostfilm): The cookies provided by FlareSolverr are not valid: Parse error (Config)

### ISSUE THREAD

**Issue by uchuu-me** [Jackett/Jackett#12053]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker (hotio/jackett)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.18.455

**Last Working Jackett Version**: 0.18.455

**Are you using a proxy or VPN?** yes

### Description

Add indexer Lostfilm.tv , with site link "www.lostfilm.tv". Set correct FlareSolverr API URL.

### Logged Error Messages

Exception (lostfilm): The cookies provided by FlareSolverr are not valid: Parse error

```
Jackett.Common.IndexerException: Exception (lostfilm): The cookies provided by FlareSolverr are not valid
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 592
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 658
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 478
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 779
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 490
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 437
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 779
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 443
   at Jackett.Common.Indexers.LostFilm.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 234
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 399
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 411
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 753
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by vchunikhin** [comment]
I have exactly same issue here.

**Comment by garfield69** [comment]
Use your jackett dashboard to edit the config of the indexer and try out any and all of the other site links and see what you get.
Remember that you may need to try each site twice, as the first time you switch, if the new site needs a captcha text, then the first challenge image will be from the old site. so close, edit and try again.

**Comment by ilike2burnthing** [comment]
Is FlareSolverr also behind the same VPN?

**Comment by uchuu-me** [comment]
FlareSolverr use same VPN. I have already tried to add and remove lostfilm indexer about 10 times and reconfiger it twice or more on each try.

**Comment by ilike2burnthing** [comment]
Test 1 - disable the VPN and try again

Test 2 - disable IPv6 for both containers and try again

**Comment by MaLaH88** [comment]
Having the same issue, but I'm not using VPN

#12146
