### ISSUE TITLE
[xwtorrents] FlareSolverrException: Unsupported POST Content-Type

### ISSUE THREAD

**Issue by dRuEFFECT** [Jackett/Jackett#12051]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Unraid (Version: 6.9.1)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.448

**Last Working Jackett Version**: v0.18.448

**Are you using a proxy or VPN?** [yes/no] no

### Description

XWT was working fine until a few weeks ago (or so i just noticed then) but now is getting hit by cloudfare errors. installed Flaresolverr and seems to be working fine but getting this error when trying to configure it in Jackett with my credentials

### Logged Error Messages

FlareSolverrSharp.Exceptions.FlareSolverrException: Error connecting to FlareSolverr server: FlareSolverrSharp.Exceptions.FlareSolverrException: Unsupported POST Content-Type: application/x-www-form-urlencoded
   at FlareSolverrSharp.Solvers.FlareSolverr.GenerateFlareSolverrRequest(HttpRequestMessage request)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 606
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 541
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 965
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

### Screenshots
![image](https://user-images.githubusercontent.com/7904175/126084912-d61450aa-568f-4137-a11d-3eb4e71f5731.png)
![image](https://user-images.githubusercontent.com/7904175/126084287-5bfd5bd4-b752-434c-9f02-3156cd1ad4a5.png)
![image](https://user-images.githubusercontent.com/7904175/126084711-089bfa03-707c-48c4-ae75-66f67ec01674.png)

**Comment by garfield69** [comment]
I dont think this is an issue with XWT as much as it is an issue with JAckett not communicating with flaresolver.
check your jackett dashboard, have you set the flaresolver api url to `http://127.0.0.1:8191` and clicked on the apply server settings button?
are you running both jackett and flaresolver natively on your unraid box?

**Comment by dRuEFFECT** [comment]
> I dont think this is an issue with XWT as much as it is an issue with JAckett not communicating with flaresolver.
> check your jackett dashboard, have you set the flaresolver api url to `http://127.0.0.1:8191` and clicked on the apply server settings button?
> are you running both jackett and flaresolver natively on your unraid box?

Yes and yes. I haven't needed to bypass cloudfare before so i don't know if it's specific to this tracker. Is there a public tracker i can test with? I believe i set up the flaresolverr container correctly, but maybe i missed something?

![image](https://user-images.githubusercontent.com/7904175/126245311-3ce9add3-f441-4627-af4b-6607a79ba9ef.png)
![image](https://user-images.githubusercontent.com/7904175/126245393-39cbd874-0afe-4fb3-ab7b-74b88a9247e5.png)
![image](https://user-images.githubusercontent.com/7904175/126245469-1f791db1-7aeb-4601-b4b1-94519867a69b.png)

**Comment by garfield69** [comment]
@ilike2burnthing  linux, flaresolverr, none of my favourite things... can you help?

**Comment by garfield69** [comment]
@dRuEFFECT I thought you said you were running flaresolverr natively, why am I seeing a container id?
are you using docker?

**Comment by garfield69** [comment]
have you tried setting up jackett flaresolverrs api url as http://192.168.1.69:8191 or 172.17.0.9 ?

**Comment by dRuEFFECT** [comment]
> @dRuEFFECT I thought you said you were running flaresolverr natively, why am I seeing a container id?
> are you using docker?

sorry, i was thinking "natively" in terms of unraid os, which would be in a docker.

i believe the issue is tracker specific. i previously deleted the tracker out of the config to try and re-set it up fresh, and that deleted the xwtorrents.json, and since i'm receiving this error on the config screen it's not creating the json. i manually pieced together the json file and relaunched jackett to play with the config there. 

when i go to the configure screen and hit Okay, i get the error i originally posted
![image](https://user-images.githubusercontent.com/7904175/126250704-6dbae70c-b6ea-4388-9540-9b3a1e2164c8.png)

even tho it errors, i notice actually saves the password to the json file correctly, and all the other fields are there as well so i believe the manual generated json is valid.

so i close out of the configure screen and click Test, I get this error instead....
![image](https://user-images.githubusercontent.com/7904175/126250950-ae122f5c-35d1-4a05-ac26-415c1c04398f.png)

flaresolverr logs show things went well, so it's certainly not a connection issue...
![image](https://user-images.githubusercontent.com/7904175/126251018-c1393149-b947-4bc2-99ea-d7041a008c24.png)

on the Flaresolverr github I now found this open ticket that this is clearly related to...
https://github.com/FlareSolverr/FlareSolverr/issues/169

it's odd that from the configure screen it's not actually hitting Flaresolverr, but the test button does. maybe that's part of the reason the tracker isn't working altogether?

**Comment by ilike2burnthing** [comment]
Add 1337x, change the site link to the unblockit.uno proxy and run a test with it. If it works fine then the issue is indexer specific, or rather it's indexer specific for some users, because it's working fine for me.

Provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by dRuEFFECT** [comment]
hmmm.. i tried 1337x with the variant link as you described and I'm getting the same cookies not valid error when hitting the test button.
![image](https://user-images.githubusercontent.com/7904175/126371146-af71b0a7-a788-46e2-b814-4e5a42fa3ddb.png)

i've been reading up on some issues regarding ipv6 (which I don't think applies to my setup) but regardless I tried adding 
these extra parameters to the flaresolverr docker, still no success.
![image](https://user-images.githubusercontent.com/7904175/126371470-3ba0eba1-02db-4df6-8fe3-0187e47d43b0.png)

flaresolverr logs looking good...
`2021-07-20T14:00:56-04:00 INFO REQ-11 Incoming request: POST /v1
20T14:00:56-04:00 INFO REQ-11 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://1337x.unblockit.uno/cat/Movies/time/desc/1/","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
2021-07-20T14:00:57-04:00 INFO REQ-11 Cloudflare detected
2021-07-20T14:00:57-04:00 INFO REQ-11 Cloudflare detected
2021-07-20T14:01:13-04:00 INFO REQ-11 Challenge solved.
2021-07-20T14:01:13-04:00 INFO REQ-11 Response in 16.796 s`

jackett enhanced logging here...
`
<html>
<body>


Date | Level | Message
-- | -- | --
2021-07-20 14:01:19 | Debug | Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2021-07-20 14:01:19 | Debug | Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2021-07-20 14:01:19 | Info | Authorization was successful.
2021-07-20 14:01:19 | Debug | Execution plan of result filters (in the following order): None
2021-07-20 14:01:19 | Debug | Execution plan of exception filters (in the following order): None
2021-07-20 14:01:19 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2021-07-20 14:01:19 | Debug | Execution plan of resource filters (in the following order): None
2021-07-20 14:01:19 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2021-07-20 14:01:19 | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (jackett).
2021-07-20 14:01:19 | Info | Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
2021-07-20 14:01:19 | Debug | Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
2021-07-20 14:01:19 | Debug | Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'
2021-07-20 14:01:19 | Debug | 1 candidate(s) found for the request path '/api/v2.0/server/logs'
2021-07-20 14:01:19 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2021-07-20 14:01:19 | Debug | The request path /api/v2.0/server/logs does not match a supported file type
2021-07-20 14:01:19 | Debug | Request is continuing in applying rules. Current url is http://192.168.1.69:9117/jackett/api/v2.0/server/logs?_=1626803838552
2021-07-20 14:01:19 | Debug | Request is continuing in applying rules. Current url is http://192.168.1.69:9117/jackett/api/v2.0/server/logs?_=1626803838552
2021-07-20 14:01:19 | Debug | Request is continuing in applying rules. Current url is http://192.168.1.69:9117/jackett/api/v2.0/server/logs?_=1626803838552
2021-07-20 14:01:19 | Info | Request starting HTTP/1.1 GET http://192.168.1.69:9117/jackett/api/v2.0/server/logs?_=1626803838552 - -
2021-07-20 14:01:13 | Info | Request finished HTTP/1.1 POST http://192.168.1.69:9117/jackett/api/v2.0/indexers/1337x/test - 0 - 500 - application/json 16954.7822ms
2021-07-20 14:01:13 | Debug | Connection id "0HMABKLTQ2FHS" completed keep alive response.
2021-07-20 14:01:13 | Debug | The response will be compressed with 'gzip'.
2021-07-20 14:01:13 | Error | Jackett.Common.IndexerException: Exception (1337x): The cookies provided by FlareSolverr are not valid  ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 592    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1327    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 756    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2021-07-20 14:01:13 | Info | Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2021-07-20 14:01:13 | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 16934.3929ms
2021-07-20 14:01:13 | Debug | Saving new config file: /config/Jackett/Indexers/1337x.json.c75dee392cbf48a8bd80e68144e56682.tmp
2021-07-20 14:00:56 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://1337x.unblockit.uno/cat/Movies/time/desc/1/)
2021-07-20 14:00:56 | Debug | CACHE IsCacheEnabled => false
2021-07-20 14:00:56 | Debug | Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2021-07-20 14:00:56 | Debug | Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2021-07-20 14:00:56 | Info | Authorization was successful.
2021-07-20 14:00:56 | Debug | Execution plan of result filters (in the following order): None
2021-07-20 14:00:56 | Debug | Execution plan of exception filters (in the following order): None
2021-07-20 14:00:56 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2021-07-20 14:00:56 | Debug | Execution plan of resource filters (in the following order): None
2021-07-20 14:00:56 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2021-07-20 14:00:56 | Info | Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2021-07-20 14:00:56 | Info | Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2021-07-20 14:00:56 | Debug | Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2021-07-20 14:00:56 | Debug | Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/1337x/test'
2021-07-20 14:00:56 | Debug | 1 candidate(s) found for the request path '/api/v2.0/indexers/1337x/test'
2021-07-20 14:00:56 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2021-07-20 14:00:56 | Debug | POST requests are not supported
2021-07-20 14:00:56 | Debug | Request is continuing in applying rules. Current url is http://192.168.1.69:9117/jackett/api/v2.0/indexers/1337x/test
2021-07-20 14:00:56 | Debug | Request is continuing in applying rules. Current url is http://192.168.1.69:9117/jackett/api/v2.0/indexers/1337x/test
2021-07-20 14:00:56 | Debug | Request is continuing in applying rules. Current url is http://192.168.1.69:9117/jackett/api/v2.0/indexers/1337x/test
2021-07-20 14:00:56 | Info | Request starting HTTP/1.1 POST http://192.168.1.69:9117/jackett/api/v2.0/indexers/1337x/test - 0


</body>
</html>`

**Comment by ilike2burnthing** [comment]
This may be a fairly sporadic and annoying issue for FlareSolverr, as previously it happened to me for a different indexer and then just magically resolved itself without me doing anything.

I'd suggest opening an issue on [FlareSolverr/FlareSolverr](https://github.com/FlareSolverr/FlareSolverr/), link to this issue, and provide the debug and HTML FlareSolverr logs for when you try to add xwtorrents.

**Comment by dRuEFFECT** [comment]
> it's working fine for me

when you say it's working fine, do you mean 1337x or XWT? if you're using XWT through FlareSolverr without issue, I'm curious if you'd have any issues recreating the XWT config from scratch. I'm finding it's not even pinging FlareSolver and not saving the encoded credentials.

**Comment by ilike2burnthing** [comment]
Signing into XWT from scratch while using FlareSolverr works fine for me, but I'm not getting any challenge.

**Comment by ngosang** [comment]
I'm not getting a Cloudflare challenge for this site so I can not reproduce the issue. The site is working fine without Cloudflare.

**Comment by dRuEFFECT** [comment]
then what the heck is going on with things on my side? everything was fine until about a month ago when jackett just stopped working with this indexer.... if there's no challenge, why does jackett suddenly start telling me i need flaresolverr

deleting the XWT config and removing the flaresolver url, i get this when trying to re-add XWT as new.
without flaresolverr....
![image](https://user-images.githubusercontent.com/7904175/127821715-a357253e-761f-4138-a5e6-2f91de4c2e08.png)

`
<html>
<body>


2021-08-02 03:30:25 | Info | Request finished HTTP/1.1 POST http://192.168.1.69:9117/jackett/api/v2.0/indexers/xwtorrents/config application/json 346 - 500 - application/json 94.5604ms
-- | -- | --
2021-08-02 03:30:25 | Debug | Connection id "0HMALCU3T2MLQ" completed keep alive response.
2021-08-02 03:30:25 | Debug | The response will be compressed with 'gzip'.
2021-08-02 03:30:25 | Error | FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208    at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 606    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 541    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 965    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2021-08-02 03:30:25 | Info | Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2021-08-02 03:30:25 | Info | Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 77.6072ms
2021-08-02 03:30:25 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://xtremewrestlingtorrents.net/takelogin.php PostData: {username=redacted, password=redacted, returnto=/} RawBody: )
2021-08-02 03:30:25 | Debug | CACHE Status / Total cached results: 0
2021-08-02 03:30:25 | Debug | CACHE PruneCacheByTtl / Pruned queries: 0
2021-08-02 03:30:25 | Debug | CACHE CleanIndexerCache / Indexer: xwtorrents
2021-08-02 03:30:25 | Debug | Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2021-08-02 03:30:25 | Debug | Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...
2021-08-02 03:30:25 | Debug | Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2021-08-02 03:30:25 | Debug | Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2021-08-02 03:30:25 | Debug | Connection id "0HMALCU3T2MLQ", Request id "0HMALCU3T2MLQ:00000015": done reading request body.
2021-08-02 03:30:25 | Debug | Connection id "0HMALCU3T2MLQ", Request id "0HMALCU3T2MLQ:00000015": started reading request body.
2021-08-02 03:30:25 | Debug | Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'.
2021-08-02 03:30:25 | Debug | Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'.
2021-08-02 03:30:25 | Debug | Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ...
2021-08-02 03:30:25 | Debug | Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...
2021-08-02 03:30:25 | Debug | Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2021-08-02 03:30:25 | Debug | Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2021-08-02 03:30:25 | Info | Authorization was successful.
2021-08-02 03:30:25 | Debug | Execution plan of result filters (in the following order): None
2021-08-02 03:30:25 | Debug | Execution plan of exception filters (in the following order): None
2021-08-02 03:30:25 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2021-08-02 03:30:25 | Debug | Execution plan of resource filters (in the following order): None
2021-08-02 03:30:25 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2021-08-02 03:30:25 | Info | Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2021-08-02 03:30:25 | Info | Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2021-08-02 03:30:25 | Debug | Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2021-08-02 03:30:25 | Debug | Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/xwtorrents/config'
2021-08-02 03:30:25 | Debug | 1 candidate(s) found for the request path '/api/v2.0/indexers/xwtorrents/config'
2021-08-02 03:30:25 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2021-08-02 03:30:25 | Debug | POST requests are not supported
2021-08-02 03:30:25 | Debug | Request is continuing in applying rules. Current url is http://192.168.1.69:9117/jackett/api/v2.0/indexers/xwtorrents/config
2021-08-02 03:30:25 | Debug | Request is continuing in applying rules. Current url is http://192.168.1.69:9117/jackett/api/v2.0/indexers/xwtorrents/config
2021-08-02 03:30:25 | Debug | Request is continuing in applying rules. Current url is http://192.168.1.69:9117/jackett/api/v2.0/indexers/xwtorrents/config
2021-08-02 03:30:25 | Info | Request starting HTTP/1.1 POST http://192.168.1.69:9117/jackett/api/v2.0/indexers/xwtorrents/config application/json 346


</body>
</html>`

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/169
