### ISSUE TITLE
[hdbits] Cannot access child value on Newtonsoft.Json.Linq.JValue. (Config)

### ISSUE THREAD

**Issue by aiyyo** [Jackett/Jackett#12120]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Debian 10

**.Net Runtime**: .Net-Core

**.Net Version**:

**Jackett Version**: v0.18.518

**Last Working Jackett Version**: -

**Are you using a proxy or VPN?** no

### Description

Try to add HDBits indexer. Click configure, fill username and password and click Okay button.

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

```
System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 654
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 965
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
no, the simple picture challenge is automatically solved by Jackett. the problem may be the test that occurs after the login to confirm that the login was successful.
we are going to need to see an enhanced log with the debug and HTML as the stack trace you provided is of little value in this case.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
thanks.

**Comment by aiyyo** [comment]
I attached the log file.
[_log.txt](https://github.com/Jackett/Jackett/files/6922359/_log.txt)

**Comment by garfield69** [comment]
It looks like you are right, the indexer is tripping over the SimpleCaptcha.
Cardigann has the automatic SimpleCaptcha logic in play, and received back from the site this JSON
```json
{"text":"house","images":["6cf9373f69bae2bec43d4d729837f6046396ee47","a59d011afefff257050737c2843ccc7d72c73efe","ad107a1ded229c56dd5e103e25f053dcef38e97b","47b236824b506f4abdaf9720291ad5adf9b1fea3","39b1a03a7087fe5a5dfb2541a109c5995faf78db"]} 
```
which Cardigann then tries to analyse in order to set the `captchaSelection` hash key.
but Cardigann is expecting 
https://github.com/Jackett/Jackett/blob/bf8decd6095eef076e3827d5e2ac774a276d282c/src/Jackett.Common/Indexers/CardigannIndexer.cs#L656
and the JSON returned by the site does not appear to have a hash pair.

So it seems the SimpleCaptcha that the hdbits web site is using is a variation that Cardigann is not set up to handle.
Unfortunately I am not a C# dev so I am not sure how to alter the Cardigann processor to handle both the standard SimpleCaptcha and this variation of it when its in use.
We are going to need a C# dev volunteer to help.

While we wait for a solve, have you tried the hdbits (API) indexer? 
You supply your username, and the API passkey which you get from your account profile and should let you access hdbits torrents.

**Comment by aiyyo** [comment]
Thanks garfield69 for the quick responses! The HDBits (API) indexer works flawlessly.

**Comment by garfield69** [comment]
@aiyyo could you update your Jackett to v0.18.590 and try out the regular hdbits indexer to test a fix I've had a crack at?
Thanks.

**Comment by aiyyo** [comment]
@garfield69 I tested the v0.18.590 version but I got same error message than before.

[log_0823.txt](https://github.com/Jackett/Jackett/files/7030404/log_0823.txt)

**Comment by garfield69** [comment]
ah well, was worth a try. i'll leave it to the c# devs then. thanks for testing.

**Comment by Simpuhl** [comment]
Seems like this is an ongoing issue

**Comment by jonandeva** [comment]
Same problem here. Could 2FA have something to do with it?
