### ISSUE TITLE
[torrentleech] Error:  Please click on the reCAPTCHA box. (Config)

### ISSUE THREAD

**Issue by fillilutten** [Jackett/Jackett#12133]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.18.527

**Last Working Jackett Version**: v0.18.527

**Are you using a proxy or VPN?** [yes/no] Yes and No, I've tried both local and through reverser proxy

### Description

I changed password on torrentleech and wanted to update the password in jackett to make it work again and now I cant login.

### Logged Error Messages

Jackett.Common.ExceptionWithConfigData: Error:  Please click on the reCAPTCHA box.
   at Jackett.Common.Indexers.TorrentLeech.<>c__DisplayClass12_0.<DoLogin>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentLeech.cs:line 146
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 259
   at Jackett.Common.Indexers.TorrentLeech.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentLeech.cs:line 141
   at Jackett.Common.Indexers.TorrentLeech.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentLeech.cs:line 129
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by ilike2burnthing** [comment]
In browser, log out of the tracker, then log back in and complete any captcha challenge. Log out again, log back in and check if you're still presented with a captcha challenge. If there is no captcha you should be able to log in with Jackett.

**Comment by fillilutten** [comment]
Forgot to mention that. I’ve tried that multiple times and went from needing to one click check box capatcha to a image based one.

Vänligen,
Jacob

**Comment by ilike2burnthing** [comment]
Give it a few days to see if the heightened security is dropped. I can login fine, so it looks like it's a result of you making that change, and not anything else.

If you have any automation software (e.g. Sonarr) using TorrentLeech, disable or remove TL from it so that there are no repeated failed login attempts making the issue worse.

**Comment by fillilutten** [comment]
I tried now again and capatcha was gone and now its working, huge thanks!
