### ISSUE TITLE
[film-paleis] Login failed: Selector

### ISSUE THREAD

**Issue by bjornhollander** [Jackett/Jackett#12132]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker in Ubuntu 20.04 (image dyonr/jackettvpn)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: ?

**Jackett Version**: v0.18.502

**Last Working Jackett Version**: ?

**Are you using a proxy or VPN?** yes

### Description

Unable to connect to the indexer. I am able to log in directly to the website using my credentials and extract the requires information as described in the descriptor of how to set up the indexer. Might this possibly have anything to do with the DDOS protection that is active for the domain?
When using a browser you're simply redirected after a few seconds, but I suspect Jackett isn't able to handle with this properly. 

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

```
2021-08-06 11:41:58 	Info 	

Request finished HTTP/1.1 POST http://domain.me/api/v2.0/indexers/film-paleis/config application/json 317 - 500 - application/json 475.3037ms

2021-08-06 11:41:58 	Debug 	

Connection id "0HMAONN7V3H61" completed keep alive response.

2021-08-06 11:41:58 	Debug 	

No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.

2021-08-06 11:41:58 	Error 	

Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 823
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

2021-08-06 11:41:58 	Info 	

Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'

2021-08-06 11:41:58 	Info 	

Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 451.0231ms

2021-08-06 11:41:58 	Debug 	

WebClient(HttpWebClient2): Returning OK => 1793 bytes
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>DDoS protection | Film-Paleis.ME</title>
<style type="text/css">
    .main_t {height: 100%; width: 100%; border: 0px solid black;}
    .main_t td {text-align: center;}
    .main_t td.info {height: 100%; text-align: center; vertical-align: top; padding-top: 5em;}
	
    .sign { color: #ccc; margin-top: 5em;}
    .sign a { color: #ccc; }
</style>
<script>
function get_current_url() {
    document.write(window.location.href);
    return null;
}
</script>
</head>
<body>
<table class="main_t">
<tr>
<td class="info">
<h1>DDoS protection actief voor ip <a href="/blacklists/31.13.191.154" target="_new">31.13.191.154</a></h1>
<p>Duurt het laden erg lang, klik op de link om door te gaan.</p>
<a href=''><script>get_current_url();</script></a>
<p>U word automatisch doorgestuurd na de juiste pagina over 3 seconds.</p>
<div id="js_info">
<p>Zorg dat u Cookies en JavaScript heeft ingeschakeld, anders kunt u niet aanmelden.</p>
</div>
</td>
</tr>
<tr>
<td class="sign"><span style="color: #49C73B;">
DDoS protection by </span><span style="color: #49C73B;">Film-Paleis</span><span style="color: #349EBF;"> Protection</span><br />
<noscript>Please enable Javascript to see the requested page.</noscript>
</td>
</tr>
</table>
<script type="text/javascript">
        document.getElementById('js_info').style.display = 'none';
        var date = new Date();

        days = '180';
        date.setTime(date.getTime() + (days * 24*60*60*1000));

        document.cookie = 'ct_anti_ddos_key' + "=" + escape('***') + "; expires = " + date.toGMTString() + "; path=/";
        setTimeout(function(){
           window.location.reload(1);
        }, 3000);
    </script>
</body>
</html>

2021-08-06 11:41:57 	Debug 	

WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.film-paleis.me/)

2021-08-06 11:41:57 	Debug 	

CardigannIndexer (film-paleis): Cookies after login: ct_anti_ddos_key=***; uid=***; pass=***

2021-08-06 11:41:57 	Debug 	

CACHE Status / Total cached results: 0

2021-08-06 11:41:57 	Debug 	

CACHE PruneCacheByTtl / Pruned queries: 0

2021-08-06 11:41:57 	Debug 	

CACHE CleanIndexerCache / Indexer: film-paleis

2021-08-06 11:41:57 	Debug 	

Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.

2021-08-06 11:41:57 	Debug 	

Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...

2021-08-06 11:41:57 	Debug 	

Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.

2021-08-06 11:41:57 	Debug 	

Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.

2021-08-06 11:41:57 	Debug 	

Connection id "0HMAONN7V3H61", Request id "0HMAONN7V3H61:00000007": done reading request body.

2021-08-06 11:41:57 	Debug 	

Connection id "0HMAONN7V3H61", Request id "0HMAONN7V3H61:00000007": started reading request body.

2021-08-06 11:41:57 	Debug 	

Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'.

2021-08-06 11:41:57 	Debug 	

Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'.

2021-08-06 11:41:57 	Debug 	

Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ...

2021-08-06 11:41:57 	Debug 	

Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...

2021-08-06 11:41:57 	Debug 	

Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)

2021-08-06 11:41:57 	Debug 	

Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)

2021-08-06 11:41:57 	Info 	

Authorization was successful.

2021-08-06 11:41:57 	Debug 	

Execution plan of result filters (in the following order): None

2021-08-06 11:41:57 	Debug 	

Execution plan of exception filters (in the following order): None

2021-08-06 11:41:57 	Debug 	

Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer

2021-08-06 11:41:57 	Debug 	

Execution plan of resource filters (in the following order): None

2021-08-06 11:41:57 	Debug 	

Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter

2021-08-06 11:41:57 	Info 	

Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett).

2021-08-06 11:41:57 	Info 	

Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'

2021-08-06 11:41:57 	Debug 	

Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'

2021-08-06 11:41:57 	Debug 	

Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/film-paleis/config'

2021-08-06 11:41:57 	Debug 	

1 candidate(s) found for the request path '/api/v2.0/indexers/film-paleis/config'

2021-08-06 11:41:57 	Debug 	

AuthenticationScheme: Cookies was successfully authenticated.

2021-08-06 11:41:57 	Debug 	

POST requests are not supported

2021-08-06 11:41:57 	Debug 	

Request is continuing in applying rules. Current url is https://domain.me/api/v2.0/indexers/film-paleis/config

2021-08-06 11:41:57 	Debug 	

Request is continuing in applying rules. Current url is https://domain.me/api/v2.0/indexers/film-paleis/config

2021-08-06 11:41:57 	Debug 	

Request is continuing in applying rules. Current url is https://domain.me/api/v2.0/indexers/film-paleis/config

2021-08-06 11:41:57 	Info 	

Request starting HTTP/1.1 POST http://domain.me/api/v2.0/indexers/film-paleis/config application/json 317
```

### Screenshots
![Schermafbeelding 2021-08-06 om 11 34 35](https://user-images.githubusercontent.com/29463514/128491653-085de46a-0e4f-4e93-bc07-15456b761fe5.png)

If there is anything I can do to further assist in solving this issue, let me know!

**Comment by garfield69** [comment]
The indexer uses the cookie method precisely because film-paleis uses an anti DDoS check, which looks like this
![image](https://user-images.githubusercontent.com/6933240/128496963-bde7e629-0198-4a29-9b95-b6865fb83f4d.png)

I run on a windows10 without proxy, and I daily use my browser to wait for the site's DDoS check to complete when I access the site, then I access the torrents page of the site and then I grab the cookie from the development tools network page, which works for me every time in my jackett's indexer config. The cookie expires every 24 hours which is a pain in the ass.

the whole cookie string usually contains the following keys
```
uid=12345; pass=somehexstring; ct_anti_ddos_key=anotherhexstring
```
which I paste into the cookie box when I edit the indexer config using the Jackett dashboard. Then the indexer will work for me for another day.

if the cookie is not working for you then check that you are using the correct method to grab the whole cookie string, and especially read the notes section to check none of it applies to you. https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

I am guessing that using docker as well as a proxy means that you will find it difficult to fetch a cookie with the correct platform signature of your jackett docker session,  that will match the one you got when using your browser to access the site.
It is likely this combo that makes the cookie invalid. I don't use linux or docker much so I cant help further in providing a solution for you, perhaps @ilike2burnthing  can help as he is more familiar with this.

**Comment by ilike2burnthing** [comment]
Nothing to add, just highlighting that if Jackett is using a VPN, then you need to use the exact same server when fetching your cookie.

**Comment by bjornhollander** [comment]
Ahhh, that explains a lot. I'll see if I can find a way to get is working using this information. Thanks for checking up so quickly! :D
