### ISSUE TITLE
[lostfilm] Exception (lostfilm): The cookies provided by FlareSolverr are not valid: Parse error (Config)

### ISSUE THREAD

**Issue by MaLaH88** [Jackett/Jackett#12146]
### Do not delete the template.

**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed. Also check our [Troubleshooting](https://github.com/Jackett/Jackett/wiki/Troubleshooting) for steps to resolve common issues.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: CentOS

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.18.532

**Last Working Jackett Version**: Was working a long time ago.

**Are you using a proxy or VPN?** [no]

### Description

When trying to add a new LostFilm indexer.

Also tried it without FlareSolverr, and it doesn't work at all in this case.

### Logged Error Messages

Jackett.Common.IndexerException: Exception (lostfilm): The cookies provided by FlareSolverr are not valid
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 592
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 658
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 478
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 779
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 490
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 437
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 779
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 443
   at Jackett.Common.Indexers.LostFilm.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 234
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 399
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 411
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 753
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

Error on 20210809172013 for LostFilm.tv.txtSystem.Exception: Parse error
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 592
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 658
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 478
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 779
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 490
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 437

**Comment by garfield69** [comment]
The indexer is working for me, so we know it works for some platforms (I'm on win10).
Try this:
Use your Jackett dashboard to edit the config and try out the alternate site links.
NOTE: as you switch to each new link, you will fail the captcha test (because the capcha will have come from the previous site) so CLOSE the failed test, edit again, fill in the capcha text and SAVE.
Repeat sequence until you have tested all alternates.
If you still cannot get it to work then I'm out of ideas as linux platforms are not my cup of tea.

**Comment by MaLaH88** [comment]
Thanks for your answer.

Looks like none of the other URLs are working :) they are blocked.

https://www.lostfilm.tv/ - this is the only URL that I can open, and Jackett is complaining about the cookies, lol

**Comment by garfield69** [comment]
just double checking, for the username you are using your email address, yes?

**Comment by garfield69** [comment]
I am using *.site as the domain because this does not have any cloudflare conflicts.
If I try to switch to *.tv then I too see the symptoms you reported, a) without flaresolverr the cloudflare-not-configured error, b) with flaresolverr I get a timeout exceeded error.

**Comment by garfield69** [comment]
there is a whole stack of invalid-cookies issues at https://github.com/FlareSolverr/FlareSolverr

**Comment by garfield69** [comment]
Oh, and if the site is being blocked by an ISP provider you can try is to stop using the DNS provided by your ISP and switch to one of the public ones from Cloudflare (1.1.1.1 and 1.0.0.1) or Google (8.8.8.8 and 8.8.4.4) or Quad9 (9.9.9.9 and 149.112.112.112).
