### ISSUE TITLE
[Updater] The Jackett updater may not be removing unwanted indexers on all platforms

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12306]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS: Windows 7 x264
- .Net Runtime: .Net-Framework
- .Net Version: 4.8
- Jackett Version: v0.18.755
- Last Working Jackett Version: Unknown
- Are you using a proxy or VPN? No
```

### Description

the following indexers are no longer part of the Jackett stable 
epizod, funreleases, galeriens, hdreactor, lechaudron, movcr, torrentbomb

The updater should be deleting these but clearly this is not the case as Jackett complains that they no longer conform to the current Cardigann yaml code, see log below for errors.

### Logged Error Messages

```
2021-09-14 22:42:30.1810 Info Starting Jackett v0.18.755 
2021-09-14 22:42:30.9810 Info Environment version: 5.0.9 (D:\Jackett\) 
2021-09-14 22:42:30.9810 Info OS version: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit OS) 
2021-09-14 22:42:30.9810 Info Jackett variant: CoreWindows 
2021-09-14 22:42:30.9810 Info Running in Docker: No 
2021-09-14 22:42:30.9810 Info ThreadPool MaxThreads: 682 workerThreads, 1000 completionPortThreads 
2021-09-14 22:42:30.9810 Info App config/log directory: C:\ProgramData\Jackett 
2021-09-14 22:42:30.9810 Info Using proxy: Disabled 
2021-09-14 22:42:30.9810 Info Using FlareSolverr: No 
2021-09-14 22:42:30.9810 Info Using HTTP Client: HttpWebClient2 
2021-09-14 22:42:31.0000 Info Loading Native indexers ... 
2021-09-14 22:42:31.2140 Info Loaded 99 Native indexers: abnormal, alpharatio, anidex, anidub, AniLibria, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, danishbytes, darmowetorenty, desitorrents, dicmusic, digitalcore, divxtotal, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, internetarchive, iptorrents, libble, lostfilm, magnetico, mejortorrent, milkie, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, oppaitime, orpheus, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, ShizaProject, showrss, solidtorrents, speedapp, speedcd, subsplease, superbits, thepiratebay, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentleech, torrentmafya, torrentnetwork, torrent-paradise-ml, torrentscsv, torrentseeds, torrentsyndikat, tvstore, tvvault, xspeeds, xthor-api, yts, zonaq, animetosho 
2021-09-14 22:42:31.2140 Info Loading Cardigann indexers from: C:\Users\Jake\AppData\Roaming\cardigann\definitions\, C:\Users\Jake\AppData\Local\cardigann\definitions\, D:\Jackett\Definitions 
2021-09-14 22:42:32.1361 Error Error while parsing Cardigann definition D:\Jackett\Definitions\epizod.yml
YamlDotNet.Core.YamlException: (Line: 54, Col: 3, Idx: 1363) - (Line: 54, Col: 3, Idx: 1363): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'selector' not found on type 'Jackett.Common.Models.downloadBlock'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass16_0.<InitCardigannIndexers>b__3(FileInfo file) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 170 
2021-09-14 22:42:32.3191 Error Error while parsing Cardigann definition D:\Jackett\Definitions\funreleases.yml
YamlDotNet.Core.YamlException: (Line: 132, Col: 3, Idx: 4661) - (Line: 132, Col: 3, Idx: 4661): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'selector' not found on type 'Jackett.Common.Models.downloadBlock'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass16_0.<InitCardigannIndexers>b__3(FileInfo file) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 170 
2021-09-14 22:42:32.3191 Error Error while parsing Cardigann definition D:\Jackett\Definitions\galeriens.yml
YamlDotNet.Core.YamlException: (Line: 257, Col: 3, Idx: 12338) - (Line: 257, Col: 3, Idx: 12338): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'selector' not found on type 'Jackett.Common.Models.downloadBlock'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass16_0.<InitCardigannIndexers>b__3(FileInfo file) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 170 
2021-09-14 22:42:32.4841 Error Error while parsing Cardigann definition D:\Jackett\Definitions\hdreactor.yml
YamlDotNet.Core.YamlException: (Line: 53, Col: 3, Idx: 1196) - (Line: 53, Col: 3, Idx: 1196): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'selector' not found on type 'Jackett.Common.Models.downloadBlock'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass16_0.<InitCardigannIndexers>b__3(FileInfo file) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 170 
2021-09-14 22:42:32.6801 Error Error while parsing Cardigann definition D:\Jackett\Definitions\lechaudron.yml
YamlDotNet.Core.YamlException: (Line: 175, Col: 3, Idx: 8221) - (Line: 175, Col: 3, Idx: 8221): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'selector' not found on type 'Jackett.Common.Models.downloadBlock'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass16_0.<InitCardigannIndexers>b__3(FileInfo file) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 170 
2021-09-14 22:42:32.7681 Error Error while parsing Cardigann definition D:\Jackett\Definitions\movcr.yml
YamlDotNet.Core.YamlException: (Line: 38, Col: 3, Idx: 1031) - (Line: 38, Col: 3, Idx: 1031): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'selector' not found on type 'Jackett.Common.Models.downloadBlock'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass16_0.<InitCardigannIndexers>b__3(FileInfo file) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 170 
2021-09-14 22:42:33.6172 Error Error while parsing Cardigann definition D:\Jackett\Definitions\torrentbomb.yml
YamlDotNet.Core.YamlException: (Line: 53, Col: 3, Idx: 2276) - (Line: 53, Col: 3, Idx: 2276): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'selector' not found on type 'Jackett.Common.Models.downloadBlock'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass16_0.<InitCardigannIndexers>b__3(FileInfo file) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 178 
2021-09-14 22:42:33.9022 Warn Ignoring definition ID=danishbytes: Indexer already exists 
2021-09-14 22:42:33.9022 Warn Ignoring definition ID=desitorrents: Indexer already exists 
2021-09-14 22:42:33.9022 Warn Ignoring definition ID=retroflix: Indexer already exists 
2021-09-14 22:42:33.9022 Info Loaded 490 Cardigann indexers: 0daykiev, 1337x, 1ptbar, 2fast4you, 3changtrai, 3dtorrents, 4thd, 52pt, 7torrents, abtorrents, acgrip, acgsou, acidlounge, acrossthetasman, aftershock, aidoruonline, aither, amigosshare, anaschcc, angietorrents, anime-free, animeclipse, animeworld, aniRena, anisource, arabafenice, arabp2p, arenabg, asiancinema, asiandvdclub, asylumshare, audiobookbay, audiobooktorrents, audionews, aussierules, backups, badasstorrents, baibako, beitai, beyond-hd-oneurl, beyond-hd, bibliotik, bigfangroup, bigtorrent, bigtower, bit-titan, bitded, bithorlo, bithumen, bitru, bitsearch, bitsexy, bitspyder, Bittorrentfiles, bitturk, bluebirdhd, blutopia, booktracker, bootytape, borgzelle, boxingtorrents, brasiltracker, broadcity, brsociety, bt4g, btdb, btdigg, btetree, btnext, btschool, btsow, bwtorrents, byrutor, carpathians, carphunter, cartoonchaos, casatorrent, casstudiotv, cathoderaytube, catorrent, ccfbits, ceskeforum, Channelx, chdbits, chilebt, cilipro, cinemageddon, cinemamovies, cinematik, classix, coastalcrew, comicat, concen, concertos, cpasbien, cpasbienclone, crazyhd, crazyspirits, crnaberza, crt2fa, dariustracker, dark-shadow, darktracker, Das-Unerwartete, datascene, deildu, demonoid, desireleasers, devils-playground, diablotorrent, dimeadozen, divteam, dmhy, dragonworldreloaded, dxdhd, dxp, ebookparadijs, ebooks-shares, efectodoppler, ehentai, elitetorrent-biz, empornium, empornium2fa, emtrek, eniahd, erzsebet, erzsebetpl, esharenet, estone, ettv, exkinoray, extratorrent-cd, extratorrent-it, extremebits, extremetorrents, extremlymtorrents, exttorrents, eztv, fanoin, fantasticheaven, fantastiko, feedurneed, femdomcult, filebase, filelisting, film-paleis, finelite, finvip, firebit, focusx, fouducinema, freetorrent, frozenlayer, fullmixmusic, funkytorrents, gamestorrents, gay-torrents, gay-torrentsorg, gaytorrentru, generationfree, genesismovement, gfxpeers, gigatorrents, girotorrent, gktorrent, glodls, greekdiamond, greekteam, gtorrent, gtorrentpro, haidan, haitang, hamsterstudio, happyfappy, hd4fans, hdarea, hdatmos, hdbits, hdbitscom, hdc, hdcenter, hdchina, hdcity, hdcztorrent, hddolby, hdforever, hdhome, hdhouse, hdme, hdolimpo, hdonly, hdroute, hdsky, hdspain, hdstreet, hdtime, hdtorrentsit, hdturk, hdu, hdzone, hellastz, hon3yhd, horrorsite, hqsource, huntorrent, hush, ibit, idope, ilcorsaroblu, ilcorsaronero, immortuos, insanetracker, isohunt2, itorrent, iv-torrents, jpopsuki, jptv, karagarga, keepfriends, kickasstorrent-kathow, kickasstorrents-to, kickasstorrents-ws, kinonavse100, kinorun, kinozal, lastfiles, latinop2p, learnbits, learnflakes, legacyhd, legittorrents, lemonhd, lepornoinfo, lesaloon, libranet, limetorrents, linkomanija, linuxtracker, losslessclub, mactorrents, madsrevolution, magicheaven, magico, magnet4you, majomparade, marinetracker, mesevilag, metaltracker, microbit, mircrew, mixtapetorrent, mma-torrents, mnv, mononokebt, monova, montorrent, mousebits, moviesdvdr, movietorrent, moviezone, mteamtp, mteamtp2fa, muziekfabriek, mvgroupforum, mvgroupmain, mypornclub, myspleen, nbtorrents, netcosmo, nethd, netlab, newpct-me, newretro, newstudio, newstudiol, nitro, nntt, noname-club, noname-clubl, nordicplus, nyaa-pantsu, nyaasi, oasis, obscure, omgwtftrackr, oncesearch, onejav, onlineselfeducation, opencd, oshenpt, ourbits, oxtorrent, p2pbg, p2pelite, parnuxi, pctorrent, peerjunkies, peersfm, pier720, piratadigital, piratbit, piratbitl, pirateiro, pixelcove, pleasuredome, polishsource, pornbay, pornbits, pornforall, pornleech, pornolive, pornorip, pornotor, portugas, potuk, proaudiotorrents, proporno, prostylex, pterclub, ptfiles, pthome, ptmsg, ptsbao, pttime, puntotorrent, purovicio, pussytorrents, puurhollands, pwtorrents, r3vwtf, racing4everyone, racingforme, rainbowtracker, rapidzona, redbits, redstartorrent, resurrectthenet, rgfootball, rintor, rintornet, riperam, RockBox, rofd, romanianmetaltorrents, rptorrents, rus-media, rustorka, rutor, rutracker-ru, scenepalace, scenerush, sdbits, sdkino, seedfile, selezen, sexypics, sharefiles, shareisland, sharewood, shellife, shokweb, siambit, sktorrent-org, sktorrent, skytorrents-to, skytorrentsclone, skytorrentsclone2, snowpt, sosulki, soulvoice, speedmasterhd, speedtorrentreloaded, spiritofrevolution, sporthd, sportscult, springsunday, sugoimusic, sukebei-pantsu, sukebeinyaasi, swarmazon, tapochek, tasmanit, teamhd, teamos, tekno3d, tellytorrent, teracod, theaudioscene, theempire, thefallingangels, thegeeks, thehorrorcharnel, theleachzone, themixingbowl, theoccult, theplace, thesceneplace, theshinning, theshow, thevault, tjupt, tlfbits, tntfork, tokyotosho, torlock, toros, torrent-explosiv, torrent-pirat, torrent-turk, torrent4you, torrent9, torrent9clone, torrentbd, torrentccf, torrentdb, torrentdownload, torrentdownloads, torrentfactory, torrentfunk, torrentgalaxy, torrentgalaxyorg, torrenthr, torrenting, torrentkitty, torrentland, torrentleech-pl, torrentlt, torrentmax, torrentoyunindir, torrentparadise, torrentproject, torrentproject2, torrentqq, torrentsectorcrew, torrentsir, torrentslocal, torrentsurf, torrentv, torrentview, torrentwhiz, torrentz2, torrentz2eu, torrentz2k, totallykids, totheglory, totheglorycookie, trackeros, trancetraffic, trezzor, tribalmixes, trupornolabs, ttobogo, ttsweb, turkseed, turktorrent, tvchaosuk, twilight, twilightszoom, u2, uhdbits, underverse, underversel, uniondht, unionfansub, uniongang, unlimitz, vizuk, vsthouse, vsttorrents, wdt, wihd, witchhunter, woot, xiteme, xbytesv2, xwtclassics, xwtorrents, xxxadulttorrent, xxxtor, xxxtorrents, ydypt, yggcookie, yggtorrent, yingk, yourbittorrent, zamundanet, zelkaorg, zetorrents, zooqle, ztracker 
2021-09-14 22:42:33.9022 Info Loaded 589 indexers in total 
2021-09-14 22:42:33.9112 Info Adding aggregate indexer ('all' indexer) ... 
2021-09-14 22:42:33.9112 Info Adding filter indexer ('type:public' indexer) ... 
2021-09-14 22:42:33.9112 Info Adding filter indexer ('type:private' indexer) ... 
2021-09-14 22:42:33.9112 Info Adding filter indexer ('type:semi-public' indexer) ... 
2021-09-14 22:42:33.9282 Info Adding filter indexer ('tag:chinese' indexer) ... 
2021-09-14 22:42:34.1642 Info Jackett startup finished in 4.419 s 
```

**Comment by garfield69** [comment]
Ah. feedback from the user:
>Oh, my fault. Because I'm using the portable version (Jackett.Binaries.Windows.zip) and directly overwriting existing folders each time upgrade (so the old indexers not being removed). 

So no investigation is required.
