### ISSUE TITLE
[1337x] error 404 in torrent download when a query is added in rssfeed or in search results

### ISSUE THREAD

**Issue by iamLiquidX** [Jackett/Jackett#12332]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- OS: ubuntu
- .Net Runtime: [.Net-Core/.Net-Framework/Mono]
- .Net Version:
- Jackett Version: v0.18.795
- Last Working Jackett Version: v0.18.795
- Are you using a proxy or VPN? [no]
```

### Description

1337x is working fine after the multiple redirect patch but only without any query added. 
If u add a query/search term in rss feed, most of the links starts giving error 404 for torrent file download. 
Its only happening when we search and in rss feed with a query added.

### Logged Error Messages

```
--
2021-09-25 10:01:27 | Error | Error downloading. indexer: 1337x path: https://www.1337xx.to/torrent/4994951/Free-Guy-2021-1080p-Bluray-10bit-DDP-5-1-x265-HashMiner/ System.Exception: Download selectors didn't match    at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1893    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
2021-09-25 10:01:27 | Error | CardigannIndexer (1337x): Download selectors didn't match: <!DOCTYPE html> <html lang="en"> 	<head> 		<meta charset="utf-8"> 		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta name="renderer" content="webkit"> 		<title>btcache.me - Torrent Cache - 677683B2DAA98B946CC3CDC52E774B6EBF5F6D1B</title> 		<link rel="shortcut icon" href="//btcache.me/app/btc/View/img/favicon.ico"> 		<link rel='stylesheet' type='text/css' href='//btcache.me/app/btc/View/css/app.min.css'> 	</head> 	<body> <script> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]\|\|function(){ (i[r].q=i[r].q\|\|[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-74694742-1', 'auto'); ga('send', 'pageview'); </script> 		<div id="canvas"><a class="logo" href="//btcache.me/" title="btcache.me - Torrent Cache"></a> 			<h2>btcache.me is a free service for caching torrent metadata files online.</h2> 			<p>You can not search or list torrent files that are stored here, you can only access them if you already know the info_hash value of the torrent you want to download. 			<br>The way to access torrents is simple, you just use the url //btcache.me/torrent/<i>INFO_HASH_IN_HEX</i> (note HEX values A-F must be in uppercase)</p>	<div id="uploadbox" style="margin-top:30px;"> 		<h2>Download .torrent</h2> 		<form method="post" action="//btcache.me/download" style="width:620px;"> 			<input type="hidden" name="key" value="HcyxEYMwDEDRXTQBWLJkpArZULKDC+6ggBQqc9k9JN0v3v2uqO9QUjh6HGBPDgoswgU9tXmeik/EtWJtNadFhJwXX/PKbfSfF4XYI87XDXbqyJgy0YDF/te7XzvYZp8v"> 			<p>677683B2DAA98B946CC3CDC52E774B6EBF5F6D1B.torrent</p> 			<p><img id="captcha" src="" onclick="this.src='//btcache.me/captcha?'+Math.random()" style="cursor:pointer"></p> 			<script> 			document.getElementById("captcha").src = "//btcache.me/captcha?"+Math.random(); 			</script> 			<p>Text in the box: <input type="text" name="captcha"> <input type="submit" value="Download"></input></p> 		</form> 	</div>     <p>AD Links: <a href="https://avmoo.casa" target="_blank">AVMOO</a> / <a href="https://avsox.website" target="_blank">AVSOX</a> / <a href="https://avmemo.asia" target="_blank">AVMEMO</a></p>     </div> <script src='//btcache.me/app/btc/View/js/app.min.js'></script>	</body> </html>

```

### Screenshots

![IMG_20210925_100820](https://user-images.githubusercontent.com/66400864/134758329-3fc0c9a8-53b3-4375-868b-c32c58f55989.jpg)
![IMG_20210925_100844](https://user-images.githubusercontent.com/66400864/134758332-a1bee355-eadc-4a3d-a978-00c4283659f8.jpg)

**Comment by garfield69** [comment]
Aaah, BTcache appears to have a captcha in between the magnet-to-.torrent fetch.
![image](https://user-images.githubusercontent.com/6933240/134758892-e3ee7b5a-7d69-4428-b65e-a8c06404be32.png)
Not going to be able to use that service :-(
and Torrage has a click-here-to-download button
![image](https://user-images.githubusercontent.com/6933240/134758901-c8652885-f9ec-4dd3-8217-75fc4e93f135.png)
So we cant use that one either :-(
I'll amend the 1337x indexer to support only itorrents and magnet.

**Comment by iamLiquidX** [comment]
> Aaah, BTcache appears to have a captcha in between the magnet-to-.torrent fetch.
> ![image](https://user-images.githubusercontent.com/6933240/134758892-e3ee7b5a-7d69-4428-b65e-a8c06404be32.png)
> Not going to be able to use that service :-(
> and Torrage has a click-here-to-download button
> ![image](https://user-images.githubusercontent.com/6933240/134758901-c8652885-f9ec-4dd3-8217-75fc4e93f135.png)
> So we cant use that one either :-(
> I'll amend the 1337x indexer to support only itorrents and magnet.
 
I have tried with itorrents aswell, still it gives error in search result torrent download and if a query is added in rssfeed.



Here is the log of that.


 Error downloading. indexer: 1337x path: https://www.1337xx.to/torrent/4994951/Free-Guy-2021-1080p-Bluray-10bit-DDP-5-1-x265-HashMiner/ System.Exception: Download selectors didn't match    at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1893    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
-- | --

**Comment by garfield69** [comment]
Yes, itorrents is not delivering a .torrent for the title you are trying to download.
Nothing can be dome about that.
This is why the replacement 1337x will be set up for try itorrents first and magnet second.
For users such as yourself that have already defined 1337x, you may need to manually set the config in that order.

**Comment by garfield69** [comment]
v0.18.805
