### ISSUE TITLE
[btsow] Exception (btsow): Got redirected to another domain. Try changing the indexer URL to https://tellme.pw/.: Parse error (Test)

### ISSUE THREAD

**Issue by NV3S** [Jackett/Jackett#12375]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: clientType
Using FlareSolverr: Disabled or a url
Using proxy: Disabled or HTTP/SOCKS4/SOCKS5
App config/log directory: folder path
Running in Docker: No/Yes
Jackett variant: variantType
OS version: platform n.nn (32bit/64bit)
Environment version: n.n.nn (folder path)
Starting Jackett vn.nn.nn
```

### Description

btsow has blocked(?) again

### Logged Error Messages

2021-10-06 19:08:17.5|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details
2021-10-06 19:08:21.0|Warn|Torznab|Unable to connect to indexer

[v3.2.2.5080] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (btsow): Got redirected to another domain. Try changing the indexer URL to https://tellme.pw/.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://tellme.pw/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1343
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 782
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1684
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 759
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/(removed)/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 432
   at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 48
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 291
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 333
RequestUri: http://localhost:9117/api/v2.0/indexers/btsow/results/torznab/api?t=movie&cat=8000&extended=1&apikey=(removed)&offset=0&limit=100;StatusCode: OK;ContentType: application/xml; charset=utf-8;ContentLength: 1898;ContentSample: <?xml version="1.0" encoding="UTF-8"?>
<error code="900" description="Jackett.Common.IndexerException: Exception (btsow): Got redirected to another domain. Try changing the indexer URL to https://tellme.pw/.&#xA; ---&gt; System.Exception: Parse error&#xA; ---&gt; Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://tellme.pw/.&#xA;   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844&#xA;   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1343&#xA;   --- End of inner exception stack trace ---&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 782&#xA;   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1684&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416&#xA;   --- End of inner exception stack trace ---&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/(removed)/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 759&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/(removed)/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 432" />

2021-10-06 19:08:21.0|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details

**Comment by garfield69** [comment]
it seems that btsow have changed their domain to https://btsow.rest/
I will update the indexer to auto-correct the site link to the new domain for the next release of Jackett due out in about 14 hours or so.
If you want the indexer to work sooner, you can simply use your Jackett dashboard to edit the btsow config and replace the site link to `https://btsow.rest/` .

**Comment by garfield69** [comment]
v0.18.906
