### ISSUE TITLE
[req][macos]: net6.0 adds supports for Apple Silicon (os-arm64)

### ISSUE THREAD

**Issue by wyq977** [Jackett/Jackett#12372]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

As .NET 6.0 ends preview and proceeds to rc-1, I tried compiling and runing on my m1 mac mini 16 GB model and it runs fine. I basically just change net5.0 in the `Jackett/src/Jackett.Server/`: https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-5.0&tabs=visual-studio 

I wonder if Jackett would upgrade to .NET 6.0?

If so, when is the expected timeline?

Related issue: #10668 #5589
Thx

### Describe the solution you'd like

Install [.NET 6.0 SDK](https://dotnet.microsoft.com/download/dotnet/6.0)

Build:
```bash
dotnet publish Jackett.Server -f net6.0 --self-contained -r osx-arm64 -c Debug
# run
./Jackett.Server/bin/Debug/net6.0/osx-arm64/jackett
```

A compile warning link to this [SHA512Managed](https://github.com/Jackett/Jackett/blob/6a213c6eabd0264392c48564ff16a9035fd13ca4/src/Jackett.Server/Services/SecuityService.cs#L28) 

ref: [SYSLIB0021: Derived cryptographic types are obsolete](https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0021)

**Comment by wyq977** [comment]
True, dotnet6.0 is still rc right now, maybe its better to wait until the final release.

As for macOS development, I dont have experience in dotnet, not to mention on macOS, but if theres just testing, upgrading from 5.0 to 6.0, I hope I could contribute somehow.

As for two releases, I know that you can release a [universal binary](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary) which runs on both x86 and arm mac but I think thats not possible at the moment, even in 6.0, see: https://docs.microsoft.com/en-us/answers/questions/471880/net-core-support-in-new-mac-os-arm-based-processor.html

**Comment by whalehub** [comment]
@ngosang .NET 6 was released about a week ago: https://devblogs.microsoft.com/dotnet/announcing-net-6/

**Comment by ngosang** [comment]
I'm working on it #12562

**Comment by ngosang** [comment]
@wyq977 @whalehub @dvcrn @garfield69 @ilike2burnthing could you help with testing?

Download the binaries from => https://dev.azure.com/Jackett/Jackett/_build/results?buildId=4782&view=artifacts&pathAsName=false&type=publishedArtifacts
Click in the three dots, in "drop":
![image](https://user-images.githubusercontent.com/10577978/142053221-85953b8a-8eb0-4661-a1f8-fc451472f320.png)

Test the `Jackett.Binaries.macOS.tar.gz` and `Jackett.Binaries.macOSARM64.tar.gz` artifacts. Try to test the install and uninstall scripts too. The updater is implemented but it can't be tested until there is at least one official release.

**Comment by wyq977** [comment]
## `Jackett.Binaries.macOS.tar.gz`


* Works fine, tested with a couple of public indexer, some errors with one of them but it should be irrelavent.
* Install and uninstall script works as expected (only tested uninstall with option 2)

## `Jackett.Binaries.macOSARM64.tar.gz`


* Same as the macOS

```
# Jackett.Binaries.macOS.tar.gz
$ ./jackett
11-17 00:58:14 Info Starting Jackett v0.20.6 
11-17 00:58:14 Info Environment version: 6.0.0 (/Downloads/drop/Jackett/) 
11-17 00:58:14 Info OS version: Unix 11.6.0 (64bit OS) (64bit process) 
11-17 00:58:14 Info Jackett variant: CoreMacOs 
11-17 00:58:14 Info Running in Docker: No 
11-17 00:58:14 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
11-17 00:58:14 Info App config/log directory: /.config/Jackett 
11-17 00:58:14 Info Using proxy: Disabled 
11-17 00:58:14 Info Using FlareSolverr: No 
11-17 00:58:14 Info Using HTTP Client: HttpWebClient2 
11-17 00:58:14 Info Loading Native indexers ... 
11-17 00:58:14 Info Loaded 88 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, danishbytes, darmowetorenty, divxtotal, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, seals, secretcinema, sharewoodapi, shazbat, ShizaProject, showrss, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentseeds, torrentsyndikat, tvstore, xspeeds, xthor-api, zonaq, animetosho 
11-17 00:58:14 Info Loading Cardigann indexers from: /.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /Downloads/drop/Jackett/Definitions 
11-17 00:58:15 Info Loaded 497 Cardigann indexers: amigosshare, hdturk, teamos, 0daykiev, insanetracker, ilcorsaroblu, btdigg, ourbits, sukebeinyaasi, swarmazon, 1337x, theempire, puurhollands, torrentfunk, concen, dxp, lastfiles, 1ptbar, asiandvdclub, rainbowtracker, spiritofrevolution, torrentkitty, glodls, torlock, indietorrents, hdbitscom, yourbittorrent, 0magnet, torrentsectorcrew, torrentland, byrbt, ilcorsaroverde, extratorrent-st, ceskeforum, 24rolika, darktracker, blutopia-api, soulvoice, renegade, siambit, estone, acrossthetasman, limetorrentsclone, cpasbienclone, dariustracker, funkytorrents, bwtorrents, sdbits, lepornoinfo, snowpt, anaschcc, cartoonchaos, torrent9clone, greekteam, polishsource, magicheaven, sosulki, torlook, ettv, pussytorrents, lat-team, dark-shadow, beyond-hd, riperam, hddolby, animeclipse, tokyotosho, 4thd, nbtorrents, yts, movietorrent, tasmanit, arabafenice, boxingtorrents, lemonhd, theshinning, turkseed, thevault, sugoimusic, omgwtftrackr, bt4g, itorrent, ibit, noname-clubl, mononokebt, pornotor, hdme, gay-torrents, torrentdownloads, linuxtracker, shareisland-api, badasstorrents, racingforme, pthome, yggtorrent, bitded, efectodoppler, dimeadozen, pier720, rintor, tellytorrent-api, hdforever, mixtapetorrent, mircrew, extremetorrents, hdzone, film-paleis, bitspyder, concertos, thesceneplace, torrentmasters, bitsearch, byrutor, solidtorrents, sexypics, Bittorrentfiles, zooqle, p2pbg, underversel, shokweb, leech24, anilibria, purovicio, tapochek, brsociety, rus-media, magico, skipthecommercials, wdt, seedfile, pornorip, tellytorrent, ehentai, nyaasi, hdtorrentsit, sexxi, bangumi-moe, yggcookie, finvip, kinorun, gtorrentpro, crnaberza, bit-titan, genesismovement, thegeeks, mnv, uhdbits, chilebt, brasiltracker, pornbits, frozenlayer, torrentv, soundpark, girotorrent, redbits, esharenet, zelkaorg, xxxadulttorrent, reelflix-api, pornleech, datatalli, milkie, ztracker, classix, torrentleech-pl, datascene-api, gay-torrentsorg, karagarga, animeworld-api, piratbitl, proaudiotorrents, datascene, kickasstorrents-to, superbits, aussierules, fantasticheaven, redstartorrent, rapidzona, speedmasterhd, tekno3d, iv-torrents, mousebits, newstudio, theplace, mteamtp2fa, unionfansub, cathoderaytube, toros, xwtclassics, greekdiamond, gigatorrents, torrentlt, jpopsuki, hdspain, legittorrents, 3dtorrents, docspedia, onejav, peerjunkies, gamestorrents, vsttorrents, gktorrent, mteamtp, rptorrents, torrentccf, desitorrents, vsthouse, cpasbien, aither-api, bibliotik, teamhd, xxxtorrents, theoccult, torrentoyunindir, hdroute, aither, bigfangroup, anisource, discfan, madsrevolution, eniahd, bithorlo, megapeer, selezen, empornium, divteam, hdu, pttime, isohunt2, kickasstorrents-ws, hdc, gfxpeers, whiteangel, ptfiles, theaudioscene, torrentparadise, pwtorrents, theshow, piratadigital, punkshorror, peersfm, desitorrents-api, broadcity, bluebirdhd, learnflakes, hdcztorrent, hellastz, resurrectthenet, potuk, torrentmax, torrentproject2, huntorrent, woot, sharewood, devilsplayground, fouducinema, tjupt, sportscult, torrentdownload, torrent-explosiv, netcosmo, ilcorsaronero, hd4fans, jptv, catorrent, chdbits, newstudiol, teracod, cryptichaven, underverse, finelite, elitetorrent-biz, torrent-pirat, learnbits, scenerush, pixelcove, myspleen, prostylex, torrentbd, torrentwhiz, kinonavse100, hdcenter, acgsou, newretro, torrentz2eu, ydypt, 2fast4you, twilightszoom, hdhome, vizuk, oncesearch, torrenting, zetorrents, aftershock, nntt, cinemamovies, animeworld, torrent-turk, casatorrent, mvgroupmain, xiteme, anime-free, trancetraffic, arabp2p, carpathians, ptmsg, femdomcult, keepfriends, scenepalace, totheglory, btschool, deildu, rutracker-ru, crazyhd, torrent9, brsociety-api, hdhouse, torrentgalaxy, acgrip, mesevilag, theleachzone, kinozal, tvchaosuk, filebase, cinemageddon, mvgroupforum, torrentleech, RockBox, nforce, exkinoray, filelisting, hdsky, kisssub, libranet, 52pt, 01torrent, mypornclub, fanoin, themixingbowl, uniongang, torrentview, torrentsir, bootytape, pornotorrent, desireleasers, hdcity, sporthd, moviesite, putao, haidan, torrent-paradise-ml, pornoslab, opensharing, sktorrent, megamixtracker, sktorrent-org, tlfbits, trupornolabs, portugas, extremebits, booktracker, romanianmetaltorrents, thepiratebay, crazyspirits, bitbazis, abtorrents, borgzelle, xbytesv2, mikan, piratbit, parnuxi, trezzor, ebooks-shares, internetarchive, hamsterstudio, dmhy, dragonworldreloaded, comicat, the-devils-lounge, thehorrorcharnel, totallykids, majomparade, digitalcore, bithumen, rustorka, haitang, nethd, beitai, pornbay, bitturk, newpct-me, hdai, turktorrent, immortuos, moviesdvdr, ebookparadijs, falkonvisionteam, rgfootball, xxxtor, btetree, puntotorrent, hdtime, btnext, torrentqq, blutopia, bestcore, mactorrentsdownload, netlab, audionews, skipthecommercials-api, springsunday, microbit, pirateiro, 7torrents, aidoruonline, limetorrents, torrentsurf, firebit, zomb, coastalcrew, opencd, oasis, gaytorrentru, uniondht, oxtorrent, lesaloon, torrenthr, cinematik, oshenpt, rutor, hdchina, reelflix, hdonly, extremlymtorrents, idope, racing4everyone, torrentdb, tribalmixes, diablotorrent, proporno, torrentslocal, wihd, baibako, shareisland, xwtorrents, losslessclub, slosoul, speedtorrentreloaded, pctorrent, trackeros, empornium2fa, crt2fa, u2, fantastiko, mma-torrents, rintornet, beyond-hd-oneurl, noname-club, audiobookbay, backups, pornforall, nipponsei, linkomanija, hdatmos, bitru, arenabg, asiancinema, metaltracker, hdolimpo, carphunter, unlimitz, hqsource, acidlounge, 3changtrai, hdarea, totheglorycookie, zamundanet, bitsexy, exttorrents, muziekfabriek, generationfree, btsow, p2pelite, eztv, pornolive, ptsbao, thefallingangels, happyfappy, r3vwtf, nitro, twilight, marinetracker, ccfbits, hdbits, pterclub, aniRena, demonoid 
11-17 00:58:15 Info Loaded 585 indexers in total 
11-17 00:58:15 Info Adding aggregate indexer ('all' indexer) ... 
11-17 00:58:15 Info Adding filter indexer ('type:public' indexer) ... 
11-17 00:58:15 Info Adding filter indexer ('type:private' indexer) ... 
11-17 00:58:15 Info Adding filter indexer ('type:semi-public' indexer) ... 
11-17 00:58:15 Info Jackett startup finished in 2.075 s 
Hosting environment: Production
Content root path: /Downloads/drop/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
11-17 00:58:38 Info Test search in 1337x => Found 60 releases 
11-17 00:58:39 Info Test search in ETTV => Found 100 releases 
11-17 00:58:41 Info Test search in EZTV => Found 90 releases 
11-17 00:58:45 Error Jackett.Common.IndexerException: Exception (torrentz2eu): Challenge detected but FlareSolverr is not configured
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /Users/runner/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /Users/runner/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 590
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1374
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/runner/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /Users/runner/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.IndexerException: Exception (torrentz2eu): Challenge detected but FlareSolverr is not configured
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /Users/runner/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /Users/runner/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 590
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1374
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/runner/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /Users/runner/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
11-17 00:58:47 Info Test search in RARBG => Found 100 releases 
11-17 00:59:24 Warn Some of the categories provided are unsupported in RARBG:  
11-17 00:59:24 Info Torznab search in RARBG => Found 100 releases 
11-17 00:59:25 Info Torznab search in 1337x => Found 20 releases 
11-17 00:59:25 Info Torznab search in ETTV => Found 100 releases 
11-17 00:59:25 Info Torznab search in EZTV => Found 90 releases 
```

**Comment by valdupin** [comment]
Tried both. Install & uninstall script worked.

**Comment by garfield69** [comment]
v0.20.36
