### ISSUE TITLE
[cinecalidad] Found 0 releases

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#12385]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.18.911 
Environment version: 5.0.10 (/app/Jackett/) 
OS version: Unix 4.14.0.0 (64bit OS) (64bit process) 
Jackett variant: CoreLinuxAmdx64 
Running in Docker: Yes (image build: unknown) 
App config/log directory: /config/Jackett 
Using proxy: Disabled 
Using FlareSolverr: http://192.168.0.42:8191 
Using HTTP Client: HttpWebClient2
```

### Description

Keywordless search: `Found 0 releases`
I think row detection is the issue here as the homepage is now using `div.postItem`.

Keyword search (e.g. demonio): `Object reference not set to an instance of an object`
Error points to line 160 of the .cs which is for the poster, but I can't see what the issue is there.

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (cinecalidad): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Cinecalidad.ParseReleases(WebResult response, TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 160
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 782
   at Jackett.Common.Indexers.Cinecalidad.ParseReleases(WebResult response, TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 193
   at Jackett.Common.Indexers.Cinecalidad.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 92
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 402
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 414
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 756
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 228
```

**Comment by garfield69** [comment]
two issues:
- the homepage (recent list) uses a different layout than the search page. good new is that the search page accepts keywordless input so we can now use `https://www.cine-calidad.com/?s=`
- the search page no longer has the noscript selector. This has been replaced by the attribute `extract` in the `img` selector.

I think I can modify the indexer to work again.
