### ISSUE TITLE
[thesceneplace] Test search in TheScenePlace => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by jckozy86** [Jackett/Jackett#12383]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: clientType
Using FlareSolverr: Disabled or a url
Using proxy: Disabled or HTTP/SOCKS4/SOCKS5
App config/log directory: folder path
Running in Docker: No/Yes
Jackett variant: variantType
OS version: platform n.nn (32bit/64bit)
Environment version: n.n.nn (folder path)
Starting Jackett vn.nn.nn
```

### Description

When logging in to the Site using the same credentials I see a lot of torrents.
Jacket is unable to get any torrents back via the API.

### Logged Error Messages

2021-10-07 18:40:48.7472 Info Authorization was successful. 
2021-10-07 18:40:48.7472 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2021-10-07 18:40:48.7472 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2021-10-07 18:40:48.7472 Debug CACHE IsCacheEnabled => false 
2021-10-07 18:40:48.7472 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.thesceneplace.com/index.php?page=torrents&search=&category=&options=0&active=0&order=5&by=2) 
2021-10-07 18:40:50.0634 Debug WebClient(HttpWebClient2): Returning OK => 488049 bytes <BINARY> 
2021-10-07 18:40:50.1082 Info Test search in TheScenePlace => Found 0 releases 
2021-10-07 18:40:50.1082 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 1355.5743ms 
2021-10-07 18:40:50.1082 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' 
2021-10-07 18:40:50.1082 Error System.Exception: Test search in TheScenePlace => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 310
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61 System.Exception: Test search in TheScenePlace => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 310
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
2021-10-07 18:40:50.1082 Debug The response will be compressed with 'br'. 
2021-10-07 18:40:50.1082 Debug Connection id "0HMC9S7OUNCAM" completed keep alive response. 
2021-10-07 18:40:50.1082 Info Request finished HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/thesceneplace/test - 0 - 500 - application/json 1366.2660ms

**Comment by ilike2burnthing** [comment]
Working ok here. Try reconfiguring the indexer.

If you still have issues then please provide the information requested in the environment section above - `The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste replacing the example below with the last 10 Info lines at the bottom of the log.`

Also provide an **enhanced** log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ilike2burnthing** [comment]
What theme do you have TSP set to?

Try changing it to Black Neon 3.0 (if it isn't already) and run the test in Jackett again.

**Comment by jckozy86** [comment]
I had it set on black-blue, so I changed it to "Black Neon 3.0"
Stopped and restarted Jacket, still failed
Removed index, stopped Jacket, restarted and added index, still failed 

:'-(

**Comment by garfield69** [comment]
after changing the theme on the web site, logout then try using jackett.

**Comment by jckozy86** [comment]
It is still failing for me unfortunately :(

Since you guys are getting results, I'll ask the site devs to look into this in case my requests are blocked for some reason.
I will also mention the return message having int(0) so they are aware.

I tried logging out of site, tested in jacket, failed
cleared all cache from chrome, tested in jacket, failed
removed index, restarted jacket, added index, tested and failed.

**Comment by nexus382** [comment]
its working fine for me, but is there a reason its only puling 15 results for every search ?

**Comment by nexus382** [comment]
it seems your API that pulls, only works on NON staff classes, can you guys fix that so our staff acnts will pull? there shouldnt be a difference for thoes classes, they only have EXTRA permissions, nothing is taken away.... If i allow you guys to have a temp class with STAFF permissions, can you guys fix this?

**Comment by garfield69** [comment]
>its working fine for me, but is there a reason its only puling 15 results for every search ?

@nexus382  yup, thats the default from the web site.
change the Torrents per page: setting to 100 on your account profile.

**Comment by garfield69** [comment]
>it seems your API that pulls, only works on NON staff classes, can you guys fix that so our staff acnts will pull? there shouldnt be a difference for thoes classes, they only have EXTRA permissions, nothing is taken away.... If i allow you guys to have a temp class with STAFF permissions, can you guys fix this?

I can certainly can take a look. My a/c username is garfield1969

**Comment by nexus382** [comment]
ok i messaged you on site :) I appreciate you very much!

**Comment by garfield69** [comment]
so the issue is that the power users get a torrent listing where the rows contain extra selectors (the uploader user-details href between the completed and the size columns, and the remove button at the end column).
This is throwing off the indexer's selector count.
I will see if I can detect the presence of the extra columns and dynamically adjust the selector to skip over the extra columns.

**Comment by garfield69** [comment]
BTW I will also drop the dependency of the indexer of the mouseover (balloon over).

**Comment by garfield69** [comment]
v0.18.929
