### ISSUE TITLE
Redacted non responsive

### ISSUE THREAD

**Issue by suikerchiller** [Jackett/Jackett#12392]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Ubuntu 18.04
nginx reverse proxy
Jackett Version v0.18.929
```

### Description

Redacted (indexer) has become non-responsive recently.

I've re-issued new api keys, but without luck. I removed the api key from the screenshot for obvious security reasons after submitting the actual request. Other indexers are working fine.

What's causing this issue? How can it be resolved?

Thx in advance!

### Logged Error Messages
```
2021-10-11 20:20:44 | Error | System.Exception: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Your API Key did not work: Parse error    at Jackett.Common.Indexers.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 150    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
-- | -- | --

2021-10-11 20:20:44 | Error | Error on 20211011202044 for Redacted.txtNewtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)    at Jackett.Common.Indexers.Abstract.GazelleTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 205
-- | -- | --
```

### Screenshots

<img width="600" alt="Screenshot 2021-10-11 at 20 38 24" src="https://user-images.githubusercontent.com/27237108/136839389-41a508a7-4536-41fd-b894-52841b95c6b5.png">

**Comment by suikerchiller** [comment]
> 
> > Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste [...] the last 10 Info lines at the bottom of the log.
> 
> @ilike2burnthing here you go:

2021-10-11 21:18:38 | Info | Loading Native indexers ...
-- | -- | --
2021-10-11 21:18:38 | Info | Using HTTP Client: HttpWebClient2
2021-10-11 21:18:38 | Info | Using FlareSolverr: No
2021-10-11 21:18:38 | Info | Using proxy: Disabled
2021-10-11 21:18:38 | Info | App config/log directory: /var/lib/jackett/.config/Jackett
2021-10-11 21:18:38 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-10-11 21:18:38 | Info | Running in Docker: No
2021-10-11 21:18:38 | Info | File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2021-10-11 21:18:38 | Info | Jackett variant: CoreLinuxAmdx64
2021-10-11 21:18:38 | Info | OS version: Unix 4.15.0.159 (64bit OS) (64bit process)
2021-10-11 21:18:38 | Info | Environment version: 5.0.10 (/opt/Jackett/)
2021-10-11 21:18:38 | Info | Starting Jackett v0.18.929

**Comment by ngosang** [comment]
> @seeyabye @ngosang is the redacted indexer working for you?

Sorry, I lost my account.

**Comment by ilike2burnthing** [comment]
Did you try a manual search with it in Jackett?

**Comment by seeyabye** [comment]
There is indeed an issue with the exception handling when errors are happening (i.e. wrong credentials or other possibilities).

Since the original `GazelleTracker` was written with normal login in mind, the code requires a different approach when credentials are incorrect (i.e., simply stopping rather than looping and trying to re-login). The re-login part of the code is recursively calling `ApplyConfiguration` when it fails, this has to be fixed, but I don't have a lot of time at the moment, so a temporary fix for now will do.

I have rewrote a part of the exception handling to explain the reason for failure. @suikerchiller if you have the chance, please download the binaries from the PR (https://github.com/Jackett/Jackett/pull/12416) and give it a try. I am unable to replicate your problem (Redacted is giving you a redirect for some reason). Please provide an enhanced log after you've tried it.

**Comment by suikerchiller** [comment]
> I have rewrote a part of the exception handling to explain the reason for failure. @suikerchiller if you have the chance, please download the binaries from the PR (https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/4415/artifacts?artifactName=drop&api-version=6.0&%24format=zip) and give it a try.

Greatly appreciate your effort & time @seeyabye, thx! I'm having a hard time figuring out where to get a direct link for the binary of this pull request (x86_64), not too advanced with Github :) Where do I find that normally?

**Comment by garfield69** [comment]
@suikerchiller  the azure link that seeyabye provided should point to a file called drop.zip which once downloaded and unpacked will contain install packages for each of the platforms we generate (except docker images, they are created by the linuxserver.io group and they bould only from our published source not our PR).

So just click on https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/4415/artifacts?artifactName=drop&api-version=6.0&%24format=zip 
Does this not work for you?

**Comment by suikerchiller** [comment]
Not sure what went wrong there, but the end file got all messed up and was unidentifiable.. Either way, found it and everything is working as expected :) Also attached a log so you can see for yourself: [jackett.log.part3.txt](https://github.com/Jackett/Jackett/files/7340701/jackett.log.part3.txt). Will this automatically be fixed in the next release?

Thx to all for your help and patience!
