### ISSUE TITLE
solidtorrents: set categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12405]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
latest
```

### Description

I see the Solid Torrent site is not providing the categories. I think we should hardcode "Others" category for all torrents to avoid issues with 3rd party software.

### Logged Error Messages

.

**Comment by ngosang** [comment]
query: "silicon valley"

```
Jackett.Common.IndexerException: Exception (solidtorrents): Error parsing category=3!
 ---> System.Exception: Parse error
 ---> System.Exception: Error parsing category=3!
   at Jackett.Common.Indexers.SolidTorrents.ParseCategory(String query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SolidTorrents.cs:line 141
   at Jackett.Common.Indexers.SolidTorrents.MakeRelease(JToken torrent) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SolidTorrents.cs:line 230
   at Jackett.Common.Indexers.SolidTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SolidTorrents.cs:line 208
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 782
   at Jackett.Common.Indexers.SolidTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SolidTorrents.cs:line 212
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 759
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 228

Error on 20211013141208 for Solid Torrents.txtSystem.Exception: Error parsing category=3!
   at Jackett.Common.Indexers.SolidTorrents.ParseCategory(String query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SolidTorrents.cs:line 141
   at Jackett.Common.Indexers.SolidTorrents.MakeRelease(JToken torrent) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SolidTorrents.cs:line 230
   at Jackett.Common.Indexers.SolidTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SolidTorrents.cs:line 208
```
