### ISSUE TITLE
[hdspain] Login failed: Selector

### ISSUE THREAD

**Issue by ink79** [Jackett/Jackett#12488]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled	
App config/log directory: /config/Jackett	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.19.100-ls48)	
File /etc/issue: Ubuntu 18.04.6 LTS \n \l	
Jackett variant: CoreLinuxAmdx64	
OS version: Unix 4.15.0.161 (64bit OS) (64bit process)	
Environment version: 5.0.11 (/app/Jackett/)
```

### Description

tried to add hd-spain with cookie, but getting **Login failed: Selector ".tcabecera" didn't match** error

### Logged Error Messages

```
Jackett.Common.ExceptionWithConfigData: Login failed: Selector ".tcabecera" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 826
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
- Is this the first time you are adding hd-spain indexer?
If so then read https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work , especially the **Notes** section to see if any of it applies to you.
- If you had it working before and now its has stopped working, try https://github.com/Jackett/Jackett/issues/12460#issuecomment-951848902
- If you still cannot get it going then please provide a **full enhanced log**, perhaps the Debug and HTML included will give a clue to what is going on.
Read https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Let us know how you go.

**Comment by garfield69** [comment]
BTW, the ` Login failed: Selector ".tcabecera" didn't match` is the indexers way of telling you that the cookie you provided was not accepted by the web site, and when the indexer went to check for the presence of the logout button to confirm the session was established, it did not find it. You would have probably been redirected to a login page or an error page.

**Comment by ink79** [comment]
yes first time adding hd-spain to the server with a different IP address, just tried with that IP getting Unauthorized IP address error. thanks for all the additional info.
