### ISSUE TITLE
[Internet Archive] Search Bug

### ISSUE THREAD

**Issue by heroku-miraheze** [Jackett/Jackett#12487]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-10-30 12:27:21 	Error 	

Jackett.Common.IndexerException: Exception (internetarchive): Error Parsing Json Response: Status=ServiceUnavailable Response=<div style="margin:0 20px;text-align:center;font-weight:bold">We apologize but we cannot presently sort by field: descpublicdate</div>
        </div><!--/.container-->
              </main>
    </div><!--/#wrap-->
    
    <!-- Timing ...
     rendered on: www15.us.archive.org
 seconds diff sec                                                 message   stack(file:line:function)
=========================================================
  0.0000   0.0000                                           petabox start   var/cache/petabox/petabox/www/sf/advancedsearch.php:1:require
                                             |common/ia:66:require_once
                                             |setup.php:379:log
  0.0138   0.0138   going to SE jackett AND format:("Archive BitTorrent")   var/cache/petabox/petabox/www/sf/advancedsearch.php:34:formattedOutputs
                                             |advancedsearch.php:990:__construct
                                             |common/Search.inc:600:log
  0.0153   0.0015                                                bug dump   var/cache/petabox/petabox/www/sf/advancedsearch.php:34:formattedOutputs
                                             |advancedsearch.php:990:__construct
                                             |common/Search.inc:803:fatal
                                             |setup.php:91:footer
                                             |setup.php:148:footer
                                             |Nav.inc:1167:dump
                                             |Bug.inc:102:log
    -->
    <script>
if (archive_analytics) {
  archive_analytics.send_pageview_on_load(archive_analytics);
  archive_analytics.process_url_events(location);
  var vs = archive_analytics.get_data_packets();
  for (var i in vs) {
    vs[i]['cache_bust']=Math.random();
    vs[i]['server_ms']=15;
    vs[i]['server_name']="www15.us.archive.org";
      }

  if (document.querySelectorAll('.more_search').length) {
    archive_analytics.send_scroll_fetch_base_event();
  }
}
</script>
          <img src="//analytics.archive.org/0.gif?kind=track_js&track_js_case=control&cache_bust=1770879980" alt="" />
          <noscript>
        <img src="//analytics.archive.org/0.gif?kind=track_js&track_js_case=disabled&cache_bust=21517175" />
      </noscript>
          <script>
        document.addEventListener('DOMContentLoaded', function() {
          if (archive_analytics)
            archive_analytics.create_tracking_image('in_page_executes');
        });
      </script>
      </div>
  </body>
</html>
    
 ---> System.Exception: Error Parsing Json Response: Status=ServiceUnavailable Response=<div style="margin:0 20px;text-align:center;font-weight:bold">We apologize but we cannot presently sort by field: descpublicdate</div>
        </div><!--/.container-->
              </main>
    </div><!--/#wrap-->
    
    <!-- Timing ...
     rendered on: www15.us.archive.org
 seconds diff sec                                                 message   stack(file:line:function)
=========================================================
  0.0000   0.0000                                           petabox start   var/cache/petabox/petabox/www/sf/advancedsearch.php:1:require
                                             |common/ia:66:require_once
                                             |setup.php:379:log
  0.0138   0.0138   going to SE jackett AND format:("Archive BitTorrent")   var/cache/petabox/petabox/www/sf/advancedsearch.php:34:formattedOutputs
                                             |advancedsearch.php:990:__construct
                                             |common/Search.inc:600:log
  0.0153   0.0015                                                bug dump   var/cache/petabox/petabox/www/sf/advancedsearch.php:34:formattedOutputs
                                             |advancedsearch.php:990:__construct
                                             |common/Search.inc:803:fatal
                                             |setup.php:91:footer
                                             |setup.php:148:footer
                                             |Nav.inc:1167:dump
                                             |Bug.inc:102:log
    -->
    <script>
if (archive_analytics) {
  archive_analytics.send_pageview_on_load(archive_analytics);
  archive_analytics.process_url_events(location);
  var vs = archive_analytics.get_data_packets();
  for (var i in vs) {
    vs[i]['cache_bust']=Math.random();
    vs[i]['server_ms']=15;
    vs[i]['server_name']="www15.us.archive.org";
      }

  if (document.querySelectorAll('.more_search').length) {
    archive_analytics.send_scroll_fetch_base_event();
  }
}
</script>
          <img src="//analytics.archive.org/0.gif?kind=track_js&track_js_case=control&cache_bust=1770879980" alt="" />
          <noscript>
        <img src="//analytics.archive.org/0.gif?kind=track_js&track_js_case=disabled&cache_bust=21517175" />
      </noscript>
          <script>
        document.addEventListener('DOMContentLoaded', function() {
          if (archive_analytics)
            archive_analytics.create_tracking_image('in_page_executes');
        });
      </script>
      </div>
  </body>
</html>
    
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1385
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 416
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 416
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 759
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 228
```

### Description

Internet Archives changed the search page and now Jackett shows error while searching in Internet Archive.

### Logged Error Messages

<html><body>

2021-10-30 12:27:21 | Error | Jackett.Common.IndexerException: Exception (internetarchive): Error Parsing Json Response: Status=ServiceUnavailable Response=<div style="margin:0 20px;text-align:center;font-weight:bold">We apologize but we cannot presently sort by field: descpublicdate</div>         </div>               </main>     </div>               <script> if (archive_analytics) {   archive_analytics.send_pageview_on_load(archive_analytics);   archive_analytics.process_url_events(location);   var vs = archive_analytics.get_data_packets();   for (var i in vs) {     vs[i]['cache_bust']=Math.random();     vs[i]['server_ms']=15;     vs[i]['server_name']="www15.us.archive.org";       }    if (document.querySelectorAll('.more_search').length) {     archive_analytics.send_scroll_fetch_base_event();   } } </script>           <img src="//analytics.archive.org/0.gif?kind=track_js&track_js_case=control&cache_bust=1770879980" alt="" />           <noscript>         <img src="//analytics.archive.org/0.gif?kind=track_js&track_js_case=disabled&cache_bust=21517175" />       </noscript>           <script>         document.addEventListener('DOMContentLoaded', function() {           if (archive_analytics)             archive_analytics.create_tracking_image('in_page_executes');         });       </script>       </div>   </body> </html>       ---> System.Exception: Error Parsing Json Response: Status=ServiceUnavailable Response=<div style="margin:0 20px;text-align:center;font-weight:bold">We apologize but we cannot presently sort by field: descpublicdate</div>         </div>               </main>     </div>               <script> if (archive_analytics) {   archive_analytics.send_pageview_on_load(archive_analytics);   archive_analytics.process_url_events(location);   var vs = archive_analytics.get_data_packets();   for (var i in vs) {     vs[i]['cache_bust']=Math.random();     vs[i]['server_ms']=15;     vs[i]['server_name']="www15.us.archive.org";       }    if (document.querySelectorAll('.more_search').length) {     archive_analytics.send_scroll_fetch_base_event();   } } </script>           <img src="//analytics.archive.org/0.gif?kind=track_js&track_js_case=control&cache_bust=1770879980" alt="" />           <noscript>         <img src="//analytics.archive.org/0.gif?kind=track_js&track_js_case=disabled&cache_bust=21517175" />       </noscript>           <script>         document.addEventListener('DOMContentLoaded', function() {           if (archive_analytics)             archive_analytics.create_tracking_image('in_page_executes');         });       </script>       </div>   </body> </html>         at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1385    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 416    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 416    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 759    at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 228
-- | -- | --

</body>
</html>

**Comment by garfield69** [comment]
It looks like the issue is that Jackett is using the old sort settings in the config.
To fix, use your dashboard to edit the InternetArchive config, and for the **Sort requested from site** use the pulldown to switch from `created` to `size` and then once selected, switch back to `created`.
Do the same for the Order requested from site, switch from `desc` to `asc` and back again.
Once you save the config should have the correct sort settings stored, and the Indexer should be working again.
Let me know how you go.

**Comment by heroku-miraheze** [comment]
It works again, thanks.
