### ISSUE TITLE
[mteamtp2fa] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by JayXon** [Jackett/Jackett#12495]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-01 02:22:56.4797 Info Environment version: 5.0.11 (/app/Jackett/) 
2021-11-01 02:22:56.4797 Info OS version: Unix 4.4.59.0 (64bit OS) (64bit process) 
2021-11-01 02:22:56.4797 Info Jackett variant: CoreLinuxAmdx64 
2021-11-01 02:22:56.4797 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
2021-11-01 02:22:56.4804 Info Running in Docker: Yes (image build: v0.19.108-ls48) 
2021-11-01 02:22:56.4804 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2021-11-01 02:22:56.4804 Info App config/log directory: /config/Jackett 
2021-11-01 02:22:56.4804 Info Using proxy: Disabled 
2021-11-01 02:22:56.4804 Info Using FlareSolverr: http://flaresolverr:8191 
2021-11-01 02:22:56.4804 Info Using HTTP Client: HttpWebClient2
```

### Description

using the same cookie, mteam works fine in my browser but redirects jackett to `https://kp.m-team.cc/verify.php?returnto=%2Findex.php`

### Logged Error Messages

```
2021-11-01 02:30:21.7444 Debug CACHE CleanIndexerCache / Indexer: mteamtp2fa 
2021-11-01 02:30:21.7444 Debug CACHE PruneCacheByTtl / Pruned queries: 0 
2021-11-01 02:30:21.7474 Debug CACHE Status / Total cached results: 0 
2021-11-01 02:30:21.7474 Debug CardigannIndexer (mteamtp2fa): Cookies after login: tp=REDACTED 
2021-11-01 02:30:21.7483 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://kp.m-team.cc/index.php) 
2021-11-01 02:30:21.9235 Debug WebClient(HttpWebClient2): Returning Redirect => https://kp.m-team.cc/verify.php?returnto=%2Findex.php 0 bytes 
2021-11-01 02:30:21.9249 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 183.8181ms 
2021-11-01 02:30:21.9249 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2021-11-01 02:30:21.9254 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 816
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 816
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
See if these troubleshooting steps help - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work (particularly the Notes section).

If not, remove the indexer from Jackett, restart Jackett. Sign out of the site in browser and sign back in again, get the new cookie (make sure to select the cookie and copy it, do not use the 'copy value' option). Add the indexer again with the new cookie.

**Comment by JayXon** [comment]
> See if these troubleshooting steps help - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work (particularly the Notes section).
>
Thanks, tried proxy into the server that's running Jackett, and in Chrome my existing cookies still works, didn't even need to relogin or anything.
>
> If not, remove the indexer from Jackett, restart Jackett. Sign out of the site in browser and sign back in again, get the new cookie (make sure to select the cookie and copy it, do not use the 'copy value' option). Add the indexer again with the new cookie.

I was trying to add the indexer when I encountered this issue, and I already tried signing out and back in before opening this issue.

Some observations:
If I manually go visit `https://kp.m-team.cc/verify.php?returnto=%2Findex.php` in Chrome, it just redirect to `https://kp.m-team.cc/index.php` immediately, so maybe it also did that when I'm using proxy but I didn't notice because it was too fast.

Everytime after I try to add it to Jackett, and get this error, next time I visit mteam in Chrome, I'll be redirected to cloudflare, which takes a few seconds.

Then I tried to put my Chrome cookie into Edge using devtools, and I got redirected to `https://kp.m-team.cc/verify.php?returnto=%2Findex.php`!!!! But this time I had to enter 2FA.

Now both browser use the same cookies, but whenever I switch browser, I get redirected and need to enter 2FA.
Now if Jackett get this error, I no longer get cloudflare in Chrome, instead I now need to enter 2FA.
I tried to sign out on both browsers and sign back in, without messing with the cookies, however I noticed that the cookies did not change at all! They both still have the same cookies as before.

Then I tried changing the Edge user agent to match exactly what my Chrome has, and now it works on both browsers without needing to enter 2FA.

So I think we'd need to change Jackett's user agent to match user's browser, can we add that as an option for this indexer?

**Comment by ilike2burnthing** [comment]
If you haven't already, volume map the container folder `/config` to somewhere accessible on your host, e.g. `/volume1/Docker/Jackett/config`.

Access `/volume1/Docker/Jackett/config` (or wherever you've set) and create a new folder in it called `cardigann` then a new folder within that one called `definitions` (so you end up with `/volume1/Docker/Jackett/config/cardigann/definitions`).

Download [mteamtp2fa-test.txt](https://github.com/Jackett/Jackett/files/7460273/mteamtp2fa-test.txt) and rename it to `mteamtp2fa-test.yml` (annoying GitHub limitation).

Copy/move that file to your newly created `/volume1/Docker/Jackett/config/cardigann/definitions` and restart the Jackett container.

Add mteamtp2fa-test, enter your cookie and user-agent, see if that works.

**Comment by JayXon** [comment]
Hmm still the same, maybe there's something else.

**Comment by ilike2burnthing** [comment]
Unfortunately it looks like this is a known issue for which there is currently no fix - https://github.com/Jackett/Jackett/issues/6830
