### ISSUE TITLE
Torrentleech not caching torrents

### ISSUE THREAD

**Issue by vanman69ny** [Jackett/Jackett#12503]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 20.04.3 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.70.0 (64bit OS) (64bit process)
Environment version: 5.0.11 (/app/)
Starting Jackett v0.19.124
```

### Description

I am using Jackett in a docker image on Truenas Scale, which is maintained by True Charts. The current version is: Version v0.19.124. I have multiple trackers(all private) setup. Torrentleech does not show any cached items at all. If i do a manual search, Jackett displays results from the tracker.(screeenshot included)

I am including enhanced logs as well. There is an error for acid-lounge, which is only because I need to re-submit the captcha code.

### Logged Error Messages
```
2021-11-03 19:06:30 	Info 	
Torznab search in BIT-HDTV => Found 82 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in Beyond-HD => Found 100 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in IPTorrents => Found 100 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in DigitalCore => Found 100 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in RetroFlix => Found 90 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in XWtorrents => Found 100 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in TorrentDB => Found 100 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in The Horror Charnel => Found 100 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in ScenePalace => Found 29 releases (from cache)
2021-11-03 19:06:30 	Info 	
Torznab search in TheScenePlace => Found 15 releases (from cache)
2021-11-03 19:05:15 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 19:05:13 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 19:04:31 	Info 	
Torznab search in Acid-Lounge => Found 100 releases
2021-11-03 19:03:31 	Error 	
Jackett.Common.ExceptionWithConfigData: Error: Error(s) Occurred!
                                    *Security Code was wrong.    at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 520    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 737    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 968    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2021-11-03 19:02:44 	Error 	
Jackett.Common.IndexerException: Exception (acidlounge): Login Failed, got redirected.  ---> System.Exception: Parse error  ---> Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 816    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1477    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 782    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1623    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 759    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 432
2021-11-03 19:02:44 	Error 	
Error on 20211103160244 for Acid-Lounge.txtJackett.Common.ExceptionWithConfigData: Login Failed, got redirected.    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 816    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1477
2021-11-03 19:02:43 	Info 	
CardigannIndexer (acidlounge): Relogin required
2021-11-03 19:02:22 	Error 	
Jackett.Common.IndexerException: Exception (acidlounge): Relogin failed  ---> System.Exception: Parse error  ---> System.Exception: Relogin failed    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1476    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 782    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1623    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 759    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 432
2021-11-03 19:02:22 	Error 	
Error on 20211103160222 for Acid-Lounge.txtSystem.Exception: Relogin failed    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1476
2021-11-03 19:02:22 	Error 	
CardigannIndexer (acidlounge): Found captcha during automatic login, aborting
2021-11-03 19:02:22 	Info 	
CardigannIndexer (acidlounge): Relogin required
2021-11-03 19:00:34 	Info 	
Torznab search in XWtorrents => Found 100 releases
2021-11-03 18:59:58 	Info 	
Torznab search in XWT-Classics => Found 25 releases (from cache)
2021-11-03 18:59:48 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 18:59:07 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 18:58:35 	Info 	
Torznab search in TorrentDB => Found 100 releases
2021-11-03 18:58:14 	Info 	
Torznab search in TheScenePlace => Found 15 releases
2021-11-03 18:57:34 	Info 	
Torznab search in The Horror Charnel => Found 99 releases
2021-11-03 18:55:20 	Info 	
Torznab search in ScenePalace => Found 100 releases
2021-11-03 18:54:53 	Info 	
Torznab search in RetroFlix => Found 90 releases
2021-11-03 18:54:34 	Info 	
Torznab search in IPTorrents => Found 100 releases (from cache)
2021-11-03 18:54:03 	Info 	
Torznab search in IPTorrents => Found 100 releases
2021-11-03 18:52:42 	Info 	
Torznab search in DigitalCore => Found 100 releases
2021-11-03 18:51:49 	Info 	
Torznab search in BIT-HDTV => Found 17 releases
2021-11-03 18:51:03 	Info 	
Torznab search in The Horror Charnel => Found 100 releases
2021-11-03 18:51:03 	Info 	
Torznab search in Beyond-HD => Found 100 releases
2021-11-03 18:51:03 	Info 	
Torznab search in TorrentDB => Found 100 releases
2021-11-03 18:51:03 	Info 	
Torznab search in TheScenePlace => Found 15 releases
2021-11-03 18:51:02 	Info 	
Torznab search in DigitalCore => Found 100 releases
2021-11-03 18:51:02 	Info 	
Torznab search in Beyond-HD => Found 100 releases
2021-11-03 18:51:02 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 18:51:02 	Info 	
Torznab search in XWtorrents => Found 100 releases
2021-11-03 18:51:02 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 18:51:02 	Info 	
Torznab search in BIT-HDTV => Found 82 releases
2021-11-03 18:51:01 	Info 	
Torznab search in ScenePalace => Found 29 releases
2021-11-03 18:51:01 	Info 	
Torznab search in RetroFlix => Found 90 releases
2021-11-03 18:51:00 	Info 	
Torznab search in IPTorrents => Found 100 releases
2021-11-03 18:35:27 	Info 	
Torznab search in BIT-HDTV => Found 86 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in The Horror Charnel => Found 100 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in DigitalCore => Found 100 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in ScenePalace => Found 29 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in XWtorrents => Found 100 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in IPTorrents => Found 100 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in Beyond-HD => Found 100 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in TorrentDB => Found 100 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in RetroFlix => Found 90 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in TheScenePlace => Found 15 releases (from cache)
2021-11-03 18:35:27 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 18:31:02 	Info 	
Torznab search in DigitalCore => Found 100 releases
2021-11-03 18:31:02 	Info 	
Torznab search in TorrentDB => Found 100 releases
2021-11-03 18:31:02 	Info 	
Torznab search in The Horror Charnel => Found 99 releases
2021-11-03 18:31:02 	Info 	
Torznab search in BIT-HDTV => Found 14 releases
2021-11-03 18:31:02 	Info 	
Torznab search in ScenePalace => Found 100 releases
2021-11-03 18:31:02 	Info 	
Torznab search in TheScenePlace => Found 15 releases
2021-11-03 18:31:01 	Info 	
Torznab search in Beyond-HD => Found 100 releases
2021-11-03 18:31:01 	Info 	
Torznab search in XWtorrents => Found 100 releases
2021-11-03 18:31:01 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 18:31:01 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 18:31:00 	Info 	
Torznab search in RetroFlix => Found 90 releases
2021-11-03 18:30:59 	Info 	
Torznab search in IPTorrents => Found 100 releases
2021-11-03 18:30:59 	Info 	
Torznab search in XWT-Classics => Found 25 releases
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in TorrentDB: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in IPTorrents: 2020
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in The Horror Charnel: 2010,2020,2030,2040,2045,2060
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in ScenePalace: 2020,2030,2040,2045,2050,2060
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in Beyond-HD: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in Twilight Torrents: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in Twilight Torrents: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in RetroFlix: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in DigitalCore: 2010,2020,2060
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in BIT-HDTV: 2010,2020,2030,2040,2045,2060
2021-11-03 18:30:54 	Warn 	
Some of the categories provided are unsupported in TheScenePlace: 2010,2020,2060
2021-11-03 18:19:56 	Info 	
Torznab search in The Horror Charnel => Found 100 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in XWtorrents => Found 100 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in DigitalCore => Found 100 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in ScenePalace => Found 29 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in RetroFlix => Found 90 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in Beyond-HD => Found 100 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in IPTorrents => Found 100 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in BIT-HDTV => Found 86 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in TorrentDB => Found 100 releases (from cache)
2021-11-03 18:19:56 	Info 	
Torznab search in TheScenePlace => Found 15 releases (from cache)
2021-11-03 18:04:32 	Info 	
Torznab search in XWtorrents => Found 100 releases
2021-11-03 18:04:32 	Info 	
Torznab search in The Horror Charnel => Found 100 releases
2021-11-03 18:04:32 	Info 	
Torznab search in TorrentDB => Found 100 releases
2021-11-03 18:04:31 	Info 	
Torznab search in Beyond-HD => Found 100 releases
2021-11-03 18:04:31 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 18:04:31 	Info 	
Torznab search in DigitalCore => Found 100 releases
2021-11-03 18:04:31 	Info 	
Torznab search in BIT-HDTV => Found 86 releases
2021-11-03 18:04:31 	Info 	
Torznab search in TheScenePlace => Found 15 releases
2021-11-03 18:04:30 	Info 	
Torznab search in IPTorrents => Found 100 releases
2021-11-03 18:04:30 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 18:04:30 	Info 	
Torznab search in RetroFlix => Found 90 releases
2021-11-03 18:04:30 	Info 	
Torznab search in ScenePalace => Found 29 releases
2021-11-03 17:48:52 	Info 	
Torznab search in TorrentDB => Found 100 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in DigitalCore => Found 100 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in XWtorrents => Found 100 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in BIT-HDTV => Found 84 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in RetroFlix => Found 90 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in ScenePalace => Found 29 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in Beyond-HD => Found 100 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in TheScenePlace => Found 15 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in IPTorrents => Found 100 releases (from cache)
2021-11-03 17:48:52 	Info 	
Torznab search in The Horror Charnel => Found 100 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in DigitalCore => Found 100 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in XWtorrents => Found 100 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in TorrentDB => Found 100 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in The Horror Charnel => Found 100 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in ScenePalace => Found 29 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in Beyond-HD => Found 100 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in RetroFlix => Found 90 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in TheScenePlace => Found 15 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in BIT-HDTV => Found 84 releases (from cache)
2021-11-03 17:33:19 	Info 	
Torznab search in IPTorrents => Found 100 releases (from cache)
2021-11-03 17:29:56 	Info 	
Torznab search in TorrentDB => Found 100 releases
2021-11-03 17:29:56 	Info 	
Torznab search in DigitalCore => Found 100 releases
2021-11-03 17:29:55 	Info 	
Torznab search in The Horror Charnel => Found 99 releases
2021-11-03 17:29:55 	Info 	
Torznab search in BIT-HDTV => Found 13 releases
2021-11-03 17:29:55 	Info 	
Torznab search in ScenePalace => Found 100 releases
2021-11-03 17:29:55 	Info 	
Torznab search in TheScenePlace => Found 15 releases
2021-11-03 17:29:55 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 17:29:55 	Info 	
Torznab search in Beyond-HD => Found 100 releases
2021-11-03 17:29:54 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 17:29:54 	Info 	
Torznab search in XWtorrents => Found 100 releases
2021-11-03 17:29:53 	Info 	
Torznab search in XWT-Classics => Found 25 releases
2021-11-03 17:29:53 	Info 	
Torznab search in IPTorrents => Found 100 releases
2021-11-03 17:29:53 	Info 	
Torznab search in RetroFlix => Found 90 releases
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in Twilight Torrents: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in TorrentDB: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in Beyond-HD: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in Twilight Torrents: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in BIT-HDTV: 2010,2020,2030,2040,2045,2060
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in RetroFlix: 2010,2020,2030,2040,2045,2050,2060
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in The Horror Charnel: 2010,2020,2030,2040,2045,2060
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in ScenePalace: 2020,2030,2040,2045,2050,2060
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in IPTorrents: 2020
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in DigitalCore: 2010,2020,2060
2021-11-03 17:29:42 	Warn 	
Some of the categories provided are unsupported in TheScenePlace: 2010,2020,2060
2021-11-03 17:17:54 	Info 	
Torznab search in XWtorrents => Found 100 releases
2021-11-03 17:17:53 	Info 	
Torznab search in The Horror Charnel => Found 100 releases
2021-11-03 17:17:52 	Info 	
Torznab search in TorrentDB => Found 100 releases
2021-11-03 17:17:52 	Info 	
Torznab search in Beyond-HD => Found 100 releases
2021-11-03 17:17:52 	Info 	
Torznab search in TheScenePlace => Found 15 releases
2021-11-03 17:17:52 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 17:17:52 	Info 	
Torznab search in Twilight Torrents => Found 100 releases
2021-11-03 17:17:51 	Info 	
Torznab search in DigitalCore => Found 100 releases
2021-11-03 17:17:51 	Info 	
Torznab search in BIT-HDTV => Found 84 releases
2021-11-03 17:17:50 	Info 	
Torznab search in IPTorrents => Found 100 releases
2021-11-03 17:17:50 	Info 	
Torznab search in RetroFlix => Found 90 releases
2021-11-03 17:17:50 	Info 	
Torznab search in ScenePalace => Found 29 releases
2021-11-03 17:02:07 	Info 	
Torznab search in DigitalCore => Found 100 releases (from cache)
2021-11-03 17:02:07 	Info 	
Torznab search in Twilight Torrents => Found 100 releases (from cache)
2021-11-03 17:02:07 	Info 	
Torznab search in RetroFlix => Found 90 releases (from cache)
2021-11-03 17:02:07 	Info 	
Torznab search in XWtorrents => Found 100 releases (from cache)
```

### Screenshots

![manualsearch](https://user-images.githubusercontent.com/15127428/140232373-f0124d25-6a4f-4124-a6a6-f49a59cfbdf1.png)

**Comment by ilike2burnthing** [comment]
Just tested TorrentLeech with caching enabled and it's definitely working.

A few things:
- those aren't enhanced logs
- you seem to be using default categories for all indexers in Radarr, you might want to address that
- TorrentLeech doesn't appear in those logs, it can't be cached if it's never used

What are you doing that you think should be causing results to be cached for that indexer? If it's having it set up in Radarr, Twilight Torrents results seem to be duplicated, so it may be possible that you've accidentally configured TorrentLeech using Twilight Torrents' torznab feed URL.

**Comment by vanman69ny** [comment]
Thanks, your looking ffound my mistake. I did have twilight torrents torznab setup for torrentleech. I had also checked the categories in sonarr and radarr for all of my jackett feeds as well.
