### ISSUE TITLE
[pterclub] Test search in PTerClub => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by scatking** [Jackett/Jackett#12513]
### Have you checked our Troubleshooting page for your issue?

- [x] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment
```
2021-11-06 11:23:10 | Info | Loading Native indexers ...-- | -- | --
2021-11-06 11:23:10 | Info | Using HTTP Client: HttpWebClient2
2021-11-06 11:23:10 | Info | Using FlareSolverr: No
2021-11-06 11:23:10 | Info | Using proxy: Disabled
2021-11-06 11:23:10 | Info | App config/log directory: /home/user/.config/Jackett
2021-11-06 11:23:10 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-11-06 11:23:10 | Info | Running in Docker: No
2021-11-06 11:23:10 | Info | File /etc/issue: Ubuntu 18.04.5 LTS \n \l
2021-11-06 11:23:10 | Info | Jackett variant: CoreLinuxAmdx64
2021-11-06 11:23:10 | Info | OS version: Unix 4.15.0.161 (64bit OS) (64bit process)
2021-11-06 11:23:10 | Info | Environment version: 5.0.11 (/home/asgard/Jackett/)
```

### Description

when I test connection to PTerClub, it raise this error 

### Logged Error Messages

```
CardigannIndexer (pterclub): Error while parsing row '
<tr>
	<td class="rowfollow" valign="middle" style="padding: 0px">
		<input type="checkbox" name="delid[]" value="159956" onclick="BlockSelect(event.shiftKey,this)">
	</td>
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=403">
			<img class="c_anime" src="pic/cattrans.gif" alt="动漫 (Anime)" title="动漫 (Anime)" style="background-image: url(pic/category/chd/scenetorrents/chs/catsprites.png);">
		</a>
		<a href="?source2=1">
			<img class="c_bd" src="pic/cattrans.gif" style="background-image: url(pic/category/chd/scenetorrents/chs/additional/bd.png);" alt="Blu-ray" title="Blu-ray">
		</a>
		<a class="third-icon" href="?team6=1">
			<img class="c_jpn" src="pic/cattrans.gif" style="background-image: url(pic/category/chd/scenetorrents/chs/additional/JPN.png);" alt="JPN" title="JPN">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left" style="padding: 0px">
		<table class="torrentname" width="100%">
			<tbody>
				<tr>
					<td class="embedded" style="width: 75px;text-align: center;">
						<img class="lozad" style="max-width: 71px; max-height: 46px; margin: 0 2px 0; vertical-align: bottom;" onmouseover="trPreview(this);" onmouseout="trPreviewOut(this);" src="/pic/spinner.svg" data-torrent="159956" data-src="//images.weserv.nl/?url=https://images-na.ssl-images-amazon.com/images/I/71T0spJLIkL._SL1081_.jpg&amp;w=150&amp;h=92&amp;fit=inside" data-orig="https://images-na.ssl-images-amazon.com/images/I/71T0spJLIkL._SL1081_.jpg" alt="preview" onerror="if (this.src != this.dataset.orig) { console.log('fallback: 159956 ' + this.src); this.src = this.dataset.orig;}">
					</td>
					<td class="embedded"><a title="Ronia the Robber's Daughter 2014 1080p Blu-ray AVC LPCM 2.0-Ue" href="details.php?id=159956">
							<b>&nbsp;Ronia the Robber's Daughter 2014 1080p Blu-ray AVC LPCM 2.0-Ue</b>
						</a>
						<b>[<font class="hot">热门</font>]</b>
						<br>&nbsp;山贼的女儿罗妮娅|山賊の娘ローニャ|Vol.1-Vol.9 Fin|UnperceivedExistence</td>
					<td class="embedded" width="6px">
						<div style="line-height: 16px"></div>
					</td>
					<td class="embedded" width="20px"></td>
					<td class="embedded" style="padding-left: 0px;" width="20" valign="middle">
						<a href="download.php?id=159956&amp;passkey=xxxxxxxxxxxxxxxxxx">
							<img class="download" src="pic/trans.gif" style="padding-bottom: 2px;" alt="download" title="下载本种">
						</a>
						<div style="line-height: 16px">
							<a href="torrents.php?check=unchecked">
								<img src="pic/questionmark.png" title="还没有审核" width="16px">
							</a>
						</div>
					</td>
					<td class="embedded" style="padding-left: 0px;" width="20" valign="middle">
						<a id="rssmark99" href="javascript: rssmark(159956,99);">
							<img class="delrssmark" src="pic/trans.gif" alt="Unrssmarked" title="RSS">
						</a>
						<a id="bookmark99" href="javascript: bookmark(159956,99);">
							<img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="收藏">
						</a>
					</td>
					<td class="embedded" width="44px">
						<div>
							<img src="pic/imdb.png" title="IMDb评分">
							<a target="_blank" href="https://www.imdb.com/title/tt3503520/">
								<label style="padding-left: 5px; cursor:pointer;"></label>
							</a>
							<font color="gray">N/A</font>
						</div>
						<div>
							<img src="pic/douban.png" title="豆瓣评分">
							<a target="_blank" href="https://movie.douban.com/subject/25822211/">
								<label style="padding-left: 5px; cursor:pointer;"></label>
							</a>
							<font color="gray">N/A</font>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow">
		<a href="comment.php?action=add&amp;pid=159956&amp;type=torrent" title="&amp;game=yes添加评论">0</a>
	</td>
	<td class="rowfollow nowrap">
		<span title="2021-11-04 23:01:09">1天<br>12时</span>
	</td>
	<td class="rowfollow">353.83<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=159956&amp;dllist=1#seeders">3</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=159956">
			<b>20</b>
		</a>
	</td>
	<td class="rowfollow" align="center">
		<i>匿名</i>
		<br>(<span class="nowrap">
			<a href="userdetails.php?id=14233" class="CrazyUser_Name">
				<b>orbdust</b>
			</a>
		</span>)</td>
	<td class="rowfollow">
		<a href="fastdelete.php?id=159956">
			<img class="staff_delete" src="pic/trans.gif" alt="D" title="删除">
		</a>
		<br>
		<a href="edit.php?returnto=%2Ftorrents.php%3Fsearch%3DThe%26incldead%3D0%26spstate%3D0%26search_area%3D0%26search_mode%3D0%26sort%3D4%26type%3Ddesc&amp;id=159956">
			<img class="staff_edit" src="pic/trans.gif" alt="E" title="编辑">
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=0 +08:00: DateTime parsing failed for "0 +08:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 115
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1563
```

**Comment by garfield69** [comment]
Are you by any chance an elevated user, which is to say, you have additional privileges that a regular users does not have?

The row you posted appears to hace a checkbox at the front of the category column, so this is throwing out the column count by one.
I will compare your row with the one I get as a regular user, and see if I can adjust the indexer to handle both layouts.

**Comment by scatking** [comment]
That makes sense, I have 2 additional message box which looks like this:
![图片](https://user-images.githubusercontent.com/34273647/140598812-73358875-a8b6-4304-8a08-390647011595.png)
They will show up when users send a report or staff PM and disappear when resolved 

```
<tr><td style="border: none; padding: 10px; background: blue">
<b><a href="reports.php" one-link-mark="yes"><font color="white">There is 1 new report</font></a></b></td></tr>
```
```
<tr><td style="border: none; padding: 10px; background: blue">
<b><a href="staffbox.php" one-link-mark="yes"><font color="white">There is 1 new staff message</font></a></b></td></tr>
```

**Comment by scatking** [comment]
looks like I made a mistake:
![图片](https://user-images.githubusercontent.com/34273647/140598982-c3739577-1281-43cf-93e8-b55bbd1631fb.png)
This is what we talk about then..Yes, this is a checkbox regular user don't have

**Comment by garfield69** [comment]
v0.19.207
