### ISSUE TITLE
[yggtorrent] Test search in YGGtorrent => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Foxlider** [Jackett/Jackett#12511]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 682 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.20348.0 (64bit OS)
Environment version: 5.0.11 (C:\ProgramData\Jackett\)
Starting Jackett v0.19.162
```

### Description

- Added YggTorrent indexer, log in and set up
- Getting error message `Test search in YGGtorrent => Found no results while trying to browse this tracker`

Pretty much the same error than #10951 

### Logged Error Messages

<html>
<body>

Date | Level | Message
-- | -- | --
2021-11-05 18:13:03 | Error | System.Exception: Test search in YGGtorrent => Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 311    at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
2021-11-05 18:13:03 | Info | Test search in YGGtorrent => Found 0 releases
2021-11-05 18:13:03 | Info | CardigannIndexer (yggtorrent): Relogin required
2021-11-05 18:13:02 | Info | CardigannIndexer (yggtorrent): Relogin required

</body>
</html>

**Comment by ilike2burnthing** [comment]
Please provide enhanced logs of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Foxlider** [comment]
<html>
<body>


2021-11-05 18:53:40 | Error | System.Exception: Test search in YGGtorrent => Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 311    at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
-- | -- | --
2021-11-05 18:53:40 | Info | Test search in YGGtorrent => Found 0 releases
2021-11-05 18:53:38 | Info | CardigannIndexer (yggtorrent): Relogin required
2021-11-05 18:53:37 | Info | CardigannIndexer (yggtorrent): Relogin required
2021-11-05 18:53:36 | Info | Torznab search in YGGtorrent => Found 0 releases
2021-11-05 18:53:36 | Info | CardigannIndexer (yggtorrent): Relogin required
2021-11-05 18:53:35 | Info | CardigannIndexer (yggtorrent): Relogin required


</body>
</html>

Not much more than that

**Comment by Foxlider** [comment]
Scratch last, I'm an idiot and did not see that the enhanced logs unticked it when refreshing

Here are the logs


[log.txt](https://github.com/Jackett/Jackett/files/7488022/log.txt)

**Comment by garfield69** [comment]
debug log, redacted for privacy.
[log.txt](https://github.com/Jackett/Jackett/files/7488256/log.txt)

**Comment by garfield69** [comment]
You are using the wrong domain.
Your setup is trying to use `https://yggtorrent.nz/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date` and yggtorrent is returning 404 not found.

Use your Jackett dashboard to edit your yggtorrent config and change the site link to `https://www3.yggtorrent.nz/`
save and see if that works for you.
Please report back so we can close the ticket.

**Comment by Foxlider** [comment]
Oh yeah it worked. 🤔 
Weird it is also valid without the ww3
