### ISSUE TITLE
Not skipping down trackers

### ISSUE THREAD

**Issue by iamLiquidX** [Jackett/Jackett#12514]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Loading Native indexers ...
2021-11-06 16:06:26	Info	
Using HTTP Client: HttpWebClient2
2021-11-06 16:06:26	Info	
Using FlareSolverr: No
2021-11-06 16:06:26	Info	
Using proxy: Disabled
2021-11-06 16:06:26	Info	
App config/log directory: /config/Jackett
2021-11-06 16:06:26	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-11-06 16:06:26	Info	
Running in Docker: No
2021-11-06 16:06:26	Info	
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2021-11-06 16:06:26	Info	
Jackett variant: CoreLinuxAmdx64
2021-11-06 16:06:26	Info	
OS version: Unix 4.4.0.1097 (64bit OS) (64bit process)
2021-11-06 16:06:26	Info	
Environment version: 5.0.11 (/app/Jackett/)
2021-11-06 16:06:25	Info	
Overriding port to 25191
2021-11-06 16:06:25	Info	
Starting Jackett v0.19.147
```

### Description

If any of the public configured tracker goes down , the manual search in all trackers stops working ,cause it doesn't skips the down tracker and throws error. Hope you can look into it.

### Logged Error Messages

Jackett.Common.IndexerException: Exception (firebit): Request to https://firebit.net/index.php?do=search&type=simple&q=harry%20potter%20e%20il%20prigioniero%20di failed (Error 522) - The tracker seems to be down.
 ---> System.Exception: Request to https://firebit.net/index.php?do=search&type=simple&q=harry%20potter%20e%20il%20prigioniero%20di failed (Error 522) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 639
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 595
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1374
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 759
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 228

**Comment by ilike2burnthing** [comment]
Unless a site is causing some massive delay so as to timeout your search, Jackett does move on to other indexers when one fails.

With the cache enabled you can also restart your search and it will pick up where it left off (the search term has to be the same, but you can remove indexers which are causing issues).

I'm not sure there's much more we can really do beyond that.
