### ISSUE TITLE
[divxtotal] Test search in DivxTotal => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by JMVS** [Jackett/Jackett#12527]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.19.210 
Environment version: 5.0.11 (/app/Jackett/) 
OS version: Unix 4.15.0.161 (64bit OS) (64bit process) 
Jackett variant: CoreLinuxAmdx64 
File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
Running in Docker: Yes (image build: v0.19.210-ls50) 
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
App config/log directory: /config/Jackett 
Using proxy: Disabled 
Using FlareSolverr: http://localhost:<removed>/
```

### Description

New DIVXTotal site: https://www.divxtotal.in/

### Logged Error Messages

DivxTotal: Failed to load url https://www.divxtotal.li/page/1/?s=
ystem.Exception: Test search in DivxTotal => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 311
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

### Screenshots

![imagen](https://user-images.githubusercontent.com/7751148/140803940-302f0bd9-e4c8-4728-afc0-beedd243050d.png)

**Comment by garfield69** [comment]
https://www.divxtotal.in/ is a clone run by a different owner, under the skin their html is a little different.
As is https://www.divxtotal.cc/ run by a 3rd owner whose html is even more different.
We need to find the proper https://www.divxtotal.li/ successor if this domain is broken or the indexer will need rewriting to switch to one of the clones.

**Comment by garfield69** [comment]
https://www.divxtotal.li/ is working for me with the Jackett indexer.
we cannot support the other clones without significant changes to the C# indexer to support the different html.

**Comment by ilike2burnthing** [comment]
https://www.divxtotal.li/ was down (I was getting `too many redirects` errors in browser). Seems to be fine now, so I think we can put this down to being a temporary issue. @JMVS if you continue to have issues feel free to reopen.

**Comment by Tau5** [comment]
It isn't working again. I've been testing and seems to not be working

**Comment by Tau5** [comment]
I am experiencing this as well

**Comment by ilike2burnthing** [comment]
Working ok here. Maybe you were unlucky and the site was temporarily down 8mins ago. If you still get the error, and the site is loading fine in browser on the same device and IP, then please open a new issue.
