### ISSUE TITLE
[cathoderaytube] Error: Bots are forbidden (Config)

### ISSUE THREAD

**Issue by kadektop2** [Jackett/Jackett#12539]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-12 19:36:59.3552 Info Initiating Jackett service start 
2021-11-12 19:37:00.2942 Info Starting Jackett v0.19.229 
2021-11-12 19:37:01.6273 Info Environment version: 5.0.12 (C:\ProgramData\Jackett\) 
2021-11-12 19:37:01.6273 Info OS version: Microsoft Windows NT 10.0.19043.0 (64bit OS) 
2021-11-12 19:37:01.6273 Info Jackett variant: CoreWindows 
2021-11-12 19:37:01.6304 Info Running in Docker: No 
2021-11-12 19:37:01.6304 Info ThreadPool MaxThreads: 682 workerThreads, 1000 completionPortThreads 
2021-11-12 19:37:01.6304 Info App config/log directory: C:\ProgramData\Jackett 
2021-11-12 19:37:01.6304 Info Using proxy: Disabled 
2021-11-12 19:37:01.6304 Info Using FlareSolverr: No 
2021-11-12 19:37:01.6304 Info Using HTTP Client: HttpWebClient2 
2021-11-12 19:37:01.6497 Info Loading Native indexers ... 
2021-11-12 19:37:01.8453 Info Loaded 87 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, danishbytes, darmowetorenty, divxtotal, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, oppaitime, orpheus, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, seals, secretcinema, sharewoodapi, shazbat, ShizaProject, showrss, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentseeds, torrentsyndikat, tvstore, xspeeds, xthor-api, zonaq, animetosho 
2021-11-12 19:37:01.8549 Info Loading Cardigann indexers from: C:\Windows\system32\config\systemprofile\AppData\Roaming\cardigann\definitions\, C:\Windows\system32\config\systemprofile\AppData\Local\cardigann\definitions\, C:\ProgramData\Jackett\Definitions 
2021-11-12 19:37:04.5323 Info Loaded 492 Cardigann indexers: 01torrent, 0daykiev, 0magnet, 1337x, 1ptbar, 24rolika, 2fast4you, 3changtrai, 3dtorrents, 4thd, 52pt, 7torrents, abtorrents, acgrip, acgsou, acidlounge, acrossthetasman, aftershock, aidoruonline, aither-api, aither, amigosshare, anaschcc, anilibria, anime-free, animeclipse, animeworld-api, animeworld, aniRena, anisource, arabafenice, arabp2p, arenabg, asiancinema, asiandvdclub, audiobookbay, audionews, aussierules, backups, badasstorrents, baibako, bangumi-moe, beitai, bestcore, beyond-hd-oneurl, beyond-hd, bibliotik, bigfangroup, bit-titan, bitbazis, bitded, bithorlo, bithumen, bitru, bitsearch, bitsexy, bitspyder, Bittorrentfiles, bitturk, bluebirdhd, blutopia-api, blutopia, booktracker, bootytape, borgzelle, boxingtorrents, brasiltracker, broadcity, brsociety-api, brsociety, bt4g, btdigg, btetree, btnext, btschool, btsow, bwtorrents, byrutor, carpathians, carphunter, cartoonchaos, casatorrent, cathoderaytube, catorrent, ccfbits, ceskeforum, chdbits, chilebt, cinemageddon, cinemamovies, cinematik, classix, coastalcrew, comicat, concen, concertos, cpasbien, cpasbienclone, crazyhd, crazyspirits, crnaberza, crt2fa, cryptichaven, dariustracker, dark-shadow, darktracker, datascene-api, datascene, datatalli, deildu, demonoid, desireleasers, desitorrents-api, desitorrents, devilsplayground, diablotorrent, digitalcore, dimeadozen, discfan, divteam, dmhy, docspedia, dragonworldreloaded, dxp, ebookparadijs, ebooks-shares, efectodoppler, ehentai, elitetorrent-biz, empornium, empornium2fa, eniahd, esharenet, estone, ettv, exkinoray, extratorrent-st, extremebits, extremetorrents, extremlymtorrents, exttorrents, eztv, falkonvisionteam, fanoin, fantasticheaven, fantastiko, femdomcult, filebase, filelisting, film-paleis, finelite, finvip, firebit, fouducinema, frozenlayer, funkytorrents, gamestorrents, gay-torrents, gay-torrentsorg, gaytorrentru, generationfree, genesismovement, gfxpeers, gigatorrents, girotorrent, gktorrent, glodls, greekdiamond, greekteam, gtorrentpro, haidan, haitang, hamsterstudio, happyfappy, hd4fans, hdai, hdarea, hdatmos, hdbits, hdbitscom, hdc, hdcenter, hdchina, hdcity, hdcztorrent, hddolby, hdforever, hdhome, hdhouse, hdme, hdolimpo, hdonly, hdroute, hdsky, hdspain, hdtime, hdtorrentsit, hdturk, hdu, hdzone, hellastz, hqsource, huntorrent, ibit, idope, ilcorsaroblu, ilcorsaronero, immortuos, indietorrents, insanetracker, internetarchive, isohunt2, itorrent, iv-torrents, jpopsuki, jptv, karagarga, keepfriends, kickasstorrents-to, kickasstorrents-ws, kinonavse100, kinorun, kinozal, kisssub, lastfiles, lat-team, learnbits, learnflakes, legittorrents, lemonhd, lepornoinfo, lesaloon, libranet, limetorrents, limetorrentsclone, linkomanija, linuxtracker, losslessclub, mactorrentsdownload, madsrevolution, magicheaven, magico, majomparade, marinetracker, megamixtracker, megapeer, mesevilag, metaltracker, microbit, mikan, milkie, mircrew, mixtapetorrent, mma-torrents, mnv, mononokebt, mousebits, moviesdvdr, moviesite, movietorrent, mteamtp, mteamtp2fa, muziekfabriek, mvgroupforum, mvgroupmain, mypornclub, myspleen, nbtorrents, netcosmo, nethd, netlab, newpct-me, newretro, newstudio, newstudiol, nforce, nipponsei, nitro, nntt, noname-club, noname-clubl, nyaasi, oasis, omgwtftrackr, oncesearch, onejav, opencd, opensharing, oshenpt, ourbits, oxtorrent, p2pbg, p2pelite, parnuxi, pctorrent, peerjunkies, peersfm, pier720, piratadigital, piratbit, piratbitl, pirateiro, pixelcove, polishsource, pornbay, pornbits, pornforall, pornleech, pornolive, pornorip, pornoslab, pornotor, pornotorrent, portugas, potuk, proaudiotorrents, proporno, prostylex, pterclub, ptfiles, pthome, ptmsg, ptsbao, pttime, punkshorror, puntotorrent, purovicio, pussytorrents, puurhollands, pwtorrents, r3vwtf, racing4everyone, racingforme, rainbowtracker, rapidzona, redbits, redstartorrent, reelflix-api, reelflix, renegade, resurrectthenet, rgfootball, rintor, rintornet, riperam, RockBox, romanianmetaltorrents, rptorrents, rus-media, rustorka, rutor, rutracker-ru, scenepalace, scenerush, sdbits, seedfile, selezen, sexxi, sexypics, shareisland-api, shareisland, sharewood, shokweb, siambit, skipthecommercials-api, skipthecommercials, sktorrent-org, sktorrent, slosoul, snowpt, solidtorrents, sosulki, soulvoice, soundpark, speedmasterhd, speedtorrentreloaded, spiritofrevolution, sporthd, sportscult, springsunday, sugoimusic, sukebeinyaasi, superbits, swarmazon, tapochek, tasmanit, teamhd, teamos, tekno3d, tellytorrent-api, tellytorrent, teracod, theaudioscene, theempire, thefallingangels, thegeeks, thehorrorcharnel, theleachzone, themixingbowl, theoccult, thepiratebay, theplace, thesceneplace, theshinning, theshow, thevault, tjupt, tlfbits, tokyotosho, torlock, torlook, toros, torrent-explosiv, torrent-paradise-ml, torrent-pirat, torrent-turk, torrent9, torrent9clone, torrentbd, torrentccf, torrentdb, torrentdownload, torrentdownloads, torrentfunk, torrentgalaxy, torrenthr, torrenting, torrentkitty, torrentland, torrentleech-pl, torrentleech, torrentlt, torrentmasters, torrentmax, torrentoyunindir, torrentparadise, torrentproject2, torrentqq, torrentsectorcrew, torrentsir, torrentslocal, torrentsurf, torrentv, torrentview, torrentwhiz, torrentz2eu, totallykids, totheglory, totheglorycookie, trackeros, trancetraffic, trezzor, tribalmixes, trupornolabs, turkseed, turktorrent, tvchaosuk, twilight, twilightszoom, u2, uhdbits, underverse, underversel, uniondht, unionfansub, uniongang, unlimitz, vizuk, vsthouse, vsttorrents, wdt, whiteangel, wihd, woot, xiteme, xbytesv2, xwtclassics, xwtorrents, xxxadulttorrent, xxxtor, xxxtorrents, ydypt, yggcookie, yggtorrent, yourbittorrent, yts, zamundanet, zelkaorg, zetorrents, zomb, zooqle, ztracker 
2021-11-12 19:37:04.5323 Info Loaded 579 indexers in total 
2021-11-12 19:37:04.5323 Info Adding aggregate indexer ('all' indexer) ... 
2021-11-12 19:37:04.5439 Info Adding filter indexer ('type:public' indexer) ... 
2021-11-12 19:37:04.5439 Info Adding filter indexer ('type:private' indexer) ... 
2021-11-12 19:37:04.5439 Info Adding filter indexer ('type:semi-public' indexer) ... 
2021-11-12 19:37:04.7923 Info Jackett startup finished in 5.030 s
```

### Description

Steps to reproduce:
1. Add indexer
2. Choose Cathode-Ray.Tube
3. Fill username and password
4. Press okay
5. Error appears.

To be clear I'm not using any kind of bots nor I am familiar with one.

### Logged Error Messages

```
2021-11-12 19:42:38.0330 Error Jackett.Common.ExceptionWithConfigData: Error: Bots are forbidden
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 520
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 737
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 968
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26 Jackett.Common.ExceptionWithConfigData: Error: Bots are forbidden
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 520
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 737
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 968
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

```

### Screenshots

![Error message](https://user-images.githubusercontent.com/15376541/141469692-fd22d933-84e9-4498-9c0f-1a8f293e607d.png)

**Comment by garfield69** [comment]
Yup, it appears CRT have updated their login page and Jackett does not pass muster. 
I'll try to update the indexer to provide the new requirements.

**Comment by garfield69** [comment]
v0.19.249
