### ISSUE TITLE
[pterclub] Login failed: No form found on https://pterclub.com/login.php using form selector form[action=

### ISSUE THREAD

**Issue by onthecliff** [Jackett/Jackett#12548]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.19.207-ls50)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 5.0.12 (/app/Jackett/)
```

### Description

When I try to add PTerClub, it returns a "No form found" error.

I assume this is happening because Jackett does not know how/where to input the login info when the page is loaded.

I think the cause of this is that whenever I refresh the PTerClub login page, a green loading circle in the middle of the page prevents any data from being entered for 1-2 seconds. Because nothing can be entered for that short period of time, does Jackett assume there is no form?

### Logged Error Messages

An error occurred while updating this indexer
Login failed: No form found on https://pterclub.com/login.php using form selector form[action="takelogin.php"]

**Comment by garfield69** [comment]
The pterclub indexer works for me.  I can enter my credentials in the Jackett dashboard config page, fill in the captcha and click save to login, and subsequently use the torrent search without issues.

To see what may be happening at your end, turn on enhanced logging and provide the full redacted log here, pehaps the additional Debug and HTML will give a clue to your problem.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by onthecliff** [comment]
Hmm, I just noticed that for some reason my PTerClub config doesn't have a captcha now, but it did a couple of hours ago. Maybe if I could get it back it would work? https://i.imgur.com/lELnIkS.jpeg

I've tried restarting the container a few times and no luck. I'm running Jackett Version v0.19.249.

I turned on enhanced logger and I think this is the full log for the error (I don't have much experience here so I apologize if I'm doing anything wrong).

Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://pterclub.com/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 573
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 968
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by garfield69** [comment]
yeah, nah.
the stack trace you provided is useless in this situation.
please read the link I gave you earlier and provide the log file with the complete debug and html included, its the only way we can hopefully see the traffic to and from your session.
