### ISSUE TITLE
[magicheaven] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by alscho12** [Jackett/Jackett#12556]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.19.62-ls48)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.19.0.17 (64bit OS) (64bit process)
Environment version: 5.0.11 (/app/Jackett/)
```

### Description

The magic-heaven indexer that used to work stopped working.

>  An error occurred while testing this indexer
Test search in magic-heaven => Found no results while trying to browse this tracker

To reproduce:

- Add magic-heaven 
- Run a test search

Tried removing and re-adding the indexer, but still received same error message.  Verified that I can login to the tracker site directly and that there are no restrictions on my account.

This was working a few weeks ago when it was first added to Jackett (and consequently added as a Torznab indexer in Sonarr).  I only noticed there was an error when I tried to add magic-heaven as a Torznab indexer in Radarr earlier today.

The issue can be recreated.

### Logged Error Messages

```
2021-11-15 11:12:21	Error	
System.Exception: Test search in magic-heaven => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 311
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

2021-11-15 11:12:21	Info	
Test search in magic-heaven => Found 0 releases
```
[log.txt](https://github.com/Jackett/Jackett/files/7540322/log.txt)

**Comment by garfield69** [comment]
A couple weeks ago magic-heaven upgraded their web site engine from TS Special Edition v.7.5 to v8.0
The Jackett indexer was updated to handle the new html selectors that come with the v8.0 upgrade, which was published beginning with 0.19.138
You are using Jackett Docker image 0.19.62
So fetch and update to the latest Jackett docker image to resolve your issue.
