### ISSUE TITLE
[rarbg] Test search in RARBG => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by raphaelmaria** [Jackett/Jackett#12550]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2

Using FlareSolverr: No
	
Using proxy: Disabled

App config/log directory: /home/raphaelmaria/.config/Jackett
	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
	
Running in Docker: No

File /etc/issue: Ubuntu 20.04.3 LTS \n \l
	
Jackett variant: CoreLinuxAmdx64

OS version: Unix 5.11.0.38 (64bit OS) (64bit process)

Environment version: 5.0.12 (/opt/Jackett/)
	
Starting Jackett v0.19.249
```

### Description

An error occurred while testing this indexer
Test search in RARBG => Found no results while trying to browse this tracker

### Logged Error Messages

System.Exception: Test search in RARBG => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 311
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

### Screenshots

![Screenshot_351](https://user-images.githubusercontent.com/26657697/141662708-47649554-df2d-481d-ac13-369f610aae4f.png)

**Comment by garfield69** [comment]
well know issue with the rarbg API is that it intermittently fails to return results.
retrying after a short break usually yields results again.
The indexer is working for me ATM.
There is nothing we can do from the Jackett end, albeit I will drop book search support and category 35 since RARBG no longer lists this on their torrent search page.
