### ISSUE TITLE
sexxi: Error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12567]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
latest
```

### Description

Empty query

### Logged Error Messages

```
CardigannIndexer (sexxi): Error while parsing row '
<div class="short-item">
	<div class="short-cols fx-row">
		<a class="short-img img-fit" href="https://sexxi.club/1225-ot-razgovora-k-trahu-from-talking-to-fucking-2021-torrent.html">
			<img src="/uploads/posts/2021-11/1636364316_viola-weber.jpg" alt="От разговора к траху / From talking to fucking (2021) Торрент">
			<div class="short-label">
				SATRip
			</div>
		</a>
		<div class="short-desc fx-1 fx-col fx-between">
			<div class="short-header fx-row fx-middle">
				<a class="short-title fx-1" href="https://sexxi.club/1225-ot-razgovora-k-trahu-from-talking-to-fucking-2021-torrent.html">От разговора к траху / From talking to fucking (2021) Торрент</a>
			</div>
			<ul class="short-list">
				<li>
					<span>Год выхода:</span>
					2021
				</li>
				<li>
					<span>Актеры:</span>
					Viola Weber
				</li>
				<li>
					<span>Жанр:</span>
					Просто секс, молодые
				</li>
				<li>
					<span>Режиссёр:</span>
					-
				</li>
			</ul>
			<div class="short-meta fx-row fx-middle icon-left">
				<div class="mrating">
					<div id="ratig-layer-1225">
						<div class="rating">
							<ul class="unit-rating">
								<li class="current-rating" style="width:0%;">0</li>
								<li>
									<a href="#" title="Плохо" class="r1-unit" onclick="doRate('1', '1225'); return false;">1</a>
								</li>
								<li>
									<a href="#" title="Приемлемо" class="r2-unit" onclick="doRate('2', '1225'); return false;">2</a>
								</li>
								<li>
									<a href="#" title="Средне" class="r3-unit" onclick="doRate('3', '1225'); return false;">3</a>
								</li>
								<li>
									<a href="#" title="Хорошо" class="r4-unit" onclick="doRate('4', '1225'); return false;">4</a>
								</li>
								<li>
									<a href="#" title="Отлично" class="r5-unit" onclick="doRate('5', '1225'); return false;">5</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="short-meta-item">
					<span class="fal fa-calendar-alt"></span>08.11.2021</div>
				<div class="short-meta-item fx-1">
					<span class="fal fa-eye"></span>87</div>
				<a href="https://sexxi.club/1225-ot-razgovora-k-trahu-from-talking-to-fucking-2021-torrent.html" class="short-btn btn">Скачать торрент</a>
				<br>
				<div class="line2"></div>
				<p class="argcat small">
					<b>
						<font color="#c0d8f7">Категория:</font>
					</b>
					<a href="https://sexxi.club/young/">Молодые</a>
				</p>
			</div>
		</div>
	</div>
</div>':

System.Exception: Error while parsing field=category, selector=p a:nth-child(3), p:has(a:nth-child(3):empty) a:nth-child(2), value=<null>: Selector "p a:nth-child(3), p:has(a:nth-child(3):empty) a:nth-child(2)" didn't match 
<div class="short-item">
	<div class="short-cols fx-row">
		<a class="short-img img-fit" href="https://sexxi.club/1225-ot-razgovora-k-trahu-from-talking-to-fucking-2021-torrent.html">
			<img src="/uploads/posts/2021-11/1636364316_viola-weber.jpg" alt="От разговора к траху / From talking to fucking (2021) Торрент">
			<div class="short-label">
				SATRip
			</div>
		</a>
		<div class="short-desc fx-1 fx-col fx-between">
			<div class="short-header fx-row fx-middle">
				<a class="short-title fx-1" href="https://sexxi.club/1225-ot-razgovora-k-trahu-from-talking-to-fucking-2021-torrent.html">От разговора к траху / From talking to fucking (2021) Торрент</a>
			</div>
			<ul class="short-list">
				<li>
					<span>Год выхода:</span>
					2021
				</li>
				<li>
					<span>Актеры:</span>
					Viola Weber
				</li>
				<li>
					<span>Жанр:</span>
					Просто секс, молодые
				</li>
				<li>
					<span>Режиссёр:</span>
					-
				</li>
			</ul>
			<div class="short-meta fx-row fx-middle icon-left">
				<div class="mrating">
					<div id="ratig-layer-1225">
						<div class="rating">
							<ul class="unit-rating">
								<li class="current-rating" style="width:0%;">0</li>
								<li>
									<a href="#" title="Плохо" class="r1-unit" onclick="doRate('1', '1225'); return false;">1</a>
								</li>
								<li>
									<a href="#" title="Приемлемо" class="r2-unit" onclick="doRate('2', '1225'); return false;">2</a>
								</li>
								<li>
									<a href="#" title="Средне" class="r3-unit" onclick="doRate('3', '1225'); return false;">3</a>
								</li>
								<li>
									<a href="#" title="Хорошо" class="r4-unit" onclick="doRate('4', '1225'); return false;">4</a>
								</li>
								<li>
									<a href="#" title="Отлично" class="r5-unit" onclick="doRate('5', '1225'); return false;">5</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="short-meta-item">
					<span class="fal fa-calendar-alt"></span>08.11.2021</div>
				<div class="short-meta-item fx-1">
					<span class="fal fa-eye"></span>87</div>
				<a href="https://sexxi.club/1225-ot-razgovora-k-trahu-from-talking-to-fucking-2021-torrent.html" class="short-btn btn">Скачать торрент</a>
				<br>
				<div class="line2"></div>
				<p class="argcat small">
					<b>
						<font color="#c0d8f7">Категория:</font>
					</b>
					<a href="https://sexxi.club/young/">Молодые</a>
				</p>
			</div>
		</div>
	</div>
</div>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1563

CardigannIndexer (sexxi): Error while parsing row '
<div class="short-item">
	<div class="short-cols fx-row">
		<a class="short-img img-fit" href="https://sexxi.club/1227-lili-konchaet-na-silnom-lily-cums-on-strong-2021-torrent.html">
			<img src="/uploads/posts/2021-11/1636365235_lily-lou.jpg" alt="Лили кончает / Lily Cums on Strong (2021) Торрент">
			<div class="short-label">
				SATRip
			</div>
		</a>
		<div class="short-desc fx-1 fx-col fx-between">
			<div class="short-header fx-row fx-middle">
				<a class="short-title fx-1" href="https://sexxi.club/1227-lili-konchaet-na-silnom-lily-cums-on-strong-2021-torrent.html">Лили кончает / Lily Cums on Strong (2021) Торрент</a>
			</div>
			<ul class="short-list">
				<li>
					<span>Год выхода:</span>
					2021
				</li>
				<li>
					<span>Актеры:</span>
					Lily Lou
				</li>
				<li>
					<span>Жанр:</span>
					Просто секс, брюнетка
				</li>
				<li>
					<span>Режиссёр:</span>
					-
				</li>
			</ul>
			<div class="short-meta fx-row fx-middle icon-left">
				<div class="mrating">
					<div id="ratig-layer-1227">
						<div class="rating">
							<ul class="unit-rating">
								<li class="current-rating" style="width:100%;">100</li>
								<li>
									<a href="#" title="Плохо" class="r1-unit" onclick="doRate('1', '1227'); return false;">1</a>
								</li>
								<li>
									<a href="#" title="Приемлемо" class="r2-unit" onclick="doRate('2', '1227'); return false;">2</a>
								</li>
								<li>
									<a href="#" title="Средне" class="r3-unit" onclick="doRate('3', '1227'); return false;">3</a>
								</li>
								<li>
									<a href="#" title="Хорошо" class="r4-unit" onclick="doRate('4', '1227'); return false;">4</a>
								</li>
								<li>
									<a href="#" title="Отлично" class="r5-unit" onclick="doRate('5', '1227'); return false;">5</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="short-meta-item">
					<span class="fal fa-calendar-alt"></span>08.11.2021</div>
				<div class="short-meta-item fx-1">
					<span class="fal fa-eye"></span>111</div>
				<a href="https://sexxi.club/1227-lili-konchaet-na-silnom-lily-cums-on-strong-2021-torrent.html" class="short-btn btn">Скачать торрент</a>
				<br>
				<div class="line2"></div>
				<p class="argcat small">
					<b>
						<font color="#c0d8f7">Категория:</font>
					</b>
					<a href="https://sexxi.club/brunette/">Брюнетки</a>
				</p>
			</div>
		</div>
	</div>
</div>':

System.Exception: Error while parsing field=category, selector=p a:nth-child(3), p:has(a:nth-child(3):empty) a:nth-child(2), value=<null>: Selector "p a:nth-child(3), p:has(a:nth-child(3):empty) a:nth-child(2)" didn't match 
<div class="short-item">
	<div class="short-cols fx-row">
		<a class="short-img img-fit" href="https://sexxi.club/1227-lili-konchaet-na-silnom-lily-cums-on-strong-2021-torrent.html">
			<img src="/uploads/posts/2021-11/1636365235_lily-lou.jpg" alt="Лили кончает / Lily Cums on Strong (2021) Торрент">
			<div class="short-label">
				SATRip
			</div>
		</a>
		<div class="short-desc fx-1 fx-col fx-between">
			<div class="short-header fx-row fx-middle">
				<a class="short-title fx-1" href="https://sexxi.club/1227-lili-konchaet-na-silnom-lily-cums-on-strong-2021-torrent.html">Лили кончает / Lily Cums on Strong (2021) Торрент</a>
			</div>
			<ul class="short-list">
				<li>
					<span>Год выхода:</span>
					2021
				</li>
				<li>
					<span>Актеры:</span>
					Lily Lou
				</li>
				<li>
					<span>Жанр:</span>
					Просто секс, брюнетка
				</li>
				<li>
					<span>Режиссёр:</span>
					-
				</li>
			</ul>
			<div class="short-meta fx-row fx-middle icon-left">
				<div class="mrating">
					<div id="ratig-layer-1227">
						<div class="rating">
							<ul class="unit-rating">
								<li class="current-rating" style="width:100%;">100</li>
								<li>
									<a href="#" title="Плохо" class="r1-unit" onclick="doRate('1', '1227'); return false;">1</a>
								</li>
								<li>
									<a href="#" title="Приемлемо" class="r2-unit" onclick="doRate('2', '1227'); return false;">2</a>
								</li>
								<li>
									<a href="#" title="Средне" class="r3-unit" onclick="doRate('3', '1227'); return false;">3</a>
								</li>
								<li>
									<a href="#" title="Хорошо" class="r4-unit" onclick="doRate('4', '1227'); return false;">4</a>
								</li>
								<li>
									<a href="#" title="Отлично" class="r5-unit" onclick="doRate('5', '1227'); return false;">5</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="short-meta-item">
					<span class="fal fa-calendar-alt"></span>08.11.2021</div>
				<div class="short-meta-item fx-1">
					<span class="fal fa-eye"></span>111</div>
				<a href="https://sexxi.club/1227-lili-konchaet-na-silnom-lily-cums-on-strong-2021-torrent.html" class="short-btn btn">Скачать торрент</a>
				<br>
				<div class="line2"></div>
				<p class="argcat small">
					<b>
						<font color="#c0d8f7">Категория:</font>
					</b>
					<a href="https://sexxi.club/brunette/">Брюнетки</a>
				</p>
			</div>
		</div>
	</div>
</div>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1563
```

**Comment by garfield69** [comment]
this was fixed 2 days ago with db5ee7d0128819c97a43181b8d0668c9dba8cd6b beginning with Jackett v0.19.266
