### ISSUE TITLE
[animetosho] Exception (animetosho): No route to host: No route to host (feed.mirror.animetosho.org:443) (Test)

### ISSUE THREAD

**Issue by joetea** [Jackett/Jackett#12588]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-20 19:27:38	Info	Loading Native indexers ...
2021-11-20 19:27:38	Info	Using HTTP Client: HttpWebClient2
2021-11-20 19:27:38	Info	Using FlareSolverr: No
2021-11-20 19:27:38	Info	Using proxy: Disabled
2021-11-20 19:27:38	Info	App config/log directory: /config/Jackett
2021-11-20 19:27:38	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-11-20 19:27:38	Info	Running in Docker: Yes (image build: v0.20.43-ls50)
2021-11-20 19:27:38	Info	File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2021-11-20 19:27:38	Info	Jackett variant: CoreLinuxAmdx64
2021-11-20 19:27:38	Info	OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2021-11-20 19:27:38	Info	Environment version: 6.0.0 (/app/Jackett/)
2021-11-20 19:27:36	Info	Starting Jackett v0.20.43
```

### Description

Basic Addition of Indexer Tosho and Nyaa to Jackett for Synology DS920 Docker
no route to host on jackett or sonarr

### Logged Error Messages

Jackett.Common.IndexerException: Exception (animetosho): No route to host
 ---> System.Net.Http.HttpRequestException: No route to host (feed.animetosho.org:443)
 ---> System.Net.Sockets.SocketException (113): No route to host
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.Feeds.BaseFeedIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Feeds/BaseFeedIndexer.cs:line 59
   at Jackett.Common.Indexers.Feeds.AnimeTosho.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Feeds/AnimeTosho.cs:line 48
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

### Screenshots

.

**Comment by garfield69** [comment]
the https://mirror.animetosho.org/ that you are using apparently no longer supports the feed API, with https://feed.mirror.animetosho.org/ now returning a domain not found.
Use your Jackett dashboard to set the site link to https://animetosho.org/ which is the only domain we support and which I know works as I tested this indexer just now.

**Comment by joetea** [comment]
Hi, thanks for replying so fast!

Sorry, I was going through all the sites to try them, that just happened to be the latest log.
I have tried https://animetosho.org/
and also
https://nyaa.si from the simple clicks on jackett

Here is the log for the normal unedited animetosho

ackett.Common.IndexerException: Exception (animetosho): No route to host
 ---> System.Net.Http.HttpRequestException: No route to host (feed.animetosho.org:443)
 ---> System.Net.Sockets.SocketException (113): No route to host
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.Feeds.BaseFeedIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Feeds/BaseFeedIndexer.cs:line 59
   at Jackett.Common.Indexers.Feeds.AnimeTosho.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Feeds/AnimeTosho.cs:line 48
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

**Comment by garfield69** [comment]
open a terminal and see what you get from a 
`openssl s_client -connect animetosho.org:443`
and
`curl -vvv https://animetosho.org/`
and similar for https://nyaa.si/

I presume you can access other sites using other public indexers on jackett?

**Comment by joetea** [comment]
Hi,

root@The_Executor:~# openssl s_client -connect animetosho.org:443
140561958637952:error:02002071:lib(2):func(2):reason(113):NA:0:
140561958637952:error:2008A067:lib(32):func(138):reason(103):NA:0:
connect:errno=113
root@The_Executor:~# curl -vvv https://animetosho.org
* Failed to connect to animetosho.org port 443: No route to host
curl: (7) Failed to connect to animetosho.org port 443: No route to host
root@The_Executor:~#
root@The_Executor:~# openssl s_client -connect nyaa.si:443
140561958637952:error:02002071:lib(2):func(2):reason(113):NA:0:
140561958637952:error:2008A067:lib(32):func(138):reason(103):NA:0:
connect:errno=113
root@The_Executor:~# curl -vvv https://nyaa.si/
* Failed to connect to animetosho.org port 443: No route to host
curl: (7) Failed to connect to animetosho.org port 443: No route to host
root@The_Executor:~#

RARBG seems to work as an indexer on jackett, test went ok

**Comment by garfield69** [comment]
@ilike2burnthing  what do you think? Is this another flavour of the R3,Let's Encrypt CA issue or something else?
Docker, Linux, not my cup of tea. Help. Thanks.

**Comment by ilike2burnthing** [comment]
Please also check Anidex so we can check for a trend here. You could add a few more data points by curl-ing:

```none
https://blutopia.xyz/
https://mircrew-releases.org/
https://hd-only.org/
https://greekdiamond.info/
https://forums.mvgroup.org/
```

If those are all failing then see the solutions in the last few comments here - https://github.com/Jackett/Jackett/issues/12341

**Comment by joetea** [comment]
Hi All,

Thanks for taking the time to reply.
anidex does not seem to work with same error 

curling all these seem to go through.
https://blutopia.xyz/
https://mircrew-releases.org/
https://hd-only.org/
https://greekdiamond.info/
https://forums.mvgroup.org/



Could not chdir to home directory /var/services/homes/joetea: No such file or directory
joetea@The_Executor:/$ curl -vvv https://anidex.info
* Failed to connect to anidex.info port 443: No route to host
curl: (7) Failed to connect to anidex.info port 443: No route to host

joetea@The_Executor:/$ curl -vvv https://blutopia.xyz
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
> GET / HTTP/2
> Host: blutopia.xyz
> user-agent: curl/7.75.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 302
< server: nginx
< content-type: text/html; charset=UTF-8
< location: https://blutopia.xyz/login
< cache-control: no-cache, private
< date: Wed, 24 Nov 2021 11:19:12 GMT
< content-security-policy: base-uri 'self'; form-action 'self'; frame-ancestors 'self'; object-src 'self'; script-src 'self' 'unsafe-eval' https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js https://code.jquery.com/jquery-3.2.1.min.js https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js; block-all-mixed-content; upgrade-insecure-requests
< permissions-policy: accelerometer=(self), ambient-light-sensor=(self), autoplay=(self), battery=(self), camera=(self), cross-origin-isolated=(self), display-capture=(self), document-domain=*, encrypted-media=(self), execution-while-not-rendered=*, execution-while-out-of-viewport=*, fullscreen=(self), geolocation=(self), gyroscope=(self), magnetometer=(self), microphone=(self), midi=(self), navigation-override=(self), payment=(self), picture-in-picture=*, publickey-credentials-get=(self), screen-wake-lock=(self), sync-xhr=*, usb=(self), web-share=(self), xr-spatial-tracking=(self)
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< expect-ct: max-age=2147483648
< x-content-type-options: nosniff
< x-download-options: noopen
< x-frame-options: sameorigin
< x-permitted-cross-domain-policies: none
< x-xss-protection: 1; mode=block
< referrer-policy: no-referrer-when-downgrade
< set-cookie: laravel_session=eyJpdiI6ImN4dXIyTEdvWFNSUmF4NEZpRnFUcmc9PSIsInZhbHVlIjoiV0ZwMGRpODFIbUI1WTJXVUpMbWtZQzkzSmY0ZWZORVBzVnVwNGZ2b3J1ckRJbDRaWEFlM2pvWUtJVGREYmV6czFLM1VwMUVDc05MQTh2c0NJMEZnMHlNZGt1ajBNWjdER0M1ZWdueU1FOUtZMnpvdjhCWDhTeUI3Q0VXMy8zRVciLCJtYWMiOiJjZTYyNDU2NDhjMjk3MmM4OTExZDZhODFiMmI3ZWRlNjE0OTQ2NTg0YjkxNjgxMTAyYTcwNWEwZjFkODA3ZTNmIiwidGFnIjoiIn0%3D; expires=Wed, 24-Nov-2021 13:19:12 GMT; Max-Age=7200; path=/; secure; httponly; samesite=lax
< x-frame-options: SAMEORIGIN
< referrer-policy: no-referrer-when-downgrade
<
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='https://blutopia.xyz/login'" />

        <title>Redirecting to https://blutopia.xyz/login</title>
    </head>
    <body>
        Redirecting to <a href="https://blutopia.xyz/login">https://blutopia.xyz/login</a>.
    </body>
joetea@The_Executor:/$

**Comment by ilike2burnthing** [comment]
Ok well we've ruled out the certificate issue (didn't really make sense as you're using Docker, but worth ruling out).

Please check if changing the DNS of the container to Google or Cloudflare resolves the issue, similar to - https://github.com/Jackett/Jackett/issues/12591#issuecomment-976673651

If you use Docker run commands instead, use `--dns 1.1.1.1` (for example) instead - https://docs.docker.com/config/containers/container-networking/

If you're using Portainer, edit the container, and add the DNS servers under the Network tab.

**Comment by joetea** [comment]
Thanks! I used docker run and now it's all working. Was probably ISP problem. Thanks heaps.
