### ISSUE TITLE
Searching error for YTS

### ISSUE THREAD

**Issue by Starstrike** [Jackett/Jackett#12598]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-22 20:56:27.9012 Info Starting Jackett v0.20.53 
2021-11-22 20:56:29.8074 Info Environment version: 6.0.0 (C:\ProgramData\Jackett\) 
2021-11-22 20:56:29.8074 Info OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS) 
2021-11-22 20:56:29.8074 Info Jackett variant: CoreWindows 
2021-11-22 20:56:29.8074 Info Running in Docker: No 
2021-11-22 20:56:29.8074 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2021-11-22 20:56:29.8074 Info App config/log directory: C:\ProgramData\Jackett 
2021-11-22 20:56:29.8074 Info Using proxy: Disabled 
2021-11-22 20:56:29.8074 Info Using FlareSolverr: No 
2021-11-22 20:56:29.8188 Info Using HTTP Client: HttpWebClient2
```

### Description

The logged error shows up when searching for anything from YTS.

### Logged Error Messages

2021-11-23 07:08:21.1113 Error Jackett.Common.IndexerException: Exception (yts): Error Parsing Rows Selector
 ---> System.Exception: Error Parsing Rows Selector
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1402
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 758
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 432 Jackett.Common.IndexerException: Exception (yts): Error Parsing Rows Selector
 ---> System.Exception: Error Parsing Rows Selector
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1402
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 758
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 432

**Comment by ilike2burnthing** [comment]
Please provide and enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
The indexer is working for me so the issue appears to be at your end.

Note that only the domains provided by the Jackett YTS config are supported, so use your Jackett dashboard and edit the YTS config and select any of the alternate domains listed there to load the sitelink.

Any alternate web sites that has the YTS logo that you may have found is very likely a clone run by other providers, and under the skin may be different enough that the Jackett YTS indexer cannot process the unexpected API responses.

**Comment by Starstrike** [comment]
Thanks for the reply y'all. I have followed the instructions for enabling enhanced logging. Didnt look like much changed. I also restarted Jackett and Radarr and make sure the log was cleared so I could get a clean one. I also disabled all other indexers. I am also using the YTS that is provided by Jackett, not any others.

2021-11-24 15:07:04.8234 Info Starting Jackett v0.20.63 
2021-11-24 15:07:05.2442 Info Environment version: 6.0.0 (C:\ProgramData\Jackett\) 
2021-11-24 15:07:05.2442 Info OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS) 
2021-11-24 15:07:05.2477 Info Jackett variant: CoreWindows 
2021-11-24 15:07:05.2477 Info Running in Docker: No 
2021-11-24 15:07:05.2477 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2021-11-24 15:07:05.2477 Info App config/log directory: C:\ProgramData\Jackett 
2021-11-24 15:07:05.2477 Info Using proxy: Disabled 
2021-11-24 15:07:05.2477 Info Using FlareSolverr: No 
2021-11-24 15:07:05.2477 Info Using HTTP Client: HttpWebClient2 
2021-11-24 15:08:13.3469 Error Jackett.Common.IndexerException: Exception (yts): Error Parsing Rows Selector
 ---> System.Exception: Error Parsing Rows Selector
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1402
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 755
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 397 Jackett.Common.IndexerException: Exception (yts): Error Parsing Rows Selector
 ---> System.Exception: Error Parsing Rows Selector
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1402
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 755
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 397

Let me know if there's anything else I can grab.

**Comment by Starstrike** [comment]
Actually, I see now that enhanced logging is turned off when restarting. Let me check once more for that log.

**Comment by Starstrike** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/7598516/log.txt)

Sorry about that. Didn't see the part that it would be disabled. Lot more in the log now.

**Comment by garfield69** [comment]
its a bug in the YTS API service.
you made the query
```
https://yts.mx/api/v2/list_movies.json?query_term=Ambulance+2022&limit=50&sort=date_added
```
and YTS returned
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":1,"limit":50,"page_number":1},"@meta":{"server_time":1637785366,"server_timezone":"CET","api_version":2,"execution_time":"0 ms"}}
```
we were expecting a torrent to be included, since the movie count is 1, but none is provided !
if there was no movie found we would have expected
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":0,"limit":50,"page_number":1},"@meta":{"server_time":1637785366,"server_timezone":"CET","api_version":2,"execution_time":"0 ms"}}
```
So YTS is returning an invalid response.

When #12442 is implemented we can add a row filter to trap this false result.
until then there is nothing more we can do.

**Comment by Starstrike** [comment]
Thanks for looking into it! Testing a bit more, looks like this only happens if no results are found. Instead of just not finding any results, an error is reported to radarr that something is wrong with the indexer.

As long as YTS has results, it works fine. Not a major issue. Will wait for that JSON improvement to be implemented.

**Comment by ilike2burnthing** [comment]
Still waiting on https://github.com/Jackett/Jackett/issues/12442

**Comment by ilike2burnthing** [comment]
@garfield69 I tried and failed at adding a row filter for this. You able to give it a shot when you're free?

**Comment by garfield69** [comment]
v0.20.639
