### ISSUE TITLE
[btdigg] Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.: Parse error (Test)

### ISSUE THREAD

**Issue by heroku-miraheze** [Jackett/Jackett#12601]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-24 10:51:11 	Debug 	

Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)

2021-11-24 10:51:11 	Debug 	

Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)

2021-11-24 10:51:11 	Debug 	

Authorization was successful.

2021-11-24 10:51:11 	Debug 	

Execution plan of result filters (in the following order): None

2021-11-24 10:51:11 	Debug 	

Execution plan of exception filters (in the following order): None

2021-11-24 10:51:11 	Debug 	

Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter

2021-11-24 10:51:11 	Debug 	

Execution plan of resource filters (in the following order): None

2021-11-24 10:51:11 	Debug 	

Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter

2021-11-24 10:51:11 	Info 	

Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole).

2021-11-24 10:51:11 	Info 	

Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'

2021-11-24 10:51:11 	Debug 	

Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'

2021-11-24 10:51:11 	Debug 	

Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'

2021-11-24 10:51:11 	Debug 	

1 candidate(s) found for the request path '/api/v2.0/server/logs'

2021-11-24 10:51:11 	Debug 	

AuthenticationScheme: Cookies was successfully authenticated.

2021-11-24 10:51:11 	Debug 	

The request path /api/v2.0/server/logs does not match a supported file type

2021-11-24 10:51:11 	Debug 	

Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/server/logs?_=1637747430505

2021-11-24 10:51:11 	Debug 	

Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/server/logs?_=1637747430505

2021-11-24 10:51:11 	Debug 	

Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/server/logs?_=1637747430505

2021-11-24 10:51:11 	Info 	

Request starting HTTP/1.1 GET http://localhost:9117/api/v2.0/server/logs?_=1637747430505 - -

2021-11-24 10:51:09 	Info 	

Request finished HTTP/1.1 POST http://localhost:9117/api/v2.0/indexers/btdigg/test - 0 - 500 - application/json 279.5568ms

2021-11-24 10:51:09 	Debug 	

Connection id "0HMDEG6H52L6K" completed keep alive response.

2021-11-24 10:51:09 	Debug 	

The response will be compressed with 'gzip'.

2021-11-24 10:51:09 	Error 	

Jackett.Common.IndexerException: Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 839
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1470
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 781
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1621
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 758
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

2021-11-24 10:51:09 	Info 	

Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'

2021-11-24 10:51:09 	Info 	

Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 243.9157ms

2021-11-24 10:51:09 	Error 	

Error on 20211124105109 for BTDigg.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 839
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1470




2021-11-24 10:51:09 	Debug 	

WebClient(HttpWebClient2): Returning Moved => https://www.domflow.it/cart.php?a=confproduct&i=486450430 0 bytes

2021-11-24 10:51:09 	Debug 	

WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://btdig.com/search?q=2021&order=0)

2021-11-24 10:51:09 	Debug 	

CACHE Status / Total cached results: 4361

2021-11-24 10:51:09 	Debug 	

CACHE PruneCacheByTtl / Pruned queries: 0

2021-11-24 10:51:09 	Debug 	

Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole)

2021-11-24 10:51:09 	Debug 	

Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole)

2021-11-24 10:51:09 	Debug 	

Authorization was successful.

2021-11-24 10:51:09 	Debug 	

Execution plan of result filters (in the following order): None

2021-11-24 10:51:09 	Debug 	

Execution plan of exception filters (in the following order): None

2021-11-24 10:51:09 	Debug 	

Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer

2021-11-24 10:51:09 	Debug 	

Execution plan of resource filters (in the following order): None

2021-11-24 10:51:09 	Debug 	

Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter

2021-11-24 10:51:09 	Info 	

Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (JackettConsole).

2021-11-24 10:51:09 	Info 	

Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'

2021-11-24 10:51:09 	Debug 	

Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'

2021-11-24 10:51:09 	Debug 	

Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/btdigg/test'

2021-11-24 10:51:09 	Debug 	

1 candidate(s) found for the request path '/api/v2.0/indexers/btdigg/test'

2021-11-24 10:51:09 	Debug 	

AuthenticationScheme: Cookies was successfully authenticated.

2021-11-24 10:51:09 	Debug 	

POST requests are not supported

2021-11-24 10:51:09 	Debug 	

Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/btdigg/test

2021-11-24 10:51:09 	Debug 	

Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/btdigg/test

2021-11-24 10:51:09 	Debug 	

Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/btdigg/test

2021-11-24 10:51:09 	Info 	

Request starting HTTP/1.1 POST http://localhost:9117/api/v2.0/indexers/btdigg/test - 0

2021-11-24 10:51:02 	Info 	

Request finished HTTP/1.1 GET http://localhost:9117/api/v2.0/server/logs?_=1637747430504 - - - 200 - application/json;+charset=utf-8 34.7774ms

2021-11-24 10:51:02 	Debug 	

Connection id "0HMDEG6H52L6K" completed keep alive response.

2021-11-24 10:51:02 	Info 	

Executed endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'

2021-11-24 10:51:02 	Info 	

Executed action Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole) in 17.677ms

2021-11-24 10:51:02 	Debug 	

The response will be compressed with 'gzip'.

2021-11-24 10:51:02 	Info 	

Executing ObjectResult, writing value of type 'System.Collections.Generic.List`1[[Jackett.Common.Models.CachedLog, Jackett.Common, Version=0.20.53.0, Culture=neutral, PublicKeyToken=null]]'.

2021-11-24 10:51:02 	Debug 	

Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response.

2021-11-24 10:51:02 	Debug 	

Attempting to select the first formatter in the output formatters list which can write the result.

2021-11-24 10:51:02 	Debug 	

Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.

2021-11-24 10:51:02 	Debug 	

No information found on request to perform content negotiation.

2021-11-24 10:51:02 	Debug 	

List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter

2021-11-24 10:51:02 	Debug 	

Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)

2021-11-24 10:51:02 	Debug 	

Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)

2021-11-24 10:51:02 	Debug 	

Authorization was successful.
```

### Description

The problem persists, now get redirected to https://www.domflow.it/ without reason, when i can go to btdig.com in my web browser, it works perfectly.

### Logged Error Messages

<html><body>

2021-11-24 10:51:11 | Debug | Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)
-- | -- | --
2021-11-24 10:51:11 | Debug | Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)
2021-11-24 10:51:11 | Debug | Authorization was successful.
2021-11-24 10:51:11 | Debug | Execution plan of result filters (in the following order): None
2021-11-24 10:51:11 | Debug | Execution plan of exception filters (in the following order): None
2021-11-24 10:51:11 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2021-11-24 10:51:11 | Debug | Execution plan of resource filters (in the following order): None
2021-11-24 10:51:11 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2021-11-24 10:51:11 | Info | Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole).
2021-11-24 10:51:11 | Info | Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'
2021-11-24 10:51:11 | Debug | Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'
2021-11-24 10:51:11 | Debug | Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'
2021-11-24 10:51:11 | Debug | 1 candidate(s) found for the request path '/api/v2.0/server/logs'
2021-11-24 10:51:11 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2021-11-24 10:51:11 | Debug | The request path /api/v2.0/server/logs does not match a supported file type
2021-11-24 10:51:11 | Debug | Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/server/logs?_=1637747430505
2021-11-24 10:51:11 | Debug | Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/server/logs?_=1637747430505
2021-11-24 10:51:11 | Debug | Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/server/logs?_=1637747430505
2021-11-24 10:51:11 | Info | Request starting HTTP/1.1 GET http://localhost:9117/api/v2.0/server/logs?_=1637747430505 - -
2021-11-24 10:51:09 | Info | Request finished HTTP/1.1 POST http://localhost:9117/api/v2.0/indexers/btdigg/test - 0 - 500 - application/json 279.5568ms
2021-11-24 10:51:09 | Debug | Connection id "0HMDEG6H52L6K" completed keep alive response.
2021-11-24 10:51:09 | Debug | The response will be compressed with 'gzip'.
2021-11-24 10:51:09 | Error | Jackett.Common.IndexerException: Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.  ---> System.Exception: Parse error  ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.    at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 839    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1470    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 781    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1621    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 758    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 306    at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
2021-11-24 10:51:09 | Info | Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'
2021-11-24 10:51:09 | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 243.9157ms
2021-11-24 10:51:09 | Error | Error on 20211124105109 for BTDigg.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.    at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 839    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1470
2021-11-24 10:51:09 | Debug | WebClient(HttpWebClient2): Returning Moved => https://www.domflow.it/cart.php?a=confproduct&i=486450430 0 bytes
2021-11-24 10:51:09 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://btdig.com/search?q=2021&order=0)
2021-11-24 10:51:09 | Debug | CACHE Status / Total cached results: 4361
2021-11-24 10:51:09 | Debug | CACHE PruneCacheByTtl / Pruned queries: 0
2021-11-24 10:51:09 | Debug | Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole)
2021-11-24 10:51:09 | Debug | Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole)
2021-11-24 10:51:09 | Debug | Authorization was successful.
2021-11-24 10:51:09 | Debug | Execution plan of result filters (in the following order): None
2021-11-24 10:51:09 | Debug | Execution plan of exception filters (in the following order): None
2021-11-24 10:51:09 | Debug | Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2021-11-24 10:51:09 | Debug | Execution plan of resource filters (in the following order): None
2021-11-24 10:51:09 | Debug | Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2021-11-24 10:51:09 | Info | Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (JackettConsole).
2021-11-24 10:51:09 | Info | Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'
2021-11-24 10:51:09 | Debug | Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'
2021-11-24 10:51:09 | Debug | Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/btdigg/test'
2021-11-24 10:51:09 | Debug | 1 candidate(s) found for the request path '/api/v2.0/indexers/btdigg/test'
2021-11-24 10:51:09 | Debug | AuthenticationScheme: Cookies was successfully authenticated.
2021-11-24 10:51:09 | Debug | POST requests are not supported
2021-11-24 10:51:09 | Debug | Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/btdigg/test
2021-11-24 10:51:09 | Debug | Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/btdigg/test
2021-11-24 10:51:09 | Debug | Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/btdigg/test
2021-11-24 10:51:09 | Info | Request starting HTTP/1.1 POST http://localhost:9117/api/v2.0/indexers/btdigg/test - 0
2021-11-24 10:51:02 | Info | Request finished HTTP/1.1 GET http://localhost:9117/api/v2.0/server/logs?_=1637747430504 - - - 200 - application/json;+charset=utf-8 34.7774ms
2021-11-24 10:51:02 | Debug | Connection id "0HMDEG6H52L6K" completed keep alive response.
2021-11-24 10:51:02 | Info | Executed endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole)'
2021-11-24 10:51:02 | Info | Executed action Jackett.Server.Controllers.ServerConfigurationController.Logs (JackettConsole) in 17.677ms
2021-11-24 10:51:02 | Debug | The response will be compressed with 'gzip'.
2021-11-24 10:51:02 | Info | Executing ObjectResult, writing value of type 'System.Collections.Generic.List`1[[Jackett.Common.Models.CachedLog, Jackett.Common, Version=0.20.53.0, Culture=neutral, PublicKeyToken=null]]'.
2021-11-24 10:51:02 | Debug | Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response.
2021-11-24 10:51:02 | Debug | Attempting to select the first formatter in the output formatters list which can write the result.
2021-11-24 10:51:02 | Debug | Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
2021-11-24 10:51:02 | Debug | No information found on request to perform content negotiation.
2021-11-24 10:51:02 | Debug | List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter
2021-11-24 10:51:02 | Debug | Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)
2021-11-24 10:51:02 | Debug | Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (JackettConsole)
2021-11-24 10:51:02 | Debug | Authorization was successful.

</body>
</html>

**Comment by ilike2burnthing** [comment]
Working ok here. Possibly a temporary issue with the site. Please check again.

If the issue continues, please confirm that other indexers are working fine and correct the environment section of your post.

**Comment by heroku-miraheze** [comment]
Now it's working, thanks.
