### ISSUE TITLE
[speedcd] Exception (speedcd): Exception of type 'System.Exception' was thrown.: Exception of type 'System.Exception' was thrown. (Test)

### ISSUE THREAD

**Issue by skcuslleb** [Jackett/Jackett#12620]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Info Starting Jackett v0.20.78 
Info Environment version: 6.0.0 (/app/Jackett/) 
Info OS version: Unix 4.4.180.0 (64bit OS) (64bit process) 
Info Jackett variant: CoreLinuxAmdx64 
Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
Info Running in Docker: Yes (image build: v0.20.78-ls51) 
Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
Info App config/log directory: /config/Jackett 
Info Using proxy: Disabled 
Info Using FlareSolverr: http://xxx.xxx.xxx.xxx:8191 
Info Using HTTP Client: HttpWebClient2
```

### Description

Click "Test" on the speed.cd indexer

### Logged Error Messages

11-30 15:22:08 Error Jackett.Common.IndexerException: Exception (speedcd): Exception of type 'System.Exception' was thrown.
 ---> System.Exception: Exception of type 'System.Exception' was thrown.
   at Jackett.Common.Indexers.SpeedCD.<>c__DisplayClass14_0.<DoLogin>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 143
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 136
   at Jackett.Common.Indexers.SpeedCD.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 174
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 397 Jackett.Common.IndexerException: Exception (speedcd): Exception of type 'System.Exception' was thrown.
 ---> System.Exception: Exception of type 'System.Exception' was thrown.
   at Jackett.Common.Indexers.SpeedCD.<>c__DisplayClass14_0.<DoLogin>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 143
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 136
   at Jackett.Common.Indexers.SpeedCD.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 174
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 397

**Comment by skcuslleb** [comment]
You're right, the problem is on my end. For anyone having the same problem in the future: Geolocking was turned on in the speed.cd security settings, and I recently moved Jackett behind a VPN so my location changed. Turning Geolocking off fixed the issue.
