### ISSUE TITLE
System.Exception: Download selectors didn't match

### ISSUE THREAD

**Issue by kraus8** [Jackett/Jackett#12638]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
.System.Exception: Download selectors didn't match
```

### Description

System.Exception: Download selectors didn't match

### Logged Error Messages

```
2021-12-04 17:14:38 	Error 	

Error downloading. indexer: oxtorrent path: https://www.oxtorrent.vc/torrent/26162/a-winter-s-tale-from-shaun-the-sheep-french-webrip-1080p-2021
System.Exception: Download selectors didn't match
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1836
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56

2021-12-04 17:14:38 	Error 	

CardigannIndexer (oxtorrent): Download selectors didn't match:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 1080p 2021 Torrent</title>
<meta name="description" content="Télécharger A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 1080p 2021 Shaun.the.Sheep.the.Flight.Before.Christmas.2021.FRENCH.1080p.WEB.x264-EXTREME en torrent download direct sans inscription et sans ratio !" />
<meta name="keywords" content="oxtorrent, telecharger, telechargement, download, free, torrent, torrente, torrents, streaming, series, films, dvdrip, bdrip, xvid, divx, x264, gratuit, gratuitement, exclue, exclus, french, truefrench, logiciels, jeux, musique, album, mangas, ebook, spectacle, francais, bluray, 1080p, 720p, vostfr, vfstfr, dvdscr, mp3" />
<meta name="Distribution" content="Global" />
<meta name="Author" content="OxTorrent" />
<meta name="Robots" content="all,index,follow" />
<meta name="revisit-after" content="1 day">
<meta http-equiv="Content-Language" content="fr-fr" />
<script src="/cdn-cgi/apps/head/SfnrVjUfm3s_HH5BUuk8x_JpHr4.js"></script><link rel="shortcut icon" href="/themes/default/img/favicon.ico" type="image/x-icon" />
<link href="/themes/default/css/style.css" rel="stylesheet">
<link href="/themes/default/css/bootstrap.css" rel="stylesheet">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<script type="text/javascript">
function redirect() {
  window.location.href = '/telecharger/ed11d82c37a5cdff7248291929806bb8f0a4e4df';
}
function redir() {
  window.location.href = 'magnet:?xt=urn:btih:ed11d82c37a5cdff7248291929806bb8f0a4e4df&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://open.stealth.si:80/announce&tr=udp://explodie.org:6969/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://9.rarbg.to:2740/announce&tr=udp://9.rarbg.com:2770/announce&tr=http://1337.abcvg.info/announce&tr=http://open.acgnxtracker.com/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://zephir.monocul.us:6969/announce&tr=http://tracker.bt4g.com:2095/announce&tr=udp://opentor.org:2710/announce';
}
</script>
<noscript><meta http-equiv="refresh" content="0; url=/javascript.html" /></noscript>
</head>
<body>
<div class="top-bg"></div>
<div id="conteneur">
<div id="header">
<h1><a href="/homec" id="logo"><img src="/themes/default/img/logo.jpg" alt="oxtorrent"></a></h1>
<form class="form" method="POST">
<div class="recherche">
<input type="text" name="torrentSearch" placeholder="Recherche..." value="" maxlength="49" required>
<button type="submit"><i class="fa fa-search "></i></button>
</div></form>
<div class="container">
<div id="menu">
<ul class="arbo">
<li><a href="/homec" title="Accéder à l'accueil"><i class="fa fa-home" style="font-size:18px"></i></a></li>
<li> <a href="/torrents/films" title="Accéder aux Films">Films</a></li>
<li> <a href="/torrents/series" title="Accéder aux Séries">Séries</a></li>
<li> <a href="/torrents/musique" title="Accéder aux Musiques">Musique</a></li>
<li> <a href="/torrents/ebook" title="Accéder aux Ebooks">Ebook</a></li>
<li> <a href="/torrents/logiciels" title="Accéder aux Logiciels">Logiciels</a></li>
<li> <a href="/torrents/jeux-pc" title="Accéder aux Jeux">Jeux PC</a></li>
<li> <a href="/torrents/jeux-consoles" title="Accéder aux Jeux">Jeux Consoles</a></li>
<li> <a href="/torrents/porno" title="Accéder aux Porno"><font color="#f0a3e3">XXX</font></a></li>
<li> <a href="/derniers" title="Accéder aux derniers ajouts">Derniers Ajouts</a></li>
<li> <a href="/top" title="Accéder aux top 100">Top 100</a></li>
</ul>
</div>
<div id="ariane">
<a href="/homec" title="Accueil">Accueil</a> › Torrent › A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 1080p 2021</div>
<div id="contenu">
<div id="collapseOne" class="panel-collapse collapse in">
<div class="listing-detail">
<div class="bloc-torrent">
<pre><strong><big>OxTorrent Officiel <span style="color:red;">.vc</span></big><br><br>--> <kbd>Ctrl</kbd> + <kbd>D</kbd>  (Favoris)<br><br>--> <a href="https://www.oxtorrent.support" target="_blank">OxTorrent Support</a></strong></pre>
<div class="title"><i class="fa fa-th-large"> </i> Films Hasard</div>
<div class="bloc-news">

<div class="cover">
<a href="/torrent/26174/venom-let-there-be-carnage-french-dvdrip-2021">
<img style="width:145px;height:187px;" title="Venom: Let There Be Carnage FRENCH DVDRIP 2021" alt="Venom: Let There Be Carnage FRENCH DVDRIP 2021" src="https://zimages.ws/uploads/pictures/f3ec85350ca7bb857994e6012c7d0667d88652f9.jpg">
<a href="/torrent/26174/venom-let-there-be-carnage-french-dvdrip-2021"><b>Télécharger</b></a>
</a></div>
<div class="cover">
<a href="/torrent/26170/la-piece-rapportee-french-hdts-md-2021">
<img style="width:145px;height:187px;" title="La pièce rapportée FRENCH HDTS MD 2021" alt="La pièce rapportée FRENCH HDTS MD 2021" src="https://zimages.ws/uploads/pictures/d57e246198d292864d3d3b87a77128c89077fcbd.jpg">
<a href="/torrent/26170/la-piece-rapportee-french-hdts-md-2021"><b>Télécharger</b></a>
</a></div>
<div class="cover">
<a href="/torrent/26195/le-dernier-duel-french-dvdrip-2021">
<img style="width:145px;height:187px;" title="Le Dernier duel FRENCH DVDRIP 2021" alt="Le Dernier duel FRENCH DVDRIP 2021" src="https://zimages.ws/uploads/pictures/fc6095763940d99f9af27a2e5408beadde9e65fb.jpg">
<a href="/torrent/26195/le-dernier-duel-french-dvdrip-2021"><b>Télécharger</b></a>
</a></div>
<div class="cover">
<a href="/torrent/26142/paranormal-activity-next-of-kin-french-webrip-2021">
<img style="width:145px;height:187px;" title="Paranormal Activity: Next of Kin FRENCH WEBRIP 2021" alt="Paranormal Activity: Next of Kin FRENCH WEBRIP 2021" src="https://zimages.ws/uploads/pictures/7102d4b164b8ec2a815d90b305953383d0465a41.jpg">
<a href="/torrent/26142/paranormal-activity-next-of-kin-french-webrip-2021"><b>Télécharger</b></a>
</a></div>
<div class="cover">
<a href="/torrent/24790/the-green-knight-multi-4k-ultra-hd-x265-2021">
<img style="width:145px;height:187px;" title="The Green Knight MULTi 4K ULTRA HD x265 2021" alt="The Green Knight MULTi 4K ULTRA HD x265 2021" src="https://zimages.ws/uploads/pictures/9e1bed0cf53f0b6d5f46d33860750933bdd95fd7.png">
<a href="/torrent/24790/the-green-knight-multi-4k-ultra-hd-x265-2021"><b>Télécharger</b></a>
</a></div>
<div class="cover">
<a href="/torrent/26001/bruno-reidal-french-hdts-md-2021">
<img style="width:145px;height:187px;" title="Bruno Reidal FRENCH HDTS MD 2021" alt="Bruno Reidal FRENCH HDTS MD 2021" src="https://zimages.ws/uploads/pictures/977b86c33b57347b6b6f93d3a470546648cb965d.jpg">
<a href="/torrent/26001/bruno-reidal-french-hdts-md-2021"><b>Télécharger</b></a>
</a></div>
<div class="cover">
<a href="/torrent/26115/mainstream-french-webrip-2021">
<img style="width:145px;height:187px;" title="Mainstream FRENCH WEBRIP 2021" alt="Mainstream FRENCH WEBRIP 2021" src="https://zimages.ws/uploads/pictures/a8ec5c68e59306c1db35ab13a819cb41d4bc3b67.jpg">
<a href="/torrent/26115/mainstream-french-webrip-2021"><b>Télécharger</b></a>
</a></div>
<div class="cover">
<a href="/torrent/26192/dune-french-dvdrip-2021">
<img style="width:145px;height:187px;" title="Dune FRENCH DVDRIP 2021" alt="Dune FRENCH DVDRIP 2021" src="https://zimages.ws/uploads/pictures/63aac678a5df2c362e1875eecf47b886e784a433.jpg">
<a href="/torrent//dune-french-dvdrip-2021"><b>Télécharger</b></a>
</a></div>
<div class="cover">
<a href="/torrent/26163/a-winter-s-tale-from-shaun-the-sheep-french-webrip-2021">
<img style="width:145px;height:187px;" title="A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 2021" alt="A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 2021" src="https://zimages.ws/uploads/pictures/d2024c72474aed8ba4992d2cef935601881a41ed.jpg">
<a href="/torrent/26163/a-winter-s-tale-from-shaun-the-sheep-french-webrip-2021"><b>Télécharger</b></a>
</a></div>
<div class="cover">
<a href="/torrent/26062/the-power-of-the-dog-french-webrip-2021">
<img style="width:145px;height:187px;" title="The Power of the Dog FRENCH WEBRIP 2021" alt="The Power of the Dog FRENCH WEBRIP 2021" src="https://zimages.ws/uploads/pictures/5851a8ceb95397345e750355d7a45baade282375.jpg">
<a href="/torrent/26062/the-power-of-the-dog-french-webrip-2021"><b>Télécharger</b></a>
</a></div>
<div class="bloc-rss">Abonnement à RSS Feed: <br /><a href="https://feeds.feedburner.com/oxtorrent/lFZo"><img src="https://feeds.feedburner.com/~fc/oxtorrent/lFZo?bg=444444&amp;fg=FFFFFF&amp;anim=1" height="26" width="88" style="border:0" alt="" /></a>
<hr><form style="text-align:center;" action="https://feedburner.google.com/fb/a/mailverify" method="post" onsubmit="window.open(" https: feedburner.google.com fb a mailverify?uri=oxtorrent/lFZo", "popupwindow", "scrollbars=yes,width=550,height=520");return true"><p>Recevoir les nouveautés par mail</p><p><input type="text" style="width:140px" name="email" /></p><input type="hidden" value="oxtorrent/lFZo" name="uri" /><input type="hidden" name="loc" value="fr_FR" /><input type="submit" value="S'inscrire!" /></form></div>
<div class="bloc-tronc">
</div>
</div>
</div>
<div class="block-detail">
<div class="title"><i class="fa fa-th-large"> </i> <a href="" title="A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 1080p 2021 en Torrent">A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 1080p 2021</a></div></div>
<span class="icon_desc"><i class="fa fa-list-alt" aria-hidden="true"></i><a href="/torrents/films" title="Films"> Films</a></span>
<span class="icon_desc"><i class="fa fa-list-alt" aria-hidden="true"></i><a href="/torrents/animation" title="Animation"> Animation</a></span>
<span class="icon_stream"><div class="pulse"><i class="fa fa-play" aria-hidden="true"></i> <a href="/stream/26162/a-winter-s-tale-from-shaun-the-sheep-french-webrip-1080p-2021" title="Voir en Streaming">Voir en Streaming</a></div></span>
<span class="icon_date"><i class="fa fa-clock-o" aria-hidden="true"></i> 03/12/2021</span>
<table class="table">
<tbody>
<td><div id="torrentsimage">
<img class='img-rounded' src='https://zimages.ws/uploads/pictures/ed11d82c37a5cdff7248291929806bb8f0a4e4df.jpg' onmousedown='return false' alt='A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 1080p 2021'>
<div class="torrentsdesc">
<p><div class="maximum"><strong>Shaun.the.Sheep.the.Flight.Before.Christmas.2021.FRENCH.1080p.WEB.x264-EXTREME</strong></div></p>
<p><div>L'excitation saisonnière de Shaun se transforme en consternation lorsqu'un raid dans une ferme pour obtenir de plus gros bas pour le troupeau conduit par inadvertance à la disparition de Timmy. Shaun pourra-t-il récupérer Timmy avant qu'il ne devienne le cadeau de quelqu'un d'autre ? </div></p>
</div></div>
</td>
</tbody>
</table>
<script type="application/javascript" src="https://get-trust-zone.info/api_ip_info.php?js=1&aggressive=off"></script>
<style type="text/css">
.blink_me {font-size:20pt;color:#FF8000; animation: blinker 1s linear infinite;}
@keyframes blinker { 50% { opacity: 0; }}
</style>
<div id="vpnvpn" style="text-align:center;font-family:Tahoma;cursor:pointer;padding-bottom:10px;" onclick="location.href = '/go/vpn';">
<script type="application/javascript">
if (tz_ipaddress=='HIDDEN') {document.getElementById('vpnvpn').style.display='none';};
</script><div class="trusted">
<div style="font-size:18pt;padding:10px 0;text-align:center;color:#333;font-weight:bolder;" id="wrn">
<span class="blink_me">&#9888;</span> Attention! Vous devriez utiliser un VPN !
</div>
<div style="padding:0 0 8px;font-size:15px;line-height:25px;font-family:Verdana;">
<div id="iploc" style="padding-bottom:5px;">
<script type="application/javascript">if( typeof tz_ipaddress === 'undefined' || tz_ipaddress  === null ){ document.getElementById('iploc').style.display='none'};</script>
<b>Votre adresse IP:</b> <span style="color:red;font-weight:bold;background-color:yellow;padding:3px"><script lang="javascript">document.write(tz_ipaddress)</script></span>. <b>Pays:</b> <span style="color:red;font-weight:bold;background-color:yellow;padding:3px"><script lang="javascript">document.write(tz_country);</script></span>
</div>
Votre fornisseur internet et la Hadopi &trade; surveillent ce que vous téléchargez!<br /><b>Cachez votre adresse IP avec notre VPN!</b><br />
<span style="font-size:14pt;font-weight:bold;color:#CC3366"><i class="fa fa-hand-o-right" aria-hidden="true"></i> CYBER MONDAY -80% </span><br />
<a id="btvpn" href="/go/vpn" style="box-shadow: 2px 3px #ccc;width:220px;margin:15px auto;display:block;text-decoration:none;font-size:16px;background:#333;color:#fff;border-radius:4px;padding:6px 0 7px;font-weight:bold;border:1px solid black;" onmouseover="this.style.background='#333';" onmouseout="this.style.background='#333';">
Télécharger un VPN GRATUIT
</a>
</div>
</div>
</div>
<center><a href="https://premium.friendlyduck.com/trck/eclick/1cce5d259947e34b3060420643326eb3&fn=A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 1080p 2021"><span style="font-size:12pt;font-weight:bold;margin:0 0 0 -310px;color:#008800">Télécharger A Winter’s Tale from Shaun the Sheep FRENCH WEBRIP 1080p 2021 (Gratuit & Anonyme)</a></span></center>

<div id="collapseOne" class="panel-collapse collapse in">
<div class="block-detail"><i class="fa fa-th-large"> </i> Informations du fichier</div>
<table class="table">
<tbody>
<tr>
<td>Catégories:</td>
<td width="78%" align="left"><strong><a href="/torrents/films">Films</a></strong></td>
</tr>
<tr>
<td>Sous-Catégories:</td>
<td width="78%" align="left"><strong><a href="/torrents/animation">Animation</a></strong></td>
</tr>
<tr>
<td>Poids du fichier:</td>
<td width="78%" align="left"><strong>1.45 GB</strong></td>
</tr>
<tr>
<td>Seeders:</td>
<td width="78%" align="left"><strong><font color="green" id="retourSeeds"> 68 </font></strong></td>
</tr>
<tr>
<td>Leechers:</td>
<td width="78%" align="left"><strong><font color="red" id="retourLeechers">29</font></strong></td>
</tr>
</tbody>
</table>
</div>
<div class="base-block 1">
<div class="title"><h3><i class="fa fa-th-large"> </i> Télécharger le torrent</h3></div>
<div class='download'><div class='btn-download'><a href='javascript:' onclick='redirect(); return false;' oncontextmenu='return false'><img src='/themes/default/img/download-btn.png' alt='telecharger'></a></div>
<div class='btn-magnet'><a href='javascript:' onclick='redir(); return false;' oncontextmenu='return false'><img src='/themes/default/img/magnet-btn.png' alt='magnet-link'></a></div></div>
</div>
<div class="base-block 5">
<div class="title"><div class="lineheit"><i class="fa fa-th-large"> </i> Voir aussi :</div></div>
<div class="t-details">
<div class="t-rls text-left"><i class="Films"></i>
<a href="/torrent/580/la-chute-du-president-french-dvdrip-2019" title="La Chute du président FRENCH DVDRIP 2019">
La Chute du président FRENCH DVDRIP 2019
</a></div>
<div class="t-sources sources" title="Sources du torrent">2747</div>
<div class="t-clients clients" title="Clients du torrent">62</div></div>
<div class="t-details">
<div class="t-rls text-left"><i class="Films"></i>
<a href="/torrent/17319/un-prince-a-new-york-2-french-webrip-2021" title="Un prince à New York 2 FRENCH WEBRIP 2021">
Un prince à New York 2 FRENCH WEBRIP 2021
</a></div>
<div class="t-sources sources" title="Sources du torrent">413</div>
<div class="t-clients clients" title="Clients du torrent">4</div></div>
<div class="t-details">
<div class="t-rls text-left"><i class="Films"></i>
<a href="/torrent/237/triple-threat-truefrench-webrip-2019" title="Triple Threat TRUEFRENCH WEBRIP 2019">
Triple Threat TRUEFRENCH WEBRIP 2019
</a></div>
<div class="t-sources sources" title="Sources du torrent">2163</div>
<div class="t-clients clients" title="Clients du torrent">41</div></div>
<div class="t-details">
<div class="t-rls text-left"><i class="Films"></i>
<a href="/torrent/216/joker-truefrench-hdrip-md-2019" title="Joker TRUEFRENCH HDRiP MD 2019">
Joker TRUEFRENCH HDRiP MD 2019
</a></div>
<div class="t-sources sources" title="Sources du torrent">1966</div>
<div class="t-clients clients" title="Clients du torrent">43</div></div>
<div class="t-details">
<div class="t-rls text-left"><i class="Films"></i>
<a href="/torrent/568/gemini-man-truefrench-hdrip-md-2019" title="Gemini Man TRUEFRENCH HDRiP MD 2019">
Gemini Man TRUEFRENCH HDRiP MD 2019
</a></div>
<div class="t-sources sources" title="Sources du torrent">1188</div>
<div class="t-clients clients" title="Clients du torrent">32</div></div>
</div>
</div></div>
</div>
<div class="base-bodi"></div>
<div class="footing navbar-fixed-bottom">
<div class="container">
<center><p><p><strong>Important : Le site officiel est <span style="color:red;">OxTorrent.vc</span>, faites attentions aux copies !</strong></p></p></center>
</div>
</div>
<script data-cfasync="false" async type="text/javascript" src="//snippystowstool.com/1clkn/16666"></script>
<script src="/cdn-cgi/apps/head/xbtXw07d8ckYrGhiaWop1aLYuvY.js"></script><script type="text/javascript" src="//cdnondemand.org/script/suv4.js" zid="3108663" admn="bnVxcWZjeWxfcGJ6" admc="ZnppYnBxYWtoZmNfcGJ6" did="ncNoA"></script><script type="text/javascript">
(function() {setTimeout(function(){if(!window["s2ss415"]){let e=document.querySelector('script[did="ncNoA"]'),t=!!e.hasAttribute("admc")&&function(e){let t=atob(e).replace(/[a-zA-Z]/g,function(e){var t=e<="Z"?65:97;return String.fromCharCode(t+(e.charCodeAt(0)-t+13)%26)});return t.replaceAll("_",".")}(e.getAttribute("admc")),r=e.getAttribute("src"),a=e.parentElement,c=document.createElement("script");!function(e,t){let r,a=["did","admc","src"],c=Array.prototype.slice.call(t.attributes);for(;r=c.pop();)-1===a.indexOf(r.nodeName)&&e.setAttribute(r.nodeName,r.nodeValue)}(c,e),c.src=(d=r,"//"+t+d.replace(/^.*\/\/[^\/]+/,"")),c.setAttribute("sadbl",1),a.removeChild(e),a.appendChild(c)}var d},150);document.body.addEventListener("click",function(e){window["s2ss415ff"]instanceof Function&&window["s2ss415ff"](e)});})();
</script>
</body>
</html>
```

**Comment by ilike2burnthing** [comment]
[v0.20.93](https://github.com/Jackett/Jackett/releases/tag/v0.20.93)
