### ISSUE TITLE
[yggtorrent] Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:8191)

### ISSUE THREAD

**Issue by Floflobel** [Jackett/Jackett#12647]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Info Environment version: 6.0.0 (/opt/Jackett/)
Info OS version: Unix 5.4.0.90 (64bit OS) (64bit process)
Info Jackett variant: CoreLinuxAmdx64
Info File /etc/issue: Ubuntu 20.04.3 LTS \n \l
Info Running in Docker: No
Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Info App config/log directory: /root/.config/Jackett
Info Using proxy: Disabled
Info Using FlareSolverr: http://127.0.0.1:8191
Info Using HTTP Client: HttpWebClient2 
Hosting environment: Production
Content root path: /opt/Jackett/Content
```

### Description

I have a problem with jackett since a few days. It seems that FlareSolverr is not started anymore and I don't understand why.
If I'm not mistaken, it is now installed with Jackett and there is no need to install it separately (it's been a long time since I did the installation and I don't remember).

* FlareSolverr API URL is already defined:
https://github.com/Jackett/Jackett/wiki/Troubleshooting#error-connecting-to-flaresolverr-server

Today FlareSolver worked for ~30 minutes then impossible to know why it tells me it's not running.

How can I solve this problem or debug it?

### Logged Error Messages

```
Dec  6 17:14:18 downloader jackett[1060]: 12-06 17:14:18 Error FlareSolverrSharp.Exceptions.FlareSolverrException: Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused 
(127.0.0.1:8191)
Dec  6 17:14:18 downloader jackett[1060]:  ---> System.Net.Sockets.SocketException (111): Connection refused
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancella
tionToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationTok
en)
Dec  6 17:14:18 downloader jackett[1060]:    --- End of inner exception stack trace ---
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationTok
en)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
Dec  6 17:14:18 downloader jackett[1060]: --- End of stack trace from previous location ---
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 594
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 892
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 563
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 968
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Dec  6 17:14:18 downloader jackett[1060]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 FlareSolverrSharp.Exceptions.FlareSolverrException: Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:8191)
Dec  6 17:14:18 downloader jackett[1060]:  ---> System.Net.Sockets.SocketException (111): Connection refused
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    --- End of inner exception stack trace ---
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
Dec  6 17:14:18 downloader jackett[1060]: --- End of stack trace from previous location ---
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
Dec  6 17:14:18 downloader jackett[1060]:    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 208
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 594
Dec  6 17:14:18 downloader jackett[1060]:    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 892
```

```
root@downloader:~ # ss -antpu | grep jack
tcp      LISTEN        0         512                                 *:9117                                                    *:*                               users:(("jackett",pid=1083,fd=205))                 
                           
tcp      CLOSE-WAIT    0         0              [::ffff:192.168.1.160]:56646                               [::ffff:172.64.98.33]:443                             users:(("jackett",pid=1083,fd=239))                 
                           
root@downloader:~ # ss -antpu | grep flare
root@downloader:~ #
```

**Comment by ilike2burnthing** [comment]
As stated in the troubleshooting link you posted:
> This error can occur when either:
a) You have not installed and configured FlareSolverr
or
b) you have set up Jackett to use FlareSolverr, but the FlareSolverr server is not running, or has not been configured yet, or has been incorrectly configured.
[...]
Install and configure [FlareSolverr](https://github.com/Jackett/Jackett#configuring-flaresolverr).

So if you haven't installed FlareSolverr, do so, or if you have, check it is running and accessible in browser on the same device at http://127.0.0.1:8191

**Comment by Floflobel** [comment]
I followed these topics and was able to bypass flaresolverr, so it's ok:
https://github.com/FlareSolverr/FlareSolverr/issues/234
https://www3.yggtorrent.re/forum/index.php?threads/fin-de-prowlarr-jackett.66305/page-6#post-327029
