### ISSUE TITLE
[yggtorrent] FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Execution context was destroyed, most likely because of a navigation. (Config)

### ISSUE THREAD

**Issue by DaGreenX** [Jackett/Jackett#12679]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Symbology ds218+; dsm 6
Jackett Version v0.20.123
FlareSolverr v1.2.8 (docker from Docker Hub)
```

### Description

unable to configure and save YggTorrent
docker IPv6 is disabled

### Logged Error Messages

Jacket : 

2021-12-08 10:26:54 | Error | FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Cloudflare Error: Execution context was destroyed, most likely because of a navigation.    at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext() --- End of stack trace from previous location ---    at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)    at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)    at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 590    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 892    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 563    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 968    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
-- | -- | --
2021-12-08 10:25:56 | Error | Exception in GetConfigurationForSetup (yggtorrent): FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=55000 (ms)    at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext() --- End of stack trace from previous location ---    at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)    at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)    at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 590    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 892    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 871

FlareSolverr : 

2021-12-08 10:04:13 | stderr | 2021-12-08T10:04:13+00:00 ERROR REQ-3 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=55000 (ms)
2021-12-08 10:04:13 | stderr | at processTimers (node:internal/timers:499:7)
2021-12-08 10:04:13 | stderr | at listOnTimeout (node:internal/timers:556:17)
2021-12-08 10:04:13 | stderr | at Timeout.fn (/home/node/flaresolverr/node_modules/await-timeout/src/index.js:32:46)
2021-12-08 10:04:13 | stderr | at exports.toError (/home/node/flaresolverr/node_modules/await-timeout/src/utils.js:20:38)
2021-12-08 10:04:13 | stderr | 2021-12-08T10:04:13+00:00 ERROR REQ-3 Error: Maximum timeout reached. maxTimeout=55000 (ms)
2021-12-08 10:03:19 | stdout | 2021-12-08T10:03:19+00:00 INFO REQ-3 Cloudflare detected
2021-12-08 10:03:17 | stdout | 2021-12-08T10:03:17+00:00 INFO REQ-3 Params: {"maxTimeout":55000,"cmd":"request.get","url":"https://www3.yggtorrent.re/"}
2021-12-08 10:03:17 | stdout | 2021-12-08T10:03:17+00:00 INFO REQ-3 Incoming request: POST /v1
2021-12-08 10:03:13 | stderr | 2021-12-08T10:03:13+00:00 ERROR REQ-2 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=55000 (ms)
2021-12-08 10:03:13 | stderr | at processTimers (node:internal/timers:499:7)
2021-12-08 10:03:13 | stderr | at listOnTimeout (node:internal/timers:556:17)
2021-12-08 10:03:13 | stderr | at Timeout.fn (/home/node/flaresolverr/node_modules/await-timeout/src/index.js:32:46)
2021-12-08 10:03:13 | stderr | at exports.toError (/home/node/flaresolverr/node_modules/await-timeout/src/utils.js:20:38)
2021-12-08 10:03:13 | stderr | 2021-12-08T10:03:13+00:00 ERROR REQ-2 Error: Maximum timeout reached. maxTimeout=55000 (ms)
2021-12-08 10:02:18 | stdout | 2021-12-08T10:02:18+00:00 INFO REQ-2 Cloudflare detected
2021-12-08 10:02:17 | stdout | 2021-12-08T10:02:17+00:00 INFO REQ-2 Params: {"maxTimeout":55000,"cmd":"request.get","url":"https://www3.yggtorrent.re/"}
2021-12-08 10:02:17 | stdout | 2021-12-08T10:02:17+00:00 INFO REQ-2 Incoming request: POST /v1
2021-12-08 09:59:40 | stderr | 2021-12-08T09:59:40+00:00 ERROR REQ-1 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=55000 (ms)
2021-12-08 09:59:40 | stderr | at processTimers (node:internal/timers:499:7)
2021-12-08 09:59:40 | stderr | at listOnTimeout (node:internal/timers:556:17)
2021-12-08 09:59:40 | stderr | at Timeout.fn (/home/node/flaresolverr/node_modules/await-timeout/src/index.js:32:46)
2021-12-08 09:59:40 | stderr | at exports.toError (/home/node/flaresolverr/node_modules/await-timeout/src/utils.js:20:38)
2021-12-08 09:59:40 | stderr | 2021-12-08T09:59:40+00:00 ERROR REQ-1 Error: Maximum timeout reached. maxTimeout=55000 (ms)
2021-12-08 09:58:46 | stdout | 2021-12-08T09:58:46+00:00 INFO REQ-1 Cloudflare detected
2021-12-08 09:58:44 | stdout | 2021-12-08T09:58:44+00:00 INFO REQ-1 Params: {"maxTimeout":55000,"cmd":"request.get","url":"https://www3.yggtorrent.re/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date"}
2021-12-08 09:58:44 | stdout | 2021-12-08T09:58:44+00:00 INFO REQ-1 Incoming request: POST /v1
2021-12-08 09:57:14 | stdout | 2021-12-08T09:57:14+00:00 INFO Listening on http://0.0.0.0:8191
2021-12-08 09:57:07 | stdout | 2021-12-08T09:57:07+00:00 INFO Using 'harvester' to solve the captcha.
2021-12-08 09:57:07 | stdout | 2021-12-08T09:57:07+00:00 INFO FlareSolverr v1.2.8
2021-12-08 09:57:06 | stdout |  
2021-12-08 09:57:06 | stdout | > node ./dist/index.js
2021-12-08 09:57:06 | stdout | > flaresolverr@1.2.8 start
2021-12-08 09:57:06 | stdout

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

### Screenshots

<img width="901" alt="Capture d’écran 2021-12-08 à 11 09 12" src="https://user-images.githubusercontent.com/32598185/145189959-51ad7548-ba1f-447a-ab4d-23e55f5a5364.png">

**Comment by ilike2burnthing** [comment]
Please direct all FlareSolverr related issues to the FlareSolverr repo.

See https://github.com/FlareSolverr/FlareSolverr/issues/228 - update FlareSolverr and try again.
