### ISSUE TITLE
[revolutiontt] Login failed! Check the username and password. If they are ok, try logging on the website. (Config)

### ISSUE THREAD

**Issue by jappish84** [Jackett/Jackett#12714]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
(LOG TRACKER LIST REDACTED)

2021-12-18 08:59:10	Info	
Jackett startup finished in 20.233 s
2021-12-18 08:59:09	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2021-12-18 08:59:09	Info	
Adding filter indexer ('type:private' indexer) ...
2021-12-18 08:59:09	Info	
Adding filter indexer ('type:public' indexer) ...
2021-12-18 08:59:09	Info	
Adding aggregate indexer ('all' indexer) ...
2021-12-18 08:59:09	Info	
Loaded 591 indexers in total
2021-12-18 08:58:59	Info	
Loading Native indexers ...
2021-12-18 08:58:59	Info	
Using HTTP Client: HttpWebClient2
2021-12-18 08:58:59	Info	
Using FlareSolverr: No
2021-12-18 08:58:59	Info	
Using proxy: Disabled
2021-12-18 08:58:59	Info	
App config/log directory: /opt/jackett/Jackett
2021-12-18 08:58:59	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-12-18 08:58:59	Info	
Running in Docker: No
2021-12-18 08:58:59	Info	
File /etc/issue: Debian GNU/Linux 10 \n \l
2021-12-18 08:58:59	Info	
Jackett variant: CoreLinuxAmdx64
2021-12-18 08:58:59	Info	
OS version: Unix 4.19.0.17 (64bit OS) (64bit process)
2021-12-18 08:58:59	Info	
Environment version: 6.0.1 (/opt/jackett/)
2021-12-18 08:58:55	Info	
Starting Jackett v0.20.178
```

### Description

Not sure if related, but there is a previous issue reported with the same symptoms: https://github.com/Jackett/Jackett/issues/10310

My password got reset due to age and I had to change it, unsure how long this tracker hadn't been working.

I have no issues logging out/in through browser.
I have tried restarting the jacket service and restarting the machine.
I have tried using two different devices to reconfigure the tracker (tried removing and readding the tracker from jacket with restarting the service inbetween)

### Logged Error Messages

2021-12-18 08:59:58	Error	
Jackett.Common.ExceptionWithConfigData: Login failed! Check the username and password. If they are ok, try logging on the website.
   at Jackett.Common.Indexers.RevolutionTT.<ApplyConfiguration>b__9_0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RevolutionTT.cs:line 112
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.RevolutionTT.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RevolutionTT.cs:line 111
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by ilike2burnthing** [comment]
Check these troubleshooting steps - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#login-failed-selector

If you're using any special characters in your password, or if your password is overly long, try using 8-10 alphanumeric characters instead as a test.

If you still have issues, please provide and enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by jappish84** [comment]
Thanks for the pointer, I had special characters in the password, but later found out that my VPN was the issue, works as expected after turning off the VPN, you can now close this issue. Thanks for a great tool and keep up the great work :)
