### ISSUE TITLE
[cinecalidad] Exception (cinecalidad): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by frenchiveruti** [Jackett/Jackett#12728]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-22 07:46:02 	Info 	

Using HTTP Client: HttpWebClient2

2021-12-22 07:46:02 	Info 	

Using FlareSolverr: No

2021-12-22 07:46:02 	Info 	

Using proxy: Disabled

2021-12-22 07:46:02 	Info 	

App config/log directory: C:\ProgramData\Jackett

2021-12-22 07:46:02 	Info 	

ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads

2021-12-22 07:46:02 	Info 	

Running in Docker: No

2021-12-22 07:46:02 	Info 	

Jackett variant: CoreWindows

2021-12-22 07:46:02 	Info 	

OS version: Microsoft Windows NT 10.0.18362.0 (64bit OS)

2021-12-22 07:46:02 	Info 	

Environment version: 6.0.1 (C:\ProgramData\Jackett\)

2021-12-22 07:45:59 	Info 	

Starting Jackett v0.20.193
```

### Description

CineCalidad indexer has a challenge

### Logged Error Messages

Jackett.Common.IndexerException: Exception (cinecalidad): Challenge detected but FlareSolverr is not configured
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 590
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass11_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 567
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 566
   at Jackett.Common.Indexers.Cinecalidad.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\Cinecalidad.cs:line 116
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 755
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 397

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
