### ISSUE TITLE
[torrent9] Test search in Torrent9 => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by lplichart** [Jackett/Jackett#12726]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.188-ls54)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.91 (64bit OS) (64bit process)
Environment version: 6.0.1 (/app/Jackett/)
```

### Description

When testing the Torrent9 tracker, it fails, see logging below

### Logged Error Messages

System.Exception: Test search in Torrent9 => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by garfield69** [comment]
the indexer is working for me so this suggests the problem is at your end.
please turn on enhanced logging, repeat the test and provide the full log including the Debug and HTML. It may provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by lplichart** [comment]
Here is the log file of the failed test, a 2nd one where I do a search on this indexer in Jackett, and the html page of the search result on Torrent
[Torrent9.to - recherche_star wars.txt](https://github.com/Jackett/Jackett/files/7758136/Torrent9.to.-.recherche_star.wars.txt)
[log.txt](https://github.com/Jackett/Jackett/files/7758143/log.txt)
[log2.txt](https://github.com/Jackett/Jackett/files/7758144/log2.txt)
9

**Comment by garfield69** [comment]
the logs shows that in response to Jackett doing a search:
```
2021-12-21 21:36:30.3277 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://torrent9.to/search_torrent/star-wars.html) 
```
Jackett received:
```
2021-12-21 21:36:30.4891 Debug WebClient(HttpWebClient2): Returning OK => 0 bytes 
```
same for when you used the TEST button:
```
2021-12-21 21:20:10.1090 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://torrent9.to/) 
2021-12-21 21:20:10.2469 Debug WebClient(HttpWebClient2): Returning OK => 0 bytes 
```

so something is clearly **blocking** Jackett's access to the web site.

- Are you able to use your docker Jackett to test other _public_ indexers, or is only the _torrent9_ indexer that is behaving this way?
- Can you open a shell terminal to your Jackett docker image (typically with): 
`docker exec -it jackett /bin/bash`
and see what you get from the following:
`openssl s_client -connect torrent9.to:443`
and 
`curl -vvv https://torrent9.to/`
Thanks.

**Comment by lplichart** [comment]
Other indexers work fine, except for 1337x, but their website is currently unreachable.  Both the OpenSSL and curl commands seem to work fine, see output attached for openssl
[Openssl.txt](https://github.com/Jackett/Jackett/files/7758312/Openssl.txt)

curl output (only beginning):
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Torrent9.to - Telecharger avec Torrent9 Officiel</title>
<meta name="description" content="Torrent9 permet de télécharger des torrents de films, séries, musique et jeux. Accès direct à 60960 torrents sans inscription et sans ratio sur To
rrent9" />
<meta name="keywords" content="torrent9,torrent 9,torrent,films,cpasbien,t411,zone telechargement,torrents,series tv,telecharger,utorrent" />
<meta name="robots" content="follow,index,all" />
<meta name="revisit-after" content="1 days" />
<meta name="distribution" content="Global" />
<meta name="expires" content="never" />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
<link href='/static/css/css_style.css' rel='stylesheet' type='text/css'>
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="/static/css/font.min.css">
<link href="/static/css/style.css" rel="stylesheet">

<SCRIPT LANGUAGE="JavaScript">
        if (top.frames.length != 0)
            top.location = self.document.location;
    </script>
<script data-cfasync="false" type="text/javascript" src="//emuwanflat.com/rbTt8IeYIRE0/26544"></script>
<script data-cfasync="false" async type="text/javascript" src="//chapsartore.com/1clkn/18183"></script>

**Comment by garfield69** [comment]
@ilike2burnthing  docker, linux, network, not my cup of tea. Any thoughts?

**Comment by garfield69** [comment]
BTW https://1337x.to/ is perfectly reachable, the indexer works for me. what are you using for the address?

**Comment by lplichart** [comment]
I changed the URL for 1337x, and that worked.  I was using 1337x.to
initially, but that doesn't seem to be working.  Maybe blocked by my ISP

Le mar. 21 déc. 2021 à 22:53, garfield69 ***@***.***> a
écrit :

**Comment by lplichart** [comment]
Just tried all 3 url for torrent9 as well, and 3rd one works:
Didn't work:

   - https://torrent9.to/
   - https://www.torrent9.gg/


Worked:

   - https://torrent9.unblockninja.com/


Le mar. 21 déc. 2021 à 22:51, garfield69 ***@***.***> a
écrit :

**Comment by garfield69** [comment]
so you are now able to get results from your Jackett indexers now?

**Comment by lplichart** [comment]
Yes, I’m all good now, thanks
