### ISSUE TITLE
[req] add setting for persistent FlareSolverr session ID

### ISSUE THREAD

**Issue by shakeyourbunny** [Jackett/Jackett#12734]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-25 11:09:47 	Info 	Using HTTP Client: HttpWebClient2
2021-12-25 11:09:47 	Info 	Using FlareSolverr: No
2021-12-25 11:09:47 	Info 	Using proxy: Disabled
2021-12-25 11:09:47 	Info 	App config/log directory: /home/pulaski/.config/Jackett
2021-12-25 11:09:47 	Info 	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-12-25 11:09:47 	Info 	Running in Docker: No
2021-12-25 11:09:47 	Info 	File /etc/issue: \S
2021-12-25 11:09:47 	Info 	Jackett variant: CoreLinuxAmdx64
2021-12-25 11:09:47 	Info 	OS version: Unix 5.14.1.1 (64bit OS) (64bit process)
2021-12-25 11:09:47 	Info 	Environment version: 6.0.1 (/opt/Jackett/)
2021-12-25 11:09:45 	Info 	Starting Jackett v0.20.197
```

### Description

1337x.to yields no search results.

Reason maybe is that it is now CloudFlare protected.

### Logged Error Messages

```
2021-12-25 11:13:04 	Info 	

Manual search in 1337x for Linux => Found 0 releases

2021-12-25 11:13:03 	Error 	

Jackett.Common.IndexerException: Exception (1337x): Challenge detected but FlareSolverr is not configured
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 590
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1374
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 228
```

### Screenshots

![jackett-1337xto-empty-results](https://user-images.githubusercontent.com/5352403/147382849-e5ce6e33-c845-4c24-9dd6-ed31760087e1.png)

**Comment by shakeyourbunny** [comment]
Additional Info:
I did not have FlareSolverr installed, but after installing the latest version with docker-compose, FlareSolverr could resolve the result, but jackett ran into timeouts accessing 1337x.to:

Results after that were flakey, most requests did not succeed though.

**Comment by shakeyourbunny** [comment]
I managed to understand it now, but can you implement for Jackett an option field to have set up a persistent FlareSolverr session ID to speed up the requests with FlareSolverr?

If you don't provide a session ID for FlareSolverr, it will start the browser, process the request and destroy afterwards the browser session.

**Comment by xb00tt** [comment]
Ran into the same problem.
Saw your post.
Installed FlareSolverr.
All works fine now.

Jackett, Sonarr and Radarr timed out the first couple of times but worked fine eventually. 
Haven't tested it extensively so your issue may be absolutely valid.

**Comment by xb00tt** [comment]
![image](https://user-images.githubusercontent.com/93680121/147390105-2a338224-a240-4a52-8174-eaa4ee267606.png)

**Comment by garfield69** [comment]
@shakeyourbunny  The author of Flaresolverr is the one who set up the Jackett interface. It seems that the reason for not setting up a permanent session is to reduce the memory load, as per the description at https://github.com/FlareSolverr/FlareSolverr#how-it-works
@ngosang  this is best answered by you please. Thanks.

**Comment by ngosang** [comment]
The cookies provided by Cloudflare / FlareSolverr last less than 1 hour. Jackett is able to avoid calling FlareSolverr when the cookie is working. For example, if you make several requests in a short period of time.
I think implementing FlareSolverr sessions in Jackett will cause more issues than it will solve (related to memory, timeouts...)
