### ISSUE TITLE
[btnext] Exception (btnext)

### ISSUE THREAD

**Issue by jplobao** [Jackett/Jackett#12745]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-28 21:20:20	Info	
Loading Native indexers ...
2021-12-28 21:20:20	Info	
Using HTTP Client: HttpWebClient2
2021-12-28 21:20:20	Info	
Using FlareSolverr: No
2021-12-28 21:20:20	Info	
Using proxy: Disabled
2021-12-28 21:20:20	Info	
App config/log directory: C:\ProgramData\Jackett
2021-12-28 21:20:20	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2021-12-28 21:20:20	Info	
Running in Docker: No
2021-12-28 21:20:20	Info	
Jackett variant: CoreWindows
2021-12-28 21:20:20	Info	
OS version: Microsoft Windows NT 6.2.9200.0 (64bit OS)
2021-12-28 21:20:20	Info	
Environment version: 6.0.1 (C:\ProgramData\Jackett\)
2021-12-28 21:19:59	Info	
Starting Jackett v0.20.200
```

### Description

A mensagem recebida é inesperada ou tem a formatação incorreta.: The SSL connection could not be established, see inner exception. (Test)

While trying to get torrents get error as seen below

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (btnext): A mensagem recebida é inesperada ou tem a formatação incorreta.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): A mensagem recebida é inesperada ou tem a formatação incorreta.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 594
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1374
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 758
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 304
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Can you access the site in browser from the same device and IP?

Are you using a VPN or proxy external to Jackett?

**Comment by jplobao** [comment]
yes i can, not using VPN or proxy
Direct Access

**Comment by jplobao** [comment]
if you want, i can pass you a user and a temporary password so you can access

**Comment by ilike2burnthing** [comment]
Sure. Sign out in your browser, just so your account isn't flagged as signing in from two different IPs at the same time (I'm not sure of the tracker's rules, so this is just a precaution).

Then send your credentials to `jacketttest[AT]gmail[DOT]com`

I'll post here again once I'm done testing and signed out, and you can change the password.

**Comment by jplobao** [comment]
Hi,

Sended the e-mail

**Comment by ilike2burnthing** [comment]
Thanks, that all worked for me, so the issue seems to be specific to your system and not the site or your account.

Is your Jackett installed on a Windows 8 or Windows Server 2012 system?

Can you confirm that you have `Microsoft Windows Desktop Runtime - 6.0.1 (x64)` (the latest .NET runtime) installed?

Do you have any AV, firewall, content blocker, or other security software running which could be interfering with Jackett?

**Comment by jplobao** [comment]
Hmm, strange.. but that was recent...
Windows 8 Enterprise edition.

Not the latest one:
![image](https://user-images.githubusercontent.com/38633364/147622270-3f704926-6d65-4ebd-8272-9360acc4220f.png)

**Comment by jplobao** [comment]
No AV, Firewall, or content Blocker... :(

**Comment by ilike2burnthing** [comment]
Scroll down beneath those Visual C++ programs, it should have the exact name I typed above. If it's not there, or not a similarly named one (e.g. 6.0.0, 5.0.13, etc.), close Jackett down, and install the runtime from here - https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.1-windows-x64-installer

After it's installed, restart your computer, and see if that indexer in Jackett now works.

I take it the indexer was previously working in Jackett and has only recently stopped? No other indexers are affected?

**Comment by jplobao** [comment]
OK, i will do that.

No other 6 indexers are working great

![image](https://user-images.githubusercontent.com/38633364/147623606-5c49b52a-e908-4a21-8829-69eea5ad409a.png)

Installed Microsoft Windows Desktop Runtime - 6.0.1 (x64) , rebooted the system and the error remains

![image](https://user-images.githubusercontent.com/38633364/147623854-fa8a976c-2700-4d81-a220-f3dadfcca58a.png)

**Comment by ilike2burnthing** [comment]
Do you have a custom DNS (e.g. 1.1.1.1 or 8.8.8.8) set for your system? Do you have DNS over HTTPS (DoH) set in your browser?

Do you have access to a Windows 10/11 device that you can test this on? Wondering if Windows 8 is just too old.

**Comment by jplobao** [comment]
Do you have a custom DNS (e.g. 1.1.1.1 or 8.8.8.8) set for your system? Do you have DNS over HTTPS (DoH) set in your browser?
Yes, 8.8.8.8
Tryied acessing via browser and works fine

Do you have access to a Windows 10/11 device that you can test this on? Wondering if Windows 8 is just too old.
Unfortunatly no. I had to prepare a VM with that OS to test it!

But if you say that this problem only occors to me, i will try to figure out, anything or try to stop using it. I thought it was global... :S

**Comment by ilike2burnthing** [comment]
Try changing the DNS to 1.1.1.1 and see if that makes any difference.

Asking about DNS over HTTPS in browser was to see if there was any reason why your browser was able to bypass a potential ISP block when Jackett can't.

Out of interest, why are you using Windows 8 rather than 8.1 or newer?

**Comment by jplobao** [comment]
Hi,

Tryied that, but the problem still remains.

I'm using because i have everything installed on that system, Jackett, radarr, sonarr, emby, and more stuff. To migrate to a new OS i had to reinstall from scratch everything and loosing the database of those programs.

**Comment by ilike2burnthing** [comment]
You should be able to do an in place upgrade to Windows 10 as far as I'm aware (I've done it previously from 7 and 8.1).

In saying that, I can't say for certain that it will resolve your issue, but there's probably a good chance seeing as mainstream support ended for 8.1 nearly 3 years ago, so some things will be obsolete by now.

**Comment by jplobao** [comment]
You can't :(

Windows 10 does a new installation, and so this programs are not registered, or configured correctly... So i have to do a fresh install :(

**Comment by ilike2burnthing** [comment]
What is your host OS that VMware is running on?

**Comment by jplobao** [comment]
![image](https://user-images.githubusercontent.com/38633364/147718534-7ca7cba4-e5d0-4b69-b6f8-1fdc1c650088.png)

**Comment by ilike2burnthing** [comment]
Can you not test Jackett on it?

**Comment by jplobao** [comment]
Yeap...

fresh new install on this computer and worked great! :(

![image](https://user-images.githubusercontent.com/38633364/147718875-cf1c2041-cd8d-4e2f-b535-7242e617da0b.png)


Gonna try to reinstall on the prodution one

**Comment by jplobao** [comment]
Tried and no joy... :(

Leave it... i will try to upgrade my OS in a near future :(
