### ISSUE TITLE
[underverse] Test search in Underverse => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by shohart** [Jackett/Jackett#12749]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
I am using docker container
```

### Description

suddenly tracker stopped working. same goes with anonymous entity.

### Logged Error Messages

Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://underver.se/login.php using form selector form[action$="/login.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 573
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 968
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by ilike2burnthing** [comment]
I'm not sure why, but Jackett is receiving `Домен продается. Здесь может быть Ваша реклама.` (translated - `This domain is for sale. Here can be your advertising.`) when trying to search (shown as a 47 bytes binary file in the log) or login.

You get the same if you try to curl the site from within the Jackett Docker container - `curl -v -s -o /config/test.txt https://underver.se`

This doesn't appear to be related to the user agent (tested both Linux and Windows Jackett UAs using the UA switcher extension), nor is it a basic anti-bot screen shown on first access (open `view-source:https://underver.se/` in a private/incognito window).

Tested with and without FlareSolverr enabled, VPN makes no difference (working in browser anyway, so it's not a weird IP block), and DNS is the same for host and container, so it's not a resolution problem.

@garfield69 any ideas?

**Comment by garfield69** [comment]
No idea. Even using the cookie method I cannot get a session to work.
I'm inclined to remove the indexer as unsupportable.

**Comment by ilike2burnthing** [comment]
Same. I'll see if I can contact a site admin, see if there has been some change on their end which could be causing this. Remove it if there's no reply in a week.

**Comment by ilike2burnthing** [comment]
Not that this helps solve our issue, and I'm also not sure why, but I worked out where that 'domain is for sale' text is coming from - https://underverse.club/

**Comment by ilike2burnthing** [comment]
@shohart I sent a message to Паукан (who I think is the site founder). If you know of someone better to message, or if there is a way to contact admins as a whole, please let me know.

**Comment by ilike2burnthing** [comment]
Working again. It was a UA issue, they thought we were a copyright crawler.

I'm pretty sure now in my testing I was using FlareSolverr's UAs... 🤦
