### ISSUE TITLE
[mejortorrent] The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject]  CN=www.mejortorrentes.net[Issuer]  CN=

### ISSUE THREAD

**Issue by ElAdri1999** [Jackett/Jackett#12759]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-12-31 19:23:04.4038 Info Starting Jackett v0.20.216 
2021-12-31 19:23:07.4804 Info Environment version: 6.0.1 (C:\Jackett\) 
2021-12-31 19:23:07.4834 Info OS version: Microsoft Windows NT 10.0.19043.0 (64bit OS) 
2021-12-31 19:23:07.4834 Info Jackett variant: CoreWindows 
2021-12-31 19:23:07.4834 Info Running in Docker: No 
2021-12-31 19:23:07.4834 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2021-12-31 19:23:07.4834 Info App config/log directory: C:\ProgramData\Jackett 
2021-12-31 19:23:07.4834 Info Using proxy: Disabled 
2021-12-31 19:23:07.4834 Info Using FlareSolverr: No 
2021-12-31 19:23:07.5062 Info Using HTTP Client: HttpWebClient2 
2021-12-31 19:23:07.5301 Info Loading Native indexers ... 
2021-12-31 19:23:07.7201 Info Loaded 87 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, danishbytes, darmowetorenty, divxtotal, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, seals, secretcinema, sharewoodapi, shazbat, ShizaProject, showrss, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, xthor-api, zonaq, animetosho 
2021-12-31 19:23:07.7724 Info Loading Cardigann indexers from: C:\Users\Server-RDP\AppData\Roaming\cardigann\definitions\, C:\Users\Server-RDP\AppData\Local\cardigann\definitions\, C:\Jackett\Definitions 
2021-12-31 19:23:12.5544 Info Loaded 499 Cardigann indexers: 0daykiev, 0magnet, 1337x, 1ptbar, 24rolika, 2fast4you, 3changtrai, 3dtorrents, 4thd, 52pt, 7torrents, abtorrents, acgrip, acgsou, acidlounge, acrossthetasman, aftershock, aidoruonline, aither-api, aither, alleenretail, amigosshare, anaschcc, anilibria, anime-free, animeclipse, animelayer, animeworld-api, animeworld, aniRena, anisource, arabafenice, arabp2p, arenabg, asiancinema, asiandvdclub, audiobookbay, audionews, aussierules, backups, badasstorrents, baibako, bangumi-moe, beitai, bestcore, beyond-hd-oneurl, beyond-hd, bibliotik, bigfangroup, bit-titan, bitbazis, bitded, bithorlo, bithumen, bitru, bitsearch, bitsexy, bitspyder, Bittorrentfiles, bitturk, bluebirdhd, bluesbrothers, blutopia-api, blutopia, booktracker, bootytape, borgzelle, boxingtorrents, brasiltracker, broadcity, brsociety-api, brsociety, bt4g, btdigg, btetree, btnext, btschool, btsow, bwtorrents, byrbt, byrutor, carpathians, carphunter, cartoonchaos, casatorrent, cathoderaytube, catorrent, ccfbits, ceskeforum, chdbits, chilebt, cinemageddon, cinemamovies, cinematik, classix, coastalcrew, comicat, concen, concertos, cpasbien, cpasbienclone, crazyhd, crazyspirits, crnaberza, crt2fa, cryptichaven, dariustracker, dark-shadow, darktracker, datascene-api, datascene, datatalli, deildu, demonoid, desitorrents-api, desitorrents, diablotorrent, digitalcore, dimeadozen, discfan, divteam, dmhy, docspedia, dragonworldreloaded, dxp, ebookparadijs, ebooks-shares, ehentai, elitetorrent-biz, empornium, empornium2fa, eniahd, esharenet, estone, ettv, exkinoray, extratorrent-st, extremebits, extremetorrents, extremlymtorrents, exttorrents, eztv, falkonvisionteam, fanoin, fantasticheaven, fantastiko, femdomcult, filelisting, film-paleis, finelite, finvip, firebit, fouducinema, freshmeat, frozenlayer, funkytorrents, gamestorrents, gay-torrents, gay-torrentsorg, gaytorrentru, generationfree, genesismovement, gfxpeers, gigatorrents, girotorrent, gktorrent, glodls, greekdiamond, greekteam, gtorrentpro, haidan, haitang, hamsterstudio, happyfappy, hd4fans, hdai, hdarea, hdatmos, hdbits, hdbitscom, hdc, hdcenter, hdchina, hdcity, hdcztorrent, hddolby, hdforever, hdhome, hdhouse, hdme, hdmonkey, hdolimpo, hdonly, hdroute, hdsky, hdspain, hdtime, hdtorrentsit, hdturk, hdu, hdzone, hellastz, hqsource, huntorrent, ibit, idope, ilcorsaroblu, ilcorsaronero, ilcorsaroverde, immortuos, indietorrents, insanetracker, internetarchive, isohunt2, itorrent, iv-torrents, jpopsuki, jptv, karagarga, keepfriends, kickasstorrents-to, kickasstorrents-ws, kinonavse100, kinorun, kinozal, kisssub, krazyzone, lastfiles, lat-team, learnbits, learnflakes, leech24, legittorrents, lemonhd, lepornoinfo, lesaloon, libranet, limetorrents, limetorrentsclone, linkomanija, linuxtracker, losslessclub, mactorrentsdownload, madsrevolution, magicheaven, magico, majomparade, marinetracker, megamixtracker, megapeer, mesevilag, metaltracker, microbit, mikan, milkie, mircrew, mixtapetorrent, mma-torrents, mnv, mononokebt, mousebits, moviesdvdr, moviesite, movietorrent, movietorrentz, mteamtp, mteamtp2fa, muziekfabriek, mvgroupforum, mvgroupmain, mypornclub, myspleen, nbtorrents, netcosmo, nethd, netlab, newpct-me, newretro, newstudio, newstudiol, nipponsei, nitro, nntt, noname-club, noname-clubl, nyaasi, omgwtftrackr, oncesearch, onejav, opencd, opensharing, oshenpt, ourbits, oxtorrent, p2pbg, p2pelite, parnuxi, pctorrent, peeratiko, peerjunkies, peersfm, pier720, piratadigital, piratbit, piratbitl, pirateiro, pixelcove, polishsource, pornbay, pornbits, pornforall, pornleech, pornolive, pornorip, pornoslab, pornotor, pornotorrent, portugas, potuk, proaudiotorrents, proporno, prostylex, pterclub, ptfiles, pthome, ptmsg, ptsbao, pttime, punkshorror, puntotorrent, purovicio, pussytorrents, putao, puurhollands, pwtorrents, r3vwtf, racing4everyone, racingforme, rainbowtracker, rapidzona, redbits, redstartorrent, reelflix-api, reelflix, resurrectthenet, rgfootball, rintor, rintornet, riperam, RockBox, romanianmetaltorrents, rptorrents, rus-media, rustorka, rutor, rutracker-ru, scenepalace, scenerush, sdbits, seedfile, selezen, sexxi, sexypics, shareisland-api, shareisland, sharewood, siambit, skipthecommercials-api, skipthecommercials, sktorrent-org, sktorrent, slosoul, snowpt, solidtorrents, sosulki, soulvoice, soundpark, speedmasterhd, speedtorrentreloaded, spidertk, spiritofrevolution, sporthd, sportscult, springsunday, sugoimusic, sukebeinyaasi, superbits, swarmazon, tapochek, tasmanit, teamhd, teamos, tekno3d, tellytorrent-api, tellytorrent, teracod, the-devils-lounge, theaudioscene, theempire, thefallingangels, thegeeks, thehorrorcharnel, theleachzone, themixingbowl, theoccult, thepiratebay, theplace, thesceneplace, theshinning, theshow, thevault, tjupt, tlfbits, tokyotosho, torlock, torlook, toros, torrent-explosiv, torrent-paradise-ml, torrent-pirat, torrent-turk, torrent9, torrent9clone, torrentbd, torrentby, torrentccf, torrentdb, torrentdownload, torrentdownloads, torrentfunk, torrentgalaxy, torrenthr, torrenting, torrentkitty, torrentland, torrentleech-pl, torrentleech, torrentlt, torrentmasters, torrentmax, torrentoyunindir, torrentparadise, torrentproject2, torrentqq, torrentsectorcrew, torrentseeds-api, torrentsir, torrentslocal, torrentsurf, torrentv, torrentview, torrentwhiz, torrentz2eu, totallykids, totheglory, totheglorycookie, trackeros, trancetraffic, trezzor, tribalmixes, trupornolabs, turkseed, turktorrent, tvchaosuk, twilight, twilightszoom, u2, uhdbits, underverse, underversel, uniondht, unionfansub, uniongang, unlimitz, vizuk, vsthouse, vsttorrents, wdt, whiteangel, wihd, woot, xiteme, xbytesv2, xwtclassics, xwtorrents, xxxadulttorrent, xxxtor, xxxtorrents, ydypt, yggcookie, yggtorrent, yourbittorrent, yts, zamundanet, zelkaorg, zetorrents, zomb, zooqle, ztracker 
2021-12-31 19:23:12.5634 Info Loaded 586 indexers in total 
2021-12-31 19:23:12.5634 Info Adding aggregate indexer ('all' indexer) ... 
2021-12-31 19:23:12.5864 Info Adding filter indexer ('type:public' indexer) ... 
2021-12-31 19:23:12.5864 Info Adding filter indexer ('type:private' indexer) ... 
2021-12-31 19:23:12.5864 Info Adding filter indexer ('type:semi-public' indexer) ... 

   at Jackett.Common.Utils.Clients.HttpWebClient2.ValidateCertificate(HttpRequestMessage request, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 50
   at System.Net.Http.ConnectHelper.<>c__DisplayClass1_0.<SetUpRemoteCertificateValidationCallback>b__0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 594
   at Jackett.Common.Indexers.MejorTorrent.PerformQueryNewest(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\MejorTorrent.cs:line 174
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\MejorTorrent.cs:line 128
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\MejorTorrent.cs:line 112
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 113
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

### Description

Tried to add MejorTorrent as indexer, was expected to work normally

### Logged Error Messages

 An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] CN=www.mejortorrentes.net [Issuer] CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES [Serial Number] 00ADFBCD61000000001E00000000000000 [Not Before] 12/16/2016 2:07:49 PM [Not After] 12/16/2026 2:07:49 PM [Thumbprint] 934A3F50EE1135C6AB3DA59B989F0CF57EC3180A

### Screenshots

nothing appart from message above shown

**Comment by garfield69** [comment]
Your ISP is blocking access to this site and routing you down a black hole with an invalid certificate.
Use your Jackett dashboard to edit the config and try out any of the alternate addresses.
If all of them fail then consider using a proxy or vpn or switching dns from the one provided by your ISP to one of the public ones, such as 1.1.1.1 from cloudflare or 8.8.8.8 from google.

**Comment by dbolser** [comment]
I'm getting errors like this, but I can see / search the site in question in my browser. I'm using pi.hole as the DNS resolver, and it's configured to use 9.9.9.9, so I'm not sure where I'm going wrong... I'm going to try configuring a tor proxy to see if that helps...

**Comment by ilike2burnthing** [comment]
Post the error.

**Comment by dbolser** [comment]
```An error occurred while testing this indexer
Exception (bulltorrent): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED at /wrkdirs/usr/ports/lang/mono6.8/work/mono-6.8.0.123/external/boringssl/ssl/handshake_client.c:1132: The SSL connection could not be established, see inner exception.
```

**Comment by dbolser** [comment]
That is the popup, when I click 'Server Logs' it looks a bit different:
Jackett.Common.IndexerException: Exception (bulltorrent): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /wrkdirs/usr/ports/lang/mono6.8/work/mono-6.8.0.123/external/boringssl/ssl/handshake_client.c:1132

**Comment by dbolser** [comment]
Here you go:
```
2023-05-28 00:14:08.8995 Error Jackett.Common.IndexerException: Exception (bulltorrent): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /wrkdirs/usr/ports/lang/mono6.8/work/mono-6.8.0.123/external/boringssl/ssl/handshake_client.c:1132 Jackett.Common.IndexerException: Exception (bulltorrent): Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /wrkdirs/usr/ports/lang/mono6.8/work/mono-6.8.0.123/external/boringssl/ssl/handshake_client.c:1132 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /wrkdirs/usr/ports/lang/mono6.8/work/mono-6.8.0.123/external/boringssl/ssl/handshake_client.c:1132
  at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00048] in <2deb8ccd8f0546038e28d46e7bcc1998>:0 
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000da] in <2deb8ccd8f0546038e28d46e7bcc1998>:0 
  at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
  at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <2deb8ccd8f0546038e28d46e7bcc1998>:0 
  at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000fc] in <2deb8ccd8f0546038e28d46e7bcc1998>:0 
   --- End of inner exception stack trace ---
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00262] in <2deb8ccd8f0546038e28d46e7bcc1998>:0 
  at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x000c3] in <53402c1c880b4cf1bde830eb66c183f0>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x00102] in <53402c1c880b4cf1bde830eb66c183f0>:0 
  at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00322] in <53402c1c880b4cf1bde830eb66c183f0>:0 
  at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <53402c1c880b4cf1bde830eb66c183f0>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <53402c1c880b4cf1bde830eb66c183f0>:0 
  at System.Net.Http.DecompressionHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ca] in <53402c1c880b4cf1bde830eb66c183f0>:0 
  at FlareSolverrSharp.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000d7] in <45f627be90594a5f81a55f2c08c104ff>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x0017e] in <53402c1c880b4cf1bde830eb66c183f0>:0 
  at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x004b3] in <c0c37d2adff94c139e304e662af4f76a>:0 
  at Jackett.Common.Utils.Clients.WebClient.GetResultAsync (Jackett.Common.Utils.Clients.WebRequest request) [0x001c2] in <c0c37d2adff94c139e304e662af4f76a>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync (System.String url, System.String cookieOverride, Jackett.Common.Utils.Clients.RequestType method, System.String referer, System.Collections.Generic.IEnumerable`1[T] data, System.Collections.Generic.Dictionary`2[TKey,TValue] headers, System.String rawbody, System.Nullable`1[T] emulateBrowser) [0x00101] in <c0c37d2adff94c139e304e662af4f76a>:0 
  at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00973] in <c0c37d2adff94c139e304e662af4f76a>:0 
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query, System.Boolean isMetaIndexer) [0x00113] in <c0c37d2adff94c139e304e662af4f76a>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query, System.Boolean isMetaIndexer) [0x0021f] in <c0c37d2adff94c139e304e662af4f76a>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query, System.Boolean isMetaIndexer) [0x00071] in <c0c37d2adff94c139e304e662af4f76a>:0 
  at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000b2] in <c0c37d2adff94c139e304e662af4f76a>:0 
  at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in <e66b34d089234efd8a737cc1339e3fd0>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <e66b34d089234efd8a737cc1339e3fd0>:0 
```

**Comment by ilike2burnthing** [comment]
More appropriate issue - https://github.com/Jackett/Jackett/issues/14318

Follow the steps there (the most basic one being, don't use a mono build), and see if you can resolve your issue.

**Comment by dbolser** [comment]
Thanks, just chasing down the issue to the fact that i'm stuck wiht mono on a truenas (freebsd) box jail... this looks handy
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258709 (failed cert-sync)...

I'll follow tips in that issue.

Huge thanks for quick response!
