### ISSUE TITLE
[req]: TVroad

### ISSUE THREAD

**Issue by wanalearncode** [Jackett/Jackett#12760]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name:TVRoad
- URL:https://tvroad.info/
- Description: TVroad is a FRENCH Private Torrent Tracker for TV
- Minimum Seeding Time and Minimum Ratio (if Private):No ratio
- Additional Comments: Medusa version is available
```
engine: TTv3 clone
MST: 96h

**Comment by garfield69** [comment]
registration completed, pending validation. no clue how long that may take. I'll check back tomorrow.

**Comment by garfield69** [comment]
v0.20.238

**Comment by garfield69** [comment]
https://tvroad.info/ returning
```html
Warning: require_once(/var/www/vhosts/tvroad.info/httpdocs/themes//header.php): failed to open stream: No such file or directory in /var/www/vhosts/tvroad.info/httpdocs/inclusion/fonctions/constructionpage.php on line 25

Fatal error: require_once(): Failed opening required '/var/www/vhosts/tvroad.info/httpdocs/themes//header.php' (include_path='.:/opt/plesk/php/7.4/share/pear') in /var/www/vhosts/tvroad.info/httpdocs/inclusion/fonctions/constructionpage.php on line 25
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
getting errors during login
```
Error on 20220811110228 for TvRoad.txtJackett.Common.ExceptionWithConfigData: Error: Désolé, Les Identifiants Saisis Sont Incorrects.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 538
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 565
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1538




<br />
<b>Notice</b>:  Trying to access array offset on value of type null in <b>/var/www/vhosts/tvroad.info/httpdocs/inclusion/fonctions/connexion.php</b> on line <b>186</b><br />
<br />
<b>Notice</b>:  Trying to access array offset on value of type null in <b>/var/www/vhosts/tvroad.info/httpdocs/inclusion/fonctions/connexion.php</b> on line <b>186</b><br />
<br />
<b>Notice</b>:  Trying to access array offset on value of type null in <b>/var/www/vhosts/tvroad.info/httpdocs/inclusion/fonctions/connexion.php</b> on line <b>186</b><br />
<br />
<b>Notice</b>:  Trying to access array offset on value of type null in <b>/var/www/vhosts/tvroad.info/httpdocs/inclusion/fonctions/connexion.php</b> on line <b>186</b><br />
```
using the browser the console shows 
```
jquery-3.5.1.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at HTMLDocument.<anonymous> (java_klappe.js:125:40)
    at e (jquery-3.5.1.min.js:2:30005)
    at t (jquery-3.5.1.min.js:2:30307)
(anonymous) @ java_klappe.js:125
e @ jquery-3.5.1.min.js:2
t @ jquery-3.5.1.min.js:2
setTimeout (async)
S.readyException @ jquery-3.5.1.min.js:2
(anonymous) @ jquery-3.5.1.min.js:2
e @ jquery-3.5.1.min.js:2
t @ jquery-3.5.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
fire @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
t @ jquery-3.5.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
fire @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
ready @ jquery-3.5.1.min.js:2
B @ jquery-3.5.1.min.js:2
11:09:42.258 jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: a[href=#top]
    at oe.error (jquery.min.js:2:12961)
    at oe.tokenize (jquery.min.js:2:18943)
    at oe.select (jquery.min.js:2:21833)
    at Function.oe [as find] (jquery.min.js:2:6808)
    at w.fn.init.find (jquery.min.js:2:24400)
    at new w.fn.init (jquery.min.js:2:24889)
    at w (jquery.min.js:2:896)
    at HTMLDocument.<anonymous> (Monter_Descendre.js:19:3)
    at l (jquery.min.js:2:29375)
    at c (jquery.min.js:2:29677)
``` when the login page is presented.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://tvroad.info/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://tvroad.info/TvRoad/Connexion
```
Database Error
Bdd error. Please send a PM to the site administrator.
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://tvroad.info/TvRoad/Connexion returns
```
Notice:  Trying to access array offset on value of type null in <b>/var/www/vhosts/tvroad.info/httpdocs/pagelogin/account-login.php on line 41
```
followed by 
```
Redirection
Désolé, Les Identifiants Saisis Sont Incorrects.
```
which might mean my a/c has been deleted.

Just me?

**Comment by ilike2burnthing** [comment]
Same here, and trying to reset my password says my account doesn't exist. Maybe a temp issue as there are errors popping up as well.

**Comment by garfield69** [comment]
@ilike2burnthing  I take it you had no response from tvroad admin?
I will remove the indexer if you have no news by tomorrow.

**Comment by garfield69** [comment]
@wanalearncode  do you have any info on what is going on with tvroad?

**Comment by ilike2burnthing** [comment]
Nope, heard nothing back.

**Comment by garfield69** [comment]
v0.21.983

**Comment by ilike2burnthing** [comment]
Nope :/ and registration now returns `mysql_connect: Too many connections`

**Comment by SuissoNaBisso9** [comment]
> Nope :/ and registration now returns `mysql_connect: Too many connections`

So I go in touch with the tracker admin, they didn't know this was you account, it was deactivated for lack of activity. They can reactivate an account for you, though they need you to contact them directly for security reasons. Can I PM you ti give you their discord username so you can get in touch with them and get your access back ?

**Comment by ilike2burnthing** [comment]
Sure, send it to `jacketttest [AT] gmail [DOT] com`

**Comment by ilike2burnthing** [comment]
> xxxxx is not accepting friend requests. They'll have to add you to become friends.

I use the same username on Discord.

**Comment by SuissoNaBisso9** [comment]
> > xxxxx is not accepting friend requests. They'll have to add you to become friends.
> 
> I use the same username on Discord.

they just reopened their profile to invitation so you should be able to invite them as a friend now (and also sent you a friend request on my side just in case)

**Comment by ilike2burnthing** [comment]
[v0.21.1189](https://github.com/Jackett/Jackett/releases/v0.21.1189)

**Comment by ilike2burnthing** [comment]
https://tvroad.info/ - ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://tvroad.info/ 503 Service Temporarily Unavailable

**Comment by garfield69** [comment]
v0.21.2516
