### ISSUE TITLE
[torrentseeds-api] Test search in TorrentSeeds (API) => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by JReverse** [Jackett/Jackett#12788]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-01-08 14:25:41	Info	Loading Native indexers ...
2022-01-08 14:25:41	Info	Using HTTP Client: HttpWebClient2
2022-01-08 14:25:41	Info	Using FlareSolverr: No
2022-01-08 14:25:41	Info	Using proxy: Disabled
2022-01-08 14:25:41	Info	App config/log directory: /config/Jackett
2022-01-08 14:25:41	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-01-08 14:25:41	Info	Running in Docker: Yes (image build: unknown)
2022-01-08 14:25:41	Info	File /etc/issue: Arch Linux \r (\l)
2022-01-08 14:25:41	Info	Jackett variant: CoreLinuxAmdx64
2022-01-08 14:25:41	Info	OS version: Unix 5.14.15.0 (64bit OS) (64bit process)
2022-01-08 14:25:41	Info	Environment version: 6.0.0 (/usr/lib/jackett/)
2022-01-08 14:25:40	Info	Jackett Data will be stored in: /config/Jackett
2022-01-08 14:25:40	Info	Starting Jackett v0.20.216
```

### Description

Torrent Seeds Is Broke

### Logged Error Messages
```
System.Exception: Test search in TorrentSeeds (API) => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /tmp/makepkg/jackett/src/Jackett-0.20.216/src/Jackett.Common/Services/IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in /tmp/makepkg/jackett/src/Jackett-0.20.216/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /tmp/makepkg/jackett/src/Jackett-0.20.216/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```
### Screenshots

N/A

**Comment by garfield69** [comment]
the indexer is working for me.
please provide a full enhanced log so we can see what traffic is being sent to you, perhaps the included Debug and JSON will provide a clue to what your issue is.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by JReverse** [comment]
@garfield69 To clarify you have free-leech enabled right? Cuz thats what causes it.

**Comment by garfield69** [comment]
Ah. OK, you did not mention that previously.
But this is not a problem with the indexer.
The web site does not have any freeleech available, so it is no surprise when the indexer returns 0 results if you are searching for freeleech.
From the web site search the following:
![image](https://user-images.githubusercontent.com/6933240/148666429-cdf48784-f72b-406a-bfc7-d2d81f59cee9.png)
