### ISSUE TITLE
digitalcore: Error while parsing field=category

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12794]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
latest
```

### Description

query = baby

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (digitalcore): Error while parsing field=category, selector=category, value=38: Object reference not set to an instance of an object.
 ---> System.Exception: Error while parsing field=category, selector=category, value=38: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1448
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 758
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 228
```

**Comment by garfield69** [comment]
I don't have an account on digitalcore.
Please provide the enhanced log HTML so I can see the search page, 
OR 
provide the category 38 cat and description so I can add the category
`    - {id: 38, cat: xxxxx, desc: xxxxxxx}`
thanks.
