### ISSUE TITLE
[romanianmetaltorrents] Test search in Romanian Metal Torrents => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Furbach** [Jackett/Jackett#12809]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-01-12 13:24:47.2161 Info Starting Jackett v0.20.285 
2022-01-12 13:24:47.6159 Info Environment version: 6.0.1 (C:\Users\aldos\Desktop\Jackett\) 
2022-01-12 13:24:47.6159 Info OS version: Microsoft Windows NT 10.0.22000.0 (64bit OS) 
2022-01-12 13:24:47.6159 Info Jackett variant: CoreWindows 
2022-01-12 13:24:47.6159 Info Running in Docker: No 
2022-01-12 13:24:47.6159 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2022-01-12 13:24:47.6159 Info App config/log directory: C:\ProgramData\Jackett 
2022-01-12 13:24:47.6159 Info Using proxy: Disabled 
2022-01-12 13:24:47.6159 Info Using FlareSolverr: No 
2022-01-12 13:24:47.6250 Info Using HTTP Client: HttpWebClient2 
2022-01-12 13:24:47.6250 Info Loading Native indexers ...
```

### Description

I just create the indexer and when i test i got this error: " An error occurred while testing this indexer
Test search in Romanian Metal Torrents => Found no results while trying to browse this tracker"

### Logged Error Messages

```text
at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1563 
2022-01-12 13:22:26.5878 Info Test search in Romanian Metal Torrents => Found 0 releases 
2022-01-12 13:22:26.5878 Error System.Exception: Test search in Romanian Metal Torrents => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26 System.Exception: Test search in Romanian Metal Torrents => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Check these troubleshooting steps - https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-selector

If none of those resolve your issue, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Furbach** [comment]
can be the vpn the problems? what .exe(console,service, tray) i have to remove from the tunnel?

**Comment by ilike2burnthing** [comment]
Could be, yes. I would assume service.

**Comment by ilike2burnthing** [comment]
Did that resolve your issue?

**Comment by Furbach** [comment]
i have try witout the vpn and i got a different error. in the next days i will update

**Comment by Wolf666** [comment]
I have similar issues with this.

Error Messages: 
1 - Exception (romanianmetaltorrents): Relogin failed: Parse error (first msg after test)
2 - Login failed: Selector "a[href="logout.php"]" didn't match: Parse error (when testing)

Enhanced log attached.

[log.txt](https://github.com/Jackett/Jackett/files/12925195/log.txt)

**Comment by ilike2burnthing** [comment]
Reconfigure the indexer and enter the captcha.

If you still have issues, open a new issue, provide the information requested, and provide a new enhanced log that only has your login attempt for romanianmetaltorrents, not multiple other indexers making it nearly impossible to read.
