### ISSUE TITLE
[PORNOLAB] Cannot download torrents from search.

### ISSUE THREAD

**Issue by masterofobzene** [Jackett/Jackett#12822]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Current version: v0.20.314
WINDOWS 10
```

### Description

1. search something
2. try to add a torrent from pornolab in search results.

### Logged Error Messages

```text
Error 	

pornolab: Download selector a[class="dl-stub dl-link"] didn't match:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html dir="ltr">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<title>404 - Service unavailable</title>
</head>
<body>
	<br /><br />
	<h2 style="text-align: center;">503 - Service unavailable</h2>
</body>
</html>

-----------------------------------------------------------------
Error downloading. indexer: pornolab path: https://pornolab.net/forum/viewtopic.php?t=2831282
System.Exception: Download selector a[class="dl-stub dl-link"] didn't match
   at Jackett.Common.Indexers.PornoLab.Download(Uri link) in D:\a\1\s\src\Jackett.Common\Indexers\PornoLab.cs:line 371
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 56
```

### Screenshots

![imagen](https://user-images.githubusercontent.com/94469116/149534479-38bec0a8-0fe6-4e9f-aace-3a70f4650618.png)

**Comment by ilike2burnthing** [comment]
Working ok here, including the result in your log. Check again to see if it was a temporary issue.

If it continues, and all downloads for the indexer are affected, can you access the site, search and download in browser from the same device and IP?
