### ISSUE TITLE
toros: Error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#12823]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
v0.20.314
```

### Description

Empty search in Toros

### Logged Error Messages

```text
CardigannIndexer (toros): Error while parsing row '
<tr class="a">
	<td class="tv5" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/25520001/windows-11-x64-pro-en-us-oct-2021-tpm-2-0-bypassed-ds.html">
				<br>
				<b>Warning</b>: Undefined array key "highlightname" in
				<b>/home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php</b>
				on line
				<b>43</b>
				<br>
				Windows 11 X64 Pro en-US OCT 2021 TPM 2 0 Bypassed - DS</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.tcdn.fun/vt.webp">
				<img src="https://c.tcdn.fun/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc<br">
		<b>Warning</b>: Undefined array key "trending" in
		<b>/home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php</b>
		on line
		<b>60</b>
		<br>
		<br>
		<b>Warning</b>: Attempt to read property "value" on null in
		<b>/home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php</b>
		on line
		<b>60</b>
		<br>
		&gt;12 Nov</td>
	<td class="tc">4.8 GB</td>
	<td class="tul">1483</td>
	<td class="tdl">435</td>
	<td class="tc">
		<font size="1" color="gray">
			<i>unknown</i>
		</font>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.tcdn.fun/lang/<br">
			<b>Warning</b>: Undefined array key "lang" in
			<b>/home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php</b>
			on line
			<b>70</b>
			<br>
			.webp&gt;<img src="https://c.tcdn.fun/lang/<br">
			<b>Warning</b>: Undefined array key "lang" in
			<b>/home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php</b>
			on line
			<b>72</b>
			<br>
			.png width=16 height=16 alt="<br>
			<b>Warning</b>: Undefined array key "language" in
			<b>/home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php</b>
			on line
			<b>73</b>
			<br>
			"&gt;</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.tcdn.fun/h6.webp">
			<img src="https://c.tcdn.fun/h6.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Warning: Undefined array key "trending" in /home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php on line 60

Warning: Attempt to read property "value" on null in /home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php on line 60
>12 Nov +01:00: DateTime parsing failed for "Warning: Undefined array key "trending" in /home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php on line 60

Warning: Attempt to read property "value" on null in /home/tc/templates_c/5e9dd305a5da512d12e5eefd4ee0ecf5c126909a_0.file.browse_frontpage.tpl.php on line 60
>12 Nov +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 186
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1563
```
```


### Screenshots

_No response_

**Comment by ilike2burnthing** [comment]
Problem with their Top 100 page (and Trending page) - https://www.toros.co/top100.html

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.toros.co/?q=fett returns a blank screen with 
`Warning: Undefined array key "c" in /home/tc/core/search.php on line 301`

**Comment by ilike2burnthing** [comment]
https://www.toros.co/ - Error 522 - Connection timed out

**Comment by garfield69** [comment]
online
