### ISSUE TITLE
[cinecalidad] Could not find release from this URL. (Config)

### ISSUE THREAD

**Issue by Alexwijn** [Jackett/Jackett#12830]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Environment version: 6.0.1 (/app/Jackett/)
OS version: Unix 5.10.63.8 (64bit OS) (64bit process)
Jackett variant: CoreLinuxArm64
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Running in Docker: No
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /config/Jackett
Using proxy: Disabled
Using FlareSolverr: No
Using HTTP Client: HttpWebClient2
```

### Description

The provider cinecalidad has stopped working for me. When testing I get the following error.

### Logged Error Messages

```text
Exception: Could not find release from this URL.
   at Jackett.Common.Indexers.Cinecalidad.<>c.<ApplyConfiguration>b__9_0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 90
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.Cinecalidad.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 89
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
There's been changes to the site's results html.
I'll have a go updating the indexer for the new layout.

**Comment by garfield69** [comment]
I can pull up the results, however there has also been changes to the download link in the torrent details page.
the new method for interpreting the link is beyond my c# skills. 
We will need a proper C# dev to make this work.
example of the link below
```html
<li class="py-1 ">
  <a class="inline-block px-2 py-1 text-xs font-bold text-center text-blue-600 border border-blue-600 rounded btn hover:bg-blue-600 hover:text-white" href="#!" data-url="aHR0cHM6Ly93d3cuY2luZWNhbGlkYWQubGF0L2xpbmtzL09DODVNalkxTmk4eA==" data-lmt="eyJpYXQiOjE2NDIyMDA0NDUsImV4cCI6MTY0MjIwMDc0NSwibG10Ijp7ImlkIjo5MjY1Nn19" data-link>Torrent</a>
</li>
```

**Comment by garfield69** [comment]
v0.20.363
