### ISSUE TITLE
[newpct] Found 0 releases! (Config)

### ISSUE THREAD

**Issue by diegargon** [Jackett/Jackett#12889]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
No proxy, No Flareresolver, no docker
OS UBUNTU LTS
Jackett: v 0.20.470
```

### Description

Few days ago begin fail with : Found 0 releases 

### Logged Error Messages

```text
System.Exception: Found 0 releases!
   at Jackett.Common.Indexers.NewPCT.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 182
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```
```


### Screenshots

_No response_

**Comment by garfield69** [comment]
looks like https://atomixhq.top/ultimas-descargas/pg/1 is  Returning Moved => https://atomixhq.top/
will try to find the replacement path

**Comment by garfield69** [comment]
looks the the ultimas-descargas page is no longer in page segments, its now a very long single page.

**Comment by garfield69** [comment]
but even using https://atomixhq.top/ultimas-descargas/ only worked once for me from the browser, then I keep getting 301-moved =>  https://atomixhq.top/ so I think the site may be broken.
I'll sub the code change to handle the one page, but I don't expect success.

**Comment by garfield69** [comment]
v0.20.477

**Comment by syp1975** [comment]
I'm on v0.20.477. Still having the issue. Tested with and w/o flaresolverr. Ubuntu LTS. Docker.

**Comment by ilike2burnthing** [comment]
So long as https://atomixhq.top/ultimas-descargas/ redirects to https://atomixhq.top/ the indexer isn't going to work (without a rewrite).

**Comment by diegargon** [comment]
ultimas-descargas works but the problems continue.

Probably you must revert latest changes.

**Comment by ilike2burnthing** [comment]
Yea, that's what @garfield69 found in https://github.com/Jackett/Jackett/issues/12889#issuecomment-1024813801, it is hit or miss (and there are many more misses).

**Comment by diegargon** [comment]
yes, sorry i miss that part

**Comment by diegargon** [comment]
don't known if is coincidence or if is something useful but if i open in firefox the dev tools->network  and check "Disable Cache" seems works always.

**Comment by egrueda** [comment]
I saw they started checking the "referer" HTTP header.
If you launch a GET to https://atomixhq.top/ultimas-descargas/ without referer, it returns "301 Moved Permanently"
Using "Referer: https://atomixhq.top/" does the job.
Hope it helps

**Comment by garfield69** [comment]
>I saw they started checking the "referer" HTTP header.

Oh, nice catch. I'll test and update the indexer if I find it works for me too.

**Comment by garfield69** [comment]
v0.20.494

**Comment by egrueda** [comment]
Just updated to 0.20.494 
Is does find new episodes (thanks!) but download fails.
I opened issue 12909

**Comment by tothek** [comment]
https://atomixhq.art/

**Comment by garfield69** [comment]
@tothek thanks.

**Comment by garfield69** [comment]
v0.20.497

**Comment by diegargon** [comment]
download link not work i think they change this too and they complicated the issue more 

surely it is trying to put obstacles to app like jackett 

Movie Link
https://atomixhq.art/descargar/torrent/peliculas-castellano/the-dry-2022-/blurayrip-ac3-5-1/
Download Link
https://atomtt.com/t_download/167518/the-dry--2022-/

**Comment by garfield69** [comment]
go to #12914 for updates on this topic
