### ISSUE TITLE
Tracker passwords are not escaped and can result in HTML injection

### ISSUE THREAD

**Issue by FearrMe** [Jackett/Jackett#12883]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/jackett/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.11.22.5 (64bit OS) (64bit process)
Environment version: 6.0.1 (/home/jackett/Jackett/)
Starting Jackett v0.20.444
```

### Description

My password for one of my trackers has a `"` shortly followed by a `>` in it, which results in HTML getting injected and the password input field closing. The rest of the password gets printed below the input box., which means the password field doesn't contain the right password anymore and it makes me unable to update the tracker settings without entering the password again.

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Error: These credentials do not match our records.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 521
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 738
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

example password `abcdef"hi+k>mnop`

    <div class="setup-item-inputstring">
        <input class="form-control" type="password" value="abcdef" hi+k>
        "mnop"
    </div>
![bfMZvpr](https://user-images.githubusercontent.com/1979467/151101424-aef474ed-8ead-49c0-ba6c-38661246cc27.png)

**Comment by garfield69** [comment]
for clarity please confirm:
- you are using the jackett dashboard to edit an indexer config and entering a password or are you using the add-a-new-indexer and using the wrench to create a new config for an indexer, or some other method (specify?)
- are you pasting a password or entering it manually from the keyboard
- are you using a chrome browser (which version?) or some other browser (which? and version?)
Thanks.

**Comment by FearrMe** [comment]
> for clarity please confirm:
> 
> * you are using the jackett dashboard to edit an indexer config and entering a password or are you using the add-a-new-indexer and using the wrench to create a new config for an indexer, or some other method (specify?)
> * are you pasting a password or entering it manually from the keyboard
> * are you using a chrome browser (which version?) or some other browser (which? and version?)
>   Thanks.

* i can configure and add indexers just fine for the first time(and every subsequent time if and only if i re-enter the password), but every time i open up the indexer configuration jackett prints the password into the "password" box, which is when the HTML injection occurs, see example screenshot above
* pasting. again, the problem doesn't actually occur when _entering_ the password
* chrome 97.0.4692.71 64-bit

**Comment by garfield69** [comment]
Ah good, so the issue occurs when you edit an existing config, and the password breaks out. Gotcha. Thanks.

**Comment by garfield69** [comment]
@ilike2burnthing @ngosang  its a Gui issue I suppose, outside of my expertise.
I can confirm this happens to me too on my win10 Jackett dashboard when I edit the config for a indexer set with the `abcdef"hi+k>mnop` password.

**Comment by ilike2burnthing** [comment]
This affects all text fields on the config panel - password, username, APIKey, cookie, or user-agent. It doesn't affect Jackett's server settings.

Presumably the change needs to be made here.
https://github.com/Jackett/Jackett/blob/dc1961b10580228d6448625f1ca3f2f0ad0df411/src/Jackett.Common/Content/custom.js#L854-L863

Thought I was onto something with:

```javascript
        switch (type) {
            case "hiddendata":
                itemEntry.value = $el.find(".setup-item-hiddendata input").val();
                break;
            case "inputstring":
                itemEntry.value = encodeURI($el.find(".setup-item-inputstring input").val());
                break;
            case "password":
                itemEntry.value = encodeURI($el.find(".setup-item-password input").val());
                break;
```

as it escapes the values, but it transforms them to `abcdef%22hi+k%3Emnop` instead (that's what gets passed for login). `escape` and `encodeURIComponent` didn't work.

@ngosang all yours!

**Comment by garfield69** [comment]
v0.20.912
