### ISSUE TITLE
[trezzor] Test search in Trezzor => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by LukePavelka** [Jackett/Jackett#12880]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Inside Docker

01-23 23:14:01 Info Starting Jackett v0.20.428 
01-23 23:14:01 Info Environment version: 6.0.1 (/app/Jackett/) 
01-23 23:14:01 Info OS version: Unix 5.10.0.8 (64bit OS) (64bit process) 
01-23 23:14:01 Info Jackett variant: CoreLinuxAmdx64 
01-23 23:14:01 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
01-23 23:14:01 Info Running in Docker: Yes (image build: v0.20.324-ls55) 
01-23 23:14:01 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
01-23 23:14:01 Info App config/log directory: /config/Jackett 
01-23 23:14:01 Info Using proxy: Disabled 
01-23 23:14:01 Info Using FlareSolverr: No 
01-23 23:14:01 Info Using HTTP Client: HttpWebClient2
```

### Description

trezzor indexer not working, probably an access error.

### Logged Error Messages

```text
System.Exception: Test search in Trezzor => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 310
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26


2022-01-23 23:19:52	Info	
Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 336.4999ms
2022-01-23 23:19:52	Info	
Test search in Trezzor => Found 0 releases
2022-01-23 23:19:52	Debug	
WebClient(HttpWebClient2): Returning OK => 12907 bytes
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "DTD/xhtml1-strict.dtd">
<html><head>
<link rel="alternate" type="application/rss+xml" title="Trezzor RSS feed" href="/rss_torrents.php?idlogin=" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1250">
<title>TreZzoR Tracker - Torrents</title>
<link rel="stylesheet" href=/style/trezzor/torrentnew.css type="text/css" />
<!--[if IE]><link rel="stylesheet" type="text/css" href="/style/trezzor/torrentnewie.css" /><![endif]-->


  <script type='text/javascript' src="/js/jquery-1.2.6.pack.js"></script>
  <script type='text/javascript' src="/js/jquery.corners.min.js"></script>

<script type='text/javascript'>
	//<![CDATA[
	$(document).ready(function()
	{
		$('.block_underhead').corners("4px top-right");


    $('.down-list').width($('.dropdown-menu').width()-2);

    $('.dropdown-menu').hover(
      function () {
        $('.menu-first', this).addClass('slide-down');
        $('.down-list', this).slideDown(100);
		$('.menu_lave', this).css("background", "url('./style/trezzor/images/menu_left_bg_hover.gif')");
      },
      function () {
		$('.menu_lave', this).css("background", "url('./style/trezzor/images/menu_left_bg.gif')");
        obj = this;
        $('.down-list', this).slideUp(50, function(){
						$('.menu-first', obj).removeClass('slide-down');
						});

      }
    );
    $('.spoiler-wrap a.showit').click(function(){
        var div = $(this).parent().parent();
        div.find('.spoiler-content-full').removeClass('hide');
        div.find('.spoiler-content-short').addClass('hide');
        return false;
    })
    $('.spoiler-wrap a.hideit').click(function(){
        var div = $(this).parent().parent();
        div.find('.spoiler-content-full').addClass('hide');
        div.find('.spoiler-content-short').removeClass('hide');
        return false;
    })


	});
	//]]>
</script>
<style>
    .hide{display:none!important;}
    .spoiler-wrap{margin:15px;padding:5px;border: 1px dotted #CCCCCC}
    .spoiler-content-short , .spoiler-content-full{padding:20px;}
    .spoiler-content-full > a{margin-top: 10px;}
    .spoiler-header{font-size:18px;font-weight:bold;padding:20px 5px;}
</style>
<link rel="stylesheet" href="/style/buttons-min.css" type="text/css" />
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5808647-15', 'czech-server.com');
  ga('send', 'pageview');

</script>
</head>
<body>


<center>
<div class="wrap">
	<div id="header">

		<a href="./index.php">
	      <img class="logo" border=0 src="./images/styl1/logo.png">
		</a>

	</div><!--koniec header-->

<table border="0" width="100%">
<tr><td colspan="2">

<div id="main_menu">

	<div class="dropHolder">
		<div class="dropdown-menu">
			<a href="/">
				<div class="polozka_menu">
					<div class="menu_prave">
						<h2>HOME</h2>
					</div>
					<div class="menu_lave">
						<img src="./images/styl1/symbol_home.gif" alt="home" />
					</div>
				</div>
			</a>
		</div>
	</div>

	<div class="dropHolder">
		<div class="dropdown-menu">
				<div class="polozka_menu">
			<a href="torrents.php">
					<div class="menu_prave">
						<h2>TORRENTY</h2>
					</div>
					<div class="menu_lave">
						<img src="./images/styl1/symbol_torrent.gif" alt="torrenty" />
					</div>
				</a>
					<ul class="down-list" style="display:none;">
			            <li><a href="torrents.php">Torrenty</a></li>
                        <div class="down-list_divider"></div>
			            <li><a href="wishlist.php">Úschovňa torrentov</a></li>
                        <div class="down-list_divider"></div>
                        <li><a style="width:259px;" href="upload.php">Upload</a></li>
						<div class="down-list_divider"></div>
                        <li><a style="width:259px;" href="easyupload.php">Easy upload</a></li>
						<div class="down-list_divider"></div>
						
                        			            <li><a href="viewrequests.php">Požiadavky</a></li>
						<div class="down-list_divider"></div>
			            						<li class="down-list_bottom"><img src="./images/styl/down-list_bottom.gif" alt="down-list_bottom" /></li>
			        </ul>
				</div>
		</div>
	</div>

	<div class="dropHolder">
		<div class="dropdown-menu">
			<div class="polozka_menu">
            <a href="usercp.php?uid=">
				<div class="menu_prave">
					<h2>PROFIL</h2>
				</div>
				<div class="menu_lave">
					<img src="./images/styl1/symbol_profil.gif" alt="profil" />
				</div>
			</a>
				<ul class="down-list" style="display:none;">
		            <li><a href="usercp.php?uid=">Profil</a></li>
                    <div class="down-list_divider"></div>
                    <li><a href="ssl.php">Šifrované spojenie</a></li>

                    <div class="down-list_divider"></div>
                    <li><a href="loginlog.php">Prihlásenia</a></li>

                    <div class="down-list_divider"></div>
		            <li><a href="donate.php">Darcovstvo</a></li>
                    
                    <div class="down-list_divider"></div>
                    <li><a style="width:259px;" href="kredit.php">Počet bodov</a></li>

                    <div class="down-list_divider"></div>
		            <li><a href="invite.php">Pozvánky</a></li>

                    <div class="down-list_divider"></div>
                    <li><a href="friendlist.php">Kontakt list</a></li>
                    <div class="down-list_divider"></div>
		            <li class="lastLI"><a href="style.php">Zmena štýlu</a></li>
					<li class="down-list_bottom"><img src="./images/styl/down-list_bottom.gif" alt="down-list_bottom" /></li>
		        </ul>
			</div>
		</div>
	</div>

	<div class="dropHolder">
		<div class="dropdown-menu">
			<div class="polozka_menu">
			<a href="extra-stats.php">
                <div class="menu_prave">
					<h2>STATISTIKY</h2>
				</div>
				<div class="menu_lave">
					<img src="./images/styl1/symbol_statistiky.gif" alt="štatistiky" />
				</div>
			</a>
				<ul class="down-list" style="display:none;">
		            <li><a href="extra-stats.php">Extra štatistiky</a></li>

                    <div class="down-list_divider"></div>
                    <li><a href="top100.php">TOP 100 torrentov</a></li>
					<li class="down-list_bottom"><img src="./images/styl/down-list_bottom.gif" alt="down-list_bottom" /></li>
		        </ul>
			</div>
		</div>
	</div>

	<div class="dropHolder">
		<div class="dropdown-menu">
			<div class="polozka_menu">
			<a href="pravidla.php">
                <div class="menu_prave">
					<h2>INFO</h2>
				</div>
				<div class="menu_lave">
					<img src="./images/styl1/symbol_info.gif" alt="info" />
				</div>
			</a>
				<ul class="down-list" style="display:none;">
                <li><a href="pravidla.php">Pravidla</a></li>

                    <div class="down-list_divider"></div>
		            <li><a href="users.php">Užívatelia</a></li>
                    <div class="down-list_divider"></div>
		            <li><a href="usersv.php">Správy od vedenia</a></li>
                    <div class="down-list_divider"></div>
                    		<li><a href="forum.php">Fórum</a></li>
                    <div class="down-list_divider"></div>
		            <li><a href="kc.php">Kontaktné centrum</a></li>
                    <div class="down-list_divider"></div>
		            <li><a href="https://tracker.czech-server.com/irc/chat.php">IRC</a></li>
					<div class="down-list_divider"></div>
		            <li class="lastLI"><a href="viewnews.php">Novinky</a></li>
					<li class="down-list_bottom"><img src="./images/styl/down-list_bottom.gif" alt="down-list_bottom" /></li>
		        </ul>
			</div>
		</div>
	</div>

	<div class="dropHolder">
		<div class="dropdown-menu">
			<div class="polozka_menu">
				<div class="menu_prave">
					<h2>VSEOBECNE</h2>
				</div>
				<div class="menu_lave">
					<img src="./images/styl1/symbol_vseobecne.gif" alt="všeobecné" />
				</div>

				<ul class="down-list" style="display:none;">
		            <li><a href="games.php">Games</a></li>
					<div class="down-list_divider"></div>
		            <li><a href="dox.php">Uschovna obrazku</a></li>
					<div class="down-list_divider"></div>
		            <li><a href="rss_info.php">RSS informácie</a></li>

                    <div class="down-list_divider"></div>
		            <li class="lastLI"><a href="tfd.php">Trezzor Movies</a></li>

					<li class="down-list_bottom"><img src="./images/styl/down-list_bottom.gif" alt="down-list_bottom" /></li>
		        </ul>
			</div>
		</div>
	</div>
</div>
	<center>
    <form action="prihlasenie.php" name="login" method="post">
    <table class='menu' border="0" width="99%" cellpadding="2" cellspacing="0">
    <tr>
    <td class='menu' align="left">
      <table border="0" cellpadding="2" cellspacing="0">
      <tr>
      <td align="right" class='menu'>Uzivatel:</td>
      <td class='menu'><input type="text" size="15" name="uid" value="" maxlength="40" style="font-size:10px" /></td>
      <td align="right" class='menu'>Heslo:</td>
      <td class='menu'><input type="password" size="15" name="pwd" maxlength="40" style="font-size:10px" /></td>
      <td class='menu' align="center"><input type="submit" value="Prihlasit" style="font-size:10px" /></td>
      </tr>
      </table>
    </td>
    <td class='menu' align="center"><a href="account.php">Registrovat</a></td>
    <td class='menu' align="center"><a href="recover.php">Ztracene heslo</a></td>
    </tr>
    </table>
    </form>
	</center>

</div><!--koniec divu pre usertoolbar_block-->
<div class="float_right"><div id="wikipedia"><img src="./images/styl1/wiki.gif" /><A href="http://wiki.czech-server.com/" target=_blank><B>Wikipedia - manualy, navody, rady a mnoho ineho</B></A></div></div><BR></td></tr>

<tr>
<td width="200" valign=top>



<table style="width: 100%; margin-left: 5px;" cellspacing="0" cellpadding="0">
	<tr>
		<td style="width: 4px; height: 30px">
		<img alt"" src="./style/trezzor/styl1/block_head_left.gif" width="4" height="30" /></td>
		<td style="width: 5px" class="block_head"><span class="no_wrap">Navigace</span></td>
		<td style="width: 4px; height: 30px">
		<img alt="" src="./style/trezzor/styl1/block_head_right.gif" width="4" height="30" /></td>
		<td style="width: 99%"></td>
	</tr>
</table>


    <div class="block_underhead"></div>
    <div class="block_content">
	<table class=lista cellpadding=0 cellspacing=0 width=100% align=center>

              	<tr>

              		<TD width=100% align=justify valign=top>
  <div class="polozka"><a href=duplicity.php><h3>Bans</h3></a></div>
<div class="polozka"><a href=http://forum.czech-server.com/viewforum.php?f=2><h3>Caste problemy</h3></a></div>
<div class="polozka"><a href=login.php><h3>Prihlaseni</h3></a></div>

              		</td>

              	</tr>

            </table>
		</div>
	<div class="blok_bottom_left"><img alt="" src="./style/trezzor/styl1/block_bottom_left.gif" width="5" height="5" /></div>
	<div class="blok_bottom_right"><img alt="" src="./style/trezzor/styl1/block_bottom_right.gif" width="5" height="5" /></div>
	<div class="blok_bottom"></div>
		<br/>
  </td>
 <td valign=top><div align="center"><br /><table border="0" width="500" cellspacing="0" cellpadding="0"><tr>
<td bgcolor="#FFFFFF" align="center" style="border-style: dotted; border-width: 1px" bordercolor="#CC0000">
<font color="#CC0000"><b>ERRORNOT_AUTHORIZED Torrenty!</b><br />Sorry...<br /></font></td>
</tr></table></div><br />
<center><a href=javascript:history.go(-1)>zpet</a></center></td>
</tr>
<tr>
<td height="20%" colspan="2">
</td></tr>
</table>

</div> <!--koniec wrap-->
</center>




<p align=center>
  <div class='footer2'>
	<center>
		<div class="wrap">
			<div id="footer2_left">
<a href="/mobile/">mobilná verzia</a> <br /> [ Cas vygenerovania: 0.2704 sec. ] <br /> [ GZIP: disabled ]	</div>
      <B>Upozornení:</B> Žádný ze zde zobrazených souboru se nenachází na tomhle serveru. Administrátor stránek nenese žádnou zodpovednost za zde zverejnené odkazy. Nepoužívejte tuto stránku k distribuci nebo k downloadu jakýchkoliv materiálu, ke kterým nemáte legální oprávnení. Vše konáte na vlastní zodpovednost.<BR>
      <B>Disclaimer:</B> None of the files shown here are actually hosted on this server. The links are provided solely by this site's users. The administrator of this site cannot be held responsible for what its users post, or any other actions of its users. You may not use this site to distribute or download any material when you do not have the legal rights to do so. It is your own responsibility to adhere to these terms.
	</div>
</div>

</body>
</html>
2022-01-23 23:19:51	Debug	
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://tracker.czech-server.com/torrents.php?search=&category=0&active=1)
```

### Screenshots

![image](https://user-images.githubusercontent.com/76946156/150700263-fdefccc7-f081-4841-8fcf-0fdc69d50437.png)
![image](https://user-images.githubusercontent.com/76946156/150700289-0906d5aa-cbf5-46bc-a8a7-219e854b4ca7.png)

**Comment by garfield69** [comment]
Have you refreshed your cookie for the trezzor indexer?
Please read https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work and particularly the Notes section to see if any applies to you.

**Comment by LukePavelka** [comment]
I apologize for my mistake, I didn't realize that I have a special associated network on containers.
