### ISSUE TITLE
Most of the Turkish trackers having trouble with cookie. [****] Exception (****): Login failed: Selector (TurkSeed, HDTurk, Broadcity, TurkTorrent)

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#12887]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 10
No FlareSolverr
Jackett Version v0.20.466
```

### Description

I had this issue before and I dont know how to reproduce but here is what's going on with Turkish trackers. (BroadCity,TurkTorrent,TurkSeed, HDTurk) They are all cookie-type trackers and their cookies expire in about 2 weeks, I don't know the exact time but it's happening a lot recently. All I have to do to fix this issue is renewing cookies for all of them. There is no way to produce this issue but I can fix it by changing cookie. It's pretty annoying tho because I always have failed trackers in my dashboard  and these are causing me to search slowly.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (turkseed): Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 827
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1497
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 794
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1644
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 771
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 311
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
That is the nature of cookies.
The web site sets the life span of a cookie, and they expire in due time.
There is no way to automate replacing cookies with new ones.
For some sites we must use the cookie method because the standard login form method does not work (usually due to the site using a ReCaptcha or some other challenge that cannot be programmatically solved).
So there is nothing we ca do about it.

**Comment by garfield69** [comment]
FYI: when fetching cookie make sure you logged into site using the **remember me** check box on the form to extent the life of the session cookie.

**Comment by swannie-eire** [comment]
for anyone else seeing this issue it appears that the cookies are linked to the IP. so make sure you pull the cookies from a machine that will have the same Public IP as your Jackett instance as that was the issue for me with broadcity

**Comment by batuhankrmn** [comment]
> for anyone else seeing this issue it appears that the cookies are linked to the IP. so make sure you pull the cookies from a machine that will have the same Public IP as your Jackett instance as that was the issue for me with broadcity.
> 
> Once I used the same internet connect on my machine as jackett it worked as expected.

Here is the funny fact about Turkish internet users, Almost all of our Internet Service Providers use CGNAT IP. So that could be the problem for me because cookies used to expire quickly but this changed when I bought the static IP service. It lasts much longer now.
