### ISSUE TITLE
[iptorrents] Your cookie did not work: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_UNKNOWN_HOST at https://iptorrents.com/t?o=time (Config)

### ISSUE THREAD

**Issue by jaw1994** [Jackett/Jackett#12894]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.1.2:8191/
Using proxy: Socks5 (I have tried with none)
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.470-ls55)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.0 (64bit OS) (64bit process)
Environment version: 6.0.1 (/app/Jackett/)
Starting Jackett v0.20.470
```

### Description

This was a working system.

1. IPTorrent indexer had an error, so I clicked on to tools to fix it.
2. I pasted the cookie, in-case it was old.
3. I got the error.

` An error occurred while updating this indexer
Your cookie did not work: FlareSolverr was unable to process the request, please check FlareSolverr logs.
Message: Error: Unable to process browser request. Error: NS_ERROR_UNKNOWN_HOST at https://www.iptorrents.com/t?o=time
Click here to open an issue on GitHub for this indexer.`

### Logged Error Messages

```text
2022-01-29 17:57:09 	Error 	

System.Exception: Your cookie did not work: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_UNKNOWN_HOST at https://iptorrents.com/t?o=time
   at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 193
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

2022-01-29 17:57:00 	Warn 	

Request to IPTorrents failed with exception 'FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_UNKNOWN_HOST at https://iptorrents.com/t?o=time'. Retrying in 1s... (Attempt 2 of 2).

2022-01-29 17:56:52 	Warn 	

Request to IPTorrents failed with exception 'FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Unable to process browser request. Error: NS_ERROR_UNKNOWN_HOST at https://iptorrents.com/t?o=time'. Retrying in 0.5s... (Attempt 1 of 2).
```

**Comment by machetie** [comment]
switch to a different domain (https://ipt.findnemo.net)

**Comment by ilike2burnthing** [comment]
If the proxy uses credentials then FlareSolverr will fail. The error should be different with the proxy removed, please provide it.

If you cannot access `https://www.iptorrents.com` without a proxy/VPN, then switch to one of the several other mirrors provided.

**Comment by jaw1994** [comment]
It worked with the proxy off and without changing the domain...

Good restart of server fix the issue

`2022-01-29 18:12:26 | Info | Test search in IPTorrents => Found 50 releases`
