### ISSUE TITLE
[iptorrents] Exception (iptorrents): Challenge detected but FlareSolverr is not configured: Challenge detected but FlareSolverr is not configured (Test)

### ISSUE THREAD

**Issue by Wardy125** [Jackett/Jackett#12895]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
01-29 16:32:45 Info Starting Jackett v0.20.477
01-29 16:32:45 Info Environment version: 6.0.1 (/app/Jackett/)
01-29 16:32:45 Info OS version: Unix 5.10.28.0 (64bit OS) (64bit process)
01-29 16:32:45 Info Jackett variant: CoreLinuxAmdx64
01-29 16:32:45 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l
01-29 16:32:45 Info Running in Docker: Yes (image build: v0.20.477-ls55)
01-29 16:32:45 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
01-29 16:32:45 Info App config/log directory: /config/Jackett
01-29 16:32:45 Info Using proxy: Disabled
01-29 16:32:45 Info Using FlareSolverr: No
01-29 16:32:45 Info Using HTTP Client: HttpWebClient2
01-29 16:32:45 Info Loading Native indexers ...
01-29 16:32:45 Info Loaded 86 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, danishbytes, darmowetorenty, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, seals, secretcinema, sharewoodapi, shazbat, ShizaProject, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, xthor-api, zonaq, animetosho
01-29 16:32:45 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
01-29 16:32:46 Info Loaded 490 Cardigann indexers: 0daykiev, 0magnet, 1337x, 1ptbar, 24rolika, 2fast4you, 3changtrai, 3dtorrents, 4thd, 52pt, 7torrents, Bittorrentfiles, abtorrents, acgrip, acgsou, acidlounge, acrossthetasman, aftershock, aidoruonline, aither-api, alleenretail, amigosshare, anaschcc, anilibria, anime-free, animeclipse, animelayer, animeworld-api, aniRena, anisource, arabafenice, arabp2p, arenabg, asiancinema, audiobookbay, audionews, aussierules, backups, badasstorrents, baibako, bangumi-moe, beitai, bestcore, beyond-hd-oneurl, beyond-hd, bibliotik, bigfangroup, bit-titan, bitbazis, bitcityreloaded, bitded, bithorlo, bithumen, bitru, bitsearch, bitsexy, bitspyder, bitturk, bluebirdhd, bluesbrothers, blutopia-api, booktracker, bootytape, borgzelle, boxingtorrents, brasiltracker, broadcity, brsociety-api, bt4g, btdigg, btetree, btnext, btschool, btsow, bwtorrents, byrbt, byrutor, carpathians, carphunter, cartoonchaos, casatorrent, cathoderaytube, catorrent, ccfbits, ceskeforum, chdbits, chilebt, cinemageddon, cinemamovies, cinematik, classix, coastalcrew, comicat, concen, concertos, cpasbien, cpasbienclone, crazyhd, crazyspirits, crnaberza, crt2fa, cryptichaven, dariustracker, dark-shadow, darktracker, datascene-api, datatalli, deildu, demonoid, desitorrents-api, diablotorrent, digitalcore, dimeadozen, discfan, divteam, dmhy, docspedia, dragonworldreloaded, dxp, ebookparadijs, ebooks-shares, ehentai, elitetorrent-biz, empornium, empornium2fa, eniahd, esharenet, estone, ettv, exkinoray, extratorrent-st, extremebits, extremetorrents, extremlymtorrents, exttorrents, eztv, falkonvisionteam, fanoin, fantasticheaven, fantastiko, femdomcult, filelisting, film-paleis, finelite, finvip, firebit, fouducinema, freshmeat, frozenlayer, funkytorrents, gamestorrents, gay-torrents, gay-torrentsorg, gaytorrentru, generationfree, genesismovement, gfxpeers, gigatorrents, girotorrent, gktorrent, glodls, greekdiamond, greekteam, gtorrentpro, haidan, haitang, hamsterstudio, happyfappy, hawke-uno, hd4fans, hdai, hdarea, hdatmos, hdbits, hdbitscom, hdc, hdcenter, hdchina, hdcity, hdcztorrent, hddolby, hdforever, hdhome, hdhouse, hdme, hdmonkey, hdolimpo-api, hdonly, hdroute, hdsky, hdspain, hdtime, hdtorrentsit, hdturk, hdu, hdzone, hellastz, hqsource, huntorrent, ibit, idope, ilcorsaroblu, ilcorsaronero, ilcorsaroverde, immortuos, indietorrents, insanetracker, internetarchive, isohunt2, itorrent, iv-torrents, jpopsuki, jptv, karagarga, keepfriends, kickasstorrents-to, kickasstorrents-ws, kinonavse100, kinorun, kinozal, kisssub, krazyzone, lastfiles, lat-team, learnbits, learnflakes, leech24, legittorrents, lemonhd, lepornoinfo, lesaloon, libranet, limetorrents, limetorrentsclone, linkomanija, linuxtracker, losslessclub, mactorrentsdownload, madsrevolution, magicheaven, magico, majomparade, marinetracker, mediamaatjes, megamixtracker, megapeer, mesevilag, metaltracker, microbit, mikan, milkie, mircrew, mixtapetorrent, mma-torrents, mnv, mononokebt, mousebits, moviesdvdr, moviesite, movietorrent, movietorrentz, mteamtp, mteamtp2fa, muziekfabriek, mvgroupforum, mvgroupmain, mypornclub, myspleen, nbtorrents, netcosmo, nethd, netlab, newpct-me, newretro, newstudio, newstudiol, nipponsei, nitro, nntt, noname-club, noname-clubl, nyaasi, omgwtftrackr, onejav, opencd, opensharing, oshenpt, ourbits, oxtorrent, p2pbg, p2pelite, parnuxi, pctorrent, peeratiko, peerjunkies, peersfm, pier720, piratadigital, piratbit, piratbitl, pirateiro, pixelcove, polishsource, pornbay, pornbits, pornforall, pornleech, pornolive, pornoslab, pornotor, pornotorrent, portugas, potuk, proaudiotorrents, proporno, prostylex, pterclub, ptfiles, pthome, ptmsg, ptsbao, pttime, punkshorror, puntotorrent, purovicio, pussytorrents, putao, puurhollands, pwtorrents, r3vwtf, racing4everyone, racingforme, rainbowtracker, rapidzona, redbits, redstartorrent, reelflix-api, resurrectthenet, rgfootball, rintor, rintornet, riperam, RockBox, romanianmetaltorrents, rptorrents, rus-media, rustorka, rutor, rutracker-ru, scenepalace, scenerush, sdbits, seedfile, selezen, sexxi, sexypics, shareisland-api, sharewood, showrss, siambit, skipthecommercials-api, sktorrent-org, sktorrent, slosoul, snowpt, solidtorrents, sosulki, soulvoice, soundpark, speedmasterhd, speedtorrentreloaded, spidertk, spiritofrevolution, sporthd, sportscult, springsunday, sugoimusic, sukebeinyaasi, superbits, swarmazon, tapochek, tasmanit, teamhd, teamos, tekno3d, tellytorrent-api, teracod, theaudioscene, theempire, thefallingangels, thegeeks, thehorrorcharnel, theleachzone, themixingbowl, theoccult, thepiratebay, theplace, thesceneplace, theshinning, theshow, thevault, tjupt, tlfbits, tokyotosho, torlock, torlook, toros, torrent-explosiv, torrent-pirat, torrent-turk, torrent9, torrent9clone, torrentbd, torrentby, torrentccf, torrentdb, torrentdownload, torrentdownloads, torrentfunk, torrentgalaxy, torrenthr, torrenting, torrentkitty, torrentland, torrentleech-pl, torrentleech, torrentlt, torrentmasters, torrentmax, torrentoyunindir, torrentparadise, torrentproject2, torrentqq, torrentsectorcrew, torrentseeds-api, torrentsir, torrentslocal, torrentsurf, torrentv, torrentview, torrentwhiz, torrentz2eu, totallykids, totheglory, totheglorycookie, trackeros-api, trancetraffic, trezzor, tribalmixes, trupornolabs, turkseed, turktorrent, tvchaosuk, tvroad, twilight, twilightszoom, u2, uhd-heaven, uhdbits, underverse, underversel, uniondht, unionfansub, uniongang, unlimitz, vizuk, vsthouse, vsttorrents, wdt, whiteangel, wihd, woot, xiteme, xbytesv2, xwtclassics, xwtorrents, xxxadulttorrent, xxxtor, xxxtorrents, ydypt, yggcookie, yggtorrent, yourbittorrent, yts, zamundanet, zelkaorg, zetorrents, zomb, zooqle, ztracker
01-29 16:32:46 Info Loaded 576 indexers in total
01-29 16:32:46 Info Adding aggregate indexer ('all' indexer) ...
01-29 16:32:46 Info Adding filter indexer ('type:public' indexer) ...
01-29 16:32:46 Info Adding filter indexer ('type:private' indexer) ...
01-29 16:32:46 Info Adding filter indexer ('type:semi-public' indexer) ...
01-29 16:32:47 Info Jackett startup finished in 2.436 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
```

### Description

IPT added cloudflare to the front end, seems to affect jackett too.

### Logged Error Messages

```text
01-29 16:34:32 Warn Request to IPTorrents failed with exception 'Challenge detected but FlareSolverr is not configured'. Retrying in 0.5s... (Attempt 1 of 2).

01-29 16:34:33 Warn Request to IPTorrents failed with exception 'Challenge detected but FlareSolverr is not configured'. Retrying in 1s... (Attempt 2 of 2).

01-29 16:34:33 Warn Request to IPTorrents failed with exception 'Challenge detected but FlareSolverr is not configured'. Retrying in 1s... (Attempt 2 of 2).

01-29 16:34:34 Error Jackett.Common.IndexerException: Exception (iptorrents): Challenge detected but FlareSolverr is not configured

---> FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured
at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 603
at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass12_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 580
```

**Comment by rtm2017** [comment]
I ran into this last night as well. You need to install and host a Flaresolverr instance and configure it at the bottom of the Jackett UI

![image](https://user-images.githubusercontent.com/59209856/151669201-601bfdf1-f611-40c1-aeff-7b1ec3bd740c.png)

https://github.com/FlareSolverr/FlareSolverr

**Comment by Wardy125** [comment]
@rtm2017 Thank you! Solved.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/12897#issuecomment-1025061929
