### ISSUE TITLE
[NewPCT] Download link not found using v0.20.494

### ISSUE THREAD

**Issue by egrueda** [Jackett/Jackett#12909]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-01 07:16:29.9780 Info Starting Jackett v0.20.494 
2022-02-01 07:16:32.0352 Info Environment version: 6.0.1 (/opt/jackett/) 
2022-02-01 07:16:32.0376 Info OS version: Unix 5.10.78.4 
2022-02-01 07:16:32.0405 Info Jackett variant: CoreLinuxArm32 
2022-02-01 07:16:32.0405 Info File /etc/issue: OSMC: Open Source Media Center \n \l 
2022-02-01 07:16:32.0405 Info Running in Docker: No 
2022-02-01 07:16:32.0454 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2022-02-01 07:16:32.0454 Info App config/log directory: /home/osmc/.config/Jackett 
2022-02-01 07:16:32.0486 Info Using proxy: Disabled 
2022-02-01 07:16:32.0486 Info Using FlareSolverr: No 
2022-02-01 07:16:32.0547 Info Using HTTP Client: HttpWebClient2 
2022-02-01 07:16:32.0827 Info Loading Native indexers ... 
2022-02-01 07:16:32.7902 Info Loaded 86 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, danishbytes, darmowetorenty, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, seals, secretcinema, sharewoodapi, shazbat, ShizaProject, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, xthor-api, zonaq, animetosho 
2022-02-01 07:16:32.8029 Info Loading Cardigann indexers from: /home/osmc/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/jackett/Definitions 
2022-02-01 07:16:39.3924 Info Loaded 494 Cardigann indexers: rintor, rapidzona, hdarea, girotorrent, pornleech, siambit, byrutor, cinemageddon, 24rolika, bitspyder, theaudioscene, showrss, racing4everyone, putao, mactorrentsdownload, anaschcc, twilightszoom, acidlounge, torrentoyunindir, fantastiko, estone, milkie, theempire, yggcookie, metaltracker, moviesdvdr, movietorrentz, lesaloon, majomparade, totheglorycookie, onejav, unlimitz, solidtorrents, kickasstorrents-ws, tjupt, animeworld-api, proporno, nbytez, limetorrentsclone, sugoimusic, backups, filelisting, tellytorrent-api, p2pbg, mypornclub, Bittorrentfiles, itorrent, torrentslocal, piratadigital, puntotorrent, rus-media, soundpark, bestcore, newstudio, bitcityreloaded, mediamaatjes, frozenlayer, torrentby, dimeadozen, crazyhd, speedmasterhd, pornoslab, pornbay, ilcorsaronero, noname-clubl, 0daykiev, 0magnet, arabafenice, turktorrent, abtorrents, newpct-me, rptorrents, cathoderaytube, elitetorrent-biz, linkomanija, hdchina, nethd, greekdiamond, thepiratebay, hdai, r3vwtf, pornotorrent, peersfm, arabp2p, darktracker, mteamtp, dragonworldreloaded, movietorrent, krazyzone, carpathians, trezzor, myspleen, slosoul, broadcity, oshenpt, lemonhd, pttime, empornium2fa, yourbittorrent, animeclipse, ettv, btschool, torrentseeds-api, libranet, torrentbd, mma-torrents, uhd-heaven, 1ptbar, underversel, pornolive, tribalmixes, ibit, woot, gay-torrents, carphunter, thegeeks, tasmanit, rutor, lat-team, oxtorrent, uniongang, torrentmasters, xxxadulttorrent, hawke-uno, torrentz2eu, bitded, sdbits, sporthd, cinemamovies, yts, cpasbienclone, theplace, coastalcrew, vsthouse, eniahd, portugas, torrentleech, puurhollands, crt2fa, bootytape, spidertk, hdbits, boxingtorrents, trupornolabs, teracod, bithumen, huntorrent, sosulki, booktracker, gtorrentpro, hdbitscom, bitru, trancetraffic, selezen, isohunt2, demonoid, resurrectthenet, ebooks-shares, netcosmo, acgrip, lastfiles, sukebeinyaasi, opensharing, torrent9, dmhy, themixingbowl, totallykids, exkinoray, blutopia-api, tekno3d, sportscult, vsttorrents, peerjunkies, thesceneplace, bibliotik, ptmsg, aussierules, torrentccf, parnuxi, 3dtorrents, karagarga, rustorka, p2pelite, mircrew, mousebits, vizuk, catorrent, ztracker, nipponsei, bwtorrents, hqsource, esharenet, mvgroupmain, pornotor, torrentkitty, torrentv, underverse, shareisland-api, kinonavse100, eztv, genesismovement, acrossthetasman, omgwtftrackr, nntt, bit-titan, pthome, hd4fans, torrentsurf, tvchaosuk, dxp, bitsexy, concertos, bt4g, moviesite, hdroute, opencd, trackeros-api, torrent-explosiv, borgzelle, swarmazon, hdolimpo-api, gay-torrentsorg, kickasstorrents-to, tokyotosho, romanianmetaltorrents, hdsky, bangumi-moe, torrentsir, polishsource, torrent9clone, newstudiol, sexxi, 1337x, hdme, hdc, proaudiotorrents, aniRena, finvip, comicat, pwtorrents, beyond-hd, losslessclub, torrenthr, pixelcove, learnbits, jptv, jpopsuki, torrentdb, hdspain, soulvoice, hdtorrentsit, ptsbao, torrenting, whiteangel, punkshorror, torrentview, 52pt, keepfriends, pctorrent, chdbits, bluebirdhd, twilight, indietorrents, baibako, kisssub, tapochek, torrentsectorcrew, beitai, thehorrorcharnel, btetree, gigatorrents, gamestorrents, theshinning, torrentproject2, aftershock, spiritofrevolution, muziekfabriek, legacyhd, hdcity, hellastz, cartoonchaos, nitro, prostylex, digitalcore, uniondht, torrentgalaxy, greekteam, byrbt, scenepalace, hdhome, deildu, microbit, theoccult, mteamtp2fa, torlock, totheglory, tvroad, hdturk, wihd, 4thd, hddolby, discfan, u2, gktorrent, xiteme, cpasbien, 7torrents, 2fast4you, linuxtracker, hdu, exttorrents, haidan, hdatmos, mnv, happyfappy, bitbazis, anilibria, dariustracker, sktorrent-org, torrent-turk, datascene-api, desitorrents-api, thevault, xbytesv2, thefallingangels, torrentwhiz, mixtapetorrent, torrent-pirat, glodls, rainbowtracker, btnext, cinematik, fanoin, acgsou, badasstorrents, bluesbrothers, concen, ehentai, torrentmax, racingforme, cryptichaven, zetorrents, bithorlo, scenerush, netlab, bitbr, alleenretail, mesevilag, hdtime, torrentland, audiobookbay, pornforall, snowpt, bigfangroup, redbits, speedtorrentreloaded, tlfbits, theleachzone, ydypt, superbits, pier720, arenabg, iv-torrents, legittorrents, ccfbits, skipthecommercials-api, asiancinema, rintornet, bitsearch, sexypics, hdcztorrent, turkseed, sktorrent, diablotorrent, sharewood, xxxtorrents, teamhd, hdzone, purovicio, falkonvisionteam, brsociety-api, RockBox, docspedia, riperam, mikan, film-paleis, crnaberza, classix, ilcorsaroverde, immortuos, brasiltracker, hdmonkey, kinozal, torlook, insanetracker, bitturk, magicheaven, madsrevolution, amigosshare, anisource, xxxtor, animelayer, limetorrents, torrentqq, extremetorrents, torrentfunk, ceskeforum, noname-club, kinorun, hdcenter, xwtorrents, unionfansub, rutracker-ru, audionews, internetarchive, freshmeat, megamixtracker, extremebits, teamos, pirateiro, redstartorrent, haitang, gaytorrentru, ebookparadijs, potuk, hamsterstudio, zomb, btsow, ttsweb, leech24, torrentdownloads, torrentlt, piratbit, theshow, newretro, fouducinema, lepornoinfo, piratbitl, btdigg, femdomcult, extratorrent-st, marinetracker, hdonly, extremlymtorrents, casatorrent, magico, pornbits, springsunday, yggtorrent, gfxpeers, learnflakes, xwtclassics, idope, funkytorrents, pterclub, fantasticheaven, empornium, ptfiles, generationfree, peeratiko, torrentleech-pl, toros, dark-shadow, megapeer, mononokebt, torrentdownload, ilcorsaroblu, anime-free, datatalli, crazyspirits, hdhouse, zooqle, uhdbits, pussytorrents, chilebt, aidoruonline, zelkaorg, 3changtrai, seedfile, zamundanet, reelflix-api, finelite, firebit, ourbits, divteam, nyaasi, wdt, nbtorrents, mvgroupforum, hdforever, rgfootball, aither-api, beyond-hd-oneurl, torrentparadise 
2022-02-01 07:16:39.3924 Info Loaded 580 indexers in total 
2022-02-01 07:16:39.3974 Info Adding aggregate indexer ('all' indexer) ... 
2022-02-01 07:16:39.4246 Info Adding filter indexer ('type:public' indexer) ... 
2022-02-01 07:16:39.4246 Info Adding filter indexer ('type:private' indexer) ... 
2022-02-01 07:16:39.4246 Info Adding filter indexer ('type:semi-public' indexer) ... 
2022-02-01 07:16:39.4442 Info Deleting JackettUpdate temp files from /tmp/JackettUpdate-v0.20.494-637792965660365427 
2022-02-01 07:16:40.3442 Info Jackett startup finished in 11.503 s
```

### Description

After last commit #43f85ad it does find episodes (fixed #12889), but fails to download the torrent link.
Attached log message

### Logged Error Messages

```text
System.Exception: Download link not found!
   at Jackett.Common.Indexers.NewPCT.Download(Uri linkParam) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 195
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56
```

**Comment by garfield69** [comment]
wonder if we need to add referer to the dl too?

**Comment by egrueda** [comment]
That's it, but in a different domain 🙄 
Download page links to domain atomtt.com
Example: https://atomtt.com/t_download/167358_-1643693045-SurrealEstate---Temporada-1--HDTV-720p-AC3-5-1/
That's the request you need to add referer, but this time using that other domain atomtt.com

That page will generate a download link like this:
https://atomtt.com/download-link/167358_-1643693045-SurrealEstate---Temporada-1--HDTV-720p-AC3-5-1/dom-t/atomixhq.top
(referer atomtt.com)

And that link will take you to:
https://atomixhq.top/t_download/167358_-1643693045-SurrealEstate---Temporada-1--HDTV-720p-AC3-5-1.torrent
Which is the real torrent file (no referer needed)

Oh man, what a nightmare xD

**Comment by garfield69** [comment]
v0.20.497

**Comment by gamingtech-es** [comment]
I am using jakett version v0.20.504,
And I have the problem that the torrent does not download me.
I leave the error code that reports me.

[log.txt](https://github.com/Jackett/Jackett/files/8002729/log.txt)
