### ISSUE TITLE
[1337x] No space left on device : '/config/Jackett/Indexers' (Config)

### ISSUE THREAD

**Issue by JuhaFIN1** [Jackett/Jackett#12913]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Proxmox - Ubuntu 20.14 LTS - Docker - Portainer - Jacket from "https://raw.githubusercontent.com/Qballjos/portainer_templates/master/Template/template.json"


2022-02-02 17:02:34	Error	
Error writing config file /config/Jackett/ServerConfig.json
System.IO.IOException: No space left on device : '/config/Jackett/ServerConfig.json'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
   at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.File.WriteAllText(String path, String contents)
   at Jackett.Common.Services.ConfigurationService.SaveConfig[T](T config) in /home/vsts/work/1/s/src/Jackett.Common/Services/ConfigurationService.cs:line 174
2022-02-02 17:02:34	Error	
Error writing config file /config/Jackett/ServerConfig.json
System.IO.IOException: No space left on device : '/config/Jackett/ServerConfig.json'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
   at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.File.WriteAllText(String path, String contents)
   at Jackett.Common.Services.ConfigurationService.SaveConfig[T](T config) in /home/vsts/work/1/s/src/Jackett.Common/Services/ConfigurationService.cs:line 174
2022-02-02 17:02:34	Info	
Starting Jackett v0.20.497
```

### Description

Just installed and started to config. No Space.

### Logged Error Messages

```text
2022-02-02 17:02:34	Error	
Error writing config file /config/Jackett/ServerConfig.json
System.IO.IOException: No space left on device : '/config/Jackett/ServerConfig.json'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
   at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.File.WriteAllText(String path, String contents)
   at Jackett.Common.Services.ConfigurationService.SaveConfig[T](T config) in /home/vsts/work/1/s/src/Jackett.Common/Services/ConfigurationService.cs:line 174
2022-02-02 17:02:34	Error	
Error writing config file /config/Jackett/ServerConfig.json
System.IO.IOException: No space left on device : '/config/Jackett/ServerConfig.json'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
   at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.File.WriteAllText(String path, String contents)
   at Jackett.Common.Services.ConfigurationService.SaveConfig[T](T config) in /home/vsts/work/1/s/src/Jackett.Common/Services/ConfigurationService.cs:line 174
2022-02-02 17:02:34	Info	
Starting Jackett v0.20.497
```

**Comment by ilike2burnthing** [comment]
Sounds like a permissions issue or bad volume mapping, especially if you're just using the default values provided by your linked template. If that's the case, edit those settings in Portainer and redeploy the Jackett container.
