### ISSUE TITLE
[iptorrents] Exception (iptorrents): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by taronyx72** [Jackett/Jackett#12932]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-09 00:01:16	Info	
Loading Native indexers ...
2022-02-09 00:01:16	Info	
Using HTTP Client: HttpWebClient2
2022-02-09 00:01:16	Info	
Using FlareSolverr: http://127.0.0.1:8191
2022-02-09 00:01:16	Info	
Using proxy: Disabled
2022-02-09 00:01:16	Info	
App config/log directory: C:\ProgramData\Jackett
2022-02-09 00:01:16	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-02-09 00:01:16	Info	
Running in Docker: No
2022-02-09 00:01:16	Info	
Jackett variant: CoreWindows
2022-02-09 00:01:16	Info	
OS version: Microsoft Windows NT 10.0.19043.0 (64bit OS)
2022-02-09 00:01:16	Info	
Environment version: 6.0.1 (C:\ProgramData\Jackett\)
2022-02-09 00:01:13	Info	
Starting Jackett v0.20.529
```

### Description

open jackett web ui and test iptorrents tracker

### Logged Error Messages

```text
Error while parsing Cardigann definition C:\ProgramData\Jackett\Definitions\btworld.yml
YamlDotNet.Core.YamlException: (Line: 2, Col: 3, Idx: 6) - (Line: 2, Col: 3, Idx: 6): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'site' not found on type 'Jackett.Common.Models.IndexerDefinition'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass16_0.<InitCardigannIndexers>b__3(FileInfo file) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 170
```

**Comment by garfield69** [comment]
confused. are you reporting an issue with iptorrents or with the error you are showing in the log snippet you provided for btworld?

**Comment by garfield69** [comment]
Did you try fetching a new cookie from the sitelink that you have specified in the iptorrent config?
Pehaps https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work may help you work out what needs be done.
Otherwise please provide an enhanced log for iptorrent see https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by ilike2burnthing** [comment]
@taronyx72 please follow and respond to the rest of the instructions in https://github.com/Jackett/Jackett/issues/12932#issuecomment-1033427012 (note that if you're going to attach enhanced logs then you'll need to do so on GitHub, not via email).

**Comment by ilike2burnthing** [comment]
@Popupkiller configure FlareSolverr - https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured

**Comment by zyzzma** [comment]
Having similar problems with IPT on Jackett

**Comment by ilike2burnthing** [comment]
Look at the links provided above. If you still have problems, open a new issue and provide the information requested.

**Comment by e2zippo** [comment]
Same issue here, so something has likely changed on Iptorrents. Reading about Flaresolverr, but I'm not sure I follow. Could it be that IPtorrents recently have changed so that they are using cloudflare protection now? And if they are, is the only solution to install Flaresolverr?

**Comment by ilike2burnthing** [comment]
They're using Cloudflare DDoS protection. If you want to keep using that site link, you'll need FlareSolverr. Otherwise, you can try reconfiguring the indexer to use a different link.

**Comment by nucshuco** [comment]
I Can't get Jackett to work with https://nemo.iptorrents.com/ and new cookie. But https://nemo.iptorrents.com/ and new cookie works fine on Medusa. :(

**Comment by ilike2burnthing** [comment]
@nucshuco https://github.com/Jackett/Jackett/issues/12932#issuecomment-1034140964

**Comment by iokaravas** [comment]
IPTorrents added Cloudflare protection so you need to install flaresolverr and configure it. More info here: https://github.com/Jackett/Jackett#configuring-flaresolverr
