### ISSUE TITLE
[shareisland] error searching

### ISSUE THREAD

**Issue by rafuz** [Jackett/Jackett#12936]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2	
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads	
Running in Docker: Yes (image build: unknown)	
File /etc/issue: Ubuntu 20.04.3 LTS \n \l	
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.15.0.167 (64bit OS) (64bit process)
Environment version: 6.0.2 (/app/)
Jackett Data will be stored in: /config
Starting Jackett v0.20.539
```

### Description

This morning the website has been updated and now the search does not work anymore.

### Logged Error Messages

```text
2022-02-10 17:26:14	Info	
Manual search in shareisland-api for star wars => Found 0 releases
2022-02-10 17:26:14	Error	
Jackett.Common.IndexerException: Exception (shareisland-api): Error while parsing field=downloadvolumefactor, selector=freeleech, value=0%: Input string was not in a correct format.
 ---> System.Exception: Error while parsing field=downloadvolumefactor, selector=freeleech, value=0%: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1457
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 768
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 228
```

**Comment by garfield69** [comment]
yup, they upgraded to unit3d 6.0.0 and we need to update the indexer to handle the new API

**Comment by garfield69** [comment]
v0.20.546
