### ISSUE TITLE
[cpasbienclone] Test search in cpasbien clone => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by ZorgBtw** [Jackett/Jackett#12947]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [x] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Test search in cpasbien clone => Found no results while trying to browse this tracker
```

### Description

When I try to only test the "cpasbien clone" indexer, I got this error logged.
I can ping cpasbien.gg with the computer where Jackett is installed too

### Logged Error Messages

```text
System.Exception: Test search in cpasbien clone => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 310
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Your environment section is incorrect:
> Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste replacing the example below with the last 10 Info lines at the bottom of the log.

Please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ZorgBtw** [comment]
```2022-02-12 13:36:14.2119 Info Starting Jackett v0.20.555 
2022-02-12 13:36:15.2274 Info Environment version: 6.0.2 (/opt/jackett/Jackett/) 
2022-02-12 13:36:15.2293 Info OS version: Unix 3.10.0.1160 (64bit OS) (64bit process) 
2022-02-12 13:36:15.2304 Info Jackett variant: CoreLinuxAmdx64 
2022-02-12 13:36:15.2304 Info File /etc/issue: Ubuntu 20.04.3 LTS \n \l 
2022-02-12 13:36:15.2309 Info Running in Docker: No 
2022-02-12 13:36:15.2321 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2022-02-12 13:36:15.2321 Info App config/log directory: /root/.config/Jackett 
2022-02-12 13:36:15.2332 Info Using proxy: Disabled 
2022-02-12 13:36:15.2332 Info Using FlareSolverr: No 
2022-02-12 13:36:15.2341 Error Jackett is running with root privileges. You should run Jackett as an unprivileged user. 
2022-02-12 13:36:15.2363 Info Using HTTP Client: HttpWebClient2 
2022-02-12 13:36:15.2503 Info Loading Native indexers ... 
2022-02-12 13:36:15.4613 Info Loaded 86 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, danishbytes, darmowetorenty, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, seals, secretcinema, sharewoodapi, shazbat, ShizaProject, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, xthor-api, zonaq, animetosho 
2022-02-12 13:36:15.4717 Info Loading Cardigann indexers from: /root/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/jackett/Jackett/Definitions 
2022-02-12 13:36:18.1826 Info Loaded 490 Cardigann indexers: greekdiamond, nitro, totheglory, yts, kinonavse100, chilebt, carphunter, ebooks-shares, byrbt, happyfappy, btetree, mesevilag, vsttorrents, gaytorrentru, xwtorrents, polishsource, concertos, alleenretail, dark-shadow, uhd-heaven, audionews, teamos, torrentby, showrss, xiteme, mnv, ilcorsaroblu, exttorrents, torrentseeds-api, bitru, megamixtracker, 52pt, torrentmax, underversel, demonoid, backups, tjupt, proporno, pterclub, piratbitl, redstartorrent, linkomanija, tasmanit, opencd, hdforever, baibako, rintor, exkinoray, dimeadozen, audiobookbay, crazyspirits, noname-clubl, yggtorrent, sugoimusic, huntorrent, 0magnet, sexypics, brasiltracker, springsunday, finelite, bitcityreloaded, bigfangroup, iv-torrents, learnflakes, 4thd, movietorrentz, torrent9, theshinning, uhdbits, bluebirdhd, pixelcove, torrentsurf, kinozal, turktorrent, classix, teracod, gfxpeers, frozenlayer, aftershock, bestcore, hdu, estone, pornbay, yggcookie, rapidzona, torrentleech-pl, woot, rutracker-ru, oxtorrent, 0daykiev, peerjunkies, anilibria, metaltracker, peersfm, esharenet, torrentgalaxy, bitspyder, borgzelle, torrentwhiz, torrentbd, swarmazon, torrentv, netlab, btsow, newpct-me, sportscult, sukebeinyaasi, hdbits, acrossthetasman, skipthecommercials-api, pornotor, thesceneplace, hdspain, hdcenter, torlook, movietorrent, uniongang, genesismovement, crnaberza, spidertk, piratbit, xbytesv2, hdmonkey, brsociety-api, torrenting, cinemageddon, filelisting, pctorrent, mypornclub, elitetorrent-biz, torrent-explosiv, pornforall, film-paleis, wihd, pornoslab, hawke-uno, theaudioscene, asiancinema, newretro, bluesbrothers, fanoin, wdt, fantasticheaven, hdme, beyond-hd-oneurl, p2pbg, lepornoinfo, toros, pornleech, yourbittorrent, racingforme, trezzor, ztracker, torrentqq, ptsbao, beitai, chdbits, hdcztorrent, cpasbien, turkseed, p2pelite, 1ptbar, hdchina, beyond-hd, boxingtorrents, opensharing, teamhd, reelflix-api, hdhome, bitbr, deildu, hdbitscom, dxp, bootytape, torrentslocal, sporthd, piratadigital, internetarchive, itorrent, btdigg, animeclipse, theplace, torrentleech, bitded, bitsearch, torrentsir, abtorrents, moviesdvdr, bit-titan, aither-api, anime-free, unlimitz, newstudiol, mvgroupmain, majomparade, pwtorrents, themixingbowl, docspedia, hdatmos, 3dtorrents, ccfbits, eniahd, haidan, nbtorrents, arenabg, jpopsuki, ceskeforum, acgsou, bithumen, omgwtftrackr, fouducinema, noname-club, whiteangel, cinemamovies, torrent-turk, concen, finvip, 24rolika, bitturk, torrentdownloads, puurhollands, karagarga, torlock, hdonly, lat-team-api, losslessclub, carpathians, racing4everyone, sexxi, thevault, kickasstorrents-ws, linuxtracker, arabafenice, scenepalace, hdtime, underverse, punkshorror, dragonworldreloaded, r3vwtf, hdarea, ptfiles, 3changtrai, zetorrents, uniondht, limetorrents, diablotorrent, rutor, cinematik, ebookparadijs, girotorrent, madsrevolution, hdolimpo-api, tribalmixes, soulvoice, twilight, booktracker, aidoruonline, sktorrent, pussytorrents, shareisland-api, seedfile, hdsky, badasstorrents, dariustracker, nntt, generationfree, byrutor, twilightszoom, torrentmasters, hdcity, blutopia-api, torrentland, moviesite, hdc, torrent9clone, freshmeat, torrentoyunindir, funkytorrents, fantastiko, tapochek, hdzone, torrentkitty, speedtorrentreloaded, superbits, scenerush, mactorrentsdownload, krazyzone, bt4g, tellytorrent-api, zamundanet, 1337x, casatorrent, tvchaosuk, gktorrent, trackeros-api, hqsource, divteam, animelayer, hddolby, crazyhd, immortuos, riperam, extremlymtorrents, mma-torrents, microbit, gamestorrents, peeratiko, darktracker, xwtclassics, idope, extremetorrents, pornbits, mousebits, pornotorrent, coastalcrew, lesaloon, mixtapetorrent, torrentlt, greekteam, desitorrents-api, gigatorrents, pthome, bwtorrents, ibit, torrentfunk, acidlounge, romanianmetaltorrents, discfan, purovicio, torrent-pirat, sosulki, spiritofrevolution, resurrectthenet, hellastz, cathoderaytube, xxxtorrents, nipponsei, sktorrent-org, ourbits, vsthouse, theoccult, zelkaorg, ydypt, torrentccf, newstudio, RockBox, sharewood, thepiratebay, netcosmo, dmhy, datatalli, gtorrentpro, firebit, mircrew, extremebits, muziekfabriek, hdhouse, torrentdb, onejav, anisource, torrentview, cartoonchaos, 2fast4you, broadcity, trupornolabs, turktracker, rintornet, thegeeks, btnext, cpasbienclone, amigosshare, torrentz2eu, rptorrents, ptmsg, zomb, limetorrentsclone, slosoul, jptv, torrentproject2, ehentai, insanetracker, u2, kinorun, soundpark, femdomcult, siambit, theleachzone, magico, potuk, mvgroupforum, rainbowtracker, bitsexy, myspleen, rgfootball, arabp2p, digitalcore, pttime, bithorlo, speedmasterhd, theshow, bibliotik, torrentsectorcrew, gay-torrentsorg, rus-media, keepfriends, tekno3d, torrenthr, totallykids, aniRena, hdai, pier720, torrentdownload, leech24, Bittorrentfiles, catorrent, kisssub, empornium, cryptichaven, xbit, tokyotosho, haitang, anaschcc, thefallingangels, puntotorrent, xxxadulttorrent, totheglorycookie, hdturk, pornolive, sdbits, nethd, portugas, acgrip, marinetracker, mononokebt, trancetraffic, empornium2fa, aussierules, redbits-api, mteamtp2fa, xxxtor, selezen, torrentparadise, indietorrents, lastfiles, eztv, kickasstorrents-to, isohunt2, hdtorrentsit, mteamtp, hd4fans, libranet, thehorrorcharnel, milkie, lemonhd, extratorrent-st, animeworld-api, snowpt, tlfbits, btschool, oshenpt, glodls, magicheaven, prostylex, legittorrents, bitbazis, nyaasi, bangumi-moe, zooqle, hamsterstudio, solidtorrents, crt2fa, vizuk, datascene-api, megapeer, hdroute, parnuxi, unionfansub, comicat, theempire, tvroad, ilcorsaronero, rustorka, falkonvisionteam, mediamaatjes, mikan, learnbits, ilcorsaroverde, proaudiotorrents, putao, gay-torrents 
2022-02-12 13:36:18.1880 Info Loaded 576 indexers in total 
2022-02-12 13:36:18.1897 Info Adding aggregate indexer ('all' indexer) ... 
2022-02-12 13:36:18.2055 Info Adding filter indexer ('type:public' indexer) ... 
2022-02-12 13:36:18.2055 Info Adding filter indexer ('type:private' indexer) ... 
2022-02-12 13:36:18.2073 Info Adding filter indexer ('type:semi-public' indexer) ... 
2022-02-12 13:36:18.4821 Warn No XML encryptor configured. Key {18261015-1d02-40f0-9549-3ac66e95189a} may be persisted to storage in unencrypted form. 
2022-02-12 13:36:18.4821 Warn No XML encryptor configured. Key {18261015-1d02-40f0-9549-3ac66e95189a} may be persisted to storage in unencrypted form. 
2022-02-12 13:36:18.5713 Info Jackett startup finished in 5.676 s 
2022-02-12 13:36:23.9495 Info Jackett stopped 
```
there you go, that's all I got from the log.txt file after doing the steps

**Comment by garfield69** [comment]
the indexer is working for me which suggest the problem is at your end.
please provide an enhanced log, hopefully the debug and html included will provide a clue to your issue.
See  https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ZorgBtw** [comment]
I managed to get these logs too
```Feb 12 19:26:07 <domain> systemd-journald[75]: Suppressed 25113 messages from jackett.service
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Connection id "0HMFEBA7QESU1" accepted.
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Connection id "0HMFEBA7QESU1" started.
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Info Request starting HTTP/1.1 POST http://<vps ip>/api/v2.0/indexers/cpasbienclone/test - 0
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Request is continuing in applying rules. Current url is http://<vps ip>/api/v2.0/indexers/cpasbienclone/test
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Request is continuing in applying rules. Current url is http://<vps ip>/api/v2.0/indexers/cpasbienclone/test
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Request is continuing in applying rules. Current url is http://<vps ip>/api/v2.0/indexers/cpasbienclone/test
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug POST requests are not supported
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug AuthenticationScheme: Cookies was successfully authenticated.
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/cpasbienclone/test'
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/cpasbienclone/test'
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Info Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Execution plan of resource filters (in the following order): None
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Execution plan of exception filters (in the following order): None
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Execution plan of result filters (in the following order): None
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Authorization was successful.
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug CACHE IsCacheEnabled => false
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.cpasbien.gg/home/)
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug WebClient(HttpWebClient2): Returning OK => 0 bytes
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Info Test search in cpasbien clone => Found 0 releases
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 236.0597ms
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Error System.Exception: Test search in cpasbien clone => Found no results while trying to browse this tracker
Feb 12 19:26:07 <domain> jackett[1166160]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 310
Feb 12 19:26:07 <domain> jackett[1166160]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 System.Exception: Test search in cpasbien clone => Found no results while trying to browse this tracker
Feb 12 19:26:07 <domain> jackett[1166160]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 310
Feb 12 19:26:07 <domain> jackett[1166160]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 12 19:26:07 <domain> jackett[1166160]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug The response will be compressed with 'gzip'.
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Debug Connection id "0HMFEBA7QESU1" completed keep alive response.
Feb 12 19:26:07 <domain> jackett[1166160]: 02-12 19:26:07 Info Request finished HTTP/1.1 POST http://<vps ip>/api/v2.0/indexers/cpasbienclone/test - 0 - 500 - application/json 263.5772ms
```
moreover, when I try to do a `wget https://www.cpasbien.gg/home/`, it returns me an empty index.html, which I think it's not normal

**Comment by garfield69** [comment]
you are correct. 
https://www.cpasbien.gg/home/ should return the home page of the site, at it does for me.
So this is not an issue with Jackett but likely something interfering with your access to the site.
Unusual for a ISP block, or router firewall or anti-malware app to return 0 bytes, they usually don't return a http 200 with a zero byte result.
@ilike2burnthing  any thought on what might be going on here and how to proceed?
