### ISSUE TITLE
[divxtotal] generating ArgumentOutOfRangeException for series data

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12946]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

a TEST of the divxtotal indexer generates log errors for series data
since the indexer is public and C# you can better debug this if you are using an IDE SDK

### Logged Error Messages

```text
CardigannIndexer (divxtotal): Error while parsing row '
<tr>
	<td>
		<a style="color: #f42b10 !important;text-transform: uppercase;font-weight: 700;" href="https://www.divxtotal.top/series/hacks/" title="Hacks">Hacks</a>
	</td>
	<td>
		<a href="/series/" title="Series">Serie</a>
	</td>
	<td>25-01-2022</td>
	<td>N/A</td>
</tr>':

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)
   at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)
   at Jackett.Common.Indexers.DivxTotal.ParseSeriesReleaseAsync(TorznabQuery query, String detailsStr, String cat, DateTime publishDate) in D:\a\1\s\src\Jackett.Common\Indexers\DivxTotal.cs:line 296
   at Jackett.Common.Indexers.DivxTotal.ParseReleasesAsync(IParentNode row, TorznabQuery query, Boolean matchWords) in D:\a\1\s\src\Jackett.Common\Indexers\DivxTotal.cs:line 269
   at Jackett.Common.Indexers.DivxTotal.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\DivxTotal.cs:line 157
```

**Comment by mikeoscar2006** [comment]
Can't reproduce this. Adding the divxtotal indexer and testing then works fine too for me.
Note: I used the .pm domain instead of .nl which is the default one configured in the indexer.

**Comment by garfield69** [comment]
*.pm is running clean too.
Was using *.top which generates the error. Not entirely sure how I go onto that domain %-/
