### ISSUE TITLE
[Torrent Leech] Unable to add tracker due to 100s timeout

### ISSUE THREAD

**Issue by pazwicker** [Jackett/Jackett#12962]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-17 10:42:59	Info	Using HTTP Client: HttpWebClient2
2022-02-17 10:42:59	Info	Using FlareSolverr: No
2022-02-17 10:42:59	Info	Using proxy: Disabled
2022-02-17 10:42:59	Info	App config/log directory: /home/pazwicker/.config/Jackett
2022-02-17 10:42:59	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-02-17 10:42:59	Info	Running in Docker: No
2022-02-17 10:42:59	Info	File /etc/issue: Ubuntu 20.04.3 LTS \n \l
2022-02-17 10:42:59	Info	Jackett variant: CoreLinuxAmdx64
2022-02-17 10:42:59	Info	OS version: Unix 5.4.0.99 (64bit OS) (64bit process)
2022-02-17 10:42:59	Info	Environment version: 6.0.2 (/home/pazwicker/Downloads/Jackett/)
2022-02-17 10:42:58	Info	Starting Jackett v0.20.574
```

### Description

Torrent Leech times out when attempting to add or edit existing configuration.

I have had Torrent Leech configured for several years with Jackett. Recently the connection to the indexer stopped working. I deleted the Jackett configurating and tried to re-add, but am hit with an error saying the request timed out after 100 seconds.

### Logged Error Messages

```text
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 621
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 548
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 972
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by pazwicker** [comment]
@garfield69 thanks for the help. Pasting my enhanced log details below. Still look like this could be ISP or firewall? Does it mean anything that I can access torrent leech in my browser just fine?

```2022-02-18 20:29:30.3098 Debug WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://www.torrentleech.org/user/account/login/ PostData: {username=uname, password=password>
2022-02-18 20:29:49.5062 Debug Connection id "0HMFJ30HN1L53" disconnecting.
2022-02-18 20:29:49.5062 Debug Connection id "0HMFJ30HN1L55" disconnecting.
2022-02-18 20:29:49.5062 Debug Connection id "0HMFJ30HN1L53" stopped.
2022-02-18 20:29:49.5062 Debug Connection id "0HMFJ30HN1L55" stopped.
2022-02-18 20:29:49.5062 Debug Connection id "0HMFJ30HN1L53" sending FIN because: "The Socket transport's send loop completed gracefully."
2022-02-18 20:29:49.5062 Debug Connection id "0HMFJ30HN1L55" sending FIN because: "The Socket transport's send loop completed gracefully."
2022-02-18 20:29:55.5074 Debug Connection id "0HMFJ30HN1L56" disconnecting.
2022-02-18 20:29:55.5074 Debug Connection id "0HMFJ30HN1L52" disconnecting.
2022-02-18 20:29:55.5074 Debug Connection id "0HMFJ30HN1L56" stopped.
2022-02-18 20:29:55.5074 Debug Connection id "0HMFJ30HN1L52" stopped.
2022-02-18 20:29:55.5074 Debug Connection id "0HMFJ30HN1L56" sending FIN because: "The Socket transport's send loop completed gracefully."
2022-02-18 20:29:55.5074 Debug Connection id "0HMFJ30HN1L52" sending FIN because: "The Socket transport's send loop completed gracefully."
2022-02-18 20:29:56.5076 Debug Connection id "0HMFJ30HN1L54" disconnecting.
2022-02-18 20:29:56.5076 Debug Connection id "0HMFJ30HN1L54" stopped.
2022-02-18 20:29:56.5076 Debug Connection id "0HMFJ30HN1L54" sending FIN because: "The Socket transport's send loop completed gracefully."
2022-02-18 20:31:10.3322 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 100083.1607ms
2022-02-18 20:31:10.3322 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2022-02-18 20:31:10.3322 Error System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.```

**Comment by pazwicker** [comment]
Hey @garfield69, I can access the tracker via a browser on the machine that's also running Jackett. I'm using 1.1.1.1 and I don't see any ISP restrictions (although I did just switch to comcast which may have correlated with the tracker breaking, but my system wasn't fully operational prior to the switch to I can't be sure). 

I can explore a VPN or proxy service related to bullet 2 in the link you sent, but in the meantime is there anything in my enhanced logs that could point to a jackett-side issue?

If it helps, TPB also doesn't work but IP Torrents does.

**Comment by garfield69** [comment]
Please open a terminal and post here the results of
`curl -vvv https://www.torrentleech.org/`
and
`openssl s_client -connect www.torrentleech.org:443`

remember to post your results as a markup code block to avoid github treating your post as spam and potentially blocking your account
thanks.

**Comment by pazwicker** [comment]
First:

`*   Trying 2606:4700:10::6814:c516:443...
* TCP_NODELAY set
*   Trying 104.20.197.22:443...
* TCP_NODELAY set
* Connected to www.torrentleech.org (104.20.197.22) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jul 15 00:00:00 2021 GMT
*  expire date: Jul 14 23:59:59 2022 GMT
*  subjectAltName: host "www.torrentleech.org" matched cert's "*.torrentleech.org"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5568a64bbc90)
> GET / HTTP/2
> Host: www.torrentleech.org
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Sun, 20 Feb 2022 04:10:25 GMT
< content-type: text/html; charset=UTF-8
< set-cookie: PHPSESSID=ukvomivvrs6kp8sdblrs1httvc; path=/; secure
< set-cookie: PHPSESSID=gni76es73t3tfm6lh88l6lhckk; path=/; secure
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< vary: Accept-Encoding
< strict-transport-security: max-age=15768000; includeSubdomains; preload
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 6e04e2962adb0baf-DFW
< 
<!DOCTYPE html>
<html lang="en" class="html-lights-off">
<head>
    <title>Login :: TorrentLeech.org</title>    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="TorrentLeech">
    <meta name="keywords" content="torrent">
<link href="/common.59cde2cd44a340fa31fe389b153b0e3d.css" rel="stylesheet"><link href="/access.1e4a0f325e434838cd56ed065f87c45e.css" rel="stylesheet"></head>

<body class="tl-lights-off">

<div id="site-wrapper">
    <div id="site-canvas">

        <div class="navbar navbar-default tl">
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <a class="navbar-brand" href="/"></a>
                    </li>
                </ul>
                <ul class="guest-chat nav navbar-nav navbar-right">
                    <li>
                        <a href="/user/chat/guest" title="Guest Chat">
                            <i class="fa fa-comments-o large-fonts"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <a class="toggle-news" title="Latest News" href="#"><i class="fa fa-newspaper-o large-fonts"></i></a>

        <div class="container access-page">
            <div class="row">
                <div class="login-container col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
                    <section class="login">
                        <div class="text-center">
                            <h2 class="title">Login</h2>
                        </div>
                                                <form name="login-form" method="post" action="/user/account/login/">
                            <input type="text" class="form-control" name="username" value="" placeholder="Username">
                            <input type="password" class="form-control" name="password" placeholder="Password">
                            
                            <div class="form-group text-center">
                                <button type="submit" class="btn tl-btn btn-primary action">
                                    Log in
                                </button>
                            </div>
                            <div class="form-group text-center mt-20">
                                <a class="btn tl-btn btn-primary" href="/user/account/promoreg" >SIGN UP PROMO</a>
                            </div>
                            <div class="text-center">
                                <a href="/user/account/lostpassword" >Lost Password</a>
                            </div>
                            <div class="text-center">
                                <a href="/user/account/signup">Signup With Invite</a>
                            </div>
                        </form>
                    </section>
                </div>
            </div>
            <div class="container seedit4me_image">
                <div class="login-banner col-xs-12 col-sm-6 col-md-4 col-sm-offset-1 col-md-offset-2">
                    <a href="https://billing.seedit4.me/aff.php?aff=4/" target="_blank"><img src="/images/seedit4me.png" title="Seedit4.me banner" alt="Seedit4.me banner"></a>
                </div>
            </div>
        </div>



        <div class="footer-login">

            <div class="footer-inner-login">
                <h5 class="footer-title">Visit Our Friends</h5>
                <ul class="list-inline list-pipe">
                    <li>
                        <a href="https://truevpnreviews.net/" target="_blank"><img src="/images/truevpnreviews.png" title="True VPN Reviews" alt="True VPN Reviews" width="16" height="16">  TrueVPNReviews.net</a>
                    </li>
                    <li>
                        <a href="https://billing.seedit4.me/aff.php?aff=4/" target="_blank"><img src="/images/seedit4me-icon.png" title="Seedit4.me" alt="Seedit4.me" width="16" height="16">Seedit4.me</a>
                    </li>
                    <li>
                        <a href="https://prepaidcardreviews.net/" target="_blank"><img src="/images/prepaidcardreviews.png" title="Prepaid Card Reviews" alt="Prepaid Card Reviews" width="16" height="16">  PrepaidCardReviews.net</a>
                    </li>
                </ul>
            </div>
        </div>

        <div id="site-news">
            <div class="site-news-inner">
                <h3 class="site-news-header text-center">
                    Latest News
                </h3>

                <ul class="mt-30 list-unstyled">
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The XMAS2021 invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>January 16th 2022</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>XMAS2021 invitation code</h4>
                            <p class="body">
                                <p>Christmas is near... Best way to celebrate it..? What about a Christmas invite giveaway??</p><p><br></p><p>Use invite code XMAS2021 in the sign up form <a href="https://www.torrentleech.org/user/account/signup" target="_blank">https://www.torrentleech.org/user/account/signup</a> and enjoy your new account! As cherry on top, you'll find your account with 15GB upload credit to help you start your epic journey! HURRY UP! For the first 10k people only!</p><p><br></p><p>Merry Christmas and Happy holidays!!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>December 4th 2021</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>Get a Seedbox - Get an invite promo!</h4>
                            <p class="body">
                                <p>We have opened signups for a limited time, with an awesome promo! Get a SeedBox from Seedit4.me, and in return enjoy an invite with 1 week of VIP on top!</p><p><br></p><p>Head to sign up promo page <a href="https://www.torrentleech.org/user/account/promoreg" target="_blank">here</a> ,  to learn more!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>April 28th 2021</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The LETMEIN invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>January 15th 2021</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>LETMEIN invitation code!</h4>
                            <p class="body">
                                <p><em>Remember remember the 5th of November...</em></p><p><br></p><p>Oh wait, its 4th! </p><p><br></p><p>Use invite code LETMEIN in the sign up form <a href="http://www.torrentleech.org/user/account/signup" target="_blank">http://www.torrentleech.org/user/account/signup</a> and enjoy your new account! As cherry on top, you'll find your account with 15GB upload credit to help you start your epic journey!</p><p><br></p><p>Spread the love, not Covid! ^__^</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>November 4th 2020</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The STAYHOME invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>June 1st 2020</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>STAYHOME Invitation Code</h4>
                            <p class="body">
                                <p>Lock downs, emergency outbreaks,everyone keeps saying ”stay home”. Ok you say, stay home and do what?? Worry not, TorrentLeech has the cure! </p><p>Use invite code STAYHOME in the sign up form <a href="http://www.torrentleech.org/user/account/signup" target="_blank">http://www.torrentleech.org/user/account/signup</a> and enjoy your new account! As cherry on top, you'll find your account with 15GB upload credit to help you start your epic journey!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>March 12th 2020</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The TLFREELEECH invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>January 31st 2020</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>TLFREELEECH Invitation code!!!</h4>
                            <p class="body">
                                <p>2019 comes to an end... Santa came early this year though! And has tons of surprizes! One we will tell you now :</p><p><br></p><p>Use invite code TLFREELEECH in the sign up form <a href="http://www.torrentleech.org/user/account/signup" target="_blank">http://www.torrentleech.org/user/account/signup</a> and enjoy your new account! As cherry on top, you'll find your account with 15GB upload credit to help you start your epic journey!</p><p><br></p><p>For the second one, you should hurry up and find out yourselves.. =D</p><p>P.S. Cough*Cough Freeleech anyone..?😇</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>December 10th 2019</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The SUMMER2019 invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>August 12th 2019</span></div>
                        </li>
                                    </ul>
            </div>
        </div>
    </div>
</div>

<script src='https://www.google.com/recaptcha/api.js'></script>
<script type="text/javascript" src="/common.1f8556b52e7d1085a91b.js"></script><script type="text/javascript" src="/access.c48396a1df30ddb68b26.js"></script></body>
* Connection #0 to host www.torrentleech.org left intact`

Second openssl command hangs forever and doesn't return anything. Ubuntu with openssl installed.

**Comment by garfield69** [comment]
@ilike2burnthing  what do you think is going on here? I see the curl try ipv6 first, could openssl choke on that?
Should the user disable ipv6 even though they are not using docker jackett?

**Comment by garfield69** [comment]
@pazwicker so jackett and openssl both are made to wait for a response that never comes, the only diff is that jackett has a timeout while your openssl command did not specify one so waits forever. Hopefully one of the other team members can help further, cause I'm stumped.

**Comment by garfield69** [comment]
what version of openssl is your platform on?

**Comment by pazwicker** [comment]
Ah man, might have to go down the rabbit hole on this one.

```
sudo apt-get install openssl
[sudo] password for uname: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.1.1f-1ubuntu2.10).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by ilike2burnthing** [comment]
Repeat curl but with the additional option `-4`, and then again with `-6` instead.

Then do the same with openssl, but replacing `-connect` with `-4` and then `-6`.

If any of those fail, post the output.

**Comment by pazwicker** [comment]
It was IPV6! I disabled on my router and all works well. This is resolved, at least for me.

**Comment by garfield69** [comment]
\o/
