### ISSUE TITLE
[lesaloon]  Login failed: No form found on https://lesaloonv2-0.net/yupy_login.php using form selector form[action^="login"]

### ISSUE THREAD

**Issue by EricG66** [Jackett/Jackett#12979]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS : Windows 10 64 bit

Jackett Version: v0.20.596

Last Working Jackett Version:

Are you using a proxy or VPN? no
```

### Description

Cannot connect to the "lesaloonv2" tracker :(

Have to connect manually using the browser

### Logged Error Messages

```text
2022-02-21 20:28:11 Error   Jackett.Common.IndexerException: Exception (lesaloon): Login failed: No form found on https://lesaloonv2-0.net/yupy_login.php using form selector form[action^="login"] ---> System.Exception: Parse error ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://lesaloonv2-0.net/yupy_login.php using form selector form[action^="login"] at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 577 at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1502 --- End of inner exception stack trace --- at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 794 at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1652 at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415 --- End of inner exception stack trace --- at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 415 at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 771 at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 434

2022-02-21 20:28:11 Error   Error on 20220221202811 for LeSaloon.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://lesaloonv2-0.net/yupy_login.php using form selector form[action^="login"] at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 577 at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1502

2022-02-21 20:28:11 Info    CardigannIndexer (lesaloon): Relogin required
```

**Comment by EricG66** [comment]
I will monitor to see if the problem is coming back..

How to test the login again? How often jackett is making connection?

**Comment by ilike2burnthing** [comment]
Please post an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by defied** [comment]
I'm seeing this on a linux box running v0.20.740

Message:
```
Jackett.Common.IndexerException: Exception (badasstorrents): Challenge detected but FlareSolverr is not configured
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 607
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1383
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 771
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 434
```

**Comment by garfield69** [comment]
@defied https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
