### ISSUE TITLE
[btschool] Login failed: Selector

### ISSUE THREAD

**Issue by jcc563768606** [Jackett/Jackett#12988]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
02-23 14:44:19 Info Starting Jackett v0.20.629 
02-23 14:44:20 Info Environment version: 6.0.2 (/app/Jackett/) 
02-23 14:44:20 Info OS version: Unix 5.10.60.0 (64bit OS) (64bit process) 
02-23 14:44:20 Info Jackett variant: CoreLinuxAmdx64 
02-23 14:44:20 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
02-23 14:44:20 Info Running in Docker: Yes (image build: v0.20.576-ls56) 
02-23 14:44:20 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
02-23 14:44:20 Info App config/log directory: /config/Jackett 
02-23 14:44:20 Info Using proxy: Disabled 
02-23 14:44:20 Info Using FlareSolverr: http://192.168.1.20:8191/ 
02-23 14:44:20 Info Using HTTP Client: HttpWebClient2 

```

### Description

[https://pt.btschool.club/]
add btschool indexer by Cookie ,and then failed

### Logged Error Messages

```text
An error occurred while updating this indexer
Login failed: Selector "a[href="logout.php"]" didn't match
02-23 14:47:04 Error Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 830
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 973
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 830
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 973
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
Please read https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work especially the Notes to see if anything applies to you.
if you cannot solve then please provide a full enhanced log, perhaps the Debug and HTML will provide a clue to your issue
See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by jcc563768606** [comment]
Very few times i can pass the indexer config ,but very quickle failed to the Test
Most of the time,i can not pass the indexer config

2022-02-24 20:02:03.1964 Info Request starting HTTP/1.1 GET http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config?_=1645703970232 - - 
2022-02-24 20:02:03.1964 Debug Request is continuing in applying rules. Current url is http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config?_=1645703970232 
2022-02-24 20:02:03.1964 Debug Request is continuing in applying rules. Current url is http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config?_=1645703970232 
2022-02-24 20:02:03.1964 Debug Request is continuing in applying rules. Current url is http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config?_=1645703970232 
2022-02-24 20:02:03.1964 Debug The request path /api/v2.0/indexers/btschool/config does not match a supported file type 
2022-02-24 20:02:03.1976 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2022-02-24 20:02:03.1976 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/btschool/config' 
2022-02-24 20:02:03.1976 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/btschool/config' 
2022-02-24 20:02:03.1976 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
2022-02-24 20:02:03.1976 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
2022-02-24 20:02:03.1976 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2022-02-24 20:02:03.1976 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2022-02-24 20:02:03.1984 Debug Execution plan of resource filters (in the following order): None 
2022-02-24 20:02:03.1984 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2022-02-24 20:02:03.1984 Debug Execution plan of exception filters (in the following order): None 
2022-02-24 20:02:03.1984 Debug Execution plan of result filters (in the following order): None 
2022-02-24 20:02:03.1984 Debug Authorization was successful. 
2022-02-24 20:02:03.1984 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-02-24 20:02:03.1984 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-02-24 20:02:03.1994 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter 
2022-02-24 20:02:03.1994 Debug No information found on request to perform content negotiation. 
2022-02-24 20:02:03.1994 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response. 
2022-02-24 20:02:03.1994 Debug Attempting to select the first formatter in the output formatters list which can write the result. 
2022-02-24 20:02:03.1994 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response. 
2022-02-24 20:02:03.1994 Info Executing OkObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'. 
2022-02-24 20:02:03.1994 Debug The response will be compressed with 'gzip'. 
2022-02-24 20:02:03.2004 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 1.6407ms 
2022-02-24 20:02:03.2004 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
2022-02-24 20:02:03.2004 Debug Connection id "0HMFNDJBVVPL7" completed keep alive response. 
2022-02-24 20:02:03.2004 Info Request finished HTTP/1.1 GET http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config?_=1645703970232 - - - 200 - application/json;+charset=utf-8 4.2832ms 
2022-02-24 20:02:10.8502 Info Request starting HTTP/1.1 POST http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config application/json 510 
2022-02-24 20:02:10.8505 Debug Request is continuing in applying rules. Current url is http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config 
2022-02-24 20:02:10.8505 Debug Request is continuing in applying rules. Current url is http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config 
2022-02-24 20:02:10.8505 Debug Request is continuing in applying rules. Current url is http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config 
2022-02-24 20:02:10.8505 Debug POST requests are not supported 
2022-02-24 20:02:10.8505 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2022-02-24 20:02:10.8505 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/btschool/config' 
2022-02-24 20:02:10.8516 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/btschool/config' 
2022-02-24 20:02:10.8516 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2022-02-24 20:02:10.8516 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2022-02-24 20:02:10.8516 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2022-02-24 20:02:10.8516 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2022-02-24 20:02:10.8516 Debug Execution plan of resource filters (in the following order): None 
2022-02-24 20:02:10.8516 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2022-02-24 20:02:10.8516 Debug Execution plan of exception filters (in the following order): None 
2022-02-24 20:02:10.8528 Debug Execution plan of result filters (in the following order): None 
2022-02-24 20:02:10.8528 Debug Authorization was successful. 
2022-02-24 20:02:10.8528 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-02-24 20:02:10.8528 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-02-24 20:02:10.8534 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2022-02-24 20:02:10.8534 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2022-02-24 20:02:10.8547 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
2022-02-24 20:02:10.8547 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
2022-02-24 20:02:10.8547 Debug Connection id "0HMFNDJBVVPL7", Request id "0HMFNDJBVVPL7:00000004": started reading request body. 
2022-02-24 20:02:10.8547 Debug Connection id "0HMFNDJBVVPL7", Request id "0HMFNDJBVVPL7:00000004": done reading request body. 
2022-02-24 20:02:10.8560 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2022-02-24 20:02:10.8560 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2022-02-24 20:02:10.8564 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2022-02-24 20:02:10.8564 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2022-02-24 20:02:10.8564 Debug CACHE IsCacheEnabled => false 
2022-02-24 20:02:10.8564 Debug CardigannIndexer (btschool): Cookies after login: mycookie
2022-02-24 20:02:10.8564 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://pt.btschool.club/index.php) 
2022-02-24 20:02:11.0073 Debug WebClient(HttpWebClient2): Returning OK => 437 bytes
<html><body><script language="javascript" type="00e7b86f9eb89fb2f80c881a-text/javascript">window.location="/"  +  "index.ph"  +   "p?"+  "__SAKU"+"RA=35d7f"+   "09e3"+"5e41" +  "5aad"+  "aad15bb"   +   "c133"+  "b32" +"2"+   "0" +   "164"   +"5704131_"  +"471" +"7957";</script><script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="00e7b86f9eb89fb2f80c881a-|49" defer=""></script></body></html> 
2022-02-24 20:02:11.0076 Debug updating Cookies mycookie => cookie
2022-02-24 20:02:11.0088 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 155.8965ms 
2022-02-24 20:02:11.0088 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2022-02-24 20:02:11.0093 Error Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 830
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 973
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 830
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 973
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2022-02-24 20:02:11.0138 Debug The response will be compressed with 'gzip'. 
2022-02-24 20:02:11.0184 Debug Connection id "0HMFNDJBVVPL7" completed keep alive response. 
2022-02-24 20:02:11.0184 Info Request finished HTTP/1.1 POST http://www.mydomain.com:9117/api/v2.0/indexers/btschool/config application/json 510 - 500 - application/json 168.4157ms

**Comment by ilike2burnthing** [comment]
Make sure when copying the cookie, select the text, right-click and select `Copy`, do **not** select `Copy value`.

**Comment by jcc563768606** [comment]
i'm very sure that i select the `Copy` ,my cookie's format is 
`cf_clearance=XXXXXXXXXXXXXX; c_secure_ssl=XXXXXXXXXXX; c_secure_uid=XXXXXXXXXX; c_secure_pass=XXXXXXXXXX; c_secure_tracker_ssl=XXXXXXX; c_secure_login=XXXXXXXXXX`

**Comment by jcc563768606** [comment]
https://user-images.githubusercontent.com/11483516/155661270-4b98be2a-8b9e-42ee-a124-b6a5270c5dba.mp4

**Comment by ilike2burnthing** [comment]
Are you using a VPN or proxy?

Do the device you're grabbing the cookie from and the device Jackett and FlareSolverr are on share the same public IP?

**Comment by garfield69** [comment]
also, as you are a docker user, try 
- some Docker users appear to have success using the cookie from a firefox browser
- Another Docker user had success by setting up chrome as a service container, see https://hub.docker.com/r/browserless/chrome

**Comment by jcc563768606** [comment]
> Are you using a VPN or proxy?
> 
> Do the device you're grabbing the cookie from and the device Jackett and FlareSolverr are on share the same public IP?

oh,you are right,VPN is true reason,thank you!
