### ISSUE TITLE
[Newpct] Broken download

### ISSUE THREAD

**Issue by snamds** [Jackett/Jackett#12989]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.0.0
Environment version: 6.0.2 (C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.2\)
OS version: Microsoft Windows NT 10.0.19043.0 (64bit OS) (64bit process)
Jackett variant: CoreWindows
Running in Docker: No
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: C:\ProgramData\Jackett
Using proxy: Disabled
Using FlareSolverr: http://127.0.0.1:8191
Using HTTP Client: HttpWebClient2
```

### Description

I made a change yesterday to make Newpct work. There was a change in the final url download and referer was needed in order to work. https://github.com/Jackett/Jackett/pull/12984
Today is not working again.

As a hint:
The download function has three requests. The first one works ok but the second one, the one that gets the final link, fails with an exception.
The only way I have managed to avoid the exception is adding this to the headers:
· cookie "cf_clearance=s2X4gSgwLUxJVt3FgY_s5dRlgX6AgEOLpjHIEoDZYX4-1645633570-0-150". Seen in my browser
· user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0". The default one does not work
· x-requested-with "XMLHttpRequest"
BUT the result you get with this changes is the text "ERROR" in the response.
So seems that this cookie has some info needed to work ok.

I have managed to get my own cookie using flareSolverr, quering the url "https://atomtt.com/t_download/168993/los-consejos-del-doctor-bird-para-poetas-tristes--2022-/" (is just an example) and parsing the response but using this cookie doen't solve the "ERROR" problem.

Any ideas?

### Logged Error Messages

```text
02-23 19:20:44 Error Error downloading. indexer: newpct path: https://atomixhq.art/descargar/peliculas-castellano/los-consejos-del-doctor-bird-para-poetas-tristes-2022-/blurayrip-ac3-5-1/
FlareSolverrSharp.Exceptions.FlareSolverrException: Unimplemented POST Content-Type: text/plain; charset=utf-8
   at FlareSolverrSharp.Solvers.FlareSolverr.GenerateFlareSolverrRequest(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in C:\Work\Jackett-master\Jackett-master\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in C:\Work\Jackett-master\Jackett-master\src\Jackett.Common\Utils\Clients\WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in C:\Work\Jackett-master\Jackett-master\src\Jackett.Common\Indexers\BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.NewPCT.Download(Uri linkParam) in C:\Work\Jackett-master\Jackett-master\src\Jackett.Common\Indexers\NewPCT.cs:line 218
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in C:\Work\Jackett-master\Jackett-master\src\Jackett.Server\Controllers\DownloadController.cs:line 56
```

**Comment by garfield69** [comment]
>Any ideas?

my uneducated guess is that newpct have added a cloudflare challenge just prior to initiating the download, and maybe Jackett is not invoking flaresolverr at this point.
But I'm not a C# dev so I don't know for sure, or even hot to code a solve. C# dev needed.

**Comment by ilike2burnthing** [comment]
Dupe - https://github.com/Jackett/Jackett/issues/12958#issuecomment-1048488792
