### ISSUE TITLE
[thesceneplace] Test search in TheScenePlace => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by AzureBelmont** [Jackett/Jackett#12992]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-24 09:58:20	Info	Using FlareSolverr: No
2022-02-24 09:58:20	Info	Using proxy: Disabled
2022-02-24 09:58:20	Info	App config/log directory: C:\ProgramData\Jackett
2022-02-24 09:58:20	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-02-24 09:58:20	Info	Running in Docker: No
2022-02-24 09:58:20	Info	Jackett variant: CoreWindows
2022-02-24 09:58:20	Info	OS version: Microsoft Windows NT 10.0.22000.0 (64bit OS)
2022-02-24 09:58:20	Info	Environment version: 6.0.2 (C:\ProgramData\Jackett\)
2022-02-24 09:58:20	Info	Starting Jackett v0.20.631
```

### Description

add or test tracker gives me the issue. 

### Logged Error Messages

```text
System.Exception: Test search in TheScenePlace => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 311
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61

	
CardigannIndexer (thesceneplace): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=18">
			<img src="https://www.thesceneplace.com/style/Black-n-Blue_3.0/images/categories/PACK-TV.gif" border="0" alt="Packs" title="Packs">
		</a>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<img src="images/fls_locked.png" border="0" alt="Locked" title="Locked">
	</td>
	<td class="lista" valign="middle" onmouseover="this.className='post'" onmouseout="this.className='lista'" style="padding-left:10px;overflow:auto;">
		<a href="index.php?page=torrent-details&amp;id=9f3afee3fad64af2c8b98d31d96b5749e950e92b" onmouseover=" return overlib('<img src=torrentimg/9f3afee3fad64af2c8b98d31d96b5749e950e92b.jpg width=200 border=0>', CENTER);" onmouseout="return nd();">Peacemaker S01 2022 1080p WEB DL OPUS 5 1 H265   TSP</a><img title="high speed torrent" src="images/seedbox.gif" alt="high speed torrent">
		<img alt="3x Upload Multiplier" title="3x Upload Multiplier" src="images/3x.gif">
		<img title="Free Leech" src="images/freeleech.gif" alt="Free Leech">
		<img title="Gold 100% Free" src="images/gold.gif" alt="Gold 100% Free">
	</td>
	<td align="center" width="30" class="lista" style="white-space:wrap;padding-left:10px;">---
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=9f3afee3fad64af2c8b98d31d96b5749e950e92b&amp;f=Peacemaker+S01+2022+1080p+WEB-DL+OPUS+5.1+H265+-+TSP.torrent">
			<img src="images/download.gif" border="0" alt="Download Torrent" title="Download Torrent">
		</a>
	</td>
	<td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">24/02/2022</td>
	<td align="center" width="30" class="lista #FFFF00" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=9f3afee3fad64af2c8b98d31d96b5749e950e92b" title="Click here to view peers details">2</a>
	</td>
	<td align="center" width="30" class="lista #FF0000" style="text-align: center;">
		<a href="index.php?page=peers&amp;id=9f3afee3fad64af2c8b98d31d96b5749e950e92b" title="Click here to view peers details">0</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=9f3afee3fad64af2c8b98d31d96b5749e950e92b" title="History - Peacemaker S01 2022 1080p WEB-DL OPUS 5.1 H265 - TSP">1</a>
	</td>
	<td align="center" width="30" class="lista">
		<a href="index.php?page=userdetails&amp;id=9084">
			<span style="font-style:italic;color:#ff0000">Rogerthat</span>
		</a>
	</td>
	<td align="center" width="30" class="lista">7.63 GB</td>
	<td align="center" width="45" class="lista" style="text-align: center;">691.48 KB/sec</td>
	<td align="center" width="45" class="lista" style="text-align: center;">100%<br>
		<table border="0" width="44" cellspacing="0" cellpadding="0">
			<tbody>
				<tr>
					<td align="right" border="0" width="2">
						<img src="images/bar_left.gif">
					</td>
					<td align="left" border="0" background="images/progbar-red.gif" width="40">
						<img height="9" width="40" src="images/progbar-green.gif">
					</td>
					<td align="right" border="0" width="2">
						<img src="images/bar_right.gif">
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="lista" style="text-align: center;width:50px;">
		<input type="checkbox" name="msg[]" value="9f3afee3fad64af2c8b98d31d96b5749e950e92b">
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector={{ if .Result.superuser }}td:nth-last-child(10){{ else }}td:nth-last-child(8){{ end }}, value= +00:00: DateTime parsing failed for "+00:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in D:\a\1\s\src\Jackett.Common\Utils\DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in D:\a\1\s\src\Jackett.Common\Utils\DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1594
```

**Comment by AzureBelmont** [comment]
https://www.toptal.com/developers/hastebin/ 
Full enhanced logs

**Comment by garfield69** [comment]
The indexer is set up to count the columns in the torrents page differently depending on whether the row contains the username of the uploader or not.
For instance, My rank is `Power User`, and my torrent page does not have the uploader, so the indexer works for me.
Can you please provide your rank, `User`, `Power User`, `Scene User`, `Scene Master`, `VIP`, `Site Friend`, `Uploader`, something else?
I need to work out if there is now a third variation of the torrent page, or if it is simply a layout change.
Thanks.

**Comment by garfield69** [comment]
@nexus382 @jckozy86 is the Jackett thesceneplace indexer still working for you?

**Comment by AzureBelmont** [comment]
my rank is uploader

**Comment by garfield69** [comment]
@AzureBelmont  is this the first time you are using this indexer, or did it work for you previously, and if it was working before did your rank recently change and the indexer stopped working?

**Comment by AzureBelmont** [comment]
@garfield69 it was working with prowlarr but started having an issue with it so I came back to jackett since I knew it was working on that, I was recently changed to Uploader though and it has now stopped working for me on jackett as well.

**Comment by garfield69** [comment]
OK thanks. So it looks like the Uploader rank is getting another variation of the torrent page, just slightly different enough to throw off the column count that the indexer uses to pick up the different fields :-(
I'll do some research and see if I can work out a solve to keep what is now three different torrent page presentations working in the indexer.

**Comment by AzureBelmont** [comment]
awesome, thank you!

**Comment by bakerboy448** [comment]
> OK thanks. So it looks like the Uploader rank is getting another variation of the torrent page, just slightly different enough to throw off the column count that the indexer uses to pick up the different fields :-(
> I'll do some research and see if I can work out a solve to keep what is now three different torrent page presentations working in the indexer.

I think superuser changed to superfriend in the response - at least thats what was partially being seen in Prowlarr
https://github.com/Prowlarr/Prowlarr/issues/858

but admin indicated on prowlarr discord they have had no changes since Oct

**Comment by garfield69** [comment]
I've tested c88c7e5dce522e5d17fc63ad705438a080ac1c25 with my PowerUser rank, hopefully the Uploader and Moderator ranks will also work, but post here if it fails. Thanks.

**Comment by AzureBelmont** [comment]
tried to test it again. also removed and readded the tracker and tested. https://www.toptal.com/developers/hastebin/ugagozuhun.xml

**Comment by garfield69** [comment]
The Jackett release is due out in about 15 minutes. How did you test?

**Comment by AzureBelmont** [comment]
sorry looked at the time wrong :( thought it was two hours later than it is

**Comment by garfield69** [comment]
v0.20.632

**Comment by AzureBelmont** [comment]
it works, thank you
