### ISSUE TITLE
[newpct] found no results

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12998]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

site stuffed again

### Logged Error Messages

```text
https://atomixhq.art/ultimas-descargas/ is retuning a blank page which breaks the indexer
```

### Screenshots

really getting tired of this problematic site.

**Comment by garfield69** [comment]
same problem, https://atomixhq.link/ultimas-descargas/ returns an empty page.

**Comment by syp1975** [comment]
well, is clear the site owner is fighting against indexers. his greedy is making the site useless even for visitors. in no time this site will disappear, so _buen viaje_.

**Comment by snamds** [comment]
https://atomixhq.link/ultimas-descargas/ returning a blank page is not a problem. Using https://atomixhq.link/get/result/ with an empty search string will do the trick. The problem is that resolverr is not able to query this site. https://github.com/FlareSolverr/FlareSolverr/issues/77

**Comment by ilike2burnthing** [comment]
FlareSolverr has no issue accessing it here, so that's definitely an option, but would still be reliant on C#.

**Comment by snamds** [comment]
@ilike2burnthing, it doesn't work for me.
The indexer already uses "/get/result/" to get movies results and it's not working.
In order to test, do a manual search on newpct. Select category "2000 (movies)" first.
I get the exception "Unsupported POST Content-Type: application/x-www-form-urlencoded". It's the same exception that you get when trying to download a result:

03-08 17:24:46 Error Jackett.Common.IndexerException: Exception (newpct): Unsupported POST Content-Type: application/x-www-form-urlencoded
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Unsupported POST Content-Type: application/x-www-form-urlencoded
   at FlareSolverrSharp.Solvers.FlareSolverr.GenerateFlareSolverrRequest(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Utils\Clients\WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.NewPCT.MovieSearch(TorznabQuery query) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\NewPCT.cs:line 463
   at Jackett.Common.Indexers.NewPCT.PerformQuery(TorznabQuery query) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\NewPCT.cs:line 232
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 768
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Server\Controllers\ResultsController.cs:line 228 Jackett.Common.IndexerException: Exception (newpct): Unsupported POST Content-Type: application/x-www-form-urlencoded
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: Unsupported POST Content-Type: application/x-www-form-urlencoded
   at FlareSolverrSharp.Solvers.FlareSolverr.GenerateFlareSolverrRequest(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Utils\Clients\WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.NewPCT.MovieSearch(TorznabQuery query) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\NewPCT.cs:line 463
   at Jackett.Common.Indexers.NewPCT.PerformQuery(TorznabQuery query) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\NewPCT.cs:line 232
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:line 768
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in C:\Users\xxxx\Documents\GitHub\Jackett\src\Jackett.Server\Controllers\ResultsController.cs:line 228

**Comment by snamds** [comment]
So, we have to wait flaresolverr to solve this unsopported-post-data exception issue, isn't it?

**Comment by ilike2burnthing** [comment]
Unless the indexer can be rewritten, yes.

**Comment by ilike2burnthing** [comment]
https://atomixhq.link/ultimas-descargas/ is back up

Docker - FlareSolverr timeout
Windows - working, no Cloudflare check
Guessing it's a UA thing.

Results are a mess and downloads don't work:
![Screenshot 2022-03-10 120347](https://user-images.githubusercontent.com/59480337/157658976-4d042df9-6c20-4879-b93b-9e98b876acf3.png)

**Comment by Yonoesio** [comment]
This is the antivirus error when loading https://atomixhq.link/


![captura](https://user-images.githubusercontent.com/36561979/157666586-0541b1a7-330b-4db8-a776-d6ae12c4b73e.png)

**Comment by snamds** [comment]
New antibot measures have been added.
Now you have to pass two previous pages and a timer before downloading once per day.

https://www.youtube.com/embed/nU8fK0OROWo

![image](https://user-images.githubusercontent.com/3266153/158784871-5d54e580-c8b9-4002-9853-2983fe26cfd0.png)

**Comment by ilike2burnthing** [comment]
I can't get the ads to show in the last step (yes I've disabled uBO), so can't test beyond that. If it's just a cookie issue, we can have a cookie login and an info note, but otherwise we'll just get rid of the indexer.

**Comment by garfield69** [comment]
I used firefox and waded my way through a download attempt.
There is enough click bait on the site to sink a battleship.
Clearly the site wants to generate revenue and discourages automation.
I'm going to remove the indexer and call it a day.

**Comment by garfield69** [comment]
v0.20.726

**Comment by elvisaloha** [comment]
garfield , sorry for duplicate the request, my fault. Yes I update every day jacket but I thought that "atomixhq" as newpct indexer was different than "newpct-me" It could be a good idea rename "newpct-me" indexer to "newpct" (https://www.newpct.net/) and if "atomixhq" come back use "atomixhq" as name?  bc I always was a little confused about it :)

Thank for working so great and fast with jacket, it is a must have!

Have a nice weekend guys!

**Comment by joseeloren** [comment]
I was dealing with this with python plugins on qbittorrent. I had an idea to use btdig as a workaround, searching titles on atomixhq on btdig, and it works. However, I don't know how to skip btdig capcha.
