### ISSUE TITLE
[1337x] Exception (1337x): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (1337x.to:443) (Test)

### ISSUE THREAD

**Issue by keatit71** [Jackett/Jackett#12997]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-08 10:11:40.2303 Error Jackett.Common.IndexerException: Exception (1337x): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (1337x.to:443)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 170
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 208
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 595
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1374
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 416
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 416
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 759
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 228 Jackett.Common.IndexerException: Exception (1337x): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

### Description

Install 1337x indexer on Jackett and test or try to search on the indexer.

### Logged Error Messages

```text
Exception (1337x): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (1337x.to:443)
```

**Comment by garfield69** [comment]
The indexer works for me which suggest the issue is at your end.
However, since you have placed a stack trace in the environment section, instead of providing the proper environment data, we have nothing to identify your Jackett platform, version or other important info.
The error message itself is a generic jackett-gave-up-waiting-for-a-response error, so there is nothing that explains what the reason for the timeout is.
Have a read of https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed and see if you can figure out your issue.
If you cannot make progress, then 
- provide the proper environment data
- provide a full enhanced log, see https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
