### ISSUE TITLE
[mejortorrent] Could not find releases from this URL (Config)

### ISSUE THREAD

**Issue by killo3967** [Jackett/Jackett#12999]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-02-26 12:58:40.0930 Info Request finished HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/newpct/test - 0 - 500 - application/json 595.7770ms 
2022-02-26 13:00:46.1273 Info Starting Jackett v0.20.632 
2022-02-26 13:00:46.7337 Info Environment version: 6.0.2 (C:\ProgramData\Jackett\) 
2022-02-26 13:00:46.7348 Info OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS) 
2022-02-26 13:00:46.7348 Info Jackett variant: CoreWindows 
2022-02-26 13:00:46.7348 Info Running in Docker: No 
2022-02-26 13:00:46.7348 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2022-02-26 13:00:46.7348 Info App config/log directory: C:\ProgramData\Jackett 
2022-02-26 13:00:46.7348 Info Using proxy: Disabled 
2022-02-26 13:00:46.7348 Info Using FlareSolverr: http://localhost:8191/ 
2022-02-26 13:00:46.7348 Info Using HTTP Client: HttpWebClient2 
2022-02-26 13:00:46.7540 Info Loading Native indexers ... 
2022-02-26 13:00:46.9152 Info Loaded 86 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, danishbytes, darmowetorenty, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, greatposterwall, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, newpct, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, ShizaProject, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, xthor-api, zonaq, animetosho 
2022-02-26 13:00:46.9152 Info Loading Cardigann indexers from: C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\cardigann\definitions\, C:\WINDOWS\system32\config\systemprofile\AppData\Local\cardigann\definitions\, C:\ProgramData\Jackett\Definitions 
2022-02-26 13:00:48.3061 Info Loaded 494 Cardigann indexers: 0daykiev, 0magnet, 1337x, 1ptbar, 24rolika, 2fast4you, 3changtrai, 3dtorrents, 4thd, 52pt, abtorrents, acgrip, acgsou, acidlounge, acrossthetasman, aftershock, aidoruonline, aither-api, alleenretail, amigosshare, anaschcc, anilibria, anime-free, animeclipse, animelayer, animeworld-api, aniRena, anisource, arabafenice, arabp2p, arenabg, asiancinema, audiobookbay, audionews, aussierules, backups, badasstorrents, baibako, bangumi-moe, beitai, bestcore, beyond-hd-oneurl, beyond-hd, bibliotik, bigfangroup, bit-titan, bitbazis, bitbr, bitcityreloaded, bitded, bithorlo, bithumen, bitru, bitsearch, bitsexy, bitspyder, Bittorrentfiles, bitturk, bluebirdhd, bluesbrothers, blutopia-api, booktracker, bootytape, borgzelle, boxingtorrents, brasiltracker, broadcity, brsociety-api, bt4g, btdigg, btetree, btnext, btschool, btsow, bwtorrents, byrbt, byrutor, carpathians, carphunter, cartoonchaos, casatorrent, cathoderaytube, catorrent, ccfbits, ceskeforum, chdbits, chilebt, cinemageddon, cinemamovies, cinematik, classix, coastalcrew, comicat, concen, concertos, cpasbien, cpasbienclone, crazyhd, crazyspirits, crnaberza, crt2fa, cryptichaven, dariustracker, dark-shadow, darktracker, datascene-api, datatalli, deildu, demonoid, desitorrents-api, diablotorrent, digitalcore, dimeadozen, discfan, divteam, dmhy, docspedia, dragonworldreloaded, dxp, ebookparadijs, ebooks-shares, ehentai, elitetorrent-biz, empornium, empornium2fa, eniahd, esharenet, estone, exkinoray, extratorrent-st, extremebits, extremetorrents, extremlymtorrents, exttorrents, eztv, falkonvisionteam, fanoin, fantasticheaven, fantastiko, femdomcult, filelisting, film-paleis, finelite, finvip, firebit, fouducinema, freshmeat, frozenlayer, funkytorrents, gamestorrents, gay-torrents, gay-torrentsorg, gaytorrentru, generationfree-api, generationfree, genesismovement, gfxpeers, gigatorrents, girotorrent, gktorrent, glodls, greekdiamond, greekteam, gtorrentpro, haidan, haitang, hamsterstudio, happyfappy, hawke-uno, hd4fans, hdai, hdarea, hdatmos, hdbits, hdbitscom, hdc, hdcenter, hdchina, hdcity, hdcztorrent, hddolby, hdforever, hdhome, hdhouse, hdme, hdmonkey, hdolimpo-api, hdonly, hdroute, hdsky, hdspain, hdtime, hdtorrentsit, hdturk, hdu, hdzone, hellastz, hqsource, huntorrent, ibit, idope, ilcorsaroblu, ilcorsaronero, ilcorsaroverde, immortuos, indietorrents, insanetracker, internetarchive, isohunt2, itorrent, iv-torrents, jpopsuki, jptv, karagarga, keepfriends, kickasstorrents-to, kickasstorrents-ws, kinonavse100, kinorun, kinozal, kisssub, krazyzone, lastfiles, lat-team-api, learnbits, learnflakes, leech24, legacyhd, legittorrents, lemonhd, lepornoinfo, lesaloon, libranet, limetorrents, limetorrentsclone, linkomanija, linuxtracker, losslessclub, mactorrentsdownload, madsrevolution, magicheaven, magico, majomparade, marinetracker, mediamaatjes, megamixtracker, megapeer, mesevilag, metaltracker, microbit, mikan, milkie, mircrew, mixtapetorrent, mma-torrents, mnv, mononokebt, mousebits, moviesdvdr, moviesite, movietorrent, movietorrentz, mteamtp, mteamtp2fa, muziekfabriek, mvgroupforum, mvgroupmain, mypornclub, myspleen, nbtorrents, nbytez, netcosmo, nethd, netlab, newpct-me, newretro, newstudio, newstudiol, nipponsei, nitro, nntt, noname-club, noname-clubl, nyaasi, omgwtftrackr, onejav, opencd, opensharing, oshenpt, ourbits, oxtorrent, p2pbg, p2pelite, parnuxi, pctorrent, peeratiko, peerjunkies, peersfm, pier720, piratadigital, piratbit, piratbitl, pixelcove, polishsource, pornbay, pornbits, pornforall, pornleech, pornolive, pornoslab, pornotor, pornotorrent, portugas, potuk, proaudiotorrents, proporno, prostylex, pterclub, ptfiles, pthome, ptmsg, ptsbao, pttime, punkshorror, puntotorrent, purovicio, pussytorrents, putao, puurhollands, pwtorrents, r3vwtf, racing4everyone-api, racingforme, rainbowtracker, rapidzona, redbits-api, redstartorrent, reelflix-api, resurrectthenet, rgfootball, rintor, rintornet, riperam, RockBox, romanianmetaltorrents, rptorrents, rus-media, rustorka, rutor, rutracker-ru, scenepalace, scenerush, sdbits, seedfile, selezen, sexxi, sexypics, shareisland-api, sharewood, showrss, siambit, skipthecommercials-api, sktorrent-org, sktorrent, slosoul, snowpt, solidtorrents, sosulki, soulvoice, soundpark, speedmasterhd, speedtorrentreloaded, spidertk, spiritofrevolution, sporthd, sportscult, springsunday, sugoimusic, sukebeinyaasi, superbits, swarmazon, tapochek, tasmanit, teamhd, teamos, tekno3d, tellytorrent-api, teracod, theaudioscene, theempire, thefallingangels, thegeeks, thehorrorcharnel, theleachzone, themixingbowl, theoccult, thepiratebay, theplace, thesceneplace, theshinning, theshow, thevault, tjupt, tlfbits, tokyotosho, torlock, torlook, toros, torrent-explosiv, torrent-pirat, torrent-turk, torrent9, torrent9clone, torrentbd, torrentby, torrentccf, torrentdb, torrentdownload, torrentdownloads, torrentfunk, torrentgalaxy, torrenthr, torrenting, torrentkitty, torrentland, torrentleech-pl, torrentleech, torrentlt, torrentmasters, torrentmax, torrentoyunindir, torrentparadise, torrentproject2, torrentqq, torrentsectorcrew, torrentseeds-api, torrentsir, torrentslocal, torrentsurf, torrentv, torrentview, torrentwhiz, torrentz2eu, totallykids, totheglory, totheglorycookie, trackeros-api, trancetraffic, trezzor, tribalmixes, trupornolabs, ttsweb, turkseed, turktorrent, turktracker, tvchaosuk, tvroad, twilight, twilightszoom, u2, uhd-heaven, uhdbits, underverse, underversel, uniondht, unionfansub, uniongang, unlimitz, vizuk, vsthouse, vsttorrents, wdt, whiteangel, wihd, woot, xiteme, xbit, xbytesv2, xwtclassics, xwtorrents, xxxadulttorrent, xxxtor, xxxtorrents, ydypt, yggcookie, yggtorrent, yourbittorrent, yts, zamundanet, zelkaorg, zetorrents, zomb, zooqle, ztracker 
2022-02-26 13:00:48.3061 Info Loaded 580 indexers in total 
2022-02-26 13:00:48.3061 Info Adding aggregate indexer ('all' indexer) ... 
2022-02-26 13:00:48.3163 Info Adding filter indexer ('type:public' indexer) ... 
2022-02-26 13:00:48.3163 Info Adding filter indexer ('type:private' indexer) ... 
2022-02-26 13:00:48.3163 Info Adding filter indexer ('type:semi-public' indexer) ... 
2022-02-26 13:00:48.4923 Info Jackett startup finished in 2.702 s
```

### Description

Could not connect to Mejortorrent indexer. I tried all the url's and no one function with me.

### Logged Error Messages

```text
2022-02-26 13:03:37.8389 Error System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.MejorTorrent.<>c.<ApplyConfiguration>b__12_0() in D:\a\1\s\src\Jackett.Common\Indexers\MejorTorrent.cs:line 118
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\MejorTorrent.cs:line 117
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26 System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.MejorTorrent.<>c.<ApplyConfiguration>b__12_0() in D:\a\1\s\src\Jackett.Common\Indexers\MejorTorrent.cs:line 118
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\MejorTorrent.cs:line 117
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

### Screenshots

![image](https://user-images.githubusercontent.com/71940871/155842634-adff98ab-3c44-4adf-af58-5ad4f10dde5d.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/12559

**Comment by MiTvSpain** [comment]
Hay solución a los problemas?

**Comment by garfield69** [comment]
no, the web site's latest-torrents page is empty. See #12559
