### ISSUE TITLE
[nyaasi] Test search in Nyaa.si => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by andrewbenton0** [Jackett/Jackett#13003]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/seclusivebox/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: 
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.23.0 (64bit OS) (64bit process)
Environment version: 6.0.1 (/usr/share/jackett/)
Starting Jackett v0.0.0
```

### Description

I created the indexer for nyaa.si awhile ago and had no issues using it together with Sonarr. Suddenly today the indexer created through sonarr is no longer able to grab any results, but it able to query the server. I've tried to recreate the indexer from scratch but can no longer pull nyaa.si from the list on Jackett. 

### Logged Error Messages

```text
System.Exception: Test search in Nyaa.si => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name)
   at Jackett.Server.Controllers.IndexerApiController.Test()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext)
```

**Comment by garfield69** [comment]
The nyaa.si indexer is working for me which suggests the problem is at your end.
Please turn on the enhanced logging and the Jackett dashboard, and use the TEST button for the nyaa.si indexer.
Perhaps the enhanced log with the Debug and HTML will provide a clue to your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by andrewbenton0** [comment]
[jackett enhanced logs.txt](https://github.com/Jackett/Jackett/files/8149371/jackett.enhanced.logs.txt)
[Browse Nyaa.txt](https://github.com/Jackett/Jackett/files/8149373/Browse.Nyaa.txt)

**Comment by echozs151** [comment]
I'm also currently facing the same issue on a remote server. The response that jackett is getting is a page saying "429 Too Many Requests", as I can see from my logs and the logs you posted. 

Trying to simply visit the page from the remote server gives me the same page so my conclusion is nyaa is limiting the request rate on that host.

I recently tried on sonarr to search for around 350 entries and I believe this is what may have caused the site to block me.

**Comment by andrewbenton0** [comment]
So would the only alternative to be to contact Nyaa admins and see why I was blocked?

**Comment by garfield69** [comment]
A 429 error would usually be lifted after a period of inactivity has passed. 
How long you have to wait is up to the web site. 
I suggest you try tomorrow, and if still blocked then wait a couple days, then a week.
Also, if you are using apps like Sonarr, and have the Sonarr automation turned on so that it frequently makes queries to Jackett indexers, then consider turning on the Jackett cache option on its dashboard, which should help reduce the unnecessary traffic to web sites, since no one really needs to have up to the hour updates of the latest torrents. 
Cultivate some patience ;-)

**Comment by garfield69** [comment]
Oh, as far as not finding nyaa on the Jackett dasboard, there are two places it can be:
on the active list, (check you have not turned on any filters that could hide it), and on the add-an-indexer page, (also check your filters are not hiding it).
IF you cannot find it, then restart Jackett, and check the log. One of the first messages after start-up is a list of indexer that have been loaded. Nyaa should be there.
If not then perhaps you need to update your version of Jackett to overwrite the broken one you may have.

**Comment by garfield69** [comment]
And if you have deleted the indexer entry on sonarr, and are trying to add it afresh, then that will not work until you have full access the nyaaa web site again via Jackett.
Part of the define-an-indexer on Sonarr is to perform a TEST to confirm that the indexer is good to go. If Nyaa is rejecting your Jackett indexer query then it will not pass the test and Sonarr will save your definition.

**Comment by andrewbenton0** [comment]
Appreciate the in depth responses. As someone relatively new to this helps me get a deeper understanding! I'll work on editing the amount queries and try to lower the frequency. As for updating Jackett, I use a remote server that I believe automatically updates Jackett and Sonarr.
