### ISSUE TITLE
[orpheus] Your API Key did not work: Parse error (Config)

### ISSUE THREAD

**Issue by eac4** [Jackett/Jackett#13015]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-03-04 12:11:20	Info	
Using HTTP Client: HttpWebClient2
2022-03-04 12:11:20	Info	
Using FlareSolverr: No
2022-03-04 12:11:20	Info	
Using proxy: Disabled
2022-03-04 12:11:20	Info	
App config/log directory: /home1/eac/.config/Jackett
2022-03-04 12:11:20	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-03-04 12:11:20	Info	
Running in Docker: No
2022-03-04 12:11:20	Info	
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-03-04 12:11:20	Info	
Jackett variant: CoreLinuxAmdx64
2022-03-04 12:11:20	Info	
OS version: Unix 5.4.0.91 (64bit OS) (64bit process)
2022-03-04 12:11:20	Info	
Environment version: 6.0.2 (/home1/eac/bin/Jackett/)
2022-03-04 12:11:20	Info	
Starting Jackett v0.20.662
```

### Description

Generate new API token on OPS (or use an old one), attempt to add OPS to Jackett ->  Error: Your API Key did not work: Parse error

### Logged Error Messages

```text
System.Exception: Your API Key did not work: Parse error
   at Jackett.Common.Indexers.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 106
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 113
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

Error on 20220304121422 for Orpheus.txtSystem.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Jackett.Common.Indexers.Abstract.GazelleTracker.PerformQuery(TorznabQuery query)
```

**Comment by ilike2burnthing** [comment]
`Input string was not in a correct format` - first thing that jumps to mind is that there may be an additional space at the start or end of the key. Check that this isn't the case. I don't have an account but according to the indexer it should be 118 characters long:
https://github.com/Jackett/Jackett/blob/1e136624a7e258ba0c3e1f2154e197fe9f39fcfb/src/Jackett.Common/Indexers/Orpheus.cs#L19

If the key is the correct length, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by eac4** [comment]
Hi,

The key is indeed the correct length. Attaching the enhanced log

[log.txt](https://github.com/Jackett/Jackett/files/8185803/log.txt)

**Comment by ilike2burnthing** [comment]
Odd. I'm not really sure what it's unable to parse there, everything looks fine, and of course it doesn't tell us.

@garfield69 anything obvious pop out that I'm missing?

**Comment by eac4** [comment]
Indeed. OPS side seems fine, getting the expected response from the API for an example request to `https://orpheus.network/ajax.php?action=index`. The same response while using a cookie header or the Authorization header with my token

**Comment by garfield69** [comment]
>anything obvious pop out that I'm missing?

bah, its GazelleTracker, so its C#, not my area of expertise.
The error occurs within the GazelleTracker ApplyConfiguration routine, which checked the apikey was not null and had the correct length. It then called the  PerformQuery(new TorznabQuery()) routine, which returned a json response from the api, so at this stage we can assume that the apikey was good or we would not see the results of the search.
However we are getting a parse error, which is trapped and the try-catch triggers the your-apikey-did-not-work.
So my guess is that one of the torrent that was returned is causing a parse error.
But I don't know for sure, this is one for @ngosang or a C# dev to debug.

**Comment by ilike2burnthing** [comment]
Maybe the results from the Applications categories are causing the issue? They have no `artist`, `cover`, `groupyear`, or `releaseType` values.

**Comment by garfield69** [comment]
>Maybe the results from the Applications categories are causing the issue? They have no artist, cover, groupyear, or releaseType values.

It all depends on how the code handles missing keys or missing values. Really need to have access to an account on the site and Jackett running in VS to properly debug the routine and find which key/value breaks the parser.

**Comment by ngosang** [comment]
We need to borrow an account to fix this issue.

**Comment by jonesnc** [comment]
> We need to borrow an account to fix this issue.

I have an Orpheus account. I'd be willing to help as it long as it doesn't involve sharing credentials.

**Comment by garfield69** [comment]
@jonesnc  if you are able to provide an invite then this is the best option.
Second choice would be to allow us to borrow your apikey for the duration of the debugging/recoding.
if you are unable/unwilling to provide either, then unless you are a C# dev and willing to raise a PR fix yourself, then I don't think there is much more you can do to help.
Let us know which option you are able to provide. Thanks.

**Comment by jonesnc** [comment]
@garfield69 I can send an invite. What email should I send the invite to?

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine -at- gmail.com I will have a go fixing the indexer.

**Comment by garfield69** [comment]
Hmm. The indexer is working for me. I added my api key and saved the config successfully.
I can click on the TEST and that works too.
Please confirm you are still having issues.

**Comment by jonesnc** [comment]
It has just started working for me as well. I just tried it on `v0.20.1062`, with the same API Key as what I was trying before, and it works for me.

**Comment by jonesnc** [comment]
Before I got it to work, I deleted the Orpheus indexer and re-added it. I wonder if that was what caused it to start working.

**Comment by N00bDaan** [comment]
After trying to add orpheus as an indexer with a freshly made API key (15 minutes ago or so), I stumble upon this issue. I'm also on `v0.20.1062`

**Comment by jonesnc** [comment]
I just tried it again, and it's not working anymore. I'm getting the same Parse error as before.

**Comment by jonesnc** [comment]
Well, this is strange. I keep clicking Test on my Orpheus tracker intermittently, and sometimes it passes, sometimes it fails.

**Comment by garfield69** [comment]
The Rules state that the API has a 5 requests within a 10 seconds window limit, so don't do too many queries in quick succession.
also the site blog states that the site has been having performance issues, so that may play a part too.

**Comment by garfield69** [comment]
I have found a discrepancy in the returned results, where the gazelletracker abstract is expecting the groupTime to be a long value representing the unixtime, (e.g. `1652653129`) and when I search for e-books the groupTime is is a string (e.g. `2022-05-15 19:42:21`), so I'm going to amend the code to cope with either and perform some further tests to see if I can catch other discrepancies.

**Comment by jonesnc** [comment]
@garfield69 Thanks for digging into this issue.

**Comment by garfield69** [comment]
v0.20.1066
