### ISSUE TITLE
[lostfilm] Test search in LostFilm.tv => Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#13028]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Docker: linuxserver/jackett
Version: Jackett Version v0.20.671 
FlareSolverr: Self hosted
```

### Description

Just launch the test for LostFilm.tv, there are an error. But if you try to search for specific show in LostFilm.tv in Jackett, search is working. Seems that test contains some kind of bug. Site is working okay https://www.lostfilmtv5.site/

### Logged Error Messages

```text
System.Exception: Test search in LostFilm.tv => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 311
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
the TEST for the indexer uses this path: `https://www.lostfilmtv2.site/new`
however the website returns http 200 but with the following payload `...`
so we need to check if the web site has a new `recent` page, or if its just a temporary issue, or if we need to find some alternate way of providing new results for keywordless searches (which is what the TEST in essence is doing)

**Comment by garfield69** [comment]
Bah. the latest releases is still the `/new` page, so its not clear to me what the problem is.
And its a C# indexer so I'm reluctant to get into it, its not my cup of tea.
PR welcome.

**Comment by SuberSeb** [comment]
For me the /new page returning no useful payload. How you get list of latest releases?

**Comment by garfield69** [comment]
just visited the site and clicked on the new link
![image](https://user-images.githubusercontent.com/6933240/157191953-78378c96-7107-46fb-bc74-b06a0a0b73d2.png)

**Comment by SuberSeb** [comment]
Can you please try that link? https://www.lostfilmtv5.site/new

Is there any output?

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/157192838-e9372ebb-f484-4eb5-9837-0d9e8d1a0097.png)

**Comment by SuberSeb** [comment]
🤔

This is very strange. And you still getting error while testing with new link?

**Comment by garfield69** [comment]
![image](https://user-images.githubusercontent.com/6933240/157193861-0d8275bd-8c5b-4f1c-afc9-0390884fa02c.png)

**Comment by garfield69** [comment]
v0.20.681
