### ISSUE TITLE
[spidertk] Login failed: No form found on https://spidertk.xyz/login.php using form selector form[action=

### ISSUE THREAD

**Issue by thegrunge36** [Jackett/Jackett#13035]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Unbuntu 20.0
Flaresolverr
Jackett
Ombi
Sonarr
Radarr
```

```
2022-03-09 15:33:01.8023 Info Starting Jackett v0.20.681 
2022-03-09 15:33:02.5013 Info Environment version: 6.0.3 (/home/jonathan/Jackett/) 
2022-03-09 15:33:02.5013 Info OS version: Unix 5.13.0.35 (64bit OS) (64bit process) 
2022-03-09 15:33:02.5013 Info Jackett variant: CoreLinuxAmdx64 
2022-03-09 15:33:02.5013 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
2022-03-09 15:33:02.5013 Info Running in Docker: No 
2022-03-09 15:33:02.5043 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2022-03-09 15:33:02.5043 Info App config/log directory: /home/jonathan/.config/Jackett 
2022-03-09 15:33:02.5043 Info Using proxy: Disabled 
2022-03-09 15:33:02.5043 Info Using FlareSolverr: http://localhost:8191/ 
2022-03-09 15:33:02.5043 Info Using HTTP Client: HttpWebClient2 
```

### Description

Hello, I can no longer connect to a tracker with jackett. I don't know why I only somater ubuntu and since then it doesn't work only for him..

Thanks if you can enlighten me!

### Logged Error Messages

```text
2022-03-09 14:57:56	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://spidertk.xyz/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 577
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 972
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
spidertk has a captcha which means that you occasionally need to refresh the config with the new captcha code when the session cookie expires.
if that is not the issue then you need to turn on the Jackett enhanced logging so you can capture more of the traffic between Jackett and the website. Hopefully the extra Debug and HTML in the log will provide a clue to your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by thegrunge36** [comment]
Strangely I have no capcha to enter....

![Spider](https://user-images.githubusercontent.com/32209587/157529860-52661ba9-b49d-43f7-8447-e4a909fd2711.png)

**Comment by thegrunge36** [comment]
Here is the complete log after activating Enhanced logging.
Thank you!

[log.txt](https://github.com/Jackett/Jackett/files/8218051/log.txt)

**Comment by ilike2burnthing** [comment]
Removed your log as it contained credentials for various trackers. Read the instructions in the link garfield69 gave you, redact anything sensitive.

It will also make things a lot easier if you delete, rename, or move your current logs before enabling enhanced logging, recreate your issue, and then post just that (redacted) log.

**Comment by thegrunge36** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/8219273/log.txt)

**Comment by ilike2burnthing** [comment]
Again, please read the instructions for providing an **enhanced log** - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by thegrunge36** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/8219383/log.txt)

**Comment by garfield69** [comment]
```html
<h2>Login Vérouillé! Le nombre maximum de tentatives Login  est atteint lors de la réauthentification</h2>
<table width="100%" border="1" cellspacing="0" cellpadding="10"><tr><td class="text">Nous en venons à croire que vous essayez de tromper notre système, nous avons donc banni votre adresse IP!</td></tr></table></td></tr></table>
```

you have generated too many failed login attempts and your ip has been banned.

**Comment by thegrunge36** [comment]
ok thank you I will communicate with the tacker who himself did not understand

**Comment by thegrunge36** [comment]
Hello, I checked with eu and my ip was banned because I made 10 connection attempts. The problem remains that I do not see the captcha to enter. I tried with chrome and firefox.
![Spider](https://user-images.githubusercontent.com/32209587/157665695-8babadee-fb8b-4221-a9e6-78c28fd96bfb.png)

**Comment by thegrunge36** [comment]
Hello, the captcha appeared today as if by magic! I don't know if it can have a link with a banned ip...

Thank you!

**Comment by SuissoNaBisso9** [comment]
Yes same issue here, I had the error no login form found, then saw ths post so I did the CAPTCHA thing and then reworked, but since few days it's not working anymore and on the tracker setting on Jackett, I don't see the CAPTCHA field anymore, anything I should do to get this field back in the settings ?
Thanks

**Comment by thegrunge36** [comment]
> Yes same issue here, I had the error no login form found, then saw ths post so I did the CAPTCHA thing and then reworked, but since few days it's not working anymore and on the tracker setting on Jackett, I don't see the CAPTCHA field anymore, anything I should do to get this field back in the settings ? Thanks

Hi please update flaresolverr on the last version, and i also update Jackett yesterday to fix an error with Xthor.
