### ISSUE TITLE
[iptorrents] Your cookie did not work, make sure the user agent matches your computer: The cookies provided by FlareSolverr are not valid (Config)

### ISSUE THREAD

**Issue by JReverse** [Jackett/Jackett#13047]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-03-11 23:31:28	Info	
Using HTTP Client: HttpWebClient2
2022-03-11 23:31:28	Info	
Using FlareSolverr: No
2022-03-11 23:31:28	Info	
Using proxy: Disabled
2022-03-11 23:31:28	Info	
App config/log directory: /home/justxn/.config/Jackett
2022-03-11 23:31:28	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-03-11 23:31:28	Info	
Running in Docker: No
2022-03-11 23:31:28	Info	
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-03-11 23:31:28	Info	
Jackett variant: CoreLinuxAmdx64
2022-03-11 23:31:28	Info	
OS version: Unix 5.4.0.104 (64bit OS) (64bit process)
2022-03-11 23:31:28	Info	
Environment version: 6.0.3 (/home/justxn/Jackett/)
2022-03-11 23:31:27	Info	
Starting Jackett v0.20.696
```

### Description

login to ipttorent fresh click the /t in network cooy info

### Logged Error Messages

```text
System.Exception: Your cookie did not work, make sure the user agent matches your computer: The cookies provided by FlareSolverr are not valid
   at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 194
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, String matchedPath, String remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
```text
The cookies provided by FlareSolverr are not valid
```

```text
Using FlareSolverr: No
```

These don't match up. Are you using FlareSolverr? Do you have configured in Jackett? If not, see https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured

**Comment by JReverse** [comment]
2022-03-13 07:04:46 | Info | Using HTTP Client: HttpWebClient2
2022-03-13 07:04:46 | Info | Using FlareSolverr: http://51.255.5.108:8191/
2022-03-13 07:04:46 | Info | Using proxy: Disabled
2022-03-13 07:04:46 | Info | App config/log directory: /home/justxn/.config/Jackett
2022-03-13 07:04:46 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-03-13 07:04:46 | Info | Running in Docker: No
2022-03-13 07:04:46 | Info | File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-03-13 07:04:46 | Info | Jackett variant: CoreLinuxAmdx64
2022-03-13 07:04:46 | Info | OS version: Unix 5.4.0.104 (64bit OS) (64bit process)
2022-03-13 07:04:46 | Info | Environment version: 6.0.3 (/home/justxn/Jackett/)
2022-03-13 07:04:45 | Info | Starting Jackett v0.20.703





Still not working

**Comment by garfield69** [comment]
>login to ipttorent fresh click the /t in network cooy info

Not familiar with this method. Are you using the **Development Tools** **Network** menu, the **Headers** tab, scrolling down to the **Request Headers** section, and selecting the whole string after the `cookie: `?
And the same for the `user-agent: ` further down?

**Comment by JReverse** [comment]
@garfield69 yes i followed the guide jacket gives

**Comment by garfield69** [comment]
Have you tried using any of the alternate sitelinks in the Jackett indexer config, with the corresponding cookie/user-agent for those alternates?

**Comment by JReverse** [comment]
https://ipt.beelyrics.net/ works

**Comment by garfield69** [comment]
\o/

**Comment by jaum20** [comment]
gad the samem problem, changed to https://ipt.beelyrics.net/ and now it is working

**Comment by Soljia** [comment]
Same, https://ipt.beelyrics.net/  works for me.
