### ISSUE TITLE
[Torrentleech] Connection Timeout

### ISSUE THREAD

**Issue by NHDriver4** [Jackett/Jackett#13064]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-03-18 18:34:10.2104 Info Starting Jackett v0.20.726 
2022-03-18 18:34:10.7364 Info Environment version: 6.0.3 (/app/Jackett/) 
2022-03-18 18:34:10.7364 Info OS version: Unix 5.4.0.104 (64bit OS) (64bit process) 
2022-03-18 18:34:10.7364 Info Jackett variant: CoreLinuxAmdx64 
2022-03-18 18:34:10.7364 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
2022-03-18 18:34:10.7364 Info Running in Docker: Yes (image build: v0.20.726-ls58) 
2022-03-18 18:34:10.7364 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2022-03-18 18:34:10.7364 Info App config/log directory: /config/Jackett 
2022-03-18 18:34:10.7402 Info Using proxy: Disabled 
2022-03-18 18:34:10.7402 Info Using FlareSolverr: No 
2022-03-18 18:34:10.7402 Info Using HTTP Client: HttpWebClient2 
2022-03-18 18:34:10.7464 Info Loading Native indexers ...
```

### Description

Torrentleech is not longer working with Jackett. Getting The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. There was a post on the torrentleech forums where a staff member indicated that there have been no recent changes to the tracker site that would have impacted this operation. I am using the ghcr.io/linuxserver/jackett docker image.

Steps:
Add Torrentleech tracker and attempt to save.

### Logged Error Messages

```text
2022-03-18 18:29:14.8351 Debug Connection id "0HMG929AJBVQJ" accepted. 
2022-03-18 18:29:14.8429 Debug Connection id "0HMG929AJBVQJ" started. 
2022-03-18 18:29:14.8429 Info Request starting HTTP/1.1 POST http://jackett.*******.com/api/v2.0/indexers/torrentleech/test - 0 
2022-03-18 18:29:14.8429 Debug Request is continuing in applying rules. Current url is http://jackett.*******.com/api/v2.0/indexers/torrentleech/test 
2022-03-18 18:29:14.8429 Debug Request is continuing in applying rules. Current url is http://jackett.*******.com/api/v2.0/indexers/torrentleech/test 
2022-03-18 18:29:14.8438 Debug Request is continuing in applying rules. Current url is http://jackett.*******.com/api/v2.0/indexers/torrentleech/test 
2022-03-18 18:29:14.8438 Debug POST requests are not supported 
2022-03-18 18:29:14.8438 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2022-03-18 18:29:14.8438 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/torrentleech/test' 
2022-03-18 18:29:14.8438 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/torrentleech/test' 
2022-03-18 18:29:14.8438 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2022-03-18 18:29:14.8438 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2022-03-18 18:29:14.8438 Info Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2022-03-18 18:29:14.8438 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2022-03-18 18:29:14.8438 Debug Execution plan of resource filters (in the following order): None 
2022-03-18 18:29:14.8438 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2022-03-18 18:29:14.8438 Debug Execution plan of exception filters (in the following order): None 
2022-03-18 18:29:14.8438 Debug Execution plan of result filters (in the following order): None 
2022-03-18 18:29:14.8438 Debug Authorization was successful. 
2022-03-18 18:29:14.8438 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-03-18 18:29:14.8438 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-03-18 18:29:14.8438 Debug CACHE PruneCacheByTtl / Pruned queries: 0 
2022-03-18 18:29:14.8438 Debug CACHE Status / Total cached results: 200 
2022-03-18 18:29:14.8438 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.torrentleech.org/torrents/browse/list/exact/1/query//newfilter/2/orderby/added/order/desc) 
2022-03-18 18:30:14.8733 Debug Connection id "0HMG929AJBVQJ" received FIN. 
2022-03-18 18:30:14.8733 Debug Connection id "0HMG929AJBVQJ" sending FIN because: "The client closed the connection." 
2022-03-18 18:30:14.8733 Debug Connection id "0HMG929AJBVQJ" disconnecting. 
2022-03-18 18:30:54.8511 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 100004.96ms 
2022-03-18 18:30:54.8511 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2022-03-18 18:30:54.8519 Error Jackett.Common.IndexerException: Exception (torrentleech): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1383
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 771
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.IndexerException: Exception (torrentleech): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1383
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 771
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 306
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2022-03-18 18:30:54.8629 Debug The response will be compressed with 'gzip'. 
2022-03-18 18:30:54.8629 Info Request finished HTTP/1.1 POST http://jackett.*******.com/api/v2.0/indexers/torrentleech/test - 0 - 500 - application/json 100020.0728ms 
2022-03-18 18:30:54.8629 Debug Connection id "0HMG929AJBVQJ" stopped.
```

### Screenshots

![YUsHVNOJ3L](https://user-images.githubusercontent.com/49725/159093420-545677b9-f153-45c2-8c00-573ad2db31c5.png)

**Comment by garfield69** [comment]
The torrentleech indexer is working for me which suggest the issue is at your end.
can you use a browser on the same machine that is running Jackett to access the site?
a task cancelled is usually due to something blocking access.
see https://github.com/Jackett/Jackett/wiki/TroubleShooting/#a-connection-attempt-failed and see if that helps figure out what is going on.

**Comment by garfield69** [comment]
ah, your are on docker. 
so for the part about using a browser to check to site, do instead:
Try accessing the docker image via your terminal and doing a curl and openssl from within the image 
```
docker exec -it jackett /bin/bash
```
and see what you get from the following:
```
openssl s_client -connect www.torrentleech.org:443
```
and
```
curl -vvv https://www.torrentleech.org/
```

**Comment by NHDriver4** [comment]
Yes, I am using the ghcr.io/linuxserver/jackett docker image. Sorry for not mentioning that.

The curl works just fine, ending with Connection #0 to host www.torrentleech.org left intact. It displays the raw html from the login page.

The openssl command is not doing anything. It just hangs there. I tried the command to another SSL host, and it replied right away. 

I do have IPv6 on this host, not sure if that would interfere or not? I'd assume not, since the curl with https worked.

**Comment by garfield69** [comment]
I am aware of an issue with docker and ipv6 and open_ssl, which is what Jackett uses too on linux.
have a read of https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established and see if you can make it work.

**Comment by NHDriver4** [comment]
Disabling ipv6 on the container worked, thanks so much!

For anyone else, here's what I added to my docker compose:

sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
