### ISSUE TITLE
[xthor-api] Exception (xthor-api): Object reference not set to an instance of an object.: Object reference not set to an instance of an object. (Test)

### ISSUE THREAD

**Issue by thegrunge36** [Jackett/Jackett#13086]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Flaresolverr 2.2.2
Ubuntu 20.04
```

### Description

Jackett cannot add Xthor since 3 days

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (xthor-api): Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Models.TorznabQuery.MatchQueryStringAND(String title, Nullable`1 limit, String queryStringOverride) in /home/vsts/work/1/s/src/Jackett.Common/Models/TorznabQuery.cs:line 181
   at Jackett.Common.Indexers.CardigannIndexer.ParseRowFilters(List`1 Filters, ReleaseInfo release, TorznabQuery query, Dictionary`2 variables, Object Row) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 2083
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1463
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 415
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 771
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 434
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13083

**Comment by thegrunge36** [comment]
What i'm suposed to understand?

**Comment by garfield69** [comment]
>What i'm suposed to understand?

This ticket is a duplicate of #13083, and that the next release of Jackett due out in about 6 hours or so should have a fix. Albeit since its untested, if more issues crop up then raised them in the other open ticket. Thanks.
