### ISSUE TITLE
[gimmepeers] DateTime.: Parse error

### ISSUE THREAD

**Issue by psycik** [Jackett/Jackett#13115]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-04-05 17:37:46	Info	Using HTTP Client: HttpWebClient2
2022-04-05 17:37:46	Info	Using FlareSolverr: No
2022-04-05 17:37:46	Info	Using proxy: Disabled
2022-04-05 17:37:46	Info	App config/log directory: /config/Jackett
2022-04-05 17:37:46	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-04-05 17:37:46	Info	Running in Docker: Yes (image build: unknown)
2022-04-05 17:37:46	Info	File /etc/issue: Arch Linux \r (\l)
2022-04-05 17:37:46	Info	Jackett variant: CoreLinuxAmdx64
2022-04-05 17:37:46	Info	OS version: Unix 5.10.28.0 (64bit OS) (64bit process)
2022-04-05 17:37:46	Info	Environment version: 6.0.2 (/usr/lib/jackett/)
2022-04-05 17:37:46	Info	Jackett Data will be stored in: /config/Jackett
2022-04-05 17:37:46	Info	Starting Jackett v0.20.781
```

### Description

gimmepeers is not working, tried deleting to re-add and cannot add it any longer either.

### Logged Error Messages

```text
2022-04-05 17:53:50	Error	
Jackett.Common.IndexerException: Exception (gimmepeers): String '2022-04-05 20:21:4' was not recognized as a valid DateTime.
 ---> System.Exception: Parse error
 ---> System.FormatException: String '2022-04-05 20:21:4' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(ReadOnlySpan`1 s, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider, DateTimeStyles style)
   at Jackett.Common.Indexers.GimmePeers.PerformQuery(TorznabQuery query) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/GimmePeers.cs:line 191
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/BaseIndexer.cs:line 794
   at Jackett.Common.Indexers.GimmePeers.PerformQuery(TorznabQuery query) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/GimmePeers.cs:line 209
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/BaseIndexer.cs:line 768
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Services/IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2022-04-05 17:53:50	Error	
Error on 20220405175350 for GimmePeers.txtSystem.FormatException: String '2022-04-05 20:21:4' was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(ReadOnlySpan`1 s, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider, DateTimeStyles style)
   at Jackett.Common.Indexers.GimmePeers.PerformQuery(TorznabQuery query) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/GimmePeers.cs:line 191


2022-04-05 17:53:42	Error	
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.GimmePeers.<>c__DisplayClass8_0.<ApplyConfiguration>b__0() in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/GimmePeers.cs:line 119
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.GimmePeers.ApplyConfiguration(JToken configJson) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Common/Indexers/GimmePeers.cs:line 114
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /tmp/makepkg/jackett/src/Jackett-0.20.781/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
None of the current team have an account on this site so we cannot test independently.
It appears that on the site there is a torrent with an invalid date `2022-04-05 20:21:4` which is tripping the indexer up.
Can you provide a dump of the web site's torrent search page  so we can confirm its just a single instance of a date error, or if there has been some sort of change in the html layout that is tripping up the indexer ?
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source for details.
Thanks.

**Comment by psycik** [comment]
[gimmie.txt](https://github.com/Jackett/Jackett/files/8422999/gimmie.txt)
Thanks, attached.

**Comment by garfield69** [comment]
Seems that there has been a layout change to the published date timestamp, with an extra `&nbsp;` inserted between the date and time 
```HTML
<td align=center>&nbsp;2022-04-05&nbsp;&nbsp;20:21:43&nbsp;<br><font size=1>(40 minutes ago)</font></td>
```

I'll see if I can amend the indexer code to compensate.

**Comment by garfield69** [comment]
v0.20.805

**Comment by psycik** [comment]
Can confirm this is fixed. Thanks.
