### ISSUE TITLE
[yggtorrent] Resource temporarily unavailable (www3.yggtorrent.re:443): Resource temporarily unavailable (Config)

### ISSUE THREAD

**Issue by cmoi936** [Jackett/Jackett#13123]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using Jackett v0.20.805 in docker container : 
"env_variables" :  
     "TZ": "Europe/Paris"
     "GUID": "1000"
     "PUID":"1000"
     "PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
     "HOME":"/root"
     "LANGUAGE":"en_US.UTF-8"
     "LANG":"en_US.UTF-8"
     "TERM":"xterm"
     "XDG_DATA_HOME":"/config"
     "XDG_CONFIG_HOME":"/config"
"port_bindings" : [
      {
         "container_port" : 9117,
         "host_port" : 9117,
         "type" : "tcp"
      }
   ],
"privileged" : false
```

### Description

FlareSolverr Container runs on 10.0.0.2:8191.
I have set the url to use flaresolver in jackett .
When adding the indexer "YGGTorrent" with my credentials on error pops.
(I success to access yggtorrent.re and success to login with my credentials into the website.)
Flaresolverr seems not to be called.

In result, the indexer "yggTorrent" is not added..

Am I doing something wrong ?

### Logged Error Messages

```text
System.Net.Http.HttpRequestException: Resource temporarily unavailable (www3.yggtorrent.re:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 896
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 567
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 972
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

FlareSolverr running
![image](https://user-images.githubusercontent.com/88500931/162293881-42b501e2-7658-4f52-b3be-8d8459a91e6a.png)

flaresolver in jackett : 
![image](https://user-images.githubusercontent.com/88500931/162294948-f95eff2c-3f25-401b-a3df-d78fbfdd24fb.png)

"YGGTorrent" with my credentials: 
![image](https://user-images.githubusercontent.com/88500931/162299140-980aed1c-c849-4521-8cc6-2545011d5d81.png)

Error pops : 
![image](https://user-images.githubusercontent.com/88500931/162299507-8c8f55c9-9728-47ec-bd73-09296d0c1f7b.png)

Flaresolverr logs, no calls to yggtorrent.re :
![image](https://user-images.githubusercontent.com/88500931/162302657-6335e37f-fddd-41ec-bd8d-0279d27de5cc.png)

**Comment by ilike2burnthing** [comment]
Connection is ok here*. Can you access the site in browser from the same device and IP as Jackett, using the same DNS? Are you using a VPN? Are other Jackett indexers working for you?

Please see the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

*ok in that I can connect to it, it still has issues - https://github.com/FlareSolverr/FlareSolverr/issues/355

**Comment by cmoi936** [comment]
Ok from the container jackett : 
```
root@linuxserver-jackett1:/# curl https://yggtorrent.re                                                                     
curl: (6) Could not resolve host: yggtorrent.re 
```

```
root@linuxserver-jackett1:/# curl https://google.fr                                                                         
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">                                              
<TITLE>301 Moved</TITLE></HEAD><BODY>                                                                                       
<H1>301 Moved</H1>                                                                                                          
The document has moved   
[...]   
```           
I have change the DNS into my router to use CloudFlare's DNS : 
primary : 1.1.1.1
secondary : 1.0.0.1

And then it works ! :)
```
root@linuxserver-jackett1:/# curl https://yggtorrent.re                                                                     
<!DOCTYPE HTML>                                                                                                             
<html lang="en-US">                                                                                                         
<head>                                                                                                                      
  <meta charset="UTF-8" />                                                                                                  
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />                                                     
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />                                                          
  <meta name="robots" content="noindex, nofollow" />                                                                        
  <meta name="viewport" content="width=device-width,initial-scale=1" />                                                     
  <title>Just a moment...</title>                                                                                           
  <style type="text/css">                                 
```

I also confirm that now i can add the indexer "YggTorrent".

**Comment by cmoi936** [comment]
This issue can be closed. :)
