### ISSUE TITLE
[bjshare] Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings. (Config)

### ISSUE THREAD

**Issue by bpbastos** [Jackett/Jackett#13144]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
04-14 11:04:28 Info Starting Jackett v0.20.865
04-14 11:04:29 Info Environment version: 6.0.4 (/app/Jackett/)
04-14 11:04:29 Info OS version: Unix 4.15.0.137 (64bit OS) (64bit process)
04-14 11:04:29 Info Jackett variant: CoreLinuxAmdx64
04-14 11:04:29 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l
04-14 11:04:29 Info Running in Docker: Yes (image build: v0.20.865-ls61)
04-14 11:04:29 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
04-14 11:04:29 Info App config/log directory: /config/Jackett
04-14 11:04:29 Info Using proxy: Disabled
04-14 11:04:29 Info Using FlareSolverr: No
04-14 11:04:29 Info Using HTTP Client: HttpWebClient2
04-14 11:04:29 Info Loading Native indexers ...
04-14 11:04:29 Info Loaded 84 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, avistaz, bakabt, bb, beyond-hd-api, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, greatposterwall, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, morethantv, myanonamouse, ncore, nebulance, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, ShizaProject, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentmafya, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, zonaq, animetosho, morethantv-api
04-14 11:04:29 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
04-14 11:04:31 Info Loaded 497 Cardigann indexers: moviesite, torrenthr, xbytesv2, jpopsuki, yourbittorrent, greekteam, slosoul, torrentsurf, houseofdevil, aniRena, miobt, cpasbienclone, noname-clubl, extremebits, madsrevolution, lesaloon, teamctgame, torrentdownloads, bt4g, scenerush, empornium2fa, theaudioscene, linkomanija, ebookparadijs, exttorrents, bithorlo, redbits-api, prostylex, kinonavse100, tlfbits, sharewood, pornolive, netlab, alleenretail, bwtorrents, cathoderaytube, xbit, mircrew, exkinoray, u2, moviesdvdr, rutor, ourbits, frozenlayer, pornleech, selezen, xthor-api, torrentleech-pl, anime-free, siambit, metaltracker, hqsource, dmhy, pwtorrents, anilibria, torrentdb, milkie, muziekfabriek, zelkaorg, aither-api, extremetorrents, microbit, torrent-explosiv, torrentccf, xwtclassics, peeratiko, rintor, aftershock, femdomcult, tekno3d, hdsky, elitetorrent-biz, learnbits, chdbits, torrentseeds-api, finvip, gamestorrents, backups, ptsbao, ebooks-shares, xwtorrents, mixtapetorrent, yggcookie, cpasbien, thefallingangels, fouducinema, girotorrent, torrentsectorcrew, underverse, lemonhd, torrentslocal, bitsexy, gaytorrentru, skipthecommercials-api, jav-torrent, shareisland-api, hdatmos, idope, soundpark, dark-shadow, leech24, tvroad, tvchaosuk, hdcity, acgsou, limetorrents, xxxtor, demonoid, bithumen, bigfangroup, putao, greekdiamond, theshinning, torrentfunk, theshow, bibliotik, generationfree-api, animeworld-api, borgzelle, zooqle, oxtorrent, sdbits, sukebeinyaasi, p2pelite, mvgroupmain, vsthouse, hdzone, ibit, docspedia, totheglorycookie, nyaasi, crazyspirits, isohunt2, piratbitl, torrent-turk, mononokebt, aidoruonline, hdarea, animeitalia, iv-torrents, gtorrentpro, woot, 4thd, divteam, thenewfun, nitro, mteamtp2fa, bitbazis, newretro, bitbr, uhdbits, haidan, pthome, sugoimusic, torrentbd, hdspain, brsociety-api, xxxadulttorrent, hidden-palace, ceskeforum, ptfiles, mnv, nipponsei, rptorrents, byrutor, torrentby, uniondht, hdu, puntotorrent, audiobookbay, torrent9, extremlymtorrents, animeclipse, eztv, hdcztorrent, hdbitscom, anaschcc, lat-team-api, rgfootball, gfxpeers, hdc, torrentview, teamhd, torrentqq, torrentland-api, aussierules, netcosmo, tasmanit, theempire, racingforme, mypornclub, concertos, btsow, pttime, chilebt, r3vwtf, resurrectthenet, ftuapps, mactorrentsdownload, potuk, xiteme, spiritofrevolution, ilcorsaroblu, hellastz, hdroute, extratorrent-st, finelite, pornbay, hdolimpo-api, esharenet, unionfansub, discfan, the-crazy-ones, acgrip, crnaberza, limetorrentsclone, totallykids, torrentsir, zamundanet, eniahd, torlock, riperam, 24rolika, classix, cinemamovies, spidertk, polishsource, RockBox, gay-torrentsorg, teracod, thepiratebay, empornium, torrentwhiz, boxingtorrents, purovicio, ccfbits, kinorun, torrentmasters, btdigg, bitsearch, hdbits, solidtorrents, desitorrents-api, racing4everyone-api, diablotorrent, hdonly, rapidzona, coastalcrew, noname-club, sporthd, theplace, whiteangel, krazyzone, myspleen, glodls, fantastiko, bitcityreloaded, byrbt, nbtorrents, puurhollands, thevault, linuxtracker, datascene-api, wihd, gay-torrents, fantasticheaven, hawke-uno, bestcore, mma-torrents, soulvoice, turkseed, pornbits, datatalli, btschool, turktracker, rutracker-ru, 1ptbar, deildu, rudub, pterclub, sosulki, torrentproject2, trezzor, asiancinema, acrossthetasman, carphunter, redstartorrent, hd4fans, fenyarnyek-tracker, themixingbowl, hdhome, digitalcore, mikan, 0daykiev, cinematik, kickasstorrents-to, underversel, springsunday, hdcenter, amigosshare, freshmeat, lastfiles, tapochek, pctorrent, crazyhd, libranet, bluesbrothers, kinozal, torrent-pirat, itorrent, firebit, torrentdownload, speedmasterhd, dragonworldreloaded, keepfriends, tjupt, tokyotosho, newstudio, romanianmetaltorrents, torrent9clone, tribalmixes, torrentv, dxp, badasstorrents, zetorrents, arabp2p, 3changtrai, hdturk, carpathians, pornforall, gktorrent, 3dtorrents, karagarga, rus-media, mediamaatjes, mesevilag, vizuk, hdai, yts, pixelcove, thehorrorcharnel, animelayer, wdt, pornotor, proaudiotorrents, lepornoinfo, dariustracker, 1337x, btetree, hdchina, hdtorrentsit, totheglory, broadcity, majomparade, audionews, peerjunkies, bangumi-moe, rintornet, ilcorsaronero, torrentoyunindir, zomb, punkshorror, hdtime, megapeer, mvgroupforum, bluebirdhd, filelisting, torrentz2eu, thesceneplace, speedtorrentreloaded, trancetraffic, comicat, dimeadozen, nntt, ztracker, cartoonchaos, brasiltracker, turktorrent, ptmsg, film-paleis, movietorrentz, concen, uniongang, nethd, onejav, cryptichaven, torrentgalaxy, p2pbg, opencd, rainbowtracker, acidlounge, crt2fa, showrss, hdme, teamos, twilightszoom, happyfappy, genesismovement, ilcorsaroverde, torrenting, fanoin, sexypics, parnuxi, booktracker, 52pt, jptv, estone, 0magnet, hddolby, vsttorrents, torrentkitty, mteamtp, bitru, insanetracker, legittorrents, mousebits, swarmazon, xxxtorrents, superbits, magico, omgwtftrackr, pier720, seedfile, newstudiol, theoccult, losslessclub, megamixtracker, piratadigital, jme-reunit3d-api, pornotorrent, sktorrent, bitded, skipthetrailers, oshenpt, hdmonkey, catorrent, beyond-hd, marinetracker, torrentleech, scenepalace, twilight, thegeeks, theleachzone, learnflakes, arenabg, piratbit, sktorrent-org, opensharing, abtorrents, pussytorrents, cinemageddon, falkonvisionteam, blutopia-api, crackingpatching, korsar, beitai, Bittorrentfiles, haitang, newpct-me, indietorrents, ydypt, bitspyder, 2fast4you, immortuos, kickasstorrents-ws, reelflix-api, proporno, btnext, hamsterstudio, magicheaven, movietorrent, trupornolabs, funkytorrents, portugas, arabafenice, ehentai, anisource, torrentlt, huntorrent, bitturk, torrentparadise, danishbytes-api, bootytape, gigatorrents, snowpt, torlook, sportscult, trackeros-api, pornoslab, tellytorrent-api, internetarchive, hdforever, ps4-torrent, unlimitz, rustorka, peersfm, yggtorrent
04-14 11:04:31 Info Loaded 581 indexers in total
04-14 11:04:31 Info Adding aggregate indexer ('all' indexer) ...
04-14 11:04:31 Info Adding filter indexer ('type:public' indexer) ...
04-14 11:04:31 Info Adding filter indexer ('type:private' indexer) ...
04-14 11:04:31 Info Adding filter indexer ('type:semi-public' indexer) ...
04-14 11:04:31 Info Jackett startup finished in 4.503 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
```

### Description

Flow the lead of the bjshare page in jackett, it should appear.

### Logged Error Messages

```text
04-14 11:06:42 Error Jackett.Common.IndexerException: Exception (bjshare): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
 ---> System.Exception: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
   at Jackett.Common.Indexers.BJShare.ParseLast24HoursAsync() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs:line 439
   at Jackett.Common.Indexers.BJShare.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs:line 246
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 768
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 308
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (bjshare): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
 ---> System.Exception: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
   at Jackett.Common.Indexers.BJShare.ParseLast24HoursAsync() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs:line 439
   at Jackett.Common.Indexers.BJShare.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs:line 246
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 768
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 308
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

![image](https://user-images.githubusercontent.com/7807596/163407970-badfbab0-54d6-43e6-ba01-983540a50b21.png)

**Comment by ilike2burnthing** [comment]
Did you tick the `Lembrar-me` box when logging in?

Is Jackett on the same device and using the same IP as you used to get the cookie?

**Comment by bpbastos** [comment]
> kett on the same device and using the same IP as you used to get the cookie?

Yes, I've tick the "Lembrar-me" box and no, jackett is running on a headless server (Kubernetes)

**Comment by ilike2burnthing** [comment]
Is there anything in your bjshare account settings about locking your account to a single IP? If so, disable it, log out and log back in again, and use that new cookie.

If there is no option, as a test try a local install of Jackett to see if it at least works.

**Comment by bpbastos** [comment]
> Is there anything in your bjshare account settings about locking your account to a single IP? If so, disable it, log out and log back in again, and use that new cookie.
> 
> If there is no option, as a test try a local install of Jackett to see if it at least works.

Unfortunately no, it used to work, stopped last week. I'll try to up Jackett locally to see if it solves the problem.

**Comment by bpbastos** [comment]
I was using Edge browser and it was copying the session cookie value clean (url decoded) need to be encoded to work.
