### ISSUE TITLE
[demonoid] (testing) Test search in Demonoid => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by triantos** [Jackett/Jackett#13203]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-04-26 19:37:12	Info	
Loading Native indexers ...
2022-04-26 19:37:12	Info	
Using HTTP Client: HttpWebClient2
2022-04-26 19:37:12	Info	
Using FlareSolverr: No
2022-04-26 19:37:12	Info	
Using proxy: Disabled
2022-04-26 19:37:12	Info	
App config/log directory: /home/vpn/.config/Jackett
2022-04-26 19:37:12	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-04-26 19:37:12	Info	
Running in Docker: No
2022-04-26 19:37:12	Info	
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-04-26 19:37:12	Info	
Jackett variant: CoreLinuxAmdx64
2022-04-26 19:37:12	Info	
OS version: Unix 5.4.0.109 (64bit OS) (64bit process)
2022-04-26 19:37:12	Info	
Environment version: 6.0.4 (/opt/Jackett/)
2022-04-26 19:37:10	Info	
Starting Jackett v0.20.961
```

### Description

Trying to add demonoid. I put in my login credentials and get the error "Found no results". When I manually browse via a web browser, it does work.

### Logged Error Messages

```text
2022-04-26 19:33:55	Error	
System.Exception: Test search in Demonoid => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 313
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2022-04-26 19:33:55	Info	
Test search in Demonoid => Found 0 releases
```

**Comment by triantos** [comment]
My mistake, I had the wrong demonoid theme. I missed that in the setup.
