### ISSUE TITLE
[rarbg] (testing) Test search in RARBG => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by rbaprado** [Jackett/Jackett#13207]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-04-27 11:21:03	Info	
Using HTTP Client: HttpWebClient2
2022-04-27 11:21:03	Info	
Using FlareSolverr: No
2022-04-27 11:21:03	Info	
Using proxy: Socks5
2022-04-27 11:21:03	Info	
App config/log directory: C:\ProgramData\Jackett
2022-04-27 11:21:03	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-04-27 11:21:03	Info	
Running in Docker: No
2022-04-27 11:21:03	Info	
Jackett variant: CoreWindows
2022-04-27 11:21:03	Info	
OS version: Microsoft Windows NT 10.0.22000.0 (64bit OS)
2022-04-27 11:21:03	Info	
Environment version: 6.0.4 (C:\ProgramData\Jackett\)
2022-04-27 11:21:00	Info	
Starting Jackett v0.20.929
```

### Description

Both Sonarr and Radarr were complaining about RARBG, so I went to test it in Jackett

### Logged Error Messages

```text
System.Exception: Test search in RARBG => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 313
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
It's an issue with RARBG's API, it will regularly fail but return 0 results rather than an actual error. Only solution is to retry, sometimes multiple times.

**Comment by amogusballsw** [comment]
is there a way to fix this?

**Comment by garfield69** [comment]
>is there a way to fix this?

This has been going on since April 2020. 
The Jackett RarBG indexer already has a rate limit and retry function.
It's likely a capacity issue and I suspect it will require a hardware upgrade at the RarBG server side.

**Comment by ilike2burnthing** [comment]
@amogusballsw are you able to access the same URL in browser on the same device and IP as Jackett? If not, try the alternate URLs for one which works for you in browser, or change your DNS, or use a VPN or proxy.

**Comment by garfield69** [comment]
This has now been mostly mitigated by #13287 beginning with Jackett v0.20.1158 onwards.
