### ISSUE TITLE
[ilcorsaronero] (testing) Test search in Il Corsaro Nero => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by DarkFighterLuke** [Jackett/Jackett#13215]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-04-25 00:20:49.7694 Info Environment version: 6.0.4 (C:\ProgramData\Jackett\) 
2022-04-25 00:20:49.7694 Info OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS) 
2022-04-25 00:20:49.7694 Info Jackett variant: CoreWindows 
2022-04-25 00:20:49.7694 Info Running in Docker: No 
2022-04-25 00:20:49.7741 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2022-04-25 00:20:49.7741 Info App config/log directory: C:\ProgramData\Jackett 
2022-04-25 00:20:49.7741 Info Using proxy: Disabled 
2022-04-25 00:20:49.7741 Info Using FlareSolverr: No 
2022-04-25 00:20:49.7741 Info Using HTTP Client: HttpWebClient2
```

### Description

When trying to test www.ilcorsaronero.in it returns `Test search in Il Corsaro Nero => Found no results while trying to browse this tracker`, but the site is available if you try to navigate into it with a browser.

To reach this site a VPN (multiple have been tried) has been used (both with Jackett and with the browser quoted before).

### Logged Error Messages

```text
System.Exception: Test search in Il Corsaro Nero => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 313
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
what domain are you using?
Ticket #986  shows https://ilcorsaronero.link/ returning Error 523 Origin is unreachable
so as far as I know the site is offline?

**Comment by garfield69** [comment]
I expect that www.ilcorsaronero.in is not an official domain but a clone, which means that under the skin the html is different from the official site, which is why the indexer does not work.
to check, it would be helpful if you turn on the jackett enhanced logging, so that you can lost the full log with the HTML and debug included. see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by DarkFighterLuke** [comment]
> which means that under the skin the html is different from the official site, which is why the indexer does not work

It was working until some days ago (about 5-6 days ago), but they are changing something in the HTML maybe.
I'll try to collect these enhanced logs.

**Comment by DarkFighterLuke** [comment]
> it would be helpful if you turn on the jackett enhanced logging, so that you can post the full log with the HTML and debug included

Here it is:
[log.txt](https://github.com/Jackett/Jackett/files/8586316/log.txt)

**Comment by garfield69** [comment]
Heh. The log shows that you turned on the enhanced option, but has no records of the test.
But never mind, found access via hideme.
So the indexer is expecting https://ilcorsaronero.in/advsearch.php?&category=1;2;3;4;5;6;7;8;9;13;14;15;16;18;19;20;&search=john&order=data&by=DESC&page=0 to work bet gets 404 Not Found
similarly, for keywordless TEST, the indexer uses https://ilcorsaronero.in/browse/0 and gets 404 Not Found

the *.in site uses https://www.ilcorsaronero.in/argh?search=john and so it is clearly very different.
When I have some free time later today I'll take a deeper look and try to determine if this site is the official site or a clone. If a clone we will not be changing this indexer, but may consider creating an new one for this site.

**Comment by DarkFighterLuke** [comment]
Ok thank you, let me know. If you need anything else just ask me.
In my opinion that's a clone, so, if this hypothesis gets confirmed, I think that I'll look for a separate indexer.

**Comment by ilike2burnthing** [comment]
*.in has been [mentioned](https://github.com/Jackett/Jackett/issues/986#issuecomment-1001177937) before, it was even very briefly [added](https://github.com/Jackett/Jackett/pull/12744) at one point but then [removed](https://github.com/Jackett/Jackett/pull/12748).

I've seen no evidence it's a legitimate (but, for some reason, altered) mirror, rather it just seems to be a clone.

**Comment by DarkFighterLuke** [comment]
> *.in has been [mentioned](https://github.com/Jackett/Jackett/issues/986#issuecomment-1001177937) before, it was even very briefly [added](https://github.com/Jackett/Jackett/pull/12744) at one point but then [removed](https://github.com/Jackett/Jackett/pull/12748).
> 
> I've seen no evidence it's a legitimate (but, for some reason, altered) mirror, rather it just seems to be a clone.

So how should I proceed now?

**Comment by ilike2burnthing** [comment]
Wait for the legitimate Il Corsaro Nero to come back, or switch to another indexer. If the original is not back up after 30 days we'll remove it, and at that point we can look creating a new indexer for the *.in clone.
