### ISSUE TITLE
[leech24] (updating) Login failed: Selector "a[href="account-logout.php"]" didn't match

### ISSUE THREAD

**Issue by JReverse** [Jackett/Jackett#13218]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-05-04 14:38:04 | Info | Using HTTP Client: HttpWebClient2
2022-05-04 14:38:04 | Info | Using FlareSolverr: REDACTED
2022-05-04 14:38:04 | Info | Using proxy: Disabled
2022-05-04 14:38:04 | Info | App config/log directory: /config/Jackett
2022-05-04 14:38:04 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-05-04 14:38:04 | Info | Running in Docker: Yes (image build: v0.20.989-ls62)
2022-05-04 14:38:04 | Info | File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-05-04 14:38:04 | Info | Jackett variant: CoreLinuxAmdx64
2022-05-04 14:38:04 | Info | OS version: Unix 5.4.0.109 (64bit OS) (64bit process)
2022-05-04 14:38:04 | Info | Environment version: 6.0.4 (/app/Jackett/)
2022-05-04 14:38:04 | Info | Starting Jackett v0.20.1005
```

### Description

Add cookie

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 830
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 973
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Please provide the environment information as requested.

Can you access the tracker in browser from the same device and IP, using the same DNS?

**Comment by JReverse** [comment]
@ilike2burnthing yes in browser it works

**Comment by garfield69** [comment]
The best way to provide the environment info is to restart Jackett, access the dashboard, view the log, and copy/paste replacing the example below with the last 10 Info lines at the bottom of the log.

**Comment by JReverse** [comment]
@garfield69 

2022-05-04 14:38:04 | Info | Using HTTP Client: HttpWebClient2
2022-05-04 14:38:04 | Info | Using FlareSolverr: REDACTED
2022-05-04 14:38:04 | Info | Using proxy: Disabled
2022-05-04 14:38:04 | Info | App config/log directory: /config/Jackett
2022-05-04 14:38:04 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-05-04 14:38:04 | Info | Running in Docker: Yes (image build: v0.20.989-ls62)
2022-05-04 14:38:04 | Info | File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-05-04 14:38:04 | Info | Jackett variant: CoreLinuxAmdx64
2022-05-04 14:38:04 | Info | OS version: Unix 5.4.0.109 (64bit OS) (64bit process)
2022-05-04 14:38:04 | Info | Environment version: 6.0.4 (/app/Jackett/)
2022-05-04 14:38:04 | Info | Starting Jackett v0.20.1005


@ilike2burnthing I already said yes...

**Comment by garfield69** [comment]
Ah, a docker user. complicates getting the cookie. 
@ilike2burnthing  I forget, what's the best way to fetch a cookie for use with a docker jackett indexer?

**Comment by ilike2burnthing** [comment]
@JReverse your browser is running on the same device Jackett container is running on? It's using the same IP and DNS as the Jackett container?

Can you share the format of your cookie? e.g.
`slidingDivf-xxxxx=show; PHPSESSID=xxxxx; pass=xxxxx; uid=nnn`

@garfield69 in this case it shouldn't really matter so long as the public IP is the same (not even sure that matters). I'm using a cookie for leech24 from a browser on my Windows machine for a Jackett container on my NAS.

**Comment by garfield69** [comment]
@JReverse Also identify the browser type, eg Chrome, Firefox, Opera, Edge, Vivaldi etc.
Did you use the crtl-c ctrl-v to copy paste or some other method?
Have you tried following https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work ?
@ilike2burnthing  I recall the firefox copy behaved differently from Chrome, something about encoded versus decoded based on browser type or was it copy/paste method, I forget which?

**Comment by ilike2burnthing** [comment]
Yea, Firefox will only return encoded (which is what we need), whereas Chromium-based browsers provide both.

Right-click > `Copy` (or highlight > Ctrl+C > Ctrl+V):

```text
color_mode=%7B%22color_mode%22%3A%22auto%22%2C%22light_theme%22%3A%7B%22name%22%3A%22light%22%2C%22color_mode%22%3A%22light%22%7D%2C%22dark_theme%22%3A%7B%22name%22%3A%22dark%22%2C%22color_mode%22%3A%22dark%22%7D%7D
```

Right-click > `Copy value`:

```text
color_mode={"color_mode":"auto","light_theme":{"name":"light","color_mode":"light"},"dark_theme":{"name":"dark","color_mode":"dark"}}
```

In the case of leech24 though, at least for me, it shouldn't make a difference.

**Comment by JReverse** [comment]
PHPSESSID=XX; pass=XX; uid=XX

**Comment by ilike2burnthing** [comment]
Please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by JReverse** [comment]
[leech24 _ Login.zip](https://github.com/Jackett/Jackett/files/8642540/leech24._.Login.zip)

**Comment by ilike2burnthing** [comment]
Think you might have misunderstood, I need the enhanced Jackett log of your issue, not an HTML dump of the site.

**Comment by JReverse** [comment]
@ilike2burnthing 
![image](https://user-images.githubusercontent.com/40630518/168847594-133f1c68-3126-4e2d-a108-6f20ec044c81.png)

bro i followed the exact guide ...

**Comment by ilike2burnthing** [comment]
Enhanced logs will include `Debug` entries, including the HTML of any response, not just `Info` and `Warn`. After applying the settings make sure that the `Enhanced logging` box is still ticked; if it isn't try again.

**Comment by JReverse** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/8710158/log.txt)
@ilike2burnthing try this

**Comment by ilike2burnthing** [comment]
Well that was annoyingly unhelpful:

```text
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://leech24.net/)
WebClient(HttpWebClient2): Returning OK => 0 bytes
```

From within the container run `curl -v https://leech24.net/account-login.php` and post the output here.

Also, please provide the answers to the previously asked questions:

> @JReverse your browser is running on the same device Jackett container is running on? It's using the same IP and DNS as the Jackett container?

Keep in mind that we know very little about your setup, you could be using a VPS or seedbox in a different country but pulling the cookie from your home computer, so the answer of _"in browser it works"_ doesn't really help us with your issue.

**Comment by JReverse** [comment]
[leech24.txt](https://github.com/Jackett/Jackett/files/8711420/leech24.txt)

Steps how i installed

Bought a hetzner cx11
Installed docker
Attempted to add leech24
Failed to add at the okay button giving that error

**Comment by ilike2burnthing** [comment]
Ok, so the VPS can access the site but the cookie isn't working.

As test, install Jackett locally and see if leech24 works for you.

If so, you'll need to pull a cookie from the same IP as your Hetzner Jackett install. If you're able to install and use a browser then that's easily done, otherwise see the last few notes here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

**Comment by JReverse** [comment]
solved using https://github.com/Nyr/wireguard-install on same box and connecting via pc if anyone has this issue do that 👍
