### ISSUE TITLE
[zooqle] (testing) Exception (zooqle): Request to https://zooqle.com/search?s=dt&v=t&sd=d&q=%20* failed (Error 522) - The tracker seems to be down.: Request to https://zooqle.com/search?s=dt&v=t&sd=d&q=%20* failed (Error 522) - The tracker seems to be down.

### ISSUE THREAD

**Issue by rafi-d** [Jackett/Jackett#13229]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-05-07 12:50:12 	Info 	

Loading Native indexers ...

2022-05-07 12:50:12 	Info 	

Using HTTP Client: HttpWebClient2

2022-05-07 12:50:12 	Info 	

Using FlareSolverr: No

2022-05-07 12:50:12 	Info 	

Using proxy: Disabled

2022-05-07 12:50:12 	Info 	

App config/log directory: C:\ProgramData\Jackett

2022-05-07 12:50:12 	Info 	

ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads

2022-05-07 12:50:12 	Info 	

Running in Docker: No

2022-05-07 12:50:12 	Info 	

Jackett variant: CoreWindows

2022-05-07 12:50:12 	Info 	

OS version: Microsoft Windows NT 10.0.19042.0 (64bit OS)

2022-05-07 12:50:12 	Info 	

Environment version: 6.0.4 (C:\ProgramData\Jackett\)

2022-05-07 12:50:11 	Info 	

Starting Jackett v0.20.1024
```

### Description

Hi,
The issue is not Zoogle being off-line , but more that doing Aggregate search request from the client (pymedusa using "all/" ) it is showing  getting "undefined response"  from Jackett, and I suspect (but not sure) it might be related to this single provider timeout (out of them all)?

Thanks

Rafi

PS: Seting any single provider - works fine. Is it possible to define per-server (or global) timeout for Jackett?

### Logged Error Messages

```text
2022-05-07 12:53:54 	Error 	

Jackett.Common.IndexerException: Exception (zooqle): Request to https://zooqle.com/search?s=dt&v=t&sd=d&q=%20* failed (Error 522) - The tracker seems to be down.
 ---> System.Exception: Request to https://zooqle.com/search?s=dt&v=t&sd=d&q=%20* failed (Error 522) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 558
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 511
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1390
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 308
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 320
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 675
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 308
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://user-images.githubusercontent.com/2458280/167249423-434d8d80-7937-4feb-a882-c5596bce01dc.png)

![image](https://user-images.githubusercontent.com/2458280/167249357-2bbd0d6b-3955-4ae0-b598-11d98f1c2fb0.png)

![image](https://user-images.githubusercontent.com/2458280/167249377-f021d6a2-780b-4fdf-ad15-dbcc714dda80.png)

**Comment by ilike2burnthing** [comment]
Don't use `all` aggregate search - https://github.com/Jackett/Jackett#aggregate-indexers

If for some reason you 'must' use `all`, use filters to avoid down or otherwise excluded indexers - https://github.com/Jackett/Jackett#filter-indexers
