### ISSUE TITLE
xthor indexer: error parsing 'no result' response.

### ISSUE THREAD

**Issue by analogbit** [Jackett/Jackett#13223]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /jackett-data/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: unknown)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.17.5.1 (64bit OS) (64bit process)
Environment version: 6.0.3 (/jackett/)
Starting Jackett v0.20.818
```

### Description

When querying the xthor api, if no results are found then jackett fails to parse the response.

### Logged Error Messages

The xthor response to the request `https://api.xthor.tk/?passkey=xxxxxxxxxx&search=DoesNotExist&category=&freeleech=&tmdbid=&size=&accent=&price=&page=`

```text
{
    "error": {
        "code": 2,
        "descr": "no result"
    },
    "user": { ... }
}
```

The jackett log:

```
Jackett.Common.IndexerException: Exception (xthor-api): Error Parsing Rows Selector. There are 0 rows.
 ---> System.Exception: Error Parsing Rows Selector. There are 0 rows.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1413
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 401
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 413
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 768
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 398
```
```


### Screenshots

_No response_

**Comment by garfield69** [comment]
Without an xthor account it's going to be difficult for me to code and test a solution.
I don't suppose you have an invite to send to garfieldsixtynine -at- gmail.com ?
Alternatively, would you be willing to let me borrow your credentials for the duration of this ticket?

**Comment by garfield69** [comment]
Never mind, I used another indexer as a test bed and I think my solve will universally work.

**Comment by garfield69** [comment]
v0.20.1010
