### ISSUE TITLE
[xbytesv2] (updating) Login Failed, got redirected. Try changing the indexer URL to https://xbytesv2.li/.

### ISSUE THREAD

**Issue by lopjonp** [Jackett/Jackett#13239]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-05-13 11:01:50	Info	Using HTTP Client: HttpWebClient2
2022-05-13 11:01:50	Error	Jackett is running with root privileges. You should run Jackett as an unprivileged user.
2022-05-13 11:01:50	Info	Using FlareSolverr: No
2022-05-13 11:01:50	Info	Using proxy: Disabled
2022-05-13 11:01:50	Info	App config/log directory: /storage/.kodi/userdata/addon_data/service.jackett/Jackett
2022-05-13 11:01:50	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-05-13 11:01:50	Info	Running in Docker: No
2022-05-13 11:01:50	Info	File /etc/issue: ##############################################
2022-05-13 11:01:50	Info	Jackett variant: CoreLinuxArm32
2022-05-13 11:01:50	Info	OS version: Unix 4.9.113.0
2022-05-13 11:01:50	Info	Environment version: 6.0.5 (/storage/.kodi/addons/service.jackett/libs/)
2022-05-13 11:01:34	Info	Starting Jackett v0.20.1050
```

### Description

the indexer after a web update does not connect because previously it worked with http and now with https.

### Logged Error Messages

```text
An error occurred while updating this indexer
Login Failed, got redirected. Try changing the indexer URL to https://xbytesv2.li/.
```

**Comment by garfield69** [comment]
The site has upgraded to xbtitFM v3.1.00 so it is likely that there will be other changes needed.
Please try using your Jackett dashboard to edit the config and change the site link to use https and see if you can complete the login, and if successful let us know.
None of the team that are regularly available have an account so we cannot test and debug independently.
If you still have issues with the login in after changing to https, or the TEST fails with errors, then please enable the Jackett enhanced logging and provide a full enhanced log. The Debug and HTML should help us make amendments.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by lopjonp** [comment]
hello, thanks for your answer, I already did the test changing the indexer by hand with "https" but it doesn't work, I send a full enhanced log. (I removed the html from the log)




2022-05-13 12:49:13	Debug	
Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2022-05-13 12:49:13	Debug	
Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2022-05-13 12:49:13	Debug	
Authorization was successful.
2022-05-13 12:49:13	Debug	
Execution plan of result filters (in the following order): None
2022-05-13 12:49:13	Debug	
Execution plan of exception filters (in the following order): None
2022-05-13 12:49:13	Debug	
Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2022-05-13 12:49:13	Debug	
Execution plan of resource filters (in the following order): None
2022-05-13 12:49:13	Debug	
Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2022-05-13 12:49:13	Info	
Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (jackett).
2022-05-13 12:49:13	Info	
Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
2022-05-13 12:49:13	Debug	
Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
2022-05-13 12:49:13	Debug	
Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'
2022-05-13 12:49:13	Debug	
1 candidate(s) found for the request path '/api/v2.0/server/logs'
2022-05-13 12:49:13	Debug	
AuthenticationScheme: Cookies was successfully authenticated.
2022-05-13 12:49:13	Debug	
The request path /api/v2.0/server/logs does not match a supported file type
2022-05-13 12:49:13	Debug	
Request is continuing in applying rules. Current url is http://192.168.1.47:9117/api/v2.0/server/logs?_=1652438744272
2022-05-13 12:49:13	Debug	
Request is continuing in applying rules. Current url is http://192.168.1.47:9117/api/v2.0/server/logs?_=1652438744272
2022-05-13 12:49:13	Debug	
Request is continuing in applying rules. Current url is http://192.168.1.47:9117/api/v2.0/server/logs?_=1652438744272
2022-05-13 12:49:13	Info	
Request starting HTTP/1.1 GET http://192.168.1.47:9117/api/v2.0/server/logs?_=1652438744272 - -
2022-05-13 12:49:10	Info	
Request finished HTTP/1.1 POST http://192.168.1.47:9117/api/v2.0/indexers/xbytesv2/test - 0 - 500 - application/json 4626.9690ms
2022-05-13 12:49:10	Debug	
Connection id "0HMHKP75JI2NI" completed keep alive response.
2022-05-13 12:49:10	Debug	
The response will be compressed with 'gzip'.
2022-05-13 12:49:09	Error	
System.Exception: Test search in XbytesV2 => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 313
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2022-05-13 12:49:09	Info	
Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2022-05-13 12:49:09	Info	
Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 4517.4857ms
2022-05-13 12:49:09	Info	
Test search in XbytesV2 => Found 0 releases
2022-05-13 12:49:09	Debug	
WebClient(HttpWebClient2): Returning OK => 52305 bytes
_________________
/////here HTML ////
_________________

2022-05-13 12:49:05	Debug	
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://xbytesv2.li/index.php?page=torrents&category=&active=1&options=0&search=&order=3&by=2)
2022-05-13 12:49:05	Debug	
CACHE IsCacheEnabled => false
2022-05-13 12:49:05	Debug	
Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2022-05-13 12:49:05	Debug	
Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2022-05-13 12:49:05	Debug	
Authorization was successful.
2022-05-13 12:49:05	Debug	
Execution plan of result filters (in the following order): None
2022-05-13 12:49:05	Debug	
Execution plan of exception filters (in the following order): None
2022-05-13 12:49:05	Debug	
Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2022-05-13 12:49:05	Debug	
Execution plan of resource filters (in the following order): None
2022-05-13 12:49:05	Debug	
Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2022-05-13 12:49:05	Info	
Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2022-05-13 12:49:05	Info	
Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2022-05-13 12:49:05	Debug	
Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2022-05-13 12:49:05	Debug	
Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/xbytesv2/test'
2022-05-13 12:49:05	Debug	
1 candidate(s) found for the request path '/api/v2.0/indexers/xbytesv2/test'
2022-05-13 12:49:05	Debug	
AuthenticationScheme: Cookies was successfully authenticated.
2022-05-13 12:49:05	Debug	
POST requests are not supported
2022-05-13 12:49:05	Debug	
Request is continuing in applying rules. Current url is http://192.168.1.47:9117/api/v2.0/indexers/xbytesv2/test
2022-05-13 12:49:05	Debug	
Request is continuing in applying rules. Current url is http://192.168.1.47:9117/api/v2.0/indexers/xbytesv2/test
2022-05-13 12:49:05	Debug	
Request is continuing in applying rules. Current url is http://192.168.1.47:9117/api/v2.0/indexers/xbytesv2/test
2022-05-13 12:49:05	Info	
Request starting HTTP/1.1 POST http://192.168.1.47:9117/api/v2.0/indexers/xbytesv2/test - 0

**Comment by garfield69** [comment]
As I expected, the site's upgrade to  xbtitFM v3.1.00 has changed the HTML for their torrent search page.
The HTML that you left out was the most important bit in the enhanced log.

The best option to upgrade the indexer would be for you could send me an invite to garfieldsixtynine -at- gmail.com 
If you are unable to provide a invite, then the next option would be for you to email me the HTML for the Jackett enhanced log.
But this latter option is piece meal because I will be coding changes without being able to test my syntax.
An alternate option would be for you to let me borrow your account by emailing me your login creds while I upgrade the indexer.
You could change your password after I complete the upgrade to restore privacy.
Let me know what you decide to do.

**Comment by garfield69** [comment]
It seems that in response to the TEST search query that the indexer made, the site returned the FAQ page.
So there is nothing useful in the HTML.
Are you able to access the browse torrents page on the site?
I think we have two options:
We can wait for @ngosang to contribute. He is the only team member with an account, however he only is available sporadically, sometimes several months apart.
Or you email your login to me and I can take a look directly on the site.
Rest assured that I will not download anything, I do not need to download to upgrade the indexer.

**Comment by lopjonp** [comment]
ok I leave you my account to solve it, thanks.

user: Lopjonplex
pass: sistemasauxiliaresdelmotor

**Comment by garfield69** [comment]
Before I begin, please confirm that you have logged out of the site.
We do not want to have two different IP addresses active at the same time, it may raise red flags.
I will start once I get your all clear.
Thanks.

**Comment by lopjonp** [comment]
yes, I closed my session

**Comment by garfield69** [comment]
OK all done. Please change your password to restore privacy.
The next release of Jackett due out in about 7 hours should include the upgraded indexer.

**Comment by lopjonp** [comment]
OK, thanks for fixing it so quickly! :)

**Comment by garfield69** [comment]
v0.20.1058
