### ISSUE TITLE
[dontorrent] (testing) Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.bet/ultimos">here</a>.</p></body></html>: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>301 Moved Permanently</title></head><body><h1>Moved Permanently</h1><p>The document has moved <a href="https://dontorrent.bet/ultimos">here</a>.</p></body></html>

### ISSUE THREAD

**Issue by pelagrellas** [Jackett/Jackett#13238]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-05-12 09:01:34	Info	
Using HTTP Client: HttpWebClient2
2022-05-12 09:01:34	Info	
Using FlareSolverr: http://192.168.2.4:8191
2022-05-12 09:01:34	Info	
Using proxy: Disabled
2022-05-12 09:01:34	Info	
App config/log directory: C:\ProgramData\Jackett
2022-05-12 09:01:34	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-05-12 09:01:34	Info	
Running in Docker: No
2022-05-12 09:01:34	Info	
Jackett variant: CoreWindows
2022-05-12 09:01:34	Info	
OS version: Microsoft Windows NT 10.0.17763.0 (64bit OS)
2022-05-12 09:01:34	Info	
Environment version: 6.0.5 (C:\ProgramData\Jackett\)
```

### Description

<img width="317" alt="image" src="https://user-images.githubusercontent.com/85077900/168012712-a4a844a6-cfa0-4826-8094-ed99dae8f185.png">

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (dontorrent): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://dontorrent.bet/ultimos">here</a>.</p>
</body></html>

 ---> Jackett.Common.ExceptionWithConfigData: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://dontorrent.bet/ultimos">here</a>.</p>
</body></html>

   at Jackett.Common.Indexers.DonTorrent.PerformQueryNewest(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\DonTorrent.cs:line 180
   at Jackett.Common.Indexers.DonTorrent.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\DonTorrent.cs:line 139
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 308
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 320
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 675
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 308
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

### Screenshots

<img width="743" alt="image" src="https://user-images.githubusercontent.com/85077900/168012840-5e49c75d-37fe-4a97-b7a3-437b08034334.png">

**Comment by garfield69** [comment]
Use your jackett dashboard to edit the config and change the site link to `https://dontorrent.bet/` and save.
You should be good to go.
Or wait for the Jackett release in about 22 hours for the auto-update.

**Comment by garfield69** [comment]
Or switch to one of the other alternate links, they don't change as often.

**Comment by garfield69** [comment]
v0.20.1053
