### ISSUE TITLE
[bakabt] (updating) Too many failed attempts. Try again in 0:00s.

### ISSUE THREAD

**Issue by jnorvel1** [Jackett/Jackett#13248]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.1088-ls67)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 6.0.5 (/app/Jackett/)
Starting Jackett v0.20.1088
```

### Description

I'm currently running Jackett Version v0.20.1088 in a docker instance on a Synology NAS device. 

I've been receiving failures to connect to indexer for over 6 hours in both Sonarr and Radarr. In the Jackett Web UI, I tested the connection to all my added trackers and they all pass besides BakaBT. When I remove and try to add BakaBT, I receive the following pop-up error:

An error occurred while updating this indexer
Too many failed attempts. Try again in 0:00s.

I'm 100% certain I'm only hitting the button to add the tracker once. I've gone to the actual website, logged in, and I log in just fine and so it is not an issue with my login.

### Logged Error Messages

```text
2022-05-20 18:11:39	Error	
Jackett.Common.ExceptionWithConfigData: Too many failed attempts. Try again in 0:00s.
   at Jackett.Common.Indexers.BakaBT.<>c__DisplayClass15_0.<DoLogin>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BakaBT.cs:line 117
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 161
   at Jackett.Common.Indexers.BakaBT.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BakaBT.cs:line 111
   at Jackett.Common.Indexers.BakaBT.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BakaBT.cs:line 85
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Disable the indexers in Sonarr and Radarr for now.

Are you using a VPN or proxy for Jackett? If so, are you able to log into the site in browser using the same server?

When you delete the indexer from Jackett and re-add it, are you using auto-filled credentials? If so, delete these and type them in manually.

**Comment by garfield69** [comment]
For what it's worth,  #9240 is similar.
I recommend waiting 24 hours before trying to use the indexer, to allow for the lockout to expire that seems to be tied to your docker sessions.

**Comment by jnorvel1** [comment]
> 

Hi. Sorry for the late reply. I've been busy. 

I have disabled the indexes in both Sonarr and Radarr. I'm not using a vpn or proxy for jackett.  I was using auto-filled before and typed them manually. I'm now getting this error:

 An error occurred while updating this indexer
To login to this user, answer the CAPTCHA (if prompted). You still have 1 attempt(s)

I'm not seeing any captcha popup.

**Comment by ilike2burnthing** [comment]
Now that you've disabled the indexers in Sonarr and Radarr, as garfield69 recommended leave it for 24hrs. Also sign out in browser.

After 24hrs, sign back in in browser, then try adding it again in Jackett. If you get another error, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by jnorvel1** [comment]
It seems the issue has resolved itself. Thanks
