### ISSUE TITLE
[abtorrents] (updating) Login Failed, got redirected.

### ISSUE THREAD

**Issue by derekcentrico** [Jackett/Jackett#13256]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Loading Native indexers ...
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191/
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.1071-ls67)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.13.0.41 (64bit OS) (64bit process)
Environment version: 6.0.5 (/app/Jackett/)
Starting Jackett v0.20.1104
```

### Description

I attempted to add ABTorrents but the cookie is not being accepted.  

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 820
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 973
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
See the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

If you are using a Chromium-based browser to grab the cookie, make sure you're highlighting the cookie text and clicking `Copy`, and not `Copy value`.

**Comment by derekcentrico** [comment]
Thanks for the comment.  I did these steps originally and tried again.  Of note, I created 4 other tracker entries with cookies and they worked flawlessly this morning.  

The only odd thing here is that the cookie is extremely long, has a space in it.  Here's a shortened version where I notate the amount of characters per two sections of the cookie:  ABTorrents=128charactershere; remember=113charactershere

The other trackers did not have such long/complex cookies.  For instance, Demonoid was auth=54characters

**Comment by ilike2burnthing** [comment]
Does your cookie have multiple instances of `%2C` in it? Or does it instead have commas?

Are you able to access the browse page? https://abtorrents.me/browse.php

Are you using a VPN or proxy either for Jackett or when grabbing the cookie?

**Comment by ilike2burnthing** [comment]
There shouldn't be commas. Like I said earlier, if you are using a Chromium-based browser to grab the cookie, make sure you're highlighting the cookie text and clicking `Copy`, and not `Copy value`.

As is mentioned in the troubleshooting steps linked to earlier:

> Make sure that before fetching the cookie you can access the Site's torrent search page, as anything the site does to prevent this (alerts, unread notices or unread PM, or a low ratio warning) will stop Jackett from having a successful test after using the cookie.

As also mentioned in the troubleshooting steps:

> Some web sites generate cookies that are IP locked to the users' current IP address. If you are using a VPN service then make sure that the VPN is allocating the same server for your Browser as it does for Jackett, otherwise your cookie will not work.

At least one of those will be causing your issue.

**Comment by derekcentrico** [comment]
Thanks will mark as closed and play with those later.

**Comment by garfield69** [comment]
>The browse.php loads to https://abtorrents.me/pm_system.php?action=view_mailbox

There is your problem. The indexer needs to access to browse page to search for torrents. The indexer will continue to fail the set up test until you read your mail to prevent the web site redirection.

**Comment by derekcentrico** [comment]
Doh, I didn't dismiss that dang message.  Newb move this morning.  Thanks, I'll fix that in a bit.
