### ISSUE TITLE
[elitetorrent-biz] (testing) Exception (elitetorrent-biz): Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.: Parse error

### ISSUE THREAD

**Issue by pabsi** [Jackett/Jackett#13268]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:54.001971966Z 05-26 23:05:53 Info Starting Jackett v0.20.1104 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.089150183Z 05-26 23:05:59 Info Environment version: 6.0.5 (/app/Jackett/) 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.090271019Z 05-26 23:05:59 Info OS version: Unix 5.4.0.110 (64bit OS) (64bit process) 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.094967159Z 05-26 23:05:59 Info Jackett variant: CoreLinuxAmdx64 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.095315257Z 05-26 23:05:59 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.096586141Z 05-26 23:05:59 Info Running in Docker: Yes (image build: v0.20.1104-ls68) 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.098975993Z 05-26 23:05:59 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.099970630Z 05-26 23:05:59 Info App config/log directory: /config/Jackett 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.101984791Z 05-26 23:05:59 Info Using proxy: Disabled 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.102983903Z 05-26 23:05:59 Info Using FlareSolverr: http://flaresolverr:8191/ 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.104387036Z 05-26 23:05:59 Error Jackett is running with root privileges. You should run Jackett as an unprivileged user. 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.108338986Z 05-26 23:05:59 Info Using HTTP Client: HttpWebClient2 
ESC[36mjackett         |ESC[0m 2022-05-26T21:05:59.192379763Z 05-26 23:05:59 Info Loading Native indexers ...
```

### Description

When testing elitetorrent-biz tracker, it fails. It says:
```
 An error occurred while testing this indexer
Exception (elitetorrent-biz): Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.: Parse error
```
I tried editing the URL to the ".com" version to no avail, it seems Jackett reverts my change to the ".biz" variant after saving. And then it errors again.

### Logged Error Messages

```text
jackett         | 2022-05-29T22:54:06.036206797Z 05-30 00:54:06 Error Error on 20220530005406 for EliteTorrent.biz.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:06.036230852Z    at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 843
jackett         | 2022-05-29T22:54:06.036236267Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1510
jackett         | 2022-05-29T22:54:06.036240176Z 
jackett         | 2022-05-29T22:54:06.036243427Z 
jackett         | 2022-05-29T22:54:06.036246517Z 
jackett         | 2022-05-29T22:54:06.036249498Z 
jackett         | 2022-05-29T22:54:06.036252500Z  
jackett         | 2022-05-29T22:54:06.038855527Z 05-30 00:54:06 Error Jackett.Common.IndexerException: Exception (elitetorrent-biz): Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:06.038879136Z  ---> System.Exception: Parse error
jackett         | 2022-05-29T22:54:06.038883628Z  ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:06.038887381Z    at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 843
jackett         | 2022-05-29T22:54:06.038890752Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1510
jackett         | 2022-05-29T22:54:06.038894046Z    --- End of inner exception stack trace ---
jackett         | 2022-05-29T22:54:06.038897070Z    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 701
jackett         | 2022-05-29T22:54:06.038900458Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1666
jackett         | 2022-05-29T22:54:06.038911147Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
jackett         | 2022-05-29T22:54:06.038914377Z    --- End of inner exception stack trace ---
jackett         | 2022-05-29T22:54:06.038917098Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
jackett         | 2022-05-29T22:54:06.038920022Z    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 678
jackett         | 2022-05-29T22:54:06.038922906Z    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 308
jackett         | 2022-05-29T22:54:06.038925826Z    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
jackett         | 2022-05-29T22:54:06.038929265Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett         | 2022-05-29T22:54:06.038932316Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett         | 2022-05-29T22:54:06.038935422Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:06.038938551Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett         | 2022-05-29T22:54:06.038944742Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett         | 2022-05-29T22:54:06.038947934Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:06.038951037Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:06.038966147Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         | 2022-05-29T22:54:06.038970050Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         | 2022-05-29T22:54:06.038973025Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett         | 2022-05-29T22:54:06.038975985Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett         | 2022-05-29T22:54:06.038982244Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.IndexerException: Exception (elitetorrent-biz): Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:06.038985665Z  ---> System.Exception: Parse error
jackett         | 2022-05-29T22:54:06.038988333Z  ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:06.038991262Z    at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 843
jackett         | 2022-05-29T22:54:06.038994213Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1510
jackett         | 2022-05-29T22:54:06.038997130Z    --- End of inner exception stack trace ---
jackett         | 2022-05-29T22:54:06.039004335Z    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 701
jackett         | 2022-05-29T22:54:06.039007343Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1666
jackett         | 2022-05-29T22:54:06.039010262Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
jackett         | 2022-05-29T22:54:06.039013133Z    --- End of inner exception stack trace ---
jackett         | 2022-05-29T22:54:06.039016149Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
jackett         | 2022-05-29T22:54:06.039019079Z    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 678
jackett         | 2022-05-29T22:54:06.039022019Z    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 308
jackett         | 2022-05-29T22:54:06.039024919Z    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
jackett         | 2022-05-29T22:54:06.039027839Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett         | 2022-05-29T22:54:06.039030824Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett         | 2022-05-29T22:54:06.039033859Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:06.039036897Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett         | 2022-05-29T22:54:06.039042035Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett         | 2022-05-29T22:54:06.039045129Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:06.039048211Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:06.039051237Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         | 2022-05-29T22:54:06.039054490Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         | 2022-05-29T22:54:06.039057439Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett         | 2022-05-29T22:54:06.039060378Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett         | 2022-05-29T22:54:06.039063135Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
jackett         | 2022-05-29T22:54:28.979358560Z 05-30 00:54:28 Error Error on 20220530005428 for EliteTorrent.biz.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:28.979382325Z    at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 843
jackett         | 2022-05-29T22:54:28.979387379Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1510
jackett         | 2022-05-29T22:54:28.979391036Z 
jackett         | 2022-05-29T22:54:28.979394165Z 
jackett         | 2022-05-29T22:54:28.979397159Z 
jackett         | 2022-05-29T22:54:28.979400124Z 
jackett         | 2022-05-29T22:54:28.979403133Z  
jackett         | 2022-05-29T22:54:28.982162745Z 05-30 00:54:28 Error Jackett.Common.IndexerException: Exception (elitetorrent-biz): Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:28.982183041Z  ---> System.Exception: Parse error
jackett         | 2022-05-29T22:54:28.982189756Z  ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:28.982193403Z    at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 843
jackett         | 2022-05-29T22:54:28.982196846Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1510
jackett         | 2022-05-29T22:54:28.982207683Z    --- End of inner exception stack trace ---
jackett         | 2022-05-29T22:54:28.982210674Z    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 701
jackett         | 2022-05-29T22:54:28.982213651Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1666
jackett         | 2022-05-29T22:54:28.982393998Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
jackett         | 2022-05-29T22:54:28.982401878Z    --- End of inner exception stack trace ---
jackett         | 2022-05-29T22:54:28.982405024Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
jackett         | 2022-05-29T22:54:28.982408016Z    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 678
jackett         | 2022-05-29T22:54:28.982410939Z    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 308
jackett         | 2022-05-29T22:54:28.982413866Z    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
jackett         | 2022-05-29T22:54:28.982416712Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett         | 2022-05-29T22:54:28.982419693Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett         | 2022-05-29T22:54:28.982422860Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:28.982426142Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett         | 2022-05-29T22:54:28.982429043Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett         | 2022-05-29T22:54:28.982434552Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:28.982442034Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:28.982445436Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         | 2022-05-29T22:54:28.982448381Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         | 2022-05-29T22:54:28.982455747Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett         | 2022-05-29T22:54:28.982458909Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett         | 2022-05-29T22:54:28.982461805Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.IndexerException: Exception (elitetorrent-biz): Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:28.982465086Z  ---> System.Exception: Parse error
jackett         | 2022-05-29T22:54:28.982467776Z  ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.elitetorrent.com/.
jackett         | 2022-05-29T22:54:28.982470670Z    at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 843
jackett         | 2022-05-29T22:54:28.982473648Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1510
jackett         | 2022-05-29T22:54:28.982476538Z    --- End of inner exception stack trace ---
jackett         | 2022-05-29T22:54:28.982479231Z    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 701
jackett         | 2022-05-29T22:54:28.982482146Z    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1666
jackett         | 2022-05-29T22:54:28.982716734Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
jackett         | 2022-05-29T22:54:28.982724226Z    --- End of inner exception stack trace ---
jackett         | 2022-05-29T22:54:28.982727263Z    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
jackett         | 2022-05-29T22:54:28.982730227Z    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 678
jackett         | 2022-05-29T22:54:28.982733235Z    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 308
jackett         | 2022-05-29T22:54:28.982736174Z    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
jackett         | 2022-05-29T22:54:28.982739056Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett         | 2022-05-29T22:54:28.982742015Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett         | 2022-05-29T22:54:28.982749147Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:28.982752459Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett         | 2022-05-29T22:54:28.982755269Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett         | 2022-05-29T22:54:28.982758282Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:28.982761369Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         | 2022-05-29T22:54:28.982769888Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         | 2022-05-29T22:54:28.982773456Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         | 2022-05-29T22:54:28.982776387Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett         | 2022-05-29T22:54:28.982779320Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett         | 2022-05-29T22:54:28.982782238Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://user-images.githubusercontent.com/5247611/170894469-17bd6312-ca94-4a94-aad8-f1cd96e53bca.png)

**Comment by garfield69** [comment]
update your Jackett. The elitetorrent-biz indexer was updated three days ago beginning with v0.20.1108 
and you are still on v0.20.1104
So fetch the latest docker image and you will be good to go.

**Comment by pabsi** [comment]
Damn :facepalm: I am sorry I did not do this in the first instance. 
I regularly update my "arr" docker images as well as jackett, I guess I learnt my lesson.

Thank you so much!
