### ISSUE TITLE
[mteamtp] (testing) Test search in M-Team - TP => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by fangguisheng** [Jackett/Jackett#13261]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Synology-dsm7.0.1

2022-05-28 11:45:35	Info	Using HTTP Client: HttpWebClient2
2022-05-28 11:45:35	Info	Using FlareSolverr: No
2022-05-28 11:45:35	Info	Using proxy: Disabled
2022-05-28 11:45:35	Info	App config/log directory: /config/Jackett
2022-05-28 11:45:35	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-05-28 11:45:35	Info	Running in Docker: Yes (image build: v0.20.1108-ls68)
2022-05-28 11:45:35	Info	File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-05-28 11:45:35	Info	Jackett variant: CoreLinuxAmdx64
2022-05-28 11:45:35	Info	OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2022-05-28 11:45:35	Info	Environment version: 6.0.5 (/app/Jackett/)
2022-05-28 11:45:33	Info	Starting Jackett v0.20.1108
```

### Description

M-team - TP cannot search any resources

### Logged Error Messages

```text
System.Exception: Test search in M-Team - TP => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 313
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
None of the current team members have an account so we cannot test independently.
Please enabled enhanced logging and repeat the test and provide the full logs.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by fangguisheng** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/8790486/log.txt)
Thank you. This is the enhanced log I started. Please check it

**Comment by garfield69** [comment]
Hmmm. Seems like the download links in the search results is no longer available.
So we are going to need to use the download link in the torrent details page.
Can you please 
- use your browser to view the torrents search page at https://kp.m-team.cc/torrents.php
- then click on any one of the torrents on that page to pull up the torrent details page.
- Right click, and select save page as HTML, (use txt extension)
- Remove personal information (username, password, passkey, hashes, IP address etc) from the HTML file (without breaking the code)
- Drag/drop the txt file into the body of this ticket so we can use it to update the indexer.

Thanks.

**Comment by fangguisheng** [comment]
[搜索結果-钢铁侠.txt](https://github.com/Jackett/Jackett/files/8790531/-.txt)
Please check it，Thank you

**Comment by garfield69** [comment]
I think you have posted a html dump of the torrent search page.
What I really need is a torrent's details page. Do you know what I mean by this?

**Comment by fangguisheng** [comment]
[Iron Man 2008 BluRay 2160p TrueHD 7.1 HDR x265 10bit-CHD.txt](https://github.com/Jackett/Jackett/files/8790546/Iron.Man.2008.BluRay.2160p.TrueHD.7.1.HDR.x265.10bit-CHD.txt)
I don't know if my understanding is correct. I use translation software and may make mistakes，Thank you

**Comment by garfield69** [comment]
The details page seems to have multiple choices for the download link, with ipv4, ipv6, https combinations.
I chose the first Download link, which I hope will work. 
But if the Download turns out that it is missing the passkey, then you need to let me know and I will select one of those other Download links instead, perhaps the ipv4https link.
Try out v0.20.1117 just release now.

**Comment by fangguisheng** [comment]
> 详细信息页面似乎有多个下载链接选择，包括ipv4，ipv6，https组合。我选择了第一个下载链接，我希望它能起作用。但是，如果下载结果显示它缺少密钥，那么您需要让我知道，我将选择其他下载链接之一，也许是ipv4https链接。试用刚刚发布的 v0.20.1117。

I am https://hub.docker.com/r/linuxserver/jackett I don't see any updates in. Is it in this link? Lscr Io/linuxserver/jackett:v0.20.1117

**Comment by fangguisheng** [comment]
> 详细信息页面似乎有多个下载链接选择，包括ipv4，ipv6，https组合。我选择了第一个下载链接，我希望它能起作用。但是，如果下载结果显示它缺少密钥，那么您需要让我知道，我将选择其他下载链接之一，也许是ipv4https链接。试用刚刚发布的 v0.20.1117。

lscr.io/linuxserver/jackett:v0.20.1117

**Comment by garfield69** [comment]
We are not responsible for the building of the docker versions of Jackett, that is handled by the  https://linuxserver.io/ group.
It may take a little while for the linuxserver automation to build their docker images from our source after we post our releases.
I do not know how long before the docker images are ready, I do not use docker and have not experience with this topic.

**Comment by ilike2burnthing** [comment]
It can be anywhere from a few minutes to a few hours. In this case it looks like it was about an hour.

@fangguisheng it is out now if you want to try it.

**Comment by fangguisheng** [comment]
> 它可以是几分钟到几个小时的任何地方。在这种情况下，看起来大约是一个小时。
> 
> @fangguisheng，如果你想尝试一下，它现在已经出来了。

OK, I'm downloading the test. The Internet speed is slow. thanks

**Comment by fangguisheng** [comment]
> > 它可以是几分钟到几个小时的任何地方。在这种情况下，看起来大约是一个小时。
> > @fangguisheng，如果你想尝试一下，它现在已经出来了。
> 
> OK, I'm downloading the test. The Internet speed is slow. thanks

After testing, the content can be searched, but cannot be downloaded. Transmission: 3.00 displays the error "Tracker gave HTTP response code 0 (No Response) (2)"

**Comment by fangguisheng** [comment]
> It can be anywhere from a few minutes to a few hours. In this case it looks like it was about an hour.
> 
> @fangguisheng it is out now if you want to try it.

After testing, the content can be searched, but cannot be downloaded. Transmission: 3.00 displays the error "Tracker gave HTTP response code 0 (No Response) (2)"

**Comment by ilike2burnthing** [comment]
Does the .torrent file download?

Does Transmission accept it as a valid torrent?

Is this error just the tracker status response?

If you download manually from the tracker, do you get the same error?

**Comment by fangguisheng** [comment]
> Does the .torrent file download?
> 
> Does Transmission accept it as a valid torrent?
> 
> Is this error just the tracker status response?
> 
> If you download manually from the tracker, do you get the same error?

.torrent can be downloaded normally and Transmission can be recognized normally. I try to access [KP manually M-team CC](https://kp.m-team.cc/) downloads the seed file, and the Transmission also reports an error, so I tried. Both IPv4 and IPv6 report errors, and both ipv4+https and ipv6+https can work normally. I am also very confused because I can normally download files that are not HTTPS the other day. Is it[ KP M-team CC](https://kp.m-team.cc/)  failure?

**Comment by ilike2burnthing** [comment]
This seems to be an issue with the tracker itself, yes. If it continues then let us know and we can switch to the HTTPS IPv4 torrent.

**Comment by fangguisheng** [comment]
> This seems to be an issue with the tracker itself, yes. If it continues then let us know and we can switch to the HTTPS IPv4 torrent.

Yes, please switch to HTTPS. I can continue the test. Thank you

**Comment by ilike2burnthing** [comment]
Will be out in ~11hrs.

If you want to test it before then, download from [here](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/5918/artifacts?artifactName=drop&api-version=7.0&%24format=zip), extract the version you need (we don't provide Docker images, so you'll need to test this on a different device, e.g. a Windows computer), add mteamtp, and ensure that downloads now work.

**Comment by garfield69** [comment]
v0.20.1119

**Comment by fangguisheng** [comment]
> v0.20.1119

@garfield69 @ilike2burnthing
![屏幕截图 2022-05-29 225122](https://user-images.githubusercontent.com/51241778/170875739-ca064dab-d71a-48b4-ac59-3fab792be437.png)
 And you can search and download normally. Thank you
