### ISSUE TITLE
[req]: HDFans

### ISSUE THREAD

**Issue by ClandestineClout** [Jackett/Jackett#13272]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: HDFans
- URL: https://hdfans.org/
- Description: Chinese general tracker
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments:
```
Registration currently closed, invites only
engine: NexusPHP 1.7.6

**Comment by garfield69** [comment]
v0.20.1649

**Comment by sjtuross** [comment]
It doesn't seem working for me because captcha is required for login.

**Comment by ilike2burnthing** [comment]
You will see the captcha image at the bottom of the panel when configuring the indexer, there, and can enter the code below it.

**Comment by sjtuross** [comment]
I thought so, but it doesn't show up. Actually I don't see the captcha part at all.

**Comment by ilike2burnthing** [comment]
When you click to add HDFans, does it take a long time for the config panel to open?

Do you get an error in the logs when you do so?

**Comment by sjtuross** [comment]
It took a few seconds to load the form. Below is the error log with either FlareSolverr disabled or enabled.

```
Exception in GetConfigurationForSetup (hdfans): FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 516
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889
```

```
Exception in GetConfigurationForSetup (hdfans): FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 516
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889
```

**Comment by ilike2burnthing** [comment]
See the troubleshooting steps - https://github.com/Jackett/Jackett/wiki/Troubleshooting#the-cookies-provided-by-flaresolverr-are-not-valid

You should also disable IPv6. If using Docker, you'll need to do this for both Jackett and FlareSolverr containers - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

If you continue to have issues, open a new issue, providing the information requested.

**Comment by garfield69** [comment]
https://hdfans.org/ returns DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)

**Comment by sjtuross** [comment]
The site is up now.

**Comment by garfield69** [comment]
https://hdfans.org/ HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Not for me.
The captcha image is not fetched.
And via the browser, I also got a login without a captcha, and when I refreshed I got the HTTP ERROR 500 again.

**Comment by garfield69** [comment]
ok, now ok on browser, but jackett still no captcha.  site must still be getting hammered or something.

**Comment by ilike2burnthing** [comment]
Seems to be working ok here now - login and searching, both in browser and Jackett. If it's still down for you, reopen.

**Comment by garfield69** [comment]
https://hdfans.org/ DNS_PROBE_FINISHED_NXDOMAIN

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://hdfans.org/ cloudflare Web server is down Error code 521

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13272#issuecomment-1376736152

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13272#issuecomment-1376736152

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://hdfans.org/ Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
The site is down for maintenance, please visit it later... Thank you

**Comment by garfield69** [comment]
online. site notice reports hardrive replaced but expect lots of 500 while torrents are cleaned up

**Comment by garfield69** [comment]
https://hdfans.org/ > 500 Internal Server Error

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13272#issuecomment-3185060163

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13272#issuecomment-3185060163

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13272#issuecomment-3185060163

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13272#issuecomment-3185060163

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13272#issuecomment-3185060163

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13272#issuecomment-3185060163

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://hdfans.org/ > cloudflare  Web server is down Error code 521

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://hdfans.org/ - working
https://hdfans.org/torrents.php
- browser - slow or Bad gateway Error code 502
- Jackett - The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing

**Comment by ilike2burnthing** [comment]
slooooooow, but working again in Jackett

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13272#issuecomment-3797949472

**Comment by FunFrog-BY** [comment]
I see it got reopened. Good. Sometimes it fits into timeout:

> 2026-02-23 09:30:54 | Info | Torznab search in HDFans for [REDACTED] => Found 0 releases [90934ms]

But most of the time (99+%) not.

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
and back to the torrents page timing out again

**Comment by socketcat** [comment]
Setting `incldead` to 1 fixed the search issue for me. Maybe that option creates too much overhead for their server...

**Comment by garfield69** [comment]
v0.24.1218
