### ISSUE TITLE
[divxtotal] Error while parsing row

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13270]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

divxtotal is no longer able to parse series

### Logged Error Messages

```text
CardigannIndexer (divxtotal): Error while parsing row '
<tr>
	<td class="text-left">
		<a href="https://www.divxtotal.ac/series/walker/" title="Walker">Walker</a>
	</td>
	<td class="text-left">
		<a href="https://www.divxtotal.ac/category/western/">Western</a>
	</td>
	<td class="text-left">30-05-2022</td>
	<td class="text-left">
		N/A
	</td>
</tr>':

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)
   at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)
   at Jackett.Common.Indexers.DivxTotal.ParseSeriesReleaseAsync(TorznabQuery query, String detailsStr, String cat, DateTime publishDate) in D:\a\1\s\src\Jackett.Common\Indexers\DivxTotal.cs:line 294
   at Jackett.Common.Indexers.DivxTotal.ParseReleasesAsync(IParentNode row, TorznabQuery query, Boolean matchWords) in D:\a\1\s\src\Jackett.Common\Indexers\DivxTotal.cs:line 267
   at Jackett.Common.Indexers.DivxTotal.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\DivxTotal.cs:line 160
```

**Comment by garfield69** [comment]
v0.20.1285
