### ISSUE TITLE
[rarbg] (configuring) Could not find releases from this URL

### ISSUE THREAD

**Issue by Locutus64** [Jackett/Jackett#13293]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-06-11 09:57:05	Info	Using HTTP Client: HttpWebClient2
2022-06-11 09:57:05	Info	Using FlareSolverr: http://10.0.0.86:8089
2022-06-11 09:57:05	Info	Using proxy: Disabled
2022-06-11 09:57:05	Info	App config/log directory: /var/lib/jackett
2022-06-11 09:57:05	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-06-11 09:57:05	Info	Running in Docker: No
2022-06-11 09:57:05	Info	File /etc/issue: Arch Linux \r (\l)
2022-06-11 09:57:05	Info	Jackett variant: CoreLinuxAmdx64
2022-06-11 09:57:05	Info	OS version: Unix 5.18.3.1 (64bit OS) (64bit process)
2022-06-11 09:57:05	Info	Environment version: 6.0.2 (/usr/lib/jackett/)

XeroLinux based on Arch Linux 
Jackett Version v0.20.1168
```

### Description

I just did a fresh install of my OS and added Sonarr, Radarr, Jackett, and Flaresolverr. Wghen I try to add RARBG to Jackett it errors out. Usually when a indexter is having a issue it's been pulled and is no longer listed. Being RARBG I'm assuming the site itself has no issue just whatever information Jackett poles for has changed.

### Logged Error Messages

```text
Server Logs
Date	Level	Message
2022-06-11 10:07:14	Error	
System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.RarBG.<>c.<ApplyConfiguration>b__11_0() in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/RarBG.cs:line 128
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/BaseIndexer.cs:line 161
   at Jackett.Common.Indexers.RarBG.ApplyConfiguration(JToken configJson) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/RarBG.cs:line 127
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2022-06-11 10:03:55	Error	
System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.RarBG.<>c.<ApplyConfiguration>b__11_0() in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/RarBG.cs:line 128
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/BaseIndexer.cs:line 161
   at Jackett.Common.Indexers.RarBG.ApplyConfiguration(JToken configJson) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/RarBG.cs:line 127
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2022-06-11 10:03:46	Warn	
Request to RARBG failed with exception 'Request to https://torrentapi.org/pubapi_v2.php?token=1k76amrn23&format=json_extended&app_id=jackett_v0.20.1168&limit=100&ranked=0&mode=list&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54 failed (Error BadGateway) - The tracker seems to be down.'. Retrying in 0.5s... (Attempt 1 of 2).
2022-06-11 10:03:24	Error	
System.Exception: Request to https://torrentapi.org/pubapi_v2.php?token=1k76amrn23&format=json_extended&app_id=jackett_v0.20.1168&limit=100&ranked=0&mode=list&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54 failed (Error BadGateway) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/BaseIndexer.cs:line 558
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/BaseIndexer.cs:line 511
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass12_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/BaseIndexer.cs:line 487
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/BaseIndexer.cs:line 486
   at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/RarBG.cs:line 143
   at Jackett.Common.Indexers.RarBG.PerformQuery(TorznabQuery query) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/RarBG.cs:line 134
   at Jackett.Common.Indexers.RarBG.ApplyConfiguration(JToken configJson) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/RarBG.cs:line 125
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2022-06-11 10:03:06	Warn	
Request to RARBG failed with exception 'Request to https://torrentapi.org/pubapi_v2.php?token=1k76amrn23&format=json_extended&app_id=jackett_v0.20.1168&limit=100&ranked=0&mode=list&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54 failed (Error BadGateway) - The tracker seems to be down.'. Retrying in 1s... (Attempt 2 of 2).
2022-06-11 10:02:47	Warn	
Request to RARBG failed with exception 'Request to https://torrentapi.org/pubapi_v2.php?token=1k76amrn23&format=json_extended&app_id=jackett_v0.20.1168&limit=100&ranked=0&mode=list&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54 failed (Error BadGateway) - The tracker seems to be down.'. Retrying in 0.5s... (Attempt 1 of 2).
2022-06-11 10:02:11	Error	
System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.RarBG.<>c.<ApplyConfiguration>b__11_0() in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/RarBG.cs:line 128
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/BaseIndexer.cs:line 161
   at Jackett.Common.Indexers.RarBG.ApplyConfiguration(JToken configJson) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Common/Indexers/RarBG.cs:line 127
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /var/tmp/pamac-build-locutus/jackett/src/Jackett-0.20.1168/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
the RarBG API server was offline, as shown by your log `failed (Error BadGateway) - The tracker seems to be down.`

But the server appears to be back online now, so try again.
