### ISSUE TITLE
[anthelion] (testing) Test search in Anthelion => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by JReverse** [Jackett/Jackett#13319]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-06-25 22:38:03	Info	Loading Native indexers ...
2022-06-25 22:38:03	Info	Using HTTP Client: HttpWebClient2
2022-06-25 22:38:03	Info	Using FlareSolverr: http://:/
2022-06-25 22:38:03	Info	Using proxy: Disabled
2022-06-25 22:38:03	Info	App config/log directory: /config/Jackett
2022-06-25 22:38:03	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-06-25 22:38:03	Info	Running in Docker: Yes (image build: v0.20.989-ls62)
2022-06-25 22:38:03	Info	File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-06-25 22:38:03	Info	Jackett variant: CoreLinuxAmdx64
2022-06-25 22:38:03	Info	OS version: Unix 5.4.0.121 (64bit OS) (64bit process)
2022-06-25 22:38:03	Info	Environment version: 6.0.6 (/app/Jackett/)
2022-06-25 22:38:02	Info	Starting Jackett v0.20.1220
```

### Description

Not searching. For stuff.

### Logged Error Messages

```text
System.Exception: Test search in Anthelion => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 313
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

![image](https://user-images.githubusercontent.com/40630518/175798445-407978a1-0cd8-4d52-aa8f-2015ad7d19e1.png)

**Comment by garfield69** [comment]
The indexer is working for me which suggests the problem is at your end.
- Did you redact your flaresolverr address in this post, or is it really set to `http://:/` because I don't think that is a valid address.
Correct and try again.
- Have you tried using your dashboard to edit the anthelion config and re-entering your username and password (and renewing your 2fa if you have that enabled)?
- Try accessing the docker image via your terminal and doing an openssl from within the image 
```
docker exec -it jackett /bin/bash
```
and see what you get from the following:
```
openssl s_client -connect anthelion.me:443
```
- if you still do not have joy then enable your Jackett enhanced logging and repeat the test and post the redacted log file here.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details,
perhaps the enhanced log will reveal more details about your issue.
