### ISSUE TITLE
[torrentday] (updating) Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

### ISSUE THREAD

**Issue by DarrenPIngram** [Jackett/Jackett#13316]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-06-23 12:25:09	Info	
Loading Native indexers ...
2022-06-23 12:25:09	Info	
Using HTTP Client: HttpWebClient2
2022-06-23 12:25:09	Info	
Using FlareSolverr: No
2022-06-23 12:25:09	Info	
Using proxy: Disabled
2022-06-23 12:25:09	Info	
App config/log directory: /Users/di/.config/Jackett
2022-06-23 12:25:09	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-06-23 12:25:09	Info	
Running in Docker: No
2022-06-23 12:25:09	Info	
Jackett variant: CoreMacOs
2022-06-23 12:25:09	Info	
OS version: Unix 10.15.7 (64bit OS) (64bit process)
2022-06-23 12:25:09	Info	
Environment version: 6.0.6 (/Users/di/Jackett/)
2022-06-23 12:25:08	Info	
Starting Jackett v0.20.1212
```

### Description

Trying to add a cookie, exported with the Google Chrome edit my cookie / paste to clipboard does not work. Instructions for manually getting cookies seems to have changed with Chrome102 or the site is not giving a cookie in the expected way. Or user error.

I am logged in and can navigate the site.

### Logged Error Messages

```text
System.Exception: Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
   at Jackett.Common.Indexers.TorrentDay.ApplyConfiguration(JToken configJson) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/TorrentDay.cs:line 162
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /Users/runner/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
I don't have an account but cookies only appear for the login page after refreshing once. If that doesn't work for you, try a private/incognito window with no extensions enabled, or a different browser.

@garfield69 any issues for you?

**Comment by garfield69** [comment]
> any issues for you?

the torrentday indexer is working for me.

**Comment by DarrenPIngram** [comment]
I wonder what I am doing wrong then... I am at the /t page, refreshed,
shown as logged in.

Extract cookies from Chrome show similar to:

torrentday.com FALSE
/cdn-cgi/challenge-platform/h/g/flow/ov1/0.1686652XXXXX2029:1656047357:nz7PV13VxXXXXXHQVL-6KIrUQtPdaPAltNnb5nL5ve0/720311435d64376a
FALSE 0 cf_chl_seq_3cfd239908acdcb OHe7UG94X8j1XKY
.torrentday.com TRUE / TRUE 1687588188 cf_clearance
VGucbRjpXXXXXS1jobtkK77Z.ER0C58vZt.ntV0567g-1656048588-0-150
www.torrentday.com FALSE / FALSE 2147XXXX47 uid 28XXXXX
www.torrentday.com FALSE / FALSE 2XXXXX3647 pass
wGGXXXXXXjbG5FZqswMdiq9LQ4ssX
.torrentday.com TRUE / FALSE 214XXXXXX47 uid 28XXXXX
.torrentday.com TRUE / FALSE 2XXXXXX7 pass wGGXXXXXXXXwMdiq9LQ4ssX

(Obviously modified for posting). I get the big red "not logged in" box...

I've tried a couple of Chrome extensions to grab the cookies.

**Comment by garfield69** [comment]
>s the example/info in the pop-up generic, or could it be customised per tracker? Certainly your advice would be better there than looking for a PHP session text too.

the instructions are available on the jackett torrentday config page, in the cookie instructions **see here** link
![image](https://user-images.githubusercontent.com/6933240/195159183-9d6849f1-6b3e-4f86-94d8-8884a8f12dac.png)

the link takes you to https://github.com/Jackett/Jackett/wiki/Finding-cookies which shows where to find the cookie to copy/paste
that wiki also has a link to written instructions that take you https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work
