### ISSUE TITLE
[req] pixelados unit3d 6.* HTML scraping indexer

### ISSUE THREAD

**Issue by juanfcocontreras** [Jackett/Jackett#13329]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/user/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Linux Mint 20.3 Una \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.117 (64bit OS) (64bit process)
Environment version: 6.0.6 (/home/user/Desarrollo/Jackett/)
```

### Description

The API Token tab has disappear from My Security page, and previous generated API token is rising error.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (pixelados): Error Parsing Json Response: Status=NotFound Response={"success":false,"message":"Permission Error.","data":"You Are Not Allowed To Use the API!"}
 ---> System.Exception: Error Parsing Json Response: Status=NotFound Response={"success":false,"message":"Permission Error.","data":"You Are Not Allowed To Use the API!"}
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1414
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 677
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 308
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
This has nothing to do with Jackett, in so far as this is an issue with your pixelados account.
It is likely that your user ranking has been demoted such that you have no longer have been granted access to the API.
Is your ratio below par, or have you generated H&R violations or broken a site rule?
You need to contact the pixelatos support staff and find out what the reason for loosing access to the API key is, and what you need to do to restore access.

**Comment by juanfcocontreras** [comment]
> This has nothing to do with Jackett, in so far as this is an issue with your pixelados account. It is likely that your user ranking has been demoted such that you no longer have been granted access to the API. Is your ratio below par, or have you generated H&R violations or broken a site rule? You need to contact the pixelados support staff and find out what the reason for loosing access to the API key is, and what you need to do to restore access.

Thanks for the reply. Anything change on my side lately. The tracker is new and I'm in the same ranking, but I try to contact tracker staff.

**Comment by garfield69** [comment]
@TuGeek are you having any issues using the pixelados Jackett indexer?

**Comment by juanfcocontreras** [comment]
> @TuGeek are you having any issues using the pixelados Jackett indexer?

I've just written to Pixelados staff. I'll keep you posted.

Thanks for your interest!

**Comment by TuGeek** [comment]
> @TuGeek are you having any issues using the pixelados Jackett indexer?

They disallow the usage of API until the user reach a high user level in the tracker (1080p).... -_- , that changed in the last days...

We can't do anything... Only  try to parse the web with another Cardigan file... I though if we can find any solution

**Comment by garfield69** [comment]
I may be able to add a html scraping version of the indexer for this site, but I will need an invite or an account I can borrow while I research and test the alternate indexer for this site. PM at garfieldsixtynine -at- gmail.com

**Comment by TuGeek** [comment]
> I may be able to add a html scraping version of the indexer for this site, but I will need an invite or an account I can borrow while I research and test the alternate indexer for this site. PM to garfieldsixtynine -at- gmail.com

Sorry @garfield69 , but invitations are closed, and seems won't open in a near future. The new tracker is based on UNIT3D, there is any HTML scraper of another tracker based in UNIT3D in Jackett?

**Comment by garfield69** [comment]
We have a few scrapers for older 2.* and 3.* versions, but not for the 6.1.* versions of unit3d.
HDVinnie the author of unit3d wanted to promote the use of the API for versions 5.* onwards, as using the API was much easier on the web site servers' resources than generating html. 
This is why its so strange that pixelados would restrict the API use to only higher ranking users.
Did the pixelatos staff give a reason for their decision?
My intuition is that pixelatos might be reliant of the revenue generated by adverts which would only be generating clicks or views when browsing HTML pages, to help pay their server bills. Using the API would reduce that income.

I have written and tested a html scraper for Blutopia (which runs unit3d 6.1.1), but pixelados have customised their unit3d engine so I really need to have an account to be able to test login (success and failure), torrent searching with and without name queries, imdbid searching, freeleech filtering, etc etc, and the best way to get this done is to have an account.

**Comment by TuGeek** [comment]
> We have a few scrapers for older 2.* and 3.* versions, but not for the 6.1.* versions of unit3d. HDVinnie the author of unit3d wanted to promote the use of the API for versions 5.* onwards, as using the API was much easier on the web site servers' resources than generating html. This is why its so strange that pixelados would restrict the API use to only higher ranking users. Did the pixelados staff give a reason for their decision? My intuition is that pixelados might be reliant of the revenue generated by adverts which would only be generating clicks or views when browsing HTML pages, to help pay their server bills. Using the API would reduce that income.
> 
> I have written and tested a html scraper for Blutopia (which runs unit3d 6.1.1), but pixelados have customised their unit3d engine so I really need to have an account to be able to test login (success and failure), torrent searching with and without name queries, imdbid searching, freeleech filtering, etc etc, and the best way to get this done is to have an account.

There is no advertising, the decision is just stubborn that people go through the main page to "promote the community".

I have sent you an email, but from what you say you will need something else to be able to fine-tune it. I can help you with that, and I can prove whatever it takes.

I was thinking of trying to develop the definition from scratch but if you have some basis it would be perfect.

Keep in touch.

**Comment by garfield69** [comment]
I have loaded `pixelados-html.yml` to your GoogleDrive. 
The pixelados torrent html is quite different from blutopia, so I've had to customise significantly.
The torrent html you provided has no examples of freeleech so I expect the downloadvolumefactor and uploadvolumefactor detection will be incorrect.
If you can find torrent examples with each of the freeleech types for the DLVF and ULVF we can correct.
Expect indexer failures since its coded without testing so you may need to correct syntax or fix incorrect assumptions.
Try it and lets see what happens.
Check that the titles contain the most useful info (name, format, Spanish (for non-vose), overview (audio and so forth) and Proper (for the 3 types). Title should not contain the uploader, tmdb/imdb votes, thanks and comments counts.

**Comment by TuGeek** [comment]
> I have loaded `pixelados-html.yml` to your GoogleDrive. The pixelados torrent html is quite different from blutopia, so I've had to customise significantly. The torrent html you provided has no examples of freeleech so I expect the downloadvolumefactor and uploadvolumefactor detection will be incorrect. If you can find torrent examples with each of the freeleech types for the DLVF and ULVF we can correct. Expect indexer failures since its coded without testing so you may need to correct syntax or fix incorrect assumptions. Try it and lets see what happens. Check that the titles contain the most useful info (name, format, Spanish (for non-vose), overview (audio and so forth) and Proper (for the 3 types). Title should not contain the uploader, tmdb/imdb votes, thanks and comments counts.

For the first try, It seems works, good job @garfield69 !!!

I expect to have sometime this weekend to fine tuning and parse de tags for DLVF and ULVF.

**Comment by TuGeek** [comment]
> I have the same problem. any solution?

It's solved, wait for the next Jackett release. Maybe you need to reconfigure "Pixelados" in Jackett.

**Comment by garfield69** [comment]
I will post the version of Jackett that has the solve once the next release of Jackett is published (due out in about 12 hours from the time of this post).
Once you have update to that version, then use your Jackett dashboard and trash-bin the pixalados config from your **Configured Indexers** page, then click on the **Add Indexer** button, search for _pix_ and click on the **wrench** for the Pixelados-HTML indexer. Fill in the config and save.

**Comment by garfield69** [comment]
v0.20.1281

**Comment by garfield69** [comment]
It appears that pixelados have upgraded their site judging by the change in app signature.
If the indexer is not displaying all the usual data please respond.

**Comment by TuGeek** [comment]
> It appears that pixelados have upgraded their site judging by the change in app signature. If the indexer is not displaying all the usual data please respond.

It's working fine, you don't have to touch anything. 

Thanks @garfield69
