### ISSUE TITLE
[torrentfunk] (testing) Test search in TorrentFunk => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by frykauf** [Jackett/Jackett#13337]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-07-03 11:20:57	Info	
Loading Native indexers ...
2022-07-03 11:20:57	Info	
Using HTTP Client: HttpWebClient2
2022-07-03 11:20:57	Info	
Using FlareSolverr: No
2022-07-03 11:20:57	Info	
Using proxy: Disabled
2022-07-03 11:20:57	Info	
App config/log directory: /Users/Anon/.config/Jackett
2022-07-03 11:20:57	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-03 11:20:57	Info	
Running in Docker: No
2022-07-03 11:20:57	Info	
Jackett variant: CoreMacOs
2022-07-03 11:20:57	Info	
OS version: Unix 12.4.0 (64bit OS) (64bit process)
2022-07-03 11:20:57	Info	
Environment version: 6.0.6 (/Users/Anon/Downloads/Jackett/)
2022-07-03 11:20:57	Info	
Jackett stopped
2022-07-03 11:20:57	Info	
Restart of the web application host (not process) initiated
2022-07-03 11:20:57	Info	
Restarting webhost due to configuration change
2022-07-03 11:20:56	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2022-07-03 11:20:56	Info	
Adding filter indexer ('type:private' indexer) ...
2022-07-03 11:20:56	Info	
Adding filter indexer ('type:public' indexer) ...
2022-07-03 11:20:56	Info	
Adding aggregate indexer ('all' indexer) ...
2022-07-03 11:17:32	Info	
Jackett is already updated. Current version: v0.20.1270
2022-07-03 11:17:31	Info	
Checking for updates... Jackett variant: CoreMacOs
```

### Description

Test search w/ TorrentfFunk returned this error

### Logged Error Messages

```text
System.Exception: Test search in TorrentFunk => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/runner/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 315
   at Jackett.Server.Controllers.IndexerApiController.Test() in /Users/runner/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/10112#issuecomment-1172939714
