### ISSUE TITLE
[New tracker REQ] AniDex

### ISSUE THREAD

**Issue by ghost** [Jackett/Jackett#1335]
Anidex is a torrent tracker and indexer, primarily for English fansub groups of anime, but also caters for other languages and media.

AniDex is available at http://www.anidex.info and they have an IRC channel over at rizon.net; #anidex.

Their categories are currently a bit lacking and will probably be changed soon:

//ANIME
AddCategoryMapping("1", TorznabCatType.TVAnime);
//DRAMA
AddCategoryMapping("2", TorznabCatType.TV);
//PC GAMES
AddCategoryMapping("3", TorznabCatType.PC
//CONSOLE GAMES (anidex uses one single games category for now)
AddCategoryMapping("3", TorznabCatType.Console);
//LIGHT NOVELS
AddCategoryMapping("4", TorznabCatType.BooksForeign);
//MANGA
AddCategoryMapping("5", TorznabCatType.BooksComics);
//MUSIC
AddCategoryMapping("6", TorznabCatType.Audio);
//OTHER
AddCategoryMapping("7", TorznabCatType.Other);

(this is my first request, I hope I did it right)

**Comment by hergonoway** [comment]
+1 absolutely need this one since Nyaa.se closed

**Comment by ruifung** [comment]
I've taken a  quick lock at the anidex site, and it is remarkably annoying to scrape with the complete lack of marker classes / ids, thus needing to use long selectors / nth-child selectors.

On another note, is there any detailed documentation for the Definitions yml format?

**Comment by flightlevel** [comment]
https://github.com/Jackett/Jackett/wiki/Definition-format

**Comment by evq** [comment]
I put together a definition for Cardigann (it's missing categories but works otherwise):
https://github.com/evq/cardigann/blob/e7be3491c9ca8ee92abae4110ca5f2a34b8ff55b/definitions/anidex.yml

Unfortunately it won't work without modifications in Jackett. As far as I could tell there isn't a way to set request headers in the current format, so I added a way in Cardigann. (Anidex seems to ignore requests without `x-requested-with: XMLHttpRequest` made via the URL the main page uses.)

**Comment by Quatroking** [comment]
@ruifung Yeah I've tried my hand at it after finishing nyaa-pantsu and even after throwing in long selectors, it wouldn't work because their entire site is JS-based and doesn't seem to parse at all. It's pretty badly designed, but it's one of the very few anime-oriented public indexers still available to us.

**Comment by kaso17** [comment]
Added support for headers to jackett via aa6e7b148b34c582923f859953d1799d37565172 and anidex (with minimal changes) via d0d62eeae9e570358cff26913e51d30c2f1351e3
Thank you @evq

**Comment by ilike2burnthing** [comment]
https://anidex.info/ - HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://anidex.info/ - HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://anidex.info/ - 504 - Gateway Timeout

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://anidex.info/ returns HTTP ERROR 500

**Comment by garfield69** [comment]
AniDex's built in DDoS-Guard checking no longer allows my Jackett access.
getting `Exception (anidex): Anidex search returned unexpected result. Expected 200 OK but got Forbidden.`
Just me?

**Comment by ilike2burnthing** [comment]
Not just you. Another update to FlareSolverr by @ngosang is needed I think.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
not for me, I still get 
![image](https://user-images.githubusercontent.com/6933240/162042267-793fc082-8e82-4389-9594-736a16b0a5d1.png)

**Comment by ilike2burnthing** [comment]
Damn, yea it worked briefly, but not any more.

**Comment by atrumtest** [comment]
I'm also getting the same error:

>Anidex search returned unexpected result. Expected 200 OK but got Forbidden.

**Comment by Rick45** [comment]
Same error, 
tried to remove it and re add it, no success.

error from logs:

`
System.Net.WebException: Anidex search returned unexpected result. Expected 200 OK but got Forbidden.
   at Jackett.Common.Indexers.Anidex.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anidex.cs:line 193
   at Jackett.Common.Indexers.Anidex.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anidex.cs:line 142
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask 1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 
`

**Comment by Esarve** [comment]
Same error :(

**Comment by ilike2burnthing** [comment]
`same error` comments aren't helpful, please don't post them

**Comment by ngosang** [comment]
Requires FlareSolverr >= 2.2.4

**Comment by garfield69** [comment]
@ngosang  Thank you.

**Comment by garfield69** [comment]
v0.20.912
