### ISSUE TITLE
[rarbg] (testing) Exception (rarbg): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by kshannoninnes** [Jackett/Jackett#13350]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-07-11 00:41:59 	Info 	Using HTTP Client: HttpWebClient2
2022-07-11 00:41:59 	Info 	Using FlareSolverr: No
2022-07-11 00:41:59 	Info 	Using proxy: Disabled
2022-07-11 00:41:59 	Info 	App config/log directory: C:\ProgramData\Jackett
2022-07-11 00:41:59 	Info 	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-07-11 00:41:59 	Info 	Running in Docker: No
2022-07-11 00:41:59 	Info 	Jackett variant: CoreWindows
2022-07-11 00:41:59 	Info 	OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS)
2022-07-11 00:41:59 	Info 	Environment version: 6.0.6 (C:\ProgramData\Jackett\)
2022-07-11 00:41:58 	Info 	Starting Jackett v0.20.1296
```

### Description

Not really sure what special steps there might be.

- Log into Jackett
- Click "Test" on existing RARBG indexer
- Expect a successful test, but get the below exception message instead

Exception (rarbg): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### Logged Error Messages

```text
2022-07-11 00:43:52 	Error 	Jackett.Common.IndexerException: Exception (rarbg): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 143
   at Jackett.Common.Indexers.RarBG.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\RarBG.cs:line 134
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 677
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
2022-07-11 00:43:49 	Warn 	Request to RARBG failed with status 520. Retrying in 1s... (Attempt 2 of 2).
2022-07-11 00:43:46 	Warn 	Request to RARBG failed with status 520. Retrying in 0.5s... (Attempt 1 of 2).
2022-07-11 00:42:07 	Info 	Jackett startup finished in 10.296 s
2022-07-11 00:42:07 	Info 	Adding filter indexer ('type:semi-public' indexer) ...
2022-07-11 00:42:07 	Info 	Adding filter indexer ('type:private' indexer) ...
2022-07-11 00:42:07 	Info 	Adding filter indexer ('type:public' indexer) ...
2022-07-11 00:42:07 	Info 	Adding aggregate indexer ('all' indexer) ...
2022-07-11 00:42:07 	Info 	Loaded 585 indexers in total
2022-07-11 00:42:07 	Info 	Loaded 503 Cardigann indexers: 0daykiev, 0magnet, 1337x, 1ptbar, 2fast4you, 3changtrai, 3dtorrents, 4thd, 52pt, abtorrents, acervos, acgrip, acgsou, acidlounge, acrossthetasman, aftershock, aidoruonline, aither-api, amigosshare, anaschcc, anilibria, anime-free, animeclipse, animelayer, animeworld-api, aniRena, anisource, arabafenice, arabp2p, arenabg, asiancinema, audiences, audiobookbay, audionews, aussierules, backups, badasstorrents, bangumi-moe, beitai, bestcore, beyond-hd, bibliotik, bigfangroup, bitbazis, bitbr, bitcityreloaded, bitded, bithorlo, bithumen, bitru, bitsearch, bitsexy, bitspyder, Bittorrentfiles, bitturk, bluebirdhd, bluesbrothers, blutopia-api, booktracker, bootytape, borgzelle, boxingtorrents, broadcity, brsociety-api, bt4g, btdigg, btetree, btmet, btmirror, btnext, btschool, btsow, bwtorrents, byrbt, byrutor, carpathians, carphunter, cartoonchaos, cathoderaytube, catorrent, ccfbits, ceskeforum, chdbits, chilebt, cinemageddon, cinemamovies, cinematik, classix, cloudtorrents, coastalcrew, comicat, concen, concertos, cpasbien, cpasbienclone, crackingpatching, crazyhd, crazyspirits, crnaberza, crt2fa, cryptichaven, danishbytes-api, dariustracker, dark-shadow, datascene-api, datatalli, deildu, demonoid, desitorrents-api, diablotorrent, digitalcore, dimeadozen, discfan, divteam, dmhy, docspedia, dragonworldreloaded, dreamtracker, dxp, ebookparadijs, ebooks-shares, ehentai, elitetorrent-biz, empornium, empornium2fa, eniahd, esharenet, estone, exkinoray, extratorrent-st, extremebits, extremetorrents, extremlymtorrents, exttorrents, eztv, falkonvisionteam, fanoin, fantasticheaven, fantastiko, femdomcult, fenyarnyek-tracker, file-tracker, filelisting, film-paleis, finelite, finvip, firebit, fouducinema, freshmeat, frozenlayer, ftuapps, funkytorrents, gamestorrents, gay-torrents, gay-torrentsorg, gaytorrentru, generationfree-api, genesismovement, gfxpeers, gigatorrents, girotorrent, gktorrent, glodls, greekdiamond, greekteam, gtorrentpro, haidan, haitang, hamsterstudio, happyfappy, hawke-uno, hd4fans, hdai, hdarea, hdatmos, hdbits, hdbitscom, hdc, hdcenter, hdchina, hdcity, hdcztorrent, hddolby, hdforever, hdgalaktik, hdhome, hdme, hdmonkey, hdolimpo-api, hdonly, hdroute, hdsky, hdspain, hdtime, hdtorrentsit, hdturk, hdu, hdzone, houseofdevil, hqsource, huntorrent, ibit, idope, ilcorsaroblu, ilcorsaronero, ilcorsaroverde, immortuos, indietorrents, insanetracker, internetarchive, isohunt2, itorrent, iv-torrents, jav-torrent, jme-reunit3d-api, jpopsuki, jptv, karagarga, keepfriends, kickasstorrents-to, kickasstorrents-ws, kinonavse100, kinorun, kinozal, knaben, korsar, krazyzone, kufirc, lastfiles, lat-team-api, learnbits, learnflakes, leech24, legittorrents, lemonhd, lepornoinfo, lesaloon, libranet, limetorrents, limetorrentsclone, linkomanija, linuxtracker, locadora, losslessclub, mactorrentsdownload, madsrevolution, magicheaven, magico, majomparade, marinetracker, mediamaatjes, megamixtracker, megapeer, mesevilag, metaltracker, microbit, mikan, milkie, miobt, mircrew, mixtapetorrent, mma-torrents, mnv, mononokebt, mousebits, moviesdvdr, moviesite, movietorrent, movietorrentz, mteamtp, mteamtp2fa, muziekfabriek, mvgroupforum, mvgroupmain, mypornclub, myspleen, nbtorrents, netcosmo, nethd, newpct-me, newretro, newstudio, newstudiol, nipponsei, nitro, nntt, noname-club, noname-clubl, nyaasi, omgwtftrackr, oncesearch, onejav, opencd, opensharing, oshenpt, ourbits, p2pbg, p2pelite, parnuxi, pctorrent, peeratiko, peerjunkies, peersfm, pier720, pignetwork, piratbit, piratbitl, pixelados-html, pixelados, pixelcove, polishsource, pornbay, pornbits, pornforall, pornleech, pornolive, pornoslab, pornotor, pornotorrent, portugas, potuk, proaudiotorrents, proporno, prostylex, ps4-torrent, pterclub, ptfiles, pthome, ptmsg, ptsbao, pttime, punkshorror, puntotorrent, purovicio, pussytorrents, putao, puurhollands, pwtorrents, r3vwtf, racing4everyone-api, racingforme, rainbowtracker, rapidzona, redbits-api, redstartorrent, reelflix-api, resurrectthenet, rgfootball, rintor, rintornet, riperam, RockBox, romanianmetaltorrents, rptorrents, rudub, rus-media, rustorka, rutor, rutracker-ru, satclubbing, scenepalace, scenerush, sdbits, seedoff, selezen, sexypics, shanaproject, shareisland-api, sharewood, showrss, siambit, skipthecommercials-api, skipthetrailers, sktorrent-org, sktorrent, slosoul, snowpt, solidtorrents, sosulki, soulvoice, soundpark, speedmasterhd, speedtorrentreloaded, spidertk, spiritofrevolution, sporthd, sportscult, springsunday, sugoimusic, sukebeinyaasi, superbits, swarmazon, tapochek, tasmanit, teamctgame, teamhd, teamos, tekno3d, tellytorrent-api, teracod, the-crazy-ones, theaudioscene, theempire, thefallingangels, thegeeks, thehorrorcharnel, theleachzone, themixingbowl, thenewfun, theoccult, thepiratebay, theplace, thesceneplace, theshinning, theshow, thevault, tjupt, tlfbits, tmghub, tokyotosho, torlock, torlook, torrent-explosiv, torrent-pirat, torrent-turk, torrent9, torrent911, torrent9clone, torrentbd, torrentby, torrentccf, torrentcore, torrentdb, torrentdownload, torrentdownloads, torrentfunk, torrentgalaxy, torrenthr, torrenting, torrentkitty, torrentland-api, torrentleech-pl, torrentleech, torrentlt, torrentmasters, torrentoyunindir, torrentproject2, torrentqq, torrentsectorcrew, torrentseeds-api, torrentsir, torrentslocal, torrentsurf, torrentv, torrentview, torrentwhiz, torrentz2eu, totallykids, totheglory, totheglorycookie, trancetraffic, trezzor, tribalmixes, turkseed, turktorrent, turktracker, tvchaosuk, tvroad, twilight, twilightszoom, u2, uhdbits, underversel, uniondht, unionfansub, uniongang, unlimitz, vizuk, vsthouse, vsttorrents, wdt, whiteangel, wihd, woot, xiteme, xbit, xbytesv2, xthor-api, xwtclassics, xwtorrents, xxxadulttorrent, xxxtor, xxxtorrents, ydypt, yggcookie, yggtorrent, yourbittorrent, yts, zamundanet, zelkaorg, zetorrents, zomb, ztracker
2022-07-11 00:42:00 	Info 	Loading Cardigann indexers from: C:\Windows\system32\config\systemprofile\AppData\Roaming\cardigann\definitions\, C:\Windows\system32\config\systemprofile\AppData\Local\cardigann\definitions\, C:\ProgramData\Jackett\Definitions
2022-07-11 00:42:00 	Info 	Loaded 82 Native indexers: abnormal, alpharatio, anidex, anidub, animebytes, Animedia, animetorrents, anthelion, aro, avistaz, bakabt, beyond-hd-api, bithdtv, bjshare, brasiltracker, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, greatposterwall, hdbitsapi, hdspace, hdtorrents, hebits, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, myanonamouse, ncore, nebulance, norbits, oppaitime, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, ShizaProject, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentheaven, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, xspeeds, zonaq, animetosho, morethantv-api
2022-07-11 00:41:59 	Info 	Loading Native indexers ...
2022-07-11 00:41:59 	Info 	Using HTTP Client: HttpWebClient2
2022-07-11 00:41:59 	Info 	Using FlareSolverr: No
2022-07-11 00:41:59 	Info 	Using proxy: Disabled
2022-07-11 00:41:59 	Info 	App config/log directory: C:\ProgramData\Jackett
2022-07-11 00:41:59 	Info 	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-07-11 00:41:59 	Info 	Running in Docker: No
2022-07-11 00:41:59 	Info 	Jackett variant: CoreWindows
2022-07-11 00:41:59 	Info 	OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS)
2022-07-11 00:41:59 	Info 	Environment version: 6.0.6 (C:\ProgramData\Jackett\)
2022-07-11 00:41:58 	Info 	Starting Jackett v0.20.1296
```

**Comment by garfield69** [comment]
The RARBG API server at https://torrentapi.org/ is intermittently returning an Error 520 which results in a non-JSON response being returns to the indexer.
I'll try to add some detection code so the indexer can generated a better error message
But apart from that there is nothing we can do about it, as the issue is at the server end.
Try using the indexer again later. I've had a initial error just now, then a successful test a couple minutes later.

**Comment by garfield69** [comment]
v0.20.1299
