### ISSUE TITLE
[rarbg] Exception (rarbg): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Unexpected character encountered while parsing value: <. Path '', line 0, position 0. (Test)

### ISSUE THREAD

**Issue by heartdeadz** [Jackett/Jackett#13356]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-07-12 19:44:09	Info	
Loading Native indexers ...
2022-07-12 19:44:09	Info	
Using HTTP Client: HttpWebClient2
2022-07-12 19:44:09	Info	
Using FlareSolverr: No
2022-07-12 19:44:09	Info	
Using proxy: Disabled
2022-07-12 19:44:09	Info	
App config/log directory: /media/sdh1/heartdead/.config/Jackett
2022-07-12 19:44:09	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-12 19:44:09	Info	
Running in Docker: No
2022-07-12 19:44:09	Info	
File /etc/issue: Debian GNU/Linux 9 \n \l
2022-07-12 19:44:09	Info	
Jackett variant: CoreLinuxAmdx64
2022-07-12 19:44:09	Info	
OS version: Unix 4.19.123.0 (64bit OS) (64bit process)
2022-07-12 19:44:09	Info	
Environment version: 6.0.6 (/media/sdh1/heartdead/Jackett/)
2022-07-12 19:44:08	Info	
Starting Jackett v0.20.1300
```

### Description

[Warning.txt](https://github.com/Jackett/Jackett/files/9095569/Warning.txt)

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (rarbg): The response was not JSON
 ---> System.Exception: The response was not JSON
   at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 148
   at Jackett.Common.Indexers.RarBG.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 134
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 677
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

---------------------------------------------------------------------------

Also a bunch of warn text came up (tons of text, so i added it as a .txt in Description)
```

**Comment by garfield69** [comment]
The RarBG API server torrentapi.org is returning Error 520: Web server is returning an unknown error
Until RarBG fix the issue, all you can do is try again later.
You can try using your Jackett Dashboard to edit the  RarBG config and set the **Number of Retries** to a higher amount, but this you are still going to get failures from time to time.
