### ISSUE TITLE
RSS feed indicates it has failed using jacket indexer and RARBG

### ISSUE THREAD

**Issue by jprokos** [Jackett/Jackett#13363]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: /Users/john/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreMacOs
OS version: Unix 10.15.7 (64bit OS) (64bit process)
Environment version: 6.0.7 (/Users/john/GitHub/Jackett/)
Starting Jackett v0.20.1307
```

### Description

I have the Jackett plugin for qBittorrent installed

These two feeds continually fail, show up as not working, then sometimes they are eventually updated and sometimes not.
http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxx&t=search&cat=100054
http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxx&t=search&cat=5000

These feeds with tags don't appear to suffer from this issue:
http://0.0.0.0:9117/api/v2.0/indexers/tag:movies/results/torznab/api?apikey=xxx&t=search&cat=2000
http://0.0.0.0:9117/api/v2.0/indexers/tag:tv/results/torznab/api?apikey=xxx&t=search&cat=5000

Jackett log file
[log.txt](https://github.com/Jackett/Jackett/files/9121796/log.txt)

### Logged Error Messages

```text
QBT

7/15/22 9:25 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/tag:tv/results/torznab/api?apikey=xxx&t=search&cat=5000' updated. Added 46 new articles.
7/15/22 9:25 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/tag:tv/results/torznab/api?apikey=xxx&t=search&cat=5000' is successfully downloaded. Starting to parse it.
7/15/22 9:25 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/tag:movies/results/torznab/api?apikey=xxx&t=search&cat=2000' updated. Added 5 new articles.
7/15/22 9:25 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/tag:movies/results/torznab/api?apikey=xxx&t=search&cat=2000' is successfully downloaded. Starting to parse it.
7/15/22 9:25 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxx&t=search&cat=5000' updated. Added 0 new articles.
7/15/22 9:25 AM - Failed to parse RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxx&t=search&cat=5000'. Reason: Premature end of document. (line: 2, column: 1259, offset: 1298).
7/15/22 9:25 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxx&t=search&cat=5000' is successfully downloaded. Starting to parse it.
7/15/22 9:25 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxx&t=search&cat=100054' updated. Added 0 new articles.
7/15/22 9:25 AM - Failed to parse RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxx&t=search&cat=100054'. Reason: Premature end of document. (line: 2, column: 1259, offset: 1298).
7/15/22 9:25 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=xxx&t=search&cat=100054' is successfully downloaded. Starting to parse it.
```
JACKET
```
Jackett.Common.IndexerException: Exception (rarbg): The response was not JSON
 ---> System.Exception: The response was not JSON
   at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 148
   at Jackett.Common.Indexers.RarBG.PerformQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 134
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 680
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /Users/runner/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 440
```
```


### Screenshots

<img width="296" alt="screenshot_ 2022-07-15 at 9 37 07 AM" src="https://user-images.githubusercontent.com/9438406/179245858-edef9587-322b-4a29-adf7-c0df48c4b026.png">

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13358#issuecomment-1183775496

**Comment by ilike2burnthing** [comment]
Increasing the number of retries doesn't fix the issue, as the problem lies with RARBG, it only reduces the chance of a failure for a single search (e.g. failing 5 times in a row is much less likely, but still possible).

`indexer specific categories (>= 100000) can't be used` should only apply to the aggregate `ALL` indexer and filter indexers such as tags.

**Comment by jprokos** [comment]
@ilike2burnthing 
Thank you for all of your replies.

Do you think this has to do with RARBG limits from certain IP addresses or something else?
It seems totally random when it works and when it doesn't. I can make multiple request in succession and get articles using curl, but then try again in 15 minutes and get the error below. I know this has been posted before just adding it for the record and search patterns

Also, there are times I get the red x icon even though new articles do show up.

Has anyone contacted RARBG about this? What has their response been to this issue?
```
<error code="900" description="Jackett.Common.IndexerException: Exception (rarbg): The response was not JSON&#xA; ---&gt; System.Exception: The response was not JSON&#xA;   at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 148&#xA;   at Jackett.Common.Indexers.RarBG.PerformQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 134&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324&#xA;   --- End of inner exception stack trace ---&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 680&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /Users/runner/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 440" />
```

**Comment by ilike2burnthing** [comment]
The indexer already incorporates a delay to abide by the API request limit:
https://github.com/Jackett/Jackett/blob/aae44fd2d521d63be1e7a91779a7733f016d3311/src/Jackett.Common/Indexers/RarBG.cs#L67

So no matter how many times you search, or how many retries you enable, it will never exceed 1req/2s in a single instance of Jackett.

**Comment by jprokos** [comment]
Got it. I guess I have two issues then. The one that is mentioned here and is caused by the RARBG API server, and the other which appears to be related to something else, either in Jackett or qBittorrent.
If I remove  the RSS URL from qBittorrent and then add it... it works on the first try. Then on subsequent tries it always errors out with something like this:

```
7/17/22 9:38 PM - Failed to parse RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=search&cat=100054&limit=100&q='. Reason: Premature end of document. (line: 2, column: 1259, offset: 1298).
7/17/22 9:38 PM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/rarbg/results/torznab/api?apikey=redacted&t=search&cat=100054&limit=100&q=' updated. Added 0 new articles.
```

**Comment by ilike2burnthing** [comment]
If you disable the cache in Jackett does the issue continue?

**Comment by jprokos** [comment]
Yes it does.

**Comment by ilike2burnthing** [comment]
If you try a different indexer, does the same issue occur? 

If you switch from `0.0.0.0` to `127.0.0.1`, does the same issue occur?

If you downgrade to the latest stable build of qBittorrent (v4.4.3.1), does the same issue occur?

I can't replicate the issue on Windows when using `127.0.0.1` on v4.4.3.1

**Comment by jprokos** [comment]
> If you try a different indexer, does the same issue occur?

I will try this to test, but I only use RARBG. All of my scripts are set up for their naming scheme, etc..

> If you switch from 0.0.0.0 to 127.0.0.1, does the same issue occur?

I have another indexer running at the same time that uses Jackett. So far it has not had this "parsing" issue - but the command is different. It uses `tag:rarbg` where I have only added that tag to the RARBG indexer. Because of that difference... just fishing around to see, I created another rule for category `100054` using `tag:rarbg` that errors after the first time it's run. I thought maybe it's the category that's the issue so I tried `2040` and filtered it, but that also errors. 

This is the feed that's not having the issue right now:
`http://0.0.0.0:9117/api/v2.0/indexers/tag:rarbg/results/torznab/api?apikey=redacted&t=search&cat=5040&q=`

```
7/18/22 10:42 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/tag:rarbg/results/torznab/api?apikey=redacted&t=search&cat=5040&q=' is successfully downloaded. Starting to parse it.
7/18/22 10:42 AM - RSS feed at 'http://0.0.0.0:9117/api/v2.0/indexers/tag:rarbg/results/torznab/api?apikey=redacted&t=search&cat=5040&q=' updated. Added 11 new articles.
```

> If you downgrade to the latest stable build of qBittorrent (v4.4.3.1), does the same issue occur?

The reason I upgraded was because I was getting this issue on the latest stable build. I think I would have to go back in versions to find a different release - not sure exactly sure when this appeared.

**Comment by jprokos** [comment]
maybe jumping the gun, but it looks like sometimes the RSS feed is automatically renamed to the indexer name? Other times it has not been renamed (maintaining the long cumbersome name of the command) and I have always renamed it after its first run - maybe it's the renaming of the new feed subscription that is causing this issue? Because I didn't rename the naughty one this time and it seems to be running properly - so far.

Is there a cache of the RSS commands somewhere in qBT that may need to be cleared out - if the rules were different but renamed the same that could potentially cause a conflicts?

**Comment by ilike2burnthing** [comment]
Not sure. You'd need to direct those questions to qBit devs.
