### ISSUE TITLE
[hdatmos] (updating) Login failed: No form found on https://hdatmos.club/login.php using form selector form[action="takelogin.php"]

### ISSUE THREAD

**Issue by mohitjoshi155** [Jackett/Jackett#13369]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-07-17 13:31:52	Info	Using HTTP Client: HttpWebClient2
2022-07-17 13:31:52	Info	Using FlareSolverr: http://redacted:8191/
2022-07-17 13:31:52	Info	Using proxy: Disabled
2022-07-17 13:31:52	Info	App config/log directory: /config/Jackett
2022-07-17 13:31:52	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-07-17 13:31:52	Info	Running in Docker: Yes (image build: v0.20.1096-ls67)
2022-07-17 13:31:52	Info	File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-07-17 13:31:52	Info	Jackett variant: CoreLinuxAmdx64
2022-07-17 13:31:52	Info	OS version: Unix 4.19.0.20 (64bit OS) (64bit process)
2022-07-17 13:31:52	Info	Environment version: 6.0.7 (/app/Jackett/)
2022-07-17 13:31:51	Info	Starting Jackett v0.20.1316
```

### Description

enter hdatmos credentials on jackett
expected to work normally

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://hdatmos.club/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 590
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 985
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
Please provide an enhanced log so we can take a look at the traffic to/from the site and see if we can spot the problem.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
Thanks.

**Comment by mohitjoshi155** [comment]
> Please provide an enhanced log so we can take a look at the traffic to/from the site and see if we can spot the problem. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details. Thanks.

`2022-07-17 08:31:07.6216 Debug Connection id "0HMJ7PAF0SPE0" accepted. 
2022-07-17 08:31:07.6403 Debug Connection id "0HMJ7PAF0SPE0" started. 
2022-07-17 08:31:07.6403 Debug Connection id "0HMJ7PAF0SPE1" accepted. 
2022-07-17 08:31:07.6403 Debug Connection id "0HMJ7PAF0SPE1" started. 
2022-07-17 08:31:23.9083 Debug Connection id "0HMJ7PAF0SPE0" received FIN. 
2022-07-17 08:31:23.9083 Debug Connection id "0HMJ7PAF0SPE0" disconnecting. 
2022-07-17 08:31:23.9083 Debug Connection id "0HMJ7PAF0SPE0" sending FIN because: "The client closed the connection." 
2022-07-17 08:31:23.9083 Debug Connection id "0HMJ7PAF0SPE0" stopped. 
2022-07-17 08:31:23.9083 Debug Connection id "0HMJ7PAF0SPE1" received FIN. 
2022-07-17 08:31:23.9083 Debug Connection id "0HMJ7PAF0SPE1" disconnecting. 
2022-07-17 08:31:23.9083 Debug Connection id "0HMJ7PAF0SPE1" sending FIN because: "The client closed the connection." 
2022-07-17 08:31:23.9119 Debug Connection id "0HMJ7PAF0SPE1" stopped. 
2022-07-17 08:31:29.2056 Debug Connection id "0HMJ7PAF0SPE2" accepted. 
2022-07-17 08:31:29.2056 Debug Connection id "0HMJ7PAF0SPE2" started. 
2022-07-17 08:31:29.2056 Info Request starting HTTP/1.1 GET http://redacted:9118/api/v2.0/indexers/hdatmos/config?_=1658046154237 - - 
2022-07-17 08:31:29.2056 Debug Request is continuing in applying rules. Current url is http://redacted:9118/api/v2.0/indexers/hdatmos/config?_=1658046154237 
2022-07-17 08:31:29.2056 Debug Request is continuing in applying rules. Current url is http://redacted:9118/api/v2.0/indexers/hdatmos/config?_=1658046154237 
2022-07-17 08:31:29.2056 Debug Request is continuing in applying rules. Current url is http://redacted:9118/api/v2.0/indexers/hdatmos/config?_=1658046154237 
2022-07-17 08:31:29.2056 Debug The request path /api/v2.0/indexers/hdatmos/config does not match a supported file type 
2022-07-17 08:31:29.2056 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2022-07-17 08:31:29.2072 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/hdatmos/config' 
2022-07-17 08:31:29.2072 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/hdatmos/config' 
2022-07-17 08:31:29.2072 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
2022-07-17 08:31:29.2072 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
2022-07-17 08:31:29.2072 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2022-07-17 08:31:29.2072 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2022-07-17 08:31:29.2072 Debug Execution plan of resource filters (in the following order): None 
2022-07-17 08:31:29.2072 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2022-07-17 08:31:29.2072 Debug Execution plan of exception filters (in the following order): None 
2022-07-17 08:31:29.2072 Debug Execution plan of result filters (in the following order): None 
2022-07-17 08:31:29.2072 Debug Authorization was successful. 
2022-07-17 08:31:29.2072 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-07-17 08:31:29.2072 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-07-17 08:31:29.2072 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://hdatmos.club/login.php) 
2022-07-17 08:31:29.4475 Debug Connection id "0HMJ7PAF0SPE3" accepted. 
2022-07-17 08:31:29.4475 Debug Connection id "0HMJ7PAF0SPE3" started. 
2022-07-17 08:31:29.4560 Debug WebClient(HttpWebClient2): Returning OK => 3794 bytes
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="NexusPHP" />
<title>HDAtmos *HDAtmos 阿童木洗版4K蓝光原盘高清 Atmos/DTS:X  - Powered by NexusPHP</title>
<script src="/cdn-cgi/apps/head/ti_3u82roXIftvQsoXXI6GCy_HI.js"></script><link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="search" type="application/opensearchdescription+xml" title="HDAtmos Torrents" href="opensearch.php" />
<link rel="stylesheet" href="styles/mediumfont.css" type="text/css" />
<link rel="stylesheet" href="styles/sprites.css" type="text/css" />
<link rel="stylesheet" href="pic/forum_pic/chs/forumsprites.css" type="text/css" />
<link rel="stylesheet" href="styles/BlueGene/theme.css" type="text/css" />
<link rel="stylesheet" href="styles/BlueGene/DomTT.css" type="text/css" />
<link rel="stylesheet" href="styles/curtain_imageresizer.css" type="text/css" />
<link rel="alternate" type="application/rss+xml" title="Latest Torrents" href="torrentrss.php" />
<script type="text/javascript" src="js/curtain_imageresizer.js"></script>
<script type="text/javascript" src="js/ajaxbasic.js"></script>
<script type="text/javascript" src="js/common.js"></script>
<script type="text/javascript" src="js/domLib.js"></script>
<script type="text/javascript" src="js/domTT.js"></script>
<script type="text/javascript" src="js/domTT_drag.js"></script>
<script type="text/javascript" src="js/fadomatic.js"></script>
<script type="text/javascript" src="js/jquery-1.12.4.min.js"></script>
<script type="text/javascript">jQuery.noConflict();</script>
<script type="text/javascript" src="vendor/layer-v3.5.1/layer/layer.js"></script>
</head>
<body>
<table class="head" cellspacing="0" cellpadding="0" align="center">
	<tr>
		<td class="clear">
			<div class="logo_img"><img src="https://z4a.net/images/2020/11/05/logo.png" alt="HDAtmos" title="HDAtmos - 喜欢洗版原盘  请到【投影玩家&amp;洗版收藏】专区下载" /></div>
		</td>
		<td class="clear nowrap" align="right" valign="middle">
			<a href="donate.php"><img src="pic/forum_pic/chs/donate.gif" alt="Make a donation" style="margin-left: 5px; margin-top: 50px;" /></a>
		</td>
	</tr>
</table>

<table class="mainouter" width="1200" cellspacing="0" cellpadding="5" align="center">
	<tr><td id="nav_block" class="text" align="center">
			<a href="login.php"><font class="big"><b>登录</b></font></a> / <a href="signup.php"><font class="big"><b>注册</b></font></a>
<table align="center" class="main" width="500" border="0" cellpadding="0" cellspacing="0"><tr><td class="embedded">
<h2>Login 锁定！(认证的最大错误尝试次数Login次已到)</h2>
<table width="100%" border="1" cellspacing="0" cellpadding="10"><tr><td class="text">我们怀疑你在欺骗系统，因此禁用了你的IP地址！</td></tr></table></td></tr></table>
</td></tr></table><div id="footer"><div style="margin-top: 10px; margin-bottom: 30px;" align="center"> (c)  <a href="https://hdatmos.club" target="_self">HDAtmos</a> 2020-2022 Powered by <a href="aboutnexus.php">NexusPHP</a><br /><br />[page created in <b> 0.023 </b> sec with <b>2</b> db queries, <b>4</b> reads and <b>0</b> writes of Redis and <b>1.37 MB</b> ram]</div>
<div style="display: none;" id="lightbox" class="lightbox"></div><div style="display: none;" id="curtain" class="curtain"></div></div><script type="application/javascript" src="js/nexus.js"></script>
<script type="application/javascript" src="vendor/jquery-goup-1.1.3/jquery.goup.min.js"></script>
<script>
jQuery(document).ready(function(){
    jQuery.goup()
});
</script></body></html> 
2022-07-17 08:31:29.4560 Debug updating Cookies  =>  
2022-07-17 08:31:29.4560 Debug CardigannIndexer (hdatmos): No captcha image found 
2022-07-17 08:31:29.4560 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter 
2022-07-17 08:31:29.4560 Debug No information found on request to perform content negotiation. 
2022-07-17 08:31:29.4560 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response. 
2022-07-17 08:31:29.4560 Debug Attempting to select the first formatter in the output formatters list which can write the result. 
2022-07-17 08:31:29.4560 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response. 
2022-07-17 08:31:29.4560 Info Executing OkObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'. 
2022-07-17 08:31:29.4560 Debug The response will be compressed with 'gzip'. 
2022-07-17 08:31:29.4560 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 250.3635ms 
2022-07-17 08:31:29.4560 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
2022-07-17 08:31:29.4560 Debug Connection id "0HMJ7PAF0SPE2" completed keep alive response. 
2022-07-17 08:31:29.4560 Info Request finished HTTP/1.1 GET http://redacted:9118/api/v2.0/indexers/hdatmos/config?_=1658046154237 - - - 200 - application/json;+charset=utf-8 252.5761ms 
2022-07-17 08:31:33.2748 Info Request starting HTTP/1.1 POST http://redacted:9118/api/v2.0/indexers/hdatmos/config application/json 311 
2022-07-17 08:31:33.2748 Debug Request is continuing in applying rules. Current url is http://redacted:9118/api/v2.0/indexers/hdatmos/config 
2022-07-17 08:31:33.2751 Debug Request is continuing in applying rules. Current url is http://redacted:9118/api/v2.0/indexers/hdatmos/config 
2022-07-17 08:31:33.2751 Debug Request is continuing in applying rules. Current url is http://redacted:9118/api/v2.0/indexers/hdatmos/config 
2022-07-17 08:31:33.2751 Debug POST requests are not supported 
2022-07-17 08:31:33.2751 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2022-07-17 08:31:33.2751 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/hdatmos/config' 
2022-07-17 08:31:33.2751 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/hdatmos/config' 
2022-07-17 08:31:33.2751 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2022-07-17 08:31:33.2751 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2022-07-17 08:31:33.2751 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2022-07-17 08:31:33.2751 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2022-07-17 08:31:33.2751 Debug Execution plan of resource filters (in the following order): None 
2022-07-17 08:31:33.2751 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2022-07-17 08:31:33.2751 Debug Execution plan of exception filters (in the following order): None 
2022-07-17 08:31:33.2751 Debug Execution plan of result filters (in the following order): None 
2022-07-17 08:31:33.2751 Debug Authorization was successful. 
2022-07-17 08:31:33.2751 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-07-17 08:31:33.2751 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-07-17 08:31:33.2751 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2022-07-17 08:31:33.2751 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2022-07-17 08:31:33.2751 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
2022-07-17 08:31:33.2751 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
2022-07-17 08:31:33.2751 Debug Connection id "0HMJ7PAF0SPE2", Request id "0HMJ7PAF0SPE2:00000003": started reading request body. 
2022-07-17 08:31:33.2751 Debug Connection id "0HMJ7PAF0SPE2", Request id "0HMJ7PAF0SPE2:00000003": done reading request body. 
2022-07-17 08:31:33.2751 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2022-07-17 08:31:33.2751 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2022-07-17 08:31:33.2751 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2022-07-17 08:31:33.2751 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2022-07-17 08:31:33.2751 Debug CACHE IsCacheEnabled => false 
2022-07-17 08:31:33.2751 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 1.8624ms 
2022-07-17 08:31:33.2751 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2022-07-17 08:31:33.2751 Error Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://hdatmos.club/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 590
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 985
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://hdatmos.club/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 590
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 985
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2022-07-17 08:31:33.2820 Debug The response will be compressed with 'gzip'. 
2022-07-17 08:31:33.2820 Debug Connection id "0HMJ7PAF0SPE2" completed keep alive response. 
2022-07-17 08:31:33.2820 Info Request finished HTTP/1.1 POST http://redacted:9118/api/v2.0/indexers/hdatmos/config application/json 311 - 500 - application/json 7.7000ms 
`

**Comment by garfield69** [comment]
the login page is showing this (translated with google)
```
Login Locked! (The maximum number of failed authentication attempts Login times has been reached)
We suspect you are cheating the system, so we disabled your IP address!
```

Can you login with your browser?
You may need to contact the site's admin via the browser login page contacts and see if you can sort it out.

**Comment by mohitjoshi155** [comment]
> the login page is showing this (translated with google)
> 
> ```
> Login Locked! (The maximum number of failed authentication attempts Login times has been reached)
> We suspect you are cheating the system, so we disabled your IP address!
> ```
> 
> Can you login with your browser? You may need to contact the site's admin via the browser login page contacts and see if you can sort it out.

ya i can login from browser but its from a different ip since i browse locally and use jackett on server

**Comment by ilike2burnthing** [comment]
You'll need to either move your Jackett installation or use a proxy or VPN to resolve your issue.
