### ISSUE TITLE
error when trying to change indexer URL

### ISSUE THREAD

**Issue by chenks** [Jackett/Jackett#13361]
### Have you checked our Troubleshooting page for your issue?

- [x] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.492-ls55)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.59.0 (64bit OS) (64bit process)
Environment version: 6.0.7 (/app/Jackett/)
Starting Jackett v0.20.1305
```

### Description

my ISP has now blocked torrentleech.cc but torrentleech.me still works.
attempting to change the URL in jackett fails saying

```
An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: Cannot determine the frame size or a corrupted frame was received.
```

i can browse torrentleech.me fine in a web browser so no idea why jackett is having issues.

### Logged Error Messages

```text
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 530
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 561
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 985
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Are your browser and the Jackett Docker container running on the same device with the same IP and using the same DNS?

**Comment by chenks** [comment]
> Are your browser and the Jackett Docker container running on the same device with the same IP and using the same DNS?

no they are not.
browser is on my laptop, jacket is running in a docker on my Synology NAS.
both are using the same DNS though.

**Comment by ilike2burnthing** [comment]
Do they have the same public IP?

**Comment by chenks** [comment]
> Do they have the same public IP?

yes

**Comment by ilike2burnthing** [comment]
How have you set the DNS for Jackett? For the NAS as a whole, or for the container specifically? Have you tried both?

**Comment by chenks** [comment]
for the NAS as a whole.
all my LAN devices (and dockers) use the same DNS server, which is pihole using cloudfare.
i've tried it with pihole disable and the issue remains, also tried it with pihole using google, also same issue.

```
An error occurred while testing this indexer
Exception (torrentleech): Cannot determine the frame size or a corrupted frame was received.: The SSL connection could not be established, see inner exception.
```

**Comment by ilike2burnthing** [comment]
Try just setting the DNS server as Cloudflare or Google directly, skip Pihole. Also try this in the Jackett container settings.

**Comment by chenks** [comment]
> Try just setting the DNS server as Cloudflare or Google directly, skip Pihole. Also try this in the Jackett container settings.

i already tried that, disabling pihole completey and the issue remains. i see no option to set DNS specifically within the container settings?

i don't believe this to be a DNS or local network issue though.

**Comment by ilike2burnthing** [comment]
Docker run:

```text
--dns="1.0.0.1" --dns="1.1.1.1"
```

Docker compose:

```yml
dns:
  - "1.0.0.1"
  - "1.1.1.1"
```

Portainer:

> Duplicate/Edit > Advanced container settings > Network > Primary/Secondary DNS Server > Deploy the container

**Comment by chenks** [comment]
i'm using synology NAS with the synology docker app, not sure if those are available to me (don't have portainer installed).
i'll take a look though, but i doubt this is a DNS issue otherwise it would be affecting all my devices, and it's not.

**Comment by chenks** [comment]
> Try just setting the DNS server as Cloudflare or Google directly, skip Pihole. Also try this in the Jackett container settings.

made no difference.
enhanced logs attached
[log.txt](https://github.com/Jackett/Jackett/files/9113042/log.txt)

**Comment by garfield69** [comment]
FWIW, as a control, I have no issues using the Jackett torrentleech indexer with any of the 3 domains
`https://www.torrentleech.org/ https://www.torrentleech.cc/ https://www.torrentleech.me/`
on my win10 platform.
So you should concentrate your research on your network path starting from within docker out to WAN and consider what security apps, DNS, router and ISP, one of which may be interfering with your access to any of these 3 domains, and compare them to your laptop whose browser you say works ok.
You can take Jackett out of the equation if you like, by opening a terminal to your docker image and seeing if url or openssl can get a response.

```
docker exec -it jackett /bin/bash
```
and see what you get from the following:
```
openssl s_client -connect www.torrentleech.org:443
```
and
```
curl -vvv https://www.torrentleech.org/
```
Do the same for *.cc and *.me and compare.

**Comment by garfield69** [comment]
A recent ticket with a user on docker and torrentleech discovered that ipv6 was a problem, see #13064

**Comment by chenks** [comment]
> curl -vvv https://www.torrentleech.org/

see below.

```
root@jackett:/# openssl s_client -connect www.torrentleech.cc:443                                 
CONNECTED(00000005)                                                                               
140391082934720:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl
3_record.c:332:                                                                                   
---                                                                                               
no peer certificate available                                                                     
---                                                                                               
No client certificate CA names sent                                                               
---                                                                                               
SSL handshake has read 5 bytes and written 321 bytes                                              
Verification: OK                                                                                  
---                                                                                               
New, (NONE), Cipher is (NONE)                                                                     
Secure Renegotiation IS NOT supported                                                             
Compression: NONE                                                                                 
Expansion: NONE                                                                                   
No ALPN negotiated                                                                                
Early data was not sent                                                                           
Verify return code: 0 (ok)                                                                        
---                                                                                               
root@jackett:/# curl -vvv https://www.torrentleech.cc/                                            
*   Trying 172.67.141.14...                                                                       
* TCP_NODELAY set                                                                                 
* Connected to www.torrentleech.cc (172.67.141.14) port 443 (#0)                                  
* ALPN, offering h2                                                                               
* ALPN, offering http/1.1                                                                         
* successfully set certificate verify locations:                                                  
*   CAfile: /etc/ssl/certs/ca-certificates.crt                                                    
  CApath: /etc/ssl/certs                                                                          
* TLSv1.3 (OUT), TLS handshake, Client hello (1):                                                 
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number                                
* stopped the pause stream!                                                                       
* Closing connection 0                                                                            
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number        
```

**Comment by garfield69** [comment]
yup, so this is not a Jackett issue, but a docker one.
Try disabling the docker ipv6 and see iif that helps.

**Comment by chenks** [comment]
> yup, so this is not a Jackett issue, but a docker one. Try disabling the docker ipv6 and see if that helps.

i'm not aware of IPv6 being enabled? i don't have IPv6 on my LAN or WAN.
and it was working fine up until 2 days ago, and nothing has changed on my LAN side.

the docker is running on synology NAS, using the synology docker app, and on the NAS itself the IPv6 setting is disabled

**Comment by garfield69** [comment]
then your next avenue for help is the docker syno community, as there is little we can from the Jackett side.

**Comment by chenks** [comment]
> then your next avenue for help is the docker syno community, as there is little we can do from the Jackett side.

where in my previous post does it point that it's an IPv6 issue?
i've never had IPv6 enabled, and apart from torrentleech Jackett still works correctly, torrentleech only stopped working 2 days ago and nothing has changed on my LAN side or in jacket config.

**Comment by garfield69** [comment]
I am not stating that it is an ipv6 issue.
I only suggested that as an option to explore, based on a similar issue raised by another Jackett user on Docker trying to access torrentleach.
You have shown that curl on that docker image cannot access torrentleech, so that eliminates Jackett from the equation.
And I have shown that Jackett on other platforms can access the torrentleech site via its indexer using any of the 3 available domains.
So we are left with a mystery, on a syno docket image, for which we cannot offer further support.
Which is why I suggest you try getting help from the syno support community since they may have more experience with syno docker and issues accessing  domains.

**Comment by chenks** [comment]
> You have shown that curl on that docker image cannot access torrentleech, so that eliminates Jackett from the equation.

does it?
but this line says "connected"

root@jackett:/# curl -vvv https://www.torrentleech.cc/                                            
*   Trying 172.67.141.14...                                                                       
* TCP_NODELAY set                                                                                 
* Connected to www.torrentleech.cc (172.67.141.14) port 443 (#0)

**Comment by garfield69** [comment]
`error:1408F10B:SSL routines:ssl3_get_record:wrong version number      `

**Comment by chenks** [comment]
> `error:1408F10B:SSL routines:ssl3_get_record:wrong version number `

that tends to be server side error though, not a client side error, and usually means that the response from 443 is HTTP rather than HTTPS, and isn't related to IPv6.

usually it means there is an apache config issue, and if true everyone should get the same result, but you said that it was working fine for you ?

**Comment by garfield69** [comment]
> but you said that it was working fine for you ?

```
2022-07-15 19:11:50 | Info | Test search in TorrentLeech => Found 100 releases
-- | -- | --
2022-07-15 19:11:50 | Debug | Saving new config file: C:\ProgramData\Jackett\Indexers\torrentleech.json.e4f403dc5792424394686bc2020e99c9.tmp
2022-07-15 19:11:50 | Debug | updating Cookies PHPSESSID=redacted; member_id=redacted; pass_hash=redacted; tluid=1597228; tlpass=redacted; lastBrowse1=redacted; lastBrowse2=redacted=> PHPSESSID=lh6c36812e8jtrjq7er5la5mu0; member_id=841763; pass_hash=bf5ba5a1ac2de8dbf025f989ba008f69; tluid=1597228; tlpass=487a150e6b37f397cafe01b402c0aa9f9462ab6a; lastBrowse1=1657834195; lastBrowse2=1657869110
2022-07-15 19:11:50 | Debug | WebClient(HttpWebClient2): Returning OK => 48397 bytes {"numFound":1684239,"torrentList":[{"fid":"240863577",[...]}
2022-07-15 19:11:50 | Debug | PHPSESSID=lh6c36812e8jtrjq7er5la5mu0; path=/; secure
2022-07-15 19:11:50 | Debug | lastBrowse1=redacted; expires=Tue, 19-Jan-2038 03:14:07 GMT; Max-Age=489614537; path=/; domain=.torrentleech.org; secure
2022-07-15 19:11:50 | Debug | PHPSESSID=redacted; path=/; secure
2022-07-15 19:11:47 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.torrentleech.org/torrents/browse/list/exact/1/query//newfilter/2/orderby/added/order/desc)
```

**Comment by garfield69** [comment]
this one using the indexer with the *.cc sitelink
```
2022-07-15 19:19:34 | Info | Test search in TorrentLeech => Found 100 releases
-- | -- | --
2022-07-15 19:19:33 | Debug | Saving new config file: C:\ProgramData\Jackett\Indexers\torrentleech.json.e3cfd82c05be49658b7c84bccec6d604.tmp
2022-07-15 19:19:33 | Debug | updating Cookies PHPSESSID=redacted; member_id=redacted; pass_hash=redacted; tluid=redacted; tlpass=redacted=> PHPSESSID=redacted; member_id=redacted; pass_hash=redacted; tluid=redacted; tlpass=redacted; lastBrowse1=redacted; lastBrowse2=redacted
2022-07-15 19:19:33 | Debug | WebClient(HttpWebClient2): Returning OK => 48555 bytes {"numFound":1684254,"torrentList[...]}
2022-07-15 19:19:33 | Debug | lastBrowse1=redacted; expires=Tue, 19-Jan-2038 03:14:07 GMT; Max-Age=489614074; path=/; domain=.torrentleech.org; secure
2022-07-15 19:19:32 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.torrentleech.cc/torrents/browse/list/exact/1/query//newfilter/2/orderby/added/order/desc)
```

**Comment by garfield69** [comment]
Could the issue be that the docker is trying ipv6 and the ca conflict arises because everything outside of the image is ipv4?
Try disabling the ipv6 in docker, it cost you nothing to try and will eliminate one more possibility. I've got nothing else to offer.

**Comment by chenks** [comment]
> Try disabling the ipv6 in docker, it cost you nothing to try and will eliminate one more possibility. I've got nothing else to offer.

IPv6 is not enabled in the docker, never has been.

**Comment by garfield69** [comment]
@ilike2burnthing  I'm passing the baton back to you, linux docker syno oh my, not my area of expertise ;-)

**Comment by garfield69** [comment]
@chenks  are you using an Asus router by any chance? a recent ticket sporting similar frame corruption error from jackett had this comment posted just now https://github.com/Jackett/Jackett/issues/11963#issuecomment-1185343932

**Comment by garfield69** [comment]
could ASUS push FW updates or is it completely up to you to initiate? Seems extremely coincidental that the route model and frame error coincide with a Jackett failure but browser allowed issue, don't you think?

**Comment by chenks** [comment]
> could ASUS push FW updates or is it completely up to you to initiate? Seems extremely coincidental that the router model and frame error coincide with a Jackett failure but browser allowed issue, don't you think?

manual update only

**Comment by garfield69** [comment]
Does Jackett nyaa.si indexer also fail in the same way as torrentleech?

**Comment by chenks** [comment]
> Does Jackett nyaa.si indexer also fail in the same way as torrentleech?

that URL is actually on a trend micro public malware list, that's why asus routers are blocking that particular site.
it can be unblocked from within the router admin page though, so this isn't the same issue as what i have

![Screenshot 2022-07-15 103401](https://user-images.githubusercontent.com/11945919/179196789-3a708803-5856-4b6a-b655-c91bb5b3da9c.jpg)
.

**Comment by garfield69** [comment]
does the route have logging capability, perhaps an option to increase the logging level, to see if it records anything about blocking while you try accessing the indexer with torrentleech.cc ?

**Comment by chenks** [comment]
> does the router have logging capability, perhaps an option to increase the logging level, to see if it records anything about blocking while you try accessing the indexer with torrentleech.cc ?

it probably does, but as i can access it everywhere else on my LAN (on laptop, phone etc) i'm not sure what the router log would specifically show when jackett tries to communicate with it.

**Comment by garfield69** [comment]
All I'm saying is, there is the possibility that your ASUS router could be interfering with access to torrentleech such that browsers get a pass but Jackett and Prowlerr don't. And the block comes in the form of a frame corruption error.
Food for thought.

**Comment by ilike2burnthing** [comment]
All good recommendations from garfield69, I would suggest trying them.

IPv6 - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established

**Comment by chenks** [comment]
issues remains.
removed router from equation and connected direct to the internet - made no difference
IPv6 is not enabled anyway, router, NAS or docker container.

**Comment by ilike2burnthing** [comment]
It's enabled by default, you'd need to disable it to see if it's the issue.

**Comment by chenks** [comment]
> It's enabled by default, you'd need to disable it to see if it's the issue.

it's not enabled by default in the synology docker process.
i checked, IPv6 is NOT enabled, and never has been.

**Comment by ilike2burnthing** [comment]
There is no option to enable it, there's only the aforementioned setting to disable it.

**Comment by chenks** [comment]
gotta just keep repeating it.
IPv6 is **NOT** enabled, never has been, never will be

**Comment by chenks** [comment]
![Screenshot 2022-07-15 155636](https://user-images.githubusercontent.com/11945919/179249570-fa4fd2d9-c951-480d-a0e7-5e33605f78b1.jpg)

**Comment by ilike2burnthing** [comment]
Synology is different than everything else I've used then.

Repeat the tests in https://github.com/Jackett/Jackett/issues/13361#issuecomment-1184855758 for another container and also your host Synology device. If the issue is the same for your other containers but not the NAS, then the issue lies with your Docker setup. If the issue also persists on the NAS, then the issue lies there.

**Comment by ilike2burnthing** [comment]
Also try disabling `QoS - Web History` in your router settings - https://github.com/Jackett/Jackett/issues/11963#issuecomment-1185674903
