### ISSUE TITLE
[acgrip] (testing) Exception (acgrip): Resource temporarily unavailable: Resource temporarily unavailable (acg.rip:443)

### ISSUE THREAD

**Issue by champion-hope** [Jackett/Jackett#13404]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Description

长时间没启动后一直测试失败

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (acgsou): Resource temporarily unavailable: Resource temporarily unavailable (www.36dm.club:443)
```

**Comment by ilike2burnthing** [comment]
You're having this issue with both ACGsou and ACG.RIP? Are any other indexers working for you?

**Comment by garfield69** [comment]
See https://github.com/Jackett/Jackett/wiki/Troubleshooting/#resource-temporarily-unavailable

**Comment by champion-hope** [comment]
都不行，都出错了，不知道为什么


枯港
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jackett/Jackett"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月26日(星期二) 中午11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jackett/Jackett] [acgrip] (testing) Exception (acgrip): Resource temporarily unavailable: Resource temporarily unavailable (acg.rip:443) (Issue #13404)





 
You're having this issue with both ACGsou and ACG.RIP? Are any other indexers working for you?

**Comment by ilike2burnthing** [comment]
If all indexers are failing, then it's likely an issue with your setup, not Jackett.

See the troubleshooting link provided by garfield69, and if that doesn't work then please supply the environment information as requested.
