### ISSUE TITLE
[v0.20.1496] [yggtorrent] Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by SingingFrog7** [Jackett/Jackett#13426]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolverr:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.1496-ls74)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.16 (64bit OS) (64bit process)
Environment version: 6.0.7 (/app/Jackett/)
```

### Description

Just upgraded to v0.20.1496 and got this error. (it was a working configuration before, didn't change anything apart from updating my Docker Container) I tried multiple different hostnames, with or without "https://", without any change

Tried to remove and reconfigure indexer and can't save it with the same error

This happens only with yggtorrent. Other indexers seems OK.

Reverting to v0.20.1489 fix the issue

### Logged Error Messages

```text
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    | 07-30 21:04:15 Error System.UriFormatException: Invalid URI: The hostname could not be parsed.
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at System.Uri..ctor(String uriString)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Utils.CookieUtil.RemoveAllCookies(CookieContainer cookieJar) in /home/vsts/work/1/s/src/Jackett.Common/Utils/CookieUtil.cs:line 56
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 119
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 516
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 581
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 986
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    | --- End of stack trace from previous location ---
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 System.UriFormatException: Invalid URI: The hostname could not be parsed.
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at System.Uri..ctor(String uriString)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Utils.CookieUtil.RemoveAllCookies(CookieContainer cookieJar) in /home/vsts/work/1/s/src/Jackett.Common/Utils/CookieUtil.cs:line 56
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 119
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 516
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 581
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 986
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    | --- End of stack trace from previous location ---
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett_jackett.1.sw9b40qm5z7d@vm-docker-1    |    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by SingingFrog7** [comment]
Reverting to v0.20.1489 fix the issue for me

**Comment by garfield69** [comment]
upgrading to v0.20.1504 should fix this issue.
