### ISSUE TITLE
[mteamtp] (updating) Login Failed, got redirected.

### ISSUE THREAD

**Issue by sokouu** [Jackett/Jackett#13441]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client:HttpWebClient/HttpWebClient2
Using FlareSolverr:192.168.1.8:8191
Using proxy:Disabled
App config/log directory:
Running in Docker:Yes
Jackett variant:
Corewindows/FullFrameworkWindows/CoreMacos/CoreLinuxAmdx64/CoreLinuxArm32/CoreLinuxArm64/Mono
OS version:Synology 218+ (64bit)
Environment version:n.n.nn (folder path)
```

### Description

Can't log into m-team, already used the latest version of Jackett(0.20.1529) and Flaresolverr(2.2.6). 

### Logged Error Messages

```text
Login Failed, got redirected.
```

**Comment by sokouu** [comment]
loginfo:

Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 834
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 987
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by garfield69** [comment]
please turn on enhanced logging and provide the log.txt file 
perhaps the included HTML and Debug will shed more light on your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details

**Comment by sokouu** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/9232405/log.txt)

Please have a check, thank you!

**Comment by garfield69** [comment]
after the login page is filled by jackett, instead of being presented with index.php page jackett is given a verification page
```
Please enter the 6-digit verification code displayed on the validator:
<input type="text" name="otp" value="" size="6" maxlength="6"
You have 30 more attempts, otherwise the IP will be blocked. 
```
which jackett is not expecting and which the indexer cannot handle.

@ilike2burnthing have you seen this before, is there a sequence of steps the use can take to make mteamp accept a login without requiring a verification?

OR perhaps  is the only way to bypass the issue to switch on 2fa and use the mteam2fa indexer?

**Comment by sokouu** [comment]
@ilike2burnthing @garfield69 yes, when I turned off 2FA, everything works fine, thank you!
