### ISSUE TITLE
https://spidertk.top/ page not found

### ISSUE THREAD

**Issue by RedBull01** [Jackett/Jackett#13454]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-08-07 11:15:31	Info	Using HTTP Client: HttpWebClient2
2022-08-07 11:15:31	Info	Using FlareSolverr: **************
2022-08-07 11:15:31	Info	Using proxy: Disabled
2022-08-07 11:15:31	Info	App config/log directory: /config/Jackett
2022-08-07 11:15:31	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-08-07 11:15:31	Info	Running in Docker: Yes (image build: v0.20.1627)
2022-08-07 11:15:31	Info	File /etc/issue: Ubuntu 18.04.6 LTS \n \l
2022-08-07 11:15:31	Info	Jackett variant: CoreLinuxAmdx64
2022-08-07 11:15:31	Info	OS version: Unix 5.4.0.121 (64bit OS) (64bit process)
2022-08-07 11:15:31	Info	Environment version: 6.0.7 (/app/Jackett/)
2022-08-07 11:15:31	Info	Starting Jackett v0.20.1627
```

### Description

Hi.

Shearch on spidertk for: 12 Deadly Days.
Find 1.
Click for download->Page not found

### Logged Error Messages

```text
2022-08-07 11:06:50	Error	
Error downloading. indexer: spidertk path: https://spidertk.top/download.php?id=14124
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
2022-08-07 11:06:50	Error	
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="SpiderTK" />
<title>SpiderTK :: Connexion - Powered by SpiderTK</title>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="search" type="application/opensearchdescription+xml" title="SpiderTK Torrents" href="opensearch.php" />
<link rel="stylesheet" href="styles/mediumfont.css" type="text/css" />
<link rel="stylesheet" href="styles/sprites.css" type="text/css" />
<link rel="stylesheet" href="pic/forum_pic/en/forumsprites.css" type="text/css" />
<link rel="stylesheet" href="styles/DarkPassion/theme.css" type="text/css" />
<link rel="stylesheet" href="styles/DarkPassion/DomTT.css" type="text/css" />
<link rel="stylesheet" href="styles/curtain_imageresizer.css" type="text/css" />
<link rel="alternate" type="application/rss+xml" title="Latest Torrents" href="torrentrss.php" />
<script type="text/javascript" src="js/curtain_imageresizer.js"></script>
<script type="text/javascript" src="js/ajaxbasic.js"></script>
<script type="text/javascript" src="js/common.js"></script>
<script type="text/javascript" src="js/domLib.js"></script>
<script type="text/javascript" src="js/domTT.js"></script>
<script type="text/javascript" src="js/domTT_drag.js"></script>
<script type="text/javascript" src="js/fadomatic.js"></script>
<script type="text/javascript" src="js/jquery-1.12.4.min.js"></script>
<script type="text/javascript">jQuery.noConflict();</script>
</head>
<body>
<table class="head" cellspacing="0" cellpadding="0" align="center">
	<tr>
		<td class="clear">
			<div class="logo"></div>
		</td>
		<td class="clear nowrap" align="right" valign="middle">
		</td>
	</tr>
</table>

<table class="mainouter" width="1200" cellspacing="0" cellpadding="5" align="center">
	<tr><td id="nav_block" class="text" align="center">
			<a href="login.php"><font class="big"><b>Connexion</b></font></a> / <a href="signup.php"><font class="big"><b>Inscription</b></font></a>
<form method="get" action="/login.php?returnto=downloadnotice.php%3Ftorrentid%3D14124%26type%3Dfirsttime">
    <input type="hidden" name="secret" value="">
</form>
<h1>Pas connecté!</h1>
<p><b>Erreur:</b> Vous devez être connecté pour consulter cette page.</p>
<form method="post" action="takelogin.php">
    <input type="hidden" name="secret" value="">
<p>Vous n'avez pas encore de compte? <a href="signup.php"><b>Inscrivez-vous</b></a> maintenant!</p>
<p><b>Remarque</b>: Vous devez activer les cookies pour pouvoir vous connecter.<br /> [<b>20</b>] tentatives de connexion échouées d'affilée  provoqueront le bannissement de votre adresse IP!</p>
<p>Il vous reste <b><font color="green" size="2">[20]</font></b> essais.</p>
<table border="0" cellpadding="5">
<tr><td class="rowhead">Nom d'utilisateur:</td><td class="rowfollow" align="left"><input type="text" name="username" style="width: 180px; border: 1px solid gray" /></td></tr>
<tr><td class="rowhead">Mot de passe:</td><td class="rowfollow" align="left"><input type="password" name="password" style="width: 180px; border: 1px solid gray"/></td></tr>
<tr><td class="rowhead">Authentification à deux facteurs</td><td class="rowfollow" align="left"><input type="text" name="two_step_code"  placeholder="Doit être complété si activé" style="width: 180px; border: 1px solid gray"/></td></tr>
<tr><td class="rowhead">Image de sécurité:</td><td align="left"><img src="image.php?action=regimage&amp;imagehash=1ff5efc815ea2e79c4d780d51cc6e798&amp;secret=" border="0" alt="CAPTCHA" /></td></tr><tr><td class="rowhead">Code de sécurité:</td><td align="left"><input type="text" autocomplete="off" style="width: 180px; border: 1px solid gray" name="imagestring" value="" /><input type="hidden" name="imagehash" value="1ff5efc815ea2e79c4d780d51cc6e798" /></td></tr><tr><td class="toolbox" colspan="2" align="left">Options avancées:</td></tr>
<tr><td class="rowhead">Déconnexion Auto:</td><td class="rowfollow" align="left"><input class="checkbox" type="checkbox" name="logout" value="yes" /> Me déconnecter après 15 minutes</td></tr>
<tr><td class="rowhead">Restriction IP:</td><td class="rowfollow" align="left"><input class="checkbox" type="checkbox" name="securelogin" value="yes" /> Restreindre la session à mon IP</td></tr>
<tr style="display: none;"><td class="rowhead">SSL (HTTPS):</td><td class="rowfollow" align="left"><input class="checkbox" type="checkbox" name="ssl" value="yes" checked="checked" disabled="disabled" /> Naviguer sur le site avec un chiffrement SSL (Navigateur Web)<br /><input class="checkbox" type="checkbox" name="trackerssl" value="yes"  /> Connecter le tracker avec un chiffrement SSL (Client BitTorrent)</td></tr>
<tr><td class="toolbox" colspan="2" align="right"><input type="submit" value="Connexion!" class="btn" /> <input type="reset" value="Recommencer" class="btn" /></td></tr>
</table>
<input type="hidden" name="returnto" value="downloadnotice.php?torrentid=14124&amp;type=firsttime" />
</form>
<p>Vous n'avez pas encore de compte? <a href="signup.php"><b>Inscrivez-vous</b></a> maintenant!</p>
<p>Mot de passe oublié? Réinitialisez votre mot de passe <a href="recover.php"><b>par email</b></a></p>
<p>Compte bloqué? Voyez-en la raison sur le <a href="user-ban-log.php"><b>journal des comptes bloqués</b></a></p>
<p>Vous n'avez pas reçu le mail de confirmation ou le lien de confirmation ne fonctionne pas? <a href="confirm_resend.php"><b>Recevez un nouveau mail de confirmation</b></a></p>
<br> <a href="https://spidertk.top" target="_self">SpiderTK</a> fait avec ♥♥♥<br />[page générée en <b> 0.007 </b> secondes.]</td></tr></table><div id="footer"><div style="margin-top: 10px; margin-bottom: 30px;" align="center"></div>
<div style="display: none;" id="lightbox" class="lightbox"></div><div style="display: none;" id="curtain" class="curtain"></div></div><script type="application/javascript" src="js/nexus.js"></script>
<script type="application/javascript" src="vendor/jquery-goup-1.1.3/jquery.goup.min.js"></script>
<script>
jQuery(document).ready(function(){
    jQuery.goup()
});
</script></body></html>
2022-08-07 11:06:40	Info	
Manual search in SpiderTK for 12 Deadly Days => Found 1 releases
```

**Comment by ilike2burnthing** [comment]
Try reconfiguring the indexer, making sure to enter the captcha code.

Are you able to download that torrent on their site in browser?

**Comment by garfield69** [comment]
It appears that this is the first time you are using SpiderTK to download, so you are being presented with a intermediate page (called the download notice) which explains the rules for downloading, and you need to click on the accept checkbox and click on the continue to download.
This need to be done on the web site, since the spidertk Jackett indexer does not have the ability to handle this.
Once the first download is complete you should not get this download notice again, and the indexer should work too.

Secondly, I note that when I tried downloading from spidetk web site just now using my web browser, I ended up with a error 502 bad gateway, so the spidertk web site is not working 100% and this can also interfere with the Jackett indexer.
