### ISSUE TITLE
[req]: Cardigann wiki article => comments and annotations in the json schema

### ISSUE THREAD

**Issue by bakerboy448** [Jackett/Jackett#13468]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Now that we have a [json schema](https://github.com/Jackett/Jackett/issues/12793). Would it make sense to transfer the comments and documentation currently in the wiki to the schema itself?

### Describe the solution you'd like

See above

### Describe alternatives you've considered

N/a

**Comment by garfield69** [comment]
Sorry, I do not understand what you are proposing.
From a user point of view, the schema script is just a black box you run to get a pass or (at least to my eyes) a cryptic error message which I find difficult to use to pin point the source of the statement that the schema is objecting to.
How does embedding the script with comments from the wiki be useful? What have I miss-understood?

What I really would like to see is more useful error messages, with perhaps at the very minimum, the line number of the yml statement that the schema is objecting to ;-)

**Comment by bakerboy448** [comment]
Something like this? https://github.com/adobe/jsonschema2md

Basically where the json is the source of truth and the wiki is a prettified more user friendly version

**Comment by garfield69** [comment]
>also the script's output shows which line for which file has what issue

huh?
```
Garfield69@PC1 MINGW64 ~/Documents/GitHub/Garfield69/Jackett (master)
$ ajv test -d "src\Jackett.Common\Definitions\bitbazis.yml" -s "src\Jackett.Common\Definitions\schema.json" --valid -c ajv-formats
src\Jackett.Common\Definitions\bitbazis.yml failed test
[
  {
    instancePath: '/search/fields',
    schemaPath: '#/additionalProperties',
    keyword: 'additionalProperties',
    params: { additionalProperty: 'test' },
    message: 'must NOT have additional properties'
  }
]

Garfield69@PC1 MINGW64 ~/Documents/GitHub/Garfield69/Jackett (master)
```
all I see is an obscure error message %-/

I tried the adobe/jsonschema2md but I cant get it to work
```
Garfield69@PC1 MINGW64 ~/Documents/GitHub/Garfield69/Jackett (master)
$ jsonschema2md  -d "src\Jackett.Common\Definitions" -o "docs" -f yaml
file:///C:/Users/Garfield69/AppData/Roaming/npm/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:13
import { list, eq, contains } from 'ferrum';
               ^^
SyntaxError: Named export 'eq' not found. The requested module 'ferrum' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'ferrum';
const { list, eq, contains } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

Garfield69@PC1 MINGW64 ~/Documents/GitHub/Garfield69/Jackett (master)
```
any ideas?

I'm not sure this is worth the effort. No one has ever complained that the existing wiki is not sufficiently accurate in helping generate an indexer, but then again, apart from myself and @ilike2burnthing hardly anyone else ever contributes here anyway.
Perhaps on the Prowlarr repo things are different, so I'm just going to leave this for now, I've got other things I would rather spend my time on.

**Comment by ilike2burnthing** [comment]
So it seems that Prowlarr's implementation of the YAML validation, as performed through GitHub Actions, gives the line and character numbers - e.g. https://github.com/Prowlarr/Indexers/actions/runs/2886911657

We've added it to our Azure Pipelines, as that's where we're doing our YAML and dotNET linting, so that seemed to fit better. While there was a fair bit of trial and error on my part to get it to work, it was largely a copy and paste job - https://github.com/Jackett/Jackett/pull/13397 (updated now with https://github.com/Jackett/Jackett/commit/dbc9dea7a3aa7990e50b0bc16cdc088f1120c6cb and https://github.com/Jackett/Jackett/commit/01c77ee1fa1c8155ec3e74bf9b1052a969f42616).

In its current state it's essentially identical to Prowlarr's, without the need to use multiple folders and schemas. I'm assuming we don't get line and character numbers just because it's not available to Pipelines?

What we do get though is the path of the block the error is in (instancePath), the name of the value which has the error (params), and the name of the fault (basically on every line). So for the below example, one of the `additionalProperties` errors is the `test-caps-modes` value in the `/caps/modes` block:

```text
{
  instancePath: '/caps/modes',
  schemaPath: '#/definitions/Modes/additionalProperties',
  keyword: 'additionalProperties',
  params: { additionalProperty: 'test-caps-modes' },
  message: 'must NOT have additional properties'
},
```

Example file:
https://github.com/Jackett/Jackett/pull/13490/files
Example errors:
https://dev.azure.com/Jackett/Jackett/_build/results?buildId=6555&view=logs&j=9f2a564b-74e8-5c98-938f-029d53ac7443&t=19445350-200f-5747-7911-92f66750f853&l=20

The output from Prowlarr's Action is the same as ours:
https://github.com/Prowlarr/Indexers/runs/7911211271
However, there are also additional Annotations provided by Actions which give the line and character numbers:
https://github.com/Prowlarr/Indexers/actions/runs/2886838664

@bakerboy448 is there a debug argument which would provide this information in the output? Or can you see some error or typo I've overlooked?

Also, do you have a good resource which defines the errors? While they be obvious to someone familiar with them, as @garfield69 said, to the rest of us they're fairly obscure. Is this sufficient? https://json-schema.org/understanding-json-schema/reference/index.html

Using `additionalProperties` as an example - https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties

As for the original req though, would these comments/annotations be seen anywhere other than the schema.json file (e.g. a tooltip in some software)? If not, I'm not sure what the benefit would be of duplicating the information (and the work of maintaining it).

**Comment by ilike2burnthing** [comment]
Quick update.

From - https://github.com/ajv-validator/ajv-cli#commands
`--verbose` didn't work - https://github.com/Jackett/Jackett/pull/13491
`--errors=` didn't work - https://github.com/Jackett/Jackett/pull/13492

I'm now fairly sure it's not doable without some significant work that's beyond me - https://github.com/ajv-validator/ajv-cli/issues/34

@garfield69 is the current output enough (value, block, and error), or would you want to switch to Actions to get the line and character numbers?

**Comment by garfield69** [comment]
>is the current output enough (value, block, and error)?

Meh, lets leave it as is for now. If I get the urge later I might read the validator repo docs and see if there is scope for improving the message content to replace the current double-Dutch with something more helpful.

**Comment by garfield69** [comment]
https://github.com/adobe/jsonschema2md/issues/441 opened for the jsonschema2md syntax error

**Comment by garfield69** [comment]
re: jsonschema2md
made some progress: got the tool to start by upgrading node.js to 16 (was on 14 previously and that was the min spec suggested for the tool but it clearly was outdated).
to run the tool I temporarily renamed schema.json to cardigann.schema.json so it could find source.
but now I get
```
Garfield69@PC1 MINGW64 ~/Documents/GitHub/Jackett (master)
$ jsonschema2md  -d "src\Jackett.Common\Definitions" -o "docs" -f yaml
loading 1 schemas
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at Object.parse (node:path:913:5)
    at Object.get (file:///C:/Users/Garfield69/AppData/Roaming/npm/node_modules/@adobe/jsonschema2md/lib/schemaProxy.js:128:27)
    at Function.values (<anonymous>)
    at reducer (file:///C:/Users/Garfield69/AppData/Roaming/npm/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:38:25)
    at Array.reduce (<anonymous>)
    at reducer (file:///C:/Users/Garfield69/AppData/Roaming/npm/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:44:39)
    at Array.reduce (<anonymous>)
    at reducer (file:///C:/Users/Garfield69/AppData/Roaming/npm/node_modules/@adobe/jsonschema2md/lib/traverseSchema.js:44:39) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Garfield69@PC1 MINGW64 ~/Documents/GitHub/Jackett (master)
```
so the schema is missing a definition for path? @bakerboy448  I think I'm the wrong person to pursue this.

**Comment by ilike2burnthing** [comment]
Apologies for the necro-bump :P

Used latest Node.js (v24.21.0) and npm (12.0.2) on Windows.

Added `$id` to schema.json:

```json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "cardigann",
    "$ref": "#/definitions/SchemaRoot",
    "definitions": {
```

Ran `jsonschema2md`:

```cmd
C:\Users\User\Downloads\Jackett-master> jsonschema2md -d "src\Jackett.Common\Definitions" -o "docs" -f yaml
loading 1 schemas
preparing schemas...
preparing schemas
writing schemas to C:\Users\WDAGUtilityAccount\Downloads\Jackett-master\out
preparing README...
building readme
README.md created
preparing documentation...
generating markdown
```

234 `.md` files are generated in `docs` folder, with the main two being `README.md` (8.29KB) and `schema.md` (99.1KB):

[README.md](https://github.com/user-attachments/files/32394762/README.md)
[schema.md](https://github.com/user-attachments/files/32394763/schema.md)

Looks like some work would need to be done to `schema.json`, as there are a lot of instances of `untitled` and `unknown` in the `.md` files.

It does look like it might actually be useful as a more readable version of the schema, however for me at least it doesn't replace the examples and explanations in the definition format wiki.
