### ISSUE TITLE
[mircrew] (testing) Test search in MIRCrew => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by Orpheusz** [Jackett/Jackett#13472]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-08-15 11:12:35	Info	Using HTTP Client: HttpWebClient2
2022-08-15 11:12:35	Info	Using FlareSolverr: No
2022-08-15 11:12:35	Info	Using proxy: Disabled
2022-08-15 11:12:35	Info	App config/log directory: /config/Jackett
2022-08-15 11:12:35	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-08-15 11:12:35	Info	Running in Docker: Yes (image build: v0.20.1698-ls74)
2022-08-15 11:12:35	Info	File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-08-15 11:12:35	Info	Jackett variant: CoreLinuxAmdx64
2022-08-15 11:12:35	Info	OS version: Unix 5.10.0.16 (64bit OS) (64bit process)
2022-08-15 11:12:35	Info	Environment version: 6.0.8 (/app/Jackett/)
2022-08-15 11:12:31	Info	Starting Jackett v0.20.1698
```

### Description

Add the MirCrew Indexer, put username and password and press TEST

### Logged Error Messages

```text
2022-08-15 11:13:41	Error	
System.Exception: Test search in MIRCrew => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 314
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2022-08-15 11:13:41	Info	
Test search in MIRCrew => Found 0 releases
```

### Screenshots

![image](https://user-images.githubusercontent.com/18346307/184609230-80846bad-b33b-4f60-a8e7-0b097de41d73.png)

**Comment by garfield69** [comment]
I'm seeing this too. Looks like they may have changed their results layout. I'll investigate.

**Comment by garfield69** [comment]
the website search.php is showing
```

Dear friends,
we apologize for the technical problems that have recently prevented access to the Forum.
The problems in question have mostly been solved, but the "General Search" function is not yet available.
All other Forum features are available and we plan to resolve and restore this feature as soon as possible.
Thank you all for your patience and, in the meantime, good navigation and good fun

The Staff
Information
Sorry, search could not be performed. More information about this failure has been logged in the error log.
```
looks like there is an issue at the web site and there is nothing for us to do but wait.

**Comment by ilike2burnthing** [comment]
back up
