### ISSUE TITLE
[mircrew] (testing) Exception (mircrew): Error: Il form inviato non è valido. Prova a inviarlo di nuovo.: Parse error

### ISSUE THREAD

**Issue by pbarone** [Jackett/Jackett#13486]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
08-18 20:03:12 Info Starting Jackett v0.20.1740 
08-18 20:03:13 Info Environment version: 6.0.8 (/app/Jackett/) 
08-18 20:03:13 Info OS version: Unix 5.15.0.46 (64bit OS) (64bit process) 
08-18 20:03:13 Info Jackett variant: CoreLinuxAmdx64 
08-18 20:03:13 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
08-18 20:03:13 Info Running in Docker: Yes (image build: v0.20.1740-ls74) 
08-18 20:03:13 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
08-18 20:03:13 Info App config/log directory: /config/Jackett 
08-18 20:03:13 Info Using proxy: Disabled 
08-18 20:03:13 Info Using FlareSolverr: http://10.0.0.83:8191/ 
08-18 20:03:13 Info Using HTTP Client: HttpWebClient2
```

### Description

I receive the error message  

An error occurred while testing this indexer
Exception (mircrew): Error: Il form inviato non è valido. Prova a inviarlo di nuovo.: Parse error

when testing mircrew. Used to work and I did not change anything

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (mircrew): Error: Il form inviato non è valido. Prova a inviarlo di nuovo.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Error: Il form inviato non è valido. Prova a inviarlo di nuovo.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 538
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 755
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1538
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 703
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1690
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 677
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

2022-08-18 20:04:32 	Error 	

Error on 20220818200432 for MIRCrew.txtJackett.Common.ExceptionWithConfigData: Error: Il form inviato non è valido. Prova a inviarlo di nuovo.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 538
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 755
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1538




	<!DOCTYPE html>
<html dir="ltr" lang="it">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1" />

<title>MIRCrew - Informazione</title>

	<link rel="alternate" type="application/atom+xml" title="Feed - MIRCrew" href="/app.php/feed">	<link rel="alternate" type="application/atom+xml" title="Feed - News" href="/app.php/feed/news">		<link rel="alternate" type="application/atom+xml" title="Feed - Nuovi argomenti" href="/app.php/feed/topics">				

<!--
	phpBB style name: prosilver
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by:
-->

<link href="./assets/css/font-awesome.min.css?assets_version=271" rel="stylesheet">
<link href="./styles/prosilver/theme/stylesheet.css?assets_version=271" rel="stylesheet">
<link href="./styles/prosilver/theme/it/stylesheet.css?assets_version=271" rel="stylesheet">



	<link href="./assets/cookieconsent/cookieconsent.min.css?assets_version=271" rel="stylesheet">

<!--[if lte IE 9]>
	<link href="./styles/prosilver/theme/tweaks.css?assets_version=271" rel="stylesheet">
<![endif]-->

<style>
	html,
	body {
		background-attachment: fixed;
		background-image: url("./images/mircrew/background/background.jpg");
		background-position: center center;
		background-repeat: no-repeat;
		background-size: cover;
	}
</style>

<style>
	.headerbar {
		background-image: url("./images/mircrew/header/header.png");
		background-position: center center;
		background-repeat: no-repeat;
		background-size: cover;
		height: 190px;
		margin-bottom: 4px;
		width: auto;
	}

	@media (max-width: 700px) {
		.headerbar {
			height: 60px;
		}

		.logo {
			display: inline-block;
			height: auto;
			width: auto;
		}

		.logo:hover {
			text-decoration: none;
		}
	}

		.site-description {
		display: none;
	}
	</style>
<link rel="shortcut icon" href="./images/mircrew/favicon/favicon.png">
<link rel="apple-touch-icon" href="./images/mircrew/favicon/favicon.png">

<link href="./ext/alfredoramos/simplespoiler/styles/all/theme/css/common.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/alfredoramos/simplespoiler/styles/prosilver/theme/css/style.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/alfredoramos/simplespoiler/styles/prosilver/theme/css/colors.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/bb3mobi/lastpostavatar/styles/all/theme/lastpostavatar.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/dmzx/membertimecounter/styles/prosilver/theme/membertimecounter.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/dmzx/topstats/styles/prosilver/theme/topstats.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/galandas/togglebbcode/styles/all/theme/togglestyle.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/marcovo/hideBBcode/styles/all/theme/custom.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/mircrew/css/styles/all/theme/custom.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/mircrew/pageloader/styles/all/theme/pageloader.min.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/mircrew/profilebox/styles/prosilver/theme/profilebox.min.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/oxpus/basicstats/styles/prosilver/theme/basicstats.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/rmcgirr83/elonw/styles/all/theme/elonw.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/vse/abbc3/styles/all/theme/abbc3_common.min.css?assets_version=271" rel="stylesheet" media="screen" />
<link href="./ext/vse/lightbox/styles/all/template/lightbox/css/lightbox.min.css?assets_version=271" rel="stylesheet" media="screen" />


	<style>
		@media (min-width: 900px) {
			.signature img.postimage,			.content img.postimage {
				
				max-width: 720px !important;
			}
		}
	</style>

</head>
<body id="phpbb" class="nojs notouch section-search ltr ">


<div id="wrap" class="wrap">
	<a id="top" class="top-anchor" accesskey="t"></a>
	<div id="page-header">
		<div class="headerbar" role="banner">
					<div class="inner">

			<div id="site-description" class="site-description">
		<a id="logo" class="logo" href="./index.php" title="MIR Home">
					<span class="site_logo"></span>
				</a>
				<h1>MIRCrew</h1>
				<p>Sharing Community</p>
				<p class="skiplink"><a href="#start_here">Passa al contenuto</a></p>
			</div>

									
			</div>
					</div>
				<div class="navbar" role="navigation">
	<div class="inner">

	<ul id="nav-main" class="nav-main linklist" role="menubar">

		<li id="quick-links" class="quick-links dropdown-container responsive-menu hidden" data-skip-responsive="true">
			<a href="#" class="dropdown-trigger">
				<i class="icon fa-bars fa-fw" aria-hidden="true"></i><span>Collegamenti Rapidi</span>
			</a>
			<div class="dropdown">
				<div class="pointer"><div class="pointer-inner"></div></div>
				<ul class="dropdown-contents" role="menu">
					
					
										<li class="separator"></li>

									</ul>
			</div>
		</li>

		<li data-last-responsive="true">
	<a href="/app.php/smartfeed/ui" title="Smartfeed" role="menuitem">
		<i class="icon fa-rss fa-fw" aria-hidden="true"></i><span>Smartfeed</span>
	</a>
</li>
		<li data-skip-responsive="true">
			<a href="/app.php/help/faq" rel="help" title="FAQ (Domande Frequenti)" role="menuitem">
				<i class="icon fa-question-circle fa-fw" aria-hidden="true"></i><span>FAQ</span>
			</a>
		</li>
						
			<li class="rightside"  data-skip-responsive="true">
			<a href="./ucp.php?mode=login&amp;redirect=search.php%3Fauthor%3D%26ch%3D300%26fid%255B%255D%3D25%26fid%255B%255D%3D26%26fid%255B%255D%3D29%26fid%255B%255D%3D30%26fid%255B%255D%3D31%26fid%255B%255D%3D33%26fid%255B%255D%3D34%26fid%255B%255D%3D35%26fid%255B%255D%3D36%26fid%255B%255D%3D37%26fid%255B%255D%3D39%26fid%255B%255D%3D40%26fid%255B%255D%3D41%26fid%255B%255D%3D42%26fid%255B%255D%3D43%26fid%255B%255D%3D45%26fid%255B%255D%3D46%26fid%255B%255D%3D47%26fid%255B%255D%3D51%26fid%255B%255D%3D52%26keywords%3D2022%26sc%3D0%26sd%3Dd%26sf%3Dtitleonly%26sk%3Dt%26sr%3Dtopics%26st%3D0%26submit%3DCerca%26t%3D0%26terms%3Dall" title="Login" accesskey="x" role="menuitem">
				<i class="icon fa-power-off fa-fw" aria-hidden="true"></i><span>Login</span>
			</a>
		</li>
					<li class="rightside" data-skip-responsive="true">
				<a href="./ucp.php?mode=register" role="menuitem">
					<i class="icon fa-pencil-square-o  fa-fw" aria-hidden="true"></i><span>Iscriviti</span>
				</a>
			</li>
						</ul>

	<ul id="nav-breadcrumbs" class="nav-breadcrumbs linklist navlinks" role="menubar">
				
		
		<li class="breadcrumbs" itemscope itemtype="https://schema.org/BreadcrumbList">

			
							<span class="crumb" itemtype="https://schema.org/ListItem" itemprop="itemListElement" itemscope><a itemprop="item" href="./index.php" accesskey="h" data-navbar-reference="index"><i class="icon fa-home fa-fw"></i><span itemprop="name">MIR Home</span></a><meta itemprop="position" content="1" /></span>

			
					</li>

		
			</ul>

	</div>
</div>
	</div>

	<!-- Extension alert to new user alex75 www.phpbb-store.it -->
    
	<a id="start_here" class="anchor"></a>
	<div id="page-body" class="page-body" role="main">
		
		
	


<div class="panel" id="message">
	<div class="inner">
	<h2 class="message-title">Informazione</h2>
	<p>Non ti è permesso di utilizzare il sistema di ricerca.</p>
		</div>
</div>

				</div>


<div id="page-footer" class="page-footer" role="contentinfo">
	<div class="navbar" role="navigation">
	<div class="inner">

	<ul id="nav-footer" class="nav-footer linklist" role="menubar">
		<li class="breadcrumbs">
									<span class="crumb"><a href="./index.php" data-navbar-reference="index"><i class="icon fa-home fa-fw" aria-hidden="true"></i><span>MIR Home</span></a></span>					</li>
		
				<li class="rightside">Tutti gli orari sono <span title="Europe/Budapest">UTC+02:00</span></li>
							<li class="rightside">
				<a href="./ucp.php?mode=delete_cookies" data-ajax="true" data-refresh="true" role="menuitem">
					<i class="icon fa-trash fa-fw" aria-hidden="true"></i><span>Cancella cookie</span>
				</a>
			</li>
														</ul>

	</div>
</div>

	<div class="copyright">
				<p class="footer-row">
			<span class="footer-copyright">Creato da <a href="https://www.phpbb.com/">phpBB</a>&reg; Forum Software &copy; phpBB Limited</span>
		</p>
				<p class="footer-row">
			<span class="footer-copyright">Traduzione Italiana <a href="https://www.phpbb-italia.it">phpBB-Italia.it</a></span>
		</p>
						<p class="footer-row" role="menu">
			<a class="footer-link" href="./ucp.php?mode=privacy" title="Privacy" role="menuitem">
				<span class="footer-link-text">Privacy</span>
			</a>
			|
			<a class="footer-link" href="./ucp.php?mode=terms" title="Condizioni" role="menuitem">
				<span class="footer-link-text">Condizioni</span>
			</a>
		</p>
					</div>

	<div id="darkenwrapper" class="darkenwrapper" data-ajax-error-title="Errore AJAX" data-ajax-error-text="Si è verificato un errore durante l’elaborazione della richiesta." data-ajax-error-text-abort="Richiesta utente interrotta" data-ajax-error-text-timeout="La tua richiesta è scaduta; riprova." data-ajax-error-text-parsererror="Si è verificato un errore con la richiesta e il server ha restituito una risposta non valida.">
		<div id="darken" class="darken">&nbsp;</div>
	</div>

	<div id="phpbb_alert" class="phpbb_alert" data-l-err="Errore" data-l-timeout-processing-req="Richiesta scaduta.">
		<a href="#" class="alert_close">
			<i class="icon fa-times-circle fa-fw" aria-hidden="true"></i>
		</a>
		<h3 class="alert_title">&nbsp;</h3><p class="alert_text"></p>
	</div>
	<div id="phpbb_confirm" class="phpbb_alert">
		<a href="#" class="alert_close">
			<i class="icon fa-times-circle fa-fw" aria-hidden="true"></i>
		</a>
		<div class="alert_text"></div>
	</div>
</div>

</div>

<div>
	<a id="bottom" class="anchor" accesskey="z"></a>
	</div>

<script src="./assets/javascript/jquery-3.6.0.min.js?assets_version=271"></script>
<script src="./assets/javascript/core.js?assets_version=271"></script>

	<script src="./assets/cookieconsent/cookieconsent.min.js?assets_version=271"></script>
	<script>
		if (typeof window.cookieconsent === "object") {
			window.addEventListener("load", function(){
				window.cookieconsent.initialise({
					"palette": {
						"popup": {
							"background": "#0F538A"
						},
						"button": {
							"background": "#E5E5E5"
						}
					},
					"theme": "classic",
					"content": {
						"message": "Questo\u0020sito\u0020utilizza\u0020cookie\u0020al\u0020fine\u0020di\u0020fornire\u0020la\u0020migliore\u0020navigazione\u0020possibile",
						"dismiss": "Accetto",
						"link": "Ulteriori\u0020informazioni",
						"href": "./ucp.php?mode=privacy"
					}
				});
			});
		}
	</script>

<script type="text/javascript">
// <![CDATA[
$(document).ready(function(){

$("#member").countdown({
		date: '',
		leadingZero: false,
		yearsAndMonths: true,
		htmlTemplate: "<span class='cd-online'></span> <strong>%y</strong> <span class=\"cd-online\">YEARS</span> <strong>%m</strong> <span class=\"cd-online\">MONTHS</span>	<strong>%d</strong> <span class=\"cd-online\">giorni</span> <strong>%h</strong> <span class=\"cd-online\">Ore</span> <strong>%i</strong> <span class=\"cd-online\">Minuti E</span> <strong>%s</strong> <span class=\"cd-online\">Secondi</span>",
		direction: "up"
	});
	});

// ]]>
</script>
<script type="text/javascript">
// <![CDATA[
$(document).ready(function(){
	$(".toggle_container").hide(); 
	//Switch the "Open" and "Close" state per click then slide up/down (depending on open/close state)
	$("h2.trigger").click(function(){
		$(this).toggleClass("active").next().slideToggle("fast");
		$(this).find(".fa").toggleClass("fa-plus-circle fa-minus-circle");
		return false; //Prevent the browser jump to the link anchor
	});
});	
// ]]>
</script>
<!--
<div id="mircrew-loader-wrapper">
	<div id="mircrew-loader"></div>
</div>
-->

<div id="mircrew-loader-wrapper">
	<div class="inner one"></div>
	<div class="inner two"></div>
	<div class="inner three"></div>
</div>

<script>
		var elonw_title = "Opens\u0020in\u0020new\u0020window";
</script>
											<script>
		var vseLightbox = {};
		vseLightbox.resizeHeight = 0;
		vseLightbox.resizeWidth = 720;
		vseLightbox.lightboxGal = 0;
		vseLightbox.lightboxSig = 1;
		vseLightbox.imageTitles = 0;
		vseLightbox.lightboxAll = 0;
		vseLightbox.downloadFile = 'download/file.php';
	</script>

<script src="./styles/prosilver/template/forum_fn.js?assets_version=271"></script>
<script src="./styles/prosilver/template/ajax.js?assets_version=271"></script>
<script src="./ext/dmzx/membertimecounter/styles/prosilver/template/jquery.jcountdown.js?assets_version=271"></script>
<script src="./ext/mircrew/pageloader/styles/all/template/pageloader.min.js?assets_version=271"></script>
<script src="./ext/rmcgirr83/elonw/styles/all/template/js/elonw.js?assets_version=271"></script>
<script src="./ext/vse/abbc3/styles/all/template/js/abbc3.min.js?assets_version=271"></script>
<script src="./ext/vse/lightbox/styles/all/template/js/resizer.js?assets_version=271"></script>
<script src="./ext/vse/lightbox/styles/all/template/lightbox/js/lightbox.min.js?assets_version=271"></script>
<script src="./ext/alfredoramos/simplespoiler/styles/all/theme/js/details-element-polyfill.min.js?assets_version=271"></script>
<script src="./ext/alfredoramos/simplespoiler/styles/all/theme/js/spoiler.js?assets_version=271"></script>


<script>
	lightbox.option({
		'albumLabel': 'Immagine\u0020\u00251\u0020di\u0020\u00252'
	});
</script>

</body>
</html>

2022-08-18 20:04:32 	Info 	

CardigannIndexer (mircrew): Relogin required
```

**Comment by garfield69** [comment]
have you tried using the Jackett dashboard to edit the mircrew config and clicking save?

**Comment by pbarone** [comment]
I just did and it fixed it!
