### ISSUE TITLE
[ilcorsaronero] (testing) Exception (ilcorsaronero): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### ISSUE THREAD

**Issue by Orpheusz** [Jackett/Jackett#13480]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-08-16 09:04:13	Info	Using HTTP Client: HttpWebClient2
2022-08-16 09:04:13	Info	Using FlareSolverr: No
2022-08-16 09:04:13	Info	Using proxy: Disabled
2022-08-16 09:04:13	Info	App config/log directory: /config/Jackett
2022-08-16 09:04:13	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-08-16 09:04:13	Info	Running in Docker: Yes (image build: v0.20.1698-ls74)
2022-08-16 09:04:13	Info	File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2022-08-16 09:04:13	Info	Jackett variant: CoreLinuxAmdx64
2022-08-16 09:04:13	Info	OS version: Unix 5.10.0.16 (64bit OS) (64bit process)
2022-08-16 09:04:13	Info	Environment version: 6.0.8 (/app/Jackett/)
2022-08-16 09:04:12	Info	Starting Jackett v0.20.1735
```

### Description

I'm trying to connect to "Il Corsaro Nero" but the connection goes in timeout, but if I try to go to the site i can reach easily and fast

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (ilcorsaronero): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 512
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1414
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 677
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://user-images.githubusercontent.com/18346307/184828506-e42fce1a-15d0-44c1-b404-be719f66a285.png)
![image](https://user-images.githubusercontent.com/18346307/184828583-5866c5ea-17a2-4741-8f06-99a1e2777e26.png)

**Comment by garfield69** [comment]
have you tried using any of the alternate sitelinks in the indexer config? 
do they all fail with the timeout?

**Comment by Orpheusz** [comment]
Hi, I've tried all of them but fail in timeout

**Comment by garfield69** [comment]
do any other indexer fail with the timeout or is it just ilcorsaronero?

**Comment by Orpheusz** [comment]
I've only two indexer, the other one works correctly

**Comment by garfield69** [comment]
well we know the site is working, and the indexer works for me on my win10 jackett so this is likely to be a specific issue at your end.
the browser you are using (that can access the web site) is running on the same machine that is running the docker jackett?
are you using a browser vpn or proxy?

**Comment by Orpheusz** [comment]
No, it is not running on the same machine but the 2 machines have the same router and DNS, I don't use any VPN browser or proxy. If I use another browser (EDGE), the browser gives me a warning about the closure of the site for AGCOM ... Maybe the other browser (CHROME) had cached the page and keeps showing it to me.
Surely it's my fault, I try to investigate ...

Thank you

**Comment by ilike2burnthing** [comment]
A few things could cause the difference between the browsers:
- your cache, as you mentioned
- DNS over HTTPS (DoH) being enabled in Chrome but not Edge
- browser extensions

Try opening an incognito Chrome window with no extensions enabled, see if that makes a difference.

You could try setting your DNS to Cloudflare, Google, or something other than your ISP. You can do this at a router, system, or Docker container level.
