### ISSUE TITLE
[pier720] (updating) Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match

### ISSUE THREAD

**Issue by chcme** [Jackett/Jackett#13507]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/name/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 10 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.19.0.17 (64bit OS) (64bit process)
Environment version: 6.0.8 (/home/name/Jackett/)	
Starting Jackett v0.20.1802
```

### Description

After adding the cookie, both tried on a remote machine through the remote browser and tried on the local machine, the same error occurs.  For the remote machine I did follow the instructions to access site via remote to get accurate cookies, but also why I tested on local machine as well.

[pier720] (updating) Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match

The log below is from the remote machine.

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 987
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Does your cookie look like this:
`phpbb3_h6m7i_track=tf%3A%2875%3A%28y5g%3A1%3B%29%3B...`
or like this:
`phpbb3_h6m7i_track=tf:(75:(y5g:1;);

**Comment by chcme** [comment]
Thanks for the quick reply, remote cookie is as follows (put ... after value to publish here):
PHPSESSID=as5o3ua4087v4aqd5n...; redirect=1; testing=1; sid=b0d38955a02e6fd19....; phpbb3_h6m7i_u=1; phpbb3_h6m7i_k=; phpbb3_h6m7i_sid=9ee0a2fc61b4d96a859e...; _ym_uid=16616139609...; _ym_d=166161...; _ym_isad=2; ulogin_token=ufe36a873415442a0374f8...

**Comment by ilike2burnthing** [comment]
`phpbb3_h6m7i_u=1; phpbb3_h6m7i_k=;`
You're not logged in.

**Comment by chcme** [comment]
Shows me logged in and I can access everything.  Here is the cookie for local machine, also logged ino.

_ym_uid=16616061717440...; _ym_d=166160...; _ym_isad=2; phpbb3_h6m7i_k=; _ym_visorc=w; phpbb3_h6m7i_u=48051; phpbb3_h6m7i_sid=8f8ca8d1c1fa0b54ec8...

**Comment by chcme** [comment]
with either machine I still get the error "Login failed: Selector ":has(a[href^="./ucp.php?mode=logout&"])" didn't match" via jackett when adding the cookie.

**Comment by ilike2burnthing** [comment]
In the latter cookie you're signed in, but there's no session key. Are you making sure to tick the `Запомнить меня` (remember me) box when signing in?

**Comment by chcme** [comment]
That was the trick.  Thank you!!!
