### ISSUE TITLE
[rustorka] (updating) Login failed: Selector "a[href="./login.php?logout=1"]" didn't match

### ISSUE THREAD

**Issue by luckycoinblu** [Jackett/Jackett#13515]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://localhost:8191/
Using proxy: Disabled
App config/log directory: /var/www/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.15.0.188 (64bit OS) (64bit process)
Environment version: 6.0.8 (/opt/Jackett/)
Starting Jackett v0.20.1819
```

### Description

Not working

Login to this tracker with your browser
Open the DevTools panel by pressing F12
Select the Network tab
Click on the Doc button (Chrome Browser) or HTML button (FireFox)
Refresh the page by pressing F5
Click on the first row entry
Select the Headers tab on the Right panel
Find 'cookie:' in the Request Headers section
**Select and Copy the whole cookie string (everything after 'cookie: ') and Paste here.**

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="./login.php?logout=1"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 987
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://user-images.githubusercontent.com/31897446/187687002-f4b04d13-77ca-4b27-94e8-6d45964af6c8.png)

**Comment by ilike2burnthing** [comment]
Are you ticking the `Запомнить` (Remember) option when signing in on the website?

**Comment by luckycoinblu** [comment]
Yes

**Comment by ilike2burnthing** [comment]
Are you using a VPN or proxy?

Are your browser and Jackett on the same device, and using the same IP and DNS?

See also the Notes section of this troubleshooting section - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

Please provide a redacted copy of your cookie, e.g.:

> bb_data=a%3A2%3A%7Bs%3A2%3A%22xx%22%3Bs%3A12%3A%22xxxxxxxxxxxx%22%3Bs%3A3%3A%22uid%22%3Bi%3Axxxxxxx%3Bs%3A3%3A%22sid%22%3Bs%3A20%3A%22xxxxxxxxxxxxxxxxxxxx%22%3B%7D; id=1; gophp=gop

**Comment by luckycoinblu** [comment]
These are different devices at the same time and geographically. I understand that it must be the same device.

**Comment by ilike2burnthing** [comment]
You can use the same VPN server or proxy IP for both to get round that.

**Comment by batuhankrmn** [comment]
@ilike2burnthing I have same issue on my end. When I took cookies from rustorka and added to Jackett, it works but only for 1 day maybe? After that I get the same error, then I need to refresh cookie from rustorke. seems like cookie is expiring or something. I read your question from your previous comment and I'm using Adguard Desktop to block ads. I believe Adguard does proxy based adblocking, so It might be the reason. Do you have any idea how to fix that or can we be sure that Adguard causes this error?

**Comment by ilike2burnthing** [comment]
Same issue with the site, it's just a short-lived cookie.

@garfield69 complete off chance, don't suppose you remember why the indexer was created with cookie login rather than credentials? Haven't tested it, but I don't see a captcha or anything obvious that would stop us.

**Comment by garfield69** [comment]
> you remember why the indexer was created with cookie login rather than credentials? 

No, too long ago. I would have only set up cookie as a last resort having found post and form to not work when first writing the indexer.
But time passes and things change, so try it and see ;-)

**Comment by ilike2burnthing** [comment]
[v0.21.1873](https://github.com/Jackett/Jackett/releases/v0.21.1873)

**Comment by garfield69** [comment]
Unable to use the rustorka login indexer, have switched privately to using the cookie login again.
Getting the same error as the header on this ticket.
Just me?

**Comment by urtaevS** [comment]
> Unable to use the rustorka login indexer, have switched privately to using the cookie login again.
> Getting the same error as the header on this ticket.
> Just me?

I got same error.

**Comment by batuhankrmn** [comment]
@garfield69 I get the same error, I had to remove this tracker from my indexer list because I'm tired of it.

**Comment by garfield69** [comment]
OK, I'll update the indexer with the cookie login.

**Comment by garfield69** [comment]
v0.22.985

**Comment by Leviann** [comment]
Started getting this error constantly. Looks like cookie lives for a few hours

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6899#issuecomment-2680171136
