### ISSUE TITLE
[animeworld] Error downloading .torrent file

### ISSUE THREAD

**Issue by HaxXorHardy** [Jackett/Jackett#13514]
### Have you checked our Troubleshooting page for your issue?

- [x] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/jd/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.19.0.21 (64bit OS) (64bit process)
Environment version: 6.0.8 (/opt/Jackett/)
```

### Description

I try to download a .torrent file with Jackett from Animeworld.

### Logged Error Messages

```text
Error downloading. indexer: animeworld-api path: https://animeworld.cx/torrent/download/23145.e58c778e3a0232abf5736f1c29e8c0fb
FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.DoFollowIfRedirect(WebResult incomingResponse, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 623
   at Jackett.Common.Indexers.BaseWebIndexer.FollowIfRedirect(WebResult response, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 571
   at Jackett.Common.Indexers.BaseWebIndexer.Download(Uri link, RequestType method, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 457
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1907
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56
```

**Comment by ilike2burnthing** [comment]
Configure FlareSolverr - https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured

However, this may not currently work due to https://github.com/FlareSolverr/FlareSolverr/issues/481.

**Comment by HaxXorHardy** [comment]
> Configure FlareSolverr - https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured
> 
> However, this may not currently work due to [FlareSolverr/FlareSolverr#481](https://github.com/FlareSolverr/FlareSolverr/issues/481).

so i have installed FlareSolverr with no change.
`Using FlareSolverr: http://localhost:8191/`

Error:
`Error downloading. indexer: animeworld-api path: https://animeworld.cx/torrent/download/23721.e58c778e3a0232abf5736f1c29e8c0fb
FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 209
   at Jackett.Common.Indexers.BaseWebIndexer.DoFollowIfRedirect(WebResult incomingResponse, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 632
   at Jackett.Common.Indexers.BaseWebIndexer.FollowIfRedirect(WebResult response, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 571
   at Jackett.Common.Indexers.BaseWebIndexer.Download(Uri link, RequestType method, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 468
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1907
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97`

**Comment by ilike2burnthing** [comment]
Like I said, it may not currently work due to https://github.com/FlareSolverr/FlareSolverr/issues/481.

**Comment by garfield69** [comment]
I think the flaresolverr error is a red herring.
The flaresolverr log that @HaxXorHardy  provided after this ticked was closed shows that the download path was replaced with a login path
`https://animeworld.cx/login` implying that the download link that the animeworld provided in the API JSON response `download_link` was not accepted by the API as authorised to download and redirected Jackett to a login page which flaresolverrsharp then got involved in.

Unfortunately, since none of the Jackett team have an account on the animeworld site we cannot investigate further.
Registration is currently open only by application, which I personally am not qualified to pass.
 If an invite was available maybe we could help further.

@HaxXorHardy  have you checked the site's forum or news pages for indications that admin have changed their API or have restricted access to the API to certain member ranks?

**Comment by ilike2burnthing** [comment]
Nice spot. I hadn't even realised the issue had been update.

**Comment by HaxXorHardy** [comment]
who wants an account?
send me an email

**Comment by ilike2burnthing** [comment]
jacketttest AT gmail DOT com

Thanks.

**Comment by HaxXorHardy** [comment]
Done. Check mailbox!

**Comment by ilike2burnthing** [comment]
Many thanks. Just waiting on my account to be verified now.

A MaDs invite would also be appreciated.

**Comment by ilike2burnthing** [comment]
I've been verified and the indexer is working well! Thanks again.

**Comment by HaxXorHardy** [comment]
> A MaDs invite would also be appreciated.

i already send you an invite! pls check you spam.

**Comment by ilike2burnthing** [comment]
Definitely isn't there. You didn't miss a `t` in the address?

**Comment by HaxXorHardy** [comment]
![firefox_ZZARQ4aCEf](https://user-images.githubusercontent.com/1397712/188271497-f9f00242-5e51-4379-851f-dab808d1dada.png)

**Comment by ilike2burnthing** [comment]
Well that's annoying :/ I've checked again, in all folders, definitely isn't there.

I've seen trackers which have issues with gmail addresses before, maybe this is another one of them.

**Comment by HaxXorHardy** [comment]
could be
do you have an other mail?

**Comment by ilike2burnthing** [comment]
Not for this, no.

@garfield69 do you have a non-gmail email account you want to try?

**Comment by garfield69** [comment]
`garfieldsixtynine@protonmail.com`

**Comment by garfield69** [comment]
registration for mads completed. thank you.
