### ISSUE TITLE
[selezen] (testing) Test search in seleZen => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by dshkoda32** [Jackett/Jackett#13524]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett Version v0.20.1830
OS version: Unix 5.4.17.2102 (64bit OS) (64bit process)
Jackett variant: CoreLinuxArm64
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Running in Docker: Yes (image build: v0.20.1197-ls70)
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /config/Jackett
Using proxy: Disabled
Using FlareSolverr: Disabled
```

### Description

Selezen stopped taking the test, I go to the site without any problems, everything is available.
Even verything was still fine yesterday

### Logged Error Messages

```text
Categories options. See the Jackett indexer configuration for a list of supported categories.
Adding a Jackett indexer in CouchPotato
Go to Settings > Searchers.
Enable TorrentPotato.
Click on the indexers corresponding  button and paste it into the CouchPotato host field.
For the Passkey use 1. Leave the username field blank.
Adding a Jackett indexer to RSS clients (RSS feed)
Click on the indexers corresponding  button and paste it into the URL field of the RSS client.
You can adjust the q (search string) and cat (categories) arguments accordingly. E.g. ...&cat=2030,2040&q=big+buck+bunny will search for "big buck bunny" in the Movies/SD (2030) and Movies/HD (2040) categories (See the indexer configuration for available categories).
Jackett Configuration
  

Admin password: 
••••••••••
  
Base path override: 
/jackett
Base URL override: 
http://jackett:9117
Server port: 
9117
Blackhole directory: 
c:\torrents\
Proxy type: 
Disabled
Proxy URL: 
Proxy port: 
Proxy username: 
Proxy password: 
External access: 
Allow CORS: 
Disable auto update: 
Update to pre-release: 
Enhanced logging: 
Cache enabled (recommended): 
Cache TTL (seconds): 
300
Cache max results per indexer: 
500
FlareSolverr API URL: 
Blank for default
FlareSolverr Max Timeout (ms): 
55000
OMDB API key: 
OMDB API Url: 
Blank for default
Jackett Version v0.20.1830
×
Server Logs
Date	Level	Message
2022-09-05 05:21:15	Error	
System.Exception: Test search in seleZen => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 315
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by garfield69** [comment]
there has been changes to the result selectors. I will work on a fix.

**Comment by garfield69** [comment]
v0.20.1843
