### ISSUE TITLE
Cinecalidad error downloading

### ISSUE THREAD

**Issue by angel-lizander** [Jackett/Jackett#13528]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows
Disable
```

### Description

When I try to download a torrent, I got http 404 with this error:

### Logged Error Messages

```text
2022-09-06 22:53:53	Error	
Error downloading. indexer: cinecalidad path: https://cinecalidad.dev/pelicula/kaamelott-premier-volet/
System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Cinecalidad.Download(Uri link) in D:\a\1\s\src\Jackett.Common\Indexers\Cinecalidad.cs:line 129
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 703
   at Jackett.Common.Indexers.Cinecalidad.Download(Uri link) in D:\a\1\s\src\Jackett.Common\Indexers\Cinecalidad.cs:line 135
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 56
2022-09-06 22:53:53	Error	
Error on 20220906225353 for Cinecalidad.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Cinecalidad.Download(Uri link) in D:\a\1\s\src\Jackett.Common\Indexers\Cinecalidad.cs:line 129
```

### Screenshots

![test](https://user-images.githubusercontent.com/31111274/188778690-7e3f1ff9-ee69-49db-8626-6ecf4d24f58b.png)

**Comment by ilike2burnthing** [comment]
```text
2022-09-07 07:21:35.8274 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://cinecalidad.dev/pelicula/la-chica-salvaje/) 
2022-09-07 07:21:35.8645 Debug WebClient(HttpWebClient2): Returning OK => 66362 bytes
[HTML removed]
2022-09-07 07:21:35.9089 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://cinecalidad.dev/links/MS8xMDA5NTIvMQ==) 
2022-09-07 07:21:35.9335 Debug WebClient(HttpWebClient2): Returning Moved => https://cinecalidad.dev/links/MS8xMDA5NTIvMQ==/ 0 bytes 
2022-09-07 07:21:35.9348 Error Error on 20220907072135 for Cinecalidad.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Cinecalidad.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 129
2022-09-07 07:21:35.9371 Error Error downloading. indexer: cinecalidad path: https://cinecalidad.dev/pelicula/la-chica-salvaje/
System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Cinecalidad.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 129
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 703
   at Jackett.Common.Indexers.Cinecalidad.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Cinecalidad.cs:line 135
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56 
2022-09-07 07:21:35.9450 Info Executing StatusCodeResult, setting HTTP status code 404 
2022-09-07 07:21:35.9456 Info Executed action Jackett.Server.Controllers.DownloadController.Download (jackett) in 127.7352ms 
```

Using https://cinecalidad.dev/pelicula/la-chica-salvaje/ as an example, the `data-url` is decoded from `aHR0cHM6Ly9jaW5lY2FsaWRhZC5kZXYvbGlua3MvTVM4eE1EQTVOVEl2TVE9PQ==` to `https://cinecalidad.dev/links/MS8xMDA5NTIvMQ==` which in browser returns a 301 redirect to https://cinecalidad.dev/links/MS8xMDA5NTIvMQ==/ which 302s to https://cinecalidad.dev/?link=MS8xMDA5NTIvMQ== which 302s to https://cinecalidad.dev/pelicula/la-chica-salvaje/?link=MS8xMDA5NTIvMQ== which has our magnet link.

However, Jackett just stops after the first redirect. I'm not sure if there's an issue there needing resolved or we should just manually build the URL. Either way, I'm out of my depth. @garfield69 are you able to fix this?

**Comment by garfield69** [comment]
I'll try extracting the last segment and build the final URI, but if I can't get it to work then I will assign it to @ngosang  who has played with the links on this site several times previously.

**Comment by garfield69** [comment]
v0.20.1850
