### ISSUE TITLE
[pttime] (updating) Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by sandboxdream** [Jackett/Jackett#13532]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
09-10 01:04:11 Info Starting Jackett v0.20.1853 
09-10 01:04:11 Info Environment version: 6.0.8 (/app/Jackett/) 
09-10 01:04:11 Info OS version: Unix 5.15.46.0 (64bit OS) (64bit process) 
09-10 01:04:11 Info Jackett variant: CoreLinuxAmdx64 
09-10 01:04:11 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
09-10 01:04:11 Info Running in Docker: Yes (image build: v0.20.1853-ls75) 
09-10 01:04:11 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
09-10 01:04:11 Info App config/log directory: /config/Jackett 
09-10 01:04:11 Info Using proxy: Disabled 
09-10 01:04:11 Info Using FlareSolverr: No 
09-10 01:04:11 Info Using HTTP Client: HttpWebClient2
```

### Description

add pttime and it notice this problem

### Logged Error Messages

```text
09-10 01:06:30 Error Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 987
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 987
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
@ilike2burnthing  is the PTtime indexer working for you, particularly from the config save?

**Comment by ilike2burnthing** [comment]
No issues here for searching or reconfiguring the indexer.

@sandboxdream does your password contain any special characters? In the browser are you able to sign out of pttime, sign back in, and navigate the site?

See the further troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting#login-failed-selector

**Comment by garfield69** [comment]
Also, despite the fact that the web site login page allows for username or mailbox to be used, the Jackett indexer is coded only username.

**Comment by sandboxdream** [comment]
@ilike2burnthing my password have special character.The begining is `.`

**Comment by garfield69** [comment]
please answer the other question:  In the browser are you able to sign out of pttime, sign back in, and navigate the site?

**Comment by sandboxdream** [comment]
@garfield69 Yes, I can log back in after logging out of the browser

**Comment by garfield69** [comment]
and access the torrent browser page without getting interrupted with a read-an-email or a notice or alert?

**Comment by garfield69** [comment]
I think we are going to need to see the full enhanced log for this one., hopefully the included HTML and Debug messages will yield a plausible explanation.
See  https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by sandboxdream** [comment]
Here is full log

`2022-09-10 13:56:19.9776 Info Request starting HTTP/1.1 POST http://192.168.101.16:9117/api/v2.0/indexers/pttime/config application/json 222 
2022-09-10 13:56:19.9815 Debug Request is continuing in applying rules. Current url is http://192.168.101.16:9117/api/v2.0/indexers/pttime/config 
2022-09-10 13:56:19.9815 Debug Request is continuing in applying rules. Current url is http://192.168.101.16:9117/api/v2.0/indexers/pttime/config 
2022-09-10 13:56:19.9815 Debug Request is continuing in applying rules. Current url is http://192.168.101.16:9117/api/v2.0/indexers/pttime/config 
2022-09-10 13:56:19.9826 Debug POST requests are not supported 
2022-09-10 13:56:19.9826 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2022-09-10 13:56:19.9826 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/pttime/config' 
2022-09-10 13:56:19.9836 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/pttime/config' 
2022-09-10 13:56:19.9836 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2022-09-10 13:56:19.9836 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2022-09-10 13:56:19.9846 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2022-09-10 13:56:19.9846 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2022-09-10 13:56:19.9846 Debug Execution plan of resource filters (in the following order): None 
2022-09-10 13:56:19.9855 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2022-09-10 13:56:19.9855 Debug Execution plan of exception filters (in the following order): None 
2022-09-10 13:56:19.9855 Debug Execution plan of result filters (in the following order): None 
2022-09-10 13:56:19.9855 Debug Authorization was successful. 
2022-09-10 13:56:19.9866 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-09-10 13:56:19.9866 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2022-09-10 13:56:19.9866 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2022-09-10 13:56:19.9877 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2022-09-10 13:56:19.9877 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
2022-09-10 13:56:19.9877 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
2022-09-10 13:56:19.9886 Debug Connection id "***", Request id "***:0000000B": started reading request body. 
2022-09-10 13:56:19.9886 Debug Connection id "***", Request id "***:0000000B": done reading request body. 
2022-09-10 13:56:19.9886 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2022-09-10 13:56:19.9895 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2022-09-10 13:56:19.9895 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2022-09-10 13:56:19.9895 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2022-09-10 13:56:19.9895 Debug CACHE IsCacheEnabled => false 
2022-09-10 13:56:19.9911 Debug WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://www.pttime.org/takelogin.php PostData: {loginmethod=username, username=shmx, password=***, dutime=month, ssl=yes} RawBody: ) 
2022-09-10 13:56:20.6894 Debug WebClient(HttpWebClient2): Returning OK => 9 bytes <BINARY> 
2022-09-10 13:56:20.6907 Debug CardigannIndexer (pttime): Cookies after login:  
2022-09-10 13:56:20.6917 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.pttime.org/index.php) 
2022-09-10 13:56:21.8526 Debug WebClient(HttpWebClient2): Returning OK => 9 bytes <BINARY> 
2022-09-10 13:56:21.8539 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 1867.6315ms 
2022-09-10 13:56:21.8545 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2022-09-10 13:56:21.8545 Error Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 987
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 987
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2022-09-10 13:56:21.8571 Debug The response will be compressed with 'gzip'. 
2022-09-10 13:56:21.8580 Debug Connection id "0HMKIU3N31AB7" completed keep alive response. 
2022-09-10 13:56:21.8587 Info Request finished HTTP/1.1 POST http://192.168.101.16:9117/api/v2.0/indexers/pttime/config application/json 222 - 500 - application/json 1881.1041ms 
`

**Comment by sandboxdream** [comment]
And I try to change password without special characters,but it didn't work

**Comment by garfield69** [comment]
In response to the login attempt the web site returned `Returning OK => 9 bytes <BINARY> ` 
unfortunately Jackett did not print out the response in full, other than to state the that result was not HTML but clearly this is not the expected index.php page that would contain the logout.php href that the indexer was expecting.

I hate it when Jackett is recalcitrant in yielding a result, very annoying.
@ilike2burnthing  its docker, and that's not my cup of tea. But docker is almost always a PITA to  sort out. 
Any ideas what might be going on?

**Comment by ilike2burnthing** [comment]
Yea, the 9 byte binary file is annoyingly unhelpful.

@sandboxdream please provide the output for 
`curl -v https://www.pttime.org/login.php` 
when run from within the container.

What kind of device are you running Docker on, e.g. a computer, a NAS, a VPS?

**Comment by sandboxdream** [comment]
@ilike2burnthing Unraid NAS.

Here is the results

```
 curl -v https://www.pttime.org/login.php
*   Trying 198.18.11.104:443...
* TCP_NODELAY set
* Connected to www.pttime.org (198.18.11.104) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: May 11 00:00:00 2022 GMT
*  expire date: May 10 23:59:59 2023 GMT
*  subjectAltName: host "www.pttime.org" matched cert's "*.pttime.org"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5581ac6bb2f0)
> GET /login.php HTTP/2
> Host: www.pttime.org
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Sat, 10 Sep 2022 14:27:32 GMT
< content-type: text/html; charset=UTF-8
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=vU4HfmtOflvwGCHo03o0Px1H3uXR7U33jRO%2F7satBaiB4Az36hfUQypNh1wZm0uWbM84ALWFeGmfMVPOvprSnEtbVsRKrnSB6u%2BLxdQD5aSezcC0XUzG7x2OD2fjfCEnQg%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 7488d847988d8b2f-HKG
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
* Connection #0 to host www.pttime.org left intact
Oops,Err!root@5e743c5eb2b0:/# 
```

**Comment by ilike2burnthing** [comment]
Is there no returned HTML?

If you run the same command on the host, do you get a different response?

**Comment by sandboxdream** [comment]
These is all output.

host output is below

```
root@shmx-nas:~# curl -v https://www.pttime.org/login.php
*   Trying 198.18.11.104:443...
* Connected to www.pttime.org (198.18.11.104) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: none
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: May 11 00:00:00 2022 GMT
*  expire date: May 10 23:59:59 2023 GMT
*  subjectAltName: host "www.pttime.org" matched cert's "*.pttime.org"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /login.php]
* h2h3 [:scheme: https]
* h2h3 [:authority: www.pttime.org]
* h2h3 [user-agent: curl/7.83.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x4974a0)
> GET /login.php HTTP/2
> Host: www.pttime.org
> user-agent: curl/7.83.1
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Sat, 10 Sep 2022 14:54:17 GMT
< content-type: text/html; charset=UTF-8
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=P7umpXZRGeC8d1CNrwkGrFswsxNRfGlm3RSSD82WdpdR%2Fz0Xi8AOPv2FdUEnjXrOQfjCWVMjA%2F9xRfN9KoPxl8AtktLaUd0BEZf%2B4bBbOxl9Kz3Tn7ZIjCpf0kddf5wrrg%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 7488ff76dda5e65e-HKG
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
* Connection #0 to host www.pttime.org left intact
Oops,Err!
```

**Comment by garfield69** [comment]
Oops,err! 
Ha! There is your 9 byte binary response Jackett got.

**Comment by sandboxdream** [comment]
Seems to be no use, is the problem that the useragent?

**Comment by ilike2burnthing** [comment]
No, the UA wouldn't be the cause as it happens on the host as well as with Jackett (which has its own UA).

On the computer where you can access pttime in browser, run that same command. No need to provide the output this time, but do you get the same `Oops,Err!` response or actual HTML?

Are other indexers working in Jackett?

**Comment by sandboxdream** [comment]
it's actual HTML

other indexers link BTSCHOOL is working in Jackett

**Comment by ilike2burnthing** [comment]
Are you running a VPN or proxy on your computer but not on your NAS??

Have you set a specific DNS (e.g. Cloudflare's 1.1.1.1 or Google's 8.8.8.8) on your computer but not on your NAS?

**Comment by sandboxdream** [comment]
My NAS is run OpenWrt and it is run openclash and my computer is run clash.They both only use proxy for GFWlist

so I don't think the proxy is the problem

**Comment by sandboxdream** [comment]
I've test if I close the openclash,then it is loading all the time.

**Comment by ilike2burnthing** [comment]
By 'it is loading all the time' do you mean 'it now always works' or 'it is now endlessly loading but never finishes'?

**Comment by sandboxdream** [comment]
&nbsp;it is now endlessly loading but never finishes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jackett/Jackett"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月12日(星期一) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jackett/Jackett] [pttime] (updating) Login failed: Selector "a[href="logout.php"]" didn't match (Issue #13532)





 
By 'it is loading all the time' do you mean 'it now always works' or 'it is now endlessly loading but never finishes'?

**Comment by sandboxdream** [comment]
i tested if i close openclash i also can't get results by curl

```
curl -v https://www.pttime.org/login.php
*   Trying 104.21.35.144:443...
* Connected to www.pttime.org (104.21.35.144) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: none
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to www.pttime.org:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.pttime.org:443 
```

**Comment by ilike2burnthing** [comment]
So, without openclash the connection is completely blocked, but with openclash you end up this `Oops,Err!` issue. 

I'm not sure if the issue lies with Unraid, OpenWrt, OpenClash, or GFWlist, but I would guess OpenClash. I would suggest opening an issue with them, and link to this one for more information. Also, please let us know if you find a solution, as it may benefit future users.

**Comment by sandboxdream** [comment]
The Rules isn't have pttime.org,I will open a issue on openclash,thank you.
