### ISSUE TITLE
[keepfriends] (testing) Test search in Keep Friends => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by ted423** [Jackett/Jackett#13531]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [x] I have read the Contributing Guidelines

### Environment

```markdown
New install in Ubuntu 22.04 LTS

podman run -d \
  --name=jackett \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Asia/shanghai \
  -e AUTO_UPDATE=true `#optional` \
  -p 9117:9117 \
  -v /home/xx/jackett:/config \
  -v /home/xx/jackett:/downloads \
  --restart unless-stopped \
  lscr.io/linuxserver/jackett:latest
```

### Description

No resault,seem the web get correct but Error parsing

### Logged Error Messages

```text
CardigannIndexer (keepfriends): Error while parsing row '
<tr>
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<input id="box" onclick="ChkSonClick('box[]','box');torrentbycheck();" class="box" type="checkbox" name="box[]" value="8522">
	</td>
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px" data-instant="">
		<a href="?cat=402">
			<img class="c_tvseries" src="/static/pic/cattrans.gif" alt="剧集" title="剧集" style="background-image: url('/static/pic/category/chd/scenetorrents/en/tvseries.png'); background-size: 45px 45px;">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr>
					<td class="embedded">
						<a title="【西部世界/西方极乐园】 第二季 HBO出品 mUHD作品 4k HDR10版本" href="details.php?id=8522&amp;hit=1" data-instant="">
							<b>
								<font color="Red">【西部世界/西方极乐园】 第二季 HBO出品 mUHD作品 4k HDR10版本</font>
							</b>
						</a>
						<br>
						<font color="Red">Westworld S02 2018 BluRay 2160p x265 10bit HDR mUHD-FRDS<b>[<font class="hot" title="Hot">
									<i class="fas fa-fire-alt"></i>
								</font>]</b>
						</font>
						<div style="width: 400px; height:16px;">
							<div style="margin-top: 2px; float: left;">
								<div style="width: 12px; height: 12px; margin: 0px auto 0px 0;">
									<img src="/static/pic/newpic/2s_up.gif">
								</div>
							</div>
							<div style="width: 300px; height:5px; float: left; margin-top: 6px; margin-left: 3px; background-color: #77f;font-size:0px;"></div>
							<div style="width: 0px; height:5px; margin-top: 6px; float: left; background-color: #f77;font-size:0px;"></div>
						</div>
					</td>
					<td width="110" class="embedded" style="text-align: right; " valign="top">
						<div style="height: 15px; margin-bottom: 3px; line-height: 15px;">
							<a href="download.php?id=8522">
								<img class="download" src="/static/pic/download.png" style="float:left margin-bottom: 0px;" alt="download" title="Download&nbsp;Torrent">
							</a>
							<img src="/static/pic/newpic/imdb.gif" style=" margin-top: 0px;">
							8.6
							<img src="/static/pic/newpic/douban.png" style=" margin-top: 0px; max-height: 12px;">
							8.9</div>
						<div style="height: 15px; margin-bottom: 3px; line-height: 15px;">
							<span style="font-size: 8pt;" onmouseover="domTT_activate(this, event, 'content', '<b>Seeder estimate bouns(bouns/day/GB)</b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);">0.03
								<i class="fab fa-btc"></i>
							</span>
							<a id="bookmark49" href="javascript: bookmark(8522,49);" style="margin-left: 2px; margin-right: 2px;">
								<img class="delbookmark" src="/static/pic/trans.gif" alt="Unbookmarked" title="Bookmark">
							</a>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow">
		<b>
			<a href="details.php?id=8522&amp;hit=1&amp;cmtpage=1#startcomments" onmouseover="domTT_activate(this, event, 'content', document.getElementById('lastcom_49'), 'trail', false, 'delay', 500,'lifetime',3000,'fade','both','styleClass','niceTitle','fadeMax', 87,'maxWidth', 400);">5</a>
		</b>
	</td>
	<td class="rowfollow nowrap">
		<span title="2018-12-11 14:26:01">3 year<br>9 months</span>
	</td>
	<td class="rowfollow">138.35<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=8522&amp;hit=1&amp;dllist=1#seeders">162</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=8522">
			<b>2,122</b>
		</a>
	</td>
	<td class="rowfollow" align="center">
		<i>Anonymous</i>
		<br>(<span class="nowrap">
			<a href="userdetails.php?id=28401" class="Moderator_Name">
				<b>匿名用户</b>
			</a>
		</span>
		<i class="fab fa-telegram" style="font-size: 12px; color: #0088CC" title="Telegram"></i>)</td>
	<td class="rowfollow">
		<a href="edit.php?returnto=%2Ftorrents.php%3Fsearch%3D%26incldead%3D0%26spstate%3D0%26search_area%3D0%26search_mode%3D0%26sort%3D5%26type%3Ddesc&amp;id=8522">
			<img class="staff_edit" src="/static/pic/trans.gif" alt="E" title="Edit">
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=5 +08:00: DateTime parsing failed for "5 +08:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 186
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630
```

**Comment by ted423** [comment]
Looks like a time parsing error

**Comment by garfield69** [comment]
From the error message you have provided, it appears that you are seeing an additional column (a checkbox?) at the start of the row, that is throwing off the column count by one.
I'm also seeing another additional column at the end of the row, with a label `Edit` .
Is this the first time you have used this indexer, or has your user rank been elevated recently from a regular user rank to something higher?

The current indexer expected a standard common layout, but I will try to adjust the indexer to cope with the presence of the extra columns when they show up.

**Comment by ted423** [comment]
> From the error message you have provided, it appears that you are seeing an additional column (a checkbox?) at the start of the row, that is throwing off the column count by one. I'm also seeing another additional column at the end of the row, with a label `Edit` . Is this the first time you have used this indexer, or has your user rank been elevated recently from a regular user rank to something higher?
> 
> The current indexer expected a standard common layout, but I will try to adjust the indexer to cope with the presence of the extra columns when they show up.

I'm the admin

**Comment by garfield69** [comment]
Ah, good, that confirms the issue. 
I think I have updated the indexer to cope with your rank, which is due for release in a couple hours from now, so please let me know if it works for you after your Jackett is updated.

**Comment by garfield69** [comment]
v0.20.1853

**Comment by ted423** [comment]
Thanks,Worked

**Comment by garfield69** [comment]
\o/
