### ISSUE TITLE
[req]: HHanClub

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13538]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: HHanClub
- URL: https://hhanclub.top/
- Description: HHanClub is a CHINESE Private Torrent Tracker for HD MOVIES / TV
- Minimum Seeding Time and Minimum Ratio (if Private): tbd
- Additional Comments: 
NexusPHP 1.7.24 2022-08-30
```

**Comment by Kelcoin** [comment]
this indexer's domain hhanclub.top has changed to hhanclub.net, hhan.club still using
but I changed it manually and it still not working,it appears that a site announcement (“重要公告X ...”) is being incorrectly matched as an error block, causing the login to fail. This seems to be a parsing/configuration issue in the Cardigann definition rather than an actual authentication error.

`Jackett.Common.ExceptionWithConfigData: Error: 重要公告X ...                               
  at Jackett.Common.Indexers.Definitions.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 557
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 807
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1080
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26`

**Comment by garfield69** [comment]
v0.24.1094
