### ISSUE TITLE
[yggcookie] (testing) Exception (yggcookie): Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée. (www.yggtorrent.fi:443)

### ISSUE THREAD

**Issue by Johnnybegood90** [Jackett/Jackett#13541]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.0.2:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19044.0 (64bit OS)
Environment version: 6.0.8 (C:\Program Files\Jackett.Binaries.Windows\Jackett\)
```

### Description

Doesn't work since a few days.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (yggcookie): Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
 ---> System.Net.Http.HttpRequestException: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée. (www.yggtorrent.fi:443)
 ---> System.Net.Sockets.SocketException (10061): Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 512
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1414
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 677
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
Use your browser from the same machine that is running Jackett,  to login to https://www5.yggtorrent.fi/ and access the `Rechercher un torrent` menu to confirm you can search.
Then edit your Jackett yggcookie config and change the sitelink to `https://www5.yggtorrent.fi/` and paste your fresh cookie and user agent and see if that works for you as it does for me.

**Comment by biliboobrian** [comment]
hello, i get the same problem from docker latest build v0.20.1903 was working some days ago

**Comment by garfield69** [comment]
@biliboobrian  And have you tried following https://github.com/Jackett/Jackett/issues/13541#issuecomment-1244447515 ?

**Comment by biliboobrian** [comment]
Hello, thanks for your reply, i use a docker version on a centos server, i don't have a available web browsing interface on it, so really difficult to browse directly the site :D, i did not change any settings from a long time and use the "yggtorrent" connector usually and both make the same error at saving configuration ..

**Comment by garfield69** [comment]
@biliboobrian  ah, your are on docker. 
so for the part about using a browser to check to site, do instead:
Try accessing the docker image via your terminal and doing a curl and openssl from within the image 
```
docker exec -it jackett /bin/bash
```
and see what you get from the following:
```
openssl s_client -connect www5.yggtorrent.fi/:443
```
and
```
curl -vvv https://www5.yggtorrent.fi/
```
and lets see what you get.

**Comment by biliboobrian** [comment]
thanks for your help :)

so for the 2 commands i get : 

`openssl s_client -connect www5.yggtorrent.fi/:443`

`140042723919168:error:2008F002:BIO routines:BIO_lookup_ex:system lib:../crypto/bio/b_addr.c:726:Name or service not known
connect:errno=0
`

and

`curl -vvv https://www5.yggtorrent.fi/`

`*   Trying 127.0.0.1:443...
* TCP_NODELAY set
* connect to 127.0.0.1 port 443 failed: Connection refused
*   Trying ::1:443...
* TCP_NODELAY set
* Immediate connect fail for ::1: Cannot assign requested address
*   Trying ::1:443...
* TCP_NODELAY set
* Immediate connect fail for ::1: Cannot assign requested address
* Failed to connect to www5.yggtorrent.fi port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to www5.yggtorrent.fi port 443: Connection refused`

**Comment by garfield69** [comment]
@ilike2burnthing  what do you think?

**Comment by ilike2burnthing** [comment]
Slight typo in the first command, please retry with:

`openssl s_client -connect www5.yggtorrent.fi:443`

**Comment by biliboobrian** [comment]
for the first one 

`openssl s_client -connect www5.yggtorrent.fi:443`

140614650950976:error:0200206F:system library:connect:Connection refused:../crypto/bio/b_sock2.c:110:
140614650950976:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
connect:errno=111

and second one

`curl -v https://www.google.com/`

*   Trying 172.217.19.228:443...
* TCP_NODELAY set
* Connected to www.google.com (172.217.19.228) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=www.google.com
*  start date: Aug 22 08:25:28 2022 GMT
*  expire date: Nov 14 08:25:27 2022 GMT
*  subjectAltName: host "www.google.com" matched cert's "www.google.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55be35a672f0)
> GET / HTTP/2
> Host: www.google.com
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< date: Fri, 16 Sep 2022 06:51:18 GMT
< expires: -1
< cache-control: private, max-age=0
< content-type: text/html; charset=ISO-8859-1
< p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< server: gws
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< set-cookie: AEC=AakniGPEocqiTcYd0Euq_4qLL3Wp1er9Q9BruWHb9Nkqsh_6U8OzALktPA; expires=Wed, 15-Mar-2023 06:51:18 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
< set-cookie: __Secure-ENID=7.SE=Q_LWxspKWwkhW4OVjRqlSoUnw02kGMIef4aPheLEfzGPH2Q9sHlI22DCTXrWyfZ6l2pd9Hsqj48aJHjm9ZqE2s1vNhV3Fye9elBZPzMMbJUCQ1X_eYO8sGY34JwbUlbEJej5nzNO_mpeO8X24tDrVfaRbTHvauOINcW-RclR-ZQ; expires=Mon, 16-Oct-2023 23:09:36 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
< set-cookie: CONSENT=PENDING+701; expires=Sun, 15-Sep-2024 06:51:18 GMT; path=/; domain=.google.com; Secure
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
< accept-ranges: none
< vary: Accept-Encoding
< 

and the content of the google page ..

**Comment by ilike2burnthing** [comment]
The same issue has been seen by Prowlarr users - https://github.com/Prowlarr/Prowlarr/issues/1112

Unfortunately there's nothing we can do to resolve it. The site is actively refusing connections, so you'd need to talk to the admins there about it.

**Comment by PekM** [comment]
it seems to be an issue with docker. You can solve the issue by simply specify port for the docker container --dns 1.1.1.1 --dns 1.0.0.1 (for unraid on "ADVANCED VIEW"  you add it to extra parameters) source: https://forums.unraid.net/topic/102067-solved-where-to-configure-docker-dns/?do=findComment&comment=941874

**Comment by biliboobrian** [comment]
@PekM many thanks !! adding the DNS to my docker-compose and it works !! 👍
