### ISSUE TITLE
[ptsbao] (testing) Test search in PTSBAO => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by xxzj990** [Jackett/Jackett#13548]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.20.1901
Environment version: 6.0.9 (/app/Jackett/)
OS version: Unix 5.10.21.0 (64bit OS) (64bit process)
Jackett variant: CoreLinuxAmdx64
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Running in Docker: Yes (image build: v0.20.1901-ls75)
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /config/Jackett
Using proxy: Socks5
FlareSolverr: http://192.168.50.231:8191
Using HTTP Client: HttpWebClient2
```

### Description

1. steps:
> Click test button

2. happens:
> Test search in PTSBAO => Found 0 releases

3. expected:
> Have the results

### Logged Error Messages

```text
CardigannIndexer (ptsbao): Error while parsing row '
<tr id="tid_35616" class="torrent_table">
	<td id="torrents_td" class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="torrents.php?cat=403">
			<img class="c_tvshows" src="pic/cattrans.gif" alt="综艺" title="综艺" style="background-image: url(pic/category/CHD/scenetorrents/chs/tvshows.png); height:60px; width:48px">
		</a>
		<a href="torrents.php?cat=403&amp;source=15">
			<img src="pic/cattrans.gif" alt="综艺-综合" title="综艺-综合" style="width:48px;height:60px;background-image: url(pic/category/CHD/scenetorrents/chs//sec/15.png);background-position: top left;">
		</a>
	</td>
	<td id="torrents_td" class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%" style="background-color:transparent">
			<tbody>
				<tr>
					<td class="embedded">
						<span class="browse new">新</span>
						<a title="Siesta Key S01 1080p MTV WEB-DL AAC2.0 x264-BTN" href="details.php?id=35616&amp;hit=1">
							<b>Siesta Key S01 1080p MTV WEB-DL AAC2.0 x264-BTN</b>
						</a>
						<img class="pro_2up" src="pic/trans.gif" alt="2x" title="2x">
						<br>西耶斯塔岛 第一季</td>
					<td width="80" class="embedded" style="text-align: right; " valign="middle">
						<a href="download.php?id=35616&amp;passkey=redacted">
							<img class="download" src="pic/trans.gif" style="padding-bottom: 2px;" alt="download" title="下载本种">
						</a>
						<a id="bookmark199" href="javascript: bookmark(35616,199,1);">
							<img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="收藏">
						</a>
						<a id="truckmark199" href="javascript: truckmark(35616,199,1);">
							<img class="truckmark" src="pic/trans.gif" alt="Untruckmarked" title="放进小货车">
						</a>
						<br>
						<span></span>
						<a href="details.php?id=35616&amp;hit=1">
							<img style="vertical-align: text-bottom;" title="IMDb评分：4.4" src="styles/img/imdb.gif">
							<span style="vertical-align: text-bottom;">4.4</span>
						</a>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td id="torrents_td" class="rowfollow">18</td>
	<td id="torrents_td" class="rowfollow">
		<a href="comment.php?action=add&amp;pid=35616&amp;type=torrent" title="添加评论">0</a>
	</td>
	<td id="torrents_td" class="rowfollow nowrap">
		<span title="2022-09-12 10:36:25">2天<br>4时</span>
	</td>
	<td id="torrents_td" class="rowfollow">25.83<br>GB</td>
	<td id="torrents_td" class="rowfollow">
		<b>
			<a href="details.php?id=35616&amp;hit=1&amp;dllist=1#seeders">2</a>
		</b>
	</td>
	<td id="torrents_td" class="rowfollow">0</td>
	<td id="torrents_td" class="rowfollow">
		<a href="viewsnatches.php?id=35616">
			<b>8</b>
		</a>
	</td>
	<td id="torrents_td" class="rowfollow">
		<i>匿名</i>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=25.83GB +08:00: DateTime parsing failed for "25.83GB +08:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 186
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630
```

**Comment by garfield69** [comment]
Looks like there have been some selector changes to their search results HTML.
Fortunately the Error message you provided should be enough for me to update the indexer.

**Comment by garfield69** [comment]
The next release of Jackett is not due out for another 22 hours.
And the Docker build will take place some time after that.
Since my a/c on the site is disabled I cannot test my changes, so once you have updated your Docker Jackett, if you have any further problems please report here. Thanks.

**Comment by garfield69** [comment]
v0.20.1903

**Comment by xxzj990** [comment]
> v0.20.1903

It works！！！
