### ISSUE TITLE
[Partis] TEST fails with Cannot perform runtime binding on a null reference: Parse error

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13555]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

https://www.partis.si/torrent/search?q=&cat= generates error, see in log section below for the message which you can also generate with your browser

https://www.partis.si/torrent/search?q=house&cat=  works so its likely we need to find an alternative to the keywordless search

### Logged Error Messages

```text
Mysql2::Error Commands out of sync; you can't run this command now
Backtrace:
/var/lib/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/var/lib/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/var/lib/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/var/lib/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
./servio.rb:160:in `call'
./servio.rb:208:in `eval'
./servio.rb:208:in `rescue in call'
./servio.rb:121:in `call'
/usr/lib/ruby/vendor_ruby/thin/connection.rb:86:in `block in pre_process'
/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `catch'
/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `pre_process'
/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
/usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run_machine'
/usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run'
/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
/usr/lib/ruby/vendor_ruby/thin/server.rb:148:in `start'
./servio.rb:745:in `
'
```

**Comment by garfield69** [comment]
looks like I can do a keywordless search by using https://www.partis.si/torrent/search?cat=
