### ISSUE TITLE
Can't start jackett service (path '/home/radarr/.config' is denied)

### ISSUE THREAD

**Issue by lapega** [Jackett/Jackett#13568]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [x] I have read the Contributing Guidelines

### Environment

```markdown
Jackett version: v0.20.1918
RPi 4
```

### Description

Just updated to new version, and can't start it.

The log show this:

```
Sep 22 14:27:02 raspberrypi jackett[5283]:  ---> System.UnauthorizedAccessException: Access to the path '/home/radarr/.config' is denied.
Sep 22 14:27:02 raspberrypi jackett[5283]:  ---> System.IO.IOException: Permission denied
```
But I don't have a "/home/radarr" folder, where do I change that?

Thanks!

### Logged Error Messages

```text
Sep 22 14:27:02 raspberrypi systemd[1]: Started Jackett Daemon.
Sep 22 14:27:02 raspberrypi jackett[5283]: Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
Sep 22 14:27:02 raspberrypi jackett[5283]:  ---> System.UnauthorizedAccessException: Access to the path '/home/radarr/.config' is denied.
Sep 22 14:27:02 raspberrypi jackett[5283]:  ---> System.IO.IOException: Permission denied
Sep 22 14:27:02 raspberrypi jackett[5283]:    --- End of inner exception stack trace ---
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.IO.FileSystem.CreateDirectory(String fullPath)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.IO.Directory.CreateDirectory(String path)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.Environment.GetFolderPathCore(SpecialFolder folder, SpecialFolderOption option)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.Environment.GetFolderPath(SpecialFolder folder, SpecialFolderOption option)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at Jackett.Common.Models.Config.RuntimeSettings.get_DataFolder() in /home/vsts/work/1/s/src/Jackett.Common/Models/Config/RuntimeSettings.cs:line 40
Sep 22 14:27:02 raspberrypi jackett[5283]:    --- End of inner exception stack trace ---
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.Reflection.PropertyInfo.GetValue(Object obj)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at Jackett.Server.Program.<>c__DisplayClass10_0.<GetValues>b__1(PropertyInfo p) in /home/vsts/work/1/s/src/Jackett.Server/Program.cs:line 145
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
Sep 22 14:27:02 raspberrypi jackett[5283]:    at Jackett.Server.Program.GetValues(Object obj) in /home/vsts/work/1/s/src/Jackett.Server/Program.cs:line 142
Sep 22 14:27:02 raspberrypi jackett[5283]:    at Jackett.Server.Program.<>c__DisplayClass9_0.<Main>b__2(ConsoleOptions options) in /home/vsts/work/1/s/src/Jackett.Server/Program.cs:line 52
Sep 22 14:27:02 raspberrypi jackett[5283]:    at Jackett.Server.Program.Main(String[] args) in /home/vsts/work/1/s/src/Jackett.Server/Program.cs:line 45
Sep 22 14:27:02 raspberrypi jackett[5280]: Aborted
```

**Comment by garfield69** [comment]
Jackett would not normally have a need to reference the radarr config, so this suggests that you have performed the install incorrectly.
did you perhaps run the installer while in the wrong directory or code/override the wrong config path?

**Comment by lapega** [comment]
Indeed, I used the given install script, and it change the config under systemctl script, I change the user and it works!

Thank you!
