### ISSUE TITLE
[bjshare] (updating) Your cookie did not work: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### ISSUE THREAD

**Issue by jaum20** [Jackett/Jackett#13564]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.1916 CoreLinuxArm32
Ubuntu 20.04.5 LTS 
Unix 4.4.194.322
```

### Description

I can't get the index to login anymore

### Logged Error Messages

```text
2022-09-22 00:55:40.6155 Info Request finished HTTP/1.1 POST http://192.168.15.78:9117/api/v2.0/indexers/bjshare/test - 0 - 500 - application/json 100347.9632ms 
2022-09-22 00:55:40.6199 Debug Connection id "0HMKS9NJ0U8L2" stopped. 
2022-09-22 00:55:46.9814 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 100054.188ms 
2022-09-22 00:55:46.9846 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2022-09-22 00:55:46.9893 Error Jackett.Common.IndexerException: Exception (bjshare): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 512
   at Jackett.Common.Indexers.BJShare.ParseLast24HoursAsync() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs:line 436
   at Jackett.Common.Indexers.BJShare.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs:line 246
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 677
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (bjshare): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 512
   at Jackett.Common.Indexers.BJShare.ParseLast24HoursAsync() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs:line 436
   at Jackett.Common.Indexers.BJShare.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs:line 246
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 677
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Was it working before on the same device and IP, using the same DNS?

Are other indexers working?

Are you using a proxy or VPN?

Are you using a VPS or seedbox?

Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#a-task-was-cancelled

https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work

**Comment by ilike2burnthing** [comment]
If you mean the order is different, but the cookie is otherwise the same, then it makes no difference.

If you mean that there are differences in how the cookie appears, e.g. `%5B20%3A22%5D` vs `[20:22]` then this is a difference in the former being URL encoded and the latter URL decoded. The cookie needs to be URL encoded for it to work in Jackett. You can do this in Chrome (and other Chromium browsers) by highlighting the text of the cookie, right-clicking, and clicking `Copy` (or just using Ctrl+C) - do not use `Copy value`.

If neither of those are what you're describing, please provide a redacted copy of each cookie to show this difference.

**Comment by jaum20** [comment]
Not just ther order:

chrome
session=xxxxxxx...%3D%3D; __cfbbid=XXXXXXXXXX
firefox
 __cfbbid=YYYYYYYYYY; session=yyyyyyyy...%3D%3D; PHPSESSID=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

**Comment by ilike2burnthing** [comment]
Different browser addons/extensions, or cookie settings could potentially explain the difference.

Do neither of the cookies work in Jackett?

If neither work, sign out of the tracker's site in both browsers, sign back in on only one browser, pull a new cookie from it, try that in Jackett.

If that also fails, sign out again, sign in using a private/incognito window and try its cookie.

**Comment by jaum20** [comment]
> Do neither of the cookies work in Jackett?

Tried both, none worked. Also, the logout/login approach didn't worked either. But when I tried the Chrome cookie on Prowlarr it worked fine. So, looks like it is a Jackett bug

**Comment by Guilhermerrrr** [comment]
Hello, I'm experiencing the same problems. 
It was working a few days ago, I don't have a static IP, but I don't think it changed in the last few days. No proxy, VPNs or VPSs used. I also tried to log out and log back in without success. I'm sending my full logs, if that helps. I didn't test with Prowlarr because I don't know where to copy the cookie to. 

[jacket_log_bjshare.txt](https://github.com/Jackett/Jackett/files/9630586/jacket_log_bjshare.txt)

My log erros are slightly different from the original user that opened the ticket, but nonetheless using the cookie this week is not working on Jackett for this tracker.

**Comment by garfield69** [comment]
@Guilhermerrrr  the logs show that you are getting `Name or service not known` for 2 different indexers which suggests the issue is not specific to bjshare, and even the Jackett check-for-updates is failing to access GitHub via api.github.com:443 with the same error.
So something is amiss with your system, some kind of network issue with https by the looks of it.
To my inexperienced eye for linux error messages, this looks like some kind of DNS issue.
can you start a terminal on the same machine you are running Jackett on,  and try the following commands and lets see what you get:
```
openssl s_client -connect www.torrentleech.org:443
```
```
openssl s_client -connect api.github.com:443
```
```
curl -vvv https://www.torrentleech.org/
```
```
curl -vvv https://api.github.com/
```
Thanks

**Comment by Guilhermerrrr** [comment]
> this looks like some kind of DNS issue.

**Isn't it always??** hehe
I feel dumb for wasting your time, but it felt like it couldn't be a coincidence to open the issues tab for Jackett and find this very same tracker here, so I jumped the gun.
Thank you for the heads up, after a very quick look, I found that for some reason my Adguard is not getting DNS queries from my NAS, I'll look into it.
Thank you again and I'm sorry

**Comment by ilike2burnthing** [comment]
@jaum20 is Jackett running on a NAS or Raspberry Pi?

Are you using Docker or is Jackett installed natively?

As a test, install Jackett natively on the computer you're pulling the cookie from, and try adding bjshare.

**Comment by jaum20** [comment]
> @jaum20 is Jackett running on a NAS or Raspberry Pi?

It is running on a sbc, but it is not a rpi

> Are you using Docker or is Jackett installed natively?

natively

> As a test, install Jackett natively on the computer you're pulling the cookie from, and try adding bjshare.

I already get the cookies using the sbc as a proxy with no luck

**Comment by ilike2burnthing** [comment]
Please provide the output from your sbc for:
`curl -v https://bj-share.info/login.php`
and:
`openssl s_client -connect bj-share.info:443`

**Comment by ilike2burnthing** [comment]
Well that's unfortunately unhelpful.

You said, "I already get the cookies using the sbc as a proxy with no luck." What did you mean?

**Comment by jaum20** [comment]
> Well that's unfortunately unhelpful.
> 
> You said, "I already get the cookies using the sbc as a proxy with no luck." What did you mean?

1. ssh -g -D 8080 <sbc ip>
2. set <sbc ip>:8080 as SOCKS v5 proxy in Firefox on my laptop
3. log in bj-share with Firefox 
4. get cookies
5. paste in jackett
6. error

**Comment by ilike2burnthing** [comment]
Does your laptop have a different public IP than your sbc?

Try using a cookie without using your sbc as a proxy.

**Comment by jaum20** [comment]
> Does your laptop have a different public IP than your sbc?

nope

> Try using a cookie without using your sbc as a proxy.

I tried to run jackett on my laptop and I could login fine in BJ. The same cookie won't work with the jackett running on the sbc. The error must be  someway related to do with my sbc or with jackett's arm7 build

**Comment by ilike2burnthing** [comment]
Try this test build - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/6757/artifacts?artifactName=drop&api-version=7.0&%24format=zip

You will need to add your useragent, as well as your cookie (make sure to pull a new one).

**Comment by jaum20** [comment]
I'll try it. Looks like the site is off for now https://downforeveryoneorjustme.com/bj-share.info

**Comment by ilike2burnthing** [comment]
https://bj-share.info/ - Connection timed out - Error code 522

**Comment by jaum20** [comment]
> Try this test build - https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/6757/artifacts?artifactName=drop&api-version=7.0&%24format=zip
> 
> You will need to add your useragent, as well as your cookie (make sure to pull a new one).

This build worked fine

**Comment by garfield69** [comment]
v0.20.2013
