### ISSUE TITLE
[torrentdb] (updating) Login failed: No form found on https://torrentdb.net/login using form selector form[action$="/login"]

### ISSUE THREAD

**Issue by algnp** [Jackett/Jackett#13562]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-09-21 13:41:44	Info	Loading Native indexers ...
2022-09-21 13:41:44	Info	Using HTTP Client: HttpWebClient2
2022-09-21 13:41:44	Info	Using FlareSolverr: No
2022-09-21 13:41:44	Info	Using proxy: Disabled
2022-09-21 13:41:44	Info	App config/log directory: /home/jmquirque/.config/Jackett
2022-09-21 13:41:44	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2022-09-21 13:41:44	Info	Running in Docker: No
2022-09-21 13:41:44	Info	File /etc/issue: 
2022-09-21 13:41:44	Info	Jackett variant: CoreLinuxAmdx64
2022-09-21 13:41:44	Info	OS version: Unix 5.15.26.0 (64bit OS) (64bit process)
2022-09-21 13:41:44	Info	Environment version: 6.0.1 (/usr/share/jackett/)
2022-09-21 13:41:43	Info	Starting Jackett v0.0.0
```

### Description

TorrentDB started timing out in Sonarr and Radarr, tried testing it first, the test seemed to time out and not run, deleted then added again and on trying to add it I receive the message 'no login found'

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://torrentdb.net/login using form selector form[action$="/login"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin()
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson)
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext)
```

**Comment by ilike2burnthing** [comment]
Working ok here.

Please see the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-no-form-found-on-url

If they don't resolve your problem, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket
