### ISSUE TITLE
[privatehd] API Status and Updates

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13573]
Id: privatehd
Name: PrivateHD
Description: PrivateHD is a Private BitTorrent site for High Quality, High Definition (HD) MOVIES and TV Shows
SiteLink: https://privatehd.to/
using AvistazTracker API

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
site up but API returns Error 503: Down for Maintenance

**Comment by Telecart** [comment]
yep seems the same issue on cinemaz and privatehd, sites work, API access is b0rked

**Comment by MyApiNeedsAnApi** [comment]
According to the forums, the API will be down for maintenance until July 1

**Comment by garfield69** [comment]
online

**Comment by xcybermanx** [comment]
any have this issue in download torrent ? with privateHd :  ---> 

NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://jackett.................

**Comment by garfield69** [comment]
Unable to access privatehd or avistaz via their API, Jackett via flaresolverr is seeing a `Sorry, you have been blocked` cloudflare page.
I can access the web sites via the browser fine.
Just me?

**Comment by ilike2burnthing** [comment]
Same.

Notice on sites: `NOTE: API access to Jackett & 'rr systems temporality disabled due to server overload. Sorry for the inconvenience!`

Closing in favour of https://github.com/Jackett/Jackett/issues/13817.

**Comment by garfield69** [comment]
site up but API returns Error 500: Internal Server Error

**Comment by no1warr1or** [comment]
Jackett.Common.IndexerException: Exception (privatehd): Invalid status code 500 (InternalServerError) received from indexer

[v0.24.2475.0] Jackett.Common.IndexerException: Exception (privatehd): Invalid status code 500 (InternalServerError) received from indexer
 ---> System.Exception: Invalid status code 500 (InternalServerError) received from indexer
   at Jackett.Common.Indexers.Definitions.Abstract.AvistazTracker.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/Abstract/AvistazTracker.cs:line 254
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 378
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 403
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 816
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 346
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

**Comment by garfield69** [comment]
online
