### ISSUE TITLE
ShizaProject: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13578]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.1951
Arch Linux
Docker: Yes
```

### Description

Indexer ShizaProject
query: "hurricane"

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (ShizaProject): Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.ShizaProject.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/ShizaProject.cs:line 138
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 680
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 228
```

**Comment by mikeoscar2006** [comment]
This pull should fix the issue.

**Comment by mikeoscar2006** [comment]
[25b16e7](https://github.com/Jackett/Jackett/commit/25b16e7326e0b1bdfc2bf0f0fc3d161c26f78ec4)
