### ISSUE TITLE
[audiobookbay] (testing) Exception (audiobookbay):  Received an unexpected EOF or 0 bytes from the transport stream.: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by richardgetz** [Jackett/Jackett#13603]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
09-26 13:12:49 Info Starting Jackett v0.20.2004 
09-26 13:12:50 Info Environment version: 6.0.9 (/app/Jackett/) 
09-26 13:12:50 Info OS version: Unix 4.4.180.0 (64bit OS) (64bit process) 
09-26 13:12:50 Info Jackett variant: CoreLinuxAmdx64 
09-26 13:12:50 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
09-26 13:12:50 Info Running in Docker: Yes (image build: v0.20.2004-ls77) 
09-26 13:12:50 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
09-26 13:12:50 Info App config/log directory: /config/Jackett 
09-26 13:12:50 Info Using proxy: Disabled 
09-26 13:12:50 Info Using FlareSolverr: http://192.168.86.231:49819 
09-26 13:12:50 Info Using HTTP Client: HttpWebClient2
```

### Description

Add Audiobook Bay and click test. I also attempted manual searches on the site and in Jackett and no results are returned. The books I have searched do exist on the site itself.

### Logged Error Messages

```text
2022-09-26T17:24:54.095303441Z,stdout,   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

2022-09-26T17:24:54.095263677Z,stdout,   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

2022-09-26T17:24:54.095223035Z,stdout,"   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
"
2022-09-26T17:24:54.095182102Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
"
2022-09-26T17:24:54.095134456Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
"
2022-09-26T17:24:54.095089335Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
"
2022-09-26T17:24:54.095043178Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
"
2022-09-26T17:24:54.094991116Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
"
2022-09-26T17:24:54.094948967Z,stdout,   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

2022-09-26T17:24:54.094897240Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
"
2022-09-26T17:24:54.094854816Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
"
2022-09-26T17:24:54.094805868Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
"
2022-09-26T17:24:54.094764378Z,stdout,   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132

2022-09-26T17:24:54.094723226Z,stdout,   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309

2022-09-26T17:24:54.094677112Z,stdout,"   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 692
"
2022-09-26T17:24:54.094613242Z,stdout,"   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
"
2022-09-26T17:24:54.094576664Z,stdout,   --- End of inner exception stack trace ---

2022-09-26T17:24:54.094529781Z,stdout,"   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
"
2022-09-26T17:24:54.094460871Z,stdout,   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1414

2022-09-26T17:24:54.094414124Z,stdout,"   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 522
"
2022-09-26T17:24:54.094371786Z,stdout,   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186

2022-09-26T17:24:54.094336563Z,stdout,   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179

2022-09-26T17:24:54.094293563Z,stdout,"   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
"
2022-09-26T17:24:54.094254125Z,stdout,"   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.094221072Z,stdout,"   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.094185812Z,stdout,"   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.094149726Z,stdout,"   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.094112601Z,stdout,"   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.094080738Z,stdout,   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)

2022-09-26T17:24:54.094050952Z,stdout,   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)

2022-09-26T17:24:54.094013874Z,stdout,"   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.093980743Z,stdout,"   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.093945200Z,stdout,"   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.093909521Z,stdout,   --- End of inner exception stack trace ---

2022-09-26T17:24:54.093867304Z,stdout,"   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.093819576Z,stdout,"   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
"
2022-09-26T17:24:54.093785400Z,stdout,   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)

2022-09-26T17:24:54.093742211Z,stdout,"   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
"
2022-09-26T17:24:54.093708234Z,stdout, ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.

2022-09-26T17:24:54.093662829Z,stdout," ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
"
2022-09-26T17:24:54.093587498Z,stdout,   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (audiobookbay):  Received an unexpected EOF or 0 bytes from the transport stream.

2022-09-26T17:24:54.093540553Z,stdout,   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

2022-09-26T17:24:54.093497814Z,stdout,"   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
"
2022-09-26T17:24:54.093460211Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
"
2022-09-26T17:24:54.093423275Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
"
2022-09-26T17:24:54.093378318Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
"
2022-09-26T17:24:54.093337922Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
"
2022-09-26T17:24:54.093293548Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
"
2022-09-26T17:24:54.093256407Z,stdout,   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

2022-09-26T17:24:54.093201230Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
"
2022-09-26T17:24:54.093158422Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
"
2022-09-26T17:24:54.093071054Z,stdout,"   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
"
2022-09-26T17:24:54.093032382Z,stdout,   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132

2022-09-26T17:24:54.092992090Z,stdout,   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 309

2022-09-26T17:24:54.092951585Z,stdout,"   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 692
"
2022-09-26T17:24:54.092914863Z,stdout,"   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
"
2022-09-26T17:24:54.092885568Z,stdout,   --- End of inner exception stack trace ---

2022-09-26T17:24:54.092844127Z,stdout,"   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
"
2022-09-26T17:24:54.092806564Z,stdout,   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1414

2022-09-26T17:24:54.092738310Z,stdout,"   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 522
"
2022-09-26T17:24:54.092697264Z,stdout,   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186

2022-09-26T17:24:54.092616961Z,stdout,   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179

2022-09-26T17:24:54.092567632Z,stdout,"   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
"
2022-09-26T17:24:54.092532984Z,stdout,"   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.092483133Z,stdout,"   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.092443711Z,stdout,"   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.092405497Z,stdout,"   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.092371605Z,stdout,"   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.092337450Z,stdout,   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)

2022-09-26T17:24:54.092304219Z,stdout,   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)

2022-09-26T17:24:54.092268464Z,stdout,"   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.092232128Z,stdout,"   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.092193188Z,stdout,"   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.092143284Z,stdout,   --- End of inner exception stack trace ---

2022-09-26T17:24:54.092044793Z,stdout,"   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
"
2022-09-26T17:24:54.092003007Z,stdout,"   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
"
2022-09-26T17:24:54.091969163Z,stdout,   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)

2022-09-26T17:24:54.091919648Z,stdout,"   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
"
2022-09-26T17:24:54.091878523Z,stdout, ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.

2022-09-26T17:24:54.091754678Z,stdout," ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
"
2022-09-26T17:24:54.091000630Z,stdout,09-26 13:24:54 Error Jackett.Common.IndexerException: Exception (audiobookbay):  Received an unexpected EOF or 0 bytes from the transport stream.
```

**Comment by ilike2burnthing** [comment]
Please follow the troubleshooting steps:
https://github.com/Jackett/Jackett/wiki/Troubleshooting/#connection-reset-by-peer-the-ssl-connection-could-not-be-established
and:
https://github.com/Jackett/Jackett/wiki/Troubleshooting/#a-connection-attempt-failed

**Comment by richardgetz** [comment]
Seems like it's an issue with my VPN only affecting this indexer. Thank you for pointing me to those troubleshooting steps.
