### ISSUE TITLE
[turkseed] (updating) Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match

### ISSUE THREAD

**Issue by batuhankrmn** [Jackett/Jackett#13616]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 11 Pro
Jackett Version v0.20.2034
```

### Description

I get  "An error occurred while updating this indexer. Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match " error when I try to add this indexer. I already changed its url to trendfilm.net.

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 848
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 992
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 113
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

**Comment by batuhankrmn** [comment]
> the site has changed their domain to `https://trendfilm.net/` logon to the site with the new domain then edit the turkseed jackett indexer config, update the domain and paste the new cookie. closed by [2e28489](https://github.com/Jackett/Jackett/commit/2e284892c79a32598203815c7babcb51dd03b0f0)

Yeah, I already did exactly what you said and I did again now. It's still same. https://prnt.sc/tY1mDbrtYdgK

**Comment by garfield69** [comment]
the indexer is working for me which suggests the problem is at your end.
please provide an **enhanced** log. hopefully the debug and html will provide a clue to your problem.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by batuhankrmn** [comment]
Sure I reproduced it and got the enhanced log file.
[log.txt](https://github.com/Jackett/Jackett/files/9691212/log.txt)

**Comment by garfield69** [comment]
the log shows that the indexer first tried to use https://turkseed.com/ which got redirected.
so in order for the cookie to be good, you need to use your browser to logon to https://trendfilm.net/
AND
the indexer config needs to have the site link changed to `https://trendfilm.net/` and the cookie from the browser pasted.

**Comment by batuhankrmn** [comment]
I've already tried these steps, but I still get the same error:
1- I logon to https://trendfilm.net/ and got cookie.
2- I changed indexer config to https://trendfilm.net/ and pasted the cookie that I got from the https://trendfilm.net/ site.
3- I even cleared site data for https://trendfilm.net/ and relogon to get new cookie.


These are didn't fix the issue. Here, I reproduced the steps and created log file. Let's see If anything different this time. 
[log.txt](https://github.com/Jackett/Jackett/files/9691346/log.txt)

**Comment by garfield69** [comment]
well its a puzzle
the cookie you are using is not being accepted by turkseed so jackett is being presented with an unlogged index.php page, which is  why the test that checks for the logout href is not found.
is the browser you are using on the same win11 machine that is running Jackett?
how are you copying the cookie? I use ctrl-c and ctrl-v to copy/paste
are you using a chrome browser or something else?

**Comment by batuhankrmn** [comment]
> is the browser you are using on the same win11 machine that is running Jackett?

Yes It's on same windows 11 machine.


> how are you copying the cookie? I use ctrl-c and ctrl-v to copy/paste

I select the cookie same way, selecting with mouse and ctrl+c/ctrl+v to copy/paste. I even tried to right click cookie and clicked "copy value". Result was same.

> are you using a chrome browser or something else?

It's Microsoft Edge. Since the other parameters doesn't look like the culprit, It might be something with the browser?

**Comment by garfield69** [comment]
hard to say. edge is using the chromium engine, same as chrome.
I use chrome, but i'll test my edge and see if it works for me. (mind you, I'm on win10 so not an exact comparison).
@ilike2burnthing  any thoughts on this topic, suggestions on how proceed?

**Comment by batuhankrmn** [comment]
Oh I missed the OS part, so I'll also try with Chrome and let you know about it.

**Comment by garfield69** [comment]
I've tested with edge and it works for me.

**Comment by batuhankrmn** [comment]
Oh boy! This is so strange. I've tested with Chrome, and it works for me too, right now. So.. Only thing that came to my mind is Chrome has 0 extension now because I just installed it. Edge has bunch of extensions. I wonder If these extensions can manipulate the cookie in some way, so jackett doesn't accept that cookie that I got from Edge.

**Comment by ilike2burnthing** [comment]
Are Jackett and your browser using the same IP address? Do you have any browser extensions which may change or spoof your IP?

**Comment by batuhankrmn** [comment]
> Are Jackett and your browser using the same IP address? Do you have any browser extensions which may change or spoof your IP?

OMG, I feel dumb at this moment. I was connected to VPN via extension, and I totally forgot it. Disconnecting fixed the issue. Thanks and sorry for the trouble guys.

**Comment by garfield69** [comment]
\o/
