### ISSUE TITLE
[torrentgalaxy] (updating) Login failed: No form found on https://torrentgalaxy.unblockninja.com/galaxyfence.php?f using form selector form[action="/galaxyfence.php"]

### ISSUE THREAD

**Issue by tejsohi** [Jackett/Jackett#13656]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
Environment version: 6.0.10 (C:\ProgramData\Jackett\)
Starting Jackett v0.20.2122
```

### Description

I cannot seem to connect to Torrent Galaxy. I am able to navigate to website fine with no issues, but I cannot connect on Jackett. I have attached the error-log I receive every time

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://torrentgalaxy.unblockninja.com/galaxyfence.php?f using form selector form[action="/galaxyfence.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 591
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 986
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

### Screenshots

![Screenshot 2022-10-17 103208](https://user-images.githubusercontent.com/57041117/196143341-355db3a4-fe5b-49c3-b9de-6b1de0471aa3.jpg)

**Comment by ilike2burnthing** [comment]
Please provide an enhance log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by tejsohi** [comment]
> Please provide an enhance log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

![Screenshot 2022-10-17 115801](https://user-images.githubusercontent.com/57041117/196160810-d2b41768-cc90-4912-ad92-ed611e0b086f.jpg)
[logs.txt](https://github.com/Jackett/Jackett/files/9799757/logs.txt)

I have attached both a screenshot and a text file of the enhanced logs

**Comment by tejsohi** [comment]
> There was no returned HTML below that? I need the rest of the log preceding the error.
This was everything before the error
[logs2.txt](https://github.com/Jackett/Jackett/files/9800632/logs2.txt)

**Comment by ilike2burnthing** [comment]
I need the logs from the moment you open the config panel for the indexer, to the moment the error appears that login has failed. It should contain several sections of HTML.

**Comment by ilike2burnthing** [comment]
Those are for BadassTorrents, BitSearch, and Internet Archive.

Please re-read the initial linked instructions and provide the full logs just for this issue with TorrentGalaxy.

**Comment by tejsohi** [comment]
> Those are for BadassTorrents, BitSearch, and Internet Archive.
> 
> Please re-read the initial linked instructions and provide the full logs just for this issue with TorrentGalaxy.

[TorrentGalacyLogs.txt](https://github.com/Jackett/Jackett/files/9801054/TorrentGalacyLogs.txt)
[log.txt](https://github.com/Jackett/Jackett/files/9801059/log.txt)
Do either of these have what you are looking for?
I restarted Jackett to clear the logs

**Comment by ilike2burnthing** [comment]
The first one is more what I was looking for, however you've now switched from the unblockninja proxy to the unblockit proxy, and seemingly it was down at the time, hence the redirect. It's currently up for me, so you can try it again or switch the proxy back.

**Comment by tejsohi** [comment]
It doesn't matter which one I choose though. It fails for all of the links I click, regardless of which one it is

**Comment by ilike2burnthing** [comment]
Pick one, let it fail, close the config panel, open the config panel again, enter the captcha, provide the enhanced log.

**Comment by tejsohi** [comment]
Enter the captcha? I don't get an option to do that

**Comment by ilike2burnthing** [comment]
You have picked the first site link, clicked Okay, let it fail, closed the config panel, opened the config panel again, and there is no captcha?

Then you have picked the second site link, clicked Okay, let it fail, closed the config panel, opened the config panel again, and there is no captcha?

Then you have picked the third site link, and so on for the rest, and none of them show a captcha?

**Comment by tejsohi** [comment]
Yes that is correct. No captcha appears at anytime.

**Comment by ilike2burnthing** [comment]
Then pick one that you can open in browser, click Okay, let it fail, close the config panel, open the config panel again, click Okay, provide the enhanced log.

**Comment by tejsohi** [comment]
[logs.txt](https://github.com/Jackett/Jackett/files/9854450/logs.txt)

**Comment by ilike2burnthing** [comment]
Once again, not an enhanced log.

**Comment by tejsohi** [comment]
[logs.txt](https://github.com/Jackett/Jackett/files/9854634/logs.txt)
Is that any better?

**Comment by ilike2burnthing** [comment]
Yes! At long last we get the real error, `The SSL connection could not be established`.

If that's the case for all of them when following the instructions above, and you never get a captcha, then you will need to look at using a VPN or proxy if you really want to access that tracker. Otherwise, use a different indexer.

**Comment by tejsohi** [comment]
How can I setup Jackett to use a VPN or proxy?

**Comment by ilike2burnthing** [comment]
Run a VPN on your system or configure a proxy in Jackett's settings.
