### ISSUE TITLE
Parsing issue on TCTG indexer

### ISSUE THREAD

**Issue by Powablocks** [Jackett/Jackett#13668]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.2142-ls78)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxArm32
OS version: Unix 5.15.61.7
Environment version: 6.0.10 (/app/Jackett/)
Starting Jackett v0.20.2142
```

### Description

Hello,
I'm having difficulties to grab movies from TCTG, apparently the parsing of the download page is not working anymore.
Does anyone have a solution ?

### Logged Error Messages

```text
2022-10-23 11:06:58	Error	
Error downloading. indexer: teamctgame path: https://tctg.pm/download.php?id=18155
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97
```

**Comment by ilike2burnthing** [comment]
Try to download from their site first. You will be redirected to a page telling you about how torrents work. Making sure the box is ticked above it, click the download button. After that you can download through Jackett without issue.
