### ISSUE TITLE
HD-Olimpo now requests login besides the token

### ISSUE THREAD

**Issue by cretayo** [Jackett/Jackett#13669]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Docker Jackett Version v0.20.2142
```

### Description

HD-Olimpo now requests a login besides the token set in Jackett. Can search but trying to download any torrent ends in a 404 page.

### Logged Error Messages

```text
2022-10-23 16:20:43	Error	
Error downloading. indexer: hdolimpo-api path: https://hd-olimpo.club/torrent/download/34843.462dbd0eb5fa859c9ce8e213314e2cc0
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 85



2022-10-23 16:20:43	Error	
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Iniciar sesión - HD-Olimpo</title>
            <meta name="description"
            content="Iniciar sesión en HD-Olimpo . ¿Aún no eres miembro? Sólo llevará 30 segundos.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="og:title" content="Iniciar sesión">
        <meta property="og:site_name" content="HD-Olimpo">
        <meta property="og:type" content="website">
        <meta property="og:image" content="https://hd-olimpo.club/img/og2.png">
        <meta property="og:description" content="HDOlimpo, todas las novedades y exclusivas en un solo lugar.">
        <meta property="og:url" content="https://hd-olimpo.club">
        <meta property="og:locale" content="es">
        <meta name="csrf-token" content="dEzzbiHTlUHMYrreurRsflYazHKHMteTS6FF4yEx">
        <link rel="shortcut icon" href="https://hd-olimpo.club/favicon.ico" type="image/x-icon">
    <link rel="icon" href="https://hd-olimpo.club/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/css/main/login.css?id=ff8556b5c1a145ea0c01" crossorigin="anonymous">
</head>

<body>
    <!-- Dont Not Change! For Jackett Support -->
    <div class="Jackett" style="display:none;">HDOlimpo, todas las novedades y exclusivas en un solo lugar.</div>
    <!-- Dont Not Change! For Jackett Support -->

        <div class="wrapper fadeInDown">
        <!--<svg viewBox="0 0 800 100" class="sitebanner">
            <symbol id="s-text">
                <text text-anchor="middle" x="50%" y="50%" dy=".35em">
                    HD-Olimpo
                </text>
            </symbol>
            <use xlink:href="#s-text" class="text"></use>
            <use xlink:href="#s-text" class="text"></use>
            <use xlink:href="#s-text" class="text"></use>
            <use xlink:href="#s-text" class="text"></use>
            <use xlink:href="#s-text" class="text"></use>
        </svg>-->

        <div id="formContent">
            <a href="https://hd-olimpo.club/login">
                <h2 class="active">Iniciar sesión </h2>
            </a>
            <a href="https://hd-olimpo.club/register/null">
                <h2 class="inactive underlineHover">Registrarse </h2>
            </a>

            <div class="fadeIn first">
                <img src="https://hd-olimpo.club/img/icon.svg" id="icon" alt="Icono de usuario" style="margin-top: 20px; margin-bottom: 30px;"/>
            </div>

            <form role="form" method="POST" action="https://hd-olimpo.club/login">
                <input type="hidden" name="_token" value="dEzzbiHTlUHMYrreurRsflYazHKHMteTS6FF4yEx">                <div>
                    <label for="username" class="col-md-4 control-label">Usuario</label>
                    <div class="col-md-6">
                        <input id="username" type="text" class="form-control" name="username"
                            value="" required autofocus>
                    </div>
                </div>

                <div>
                    <label for="password" class="col-md-4 control-label">Contraseña</label>
                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control" name="password" required>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="remember" >
                                Recordar usuario                            </label>
                        </div>
                    </div>
                </div>

                                    <input type="hidden" name="_captcha" value="eyJpdiI6IjgrVkxPOXorTFBMUnkrKzYwT2pDUGc9PSIsInZhbHVlIjoiRzE5anI5MDY0SkdZNXFEbkpjUDZYb1FTK2dkWDcrbWU0ZmVOS3NUNzBrd3FnZTFTbFpSaStLeDlpS053a1JPZE5mVWRydGRNWi9oQ3RiQi8wZTRpWm1naldnVElPN3g0MUdtTnF0dlZiQnM4WUVibXlkNjBGbUpGdW1GRkU2blVlaTJTSVlHWTV0TU1Fd2dnUzVLZ3NzVHBuREhFKzJEM2FERTExMEJTNmQwVW5vdUJIZVlSL25UZ0tqZ2trSkx2YnFqWFI0ZG8yQUUyalRIb3NYeVJDSkwrdmNGNzF1YWE3NWI0ekxJYm1PVzVEQmFYUTVpRHpYTFA4bTlESUc5d0tIWi8rdHFtb0wzL050ZlR5Mjg1eVRGcWlJbjVJbEhrUjJoL2svZUNVTFpVSVJpbDY0WVFqQ1lYVXhxbzd4VThONHVZWUlyQWY4Q0dZVWc3WlI2WjJDVDNLQkgwWEl0TUVkUmE3U1k3Q1c3Q2FOZHF0am53TFJwUnhEM25OUzZXM0JicnZnYXh3d1FaNmRXaGpvaWdtYldva2ZDbDdHc1NWRkg5VGFQTGhZdmR0TG5RQjJXaWY5d1FrVzZIcFBvczhSaGE2cVlFSmlHbXpzT3VjN0ljVDk2citUb2I1UGNXekVBcGw1MVdPdVE9IiwibWFjIjoiMTViNjdmNWMwY2UxYmY1ZDYwYjg1ZmJhYzBmMzg0MDE2ZGIwZDhjM2IzMmY1NzQ1ODA1MDk4ZDU5NTk3Yzk4NSIsInRhZyI6IiJ9" />
<div style="position:fixed;transform:translateX(-10000px);">
    <label for="_username">Name</label>
    <input type="text" name="_username" value="" />
</div>
<input type="hidden" name="1gGyAPU1ZGx8QZvO" value="1666534843" />
                
                <button type="submit" class="fadeIn fourth" id="login-button">Iniciar sesión</button>
            </form>

            <div id="formFooter">
                <a href="https://hd-olimpo.club/password/reset">
                    <h2 class="inactive underlineHover">¿Olvidaste tu contraseña? </h2>
                </a>
                <a href="https://hd-olimpo.club/username/reminder">
                    <h2 class="inactive underlineHover">¿Olvidaste tu usuario? </h2>
                </a>
            </div>
        </div>
    </div>

    <script src="/js/app.js?id=964d1522afb2d1c7b078" crossorigin="anonymous"></script>
                                        
    
</body>

</html>
```

**Comment by ilike2burnthing** [comment]
Are you able to download the same torrent from the tracker's site?

**Comment by cretayo** [comment]
Thanks for pointing me to that, seems that needs a positive greeting ratio to work. Im closing the issue.
