### ISSUE TITLE
Cannot download torrent from indexer:Audiences

### ISSUE THREAD

**Issue by boweic** [Jackett/Jackett#13666]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2	
Using FlareSolverr: https://192.168.50.254:8191	
Using proxy: Disabled
App config/log directory: /config/Jackett	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: unknown)
File /etc/issue: Arch Linux \r (\l)
Jackett variant: CoreLinuxAmdx64	
OS version: Unix 5.19.14.0 (64bit OS) (64bit process)
Environment version: 6.0.8 (/usr/lib/jackett/)
Jackett Data will be stored in: /config/Jackett
Starting Jackett v0.20.2124
```

### Description

cannot download through sonnarr from indexer:audiences. Looks like a cookie issue?

### Logged Error Messages

```text
Error downloading. indexer: audiences path: https://audiences.me/download.php?id=75500
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /tmp/makepkg/jackett/src/Jackett-0.20.2124/src/Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /tmp/makepkg/jackett/src/Jackett-0.20.2124/src/Jackett.Server/Controllers/DownloadController.cs:line 85
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="styles/custom.css" type="text/css">
<meta name="generator" content="NexusPHP" />
<title>Audiences :: 登录 - Powered by NexusPHP</title>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="search" type="application/opensearchdescription+xml" title="Audiences Torrents" href="opensearch.php" />
<link rel="stylesheet" href="styles/mediumfont.css?20220924-1" type="text/css" />
<link rel="stylesheet" href="styles/sprites.css?20220924-1" type="text/css" />
<link rel="stylesheet" href="pic/forum_pic/chs/forumsprites.css?20220924-1" type="text/css" />
<link rel="stylesheet" href="styles/BlasphemyOrange/theme.css?20220924-1" type="text/css" />
<link rel="stylesheet" href="styles/BlasphemyOrange/DomTT.css?20220924-1" type="text/css" />
<link rel="stylesheet" href="styles/curtain_imageresizer.css?20220924-1" type="text/css" />
<link rel="stylesheet" href="styles/ddlevelsmenu-base.css?20220924-1" type="text/css" />
<link rel="stylesheet" href="styles/dragon.css?20220924-1" type="text/css" />
<link rel="stylesheet" href="styles/FA/css/all.min.css?20220924-1" type="text/css" />
<link rel="stylesheet" href="template/css/torrents.css?20220924-1" type="text/css" />
<style type="text/css">
        img {
            max-width: 1000px;
        }

        span.tags {
            color: #fff;
            text-align: center;
            margin: 1px;
            padding: 1px 3px;
            height: 16px;
        }

        /*"gf","gy","yy","zz","jz",'xz','diy','dh','sf','yq','m0','yc','gz','db','hdr10','hdrm'*/
        span.tgf {
            background: #06c;
        }

        span.tyc {
            background: #085;
        }

        span.tgz {
            background: #530;
        }

        span.tdb {
            background: #358;
        }

        span.thdr10 {
            background: #9a3;
        }

        span.thdrm {
            background: #9b5;
        }

        span.tgy {
            background: #f96;
        }

        span.tyy {
            background: #f66;
        }

        span.tzz {
            background: #9c0;
        }

        span.tjz {
            background: #903;
        }

        span.txz {
            background: #c03;
        }

        span.tdiy {
            background: #993;
        }

        span.tdh {
            background: #F596AA;
        }

        span.tsf {
            background: #339;
        }

        span.tyq {
            background: #f90;
        }

        span.tm0 {
            background: #096;
        }

        span.tok {
            background: #ff3f33;
        }

        span.tmv {
            background: turquoise;
        }

        span.tlive {
            background: #ff46ed;
        }

        span.tconcert {
            background: #3b64ff;
        }

        span.tyzj {
            background: #87007e;
        }

        span.log {
            background: #ff9900;
            text-shadow: .2rem 0rem .5rem red, -.2rem 0rem .5rem red, 0rem .2rem .5rem red, 0rem -.2rem .5rem red;
        }
    </style>
<link rel="alternate" type="application/rss+xml" title="Latest Torrents" href="torrentrss.php" />
<script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="js/polyfill.js?20220924-1"></script>
<script type="text/javascript" src="curtain_imageresizer.js?20220924-1"></script>
<script type="text/javascript" src="ajaxbasic.js?20220924-1"></script>
<script type="text/javascript" src="common.js?20220924-1"></script>
<script type="text/javascript" src="domLib.js?20220924-1"></script>
<script type="text/javascript" src="domTT.js?20220924-1"></script>
<script type="text/javascript" src="domTT_drag.js?20220924-1"></script>
<script type="text/javascript" src="fadomatic.js?20220924-1"></script>
<script type="text/javascript" src="js/ddlevelsmenu.js?20220924-1"></script>
<script type="text/javascript" src="js/layer/layer.js?20220924-1"></script>
<script type="text/javascript">
        ddlevelsmenu.setup("nav", "topbar");

        function Paypal($value) {
            window.open("https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=support@audiences.me&currency_code=USD&amount=" + $value + "&return=https://audiences.me&item_name=Donations%20to%20audiences.me&undefined_quantity=1");
        }
    </script>
<style type="text/css">body {
            overflow-y: scroll;
        }</style>
<script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(window).scroll(function () {
                if ($(window).scrollTop() > 200) {
                    $("#roll_top").fadeIn(1000);
                } else {
                    $("#roll_top").fadeOut(1000);
                }
            });
            $("#roll_top").click(function () {
                $('body,html').animate({scrollTop: 0}, 500);
                preventDefault();
            });
        });
    </script>
</head>
<body>
<div title="回到顶部" id="roll_top" style="display:none; zoom:1; opacity: 0.8; height:62px; width:62px; right:15px; position: fixed; top: 90%; background:url('pic/top.gif') 0 0 no-repeat; cursor:pointer;"></div>
<table class="head" cellspacing="0" cellpadding="0" align="center">
<tr>
<td class="clear nowrap" align="center" valign="middle">
<div class="logo_img">
<a href="torrents.php?tag1=1&incldead=0&spstate=0&inclbookmarked=0&search=%E5%8F%98%E5%BD%A2%E9%87%91%E5%88%9A&search_area=2&search_mode=0">
<img style="image-rendering:-moz-crisp-edges; image-rendering:-o-crisp-edges; image-rendering:-webkit-optimize-contrast; image-rendering: crisp-edges; -ms-interpolation-mode:nearest-neighbor;max-width: 100%; width: 1700px;" src="https://i.duan.red/item/633638b816f2c2beb107c7a4.png" alt="Audiences" title="" />
</a>
</div>
</td>






</tr>
</table>
<table class="mainouter" width="982" cellspacing="0" cellpadding="5" align="center">
<tr>
<td id="nav_block" class="text" align="center">
<a href="login.php"><b class="big">登录</b></a> /
<a href="signup.php"><b class="big">注册</b></a>
/ <a href="donate.php"><b class="big" style="color: red;">捐赠VIP</b></a>
<form method="get" action="/login.php">
<div align="right">Select Site Language: <select name="sitelanguage" onchange='submit()'>
<option value="6">English</option>
<option value="25" selected="selected">简体中文</option>
<option value="28">繁體中文</option>
</select></div></form>
<h1>未登录!</h1>
<p><b>错误:</b> 该页面必须在登录后才能访问</p>
<form method="post" action="takelogin.php">
<p><b>注意</b>: 你需要启用cookies才能登录或切换语言<br /> [<b>20</b>] 次连续登录失败将导致你的IP地址被禁用!</p>
<p>你还有 <b><font color="green" size="2">[20]</font></b> 次尝试机会</p>
<table border="0" cellpadding="5">
<tr><td class="rowhead">用户名：</td><td class="rowfollow" align="left"><input type="text" name="username" style="width: 180px; border: 1px solid gray" /></td></tr>
<tr><td class="rowhead">密码：</td><td class="rowfollow" align="left"><input type="password" name="password" style="width: 180px; border: 1px solid gray" /></td></tr>
<tr><td class="rowhead">两步验证码</td><td class="rowfollow" align="left"><input type="text" name="scode" placeholder="未设置时不需要输入" style="width: 180px; border: 1px solid gray" /></td></tr>
<tr><td class="rowhead">验证图片：</td><td align="left"><img src="image.php?action=regimage&amp;imagehash=f99a38f39efd28a8c9d3be32750f9308" border="0" alt="CAPTCHA" /></td></tr><tr><td class="rowhead">验证码：</td><td align="left"><input type="text" autocomplete="off" style="width: 180px; border: 1px solid gray" name="imagestring" value="" /><input type="hidden" name="imagehash" value="f99a38f39efd28a8c9d3be32750f9308" /></td></tr><tr><td class="toolbox" colspan="2" align="left">高级选项：</td></tr>
<tr><td class="rowhead">自动登出：</td><td class="rowfollow" align="left"><input class="checkbox" type="checkbox" name="logout" value="yes" /> 15分钟后自动登出</td></tr>
<tr><td class="rowhead">限制IP：</td><td class="rowfollow" align="left"><input class="checkbox" type="checkbox" name="securelogin" value="yes" /> 限制只能使用本IP登录</td></tr>
<tr><td class="rowhead">SSL (HTTPS)：</td><td class="rowfollow" align="left"><input class="checkbox" type="checkbox" name="ssl" value="yes" checked="checked" disabled="disabled" /> 使用SSL数据加密协议浏览网站(浏览器)<br /><input class="checkbox" type="checkbox" name="trackerssl" value="yes" checked="checked" disabled="disabled" /> 使用SSL数据加密协议连接Tracker(BT客户端)</td></tr>
<tr><td class="toolbox" colspan="2" align="right"><input type="submit" value="登录" class="btn" /> <input type="reset" value="重置" class="btn" /></td></tr>
</table>
<input type="hidden" name="returnto" value="downloadnotice.php?torrentid=75500&amp;type=firsttime" />
</form>


<p>还没有账号? 马上<a href="signup.php"><b>注册</b></a>！</p>
<p><a href="accountdisabled.php">账号被封禁？点击查原因（If your account is disabled, click here for reason）</a></p>
<p>忘记了密码? 通过<a href="recover.php"><b>邮件</b></a>来找回密码</p>
<p>没有收到验证邮件或验证链接无法打开? <a href="confirm_resend.php"><b>重新发送验证邮件</b></a></p>
<p>联系我们 邮箱：<a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="81f2f4f1f1eef3f5c1e0f4e5e8e4efe2e4f2afece4">[email&#160;protected]</a></p>
</td></tr></table><div id="footer"><div style="margin-top: 10px; margin-bottom: 30px;" align="center"> (c) <a href="https://audiences.me" target="_self">Audiences</a> 2021-2022 Powered by <a href="aboutnexus.php">NexusPHP</a><br /><br />[page created in <b> 0 </b> MS / With <b>2</b> db queries, <b>4</b> reads and <b>1</b> writes of Redis and <b>454.19 KB</b> ram / Running PHP v8.0.18]</div>
<div style="display: none;" id="lightbox" class="lightbox"></div><div style="display: none;" id="curtain" class="curtain"></div></div><script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v41822dd307194b3da394f30c241f676d1666031766862" integrity="sha512-p2y/qevlt9/jsokMhKfWLFecGlsaCdYbXFjxQvewNGBVDvrmsBMZ9VN4J2PdUvCrW0PGR9t9+m6eeQhcmRQ6lQ==" data-cf-beacon='{"rayId":"75e36133ba86ddc4","version":"2022.10.3","r":1,"token":"ff17aa5f65434be4a42d24a41321938a","si":100}' crossorigin="anonymous"></script>
</body></html>
```

**Comment by garfield69** [comment]
the log you provided shows that this is the first time you have tried to download anything from the audiences website.
First time downloaders are presented with a download notice, which you have to accept in order to continue with the download.
Until you complete that action on the website the Jackett download will not work.
So access the audiences website, start a download, read the notice and tick the checkbox, and start the download.
You should be good to go after that with Jackett.
