### ISSUE TITLE
[peeratiko] Login failed: Selector "a[href^="/logout.php?auth="]" didn't match

### ISSUE THREAD

**Issue by AsteRbloX** [Jackett/Jackett#13686]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.2175-ls79)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.19.0.0 (64bit OS) (64bit process)
Environment version: 6.0.10 (/app/Jackett/)
Starting Jackett v0.20.2175
```

### Description

Add Indexer > Peeratiko > Type Username and Password > Error

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href^="/logout.php?auth="]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 987
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![Jackett Peeratiko](https://user-images.githubusercontent.com/39133415/198874673-3d9da0fa-4e3a-4c07-8ad4-b83115164bce.png)

**Comment by garfield69** [comment]
when I try to configure peeratiko on my win10 Jackett I get 
`The SSL connection could not be established, see inner exception.: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.`
@ilike2burnthing  is this working for you?

**Comment by AsteRbloX** [comment]
Now that I tried it on my win10 Jackett (since the one I originally posted was on a seedbox), I also got the same error.

**Comment by AsteRbloX** [comment]
> when I try to configure peeratiko on my win10 Jackett I get `The SSL connection could not be established, see inner exception.: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.` @ilike2burnthing is this working for you?

Now that I tried it on my win10 Jackett (since the one I originally posted was on a seedbox), I also got the same error.

**Comment by ilike2burnthing** [comment]
Working ok on my Docker setup.

@AsteRbloX for your Docker Jackett, see https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-selector

Failing that, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by AsteRbloX** [comment]
> Working ok on my Docker setup.
> 
> @AsteRbloX for your Docker Jackett, see https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-selector
> 
> Failing that, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

@ilike2burnthing Just checked with a docker on my local machine, indeed seems to work fine, will investigate with the provider of my seedbox on what is happening since, to my understanding, this is not a problem regarding Jackett.
