### ISSUE TITLE
[yggtorrent] (updating) Cannot assign requested address (www5.yggtorrent.fi:443): Cannot assign requested address

### ISSUE THREAD

**Issue by xyko0** [Jackett/Jackett#13718]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP client
Using Flaresolverr
Running in Docker: Yes
```

### Description

Hi guys, my Indexer for yggtorrent seems to be KO today. 
I changed nothing in the conf...
I'm running jackett on docker and my image is up to date.
I did the usual checks (login to the website,... my account is ok) and watched the differents issues and I can't find any information.
Can someone help me please ?

### Logged Error Messages

```text
seedbox-swarm_jackett.1.vct4l8z0rjd2@faker    | 11-15 11:51:59 Error Jackett.Common.IndexerException: Exception (yggtorrent): Cannot assign requested address
seedbox-swarm_jackett.1.vct4l8z0rjd2@faker    |  ---> System.Net.Http.HttpRequestException: Cannot assign requested address (www5.yggtorrent.fi:443)
seedbox-swarm_jackett.1.vct4l8z0rjd2@faker    |  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
seedbox-swarm_jackett.1.vct4l8z0rjd2@faker    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
seedbox-swarm_jackett.1.vct4l8z0rjd2@faker    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
seedbox-swarm_jackett.1.vct4l8z0rjd2@faker    |    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
seedbox-swarm_jackett.1.vct4l8z0rjd2@faker    |    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
seedbox-swarm_jackett.1.vct4l8z0rjd2@faker    |    --- End of inner exception stack trace ---
```

**Comment by fredrikeriksson** [comment]
I just now found this behavior in my Docker for Windows environment without doing any changes where I host Jackett for now.
I couldn't pull any images from docker hub either with similar errors, that the host couldn't be found.

I resolved it by just updating Docker for Windows to the latest.
If it was the restart of the environment or the update itself that did the trick I don't know.

**Comment by xyko0** [comment]
Ok my bad, I changed my DNS recently and it was KO resolving anything ....
Sorry I close the issue
