### ISSUE TITLE
Can’t add ImmortalSeeds

### ISSUE THREAD

**Issue by andreagattironi** [Jackett/Jackett#13714]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /storage/.kodi/userdata/addon_data/service.jackett/Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: ##############################################
Jackett variant: CoreLinuxArm32
OS version: Unix 4.19.127.0
Environment version: 6.0.11 (/storage/.kodi/addons/service.jackett/libs/)
```

### Description

Can’t add private tracker ImmortalSeeds with Jackett Version v0.20.2236
Other indexers work fine

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: 
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  dir="ltr" lang="en" id="tsse_html">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="generator" content="immortalseed.me :: An error has occured!" />
<meta name="revisit-after" content="1 day" />
<meta name="robots" content="index, follow" />
<meta name="description" content="ImmortalSeed.me, noindex" />
<meta name="keywords" content="templateshares, torrent, php, mysql, html, css, ajax, javascript, xam, template, share, shares, tsse, ts special edition, generation tracker source, tracker source, template shares torrent, php, source, torrent source, free, special edition, xam, xam source, ts v5, noindex" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<title>immortalseed.me :: An error has occured!</title>
<link rel="stylesheet" href="/include/templates/default/style.css" type="text/css" media="screen" />
<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="https://immortalseed.me/rss.php" />
<link rel="alternate" type="text/xml" title="RSS .92" href="https://immortalseed.me/rss.php" />
<link rel="shortcut icon" href="https://immortalseed.me/favicon.ico" type="image/x-icon" />

<script type="text/javascript">
	//<![CDATA[
	var baseurl="https://immortalseed.me";
	var dimagedir="https://immortalseed.me/images/";
	var themedir="https://immortalseed.me/include/templates/default/";
	var charset="UTF-8";
	var userid="0";
	var securitytoken = "";
	var lang_resized = "This image has been resized. Click the image to view the full image. The original image is sized: ";

	if (window.top !== window.self)
	{
		document.write = "";
		window.top.location = window.self.location;

		setTimeout(function()
		{
			document.body.innerHTML='';
		},1);

		window.self.onload=function(evt)
		{
			document.body.innerHTML='';
		};
	}
	//]]>
</script>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script><script type="text/javascript" src="https://immortalseed.me/scripts/bookmarkscroll.js"></script><script src="https://immortalseed.me/scripts/jquery.countdown.min.js" type="text/javascript" charset="utf-8"></script><script src="https://immortalseed.me/scripts/featherlight/featherlight.min.js" type="text/javascript" charset="utf-8"></script><link href="https://immortalseed.me/scripts/featherlight/featherlight.min.css" type="text/css" rel="stylesheet" /><script type="text/javascript" src="https://immortalseed.me/scripts/collapse_250819.js"></script><script type="text/javascript" src="https://immortalseed.me/scripts/jquery.lazyload.mini.js"></script><script type="text/javascript" src="https://immortalseed.me/scripts/main_250819.js"></script><script type="text/javascript" src="https://immortalseed.me/scripts/menu_250819.js"></script><link rel="stylesheet" href="/include/templates/default/latesttorrents.css" type="text/css"/><script type="text/javascript" src="https://immortalseed.me/scripts/sunos.js"></script><script type="text/javascript" src="https://immortalseed.me/scripts/tooltip_080820.js"></script><script type="text/javascript">
	//<![CDATA[

	jQuery(document).ready(function()
	{
		if ( !navigator.userAgent.match( /ipad/i ) )
		{
			jQuery("#lazyload img").lazyload({placeholder : themedir+"images/loading.gif", effect:"fadeIn"});
		}
	});

	//]]>
</script>
<script type="text/javascript">	
	//<![CDATA[
	var l_uncheckall="uncheck all";
	var l_checkall="check all";
	var l_logout="Are you sure you want to log out?";
	var l_ajaxerror="There was a problem with the request. Please report this to administrator.";
	var l_ajaxerror2="Cannot create XMLHTTP instance.";	
	var l_updateerror = "There was an error performing the update.\n\nError Message:\n-----------------------------------\n"; 
	var l_pleasewait="Please wait …";
	var l_ff="Netscape 6 or Mozilla is needed!";
	var l_newreply = "Post Reply";
	//]]>
</script>
<script type="text/javascript">
	//<![CDATA[
	var persistclose = 1;
	var startX = 3;
	var startY = 3;
	var verticalpos = "fromtop";
	var iv = "no";

	function showLoginBox(boxname)
	{
		if (iv == "reCAPTCHA")
		{
			window.location="login.php?";
		}
		else
		{
			if (TSGetID(boxname).style.display == "none")
			{
				ts_show(boxname);
				TSGetID("username").focus();
			}
			else
			{
				ts_hide(boxname);
			}
		}
	}

	function iecompattest()
	{
		return (document.compatMode && document.compatMode!="BackCompat") ? document.documentElement : document.body
	}

	function get_cookie(Name)
	{
		var search = Name + "=";
		var returnvalue = "";
		if (document.cookie.length > 0)
		{
			offset = document.cookie.indexOf(search);
			if (offset != -1)
			{
				offset += search.length;
				end = document.cookie.indexOf(";", offset);
				if (end == -1) end = document.cookie.length;
				returnvalue=unescape(document.cookie.substring(offset, end));
			}
		}
		return returnvalue;
	}

	function closebar()
	{
		if (persistclose)
			document.cookie="remainclosed=1";
		document.getElementById("topbar").style.visibility="hidden";
	}

	function staticbar()
	{
		barheight=document.getElementById("topbar").offsetHeight;
		var ns = (navigator.appName.indexOf("Netscape") != -1) || window.opera;
		var d = document;
		function ml(id)
		{
			var el=d.getElementById(id);
			if (!persistclose || persistclose && get_cookie("remainclosed")=="")
			el.style.visibility="visible";
			if(d.layers)el.style=el;
			el.sP=function(x,y){this.style.right=x+"px";this.style.top=y+"px";};
			el.x = startX;
			if (verticalpos=="fromtop")
				el.y = startY;
			else
			{
				el.y = ns ? pageYOffset + innerHeight : iecompattest().scrollTop + iecompattest().clientHeight;
				el.y -= startY;
			}
			return el;
		}

		window.stayTopLeft=function()
		{
			if (verticalpos=="fromtop")
			{
				var pY = ns ? pageYOffset : iecompattest().scrollTop;
				ftlObj.y += (pY + startY - ftlObj.y)/8;
			}
			else
			{
				var pY = ns ? pageYOffset + innerHeight - barheight: iecompattest().scrollTop + iecompattest().clientHeight - barheight;
				ftlObj.y += (pY - startY - ftlObj.y)/8;
			}
			ftlObj.sP(ftlObj.x, ftlObj.y);
			setTimeout("stayTopLeft()", 10);
		}
		ftlObj = ml("topbar");
		stayTopLeft();
	}

	if (window.addEventListener)
		window.addEventListener("load", staticbar, false);
	else if (window.attachEvent)
		window.attachEvent("onload", staticbar);
	else if (document.getElementById)
		window.onload=staticbar;
	//]]>
</script>
</head>
<body class="yui-skin-sam">
<div id="dhtmltooltip"></div>
<img id="dhtmlpointer" src="https://immortalseed.me/images/arrow2.gif">

<div id="topbar" class="thead">
	<span style="float: right;">
		<a href="#" onclick="closebar(); return false"><img style="float: left;" src="https://immortalseed.me/images/close.gif" border="0" alt="" /></a>
	</span>
	You are Unregistered, please <a href="https://immortalseed.me/signup.php?"><u>register</u></a> or <a href="javascript:void(0);" onclick="showLoginBox('loginbox');"><u>login</u></a> to gain Full access
	<div id="loginbox" style="display: none; padding-top: 5px;">
		<form method="post" action="https://immortalseed.me/takelogin.php">
		<table class="subheader">
			<tr><td class="none" align="right">Username:</td><td class="none"><input type="text" name="username" id="username" class="inputUsername" value="" /></td></tr>
			<tr><td class="none" align="right">Password:</td><td class="none"><input type="password" name="password" class="inputPassword" value="" /></td></tr>
			
			<tr><td  class="none" colspan="2" align="right"> <input type="submit" value="LOGIN" style="vertical-align: middle;" /> <input type="reset" value="RESET" style="vertical-align: middle;" /></td></tr>
		</table>
		</form>
	</div>
</div>

<div class="content">
	<div id="top">
		<div class="top_text">
		
			Recover Password: <a href="https://immortalseed.me/recover.php">via Email</a> | <a href="https://immortalseed.me/recoverhint.php">via Question</a>
			
		</div>
		<div class="padding" align="center">
</div>
</div>
<div id="header">


</div>
<div id="menu">

	<!-- START TSSE MENU -->
	<ul class="TSSEMenu TSSEMenum">
		<li class="TSSEMenui"><a class="TSSEMenui" href="https://immortalseed.me/index.php">Home</a></li>
																							</ul>
<!-- END TSSE MENU -->
</div>
<div id="main">
	<div class="left_side">


	<script type="text/javascript">
		function ts_show_tag(id, status)
		{
			if (TSGetID(id)){if (status == true || status == false){TSGetID(id).style.display = (status == true)?”none”:”";}
			else{TSGetID(id).style.display = (TSGetID(id).style.display == “”)?”none”:”";}}
		}
	</script>
	<div class="notification-border-e" id="notification_182fa27bc060366a3b07ef9c5084472d" align="center">
		<table class="notification-th-e" border="0" cellpadding="2" cellspacing="0">
			<tbody>
				<tr>
					<td align="left" width="100%" class="none">
					&nbsp;<span class="notification-title-e">Login Locked! (the maximum number of failed Login attempts is reached during reauthentication)</span>
					</td>
					<td class="none"><img src="https://immortalseed.me/include/templates/default/images/notification_close.gif" alt="" onclick="ts_show_tag('notification_182fa27bc060366a3b07ef9c5084472d', true);" class="hand" border="0" height="13" width="13" /></td>
				</tr>
			</tbody>
		</table>
		<div class="notification-body">
			We have come to believe you are trying to cheat our system (possibly because of too many failed login attempts), therefore we’ve banned your ip!<br /><br />Click <a href="https://immortalseed.me/unbaniprequest.php">here</a> to fill Unban IP Request form!<br />Click <a href="https://immortalseed.me/contactus.php">here</a> to contact us!<br />Click <a href="irc.php">here</a> to chat with us on IRC!
		</div>
	</div>
	<br />
	<br />
	</div>
	</div>
		<div id="footer">
			<div class="padding">
				<div style="display: none;">Powered by <font color="white"><strong><a href="http://templateshares.net" target="_blank">TS Special Edition v.7.2</a></strong></font></div>  © 2009-2022 <font color="white"><a href="https://immortalseed.me" target="_self"><strong>immortalseed.me</strong></a></font>
				[Executed in <b> 0.0219 </b>seconds]
			</div>
			
		</div>
	</div>


<!-- TS Save User Stats Code -->
	<script type="text/javascript">
	<!--
		function TSwriteCookie()
		{
			var today = new Date();
			var the_date = new Date("December 31, 2023");
			var the_cookie_date = the_date.toGMTString();
			var the_cookie = "users_resolution="+ screen.width +"x"+ screen.height;
			var the_cookie = the_cookie + ";expires=" + the_cookie_date;
			document.cookie=the_cookie;
		}
		TSwriteCookie();
	//-->
	</script>
	<img src="https://immortalseed.me/staffcp/isstuff.php?rand=1668269152&ref=https%3A%2F%2Fimmortalseed.me%2Ftakelogin.php" alt="" title="" width="1" height="1" border="0" />
<!-- TS Save User Stats Code -->

</body>
</html>

   at Jackett.Common.Indexers.ImmortalSeed.<>c__DisplayClass14_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/ImmortalSeed.cs:line 130
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 161
   at Jackett.Common.Indexers.ImmortalSeed.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/ImmortalSeed.cs:line 127
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
I can login without problems so the issue appears to be at your end.
looking at the html you have provided I see the following:
```
<title>immortalseed.me :: An error has occured!</title>

<span class="notification-title-e">Login Locked! (the maximum number of failed Login attempts is reached during reauthentication)</span>

<div class="notification-body">
			We have come to believe you are trying to cheat our system (possibly because of too many failed login attempts), therefore we’ve banned your ip!<br /><br />Click <a href="https://immortalseed.me/unbaniprequest.php">here</a> to fill Unban IP Request form!<br />Click <a href="https://immortalseed.me/contactus.php">here</a> to contact us!<br />Click <a href="irc.php">here</a> to chat with us on IRC!
```

so you need to follow the instructions to get yourself unbanned.
