### ISSUE TITLE
Kinozal tracker downloading error

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#13721]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Image: linuxserver/jackett
Flaresolverr: Yes
Version: v0.20.2250
```

### Description

1) Please search for something in Kinozal indexer. For example, Tulsa King.
2) Hit download button.

404 HTTP Error:
`http://192.168.0.1:9117/dl/kinozal/?jackett_apikey=key&path=Q2ZESjhBQ2lSU1lGeGpSTnBkSHM2MFJBVW02b2xmZF96UzFsX3FjME1hWmEySzNsRDBKa1JfZmNuQ3pza2RXMWZkVDZOMXp5N2ZsQ2Uxbjd4WkVIa24xWFdVNk9Wc2NMSk42M0xQcWxBZkdlMzBvUnFQZDRwdEUycmxFdzcyb1RrcXh2LXlVTGdIUGJDMTQ0eFBKZC11QS1CRWtLUWlKRC1xZkw4bzV3QjNBWkIwTlM&file=2022++WEBDL+1080p+-+RUSSIAN`

### Logged Error Messages

```text
2022-11-16 07:08:36	Error	
Error downloading. indexer: kinozal path: http://kinozal.tv/download.php?id=1942978
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 85
2022-11-16 07:08:36	Error	
<!DOCTYPE HTML>
<html><head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">

<title>Вход :: Кинозал.ТВ</title>
<meta name="description" content="Торрент трекер Кинозал.ТВ - фильмы и сериалы, мультфильмы, книги и музыка, скачать бесплатно с трекера">
<meta name="Keywords" content="250 лучших фильмов, 100 лучших фильмов, лучшие комедии, лучшие фильмы ужасов, лучшие драмы, лучшие фильмы +всех времен, kinozal, скачать, торрент-трекер, торрент скачать бесплатно">

<meta name="robots" content="index,follow">
<link rel="shortcut icon" href="/pic/favicon.ico" type="image/x-icon">
<link rel="search" type="application/opensearchdescription+xml" title="Поиск на Кинозал.ТВ" href="/pic/opensearch.xml">
<link rel="stylesheet" href="/pic/0_kinozal.tv.css?v=2.82" type="text/css">
<script type="text/javascript" src="/pic/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="/pic/use.js?v=1.8"></script>




</head>
<body>


<div id="header">
	<table border="0" cellspacing="0" cellpadding="0" style="width:100%;padding:0;margin:0;border:0px;"><tr>
		<td style="width:43%;"><div class="logo_new"><a href="https://kinozal.tv" title="Кинозал.ТВ"><img src="/pic/logo3.gif" alt="Кинозал.ТВ"></a></div></td>
		<td style="width:57%;" align=right><div class="rb_new" style="height:93px;overflow: hidden;">

<div style="padding:5px 25px 0px 10px">
<div id='eb750d49cf'></div>


</div>

			<div>


</div></div></td></tr>
	</table>
	<div class="clr"></div>
	<div class="menu">
	<ul>
		<li><a href="/" title="Главная">Главная</a></li>
		<li><a href="http://forum.kinozal.tv" title="Форум">Форум</a></li>
		<li><a href="/signup.php" title="Регистрация на трекере">Регистрация</a></li>
		<li><a href="/browse.php" title="Каталог раздач">Раздачи</a></li>
		<li><a href="/top.php" title="Топ раздач">Топ раздач</a></li>
		<li><a href="/personsearch.php" title="Персоны">Персоны</a></li>
		<li><a href="/novinki.php" title="Новинки кино">Новинки кино</a></li>
		<li><a href="/groupexlist.php" title="Каталог групп">Группы</a></li>
	</ul>
	<form action="/browse.php" method="get" id="srchform">
		<div><input type="text" class="inp" id="s" name="s" size="15" value=""><input class="s_submit" type="submit" title="Поиск раздач"></div>
	</form>
	<div class="clr"></div>
	</div>
	<span class="zan_l"></span>
	<span class="zan_r"></span>
</div>
<div class="clr"></div>
<div id="main">
<div style="width: 100%; text-align: center;"><div style="width: 700px; display: inline-block;text-align: left;">
<div class=pad0x0x5x0><ul class=lis><li class=mn><a href="/login.php">Вход</a></li><li><a href="/signup.php">Регистрация в Кинозал.ТВ</a></li><li><a href="/recover.php">Восстановление пароля</a></li></ul></div>
<form method=post action="/takelogin.php" name=upt"><div class=bx1>Чтобы просматривать эту страницу, нужно зайти на сайт</div><input type=hidden name=to value="/download.php?id=1942978"><div class="bx1_0"><input type=hidden value=takerecover name=wact><div class="pad10x10 floatleft"><table class="tables1" cellspacing=0 cellpadding=0><tr><td class="w150 nw b">Логин</td><td><input type=text size=35 id="username" name="username" value=""></td><tr><td class="w150 nw b">Пароль</td><td><input type=password size=35 id="password" name="password" value=""></td><tr><td colspan=2 class="right"><input class=buttonS type=submit value=" Войти "></td></table></div><div class=pad10x10 style="margin: 0px 5px 0px 380px;">Рады Вас приветствовать в Кинозал.ТВ<br>Для входа на сайт введите логин и пароль<br>Не зарегистрированы в Кинозал.ТВ? <a href="/signup.php" class=sba>Присоединиться</a><br></div></div></form></div></div><div class="clr"></div>
</div>
</div>
</body></html>
2022-11-16 07:08:35	Error	
CardigannIndexer (kinozal): An exception occurred while trying Infohash block with hashSelector li:first-child and titleSelector div.b
```

**Comment by garfield69** [comment]
Please edit the kinozal config and change the sitelink from `http://kinozal.tv/` to `https://kinozal.tv/`
and see if that resolves the issue.
Let me know how it goes.

**Comment by garfield69** [comment]
good. next release of Jackett will include an auto-sitelink update.

**Comment by ilike2burnthing** [comment]
[v0.20.2255](https://github.com/Jackett/Jackett/releases/tag/v0.20.2255)

**Comment by SuberSeb** [comment]
Hello. Faced the same issue again. Link is https://kinozal.tv/

**Comment by garfield69** [comment]
Link is https://kinozal.tv/ is working for me.

**Comment by SuberSeb** [comment]
Downloading is working too?

**Comment by garfield69** [comment]
Oh. didn't test that. needs investigation. Thanks for the heads up.

**Comment by garfield69** [comment]
Was able to get the download working again simply by using the jackett dashboard to edit the kinozal config and saving.
Problem is that normally you wouls not be able to do a search if you were not logged in and your cookie has expired, but kinozal appears to allow searches and only promp for a login at download.
Not sure that the cardigann yaml indexer can handle this event.

**Comment by SuberSeb** [comment]
Hm, I will test too
