### ISSUE TITLE
[thepiratebay] The tracker seems to be down.

### ISSUE THREAD

**Issue by magnetus26** [Jackett/Jackett#13737]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett.Common.IndexerException: Exception (thepiratebay): Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 522) - The tracker seems to be down.
 ---> System.Exception: Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 522) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 570
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 523
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1414
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 692
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 311
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

### Description

[thepiratebay] (testing) Exception (thepiratebay): Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 522) - The tracker seems to be down.: Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 522) - The tracker seems to be down.

[v3.0.9.1549] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (thepiratebay): Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 522) - The tracker seems to be down.
 ---> System.Exception: Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 522) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 570
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 526
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1414
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 324
   --- End of inner exception stack trace ---

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (thepiratebay): Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 522) - The tracker seems to be down.: Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error 522) - The tracker seems to be down.
Click here to open an issue on GitHub for this indexer.
```

**Comment by ilike2burnthing** [comment]
Been down for a few hours by the looks of it - https://pirates-forum.org/misc.php?page=tpbstatus

**Comment by rrrevin** [comment]
No.. it comes and goes. It's just suffering outages lately. Works fine for me. No need to remove.

**Comment by ilike2burnthing** [comment]
Unless it's down for 30 days, it's not getting removed.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
API https://apibay.org/q.php?q=bad+batch&cat=100,101,102,103,104 cloudflare Web server is down Error code 521
same with the web site https://thepiratebay.org/
https://pirates-forum.org/misc.php?page=tpbstatus is offline too so no status available either

**Comment by garfield69** [comment]
both the web site and the API are online.
the forum is still out but that is not relevant to jackett.

**Comment by hapklaar** [comment]
api is offline again

**Comment by ilike2burnthing** [comment]
back up

**Comment by Gareth4321** [comment]
Back down.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/13737#issuecomment-1409827221

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
TPB API and WEB and TOR is offline
See https://pirates-forum.org/misc.php?page=tpbstatus for status

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
API offline

**Comment by garfield69** [comment]
online

**Comment by Mshartzer** [comment]
Exception (thepiratebay): Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error GatewayTimeout) - The tracker seems to be down.: Request to https://apibay.org/precompiled/data_top100_recent.json failed (Error GatewayTimeout) - The tracker seems to be down.     This is what i am getting when testing in Jacket.  Can someone help me please?  Thanks

**Comment by garfield69** [comment]
This is a genuine issue, TPB API server is offline.
You can prove this for yourself by using a browser on the same machine that you are running Jackett on, and using this address
`https://apibay.org/precompiled/data_top100_recent.json`
