### ISSUE TITLE
Error System.TypeInitializationException: The type initializer for 'System.ComponentModel.TypeDescriptor' threw an exception.

### ISSUE THREAD

**Issue by pharpe** [Jackett/Jackett#13750]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.1.182:8191/
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.2247-ls83)
File /etc/issue: Ubuntu 20.04.4 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.39.4 (64bit OS) (64bit process)
Environment version: 6.0.11 (/app/Jackett/)
Starting Jackett v0.20.2297
```

### Description

Running Jackett in docker on Ubuntu 20.04.5 LTS.  It is a CTS container on Proxmox.  I have had it running for 3 years but over the last month the docker container randomly disappears.  I can manually restart it and it works fine.  I am seeing this error in the logs consistently.

Error System.TypeInitializationException: The type initializer for 'System.ComponentModel.TypeDescriptor' threw an exception.

### Logged Error Messages

```text
2022-11-28 09:21:51.4317 Error Error writing config file /config/Jackett/ServerConfig.json
System.TypeInitializationException: The type initializer for 'System.ComponentModel.TypeDescriptor' threw an exception.
 ---> System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at System.Guid.NewGuid()
   at System.ComponentModel.TypeDescriptor..cctor()
   --- End of inner exception stack trace ---
   at System.ComponentModel.TypeDescriptor.CheckDefaultProvider(Type type)
   at System.ComponentModel.TypeDescriptor.NodeFor(Type type, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Type type, String typeName)
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.CanTypeDescriptorConvertString(Type type, TypeConverter& typeConverter)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CanConvertToString(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContract(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, Formatting formatting, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting)
   at Jackett.Common.Services.SerializeService.Serialise(Object obj) in /home/vsts/work/1/s/src/Jackett.Common/Services/SerializeService.cs:line 9
   at Jackett.Common.Services.ConfigurationService.SaveConfig[T](T config) in /home/vsts/work/1/s/src/Jackett.Common/Services/ConfigurationService.cs:line 171 
2022-11-28 09:21:51.5372 Error System.TypeInitializationException: The type initializer for 'System.ComponentModel.TypeDescriptor' threw an exception.
 ---> System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at System.Guid.NewGuid()
   at System.ComponentModel.TypeDescriptor..cctor()
   --- End of inner exception stack trace ---
   at System.ComponentModel.TypeDescriptor.CheckDefaultProvider(Type type)
   at System.ComponentModel.TypeDescriptor.NodeFor(Type type, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Type type, String typeName)
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, String path, Object& result, Exception& error)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.GetPropertyValue(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in /home/vsts/work/1/s/src/Jackett.Server/Startup.cs:line 77
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args) System.TypeInitializationException: The type initializer for 'System.ComponentModel.TypeDescriptor' threw an exception.
 ---> System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at System.Guid.NewGuid()
   at System.ComponentModel.TypeDescriptor..cctor()
   --- End of inner exception stack trace ---
   at System.ComponentModel.TypeDescriptor.CheckDefaultProvider(Type type)
   at System.ComponentModel.TypeDescriptor.NodeFor(Type type, Boolean createDelegator)
   at System.ComponentModel.TypeDescriptor.GetDescriptor(Type type, String typeName)
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, String value, String path, Object& result, Exception& error)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.GetPropertyValue(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in /home/vsts/work/1/s/src/Jackett.Server/Startup.cs:line 77
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)
```

**Comment by ilike2burnthing** [comment]
When you say the container disappears, what do you mean?

Please provide your Docker run command/compose file for your Jackett container.

In your mapped `/config` folder, you should have `log.txt` files, `ServerConfig.json`, a `DataProtection` folder containing `key-xxx...xxx.xml` files, and an `Indexers` folder containing `*.json` and `*.json.bak` files.

Do these all exist for you? Have they all been recently updated? If you apply a change to your Jackett settings, is this reflected in ServerConfig.json and without errors in your logs?

**Comment by pharpe** [comment]
I got an error in Sonarr that it couldn't connect to any indexers.  So I tried to pull up the Jackett web dashboard but it timed out.  Then I went into Ubuntu and rant _docker container ls_.  The Jackett container was not listed.  Checked the logs and saw what I posted.  Then re ran the docker compose and Jackett started up fine.  It worked for a couple weeks and then the same thing happened again.  

Docker compose:
```
docker run -d \
--name=jackett \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=America/Chicago \
-e AUTO_UPDATE=true \
-p 9117:9117 \
-v /mnt/storage/config/jackett:/config \
-v /mnt/storage/downloads:/downloads \
--restart unless-stopped \
--log-opt max-size=3m --log-opt max-file=3 \
lscr.io/linuxserver/jackett:latest
```
Here is the /config folder contents
```
root@ct-plex:/mnt/storage/config/jackett/Jackett# ls -al
total 22583
drwxrwxrwx 4 pharpe pharpe      17 Nov 29 12:13 .
drwxrwxrwx 5 pharpe pharpe       6 Nov 11 14:31 ..
drwxrwxrwx 2 pharpe pharpe      10 Nov 17 08:04 DataProtection
drwxrwxrwx 2 pharpe pharpe      28 Nov 11 15:35 Indexers
-rwxrwxrwx 1 pharpe pharpe     690 Nov 29 11:17 ServerConfig.json
-rw-r--r-- 1 pharpe pharpe 1789255 Nov 29 13:36 log.txt
-rw-r--r-- 1 pharpe pharpe 2094066 Nov 28 09:18 log.txt.20221128.00195.txt
-rw-r--r-- 1 pharpe pharpe 2094066 Nov 28 09:21 log.txt.20221128.00196.txt
-rw-r--r-- 1 pharpe pharpe 2083795 Nov 29 11:26 log.txt.20221129.00000.txt
-rw-r--r-- 1 pharpe pharpe 1940771 Nov 29 11:33 log.txt.20221129.00001.txt
-rw-r--r-- 1 pharpe pharpe 1940683 Nov 29 12:13 log.txt.20221129.00002.txt
-rw-r--r-- 1 pharpe pharpe  347185 Nov 29 12:16 updater.txt
-rw-r--r-- 1 pharpe pharpe 2097013 Oct  7 15:29 updater.txt.20221007.00000.txt
-rw-r--r-- 1 pharpe pharpe 2097098 Oct 16 23:36 updater.txt.20221016.00000.txt
-rw-r--r-- 1 pharpe pharpe 2097137 Oct 25 07:37 updater.txt.20221025.00000.txt
-rw-r--r-- 1 pharpe pharpe 2097086 Nov  2 03:21 updater.txt.20221102.00000.txt
-rw-r--r-- 1 pharpe pharpe 2097143 Nov 28 10:24 updater.txt.20221128.00000.txt
```

Testing change to ServerConfig.json
Starting file:
```
root@ct-plex:/mnt/storage/config/jackett/Jackett# cat ServerConfig.json
{
  "Port": 9117,
  "AllowExternal": true,
  "AllowCORS": false,
  "APIKey": "1yxeni5cbs7gh778qtfgmbdky0nh63ti",
  "AdminPassword": null,
  "InstanceId": "pa4yszzxw283ue3hk9zvcbj0j31ak5crw4p6qf9mu6clnrre069glosl1ogdey9c",
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "",
  "BaseUrlOverride": "",
  "CacheEnabled": true,
  "CacheTtl": 2100,
  "CacheMaxResultsPerIndexer": 1000,
  "FlareSolverrUrl": "http://192.168.1.182:8191/",
  "FlareSolverrMaxTimeout": 55000,
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyType": -1,
  "ProxyUrl": "",
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
```
Changed auto update to True in the Web Dashboard
File after change shows _  "UpdateDisabled": true,_
```
root@ct-plex:/mnt/storage/config/jackett/Jackett# cat ServerConfig.json
{
  "Port": 9117,
  "AllowExternal": true,
  "AllowCORS": false,
  "APIKey": "1yxeni5cbs7gh778qtfgmbdky0nh63ti",
  "AdminPassword": null,
  "InstanceId": "pa4yszzxw283ue3hk9zvcbj0j31ak5crw4p6qf9mu6clnrre069glosl1ogdey9c",
  "BlackholeDir": "",
  "UpdateDisabled": true,
  "UpdatePrerelease": false,
  "BasePathOverride": "",
  "BaseUrlOverride": "",
  "CacheEnabled": true,
  "CacheTtl": 2100,
  "CacheMaxResultsPerIndexer": 1000,
  "FlareSolverrUrl": "http://192.168.1.182:8191/",
  "FlareSolverrMaxTimeout": 55000,
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyType": -1,
  "ProxyUrl": "",
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
```

**Comment by ilike2burnthing** [comment]
Oh ok, it just stopped then, rather than was removed.

There were key files in the `DataProtection` folder?

Is there anything in the logs before those errors which might give us an idea as to what was happening leading up to the crash?

**Comment by pharpe** [comment]
Yes 8 key files
```
-rw------- 1 pharpe pharpe  999 Nov 17 08:04 key-008d5e3e-449e-4580-a55b-050beae73c96.xml
-rwxrwxrwx 1 pharpe pharpe 1000 Nov 28  2021 key-0bb2ed41-562c-49dd-a2c9-611d4ad75b56.xml
-rwxrwxrwx 1 pharpe pharpe  997 Jun  5  2021 key-6f900e01-d45e-429e-9da7-9955bee8dcd6.xml
-rwxrwxrwx 1 pharpe pharpe  998 Mar  8  2021 key-8261a6fb-6495-47da-a637-5b4e953d6168.xml
-rwxrwxrwx 1 pharpe pharpe  998 Sep  1  2021 key-99b9b5f3-92f2-424a-93ee-d186535d8bc9.xml
-rwxrwxrwx 1 pharpe pharpe 1000 Feb 24  2022 key-a32e51d2-a3db-42dd-b03e-d95db6af6b0e.xml
-rw-r--r-- 1 pharpe pharpe 1000 Aug 20 20:58 key-de59d056-0748-4314-8665-4a730429fe66.xml
-rwxrwxrwx 1 pharpe pharpe 1000 May 24  2022 key-e3ffe9f8-c20e-448e-8e62-66cb523d760e.xml
```

Nothing in the logs I saw but the error I posted over and over

**Comment by ilike2burnthing** [comment]
```text
-rw-r--r-- 1 abc abc 1000 Jul 18 07:47 key-1.xml
-rw-r--r-- 1 abc abc 1000 May  3  2021 key-2.xml
-rw-r--r-- 1 abc abc 1000 Feb 17  2020 key-3.xml
-rwxr-xr-x 1 abc abc 1000 Nov 20  2019 key-4.xml
-rw-r--r-- 1 abc abc 1000 Aug 11  2020 key-5.xml
-rw-r--r-- 1 abc abc  997 Jan 23  2022 key-6.xml
-rw-r--r-- 1 abc abc  999 Apr 21  2022 key-7.xml
-rw-r--r-- 1 abc abc  999 Jul 31  2021 key-8.xml
-rw-r--r-- 1 abc abc 1000 Feb  4  2021 key-9.xml
-rw-r--r-- 1 abc abc 1000 Nov  8  2020 key-10.xml
-rw-r--r-- 1 abc abc  998 Oct 27  2021 key-11.xml
-rw-r--r-- 1 abc abc  999 May 15  2020 key-12.xml
-rw------- 1 abc abc 1000 Oct 15 06:36 key-13.xml
```

Apparently so, although I'm not sure why.

@garfield69 any insight to the error?

**Comment by garfield69** [comment]
>any insight to the error?

Urg, well above my paygrade.
suggestion: shutdown the jackett docker image, rename the DataProtection folder to oldDataProtection and start up jackett.
then use the jackett dashboard to edit each of your private indexers and overtype the password and save.
see if that makes a difference.

**Comment by pharpe** [comment]
So just edit the indexer and type the password back in? Or do I need to change it to something else and change it back?  What about public indexers?

**Comment by ilike2burnthing** [comment]
Re-enter the password. Public indexers will work without issue.

**Comment by pharpe** [comment]
Ok.  Did that.  So Just monitor it now?

**Comment by ilike2burnthing** [comment]
Yup.

**Comment by pharpe** [comment]
Crashed again.  Here is the full log
[https://pastebin.com/vVBYW8UX](url)

It's basically the same thing over and over.  There are also 5 backup logs that are just full of the same thing.

**Comment by ilike2burnthing** [comment]
My only other suggestion is starting completely from scratch - delete the container and image, rename/move/delete `/mnt/storage/config/jackett`, add a new Jackett container, disable auto-update in Jackett's settings (you can use [Watchtower](https://github.com/containrrr/watchtower) to update the container instead), add your indexers anew, and see how you get on.
