### ISSUE TITLE
[SugoiMusic] Received an unexpected EOF or 0 bytes from the transport stream. For Keyworldless search.

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13774]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-12-12 15:56:44	Info	Using HTTP Client: HttpWebClient2
2022-12-12 15:56:44	Info	Using FlareSolverr: http://127.0.0.1:8191
2022-12-12 15:56:44	Info	Using proxy: Disabled
2022-12-12 15:56:44	Info	App config/log directory: C:\ProgramData\Jackett
2022-12-12 15:56:44	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2022-12-12 15:56:44	Info	Running in Docker: No
2022-12-12 15:56:44	Info	Jackett variant: CoreWindows
2022-12-12 15:56:44	Info	OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
2022-12-12 15:56:44	Info	Environment version: 6.0.11 (C:\ProgramData\Jackett\)
2022-12-12 15:56:44	Info	Starting Jackett v0.20.2360
```

### Description

When performing a keywordless search (TEST) sugoiMusic returns the error logged in the next section below.
However, when copy/pasting the same GET Jackett generates into the browser the search returns results.
And using Jackett to perform a keyword search returns results.
I'm unable to figure this one out, need a fresh pair of eyes on the issue. 

### Logged Error Messages

```text
2022-12-12 15:50:23	Debug	CACHE IsCacheEnabled => false
2022-12-12 15:50:23	Debug	WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://sugoimusic.me/torrents.php?searchstr=&group_results=0&action=advanced&taglist=&order_by=time&order_way=desc&freetorrent=0&searchsubmit=1)
2022-12-12 15:50:25	Error	Jackett.Common.IndexerException: Exception (sugoimusic):  Received an unexpected EOF or 0 bytes from the transport stream.
 ---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 221
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 526
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1414
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 324
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 324
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 695
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 228
2022-12-12 15:50:25	Info	Manual search in SugoiMusic => Found 0 releases
```

**Comment by ilike2burnthing** [comment]
Same issue here, though it was working yesterday when I tested all indexers. I'm fairly certain this happened to me before, and then resolved itself after a day or few.

Currently, trying to access the torrents page in browser will sometimes work fine, and other times result in `ERR_HTTP2_PROTOCOL_ERROR`, and I'm not really sure why.

At a guess, there's just some site issue, and we'll have to wait it out.

**Comment by ilike2burnthing** [comment]
Working ok for me now. You?

**Comment by garfield69** [comment]
online
