### ISSUE TITLE
[yggtorrent] (testing) Test search in YGGtorrent => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by fischer-c187** [Jackett/Jackett#13788]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
debian 11
docker : no
FlareSolverr : yes
```

### Description

hi, i have this message when i test my indexer : 

Test search in YGGtorrent => Found no results while trying to browse this tracker 

in my logs i have this message : CardigannIndexer (yggtorrent): Relogin required

### Logged Error Messages

```text
2022-12-18 21:54:21 	Error 	

System.Exception: Test search in YGGtorrent => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 316
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

2022-12-18 21:54:21 	Info 	

Test search in YGGtorrent => Found 0 releases

2022-12-18 21:54:12 	Info 	

CardigannIndexer (yggtorrent): Relogin required

2022-12-18 21:54:02 	Info 	

CardigannIndexer (yggtorrent): Relogin required
```

**Comment by ilike2burnthing** [comment]
Are you using v0.20.2397 or later?

Is the sitelink in the indexer `https://www6.yggtorrent.lol/`?

Have you tried to reconfigure the indexer and test again?

If the answers to those questions are all yes, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by daco77** [comment]
Hi same issue here

**Comment by daco77** [comment]
is working many weeks, i update to the last version, no change

**Comment by fischer-c187** [comment]
yesterday I had the version 0.20.2400, this morning i update to v0.20.2402 but dont work

**Comment by garfield69** [comment]
please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Enohriel** [comment]
Changing the url from https://yggtorrent.lol/ to https://www6.yggtorrent.lol/ did the trick for me.

**Comment by alxdca** [comment]
Thanks @Enohriel, that fixed it on my side

**Comment by garfield69** [comment]
v0.20.2405
