### ISSUE TITLE
[yggtorrent] (updating) Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match

### ISSUE THREAD

**Issue by allforonetv** [Jackett/Jackett#13794]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Admin password: 
Blank to disable
 
Base path override: 
/jackett
Base URL override: 
http://jackett:9117
Server port: 
9117
Blackhole directory: 
c:\torrents\
Proxy type: 
Disabled
Proxy URL: 
Proxy port: 
Proxy username: 
Proxy password: 
External access: 
Allow CORS: 
Disable auto update: 
Update to pre-release: 
Enhanced logging: 
Cache enabled (recommended): 
Cache TTL (seconds): 
2100
Cache max results per indexer: 
1000
FlareSolverr API URL: 
http://**.**.***.***:8191
FlareSolverr Max Timeout (ms): 
90000
OMDB API key: 
OMDB API Url: 
Blank for default
Jackett Version v0.20.2402
× An error occurred while updating this indexer
```

### Description

When I try to connect I get an error message

while the passwords are correct

### Logged Error Messages

```text
https://www6.yggtorrent.lol/

An error occurred while updating this indexer
Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match
Click here to open an issue on GitHub for this indexer.
```

**Comment by ilike2burnthing** [comment]
Check the following troubleshooting steps:
https://github.com/Jackett/Jackett/wiki/Troubleshooting/#login-failed-selector

**Comment by markettepigeon** [comment]
Hello,

It was working yesterday however I think the problem comes from Cloudflare protections.
I will try the solution: FlareSolverr

Cordially,

**Comment by ilike2burnthing** [comment]
@markettepigeon did you mean to reply to https://github.com/Jackett/Jackett/issues/13792 instead?

**Comment by markettepigeon** [comment]
@

**Comment by markettepigeon** [comment]
@ilike2burnthing 

That was a mistake on my part.  I have been fighting since this afternoon against Windows which does not want to install HyperV haha

**Comment by warlordattack** [comment]
There is an error with flaresolver,
look other issue there : 
https://github.com/FlareSolverr/FlareSolverr/issues/628

An error occurred while updating this indexer
Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 55 seconds elapsing. ---> System.TimeoutException: The operation was canceled. ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException (125): Operation canceled --- End of inner exception stack trace --- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async) at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) --- End of inner exception stack trace --- ---

**Comment by garfield69** [comment]
Try setting your Jackett dashboard config `FlareSolverr Max Timeout (ms):` to a value higher than the default _55000_.
For example, I use **70000**

**Comment by r4lix** [comment]
I even tried with 99999 and still same error, it's the Under Attack Mode of cloudflare, we just need to wait for YGG to remove it

**Comment by allforonetv** [comment]
hello
it works again I can log in
, and floodsolver works perfectly.
but now the downloads do not launch on sonarr and radarr do you have an idea?

the error message is "getting release from indexer faild"

**Comment by Sandrus** [comment]
![image](https://user-images.githubusercontent.com/5290963/208934908-8d872268-8b7e-4ad1-93fb-6bab4bdcda57.png)

It might help, not sure, this is what the log says

**Comment by ilike2burnthing** [comment]
It's working ok here, even with that specific torrent.

I'd suggest reconfiguring your indexer, re-entering your credentials manually, and trying again. If you're getting `Vous devez vous connecter pour télécharger un torrent` it means YGG doesn't see you as signed in.

**Comment by mkay1905** [comment]
try to use the flaresolverr 3.0.0.beta3 version
It resolved all my issues with ygg and jackett

**Comment by dr400** [comment]
> It's working ok here, even with that specific torrent.
> 
> I'd suggest reconfiguring your indexer, re-entering your credentials manually, and trying again. If you're getting `Vous devez vous connecter pour télécharger un torrent` it means YGG doesn't see you as signed in.

Latest version of jackett implemented. Credentials re-entered. But no joy ...

**Comment by ilike2burnthing** [comment]
Malformed? Example?

**Comment by dr400** [comment]
When downloading the torrent file from the search results, the file is 0b and trying to open the link into a browser shows a 404 error

**Comment by the-cute-raccoon** [comment]
I can confirm ygg not working anymore
```

 ---> System.Exception: Parse error
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 221
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 526
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 980
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 581
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1538
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 718
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1690
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 695
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 440
```

**Comment by charliik** [comment]
Same here

**Comment by ilike2burnthing** [comment]
At a guess I'd say it's a result of their Cloudflare protection.

We'll see if there's any reply to https://www6.yggtorrent.lol/forum/index.php?threads/homelab-jellyfin.85774/

**Comment by the-cute-raccoon** [comment]
@ilike2burnthing does the download of the file use the all the cookies (including cloudflare) ? If flaresolverr is working correctly the problem is probably Jackett, what do you think ?

**Comment by ilike2burnthing** [comment]
It should be using that cookie. It's working for some users and not others, and some can't even login or search, so the issue more likely lies with YGG use of Cloudflare protection (which I don't object to, they need to protect their site against assholes DDoSing them).

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/issues/596

**Comment by vitoo** [comment]
With debug log (Enhanced logging) enabled we see the cookies are shown in the log, 
 `_ygg` that is the login cookie 
and cloudflare cookies "cf_*"

so it should work if this cookies are used in the download action

**Comment by ocervell** [comment]
I can confirm it works with Prowlarr latest and flaresolverr 3.0.2 ;)
