### ISSUE TITLE
[TorrentLeech] Error Parsing Json Response: Status=TooManyRequests

### ISSUE THREAD

**Issue by Jimmy062006** [Jackett/Jackett#13796]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2022-12-21 05:09:07.3493 Info Environment version: 6.0.12 (/home/<username>/Jackett/) 
2022-12-21 05:09:07.3557 Info OS version: Unix 5.10.0.20 (64bit OS) (64bit process) 
2022-12-21 05:09:07.3586 Info Jackett variant: CoreLinuxAmdx64 
2022-12-21 05:09:07.3586 Info File /etc/issue: Debian GNU/Linux 11 \n \l 
2022-12-21 05:09:07.3586 Info Running in Docker: No 
2022-12-21 05:09:07.3644 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2022-12-21 05:09:07.3650 Info App config/log directory: /home/<username>/.config/Jackett 
2022-12-21 05:09:07.3650 Info Using proxy: Disabled 
2022-12-21 05:09:07.3650 Info Using FlareSolverr: http://127.0.0.1:8191 
2022-12-21 05:09:07.3840 Info Using HTTP Client: HttpWebClient2
```

### Description

When doing a Sonarr TV series scan the tracker activates Cloudflare protection and the search fails.

### Logged Error Messages

```text
2022-12-21 05:09:43.9682 Info Torznab search in TorrentLeech for Outlander S01 => Found 100 releases 
2022-12-21 05:09:45.5077 Info Torznab search in TorrentLeech => Found 100 releases 
2022-12-21 05:09:46.7716 Info Torznab search in TorrentLeech for Outlander S01 => Found 100 releases 
2022-12-21 05:09:49.0239 Info Torznab search in TorrentLeech for Outlander S01 => Found 100 releases 
2022-12-21 05:09:49.8017 Error Jackett.Common.IndexerException: Exception (torrentleech): Error Parsing Json Response: Status=TooManyRequests Response=<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    <meta http-equiv="refresh" content="35">

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            www.torrentleech.org
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=77ce1b9a2b5e23f6')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            www.torrentleech.org needs to review the security of your connection before proceeding.
        </div>

   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1425
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 692
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 404
```

**Comment by garfield69** [comment]
Your Sonarr searches are happening too quickly in a short time period and triggering the **TooManyRequests** Response 
need to check the torrentleech web site FAQ to see if there is info on the number of requests per period, and see if we can modify the indexer to set a delay to space out the requests to avoid triggering the torrentleech limiter.

**Comment by garfield69** [comment]
I've searched the wiki and forum but cannot find anything pertinent.
So I will set a default delay of 2.1s and once the next release is published in about 23 hours, you can always reopen this ticket if you come unstuck again and we will bump the delay up a bit more until were clear of the limiter.

**Comment by Jimmy062006** [comment]
Unfortunately 2.1 seconds does not work. I will try longer now just to see if it works.

![image](https://user-images.githubusercontent.com/4639349/208943748-9940c960-0247-4a01-8e1f-ab5504466906.png)

**Comment by Jimmy062006** [comment]
`requestDelay: 3.1 # #13796`

Seems to work fine

**Comment by garfield69** [comment]
v0.20.2417

**Comment by trackermb** [comment]
Hi this seems to have raised its head again, Im assuming torrent leech are playing with the delay on their side. Could you increased again please.

Thanks

**Comment by ilike2burnthing** [comment]
@garfield69 this may need more testing to confirm, but I could get this error (granted very rarely) all the way up to a delay of 4s. 4.1 _seems_ to be ok.

Not sure if it's intentional, but it turns out the Test button doesn't respect `requestDelay`. So the most consistent test for me was creating a shortcut for a torznab search which returned 1 result (I was using `q=control+z+s02e03+720p+noma`) and then just spamming that in blocks of 5-10 at a time.

**Comment by garfield69** [comment]
given that rarbg has 5s, I'm not adverse to setting torrentleech to 4.1s. I'll update the indexer and be done with it.

**Comment by garfield69** [comment]
v0.20.2617

**Comment by bakerboy448** [comment]
TL will eventually have this fixed / better process in this side
