### ISSUE TITLE
3changtrai: Error while parsing row

### ISSUE THREAD

**Issue by khoint0210** [Jackett/Jackett#13804]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.20.2417
Ubuntu 20.04
Docker: No
```

### Description

Running test but fail

### Logged Error Messages

```text
CardigannIndexer (3changtrai): Error while parsing row '
<tr>
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=402">
			<img class="c_tvseries" src="pic/cattrans.gif" alt="TV Series" title="TV Series" style="background-image: url(pic/category/chd/scenetorrents/chs/catsprites.png);">
		</a>
		<img src="pic/cattrans.gif" style="background-image: url(pic/category/chd/scenetorrents/chs/additional/movies_bd.png);" alt="Raw" title="Raw">
	</td>
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a class="thumb">
			<img class="lazyload" height="46px" width="45px" data-src="https://m.media-amazon.com/images/M/MV5BZjBiOGIyY2YtOTA3OC00YzY1LThkYjktMGRkYTNhNTExY2I2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg">
			<span>
				<img class="lazyload" width="300px" data-src="https://m.media-amazon.com/images/M/MV5BZjBiOGIyY2YtOTA3OC00YzY1LThkYjktMGRkYTNhNTExY2I2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg">
			</span>
		</a>
		<style>
	.thumb {
	float:left; /* must be floated for same cross browser position of larger image */
	position:relative;
	
}
.thumb:hover {
	border:0; /* IE6 needs this to show large image */
	z-index:1;
}
.thumb span { 
	position:absolute;
	visibility:hidden;
}
.thumb:hover span { 
	visibility:visible;
	left:40px; 
}
	
		</style>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr>
					<td class="embedded">
						<a title="House of the Dragon S01 1080p Blu-ray AVC TrueHD Atmos 7.1-UNTOUCHED" href="details.php?id=12291&amp;hit=1">
							<b>House of the Dragon S01 1080p Blu-ray AVC TrueHD Atmos 7.1-UNTOUCHED</b>
						</a>
						<img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="if (!window.__cfRLUnblockHandlers) return false; domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>Free</font></b> sẽ kết thúc trong <b><span title=&quot;2022-12-25 05:52:14&quot;>1 ngày 17 giờ</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);" data-cf-modified-f63b3c771d483c2ff748a3ff-="">
						<br>Gia Tộc Rồng</td>
					<td width="20" class="embedded" style="text-align: right; " valign="middle">
						<a href="download.php?id=12291&amp;passkey=916f1aa76f9664e7ad07e8531bc25952">
							<img class="download" src="pic/trans.gif" style="padding-bottom: 2px;" alt="download" title="Tải&nbsp;xuống">
						</a>
						<br>
						<a id="bookmark2" href="javascript: bookmark(12291,2);">
							<img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="Đánh dấu torrent">
						</a>
					</td>
					<td width="2" class="embedded" style="text-align: right; " valign="middle"></td>
					<td width="20" class="embedded" style="text-align: right; " valign="middle">
						<a target="_blank" href="https://www.imdb.com/title/tt11198330">
							<img title="IMDb" src="pic/imdb.png" style="width:20px;">8.5</a>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow">
		<a href="comment.php?action=add&amp;pid=12291&amp;type=torrent" title="Thêm&nbsp;bình&nbsp;luận">0</a>
	</td>
	<td class="rowfollow nowrap">
		<span title="2022-12-18 05:52:14">5 ngày<br>6 giờ</span>
	</td>
	<td class="rowfollow">153.24<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=12291&amp;hit=1&amp;dllist=1#seeders">1</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=12291">
			<b>1</b>
		</a>
	</td>
	<td align="center">-</td>
	<td class="rowfollow">
		<i>Ẩn danh</i>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=8.5 +07:00: DateTime parsing failed for "8.5 +07:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 186
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630
```

### Screenshots

![image](https://user-images.githubusercontent.com/12799726/209273905-31823aab-65ca-45d0-81ac-901e227e03f6.png)
![image](https://user-images.githubusercontent.com/12799726/209273931-ad83e656-6d79-467c-a4cc-605652321d26.png)

**Comment by garfield69** [comment]
Looks like there has been a layout change. I see additional comments column and imdb and posters too.
I'll see if I can update the indexer, but it will be untested since I do not have an account to test my changes.

**Comment by garfield69** [comment]
Please try v0.20.2423 and report back. Thanks.

**Comment by khoint0210** [comment]
thanks, it work on the latest update 

don't you mind sharing your email so I can send you the account

**Comment by garfield69** [comment]
I have an account but it has been disabled so there is little point sending me an invite.
However, if you want you, can send an invite to `jacketttest@gmail.com` and @ilike2burnthing can set up the account. Thanks.
