### ISSUE TITLE
[kickasstorrents-ws] (testing) Exception (kickasstorrents-ws): The proxy tunnel request to proxy 'http://10.53.53.5:8118/' failed with status code '404'.": The proxy tunnel request to proxy 'http://10.53.53.5:8118/' failed with status code '404'."

### ISSUE THREAD

**Issue by Devo-McDuff** [Jackett/Jackett#13819]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Base path override: 
/jackett
Base URL override: 
http://jackett:9117
Server port: 
9117
Blackhole directory: 
c:\torrents\
Proxy type: 
HTTP
WARNING: The proxy option potentially leaks requests. Recommendation is to use a VPN.
Proxy URL: 
10.53.53.5
Proxy port: 
8118
Proxy username: 
Proxy password: 
External access: 
Allow CORS: 
Disable auto update: 
Update to pre-release: 
Enhanced logging: 
Cache enabled (recommended): 
Cache TTL (seconds): 
2100
Cache max results per indexer: 
1000
FlareSolverr API URL: 
Blank for default
FlareSolverr Max Timeout (ms): 
55000
OMDB API key: 
OMDB API Url: 
Blank for default
Jackett Version v0.20.2447
```

### Description

Hi,

Apologies if this is the wrong place for this. I've had jackett, along with sonnar, radarr and the BinHex Deluge container with VPN client and Privoxy all running happily on Docker on a Synology NAS for ages. But in the last few days I've noticed lots of indexee fails in Sonarr and Radarr. Checking Jackett and running a test on the 15 indexers I have configured and about two thirds are failing with the proxy error above. It's intermittent though and which indexers affected will vary. If I repeat the manual test on all 15 individually, eventually they will all pass.

Is this something that needs looking at more form the Privoxy end rather than Jackett? Just odd that's it's intermittent (but frequent).  Please let me know if any extra info/logs needed.

Cheers,

Dan

### Logged Error Messages

```text
2022-12-28 17:08:36	Error	
Jackett.Common.IndexerException: Exception (torrentgalaxy): The proxy tunnel request to proxy 'http://10.53.53.5:8118/' failed with status code '404'."
 ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://10.53.53.5:8118/' failed with status code '404'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 221
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 526
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1414
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 324
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 695
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 440
```

**Comment by ilike2burnthing** [comment]
This is an issue with your proxy or system, not Jackett.
