### ISSUE TITLE
Update error / permission denied

### ISSUE THREAD

**Issue by neogamaes** [Jackett/Jackett#13818]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.20.2297

Synology 218, DSM 7.1

Mono version
```

### Description

Hi all,

When I tried to update jackett I got the following error message suggesting a permission issue. 
Any idea how to solve this? 

I updated it a while ago and the issue wasn't there.

Thank you

### Logged Error Messages

```text
2022-12-28 15:59:23	Error	
Error performing update.
System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/tmp/JackettUpdate-v0.20.2447-638078435537048996/Jackett/JackettUpdater' with working directory '/'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Jackett.Common.Services.UpdateService.StartUpdate(String updaterExePath, String installLocation, Boolean isWindows, Boolean noRestart, Boolean trayIsRunning) in /home/vsts/work/1/s/src/Jackett.Common/Services/UpdateService.cs:line 358
   at Jackett.Common.Services.UpdateService.CheckForUpdates() in /home/vsts/work/1/s/src/Jackett.Common/Services/UpdateService.cs:line 139
2022-12-28 15:59:23	Info	
Starting updater: /tmp/JackettUpdate-v0.20.2447-638078435537048996/Jackett/JackettUpdater --Path "/volume1/@appstore/jackett/share" --Type "Console" --Args " --PIDFile /volume1/@appdata/jackett/jackett.pid" --KillPids "12037"
2022-12-28 15:59:06	Info	
Downloading release v0.20.2447 It could take a while...
2022-12-28 15:59:06	Info	
New release found. Current version: v0.20.2297 New version: v0.20.2447
```

**Comment by ilike2burnthing** [comment]
Report as not resolved for your mono build - https://github.com/SynoCommunity/spksrc/issues/5249

**Comment by neogamaes** [comment]
You are correct. The issue appeared when I moved on DSM 7.1, was working fine on DSM 7.0.
