### ISSUE TITLE
 Error downloading. indexer: yggtorrent 

### ISSUE THREAD

**Issue by raziel95100** [Jackett/Jackett#13820]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
FlareSolverr API URL:  http://127.0.0.1:8191
version 2.2.10
docker : no
proxy: no
os: windows 10 
Jackett Version v0.20.2447
```

### Description

Bonjour Lorsque j'essaye de télécharger sur sonarr ou radarr j'ai une erreur depuis 1 semaine.
Hello, when I try to download on sonarr or radarr I have an error since 1 week.

### Logged Error Messages

```text
Error downloading. indexer: yggtorrent path: https://www6.yggtorrent.lol/engine/download_torrent?id=970838
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found 'V' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 85
```

### Screenshots

![FireShot Capture 001 - Calendar - Sonarr - localhost](https://user-images.githubusercontent.com/88598577/209859612-1d0b83bc-c9e1-4015-a7ca-2d5c001bd912.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13794
