### ISSUE TITLE
[YGGTorrent] Error downloading torrent BencodeParser failed

### ISSUE THREAD

**Issue by Kroissan** [Jackett/Jackett#13825]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.1.250:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.2447-ls87)
File /etc/issue: Ubuntu 20.04.4 LTS
Jackett variant: CoreLinuxAmdx64
OS version: Unix 6.0.0.1 (64bit OS) (64bit process)
Environment version: 6.0.12 (/app/Jackett/)
Starting Jackett v0.20.2447
```

### Description

Since last version of ygg torrent (www6 and new domain .lol) I no longer can download torrent through jackett.
It may be caused by their increased cloudflare protection. 
I had to increase flaresolver timeout to 60seconds to generate an rss feed

### Logged Error Messages

```text
Error downloading. indexer: yggtorrent path: https://www6.yggtorrent.lol/engine/download_torrent?id=974073
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found 'V' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 85

2022-12-30 18:06:12	Error	
Vous devez vous connecter pour télécharger un torrent
```

### Screenshots

![image](https://user-images.githubusercontent.com/66138267/210096613-2261e3e2-91a6-4c5f-880f-daa68a515bf7.png)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13794
https://github.com/FlareSolverr/FlareSolverr/issues/596
