### ISSUE TITLE
bulltorrent: Error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13845]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.20.2495
Linux / Docker
```

### Description

"query": "720p"
Maybe replace Hoy => Today?

### Logged Error Messages

```text
CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv7" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028620/wankitnow-23-01-06-ella-roxx-foot-fun-xxx-720p-hevc-x265-prtxvx.html">WankItNow 23 01 06 Ella Roxx Foot Fun XXX 720p HEVC x265 PRT[XvX]</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">152 MB</td>
	<td class="tul">4</td>
	<td class="tdl">4</td>
	<td class="tc">
		<a href="/user/.html"></a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h3.webp">
			<img src="https://c.0c.gay/h3.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv7" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028658/putalocura-23-01-05-tiny-spanish-xxx-720p-hevc-x265-prtxvx.html">PutaLocura 23 01 05 Tiny SPANISH XXX 720p HEVC x265 PRT[XvX]</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">397.5 MB</td>
	<td class="tul">31</td>
	<td class="tdl">13</td>
	<td class="tc">
		<a href="/user/.html"></a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h5.webp">
			<img src="https://c.0c.gay/h5.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv7" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028774/sexmex-23-01-06-natalia-dirty-old-man-fucks-young-latina-xxx-720p-hevc-x265-prtxvx.html">SexMex 23 01 06 Natalia Dirty Old Man Fucks Young Latina XXX 720p HEVC x265 PRT[XvX]</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">266.4 MB</td>
	<td class="tul">28</td>
	<td class="tdl">15</td>
	<td class="tc">
		<a href="/user/.html"></a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h5.webp">
			<img src="https://c.0c.gay/h5.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv3" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028779/ghosts-2021-s02e11-the-perfect-assistant-720p-amzn-webrip-ddp5-1-ntbtgx.html">Ghosts 2021 S02E11 The Perfect Assistant 720p AMZN WEBRip DDP5.1 x264<span style="color:#fc9c6d">-NTb[TGx]</span>
			</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">631.1 MB</td>
	<td class="tul">13</td>
	<td class="tdl">8</td>
	<td class="tc">
		<a href="/user/tgx.html">TGx</a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h4.webp">
			<img src="https://c.0c.gay/h4.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv7" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028829/playboyplus-23-01-06-katie-kushe-on-home-xxx-720p-hevc-x265-prtxvx.html">PlayboyPlus 23 01 06 Katie Kush Come On Home XXX 720p HEVC x265 PRT[XvX]</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">41.9 MB</td>
	<td class="tul">13</td>
	<td class="tdl">1</td>
	<td class="tc">
		<a href="/user/.html"></a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h4.webp">
			<img src="https://c.0c.gay/h4.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv3" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028830/the-rig-s01e05-720p-hevc-x265-megustaeztv-re.html">The Rig S01E05 720p HEVC x265<span style="color:#fc9c6d">-MeGusta[eztv]</span>
			</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">408.8 MB</td>
	<td class="tul">30</td>
	<td class="tdl">6</td>
	<td class="tc">
		<a href="/user/eztv.html">EZTV</a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h5.webp">
			<img src="https://c.0c.gay/h5.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv1" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028954/ranah-3-warna-2021-720p-webrip-yts-mx.html">Ranah 3 Warna (2021) [720p] [WEBRip]
				<span style="color:#fc9c6d">[YTS]</span>
			</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">1.2 GB</td>
	<td class="tul">41</td>
	<td class="tdl">31</td>
	<td class="tc">
		<a href="/user/yts.html">YTS</a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h5.webp">
			<img src="https://c.0c.gay/h5.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv1" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028960/godland-2022-720p-webrip-yts-mx.html">Godland (2022) [720p] [WEBRip]
				<span style="color:#fc9c6d">[YTS]</span>
			</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">1.3 GB</td>
	<td class="tul">133</td>
	<td class="tdl">131</td>
	<td class="tc">
		<a href="/user/yts.html">YTS</a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h6.webp">
			<img src="https://c.0c.gay/h6.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv1" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028962/pacifiction-2022-720p-webrip-yts-mx.html">Pacifiction (2022) [720p] [WEBRip]
				<span style="color:#fc9c6d">[YTS]</span>
			</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">1.5 GB</td>
	<td class="tul">68</td>
	<td class="tdl">83</td>
	<td class="tc">
		<a href="/user/yts.html">YTS</a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h6.webp">
			<img src="https://c.0c.gay/h6.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv7" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028969/erito-23-01-06-gf-rikos-such-a-turn-on-japanese-xxx-720p-hevc-x265-prtxvx.html">Erito 23 01 06 GF Rikos Such A Turn-On JAPANESE XXX 720p HEVC x265 PRT[XvX]</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">460.8 MB</td>
	<td class="tul">24</td>
	<td class="tdl">12</td>
	<td class="tc">
		<a href="/user/.html"></a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h5.webp">
			<img src="https://c.0c.gay/h5.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv1" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028971/ostatni-etap-1948-720p-webrip-yts-mx.html">Ostatni Etap (1948) [720p] [WEBRip]
				<span style="color:#fc9c6d">[YTS]</span>
			</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">975.4 MB</td>
	<td class="tul">34</td>
	<td class="tdl">16</td>
	<td class="tc">
		<a href="/user/yts.html">YTS</a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h5.webp">
			<img src="https://c.0c.gay/h5.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv1" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30028974/puss-in-boots-the-last-wish-2022-720p-webrip-yts-mx.html">Puss In Boots The Last Wish (2022) [720p] [WEBRip]
				<span style="color:#fc9c6d">[YTS]</span>
			</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">941.8 MB</td>
	<td class="tul">3488</td>
	<td class="tdl">3886</td>
	<td class="tc">
		<a href="/user/yts.html">YTS</a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h6.webp">
			<img src="https://c.0c.gay/h6.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv7" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30029044/purecfnm-23-01-06-angel-rae-doll-and-jess-nova-girl-scout-cookies-xxx-720p-hevc-x265-prtxvx.html">PureCFNM 23 01 06 Angel Rae Doll And Jess Nova Girl Scout Cookies XXX 720p HEVC x265 PRT[XvX]</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">35.4 MB</td>
	<td class="tul">9</td>
	<td class="tdl">2</td>
	<td class="tc">
		<a href="/user/.html"></a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h4.webp">
			<img src="https://c.0c.gay/h4.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv7" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30029057/evilangel-23-01-06-sheena-shaw-xxx-720p-hevc-x265-prtxvx.html">EvilAngel 23 01 06 Sheena Shaw XXX 720p HEVC x265 PRT[XvX]</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">87.8 MB</td>
	<td class="tul">9</td>
	<td class="tdl">7</td>
	<td class="tc">
		<a href="/user/.html"></a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h4.webp">
			<img src="https://c.0c.gay/h4.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=Hoy +01:00: DateTime parsing failed for "Hoy +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 214
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630

CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv3" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30029120/csi-vegas-s02e10-720p-web-h264-kogieztv-re.html">CSI Vegas S02E10 720p WEB h264<span style="color:#fc9c6d">-KOGi[eztv]</span>
			</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">Hoy</td>
	<td class="tc">1.2 GB</td>
	<td class="tul">78</td>
	<td class="tdl">30</td>
	<td class="tc">
		<a href="/user/eztv.html">EZTV</a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h6.webp">
			<img src="https://c.0c.gay/h6.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':
```

**Comment by garfield69** [comment]
how come I see results in English?
I'll add a replace for hoy. what do you get for yesterday?

**Comment by ngosang** [comment]
They must be using the IP or something to configure the language. Add those replaces:
* Hoy => Today
* Ayer => Yesterday

![image](https://user-images.githubusercontent.com/10577978/211082214-d56e7d55-dab1-4caf-8f9f-4b11b8e21da1.png)

**Comment by ngosang** [comment]
I'm seen this error too. +01:00 is the Spain timezone. We can just remove it

```
CardigannIndexer (bulltorrent): Error while parsing row '
<tr>
	<td class="tv1" style="padding-left:30px">
		<div style="float:left">
			<a href="/torrent/30031121/mumbai-mafia-police-vs-the-underworld-2023-720p-webrip-800mb-galaxyrgtgx.html">Mumbai Mafia Police vs the Underworld 2023 720p WEBRip 800MB x264<span style="color:#fc9c6d">-GalaxyRG[TGx]</span>
			</a>
		</div>
		<div class="tcom">
			<picture>
				<source type="image/webp" srcset="https://c.0c.gay/vt.webp">
				<img src="https://c.0c.gay/vt.png" width="16" height="16" title="Torrent Verificado">
			</picture>
		</div>
	</td>
	<td class="tc">23 hour ago</td>
	<td class="tc">799.1 MB</td>
	<td class="tul">327</td>
	<td class="tdl">198</td>
	<td class="tc">
		<a href="/user/tgx.html">TGx</a>
	</td>
	<td class="tl">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/lang/en.webp">
			<img src="https://c.0c.gay/lang/en.png" width="16" height="16" alt="English">
		</picture>
	</td>
	<td class="th">
		<picture>
			<source type="image/webp" srcset="https://c.0c.gay/h6.webp">
			<img src="https://c.0c.gay/h6.jpg" width="33" height="10" id="h">
		</picture>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=23 hour ago +01:00: DateTime parsing failed for "23 hour ago +01:00": System.Exception: TimeAgo parsing failed, unknown unit: :
   at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 82
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 124
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630
```
