### ISSUE TITLE
[hdtorrentsit] (updating) Error: 404 Not Found

### ISSUE THREAD

**Issue by paggiorowarda** [Jackett/Jackett#13926]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
01-23 16:15:06 Info Starting Jackett v0.20.2688 
01-23 16:15:07 Info Environment version: 6.0.11 (/app/Jackett/) 
01-23 16:15:07 Info OS version: Unix 5.10.0.20 (64bit OS) (64bit process) 
01-23 16:15:07 Info Jackett variant: CoreLinuxAmdx64 
01-23 16:15:07 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
01-23 16:15:07 Info Running in Docker: Yes (image build: v0.20.2688-ls89) 
01-23 16:15:07 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
01-23 16:15:07 Info App config/log directory: /config/Jackett 
01-23 16:15:07 Info Using proxy: Disabled 
01-23 16:15:07 Info Using FlareSolverr: No 
01-23 16:15:07 Info Using HTTP Client: HttpWebClient2 
```

### Description

Hi,
I was trying to add HDTorrents.it indexer but it always gives me a 404 error. A message says that 404 means that the IP is not Italian.
Indeed, the IP of my VPS is not Italian but Dutch (45.61.161.153).
I contacted the HDTorrents.it guys and they told me that they don't limit only the Italian IPs but they accept this whole list: https://check-host.net/check-report/e5b649bkfa

Also they checked the IP of the VPS and it is not blocked. How come, then?

### Logged Error Messages

```text
23/01/2023 17:16:25
01-23 16:16:25 Error Jackett.Common.ExceptionWithConfigData: Error: 404 Not Found Jackett.Common.ExceptionWithConfigData: Error: 404 Not Found
23/01/2023 17:16:25
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 538
23/01/2023 17:16:25
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 565
23/01/2023 17:16:25
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 986
23/01/2023 17:16:25
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
23/01/2023 17:16:25
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
23/01/2023 17:16:25
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

![Log error](https://user-images.githubusercontent.com/63292100/214092377-47c9ed3e-5230-4444-af90-a81d5b119994.png)
![UI error](https://user-images.githubusercontent.com/63292100/214092509-672a7298-d9e0-42ae-b7f8-6b6bf27dfee0.png)

**Comment by ilike2burnthing** [comment]
> they accept this whole list: https://check-host.net/check-report/e5b649bkfa

Half of those return a 404 error code.

Run `curl -v https://hdtorrents.xyz/` from within the Jackett container and provide the output.

**Comment by paggiorowarda** [comment]
@ilike2burnthing 
```
*   Trying 193.42.111.99:443...
* TCP_NODELAY set
* Connected to hdtorrents.xyz (193.42.111.99) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Next protocol (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=hdtorrents.xyz
*  start date: Dec 24 02:02:21 2022 GMT
*  expire date: Mar 24 02:02:20 2023 GMT
*  subjectAltName: host "hdtorrents.xyz" matched cert's "hdtorrents.xyz"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: hdtorrents.xyz
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Mon, 23 Jan 2023 16:47:32 GMT
< Content-Type: text/html; charset=WINDOWS-1251
< Content-Length: 162
< Connection: keep-alive
< Vary: Accept-Encoding
< 
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host hdtorrents.xyz left intact
```

**Comment by ilike2burnthing** [comment]
Your IP is being blocked, nothing to do with Jackett.

I suggest informing the HDTorrents.it admins, because if it's not supposed to be blocked then they have an issue on their end.

**Comment by garfield69** [comment]
You are being blocked. your curl report shows you connected to the site with a CA handshake that was accepted, and then the site returned a 404 meaning that the site refused to allow you access to the login page.

Take a look at https://check-host.net/check-report/e5b649bkfa report, and any locations that report that have a status of OK are good to go
Any of the others on that list that are showing a status of server error are being blocked, and any locations that are not on that report will be rejected too.
For example, the list shows a couple entries for Germany that are OK. I used the Hide.me VPN to select a German server and used my browser ro connect to hdtorrents.it and I was presented with the login page for the site.
But if I use other VPN server locations that are either not on that report, or are listed as server error, then the browser returns a `404 Not Found nginx`

**Comment by paggiorowarda** [comment]
They added me to the whitelist and now works.
Thank you guys
