### ISSUE TITLE
Exception in GetConfigurationForSetup (yggtorrent): FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid

### ISSUE THREAD

**Issue by DaGreenX** [Jackett/Jackett#13937]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- FlareSolverr version: 2.2.10
- Last working FlareSolverr version: 2.2.10
- Operating system: DSM 6
- Are you using Docker: [yes/no] Yes's

- Are you using a proxy or VPN: [yes/no] no
- Are you using Captcha Solver: [yes/no] yes
- If using captcha solver, which one: Harvester
- URL to test this issue:
```

### Description

Unable to configure ygg

### Logged Error Messages

```text
Exception in GetConfigurationForSetup (yggtorrent): FlareSolverrSharp.Exceptions.FlareSolverrException: The cookies provided by FlareSolverr are not valid
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 522
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 910
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 889
```

**Comment by ilike2burnthing** [comment]
_Assuming FlareSolverr and Jackett are on the same device, using the same IP:_

Update FlareSolverr to v3.0.2, disable IPv6 for Jackett and FlareSolverr, try using the `host` network (as opposed to `bridge`), and disable any proxies or VPNs.

Other than that, just wait for the DDoS attacks against YGG to stop so they can drop their Cloudflare protection.

https://github.com/FlareSolverr/FlareSolverr/issues/664
