### ISSUE TITLE
Test run failed: when building an older version

### ISSUE THREAD

**Issue by elvetemedve** [Jackett/Jackett#13967]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS version: Nixos 22.11
Jackett version: 0.20.2264
```

### The problem

Two test cases are failing when Jackett [0.20.2264](https://github.com/Jackett/Jackett/releases/tag/v0.20.2264) is build from source.

### Actual Result

```
Failed TestCardigannHtmlAsync [177 ms]
  Error Message:
     Expected: 2020
  But was:  2021
```
```
Failed ParseDateTimeGoLangTest [4 ms]
  Error Message:
     Expected: 2021-09-14 07:00:00
  But was:  2022-09-14 07:00:00
```
```
Test Run Failed.
Total tests: 125
     Passed: 123
     Failed: 2
```

### Expected result

All tests should pass, since we are building a released version.

### Steps to reproduce

Build the specific version from source. For example
`nix-shell --check -p jackett -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/tags/22.11.tar.gz`

### Notes

Most likely it has something to do with the time of the build. The two failed test cases differ in the expected year only. I think that's because the current time is referenced in the tests (e.g. [ParseDateTimeGoLangTest](https://github.com/Jackett/Jackett/blob/v0.20.2264/src/Jackett.Test/Common/Utils/DateTimeUtilTests.cs#L154)) and since we are in 2023 now, the tested calculation produces a different date.

I can see that the same problem has been spotted and fixed in the commit https://github.com/Jackett/Jackett/commit/9678329b2eb23042ecb44fc2f9fcf1cd0dce0ece. But that change is a mitigation of the issue. 

As far as I can tell, there are two options to make it work regardless of the actual time:

- Mock or substitute the current time with a static value.
- Update the expected date and time to be relative to the actual time.

### Logged Error Messages

```text
running tests
Executing dotnetCheckHook
Test run for /build/source/src/Jackett.Test/bin/Release/net6.0/Jackett.Test.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.3.1 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
NUnit Adapter 4.1.0.0: Test execution started
Running all tests in /build/source/src/Jackett.Test/bin/Release/net6.0/Jackett.Test.dll
   NUnit3TestExecutor discovered 125 of 125 NUnit test cases using Current Discovery mode, Non-Explicit run
  Passed LoadAndParseAllCardigannDefinitions [829 ms]
  Passed WebUtilityHelpers_UrlDecode_BadDecodes [< 1 ms]
  Passed WebUtilityHelpers_UrlDecode_CorrectlyDecodes [1 ms]
  Passed WebUtilityHelpers_UrlEncode_BadEncodes [< 1 ms]
  Passed WebUtilityHelpers_UrlEncode_CorrectlyEncodes [< 1 ms]
  Passed TestAddCategoryMapping [11 ms]
  Passed TestAddMultiCategoryMapping [< 1 ms]
  Passed TestConstructor [1 ms]
  Passed TestFilterResultsCategories [7 ms]
  Passed TestFilterResultsLimit [< 1 ms]
  Passed TestFixResultsMagnet [5 ms]
  Passed TestFixResultsOriginPublishDate [< 1 ms]
  Passed TestMapTorznabCapsToTrackers [< 1 ms]
  Passed TestMapTrackerCatDescToNewznab [1 ms]
  Passed TestMapTrackerCatToNewznab [< 1 ms]
  Failed TestCardigannHtmlAsync [239 ms]
  Error Message:
     Expected: 2020
  But was:  2021

  Stack Trace:
     at Jackett.Test.Common.Indexers.CardigannIndexerHtmlTests.TestCardigannHtmlAsync() in /build/source/src/Jackett.Test/Common/Indexers/CardigannIndexerHtmlTests.cs:line 57
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

  Passed TestCardigannJsonAsync [440 ms]
  Passed TestCardigannTorznabCategories [3 ms]
  Passed TestTitleParsing("Tokyo Revengers") [1 ms]
  Passed TestTitleParsing("Tokyo Revengers - 02") [< 1 ms]
  Passed TestTitleParsing("Mairimashita! Iruma-kun 2nd Season - 01") [< 1 ms]
  Passed TestTitleParsing("Seijo no Maryoku wa Bannou Desu - 02 v2 (Multi)") [< 1 ms]
  Passed TestTitleParsing("Yuukoku no Moriarty Part 2 - 01 (Multi)") [< 1 ms]
  Passed TestConstructor [1 ms]
  Passed TestConstructorWithCategories [< 1 ms]
  Passed TestXmlWithInvalidCharacters [7 ms]
  Passed TestAddCategoryMapping [< 1 ms]
  Passed TestConcat [< 1 ms]
  Passed TestConstructor [< 1 ms]
  Passed TestGetTorznabCategoryList [< 1 ms]
  Passed TestGetTorznabCategoryTree [< 1 ms]
  Passed TestGetTrackerCategories [< 1 ms]
  Passed TestMapTorznabCapsToTrackers [< 1 ms]
  Passed TestMapTrackerCatDescToNewznab [< 1 ms]
  Passed TestMapTrackerCatToNewznab [< 1 ms]
  Passed TestSupportedCategories [1 ms]
  Passed TestConstructors [< 1 ms]
  Passed TestParseBookSearchParams [< 1 ms]
  Passed TestParseCardigannSearchModes [< 1 ms]
  Passed TestParseMovieSearchParams [< 1 ms]
  Passed TestParseMusicSearchParams [< 1 ms]
  Passed TestParseTvSearchParams [< 1 ms]
  Passed TestTorznabCaps [3 ms]
  Passed TestTorznabCapsCategories [< 1 ms]
  Passed TestTorznabConcat [8 ms]
  Passed CookieDictionaryToHeaderGood [< 1 ms]
  Passed CookieDictionaryToHeaderMalformed1 [1 ms]
  Passed CookieDictionaryToHeaderMalformed2 [< 1 ms]
  Passed CookieDictionaryToHeaderNull [< 1 ms]
  Passed CookieHeaderToDictionaryDuplicateKeys [1 ms]
  Passed CookieHeaderToDictionaryGood [< 1 ms]
  Passed CookieHeaderToDictionaryMalformed [< 1 ms]
  Passed CookieHeaderToDictionaryNull [< 1 ms]
  Passed RemoveAllCookies [1 ms]
  Passed DateTimeToUnixTimestampTest [< 1 ms]
  Passed FromFuzzyTimeTest [240 ms]
  Passed FromTimeAgoTest [< 1 ms]
  Passed FromUnknownTest [168 ms]
  Failed ParseDateTimeGoLangTest [1 ms]
  Error Message:
     Expected: 2021-09-14 07:00:00
  But was:  2022-09-14 07:00:00

  Stack Trace:
     at Jackett.Test.Common.Utils.DateTimeUtilTests.ParseDateTimeGoLangTest() in /build/source/src/Jackett.Test/Common/Utils/DateTimeUtilTests.cs:line 161

  Passed UnixTimestampToDateTimeTest [< 1 ms]
  Passed TestJackettVersion [1 ms]
  Passed Ctor_EmptyID_ThrowsException [< 1 ms]
  Passed Ctor_NullID_ThrowsException [< 1 ms]
  Passed Ctor_WhitespaceID_ThrowsException [< 1 ms]
  Passed FromFilter_CaseInsensitivePrefixSource [< 1 ms]
  Passed FromFilter_EmptyArgsSource_Null [< 1 ms]
  Passed FromFilter_EmptySource_Null [< 1 ms]
  Passed FromFilter_NoArgsSource_Null [< 1 ms]
  Passed FromFilter_NullSource_Null [< 1 ms]
  Passed FromFilter_SourceWithArgs [< 1 ms]
  Passed FromFilter_WhitespaceSource_Null [< 1 ms]
  Passed FromFilter_WrongSource_Null [< 1 ms]
  Passed Ctor_EmptyFilters_ThrowsException [< 1 ms]
  Passed Ctor_NoFilters_ThrowsException [< 1 ms]
  Passed Ctor_NullFilters_ThrowsException [< 1 ms]
  Passed Ctor_WithDuplicatedPrefixFilter_ThrowsException [< 1 ms]
  Passed Ctor_WithNullFilter_ThrowsException [< 1 ms]
  Passed SingleSource [< 1 ms]
  Passed SingleSource_AndOperator [< 1 ms]
  Passed SingleSource_NotOperator [< 1 ms]
  Passed SingleSource_OperatorPrecedence [< 1 ms]
  Passed SingleSource_OrOperator [< 1 ms]
  Passed CaseInsensitiveSource_CaseInsensitiveFilter [2 ms]
  Passed LanguageWithoutRegion [< 1 ms]
  Passed EmptyStatus_ThrowsException [< 1 ms]
  Passed FailedFilter_CaseInsensitiveSource [< 1 ms]
  Passed FailingFilter [< 1 ms]
  Passed HealthyFilter [< 1 ms]
  Passed InvalidStatus_ThrowsException [< 1 ms]
  Passed NullStatus_ThrowsException [< 1 ms]
  Passed PassedFilter_CaseInsensitiveSource [< 1 ms]
  Passed UnknownFilter [< 1 ms]
  Passed UnknownFilter_CaseInsensitiveSource [< 1 ms]
  Passed CaseInsensitiveFilter [< 1 ms]
  Passed ContainsTagId [< 1 ms]
  Passed EmptyStatus_ThrowsException [< 1 ms]
  Passed FailedFilter [< 1 ms]
  Passed FailedFilter_CaseInsensitiveSource [< 1 ms]
  Passed InvalidStatus_ThrowsException [< 1 ms]
  Passed NullStatus_ThrowsException [< 1 ms]
  Passed PassedFilter [< 1 ms]
  Passed PassedFilter_CaseInsensitiveSource [< 1 ms]
  Passed CaseInsensitiveSource_CaseInsensitiveFilter [< 1 ms]
  Passed PartialType [< 1 ms]
  Passed TestInfoHashToPublicMagnet [< 1 ms]
  Passed TestMagnetToInfoHash [< 1 ms]
  Passed should_parse_quality_from_title("Chuck.S04E05.HDTV.XviD-LOL",5030) [91 ms]
  Passed should_parse_quality_from_title("Gold.Rush.S04E05.Garnets.or.Gold.REAL.REAL.PROPER.HDTV.x264-W4F",5030) [2 ms]
  Passed should_parse_quality_from_title("Chuck.S03E17.REAL.PROPER.720p.HDTV.x264-ORENJI-RP",5040) [2 ms]
  Passed should_parse_quality_from_title("Covert.Affairs.S05E09.REAL.PROPER.HDTV.x264-KILLERS",5030) [2 ms]
  Passed should_parse_quality_from_title("Mythbusters.S14E01.REAL.PROPER.720p.HDTV.x264-KILLERS",5040) [2 ms]
  Passed should_parse_quality_from_title("Orange.Is.the.New.Black.s02e06.real.proper.720p.webrip.x264-2hd",5040) [2 ms]
  Passed should_parse_quality_from_title("Top.Gear.S21E07.Super.Duper.Real.Proper.HDTV.x264-FTP",5030) [2 ms]
  Passed should_parse_quality_from_title("Top.Gear.S21E07.PROPER.HDTV.x264-RiVER-RP",5030) [2 ms]
  Passed should_parse_quality_from_title("House.S07E11.PROPER.REAL.RERIP.1080p.BluRay.x264-TENEIGHTY",5040) [2 ms]
  Passed should_parse_quality_from_title("The.Blacklist.S02E05",5000) [4 ms]
  Passed should_parse_quality_from_title("The.IT.Crowd.S01.DVD.REMUX.DD2.0.MPEG2-DTG",5030) [2 ms]
NUnit Adapter 4.1.0.0: Test execution complete
  Passed Invalid_RSS_should_parse_after_removing_invalid_chars [15 ms]
  Passed ResureRedirectIsFullyQualified_makes_redicts_fully_qualified [2 ms]
  Passed FindSubstringsBetween_NestedEntries_Succeeds [4 ms]
  Passed FindSubstringsBetween_ValidEntries_Succeeds [< 1 ms]
  Passed GetQueryStringTests [1 ms]
  Passed ToEnumerableTest [< 1 ms]
  Passed Should_be_able_to_encrypt_and_decrypt [22 ms]
  Passed Default_data_folder_is_correct [2 ms]

Test Run Failed.
Total tests: 125
     Passed: 123
     Failed: 2
 Total time: 2.6959 Seconds
Test run for /build/source/src/Jackett.Test/bin/Release/net461/Jackett.Test.dll (.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 17.3.1 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
NUnit Adapter 4.1.0.0: Test execution started
Running all tests in /build/source/src/Jackett.Test/bin/Release/net461/Jackett.Test.dll
   NUnit3TestExecutor discovered 125 of 125 NUnit test cases using Current Discovery mode, Non-Explicit run
  Passed LoadAndParseAllCardigannDefinitions [1 s]
  Passed WebUtilityHelpers_UrlDecode_BadDecodes [< 1 ms]
  Passed WebUtilityHelpers_UrlDecode_CorrectlyDecodes [69 ms]
  Passed WebUtilityHelpers_UrlEncode_BadEncodes [< 1 ms]
  Passed WebUtilityHelpers_UrlEncode_CorrectlyEncodes [1 ms]
  Passed TestAddCategoryMapping [12 ms]
  Passed TestAddMultiCategoryMapping [< 1 ms]
  Passed TestConstructor [1 ms]
  Passed TestFilterResultsCategories [9 ms]
  Passed TestFilterResultsLimit [1 ms]
  Passed TestFixResultsMagnet [7 ms]
  Passed TestFixResultsOriginPublishDate [< 1 ms]
  Passed TestMapTorznabCapsToTrackers [1 ms]
  Passed TestMapTrackerCatDescToNewznab [1 ms]
  Passed TestMapTrackerCatToNewznab [< 1 ms]
  Failed TestCardigannHtmlAsync [177 ms]
  Error Message:
     Expected: 2020
  But was:  2021

  Stack Trace:
    at Jackett.Test.Common.Indexers.CardigannIndexerHtmlTests.TestCardigannHtmlAsync () [0x001fa] in <9fab772bac7b4f5e8c089a22125ff96d>:0 
  at NUnit.Framework.Internal.TaskAwaitAdapter+GenericAdapter`1[T].BlockUntilCompleted () [0x00007] in <20ef43e650914ce09f55852fc4abbf30>:0 
  at NUnit.Framework.Internal.MessagePumpStrategy+NoMessagePumpStrategy.WaitForCompletion (NUnit.Framework.Internal.AwaitAdapter awaiter) [0x00001] in <20ef43e650914ce09f55852fc4abbf30>:0 
  at NUnit.Framework.Internal.AsyncToSyncAdapter.Await (System.Func`1[TResult] invoke) [0x00034] in <20ef43e650914ce09f55852fc4abbf30>:0 
  at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod (NUnit.Framework.Internal.TestExecutionContext context) [0x0002f] in <20ef43e650914ce09f55852fc4abbf30>:0 
  at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute (NUnit.Framework.Internal.TestExecutionContext context) [0x00001] in <20ef43e650914ce09f55852fc4abbf30>:0 
  at NUnit.Framework.Internal.Execution.SimpleWorkItem+<>c__DisplayClass4_0.<PerformWork>b__0 () [0x00011] in <20ef43e650914ce09f55852fc4abbf30>:0 
  at NUnit.Framework.Internal.ContextUtils+<>c__DisplayClass1_0`1[T].<DoIsolated>b__0 (System.Object _) [0x00000] in <20ef43e650914ce09f55852fc4abbf30>:0 

  Passed TestCardigannJsonAsync [242 ms]
  Passed TestCardigannTorznabCategories [5 ms]
  Passed TestTitleParsing("Tokyo Revengers") [3 ms]
  Passed TestTitleParsing("Tokyo Revengers - 02") [< 1 ms]
  Passed TestTitleParsing("Mairimashita! Iruma-kun 2nd Season - 01") [< 1 ms]
  Passed TestTitleParsing("Seijo no Maryoku wa Bannou Desu - 02 v2 (Multi)") [< 1 ms]
  Passed TestTitleParsing("Yuukoku no Moriarty Part 2 - 01 (Multi)") [< 1 ms]
  Passed TestConstructor [1 ms]
  Passed TestConstructorWithCategories [1 ms]
  Passed TestXmlWithInvalidCharacters [10 ms]
  Passed TestAddCategoryMapping [1 ms]
  Passed TestConcat [1 ms]
  Passed TestConstructor [< 1 ms]
  Passed TestGetTorznabCategoryList [1 ms]
  Passed TestGetTorznabCategoryTree [1 ms]
  Passed TestGetTrackerCategories [< 1 ms]
  Passed TestMapTorznabCapsToTrackers [1 ms]
  Passed TestMapTrackerCatDescToNewznab [1 ms]
  Passed TestMapTrackerCatToNewznab [< 1 ms]
  Passed TestSupportedCategories [2 ms]
  Passed TestConstructors [< 1 ms]
  Passed TestParseBookSearchParams [1 ms]
  Passed TestParseCardigannSearchModes [1 ms]
  Passed TestParseMovieSearchParams [1 ms]
  Passed TestParseMusicSearchParams [1 ms]
  Passed TestParseTvSearchParams [1 ms]
  Passed TestTorznabCaps [6 ms]
  Passed TestTorznabCapsCategories [1 ms]
  Passed TestTorznabConcat [4 ms]
  Passed CookieDictionaryToHeaderGood [< 1 ms]
  Passed CookieDictionaryToHeaderMalformed1 [1 ms]
  Passed CookieDictionaryToHeaderMalformed2 [< 1 ms]
  Passed CookieDictionaryToHeaderNull [< 1 ms]
  Passed CookieHeaderToDictionaryDuplicateKeys [2 ms]
  Passed CookieHeaderToDictionaryGood [< 1 ms]
  Passed CookieHeaderToDictionaryMalformed [< 1 ms]
  Passed CookieHeaderToDictionaryNull [< 1 ms]
  Passed RemoveAllCookies [7 ms]
  Passed DateTimeToUnixTimestampTest [< 1 ms]
  Passed FromFuzzyTimeTest [2 ms]
  Passed FromTimeAgoTest [1 ms]
  Passed FromUnknownTest [10 ms]
  Failed ParseDateTimeGoLangTest [4 ms]
  Error Message:
     Expected: 2021-09-14 07:00:00
  But was:  2022-09-14 07:00:00

  Stack Trace:
    at Jackett.Test.Common.Utils.DateTimeUtilTests.ParseDateTimeGoLangTest () [0x000ec] in <9fab772bac7b4f5e8c089a22125ff96d>:0 

  Passed UnixTimestampToDateTimeTest [< 1 ms]
  Passed TestJackettVersion [< 1 ms]
  Passed Ctor_EmptyID_ThrowsException [< 1 ms]
  Passed Ctor_NullID_ThrowsException [< 1 ms]
  Passed Ctor_WhitespaceID_ThrowsException [< 1 ms]
  Passed FromFilter_CaseInsensitivePrefixSource [< 1 ms]
  Passed FromFilter_EmptyArgsSource_Null [< 1 ms]
  Passed FromFilter_EmptySource_Null [< 1 ms]
  Passed FromFilter_NoArgsSource_Null [< 1 ms]
  Passed FromFilter_NullSource_Null [< 1 ms]
  Passed FromFilter_SourceWithArgs [< 1 ms]
  Passed FromFilter_WhitespaceSource_Null [< 1 ms]
  Passed FromFilter_WrongSource_Null [< 1 ms]
  Passed Ctor_EmptyFilters_ThrowsException [< 1 ms]
  Passed Ctor_NoFilters_ThrowsException [< 1 ms]
  Passed Ctor_NullFilters_ThrowsException [< 1 ms]
  Passed Ctor_WithDuplicatedPrefixFilter_ThrowsException [1 ms]
  Passed Ctor_WithNullFilter_ThrowsException [< 1 ms]
  Passed SingleSource [1 ms]
  Passed SingleSource_AndOperator [1 ms]
  Passed SingleSource_NotOperator [< 1 ms]
  Passed SingleSource_OperatorPrecedence [< 1 ms]
  Passed SingleSource_OrOperator [< 1 ms]
  Passed CaseInsensitiveSource_CaseInsensitiveFilter [< 1 ms]
  Passed LanguageWithoutRegion [< 1 ms]
  Passed EmptyStatus_ThrowsException [< 1 ms]
  Passed FailedFilter_CaseInsensitiveSource [< 1 ms]
  Passed FailingFilter [< 1 ms]
  Passed HealthyFilter [< 1 ms]
  Passed InvalidStatus_ThrowsException [< 1 ms]
  Passed NullStatus_ThrowsException [< 1 ms]
  Passed PassedFilter_CaseInsensitiveSource [< 1 ms]
  Passed UnknownFilter [< 1 ms]
  Passed UnknownFilter_CaseInsensitiveSource [< 1 ms]
  Passed CaseInsensitiveFilter [< 1 ms]
  Passed ContainsTagId [< 1 ms]
  Passed EmptyStatus_ThrowsException [< 1 ms]
  Passed FailedFilter [< 1 ms]
  Passed FailedFilter_CaseInsensitiveSource [< 1 ms]
  Passed InvalidStatus_ThrowsException [< 1 ms]
  Passed NullStatus_ThrowsException [< 1 ms]
  Passed PassedFilter [< 1 ms]
  Passed PassedFilter_CaseInsensitiveSource [< 1 ms]
  Passed CaseInsensitiveSource_CaseInsensitiveFilter [< 1 ms]
  Passed PartialType [< 1 ms]
  Passed TestInfoHashToPublicMagnet [1 ms]
  Passed TestMagnetToInfoHash [< 1 ms]
  Passed should_parse_quality_from_title("Chuck.S04E05.HDTV.XviD-LOL",5030) [76 ms]
  Passed should_parse_quality_from_title("Gold.Rush.S04E05.Garnets.or.Gold.REAL.REAL.PROPER.HDTV.x264-W4F",5030) [3 ms]
  Passed should_parse_quality_from_title("Chuck.S03E17.REAL.PROPER.720p.HDTV.x264-ORENJI-RP",5040) [4 ms]
  Passed should_parse_quality_from_title("Covert.Affairs.S05E09.REAL.PROPER.HDTV.x264-KILLERS",5030) [3 ms]
  Passed should_parse_quality_from_title("Mythbusters.S14E01.REAL.PROPER.720p.HDTV.x264-KILLERS",5040) [3 ms]
  Passed should_parse_quality_from_title("Orange.Is.the.New.Black.s02e06.real.proper.720p.webrip.x264-2hd",5040) [4 ms]
  Passed should_parse_quality_from_title("Top.Gear.S21E07.Super.Duper.Real.Proper.HDTV.x264-FTP",5030) [3 ms]
  Passed should_parse_quality_from_title("Top.Gear.S21E07.PROPER.HDTV.x264-RiVER-RP",5030) [3 ms]
  Passed should_parse_quality_from_title("House.S07E11.PROPER.REAL.RERIP.1080p.BluRay.x264-TENEIGHTY",5040) [4 ms]
  Passed should_parse_quality_from_title("The.Blacklist.S02E05",5000) [3 ms]
  Passed should_parse_quality_from_title("The.IT.Crowd.S01.DVD.REMUX.DD2.0.MPEG2-DTG",5030) [3 ms]
NUnit Adapter 4.1.0.0: Test execution complete
  Passed Invalid_RSS_should_parse_after_removing_invalid_chars [18 ms]
  Passed ResureRedirectIsFullyQualified_makes_redicts_fully_qualified [4 ms]
  Passed FindSubstringsBetween_NestedEntries_Succeeds [3 ms]
  Passed FindSubstringsBetween_ValidEntries_Succeeds [< 1 ms]
  Passed GetQueryStringTests [1 ms]
  Passed ToEnumerableTest [1 ms]
  Passed Should_be_able_to_encrypt_and_decrypt [57 ms]
  Passed Default_data_folder_is_correct [4 ms]

Test Run Failed.
Total tests: 125
     Passed: 123
     Failed: 2
 Total time: 3.0404 Seconds
```

**Comment by ilike2burnthing** [comment]
The `TestCardigannHtmlAsync` failure is a test for `timeago` date processing:

https://github.com/Jackett/Jackett/blob/749167ba4aaca6eb1d6e23ed665b15a7f72599b6/src/Jackett.Test/Resources/html-response1.html#L89

So the 'current time' would need to be faked and fixed.

The `ParseDateTimeGoLangTest` failure is because there is no year for the dates on the last line, so it's assumed current:

https://github.com/Jackett/Jackett/blob/9678329b2eb23042ecb44fc2f9fcf1cd0dce0ece/src/Jackett.Test/Common/Utils/DateTimeUtilTests.cs#L160-L162

A simple enough 'fix'.

However, in both cases the correct processing of the current year is another useful test, and more important than someone trying to build from months or years old code. They're simple changes to make to test files in those rare cases.

**Comment by XenGi** [comment]
These tests are still/again failing:

```
Failed TestCardigannHtmlAsync [201 ms]
  Error Message:
     Expected: 2021
  But was:  2022
```

Also this one:

```
Failed ParseDateTimeGoLangTest [< 1 ms]
  Error Message:
     Expected: 2022-09-14 07:00:00
  But was:  2023-09-14 07:00:00
```

Are their plans to fix this? As of now I can't install jackett on NixOS.

**Comment by ilike2burnthing** [comment]
See the last paragraph above, there's nothing to fix. It looks like you're trying to compile a build from last year, hence the failure. Either change the test files or use a more recent version of Jackett.

I'm not familiar with NixOS, but it looks like they've updated the version [3 times this year](https://github.com/NixOS/nixpkgs/commits/master/pkgs/servers/jackett/default.nix), so things may just need updated on your end.

**Comment by XenGi** [comment]
Ah ok. Sounds good. I'll try to reach the Nix package maintainer then.

**Comment by paradisehex** [comment]
Incase someone else ends up here from google end also needs a quick workaround this worked for me.
```sh
systemctl stop systemd-timesyncd
sudo date --set="-1 years"
nixos-rebuild --swtich
systemctl start systemd-timesyncd
```
