### ISSUE TITLE
[tjupt] (testing) Exception (tjupt): Login failed: Selector "a[href*="logout.php"]" didn't match: Parse error

### ISSUE THREAD

**Issue by jv43** [Jackett/Jackett#13988]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
02-08 21:05:41 Info Starting Jackett v0.20.3004 
02-08 21:05:41 Info Environment version: 6.0.13 (/app/Jackett/) 
02-08 21:05:41 Info OS version: Unix 5.19.17.1 (64bit OS) (64bit process) 
02-08 21:05:41 Info Jackett variant: CoreLinuxAmdx64 
02-08 21:05:41 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l 
02-08 21:05:41 Info Running in Docker: Yes (image build: v0.20.2904-ls90) 
02-08 21:05:41 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
02-08 21:05:41 Info App config/log directory: /config/Jackett 
02-08 21:05:41 Info Using proxy: Disabled 
02-08 21:05:41 Info Using FlareSolverr: http://flaresolverr:8191 
02-08 21:05:41 Info Using HTTP Client: HttpWebClient2
```

### Description

TJUPT stopped working some time today. The site seemed removed the logout link. See attached screenshot.

### Logged Error Messages

```text
02-08 21:07:43 Error Jackett.Common.IndexerException: Exception (tjupt): Login failed: Selector "a[href*="logout.php"]" didn't match Jackett.Common.IndexerException: Exception (tjupt): Login failed: Selector "a[href*="logout.php"]" didn't match
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href*="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 844
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1547
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 718
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1696
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 310
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 322
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 692
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 310
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

![Snipaste](https://user-images.githubusercontent.com/15061046/217541627-b3797069-8463-4e71-899b-75f22c5306aa.jpg)

**Comment by TerminalReed** [comment]
I encountered the same problem now. This site is available this afternoon, but failed right now

**Comment by garfield69** [comment]
for some reason the site have disabled the logout button. So I shall update the indexer login-test code to look for the userdetails link instead.

**Comment by ilike2burnthing** [comment]
[v0.20.3011](https://github.com/Jackett/Jackett/releases/v0.20.3011)
