### ISSUE TITLE
[TSC] CardigannIndexer (torrentsectorcrew): Error while parsing row '

### ISSUE THREAD

**Issue by r-netizen** [Jackett/Jackett#14028]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-02-16 00:01:04 	Info Loading Native indexers ...
2023-02-16 00:01:04 	Info Using HTTP Client: HttpWebClient2
2023-02-16 00:01:04 	Info Using FlareSolverr: No
2023-02-16 00:01:04 	Info Using proxy: Disabled
2023-02-16 00:01:04 	Info App config/log directory: /config/Jackett
2023-02-16 00:01:04 	Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-02-16 00:01:04 	Info Running in Docker: Yes (image build: v0.20.2395-ls87)
2023-02-16 00:01:04 	Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2023-02-16 00:01:04 	Info Jackett variant: CoreLinuxAmdx64
2023-02-16 00:01:04 	Info OS version: Unix 4.19.0.18 (64bit OS) (64bit process)
2023-02-16 00:01:04 	Info Environment version: 6.0.12 (/app/Jackett/)
2023-02-16 00:01:04 	Info Starting Jackett v0.20.2395
```

### Description

Hi,

when i am searching for a torrent on TSC using Jackett i dont get any results in the list. As far as i can see the Tracker definitely delivers results to Jackett (Trondheim Concert Thing).
I have set the suggested Layoutoptions (Klassisches Layout, sehr breite Darstellung and Torrents pro Seite 100)

Can you help me with this?
Regards

### Logged Error Messages

```text
2023-02-16 00:07:10 	Debug 	

Error while parsing DateTime "0 +01:00", using layout "02.01.200615:04:05 -07:00" (dd.MM.yyyyHH:mm:ss zzz): String '0 +01:00' was not recognized as a valid DateTime.

2023-02-16 00:07:10 	Error 	

CardigannIndexer (torrentsectorcrew): Error while parsing row '
<tr style="height: 45px;">
	<td style="width: 25px; text-align: center;">
		<input type="checkbox" class="checkall" name="dl[]" value="1465193">
	</td>
	<td style="width: 45px; text-align: center;">
		<a href="?search=2022&amp;incldead=1&amp;orderby=added&amp;sort=desc&amp;cat=6&amp;showsearch=1">
			<img style="vertical-align: middle;" src="pic/icons/Audio_musik.png" alt="" title="Audio|Musik">
		</a>
	</td>
	<td style="width: 40%;">
		<img style="vertical-align:middle;" src="./pic/na.gif">
		<a class="thumbnail" href="details.php?id=1465193&amp;hit=1" title="Espen_Berg-The_Trondheim_Concert-(NXN2011)-2CD-FLAC-2022-HOUND">Espen_Berg-The_Trondheim_Concert-(NXN2011)-2CD-FLAC-2022-HOUND<span>
				<img src="./bitbucket/t-1465193-1.jpg" width="150" height="112.5">
			</span>
		</a>
		<hr style="height: 1px; border: none; color: #000; background-color: #000;">
		<font color="#0d7373">[Webseed]</font>
	</td>
	<td style="width: 40px; text-align: center;">
		<a href="details.php?id=1465193&amp;hit=1&amp;filelist=1">14</a>
	</td>
	<td style="width: 40px; text-align: center;">
		<a href="details.php?id=1465193&amp;hit=1&amp;tocomm=">0</a>
	</td>
	<td style="width: 80px; text-align: center;">12.02.2023<br>23:50:14
	</td>
	<td style="width: 80px; text-align: center;">343,49 MB
	</td>
	<td style="width: 80px; text-align: center;">
		<a href="details.php?id=1465193&amp;hit=1&amp;toseeders=1">
			<font color="#ffffff">1</font>
			Seeder</a>
	</td>
	<td style="width: 80px; text-align: center;">
		<a href="details.php?id=1465193&amp;hit=1&amp;todlers=1">
			<font color="">0</font>
			Leecher</a>
	</td>
	<td style="width: 60px; text-align: center;">0-mal
	</td>
	<td style="text-align: center;">
		<b>Anonym*</b>
	</td>
	<td style="width: 100px; text-align: center;">
		<a href="download_ssl.php?torrent=1465193">DL + SSL</a>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=td:nth-child(5), value=0 +01:00: DateTime parsing failed for "0 +01:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 186
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1630
```

**Comment by garfield69** [comment]
You are using an out of date docker image of Jackett v0.20.2395
On the 5th January the TSC indexer was update for the new layout, starting with v0.20.2489

fetch the latest docker Jackett image and you should be good to go.
