### ISSUE TITLE
[hdtorrentsit] (testing) Test search in HDTorrents.it => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by gipasoft** [Jackett/Jackett#14184]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-03-23 14:59:01	Info	
Loading Native indexers ...
2023-03-23 14:59:01	Info	
Using HTTP Client: HttpWebClient2
2023-03-23 14:59:01	Info	
Using FlareSolverr: http://192.168.1.131:8191/
2023-03-23 14:59:01	Info	
Using proxy: Disabled
2023-03-23 14:59:01	Info	
App config/log directory: /config/Jackett
2023-03-23 14:59:01	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-03-23 14:59:01	Info	
Running in Docker: Yes (image build: v0.17.638-ls23)
2023-03-23 14:59:00	Info	
File /etc/issue: Ubuntu 18.04.5 LTS \n \l
2023-03-23 14:59:00	Info	
Jackett variant: CoreLinuxAmdx64
2023-03-23 14:59:00	Info	
OS version: Unix 5.10.60.0 (64bit OS) (64bit process)
2023-03-23 14:59:00	Info	
Environment version: 6.0.15 (/app/Jackett/)
2023-03-23 14:58:47	Info	
Starting Jackett v0.20.3671
```

### Description

Only try to test HdTorrents indexer

Full Log:
[log.txt](https://github.com/Jackett/Jackett/files/11051736/log.txt)

### Logged Error Messages

```text
2023-03-23 12:26:35.0650 Info Test search in HDTorrents.it => Found 0 releases [272ms] 
2023-03-23 12:26:35.0759 Error System.Exception: Test search in HDTorrents.it => Found no results while trying to browse this tracker System.Exception: Test search in HDTorrents.it => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 322
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2023-03-23 12:27:56.6192 Info Test search in HDTorrents.it => Found 0 releases [465ms] 
2023-03-23 12:27:56.6336 Error System.Exception: Test search in HDTorrents.it => Found no results while trying to browse this tracker System.Exception: Test search in HDTorrents.it => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 322
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2023-03-23 12:30:28.1210 Info Torznab search in HDTorrents.it => Found 0 releases [1537ms]
```

**Comment by garfield69** [comment]
unfortunately your enhanced log did not capture your attempt to use the indexer
please turn on the enhanced logging again and perform your hdtorrent.it indexer test one more time ;-)

**Comment by gipasoft** [comment]
> unfortunately your enhanced log did not capture your attempt to use the indexer please turn on the enhanced logging again and perform your hdtorrent.it indexer test one more time ;-)

Here the new  enhanced log :-)

[log.txt](https://github.com/Jackett/Jackett/files/11054005/log.txt)

**Comment by garfield69** [comment]
the log shows that in response to Jackett sending https://hdtorrents.xyz/browse.php with the incldead=0 (active torrents only) option, the site returned `Non abbiamo trovato nulla` 

It seems that hdtorrents.if needs the `search=` parm to be present, which we are currently omitting because during during a  TEST that key has no value.
I will update the indexer with the allowEmptyInputs statement and this should fix the problem.
The next release of Jackett is does in about 10 hours or so.

**Comment by garfield69** [comment]
v0.20.3678
