### ISSUE TITLE
[yggtorrent] (updating) Resource temporarily unavailable (www3.yggtorrent.do:443): Resource temporarily unavailable

### ISSUE THREAD

**Issue by opsder** [Jackett/Jackett#14193]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://XXX.XXX.XXX.XXX:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.3583-ls96)	
File /etc/issue: Welcome to Alpine Linux 3.17
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.15.0.67 (64bit OS) (64bit process)
Environment version: 6.0.15 (/app/Jackett/)
Starting Jackett v0.20.3678
```

### Description

Full docker installation (Jackett and Flaresolverr)

### Logged Error Messages

```text
`Exception in GetConfigurationForSetup (yggtorrent): System.Net.Http.HttpRequestException: Resource temporarily unavailable (www3.yggtorrent.do:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 535
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 915
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 892`
```

**Comment by matthieu-op** [comment]
I've tried curl -v https://www3.yggtorrent.do/ : 

Inside Jackett container
```
curl -v https://www3.yggtorrent.do/ 
* Could not resolve host: www3.yggtorrent.do
* Closing connection 0
curl: (6) Could not resolve host: www3.yggtorrent.do 
```
Inside Flaresolverr container
```
curl -v https://www3.yggtorrent.do/ 
* Could not resolve host: www3.yggtorrent.do
* Closing connection 0
curl: (6) Could not resolve host: www3.yggtorrent.do
```

Inside the server
```
curl -v https://www3.yggtorrent.do/ 
* Could not resolve host: www3.yggtorrent.do
* Closing connection 0
curl: (6) Could not resolve host: www3.yggtorrent.do
```

Same local network device
```
curl -v https://www3.yggtorrent.do/ 
*   Trying [2606:4700:3033::ac43:c1d8]:443...
* Connected to www3.yggtorrent.do (2606:4700:3033::ac43:c1d8) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
...
```
Flaresolverr log 
```
2023-03-25 10:27:45 INFO     FlareSolverr 3.0.4
2023-03-25 10:27:45 INFO     Testing web browser installation...
2023-03-25 10:27:45 INFO     Chrome / Chromium path: /usr/bin/chromium
find: ‘/app/.config/chromium/Crash Reports/pending/’: No such file or directory
2023-03-25 10:27:45 INFO     Chrome / Chromium major version: 110
2023-03-25 10:27:47 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
2023-03-25 10:27:47 INFO     Test successful
2023-03-25 10:27:47 INFO     Serving on http://0.0.0.0:8191
```
``

**Comment by garfield69** [comment]
read https://github.com/Jackett/Jackett/wiki/Troubleshooting/#resource-temporarily-unavailable and see if that helps you resolve.

**Comment by opsder** [comment]
I'm using Tailscale and have a AdGuard home on the same machine. Tailscale DNS was set on 192.168.1.XXX so the same IP can't access it. I added on Tailscale the cloudflare DNS, rebooted and now it works !
