### ISSUE TITLE
[req]: iAnon

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#14219]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: iAnon
- URL: https://ianon.app/
- Description: MacOS software tracker
- Minimum Seeding Time and Minimum Ratio (if Private): none found.
- Additional Comments: 
Engine: Gazelle
Registration: Open for some days
```

**Comment by garfield69** [comment]
v0.20.3814

**Comment by garfield69** [comment]
https://ianon.app/ajax.php?action=browse&order_by=time&order_way=desc http 500 Internal Server Error

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://ianon.app/ 
```
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://ianon.app/ cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
yeah, back online now.

**Comment by garfield69** [comment]
https://ianon.app/torrents.php no response data
admin is working on it https://ianon.app/forums.php?action=viewthread&threadid=1448

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://ianon.app/login.php > Fatal error: Uncaught mysqli_sql_exception: Connection refused

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14219#issuecomment-1913251479

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://ianon.app/ > cloudflare Bad gateway Error code 502

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
indexer API test returns
```
Error on 20250503080635 for iAnon.txtNewtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Jackett.Common.Indexers.Definitions.Abstract.GazelleTracker.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/Abstract/GazelleTracker.cs:line 278
```
Just me?

**Comment by deecypher** [comment]
Looks like this tracker is in melt-down mode, people on reddit indicate that it may be gone very soon.

**Comment by garfield69** [comment]
https://ianon.app/ > HTTP ERROR 522

**Comment by garfield69** [comment]
v0.22.2015
