### ISSUE TITLE
ebookbay: index was out of range

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#14211]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.20.3756
Docker / Linux
```

### Description

"query": "Harry Potter"

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (ebookbay): Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

Error on 20230401134809 for EBookBay.txtSystem.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1607





<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<META name="y_key" content="d5d06996712382a4">

<meta name="msvalidate.01" content="356B777E88C0CE433880B661BD3448F7" />

<meta name="verify-v1" content="gZn+loh//udZkx3Xgx5t82F4BoAj4bNIhX0sJWUV7TE=" />

<meta name="google-site-verification" content="PdaVmjkp056F0pazsEhXQGPtMgTu4UT_3kTq6LUHOkE" />

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<link rel="alternate" type="application/rss+xml" title="Subscribe to Free Ebook Torrents, Download Book Torrent on EBook Bay" href="http://ebb.la/feed/" />

<link rel="alternate" type="application/rss+xml" title="Subscribe to Free Ebook Torrents, Download Book Torrent on EBook Bay" href="http://ebb.la/feed/rss/" />

<link rel="alternate" type="application/rss+xml" title="Subscribe to Free Ebook Torrents, Download Book Torrent on EBook Bay" href=" http://ebb.la/feed/atom/" />

<link rel="stylesheet" type="text/css" media="screen" href="http://ebb.la/wp-content/themes/simple-tech-10/style.css" />

<link rel="stylesheet" type="text/css" href="http://ebb.la/images/font-awesome.min.css" />









<title>Harry Potter Ebook Download, Free Online Book Torrent Search, Page 3</title>

<meta name="description" content="Harry Potter Ebook download for free, search for free Harry Potter book torrents, Page 3." />

<meta name="keywords" content="Search for Harry Potter Ebooks torrent, free download or share yours" />
<meta name="googlebot" content="noindex">





<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://ebb.la/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://ebb.la/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 2.5" />


<!-- Start Of Script Generated By WP-PageNavi 2.20 -->
<link rel="stylesheet" href="http://ebb.la/wp-content/plugins/pagenavi/pagenavi-css.css" type="text/css" media="screen" />
<!-- End Of Script Generated By WP-PageNavi 2.20 -->

<!-- Protected by WP-SpamFree v2.1.1.2 :: JS BEGIN -->
<script type="text/javascript" src="http://ebb.la/wp-content/plugins/wp-spamfree/js/wpsfv2-js.php"></script> 
<!-- Protected by WP-SpamFree v2.1.1.2 :: JS END -->


 <link rel="shortcut icon" href="http://ebb.la/images/favicon.ico" />
</head>

<body>
<div id="headerimg">

<div id="nav" style="width:100%;">

    <div class="nav" style="clear:both;">

        <div class="left" style="float:right;">

        <ul>

            <li class="page_item page-item-13"><a href="http://ebb.la/contact/" title="Contact">Contact</a></li>
<li class="page_item page-item-2071"><a href="http://ebb.la/dmca/" title="DMCA">DMCA</a></li>
            
            <li><a href="http://ebb.la/forum/" title="EBook Bay forum">Forum</a></li>

            <li><a href="http://ebb.la/forum/index.php/board,8.0.html" title="Request Ebooks">Request</a></li>

            <!--<li><a href="http://ebb.la/member/" title="Share your Ebooks">Share</a></li>-->

            <li><a href="http://ebb.la/member/login.php" title="Share your Ebooks">Login</a></li>

            		</ul>

	</div>


        <div class="header" style="float:left;">

        	<h1 style="float:left;width:280px;"><a href="http://ebb.la/">EBook Bay <span class="dotto">(EBB)</span></a></h1>
            <div style="margin-top:40px;float:left;width:250px;">
            	
				<a href="https://twitter.com/share" class="twitter-share-button" data-count="none" data-text=" EBook Downloads" data-hashtags="ebook,"></a>
				<div style="width:61px;height:20px;overflow:hidden;display:inline-block;" class="fb-share-button" data-href="http://ebb.la/page/3/?s=Harry%20Potter" data-type="button"></div>
            </div>

        </div>

    </div>

</div>

<div id="header" style="clear:both;">

<div class="description"><h2 style="font-size:11px;font-weight:normal;">Download Ebooks for Free or Share Your Ebook, High Quality and Fast!</h2></div>

</div>

</div>

<div id="wrap">
	<div id="content">



	


		<h3 class="pagetitle">Search Results for Harry Potter</h3>



<div style="text-align:center;margin:0 0 10px 0;">



</div>	



		




	<div class="poststuff"><div class="postname"><a href="http://ebb.la/harry-potter-en-de-steen-der-wijzen-jk-rowling/">Harry Potter en de steen der wijzen - J.K. Rowling</a></div>

		<span class="writer">E book under: 

		Fantasy Ebook&nbsp; 
        <br />Tags: 

        en de steen der wijzen&nbsp Harry Potter&nbsp 
 		</span>   

	</div>

<div class="entry">

	<div class="center"><p class="center">Shared by:<a href="/member/users/index.php?&amp;mode=userinfo&amp;username=jason98">jason98</a></p><p class="center"><a href="||url||"><a href="/harry-potter-en-de-steen-der-wijzen-jk-rowling/"><img src="http://ecx.images-amazon.com/images/I/31z1rtBTfpL._SL500_AA300_.jpg" alt="Harry Potter en de steen der wijzen - J.K. Rowling" /></a></a></p></div><p class="center"></p><p style='text-align:center;'>Seeds: <span style='color:#070;'>11</span><br />Peers: <span style='color:#a00;'>8</span><br />Completed Downloads: <span style='color:#00f;'>127</span><br />File Size: 608.77 KBs<br /></p><p class="post-meta"><a class="detail" href="http://ebb.la/harry-potter-en-de-steen-der-wijzen-jk-rowling/" class="more-link">Ebook Details</a><a class="download" href="/download-now.php?f=96J_K_Rowling_Harry_Potter_en_de_steen_der_wijzen_NL_Ebook_epub__DMT______..torrent" rel="nofollow">Download Files Now</a><br />
<span style="clear:both;display:none;"><img src="http://ebb.la/wp-content/plugins/wp-spamfree/img/wpsf-img.php" width="0" height="0" alt="" style="border-style:none;width:0px;height:0px;display:none;" /></span>			


</div>	

<div class="post-divider">

</div>

<br />



		




	<div class="poststuff"><div class="postname"><a href="http://ebb.la/4000-kindel-books-tons-of-them-actionadventure-etc-hunger-games-harry-potter-various/">4000+ Kindel Books tons of them action,adventure etc. hunger games, harry potter - various</a></div>

		<span class="writer">E book under: 

		Novel&nbsp; 
        <br />Tags: 

        Before They Are Hanged&nbsp harry potter etc&nbsp 
 		</span>   

	</div>

<div class="entry">
```

**Comment by garfield69** [comment]
this is an issue at the web site. 
if you navigate to http://ebb.la/page/3/?s=harry+potter
you will find an entry with the title `
4000+ Kindel Books tons of them action,adventure etc. hunger games, harry potter - various`
which is missing the second section describing poster, seeds, leeches, links etc

the yaml indexer is expecting each torrent to be made of two rows, using the `after 1` statement 
and if it is missing cardigann will end up one row short and abends.

I am not sure this can be handled in cardigann, as once a row is missing, all the torrents following will be built out of out-of-sync rows, miss-matching the torrent2 row1 with the torrent3 row2 and so forth.
Regardless, this is one for the c# devs to figure out its beyond my pay grade.
