### ISSUE TITLE
[springsunday] (updating) Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by Siriussee** [Jackett/Jackett#14228]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-04-06 21:54:26	Info	Loading Native indexers ...
2023-04-06 21:54:26	Info	Using HTTP Client: HttpWebClient2
2023-04-06 21:54:26	Info	Using FlareSolverr: http://192.168.1.160:8191
2023-04-06 21:54:26	Info	Using proxy: Disabled
2023-04-06 21:54:26	Info	App config/log directory: /config/Jackett
2023-04-06 21:54:26	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-04-06 21:54:26	Info	Running in Docker: Yes (image build: v0.20.3814-ls101)
2023-04-06 21:54:26	Info	File /etc/issue: Welcome to Alpine Linux 3.17
2023-04-06 21:54:26	Info	Jackett variant: CoreLinuxMuslAmdx64
2023-04-06 21:54:26	Info	OS version: Unix 5.19.9.0 (64bit OS) (64bit process)
2023-04-06 21:54:26	Info	Environment version: 6.0.15 (/app/Jackett/)
2023-04-06 21:54:24	Info	Starting Jackett v0.20.3814
```

### Description

Add indexer with cookie, then got this error msg.

### Logged Error Messages

```text
2023-04-06 21:57:04.9125 Error Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 845
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 992
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
Since none of the current team have an account at springsunday,  we are going to need you to turn on **enhanced logging** so that we can capture what springsunday is returning when you try to login with the indexer.
I am guessing that the logout link which the indexer is using to test that the login was completed successfully, has changed.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket on how to provide the enhanced log.
Thanks

**Comment by garfield69** [comment]
Hold the phone. the springsunday indexer is using the cookie method, so it's entirely likely that your cookie is not working.
Please read https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work first, especially the notes section, to make sure that the issue is not simply that your cookie is nbg.
Thanks.

**Comment by Siriussee** [comment]
I am pretty sure I went for the correct cookie and I read the doc again and tried adding it again. No surprise, same issue.

I am speculating the issue is due to some DOM change on their main page. As I inspect, the log-out element comes with an auth key now:
```
<a href="logout.php?auth=[redacted]" onclick="return confirm('你确定要退出吗？')">退出</a>
```
and so the `Selector "a[href="logout.php"]"` no longer works. I can attach a front-page HTML dump for a better diagnosis.

**Comment by Siriussee** [comment]
[ssd.html.txt](https://github.com/Jackett/Jackett/files/11176363/ssd.html.txt)

**Comment by garfield69** [comment]
Excellent.  I will use that html to bring the indexer up to date.

**Comment by garfield69** [comment]
one more thing, could you click on this link https://springsunday.net/aboutnexus.php and paste here the nexusphp version and release date please. thanks.

**Comment by Siriussee** [comment]
Here you go:

nexusphp version | NexusPHP
nexusphp version | Standard v1.5 Beta 4
release date | 2010-09-19

**Comment by garfield69** [comment]
Done.
The update will be included in the next release of Jackett.
Unfortunately we just missed the release window for today, so the next release is due in about 23 hours.
Any further follow up issues just reopen this ticket.

**Comment by garfield69** [comment]
v0.20.3840
