### ISSUE TITLE
[bakabt] Error while updating Baka.bt "(updating) 2,942"

### ISSUE THREAD

**Issue by alessandrapereyra** [Jackett/Jackett#14263]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.20.3939
Environment version: 6.0.16 (/home/XXXXX/Jackett/)
OS version: Unix 5.10.0.21 (64bit OS) (64bit process)
Jackett variant: CoreLinuxAmdx64
File /etc/issue: Debian GNU/Linux 11 \n \l
Running in Docker: No
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /home/XXXXX/.config/Jackett
Using proxy: Disabled
Using FlareSolverr: No
Using HTTP Client: HttpWebClient2
Loading Native indexers ...
```

### Description

After noticing that this indexer was failing from another app, I logged into Jackett to test it, getting a connection issue.

I changed my password in BakaBT just in case, but I couldn't manage to update it here either, getting the error message posted above (and in the screenshot below).

I also tried restarting Jackett, but that doesn't seem to help. Something I noticed that might not be related, and perhaps a feature and not a bug, was that after a failing attempt, when I refreshed Jackett, BakaBT was no longer listed among other indexers. I could, however, access it by trying to add it manually and editing the settings. 

### Logged Error Messages

```text
2023-04-20 02:52:54.2263 Error Jackett.Common.ExceptionWithConfigData: 2,923 Jackett.Common.ExceptionWithConfigData: 2,923
   at Jackett.Common.Indexers.BakaBT.<>c__DisplayClass32_0.<DoLogin>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BakaBT.cs:line 133
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 160
   at Jackett.Common.Indexers.BakaBT.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BakaBT.cs:line 127
   at Jackett.Common.Indexers.BakaBT.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BakaBT.cs:line 101
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

<img width="785" alt="image" src="https://user-images.githubusercontent.com/24547664/233246192-ae0e0209-4fcf-49d7-9a6c-e0129bcdcd46.png">

**Comment by ilike2burnthing** [comment]
Delete the indexer, restart Jackett, re-add the indexer, manually entering your credentials even if they're auto-filled.

Failing that, follow these troubleshooting steps - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#login-failed-selector

If those don't work, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

When logging into the site in browser, are you presented with a captcha?

**Comment by alessandrapereyra** [comment]
Thanks!

Some updates are below:

> Delete the indexer, restart Jackett, re-add the indexer, manually entering your credentials even if they're auto-filled.

Done, but same issue, sadly.

> Failing that, follow these troubleshooting steps - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#login-failed-selector

I followed the instructions, but it didn't seem to make any difference. I tested curl-ing the website from the server Jackett is installed, and it worked (of course, sending me the logged-out homepage). That led me to check the HTML on the log, and based on it, it seems like it is able to start a session as it is the logged-in view, so not quite sure what'd be the issue.

> 
> If those don't work, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

I apologize, I thought I had done that already, but it seems like the extended logging checkbox was unselected after restarting the server (which I tried, just in case). I updated the PR description with the latest one; I hope this is the right one now 🙏🏻 .

> When logging into the site in browser, are you presented with a captcha?

None.

Thanks for your support!

**Comment by ilike2burnthing** [comment]
Thanks, I've removed the URL of your server, some cookies, and your password, as well as the edit history. You may want to reset your password just to be safe.

Looks like for whatever reason they've used `<b class="error">2,897</b>` for their leechers count, which is then screwing with our error detection.

I don't have an account, but I'll put together a PR shortly and then ask you to test the build.

**Comment by ilike2burnthing** [comment]
https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/8757/artifacts?artifactName=drop&api-version=7.0&%24format=zip

Let me know if the above build works for you.

**Comment by garfield69** [comment]
v0.20.3968
