### ISSUE TITLE
Updater Fails and Breaks Service

### ISSUE THREAD

**Issue by dillingerdisco7** [Jackett/Jackett#14271]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 6.0.16 (C:\ProgramData\Jackett\)
```

### Description

Any time a new update is released, auto update crashes something, disables the background service and I am unable to start it or open the WebUI. I have to dl the new version, uninstall the old, restart, reinstall, restart, run Jackett app as admin, and it works. It does not fix itself or auto update.

If I try to open the auto updater app, it tell me theres and error with the path, but not what there error is.

### Logged Error Messages

```text
Unfortunately I cannot access the logs after the crash.
```

**Comment by ilike2burnthing** [comment]
Working ok here. Please follow these steps:

- uninstall Jackett
- open `C:\ProgramData`
- rename the folder `Jackett` to `Jackett.bak`
- download this installer from a couple of days ago - https://github.com/Jackett/Jackett/releases/download/v0.20.3971/Jackett.Installer.Windows.exe
- install with default settings
- open webUI and click the yellow `Check for updates` button

Does that still fail for you?

**Comment by dillingerdisco7** [comment]
Yeah seemed to do the same thing. However this time I have the UI still
open but cant do anything on it. Says 'request to Jackett Server failed"
when I clock on the logs. Same thing though: Start Background Service in
the tray is lit up, but clicking it does nothing. Start webUI is greyed out.

However, it did spit out an updater log, Ive attached that here.



Message ID: ***@***.***>
>
>

2023-04-24 16:58:05.7453 Info Jackett Updater v0.20.3971 
2023-04-24 16:58:05.7842 Info Options "" 
2023-04-24 16:58:05.7842 Info Jackett variant: CoreWindows 
2023-04-24 16:58:05.7842 Info Pausing for 3 seconds to give Jackett & tray time to shutdown 
2023-04-24 16:58:08.8752 Error JackettUpdater 0.20.3971
Copyright (C) 2023 JackettUpdater

ERROR(S):
  Required option 'p, Path' is missing.

  -p, --Path     Required. Install location

  -t, --Type     Install type

  -a, --Args     Launch arguments

  --NoRestart    Don't restart after update

  --KillPids     PIDs which will be killed before (Windows) or after (Unix) the
                 update

  --StartTray    Indicates that the updater should start the tray icon

  --help         Display this help screen.

  --version      Display version information.

 
2023-04-24 16:58:08.8874 Error Failed to process update arguments! 
2023-04-24 16:58:08.8874 Error System.Linq.Enumerable+<ExceptIterator>d__92`1[CommandLine.Error] 
2023-04-24 16:58:22.5638 Info Jackett Updater v0.20.3971 
2023-04-24 16:58:22.5975 Info Options "" 
2023-04-24 16:58:22.5975 Info Jackett variant: CoreWindows 
2023-04-24 16:58:22.5975 Info Pausing for 3 seconds to give Jackett & tray time to shutdown 
2023-04-24 16:58:25.6966 Error JackettUpdater 0.20.3971
Copyright (C) 2023 JackettUpdater

ERROR(S):
  Required option 'p, Path' is missing.

  -p, --Path     Required. Install location

  -t, --Type     Install type

  -a, --Args     Launch arguments

  --NoRestart    Don't restart after update

  --KillPids     PIDs which will be killed before (Windows) or after (Unix) the
                 update

  --StartTray    Indicates that the updater should start the tray icon

  --help         Display this help screen.

  --version      Display version information.

 
2023-04-24 16:58:25.7085 Error Failed to process update arguments! 
2023-04-24 16:58:25.7085 Error System.Linq.Enumerable+<ExceptIterator>d__92`1[CommandLine.Error] 
2023-04-24 16:58:30.4527 Info Jackett Updater v0.20.3985 
2023-04-24 16:58:30.4941 Info Options "--Path" "C:\ProgramData\Jackett" "--Type" "WindowsService" "--Args" " " "--KillPids" "16524" 
2023-04-24 16:58:30.5024 Info Jackett variant: CoreWindows 
2023-04-24 16:58:30.5024 Info Pausing for 3 seconds to give Jackett & tray time to shutdown 
2023-04-24 16:58:33.7117 Info Process 16524 is already dead 
2023-04-24 16:58:33.7117 Info Finding files in: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\ 
2023-04-24 16:58:33.7178 Info 995 update files found 
2023-04-24 16:58:33.7178 Info Attempting to copy Accessibility.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\Accessibility.dll to destination: C:\ProgramData\Jackett\Accessibility.dll 
2023-04-24 16:58:33.7178 Info Copied Accessibility.dll 
2023-04-24 16:58:33.7178 Info Attempting to copy AngleSharp.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\AngleSharp.dll to destination: C:\ProgramData\Jackett\AngleSharp.dll 
2023-04-24 16:58:33.7319 Info Copied AngleSharp.dll 
2023-04-24 16:58:33.7319 Info Attempting to copy AngleSharp.Xml.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\AngleSharp.Xml.dll to destination: C:\ProgramData\Jackett\AngleSharp.Xml.dll 
2023-04-24 16:58:33.7319 Info Copied AngleSharp.Xml.dll 
2023-04-24 16:58:33.7319 Info Attempting to copy api-ms-win-core-console-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-console-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-console-l1-1-0.dll 
2023-04-24 16:58:33.7319 Info Copied api-ms-win-core-console-l1-1-0.dll 
2023-04-24 16:58:33.7319 Info Attempting to copy api-ms-win-core-console-l1-2-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-console-l1-2-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-console-l1-2-0.dll 
2023-04-24 16:58:33.7319 Info Copied api-ms-win-core-console-l1-2-0.dll 
2023-04-24 16:58:33.7472 Info Attempting to copy api-ms-win-core-datetime-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-datetime-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-datetime-l1-1-0.dll 
2023-04-24 16:58:33.7749 Info Copied api-ms-win-core-datetime-l1-1-0.dll 
2023-04-24 16:58:33.7749 Info Attempting to copy api-ms-win-core-debug-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-debug-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-debug-l1-1-0.dll 
2023-04-24 16:58:33.7807 Info Copied api-ms-win-core-debug-l1-1-0.dll 
2023-04-24 16:58:33.7807 Info Attempting to copy api-ms-win-core-errorhandling-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-errorhandling-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-errorhandling-l1-1-0.dll 
2023-04-24 16:58:33.7807 Info Copied api-ms-win-core-errorhandling-l1-1-0.dll 
2023-04-24 16:58:33.7807 Info Attempting to copy api-ms-win-core-fibers-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-fibers-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-fibers-l1-1-0.dll 
2023-04-24 16:58:33.7807 Info Copied api-ms-win-core-fibers-l1-1-0.dll 
2023-04-24 16:58:33.7807 Info Attempting to copy api-ms-win-core-file-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-file-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-file-l1-1-0.dll 
2023-04-24 16:58:33.7943 Info Copied api-ms-win-core-file-l1-1-0.dll 
2023-04-24 16:58:33.7943 Info Attempting to copy api-ms-win-core-file-l1-2-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-file-l1-2-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-file-l1-2-0.dll 
2023-04-24 16:58:33.7943 Info Copied api-ms-win-core-file-l1-2-0.dll 
2023-04-24 16:58:33.7943 Info Attempting to copy api-ms-win-core-file-l2-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-file-l2-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-file-l2-1-0.dll 
2023-04-24 16:58:33.7943 Info Copied api-ms-win-core-file-l2-1-0.dll 
2023-04-24 16:58:33.7943 Info Attempting to copy api-ms-win-core-handle-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-handle-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-handle-l1-1-0.dll 
2023-04-24 16:58:33.7943 Info Copied api-ms-win-core-handle-l1-1-0.dll 
2023-04-24 16:58:33.7943 Info Attempting to copy api-ms-win-core-heap-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-heap-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-heap-l1-1-0.dll 
2023-04-24 16:58:33.8128 Info Copied api-ms-win-core-heap-l1-1-0.dll 
2023-04-24 16:58:33.8128 Info Attempting to copy api-ms-win-core-interlocked-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-interlocked-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-interlocked-l1-1-0.dll 
2023-04-24 16:58:33.8128 Info Copied api-ms-win-core-interlocked-l1-1-0.dll 
2023-04-24 16:58:33.8128 Info Attempting to copy api-ms-win-core-libraryloader-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-libraryloader-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-libraryloader-l1-1-0.dll 
2023-04-24 16:58:33.8410 Info Copied api-ms-win-core-libraryloader-l1-1-0.dll 
2023-04-24 16:58:33.8410 Info Attempting to copy api-ms-win-core-localization-l1-2-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-localization-l1-2-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-localization-l1-2-0.dll 
2023-04-24 16:58:33.8410 Info Copied api-ms-win-core-localization-l1-2-0.dll 
2023-04-24 16:58:33.8410 Info Attempting to copy api-ms-win-core-memory-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-memory-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-memory-l1-1-0.dll 
2023-04-24 16:58:33.8741 Info Copied api-ms-win-core-memory-l1-1-0.dll 
2023-04-24 16:58:33.8741 Info Attempting to copy api-ms-win-core-namedpipe-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-namedpipe-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-namedpipe-l1-1-0.dll 
2023-04-24 16:58:33.8741 Info Copied api-ms-win-core-namedpipe-l1-1-0.dll 
2023-04-24 16:58:33.8741 Info Attempting to copy api-ms-win-core-processenvironment-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-processenvironment-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-processenvironment-l1-1-0.dll 
2023-04-24 16:58:33.8741 Info Copied api-ms-win-core-processenvironment-l1-1-0.dll 
2023-04-24 16:58:33.8741 Info Attempting to copy api-ms-win-core-processthreads-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-processthreads-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-processthreads-l1-1-0.dll 
2023-04-24 16:58:33.9045 Info Copied api-ms-win-core-processthreads-l1-1-0.dll 
2023-04-24 16:58:33.9045 Info Attempting to copy api-ms-win-core-processthreads-l1-1-1.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-processthreads-l1-1-1.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-processthreads-l1-1-1.dll 
2023-04-24 16:58:33.9212 Info Copied api-ms-win-core-processthreads-l1-1-1.dll 
2023-04-24 16:58:33.9212 Info Attempting to copy api-ms-win-core-profile-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-profile-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-profile-l1-1-0.dll 
2023-04-24 16:58:33.9212 Info Copied api-ms-win-core-profile-l1-1-0.dll 
2023-04-24 16:58:33.9212 Info Attempting to copy api-ms-win-core-rtlsupport-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-rtlsupport-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-rtlsupport-l1-1-0.dll 
2023-04-24 16:58:33.9405 Info Copied api-ms-win-core-rtlsupport-l1-1-0.dll 
2023-04-24 16:58:33.9405 Info Attempting to copy api-ms-win-core-string-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-string-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-string-l1-1-0.dll 
2023-04-24 16:58:33.9405 Info Copied api-ms-win-core-string-l1-1-0.dll 
2023-04-24 16:58:33.9405 Info Attempting to copy api-ms-win-core-synch-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-synch-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-synch-l1-1-0.dll 
2023-04-24 16:58:33.9405 Info Copied api-ms-win-core-synch-l1-1-0.dll 
2023-04-24 16:58:33.9405 Info Attempting to copy api-ms-win-core-synch-l1-2-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-synch-l1-2-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-synch-l1-2-0.dll 
2023-04-24 16:58:33.9530 Info Copied api-ms-win-core-synch-l1-2-0.dll 
2023-04-24 16:58:33.9530 Info Attempting to copy api-ms-win-core-sysinfo-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-sysinfo-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-sysinfo-l1-1-0.dll 
2023-04-24 16:58:33.9530 Info Copied api-ms-win-core-sysinfo-l1-1-0.dll 
2023-04-24 16:58:33.9530 Info Attempting to copy api-ms-win-core-timezone-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-timezone-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-timezone-l1-1-0.dll 
2023-04-24 16:58:33.9530 Info Copied api-ms-win-core-timezone-l1-1-0.dll 
2023-04-24 16:58:33.9530 Info Attempting to copy api-ms-win-core-util-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-core-util-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-core-util-l1-1-0.dll 
2023-04-24 16:58:33.9530 Info Copied api-ms-win-core-util-l1-1-0.dll 
2023-04-24 16:58:33.9659 Info Attempting to copy API-MS-Win-core-xstate-l2-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\API-MS-Win-core-xstate-l2-1-0.dll to destination: C:\ProgramData\Jackett\API-MS-Win-core-xstate-l2-1-0.dll 
2023-04-24 16:58:33.9659 Info Copied API-MS-Win-core-xstate-l2-1-0.dll 
2023-04-24 16:58:33.9659 Info Attempting to copy api-ms-win-crt-conio-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-conio-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-conio-l1-1-0.dll 
2023-04-24 16:58:33.9659 Info Copied api-ms-win-crt-conio-l1-1-0.dll 
2023-04-24 16:58:33.9659 Info Attempting to copy api-ms-win-crt-convert-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-convert-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-convert-l1-1-0.dll 
2023-04-24 16:58:33.9659 Info Copied api-ms-win-crt-convert-l1-1-0.dll 
2023-04-24 16:58:33.9659 Info Attempting to copy api-ms-win-crt-environment-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-environment-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-environment-l1-1-0.dll 
2023-04-24 16:58:33.9835 Info Copied api-ms-win-crt-environment-l1-1-0.dll 
2023-04-24 16:58:33.9835 Info Attempting to copy api-ms-win-crt-filesystem-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-filesystem-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-filesystem-l1-1-0.dll 
2023-04-24 16:58:33.9835 Info Copied api-ms-win-crt-filesystem-l1-1-0.dll 
2023-04-24 16:58:33.9835 Info Attempting to copy api-ms-win-crt-heap-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-heap-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-heap-l1-1-0.dll 
2023-04-24 16:58:33.9835 Info Copied api-ms-win-crt-heap-l1-1-0.dll 
2023-04-24 16:58:33.9835 Info Attempting to copy api-ms-win-crt-locale-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-locale-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-locale-l1-1-0.dll 
2023-04-24 16:58:33.9972 Info Copied api-ms-win-crt-locale-l1-1-0.dll 
2023-04-24 16:58:33.9972 Info Attempting to copy api-ms-win-crt-math-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-math-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-math-l1-1-0.dll 
2023-04-24 16:58:34.0319 Info Copied api-ms-win-crt-math-l1-1-0.dll 
2023-04-24 16:58:34.0319 Info Attempting to copy api-ms-win-crt-multibyte-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-multibyte-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-multibyte-l1-1-0.dll 
2023-04-24 16:58:34.0499 Info Copied api-ms-win-crt-multibyte-l1-1-0.dll 
2023-04-24 16:58:34.0499 Info Attempting to copy api-ms-win-crt-private-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-private-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-private-l1-1-0.dll 
2023-04-24 16:58:34.0499 Info Copied api-ms-win-crt-private-l1-1-0.dll 
2023-04-24 16:58:34.0499 Info Attempting to copy api-ms-win-crt-process-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-process-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-process-l1-1-0.dll 
2023-04-24 16:58:34.0597 Info Copied api-ms-win-crt-process-l1-1-0.dll 
2023-04-24 16:58:34.0597 Info Attempting to copy api-ms-win-crt-runtime-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-runtime-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-runtime-l1-1-0.dll 
2023-04-24 16:58:34.0597 Info Copied api-ms-win-crt-runtime-l1-1-0.dll 
2023-04-24 16:58:34.0597 Info Attempting to copy api-ms-win-crt-stdio-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-stdio-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-stdio-l1-1-0.dll 
2023-04-24 16:58:34.0597 Info Copied api-ms-win-crt-stdio-l1-1-0.dll 
2023-04-24 16:58:34.0597 Info Attempting to copy api-ms-win-crt-string-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-string-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-string-l1-1-0.dll 
2023-04-24 16:58:34.1101 Info Copied api-ms-win-crt-string-l1-1-0.dll 
2023-04-24 16:58:34.1101 Info Attempting to copy api-ms-win-crt-time-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-time-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-time-l1-1-0.dll 
2023-04-24 16:58:34.1101 Info Copied api-ms-win-crt-time-l1-1-0.dll 
2023-04-24 16:58:34.1101 Info Attempting to copy api-ms-win-crt-utility-l1-1-0.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\api-ms-win-crt-utility-l1-1-0.dll to destination: C:\ProgramData\Jackett\api-ms-win-crt-utility-l1-1-0.dll 
2023-04-24 16:58:34.1101 Info Copied api-ms-win-crt-utility-l1-1-0.dll 
2023-04-24 16:58:34.1225 Info Attempting to copy aspnetcorev2_inprocess.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\aspnetcorev2_inprocess.dll to destination: C:\ProgramData\Jackett\aspnetcorev2_inprocess.dll 
2023-04-24 16:58:34.1225 Info Copied aspnetcorev2_inprocess.dll 
2023-04-24 16:58:34.1225 Info Attempting to copy Autofac.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\Autofac.dll to destination: C:\ProgramData\Jackett\Autofac.dll 
2023-04-24 16:58:34.1225 Info Copied Autofac.dll 
2023-04-24 16:58:34.1225 Info Attempting to copy Autofac.Extensions.DependencyInjection.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\Autofac.Extensions.DependencyInjection.dll to destination: C:\ProgramData\Jackett\Autofac.Extensions.DependencyInjection.dll 
2023-04-24 16:58:34.1410 Info Copied Autofac.Extensions.DependencyInjection.dll 
2023-04-24 16:58:34.1410 Info Attempting to copy AutoMapper.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\AutoMapper.dll to destination: C:\ProgramData\Jackett\AutoMapper.dll 
2023-04-24 16:58:34.1410 Info Copied AutoMapper.dll 
2023-04-24 16:58:34.1410 Info Attempting to copy BencodeNET.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\BencodeNET.dll to destination: C:\ProgramData\Jackett\BencodeNET.dll 
2023-04-24 16:58:34.1533 Info Copied BencodeNET.dll 
2023-04-24 16:58:34.1533 Info Attempting to copy clretwrc.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\clretwrc.dll to destination: C:\ProgramData\Jackett\clretwrc.dll 
2023-04-24 16:58:34.1822 Info Copied clretwrc.dll 
2023-04-24 16:58:34.1822 Info Attempting to copy clrjit.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\clrjit.dll to destination: C:\ProgramData\Jackett\clrjit.dll 
2023-04-24 16:58:34.1851 Error System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jackett\clrjit.dll' because it is being used by another process. System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jackett\clrjit.dll' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Jackett.Updater.Program.CopyUpdateFile(String jackettDestinationDirectory, String fullSourceFilePath, String updateSourceDirectory, Boolean previousAttemptFailed) in D:\a\1\s\src\Jackett.Updater\Program.cs:line 811
2023-04-24 16:58:34.2445 Info Attempting to copy clrjit.dll from source: C:\WINDOWS\TEMP\JackettUpdate-v0.20.3985-638179522966411821\Jackett\clrjit.dll to destination: C:\ProgramData\Jackett\clrjit.dll 
2023-04-24 16:58:34.2445 Info The first attempt copying file: clrjit.dllfailed. Retrying and will delete old file first 
2023-04-24 16:58:34.2445 Info C:\ProgramData\Jackett\clrjit.dll was found

**Comment by ilike2burnthing** [comment]
As a test, disable and shutdown your antivirus and any other security software, then run the update again, see if it's successful.

**Comment by dillingerdisco7** [comment]
Huh, that seems to have worked with Avast disabled.  Id imagine starting to play with exceptions in that directory would be the next step?

**Comment by garfield69** [comment]
Yes. Check your avast quarantine for jackett modules. If present then set up an exception.

**Comment by dillingerdisco7** [comment]
Yep, sure enough JackettConsole.exe in quarantine about every 4 days. Weird because I never got notification from Avast like I do with others it grabs.

Either way, exception has been set up. Thanks!

**Comment by garfield69** [comment]
check your avast settings to ensure you are not running it in silent mode.
