### ISSUE TITLE
[btdigg] (testing) Test search in BTDigg => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by colemar** [Jackett/Jackett#14275]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.0.0.1:8191
Using proxy: Disabled
App config/log directory: /home/jackett/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 22.04.2 LTS
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.0.69 (64bit OS) (64bit process)
Environment version: 6.0.16 (/home/jackett/Jackett/)
Starting Jackett v0.20.3996
```

### Description

- Click on [BTDigg...**Test**] ![image](https://user-images.githubusercontent.com/3066000/234707617-4700194f-6802-4d90-8d2c-b3a18a423b92.png)

An error occurred while testing this indexer
Test search in BTDigg => Found no results while trying to browse this tracker

- Click on [BTDigg...![image](https://user-images.githubusercontent.com/3066000/234708942-472ea529-a09c-4cb4-b1a0-bf64b13a7b35.png)...] ![image](https://user-images.githubusercontent.com/3066000/234707617-4700194f-6802-4d90-8d2c-b3a18a423b92.png)
- input "mandalorian" Query
- click on magnifying glass
- zero results: Manual search in BTDigg for mandalorian => Found 0 releases [104ms]

### Logged Error Messages

```text
See above.
```

**Comment by ilike2burnthing** [comment]
Follow these troubleshooting steps - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

If you still have issues, provide an enhanced log of a failed test - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by colemar** [comment]
If I test https://btdig.com/ with a browser from the same IP address as Jackett's host, then an Anti-DDoS protection challenge appears
![image](https://user-images.githubusercontent.com/3066000/234779473-3f3e409b-f262-46b7-859f-b44fdf32d4ba.png)
I cannot get Flaresolverr to work, so I give up for now.

**Comment by colemar** [comment]
I am reopening this issue because after installing and configuring Flaresolverr 3.1.2 (which solved issue #14276) BTDigg still shows zero results.

It seems that Jackett (or the BTDigg plugin) does not even attempt to connect through Flaresolverr proxy, this is evident from Flaresolverr log.

Jackett's log is not very helpful:
```
Apr 27 10:59:44 clmr.tk jackett[3078380]: 04-27 10:59:44 Info Manual search in BTDigg for mandalorian => Found 0 releases [794ms]
Apr 27 11:00:14 clmr.tk jackett[3078380]: 04-27 11:00:14 Info Test search in BTDigg => Found 0 releases [47ms]
Apr 27 11:00:14 clmr.tk jackett[3078380]: 04-27 11:00:14 Error System.Exception: Test search in BTDigg => Found no results while trying to browse this tracker System.Exception: Test search in BTDigg => Found no results while trying to browse this tracker
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 322
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompl>
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
Apr 27 11:00:14 clmr.tk jackett[3078380]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
See the instructions for enhanced logging above.

**Comment by colemar** [comment]
Enhanced log for plugin test: 
[BTDigg-Test.txt](https://github.com/Jackett/Jackett/files/11343035/BTDigg-Test.txt)

Enhanced log for plugin manual search "mandalorian": 
[BTDigg-manual-search.txt](https://github.com/Jackett/Jackett/files/11343039/BTDigg-manual-search.txt)

**Comment by ilike2burnthing** [comment]
Odd that it would be returning a Cloudflare challenge page when you have FlareSolverr configured. What is the output of FlareSolverr's log when you run a search?

I'm wondering if you using a VPS is causing the `Returning TooManyRequests` response, which is then resulting in this behaviour.

**Comment by ilike2burnthing** [comment]
Add TorrentQQ and run a test with it. If it fails as well with no FlareSolverr activity, check that the FlareSolverr API URL you're using is correct.

**Comment by colemar** [comment]
This is the enhanced log for the first test (no Flaresolverr activity):
[TorrentQQ-Test.txt](https://github.com/Jackett/Jackett/files/11344809/TorrentQQ-Test.txt)

After that, the plugin auto-adjusted the URL to https://torrentqq254.com/.
This is the second attempt (successful, see Flaresolverr's activity below):
[TorrentQQ-Test-2.txt](https://github.com/Jackett/Jackett/files/11344816/TorrentQQ-Test-2.txt)
```
Apr 27 16:42:03 clmr.tk flaresolverr[3077552]: 2023-04-27 16:42:03 INFO     Incoming request => POST /v1 body: {'maxTimeout': 25000, 'cmd': 'request.get', 'url': 'https://torrentqq254.com/torrent/newest.html'}
Apr 27 16:42:06 clmr.tk flaresolverr[3077552]: 2023-04-27 16:42:06 INFO     Challenge detected. Title found: Just a moment...
Apr 27 16:42:10 clmr.tk flaresolverr[3077552]: 2023-04-27 16:42:10 INFO     Challenge solved!
Apr 27 16:42:10 clmr.tk flaresolverr[3077552]: 2023-04-27 16:42:10 INFO     Response in 6.792 s
Apr 27 16:42:10 clmr.tk flaresolverr[3077552]: 2023-04-27 16:42:10 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK
```

After that, I did a successful manual search of "2023", this time no Flaresolverr activity was observed (I guess the cookies were enough):
[TorrentQQ-Test-3.txt](https://github.com/Jackett/Jackett/files/11345036/TorrentQQ-Test-3.txt)

**Comment by ilike2burnthing** [comment]
@colemar can you try using a proxy/VPN for Jackett (and FlareSolverr)? See if that resolves your issue.

**Comment by colemar** [comment]
@ilike2burnthing About using a proxy...

I already know that if I open https://btdig.com from my home network (provider Telecom Italia) then there is no challenge: the BTDigg search page comes up straight away.
Therefore I expected that Jackett/BTDigg search would work if Jackett is configured to use a proxy on my home network.
Indeed, it works and flaresolverr shows no activity.

I also know that if I open https://btdig.com from my home using an http proxy hosted on the same machine as Jackett's (62.210.136.x), then the challenge page comes up as shown in the image I already posted above (but I can proceed without issues after clicking [I'm not a robot]).
I disabled Jackett's proxy option again and confirmed in the enhanced log that the received HTML code looks identical to what I see using Chrome inspect function when browsing https://btdig.com from my home through the 62.210.136.x proxy. In particular, both HTML pieces show `<!-- 62.210.136.x @ AS12876 -->`.
No flaresolverr activity is ever observed when using Jackett's BTDigg plugin.

My guess is that AS12876 (that is Scaleway) is flagged as suspicious and BTDigg (or Cloudflare) sends an interstitial page that does not look like the usual Cloudflare challenge, therefore Jackett does not recognize the need to use Flaresolverr. Even if Jackett would use Flaresolverr, it seems that the latter does not recognize the page as a challenge:
```
$ curl -L -X POST 'http://localhost:8191/v1' -H 'Content-Type: application/json' --data-raw '{"cmd": "request.get", "url":"https://btdig.com//", "maxTimeout": 60000}'
{"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://btdig.com/", "status": 200, "cookies": [], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36", "headers": {}, "response": "<html><head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\">\n<meta content=\"width=device-width, initial-scale=1, minimal-ui\" name=\"viewport\">\n<title>btdig.com</title>\n<!--\n <script>var ezoicId = 339363;</script>\n <script type=\"text/javascript\" src=\"//go.ezoic.net/ezoic/ezoic.js\"></script>\n-->\n</head>\n<!-- 62.210.136.217 @ AS12876 --> ...
```

Flaresolverr's log:
```
2023-04-28 19:53:26 INFO     Challenge not detected!
2023-04-28 19:53:26 INFO     Response in 1.477 s
2023-04-28 19:53:26 INFO     127.0.0.1 POST http://localhost:8191/v1 200 OK
```

**Comment by ilike2burnthing** [comment]
K, then this is a FlareSolverr problem. Please open an issue there, linking to this one.

**Comment by colemar** [comment]
I will open an issue for Flaresolverr, but even if and when it's fixed, the issue with Jackett is that it does not try to use Flaresolverr, likely because it does not recognize the BTDigg interstitial page as a challenge.

I'm willing to grant you a temporary account for the http proxy running on the Jackett's machine, if you want to try yourself to access BTDigg using the "suspicious" IP address.

**Comment by colemar** [comment]
Well, it seems this is and old problem:
#12247

**Comment by ilike2burnthing** [comment]
> the issue with Jackett is that it does not try to use Flaresolverr, likely because it does not recognize the BTDigg interstitial page as a challenge.

That would involve a fix with FlareSolverrSharp, rather than Jackett specifically.

> Well, it seems this is and old problem:
https://github.com/Jackett/Jackett/issues/12247

As far as I'm aware the 429 status not being detected was resolved - https://github.com/FlareSolverr/FlareSolverr/issues/187
