### ISSUE TITLE
Extratorrent.st zero results

### ISSUE THREAD

**Issue by colemar** [Jackett/Jackett#14276]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.0.0.1:8191
Using proxy: Disabled
App config/log directory: /home/jackett/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 22.04.2 LTS
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.0.69 (64bit OS) (64bit process)
Environment version: 6.0.16 (/home/jackett/Jackett/)
Starting Jackett v0.20.3996
```

### Description

Manual search of "mandalorian" with Extratorrent.st gives zero results.

### Logged Error Messages

```text
Error	
Jackett.Common.IndexerException: Exception (extratorrent-st): Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()

Info	
Manual search in ExtraTorrent.st for mandalorian => Found 0 releases [30262ms]
```

### Screenshots

![image](https://user-images.githubusercontent.com/3066000/234713562-8f69c3d3-5a32-46f2-85fc-816001d50229.png)

**Comment by colemar** [comment]
```
# systemctl status flaresolverr.service
● flaresolverr.service - FlareSolverr
     Loaded: loaded (/etc/systemd/system/flaresolverr.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-04-27 00:09:33 CEST; 7s ago
   Main PID: 3039612 (flaresolverr)
      Tasks: 165 (limit: 9367)
     Memory: 286.2M
        CPU: 4.377s
     CGroup: /system.slice/flaresolverr.service
             ├─3039612 /home/flaresolverr/flaresolverr/flaresolverr
             ├─3039622 /home/flaresolverr/flaresolverr/firefox/firefox --no-remote --foreground --headless about:blank --remote-debugg>
             ├─3039650 /home/flaresolverr/flaresolverr/firefox/firefox-bin -contentproc -parentBuildID 20211212093503 -prefsLen 1 -pre>
             ├─3039700 /home/flaresolverr/flaresolverr/firefox/firefox-bin -contentproc -childID 1 -isForBrowser -prefsLen 1735 -prefM>
             └─3039723 /home/flaresolverr/flaresolverr/firefox/firefox-bin -contentproc -childID 2 -isForBrowser -prefsLen 1819 -prefM>

Apr 27 00:09:33 clmr.tk systemd[1]: Started FlareSolverr.
Apr 27 00:09:34 clmr.tk flaresolverr[3039612]: 2023-04-27T00:09:34+02:00 INFO FlareSolverr v2.1.0
Apr 27 00:09:34 clmr.tk flaresolverr[3039612]: 2023-04-27T00:09:34+02:00 INFO Testing web browser installation...
```

```
# journalctl -u flaresolverr.service
...
Apr 27 00:12:04 clmr.tk flaresolverr[3040261]: 2023-04-27T00:12:04+02:00 ERROR TimeoutError: Navigation timeout of 30000 ms exceeded
Apr 27 00:12:04 clmr.tk flaresolverr[3040261]:     at /snapshot/FlareSolverr/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
Apr 27 00:12:04 clmr.tk flaresolverr[3040261]:   -- ASYNC --
Apr 27 00:12:04 clmr.tk flaresolverr[3040261]:     at Frame.<anonymous> (/snapshot/FlareSolverr/node_modules/puppeteer/lib/helper.js:94:19)
Apr 27 00:12:04 clmr.tk flaresolverr[3040261]:     at Page.goto (/snapshot/FlareSolverr/node_modules/puppeteer/lib/Page.js:485:53)
Apr 27 00:12:04 clmr.tk flaresolverr[3040261]:     at Page.<anonymous> (/snapshot/FlareSolverr/node_modules/puppeteer/lib/helper.js:95:27)
Apr 27 00:12:04 clmr.tk flaresolverr[3040261]:     at testWebBrowserInstallation (/snapshot/FlareSolverr/dist/services/sessions.js:75:16)
Apr 27 00:12:04 clmr.tk flaresolverr[3040261]:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Apr 27 00:12:04 clmr.tk systemd[1]: flaresolverr.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 00:12:04 clmr.tk systemd[1]: flaresolverr.service: Failed with result 'exit-code'.
Apr 27 00:12:04 clmr.tk systemd[1]: flaresolverr.service: Consumed 5.761s CPU time.
Apr 27 00:12:10 clmr.tk systemd[1]: flaresolverr.service: Scheduled restart job, restart counter is at 32646.
Apr 27 00:12:10 clmr.tk systemd[1]: Stopped FlareSolverr.
Apr 27 00:12:10 clmr.tk systemd[1]: flaresolverr.service: Consumed 5.761s CPU time.
Apr 27 00:12:10 clmr.tk systemd[1]: Started FlareSolverr.
```

**Comment by colemar** [comment]
Never mind, it seems an issue of FlareSolverr v2.1.0.

**Comment by ilike2burnthing** [comment]
The current FlareSolverr version is v3.1.2, you're a year and half behind.

**Comment by colemar** [comment]
Issue solved installing and configuring Flaresolverr 3.1.2.
BTDigg is still broken though, see #14275
