### ISSUE TITLE
[torrentseeds] Hyphen in search term causes internal server error 500

### ISSUE THREAD

**Issue by altounen** [Jackett/Jackett#14300]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/torrent/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 20.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.0.71 (64bit OS) (64bit process)
Environment version: 6.0.16 (/home/torrent/Jackett/)
Starting Jackett v0.20.4071
```

### Description

Searching anything with a hyphen in the query causes TorrentSeeds to respond with internal server error 500.

This is problematic when using Jackett with other tools like cross-seed that do a search with the full name of a torrent. For example a music release with the standard naming convention: Artist_Name-Album_Name-(CATALOGNUMBER)-WEB-FLAC-2023-GROUP

Placing the query inside quotes fixes the issue, but ideally Jackett would to this internally so other tools don't have to take this into account.

### Logged Error Messages

```text
2023-05-03 12:10:14.2069 Info Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=APIKEY&Query=-&Category%5B%5D=100004&Tracker%5B%5D=torrentseeds-api&_=1683097476261 - - 
2023-05-03 12:10:14.2069 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=APIKEY&Query=-&Category%5B%5D=100004&Tracker%5B%5D=torrentseeds-api&_=1683097476261 
2023-05-03 12:10:14.2069 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=APIKEY&Query=-&Category%5B%5D=100004&Tracker%5B%5D=torrentseeds-api&_=1683097476261 
2023-05-03 12:10:14.2069 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=APIKEY&Query=-&Category%5B%5D=100004&Tracker%5B%5D=torrentseeds-api&_=1683097476261 
2023-05-03 12:10:14.2069 Debug The request path /api/v2.0/indexers/all/results does not match a supported file type 
2023-05-03 12:10:14.2069 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2023-05-03 12:10:14.2069 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/all/results' 
2023-05-03 12:10:14.2069 Debug Endpoint 'Jackett.Server.Controllers.ResultsController.Results (jackett)' with route pattern 'api/v2.0/indexers/{indexerId}/results' is valid for the request path '/api/v2.0/indexers/all/results' 
2023-05-03 12:10:14.2069 Debug Request matched endpoint 'Jackett.Server.Controllers.ResultsController.Results (jackett)' 
2023-05-03 12:10:14.2069 Info Executing endpoint 'Jackett.Server.Controllers.ResultsController.Results (jackett)' 
2023-05-03 12:10:14.2079 Info Route matched with {action = "Results", controller = "Results"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Results(Jackett.Common.Models.DTO.ApiSearch) on controller Jackett.Server.Controllers.ResultsController (jackett). 
2023-05-03 12:10:14.2079 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2023-05-03 12:10:14.2079 Debug Execution plan of resource filters (in the following order): None 
2023-05-03 12:10:14.2079 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresApiKey, Jackett.Server.Controllers.RequiresConfiguredIndexer, Jackett.Server.Controllers.RequiresValidQuery 
2023-05-03 12:10:14.2079 Debug Execution plan of exception filters (in the following order): None 
2023-05-03 12:10:14.2079 Debug Execution plan of result filters (in the following order): None 
2023-05-03 12:10:14.2079 Debug Executing controller factory for controller Jackett.Server.Controllers.ResultsController (jackett) 
2023-05-03 12:10:14.2079 Debug Executed controller factory for controller Jackett.Server.Controllers.ResultsController (jackett) 
2023-05-03 12:10:14.2079 Debug Attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch' ... 
2023-05-03 12:10:14.2079 Debug Attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch' using the name '' in request data ... 
2023-05-03 12:10:14.2079 Debug Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Query' of type 'System.String' using the name 'Query' in request data ... 
2023-05-03 12:10:14.2079 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Query' of type 'System.String'. 
2023-05-03 12:10:14.2079 Debug Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]' using the name 'Category' in request data ... 
2023-05-03 12:10:14.2079 Debug Could not bind to collection using a format like Category=value1&Category=value2 
2023-05-03 12:10:14.2079 Debug Attempting to bind model using indices. Example formats include: [0]=value1&[1]=value2, Category[0]=value1&Category[1]=value2, Category.index=zero&Category.index=one&Category[zero]=value1&Category[one]=value2 
2023-05-03 12:10:14.2079 Debug Attempting to bind model of type 'System.Int32' using the name 'Category[0]' in request data ... 
2023-05-03 12:10:14.2079 Debug Could not find a value in the request with name 'Category[0]' of type 'System.Int32'. 
2023-05-03 12:10:14.2079 Debug Done attempting to bind model of type 'System.Int32' using the name 'Category[0]'. 
2023-05-03 12:10:14.2079 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Category' of type 'System.Int32[]'. 
2023-05-03 12:10:14.2079 Debug Attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Tracker' of type 'System.String[]' using the name 'Tracker' in request data ... 
2023-05-03 12:10:14.2079 Debug Could not bind to collection using a format like Tracker=value1&Tracker=value2 
2023-05-03 12:10:14.2079 Debug Attempting to bind model using indices. Example formats include: [0]=value1&[1]=value2, Tracker[0]=value1&Tracker[1]=value2, Tracker.index=zero&Tracker.index=one&Tracker[zero]=value1&Tracker[one]=value2 
2023-05-03 12:10:14.2079 Debug Attempting to bind model of type 'System.String' using the name 'Tracker[0]' in request data ... 
2023-05-03 12:10:14.2079 Debug Could not find a value in the request with name 'Tracker[0]' of type 'System.String'. 
2023-05-03 12:10:14.2079 Debug Done attempting to bind model of type 'System.String' using the name 'Tracker[0]'. 
2023-05-03 12:10:14.2079 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.ApiSearch.Tracker' of type 'System.String[]'. 
2023-05-03 12:10:14.2079 Debug Done attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch'. 
2023-05-03 12:10:14.2079 Debug Done attempting to bind parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch'. 
2023-05-03 12:10:14.2079 Debug Attempting to validate the bound parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch' ... 
2023-05-03 12:10:14.2079 Debug Done attempting to validate the bound parameter 'requestt' of type 'Jackett.Common.Models.DTO.ApiSearch'. 
2023-05-03 12:10:14.2079 Debug CACHE PruneCacheByTtl / Pruned queries: 0 
2023-05-03 12:10:14.2079 Debug CACHE Status / Total cached results: 108 
2023-05-03 12:10:14.2137 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://torrentseeds.org/api/torrents/filter?api_token=APITOKEN&categories[]=4&name=-&sortField=created_at&sortDirection=desc&perPage=100&page=1) 
2023-05-03 12:10:14.2799 Debug WebClient(HttpWebClient2): Returning InternalServerError => 1667 bytes
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>    Error 500: Internal Server Error
 - TorrentSeeds</title>

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Error">
    <meta property="og:title" content="TorrentSeeds">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://torrentseeds.org/img/og.png">
    <meta property="og:url" content="https://torrentseeds.org">
    <meta name="csrf-token" content="">

    <link rel="shortcut icon" href="https://torrentseeds.org/favicon.ico" type="image/x-icon">
    <link rel="icon" href="https://torrentseeds.org/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="https://torrentseeds.org/css/app.css" />
</head>

<body>
    <section class="container content" id="content-area" style="min-height: 344px;">
        <div class="jumbotron shadowed">
            <div class="container">
                    <h1 class="mt-5 text-center">
        <i class="fas fa-cog fa-spin text-danger"></i> Error 500: Internal Server Error!
    </h1>
    
    <div class="separator"></div>
    
    <p class="text-center">Our server encountered an internal error. <br>Sorry For The Inconvenience</p>

                <p class="text-center">
                    <a href="https://torrentseeds.org" role="button" class="btn btn-labeled btn-primary">
                        <i class="fas fa-home"></i> Go Home
                    </a>
                </p>
            </div>
        </div>
    </section>
</body>

</html> 
2023-05-03 12:10:14.2799 Error Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=InternalServerError Response=<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>    Error 500: Internal Server Error
 - TorrentSeeds</title>

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Error">
    <meta property="og:title" content="TorrentSeeds">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://torrentseeds.org/img/og.png">
    <meta property="og:url" content="https://torrentseeds.org">
    <meta name="csrf-token" content="">

    <link rel="shortcut icon" href="https://torrentseeds.org/favicon.ico" type="image/x-icon">
    <link rel="icon" href="https://torrentseeds.org/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="https://torrentseeds.org/css/app.css" />
</head>

<body>
    <section class="container content" id="content-area" style="min-height: 344px;">
        <div class="jumbotron shadowed">
            <div class="container">
                    <h1 class="mt-5 text-center">
        <i class="fas fa-cog fa-spin text-danger"></i> Error 500: Internal Server Error!
    </h1>
    
    <div class="separator"></div>
    
    <p class="text-center">Our server encountered an internal error. <br>Sorry For The Inconvenience</p>

                <p class="text-center">
                    <a href="https://torrentseeds.org" role="button" class="btn btn-labeled btn-primary">
                        <i class="fas fa-home"></i> Go Home
                    </a>
                </p>
            </div>
        </div>
    </section>
</body>

</html>
 Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=InternalServerError Response=<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>    Error 500: Internal Server Error
 - TorrentSeeds</title>

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Error">
    <meta property="og:title" content="TorrentSeeds">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://torrentseeds.org/img/og.png">
    <meta property="og:url" content="https://torrentseeds.org">
    <meta name="csrf-token" content="">

    <link rel="shortcut icon" href="https://torrentseeds.org/favicon.ico" type="image/x-icon">
    <link rel="icon" href="https://torrentseeds.org/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="https://torrentseeds.org/css/app.css" />
</head>

<body>
    <section class="container content" id="content-area" style="min-height: 344px;">
        <div class="jumbotron shadowed">
            <div class="container">
                    <h1 class="mt-5 text-center">
        <i class="fas fa-cog fa-spin text-danger"></i> Error 500: Internal Server Error!
    </h1>
    
    <div class="separator"></div>
    
    <p class="text-center">Our server encountered an internal error. <br>Sorry For The Inconvenience</p>

                <p class="text-center">
                    <a href="https://torrentseeds.org" role="button" class="btn btn-labeled btn-primary">
                        <i class="fas fa-home"></i> Go Home
                    </a>
                </p>
            </div>
        </div>
    </section>
</body>

</html>

 ---> System.Exception: Error Parsing Json Response: Status=InternalServerError Response=<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <title>    Error 500: Internal Server Error
 - TorrentSeeds</title>

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Error">
    <meta property="og:title" content="TorrentSeeds">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://torrentseeds.org/img/og.png">
    <meta property="og:url" content="https://torrentseeds.org">
    <meta name="csrf-token" content="">

    <link rel="shortcut icon" href="https://torrentseeds.org/favicon.ico" type="image/x-icon">
    <link rel="icon" href="https://torrentseeds.org/favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="https://torrentseeds.org/css/app.css" />
</head>

<body>
    <section class="container content" id="content-area" style="min-height: 344px;">
        <div class="jumbotron shadowed">
            <div class="container">
                    <h1 class="mt-5 text-center">
        <i class="fas fa-cog fa-spin text-danger"></i> Error 500: Internal Server Error!
    </h1>
    
    <div class="separator"></div>
    
    <p class="text-center">Our server encountered an internal error. <br>Sorry For The Inconvenience</p>

                <p class="text-center">
                    <a href="https://torrentseeds.org" role="button" class="btn btn-labeled btn-primary">
                        <i class="fas fa-home"></i> Go Home
                    </a>
                </p>
            </div>
        </div>
    </section>
</body>

</html>

   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1439
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 701
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 233
2023-05-03 12:10:14.2799 Info Manual search in TorrentSeeds (API) for - => Found 0 releases [71ms] 
2023-05-03 12:10:14.2799 Info Executing JsonResult, writing value of type 'Jackett.Common.Models.DTO.ManualSearchResult'. 
2023-05-03 12:10:14.2799 Debug The response will be compressed with 'gzip'. 
2023-05-03 12:10:14.2799 Info Executed action Jackett.Server.Controllers.ResultsController.Results (jackett) in 74.0331ms 
2023-05-03 12:10:14.2799 Info Executed endpoint 'Jackett.Server.Controllers.ResultsController.Results (jackett)' 
2023-05-03 12:10:14.2799 Debug Connection id "0HMQBMO7P9KLU" completed keep alive response. 
2023-05-03 12:10:14.2799 Info Request finished HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=APIKEY&Query=-&Category%5B%5D=100004&Tracker%5B%5D=torrentseeds-api&_=1683097476261 - - - 200 - application/json;+charset=utf-8 75.6304ms 
^C
```

**Comment by altounen** [comment]
Related to #14254.

**Comment by altounen** [comment]
Additionally, if for example searching music, the search must be made with: `Artist_Name` or `Artist*`.
Using `+Artist +Name` or `"Artist" "Name"` won't work.
Hyphen seems to be the separator character between different classes (artist, album, year etc.) and underscore separates parts of the class.

Even `term*` and `"term*"` return different results. Without quotes it matches artists and with quotes it matches album names.

**Comment by garfield69** [comment]
v0.20.4078
