### ISSUE TITLE
Error System.InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. 

### ISSUE THREAD

**Issue by lordNaN** [Jackett/Jackett#14349]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: unknown)
File /etc/issue: Welcome to Alpine Linux 3.17	
Jackett variant: CoreLinuxAmdx64	
OS version: Unix 5.15.79.0 (64bit OS) (64bit process)	
Environment version: 6.0.16 (/app/)	
Starting Jackett v0.20.4145

Running in docker in TrueNAS (truecharts).

This is a fresh container.
```

### Description

Stack exception when loading the app. Explains that there are too many calls on the stack

```Error System.InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space. System.InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.```

### Logged Error Messages

```text
2023-05-20 10:04:28.605875+00:00Hosting environment: Production
2023-05-20 10:04:28.605879+00:00Content root path: /app/Content
2023-05-20 10:04:28.605980+00:00Now listening on: http://[::]:9117
2023-05-20 10:04:28.606003+00:00Application started. Press Ctrl+C to shut down.
2023-05-20 10:06:27.466629+00:0005-20 10:06:27 Error System.InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space. System.InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.
2023-05-20 10:06:27.466681+00:00at System.Runtime.CompilerServices.RuntimeHelpers.EnsureSufficientExecutionStack()
2023-05-20 10:06:27.466687+00:00at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
2023-05-20 10:06:27.466694+00:00at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel, Object container)
2023-05-20 10:06:27.466697+00:00at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model, ModelMetadata metadata, Object container)
2023-05-20 10:06:27.466712+00:00at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.EnforceBindRequiredAndValidate(ObjectModelValidator baseObjectValidator, ActionContext actionContext, ParameterDescriptor parameter, ModelMetadata metadata, ModelBindingContext modelBindingContext, ModelBindingResult modelBindingResult, Object container)
2023-05-20 10:06:27.466716+00:00at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
2023-05-20 10:06:27.466734+00:00at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
2023-05-20 10:06:27.466742+00:00--- End of stack trace from previous location ---
2023-05-20 10:06:27.466747+00:00at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Screenshots

<img width="1232" alt="image" src="https://github.com/Jackett/Jackett/assets/20895487/ce6c009f-efb3-4cc9-b33b-3cad6a42ae1d">

<img width="619" alt="image" src="https://github.com/Jackett/Jackett/assets/20895487/04a84abd-b890-4a1e-b8ca-0e9f0f12546c">

**Comment by garfield69** [comment]
how many indexers have you got on your active list?
how long had the docker image been running for?
are you using *arr apps, are they set up with an rss cycle, if so what is their time period between requests?
@ilike2burnthing  any other pertinent questions you can think of, related to docker setup that we could ask about?

**Comment by ilike2burnthing** [comment]
Have you limited the CPU or memory resources for the container, or is it running on a low powered host?

**Comment by ztnazone** [comment]
I am having the same issue. Xeon Platinum over 200 gigs ram.  Resources is not an issue in my case.

**Comment by ztnazone** [comment]
2023-05-20T16:55:10.681675468Z 05-20 16:55:10 Info Starting Jackett v0.20.4145 
2023-05-20T16:55:11.554975103Z 05-20 16:55:11 Info Environment version: 6.0.16 (/app/) 
2023-05-20T16:55:11.555284710Z 05-20 16:55:11 Info OS version: Unix 5.15.79.0 (64bit OS) (64bit process) 
2023-05-20T16:55:11.556071175Z 05-20 16:55:11 Info Jackett variant: CoreLinuxAmdx64 
2023-05-20T16:55:11.556274753Z 05-20 16:55:11 Info File /etc/issue: Welcome to Alpine Linux 3.18 
2023-05-20T16:55:11.556518516Z 05-20 16:55:11 Info Running in Docker: Yes (image build: unknown) 
2023-05-20T16:55:11.556657548Z 05-20 16:55:11 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2023-05-20T16:55:11.556728488Z 05-20 16:55:11 Info App config/log directory: /config/Jackett 
2023-05-20T16:55:11.557544639Z 05-20 16:55:11 Info Using proxy: Disabled 
2023-05-20T16:55:11.557658241Z 05-20 16:55:11 Info Using FlareSolverr: No 
2023-05-20T16:55:11.565798066Z 05-20 16:55:11 Info Using HTTP Client: HttpWebClient2 
2023-05-20T16:55:11.571252909Z 05-20 16:55:11 Info Loading Native indexers ... 
2023-05-20T16:55:11.641167020Z 05-20 16:55:11 Info Loaded 77 Native indexers: alpharatio, anidex, anidub, animebytes, animetorrents, aro, audiobookbay, avistaz, bakabt, beyond-hd-api, bithdtv, bjshare, brasiltracker, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, dicmusic, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, gazellegames, gazellegamesapi, greatposterwall, hdbitsapi, hdspace, hdtorrents, ianon, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, myanonamouse, ncore, nebulanceapi, norbits, orpheus, passthepopcorn, piratethenet, pixelhd, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentheaven, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, uniotaku, xspeeds, zonaq, animetosho, morethantv-api 
2023-05-20T16:55:11.644694482Z 05-20 16:55:11 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Definitions 
2023-05-20T16:55:13.331067491Z 05-20 16:55:13 Info Loaded 498 Cardigann indexers: btdigg, mircrew, datatalli, ilcorsaroblu, byrbt, ptchina, bitnova, skipthetrailers, gtorrentpro, sexypics, fenyarnyek-tracker, marinetracker, asiandvdclub, knaben, deildu, mesevilag, pornbay, lemonhd, sporthd, pttime, puurhollands, rustorka, pornotorrent, rintor, teamctgame, tribalmixes, beitai, soulvoice, ultrahd, piratbit, cartoonchaos, houseofdevil, glodls, gay-torrentsorg, polishtracker-api, falkonvisionteam, themixingbowl, totheglory, aither-api, coastalcrew, lastfiles, portugas-api, teracod, dxp, rutor, estone, peersfm, linkomanija, 3changtrai, kinorun, rutracker-ru, shareisland-api, demonoid, tvchaosuk, punkshorror, torrentz2eu, jpopsuki, torrentsectorcrew, riperam, pornoslab, eniahd, haidan, nipponsei, booktracker, diablotorrent, rgfootball, torrentby, yourbittorrent, torrentdownloads, animetracker, filelisting, mma-torrents, jme-reunit3d-api, cinemamovies, itorrent, teamhd, hdonly, hdfans, hellashut, torrentseeds-api, newretro, hdturk, gainbound, fantastiko, xxxtor, dark-shadow, itatorrents, madsrevolution, aussierules, btetree, dmhy, mvgroupmain, myspleen, pctorrent, theshinning-api, anime-free, pwtorrents, tlfbits, torrentleech-pl, rareshare2, seedfile, hebits, oshenpt, empornium, btnext, hdcztorrent, 2fast4you, uhdbits, theshow, fanoin, resurrectthenet, torrentlt, scenerush, datascene-api, noname-club, xtremebytes, libranet, anilibria, teamos, pixelcove2fa, peeratiko, torrent9clone, crackingpatching, hdc, r3vwtf, 3dtorrents, xwtorrents, thorsland, xthor-api, puntotorrent, majomparade, magicheaven, totallykids, concen, RockBox, unlimitz, satclubbing, mteamtp2fa, oldtoonsworld, noname-clubl, esharenet, crazyhd, gaytorrentru, devil-torrents, gamestorrents, torrentoyunindir, bitsearch, extremetorrents, catorrent, asiancinema, vtorrent, tellytorrent-api, btmet, carphunter, jptv, superbits, bitbazis, comicat, pignetwork, jav-torrent, greekdiamond, mojblink, Bittorrentfiles, slosoul, torrent-pirat, torrenting, hdolimpo-api, amigosshare, movietorrentz, ebooks-shares, showrss, mypornclub, zomb, partis, megapeer, lightning-tor, trancetraffic, sktorrent, badasstorrents, thedarkcommunity, bitsexy, kinozal, opencd, putao, haitang, sukebeinyaasi, 0magnet, hqmusic, borgzelle, concertos, pussytorrents, torrentbd, crazyspirits, joyhd, elitetorrent-pl, nextjav, turkseed, electro-torrent, world-of-tomorrow, thenewfun, sktorrent-org, solidtorrents, uniongang, lat-team-api, audiences, bitru, pier720, isohunt2, kickasstorrents-ws, cinemageddon, freshmeat, theempire, mnv, thevault, u2, bithumen, lesaloon, hdgalaktik, yggcookie, ydypt, torrentfunk, speedmasterhd, nntt, moviesdvdr, hd4fans, hawke-uno, torrentkitty, boxingtorrents, digitalcore, lepornoinfo, greekteam, divteam, torrenthr, reelflix-api, yts, romanianmetaltorrents, byrutor, hd-unit3d-api, swarmazon-api, dreamtracker, thegeeks, firebit, hdtime, speedtorrentreloaded, cathoderaytube, discfan, spidertk, limetorrents, bibliotik, megamixtracker, bithorlo, mazepa, acgrip, hdchina, torrentqq, backups, korsar, chilebt, animelayer, beyond-hd, extremlymtorrents, ccfbits, nicept, ex-torrenty, ptsbao, ptfiles, animeworld-api, 0daykiev, monikadesign-api, arabtorrents, learnbits, torrentland, brsociety-api, uploads, dimeadozen, nordichd, piratbitl, thesceneplace, hdroute, btsow, xxxtorrents, rptorrents, rainbowtracker, zamundanet, trupornolabs, ubits, xbytesv2, torrentproject2, torrent9, parnuxi, torrentccf, aniRena, rapidzona, sharkpt, unleashthecartoons, rudub, blutopia-api, karagarga, mvgroupforum, 1337x, carpathians, selezen, exttorrents, chdbits, proaudiotorrents, hhanclub, ceskeforum, hdvideo, learnflakes, moviesite, gay-torrents, p2pbg, 2xfree, proporno, shanaproject, bootytape, losslessclub, tapochek, torrentsir, bigfangroup, crt2fa, redbits-api, torrentleech, immortuos, broadcity, linuxtracker, funkytorrents, redstartorrent, arenabg, arabafenice, metaltracker, icc2022, torrentslocal, finvip, zetorrents, yggtorrent, polishsource, abtorrents, crnaberza, racingforme, extremebits, uniondht, unionfansub, wihd, miobt, limetorrentsclone, traht, tmghub, internetarchive, torrentmasters, theoccult, anisource, bitturk, genesismovement, tasmanit, mteamtp, sosulki, classix, ebookbay, fuzer, cinematik, btschool, fantasticheaven, pthome, finelite, rintornet, anthelion-api, bangumi-moe, extratorrent-st, newstudio, eztv, locadora, exkinoray, sharewood, torrent-explosiv, krazyzone, acidlounge, indietorrents, thepiratebay, girotorrent, theleachzone, pixelcove, sugoimusic, racing4everyone-api, fluxzone, hdtorrentsit, carpt, ourbits, torrentz2nz, hdu, bitded, ilcorsaronero, tornado, trezzor, theplace, ehentai, hdatmos, hdmonkey, gigatorrents, xxxadulttorrent, nyaasi, hdhome, torrent-turk, acgsou, xtorrenty, movietorrent, vsttorrents, acrossthetasman, kickasstorrents-to, magico, bitspyder, potuk, the-crazy-ones, newstudiol, tvroad, sdbits, idope, torrentcore, ztracker, mikan, springsunday, snowpt, docspedia, hdforever, zelkaorg, huntorrent, torrentview, leech24, file-tracker, seedoff, tokyotosho, 52pt, insanetracker, hdmayi, pterclub, turktorrent, acervos, thefallingangels, arabp2p, totheglorycookie, hdzone, mixtapetorrent, mousebits, xiteme, zmpt, tekno3d, generationfree-api, bwtorrents, hdsky, tjupt, skipthecommercials-api, xxxclub, sportscult, bitofvalor, xwtclassics, cpasbienclone, gktorrent, whiteangel, helltorrents, spiritofrevolution, bestcore, ntelogo, abnormal, les-cinephiles, frozenlayer, aidoruonline, aftershock, milkie, gimmepeers, empornium2fa, 4thd, nethd, mactorrentsdownload, bluebirdhd, torrentwhiz, torlock, happyfappy, torrent911, theoldschool-api, danishbytes-api, femdomcult, siambit, hdarea, cpasbien, torrentgalaxy, kamept, hddolby, bulltorrent, lst, audionews, kufirc, muziekfabriek, vsthouse, desitorrents-api, onejav, keepfriends, 1ptbar, torrentdownload 
2023-05-20T16:55:13.331227280Z 05-20 16:55:13 Info Loaded 575 indexers in total 
2023-05-20T16:55:13.332398637Z 05-20 16:55:13 Info Adding aggregate indexer ('all' indexer) ... 
2023-05-20T16:55:13.346308197Z 05-20 16:55:13 Info Adding filter indexer ('type:public' indexer) ... 
2023-05-20T16:55:13.346636220Z 05-20 16:55:13 Info Adding filter indexer ('type:private' indexer) ... 
2023-05-20T16:55:13.346792211Z 05-20 16:55:13 Info Adding filter indexer ('type:semi-public' indexer) ... 
2023-05-20T16:55:13.522218631Z 05-20 16:55:13 Warn No XML encryptor configured. Key {48f42f8e-e718-4e46-879b-c5f3f3500720} may be persisted to storage in unencrypted form. 
2023-05-20T16:55:13.564851044Z 05-20 16:55:13 Info Jackett startup finished in 3.302 s 
2023-05-20T16:55:13.564942734Z Hosting environment: Production
2023-05-20T16:55:13.564980730Z Content root path: /app/Content
2023-05-20T16:55:13.564995518Z Now listening on: http://[::]:9117
2023-05-20T16:55:13.565036899Z Application started. Press Ctrl+C to shut down.
2023-05-20T16:57:09.538038686Z 05-20 16:57:09 Error System.InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space. System.InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.
2023-05-20T16:57:09.538105738Z    at System.Runtime.CompilerServices.RuntimeHelpers.EnsureSufficientExecutionStack()
2023-05-20T16:57:09.538120672Z    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Visit(ModelMetadata metadata, String key, Object model)
2023-05-20T16:57:09.538129451Z    at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.Validate(ModelMetadata metadata, String key, Object model, Boolean alwaysValidateAtTopLevel, Object container)
2023-05-20T16:57:09.538140975Z    at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model, ModelMetadata metadata, Object container)
2023-05-20T16:57:09.538149414Z    at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.EnforceBindRequiredAndValidate(ObjectModelValidator baseObjectValidator, ActionContext actionContext, ParameterDescriptor parameter, ModelMetadata metadata, ModelBindingContext modelBindingContext, ModelBindingResult modelBindingResult, Object container)
2023-05-20T16:57:09.538164989Z    at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
2023-05-20T16:57:09.538173524Z    at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
2023-05-20T16:57:09.538187130Z --- End of stack trace from previous location ---
2023-05-20T16:57:09.538195640Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-05-20T16:57:09.538208084Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-05-20T16:57:09.538216631Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-05-20T16:57:09.538228422Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-05-20T16:57:09.538237633Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-05-20T16:57:09.538248955Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-05-20T16:57:09.538257840Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by ilike2burnthing** [comment]
To the first part of my question, you haven't manually set resource restrictions for the container?

Can you answer @garfield69's questions as well?

**Comment by ztnazone** [comment]
I have not set resource restrictions. I just installed a fresh version on Truenas "truecharts version" same issue. 

how many indexers have you got on your active list?  Info Loaded 575 indexers in total 
how long had the docker image been running for?  Fresh Install
are you using *arr apps, are they set up with an rss cycle, if so what is their time period between requests?  YES - 60 minutes

**Comment by garfield69** [comment]
>how many indexers have you got on your active list? Info Loaded 575 indexers in total

575 is the total number of indexers available, but the question was, how many of them do you have on your **active** list ;-) ?

**Comment by ztnazone** [comment]
On sorry I was only using one.

**Comment by garfield69** [comment]
>how long had the docker image been running for? Fresh Install

I meant how long (as in hours the jackett image has been active), 6 hours, 24 hours, a week, since the last reset?

**Comment by ztnazone** [comment]
One hour since last install

**Comment by garfield69** [comment]
thanks.

**Comment by ztnazone** [comment]
Thank you for your time and patience.

**Comment by ilike2burnthing** [comment]
Given you're both running the TrueNAS TrueCharts version of Jackett, and you're both having the same issue at the same time, I'd look at a recent update on their end.

Can you revert to earlier versions until you find the most recent working one, so we can see if it points to a particular change? - https://truecharts.org/charts/stable/jackett/CHANGELOG

**Comment by makanimike** [comment]
I too have this issue since a few days.  
I just updated the latest TrueChart release a few minutes ago. But that didn't change anything.  
  
I only have 2 active indexers. (well, I would have 2, if it was working)  
The problem first appeared on Friday night, after a fresh start after returning from a trip during which the server was off.

**Comment by garfield69** [comment]
@makanimike  Can you revert to earlier versions until you find the most recent working one, so we can see if it points to a particular change? - https://truecharts.org/charts/stable/jackett/CHANGELOG

**Comment by makanimike** [comment]
I only have .17, .14 and .13 available. (must be because of the recent big change with TrueChart charts which required a fresh install of charts).  
13 works again. So something happened in the release of .14 and the following which is breaking things for me (and presumably the other users in this thread).

**Comment by ilike2burnthing** [comment]
Are you able to update Jackett using the yellow `Check for updates` button in Jackett's UI while sticking with the *.13 container?

If so, and if Jackett still works when updated, then this is a TrueCharts issue and would need to brought up with them.

**Comment by ilike2burnthing** [comment]
Nevermind, it already has been - https://github.com/truecharts/charts/issues/8885

**Comment by dbolser** [comment]
Issue is back for me..

**Comment by dbolser** [comment]
Sorry, literally just saw update available, clicked upgrade... I'll let you know

**Comment by dbolser** [comment]
Same error after upgrade:

jackett
0.21.1051_15.0.21Up to date

**Comment by ilike2burnthing** [comment]
https://github.com/truecharts/charts/issues/13339

**Comment by dbolser** [comment]
I should report there?

**Comment by garfield69** [comment]
yes, because this is not so much a Jackett core issue as is a truecharts specific problem. 
All the other platform builds from this repo and the other 3rd party builds like linuxserver.io docker for example are working ok.

**Comment by dbolser** [comment]
I see, thanks.

**Comment by Ornias1993** [comment]
We just spin up a container on kubernetes, we've no influence over either the container itself or application inside of it.
We've made no changes to how resources are allocated in any way, shape or form.

Likely this issue is caused by either our container source or Jackett.

**Comment by dbolser** [comment]
TrueCharts locked their issue as 'spam' ... genius.

**Comment by Ornias1993** [comment]
> TrueCharts locked their issue as 'spam' ... genius.

Yeah must've been a mistake, should've been locked without reason filed.

**Comment by ilike2burnthing** [comment]
What is the source for the container?

**Comment by Ornias1993** [comment]
> Hmm... good question...
> 
> From here: https://github.com/truecharts/charts/tree/master/charts/stable/jackett
> 
> > This chart is not maintained by the upstream project and any issues with the chart should be raised [here](https://github.com/truecharts/charts/issues/new/choose)
> 
> I guess if you keep following links you eventually get dizzy and go lie down.

Or just open the container mirror repo directly.
https://github.com/truecharts/containers/tree/master/mirror

**Comment by Koopzington** [comment]
Okay but given how jackett isn't inside the mirror folder but instead in the [apps](https://github.com/truecharts/containers/blob/master/apps/jackett/Dockerfile) folder, doesn't that mean that this image is maintained by truecharts (and community)?
