### ISSUE TITLE
(updating) Resource temporarily unavailable (anidex.info:443)

### ISSUE THREAD

**Issue by hobb7t** [Jackett/Jackett#14367]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
05-23 13:44:47 Info Environment version: 6.0.16 (/app/Jackett/) 
05-23 13:44:47 Info OS version: Unix 5.10.0.17 (64bit OS) (64bit process) 
05-23 13:44:47 Info Jackett variant: CoreLinuxMuslAmdx64 
05-23 13:44:47 Info File /etc/issue: Welcome to Alpine Linux 3.17 
05-23 13:44:47 Info Running in Docker: Yes (image build: v0.21.17-ls107) 
05-23 13:44:47 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
05-23 13:44:47 Info App config/log directory: /config/Jackett 
05-23 13:44:47 Info Using proxy: Disabled 
05-23 13:44:47 Info Using FlareSolverr: No 
05-23 13:44:47 Info Using HTTP Client: HttpWebClient2 
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
```

### Description

after i installed nefarious, i tried to add some of the indexers through jackett's UI but i get the "Resource temporarily unavailable" error. The's no blocker to block the exact site, thats for sure, but it seems like there must be some issue and the container can't reach the web? 

### Logged Error Messages

```text
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass12_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 508
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 507
   at Jackett.Common.Indexers.Anidex.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anidex.cs:line 199
   at Jackett.Common.Indexers.Anidex.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anidex.cs:line 158
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
05-23 13:44:47 Info Restarting webhost due to configuration change 
05-23 13:44:47 Info Restart of the web application host (not process) initiated 
05-23 13:44:47 Info Jackett stopped 
05-23 13:44:47 Info Environment version: 6.0.16 (/app/Jackett/) 
05-23 13:44:47 Info OS version: Unix 5.10.0.17 (64bit OS) (64bit process) 
05-23 13:44:47 Info Jackett variant: CoreLinuxMuslAmdx64 
05-23 13:44:47 Info File /etc/issue: Welcome to Alpine Linux 3.17 
05-23 13:44:47 Info Running in Docker: Yes (image build: v0.21.17-ls107) 
05-23 13:44:47 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
05-23 13:44:47 Info App config/log directory: /config/Jackett 
05-23 13:44:47 Info Using proxy: Disabled 
05-23 13:44:47 Info Using FlareSolverr: No 
05-23 13:44:47 Info Using HTTP Client: HttpWebClient2 
05-23 13:44:47 Info Loading Native indexers ... 
05-23 13:44:47 Info Loaded 77 Native indexers: alpharatio, anidex, anidub, animebytes, animetorrents, aro, audiobookbay, avistaz, bakabt, beyond-hd-api, bithdtv, bjshare, brasiltracker, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, darmowetorenty, dicmusic, divxtotal, dontorrent, epublibre, erai-raws, exoticaz, filelist, funfile, gazellegames, gazellegamesapi, greatposterwall, hdbitsapi, hdspace, hdtorrents, ianon, immortalseed, iptorrents, libble, lostfilm, magnetico, mejortorrent, myanonamouse, ncore, nebulanceapi, norbits, orpheus, passthepopcorn, piratethenet, pixelhd, pornolab, pretome, privatehd, rarbg, redacted, retroflix, revolutiontt, rutracker, scenehd, scenetime, secretcinema, sharewoodapi, shazbat, speedapp, speedcd, subsplease, toloka, torrentbytes, torrentday, torrentheaven, torrentnetwork, torrentscsv, torrentsyndikat, tvstore, uniotaku, xspeeds, zonaq, animetosho, morethantv-api 
05-23 13:44:47 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions 
05-23 13:44:54 Info Loaded 506 Cardigann indexers: bitsexy, torrentproject2, jme-reunit3d-api, losslessclub, ptchina, knaben, siambit, xwtclassics, torrent-turk, torrentdownload, hdzone, torrent-pirat, thorsland, haitang, rgfootball, deildu, speedmasterhd, crazyspirits, helltorrents, femdomcult, huntorrent, bitspyder, crazyhd, anthelion-api, mma-torrents, polishsource, asiancinema, rudub, sktorrent-org, peersfm, yourbittorrent, hdolimpo-api, libranet, hdfans, bitbazis, torrentland, insanetracker, 52pt, abtorrents, Bittorrentfiles, pornoslab, exttorrents, theoccult, empornium, lst, dark-shadow, bulltorrent, nethd, animeworld-api, xtorrenty, torrentqq, teamos, cartoonchaos, mircrew, zelkaorg, riperam, freshmeat, torrent9, torrentcore, mteamtp2fa, world-of-tomorrow, movietorrent, mousebits, rptorrents, mazepa, linkomanija, torlock, crt2fa, blutopia-api, eniahd, cinemamovies, mypornclub, acgrip, abnormal, sktorrent, redstartorrent, theleachzone, pier720, internetarchive, ccfbits, cinefilhd, tekno3d, theplace, fanoin, glodls, audiences, the-crazy-ones, vtorrent, bithorlo, trezzor, aftershock, megamixtracker, itatorrents, arabtorrents, mvgroupmain, lastfiles, tvchaosuk, teracod, torrentslocal, comicat, pttime, backups, acervos, sugoimusic, booktracker, torrentccf, torrent-explosiv, joyhd, hdcztorrent, totheglory, kufirc, turktorrent, torrentoyunindir, electro-torrent, fluxzone, gay-torrents, fantasticheaven, exkinoray, tapochek, torrentsectorcrew, byrutor, immortuos, discfan, noname-clubl, carpathians, seedoff, teamhd, unionfansub, tvroad, isohunt2, xxxclub, proaudiotorrents, punkshorror, 2xfree, hdturk, bootytape, sporthd, arabafenice, btnext, greekdiamond, cinematik, rintor, totallykids, mojblink, icc2022, sportscult, hdforever, party-tracker, crnaberza, animelayer, linuxtracker, sosulki, btschool, mdan, bitru, torrentkitty, shanaproject, 1337x, nordichd, bitturk, proporno, teamctgame, aussierules, pthome, arenabg, metalguru, pixelcove, torrentmasters, 0daykiev, pussytorrents, superbits, nyaasi, wihd, mixtapetorrent, unleashthecartoons, crackingpatching, kickasstorrents-to, vsttorrents, xxxadulttorrent, girotorrent, tornado, beyond-hd, acrossthetasman, btetree, bangumi-moe, zmpt, mactorrentsdownload, hawke-uno, hebits, 1ptbar, bwtorrents, ztracker, datascene-api, kinorun, torrenthr, catorrent, file-tracker, rareshare2, hdonly, gay-torrentsorg, mteamtp, arabp2p, xwtorrents, btsow, masters-tb, hdtorrentsit, danishbytes-api, gimmepeers, newretro, 3changtrai, frozenlayer, bitofvalor, haidan, madsrevolution, slosoul, extremebits, sharkpt, hdc, lightning-tor, torrentz2nz, extratorrent-st, fuzer, torrentwhiz, gktorrent, rintornet, genesismovement, miobt, r3vwtf, yts, ultrahd, thenewfun, partis, pignetwork, hd-unit3d-api, 2fast4you, hddolby, fenyarnyek-tracker, totheglorycookie, anisource, swarmazon-api, ydypt, portugas-api, xiteme, hdsky, coastalcrew, hdmonkey, nntt, ceskeforum, torrenting, rustorka, rutracker-ru, snowpt, racing4everyone-api, tribalmixes, funkytorrents, skipthecommercials-api, digitalcore, ilcorsaronero, pornotorrent, mnv, ntelogo, ex-torrenty, ebookbay, redbits-api, houseofdevil, springsunday, extremetorrents, zomb, jav-torrent, milkie, torrentleech-pl, sdbits, kamept, trancetraffic, chilebt, torrentview, eztv, rutor, speedtorrentreloaded, puurhollands, hdchina, bluebirdhd, bitded, newstudio, theshow, aidoruonline, torrentsir, rainbowtracker, soulvoice, devil-torrents, broadcity, torrentgalaxy, torrentseeds-api, romanianmetaltorrents, onejav, carphunter, xtremebytes, torrent911, diablotorrent, theshinning-api, u2, piratbitl, finvip, metaltracker, torrentbd, whiteangel, tjupt, dxp, thevault, satclubbing, estone, lemonhd, gaytorrentru, 4thd, gtorrentpro, traht, karagarga, centraltorrent, ptfiles, happyfappy, asiandvdclub, ehentai, theempire, cathoderaytube, audionews, thedarkcommunity, jpopsuki, jptv, pwtorrents, demonoid, 0magnet, mesevilag, hdu, lesaloon, showrss, aither-api, ourbits, dmhy, themixingbowl, 3dtorrents, idope, trupornolabs, skipthetrailers, krazyzone, torrent9clone, datatalli, vsthouse, parnuxi, mvgroupforum, pornbay, ptitzmx, uploads, solidtorrents, RockBox, hqmusic, gainbound, docspedia, carpt, badasstorrents, shareisland-api, newstudiol, gamestorrents, sexypics, ilcorsaroblu, itorrent, animetracker, extremlymtorrents, theoldschool-api, oldtoonsworld, tlfbits, chdbits, btdigg, anime-free, bitnova, torrentdownloads, nicept, oshenpt, hd4fans, noname-club, esharenet, sukebeinyaasi, aniRena, greekteam, brsociety-api, seedfile, infire, torrentby, limetorrentsclone, p2pbg, dreamtracker, muziekfabriek, thefallingangels, acgsou, korsar, acidlounge, hdatmos, hdtime, bestcore, racingforme, reelflix-api, hdgalaktik, empornium2fa, resurrectthenet, torrentleech, thesceneplace, hdroute, bigfangroup, magicheaven, elitetorrent-pl, cinemageddon, limetorrents, firebit, lepornoinfo, torrentlt, tokyotosho, locadora, pterclub, concen, zamundanet, tasmanit, myspleen, polishtracker-api, amigosshare, movietorrentz, concertos, gigatorrents, torrentfunk, kickasstorrents-ws, classix, mikan, magico, peeratiko, majomparade, lesbians4u, lat-team-api, beitai, hdarea, keepfriends, tmghub, hdvideo, falkonvisionteam, opencd, thepiratebay, torrentz2eu, pixelcove2fa, puntotorrent, nipponsei, fantastiko, divteam, hhanclub, byrbt, potuk, hdhome, learnbits, tellytorrent-api, bitsearch, uniongang, borgzelle, megapeer, bibliotik, kinozal, yggcookie, btmet, leech24, anilibria, unlimitz, zetorrents, moviesdvdr, nextjav, uniondht, rapidzona, cpasbien, ubits, xxxtor, generationfree-api, xbytesv2, putao, sharewood, spiritofrevolution, piratbit, pctorrent, spidertk, desitorrents-api, turkseed, finelite, marinetracker, boxingtorrents, xxxtorrents, hdmayi, xthor-api, learnflakes, les-cinephiles, ptsbao, monikadesign-api, filelisting, moviesite, yggtorrent, selezen, dimeadozen, thegeeks, ebooks-shares, cpasbienclone, bithumen, indietorrents, uhdbits, scenerush 
05-23 13:44:54 Info Loaded 583 indexers in total 
05-23 13:44:54 Info Adding aggregate indexer ('all' indexer) ... 
05-23 13:44:54 Info Adding filter indexer ('type:public' indexer) ... 
05-23 13:44:54 Info Adding filter indexer ('type:private' indexer) ... 
05-23 13:44:54 Info Adding filter indexer ('type:semi-public' indexer) ... 
05-23 13:44:54 Info Jackett startup finished in 272.610 s 
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
05-23 13:45:28 Warn Request to Anidex failed with exception 'Resource temporarily unavailable (anidex.info:443)'. Retrying in 0.5s... (Attempt 1 of 2). 
05-23 13:45:34 Warn Request to Anidex failed with exception 'Resource temporarily unavailable (anidex.info:443)'. Retrying in 1s... (Attempt 2 of 2). 
05-23 13:45:40 Error System.Net.Http.HttpRequestException: Resource temporarily unavailable (anidex.info:443) System.Net.Http.HttpRequestException: Resource temporarily unavailable (anidex.info:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass12_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 508
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 507
   at Jackett.Common.Indexers.Anidex.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anidex.cs:line 199
   at Jackett.Common.Indexers.Anidex.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anidex.cs:line 158
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by hobb7t** [comment]
Ok, i tried to just add the bridge and the Unbound network to this container and now seems to move further. Now while trying to add indexers i get "A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing."

**Comment by ilike2burnthing** [comment]
I'm assuming this happens for multiple indexers, not just Anidex.

As a test, just add a Jackett container. If it works on its own, then this is an issue for Nefarious.

If you're using a VPN or proxy, or a reverse proxy, disable these temporarily to see if it resolves your issue.

You can also try pinging or curl-ing github.com from within the containers to see if it is a general connection issue.

**Comment by hobb7t** [comment]
Well, it seems that the whole situation was triggered because i disabled the IPV6 option on the .env
