### ISSUE TITLE
HDGalaKtik => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14384]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
FlareSolverr
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits
```

### Description

I added indexer successfuly with my user Cookie.
Test giving error.
No result at searching

### Logged Error Messages

```text
Error	
System.Exception: Test search in HDGalaKtik => Found no results while trying to browse this tracker
```

### Screenshots

See full log when I make a test.
[Full log.txt](https://github.com/Jackett/Jackett/files/11582502/Full.log.txt)

**Comment by ilike2burnthing** [comment]
For now, change the account language to English and pull a new cookie - https://www.trackerpmr.com/my.php

I'll have a look later when I have some free time to see if I can make it work with Russian (or all languages), unless someone beats me to it.

**Comment by AARON8888** [comment]
I tested new app version with amendment and it works for me too. 
This issue is solved for my side.

**Comment by AARON8888** [comment]
Hi, I don´t well if the issue is similar to this issue. Anyhow, see below full error log. Regarding language I think not available now English, you can check too.

---

System.Exception: Test search in HDGalaKtik => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.21.2458.0] System.Exception: Test search in HDGalaKtik => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 0
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

**Comment by ilike2burnthing** [comment]
As we've said to you before, please check commits before posting - https://github.com/Jackett/Jackett/commit/27b8d9b964454017152f16b746588876ca1bd260

**Comment by AARON8888** [comment]
@ilike2burnthing Sorry for that.
The problem is that I don´t know where to find updating commits in github. Can you show me, please?

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/commits/master/
