### ISSUE TITLE
[btdigg] (testing) Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.: Parse error

### ISSUE THREAD

**Issue by klover5** [Jackett/Jackett#14390]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.18362.0 (64bit OS)
Environment version: 6.0.16 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.52
```

### Description

BTdigg
Parse error

### Logged Error Messages

```text
Error on 20230528112409 for BTDigg.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult Result, IHtmlDocument document) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 878
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1589

Jackett.Common.IndexerException: Exception (btdigg): Got redirected to another domain. Try changing the indexer URL to https://www.domflow.it/.
```

### Screenshots

https://cdn.discordapp.com/attachments/921248278648086558/1112204835253669950/20230528_112448.png

**Comment by ilike2burnthing** [comment]
> Is there already an issue for your problem?
> - [x] I have checked older issues, open and closed

Liar - https://github.com/Jackett/Jackett/issues/14198
