### ISSUE TITLE
[yggtorrent] (testing) Test search in YGGtorrent => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by ThomasLETELLIER** [Jackett/Jackett#14402]
### Have you checked our Troubleshooting page for your issue?

- [x] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
An error occurred while testing this indexer
Test search in YGGtorrent => Found no results while trying to browse this tracker

It was working fine ~2 days ago (29/05/2023)
```

### Description

- Check of all user parameters (login, password, ...)
- Fixed URL "Site link"
- Tried manual query - No result

### Logged Error Messages

```text
05-31 11:30:01 Info CardigannIndexer (yggtorrent): Relogin required 
05-31 11:30:09 Info CardigannIndexer (yggtorrent): Relogin required 
05-31 11:30:18 Info Test search in YGGtorrent => Found 0 releases [16440ms] 
05-31 11:30:18 Error System.Exception: Test search in YGGtorrent => Found no results while trying to browse this tracker 

[v0.21.88.0] System.Exception: Test search in YGGtorrent => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 322
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ThomasLETELLIER** [comment]
Well, I just confirmed it in my Description: My credentials are good (confirmed by retyping them) and I didn't edited anything since 29/05/2023 where it worked pretty fine.
Last use of Jackett YGGTorrent : 29/05/2023
Today, I can't use it at all and I'm not the only one : It's the 3rd ticket for this tracker. Pretty weird, ngl.

**Comment by ilike2burnthing** [comment]
Working fine here.

> Fixed URL "Site link"

'Fixed' how?

Try the troubleshooting steps here:
https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-selector

Failing that, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by nthduy** [comment]
Update and restart jackett fixed the issue for me

**Comment by ThomasLETELLIER** [comment]
Update and restart jackett fixed the issue for me aswell.
