### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.do/ using form selector #user-login: Parse error

### ISSUE THREAD

**Issue by buddyqc69** [Jackett/Jackett#14408]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-05-31 20:35:52	Error	
Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.do/ using form selector #user-login
2023-05-31 20:35:51	Error	
Error on 20230531203551 for YGGtorrent.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www3.yggtorrent.do/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 597
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1621
```

### Description

i have the right page, now that the login form on YGGT..

that can change anything i think the login page form have changed?

```
<form action="/user/login" method="post" id="user-login">
		<input type="text" name="id" placeholder="Pseudo" required="">
		<input type="password" name="pass" placeholder="Password" required="" autocomplete="off"> 
		<center id="resetpass" style=" margin: 10px 10px;  font-weight: bold;"><a href="https://www3.yggtorrent.do/user/reset_password">Lost Password ?</a></center>
		<input type="hidden" name="ci_csrf_token" value="">
		
										
		<button type="submit">Connection<i class="ico_unlock"></i></button>
	</form>
```

### Logged Error Messages

```text
Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.do/ using form selector #user-login: Parse error
```

**Comment by buddyqc69** [comment]
Oh i will update the release and test again sorry

Envoyé de mon iPhone

Le 31 mai 2023 à 8:55 p.m., garfield69 ***@***.***> a écrit :

﻿

users that have had problem in the last couple days with YGG found that by upgrading their jackett to the very latest version (currently v0.21.90) resolved their problem.
Are you on the latest version?

**Comment by buddyqc69** [comment]
resolved sorry !
