### ISSUE TITLE
[cinemamovies] (updating) Login Failed - can't add indexer

### ISSUE THREAD

**Issue by greg811** [Jackett/Jackett#14403]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.100.2:8191/
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 6.0.16 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.88
```

### Description

Can't add https://cinemamovies.pl indexer
When I put cookie I get error:
 "An error occurred while updating this indexer
Login Failed, got redirected to: https://cinemamovies.pl/login.php?returnto=%2Findex.php"
It worked some time ago

### Logged Error Messages

```text
2023-06-01 11:15:34.5490 Info Request starting HTTP/1.1 GET http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config?_=1685610879526 - - 
2023-06-01 11:15:34.5490 Debug Request is continuing in applying rules. Current url is http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config?_=1685610879526 
2023-06-01 11:15:34.5490 Debug Request is continuing in applying rules. Current url is http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config?_=1685610879526 
2023-06-01 11:15:34.5490 Debug Request is continuing in applying rules. Current url is http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config?_=1685610879526 
2023-06-01 11:15:34.5490 Debug The request path /api/v2.0/indexers/cinemamovies/config does not match a supported file type 
2023-06-01 11:15:34.5490 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2023-06-01 11:15:34.5490 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/cinemamovies/config' 
2023-06-01 11:15:34.5490 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/cinemamovies/config' 
2023-06-01 11:15:34.5490 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' 
2023-06-01 11:15:34.5490 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' 
2023-06-01 11:15:34.5490 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (JackettConsole). 
2023-06-01 11:15:34.5490 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2023-06-01 11:15:34.5490 Debug Execution plan of resource filters (in the following order): None 
2023-06-01 11:15:34.5490 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2023-06-01 11:15:34.5490 Debug Execution plan of exception filters (in the following order): None 
2023-06-01 11:15:34.5490 Debug Execution plan of result filters (in the following order): None 
2023-06-01 11:15:34.5490 Debug Authorization was successful. 
2023-06-01 11:15:34.5490 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2023-06-01 11:15:34.5490 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2023-06-01 11:15:34.5858 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter 
2023-06-01 11:15:34.5858 Debug No information found on request to perform content negotiation. 
2023-06-01 11:15:34.5858 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response. 
2023-06-01 11:15:34.5858 Debug Attempting to select the first formatter in the output formatters list which can write the result. 
2023-06-01 11:15:34.5858 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response. 
2023-06-01 11:15:34.5858 Info Executing OkObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'. 
2023-06-01 11:15:34.5858 Debug The response will be compressed with 'gzip'. 
2023-06-01 11:15:34.5858 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole) in 31.4604ms 
2023-06-01 11:15:34.5858 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' 
2023-06-01 11:15:34.5858 Debug Connection id "0HMR1Q9VDERJ7" completed keep alive response. 
2023-06-01 11:15:34.5858 Info Request finished HTTP/1.1 GET http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config?_=1685610879526 - - - 200 - application/json;+charset=utf-8 43.9909ms 
2023-06-01 11:15:41.4377 Info Request starting HTTP/1.1 POST http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config application/json 521 
2023-06-01 11:15:41.4377 Debug Request is continuing in applying rules. Current url is http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config 
2023-06-01 11:15:41.4377 Debug Request is continuing in applying rules. Current url is http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config 
2023-06-01 11:15:41.4377 Debug Request is continuing in applying rules. Current url is http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config 
2023-06-01 11:15:41.4377 Debug POST requests are not supported 
2023-06-01 11:15:41.4377 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2023-06-01 11:15:41.4431 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/cinemamovies/config' 
2023-06-01 11:15:41.4431 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/cinemamovies/config' 
2023-06-01 11:15:41.4431 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)' 
2023-06-01 11:15:41.4431 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)' 
2023-06-01 11:15:41.4431 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (JackettConsole). 
2023-06-01 11:15:41.4431 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2023-06-01 11:15:41.4431 Debug Execution plan of resource filters (in the following order): None 
2023-06-01 11:15:41.4431 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2023-06-01 11:15:41.4431 Debug Execution plan of exception filters (in the following order): None 
2023-06-01 11:15:41.4431 Debug Execution plan of result filters (in the following order): None 
2023-06-01 11:15:41.4431 Debug Authorization was successful. 
2023-06-01 11:15:41.4431 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2023-06-01 11:15:41.4431 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2023-06-01 11:15:41.4431 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2023-06-01 11:15:41.4431 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2023-06-01 11:15:41.4431 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
2023-06-01 11:15:41.4431 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
2023-06-01 11:15:41.4431 Debug Connection id "0HMR1Q9VDERJ7", Request id "0HMR1Q9VDERJ7:0000000E": started reading request body. 
2023-06-01 11:15:41.4431 Debug Connection id "0HMR1Q9VDERJ7", Request id "0HMR1Q9VDERJ7:0000000E": done reading request body. 
2023-06-01 11:15:41.4431 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2023-06-01 11:15:41.4431 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2023-06-01 11:15:41.4431 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2023-06-01 11:15:41.4431 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2023-06-01 11:15:41.4431 Debug CACHE CleanIndexerCache / Indexer: cinemamovies 
2023-06-01 11:15:41.4431 Debug CACHE PruneCacheByTtl / Pruned queries: 1 
2023-06-01 11:15:41.4431 Debug CACHE Status / Total cached results: 7 
2023-06-01 11:15:41.4802 Debug CardigannIndexer (cinemamovies): Cookies after login: uid=REDACTED; pass=REDACTED; hashv=REDACTED 
2023-06-01 11:15:41.4802 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://cinemamovies.pl/index.php) 
2023-06-01 11:15:41.6543 Debug WebClient(HttpWebClient2): Returning Redirect => https://cinemamovies.pl/login.php?returnto=%2Findex.php 0 bytes 
2023-06-01 11:15:41.6597 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) in 209.8389ms 
2023-06-01 11:15:41.6597 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)' 
2023-06-01 11:15:41.6597 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected to: https://cinemamovies.pl/login.php?returnto=%2Findex.php 

[v0.21.90.0] Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected to: https://cinemamovies.pl/login.php?returnto=%2Findex.php
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 847
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1004
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61


2023-06-01 11:15:43.7195 Debug The response will be compressed with 'gzip'. 
2023-06-01 11:15:43.7195 Debug Connection id "0HMR1Q9VDERJ7" completed keep alive response. 
2023-06-01 11:15:43.7195 Info Request finished HTTP/1.1 POST http://REDACTED:9117/api/v2.0/indexers/cinemamovies/config application/json 521 - 500 - application/json 2283.0996ms 
2023-06-01 11:16:03.3164 Debug Connection id "0HMR1Q9VDERJD" received FIN. 
2023-06-01 11:16:03.3164 Debug Connection id "0HMR1Q9VDERJD" disconnecting. 
2023-06-01 11:16:03.3164 Debug Connection id "0HMR1Q9VDERJD" sending FIN because: "The client closed the connection." 
2023-06-01 11:16:03.3302 Debug Connection id "0HMR1Q9VDERJD" stopped. 
```

### Screenshots
<a href="https://ibb.co/6mkF7jH"><img src="https://i.ibb.co/6mkF7jH/cin-jack.png" alt="cin-jack" border="0" /></a>

**Comment by garfield69** [comment]
@greg811 Please enable enhanced logging and try again in order to capture more data about your problem.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

@ilike2burnthing  is the CinemaMovies_SZ indexer working for you?

**Comment by ilike2burnthing** [comment]
Yep, no issues here.

@greg811 the cookie is IP locked, so if you're using a VPN or proxy, or a seedbox or VPS, you'd need to pull a cookie using its IP. See other common troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-selector

**Comment by greg811** [comment]
@ilike2burnthing thanks, but how to get cookie from a seedbox without web browser?

**Comment by ilike2burnthing** [comment]
See notes section - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

**Comment by greg811** [comment]
I've updated first post to add log

**Comment by garfield69** [comment]
>So I need to add cookie from the same machine as jackett is installed and running?

correct
