### ISSUE TITLE
TorrentLeech now behind CloudFlare

### ISSUE THREAD

**Issue by Locutus64** [Jackett/Jackett#14410]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Loading Native indexers ...
Using HTTP Client: HttpWebClient2
Using FlareSolverr: https://127.0.0.1:8089
Using proxy: Disabled
App config/log directory: /var/lib/jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Arch Linux \r (\l)
Jackett variant: CoreLinuxAmdx64
OS version: Unix 6.3.5.1 (64bit OS) (64bit process)
Environment version: 6.0.16 (/usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.16/)
Jackett Data will be stored in: /var/lib/jackett
Starting Jackett v0.21.97
```

### Description

I didn nothing to produce this problem. TorrentLeech is now using CloudFlare.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (torrentleech): Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:8089)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
```

**Comment by David-Moreira** [comment]
+1 same issue.

**Comment by Locutus64** [comment]
I copied the info directly out of the log file for Jackett.

```
░▒▓ ~  sudo systemctl status flaresolverr
[sudo] password for locutus: 
● flaresolverr.service - FlareSolverr
     Loaded: loaded (/usr/lib/systemd/system/flaresolverr.service; enabled; preset: disabled)
     Active: active (running) since Thu 2023-06-01 15:22:56 PDT; 17h ago
   Main PID: 2120 (python)
      Tasks: 6 (limit: 28683)
     Memory: 60.3M
        CPU: 4.733s
     CGroup: /system.slice/flaresolverr.service
             ├─2120 /usr/bin/python /opt/flaresolverr/flaresolverr.py
             └─2129 Xvfb :1541643465 -screen 0 800x680x24

Jun 01 15:22:56 Unimatrix-Zero systemd[1]: Started FlareSolverr.
Jun 01 15:22:56 Unimatrix-Zero flaresolverr[2120]: 2023-06-01 15:22:56 INFO     FlareSolverr 3.1.2
Jun 01 15:22:56 Unimatrix-Zero flaresolverr[2120]: 2023-06-01 15:22:56 INFO     Testing web browser installation...
Jun 01 15:22:56 Unimatrix-Zero flaresolverr[2120]: 2023-06-01 15:22:56 INFO     Platform: Linux-6.3.5-arch1-1-x86_64-with-glibc2.37
Jun 01 15:22:56 Unimatrix-Zero flaresolverr[2120]: 2023-06-01 15:22:56 INFO     Chrome / Chromium path: /usr/bin/chromium
Jun 01 15:22:56 Unimatrix-Zero flaresolverr[2120]: 2023-06-01 15:22:56 INFO     Chrome / Chromium major version: 114
Jun 01 15:22:56 Unimatrix-Zero flaresolverr[2120]: 2023-06-01 15:22:56 INFO     Launching web browser...
Jun 01 15:22:58 Unimatrix-Zero flaresolverr[2120]: 2023-06-01 15:22:58 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Sa>
Jun 01 15:22:58 Unimatrix-Zero flaresolverr[2120]: 2023-06-01 15:22:58 INFO     Test successful!
Jun 01 15:22:58 Unimatrix-Zero flaresolverr[2120]: 2023-06-01 15:22:58 INFO     Serving on http://0.0.0.0:8191
lines 1-21/21 (END)
```

**Comment by Locutus64** [comment]
Yea I was under the impression that that's always 8089. I'm assuming it's something with TorrentLeech now since my other indexers are working and if I go directly to TL after the initial CloudFlare check I get taken to the login.

**Comment by fedonr** [comment]
Yes it is behind Cloudflare now bit works well with Flaresolverr using it already.

**Comment by garfield69** [comment]
@Locutus64  I also had this issue initially. But by using the JAckett dashboard to open the config and selecting OKAY it refreshed the cookies with the cloudflare pass, and now I can use the indexer without issues.

**Comment by Locutus64** [comment]
@garfield69 no love with that, but I did get a error message that points to Flaresloverr so I added my infor and the error message to a ticket about TorrentLeech that was opened earlier.

**Comment by garfield69** [comment]
which ticket?

**Comment by ilike2burnthing** [comment]
Error from https://github.com/FlareSolverr/FlareSolverr/issues/794#issuecomment-1574392084:

```text
Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing. ---> System.TimeoutException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled. at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) --- End of inner exception stack trace --- --- End of inner exception stack trace --- at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at FlareSolverrSharp.Solvers.FlareSolverr.<>c__Dis
```

Add TorrentQQ, test. Does it work? If not, what's the error? If it does though, does FlareSolverr show it being processed?

**Comment by garfield69** [comment]
I often need more than 60 secs to get past cloudflare these days so I've set my Jackett dashboard `FlareSolverr Max Timeout (ms):` setting to `70000`

**Comment by Locutus64** [comment]
Will give that a shot if I run into the issue again. For now I got around it by changing the url for TL in Jackett to https://www.tlgetin.cc . Now as for 8089 vs 8191 either works, but indexers take longer to pass their test using 8191.

**Comment by DyonR** [comment]
> Will give that a shot if I run into the issue again. For now I got around it by changing the url for TL in Jackett to https://www.tlgetin.cc . Now as for 8089 vs 8191 either works, but indexers take longer to pass their test using 8191.

I was a bit skeptical to change the URL to something that could be a fake website. According to their forums it's indeed a legit mirror: https://forums.torrentleech.org/t/issues-connecting-to-the-website/17734/2  
It's referenced by a Super Admin on this page, so should be good: https://forums.torrentleech.org/t/tl-mirrors-and-alternative-accessing-methods/81341  
Alternative mirrors:  
https://torrentleech.cc/  
https://torrentleech.me/  
and as mentioned before https://tlgetin.cc/

**Comment by garfield69** [comment]
v0.21.157
