### ISSUE TITLE
[hdtorrents] (updating) Test search in HD-Torrents => Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by fedonr** [Jackett/Jackett#14417]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Variant : Docker Container v0.21.114
Environment : Linux Amd64
```

### Description

This is same for all 4 links.

HD-torrents either gives error message stating : Test search in HD-Torrents => Found no results while trying to browse this tracker.

While out of 100 tries it also gave error like "Can't login" for 2 times out of 100.

While I challenges in FlareSolverr are solved. 

2023-06-03 18:20:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 155000, 'cmd': 'request.get', 'url': 'https://hd-torrents.net/login.php'}
2023-06-03 18:20:49 INFO     Challenge detected. Title found: Just a moment...
2023-06-03 18:21:21 INFO     Challenge solved!
2023-06-03 18:21:22 INFO     Response in 41.718 s
2023-06-03 18:21:22 INFO     172.17.0.1 POST http://192.168.x.x:8191/v1 200 OK

### Logged Error Messages

```text
06-03 23:51:24 Info Test search in HD-Torrents => Found 0 releases [635ms] 
06-03 23:51:24 Error System.Exception: Test search in HD-Torrents => Found no results while trying to browse this tracker 
[v0.21.114.0] System.Exception: Test search in HD-Torrents => Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 323
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 113
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by fedonr** [comment]
Yes I did

**Comment by fedonr** [comment]
Oh! Okay so that is an issue, I was aware that they do not have any 100% FL as of now, but I thought they do support it and only for time being it was not there, as they do mention that FreeLeech 100% in the tags chart along with others like no ratio,25,50, and 75.

**Comment by fedonr** [comment]
Yes, it was not referring to Jackett, I was referring to the HD-torrents itself, as they mention it in their Tags Chart, which is the core reason I enabled it in Jackett as well. So they should be the one to remove it.

**Comment by fedonr** [comment]
Thanks a lot tho, it works after removing it. I would be closing this issue.

Have a great time. And thank you once again.
