### ISSUE TITLE
[torrentleech] (testing) Exception (torrentleech): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.: Error Parsing Json Response

### ISSUE THREAD

**Issue by jmseaton** [Jackett/Jackett#14442]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-06-10 12:56:57.9567 Info Starting Jackett v0.21.186
2023-06-10 12:56:58.6048 Info Environment version: 6.0.16 (/app/Jackett/)
2023-06-10 12:56:58.6138 Info OS version: Unix 5.15.0.73 (64bit OS) (64bit process)
2023-06-10 12:56:58.6138 Info Jackett variant: CoreLinuxAmdx64
2023-06-10 12:56:58.6138 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2023-06-10 12:56:58.6138 Info Running in Docker: Yes (image build: v0.20.2357-ls86)
2023-06-10 12:56:58.6169 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-06-10 12:56:58.6169 Info App config/log directory: /config/Jackett
2023-06-10 12:56:58.6169 Info Using proxy: Disabled
2023-06-10 12:56:58.6169 Info Using FlareSolverr: http://192.168.1.69:8191
2023-06-10 12:56:58.6169 Info Using HTTP Client: HttpWebClient2
```

### Description

I have flaresolverr installed after noticing issues with torrentleech.  Now getting a parsing error when testing.  Log attached, error near the end.

[log.txt](https://github.com/Jackett/Jackett/files/11712892/log.txt)

### Logged Error Messages

```text
2023-06-10 12:51:39.2966 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2023-06-10 12:51:39.2966 Error Jackett.Common.IndexerException: Exception (torrentleech): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

[v0.21.186.0] Jackett.Common.IndexerException: Exception (torrentleech): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
 ---> System.Exception: Error Parsing Json Response
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json)
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1482
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1500
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 701
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 315
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

N/A

**Comment by garfield69** [comment]
I have managed to turn on enhanced logging before starting a TEST of the torrentleech indexer and was able to capture the content of the unexpected response that the torrentleech  site is returning.
So Jackett makes the following query:
```
Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.torrentleech.org/torrents/browse/list/exact/1/query//newfilter/2/orderby/added/order/desc)
```
and torrentleech returns the following response:
```
Unexpected response content (11449 bytes): <!DOCTYPE html>
<html lang="en" class="html-lights-off">
<head>
    <title>Login :: TorrentLeech.org</title>    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="TorrentLeech">
    <meta name="keywords" content="torrent">
<link href="/common.bb4b12dd35e928acca0e7c6b48f92ae6.css" rel="stylesheet"><link href="/access.cfc1329524b72d5815847e3d9cb82cc7.css" rel="stylesheet"></head>

<body class="tl-lights-off">

<div id="site-wrapper">
    <div id="site-canvas">

        <div class="navbar navbar-default tl">
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <a class="navbar-brand" href="/"></a>
                    </li>
                </ul>
                <ul class="guest-chat nav navbar-nav navbar-right">
                    <li>
                        <a href="/user/chat/guest" title="Guest Chat">
                            <i class="fa fa-comments-o large-fonts"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <a class="toggle-news" title="Latest News" href="#"><i class="fa fa-newspaper-o large-fonts"></i></a>

        <div class="container access-page">
            <div class="row">
                <div class="login-container col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
                    <section class="login">
                        <div class="text-center">
                            <h2 class="title">Login</h2>
                        </div>
                                                <form name="login-form" method="post" action="/user/account/login/">
                            <input type="text" class="form-control" name="username" value="" placeholder="Username">
                            <input type="password" class="form-control" name="password" placeholder="Password">
                            
                            <div class="form-group text-center">
                                <button type="submit" class="btn tl-btn btn-primary action">
                                    Log in
                                </button>
                            </div>
                            <div class="form-group text-center mt-20">
                                <a class="btn tl-btn btn-primary" href="/user/account/promoreg" >SIGN UP PROMO</a>
                            </div>
                            <div class="text-center">
                                <a href="/user/account/lostpassword" >Lost Password</a>
                            </div>
                            <div class="text-center">
                                <a href="/user/account/signup">Signup With Invite</a>
                            </div>
                        </form>
                    </section>
                </div>
            </div>
            <div class="container seedit4me_image">
                <div class="login-banner col-xs-12 col-sm-6 col-md-4 col-sm-offset-1 col-md-offset-2">
                    <a href="https://billing.seedit4.me/aff.php?aff=4/" target="_blank"><img src="/images/seedit4me.png" title="Seedit4.me banner" alt="Seedit4.me banner"></a>
                </div>
            </div>
        </div>



        <div class="footer-login">

            <div class="footer-inner-login">
                <h5 class="footer-title">Visit Our Friends</h5>
                <ul class="list-inline list-pipe">
                    <li>
                        <a href="https://truevpnreviews.net/" target="_blank"><img src="/images/truevpnreviews.png" title="True VPN Reviews" alt="True VPN Reviews" width="16" height="16">  TrueVPNReviews.net</a>
                    </li>
                    <li>
                        <a href="https://billing.seedit4.me/aff.php?aff=4/" target="_blank"><img src="/images/seedit4me-icon.png" title="Seedit4.me" alt="Seedit4.me" width="16" height="16">Seedit4.me</a>
                    </li>
                </ul>
            </div>
        </div>

        <div id="site-news">
            <div class="site-news-inner">
                <h3 class="site-news-header text-center">
                    Latest News
                </h3>

                <ul class="mt-30 list-unstyled">
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The REFUGEERARBG invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>June 9th 2023</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>REFUGEERARBG Invitation Code</h4>
                            <p class="body">
                                <p>A few hours ago, RARBG closed its gates forever, leaving lot of people without a place they can call ”home”. For a very limited time, use code REFUGEERARBG and come be part of our family! </p><p><br></p><p>On top of that, you will get 15 GB of upload to help you start your journey!</p><p><br></p><p>Welcome aboard, and we hope you will feel like home <3</p><p><br></p><p>TL Staff</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>May 31st 2023</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The SPRING2023 invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>May 26th 2023</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>SPRING2023 Invitation Code</h4>
                            <p class="body">
                                <p>Spring is here! Apart from the nice, warm temperatures, what about an invite giveaway??))</p><p><br></p><p>Use invite code SPRING2023 in the sign up form http://www.torrentleech.org/user/account/signup and enjoy your new account! As cherry on top, you'll find your account with 15GB upload credit to help you start your epic journey! HURRY UP! For the first 10k people only!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>April 23rd 2023</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The HAPPY2023 invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>January 10th 2023</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>HAPPY2023 Invitation code</h4>
                            <p class="body">
                                <p>Christmas and the New Year are near... Best way to celebrate it..? What about a New Year invite giveaway??</p><p><br></p><p>Use invite code HAPPY2023 in the sign up form <a href="https://www.torrentleech.org/user/account/signup" target="_blank" style="color: rgb(151, 143, 143);">https://www.torrentleech.org/user/account/signup</a> and enjoy your new account! As cherry on top, you'll find your account with 15GB upload credit to help you start your epic journey! HURRY UP! For the first 10k people only!</p><p><br></p><p>Merry Christmas and a Happy New Year!!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>December 19th 2022</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The WINTERISCOMING invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>September 20th 2022</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>WINTERISCOMING invitation code</h4>
                            <p class="body">
                                <p>Happy new month! Or shall we say - happy winter? =D</p><p><br></p><p>Use invite code WINTERISCOMING in the sign up form <a href="https://www.torrentleech.org/user/account/signup" target="_blank">https://www.torrentleech.org/user/account/signup</a> and enjoy your new account! As cherry on top, you'll find your account with 15GB upload credit to help you start your epic journey! HURRY UP! For the first 10k people only!</p><p><br></p><p>Enjoy the winter!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>September 1st 2022</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>Invitation giveaway expired</h4>
                            <p class="body">
                                <p>The XMAS2021 invitation code is now officially expired. Welcome to all our new members!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>January 16th 2022</span></div>
                        </li>
                                            <li class="news-item">
                            <h4>XMAS2021 invitation code</h4>
                            <p class="body">
                                <p>Christmas is near... Best way to celebrate it..? What about a Christmas invite giveaway??</p><p><br></p><p>Use invite code XMAS2021 in the sign up form <a href="https://www.torrentleech.org/user/account/signup" target="_blank">https://www.torrentleech.org/user/account/signup</a> and enjoy your new account! As cherry on top, you'll find your account with 15GB upload credit to help you start your epic journey! HURRY UP! For the first 10k people only!</p><p><br></p><p>Merry Christmas and Happy holidays!!!</p>                            </p>
                            <div class="text-right"><i class="fa fa-clock-o"></i><span>December 4th 2021</span></div>
                        </li>
                                    </ul>
            </div>
        </div>
    </div>
</div>

<script src='https://www.google.com/recaptcha/api.js'></script>
<script type="text/javascript" src="/common.f5c98e02db73ef10a549.js"></script><script type="text/javascript" src="/access.841bc815ab7ce1087ba6.js"></script></body>
</html>
```

looks like torrentleech is forcing a notification in front of the torrents browse
repeating the TEST a second and third time returns the expected response, so it appears to be a daily event.

**Comment by garfield69** [comment]
@jmseaton  Your enhanced  log shows a similar event to what I got when I tried a keywordless search
for now simply retry your search or TEST and you should get results until the next time torrentleech post that notice in front of the results.
We will think on how to handle this event. For now Cardigann does not have a handler for this event. 
We could use the existing  `noResultsMessage` statement but this would me that the indexer would return a no-results-found  at least once a day.
Ideally we could create a retryWhenResultsContains statement and simply repeat the query a second time.
Jackett Team, I'm open to suggestions.

**Comment by garfield69** [comment]
Actually, the response looks like a login page, except that normally we would get a 302 redirect to login (which cardigann would spot and perform the login and retry the query) and instead we are simply seeing a 200 OK 

And the next query for me succeeds without having to login again so that is why I think its more in line with a notice.

@jmseaton  does the Jackett indexer succeed to give results eventually and the second attempt (like it did for me) or is it always failing until you open the config and click Okay to perform a login?

**Comment by jmseaton** [comment]
Thanks for the fix!  Sorry I wasn't around to respond yesterday.

**Comment by garfield69** [comment]
v0.21.203
