### ISSUE TITLE
[lostfilm] (testing) Exception (lostfilm): certificate validation failed: [Subject]  CN=buildchain.system76.com[Issuer]  CN=buildchain.system76.com[Serial Number]  1C4255B499063F0BFD0084F84E00AD7CB887EF7B[Not Before]  8/10/2022 10:32:29 PM[Not After]  8/7/2032 10:32:29 PM[Thumbprint]  32ABC8014C3D94661AF3FE6287CC8EC7C665CC2A: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by gelato** [Jackett/Jackett#14440]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-06-08 22:13:49 	Info 	Using HTTP Client: HttpWebClient2
2023-06-08 22:13:49 	Info 	Using FlareSolverr: http://localhost:8191/
2023-06-08 22:13:49 	Info 	Using proxy: Disabled
2023-06-08 22:13:49 	Info 	App config/log directory: /home/vanholder/.config/Jackett
2023-06-08 22:13:49 	Info 	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-06-08 22:13:49 	Info 	Running in Docker: No
2023-06-08 22:13:49 	Info 	File /etc/issue: Pop!_OS 22.04 LTS \n \l
2023-06-08 22:13:49 	Info 	Jackett variant: CoreLinuxAmdx64
2023-06-08 22:13:49 	Info 	OS version: Unix 6.2.6.76060206 (64bit OS) (64bit process)
2023-06-08 22:13:49 	Info 	Environment version: 6.0.16 (/home/vanholder/Jackett/)
2023-06-08 22:13:48 	Info 	Starting Jackett v0.21.177
```

### Description

Lostfilm tracker is not working due to certificate error

### Logged Error Messages

```text
Jun  8 22:11:19 laik jackett.vanholder[894]: 06-08 22:11:19 Warn Request to LostFilm.tv failed with exception 'The SSL connection could not be established, see inner exception.'. Retrying in 0.5s... (Attempt 1 of 2).
Jun  8 22:11:20 laik jackett.vanholder[894]: 06-08 22:11:20 Warn Request to LostFilm.tv failed with exception 'The SSL connection could not be established, see inner exception.'. Retrying in 1s... (Attempt 2 of 2).
Jun  8 22:11:21 laik jackett.vanholder[894]: 06-08 22:11:21 Error Jackett.Common.IndexerException: Exception (lostfilm): certificate validation failed: [Subject]
Jun  8 22:11:21 laik jackett.vanholder[894]:   CN=buildchain.system76.com
Jun  8 22:11:21 laik jackett.vanholder[894]: [Issuer]
Jun  8 22:11:21 laik jackett.vanholder[894]:   CN=buildchain.system76.com
Jun  8 22:11:21 laik jackett.vanholder[894]: [Serial Number]
Jun  8 22:11:21 laik jackett.vanholder[894]:   1C4255B499063F0BFD0084F84E00AD7CB887EF7B
Jun  8 22:11:21 laik jackett.vanholder[894]: [Not Before]
Jun  8 22:11:21 laik jackett.vanholder[894]:   8/10/2022 10:32:29 PM
Jun  8 22:11:21 laik jackett.vanholder[894]: [Not After]
Jun  8 22:11:21 laik jackett.vanholder[894]:   8/7/2032 10:32:29 PM
Jun  8 22:11:21 laik jackett.vanholder[894]: [Thumbprint]
Jun  8 22:11:21 laik jackett.vanholder[894]:   32ABC8014C3D94661AF3FE6287CC8EC7C665CC2A
Jun  8 22:11:21 laik jackett.vanholder[894]:
Jun  8 22:11:21 laik jackett.vanholder[894]: [v0.21.177.0] Jackett.Common.IndexerException: Exception (lostfilm): certificate validation failed: [Subject]
Jun  8 22:11:21 laik jackett.vanholder[894]:   CN=buildchain.system76.com
Jun  8 22:11:21 laik jackett.vanholder[894]: [Issuer]
Jun  8 22:11:21 laik jackett.vanholder[894]:   CN=buildchain.system76.com
Jun  8 22:11:21 laik jackett.vanholder[894]: [Serial Number]
Jun  8 22:11:21 laik jackett.vanholder[894]:   1C4255B499063F0BFD0084F84E00AD7CB887EF7B
Jun  8 22:11:21 laik jackett.vanholder[894]: [Not Before]
Jun  8 22:11:21 laik jackett.vanholder[894]:   8/10/2022 10:32:29 PM
Jun  8 22:11:21 laik jackett.vanholder[894]: [Not After]
Jun  8 22:11:21 laik jackett.vanholder[894]:   8/7/2032 10:32:29 PM
Jun  8 22:11:21 laik jackett.vanholder[894]: [Thumbprint]
Jun  8 22:11:21 laik jackett.vanholder[894]:   32ABC8014C3D94661AF3FE6287CC8EC7C665CC2A
Jun  8 22:11:21 laik jackett.vanholder[894]:  ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
Jun  8 22:11:21 laik jackett.vanholder[894]:  ---> System.Exception: certificate validation failed: [Subject]
Jun  8 22:11:21 laik jackett.vanholder[894]:   CN=buildchain.system76.com
Jun  8 22:11:21 laik jackett.vanholder[894]: [Issuer]
Jun  8 22:11:21 laik jackett.vanholder[894]:   CN=buildchain.system76.com
Jun  8 22:11:21 laik jackett.vanholder[894]: [Serial Number]
Jun  8 22:11:21 laik jackett.vanholder[894]:   1C4255B499063F0BFD0084F84E00AD7CB887EF7B
Jun  8 22:11:21 laik jackett.vanholder[894]: [Not Before]
Jun  8 22:11:21 laik jackett.vanholder[894]:   8/10/2022 10:32:29 PM
Jun  8 22:11:21 laik jackett.vanholder[894]: [Not After]
Jun  8 22:11:21 laik jackett.vanholder[894]:   8/7/2032 10:32:29 PM
Jun  8 22:11:21 laik jackett.vanholder[894]: [Thumbprint]
Jun  8 22:11:21 laik jackett.vanholder[894]:   32ABC8014C3D94661AF3FE6287CC8EC7C665CC2A
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Utils.Clients.HttpWebClient2.ValidateCertificate(HttpRequestMessage request, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 53
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.ConnectHelper.<>c__DisplayClass1_0.<SetUpRemoteCertificateValidationCallback>b__0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    --- End of inner exception stack trace ---
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 186
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 531
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass12_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 508
Jun  8 22:11:21 laik jackett.vanholder[894]: --- End of stack trace from previous location ---
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 507
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 438
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Indexers.LostFilm.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 249
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 312
Jun  8 22:11:21 laik jackett.vanholder[894]:    --- End of inner exception stack trace ---
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 330
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 701
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 315
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 132
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
Jun  8 22:11:21 laik jackett.vanholder[894]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
The certificate presented is from system76 a colorado notebook, desktop and server provider.
Since this is not an official CA from the lostfilm sites, the only conclusion is that you are being blocked by your router or ISP or something.
Have you tried any of the other alternate links in the lostfilm config?
Remember that you may have to open and close the config at least once whenever the prior site has loaded a captcha challenge for you to fill, since, once you change the sitelink to an alternate you need to load its own new challenge by opening the config afresh with the new site link already loaded..
