### ISSUE TITLE
[req]: Panda

### ISSUE THREAD

**Issue by Altansar69** [Jackett/Jackett#14474]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Panda
- URL: https://pandapt.net/
- Description: Panda is a CHINESE Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): Have good ratio
- Additional Comments: Actually open, no exam
- Engine: NexusPHP 1.8.4 (2023-06-13)
```

**Comment by garfield69** [comment]
There is now an exam!!!
UL 30GB, DL 30GB, Bonus 1000

**Comment by ilike2burnthing** [comment]
Of course... 🙄

**Comment by garfield69** [comment]
v0.21.258

**Comment by ilike2burnthing** [comment]
I'm getting no results found due to DateTime parsing (it's picking up comments instead):

```text
CardigannIndexer (panda): Error while parsing row '
<tr>
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=405">
			<img class="c_anime" src="pic/cattrans.gif" alt="动漫" title="动漫" style="background-image: url(pic/category/panda/panda/Animations.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left" style="padding: 0px">
		<table class="torrentname" width="100%">
			<tbody>
				<tr>
					<td class="embedded" style="text-align: center;width: 46px;height: 46px">
						<img src="pic/misc/spinner.svg" data-src="https://m.media-amazon.com/images/M/MV5BZGQ5ZjhhZTktNWUyMy00ZWU0LWEwNDAtYjIzZTY4MjVhN2ZhXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg" class="nexus-lazy-load" style="max-height: 46px;max-width: 46px">
					</td>
					<td class="embedded" style="padding-left: 5px">
						<a title="ID Invaded 2020 BDRip 1080p HEVC FLAC-Snow-Raws" href="details.php?id=(removed)&amp;hit=1">
							<b>ID Invaded 2020 BDRip 1080p HEVC FLAC-Snow-Raws</b>
						</a>
						<b>[<font class="hot">热门</font>]</b>
						<img class="pro_free2up" src="pic/trans.gif" alt="2X Free" title="2X免费">
						<span style="margin-left: 6px" title="未审">
							<svg t="1655184824967" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="34118" width="16" height="16">
								<path d="M450.267 772.245l0 92.511 92.511 0 0-92.511L450.267 772.245zM689.448 452.28c13.538-24.367 20.311-50.991 20.311-79.875 0-49.938-19.261-92.516-57.765-127.713-38.517-35.197-90.114-52.8-154.797-52.8-61.077 0-110.191 16.4-147.342 49.188-37.16 32.798-59.497 80.032-67.014 141.703l83.486 9.927c7.218-46.025 22.41-79.875 45.576-101.533 23.166-21.665 52.047-32.494 86.647-32.494 35.802 0 66.038 11.957 90.711 35.874 24.667 23.92 37.01 51.675 37.01 83.266 0 17.451-4.222 33.55-12.642 48.284-8.425 14.747-26.698 34.526-54.83 59.346s-47.607 43.701-58.442 56.637c-14.741 17.754-25.424 35.354-32.037 52.797-9.028 23.172-13.537 50.701-13.537 82.584 0 5.418 0.146 13.539 0.45 24.374l78.069 0c0.599-32.495 2.855-55.966 6.772-70.4 3.903-14.44 9.926-27.229 18.047-38.363 8.127-11.123 25.425-28.43 51.901-51.895C649.43 506.288 675.908 476.656 689.448 452.28L689.448 452.28z" p-id="34119" fill="#e78d0f"></path>
							</svg>
						</span>
						<br>异度侵入 | イド：インヴェイデッド | 转自天雪</td>
					<td class="embedded" style="text-align: right; width: 40px;padding: 4px">
						<div style="display: flex;flex-direction: column">
							<div style="display: flex;align-content: center;justify-content: space-between;padding: 2px 0">
								<img src="pic/imdb2.png" alt="imdb" title="imdb" style="max-width: 16px;max-height: 16px">
								<span>N/A</span>
							</div>
							<div style="display: flex;align-content: center;justify-content: space-between;padding: 2px 0">
								<img src="pic/douban2.png" alt="douban" title="douban" style="max-width: 16px;max-height: 16px">
								<span>9.1</span>
							</div>
						</div>
					</td>
					<td width="20" class="embedded" style="text-align: right;padding-right: 5px" valign="middle">
						<a href="download.php?id=(removed)">
							<img class="download" src="pic/trans.gif" style="padding-bottom: 2px;" alt="download" title="下载本种">
						</a>
						<br>
						<a id="bookmark99" href="javascript: bookmark(834,99);">
							<img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="收藏">
						</a>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow">
		<a href="comment.php?action=add&amp;pid=(removed)&amp;type=torrent" title="添加评论">0</a>
	</td>
	<td class="rowfollow nowrap">
		<span title="2023-06-19 14:37:16">8时<br>35分钟</span>
	</td>
	<td class="rowfollow">17.15<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">21</a>
		</b>
	</td>
	<td class="rowfollow">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#leechers">7</a>
		</b>
	</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>44</b>
		</a>
	</td>
	<td class="rowfollow">
		<span class="nowrap">
			<a href="https://pandapt.net/userdetails.php?id=(removed)" class="User_Name">
				<b>btbr</b>
			</a>
		</span>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=0 +08:00: DateTime parsing failed for "0 +08:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 197
 ---> System.Exception: DateTime parsing failed for "0 +08:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 197
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 225
   at Jackett.Common.Indexers.CardigannIndexer.ParseFields(String value, String FieldName, ReleaseInfo release, List`1 FieldModifiers, Uri searchUrlUri) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 2307
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1799
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1809
```

@garfield69 are you seeing the same, or have I somehow changed the layout?

**Comment by garfield69** [comment]
Mea Culpa.
I acciddentally turned off comments in my tracker profile and for some reason it never occurred to me at the time I was creating the indexer to question why the selectors were off by one from the normal template. Duh.
Fixed.

**Comment by garfield69** [comment]
v0.21.265

**Comment by ilike2burnthing** [comment]
https://pandapt.net/ - HTTP ERROR 500

**Comment by ilike2burnthing** [comment]
Now redirected to Baidu. I don't have an active session in browser and I tried more than once in Jackett, so don't have the backup json with the cookie. @garfield69 any better luck than me? I'm assuming they've just gone silent.

**Comment by garfield69** [comment]
MY session is still good. the site is online. I'll switch the indexer to the cookie method.

**Comment by garfield69** [comment]
v0.24.1779
