### ISSUE TITLE
[avistaz] (testing) Exception (avistaz): Invalid status code 503 (ServiceUnavailable) received from indexer: Invalid status code 503 (ServiceUnavailable) received from indexer

### ISSUE THREAD

**Issue by gertz22** [Jackett/Jackett#14486]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
no proxy
docker: no
system: debian11
only avistaz not working
```

### Description

click on test, on latest branch

### Logged Error Messages

```text
Jun 20 14:17:37 jacket jackett[724461]: 06-20 14:17:37 Warn Request to AvistaZ failed with status ServiceUnavailable. Retrying in 0.5s... (Attempt 1 of 2).
Jun 20 14:17:40 jacket jackett[724461]: 06-20 14:17:40 Warn Request to AvistaZ failed with status ServiceUnavailable. Retrying in 1s... (Attempt 2 of 2).
Jun 20 14:17:43 jacket jackett[724461]: 06-20 14:17:43 Error Jackett.Common.IndexerException: Exception (avistaz): Invalid status code 503 (ServiceUnavailable) received from i                                                              ndexer
Jun 20 14:17:43 jacket jackett[724461]: [v0.21.265.0] Jackett.Common.IndexerException: Exception (avistaz): Invalid status code 503 (ServiceUnavailable) received from indexer
Jun 20 14:17:43 jacket jackett[724461]:  ---> System.Exception: Invalid status code 503 (ServiceUnavailable) received from indexer
Jun 20 14:17:43 jacket jackett[724461]:    at Jackett.Common.Indexers.Abstract.AvistazTracker.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Abstract/AvistazTra                                                              cker.cs:line 201
Jun 20 14:17:43 jacket jackett[724461]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseI                                                              ndexer.cs:line 312
Jun 20 14:17:43 jacket jackett[724461]:    --- End of inner exception stack trace ---
Jun 20 14:17:43 jacket jackett[724461]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseI                                                              ndexer.cs:line 330
Jun 20 14:17:43 jacket jackett[724461]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/Ba                                                              seIndexer.cs:line 701
Jun 20 14:17:43 jacket jackett[724461]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line                                                               317
Jun 20 14:17:43 jacket jackett[724461]:    at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper,                                                               ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker                                                               invoker, ValueTask`1 actionResultValueTask)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvo                                                              ker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isComplet                                                              ed)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker i                                                              nvoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task                                                               lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposa                                                              ble scope)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposa                                                              ble scope)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logg                                                              er)
Jun 20 14:17:43 jacket jackett[724461]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jun 20 14:17:43 jacket jackett[724461]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHa                                                              ndler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
If you're going to tick a box that says you checked older issues, I suggest actually doing so - https://github.com/Jackett/Jackett/issues/13573

**Comment by gertz22** [comment]
I read issues 3 month back when its work last week I didn't expect to go further
