### ISSUE TITLE
[privatehd] (testing) Exception (privatehd): Invalid status code 503 (ServiceUnavailable) received from indexer: Invalid status code 503 (ServiceUnavailable) received from indexer

### ISSUE THREAD

**Issue by BogartBme** [Jackett/Jackett#14481]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using Unraid Server and docker LINUXSERVER.IO - JACKETT

06-19 10:58:22 Warn Request to PrivateHD failed with status ServiceUnavailable. Retrying in 0.5s... (Attempt 1 of 2).

06-19 10:58:25 Warn Request to PrivateHD failed with status ServiceUnavailable. Retrying in 1s... (Attempt 2 of 2).

06-19 10:58:28 Error Jackett.Common.IndexerException: Exception (privatehd): Invalid status code 503 (ServiceUnavailable) received from indexer


[v0.21.258.0] Jackett.Common.IndexerException: Exception (privatehd): Invalid status code 503 (ServiceUnavailable) received from indexer
---> System.Exception: Invalid status code 503 (ServiceUnavailable) received from indexer
at Jackett.Common.Indexers.Abstract.AvistazTracker.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Abstract/AvistazTracker.cs:line 201
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
--- End of inner exception stack trace ---
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 701
at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 317
at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Description

When I test the indexer in Jacket for PrivateHD this morning after applying docker update I get
 An error occurred while testing this indexer
Exception (privatehd): Invalid status code 503 (ServiceUnavailable) received from indexer: Invalid status code 503 (ServiceUnavailable) received from indexer

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (privatehd): Invalid status code 503 (ServiceUnavailable) received from indexer: Invalid status code 503 (ServiceUnavailable) received from indexer
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13573
