### ISSUE TITLE
(testing) Exception (1337x): A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply...: A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply. (1337x.to:443)

### ISSUE THREAD

**Issue by chasit** [Jackett/Jackett#14509]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Info Starting Jackett v0.21.327 
Jackett service start 
Info Starting Jackett v0.21.327 
Info Environment version: 6.0.19 (C:\ProgramData\Jackett\) 
Info OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS) 
Info Jackett variant: CoreWindows 
Info Running in Docker: No 
Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
Info App config/log directory: C:\ProgramData\Jackett 
Info Using proxy: Disabled 
Info Using FlareSolverr: No 
Info Using HTTP Client: HttpWebClient2 
Info Loading Native indexers ... 
Info Loaded 76 Native indexers. 
Info Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, C:\ProgramData\Jackett\Definitions 
Info Loaded 514 Cardigann indexers. 
Info Loaded 590 indexers in total 
Info Adding aggregate indexer ('all' indexer) ... 
Info Adding filter indexer ('type:public' indexer) ... 
Info Adding filter indexer ('type:private' indexer) ... 
Info Adding filter indexer ('type:semi-public' indexer) ... 
Info Jackett startup finished in 1.799 s
```

### Description

I am unable to access some indexers. Both give the same output.
Both indexers are available through a normal browser. 

Using FlareSolverr has no impact on the outcome, the same error message is shown.

### Logged Error Messages

```text
2023-06-27 12:01:43.2403 Info Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/1337x/test - 0 
2023-06-27 12:01:43.2403 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/1337x/test 
2023-06-27 12:01:43.2403 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/1337x/test 
2023-06-27 12:01:43.2403 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/1337x/test 
2023-06-27 12:01:43.2403 Debug POST requests are not supported 
2023-06-27 12:01:43.2403 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2023-06-27 12:01:43.2403 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/1337x/test' 
2023-06-27 12:01:43.2403 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/1337x/test' 
2023-06-27 12:01:43.2403 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' 
2023-06-27 12:01:43.2403 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' 
2023-06-27 12:01:43.2403 Info Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (JackettConsole). 
2023-06-27 12:01:43.2403 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2023-06-27 12:01:43.2403 Debug Execution plan of resource filters (in the following order): None 
2023-06-27 12:01:43.2403 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2023-06-27 12:01:43.2403 Debug Execution plan of exception filters (in the following order): None 
2023-06-27 12:01:43.2403 Debug Execution plan of result filters (in the following order): None 
2023-06-27 12:01:43.2403 Debug Authorization was successful. 
2023-06-27 12:01:43.2403 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2023-06-27 12:01:43.2403 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2023-06-27 12:01:43.2403 Debug CACHE IsCacheEnabled => false 
2023-06-27 12:01:43.2403 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://1337x.to/cat/Movies/time/desc/1/) 
2023-06-27 12:02:04.3415 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 21094.9488ms 
2023-06-27 12:02:04.3415 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' 
2023-06-27 12:02:04.3415 Error Jackett.Common.IndexerException: Exception (1337x): A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply. 

[v0.21.327.0] Jackett.Common.IndexerException: Exception (1337x): A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply.
 ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply. (1337x.to:443)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not reply correctly after a certain time, or the connection made failed because the connected host did not reply.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 179
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1496
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 701
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 317
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61


2023-06-27 12:02:04.4211 Debug The response will be compressed with 'br'. 
2023-06-27 12:02:04.4211 Debug Connection id "0HMRMUG7DFB68" completed keep alive response. 
2023-06-27 12:02:04.4211 Info Request finished HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/1337x/test - 0 - 500 - application/json 21181.5318ms
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/71491544/5270bb44-2144-415e-a2e7-e0ab79b8bc4b)

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

If none of those work, can you access them in browser from the same device and IP?

**Comment by chasit** [comment]
I've followed the troubleshooting steps, this unfortunately did not solve the issue.

Both can be accessed in a browser from the same device and IP address that Jackett is running on.

**Comment by ilike2burnthing** [comment]
Have you tried using a proxy or VPN? If you're already using one, have you tried changing or disabling it?

Have you tried using the other sitelinks for the indexers?

Were they previously working, or is this your first time using them in Jackett?

**Comment by chasit** [comment]
I had used it (the indexer) previously, without a proxy/VPN this worked.
I just tried your suggestion and used my VPN, this solved the issue. FlareSolverr was also not necessary.
