### ISSUE TITLE
[req]: Wolfmax4k

### ISSUE THREAD

**Issue by malomehi** [Jackett/Jackett#14511]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: Wolfmax4k
- URL: https://wolfmax4k.com/
- Description: Wolfmax4k is a SPANISH Public tracker for MOVIES / TV
- Minimum Seeding Time and Minimum Ratio (if Private): 
- Additional Comments: 
```

**Comment by magarto** [comment]
Thanks in advance!

**Comment by Jakmaster199** [comment]
Hi!

To add more info to the request... WolfMax4K it's a tracking site under Cloudflare protection... So you should click that annoying box most of the time to continue using it...

Also, they're using javascript libraries to hide links provided in each film/chapter page... To be more specific they're using Base64 as first layer and GibberishAES with an encryption key as second layer. I don't know which salt are they using yet.
<details><summary>Current Encryption Key</summary>
<p>-> <b>fee631d2cffda38a78b96ee6d2dfb43a</b> <- </p>
</details>

**Comment by RawSmokeTerribilus** [comment]
They also use an external system to protect links where you need to click in an add and wait 30 secs to unlock the download link, only once each 24h but, with no doubts, it's the best place to get spanish content.

**Comment by Crosus97** [comment]
we can do anything with this tracker?

TY

**Comment by Jakmaster199** [comment]
Well... New extra info discovered and maybe website cr4ck3d (?)...

When you press the download button it redirects to an url hider website... but the base64 string of that URL is not the final one... Seems that they are using some type of caesar cipher in part of the string but not found what they really do yet.

If you create an script which can store the created php session and do the following flow you can fetch the real destination url:

1. GET to hider URL with headers "referer" as "https://www.wolfmax4k.com/" and "user-agent" one of the valid ones. (For example: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9")

2. POST to the url retrieved inside the "action" of the form stored in the response of the first GET.
You need to use as body a variable called "linkser" which value is stored in a hidden field in the form called with same name.
You also, you need to pass the headers "referer" with the URL of the "action" and the "user-agent" with the same value on step 1.

3. Use regex and fetch the content of link_out variable inside the raw response of the step 2:
```javascript 
var link_out = "VTJGc2RHVmtYMTlZaGlBOXo1VERNbVNUeUtCTXExL3FzM2F3eEU3elY1TWhQcmNUZWpmdkJTc1FGellWTUdmc3Y0WE5Ec2pPd2tRZ1JXcW9uQWViR1lyK0JFTklvaVg5d3Z2NHRlR1BWN0lRd0s3SEVzaTQ2bDRYL2svSXlvUHNlRFJPaU02amtvWDBlYkdrNGgzbzVrZjRBZWhWb2tEY2sxTTVVems0dlZtdTNENDJ5M0gzb2RUbHIyZ0FCMDAzaHpyaEd3Z2pTem1iV2hEVmIyeTUrdz09";
```

4. Now, this base64 string is the real destination URL buuuuut... encrypted with GibberishAES using the key that I wrote on my first comment :)

**Note 1 -** Example python code for decode the string with a given key:
```python
import base64
import hashlib
import Crypto
import Crypto.Cipher.AES
import Crypto.Random
import Crypto.Util.Padding

def rawDecrypt(ciphertext: bytes, key: bytes, iv: bytes) -> bytes:
    return Crypto.Util.Padding.unpad(
        Crypto.Cipher.AES.new(key, Crypto.Cipher.AES.MODE_CBC, iv=iv).decrypt(ciphertext),
        16
    )

def openSSLKey(password: str, salt: bytes):
    salted_password = password.encode('utf-8') + salt
    hash_1 = hashlib.md5(salted_password).digest()
    hash_2 = hashlib.md5(hash_1 + salted_password).digest()
    hash_3 = hashlib.md5(hash_2 + salted_password).digest()
    return hash_1 + hash_2, hash_3

def dec(ciphertext: str, password: str):
    ciphertext = base64.b64decode(ciphertext)
    salt = ciphertext[8:16]
    ciphertext = ciphertext[16:]
    return rawDecrypt(ciphertext, *openSSLKey(password, salt))
```

**Comment by highfredo** [comment]
Thanks @Jakmaster199 !!

I'm working on the Indexer, it's not ready yet, but I hope to have it within the week
https://github.com/highfredo/Jackett/blob/master/src/Jackett.Common/Indexers/Wolfmax4K.cs

**Comment by garfield69** [comment]
v0.21.1730

**Comment by ilike2burnthing** [comment]
https://wolfmax4k.com/buscar

> Warning
: Undefined variable $array in
/var/www/webs/wolfmax4k/pctn/library/content/newtemplate/buscar.php
on line
258
>
> Fatal error
: Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/webs/wolfmax4k/pctn/library/content/newtemplate/buscar.php:258 Stack trace: #0 /var/www/webs/wolfmax4k/pctn/library/include/selector.php(411): include() #1 /var/www/webs/wolfmax4k/pctn/index.php(56): require_once('...') #2 /var/www/webs/wolfmax4k/index.php(23): require_once('...') #3 {main} thrown in
/var/www/webs/wolfmax4k/pctn/library/content/newtemplate/buscar.php
on line
258

**Comment by Jakmaster199** [comment]
Why is down or waiting for removal?? It's working at this moment...
![image](https://github.com/Jackett/Jackett/assets/1685032/afd823eb-30d2-4171-a32b-4c9ff8130f25)

Also in Jackett logs it's also working:
![image](https://github.com/Jackett/Jackett/assets/1685032/37971f31-26af-457c-a1b3-e2ac9e27abed)

**Comment by garfield69** [comment]
if you pay attention to the log you provided you will see that the keywordless TEST for wolfmax  at 18:07 returned 0 results and only the manual search at 20:20 gave you results.
Until they fix it, or we fix it by discovering if our indexer needs to be amended to handle keywordless searches differently, the indexer is marked as down.

**Comment by djismgaming** [comment]
> if you pay attention to the log you provided you will see that the keywordless TEST for wolfmax at 18:07 returned 0 results and only the manual search at 20:20 gave you results. Until they fix it, or we fix it by discovering if our indexer needs to be amended to handle keywordless searches differently, the indexer is marked as down.

Yeah, I see the same while trying to add as a new source:
![image](https://github.com/Jackett/Jackett/assets/25346053/9fd4cb4f-8b69-41c0-8c68-0de6b8669f0a)

**Comment by djismgaming** [comment]
> Why is down or waiting for removal?? It's working at this moment... ![image](https://private-user-images.githubusercontent.com/1685032/309412769-afd823eb-30d2-4171-a32b-4c9ff8130f25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMzg2NjgsIm5iZiI6MTcwOTMzODM2OCwicGF0aCI6Ii8xNjg1MDMyLzMwOTQxMjc2OS1hZmQ4MjNlYi0zMGQyLTQxNzEtYTMyYi00YzlmZjgxMzBmMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDJUMDAxMjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmJmNzYyZGExZTdiMDgyZDNiMzQ5MTU1MTIyNzQzYmVhM2ExN2RiNTM0ZTA4YmQ3MTYyM2U5OTk4NjM0MDU5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.htiph2MqkOz3BjheS72UuL_xVtTEdkmWNwDA0Xcc1EY)
> 
> Also in Jackett logs it's also working: ![image](https://private-user-images.githubusercontent.com/1685032/309412801-37971f31-26af-457c-a1b3-e2ac9e27abed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMzg2NjgsIm5iZiI6MTcwOTMzODM2OCwicGF0aCI6Ii8xNjg1MDMyLzMwOTQxMjgwMS0zNzk3MWYzMS0yNmFmLTQ1N2MtYTFiMy1lMmFjOWUyN2FiZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDJUMDAxMjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM2MmUxMzRlY2EzNjc2ZDEwYzllNjM5NjZkY2E2NDA0NWE0ZTNiZmU4YzBiNTEzMGQzOTg5YjFmMzU2OGJkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1IoeDyJKl91Z1kSgCRYcoKzX08pWe0Q6XR8qEZgQdCE)

@Jakmaster199 Could you share your current wolfmax4k.json file in `$APPDATA/Jackett/Indexers`? I would want to add it manually for the time being. 😊 Jackett will not let me automatically as the test is not passed.

**Comment by ilike2burnthing** [comment]
```json
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://wolfmax4k.com/"
  },
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": ""
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": ""
  },
  {
    "id": "tags",
    "type": "inputtags",
    "name": "Tags",
    "value": ""
  }
]
```

**Comment by Jakmaster199** [comment]
```
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://wolfmax4k.com/"
  },
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": "PHPSESSID=ae9ncrmrtoj5pinak81pphu52e; PHPINFO=amJ5c3puazR4LnBieg%3D%3D; cf_clearance=fIAmicoxTEgN2Bh7LDgLyZR23YNKpQUBAvBwiry3Ciw-1709340401-1.0.1.1-tyipOdabG5rOvn_wZcWu98sDECJeJOTxxpO8CySF9xls1SnPeGhYZbdOWm7YeiWeohdFoogzonmJQD3cEaODmA; cf_chl_3=20650f59049df33"
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": "Test search in Wolfmax 4k => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc."
  },
  {
    "id": "tags",
    "type": "inputtags",
    "name": "Tags",
    "value": ""
  }
]
```

**Comment by ilike2burnthing** [comment]
Deleted as it included a potentially personally identifiable cookie, and redacting it would just result in the above.

**Comment by highfredo** [comment]
It seems like some kind of limitation of requests numbers to the website (maybe due to cloudflare?). 
If you wait a few hours without making any calls (be careful with sonarr and radarr requests), it works again without problems.

edit:
@djismgaming Some Spanish ISPs are blocking access, so you may need a proxy. I am using this one and it works ok https://blog.caomingjun.com/run-cloudflare-warp-in-docker/en/

**Comment by Neikon** [comment]
Pls don't delete this indexer

With flaresolver it gets the web and result of search but doesn't give me the releases

Here is a piece of the log 
```
Jackett.Common.IndexerException: Exception (wolfmax4k): Specified argument was out of the range of valid values. (Parameter 'count')

[v0.21.1915.0] Jackett.Common.IndexerException: Exception (wolfmax4k): Specified argument was out of the range of valid values. (Parameter 'count')
 ---> System.Exception: Parse error
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'count')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.Range(Int32 start, Int32 count)
   at Jackett.Common.Indexers.Wolfmax4K.GetEpisodesFromTitle(String title) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 384
   at Jackett.Common.Indexers.Wolfmax4K.ExtractReleaseInfo(IElement cardElement, TorznabQuery query) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 244
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Jackett.Common.Indexers.Wolfmax4K.PerformQuery(TorznabQuery query)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 778
   at Jackett.Common.Indexers.Wolfmax4K.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 135
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 366
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 752
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in ./Jackett.Server/Controllers/ResultsController.cs:line 253
```
later below I can see the HTML of the web with the result of the search

**Comment by ilike2burnthing** [comment]
Access https://wolfmax4k.com/buscar in browser directly and you'll get the error above. Access it by performing a search on the homepage and it works fine. I'm assuming that without the referrer or payload data it's causing the error.

That doesn't seem to be the issue for Jackett though. Restart Jackett, enable enhanced logging, run a test on the indexer, and after FlareSolverr solves the challenge Jackett says that no results have been found, but the HTML in the logs shows plenty of results. Run the test again and results are found.

Not sure why this is happening. @highfredo can you take a look at this?

**Comment by highfredo** [comment]
I still have to continue investigating, but everything indicates that it is an error in the FlareSolverrSharp library

If we put a breakpoint in the ClearanceHandler class, just before the InjectCookies function we see that there are two cookies: cf_clearance and PHPSESSID, after this function, only cf_clearance exists.

![Captura de pantalla 2024-03-02 230811](https://github.com/Jackett/Jackett/assets/5951524/2ee2b10a-f903-41a5-a4e8-2fefe30821bd)

![Captura de pantalla 2024-03-02 230909](https://github.com/Jackett/Jackett/assets/5951524/2c42c086-505c-4ffa-a708-472a080b342b)


Since the search token obtained [here](https://github.com/Jackett/Jackett/blob/4b6d6bb63abd8b0afc7657c49492c1e779cb438d/src/Jackett.Common/Indexers/Wolfmax4K.cs#L106) is associated with the session, the search no longer works

This explains why when the cloudflare protection does not trigger in the search, it does work, because the InjectCookies function is never executed https://github.com/FlareSolverr/FlareSolverrSharp/blob/b6e460f64ef0f864c492b34a50696495f36c228c/src/FlareSolverrSharp/ClearanceHandler.cs#L96

**Comment by djismgaming** [comment]
> ```json
> [
>   {
>     "id": "sitelink",
>     "type": "inputstring",
>     "name": "Site Link",
>     "value": "https://wolfmax4k.com/"
>   },
>   {
>     "id": "cookieheader",
>     "type": "hiddendata",
>     "name": "CookieHeader",
>     "value": ""
>   },
>   {
>     "id": "lasterror",
>     "type": "hiddendata",
>     "name": "LastError",
>     "value": ""
>   },
>   {
>     "id": "tags",
>     "type": "inputtags",
>     "name": "Tags",
>     "value": ""
>   }
> ]
> ```

Thanks @ilike2burnthing, it worked perfectly! I can use it like this for now as I don't request much Spanish content for myself at the moment. I don't use Jackett for automatic searches from *arrs. Thanks @highfredo for the proxy link. I'll take a look at that as it could come in handy at some point. I do use Starlink at the moment.

**Comment by vdias** [comment]
Not working on my side... read this issue, but not clear what is the actual state? should this this tracker avaiable or not?

**Comment by highfredo** [comment]
> Not working on my side... read this issue, but not clear what is the actual state? should this this tracker avaiable or not?

If the Cloudflare protection pop up when making the /buscar request, it does not work. If it doesn't, it works correctly. 
It's a matter of being lucky... I'm still looking at how to solve it

**Comment by vdias** [comment]
> > Not working on my side... read this issue, but not clear what is the actual state? should this this tracker avaiable or not?
> 
> If the Cloudflare protection pop up when making the /buscar request, it does not work. If it doesn't, it works correctly. It's a matter of being lucky... I'm still looking at how to solve it

But how to add it to jackett? tried mvarious times and no luck...

**Comment by garfield69** [comment]
>But how to add it to jackett? tried mvarious times and no luck...

what platform are you running jackett on?

**Comment by vdias** [comment]
> > But how to add it to jackett? tried mvarious times and no luck...
> 
> what platform are you running jackett on?

docker-compose on a debian....

**Comment by garfield69** [comment]
>docker-compose on a debian....

- restart Jackett and view the log
- scroll to the bottom and look for `App config/log directory:`
- open a terminal and cd to that folder
- now cd to the Indexers folder
- using a plain text editor create `wolfmax4k.json`
- copy and paste the content of https://github.com/Jackett/Jackett/issues/14511#issuecomment-1974150241
- save
- restart Jackett
- the wolfmax4k indexer should show up in your jackett dashboard active list

**Comment by vdias** [comment]
> > docker-compose on a debian....
> 
>     * restart Jackett and view the log
> 
>     * scroll to the bottom and look for `App config/log directory:`
> 
>     * open a terminal and cd to that folder
> 
>     * now cd to the Indexers folder
> 
>     * using a plain text editor create `wolfmax4k.json`
> 
>     * copy and paste the content of [[req]: Wolfmax4k #14511 (comment)](https://github.com/Jackett/Jackett/issues/14511#issuecomment-1974150241)
> 
>     * save
> 
>     * restart Jackett
> 
>     * the wolfmax4k indexer should show up in your jackett dashboard active list

Thanks, kinda works... fails some times, but at the end it works... thanks!

**Comment by highfredo** [comment]
I just found the problem, FlareSolverrSharp is overwriting the session cookies, so the searchToken is not valid.

More details here https://github.com/FlareSolverr/FlareSolverrSharp/issues/30

**Comment by Castilloo10** [comment]
Hi,

In my case this is the error that appears. I have a VM with Debian 10 and wolfmax4k.com is the only spanish that I can't add, the others (as you can see in the second image) if I have them added and working.

Can you help me, please?

![image](https://github.com/Jackett/Jackett/assets/163062556/1884fb4f-8527-4631-9e5a-3b9a788e87d6)

![image](https://github.com/Jackett/Jackett/assets/163062556/73945f0a-fe65-4b9f-8fba-7b05f259ee53)

**Comment by ilike2burnthing** [comment]
@Castilloo10 https://github.com/Jackett/Jackett/issues/15094

**Comment by ilike2burnthing** [comment]
Site no longer presents Cloudflare challenge, but FlareSolverrSharp has been updated to resolve this and (partially) [Speed.CD](https://github.com/Jackett/Jackett/issues/15164) - https://github.com/Jackett/Jackett/commit/e5521678bfa3f30bf2276db691f7c1dd5c6bc8e5

**Comment by garfield69** [comment]
The indexer is returning zero results for a TEST (keywordless search)

https://wolfmax4k.com/buscar PostData: {_ACTION=buscar, token=(removed) q=%, pgb=1} RawBody: )
returns `NO EXISTEN RESULTADOS : %`

**Comment by ilike2burnthing** [comment]
Is search working at all for you? I couldn't get it working on site or through Jackett, no matter what I searched.

**Comment by garfield69** [comment]
Ah, you're right, the search is broken.

**Comment by garfield69** [comment]
web site browser search is back, but a single percentage still does not return results. 
however three of them does work so I will update the indexer.

**Comment by garfield69** [comment]
Nope, I cant get the indexer to work, clearly too complicated for me.
PR welcome.

**Comment by ilike2burnthing** [comment]
@highfredo or @jojojox2, can either of you take a look at this?

I _think_ that they've added an additional search input `l`, that allows you to set the limit, so we shouldn't need to fetch multiple pages again.

Also, not sure if we could use `data.find.php` that the site is using, with a JSON response.

**Comment by highfredo** [comment]
I take a look at it.

Regarding data.find.php, It has very limited functionality. For example, in series it only allows you to search by title, not by episode number, and it does not allow pagination.

**Comment by garfield69** [comment]
@highfredo looks like the site has changed the way it handles downloads, see https://github.com/Jackett/Jackett/issues/17055 for details.
If no volunteer can get it working within a month I will be removing the indexer.
Can you take a look and see if you can resolve? Thanks.

**Comment by M4RC0Sx** [comment]
## Diagnosis: the enlacito.com gateway is broken for everyone, not just for Jackett

I looked into this and the gateway is not rejecting Jackett specifically — it returns the same
139-byte stub to a real browser. Details below in case they help whoever picks this up.

### The flow today

1. `GET https://wolfmax4k.com/online/270027` → 200, valid HTML, still contains the
   `DESCARGAR AHORA` link to `https://enlacito.com/s.php?i=<base64>`.
2. `GET https://enlacito.com/s.php?i=<base64>` → 200, 1041 bytes, the auto-submitting form.
   It sets `PHPSESSID` + `PHPINFO` and carries `linkser=jbysznk4x.pbz` (ROT13 of
   `wolfmax4k.com`, a constant).
3. The `POST` → 200, 139 bytes, always:
   ```html
   <html><head><meta name="referrer" content="never"><meta http-equiv="refresh" content="0; url=https://google.com"><head><body></body></html>
   ```

### What I ruled out

The `POST` returns that stub regardless of:

- User-Agent (Chrome, Safari, `Jackett/x.y`)
- `Referer` (the `s.php` URL, the wolfmax4k page, or none)
- `Origin`, `sec-ch-ua*`, `Sec-Fetch-*`, `Upgrade-Insecure-Requests`, `Accept-Language`,
  `Accept-Encoding`, `Cache-Control`
- cookies (fresh session, reused session, a jar that already had `PHPINFO`)
- a freshly fetched token from a different release page each time
- posting to the form `action` (with the `#fragment`), to `https://enlacito.com/`, or to
  `https://enlacito.com/index.php`
- HTTP/1.1 vs HTTP/2
- waiting 40 s between the GET and the POST (in case of an ad timer)

**Most importantly:** a real Chrome (`--headless=new`, clean profile) navigating to the `s.php`
URL and letting it auto-submit also ends up on `google.com`. So the browser gets the same stub.
This is not browser fingerprinting or an anti-bot check that a better-shaped request can pass.

Also worth noting: `https://enlacito.com/` itself returns that exact stub, and Wayback Machine
snapshots show the same response going back to at least May 2024 — it appears to be enlacito's
default answer for any request that does not complete whatever flow it now expects.

An unrelated project using the identical GET→POST→`link_out` flow has working recorded fixtures
from August 2026, so the breakage seems to be between August and early September 2026.

### Why it surfaces as `OverflowException`

`Download()` matches `var link_out = "(.*)"` against the response. Against the stub there is no
match, so `Groups[1]` is `""`. That empty string goes through
`Convert.FromBase64String("")` → a 0-byte array → `OpenSSLDecryptAsync` then does
`new byte[encryptedBytesWithSalt.Length - salt.Length - 8]`, i.e. `new byte[-16]`, which throws
`OverflowException`. So the exception is a symptom; the real failure is one step earlier, and the
indexer never checks that the gateway actually returned a payload.

### About the `i=` token

The `i=` parameter is `base64(base64("Salted__" + salt + ciphertext))` — the same shape as
`link_out`. It does **not** decrypt with `fee631d2cffda38a78b96ee6d2dfb43a` (bad padding), while a
real `link_out` from 2024 does decrypt with that key using the same code path. So the token going
*into* enlacito uses a different key than the payload coming *out* of it, and decrypting the link
locally without the gateway is not possible with the known key.

### One extra finding about wolfmax4k itself

The final download URL that `link_out` decrypts to looks like:

```
https://wolfmax4k.com/assets/u/t/temp/<DDMMYYYY>/<release id>/<file name>.torrent?md5=<sig>&expires=<epoch>
```

wolfmax4k **does not validate the `md5`/`expires` signature**. I confirmed that a URL from a
December 2024 archived link still returns the torrent today, both with its long-expired signature
and with the query string removed entirely. So the signature is not the obstacle — the only thing
the gateway is really hiding is `<DDMMYYYY>/<release id>/<file name>`.

**Comment by malomehi** [comment]
I have downloaded a torrent today using this indexer. Is the issue solved? Or does the issue affect only some torrents and not others?

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/6cb3c034-a406-4f35-86f2-0137f1fb38ed" />

**Comment by M4RC0Sx** [comment]
> I have downloaded a torrent today using this indexer. Is the issue solved? Or does the issue affect only some torrents and not others?
> <img alt="Image" width="1366" height="768" src="https://private-user-images.githubusercontent.com/1456960/646902510-6cb3c034-a406-4f35-86f2-0137f1fb38ed.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODg3MDI5NzksIm5iZiI6MTc4ODcwMjY3OSwicGF0aCI6Ii8xNDU2OTYwLzY0NjkwMjUxMC02Y2IzYzAzNC1hNDA2LTRmMzUtODZmMi0wMTM3ZjFmYjM4ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA5MDZUMTM1MTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjc2MWY0OGViYzQwNDMyMDBlODNhNzM3MmNjODkxYjlkYjdhOWIyOTRlZGY0NjQxMGI0NGY4NDBiZjBhYTI2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.Iv2XpH60rseqSuJNPofWM1qxHIGV90XkxlyHihq4I6k">

It is still failing for me

**Comment by highfredo** [comment]
Hi,
I'm looking into how to fix it, I'll let you know as soon as I know anything

**Comment by Jakmaster199** [comment]
Seems that "enlacito.com" is now working.

**Comment by Jakmaster199** [comment]
> ### One extra finding about wolfmax4k itself
> 
> The final download URL that `link_out` decrypts to looks like:
> 
> ```
> https://wolfmax4k.com/assets/u/t/temp/<DDMMYYYY>/<release id>/<file name>.torrent?md5=<sig>&expires=<epoch>
> ```
> 
> wolfmax4k **does not validate the `md5`/`expires` signature**. I confirmed that a URL from a December 2024 archived link still returns the torrent today, both with its long-expired signature and with the query string removed entirely. So the signature is not the obstacle — the only thing the gateway is really hiding is `<DDMMYYYY>/<release id>/<file name>`.



Well, If you see the response of the API that the search bar uses...
{
	"1": {
		"guid": "movie/270071",
		"calidad": "BluRay 1080p",
		"torrentName": "Movida celestial (Good Fortune) (2026) [Bluray 1080p][Esp]",
		"pic": "movida-celestial--good-fortune---2026---BluRay-1080p_17_1029.jpg",
		"picc": "1029_1080p.jpg",
		"image": "https://wolfmax4k.com/assets/u/p/f/movida-celestial--good-fortune---2026---BluRay-1080p_17_1029.jpg"
	}
}

And you see the link that is under "enlacito.com" site...

https://wolfmax4k.com/assets/u/t/temp/06092026/270071/movida-celestial--good-fortune---2026---BluRay-1080p_17_1029.torrent?md5=jwal2n2cDTR9skQqdBMCfw&expires=1789065263

Seems that on "pic" replacing ".jpg" is the name of the torrent... "guid" have the "release_id". And... The only part that we need to find is the date when they uploaded it...

Maybe we can de-salt and decode the base64 string that is passed to "enlacito.com" to see if that "date" is here.

**Comment by M4RC0Sx** [comment]
> > ### One extra finding about wolfmax4k itself
> > The final download URL that `link_out` decrypts to looks like:
> > ```
> > https://wolfmax4k.com/assets/u/t/temp/<DDMMYYYY>/<release id>/<file name>.torrent?md5=<sig>&expires=<epoch>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > wolfmax4k **does not validate the `md5`/`expires` signature**. I confirmed that a URL from a December 2024 archived link still returns the torrent today, both with its long-expired signature and with the query string removed entirely. So the signature is not the obstacle — the only thing the gateway is really hiding is `<DDMMYYYY>/<release id>/<file name>`.
> 
> Well, If you see the response of the API that the search bar uses... { "1": { "guid": "movie/270071", "calidad": "BluRay 1080p", "torrentName": "Movida celestial (Good Fortune) (2026) [Bluray 1080p][Esp]", "pic": "movida-celestial--good-fortune---2026---BluRay-1080p_17_1029.jpg", "picc": "1029_1080p.jpg", "image": "https://wolfmax4k.com/assets/u/p/f/movida-celestial--good-fortune---2026---BluRay-1080p_17_1029.jpg" } }
> 
> And you see the link that is under "enlacito.com" site...
> 
> https://wolfmax4k.com/assets/u/t/temp/06092026/270071/movida-celestial--good-fortune---2026---BluRay-1080p_17_1029.torrent?md5=jwal2n2cDTR9skQqdBMCfw&expires=1789065263
> 
> Seems that on "pic" replacing ".jpg" is the name of the torrent... "guid" have the "release_id". And... The only part that we need to find is the date when they uploaded it...
> 
> Maybe we can de-salt and decode the base64 string that is passed to "enlacito.com" to see if that "date" is here.

I seem to recall that I tried it, and for TV shows it didn't work the same way and ruined that approach...

**Comment by M4RC0Sx** [comment]
Seems to be working now...

**Comment by ilike2burnthing** [comment]
Working here on a few torrents. @highfredo is it still broken for you?

**Comment by highfredo** [comment]
Hi,
Its working fine for me.

It must have been a temporary issue on Enlacito’s end

**Comment by RawSmokeTerribilus** [comment]
> Seems to be working now...

Hi buddy. listen... it happens every single day that we have football in spain. just check this web 'https://hayahora.futbol/' and if you see a big 'SI' there, use TOR or wait for the match to end. ISPs are blocking half the internet when there is a match.

**Comment by Neikon** [comment]
> > Seems to be working now...
> 
> Hi buddy. listen... it happens every single day that we have football in spain. just check this web 'https://hayahora.futbol/' and if you see a big 'SI' there, use TOR or wait for the match to end. ISPs are blocking half the internet when there is a match.

Supposedly, with this dns you can evade the block https://xdp.es/  

P.S: thank you so much guys, your work helps me a lot of

**Comment by M4RC0Sx** [comment]
It is failing again for me trying to grab a series episode. @highfredo @garfield69

**Comment by highfredo** [comment]
> It is failing again for me trying to grab a series episode. [@highfredo](https://github.com/highfredo) [@garfield69](https://github.com/garfield69)

because there's football on now

**Comment by Neikon** [comment]
> It is failing again for me trying to grab a series episode. [@highfredo](https://github.com/highfredo) [@garfield69](https://github.com/garfield69)

use this dns and try again https://xdp.es/ 

There is football
