### ISSUE TITLE
[lesaloon] (updating) Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php

### ISSUE THREAD

**Issue by thenamelessthing** [Jackett/Jackett#14524]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://localhost:8191
Using proxy: Disabled
App config/log directory: /home/gandalf/.config/Jackett
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
OS version: Ubuntu 20.04.6 LTS / Unix 5.4.0.153 (64bit OS) (64bit process)
Environment version: 6.0.19 (/home/gandalf/Jackett/)	
Jackett v0.21.356
```

### Description

I'm back from vacation and since then I've had an error in jackett when I click on the test button for LeSaloon. I have verified my account information when trying to log into the website with success. I've also tried deleting the tracker in jackett and adding it again but I still get the same error message.

### Logged Error Messages

```text
Date 	Level 	Message
2023-07-01 16:32:53 	Error 	Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
2023-07-01 16:32:46 	Error 	Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
2023-07-01 16:31:54 	Error 	Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
2023-07-01 16:30:32 	Error 	Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
2023-07-01 16:29:07 	Error 	Jackett.Common.IndexerException: Exception (lesaloon): Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
2023-07-01 16:29:07 	Error 	Error on 20230701162907 for LeSaloon.txtJackett.Common.ExceptionWithConfigData: Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 865
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1713
2023-07-01 16:29:06 	Info 	CardigannIndexer(lesaloon): Relogin required
2023-07-01 16:29:06 	Error 	Redirected to: https://lesaloonv2-0.xyz/yupy_login.php
2023-07-01 16:28:49 	Error 	Jackett.Common.IndexerException: Exception (lesaloon): Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
2023-07-01 16:28:49 	Error 	Error on 20230701162849 for LeSaloon.txtJackett.Common.ExceptionWithConfigData: Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 865
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1713
2023-07-01 16:28:48 	Info 	CardigannIndexer(lesaloon): Relogin required
2023-07-01 16:28:48 	Error 	Redirected to: https://lesaloonv2-0.xyz/yupy_login.php
2023-07-01 16:28:32 	Error 	Jackett.Common.IndexerException: Exception (lesaloon): Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
2023-07-01 16:28:32 	Error 	Error on 20230701162832 for LeSaloon.txtJackett.Common.ExceptionWithConfigData: Login Failed, got redirected to: https://lesaloonv2-0.xyz/yupy_login.php
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 865
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1713
2023-07-01 16:28:24 	Info 	CardigannIndexer(lesaloon): Relogin required
2023-07-01 16:28:24 	Error 	Redirected to: https://lesaloonv2-0.xyz/yupy_login.php
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/10235448/58ef40d4-beee-4b10-985c-b5daf7e1ab31)

![image](https://github.com/Jackett/Jackett/assets/10235448/828bc07d-05a7-49ec-8e59-ff5f7b991be2)

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#login-failed-selector

Failing that, please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
looks like the login button now needs an **O** instead of **XZ**

**Comment by garfield69** [comment]
oops ignore me I read the html incorrectly.

**Comment by thenamelessthing** [comment]
today it's working again, I suppose the problem was on the tracker...
