### ISSUE TITLE
[chore] update yaml indexers with a login test using only a path

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#14537]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

l

### Logged Error Messages

```text
l
```

**Comment by ilike2burnthing** [comment]
I think something about abtorrents' simplecaptcha changed and nothing I tried worked. Granted this was back when I first started working on Jackett, so it could well have been a lack of experience on my part, or something has since changed on their end and it just hasn't been reviewed.

Re: torrentdownload, it got bumped to SP in https://github.com/Jackett/Jackett/commit/921e1076338932871d2972d2b96244a711e910a8 as a result of https://github.com/Jackett/Jackett/issues/7849 (demonoid has since actually become SP and cpabien was reverted to public in https://github.com/Jackett/Jackett/commit/be9f7ffa3ee222a18ccf2c7d443e5b04ade6e90c).

**Comment by ilike2burnthing** [comment]
Yea, the issue for abtorrent is the simplecaptcha. Currently working in Jackett:

> https://tlz.digital/simpleCaptcha.php?numImages=1
{"text":"house","images":[{"hash":"38b767f863989fa7e079017228f79c6c75bd5287","file":"captchaImages\/01.png"}]}

> https://www.crnaberza.com/simpleCaptcha.php?numImages=1
{"text":"Zastavu","images":[{"hash":"f000f46126b1b3651ddc5f8b20b0d91c50dde396","file":"captchaImages\/06.png"}]}

What abtorrents returns:

> https://abtorrents.me/simpleCaptcha.php?numImages=1
{"text":"heart","images":["2e0549297285f51697f86910365232afc0c75b13","50965b66a23f11c13dbb10b70a3d2f2876c504ee","22a8b8d0f3e03e95fc7f6b981077565556dcf471","b978b4e46a46d21c68b9b3be5371591cd36af1d6","566413ab22eec8155fe77339996864dd8b2473a1"]}

Which results in the error:

```text
2023-07-06 00:34:36.5625 Error System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue. 

[v0.21.378.0] System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 703
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1033
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Done on my end. Used `usercp.php` for Asian NexusPHP indexers in case they close login in the future. mvgroup indexers have two selectors as the tracker pages don't have the account menu.

10 left for @garfield69 (my newretro account works in Jackett but I can't sign in in browser, I messaged them twice months ago to no reply)

1 for @JigSawFr and a bunch for @RoloSoze if they're free.

 torrent-explosiv is down.

Didn't touch hqmusic or torrentgalaxy per https://github.com/Jackett/Jackett/issues/14537#issuecomment-1622281214, but didn't want to remove them yet.

That still leaves some that none of us have though, so how do we make the schema change?

**Comment by garfield69** [comment]
v0.21.418

**Comment by garfield69** [comment]
>That still leaves some that none of us have though, so how do we make the schema change?

I could try making an educated guess based on the closest matching engine for each of the remaining ones, and if the indexer breaks then we will have a report and we can get the html off the OP and fix it that way?
Consensus:
- [ ] ilike2burnthing  (tick the box for me to proceed)
- [ ] mynameisbogdan  (tick the box for me to proceed)
- [x] garfield69

**Comment by garfield69** [comment]
v0.21.424
