### ISSUE TITLE
[bjshare] (updating) Error downloading. indexer: bjshare path: https://bj-share.info/torrents.php?action=download&id=(removed)&source=browse

### ISSUE THREAD

**Issue by IgorMCesar** [Jackett/Jackett#14580]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Version ARM64: https://hub.docker.com/r/linuxserver/jackett
Jackett Version: v0.21.532
```

### Description

Bjshare stopped working, I have been using it for more than a year. Two weeks ago, it started returning the HTML page as a response.

```text 
Error downloading. indexer: bjshare path: https://bj-share.info/torrents.php?action=download&id=(removed)&source=browse
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 85```
```
### Logged Error Messages

```text
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">
<head>
    <title>BJ-Share :: Semeando Amizades</title>
    <meta name="robots" content="noindex,nofollow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="msapplication-config" content="none" />
    <link rel="shortcut icon" href="favicon.ico" />
    <link rel="search" type="application/opensearchdescription+xml" title="BJ-Share" href="opensearch.php?type=torrents" />
    <link rel="stylesheet" type="text/css" href="static/styles/global.css?v=1688223372"/>
    <link rel="stylesheet" type="text/css" href="static/styles/fa-pro.css?v=1628110657"/>
    <link rel="stylesheet" type="text/css" href="static/styles/dropzone.css?v=1599511097"/>
    <link rel="stylesheet" type="text/css" href="static/styles/jquery.passwordRequirements.css?v=1685050682"/>
    <link rel="stylesheet" type="text/css" href="static/styles/awesomplete.css?v=1619217628"/>
    <link rel="stylesheet" type="text/css" href="static/styles/datetime_picker/style.css?v=1599511097"/>
	<link rel="stylesheet" href="static/styles/tooltipster/style.css?v=1599511097" type="text/css" media="screen" />
    <link rel="stylesheet" type="text/css" title="bj-clean" media="screen" href="static/styles/bj-clean/style.css?v=1642546661 "/>
    <link rel="stylesheet" type="text/css" href="static/styles/chosen.css">
    <script>
        var authkey = "(removed)";
        var username = "CerealMilk";
    </script>
    <script src="static/functions/jquery.js?v=1599349412"></script>
    <script src="static/functions/script_start.js?v=1643206678"></script>
    <script src="static/functions/ajax.class.js?v=1684873209"></script>
    <script src="static/functions/deleteMultiple.js?v=1599349412"></script>
    <script src="static/functions/global.js?v=1630449800"></script>
    <script src="static/functions/jquery.autocomplete.js?v=1599349412"></script>
    <script src="static/functions/autocomplete.js?v=1599349412"></script>
    <script src="static/functions/jquery.popupoverlay.js?v=1599349412"></script>
    <script src="static/functions/dropzone.js?v=1599349412"></script>
    <script src="static/functions/tooltipster.js?v=1599349412"></script>
    <script src="static/functions/tooltipster_settings.js?v=1687905343"></script>
    <script src="static/functions/chosen.jquery.min.js"></script>
	<script src="static/functions/noty/noty.js?v=1599349412"></script>
	<script src="static/functions/noty/layouts/bottomRight.js?v=1599349412"></script>
	<script src="static/functions/noty/themes/default.js?v=1599349412"></script>
	<script src="static/functions/user_notifications.js?v=1599349412"></script>
    <script src="static/functions/jquery.mousewheel-3.0.6.pack.js?v=1599349412"></script>
    <script src="static/functions/jquery.fancybox.pack.js?v=2.1.5?v=1599349412"></script>
    <link rel="stylesheet" type="text/css" href="static/styles/jquery.fancybox.css?v=1619216025" media="screen" />
    <link rel="stylesheet" type="text/css" href="static/styles/jquery.fancybox-buttons.css?v=1599349412" />
    <script src="static/functions/jquery.fancybox-buttons.js?v=1599349412"></script>
    <link rel="stylesheet" type="text/css" href="static/styles/jquery.fancybox-thumbs.css?v=1599349412" />
    <script src="static/functions/jquery.fancybox-thumbs.js?v=1599349412"></script>
    <script>
        $(document).ready(function() {
            $('.fancybox').fancybox();
            $(".fancybox-effects-a").fancybox({
                helpers: {
                    title : {
                        type : 'outside'
                    },
                    overlay : {
                        speedOut : 0
                    }
                }
            });
            $(".fancybox-effects-b").fancybox({
                openEffect  : 'none',
                closeEffect	: 'none',
                helpers : {
                    title : {
                        type : 'over'
                    }
                }
            });
            $(".fancybox-effects-c").fancybox({
                wrapCSS    : 'fancybox-custom',
                closeClick : true,
                openEffect : 'none',
                helpers : {
                    title : {
                        type : 'inside'
                    },
                    overlay : {
                        css : {
                            'background' : 'rgba(238,238,238,0.85)'
                        }
                    }
                }
            });
            $(".fancybox-effects-d").fancybox({
                padding: 0,
                openEffect : 'elastic',
                openSpeed  : 100,
                closeEffect : 'elastic',
                closeSpeed  : 100,
                closeClick : true,
                helpers : {
                    overlay : null
                }
            });
            $('.fancybox-buttons').fancybox({
                openEffect  : 'none',
                closeEffect : 'none',
                prevEffect : 'none',
                nextEffect : 'none',
                closeBtn  : false,
                helpers : {
                    title : {
                        type : 'inside'
                    },
                    buttons	: {}
                },
                afterLoad : function() {
                    this.title = 'Image ' + (this.index + 1) + ' of ' + this.group.length + (this.title ? ' - ' + this.title : '');
                }
            });
            $('.fancybox-thumbs').fancybox({
                prevEffect : 'fade',
                nextEffect : 'fade',
                closeBtn  : true,
                arrows    : true,
                nextClick : true,
                helpers : {
                    thumbs : {
                        width  : 50,
                        height : 50
                    }
                }
            });
        });
    </script>
    <style>
        .fancybox-custom .fancybox-skin {
            box-shadow: 0 0 50px #222;
        }
    </style>
</head>
<body id="torrents">

<div id="noteAlertMsg">
    Faça uma <a href="/doacoes.php" style="color: #0A92C8; hover: #0A92C8;">doação</a> e ajude-nos a manter o site on-line. :)
</div>
    <div id="wrapper">
    <h1 class="hidden">BJ-Share</h1>
    <div id="header">
        <a href="/doacoes.php">            <div id="logo"></div>
        </a>        <div id="userinfo">
            <ul id="userinfo_stats">
                <li id="stats_seeding">
                    <a href="/torrents.php?type=seeding&amp;username=(removed)                    <span class="stat bjtooltip" title="9.01309 TiB">9.013 TiB</span>
                </li>
                <li id="stats_leeching">
                    <a href="/torrents.php?type=leeching&amp;username=(removed)                    <span class="stat bjtooltip" title="929.39156 GiB">929.39 GiB</span>
                    <span class="stat bjtooltip" title="81 downloads completos nos últimos 90 dias, contabilizados até ontem">(81)</span>
                </li>
                <li id="stats_ratio">
                    Ratio: <span class="stat"><span class="bjtooltip r50" title="9,93058">9,93</span></span>
                </li>
                <li id="stats_bjpontos">
                    <a href="/loja.php">BJ-Pontos</a>: <span class="stat bjtooltip">7.038.304</span>
                </li>
            </ul>
            <ul id="userinfo_minor">
                <li id="nav_staffinbox">
                    <a href="/staffpm.php">Staff PM</a>
                </li>
                <li id="nav_requests">
                    <a href="/requests.php">Pedidos</a>
                </li>
                <li id="nav_donations">
                                            <a href="/doacoes.php">Doações (75.172%)</a>
                                    </li>
            </ul>
        </div>
        <div id="menu">
            <div id="centertopmenu">
                <div id="menudrop">
                    <ul>
                        <li id="nav_index">
                            <a href="/index.php">Home &nbsp;&#9662;</a>
                            <ul>
                                <li><a href="/rules.php">Regras</a></li>
                                <li><a href="/wiki.php">Ajuda</a></li>
                                <li><a href="/grupos.php">Grupos</a><a class="symbol">&#9656;</a>
                                <ul>
                                    <li><a href="/grupos.php">Lista</a>
                                    <li><a href="/grupos.php?action=ranking">Top 10</a>
                                </ul>
                                </li>
                                <li><a href="/staffpm.php">Staff PM</a></li>
                                <li><a href="/doacoes.php">Doações</a></li>
                                <li><a href="#">Diversão</a><a class="symbol">&#9656;</a>
                                <ul>
                                    <li><a href="/diversao.php?action=minas">Minas</a>
                                    <li><a href="/diversao.php?action=cassino">Cassino</a>
                                    <li><a href="/bolao.php">Bolão</a>
                                    <li><a href="/diversao.php?action=batepapo">Bate-Papo</a>
                                </ul>
                                <li><a href="/loja.php">Loja</a></li>
                            </ul>
                        </li>
                        <li id="nav_torrents">
                            <a href="/torrents.php">Torrents &nbsp;&#9662;</a>                            <ul>
                                <li><a href="#">Categorias</a><a class="symbol">&#9656;</a>
                                    <ul>
                                        <li><a href="/torrents.php?filter_cat%5b14%5d=14">Animes</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b3%5d=3">Aplicativos</a><a class="symbol">&#9656;</a>
                                            <ul>
                                                <li><a href="/torrents.php?filter_cat%5b3%5d=3&amp;plataforma=54">Android</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b3%5d=3&amp;plataforma=55">iOS</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b3%5d=3&amp;plataforma=51">Linux</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b3%5d=3&amp;plataforma=53">Mac</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b3%5d=3&amp;plataforma=57">Multiplataforma</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b3%5d=3&amp;plataforma=52">Windows</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b3%5d=3&amp;plataforma=56">Windows Phone</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="/torrents.php?filter_cat%5b11%5d=11">Audiobook</a></li>
                                        <li><a href="/torrents.php?filter_cat%5B19%5D=1&amp;filter_cat%5B20%5D=1&amp;filter_cat%5B21%5D=1&amp;filter_cat%5B23%5D=1&amp;filter_cat%5B22%5D=1&amp;filter_cat%5B15%5D=1&action=basic&searchsubmit=1#">Conteúdo Adulto</a><a class="symbol">&#9656;</a>
                                            <ul>
                                               <li><a href="/torrents.php?filter_cat%5B19%5D=1&action=basic&searchsubmit=1">Filmes Adultos</a></li>
                                               <li><a href="/torrents.php?filter_cat%5B15%5D=1&action=basic&searchsubmit=1">Fotos Adultas</a></li>
                                               <li><a href="/torrents.php?filter_cat%5B20%5D=1&action=basic&searchsubmit=1">Jogos Adultos</a></li>
                                               <li><a href="/torrents.php?filter_cat%5B22%5D=1&action=basic&searchsubmit=1">Animes Adultos</a></li>
                                               <li><a href="/torrents.php?filter_cat%5B21%5D=1&action=basic&searchsubmit=1">Mangás Adultos</a></li>
                                               <li><a href="/torrents.php?filter_cat%5B23%5D=1&action=basic&searchsubmit=1">HQs Adultas</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="/torrents.php?filter_cat%5b18%5d=18">Cursos</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b16%5d=16">Desenhos Animados</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b10%5d=10">E-Books</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b8%5d=8">Esportes</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b1%5d=1">Filmes</a><a class="symbol">&#9656;</a>
                                            <ul>
                                                <li><a href="/torrents.php?taglist=acao&amp;filter_cat%5b1%5d=1">Ação</a></li>
                                                <li><a href="/torrents.php?taglist=animacao&amp;filter_cat%5b1%5d=1">Animação</a></li>
                                                <li><a href="/torrents.php?taglist=aventura&amp;filter_cat%5b1%5d=1">Aventura</a></li>
                                                <li><a href="/torrents.php?taglist=biografia&amp;filter_cat%5b1%5d=1">Biografia</a></li>
                                                <li><a href="/torrents.php?taglist=comedia&amp;filter_cat%5b1%5d=1">Comédia</a></li>
                                                <li><a href="/torrents.php?taglist=romance,comedia&amp;filter_cat%5b1%5d=1">Comédia Romântica</a></li>
                                                <li><a href="/torrents.php?taglist=curta&amp;filter_cat%5b1%5d=1">Curtas</a></li>
                                                <li><a href="/torrents.php?taglist=documentario&amp;filter_cat%5b1%5d=1&amp;filter_cat%5b18%5d=18">Documentário</a></li>
                                                <li><a href="/torrents.php?taglist=drama&amp;filter_cat%5b1%5d=1">Drama</a></li>
                                                <li><a href="/torrents.php?taglist=esporte&amp;filter_cat%5b1%5d=1">Esporte</a></li>
                                                <li><a href="/torrents.php?taglist=familia&amp;filter_cat%5b1%5d=1">Família</a></li>
                                                <li><a href="/torrents.php?taglist=fantasia&amp;filter_cat%5b1%5d=1">Fantasia</a></li>
                                                <li><a href="/torrents.php?taglist=faroeste&amp;filter_cat%5b1%5d=1">Faroeste</a></li>
                                                <li><a href="/torrents.php?taglist=ficcao_cientifica&amp;filter_cat%5b1%5d=1">Ficção Científica</a></li>
                                                <li><a href="/torrents.php?taglist=film_noir&amp;filter_cat%5b1%5d=1">Film Noir</a></li>
                                                <li><a href="/torrents.php?taglist=guerra&amp;filter_cat%5b1%5d=1">Guerra</a></li>
                                                <li><a href="/torrents.php?taglist=historia&amp;filter_cat%5b1%5d=1">História</a></li>
                                                <li><a href="/torrents.php?taglist=misterio&amp;filter_cat%5b1%5d=1">Mistério</a></li>
                                                <li><a href="/torrents.php?taglist=musica&amp;filter_cat%5b1%5d=1">Música</a></li>
                                                <li><a href="/torrents.php?taglist=musical&amp;filter_cat%5b1%5d=1">Musical</a></li>
                                                <li><a href="/torrents.php?taglist=policial&amp;filter_cat%5b1%5d=1">Policial</a></li>
                                                <li><a href="/torrents.php?taglist=romance&amp;filter_cat%5b1%5d=1">Romance</a></li>
                                                <li><a href="/torrents.php?taglist=suspense&amp;filter_cat%5b1%5d=1">Suspense</a></li>
                                                <li><a href="/torrents.php?taglist=terror&amp;filter_cat%5b1%5d=1">Terror</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="/torrents.php?filter_cat%5b12%5d=12">HQs</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b4%5d=4">Jogos</a><a class="symbol">&#9656;</a>
                                            <ul>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=13">3DS</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=2">Celular/Tablet</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=12">DS</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=1">Emuladores e ROMs</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=3">PC</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=15">PS Vita</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=4">PS1</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=5">PS2</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=6">PS3</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=7">PS4</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=14">PSP</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=16">Switch</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=8">Wii</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=9">Wii U</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=17">Xbox</a></li>
                                                <li><a href="/torrents.php?filter_cat%5b4%5d=4&amp;plataforma=10">Xbox 360</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="/torrents.php?filter_cat%5b5%5d=5">Mangás</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b7%5d=7">Outros</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b9%5d=9">Revistas</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b2%5d=2">Seriados</a><a class="symbol">&#9656;</a>
                                            <ul>
                                                <li><a href="/torrents.php?taglist=acao&amp;filter_cat%5b2%5d=2">Ação</a></li>
                                                <li><a href="/torrents.php?taglist=animacao&amp;filter_cat%5b2%5d=2">Animação</a></li>
                                                <li><a href="/torrents.php?taglist=aventura&amp;filter_cat%5b2%5d=2">Aventura</a></li>
                                                <li><a href="/torrents.php?taglist=biografia&amp;filter_cat%5b2%5d=2">Biografia</a></li>
                                                <li><a href="/torrents.php?taglist=comedia&amp;filter_cat%5b2%5d=2">Comédia</a></li>
                                                <li><a href="/torrents.php?taglist=romance,comedia&amp;filter_cat%5b2%5d=2">Comédia Romântica</a></li>
                                                <li><a href="/torrents.php?taglist=curta&amp;filter_cat%5b2%5d=2">Curtas</a></li>
                                                <li><a href="/torrents.php?taglist=documentario&amp;filter_cat%5b2%5d=2&amp;filter_cat%5b18%5d=18">Documentário</a></li>
                                                <li><a href="/torrents.php?taglist=drama&amp;filter_cat%5b2%5d=2">Drama</a></li>
                                                <li><a href="/torrents.php?taglist=esporte&amp;filter_cat%5b2%5d=2">Esporte</a></li>
                                                <li><a href="/torrents.php?taglist=familia&amp;filter_cat%5b2%5d=2">Família</a></li>
                                                <li><a href="/torrents.php?taglist=fantasia&amp;filter_cat%5b2%5d=2">Fantasia</a></li>
                                                <li><a href="/torrents.php?taglist=faroeste&amp;filter_cat%5b2%5d=2">Faroeste</a></li>
                                                <li><a href="/torrents.php?taglist=ficcao_cientifica&amp;filter_cat%5b2%5d=2">Ficção Científica</a></li>
                                                <li><a href="/torrents.php?taglist=guerra&amp;filter_cat%5b2%5d=2">Guerra</a></li>
                                                <li><a href="/torrents.php?taglist=historia&amp;filter_cat%5b2%5d=2">História</a></li>
                                                <li><a href="/torrents.php?taglist=misterio&amp;filter_cat%5b2%5d=2">Mistério</a></li>
                                                <li><a href="/torrents.php?taglist=musica&amp;filter_cat%5b2%5d=2">Música</a></li>
                                                <li><a href="/torrents.php?taglist=musical&amp;filter_cat%5b2%5d=2">Musical</a></li>
                                                <li><a href="/torrents.php?taglist=policial&amp;filter_cat%5b2%5d=2">Policial</a></li>
                                                <li><a href="/torrents.php?taglist=romance&amp;filter_cat%5b2%5d=2">Romance</a></li>
                                                <li><a href="/torrents.php?taglist=suspense&amp;filter_cat%5b2%5d=2">Suspense</a></li>
                                                <li><a href="/torrents.php?taglist=terror&amp;filter_cat%5b2%5d=2">Terror</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="/torrents.php?filter_cat%5b6%5d=6">Shows</a></li>
                                        <li><a href="/torrents.php?filter_cat%5b13%5d=13">Stand Up Comedy</a></li>
                                    </ul>
                                </li>
                                <li><a href="/torrents.php?action=destaques">Destaques</a></li>
                                <li><a href="/collages.php">Coleções</a></li>
                                <li><a href="/requests.php">Pedidos</a></li>
                                <li><a href="/torrents.php?action=today">Últimas 24h</a></li>
                                <li><a href="/rss.php">RSS</a></li>
                                <li><a href="/upload.php">Upload</a></li>
                                <li><a href="/torrents.php?action=pendentes">Pendentes</a></li>
                                <li><a href="/torrents.php?action=morrendo">Morrendo</a></li>
                                <li><a href="/torrents.php?action=reseeds">Reseeds</a></li>
                                <li><a href="/torrents.php?action=reciclagem">Reciclagem</a></li>
                            </ul>
                        </li>
                        <li id="nav_forums"><a href="/forums.php">Fórum</a></li>
                        <li id="nav_top10"><a href="/top10.php">Top 10</a></li>                        <li id="nav_userinfor">
                            <a href="/user.php?username=(removed) &nbsp;&#9662;</a>
                            <ul>
                                <li><a href="/friends.php">Amigos</a></li>
                                                                <li><a href="/user.php?action=invite">Convites</a></li>
                                <li><a href="/inbox.php?sort=unread">Mensagens</a><a class="symbol">&#9656;</a>
                                    <ul>
                                        <li><a href="/inbox.php">Recebidas</a></li>
                                        <li><a href="/inbox.php?action=sentbox">Enviadas</a></li>
                                     </ul>
                                </li>
                                <li><a href="/bookmarks.php?type=torrents">Favoritos</a></li>
                                <li><a href="/comments.php">Comentários</a></li>
                                <li><a href="#">Torrents</a><a class="symbol">&#9656;</a>
                                    <ul>
                                        <li><a href="/torrents.php?type=uploaded&amp;username=(removed)                                        <li><a href="/torrents.php?type=seeding&amp;username=(removed)                                        <li><a href="/torrents.php?type=leeching&amp;username=(removed)                                        <li><a href="/torrents.php?type=snatched&amp;username=(removed)                                        <li><a href="/user.php?action=torrenthistory&amp;username=(removed)                                        <li><a href="/user.php?action=reseedhistory&amp;username=(removed)                                     </ul>
                                <li><a href="/user.php?action=edit&amp;username=(removed)                                <li><a href="/userhistory.php?action=subscriptions">Seguidos</a></li>
                                <li><a href="/logout.php?auth=(removed)">Sair</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
            <div id="alerts">
                <div class="alertbar"><span style="color: red;"><strong>Siga-nos no nosso <a style="color: #0A92C8" target="_blank" href="https://href.li/?https://t.me/joinchat/AAAAAFNykFILShniPNfiMg">Canal Oficial do Telegram</a></strong></span><br />
Postagem de Lan&ccedil;amentos mais aguardados e informa&ccedil;&otilde;es importantes sobre o site.</div>
            </div>
        <div id="searchbars">
            <ul>
                <li id="searchbar_torrents">
                    <span class="hidden">Torrents: </span>
                    <form class="search_form" name="torrents" action="torrents.php" method="get">
                        <input id="torrentssearch" accesskey="t" spellcheck="false"
                               onfocus="if (this.value == 'Torrents') { this.value = ''; }"
                               onblur="if (this.value == '') { this.value = 'Torrents'; }"
									value="Torrents" placeholder="Torrents" type="text" name="searchstr" size="17" />
                    </form>
                </li>
                <li id="searchbar_requests">
                    <span class="hidden">Requests: </span>
                    <form class="search_form" name="requests" action="requests.php" method="get">
                        <input id="requestssearch" spellcheck="false" onfocus="if (this.value == 'Pedidos') { this.value = ''; }" onblur="if (this.value == '') { this.value = 'Pedidos'; }" value="Pedidos" placeholder="Pedidos" type="text" name="search" size="17" />
                    </form>
                </li>
                <li id="searchbar_forums">
                    <span class="hidden">Forums: </span>
                    <form class="search_form" name="forums" action="forums.php" method="get">
                        <input value="search" type="hidden" name="action"/>
                        <input id="forumssearch"
                               onfocus="if (this.value == 'Fórum') { this.value = ''; }"
                               onblur="if (this.value == '') { this.value = 'Fórum'; }"
                               value="Fórum" placeholder="Fórum" type="text" name="search" size="17"/>
                    </form>
                </li>
                <li id="searchbar_log">
                    <span class="hidden">Log: </span>
                    <form class="search_form" name="log" action="log.php" method="get">
                        <input id="logsearch"
                               onfocus="if (this.value == 'Logs') { this.value = ''; }"
                               onblur="if (this.value == '') { this.value = 'Logs'; }"
                               value="Logs" placeholder="Logs" type="text" name="search" size="17"/>
                    </form>
                </li>
                <li id="searchbar_users">
                    <span class="hidden">Users: </span>
                    <form class="search_form" name="users" action="user.php" method="get">
                        <input
                                id="userssearch"
                                onfocus="if (this.value == 'Usuários') { this.value = ''; }"
                                onblur="if (this.value == '') { this.value = 'Usuários'; }"
                                value="Usuários" placeholder="Usuários" type="text" name="searchuser" size="20"/>
                    </form>
                </li>
            </ul>
        </div>
    </div>
    <div id="content">
	<div class="thin">
		<div class="header">
			<h2></h2>
		</div>
		<div class="box pad">
			<p><h2>Sua senha expirou.<br />A validade da senha é de 1.080 dias para contas com a autenticação de dois fatores.</h2><div style="text-align:center"><br /><br />Troque a sua senha a partir da página de <a href="user.php?action=edit">Configurações</a>, próximo ao final da página.</div></p>
		</div>
	</div>
</div>
<div id="footer">
	<p>BJ-Share &copy; 2023</p>
	<p>
		<a href="user.php?action=sessions">
			<span class="tooltip" title="Manage sessions">Última atividade: </span><span class="time bjtooltip" title="Jun 29 2023, 18:54">3 semanas, 3 dias atrás</span><span class="tooltip" title="Manage sessions"> IP: 149.90.227.148.</span>
		</a>
	</p>
	<p>
		<strong>Tempo de carregamento:</strong> <span>0.0017 segundos</span>
		<strong>Uso:</strong> <span>2.00 MiB</span>
		<strong>Carga:</strong> <span>1.64 1.21 1.06</span>
		<strong>Data:</strong> <span id="site_date">24/Jul/2023</span> - <span id="site_time">16:02</span>

	</p>
	</div>

</div>
<div id="lightbox" class="lightbox hidden"></div>
<div id="curtain" class="curtain hidden"></div>
<span class="noty-notification" style="display: none;" data-noty-type="Inbox" data-noty-id="0" data-noty-importance="confirmation" data-noty-url="inbox.php?sort=unread">Você tem uma nova mensagem.</span>
<a href="javascript:void(0);" id="irtopo" title="Ir para o topo" style="display: none;">Topo<span></span></a>
<script>
    $(document).ready(function() {
        $(window).scroll(function(){
            if ($(this).scrollTop() > 100) {
                $('#irtopo').fadeIn();
            } else {
                $('#irtopo').fadeOut();
            }
        });
        $('#irtopo').click(function(){
            $("html, body").animate({ scrollTop: 0 }, 600);
            return false;
        });
    });
    function iraotoponew(){
        $("html, body").animate({ scrollTop: 0 }, 600);
        return false;
    }
</script>
</body>
</html>
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/5064518/1a4818a0-a633-4e17-9417-88b6e099cf0e)
![image](https://github.com/Jackett/Jackett/assets/5064518/a32debe1-e546-49bb-92f2-f258dc01c4a6)

**Comment by garfield69** [comment]
I take it you discovered the message that your 2fa password has expired and you need to change it ;-)

**Comment by IgorMCesar** [comment]
> I take it you discovered the message that your 2fa password has expired and you need to change it ;-)

Yeah, I did while analyzing the log... The site itself doesn't show this. Weird stuff xD
