### ISSUE TITLE
[yggcookie] (updating) The operation was canceled.

### ISSUE THREAD

**Issue by Triskae** [Jackett/Jackett#14601]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
jackett-jackett-1  | 08-02 11:49:14 Info Starting Jackett v0.21.574 
jackett-jackett-1  | 08-02 11:49:15 Info Environment version: 6.0.20 (/app/Jackett/) 
jackett-jackett-1  | 08-02 11:49:15 Info OS version: Unix 5.19.0.46 (64bit OS) (64bit process) 
jackett-jackett-1  | 08-02 11:49:15 Info Jackett variant: CoreLinuxMuslAmdx64 
jackett-jackett-1  | 08-02 11:49:15 Info File /etc/issue: Welcome to Alpine Linux 3.18 
jackett-jackett-1  | 08-02 11:49:15 Info Running in Docker: Yes (image build: v0.21.574-ls119) 
jackett-jackett-1  | 08-02 11:49:15 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
jackett-jackett-1  | 08-02 11:49:15 Info App config/log directory: /config/Jackett 
jackett-jackett-1  | 08-02 11:49:15 Info Using proxy: Disabled 
jackett-jackett-1  | 08-02 11:49:15 Info Using FlareSolverr: http://192.168.1.138:8191 
jackett-jackett-1  | 08-02 11:49:15 Info Using HTTP Client: HttpWebClient2 
jackett-jackett-1  | 08-02 11:49:15 Info Loading Native indexers ... 
jackett-jackett-1  | 08-02 11:49:15 Info Loaded 73 Native indexers. 
jackett-jackett-1  | 08-02 11:49:15 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions 
jackett-jackett-1  | 08-02 11:49:16 Info Loaded 519 Cardigann indexers. 
jackett-jackett-1  | 08-02 11:49:16 Info Loaded 592 indexers in total 
jackett-jackett-1  | 08-02 11:49:16 Info Adding aggregate indexer ('all' indexer) ... 
jackett-jackett-1  | 08-02 11:49:16 Info Adding filter indexer ('type:public' indexer) ... 
jackett-jackett-1  | 08-02 11:49:16 Info Adding filter indexer ('type:private' indexer) ... 
jackett-jackett-1  | 08-02 11:49:16 Info Adding filter indexer ('type:semi-public' indexer
```

### Description

Can't add yggtorrent as tracker, it loads for a while but don't add tracker/

### Logged Error Messages

```text
jackett-jackett-1  | [v0.21.574.0] System.OperationCanceledException: The operation was canceled.
jackett-jackett-1  |    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
jackett-jackett-1  |    at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
jackett-jackett-1  |    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
jackett-jackett-1  |    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
jackett-jackett-1  |    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 531
jackett-jackett-1  |    at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
jackett-jackett-1  |    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 593
jackett-jackett-1  |    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
jackett-jackett-1  |    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
jackett-jackett-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett-jackett-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett-jackett-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett-jackett-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett-jackett-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett-jackett-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett-jackett-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett-jackett-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett-jackett-1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett-jackett-1  |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett-jackett-1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett-jackett-1  |    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
duplicate of  #14598
flaresolverr is unable to solve cloudflare ATM see https://github.com/FlareSolverr/FlareSolverr/issues/811
