### ISSUE TITLE
Jackett looses indexers and changes API-Key after crash

### ISSUE THREAD

**Issue by sfreek76** [Jackett/Jackett#14612]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-08-07 16:49:35 08-07 14:49:35 Info Environment version: 6.0.20 (/app/Jackett/) 
2023-08-07 16:49:35 08-07 14:49:35 Info OS version: Unix 5.15.49.0 (64bit OS) (64bit process) 
2023-08-07 16:49:35 08-07 14:49:35 Info Jackett variant: CoreLinuxMuslArm64 
2023-08-07 16:49:35 08-07 14:49:35 Info File /etc/issue: Welcome to Alpine Linux 3.18 
2023-08-07 16:49:35 08-07 14:49:35 Info Running in Docker: Yes (image build: v0.21.589-ls124) 
2023-08-07 16:49:35 08-07 14:49:35 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2023-08-07 16:49:35 08-07 14:49:35 Info App config/log directory: /config/Jackett 
2023-08-07 16:49:35 08-07 14:49:35 Info Using proxy: Disabled 
2023-08-07 16:49:35 08-07 14:49:35 Info Using FlareSolverr: No 
2023-08-07 16:49:35 08-07 14:49:35 Info Using HTTP Client: HttpWebClient2 
2023-08-07 16:49:35 08-07 14:49:35 Info Loading Native indexers ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Loaded 73 Native indexers. 
2023-08-07 16:49:35 08-07 14:49:35 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions 
2023-08-07 16:49:35 08-07 14:49:35 Info Loaded 521 Cardigann indexers. 
2023-08-07 16:49:35 08-07 14:49:35 Info Loaded 594 indexers in total 
2023-08-07 16:49:35 08-07 14:49:35 Info Adding aggregate indexer ('all' indexer) ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Adding filter indexer ('type:public' indexer) ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Adding filter indexer ('type:private' indexer) ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Adding filter indexer ('type:semi-public' indexer) ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Jackett startup finished in 1.420 s 
2023-08-07 16:49:35 Hosting environment: Production
2023-08-07 16:49:35 Content root path: /app/Jackett/Content
2023-08-07 16:49:35 Now listening on: http://[::]:9117
2023-08-07 16:49:35 Application started. Press Ctrl+C to shut down.
2023-08-07 16:49:36 [ls.io-init] done.
```

### Description

I configured Jackett yesterday and everything seemed fine. Today I made a search via Sonarr which did not work. I then opened Jackett and saw that all my indexers were gone and the API Key had changed. Checked Container health and saw Jacket was restarted 3 hours ago. Since I did not do that I presume a crash. After Restart Indexers were gone and API-Key had changed and I had to re-configure everything.

Machine is MacMini M1 which runs latest Monterey. Since installing as a Service did not work (Jackett was not started on Restart of Machine) I installed it via Docker Desktop which went fine until this issue above occured...

Thanks for any help!

### Logged Error Messages

```text
Unfortunately I can only provide logs after the restart, not the crash. It did an automatic restart so logs were wiped...

2023-08-07 13:11:31 [migrations] started
2023-08-07 13:11:31 [migrations] no migrations found
2023-08-07 13:11:31 ───────────────────────────────────────
2023-08-07 13:11:31 
2023-08-07 13:11:31       ██╗     ███████╗██╗ ██████╗ 
2023-08-07 13:11:31       ██║     ██╔════╝██║██╔═══██╗
2023-08-07 13:11:31       ██║     ███████╗██║██║   ██║
2023-08-07 13:11:31       ██║     ╚════██║██║██║   ██║
2023-08-07 13:11:31       ███████╗███████║██║╚██████╔╝
2023-08-07 13:11:31       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
2023-08-07 13:11:31 
2023-08-07 13:11:31    Brought to you by linuxserver.io
2023-08-07 13:11:31 ───────────────────────────────────────
2023-08-07 13:11:31 
2023-08-07 13:11:31 To support LSIO projects visit:
2023-08-07 13:11:31 https://www.linuxserver.io/donate/
2023-08-07 13:11:31 
2023-08-07 13:11:31 ───────────────────────────────────────
2023-08-07 13:11:31 GID/UID
2023-08-07 13:11:31 ───────────────────────────────────────
2023-08-07 13:11:31 
2023-08-07 13:11:31 User UID:    1000
2023-08-07 13:11:31 User GID:    1000
2023-08-07 13:11:31 ───────────────────────────────────────
2023-08-07 13:11:31 
2023-08-07 13:11:32 [custom-init] No custom files found, skipping...
2023-08-07 13:11:32 08-07 11:11:32 Info Starting Jackett v0.21.589 
2023-08-07 13:11:32 08-07 11:11:32 Info Environment version: 6.0.20 (/app/Jackett/) 
2023-08-07 13:11:32 08-07 11:11:32 Info OS version: Unix 5.15.49.0 (64bit OS) (64bit process) 
2023-08-07 13:11:32 08-07 11:11:32 Info Jackett variant: CoreLinuxMuslArm64 
2023-08-07 13:11:33 08-07 11:11:33 Info File /etc/issue: Welcome to Alpine Linux 3.18 
2023-08-07 13:11:33 08-07 11:11:33 Info Running in Docker: Yes (image build: v0.21.589-ls124) 
2023-08-07 13:11:33 08-07 11:11:33 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2023-08-07 13:11:33 08-07 11:11:33 Info App config/log directory: /config/Jackett 
2023-08-07 13:11:33 08-07 11:11:33 Info Using proxy: Disabled 
2023-08-07 13:11:33 08-07 11:11:33 Info Using FlareSolverr: No 
2023-08-07 13:11:33 08-07 11:11:33 Info Using HTTP Client: HttpWebClient2 
2023-08-07 13:11:33 08-07 11:11:33 Info Loading Native indexers ... 
2023-08-07 13:11:33 08-07 11:11:33 Info Loaded 73 Native indexers. 
2023-08-07 13:11:33 08-07 11:11:33 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions 
2023-08-07 13:11:33 08-07 11:11:33 Info Loaded 521 Cardigann indexers. 
2023-08-07 13:11:33 08-07 11:11:33 Info Loaded 594 indexers in total 
2023-08-07 13:11:33 08-07 11:11:33 Info Adding aggregate indexer ('all' indexer) ... 
2023-08-07 13:11:33 08-07 11:11:33 Info Adding filter indexer ('type:public' indexer) ... 
2023-08-07 13:11:33 08-07 11:11:33 Info Adding filter indexer ('type:private' indexer) ... 
2023-08-07 13:11:33 08-07 11:11:33 Info Adding filter indexer ('type:semi-public' indexer) ... 
2023-08-07 13:11:33 08-07 11:11:33 Warn No XML encryptor configured. Key {84dec132-3daa-4e7d-8928-9cb698e6db6a} may be persisted to storage in unencrypted form. 
2023-08-07 13:11:33 08-07 11:11:33 Info Jackett startup finished in 1.525 s 
2023-08-07 13:11:33 Hosting environment: Production
2023-08-07 13:11:33 Content root path: /app/Jackett/Content
2023-08-07 13:11:33 Now listening on: http://[::]:9117
2023-08-07 13:11:33 Application started. Press Ctrl+C to shut down.
2023-08-07 13:11:34 [ls.io-init] done.
2023-08-07 14:11:33 08-07 12:11:33 Info Checking for updates... Jackett variant: CoreLinuxMuslArm64 
2023-08-07 14:11:34 08-07 12:11:34 Info Jackett is already updated. Current version: v0.21.589 
2023-08-07 16:27:10 08-07 14:27:10 Info Adding aggregate indexer ('all' indexer) ... 
2023-08-07 16:27:10 08-07 14:27:10 Info Adding filter indexer ('type:public' indexer) ... 
2023-08-07 16:27:10 08-07 14:27:10 Info Adding filter indexer ('type:private' indexer) ... 
2023-08-07 16:27:10 08-07 14:27:10 Info Adding filter indexer ('type:semi-public' indexer) ... 
2023-08-07 16:27:11 08-07 14:27:11 Info Restarting webhost due to configuration change 
2023-08-07 16:27:11 08-07 14:27:11 Info Restart of the web application host (not process) initiated 
2023-08-07 16:27:11 08-07 14:27:11 Info Jackett stopped 
2023-08-07 16:27:11 08-07 14:27:11 Info Environment version: 6.0.20 (/app/Jackett/) 
2023-08-07 16:27:11 08-07 14:27:11 Info OS version: Unix 5.15.49.0 (64bit OS) (64bit process) 
2023-08-07 16:27:11 08-07 14:27:11 Info Jackett variant: CoreLinuxMuslArm64 
2023-08-07 16:27:11 08-07 14:27:11 Info File /etc/issue: Welcome to Alpine Linux 3.18 
2023-08-07 16:27:11 08-07 14:27:11 Info Running in Docker: Yes (image build: v0.21.589-ls124) 
2023-08-07 16:27:11 08-07 14:27:11 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2023-08-07 16:27:11 08-07 14:27:11 Info App config/log directory: /config/Jackett 
2023-08-07 16:27:11 08-07 14:27:11 Info Using proxy: Disabled 
2023-08-07 16:27:11 08-07 14:27:11 Info Using FlareSolverr: No 
2023-08-07 16:27:11 08-07 14:27:11 Info Using HTTP Client: HttpWebClient2 
2023-08-07 16:27:11 08-07 14:27:11 Info Loading Native indexers ... 
2023-08-07 16:27:11 08-07 14:27:11 Info Loaded 73 Native indexers. 
2023-08-07 16:27:11 08-07 14:27:11 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions 
2023-08-07 16:27:12 08-07 14:27:12 Info Loaded 521 Cardigann indexers. 
2023-08-07 16:27:12 08-07 14:27:12 Info Loaded 594 indexers in total 
2023-08-07 16:27:12 08-07 14:27:12 Info Adding aggregate indexer ('all' indexer) ... 
2023-08-07 16:27:12 08-07 14:27:12 Info Adding filter indexer ('type:public' indexer) ... 
2023-08-07 16:27:12 08-07 14:27:12 Info Adding filter indexer ('type:private' indexer) ... 
2023-08-07 16:27:12 08-07 14:27:12 Info Adding filter indexer ('type:semi-public' indexer) ... 
2023-08-07 16:27:12 08-07 14:27:12 Info Jackett startup finished in 11739.766 s 
2023-08-07 16:27:12 Hosting environment: Production
2023-08-07 16:27:12 Content root path: /app/Jackett/Content
2023-08-07 16:27:12 Now listening on: http://[::]:9117
2023-08-07 16:27:12 Application started. Press Ctrl+C to shut down.
2023-08-07 16:31:14 08-07 14:31:14 Info Torznab search in Bangumi Moe => Found 30 releases [850ms] 
2023-08-07 16:31:15 08-07 14:31:15 Info Torznab search in Bangumi Moe => Found 30 releases (from cache) [7ms] 
2023-08-07 16:31:19 08-07 14:31:19 Warn Some of the categories provided are unsupported in EZTV: 5030,5040 
2023-08-07 16:31:20 08-07 14:31:20 Info Torznab search in EZTV => Found 100 releases [550ms] 
2023-08-07 16:31:21 08-07 14:31:21 Warn Some of the categories provided are unsupported in EZTV: 5030,5040 
2023-08-07 16:31:21 08-07 14:31:21 Info Torznab search in EZTV => Found 100 releases (from cache) [2ms] 
2023-08-07 16:31:36 08-07 14:31:36 Info Torznab search in kickasstorrents.to => Found 40 releases [8963ms] 
2023-08-07 16:31:38 08-07 14:31:38 Info Torznab search in kickasstorrents.to => Found 40 releases (from cache) [7ms] 
2023-08-07 16:31:44 08-07 14:31:44 Info Torznab search in The Pirate Bay => Found 19 releases [1575ms] 
2023-08-07 16:31:46 08-07 14:31:46 Info Torznab search in The Pirate Bay => Found 19 releases (from cache) [0ms] 
2023-08-07 16:32:43 08-07 14:32:43 Info CardigannIndexer(torrentgalaxy): Relogin required 
2023-08-07 16:32:43 08-07 14:32:43 Error CardigannIndexer (torrentgalaxy): Found captcha during automatic login, aborting 
2023-08-07 16:32:43 08-07 14:32:43 Error Error on 20230807143243 for TorrentGalaxy.txtSystem.Exception: Relogin failed
2023-08-07 16:32:43    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1719
2023-08-07 16:32:43 
2023-08-07 16:32:43 
2023-08-07 16:32:43 
2023-08-07 16:32:43 
2023-08-07 16:32:43  
2023-08-07 16:32:43 08-07 14:32:43 Error Jackett.Common.IndexerException: Exception (torrentgalaxy): Relogin failed 
2023-08-07 16:32:43 
2023-08-07 16:32:43 [v0.21.589.0] Jackett.Common.IndexerException: Exception (torrentgalaxy): Relogin failed
2023-08-07 16:32:43  ---> System.Exception: Parse error
2023-08-07 16:32:43  ---> System.Exception: Relogin failed
2023-08-07 16:32:43    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1719
2023-08-07 16:32:43    --- End of inner exception stack trace ---
2023-08-07 16:32:43    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 732
2023-08-07 16:32:43    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
2023-08-07 16:32:43    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
2023-08-07 16:32:43    --- End of inner exception stack trace ---
2023-08-07 16:32:43    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
2023-08-07 16:32:43    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
2023-08-07 16:32:43    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 414
2023-08-07 16:32:43 
2023-08-07 16:32:43 
2023-08-07 16:33:03 08-07 14:33:03 Info CardigannIndexer(torrentgalaxy): Relogin required 
2023-08-07 16:33:04 08-07 14:33:04 Info Torznab search in TorrentGalaxy => Found 0 releases [1228ms] 
2023-08-07 16:33:16 08-07 14:33:16 Info Torznab search in TorrentGalaxy => Found 0 releases (from cache) [0ms] 
2023-08-07 16:33:37 08-07 14:33:37 Info Torznab search in TorrentGalaxy => Found 0 releases (from cache) [0ms] 
2023-08-07 16:33:57 08-07 14:33:57 Info Torznab search in TorrentGalaxy => Found 0 releases (from cache) [1ms] 
2023-08-07 16:34:07 08-07 14:34:07 Info Torznab search in TorrentGalaxy => Found 0 releases (from cache) [0ms] 
2023-08-07 16:34:56 08-07 14:34:56 Info CardigannIndexer(torrentgalaxy): Relogin required 
2023-08-07 16:34:58 08-07 14:34:58 Error CardigannIndexer (torrentgalaxy): Found captcha during automatic login, aborting 
2023-08-07 16:34:58 08-07 14:34:58 Error Error on 20230807143458 for TorrentGalaxy.txtSystem.Exception: Relogin failed
2023-08-07 16:34:58    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1719
2023-08-07 16:34:58 
2023-08-07 16:34:58 
2023-08-07 16:34:58 
2023-08-07 16:34:58 
2023-08-07 16:34:58  
2023-08-07 16:34:58 08-07 14:34:58 Error Jackett.Common.IndexerException: Exception (torrentgalaxy): Relogin failed 
2023-08-07 16:34:58 
2023-08-07 16:34:58 [v0.21.589.0] Jackett.Common.IndexerException: Exception (torrentgalaxy): Relogin failed
2023-08-07 16:34:58  ---> System.Exception: Parse error
2023-08-07 16:34:58  ---> System.Exception: Relogin failed
2023-08-07 16:34:58    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1719
2023-08-07 16:34:58    --- End of inner exception stack trace ---
2023-08-07 16:34:58    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 732
2023-08-07 16:34:58    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
2023-08-07 16:34:58    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
2023-08-07 16:34:58    --- End of inner exception stack trace ---
2023-08-07 16:34:58    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
2023-08-07 16:34:58    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
2023-08-07 16:34:58    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 414
2023-08-07 16:34:58 
2023-08-07 16:34:58 
2023-08-07 16:35:21 08-07 14:35:21 Info CardigannIndexer(torrentgalaxy): Relogin required 
2023-08-07 16:35:32 08-07 14:35:32 Info Torznab search in TorrentGalaxy => Found 0 releases [11763ms] 
2023-08-07 16:35:52 08-07 14:35:52 Info CardigannIndexer(torrentgalaxy): Relogin required 
2023-08-07 16:36:02 08-07 14:36:02 Error CardigannIndexer (torrentgalaxy): Found captcha during automatic login, aborting 
2023-08-07 16:36:02 08-07 14:36:02 Error Error on 20230807143602 for TorrentGalaxy.txtSystem.Exception: Relogin failed
2023-08-07 16:36:02    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1719
2023-08-07 16:36:02 
2023-08-07 16:36:02 
2023-08-07 16:36:02 
2023-08-07 16:36:02 
2023-08-07 16:36:02  
2023-08-07 16:36:02 08-07 14:36:02 Error Jackett.Common.IndexerException: Exception (torrentgalaxy): Relogin failed 
2023-08-07 16:36:02 
2023-08-07 16:36:02 [v0.21.589.0] Jackett.Common.IndexerException: Exception (torrentgalaxy): Relogin failed
2023-08-07 16:36:02  ---> System.Exception: Parse error
2023-08-07 16:36:02  ---> System.Exception: Relogin failed
2023-08-07 16:36:02    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1719
2023-08-07 16:36:02    --- End of inner exception stack trace ---
2023-08-07 16:36:02    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 732
2023-08-07 16:36:02    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
2023-08-07 16:36:02    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
2023-08-07 16:36:02    --- End of inner exception stack trace ---
2023-08-07 16:36:02    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
2023-08-07 16:36:02    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
2023-08-07 16:36:02    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 414
2023-08-07 16:36:02 
2023-08-07 16:36:02 
2023-08-07 16:36:18 08-07 14:36:18 Info Torznab search in TorrentGalaxy => Found 0 releases (from cache) [2ms] 
2023-08-07 16:36:30 08-07 14:36:30 Info CardigannIndexer(torrentgalaxy): Relogin required 
2023-08-07 16:36:40 08-07 14:36:40 Info Torznab search in TorrentGalaxy => Found 0 releases [10192ms] 
2023-08-07 16:36:48 08-07 14:36:48 Warn Some of the categories provided are unsupported in EZTV: 5030,5040 
2023-08-07 16:36:48 08-07 14:36:48 Info Torznab search in EZTV => Found 100 releases (from cache) [3ms] 
2023-08-07 16:36:48 08-07 14:36:48 Info Torznab search in kickasstorrents.to => Found 40 releases (from cache) [3ms] 
2023-08-07 16:36:48 08-07 14:36:48 Info Torznab search in The Pirate Bay => Found 19 releases (from cache) [0ms] 
2023-08-07 16:36:48 08-07 14:36:48 Info Torznab search in Bangumi Moe => Found 30 releases (from cache) [0ms] 
2023-08-07 16:37:13 08-07 14:37:13 Info Torznab search in Bangumi Moe => Found 30 releases [716ms] 
2023-08-07 16:37:15 08-07 14:37:15 Info Torznab search in Bangumi Moe => Found 30 releases (from cache) [4ms] 
2023-08-07 16:37:20 08-07 14:37:20 Info Torznab search in EZTV => Found 100 releases [493ms] 
2023-08-07 16:37:21 08-07 14:37:21 Info Torznab search in EZTV => Found 100 releases (from cache) [0ms] 
2023-08-07 16:37:23 08-07 14:37:23 Info Torznab search in Bangumi Moe => Found 30 releases (from cache) [14ms] 
2023-08-07 16:37:23 08-07 14:37:23 Info Torznab search in EZTV => Found 100 releases (from cache) [0ms] 
2023-08-07 16:37:26 08-07 14:37:26 Warn Some of the categories provided are unsupported in kickasstorrents.to: 2010,2020,2030,2040,2045,2050,2060 
2023-08-07 16:37:35 08-07 14:37:35 Info Torznab search in kickasstorrents.to => Found 7 releases [8969ms] 
2023-08-07 16:37:36 08-07 14:37:36 Warn Some of the categories provided are unsupported in kickasstorrents.to: 2010,2020,2030,2040,2045,2050,2060 
2023-08-07 16:37:36 08-07 14:37:36 Info Torznab search in kickasstorrents.to => Found 7 releases (from cache) [2ms] 
2023-08-07 16:38:27 08-07 14:38:27 Info Torznab search in The Pirate Bay => Found 19 releases (from cache) [0ms] 
2023-08-07 16:38:27 08-07 14:38:27 Warn Some of the categories provided are unsupported in EZTV: 5030,5040 
2023-08-07 16:38:27 08-07 14:38:27 Info Torznab search in EZTV => Found 100 releases (from cache) [1ms] 
2023-08-07 16:38:27 08-07 14:38:27 Info Torznab search in kickasstorrents.to => Found 40 releases (from cache) [6ms] 
2023-08-07 16:38:27 08-07 14:38:27 Info Torznab search in Bangumi Moe => Found 30 releases (from cache) [2ms] 
2023-08-07 16:39:04 08-07 14:39:04 Warn Some of the categories provided are unsupported in MovieTorrent: 2010,2020,2030,2045,2050,2060 
2023-08-07 16:39:53 08-07 14:39:53 Info Torznab search in MovieTorrent => Found 36 releases [48740ms] 
2023-08-07 16:41:49 08-07 14:41:49 Warn Some of the categories provided are unsupported in MovieTorrent: 2010,2020,2030,2045,2050,2060 
2023-08-07 16:41:49 08-07 14:41:49 Info Torznab search in MovieTorrent => Found 36 releases (from cache) [20ms] 
2023-08-07 16:41:53 08-07 14:41:53 Warn Some of the categories provided are unsupported in MovieTorrent: 2010,2020,2030,2045,2050,2060 
2023-08-07 16:41:53 08-07 14:41:53 Info Torznab search in MovieTorrent => Found 36 releases (from cache) [7ms] 
2023-08-07 16:43:26 08-07 14:43:26 Info Torznab search in MovieTorrent => Found 36 releases [54946ms] 
2023-08-07 16:46:55 08-07 14:46:55 Info Torznab search in MovieTorrent => Found 36 releases (from cache) [8ms] 
2023-08-07 16:49:24 Application is shutting down...
2023-08-07 16:49:24 08-07 14:49:24 Info Jackett stopped 
2023-08-07 16:49:34 [migrations] started
2023-08-07 16:49:34 [migrations] no migrations found
2023-08-07 16:49:34 usermod: no changes
2023-08-07 16:49:34 ───────────────────────────────────────
2023-08-07 16:49:34 
2023-08-07 16:49:34       ██╗     ███████╗██╗ ██████╗ 
2023-08-07 16:49:34       ██║     ██╔════╝██║██╔═══██╗
2023-08-07 16:49:34       ██║     ███████╗██║██║   ██║
2023-08-07 16:49:34       ██║     ╚════██║██║██║   ██║
2023-08-07 16:49:34       ███████╗███████║██║╚██████╔╝
2023-08-07 16:49:34       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
2023-08-07 16:49:34 
2023-08-07 16:49:34    Brought to you by linuxserver.io
2023-08-07 16:49:34 ───────────────────────────────────────
2023-08-07 16:49:34 
2023-08-07 16:49:34 To support LSIO projects visit:
2023-08-07 16:49:34 https://www.linuxserver.io/donate/
2023-08-07 16:49:34 
2023-08-07 16:49:34 ───────────────────────────────────────
2023-08-07 16:49:34 GID/UID
2023-08-07 16:49:34 ───────────────────────────────────────
2023-08-07 16:49:34 
2023-08-07 16:49:34 User UID:    1000
2023-08-07 16:49:34 User GID:    1000
2023-08-07 16:49:34 ───────────────────────────────────────
2023-08-07 16:49:34 
2023-08-07 16:49:34 [custom-init] No custom files found, skipping...
2023-08-07 16:49:34 08-07 14:49:34 Info Starting Jackett v0.21.589 
2023-08-07 16:49:35 08-07 14:49:35 Info Environment version: 6.0.20 (/app/Jackett/) 
2023-08-07 16:49:35 08-07 14:49:35 Info OS version: Unix 5.15.49.0 (64bit OS) (64bit process) 
2023-08-07 16:49:35 08-07 14:49:35 Info Jackett variant: CoreLinuxMuslArm64 
2023-08-07 16:49:35 08-07 14:49:35 Info File /etc/issue: Welcome to Alpine Linux 3.18 
2023-08-07 16:49:35 08-07 14:49:35 Info Running in Docker: Yes (image build: v0.21.589-ls124) 
2023-08-07 16:49:35 08-07 14:49:35 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2023-08-07 16:49:35 08-07 14:49:35 Info App config/log directory: /config/Jackett 
2023-08-07 16:49:35 08-07 14:49:35 Info Using proxy: Disabled 
2023-08-07 16:49:35 08-07 14:49:35 Info Using FlareSolverr: No 
2023-08-07 16:49:35 08-07 14:49:35 Info Using HTTP Client: HttpWebClient2 
2023-08-07 16:49:35 08-07 14:49:35 Info Loading Native indexers ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Loaded 73 Native indexers. 
2023-08-07 16:49:35 08-07 14:49:35 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions 
2023-08-07 16:49:35 08-07 14:49:35 Info Loaded 521 Cardigann indexers. 
2023-08-07 16:49:35 08-07 14:49:35 Info Loaded 594 indexers in total 
2023-08-07 16:49:35 08-07 14:49:35 Info Adding aggregate indexer ('all' indexer) ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Adding filter indexer ('type:public' indexer) ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Adding filter indexer ('type:private' indexer) ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Adding filter indexer ('type:semi-public' indexer) ... 
2023-08-07 16:49:35 08-07 14:49:35 Info Jackett startup finished in 1.420 s 
2023-08-07 16:49:35 Hosting environment: Production
2023-08-07 16:49:35 Content root path: /app/Jackett/Content
2023-08-07 16:49:35 Now listening on: http://[::]:9117
2023-08-07 16:49:35 Application started. Press Ctrl+C to shut down.
2023-08-07 16:49:36 [ls.io-init] done.
2023-08-07 16:50:21 08-07 14:50:21 Info Checking for updates... Jackett variant: CoreLinuxMuslArm64 
2023-08-07 16:50:21 08-07 14:50:21 Info Jackett is already updated. Current version: v0.21.589
```

**Comment by sfreek76** [comment]
docker run -d \
  --name=jackett \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Etc/UTC \
  -e AUTO_UPDATE=true `#optional` \
  -e RUN_OPTS= `#optional` \
  -p 9117:9117 \
  -v /config \
  -v /downloads \
  --restart unless-stopped \
  lscr.io/linuxserver/jackett:latest


Thanks!

**Comment by sfreek76** [comment]
OK. Sorry for asking, but I'm only a simple user here, how do I do that, what do I have to put in there? If I use original paths from docker compose docker won't start the container at all...

Thanks!

**Comment by ilike2burnthing** [comment]
Out of interest, why are using Docker rather than installing natively?

**Comment by sfreek76** [comment]
> https://github.com/linuxserver/docker-jackett#docker-cli-click-here-for-more-info
> 
> You use `-v /path/to/data:/config` aka `-v /path/from/your/pc:/config`. It's `-v HOST_PATH:CONTAINER_PATH`.

Sorry, maybe I'm stupip, if I add a path I get same result, Container won't start...


> Out of interest, why are using Docker rather than installing natively?

I tried to install as a service but that did only work until restart of my Mac...

**Comment by ilike2burnthing** [comment]
> -v /config
-v /downloads

What are you replacing the above with?

---

> The service will start on each logon. You can always stop it by running `launchctl unload ~/Library/LaunchAgents/org.user.Jackett.plist` from Terminal. You can start it again it using `launchctl load ~/Library/LaunchAgents/org.user.Jackett.plist`.

https://github.com/Jackett/Jackett#installation-on-macos

**Comment by sfreek76** [comment]
> > The service will start on each logon. You can always stop it by running `launchctl unload ~/Library/LaunchAgents/org.user.Jackett.plist` from Terminal. You can start it again it using `launchctl load ~/Library/LaunchAgents/org.user.Jackett.plist`.
> 
> https://github.com/Jackett/Jackett#installation-on-macos

Thanks, did not work for me, reaearched all the details you've postet, no luck!

**Comment by ilike2burnthing** [comment]
Can you answer the question in my response?

**Comment by sfreek76** [comment]
Thanks to all for the help, but I have to deinstall Jackett from docker it crashes every 12 hours and takes other containers with it, so I had to restore from a docker backup...

Regards!

**Comment by garfield69** [comment]
maybe you will have better luck with https://github.com/Prowlarr/Prowlarr

**Comment by sfreek76** [comment]
> maybe you will have better luck with https://github.com/Prowlarr/Prowlarr

Thanks for the hint, will look into it!
