### ISSUE TITLE
修改了mteamtp.yaml中，adult中default: false为default: true之后，使用any搜索仍然搜不到XXX内容

### ISSUE THREAD

**Issue by wang923345843** [Jackett/Jackett#14611]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
windows最新版本
```

### Description

修改了mteamtp.yaml的 false为true，any搜索仍然没有XXX内容。

by the way，问另一个问题，使用docker安装jackett，config目录下没有definitions文件夹，找不到该目录下的yaml文件，请问docker版本怎么找到definitions文件夹以修改yaml，谢谢

### Logged Error Messages

```text
2023-08-07 21:36:37.3976 Info Starting Jackett v0.21.589 
2023-08-07 21:36:38.3568 Info Initiating Jackett service uninstall 
2023-08-07 21:36:38.7764 Warn The service is already uninstalled 
2023-08-07 21:36:39.0228 Info The service was uninstalled. 
2023-08-07 21:36:39.4728 Info Starting Jackett v0.21.589 
2023-08-07 21:36:39.9240 Info Initiating ReserveUrls 
2023-08-07 21:36:40.6423 Info Starting Jackett v0.21.589 
2023-08-07 21:36:41.0903 Info Initiating Jackett service install 
2023-08-07 21:36:41.9595 Info Starting Jackett v0.21.589 
2023-08-07 21:36:42.4118 Info Initiating Jackett service start 
2023-08-07 21:36:43.3768 Info Starting Jackett v0.21.589 
2023-08-07 21:36:46.3629 Info Environment version: 6.0.20 (C:\ProgramData\Jackett\) 
2023-08-07 21:36:46.3629 Info OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS) 
2023-08-07 21:36:46.3629 Info Jackett variant: CoreWindows 
2023-08-07 21:36:46.3747 Info Running in Docker: No 
2023-08-07 21:36:46.3747 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2023-08-07 21:36:46.3747 Info App config/log directory: C:\ProgramData\Jackett 
2023-08-07 21:36:46.3747 Info Using proxy: Disabled 
2023-08-07 21:36:46.3747 Info Using FlareSolverr: No 
2023-08-07 21:36:46.3747 Info Using HTTP Client: HttpWebClient2 
2023-08-07 21:36:46.3995 Info Loading Native indexers ... 
2023-08-07 21:36:46.4407 Info Loaded 73 Native indexers. 
2023-08-07 21:36:46.4956 Info Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, C:\ProgramData\Jackett\Definitions 
2023-08-07 21:36:50.1028 Info Loaded 521 Cardigann indexers. 
2023-08-07 21:36:50.1028 Info Loaded 594 indexers in total 
2023-08-07 21:36:50.1028 Info Adding aggregate indexer ('all' indexer) ... 
2023-08-07 21:36:50.1143 Info Adding filter indexer ('type:public' indexer) ... 
2023-08-07 21:36:50.1143 Info Adding filter indexer ('type:private' indexer) ... 
2023-08-07 21:36:50.1143 Info Adding filter indexer ('type:semi-public' indexer) ... 
2023-08-07 21:36:50.5816 Warn No XML encryptor configured. Key {bb85e8a7-2287-4e6e-a2d4-8549aff3f8a7} may be persisted to storage in unencrypted form. 
2023-08-07 21:36:50.6238 Info Jackett startup finished in 7.576 s 
2023-08-07 21:43:43.6159 Warn Request to Anidex failed with exception 'Challenge detected but FlareSolverr is not configured'. Retrying in 0.5s... (Attempt 1 of 2). 
2023-08-07 21:43:44.2612 Warn Request to Anidex failed with exception 'Challenge detected but FlareSolverr is not configured'. Retrying in 1s... (Attempt 2 of 2). 
2023-08-07 21:43:44.9151 Info Test search in Anime Tosho => Found 75 releases [2224ms] 
2023-08-07 21:43:45.4109 Error FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured 

[v0.21.589.0] FlareSolverrSharp.Exceptions.FlareSolverrException: Challenge detected but FlareSolverr is not configured
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass12_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in ./Jackett.Common/Indexers/BaseIndexer.cs:line 508
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 507
   at Jackett.Common.Indexers.Anidex.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Anidex.cs:line 201
   at Jackett.Common.Indexers.Anidex.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Anidex.cs:line 158
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61


2023-08-07 21:44:25.6928 Info Test search in BT.etree => Found 50 releases [4676ms] 
2023-08-07 21:44:54.2936 Info Manual search in M-Team - TP (2FA) for kink => Found 32 releases [15375ms] 
2023-08-07 21:46:33.6208 Info Manual search in M-Team - TP for kink => Found 32 releases [5443ms]
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/100781270/77d62bf1-257b-4724-ac81-6504179b1c54)
![image](https://github.com/Jackett/Jackett/assets/100781270/2c253048-bb7e-4fbb-82e9-6967b9d351ea)
![image](https://github.com/Jackett/Jackett/assets/100781270/14cb2c0c-4913-46f5-98d9-d6b205000a54)
![image](https://github.com/Jackett/Jackett/assets/100781270/85c5d17d-775c-4f76-bdb1-9b9b0d0c719c)
![image](https://github.com/Jackett/Jackett/assets/100781270/92d86545-5ccc-4d00-9932-3a90a2a489fb)

**Comment by ilike2burnthing** [comment]
Did you restart Jackett after saving those changes to the definition file? If not, do so.

I do not have an account for the tracker, but by changing the domain and removing the login test I have been able to test that the indexer should be working.

Enable enhanced logging and perform a search for `kink`. You should then see in the logs URLs beginning:

```text
https://kp.m-team.cc/torrents.php?cat401=1&cat419=1&cat420=1&cat421=1&cat439=1&cat403=1&cat402=1&cat435=1&cat438=1&cat404=1&cat405=1&cat407=1&cat422=1&cat423=1&cat427=1&cat409=1&search=kink&incldead=
```

```text
https://kp.m-team.cc/adult.php?cat410=1&cat429=1&cat424=1&cat430=1&cat426=1&cat437=1&cat431=1&cat432=1&cat436=1&cat425=1&cat433=1&cat411=1&cat412=1&cat413=1&search=kink&incldead=
```

```text
https://kp.m-team.cc/music.php?cat406=1&cat408=1&cat434=1&search=kink&incldead=
```

If so, then all 3 searches are being performed. If not, then you can provide the full enhanced log - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

---

For Docker, you need to create a new path for custom indexers. Using your above screenshot, this would need to be:
`...\DS220PLUS\docker\Jackett\config\cardigann\definitions`

**Comment by wang923345843** [comment]
> definitions
im sorry，我没有把这个目录设置出来，请问是哪里不对，谢谢
![image](https://github.com/Jackett/Jackett/assets/100781270/647e7f5a-b619-486c-9bc8-13d18409878a)

**Comment by wang923345843** [comment]
> definitions
这样设置也不出现definitions文件夹
![image](https://github.com/Jackett/Jackett/assets/100781270/5206ef7d-d254-4206-a741-779dcd6574a7)

**Comment by wang923345843** [comment]
> > ![258826235-92d86545-5ccc-4d00-9932-3a90a2a489fb](https://user-images.githubusercontent.com/59480337/258992820-8dee81e4-9ca7-4c48-a433-0147151d883c.png)
> 
> > 对于 Docker，您需要为自定义索引器创建新路径。使用上面的屏幕截图，这需要是：
> > `...\DS220PLUS\docker\Jackett\config\cardigann\definitions`
> 
> 您不需要新的 Docker 卷映射，只需将自定义索引器添加到上面的新文件夹中，重新启动 Jackett，然后添加新索引器即可。

您的意思是我手动创建cardigann\definitions这个目录对吗，
![image](https://github.com/Jackett/Jackett/assets/100781270/8e75a89c-2dd6-4e91-b6b3-3acf1a5e5d8b)
![image](https://github.com/Jackett/Jackett/assets/100781270/bb3e1a01-a6a6-4450-95cc-7bdf9f3db81b)
然后手动添加yaml文件，把这个yaml单独添加到cardigann\definitions，然后修改这个yaml的default: false为default: true。
这样jackett就会生效对吗。
那么yaml手动添加到这个目录下，yaml如何获得呢？因为我可以找到windows版本的definitions文件夹，我可以把windows版本的definitions路径下的yaml手动添加到docker刚刚创建的文件夹下吗？

**Comment by wang923345843** [comment]
> > ![258826235-92d86545-5ccc-4d00-9932-3a90a2a489fb](https://user-images.githubusercontent.com/59480337/258992820-8dee81e4-9ca7-4c48-a433-0147151d883c.png)
> 
> > 对于 Docker，您需要为自定义索引器创建新路径。使用上面的屏幕截图，需要是：
> > `...\DS220PLUS\docker\Jackett\config\cardigann\definitions`
> 
> 你不需要新的 Docker 卷映射，只需将自定义索引器添加到上面的新文件夹中，重新启动 Jackett，然后添加新的索引器即可。

最后我是这么操作的
![image](https://github.com/Jackett/Jackett/assets/100781270/5ed66960-b79d-4819-b142-16c1f332cb2f)

**Comment by ilike2burnthing** [comment]
That's the wrong path, look again.

https://github.com/Jackett/Jackett/issues/14603#issuecomment-1666521784

**Comment by wang923345843** [comment]
> 

![image](https://github.com/Jackett/Jackett/assets/100781270/84a0d72a-6664-409e-81f6-cdcba8ac0280)
this path is right？

**Comment by ilike2burnthing** [comment]
Yes. Working?

**Comment by wang923345843** [comment]
> 是的。在职的？

这个是我手动创建的目录和复制的windows的yaml，现在修改一下default: false为default: true，看看能不能生效

**Comment by garfield69** [comment]
do not forget to change the id and name in the indexers you are editing, so you can tell them apart from the ones that come with docker on your jackett dashboard.

**Comment by wang923345843** [comment]
> Yes. Working?

IM sorry，now i can use Manual search find XXX films。but i meet another question。我使用另一个叫做nastool的程序，使用jackett的网址和api来搜索电影，但是我无法搜索到m-team的东西，搜不到任何电影。但是用其他的索引器可以搜到。
进入jackett 的Manual search也能搜到，就是使用nastool搜索不到，请赐教，thank you again！！！。
![image](https://github.com/Jackett/Jackett/assets/100781270/40948983-3834-43cf-a951-1b7eaf6ebb17)
![image](https://github.com/Jackett/Jackett/assets/100781270/3224a834-90d0-470b-b3e3-ec1a7f9bd43e)
我在日志中看到了Torznab字样，使用nastool好像是用它来搜索的，结果失败

**Comment by wang923345843** [comment]
> do not forget to change the id and name in the indexers you are editing, so you can tell them apart from the ones that come with docker on your jackett dashboard.

thanks for answer my question，我目前就遇到了好像你说的问题，请问如何操作，我对于代码不了解，不是很明白如何操作，thank you again

**Comment by wang923345843** [comment]
> > 是的。在职的？
> 
> 这是我手动创建的目录并复制的windows的yaml，现在修改一下default: false为default: true，看看能不能生效
[log.txt](https://github.com/Jackett/Jackett/files/12292153/log.txt)

**Comment by ilike2burnthing** [comment]
Change:

```yml
id: mteamtp
name: M-Team - TP
```

to:

```yml
id: mteamtp-xxx
name: M-Team - TP-XXX
```

or anything of your choosing.

From the logs it appears to be working.

I have never used NAStool, but I would guess you would need to configure your new custom indexer with it. However, it looks like NAStool was abandoned earlier this year - https://github.com/NAStool/nas-tools. If you want alternatives, I suggest looking at Sonarr and Radarr.
