### ISSUE TITLE
[rousi]: they have a captcha now

### ISSUE THREAD

**Issue by KyleSanderson** [Jackett/Jackett#14620]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
v0.21.611
```

### Description

They've added a captcha to the login page.

### Logged Error Messages

```text
08-09 23:41:44 Error Error on for Rousi.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://rousi.zip/login.php using form selector form[action="takelogin.php"]   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 603   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1715
```

**Comment by garfield69** [comment]
That is nothing new, the indexer has always been able to present a captcha image in the config when you use the dashboard indexer edit, and generates an error message if you get the captcha wrong.
Naturally this means that you have to regularly edit and enter the new code whenever your session expires.
Are you having problems viewing the captcha code in the config?

**Comment by KyleSanderson** [comment]
> That is nothing new, the indexer has always been able to present a captcha image in the config when you use the dashboard indexer edit, and generates an error message if you get the captcha wrong. Naturally this means that you have to regularly edit and enter the new code whenever your session expires. Are you having problems viewing the captcha code in the config?

Yes, the captcha field isn't there at all in my config. It previously worked as well.

**Comment by garfield69** [comment]
The indexer is working for me which suggests that the issue is at your end.
I suggest you provide an enhanced log so we can take a look and see if we can find a clue to what is going on.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by KyleSanderson** [comment]
Yeah ok - so there is indeed something wrong with Jackett itself. The captcha is there on initial add, and then gone for all subsequent reconfigurations. Same thing happened with dajiao

**Comment by KyleSanderson** [comment]
09-04 13:14:34 Info CardigannIndexer(dajiao): Relogin required
09-04 13:14:34 Error Error on 20230904131434 for Dajiao.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://dajiao.cyou/login.php using form selector form[action="takelogin.php"]
09-04 13:14:34 Error Jackett.Common.IndexerException: Exception (dajiao): Login failed: No form found on https://dajiao.cyou/login.php using form selector form[action="takelogin.php"]
[v0.21.741.0] Jackett.Common.IndexerException: Exception (dajiao): Login failed: No form found on https://dajiao.cyou/login.php using form selector form[action="takelogin.php"]
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://dajiao.cyou/login.php using form selector form[action="takelogin.php"]
09-04 13:17:38 Error Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://dajiao.cyou/login.php using form selector form[action="takelogin.php"]
[v0.21.741.0] Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://dajiao.cyou/login.php using form selector form[action="takelogin.php"]
09-04 13:18:54 Error Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://dajiao.cyou/login.php using form selector form[action="takelogin.php"]
[v0.21.741.0] Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://dajiao.cyou/login.php using form selector form[action="takelogin.php"]
09-04 13:21:02 Info Request starting HTTP/1.1 GET http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693858856242 - -
09-04 13:21:02 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693858856242
09-04 13:21:02 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693858856242
09-04 13:21:02 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693858856242
09-04 13:21:02 Debug The request path /api/v2.0/indexers/dajiao/config does not match a supported file type
09-04 13:21:02 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/dajiao/config'
09-04 13:21:20 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/dajiao/config'
09-04 13:21:29 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://dajiao.cyou/login.php)
09-04 13:21:29 Info Request starting HTTP/1.1 GET http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693858856243 - -
09-04 13:21:29 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693858856243
09-04 13:21:29 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693858856243
09-04 13:21:29 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693858856243
09-04 13:21:29 Debug The request path /api/v2.0/indexers/dajiao/config does not match a supported file type
09-04 13:21:29 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/dajiao/config'
09-04 13:21:29 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/dajiao/config'
09-04 13:21:29 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://dajiao.cyou/login.php)

**Comment by garfield69** [comment]
need more of the log. The debug and html that is most useful happens after that last message in your snippet, thats shows what is returned by the site after the GET Url is actioned.

**Comment by KyleSanderson** [comment]
```
09-04 13:34:05 Info Request starting HTTP/1.1 GET http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693859637718 - -
09-04 13:34:05 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693859637718
09-04 13:34:05 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693859637718
09-04 13:34:05 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693859637718
09-04 13:34:05 Debug The request path /api/v2.0/indexers/dajiao/config does not match a supported file type
09-04 13:34:05 Debug AuthenticationScheme: Cookies was successfully authenticated.
09-04 13:34:05 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/dajiao/config'
09-04 13:34:05 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/dajiao/config'
09-04 13:34:05 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
09-04 13:34:05 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
09-04 13:34:05 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
09-04 13:34:05 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
09-04 13:34:05 Debug Execution plan of resource filters (in the following order): None
09-04 13:34:05 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
09-04 13:34:05 Debug Execution plan of exception filters (in the following order): None
09-04 13:34:05 Debug Execution plan of result filters (in the following order): None
09-04 13:34:05 Debug Authorization was successful.
09-04 13:34:05 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
09-04 13:34:05 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
09-04 13:34:05 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://dajiao.cyou/login.php)
09-04 13:34:06 Debug WebClient(HttpWebClient2): Returning OK => 3756 bytes
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="NexusPHP" />
<title>打胶 - Powered by NexusPHP</title>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="search" type="application/opensearchdescription+xml" title="打胶 Torrents" href="opensearch.php" />
<link rel="stylesheet" href="styles/mediumfont.css" type="text/css" />
<link rel="stylesheet" href="styles/sprites.css" type="text/css" />
<link rel="stylesheet" href="pic/forum_pic/chs/forumsprites.css" type="text/css" />
<link rel="stylesheet" href="styles/Classic/theme.css" type="text/css" />
<link rel="stylesheet" href="styles/Classic/DomTT.css" type="text/css" />
<link rel="stylesheet" href="styles/curtain_imageresizer.css" type="text/css" />
<link rel="stylesheet" href="styles/nexus.css" type="text/css" />
<link rel="alternate" type="application/rss+xml" title="Latest Torrents" href="torrentrss.php" />
<script type="text/javascript" src="js/curtain_imageresizer.js"></script>
<script type="text/javascript" src="js/ajaxbasic.js"></script>
<script type="text/javascript" src="js/common.js"></script>
<script type="text/javascript" src="js/domLib.js"></script>
<script type="text/javascript" src="js/domTT.js"></script>
<script type="text/javascript" src="js/domTT_drag.js"></script>
<script type="text/javascript" src="js/fadomatic.js"></script>
<script type="text/javascript" src="js/jquery-1.12.4.min.js"></script>
<script type="text/javascript">jQuery.noConflict();</script>
<script type="text/javascript" src="vendor/layer-v3.5.1/layer/layer.js"></script>
</head>
<body style="background-image:url(https://ik.jcwsr.top:9989/i/2023/08/21/1692554700.jpg);">
<table class="head" cellspacing="0" cellpadding="0" align="center" style="width: 1200px">
	<tr>
		<td class="clear">
			<div class="logo_img"><a href='https://dajiao.cyou/torrents.php?tag_id=3'><img src="https://ik.jcwsr.top:9989/i/2023/06/05/1685897318.png" alt="打胶" title="打胶 - " /></a></div>
		</td>
		<td class="clear nowrap" align="right" valign="middle">
		</td>
	</tr>
</table>

<table class="mainouter" width="1200" cellspacing="0" cellpadding="5" align="center">
	<tr><td id="nav_block" class="text" align="center">
			<a href="login.php"><font class="big"><b>登录</b></font></a> / <a href="signup.php"><font class="big"><b>注册</b></font></a>
<table align="center" class="main" width="500" border="0" cellpadding="0" cellspacing="0"><tr><td class="embedded">
<h2>Login 锁定！(认证的最大错误尝试次数Login次已到)</h2>
<table width="100%" border="1" cellspacing="0" cellpadding="10"><tr><td class="text">我们怀疑你在欺骗系统，因此禁用了你的IP地址！</td></tr></table></td></tr></table>
</td></tr></table><div id="footer"><div style="margin-top: 10px; margin-bottom: 30px;" align="center"> (c)  <a href="https://dajiao.cyou" target="_self">打胶</a> 2023 Powered by <a href="aboutnexus.php">NexusPHP</a><br /><br />[page created in <b> 0.006 </b> sec with <b>2</b> db queries, <b>4</b> reads and <b>0</b> writes of Redis and <b>1.50 MB</b> ram]</div>
<div style="display: none;" id="lightbox" class="lightbox"></div><div style="display: none;" id="curtain" class="curtain"></div></div><script type="application/javascript" src="js/nexus.js"></script>
<script type="application/javascript" src="vendor/jquery-goup-1.1.3/jquery.goup.min.js"></script>
<script>
jQuery(document).ready(function(){
    jQuery.goup()
});
</script><img id="nexus-preview" style="display: none; position: absolute" src="" /></body></html>
09-04 13:34:06 Debug updating Cookies  =>
09-04 13:34:06 Debug CardigannIndexer (dajiao): No captcha image found
09-04 13:34:06 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter
09-04 13:34:06 Debug No information found on request to perform content negotiation.
09-04 13:34:06 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
09-04 13:34:06 Debug Attempting to select the first formatter in the output formatters list which can write the result.
09-04 13:34:06 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response.
09-04 13:34:06 Info Executing OkObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'.
09-04 13:34:06 Debug The response will be compressed with 'br'.
09-04 13:34:06 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 573.9214ms
09-04 13:34:06 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
09-04 13:34:06 Debug Connection id "0HMTDGE3LEAV5" completed keep alive response.
09-04 13:34:06 Info Request finished HTTP/1.1 GET http://localhost:9117/api/v2.0/indexers/dajiao/config?_=1693859637718 - - - 200 - application/json;+charset=utf-8 750.3380ms
```

**Comment by KyleSanderson** [comment]
```
09-04 13:39:41 Info Request starting HTTP/1.1 POST http://localhost:9117/api/v2.0/indexers/rousi/config application/json 388
09-04 13:39:41 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/rousi/config
09-04 13:39:41 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/rousi/config
09-04 13:39:41 Debug Request is continuing in applying rules. Current url is http://localhost:9117/api/v2.0/indexers/rousi/config
09-04 13:39:41 Debug POST requests are not supported
09-04 13:39:41 Debug AuthenticationScheme: Cookies was successfully authenticated.
09-04 13:39:41 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/rousi/config'
09-04 13:39:41 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/rousi/config'
09-04 13:39:41 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
09-04 13:39:41 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
09-04 13:39:41 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett).
09-04 13:39:41 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
09-04 13:39:41 Debug Execution plan of resource filters (in the following order): None
09-04 13:39:41 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
09-04 13:39:41 Debug Execution plan of exception filters (in the following order): None
09-04 13:39:41 Debug Execution plan of result filters (in the following order): None
09-04 13:39:41 Debug Authorization was successful.
09-04 13:39:41 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
09-04 13:39:41 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
09-04 13:39:41 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...
09-04 13:39:41 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ...
09-04 13:39:41 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'.
09-04 13:39:41 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'.
09-04 13:39:41 Debug Connection id "0HMTDGE3LEB1S", Request id "0HMTDGE3LEB1S:00000007": started reading request body.
09-04 13:39:41 Debug Connection id "0HMTDGE3LEB1S", Request id "0HMTDGE3LEB1S:00000007": done reading request body.
09-04 13:39:41 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
09-04 13:39:41 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
09-04 13:39:41 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...
09-04 13:39:41 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
09-04 13:39:41 Debug CACHE CleanIndexerCache / Indexer: rousi
09-04 13:39:41 Debug CACHE PruneCacheByTtl / Pruned queries: 0
09-04 13:39:41 Debug CACHE Status / Total cached results: 1213
09-04 13:39:41 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 32.3759ms
09-04 13:39:41 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
09-04 13:39:41 Error Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://rousi.zip/login.php using form selector form[action="takelogin.php"]

[v0.21.741.0] Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://rousi.zip/login.php using form selector form[action="takelogin.php"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 603
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

09-04 13:39:41 Debug The response will be compressed with 'br'.
09-04 13:39:41 Debug Connection id "0HMTDGE3LEB1S" completed keep alive response.
09-04 13:39:41 Info Request finished HTTP/1.1 POST http://localhost:9117/api/v2.0/indexers/rousi/config application/json 388 - 500 - application/json 140.9903ms
```

**Comment by garfield69** [comment]
the page the web site returned states:
`我们怀疑你在欺骗系统，因此禁用了你的IP地址！`
which google translates as:
`We suspect you are spoofing the system and have disabled your IP address!`

you need to contact the web site admins and ask them to unblock your IP address

**Comment by KyleSanderson** [comment]
ugh. sorry man. thank you for looking

**Comment by garfield69** [comment]
as for the rousi log, I cant tell what is going on, I don't see the html returned by rousi in response to the get login.php page
