### ISSUE TITLE
[kamept] (updating) Error: 失败图片代码无效！不要返回，图片代码已被清除！点击这里获取新的图片代码。

### ISSUE THREAD

**Issue by KanoYL** [Jackett/Jackett#14628]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.21.635
Docker / Linux
Use Http Proxy/FlareSolverr
```

### Description

FlareSolverr seemed didn't work with Cloudflare Turnstile

### Logged Error Messages

```text
2023-08-13 12:38:56.4274 Debug Connection id "0HMSRAJNBA09F" received FIN.
2023-08-13 12:38:56.4274 Debug Connection id "0HMSRAJNBA09F" sending FIN because: "The Socket transport's send loop completed gracefully."
2023-08-13 12:38:56.4274 Debug Connection id "0HMSRAJNBA09F" disconnecting.
2023-08-13 12:38:56.4345 Debug Connection id "0HMSRAJNBA09F" stopped.
2023-08-13 12:40:30.6783 Debug Connection id "0HMSRAJNBA09L" accepted.
2023-08-13 12:40:30.6783 Debug Connection id "0HMSRAJNBA09L" started.
2023-08-13 12:40:30.6783 Info Request starting HTTP/1.1 GET http://192.168.6.151:9117/api/v2.0/indexers/kamept/config?_=1691930008967 - -
2023-08-13 12:40:30.6783 Debug Request is continuing in applying rules. Current url is http://192.168.6.151:9117/api/v2.0/indexers/kamept/config?_=1691930008967
2023-08-13 12:40:30.6783 Debug Request is continuing in applying rules. Current url is http://192.168.6.151:9117/api/v2.0/indexers/kamept/config?_=1691930008967
2023-08-13 12:40:30.6783 Debug Request is continuing in applying rules. Current url is http://192.168.6.151:9117/api/v2.0/indexers/kamept/config?_=1691930008967
2023-08-13 12:40:30.6783 Debug The request path /api/v2.0/indexers/kamept/config does not match a supported file type
2023-08-13 12:40:30.6819 Debug AuthenticationScheme: Cookies was successfully authenticated.
2023-08-13 12:40:30.6819 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/kamept/config'
2023-08-13 12:40:30.6819 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/kamept/config'
2023-08-13 12:40:30.6819 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
2023-08-13 12:40:30.6819 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
2023-08-13 12:40:30.6819 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2023-08-13 12:40:30.6819 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2023-08-13 12:40:30.6819 Debug Execution plan of resource filters (in the following order): None
2023-08-13 12:40:30.6819 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2023-08-13 12:40:30.6857 Debug Execution plan of exception filters (in the following order): None
2023-08-13 12:40:30.6857 Debug Execution plan of result filters (in the following order): None
2023-08-13 12:40:30.6857 Debug Authorization was successful.
2023-08-13 12:40:30.6857 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2023-08-13 12:40:30.6857 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2023-08-13 12:40:30.6857 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter
2023-08-13 12:40:30.6857 Debug No information found on request to perform content negotiation.
2023-08-13 12:40:30.6857 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
2023-08-13 12:40:30.6857 Debug Attempting to select the first formatter in the output formatters list which can write the result.
2023-08-13 12:40:30.6857 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response.
2023-08-13 12:40:30.6857 Info Executing OkObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'.
2023-08-13 12:40:30.6857 Debug The response will be compressed with 'gzip'.
2023-08-13 12:40:30.6900 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 3.8236ms
2023-08-13 12:40:30.6900 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
2023-08-13 12:40:30.6900 Debug Connection id "0HMSRAJNBA09L" completed keep alive response.
2023-08-13 12:40:30.6900 Info Request finished HTTP/1.1 GET http://192.168.6.151:9117/api/v2.0/indexers/kamept/config?_=1691930008967 - - - 200 - application/json;+charset=utf-8 10.8130ms
2023-08-13 12:40:33.5022 Info Request starting HTTP/1.1 POST http://192.168.6.151:9117/api/v2.0/indexers/kamept/config application/json 351
2023-08-13 12:40:33.5022 Debug Request is continuing in applying rules. Current url is http://192.168.6.151:9117/api/v2.0/indexers/kamept/config
2023-08-13 12:40:33.5022 Debug Request is continuing in applying rules. Current url is http://192.168.6.151:9117/api/v2.0/indexers/kamept/config
2023-08-13 12:40:33.5022 Debug Request is continuing in applying rules. Current url is http://192.168.6.151:9117/api/v2.0/indexers/kamept/config
2023-08-13 12:40:33.5022 Debug POST requests are not supported
2023-08-13 12:40:33.5022 Debug AuthenticationScheme: Cookies was successfully authenticated.
2023-08-13 12:40:33.5022 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/kamept/config'
2023-08-13 12:40:33.5022 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/kamept/config'
2023-08-13 12:40:33.5059 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2023-08-13 12:40:33.5059 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2023-08-13 12:40:33.5059 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2023-08-13 12:40:33.5059 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2023-08-13 12:40:33.5059 Debug Execution plan of resource filters (in the following order): None
2023-08-13 12:40:33.5059 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2023-08-13 12:40:33.5059 Debug Execution plan of exception filters (in the following order): None
2023-08-13 12:40:33.5099 Debug Execution plan of result filters (in the following order): None
2023-08-13 12:40:33.5099 Debug Authorization was successful.
2023-08-13 12:40:33.5099 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2023-08-13 12:40:33.5099 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2023-08-13 12:40:33.5099 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...
2023-08-13 12:40:33.5099 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ...
2023-08-13 12:40:33.5099 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'.
2023-08-13 12:40:33.5099 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'.
2023-08-13 12:40:33.5099 Debug Connection id "0HMSRAJNBA09L", Request id "0HMSRAJNBA09L:00000003": started reading request body.
2023-08-13 12:40:33.5099 Debug Connection id "0HMSRAJNBA09L", Request id "0HMSRAJNBA09L:00000003": done reading request body.
2023-08-13 12:40:33.5099 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2023-08-13 12:40:33.5099 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2023-08-13 12:40:33.5139 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...
2023-08-13 12:40:33.5139 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2023-08-13 12:40:33.5139 Debug CACHE CleanIndexerCache / Indexer: kamept
2023-08-13 12:40:33.5139 Debug CACHE PruneCacheByTtl / Pruned queries: 0
2023-08-13 12:40:33.5139 Debug CACHE Status / Total cached results: 0
2023-08-13 12:40:33.5139 Debug WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://kamept.com/takelogin.php PostData: {secret=, username=(removed) password=(removed) two_step_code=, logout=, securelogin=, ssl=yes, trackerssl=yes} RawBody: )
2023-08-13 12:40:36.8252 Debug WebClient(HttpWebClient2): Returning OK => 4074 bytes
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="NexusPHP" />
<title>KamePT - Powered by NexusPHP</title>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="search" type="application/opensearchdescription+xml" title="KamePT Torrents" href="opensearch.php" />
<link rel="stylesheet" href="styles/nexus.css?202305270024" type="text/css" />
<link rel="stylesheet" href="styles/mediumfont.css?202305270024" type="text/css" />
<link rel="stylesheet" href="styles/sprites.css?202305270024" type="text/css" />
<link rel="stylesheet" href="pic/forum_pic/chs/forumsprites.css?202305270024" type="text/css" />
<link rel="stylesheet" href="styles/Classic/theme.css?202305270024" type="text/css" />
<link rel="stylesheet" href="styles/Classic/DomTT.css?202305270024" type="text/css" />
<link rel="stylesheet" href="styles/curtain_imageresizer.css?202305270024" type="text/css" />
<link rel="alternate" type="application/rss+xml" title="Latest Torrents" href="torrentrss.php" />
<script type="text/javascript" src="js/curtain_imageresizer.js?202305270024"></script>
<!--<script type="text/javascript" src="js/ajaxbasic.js?202305270024"></script>-->
<script type="text/javascript" src="js/common.js?202305270024"></script>
<script type="text/javascript" src="js/domLib.js?202305270024"></script>
<script type="text/javascript" src="js/domTT.js?202305270024"></script>
<script type="text/javascript" src="js/domTT_drag.js?202305270024"></script>
<script type="text/javascript" src="js/fadomatic.js?202305270024"></script>
<script type="text/javascript" src="js/jquery-1.12.4.min.js?202305270024"></script>
<script type="text/javascript">jQuery.noConflict();</script>
<script type="text/javascript" src="vendor/layer-v3.5.1/layer/layer.js?202305270024"></script>
</head>
<body>
<table class="head" cellspacing="0" cellpadding="0" align="center" style="width: 1200px">
	<tr>
		<td class="clear">
			<div class="logo_img"><img src="pic/logo2_100.png" alt="KamePT" title="KamePT - CosAV！" /></div>
		</td>
		<td class="clear nowrap" align="right" valign="middle">
<span><font size="4">本站下载超过50G，且分享率低于0.2将立即ban号　发邀不如发种，保号不如保种<br />
downloaded exceeds 50G and Ratio lower 0.2,the account will be banned immediately<br />
</font></span>		</td>
	</tr>
</table>

<table class="mainouter" width="1200" cellspacing="0" cellpadding="5" align="center">
	<tr><td id="nav_block" class="text" align="center">
			<a href="login.php"><font class="big"><b>登录</b></font></a> / <a href="signup.php"><font class="big"><b>注册</b></font></a>
<table align="center" class="main" width="500" border="0" cellpadding="0" cellspacing="0"><tr><td class="embedded">
<h2>失败</h2>
<table width="100%" border="1" cellspacing="0" cellpadding="10"><tr><td class="text">图片代码无效！<br /><b>不要返回，图片代码已被清除！</b><br /><br />点击<a href="login.php"><b>这里</b></a>获取新的图片代码。</td></tr></table></td></tr></table>
</td></tr></table><div id="footer"><div style="margin-top: 10px; margin-bottom: 30px;" align="center"> (c)  <a href="https://kamept.com" target="_self">KamePT</a> 2022-2023 Powered by <a href="aboutnexus.php">NexusPHP</a><br /><br />[page created in <b> 0.054 </b> sec with <b>4</b> db queries, <b>4</b> reads and <b>0</b> writes of Redis and <b>1.47 MB</b> ram]</div>
<div style="display: none;" id="lightbox" class="lightbox"></div><div style="display: none;" id="curtain" class="curtain"></div></div><script type="application/javascript" src="js/nexus.js"></script>
<script type="application/javascript" src="vendor/jquery-goup-1.1.3/jquery.goup.min.js"></script>
<script>
jQuery(document).ready(function(){
    jQuery.goup()
});
</script><img id="nexus-preview" style="display: none; position: absolute" src="" /></body></html>
2023-08-13 12:40:36.8325 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 3322.3256ms
2023-08-13 12:40:36.8325 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2023-08-13 12:40:36.8325 Error Jackett.Common.ExceptionWithConfigData: Error: 失败
图片代码无效！不要返回，图片代码已被清除！点击这里获取新的图片代码。

[v0.21.635.0] Jackett.Common.ExceptionWithConfigData: Error: 失败
图片代码无效！不要返回，图片代码已被清除！点击这里获取新的图片代码。
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 542
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 579
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61

2023-08-13 12:40:36.8660 Debug The response will be compressed with 'gzip'.
2023-08-13 12:40:36.8660 Debug Connection id "0HMSRAJNBA09L" completed keep alive response.
2023-08-13 12:40:36.8660 Info Request finished HTTP/1.1 POST http://192.168.6.151:9117/api/v2.0/indexers/kamept/config application/json 351 - 500 - application/json 3364.5643ms
```

**Comment by garfield69** [comment]
Yes, it appears that kamept have added an embedded cloudflare check in the login page
![image](https://github.com/Jackett/Jackett/assets/6933240/52ac9de1-ac2f-4a6b-a0da-22b751297d34)
so Jackett does not call flaresolverr in this instance.
Flaresolverr is called for the full cloudflare redirect page, the one that starts with something like `please wait while we check your connection is secure` which after solve takes you to the regular login page.
We are going to have to switch to using the cookie method for this indexer.

**Comment by garfield69** [comment]
v0.21.643
