### ISSUE TITLE
exttorrents search error

### ISSUE THREAD

**Issue by gersey** [Jackett/Jackett#14637]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-08-15 17:36:51.2704 Info Starting Jackett v0.21.648
2023-08-15 17:36:52.8765 Info Environment version: 6.0.21 (/opt/Jackett/)
2023-08-15 17:36:52.8951 Info OS version: Unix 5.10.0.23 (64bit OS) (64bit process)
2023-08-15 17:36:52.8951 Info Jackett variant: CoreLinuxAmdx64
2023-08-15 17:36:52.8951 Info File /etc/issue: Debian GNU/Linux 11 \n \l
2023-08-15 17:36:52.8985 Info Running in Docker: No
2023-08-15 17:36:52.8985 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-08-15 17:36:52.8985 Info App config/log directory: /home/user/.config/Jackett
2023-08-15 17:36:52.9033 Info Using proxy: Disabled
2023-08-15 17:36:52.9033 Info Using FlareSolverr: http://127.0.0.1:8191
2023-08-15 17:36:52.9073 Info Using HTTP Client: HttpWebClient2
```

### Description

I use the Sonarr with the Jacket. I would like to add Ext Torrents as a new indexer. Within Jacket, if I am looking it works fine.
(2023-08-15 17:49:54 | Info | Torznab search in EXT Torrents => Found 19 releases (from cache) [2ms])
In Sonarr, when I click test it shows as good, but when I search for anything I see the following error in the Jackett log.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (exttorrents): Got redirected to another domain. Try changing the indexer URL to http://ext.to/.

[v0.21.648.0] Jackett.Common.IndexerException: Exception (exttorrents): Got redirected to another domain. Try changing the indexer URL to http://ext.to/.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to http://ext.to/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult response) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 908
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1709
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 732
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 709
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 469
Error on 20230815175043 for EXT Torrents.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to http://ext.to/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult response) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 908
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1709
```

**Comment by garfield69** [comment]
Please turn on the Jackett **enhanced** logging, repeat the test with sonarr and provide the full Jackett **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by gersey** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/12352142/log.txt)

**Comment by gersey** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/12352193/log.txt)

**Comment by garfield69** [comment]
It took me a while to sort out the flow in the log you provided because you performed a search for Exttorrents and well as nCore so the log had both search activity interleaving ;-b 

But from what I can gather, it appears that the Exttorrents indexer is set up to try to fetch results from page 1 and page 2 in order to gather up to 100 results 

But it seems that Exttorrents have changed their site, so that if you make a search for page 2 and there are no results, the site redirects to you `https://ext.to/search/` which confuses Jackett.

The solution would appear to change the indexer to stop making requests for the second page. I will update the indexer.

**Comment by gersey** [comment]
Thank you for your efforts!

**Comment by garfield69** [comment]
found a better solution, keep the 2nd page search, but add a `followredirect: true` ;-)

**Comment by gersey** [comment]
It works! Thanx :)
