### ISSUE TITLE
Connection Error for Indexer

### ISSUE THREAD

**Issue by LazerDickMcCheese** [Jackett/Jackett#14631]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 11, qbittorrent, with Jackett v0.21.637
```

### Description

I installed the Jackett plugin, the .json has been updated as required, and I made a firewall rule to allow Jackett. Yet every tracker has a connection error. Look at this beautiful error:

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (torrent9): The requested address is not valid in its context.

[v0.21.637.0] Jackett.Common.IndexerException: Exception (torrent9): The requested address is not valid in its context.
 ---> System.Net.Http.HttpRequestException: The requested address is not valid in its context. (www.torrent9.fm:443)
 ---> System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 535
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 709
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 469
```

**Comment by garfield69** [comment]
I think you should start by taking qBt and its plugin out of the equation and confirm that your Jackett is set up correctly on your platform. Use the Jackett dashboard and test that you can use torrent9 successfully to get results.

In general, `address not valid` can be caused by a myriad of misconfigurations, the most common but not exclusively is a firewall or other app that is blocking access either on your platform, your router, or your ISP.

If the Jackett indexer works OK, then at least you have eliminated half the problem, and you can start digging into qBt and its plugin.

If the Jackett indexer is not working then then you have a starting place. Perhaps https://github.com/Jackett/Jackett/wiki/Troubleshooting/#a-connection-attempt-failed could be useful.

**Comment by LazerDickMcCheese** [comment]
Hey, thank you for the reply. I promise I checked that page before posting, how do I check if my ISP is "trapping DNS lookups"?


Regardless, I just manually checked every publicly available tracker in Jackett, and I can confirm that all sites used in the indexing can be accessed in my browser (except firebit.net and BullTorrent gave server errors). If I eliminated VPN issues and firewall issues, I don't see many hurdles left according to the troubleshooting guide. What am I missing?

**Comment by garfield69** [comment]
For clarity, since you have not actually stated this anywhere, are you confirming that if you use the Jackett dashboard to TEST a public indexer it fails with the same error you reported at the start?
And presumably these have never worked previously?

And that the browser you are using is running on the same machine that is running Jackett?

Please restart Jackett, view the log and scroll to the bottom and provide the last 10 lines so we can get some proper environmental info on your Jackett set up.

Re: testing ISP traps, it may be a mute question, if your browser is not using a proxy or VPN, and Jackett is not using a proxy or VPN, and a browser works but Jackett does not; but the test would be to switch your DNS service from the ISP provided one to one of the public ones like Google 8.8.8.8 or Cloudflare 1.1.1.1

**Comment by garfield69** [comment]
@ilike2burnthing  please feel free to take this one over, I'm about to become unavailable shortly, until tomorrow again.

**Comment by LazerDickMcCheese** [comment]
Testing the indexers on the dashboard results in a complete failure of all entries, the failure that started the thread was due to errors in qbittorrent. I set Jackett up and left it, assuming it would work upon install and setup, but I just found out by looking for specific results that Jackett does not (and probably has never) worked for me.

Yes, all testing has been done on one machine: the install, the browser, the client, etc.

<html><body>


2023-08-14 03:14:58 | Info | Jackett startup finished in 1.745 s
-- | -- | --
2023-08-14 03:14:58 | Info | Adding filter indexer ('type:semi-public' indexer) ...
2023-08-14 03:14:58 | Info | Adding filter indexer ('type:private' indexer) ...
2023-08-14 03:14:58 | Info | Adding filter indexer ('type:public' indexer) ...
2023-08-14 03:14:58 | Info | Adding aggregate indexer ('all' indexer) ...
2023-08-14 03:14:58 | Info | Loaded 593 indexers in total
2023-08-14 03:14:58 | Info | Loaded 521 Cardigann indexers.
2023-08-14 03:14:57 | Info | Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, C:\ProgramData\Jackett\Definitions
2023-08-14 03:14:57 | Info | Loaded 72 Native indexers.
2023-08-14 03:14:57 | Info | Loading Native indexers ...
2023-08-14 03:14:57 | Info | Using HTTP Client: HttpWebClient2
2023-08-14 03:14:57 | Info | Using FlareSolverr: No
2023-08-14 03:14:57 | Info | Using proxy: Disabled
2023-08-14 03:14:57 | Info | App config/log directory: C:\ProgramData\Jackett
2023-08-14 03:14:57 | Info | ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2023-08-14 03:14:57 | Info | Running in Docker: No
2023-08-14 03:14:57 | Info | Jackett variant: CoreWindows
2023-08-14 03:14:57 | Info | OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
2023-08-14 03:14:57 | Info | Environment version: 6.0.21 (C:\ProgramData\Jackett\)
2023-08-14 03:14:57 | Info | Starting Jackett v0.21.637


</body>
</html>

**Comment by ilike2burnthing** [comment]
Are you using a proxy or VPN?

Are you using a custom DNS or pihole which could be blocking connections?

Are you using any third-party firewall or security software which may be blocking connections?

**Comment by LazerDickMcCheese** [comment]
I'm using a paid VPN and a Pi-hole, but I whitelisted every tracker (and their subdomains) on both. I'm not using any third-party firewall/security software

**Comment by ilike2burnthing** [comment]
Disable them both and try again.

**Comment by LazerDickMcCheese** [comment]
Bad news, it's the VPN. Can I split Jackett's traffic outside of the VPN safely or would my ISP jump at that?

**Comment by ilike2burnthing** [comment]
If your provider supports split-tunnelling then you can use that to select programs that you want behind it (e.g. your torrent client) and leave Jackett working.

If your provider has a HTTP or SOCKS4/5 proxy, then you could potentially use that in Jackett's settings, but generally the only benefit for that is to get around ISP blocks (which is probably that <5%).

**Comment by LazerDickMcCheese** [comment]
Adding JackettTray to the split doesn't let the connections through, but I suspect that's a VPN issue. In other words, I believe Jackett cannot work with my setup.

**Comment by ilike2burnthing** [comment]
Again, you would add other programs to use the VPN split tunnel, like your torrent client, NOT Jackett.

**Comment by LazerDickMcCheese** [comment]
I'm referring to splitting AWAY from the VPN. I have Jackett set to circumvent the VPN with the client still going through because...ISPs and Linux distro torrents blah blah blah

**Comment by ilike2burnthing** [comment]
Rather than setting your split tunnel to be everything apart from select programs, set it to only select programs (e.g. your torrent client).

**Comment by LazerDickMcCheese** [comment]
The trackers still fail in both the dashboard and client.

**Comment by ilike2burnthing** [comment]
Then yes, it would seem to be an issue with your VPN provider. I can only opening an issue with their support team.

**Comment by LazerDickMcCheese** [comment]
I'm using Nord

**Comment by ilike2burnthing** [comment]
Then open an issue with support, there's some issue with your setup and I'm not going to be able to troubleshoot it for you as it's working for me.

**Comment by LazerDickMcCheese** [comment]
Problem solved, the solution was to set the VPN as a proxy and disable the machine-wide implementation of the VPN.

Future readers: check for browser extensions for your VPN and use ipleak to test your client.

**Comment by LazerDickMcCheese** [comment]
Never mind, setting the VPN as a SOCKS5 proxy makes qbittorrent incapable of detecting search plugins. Only one solution left: don't use Jackett.
