### ISSUE TITLE
Redirect, Fail and Screw configuration

### ISSUE THREAD

**Issue by TehAppKiller** [Jackett/Jackett#14645]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: /home/xxx/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 22.04.3 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.0.79 (64bit OS) (64bit process)
Environment version: 6.0.21 (/opt/Jackett/)
Starting Jackett v0.21.662
```

### Description

Using 1337 indexer through URL https://1337x.unblockit.vegas/
Work at first and after some time (at least once a day) a redirection problem pop-up and Jackett destroys the configuration applying lower URL https://unblockit.vegas/ which of course never works as is not a valid URL indexer.

### Logged Error Messages

```text
2023-08-17 16:05:10	Error	
Jackett.Common.IndexerException: Exception (1337x): Got redirected to another domain. Try changing the indexer URL to https://unblockit.vegas/. Updated site link, please try again.

[v0.21.655.0] Jackett.Common.IndexerException: Exception (1337x): Got redirected to another domain. Try changing the indexer URL to https://unblockit.vegas/. Updated site link, please try again.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://unblockit.vegas/. Updated site link, please try again.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult response) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 908
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1709
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 732
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 414
   
-----
   
2023-08-17 16:05:10	Error	
Error on 20230817160510 for 1337x.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://unblockit.vegas/. Updated site link, please try again.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult response) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 908
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1709




<html>
<head><title>302 Found</title><script src="//achcdn.com/script/suv4.js" data-adel="lwsu" zid="4324615"></script></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by garfield69** [comment]
Looks like unblockit might be having some server issues. When that service fails to connect to its 1337x proxy it automatically redirects back to its home page at unblockit.vegas 
And because the indexer has a followredirect which was needed for some of the other alternate sitelinks, it auto updates the sitelink.
I will investigate if that followredirect is still needed, removing it would prevent the config sitelink being auto-updated.

**Comment by garfield69** [comment]
I've tested all the alternate sitelinks and none require the followredirect so I have removed it.

**Comment by garfield69** [comment]
v0.21.668

**Comment by TehAppKiller** [comment]
oHi o/
Same problem for limetorrents.unblockit.esq
Jackett Version v0.21.763
Don't know if same thing can be done ?!
Thx

NB: I dropped 1337x as it returns only 20 results (1st page) (even if offset is to 100) and so fails to acknowledge a suitable result with at least 1 peer in time (= time to update with peers to >0, while still appears in 20 first results list ; maybe cache keeps peers to 0 too (?), didn't check much more)

**Comment by garfield69** [comment]
Did some digging. Looks like back in March 2020 I added the followredirect when I added unblockit for the first time.  6f854d0
But now, if 1337x does not need the followredirect, then its likely none of the others needs it either, so I'll drop it from them too.

**Comment by TehAppKiller** [comment]
oHi o/

Sorry for disturbing : (
Unfortunately manual search does not work

The original request works into browser:
https://limetorrents.unblockit.esq/search/all/my%20query/date/1/

but Jackett checkings fails and returns a none-working final request:
https://unblockit.esq/?domain=http://limetorrents.unblockit.esq&status=403&request=/search/all/my%20query/date/1/

Not sure why : /

Thx again <3

```
2023-09-27 07:47:13	Error	
Jackett.Common.IndexerException: Exception (limetorrents): Got redirected to another domain. Try changing the indexer URL to https://unblockit.esq/.

[v0.21.916.0] Jackett.Common.IndexerException: Exception (limetorrents): Got redirected to another domain. Try changing the indexer URL to https://unblockit.esq/.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://unblockit.esq/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult response) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 898
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1709
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 732
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 709
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in ./Jackett.Server/Controllers/ResultsController.cs:line 233

---

2023-09-27 07:47:13	Error	
Error on 20230927074713 for LimeTorrents.txtJackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://unblockit.esq/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebResult response) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 898
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1709

<html>
<head><title>302 Found</title><script src="//achcdn.com/script/suv4.js" data-adel="lwsu" zid="4324615"></script></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

---

2023-09-27 07:47:13	Debug	
WebClient(HttpWebClient2): Returning Redirect => https://unblockit.esq/?domain=http://limetorrents.unblockit.esq&status=403&request=/search/all/my query/date/1/ 220 bytes
<html>
<head><title>302 Found</title><script src="//achcdn.com/script/suv4.js" data-adel="lwsu" zid="4324615"></script></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

---

2023-09-27 07:47:13	Debug	
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://limetorrents.unblockit.esq/search/all/my%20query/date/1/)
```
