### ISSUE TITLE
[hhanclub] (testing) Test search in HHanClub => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by fayswing** [Jackett/Jackett#14647]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-07-21 21:18:56.6845 Info Starting Jackett v0.21.505 
2023-07-21 21:18:58.2877 Info Environment version: 6.0.20 (/app/Jackett/) 
2023-07-21 21:18:58.3060 Info OS version: Unix 4.4.59.0 (64bit OS) (64bit process) 
2023-07-21 21:18:58.3100 Info Jackett variant: CoreLinuxMuslAmdx64 
2023-07-21 21:18:58.3100 Info File /etc/issue: Welcome to Alpine Linux 3.18 
2023-07-21 21:18:58.3156 Info Running in Docker: Yes (image build: v0.21.505-ls115) 
2023-07-21 21:18:58.3179 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2023-07-21 21:18:58.3186 Info App config/log directory: /config/Jackett 
2023-07-21 21:18:58.3200 Info Using proxy: Disabled 
2023-07-21 21:18:58.3204 Info Using FlareSolverr: No 
2023-07-21 21:18:58.3231 Info Using HTTP Client: HttpWebClient2
```

### Description

Because the website has changed its interface, it cannot be used now
Request update Thank you！

### Logged Error Messages

```text
[v0.21.671.0] System.Exception: Test search in HHanClub => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 327
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
```

**Comment by garfield69** [comment]
v0.21.674

**Comment by fayswing** [comment]
Thank you for your reply and update。
Thank you very much!
