### ISSUE TITLE
TorrentLeech - System.UriFormatException: Invalid URI: The URI scheme is not valid

### ISSUE THREAD

**Issue by muppet3000** [Jackett/Jackett#14654]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
08-22 06:54:26 Info Starting Jackett v0.21.674
08-22 06:54:28 Info Environment version: 6.0.21 (/app/Jackett/)
08-22 06:54:28 Info OS version: Unix 3.10.0.1160 (64bit OS) (64bit process)
08-22 06:54:28 Info Jackett variant: CoreLinuxMuslAmdx64
08-22 06:54:28 Info File /etc/issue: Welcome to Alpine Linux 3.18
08-22 06:54:28 Info Running in Docker: Yes (image build: v0.21.674-ls138)
08-22 06:54:28 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
08-22 06:54:28 Info App config/log directory: /config/Jackett
08-22 06:54:28 Info Using proxy: Disabled
08-22 06:54:28 Info Using FlareSolverr: No
08-22 06:54:28 Info Using HTTP Client: HttpWebClient2
```

### Description

First time using Jackett so happy to be told that I'm doing something wrong.

I've configured TorrentLeech as the tracker and the test passed successfully, however when I try to perform a search or copy the RSS feed for it I get a `System.UriFormatException: Invalid URI: The URI scheme is not valid` error (full errors provided below).

Any help to fix the issue would be greatly appreciated.

### Logged Error Messages

Error when performing a search:
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.

[v0.21.674.0] System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Jackett.Server.Services.ServerService.ConvertToProxyLink(Uri link, String serverUrl, String indexerId, String action, String file) in ./Jackett.Server/Services/ServerService.cs:line 61
   at Jackett.Server.Controllers.ResultsController.ConfigureCacheResults(IEnumerable`1 results) in ./Jackett.Server/Controllers/ResultsController.cs:line 587
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in ./Jackett.Server/Controllers/ResultsController.cs:line 296
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

Error when accessing the RSS feed:
```
System.UriFormatException: Invalid URI: The URI scheme is not valid.

[v0.21.674.0] System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Jackett.Server.Services.ServerService.ConvertToProxyLink(Uri link, String serverUrl, String indexerId, String action, String file) in ./Jackett.Server/Services/ServerService.cs:line 61
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__4(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 426
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 431
```
```


### Screenshots

_No response_

**Comment by garfield69** [comment]
Unfortunately all the traces tell us is that the URI is not valid, when what we really need to see is the URI in question.
Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by muppet3000** [comment]
@garfield69  Thanks for the swift response. Enabling the enhanced logging helped me work out what the issue was.
The tracker worked absolutely fine, the issue was with the reverse proxy setup that I had.
When I tested it directly it worked fine.

I'm not 100% sure what was incorrect with my config, but this is what is working for me now:
Apache Config snippet:
```
<Location /jackett>
        ProxyPass http://jackett:9117/jackett
        ProxyPassReverse http://jackett:9117/jackett
</Location>
```

Jackett config snippet:
```
"BasePathOverride": "/jackett",
```

I feel like I may have had an extra `/` somewhere in my Apache config where it wasn't needed.

**Comment by garfield69** [comment]
\o/
