### ISSUE TITLE
Exception (eztv): Network unreachable: Network unreachable (eztv.re:443)

### ISSUE THREAD

**Issue by lavcanskiz** [Jackett/Jackett#14658]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Environment
OS: Unraid

Running Jackett as a Docker

Jackett Version: v0.21.687

Last Working Jackett Version:Do not remember. Maybe 5 updates ago...

Are you using a proxy or VPN? No
```

### Description

EZTV is not securing a connection. When testing via jackett this is the following error that appears at the bottom of my screen.

Exception (eztv): Network unreachable: Network unreachable (eztv.re:443)

### Logged Error Messages

```text
2023-08-23 19:12:35	Error	
Jackett.Common.IndexerException: Exception (eztv): Network unreachable

[v0.21.687.0] Jackett.Common.IndexerException: Exception (eztv): Network unreachable
 ---> System.Net.Http.HttpRequestException: Network unreachable (eztv.re:443)
 ---> System.Net.Sockets.SocketException (101): Network unreachable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![Jackett](https://github.com/Jackett/Jackett/assets/87933197/02643b3b-6414-4221-9153-ea837737d3a2)

**Comment by ilike2burnthing** [comment]
Are other indexers working?

Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

**Comment by lavcanskiz** [comment]
All other indexes are working.

I have IPV6 already disabled.

**Comment by garfield69** [comment]
Try accessing the docker image via your terminal and doing a curl and openssl from within the image 
```
docker exec -it jackett /bin/bash
```
and see what you get from the following:
```
openssl s_client -connect eztv.re:443
```
and
```
curl -vvv https://eztv.re/
```

**Comment by lavcanskiz** [comment]
Here is the response I received

root@<Host>:~# docker exec -it jackett /bin/bash
root@ <Host>  :/# openssl s_client -connect eztv.re:443
bash: openssl: command not found
root@ <Host>  :/# curl -vvv https://eztv.re/
* processing: https://eztv.re/
*   Trying 121.200.0.52:443...
*   Trying [2403:5800:3:53::404]:443...
* Immediate connect fail for 2403:5800:3:53::404: Address not available

Kind Regards,


*Zlatko Lavcanski*

E: ***@***.***

M: +61 4 31 751 323

**Comment by garfield69** [comment]
@ilike2burnthing  what do you make of that strange response, its like the OP did not establish a session with the docker jackett image?

**Comment by garfield69** [comment]
121.200.0.52 is a broadband ISP so at a glance it would seem your attempt to access eztv.re was redirected to a black hole

have you tried using your jackett dashboard to edit the eztv indexer config, and work you way through all the alternate sitelinks?
perhaps one of those will not be blocked and you'll get results.

**Comment by lavcanskiz** [comment]
Thank you all for your quick responses.

I have tried all their other links and still the same thing. Cannot connect
to it and which is very strange as a friend has the same setup as me and he
has the latest version of Jackett and it works for him.

Kind Regards,


*Zlatko Lavcanski*

E: ***@***.***

M: +61 4 31 751 323

**Comment by garfield69** [comment]
is your friend on the same ISP as you?
If not, then consider (as a test) setting up a free system VPN, such as hide.me or proton or whatever, and see if that works.
My guess is that your ISP is blocking access to eztv

**Comment by lavcanskiz** [comment]
We are both with the same ISP. I have also removed the Jackett Docker and
installed it again and configured it and still the same issue.


Kind Regards,


*Zlatko Lavcanski*

E: ***@***.***

M: +61 4 31 751 323

**Comment by garfield69** [comment]
Ah well, this is where I leave you. Docker and linux are not my area of expertise. Perhaps ilike2burnthing may have further insights.

**Comment by lavcanskiz** [comment]
Thanks Garfield69. I really appreciate your assistance.

Kind Regards,


*Zlatko Lavcanski*

E: ***@***.***

M: +61 4 31 751 323

**Comment by lavcanskiz** [comment]
Just an update. This has been resolved.

I noticed that my DNS settings were pointing to my ISP. As soon as I
changed the DNS settings, I was able to get a successful test from EZTV.

Thank you all for your help.

Kind Regards,


*Zlatko Lavcanski*

E: ***@***.***

M: +61 4 31 751 323

**Comment by garfield69** [comment]
\o/
