### ISSUE TITLE
[mteamtp2fa] (updating) Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by hussion** [Jackett/Jackett#14657]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: YES
Using proxy: Disabled
App config/log directory: /volume3/@appdata/jackett/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
Environment version: 6.0.21 (/volume3/@appstore/jackett/share/)
```

### Description

I used DSM NAS to install jackett via kit, and also installed firefox browser in the form of docker in dsm. When I successfully logged in m-team in firefox browser and copied cookies and ua, I still failed to add them.

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match

[v0.21.687.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/1524545/0a97ac96-3d1f-4704-af21-f6a7a5c3c0fd)

**Comment by garfield69** [comment]
Given you are using a firefox docker image, perhaps you should try the Jackett docker image. Assuming the two docker images are using the same OS, then this would better match the cookie and UA cross-references.

**Comment by hussion** [comment]
> 

jlesage/firefox:latest

**Comment by garfield69** [comment]
@ilike2burnthing  this is more your cup of tea. I don't even know what the last response is supposed to mean ;-D

**Comment by ilike2burnthing** [comment]
@hussion as @garfield69 said, move to using the Jackett Docker container, rather than the natively installed version. The specific Firefox image you're using wasn't asked for.

Are you actually using 2FA for this tracker?

**Comment by hussion** [comment]
> @hussion as @garfield69 said, move to using the Jackett Docker container, rather than the natively installed version. The specific Firefox image you're using wasn't asked for.
> 
> Are you actually using 2FA for this tracker?

yes, i'm using 2FA, let me try Jackett Docker container and get back to you， thx

**Comment by hussion** [comment]
Using Jackett Docker Containers is OK, why? How to fix kit version of jackett ? @ilike2burnthing 

> @hussion as @garfield69 said, move to using the Jackett Docker container, rather than the natively installed version. The specific Firefox image you're using wasn't asked for.
> 
> Are you actually using 2FA for this tracker?

**Comment by ilike2burnthing** [comment]
Not quite sure what you mean by 'kit'. If you mean installed natively using their package manager, then it may just be a setup issue that Docker is resolving. You can have a look at the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#the-cookies-provided-by-flaresolverr-are-not-valid
