### ISSUE TITLE
IPT not working again

### ISSUE THREAD

**Issue by melbasuonyy** [Jackett/Jackett#1466]
![untitled](https://user-images.githubusercontent.com/29347988/27007888-7ed1d4da-4e73-11e7-9ff8-a983890e3338.jpg)

Hi,

I always have issues for IPtorrent.com as it's blocked by ISP however iptorrents.eu is working fine with browsers 
I'm trying to add Iptorrents indexer but I'm getting the below error msg. 

Note: I know it may by considered as duplicate issue but I have tried all the solutions on the last issues and didn't work also it was giving the same error on the previous windows version but worked I don't know how now i installed new version and it stopped 

Jackett Version: v0.7.1483
Mono: 5.01 & 4.8 tried also
Python 2.7.13

please look into the issue

**Comment by melbasuonyy** [comment]
Log:

06-11 07:14:09 Error Exception in GetConfigForm System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudFlareUtilities.ClearanceHandler.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Utils.Clients.HttpWebClient.<Run>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Utils.Clients.IWebClient.<GetString>c__async2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.BaseIndexer.<RequestStringWithCookies>c__async6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.IPTorrents.<GetConfigurationForSetup>c__async0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<GetConfigForm>c__async3.MoveNext()

**Comment by melbasuonyy** [comment]
I figured out .. I have to change the master iptorrent url to IPTORRENTS.EU i have done it by visual studio any one has easier way

Thanks

**Comment by kaso17** [comment]
This is a known limitation, I've opened #1473 as enhancement ticket. The easier workaround would have been to manually create the JSON config file.
