### ISSUE TITLE
Invalid URI: The hostname could not be parsed(kinozal/dotnet)

### ISSUE THREAD

**Issue by IGNATOV93** [Jackett/Jackett#14678]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
httpclient 
windows 10/ubuntu22
last jackett
```

### Description

Hello, I have my own small application and when working with certain sites (kinozal) an error comes out.
Here's what the console outputs : 

```text
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder.get_Uri()
   at System.Net.Http.HttpAuthority..ctor(String host, Int32 port)
   at System.Net.Http.HttpConnectionPool..ctor(HttpConnectionPoolManager poolManager, HttpConnectionKind kind, String host, Int32 port, String sslHostName, Uri proxyUri)
   at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(HttpRequestMessage request, Uri proxyUri, Boolean async, Boolean doRequestAuth, Boolean isProxyConnect, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at searchOfTorrents_bot.BotTelegram.BotTelegram.Update(ITelegramBotClient botClient, Update update, CancellationToken token) in C:\Users\ignat\source\repos\searchOfTorrents_bot\searchOfTorrents_bot\BotTelegram\BotTelegram.cs:line 518 .
```

Here is the part of my code where the error occurs :

```text
  using var httpClient = new HttpClient();
                            var response = await httpClient.GetAsync(DictionaryResultId[chatiDs][numberOne]._urlTorrentDown);
                            response.EnsureSuccessStatusCode();
                            Stream stream = await response.Content.ReadAsStreamAsync();

                            InputFile torrents = new InputFile(stream, DictionaryResultId[chatiDs][numberOne]._title + ".torrent"); 
```

I will attach a screenshot of which sites Jackket works with without problems .In the browser , these links with kinozal opens without problems . Checked both on Linix/ubuntu and on windows10 .I tried to find a legal basis , but I never found it .I hope for help
There are no errors in the log , it shows that all requests are processed as usual !
![Сникукуууккккккмок](https://github.com/Jackett/Jackett/assets/119799988/a54dd830-3953-4e13-89e3-60eec308b0fb)

### Logged Error Messages

```text
Authorization was successful.
```

**Comment by ilike2burnthing** [comment]
We're not going to debug your Telegram bot, but I can point you in the direction of some relevant troubleshooting steps - https://github.com/Jackett/Jackett/wiki/Troubleshooting#a-connection-attempt-failed

**Comment by sergeiwork** [comment]
Error happens when url returns redirect to magnet:. HttpClient fails to get connection from pool because it assumes that it works with http and tries to get host from redirect location header. Obviously magnet does not have host part and that's why it fails.
