### ISSUE TITLE
[finvip] (updating) Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by ronilaukkarinen** [Jackett/Jackett#14675]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using FlareSolverr: Disabled
Using proxy: Disabled
App config/log/directory: ~/.apps/jackett/Jackett
Running in Docker: Yes
Jackett Version v0.21.733
```

### Description

After changed password trying to update the login, getting this error.

### Logged Error Messages

```text
2023-09-03 09:51:33.6004 Error Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match

[v0.21.733.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/1534150/08607a0f-5faf-4aff-9260-90befbd6f98e)

**Comment by ronilaukkarinen** [comment]
Never mind, the password was somehow wrong. But it still shouldn't give this kind of error.

**Comment by garfield69** [comment]
I agree. The indexer does have an error message section in the login, so it should be able to detect an incorrect password message, rather than fall back to the catch all if checking the indexer page for the presence of the logout link.
I will take a look and see if there is anything that needs updating.

**Comment by garfield69** [comment]
I cannot replicate this issue. If I edit the config and enter an incorrect password I get the invalid password error message.
Do you recall the timing of events that caused this issue for you?

**Comment by ronilaukkarinen** [comment]
> I cannot replicate this issue. If I edit the config and enter an incorrect password I get the invalid password error message. Do you recall the timing of events that caused this issue for you?

I had it added with the wrong password already, then I tried to change it. So it was already added earlier. If I add it "as new" in fresh install, this problem doesn't occur. Only when changing the password.

I guess this only can be replicated with the actual account logged in, then after changing the actual password in the tracker...

**Comment by garfield69** [comment]
Cant improve the indexer. The catch all is there to handle any response that the web site returns that is outside of the login failed event.
