### ISSUE TITLE
[beyond-hd-api] (testing) Exception (beyond-hd-api): Value cannot be null. (Parameter 'uriString'): Value cannot be null. (Parameter 'uriString')

### ISSUE THREAD

**Issue by rlaphoenix** [Jackett/Jackett#14683]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
Environment version: 6.0.21 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.756
```

### Description

1. Add Indexer "Beyond-HD (API)"
2. Add API Key listed in https://beyond-hd.me/settings/change_api
3. Add RSS Key listed in https://beyond-hd.me/settings/change_rid
4. Leave everything default, or set some settings, it doesn't matter.
5. Hit save and click Test. It will fail.

This has been happening for me for about a week now. Maybe a bit longer.

### Logged Error Messages

Error location: https://github.com/Jackett/Jackett/blob/c877ced77a369c63258cb077a756e3ca52aab7af/src/Jackett.Common/Indexers/BeyondHDAPI.cs#L172

```text
Jackett.Common.IndexerException: Exception (beyond-hd-api): Value cannot be null. (Parameter 'uriString')

[v0.21.756.0] Jackett.Common.IndexerException: Exception (beyond-hd-api): Value cannot be null. (Parameter 'uriString')
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.Uri..ctor(String uriString)
   at Jackett.Common.Indexers.BeyondHDAPI.mapToReleaseInfo(BHDResult bhdResult) in ./Jackett.Common/Indexers/BeyondHDAPI.cs:line 172
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 315
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/17136956/e00fbaa4-d1ff-4792-b698-87b867ab74ca)

**Comment by rlaphoenix** [comment]
Possible fix (untested):

```cs
private ReleaseInfo mapToReleaseInfo(BHDResult bhdResult)
        {
-            var downloadUri = new Uri(bhdResult.download_url);
-
            var title = getTitle(bhdResult);

            var releaseInfo = new ReleaseInfo
            {
                Title = title,
                Seeders = bhdResult.seeders,
                Guid = new Uri(bhdResult.url),
                Details = new Uri(bhdResult.url),
                Link = downloadUri,
                InfoHash = bhdResult.info_hash,
                Peers = bhdResult.leechers + bhdResult.seeders,
                Grabs = bhdResult.times_completed,
                PublishDate = bhdResult.created_at,
                Size = bhdResult.size,
                Category = MapTrackerCatToNewznab(bhdResult.category)
            };

            if (!string.IsNullOrEmpty(bhdResult.imdb_id))
                releaseInfo.Imdb = ParseUtil.GetImdbId(bhdResult.imdb_id);

+            if (!string.IsNullOrEmpty(bhdResult.download_url))
+                releaseInfo.Link = new Uri(bhdResult.download_url);
```

**Comment by garfield69** [comment]
None of the team have an account for this indexer so we cannot test, which is why the problem has been likely outstanding for a while.
If the download_url is empty, then this could be caused by two things:
1. the API download_url has had a name change (unlikely)
2. the field is genuinely empty for this torrent (which could mean the the torrent has not been approved yet, or has been blocked by admin because it was not valid or did not meet the sites criteria, whatever)

The point being, that if the torrent does not have a link, then there is no point presenting that torrent in the results, since the download link is the primary reason for the torrent existence.
I will update the indexer to just skip the torrent when the download link is not available, this is the usual method for all the other indexers.

**Comment by rlaphoenix** [comment]
Is there a way I can see info about the bhd_result, as curiously this is not happening to anyone else on BHD when I brought it up. Therefore, maybe its something specific under my account, which may or many not need to be brought up with BHD staff.

**Comment by garfield69** [comment]
Turn in the jackett  enhanced logging and see if that yields more data in the logs. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-turn-on-enhanced-logging

**Comment by rlaphoenix** [comment]
Enhanced logging didn't make a difference. I made a direct request for a search term "test", this is the first result. As you can see there's no "download_url".

```json
{
  "id": redacted,
  "name": "redacted",
  "folder_name": "/",
  "info_hash": "redacted",
  "size": 3369758139,
  "category": "TV",
  "type": "1080p",
  "dv": 0,
  "hdr10": 0,
  "hdr10+": 0,
  "hlg": 0,
  "commentary": 0,
  "seeders": 12,
  "leechers": 0,
  "times_completed": 38,
  "imdb_id": "tt1433870",
  "tmdb_id": "tv/16395",
  "bhd_rating": 7.13,
  "tmdb_rating": 7.2,
  "imdb_rating": 8.2,
  "internal": 0,
  "tv_pack": 0,
  "promo25": 0,
  "promo50": 0,
  "promo75": 0,
  "freeleech": 0,
  "rewind": 0,
  "refund": 0,
  "limited": 0,
  "rescue": 0,
  "bumped_at": "2023-07-01 15:15:36",
  "created_at": "2023-07-01 15:15:36",
  "url": "https://beyond-hd.me/torrents/redacted.redacted"
}
```

**Comment by rlaphoenix** [comment]
You're not gonna believe this one... I had the first character of my RSS key missing  🤣

If invalid, BHD's API does not give any error or indication about that. It's also required if you want download_url. Therefore, just add an error message if download_url is missing, and state that RSS key may be invalid.

**Comment by garfield69** [comment]
have you logged on the site, and done a brose torrents there, and checked if the torrents have a download either on the browse page, or in the details page of the torrent? 
Perhaps you have lost your right to download? IS your ratio good, no H&R outstanding?

**Comment by garfield69** [comment]
Oh ;-)
that is the length of the RSS key? I can add a length check to trap short/longs one, to add a little more proofing.
Same for the API key, what's the length?

**Comment by rlaphoenix** [comment]
> Oh ;-) that is the length of the RSS key? I can add a length check to trap short/longs one, to add a little more proofing. Same for the API key, what's the length?

The exact format is `[a-z0-9]{32}`

**Comment by garfield69** [comment]
for both?

**Comment by rlaphoenix** [comment]
> for both?

Correct

**Comment by garfield69** [comment]
cool. I'll update the indexer and close.

**Comment by garfield69** [comment]
v0.21.763
