### ISSUE TITLE
[amigosshare] (testing) Test search in Amigos Share Club => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by ricardolange** [Jackett/Jackett#14684]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Date	Level	Message
2023-09-09 22:49:08	Error	
System.Exception: Test search in Amigos Share Club => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.21.756.0] System.Exception: Test search in Amigos Share Club => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 327
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2023-09-09 22:49:08	Info	
Test search in Amigos Share Club => Found 0 releases [12548ms]
2023-09-09 22:46:47	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match

[v0.21.756.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2023-09-09 22:46:42	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match

[v0.21.756.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2023-09-09 22:44:07	Info	
Manual search in Amigos Share Club for flash => Found 0 releases [11083ms]
2023-09-09 22:43:28	Error	
System.Exception: Test search in Amigos Share Club => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.21.756.0] System.Exception: Test search in Amigos Share Club => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 327
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2023-09-09 22:43:28	Info	
Test search in Amigos Share Club => Found 0 releases [12504ms]
2023-09-09 22:43:07	Info	
Torznab search in Amigos Share Club => Found 0 releases [12758ms]
2023-09-09 22:42:54	Warn	
Some of the categories provided are unsupported in Amigos Share Club: 2010,2020,2030,2040,2045,2050,2060
2023-09-09 22:42:44	Info	
Jackett startup finished in 1352.034 s
2023-09-09 22:42:44	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2023-09-09 22:42:44	Info	
Adding filter indexer ('type:private' indexer) ...
2023-09-09 22:42:44	Info	
Adding filter indexer ('type:public' indexer) ...
2023-09-09 22:42:44	Info	
Adding aggregate indexer ('all' indexer) ...
2023-09-09 22:42:44	Info	
Loaded 594 indexers in total
2023-09-09 22:42:44	Info	
Loaded 522 Cardigann indexers.
2023-09-09 22:42:41	Info	
Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
2023-09-09 22:42:41	Info	
Loaded 72 Native indexers.
2023-09-09 22:42:41	Info	
Loading Native indexers ...
2023-09-09 22:42:41	Info	
Using HTTP Client: HttpWebClient2
2023-09-09 22:42:41	Info	
Using FlareSolverr: No
2023-09-09 22:42:41	Info	
Using proxy: Disabled
2023-09-09 22:42:41	Info	
App config/log directory: /config/Jackett
2023-09-09 22:42:41	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-09-09 22:42:41	Info	
Running in Docker: Yes (image build: v0.21.756-ls155)
2023-09-09 22:42:41	Info	
File /etc/issue: Welcome to Alpine Linux 3.18
2023-09-09 22:42:41	Info	
Jackett variant: CoreLinuxMuslAmdx64
2023-09-09 22:42:41	Info	
OS version: Unix 5.15.0.83 (64bit OS) (64bit process)
2023-09-09 22:42:41	Info	
Environment version: 6.0.21 (/app/Jackett/)
2023-09-09 22:42:41	Info	
Jackett stopped
2023-09-09 22:42:41	Info	
Restart of the web application host (not process) initiated
2023-09-09 22:42:41	Info	
Restarting webhost due to configuration change
2023-09-09 22:42:40	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2023-09-09 22:42:40	Info	
Adding filter indexer ('type:private' indexer) ...
2023-09-09 22:42:40	Info	
Adding filter indexer ('type:public' indexer) ...
2023-09-09 22:42:40	Info	
Adding aggregate indexer ('all' indexer) ...
2023-09-09 22:42:13	Info	
Torznab search in Amigos Share Club => Found 0 releases (from cache) [2ms]
2023-09-09 22:42:13	Warn	
Some of the categories provided are unsupported in Amigos Share Club: 2010,2020,2030,2040,2045,2050,2060
2023-09-09 22:41:51	Info	
Torznab search in Amigos Share Club => Found 0 releases (from cache) [7ms]
2023-09-09 22:41:51	Warn	
Some of the categories provided are unsupported in Amigos Share Club: 2010,2020,2030,2040,2045,2050,2060
2023-09-09 22:41:46	Info	
Torznab search in Amigos Share Club => Found 0 releases [13203ms]
2023-09-09 22:41:33	Warn	
Some of the categories provided are unsupported in Amigos Share Club: 2010,2020,2030,2040,2045,2050,2060
2023-09-09 22:20:22	Info	
Jackett startup finished in 9.430 s
2023-09-09 22:20:22	Warn	
No XML encryptor configured. Key {22c4b54e-bfe5-47cd-82c5-18f879dc1600} may be persisted to storage in unencrypted form.
2023-09-09 22:20:21	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2023-09-09 22:20:21	Info	
Adding filter indexer ('type:private' indexer) ...
2023-09-09 22:20:21	Info	
Adding filter indexer ('type:public' indexer) ...
2023-09-09 22:20:21	Info	
Adding aggregate indexer ('all' indexer) ...
2023-09-09 22:20:21	Info	
Loaded 594 indexers in total
2023-09-09 22:20:21	Info	
Loaded 522 Cardigann indexers.
2023-09-09 22:20:15	Info	
Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
2023-09-09 22:20:15	Info	
Loaded 72 Native indexers.
2023-09-09 22:20:15	Info	
Loading Native indexers ...
2023-09-09 22:20:15	Info	
Using HTTP Client: HttpWebClient2
2023-09-09 22:20:15	Info	
Using FlareSolverr: No
2023-09-09 22:20:15	Info	
Using proxy: Disabled
2023-09-09 22:20:15	Info	
App config/log directory: /config/Jackett
2023-09-09 22:20:15	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-09-09 22:20:15	Info	
Running in Docker: Yes (image build: v0.21.756-ls155)
2023-09-09 22:20:15	Info	
File /etc/issue: Welcome to Alpine Linux 3.18
2023-09-09 22:20:15	Info	
Jackett variant: CoreLinuxMuslAmdx64
2023-09-09 22:20:15	Info	
OS version: Unix 5.15.0.83 (64bit OS) (64bit process)
2023-09-09 22:20:15	Info	
Environment version: 6.0.21 (/app/Jackett/)
2023-09-09 22:20:13	Info	
Starting Jackett v0.21.756
```

### Description

Using CasaOS. Tried both with Jackett and Prowlarr and got the same error, as shown on title
I have a login as password for this tracker. I am an active user. 

### Logged Error Messages

```text
Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```

### Screenshots

![CleanShot 2023-09-09 at 22 55 18](https://github.com/Jackett/Jackett/assets/144572140/5c527b64-5c24-4165-9203-807a0ad5c72f)

**Comment by ilike2burnthing** [comment]
Have you followed the indexer instruction?

> Set **Exibição De Torrents** to **Lista** in your **Minhas Configurações**.
Using **Capas** is not supported and will return 0 results.

If so, and you're not filtering by freeleech only, then provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
I've tested Filtering freeleech with the ASC indexer and it returns results, so we can eliminate that possibility.

**Comment by ricardolange** [comment]
I'm sorry. Change to list worked. Maybe put that info clearer somehow would help. 
But thank you and congrats for the awesome work so far. 
Thanks !

**Comment by garfield69** [comment]
>Maybe put that info clearer somehow would help.

really?
![image](https://github.com/Jackett/Jackett/assets/6933240/8066e871-1c0c-4d0e-b93b-48aef2d063ab)
What else do we need to add, flashing lights and audio warnings?

**Comment by ilike2burnthing** [comment]
It's in the centre of the indexer config panel, in a blue highlighted box, with the key words in bold; I don't know how much clearer we could make it.
