### ISSUE TITLE
[filelist] (updating) Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.

### ISSUE THREAD

**Issue by psmerica** [Jackett/Jackett#14701]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-09-18 10:06:37	Info	Using HTTP Client: HttpWebClient2
2023-09-18 10:06:37	Info	Using FlareSolverr: No
2023-09-18 10:06:37	Info	Using proxy: Disabled
2023-09-18 10:06:37	Info	App config/log directory: /config/Jackett
2023-09-18 10:06:37	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-09-18 10:06:37	Info	Running in Docker: Yes (image build: v0.21.812-ls164)
2023-09-18 10:06:37	Info	File /etc/issue: Welcome to Alpine Linux 3.18
2023-09-18 10:06:37	Info	Jackett variant: CoreLinuxMuslAmdx64
2023-09-18 10:06:37	Info	OS version: Unix 6.1.49.0 (64bit OS) (64bit process)
2023-09-18 10:06:37	Info	Environment version: 6.0.22 (/app/Jackett/)
2023-09-18 10:06:37	Info	Starting Jackett v0.21.826
```

### Description

While setting up and adding the FileList tracker. After inputting username and password you are presented with the following errors.

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.

[v0.21.826.0] Jackett.Common.ExceptionWithConfigData: Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.
   at Jackett.Common.Indexers.FileList.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/FileList.cs:line 129
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
If you're using your password, you haven't read the config info correctly.

If you're using your passkey, and the above was just a typo, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
v0.21.841
