### ISSUE TITLE
[btdigg] (testing) Exception (btdigg): Operation canceled: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### ISSUE THREAD

**Issue by subexx** [Jackett/Jackett#14706]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.860-ls167)
File /etc/issue: Welcome to Alpine Linux 3.18
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 6.0.22 (/app/Jackett/)
Starting Jackett v0.21.860
```

### Description

BTDigg stopped working. Now its giving error. I can access the website from web browser without any issue.

### Logged Error Messages

```text
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
09-21 16:07:44 Info Starting Jackett v0.21.860
09-21 16:07:46 Info Environment version: 6.0.22 (/app/Jackett/)
09-21 16:07:46 Info OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
09-21 16:07:46 Info Jackett variant: CoreLinuxMuslAmdx64
09-21 16:07:46 Info File /etc/issue: Welcome to Alpine Linux 3.18
09-21 16:07:46 Info Running in Docker: Yes (image build: v0.21.860-ls167)
09-21 16:07:46 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
09-21 16:07:46 Info App config/log directory: /config/Jackett
09-21 16:07:46 Info Using proxy: Disabled
09-21 16:07:46 Info Using FlareSolverr: No
09-21 16:07:46 Info Using HTTP Client: HttpWebClient2
09-21 16:07:46 Info Loading Native indexers ...
09-21 16:07:46 Info Loaded 72 Native indexers.
09-21 16:07:46 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
09-21 16:07:52 Info Loaded 518 Cardigann indexers.
09-21 16:07:52 Info Loaded 590 indexers in total
09-21 16:07:52 Info Adding aggregate indexer ('all' indexer) ...
09-21 16:07:52 Info Adding filter indexer ('type:public' indexer) ...
09-21 16:07:52 Info Adding filter indexer ('type:private' indexer) ...
09-21 16:07:52 Info Adding filter indexer ('type:semi-public' indexer) ...
09-21 16:07:53 Info Jackett startup finished in 10.358 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
[ls.io-init] done.
09-21 16:12:03 Error Jackett.Common.IndexerException: Exception (btdigg): Operation canceled
[v0.21.860.0] Jackett.Common.IndexerException: Exception (btdigg): Operation canceled
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
Try accessing the docker image via your terminal and doing a curl and openssl from within the image 
```
docker exec -it jackett /bin/bash
```
and see what you get from the following:
```
openssl s_client -connect btdig.com:443
```
if it fails to connect then you know its not a Jackett issue but a docker connection issue.

Are any of the other public indexer working?

Sometimes simply shutting down your docker image and starting it up afresh can clear the issue.

Otherwise, you may find this helpful: https://github.com/Jackett/Jackett/wiki/TroubleShooting/#a-task-was-cancelled

**Comment by subexx** [comment]
The command you gave me doesn't work in the container. I have tried the tropubleshooting tips. But didn't work.
Tried reboot, resinatall, complete new install, installed on a. diffrenet server as well. all giving the same error. Other public indexers are working fine.

root@Subin_NAS:~# docker exec -it jackett /bin/bash
root@5d556a57b298:/# openssl s_client -connect btdig.com:443
bash: openssl: command not found
root@5d556a57b298:/#

**Comment by garfield69** [comment]
Bugger. Sorry about that. The notes I have for docker were written back when docker images were linux ubuntu, but at some point they switched to using Alpine Linux which does not come with openssl bundled.
so please do the following:
Try accessing the docker image via your terminal and doing a openssl from within the image 
```
docker exec -it jackett /bin/bash
```
then install openssl
```
apk add openssl
```
and now see what you get from the following:
```
openssl s_client -connect btdig.com:443
```
Thanks.

**Comment by subexx** [comment]
`root@5d556a57b298:/# openssl s_client -connect btdig.com:443
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = btdig.com
verify return:1
---
Certificate chain
 0 s:CN = btdig.com
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  7 01:04:49 2023 GMT; NotAfter: Dec  6 01:04:48 2023 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 19:14:03 2021 GMT; NotAfter: Sep 30 18:14:03 2024 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIE/DCCA+SgAwIBAgISAzUKS82t7sYxXRhEckWNo0DdMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzA5MDcwMTA0NDlaFw0yMzEyMDYwMTA0NDhaMBQxEjAQBgNVBAMT
CWJ0ZGlnLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ8OAlEC
KBglhMGKrzIzkcTXFw/HCYdMIJ32bOK8zTrrvnQMXf5kFcBDZoI3DM+MiM0iFcwA
hA0JRmSEqY4puHm6atHiveb2ZVbKm4Bmo4j8lyvt24aJ0sVm/ibORss8CsqkwJ7t
Hp9TBB5dkXDG2k5x2E9z426HP40Svh9gcMYCt4VLaXQCn5ITLFyMIUIYJ8HusI2l
mWGL22x4V35j74SWaeKRdscgfW7sD1SVNLoU9Nr9KnMq5lY4q8Ku4bBDAQkoy9gF
0Soa26/0J/2XqDJNx3vTTiiBvsLWG106jM28tUq4BDym40nNl75YNQQZqFRQKRFP
viDm71wRsJd8Y6MCAwEAAaOCAigwggIkMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUE
FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU
hQx+awuDNBFhK2WyklEhgR/+9WEwHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+v
nYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5s
ZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wMQYD
VR0RBCowKIIJYnRkaWcuY29tggxlbi5idGRpZy5jb22CDXd3dy5idGRpZy5jb20w
EwYDVR0gBAwwCjAIBgZngQwBAgEwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdgC3
Pvsk35xNunXyOcW6WPRsXfxCz3qfNcSeHQmBJe20mQAAAYptYoykAAAEAwBHMEUC
IEXWwOcJZ51fHxGkRz3pnF7+lgc9z4KP4/HvbAaA2YPSAiEA6/wftmN8HfBserCH
k9Pdjze0cnqAcK9TJPD/7zBQJIkAdgDoPtDaPvUGNTLnVyi8iWvJA9PL0RFr7Otp
4Xd9bQa9bgAAAYptYoyTAAAEAwBHMEUCIEgxkQNU3I3FS8L4ry6vULo+L9doQ/5K
vt/YWZ3s1WOIAiEA5gegSuPpIktTi6FewbPEbS9zpVBe9uxmpqoGSGH6ibMwDQYJ
KoZIhvcNAQELBQADggEBAHp0fm3vtUaK6an5LJY0ndYoAufoDDs/rCsIO6pubH0v
DsSGfhkTofiGhRVVWN0vrfjoBKYsGeBMKRgp0C+Nh9YsOsjVKnvI92Tx+gSaUgXD
PuL78BOzMuEGNpoaEb8B5CnImamffgEQBWa8tfGxsi4bA/fgMAymRht21SyANQ9Z
M5fXOwF+SyLFandX3IAfBvcg+D/MjKx/SDzxqe4HBVCpbk/S14mwzlcWid4h9kCG
zxPBYCpRNlDRzUuGLy7RVEtachRlLLcC82S63RxwB9MsDW/trMCitR9MrGk0ZHFi
B6BGIuhjKtjtzGGuRI7O30Z0tWBcSklgKJTw5yZ2yGQ=
-----END CERTIFICATE-----
subject=CN = btdig.com
issuer=C = US, O = Let's Encrypt, CN = R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4454 bytes and written 404 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 34E88D71801E26E4D36D63B25C0725A0BE8A8424D1674656EE841E454C8BA457
    Session-ID-ctx: 
    Master-Key: 6EFC5D2CB5698CFE0618ECEAEF2653FA337391F9093AD7D82FF14B284B838E053CDD345DBB7C6D30BA125C710ED28D3F
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1695356530
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
closed
root@5d556a57b298:/# 
`

**Comment by garfield69** [comment]
well, that is the correct CA from the btdigg website, so it appears  you are connecting to the site and establishing a session.

what do you get if you use curl instead of openssl
```
curl -vvv https://btdig.com/
```
Thanks.

**Comment by subexx** [comment]
```
root@5d556a57b298:/# curl -vvv https://btdig.com/
* processing: https://btdig.com/
*   Trying 193.233.203.196:443...
* Connected to btdig.com (193.233.203.196) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=btdig.com
*  start date: Sep  7 01:04:49 2023 GMT
*  expire date: Dec  6 01:04:48 2023 GMT
*  subjectAltName: host "btdig.com" matched cert's "btdig.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: btdig.com]
* h2 [:path: /]
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* Using Stream ID: 1
> GET / HTTP/2
> Host: btdig.com
> User-Agent: curl/8.2.1
> Accept: */*
> 

```

**Comment by garfield69** [comment]
Interesting. 
so my win10 Jackett has no trouble getting a TEST result from the btdigg indexer.

So I started docker desktop on my win10 and installed the latest Jackett docker image and repeated my test and I can replicate your timeout.

So I then started my win10 virtualbox and fired up my Ubuntu21 image, and tested that indexer on the Jackett from there and once again got the timeout.

So it appears that the web site is blocking Jackett from linux platforms.

@ilike2burnthing  what do you think about these results? Any ideas?

**Comment by ilike2burnthing** [comment]
Looks like it's the opposite of https://github.com/Jackett/Jackett/issues/14198#issuecomment-1491806580, where Jackett on Windows didn't work. I wasn't able to resolve it by changing the UA then, and testing now has the same result. No idea what they're using to distinguish Windows from Linux requests.

**Comment by garfield69** [comment]
Oh yeah, I forgot about that windows only block from a while ago.
Well, to my mind, it is clear that the site does not want Jackett traffic, so I think we should seriously just remove the indexer.

**Comment by garfield69** [comment]
Closing this ticket,  #4907 will be used to remove the indexer.
