### ISSUE TITLE
[torrentbytes] (updating) The SSL connection could not be established, see inner exception.: Authentication failed, see inner exception.

### ISSUE THREAD

**Issue by g00p99** [Jackett/Jackett#14704]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/hd25/jme23/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 22.04.1 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.0.69 (64bit OS) (64bit process)
Environment version: 6.0.22 (/home/hd25/jme23/apps/jackett-dotnet/)
Starting Jackett v0.21.841
```

### Description

Attempted to add TorrentBytes (TBy) indexer, and was unsuccessful - received the below error message.

### Logged Error Messages

```text
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

[v0.21.841.0] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A00018A:SSL routines::dh key too small
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.TorrentBytes.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/TorrentBytes.cs:line 113
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
See what you get from the following:
```
openssl s_client -connect www.torrentbytes.net:443
```
and
```
curl -vvv https://www.torrentbytes.net/
```

**Comment by g00p99** [comment]
> See what you get from the following:
> 
> ```
> openssl s_client -connect www.torrentbytes.net:443
> ```

Got the following:
```
$ openssl s_client -connect www.torrentbytes.net:443
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = torrentbytes.net
verify return:1
80EB684CC37F0000:error:0A00018A:SSL routines:tls_process_ske_dhe:dh key too small:../ssl/statem/statem_clnt.c:2086:
---
Certificate chain
 0 s:CN = torrentbytes.net
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jul  2 16:19:35 2023 GMT; NotAfter: Sep 30 16:19:34 2023 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
 2 s:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 19:14:03 2021 GMT; NotAfter: Sep 30 18:14:03 2024 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFATCCA+mgAwIBAgISAxrJZzJfZot0c6vCHsIzbUdCMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yMzA3MDIxNjE5MzVaFw0yMzA5MzAxNjE5MzRaMBsxGTAXBgNVBAMT
EHRvcnJlbnRieXRlcy5uZXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDV4bXsQF+eMZbKTIn9y1n0YgyDVo+mcSB0/wSQvvdysWGfnFXCEWXpYBn3WyaU
zXxMFjtknSvfIIftm7EXjGce4NoXXOZ3kcIO4nJWcLguoHMm+W1XpNwmAKbgdt/z
KZNy6KLMIItkmO53EzTD9+fdPhfsHw62BrZ6rq5GZg9OjgFRhJuJk+7ugbwNgyYz
PJ+tGaXlsILTjDzTdcCw9pgmDj6Dy6JV7BT9l2wH8zp3dQRWaZjTR6Mk7NKbUTLe
KboYIvl9jhAmuJBQvu4C6CM32bUe8DHbp6CTgrzAoZF+3krur9cyJNxbG6pnAsw7
RaCM6kiBDi7vxTFrsUd6fznfAgMBAAGjggImMIICIjAOBgNVHQ8BAf8EBAMCBaAw
HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYD
VR0OBBYEFKaywE/9wGH6XwHMkcxEhxVWJxMJMB8GA1UdIwQYMBaAFBQusxe3WFbL
rlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDov
L3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5v
cmcvMDEGA1UdEQQqMCiCEHRvcnJlbnRieXRlcy5uZXSCFHd3dy50b3JyZW50Ynl0
ZXMubmV0MBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBAgYKKwYBBAHWeQIEAgSB8wSB
8ADuAHUAejKMVNi3LbYg6jjgUh7phBZwMhOFTTvSK8E6V6NS61IAAAGJF533lQAA
BAMARjBEAiAaY+BDRh/2JyTXbk7H1SkqgjYa0aNf+CqS0O36fSBOsAIgdaAecDBc
6St8x1V+V2utKR27pd2SVrH+9ZGm2NXggPEAdQDoPtDaPvUGNTLnVyi8iWvJA9PL
0RFr7Otp4Xd9bQa9bgAAAYkXnfeIAAAEAwBGMEQCIGPbYxFr9o4H9ty+pqNfho0K
WyvcUAzgz7nxbIZVjtWkAiAhYRkwfN8p89UOoM1Izg1EDQV1wZ/ZyD6ztaQWg97r
qDANBgkqhkiG9w0BAQsFAAOCAQEAQKtgt2YzaOj0I8MlHqZnnv6SQDilBImEzqd9
kbpmv6I6o634FnNHFZGO1K5yiOu6NXU9wxNnPbv1ukC/jLFygulUDKaygNb5zI8b
oM32oj453pUMqGBYlR8dqqgtQUPZfg26yGPHmgSLkUTaQ+7YcCKIfm/+Eo4FyJCr
1rfzrnKXunZlpbCsBElo+T0oOhv7c7T368xOPamGbW0SkxzRGBXJi5YPwyXToDME
bqDv2bVgFw4t4GMz+/omC/0xpke6ttrjNmJY/nG1qNPVyadCcQxsEr7THYx/ay+O
nVp23VisO4fup32wYy+3g7EZq3SPRFg5v7cH2YhF5dVG/Z+r7Q==
-----END CERTIFICATE-----
subject=CN = torrentbytes.net
issuer=C = US, O = Let's Encrypt, CN = R3
---
No client certificate CA names sent
---
SSL handshake has read 4586 bytes and written 329 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1695176009
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
```

> and
> 
> ```
> curl -vvv https://www.torrentbytes.net/
> ```

Got the following:
```
$ curl -vvv https://www.torrentbytes.net/
*   Trying 88.80.28.24:443...
* Connected to www.torrentbytes.net (88.80.28.24) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:0A00018A:SSL routines::dh key too small
* Closing connection 0
curl: (35) error:0A00018A:SSL routines::dh key too small
```

**Comment by garfield69** [comment]
OK, so the open_ssl app confirms that you are being presented with the correct CA from torrentbytes (TB).
And both your open_ssl and curl apps are failing with the same error `error:0A00018A:SSL routines::dh key too small` so this shows the problem is not with Jackett, or with your access being blocked by your ISP or security apps.

I don't have an account on TB but for a test I can set up the TB indexer config on my Jackett with dummy credentials and test that I get a `user not found` message instead of an `SSL error` to prove that I could login if I had an account.

So on my Windows10 Jackett I can access the sites' login page without getting this CA error, so this would suggest a platform issue with your Ubuntu22 negotiating TLSv1.2

Interestingly, if I use my win10 VirtualBox image of Ubuntu21, the Jackett on that platform fails with the CA error you presented which supports my platform issue theory.

I then started my win10 Docker Desktop and tried the latest Docker Jackett to access TB and I was able to access that sites login page and get a `user not found` message, so a possible solve for your issue is to switch to using the Docker build of Jackett from the LinuxServer.io team at https://hub.docker.com/r/linuxserver/jackett/

@ilike2burnthing  you are more familiar with the linux platforms than I, do you have any suggestions for resolving this SSL error on Native Ubuntu?
Or is Docker the only way forward for the OP ATM?

**Comment by ilike2burnthing** [comment]
https://updown.uservoice.com/knowledgebase/articles/1989814-what-does-the-dh-key-too-small-ssl-error-means

Contact the site admins to get them to improve their security, or use an older version of openssl, or switch to Docker.

**Comment by g00p99** [comment]
OK, thanks for the info.
