### ISSUE TITLE
[tjupt] (testing) Exception (tjupt): Login failed: Selector "a[href="logout.php"]" didn't match: Parse error

### ISSUE THREAD

**Issue by issaccv** [Jackett/Jackett#14736]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
10-03 03:07:25 Info Starting Jackett v0.21.947
10-03 03:07:26 Info Environment version: 6.0.22 (/app/Jackett/)
10-03 03:07:26 Info OS version: Unix 6.1.49.0 (64bit OS) (64bit process)
10-03 03:07:26 Info Jackett variant: CoreLinuxMuslAmdx64
10-03 03:07:26 Info File /etc/issue: Welcome to Alpine Linux 3.18
10-03 03:07:26 Info Running in Docker: Yes (image build: v0.21.947-ls178)
10-03 03:07:26 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
10-03 03:07:26 Info App config/log directory: /config/Jackett
10-03 03:07:26 Info Using proxy: Disabled
10-03 03:07:26 Info Using FlareSolverr: http://flare:8191
10-03 03:07:26 Info Using HTTP Client: HttpWebClient2
10-03 03:07:26 Info Loading Native indexers ...
10-03 03:07:26 Info Loaded 74 Native indexers.
10-03 03:07:26 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
10-03 03:07:29 Info Loaded 520 Cardigann indexers.
10-03 03:07:29 Info Loaded 594 indexers in total
10-03 03:07:29 Info Adding aggregate indexer ('all' indexer) ...
10-03 03:07:29 Info Adding filter indexer ('type:public' indexer) ...
10-03 03:07:29 Info Adding filter indexer ('type:private' indexer) ...
10-03 03:07:29 Info Adding filter indexer ('type:semi-public' indexer) ...
10-03 03:07:29 Info Jackett startup finished in 4.731 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
```

### Description

Just try to relogin TJUPT.

I have checked old issues, and I found #13988 which has same error info. But the difference is this time TJUPT's logout buttom is not disabled. By the way, the site has restore the normal login method, I guess cookie is no longer required(which expired in 3 months).

### Logged Error Messages

```text
10-03 23:27:13 Error Jackett.Common.IndexerException: Exception (tjupt): Login failed: Selector "a[href="logout.php"]" didn't match
[v0.21.947.0] Jackett.Common.IndexerException: Exception (tjupt): Login failed: Selector "a[href="logout.php"]" didn't match
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1722
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 732
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
I'll switch the indexer back to using the login method since that is working for me in testing just now.

**Comment by garfield69** [comment]
v0.21.958
