### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match: Parse error

### ISSUE THREAD

**Issue by hrxfab** [Jackett/Jackett#14753]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jacket docker version: Version v0.21.983
```

### Description

impossible to logon on Yggtorrent indexer, however indexer was working previously.

### Logged Error Messages

```text
An error occurred while testing this indexer
Exception (yggtorrent): Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match: Parse error

Detailed logs:

Jackett.Common.IndexerException: Exception (yggcookie): Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match

[v0.21.987.0] Jackett.Common.IndexerException: Exception (yggcookie): Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#top_panel:contains("Déconnexion")" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1722
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 732
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Working ok here. Follow these troubleshooting steps:
https://github.com/Jackett/Jackett/wiki/Troubleshooting/#login-failed-selector
https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work

Failing that, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by cmoi936** [comment]
Hi I've got the  same issue as @hrxfab.
I've also check all troubleshooting steps, it seems ok for me : 
 - refresh cookie and user-agent's values
 - DNS on my router is set to 1.1.1.1 (CloudFlare)
 - I success to login on Opera and Chrome with another computer.
 
I think yggtorrent website may have change their login page, so that the indexer fails to login.

**Comment by ilike2burnthing** [comment]
Still working fine here.

If you're using yggcookie (seeing as you're talking about the cookie and UA), then the login page isn't accessed at any point (and no, they haven't changed the login page).

Provide an enhanced log of the issue.

**Comment by garfield69** [comment]
for contrast, both the yggtorrent and yggcookie indexer are working for me on win10 Jackett 0.21.1073

**Comment by cmoi936** [comment]
[log (1).txt](https://github.com/Jackett/Jackett/files/13065318/log.1.txt)

Here is the enhanced log, I've repladced sensitive values with "******"

For me both yggtorrent and yggcookie indexers are NOK.

**Comment by garfield69** [comment]
@cmoi936 
The log you provided shows that you used the yggtorrent indexer, but did not have the correct sitelink configured.
You were using `https://yggtorrent.wtf/` which, while it allows you to login, generates 404-not-found when the indexer tries to do a search with it.

The log also show you using the yggcookie indexer, with the correct sitelink, however your session cookie from whichever browser you copied it from, did not satisfy the yggtorrent web site and the yggcookie indexer was presented with a not-logged-in page.

This is a common failure for users using docker, the cookie from a browser on a machine that does not match the one the docker image contains, will usually fail the session cookie match test.


I suggest you try the yggtorrent indexer again. This at least shows that you were logged in correctly, its just that you were not using the correct domain to allow torrent searching.

So edit your yggtorrent indexer config and set the site link to ` https://www3.yggtorrent.wtf/` and I think you may have better success.

**Comment by cmoi936** [comment]
thx a lot @garfield69, after changing the sitelink with https://www3.yggtorrent.wtf/, it's working. 
I'll abandon yggtorrentCookie, to use only yggtorrent indexer.

Have a good day.

**Comment by GeekndGamer** [comment]
I've been encountering this error message for the past two days, even when using the URL https://www3.yggtorrent.wtf/. Are any of you facing the same problem? : 

An error occurred while updating this indexer
Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Connection refused (192.168.1.41:8191) ---> System.Net.Sockets.SocketException (111): Connection refused at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) --- End of inner exception stack trace --- at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.Diag
