### ISSUE TITLE
[hdbits] (updating) Cannot access child value on Newtonsoft.Json.Linq.JValue.

### ISSUE THREAD

**Issue by sarajev0** [Jackett/Jackett#14766]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-10-15 19:45:53	Info	Loading Native indexers ...
2023-10-15 19:45:53	Info	Using HTTP Client: HttpWebClient2
2023-10-15 19:45:53	Info	Using FlareSolverr: No
2023-10-15 19:45:53	Info	Using proxy: Disabled
2023-10-15 19:45:53	Info	App config/log directory: C:\ProgramData\Jackett
2023-10-15 19:45:53	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2023-10-15 19:45:53	Info	Running in Docker: No
2023-10-15 19:45:53	Info	Jackett variant: CoreWindows
2023-10-15 19:45:53	Info	OS version: Microsoft Windows NT 10.0.19042.0 (64bit OS)
2023-10-15 19:45:53	Info	Environment version: 6.0.23 (C:\ProgramData\Jackett\)
2023-10-15 19:45:47	Info	Starting Jackett v0.21.1018
```

### Description

Hello i cannot login...
can you fix it?

### Logged Error Messages

```text
System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.

[v0.21.1018.0] System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 704
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![Screenshot_15](https://github.com/Jackett/Jackett/assets/147999560/856cb0cd-6185-4c56-bec6-cc987f5bee35)

**Comment by ilike2burnthing** [comment]
The indexer `hdbits` was removed from Jackett in February (as the API version is available and working), and so shouldn't be available in your v0.21.1018 installation, so you may have a permissions issue with your installation folder.

Download the latest installer, reinstall over your current Jackett, and check the log once restarted; you should see a bunch of files removed and hdbits no longer available.

Failing that, you can go to `C:\ProgramData`, rename the `Jackett` folder to `Jackett.old`, run the installer again, once finished stop the Jackett service, copy across `ServerConfig.json` from the `.old` folder to the new `Jackett` folder, then create a new `Indexers` folder and copy across all the old indexer files, then restarting the Jackett service.

**Comment by garfield69** [comment]
The issue here is that 62aa75b7ad17a76f4dff40b1d83865ef4540d656 from #12120 was not implemented properly, because while the source was removed, the hdbits.yml delete from Jackettupdater was not added.
I too am seeing hdbits.yml in my Jackett definitions.
I will update jackettUpdater to remove hdbits.yml from the users library.

**Comment by garfield69** [comment]
@sarajev0  please use the hdbits (API) indexer, and note that you use the passkey NOT the password in the config for that indexer.

**Comment by garfield69** [comment]
v0.21.1025
