### ISSUE TITLE
[TorrentLeech] Exception in GetConfigurationForSetup. FlareSolver timing out

### ISSUE THREAD

**Issue by ImCheesecake** [Jackett/Jackett#14769]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.0.2:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
Running in Docker: Yes
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.15.0.78 (64bit OS) (64bit process)
Environment version: 6.0.23 (/app/Jackett/)
Starting Jackett v0.21.1025
```

### Description

TorrentLeech config doesn't open anymore. It worked a few days ago but now the logs says that `GetConfigurationForSetup` times out because of FlareSolver.
Other indexers works with the same config

### Logged Error Messages

```text
Exception in GetConfigurationForSetup (torrentleech): FlareSolverrSharp.Exceptions.FlareSolverrException: Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 535
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 966
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 943
```

**Comment by ilike2burnthing** [comment]
Add the public indexers iDope, TorrentQQ, and Torrent[CORE]; do you get the same error with these?

If so - https://github.com/FlareSolverr/FlareSolverr/wiki/Troubleshooting

If not - change to one of the TorrentLeech mirrors.

**Comment by ImCheesecake** [comment]
I don't get the same error, and the problem is that I can't even open the config on TorrentLeech to change the mirror. If I remove the IP for FlareSolverr it works, but then I can't save because of FlareSolverr config errors

**Comment by ilike2burnthing** [comment]
Are you waiting long enough for FlareSolverr to timeout before clicking anything else?

None of the mirrors are using Cloudflare DDoS protection for me, so FlareSolverr shouldn't be needed. However, if your IP is being flagged for some reason and is causing a Cloudflare challenge page for all mirrors, then remove the FlareSolverr API URL, apply server settings, click to configure TorrentLeech, change to one of the mirrors, open a second browser tab, open Jackett, re-enter the FlareSolverr API URL, apply server settings, return to the original tab with the TorrentLeech config panel open, click the Okay button.

**Comment by ImCheesecake** [comment]
That worked, I could re-add TL again now. Thanks for the help!
