### ISSUE TITLE
[orpheus] (updating) Invalid API Key configured: expected length: 118, got 116

### ISSUE THREAD

**Issue by felyduw** [Jackett/Jackett#14791]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /media/sdr1/migo/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 9 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 6.1.47.0 (64bit OS) (64bit process)
Environment version: 6.0.23 (/media/sdr1/migo/Jackett/)
Starting Jackett v0.21.1066
```

### Description

I've generated a brand new Orpheus token and after double checking that I've copied the token correctly, the error above remains. It's expecting a string length of 118 but the token only has 116 characters.

### Logged Error Messages

```text
System.Exception: Invalid API Key configured: expected length: 118, got 116

[v0.21.1066.0] System.Exception: Invalid API Key configured: expected length: 118, got 116
   at Jackett.Common.Indexers.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 93
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by felyduw** [comment]
Essentially I think line 26 of Jackett.Common/Indexers/Orpheus.cs should be
`protected override int ApiKeyLength => 116;`

**Comment by garfield69** [comment]
Complicated. My current token is 118 but my new token is 116.
The Orpheus indexer uses the GazelleTracker abstract which currently supports only the option to override the default token length.
If I simply change the Orpheus token length to 116, then users that currently have tokens of 118 will continue to work in Jackett as long as the user does not edit the Orpheus indexer config. If they do edit then they will not be able to save the config until they generate a new token with the new length of 116.

So we are going to have to change the GazelleTracker abstract to support multiple token lengths.

I'm thinking I could define ApiKeyLengthLegacy, which the GazelleTracker will default to have the same value as ApiKeyLength, but if overridden by the indexer would allow for tokens of an alternate length to be accepted.
Then I update Orpheus to have ApiKeyLengthLegacy=118 and ApiKeyLength=116.

**Comment by garfield69** [comment]
v0.21.1076
