### ISSUE TITLE
[linkomanija] (testing) Exception (linkomanija): The given key '.Config.order' was not present in the dictionary.: The given key '.Config.order' was not present in the dictionary.

### ISSUE THREAD

**Issue by podcastqq** [Jackett/Jackett#14800]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-10-28 10:08:20	Info	Using HTTP Client: HttpWebClient2
2023-10-28 10:08:20	Info	Using FlareSolverr: No
2023-10-28 10:08:20	Info	Using proxy: Disabled
2023-10-28 10:08:20	Info	App config/log directory: /home/martynas/.config/Jackett
2023-10-28 10:08:20	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-10-28 10:08:20	Info	Running in Docker: No
2023-10-28 10:08:20	Info	File /etc/issue: Ubuntu 20.04.6 LTS \n \l
2023-10-28 10:08:20	Info	Jackett variant: CoreLinuxAmdx64
2023-10-28 10:08:20	Info	OS version: Unix 5.15.0.79 (64bit OS) (64bit process)
2023-10-28 10:08:20	Info	Environment version: 6.0.24 (/home/martynas/Downloads/Jackett/)
2023-10-28 10:08:19	Info	Starting Jackett v0.21.1096
```

### Description

Since last update test on linkomanija tracker is failing. Seems line 107 in this commit is causing the issue: https://github.com/Jackett/Jackett/commit/40aeeff0c3f8266339bd3413ec65aa2510777283 

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (linkomanija): The given key '.Config.order' was not present in the dictionary.

[v0.21.1096.0] Jackett.Common.IndexerException: Exception (linkomanija): The given key '.Config.order' was not present in the dictionary.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '.Config.order' was not present in the dictionary.
   at Jackett.Common.Indexers.CardigannIndexer.applyGoTemplateText(String template, Dictionary`2 variables, TemplateTextModifier modifier) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 511
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query)
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 332
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 709
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
yes, this was discovered about 6 hours ago and fixed with 0bba697c89b32892105d1c435dfbca88c8f934c1
the fix will be published in the next Jackett release due out in about 13 hours or so.
