### ISSUE TITLE
[eztv] Exception (eztv): HTTP StatusCode not 200 or 500. Status is :NotFound: HTTP StatusCode not 200 or 500. Status is :NotFound

### ISSUE THREAD

**Issue by TheGates** [Jackett/Jackett#14801]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett startup finished in 12.000 s
Adding filter indexer ('type:semi-public' indexer) ...
Adding filter indexer ('type:private' indexer) ...
Adding filter indexer ('type:public' indexer) ...
Adding aggregate indexer ('all' indexer) ...
Loaded 597 indexers in total
Loaded 524 Cardigann indexers.
Loading Cardigann indexers from: /home/ubuntu/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /home/ubuntu/Jackett/Definitions
Loaded 73 Native indexers.
Loading Native indexers ...
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://localhost:8191/v1
Using proxy: Disabled
App config/log directory: /home/ubuntu/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 23.04 \n \l
Jackett variant: CoreLinuxArm64
OS version: Unix 6.2.0.1015 (64bit OS) (64bit process)
Environment version: 6.0.24 (/home/ubuntu/Jackett/)
Starting Jackett v0.21.1085
```

### Description

Using EZTV as an indexer.

### Logged Error Messages

```text
10-28 16:44:39 Error Jackett.Common.IndexerException: Exception (eztv): HTTP StatusCode not 200 or 500. Status is :NotFound

[v0.21.1085.0] Jackett.Common.IndexerException: Exception (eztv): HTTP StatusCode not 200 or 500. Status is :NotFound
 ---> FlareSolverrSharp.Exceptions.FlareSolverrException: HTTP StatusCode not 200 or 500. Status is :NotFound
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 531
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 312
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 330
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 706
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in ./Jackett.Server/Controllers/ResultsController.cs:line 233
```

**Comment by garfield69** [comment]
Fix your flaresolverr link on your Jackett dashboard. you currently have it set as `http://localhost:8191/v1`
It should be `http://localhost:8191/`
