### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by MarekBeers** [Jackett/Jackett#14821]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2

Using FlareSolverr: No

Using proxy: Disabled

App config/log directory: /home/marek/.config/Jackett

ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads

Running in Docker: No

File /etc/issue: Ubuntu 20.04.6 LTS \n \l

Jackett variant: CoreLinuxAmdx64

OS version: Unix 5.15.0.88 (64bit OS) (64bit process)

Environment version: 6.0.24 (/home/marek/plex_hdd/Jackett.Binaries.LinuxAMDx64/Jackett/)

Starting Jackett v0.21.1138
```

### Description

Jackett just updated to the new release and I get the the error/s stated below.

### Logged Error Messages

```text
2023-11-05 21:05:02 	Error 	 System.NullReferenceException: Object reference not set to an instance of an object.

[v0.21.1138.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Models.ResultPage.<>c.<ToXml>b__14_0(ReleaseInfo r) in ./Jackett.Common/Models/ResultPage.cs:line 77
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XElement..ctor(XName name, Object[] content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in ./Jackett.Common/Models/ResultPage.cs:line 59
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 442

2023-11-05 21:05:02 	Info 	 Torznab search in AggregateSearch => Found 1000 releases [40134ms]

2023-11-05 21:04:13 	Error 	 System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already been disposed.

[v0.21.1138.0] System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it (or one of its parent scopes) has already been disposed.
   at Autofac.Core.Lifetime.LifetimeScope.ThrowDisposedException()
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.ContentResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

2023-11-05 21:04:13 	Error 	 System.NullReferenceException: Object reference not set to an instance of an object.

[v0.21.1138.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Models.ResultPage.<>c.<ToXml>b__14_0(ReleaseInfo r) in ./Jackett.Common/Models/ResultPage.cs:line 77
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XElement..ctor(XName name, Object[] content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in ./Jackett.Common/Models/ResultPage.cs:line 59
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 442

2023-11-05 21:04:13 	Info 	 Torznab search in AggregateSearch => Found 1000 releases [40617ms]
```

**Comment by garfield69** [comment]
One of the indexers in your AggregateSearch  group is unable to fetch data, but I cannot tell which one is faulty.
I suggest you access the Jackett dashboard and test each indexer individually so we can at least have an indexer name to work with.

**Comment by MarekBeers** [comment]
I basically added all the public indexers in jackett, and I was using the slash /all endpoint. Even after removing all indexers that gave 'errors' it still was throwing the same error. Now I added a few indexers using there own endpoint and that seems to work. Sorry for the troubles but still weird that it broke on the most recent update.

**Comment by garfield69** [comment]
Well, there has not been any changes to Jackett core in quite some time, all the recent changes are to individual indexers.
Its possible one of the web sites was temporarily out of action or returning a html page with a notice instead of the expected xml result, but without a name we will never know. 
My daily test of all public indexer came out clean today.
