### ISSUE TITLE
[cinemamovies] (updating) Login failed: Selector "a[href^="/logout.php"]" didn't match: Parse error

### ISSUE THREAD

**Issue by padrekopre** [Jackett/Jackett#14848]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-11-12 10:44:31	Info	Using HTTP Client: HttpWebClient2
2023-11-12 10:44:31	Info	Using FlareSolverr: No
2023-11-12 10:44:31	Info	Using proxy: Disabled
2023-11-12 10:44:31	Info	App config/log directory: /config/Jackett
2023-11-12 10:44:31	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-11-12 10:44:31	Info	Running in Docker: Yes (image build: unknown)
2023-11-12 10:44:31	Info	File /etc/issue: Arch Linux \r (\l)
2023-11-12 10:44:31	Info	Jackett variant: CoreLinuxAmdx64
2023-11-12 10:44:31	Info	OS version: Unix 6.1.49.0 (64bit OS) (64bit process)
2023-11-12 10:44:31	Info	Environment version: 6.0.24 (/usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.24/)
2023-11-12 10:44:23	Info	Jackett Data will be stored in: /config/Jackett
2023-11-12 10:44:23	Info	Starting Jackett v0.21.1155
```

### Description

when try to login I get error : 

```
An error occurred while testing this indexer
Exception (cinemamovies): Login failed: Selector "a[href^="/logout.php"]" didn't match: Parse error
```

a few weeks ago it was working fine

### Logged Error Messages

```text
2023-11-12 10:35:09	Error	
System.UriFormatException: Invalid URI: The format of the URI could not be determined.

[v0.21.1155.0] System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Jackett.Common.Indexers.BaseIndexer.LoadValuesFromJson(JToken jsonConfig, Boolean useProtectionService) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 113
   at Jackett.Common.Indexers.CardigannIndexer.LoadValuesFromJson(JToken jsonConfig, Boolean useProtectionService) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 226
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1040
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2023-11-12 10:33:36	Error	
Jackett.Common.IndexerException: Exception (cinemamovies): Login failed: Selector "a[href^="/logout.php"]" didn't match

[v0.21.1155.0] Jackett.Common.IndexerException: Exception (cinemamovies): Login failed: Selector "a[href^="/logout.php"]" didn't match
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href^="/logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1722
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 759
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1878
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 359
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 359
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 736
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2023-11-12 10:33:36	Error	
Error on 20231112103336 for CinemaMovieS_ZT.txtJackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href^="/logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1722




2023-11-12 10:33:36	Info	
CardigannIndexer(cinemamovies): Relogin required
2023-11-12 10:33:36	Error	
Redirected to: https://cinemamovies.pl/login.php?returnto=%2Fbrowse.php%3Fincldead%3D1%26blah%3D0%26gatunek%3D0%26quality%3Dnone%26sort%3D2%26type%3Ddesc
```

### Screenshots

![Zrzut ekranu 2023-11-12 o 10 36 04](https://github.com/Jackett/Jackett/assets/8384168/ae52f6ab-65b7-4e0f-b4b5-5b1954ada0b5)

**Comment by garfield69** [comment]
@ilike2burnthing  is the indexer working for you?

**Comment by padrekopre** [comment]
I can login on the site and download torrent file.

**Comment by ilike2burnthing** [comment]
Yep, working fine here. Looks like the issue is you've removed `https://` from the sitelink for some reason. Don't do that.

**Comment by padrekopre** [comment]
I've remove it to check if it's the problem - with or without it does not work.

**Comment by ilike2burnthing** [comment]
K, so the actual error you're reporting then is the login error.

Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-selector

If you still have problems, provide an enhanced log of the login issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by padrekopre** [comment]
Is that OK ? :

[log.txt](https://github.com/Jackett/Jackett/files/13402885/log.txt)

**Comment by garfield69** [comment]
The log (starting at line 4372) shows that now that you are using the correct sitelink you are not longer getting the invalid uri error.
However, the cookie you are using was not accepted by cinemamovies, and you are begin redirected to the login page.

You are a docker user, so from which browser on which machine are you using to get the cookie from?
https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work
@ilike2burnthing  anything to add?

**Comment by padrekopre** [comment]
My mistake - I copied the cookie content from the browser incorrectly - I didn't copy the 'hashv' part... now it works properly - sorry for bothering you.
