### ISSUE TITLE
[mejortorrent] (testing) Exception (mejortorrent): Se ha forzado la interrupción de una conexión existente por el host remoto.: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by killo3967** [Jackett/Jackett#14854]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-11-16 13:43:35.4106 Info Starting Jackett v0.21.1214
2023-11-16 13:43:36.0491 Info Environment version: 6.0.25 (C:\ProgramData\Jackett\)
2023-11-16 13:43:36.0491 Info OS version: Microsoft Windows NT 10.0.22621.0 (64bit OS)
2023-11-16 13:43:36.0491 Info Jackett variant: CoreWindows
2023-11-16 13:43:36.0491 Info Running in Docker: No
2023-11-16 13:43:36.0702 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2023-11-16 13:43:36.0702 Info App config/log directory: C:\ProgramData\Jackett
2023-11-16 13:43:36.0702 Info Using proxy: Disabled
2023-11-16 13:43:36.0702 Info Using FlareSolverr: http://localhost:8191/
2023-11-16 13:43:36.0702 Info Using HTTP Client: HttpWebClient2
2023-11-16 13:43:36.0862 Info Loading Native indexers ...
2023-11-16 13:43:36.1563 Info Loaded 73 Native indexers.
2023-11-16 13:43:36.1602 Info Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, C:\ProgramData\Jackett\Definitions
2023-11-16 13:43:40.8066 Info Loaded 532 Cardigann indexers.
2023-11-16 13:43:40.8066 Info Loaded 605 indexers in total
2023-11-16 13:43:40.8066 Info Adding aggregate indexer ('all' indexer) ...
2023-11-16 13:43:40.8159 Info Adding filter indexer ('type:public' indexer) ...
2023-11-16 13:43:40.8159 Info Adding filter indexer ('type:private' indexer) ...
2023-11-16 13:43:40.8159 Info Adding filter indexer ('type:semi-public' indexer) ...
2023-11-16 13:43:40.9663 Info Jackett startup finished in 5.829 s
```

### Description

Error from test:

An error occurred while testing this indexer
Exception (mejortorrent): Se ha forzado la interrupción de una conexión existente por el host remoto.: The SSL connection could not be established, see inner exception.
[Click here to open an issue on GitHub for this indexer.](https://github.com/Jackett/Jackett/issues/new?template=bug_report.yml&title=[mejortorrent]%20(testing)%20Exception%20(mejortorrent)%3A%20Se%20ha%20forzado%20la%20interrupci%C3%B3n%20de%20una%20conexi%C3%B3n%20existente%20por%20el%20host%20remoto.%3A%20The%20SSL%20connection%20could%20not%20be%20established%2C%20see%20inner%20exception.)

### Logged Error Messages

```text
2023-11-16 13:53:55.4822 Error Jackett.Common.IndexerException: Exception (mejortorrent): Se ha forzado la interrupciÃ³n de una conexiÃ³n existente por el host remoto.

[v0.21.1214.0] Jackett.Common.IndexerException: Exception (mejortorrent): Se ha forzado la interrupciÃ³n de una conexiÃ³n existente por el host remoto.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Se ha forzado la interrupciÃ³n de una conexiÃ³n existente por el host remoto..
 ---> System.Net.Sockets.SocketException (10054): Se ha forzado la interrupciÃ³n de una conexiÃ³n existente por el host remoto.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 562
   at Jackett.Common.Indexers.MejorTorrent.PerformQueryNewest(TorznabQuery query) in ./Jackett.Common/Indexers/MejorTorrent.cs:line 167
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/MejorTorrent.cs:line 149
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 339
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 357
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 733
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Update to [v0.21.1217](https://github.com/Jackett/Jackett/releases/v0.21.1217). If the problem continues, delete the indexer, restart the Jackett service, re-add the indexer, and test.

If you still have issues, follow the troubleshooting steps here:
- https://github.com/Jackett/Jackett/wiki/Troubleshooting/#connection-reset-by-peer-the-ssl-connection-could-not-be-established
- https://github.com/Jackett/Jackett/wiki/Troubleshooting/#a-connection-attempt-failed

**Comment by killo3967** [comment]
I update to 0.21.1217 and could connect to indexer . 

Thanks very much.

**Comment by killo3967** [comment]
I update to 0.21.1217 and could connect to indexer .
