### ISSUE TITLE
Hebits bug

### ISSUE THREAD

**Issue by HighsR** [Jackett/Jackett#14859]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett startup finished in 2.796 s
2023-11-22 13:21:20	Info	Using HTTP Client: HttpWebClient2
2023-11-22 13:21:20	Info	Using FlareSolverr: http://172.17.0.1:XXXXX
2023-11-22 13:21:20	Info	Using proxy: Disabled
2023-11-22 13:21:20	Info	App config/log directory: /config/Jackett
2023-11-22 13:21:20	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-11-22 13:21:20	Info	Running in Docker: Yes (image build: v0.21.1236-ls226)
2023-11-22 13:21:20	Info	File /etc/issue: Welcome to Alpine Linux 3.18
2023-11-22 13:21:20	Info	Jackett variant: CoreLinuxMuslAmdx64
2023-11-22 13:21:20	Info	OS version: Unix 5.10.0.0 (64bit OS) (64bit process)
2023-11-22 13:21:20	Info	Environment version: 6.0.25 (/app/Jackett/)
2023-11-22 13:21:19	Info	Starting Jackett v0.21.1236
```

### Description

hebits doesnt work for me in jackett 

### Logged Error Messages

```text
Error downloading. indexer: hebits path: https://hebits.net/torrents.php?action=download&id=(removed) BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 99
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 99
```

**Comment by garfield69** [comment]
I can initiate a download with the hebits indexer so the issue appears to be at your end.
The error suggests that instead of being presented with a torrent you are being presented with a html page.
Have you logged into hebits on the website with your browser and confirmed that you do not have any outstanding alerts, such as  low ratio, outstanding H&R, unread mail or anything else that could prevent you downloading from the website?
To see what is going on try to download via the browser and you should see what is going on.

If you cannot figure it out then provide an enhanced log and we can take a look. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by HighsR** [comment]
in the logs it says I am getting blocked because I am trying to log in from a deferent country is there a way to bypass it ?

**Comment by ilike2burnthing** [comment]
A proxy or VPN.
