### ISSUE TITLE
[rutracker] "(Error 521) - The tracker seems to be down" but it loads fine in browser

### ISSUE THREAD

**Issue by rmlrml** [Jackett/Jackett#14865]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.17.0.2:8191/
Using proxy: Disabled
App config/log directory: /home/ryan/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 12 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 6.1.0.13 (64bit OS) (64bit process)
Environment version: 6.0.25 (/opt/Jackett/)
Starting Jackett v0.21.1256
```

### Description

1. receive error "Jackett: connection error for indexer: rutracker!" in qBittorrent results
2. open Jackett dashboard in Firefox 115.5.0esr
3. click "Test" button next to rutracker
4. receive error

> Exception (rutracker): Request to https://rutracker.org/forum/tracker.php?nm= failed (Error 521) - The tracker seems to be down.

5. try rutracker.org in a new tab in browser, **page loads fine**; refresh several times, do a test search, **everything loads fine**.

fwiw I created a new vanilla FF profile and tested the website, it gives 521 consistently, although occasionally randomly works.  Whereas my normal profile I can't seem to get the website to fail.  It works consistently.  And there's murmerings around the web of rutracker being down lately and it's all weird and inconsistent.

I don't know what it is about my main profile that's allowing the site to load fine and search for torrents.  DNS settings are the same in both profiles.  How can I make Jacket approach the website the same way my browser is approaching it, so that it just works?

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (rutracker): Request to https://rutracker.org/forum/tracker.php?nm= failed (Error 521) - The tracker seems to be down.

[v0.21.1256.0] Jackett.Common.IndexerException: Exception (rutracker): Request to https://rutracker.org/forum/tracker.php?nm= failed (Error 521) - The tracker seems to be down.
 ---> System.Exception: Request to https://rutracker.org/forum/tracker.php?nm= failed (Error 521) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 606
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 562
   at Jackett.Common.Indexers.RuTracker.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/RuTracker.cs:line 1465
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 359
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 359
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 736
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 319
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
have you tried the other two alternate domains .net and .nl , do they behave the same way for you with jackett?

**Comment by rmlrml** [comment]
OMG I accidentally clicked the trash can icon instead of the wrench icon and deleted it.

But when I try to add it again, yes, I get the same 521 for both .net and .nl

> An error occurred while updating this indexer
> Request to https://rutracker.net/forum/login.php failed (Error 521) - The tracker seems to be down.

> An error occurred while updating this indexer
> Request to https://rutracker.nl/forum/login.php failed (Error 521) - The tracker seems to be down.

**Comment by garfield69** [comment]
Interesting.
As for your existing browser profile working, that is likely due to the browser cache. I bet that if you were to delete the cookie and cache you would probably end up with the same issue, BUT DO NOT do it to test ;-)
@ilike2burnthing any thoughts on this topic?

**Comment by shir** [comment]
Having the same issue. Work without issues in the browser with VPN and without VPN and in private mode too. But failed in the Jackett

**Comment by ilike2burnthing** [comment]
Not working in browser or Jackett for me normally, but works in both when using a VPN/proxy in a different location. Using a VPN in the same location makes it fail again.

Uptrends shows failures for 13 checkpoints - 2 timing out, the rest getting a 521 error. Repeated tests show the same checkpoints failing.

I'm assuming it's a temporary localised error, rather than geo-blocking. Just gotta wait it out.
