### ISSUE TITLE
[oldtoonsworld] (testing) Test search in Old Toons World => Found no results while trying to browse this tracker.

### ISSUE THREAD

**Issue by IevgenSobko** [Jackett/Jackett#14872]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Dockerized Jacket latest version
```

### Description

Seems OldToonsWorld changed little bit HTML structure so regex parsing doesn't work now.
Configure OldToonsWorld indexer
Try to test it or manually search

### Logged Error Messages

```text
System.Exception: Error while parsing field=date, selector=, value=2.00GB +00:00: DateTime parsing failed for "2.00GB +00:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 197
 ---> System.Exception: DateTime parsing failed for "2.00GB +00:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 197
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 225
   at Jackett.Common.Indexers.CardigannIndexer.ParseFields(String value, String FieldName, ReleaseInfo release, List`1 FieldModifiers, Uri searchUrlUri) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 2319
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1808
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1818
11-29 18:43:04 Error CardigannIndexer (oldtoonsworld): Error while parsing row '
<tr>
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=404">
			<img class="c_doc" src="pic/cattrans.gif" alt="Cartoon" title="Cartoon" style="background-image: url(pic/category/chd/scenetorrents/en/catsprites.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left" style="padding: 0px">
		<table class="torrentname" width="100%">
			<tbody>
				<tr>
					<td class="embedded" style="text-align: center;width: 46px;height: 46px">
						<img src="pic/misc/spinner.svg" data-src="https://m.media-amazon.com/images/M/MV5BYjBkM2RjMzItM2M3Ni00N2NjLWE3NzMtMGY4MzE4MDAzMTRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg" class="nexus-lazy-load" style="max-height: 46px;max-width: 46px">
					</td>
					<td class="embedded" style="padding-left: 5px">
						<a onmouseover="get_ext_info_ajax('torrent_97','1049413','0','minor'); domTT_activate(this, event, 'content', document.getElementById('torrent_97'), 'trail', false, 'delay',600,'lifetime',6000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 500);" href="details.php?id=11955&amp;hit=1">
							<b>Up 2009 1080p BluRay DD+ 5.1 x265-NAN0</b>
						</a>
						<img class="hitandrun" src="pic/trans.gif" alt="H&amp;R" title="H&amp;R">
						<br>
						<span style="background-color:#DA81F5;color:#ffffff;border-radius:0;font-size:12px;margin:	 0 4px 0 0;padding:1px 2px" title="">HD</span>
						<span style="background-color:#C71585;color:#ffffff;border-radius:0;font-size:12px;margin:0 4px 0 0;padding:1px 2px" title="">&gt;00's</span>
						<span style="background-color:#8B008B;color:#ffffff;border-radius:0;font-size:12px;margin:0 4px 0 0;padding:1px 2px" title="">Movie</span>Animation, Comedy, Family, Adventure</td>
					<td class="embedded" style="text-align: right; width: 40px;padding: 4px">
						<div style="display: flex;flex-direction: column">
							<div style="display: flex;align-content: center;justify-content: space-between;padding: 2px 0">
								<img src="pic/imdb2.png" alt="imdb" title="imdb" style="max-width: 16px;max-height: 16px">
								<span>8.3</span>
							</div>
						</div>
					</td>
					<td width="20" class="embedded" style="text-align: right;padding-right: 5px" valign="middle">
						<a href="download.php?id=11955">
							<img class="download" src="pic/trans.gif" style="padding-bottom: 2px;" alt="download" title="Download&nbsp;Torrent">
						</a>
						<br>
						<a id="bookmark97" href="javascript: bookmark(11955,97);">
							<img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="Bookmark">
						</a>
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">
		<span title="2023-11-18 00:50:31">11 days<br>15 hours</span>
	</td>
	<td class="rowfollow">5.36<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=11955&amp;hit=1&amp;dllist=1#seeders">13</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=11955">
			<b>14</b>
		</a>
	</td>
	<td class="rowfollow">
		<span class="nowrap">
			<a href="https://oldtoons.world/userdetails.php?id=12743" class="PowerUser_Name">
				<b>redglassleaf</b>
			</a>
		</span>
	</td>
</tr>':
```

**Comment by garfield69** [comment]
Your error is most likely due to your **User CP / Tracker Settings / Comments** setting.
I think you have the **Show number of comments** checkbox _un-ticked_, which hides this field from the results and throws off the field count for the Jackett indexer by one, causing the indexer to pick up the size field instead of the date field.
So **tick** the **comments** checkbox, save, and then try your indexer again and you should be good to go.
Let me know what you find.

**Comment by IevgenSobko** [comment]
Yes, that was the problem.
After checking comments number, indexer works 💥
@garfield69  Is this fix documented somewhere?

**Comment by garfield69** [comment]
No, its not documented. All the nexus indexers have this potential problem, but out of the 77 nexus indexers and the hundreds of  thousands of users that use Jackett this issue rarely crops up if ever. ;-)
