### ISSUE TITLE
[audiobookbay] (updating) Connection timed out (audiobookbay.is:443): Connection timed out

### ISSUE THREAD

**Issue by Bishop-trevorstuart** [Jackett/Jackett#14928]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2023-12-21 15:38:34	Info	Using HTTP Client: HttpWebClient2
2023-12-21 15:38:34	Info	Using FlareSolverr: http://192.168.1.:8191/
2023-12-21 15:38:34	Info	Using proxy: Disabled
2023-12-21 15:38:34	Info	App config/log directory: /home//.config/Jackett
2023-12-21 15:38:34	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2023-12-21 15:38:34	Info	Running in Docker: No
2023-12-21 15:38:34	Info	File /etc/issue: Ubuntu 20.04.6 LTS \n \l
2023-12-21 15:38:34	Info	Jackett variant: CoreLinuxAmdx64
2023-12-21 15:38:34	Info	OS version: Unix 5.4.0.169 (64bit OS) (64bit process)
2023-12-21 15:38:34	Info	Environment version: 6.0.25 (/home//Jackett/)
2023-12-21 15:38:33	Info	Starting Jackett v0.21.1431
```

### Description

Happens when adding tracker

### Logged Error Messages

```text
An error occurred while updating this indexer
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: A task was canceled.

2023-12-21 15:41:41	Error	
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

[v0.21.1431.0] System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 569
   at Jackett.Common.Indexers.AudioBookBay.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/AudioBookBay.cs:line 193
   at Jackett.Common.Indexers.AudioBookBay.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/AudioBookBay.cs:line 158
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
have you tried using the alternate sitelink for this indexer (use your jackett dashboard to edit the indexer config and select the alternate sitelink and save) ?
Are other public indexers working for you are are all of them timing out this way?

**Comment by garfield69** [comment]
I notice your flaresolverr config on the jackett dashboard is missing an address node `192.168.1.`
is this a typo?

**Comment by Bishop-trevorstuart** [comment]
I was sanitising and got a bit overzealous. Flaresolver does have a proper address. 
This is the only tracker Im Having issues with.

**Comment by garfield69** [comment]
What about my earlier questions?
>have you tried using the alternate sitelink for this indexer (use your jackett dashboard to edit the indexer config and select the alternate sitelink and save) ?
>Are other public indexers working for you are are all of them timing out this way?

**Comment by garfield69** [comment]
never mind, I see that the .se domain redirects to the .is domain.
the .is domain is working for me with this indexer, so the issue appears to be at your end.
may be worth turning on enhanced logging to see if we get a little more info about your issue
see https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ilike2burnthing** [comment]
Not sure why jackettbot hasn't closed this, maybe taking Christmas and new years off :P
