### ISSUE TITLE
[unionfansub] (updating) Login failed: Selector "div#statusbar" didn't match

### ISSUE THREAD

**Issue by darlopvil** [Jackett/Jackett#14921]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Flaresolverr: yes, activated.
Jackett version: latest
OS version: Windows 10 x64 bits

More info needed? I don't see the environment info requested in the Jackett log.
```

### Description

Selected "union fansub" semi private tracker from the list
Introduced the credentials
Clicked "Okay"
Error prompted

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#statusbar" didn't match

[v0.21.1424.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#statusbar" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![imagen](https://github.com/Jackett/Jackett/assets/60988792/7589b60b-cd1e-42e8-980e-eb207fe57f6a)

**Comment by garfield69** [comment]
1. to fill the environment section properly, first shutdown and start-up Jackett. then browser the dashboard log and you will find the info you need.
2. the unionfansub indexer is working for me which suggests the issue is at you end. The error you are getting suggest that the login did not work, but we cannot tell the cause from what little is provided.
Please provide a full enhanced log, see https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by darlopvil** [comment]
I've edited mi first post, now you can see the environment report correctly.

And here's the log:

[log.txt](https://github.com/Jackett/Jackett/files/13708061/log.txt)

**Comment by garfield69** [comment]
The log shows that you entered in invalid combination of username and password.
I suggest you use your browser to login to the web site directly, and thus confirm that the username and password are correct.
If you recently changed your password, then use your browser to logout of the site and login back again to confirm you have the correct credentials.
Then use your jackett dashboard to edit the indexer and clear and re-enter the username and password afresh and you should be good to go.
if you still have issue let us know and we can take another look.

**Comment by garfield69** [comment]
BTW you log also shows that you have not enabled RSS feed on your exoticaz account profile, so you are currently seeing Error 403: Access Denied! errors.
There is also something wrong with your chilebt indexer, but I cant tell exactly what that might be.

**Comment by darlopvil** [comment]
It was weird, although I had my credentials, the site didn't seem to recognize them. I've created again my account with the same info and now it works. Never would have thought that was the cause tbh, thanks.

Also, checked Exoticaz. Again, weird, I always try to be careful with all this. On the other side, perhaps being leech on ChileBT is the reason. Sign in and browsing the web was ok.

**Comment by garfield69** [comment]
v0.24.1552
