### ISSUE TITLE
[lostfilm] (adding): Request to Jackett server failed

### ISSUE THREAD

**Issue by Vinticb** [Jackett/Jackett#14954]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
Running in Docker: Yes (image build: v0.21.1454-ls263)
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.0.0.0 (64bit OS) (64bit process)
Environment version: 6.0.25 (/app/Jackett/)
Starting Jackett v0.21.1491
```

### Description

The error occurs while adding the indexer.
I press button "Add indexer", when i found "Lostfilm" in the list, when i press button "Configure". After that  window "Select an indexer to setup" closes, the indexer is not added to the list, and an error "Request to Jackett server failed" appears
[log4.txt](https://github.com/Jackett/Jackett/files/13834042/log4.txt)

### Logged Error Messages

```text
2024-01-04 20:52:37.6959 Info Starting Jackett v0.21.1491
2024-01-04 20:52:38.7413 Info Environment version: 6.0.25 (/app/Jackett/)
2024-01-04 20:52:38.7530 Info OS version: Unix 6.0.0.0 (64bit OS) (64bit process)
2024-01-04 20:52:38.7530 Info Jackett variant: CoreLinuxMuslAmdx64
2024-01-04 20:52:38.7530 Info File /etc/issue: Welcome to Alpine Linux 3.18
2024-01-04 20:52:38.7530 Info Running in Docker: Yes (image build: v0.21.1454-ls263)
2024-01-04 20:52:38.7566 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-01-04 20:52:38.7566 Info App config/log directory: /config/Jackett
2024-01-04 20:52:38.7566 Info Using proxy: Disabled
2024-01-04 20:52:38.7566 Info Using FlareSolverr: No
2024-01-04 20:52:38.7599 Info Using HTTP Client: HttpWebClient2
2024-01-04 20:52:38.7660 Info Loading Native indexers ...
2024-01-04 20:52:38.9022 Info Loaded 73 Native indexers.
2024-01-04 20:52:38.9074 Info Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
2024-01-04 20:52:40.7514 Info Loaded 533 Cardigann indexers.
2024-01-04 20:52:40.7514 Info Loaded 606 indexers in total
2024-01-04 20:52:40.7531 Info Adding aggregate indexer ('all' indexer) ...
2024-01-04 20:52:40.7627 Info Adding filter indexer ('type:public' indexer) ...
2024-01-04 20:52:40.7627 Info Adding filter indexer ('type:private' indexer) ...
2024-01-04 20:52:40.7716 Info Adding filter indexer ('type:semi-public' indexer) ...
2024-01-04 20:52:40.9554 Info Jackett startup finished in 3.797 s
2024-01-04 20:52:57.0117 Info Executing JsonResult, writing value of type 'Jackett.Common.Models.Config.ServerConfig'.
2024-01-04 20:52:57.0323 Debug The response will be compressed with 'gzip'.
2024-01-04 20:52:57.0323 Info Executed endpoint 'Jackett.Server.Controllers.ServerConfigurationController.UpdateConfig (jackett)'
2024-01-04 20:52:57.0379 Debug Connection id "0HN0D9NP85UA9" completed keep alive response.
2024-01-04 20:53:02.0638 Info Request starting HTTP/1.1 GET http://192.168.17.8:9117/UI/Dashboard - -
2024-01-04 20:53:02.0638 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/UI/Dashboard
2024-01-04 20:53:02.1171 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/UI/Dashboard
2024-01-04 20:53:02.1171 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/UI/Dashboard
2024-01-04 20:53:02.1215 Debug The request path /UI/Dashboard does not match a supported file type
2024-01-04 20:53:02.1215 Debug AuthenticationScheme: Cookies was successfully authenticated.
2024-01-04 20:53:02.1307 Debug 1 candidate(s) found for the request path '/UI/Dashboard'
2024-01-04 20:53:02.1369 Debug Endpoint 'Jackett.Server.Controllers.WebUIController.Dashboard (jackett)' with route pattern 'UI/Dashboard' is valid for the request path '/UI/Dashboard'
2024-01-04 20:53:02.1369 Debug Request matched endpoint 'Jackett.Server.Controllers.WebUIController.Dashboard (jackett)'
2024-01-04 20:53:02.1369 Info Executing endpoint 'Jackett.Server.Controllers.WebUIController.Dashboard (jackett)'
2024-01-04 20:53:02.1434 Info Route matched with {action = "Dashboard", controller = "WebUI"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Dashboard() on controller Jackett.Server.Controllers.WebUIController (jackett).
2024-01-04 20:53:02.1491 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2024-01-04 20:53:02.1491 Debug Execution plan of resource filters (in the following order): None
2024-01-04 20:53:02.1491 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2024-01-04 20:53:02.1526 Debug Execution plan of exception filters (in the following order): None
2024-01-04 20:53:02.1526 Debug Execution plan of result filters (in the following order): None
2024-01-04 20:53:02.1574 Debug Authorization was successful.
2024-01-04 20:53:02.1742 Debug Executing controller factory for controller Jackett.Server.Controllers.WebUIController (jackett)
2024-01-04 20:53:02.1742 Debug Executed controller factory for controller Jackett.Server.Controllers.WebUIController (jackett)
2024-01-04 20:53:02.1762 Info Executing PhysicalFileResult, sending file '/app/Jackett/Content/index.html' with download name '' ...
2024-01-04 20:53:02.1762 Debug The file result has not been enabled for processing range requests. To enable it, set the EnableRangeProcessing property on the result to 'true'.
2024-01-04 20:53:02.1762 Debug The response will be compressed with 'gzip'.
2024-01-04 20:53:02.1885 Info Executed action Jackett.Server.Controllers.WebUIController.Dashboard (jackett) in 27.4311ms
2024-01-04 20:53:02.1885 Info Executed endpoint 'Jackett.Server.Controllers.WebUIController.Dashboard (jackett)'
2024-01-04 20:53:02.1885 Debug Connection id "0HN0D9NP85UA9" completed keep alive response.
2024-01-04 20:53:02.1885 Info Request finished HTTP/1.1 GET http://192.168.17.8:9117/UI/Dashboard - - - 200 - text/html 129.9984ms
2024-01-04 20:53:02.3820 Info Request starting HTTP/1.1 GET http://192.168.17.8:9117/api/v2.0/server/config?_=1704390783166 - -
2024-01-04 20:53:02.3820 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/api/v2.0/server/config?_=1704390783166
2024-01-04 20:53:02.3820 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/api/v2.0/server/config?_=1704390783166
2024-01-04 20:53:02.3845 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/api/v2.0/server/config?_=1704390783166
2024-01-04 20:53:02.3845 Debug The request path /api/v2.0/server/config does not match a supported file type
2024-01-04 20:53:02.3845 Debug AuthenticationScheme: Cookies was successfully authenticated.
2024-01-04 20:53:02.3845 Debug 1 candidate(s) found for the request path '/api/v2.0/server/config'
2024-01-04 20:53:02.3845 Debug Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Config (jackett)' with route pattern 'api/v2.0/server/Config' is valid for the request path '/api/v2.0/server/config'
2024-01-04 20:53:02.3887 Debug Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Config (jackett)'
2024-01-04 20:53:02.3887 Info Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Config (jackett)'
2024-01-04 20:53:02.3887 Info Route matched with {action = "Config", controller = "ServerConfiguration"}. Executing controller action with signature Jackett.Common.Models.DTO.ServerConfig Config() on controller Jackett.Server.Controllers.ServerConfigurationController (jackett).
2024-01-04 20:53:02.3887 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2024-01-04 20:53:02.3923 Debug Execution plan of resource filters (in the following order): None
2024-01-04 20:53:02.3923 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2024-01-04 20:53:02.3923 Debug Execution plan of exception filters (in the following order): None
2024-01-04 20:53:02.3923 Debug Execution plan of result filters (in the following order): None
2024-01-04 20:53:02.3923 Debug Authorization was successful.
2024-01-04 20:53:02.3963 Debug Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2024-01-04 20:53:02.3963 Debug Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2024-01-04 20:53:02.4007 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter
2024-01-04 20:53:02.4040 Debug No information found on request to perform content negotiation.
2024-01-04 20:53:02.4040 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
2024-01-04 20:53:02.4040 Debug Attempting to select the first formatter in the output formatters list which can write the result.
2024-01-04 20:53:02.4040 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response.
2024-01-04 20:53:02.4088 Info Executing ObjectResult, writing value of type 'Jackett.Common.Models.DTO.ServerConfig'.
2024-01-04 20:53:02.4088 Debug The response will be compressed with 'gzip'.
2024-01-04 20:53:02.4088 Info Executed action Jackett.Server.Controllers.ServerConfigurationController.Config (jackett) in 14.8155ms
2024-01-04 20:53:02.4088 Info Executed endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Config (jackett)'
2024-01-04 20:53:02.4088 Debug Connection id "0HN0D9NP85UA9" completed keep alive response.
2024-01-04 20:53:02.4088 Info Request finished HTTP/1.1 GET http://192.168.17.8:9117/api/v2.0/server/config?_=1704390783166 - - - 200 - application/json;+charset=utf-8 29.5100ms
2024-01-04 20:53:02.4177 Info Request starting HTTP/1.1 GET http://192.168.17.8:9117/api/v2.0/indexers?_=1704390783167 - -
2024-01-04 20:53:02.4177 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/api/v2.0/indexers?_=1704390783167
2024-01-04 20:53:02.4177 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/api/v2.0/indexers?_=1704390783167
2024-01-04 20:53:02.4177 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/api/v2.0/indexers?_=1704390783167
2024-01-04 20:53:02.4203 Debug The request path /api/v2.0/indexers does not match a supported file type
2024-01-04 20:53:02.4203 Debug AuthenticationScheme: Cookies was successfully authenticated.
2024-01-04 20:53:02.4203 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers'
2024-01-04 20:53:02.4203 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Indexers (jackett)' with route pattern 'api/v2.0/indexers' is valid for the request path '/api/v2.0/indexers'
2024-01-04 20:53:02.4203 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Indexers (jackett)'
2024-01-04 20:53:02.4203 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Indexers (jackett)'
2024-01-04 20:53:02.4239 Info Route matched with {action = "Indexers", controller = "IndexerApi"}. Executing controller action with signature System.Collections.Generic.IEnumerable`1[Jackett.Common.Models.DTO.Indexer] Indexers(Boolean) on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2024-01-04 20:53:02.4239 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2024-01-04 20:53:02.4239 Debug Execution plan of resource filters (in the following order): None
2024-01-04 20:53:02.4239 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2024-01-04 20:53:02.4279 Debug Execution plan of exception filters (in the following order): None
2024-01-04 20:53:02.4279 Debug Execution plan of result filters (in the following order): None
2024-01-04 20:53:02.4279 Debug Authorization was successful.
2024-01-04 20:53:02.4279 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2024-01-04 20:53:02.4279 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2024-01-04 20:53:02.4279 Debug Attempting to bind parameter 'configured' of type 'System.Boolean' ...
2024-01-04 20:53:02.4328 Debug Attempting to bind parameter 'configured' of type 'System.Boolean' using the name 'configured' in request data ...
2024-01-04 20:53:02.4328 Debug Could not find a value in the request with name 'configured' for binding parameter 'configured' of type 'System.Boolean'.
2024-01-04 20:53:02.4328 Debug Done attempting to bind parameter 'configured' of type 'System.Boolean'.
2024-01-04 20:53:02.4360 Debug Done attempting to bind parameter 'configured' of type 'System.Boolean'.
2024-01-04 20:53:02.4360 Debug Attempting to validate the bound parameter 'configured' of type 'System.Boolean' ...
2024-01-04 20:53:02.4360 Debug Done attempting to validate the bound parameter 'configured' of type 'System.Boolean'.
2024-01-04 20:53:02.4400 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter
2024-01-04 20:53:02.4400 Debug No information found on request to perform content negotiation.
2024-01-04 20:53:02.4400 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
2024-01-04 20:53:02.4445 Debug Attempting to select the first formatter in the output formatters list which can write the result.
2024-01-04 20:53:02.4445 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and content type 'application/json' to write the response.
2024-01-04 20:53:02.4445 Info Executing ObjectResult, writing value of type 'System.Linq.Enumerable+SelectListIterator`2[[Jackett.Common.Indexers.IIndexer, Jackett.Common, Version=0.21.1491.0, Culture=neutral, PublicKeyToken=(removed) Jackett.Common, Version=0.21.1491.0, Culture=neutral, PublicKeyToken=(removed)
2024-01-04 20:53:02.6245 Debug The response will be compressed with 'gzip'.
2024-01-04 20:53:02.6919 Info Executed action Jackett.Server.Controllers.IndexerApiController.Indexers (jackett) in 263.0753ms
2024-01-04 20:53:02.6919 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Indexers (jackett)'
2024-01-04 20:53:02.6919 Debug Connection id "0HN0D9NP85UA9" completed keep alive response.
2024-01-04 20:53:02.6919 Info Request finished HTTP/1.1 GET http://192.168.17.8:9117/api/v2.0/indexers?_=1704390783167 - - - 200 - application/json;+charset=utf-8 275.8681ms
2024-01-04 20:53:17.9133 Info Request starting HTTP/1.1 GET http://192.168.17.8:9117/api/v2.0/indexers/lostfilm/config?_=1704390783168 - -
2024-01-04 20:53:17.9133 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/api/v2.0/indexers/lostfilm/config?_=1704390783168
2024-01-04 20:53:17.9133 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/api/v2.0/indexers/lostfilm/config?_=1704390783168
2024-01-04 20:53:17.9159 Debug Request is continuing in applying rules. Current url is http://192.168.17.8:9117/api/v2.0/indexers/lostfilm/config?_=1704390783168
2024-01-04 20:53:17.9159 Debug The request path /api/v2.0/indexers/lostfilm/config does not match a supported file type
2024-01-04 20:53:17.9159 Debug AuthenticationScheme: Cookies was successfully authenticated.
2024-01-04 20:53:17.9159 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/lostfilm/config'
2024-01-04 20:53:17.9159 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/lostfilm/config'
2024-01-04 20:53:17.9202 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
2024-01-04 20:53:17.9202 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
2024-01-04 20:53:17.9410 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2024-01-04 20:53:17.9410 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2024-01-04 20:53:17.9444 Debug Execution plan of resource filters (in the following order): None
2024-01-04 20:53:17.9444 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2024-01-04 20:53:17.9444 Debug Execution plan of exception filters (in the following order): None
2024-01-04 20:53:17.9444 Debug Execution plan of result filters (in the following order): None
2024-01-04 20:53:17.9481 Debug Authorization was successful.
2024-01-04 20:53:17.9481 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2024-01-04 20:53:17.9481 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2024-01-04 20:53:17.9595 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.lostfilmtv2.site/login)
2024-01-04 20:53:33.1995 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 15251.5202ms
2024-01-04 20:53:33.2003 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
2024-01-04 20:53:33.2003 Error System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

[v0.21.1491.0] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 569
   at Jackett.Common.Indexers.LostFilm.GetConfigurationForSetup() in ./Jackett.Common/Indexers/LostFilm.cs:line 158
   at Jackett.Server.Controllers.IndexerApiController.Config() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

2024-01-04 20:53:33.4018 Debug The response will be compressed with 'gzip'.
2024-01-04 20:53:33.4018 Debug Connection id "0HN0D9NP85UA9" completed keep alive response.
2024-01-04 20:53:33.4018 Info Request finished HTTP/1.1 GET http://192.168.17.8:9117/api/v2.0/indexers/lostfilm/config?_=1704390783168 - - - 500 - application/json 15489.7382ms
```

### Screenshots

![2024-01-04_20-46-35](https://github.com/Jackett/Jackett/assets/83859796/4898ad6e-74f2-49bd-b0dc-5ca98bc5aa37)

**Comment by ilike2burnthing** [comment]
Which of the following addresses are you able to access from the same IP and using the same DNS as the Jackett container?

https://www.lostfilmtv2.site/
https://www.lostfilmtv3.site/
https://www.lostfilmtv5.site/
https://www.lostfilm.win/
https://www.lostfilm.tw/
https://www.lostfilm.uno/
https://www.lostfilm.life/
https://www.lostfilmtv.site/
https://www.lostfilm.tv/

**Comment by Vinticb** [comment]
> Which of the following addresses are you able to access from the same IP and using the same DNS as the Jackett container?
> 
> https://www.lostfilmtv2.site/ https://www.lostfilmtv3.site/ https://www.lostfilmtv5.site/ https://www.lostfilm.win/ https://www.lostfilm.tw/ https://www.lostfilm.uno/ https://www.lostfilm.life/ https://www.lostfilm.tv/

https://www.lostfilm.win/
https://www.lostfilm.uno/
https://www.lostfilm.life/
https://www.lostfilm.tv/
https://www.lostfilm.tw/

**Comment by garfield69** [comment]
v0.21.1504

**Comment by Vinticb** [comment]
> v0.21.1504

lostfilm works fine, thank you!

**Comment by rummyvn** [comment]
**Lostfilm not work again**
Jackett v0.21.1915
Environment version: 6.0.27 (/app/Jackett/)
OS version: Unix 6.1.64.0 (64bit OS) (64bit process)
Jackett variant: CoreLinuxMuslAmdx64
File /etc/issue: Welcome to Alpine Linux 3.18
Running in Docker: Yes (image build: v0.21.1897-ls323)
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /config/Jackett
Using proxy: Disabled
Using FlareSolverr: http://192.168.1.221:8191
Using HTTP Client: HttpWebClient2
![image](https://github.com/Jackett/Jackett/assets/139438950/b4233ddc-b52e-43f4-b6a5-9862c08d3f31)

**Site good access link:**
https://www.lostfilmtv5.site/

**Comment by ilike2burnthing** [comment]
All working fine here. If one isn't working for you, pick a different one.

**Comment by Vinticb** [comment]
Hello. The same problem appeared again: i can't add lostfilm tracker
**Environment**
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
Running in Docker: Yes (image build: v0.21.2554-ls391)
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.1.0.20 (64bit OS) (64bit process)
Environment version: 6.0.29 (/app/Jackett/)
Starting Jackett v0.21.2554

**Description**
The error occurs while adding the indexer.
I press button "Add indexer", when i found "Lostfilm" in the list, when i press button "Configure". After that window "Select an indexer to setup" closes, the indexer is not added to the list, and an error "Request to Jackett server failed" appears after around 60-80 seconds.

[log7.txt](https://github.com/Jackett/Jackett/files/15219358/log7.txt)

The only one mirror of this tracker is working for me: https://www.lostfilm.download. The rest are blocked by the ISP.

**Comment by Vinticb** [comment]
> Why did you have to add the indexer as new today?

I wanted to change the mirror, but the button "Configure" didn't work on this tracker, so I deleted the tracker, and couldn't add it again after that.

> Alternatively, create a lostfilm.json file in the Indexers folder (or copy another and rename the copy), then add the following and save the file:

It worked, thanks!
