### ISSUE TITLE
BitHumen: Tracker login problem

### ISSUE THREAD

**Issue by shummo** [Jackett/Jackett#14952]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.21.1491
Running on Windows 10.
```

### Description

hi
I have a problem with https://bithumen.be/ tracker. I can not login at all from Jackett. In Chrome I do with no problem.
It said 
401 Unauthorized, check your credentials.

### Logged Error Messages

```text
2024-01-04 16:23:44.1807 Error Jackett.Common.ExceptionWithConfigData: 401 Unauthorized, check your credentials

[v0.21.1491.0] Jackett.Common.ExceptionWithConfigData: 401 Unauthorized, check your credentials
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 525
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 579
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Unfortunately none of the maintainers have an account, so we're unable to test this indexer.

There are some hidden inputs on the login page which we'd normally be able to add to resolve this issue, however it also appears to be using an embedded Cloudflare Turnstile challenge, which FlareSolverr isn't currently able to solve.

I'll create a PR shortly, replacing the credentials login with a cookie one, and I'll provide you with a link for the test build so you can confirm this is working for you.

**Comment by ilike2burnthing** [comment]
Download the [test build](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/10516/artifacts?artifactName=drop&api-version=7.1&%24format=zip), extract and run the Windows installer, once complete reconfigure the BitHUmen indexer with a cookie, following the instructions provided.

If you have any issues, follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

If you still have issues, provide an enhanced log of the failed login - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by shummo** [comment]
Thanks. 
I started to try your build, but before it i reconnected again. (I did't change any, just searched for Bithumen, then click "OKAY". There was already the credentials, that i tried yesterday)
It was succesfull without any error or  any log with credential.  Now i testing it, and reply if go wrong or have to try the build with cookie.
Thanks!
