### ISSUE TITLE
[tvchaosuk] (testing) Exception (tvchaosuk): certificate validation failed: [Subject]  CN=tvchaosuk.com[Issuer]  CN=E1, O=Let's Encrypt, C=US[Serial Number]  040A51B76179C7163B78E9598F9D19293389[Not Before]  12/17/2023 4:19:27 PM[Not After]  3/16/2024 4:19:26 PM[Thumbprint]  5FBB00C292F1724DB365889FD997BC506C587873: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by rtweed** [Jackett/Jackett#14982]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-01-12 16:46:33	Info	Using HTTP Client: HttpWebClient2
2024-01-12 16:46:33	Info	Using FlareSolverr: No
2024-01-12 16:46:33	Info	Using proxy: Disabled
2024-01-12 16:46:33	Info	App config/log directory: /home/sonarr/.config/Jackett
2024-01-12 16:46:33	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-01-12 16:46:33	Info	Running in Docker: No
2024-01-12 16:46:33	Info	File /etc/issue: \S
2024-01-12 16:46:33	Info	Jackett variant: CoreLinuxAmdx64
2024-01-12 16:46:33	Info	OS version: Unix 3.10.0.1062 (64bit OS) (64bit process)
2024-01-12 16:46:33	Info	Environment version: 6.0.26 (/opt/jackett/Jackett/)
2024-01-12 16:46:33	Info	Starting Jackett v0.21.1537
```

### Description

Attempting to connect to tvchaosuk.com; connection has been been configured and working perfectly for several years, but is now failing connection test.

It appears to be failing on the cert validation, which looks current to me and the current system date/time is correct and NTP synced.

From the server commandline, I can connect correctly to https://tvchaos.com, as well as being able to login via the /login page.

Have searched previous issues related to this, and the related issue in the troubleshooting guide; most of the issues there seem to have simple explanations or connectivity failures / site blocking. I can't see any evidence of that here though; can anyone help?

### Logged Error Messages

```text
On testing the connection, the below appears:

Jackett.Common.IndexerException: Exception (tvchaosuk): certificate validation failed: [Subject]
  CN=tvchaosuk.com

[Issuer]
  CN=E1, O=Let's Encrypt, C=US

[Serial Number]
  040A51B76179C7163B78E9598F9D19293389

[Not Before]
  12/17/2023 4:19:27 PM

[Not After]
  3/16/2024 4:19:26 PM

[Thumbprint]
  5FBB00C292F1724DB365889FD997BC506C587873


[v0.21.1537.0] Jackett.Common.IndexerException: Exception (tvchaosuk): certificate validation failed: [Subject]
  CN=tvchaosuk.com

[Issuer]
  CN=E1, O=Let's Encrypt, C=US

[Serial Number]
  040A51B76179C7163B78E9598F9D19293389

[Not Before]
  12/17/2023 4:19:27 PM

[Not After]
  3/16/2024 4:19:26 PM

[Thumbprint]
  5FBB00C292F1724DB365889FD997BC506C587873

 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Exception: certificate validation failed: [Subject]
  CN=tvchaosuk.com

[Issuer]
  CN=E1, O=Let's Encrypt, C=US

[Serial Number]
  040A51B76179C7163B78E9598F9D19293389

[Not Before]
  12/17/2023 4:19:27 PM

[Not After]
  3/16/2024 4:19:26 PM

[Thumbprint]
  5FBB00C292F1724DB365889FD997BC506C587873

   at Jackett.Common.Utils.Clients.HttpWebClient2.ValidateCertificate(HttpRequestMessage request, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 53
   at System.Net.Http.ConnectHelper.<>c__DisplayClass1_0.<SetUpRemoteCertificateValidationCallback>b__0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 569
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 340
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 358
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 744
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 414
```

**Comment by garfield69** [comment]
Hmm. I can get my ubuntu22 jackett tvchaosuk indexer to work ok, so this appears to be an issue on your platform.
Jackett on linux uses OpenSSL to handle its CA validation, and Let's Encrypt certificates have been an issue in the past for some linux platforms.
Which specific flavour of linux are you using?
From a terminal on the same machine that is running jackett what do you get if you use
`openssl s_client -connect tvchaosuk.com:443` ?

**Comment by rtweed** [comment]
This is RHEL7.9 patched up-to-date - so old, but not ancient. :)

I think this may be a site-specific problem, rather than anything related to jackett itself. Running that openssl command against tvchaosuk.com, I get the following:

[asxa@ums]# openssl s_client -connect tvchaosuk.com:443
CONNECTED(00000003)
140166031533968:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 289 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1705089618
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

(note the 'no peer certificate available' - running this exact same command against a bunch of other various sites presents me with the certificate, exactly as I'd expect.

**Comment by garfield69** [comment]
Looks you may need to refresh/update your CA store. @ilike2burnthing  opinion/method?

**Comment by ilike2burnthing** [comment]
I've updated https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work-the-ssl-connection-could-not-be-established with instructions for updating OpenSSL and certificates, including a link specific for Red Hat (because they just have to be different 😛).

**Comment by rtweed** [comment]
Thanks both; figuring out to update the certs resolved this issue for me. 

Just FYI - the relevant command in RHEL7+ is 'update-ca-trust', not 'update-ca-certificates'. :)

**Comment by ilike2burnthing** [comment]
Glad you got it sorted.

> Just FYI - the relevant command in RHEL7+ is 'update-ca-trust', not 'update-ca-certificates'. :)

Yep, that's included in the wiki:

> [...] or for RHEL 6 and later follow the [instructions here](https://access.redhat.com/solutions/1549003).
