### ISSUE TITLE
[filelist] (updating) Service unavailable at the moment!

### ISSUE THREAD

**Issue by sergiu46** [Jackett/Jackett#14993]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Docker instalation on unraid,
```

### Description

Filelist.io was down for a day and after it came back jackett is not working anymore with this indexer.

### Logged Error Messages

```text
01-16 15:44:40 Error Jackett.Common.ExceptionWithConfigData: Service unavailable at the moment!

[v0.21.1553.0] Jackett.Common.ExceptionWithConfigData: Service unavailable at the moment!
   at Jackett.Common.Indexers.FileList.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/FileList.cs:line 149
   at Jackett.Common.Indexers.FileList.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/FileList.cs:line 122
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/38151078/87283532-dbee-44c1-bf15-a6aad3b47b70)

**Comment by paulierco** [comment]
I have the same problem.

**Comment by sergiu46** [comment]
Api was intentionally stopped. I read on the forum

**Comment by garfield69** [comment]
we will keep this open for 30 days, after which time, if the API is not made available again we will remove the indexer.
Please update when the API is available again. Thanks.

**Comment by tp0** [comment]
> Hi, The API System is down and will stay down for a while. We don't know yet when we will release it, we will probably announce something.

[From the Romanian-language forum](https://filelist.io/forums.php?action=viewtopic&topicid=120435&page=7).

**Comment by tp0** [comment]
The API is enabled again. Users need to fill the *Whitelist IP for API* on Filelist profile settings page for it to work. Temporary solution for now, apparently.

**Comment by garfield69** [comment]
I can add that info to the indexer config, but unless Jackett users edit the config in the first place they are not going to see the notice. But better than nothing. I'll update the indexer and close the ticket.

**Comment by Ionutovic** [comment]
How can I recover my fl account if I lost access to the email?

**Comment by ilike2burnthing** [comment]
This is not a support channel for the tracker (or any tracker). Use their IRC.
