### ISSUE TITLE
[1337x] (testing) Exception (1337x): Connection reset by peer: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by acorderob** [Jackett/Jackett#15014]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
This is on a Synology NAS.

Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /volume1/@appdata/jackett/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
Environment version: 6.0.26 (/volume1/@appstore/jackett/share/)
Starting Jackett v0.21.1594
```

### Description

The indexer cannot connect to the website. Doesn't look like an ISP block. Access to the site through browser works fine, and the domain is resolved to the same address in both the Synology and the PC. Certificate looks ok in the browser.

### Logged Error Messages

```text
2024-01-24 18:29:03	Debug	
Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2024-01-24 18:29:03	Debug	
Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)
2024-01-24 18:29:03	Debug	
Authorization was successful.
2024-01-24 18:29:03	Debug	
Execution plan of result filters (in the following order): None
2024-01-24 18:29:03	Debug	
Execution plan of exception filters (in the following order): None
2024-01-24 18:29:03	Debug	
Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
2024-01-24 18:29:03	Debug	
Execution plan of resource filters (in the following order): None
2024-01-24 18:29:03	Debug	
Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2024-01-24 18:29:03	Info	
Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (jackett).
2024-01-24 18:29:03	Info	
Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
2024-01-24 18:29:03	Debug	
Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'
2024-01-24 18:29:03	Debug	
Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'
2024-01-24 18:29:03	Debug	
1 candidate(s) found for the request path '/api/v2.0/server/logs'
2024-01-24 18:29:03	Debug	
AuthenticationScheme: Cookies was successfully authenticated.
2024-01-24 18:29:03	Debug	
The request path /api/v2.0/server/logs does not match a supported file type
2024-01-24 18:29:03	Debug	
Request is continuing in applying rules. Current url is http://192.168.0.13:9117/api/v2.0/server/logs?_=1706117329030
2024-01-24 18:29:03	Debug	
Request is continuing in applying rules. Current url is http://192.168.0.13:9117/api/v2.0/server/logs?_=1706117329030
2024-01-24 18:29:03	Debug	
Request is continuing in applying rules. Current url is http://192.168.0.13:9117/api/v2.0/server/logs?_=1706117329030
2024-01-24 18:29:03	Info	
Request starting HTTP/1.1 GET http://192.168.0.13:9117/api/v2.0/server/logs?_=1706117329030 - -
2024-01-24 18:28:53	Info	
Request finished HTTP/1.1 POST http://192.168.0.13:9117/api/v2.0/indexers/1337x/test - 0 - 500 - application/json 322.0787ms
2024-01-24 18:28:53	Debug	
Connection id "0HN0S79EUNGVA" completed keep alive response.
2024-01-24 18:28:53	Debug	
The response will be compressed with 'gzip'.
2024-01-24 18:28:53	Error	
Jackett.Common.IndexerException: Exception (1337x): Connection reset by peer

[v0.21.1594.0] Jackett.Common.IndexerException: Exception (1337x): Connection reset by peer
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 178
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 573
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1505
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 360
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 360
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 747
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 321
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2024-01-24 18:28:53	Info	
Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2024-01-24 18:28:53	Info	
Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 24.6124ms
2024-01-24 18:28:53	Debug	
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://1337x.to/cat/Movies/time/desc/1/)
2024-01-24 18:28:53	Debug	
CACHE IsCacheEnabled => false
2024-01-24 18:28:53	Debug	
Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2024-01-24 18:28:53	Debug	
Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2024-01-24 18:28:53	Debug	
Authorization was successful.
2024-01-24 18:28:53	Debug	
Execution plan of result filters (in the following order): None
2024-01-24 18:28:53	Debug	
Execution plan of exception filters (in the following order): None
2024-01-24 18:28:53	Debug	
Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2024-01-24 18:28:53	Debug	
Execution plan of resource filters (in the following order): None
2024-01-24 18:28:53	Debug	
Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2024-01-24 18:28:53	Info	
Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2024-01-24 18:28:53	Info	
Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2024-01-24 18:28:53	Debug	
Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2024-01-24 18:28:53	Debug	
Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/1337x/test'
2024-01-24 18:28:53	Debug	
1 candidate(s) found for the request path '/api/v2.0/indexers/1337x/test'
```

**Comment by acorderob** [comment]
More info: doing a verbose curl from the Synology:

```
$  curl -v https://1337x.to/
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to 1337x.to:443 
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to 1337x.to:443 
```

Seems to be a problem with TLSv1.3 ? Maybe a library compatibility?

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here:
- https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed
- https://github.com/Jackett/Jackett/wiki/TroubleShooting#connection-reset-by-peer-the-ssl-connection-could-not-be-established

You'll also need FlareSolverr installed and configured - https://github.com/Jackett/Jackett/wiki/Troubleshooting#challenge-detected-but-flaresolverr-is-not-configured (that might also require you switching from a native Jackett install to Docker)
