### ISSUE TITLE
[dreamtracker] (testing) Test search in Dream Tracker => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by acolis** [Jackett/Jackett#15025]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Environment version: 6.0.26 (/app/Jackett/)
2024-01-29 10:24:27.7123 Info OS version: Unix 5.10.0.0 (64bit OS) (64bit process)
2024-01-29 10:24:27.7123 Info Jackett variant: CoreLinuxAmdx64
2024-01-29 10:24:27.7123 Info File /etc/issue: Ubuntu 20.04.4 LTS \n \l
2024-01-29 10:24:27.7123 Info Running in Docker: Yes (image build: v0.20.2365-ls86)
2024-01-29 10:24:27.7123 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-01-29 10:24:27.7145 Info App config/log directory: /config/Jackett
2024-01-29 10:24:27.7145 Info Using proxy: Disabled
2024-01-29 10:24:27.7145 Info Using FlareSolverr: http://192.168.1.182:8191
2024-01-29 10:24:27.7145 Info Using HTTP Client: HttpWebClient2
```

### Description

Initiated a test on the tracker.
Attempted to paste the password again in the settings

### Logged Error Messages

```text
2024-01-29 10:34:52.4553 Info Test search in Dream Tracker => Found 0 releases [226ms]
2024-01-29 10:34:52.4553 Error System.Exception: Test search in Dream Tracker => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.21.1640.0] System.Exception: Test search in Dream Tracker => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 331
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 147
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Working ok here.

Have you followed the instruction for that indexer? If not, do so.

> 1. Only the English Classic profile is supported.
> 2. Make sure to set the **Torrent Listing** option in your profile to **Classic**
> 3. And set the **Language** to **English**
> 4. Using the _Modern_ theme will prevent results, and using _Greek_ will prevent upload dates.

Do you have `Filter freeleech only` enabled? If so, disable it.

**Comment by acolis** [comment]
![image](https://github.com/Jackett/Jackett/assets/43079252/3dd79089-4bbd-419e-b97c-c2a0046a698c)
![image](https://github.com/Jackett/Jackett/assets/43079252/ee57f933-e4d5-4cd0-94d2-52cabc564ab3)

**Comment by acolis** [comment]
Test success now. can be closed. will keep watch for changes
