### ISSUE TITLE
[scenetime] (updating) Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

### ISSUE THREAD

**Issue by coolsudheera** [Jackett/Jackett#15020]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-01-27 14:51:24	Info	
Jackett startup finished in 4.249 s
2024-01-27 14:51:23	Info	
Deleting JackettUpdate temp files from C:\WINDOWS\TEMP\JackettUpdate-v0.21.1635-638419638615099746
2024-01-27 14:51:23	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2024-01-27 14:51:23	Info	
Adding filter indexer ('type:private' indexer) ...
2024-01-27 14:51:23	Info	
Adding filter indexer ('type:public' indexer) ...
2024-01-27 14:51:23	Info	
Adding aggregate indexer ('all' indexer) ...
2024-01-27 14:51:23	Info	
Loaded 609 indexers in total
2024-01-27 14:51:23	Info	
Loaded 536 Cardigann indexers.
2024-01-27 14:51:22	Info	
Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, C:\ProgramData\Jackett\Definitions
2024-01-27 14:51:22	Info	
Loaded 73 Native indexers.
2024-01-27 14:51:22	Info	
Loading Native indexers ...
2024-01-27 14:51:22	Info	
Using HTTP Client: HttpWebClient2
2024-01-27 14:51:22	Info	
Using FlareSolverr: http://192.xxx.x.xx:8191
2024-01-27 14:51:22	Info	
Using proxy: Disabled
2024-01-27 14:51:22	Info	
App config/log directory: C:\ProgramData\Jackett
2024-01-27 14:51:22	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-01-27 14:51:22	Info	
Running in Docker: No
2024-01-27 14:51:22	Info	
Jackett variant: CoreWindows
2024-01-27 14:51:22	Info	
OS version: Microsoft Windows NT 10.0.22631.0 (64bit OS)
2024-01-27 14:51:22	Info	
Environment version: 6.0.26 (C:\ProgramData\Jackett\)
2024-01-27 14:51:20	Info	
Starting Jackett v0.21.1635
```

### Description

Please kindly add an easy way to integrate https://www.scenetime.com. Current cookie method gives an error. Hope this gets fixed in future releases.

### Logged Error Messages

```text
2024-01-27 14:52:09	Error	
System.Exception: Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

[v0.21.1635.0] System.Exception: Your cookie did not work: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
   at Jackett.Common.Indexers.SceneTime.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/SceneTime.cs:line 118
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Delete indexer, restart Jackett, re-add with new cookie & UA - https://github.com/Jackett/Jackett/issues/14831
