### ISSUE TITLE
[hdspace] (updating) Unknown error message, please report.

### ISSUE THREAD

**Issue by wazerstar** [Jackett/Jackett#15023]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.22631.0 (64bit OS)
Environment version: 6.0.26 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.1638
```

### Description

Clean installation of jackett windows 64bit, cannot import hd-space gives unknown error with flaresolverr latest version from january 2024

### Logged Error Messages

```text
screenshot attached
```

### Screenshots

[https://i.imgur.com/2sPn1vK.png](url)

**Comment by garfield69** [comment]
Me too, on my win10 Jackett 0.21.1638
enhanced log fetched from dashboard view
```
Jackett.Common.ExceptionWithConfigData: Unknown error message, please report.  [v0.21.1638.0] Jackett.Common.ExceptionWithConfigData: Unknown error message, please report.    at Jackett.Common.Indexers.HDSpace.<>c__DisplayClass24_0.<ApplyConfiguration>b__0() in ./Jackett.Common/Indexers/HDSpace.cs:line 121    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 161    at Jackett.Common.Indexers.HDSpace.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/HDSpace.cs:line 111    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
--
2024-01-29 06:11:53 | Info | Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole)'
2024-01-29 06:11:53 | Info | Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) in 14104.2718ms
2024-01-29 06:11:53 | Debug | WebClient(HttpWebClient2): Returning OK => 7758 bytes <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head>   <title>HD-Space - Sharing The Universe .::. Index</title>             <link rel="stylesheet" href="https://hd-space.org/style/xbtit_default/main.css" type="text/css" />      <link rel="stylesheet" type="text/css"  /><link rel="stylesheet" href="https://hd-space.org/style/xbtit_default/menu.css" type="text/css" />            	<!--[if lt IE 7.]> 	<script defer type="text/javascript" src="https://hd-space.org/jscript/pngfix.js"></script> 	<![endif]--> 	<script type="text/javascript" src="https://hd-space.org/jscript/ajax.js"></script>  	<script type="text/javascript" src="https://hd-space.org/jscript/xbtit.js"></script>     <script type="text/javascript" src="https://hd-space.org/jscript/jquery-3.2.1.min.js"></script>     <script type="text/javascript" src="https://hd-space.org/jscript/freeInvitations.js"></script> 	<script type="text/javascript" src="https://hd-space.org/js/jquery.js"></script>         <script type="text/javascript" src="https://hd-space.org/js/menu.js"></script>   <script type="text/javascript" src="js/jquery.js"></script> <script type="text/javascript" src="js/menu.js"></script> <script type="text/javascript" src="./jscript/overlib.js"></script>   </head> <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div> <body>    <div align="center"> <table width='100%' cellspacing='0' style='background: transperant; border: 3px;'>   <tr>     <td align='center'> <table width='900px' cellspacing='2' style='background: #212121; border: 3px solid #141414;'>   <tr>      <td  align='center'>  <table width='100%' cellspacing='0' style='background: transperant; border:none;'>   <tr>     <td align='center'> <table width='900px' cellspacing='2' style='background: #212121; border: 3px solid #141414;'>   <tr>      <td  align='center'>  <table class=new  width="100%" height="250px"  border="0"> <td  height="100" colspan="2">     <table width=100%> 	<td align=center><FORM action="index.php?page=donpage" method="post">  <tr><input type="image" src="images/donatenew.png" align=right border="0" title="PayPal - The safer, easier way to pay online!"></tr>    </form></td></table>  <br><br><br><br><br><br>          <table width="100%" cellpadding="0" cellspacing="6" border="0">         <tr>         <td valign="top"><div><br />  <table class="lista" cellpadding="0" cellspacing="0" width="100%" align="center">   <tr>     <td class="blockheader" align="center" height="20px"><b></b></td>   </tr>   <tr>     <td width="100%" align="justify" valign="top">         <form action="index.php?page=login" name="login" method="post">     <table class="lista" border="0" width="100%" cellpadding="4" cellspacing="1">     <tr>     <td class="lista" align="left">       <table border="0" cellpadding="0" cellspacing="0">       <tr>       <td align="right" class="lista">User:</td>       <td class="lista"><input type="text" size="15" name="uid" id="want_username1" value="" maxlength="40" style="font-size:10px" /></td>       <td align="right" class="lista">Password:</td>       <td class="lista"><input type="password" size="15" name="pwd" id="want_password1" maxlength="40" style="font-size:10px" /></td>       <td align="right" class="lista">Automatic log off after 15 minutes inactivity<input type=checkbox name=logout value='yes'></td>       <td class="lista" align="center"><input type="submit" value="Login" style="font-size:10px" /></td>       </tr>       </table>     </td>     <td class="lista" align="center"><a href="index.php?page=signup">Create account</a></td>     <td class="lista" align="center"><a href="index.php?page=recover">Recover password</a></td>     </tr>     </table>     </form> <style type="text/css"> .mail {       -moz-box-shadow: 0px 10px 14px -7px #3e7327; 	-webkit-box-shadow: 0px 10px 14px -7px #3e7327; 	box-shadow: 0px 10px 14px -7px #3e7327; 	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #77b55a), color-stop(1, #72b352)); 	background:-moz-linear-gradient(top, #77b55a 5%, #72b352 100%); 	background:-webkit-linear-gradient(top, #77b55a 5%, #72b352 100%); 	background:-o-linear-gradient(top, #77b55a 5%, #72b352 100%); 	background:-ms-linear-gradient(top, #77b55a 5%, #72b352 100%); 	background:linear-gradient(to bottom, #77b55a 5%, #72b352 100%); 	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77b55a', endColorstr='#72b352',GradientType=0); 	background-color:#77b55a; 	-moz-border-radius:4px; 	-webkit-border-radius:4px; 	border-radius:4px; 	border:1px solid #4b8f29; 	display:inline-block; 	cursor:pointer; 	color:#000000; 	font-family:Arial; 	font-size:14px; 	font-weight:bold; 	padding:5px 12px; 	text-decoration:none; 	text-shadow:0px 1px 0px #5b8a3c; } </style>      </td>   </tr> </table></div></td> 		         </tr>         </div> 		          <td class="lista" width="100%">     <script type="text/javascript">     //Syntax: var uniquevar=new animatedcollapse("DIV_id", animatetime_milisec, enablepersist(true/fase), [initialstate] )     var collapse2=new animatedcollapse("header", 800, false, "block")     </script>     <div id="bodyarea">       <table border="0" align="center" cellpadding="0" cellspacing="0" width="100%">       <tr>         <td valign="top" width="5" rowspan="2"></td>         <td valign="top"><br />  <table class="lista" cellpadding="0" cellspacing="0" width="100%" align="center">   <tr>     <td class="block" align="center" height="20px"><b></b></td>   </tr>   <tr>     <td width="100%" align="justify" valign="top">      <marquee onmouseover=this.stop() onmouseout=this.start() scrollAmount=1.5 direction=up width='100%' height='80'><br><br> <center> <b><br> None of the files shown here are actually hosted on this server.The links are provided solely by this site's users.<br>The WebMaster/administrator of this site <font color=red>HD-Space</font> cannot be held responsible for what its users post,or any other actions of its users. </b><br><br> ============================================================================================================<br> <br> MPAA & RIAA Please Note:- <br><i>AT NO TIME DOES ANY COPYRIGHTED MATERIAL ENTER OR GET TRANSFERED VIA <font color=red>HD-Space</font> WebSite..</i><br> <br>   </marquee>    <div align="center"></div> <div align="center"></div>       </td>   </tr> </table></td>         <td valign="top" width="5" rowspan="2"></td>       </tr>     </table>       <br />       <table width="100%" cellpadding="0" cellspacing="0" border="0">         <tr>           <td valign="top" width="5" rowspan="2"></td>           <td valign="top"><br /> </td>           <td valign="top" width="5" rowspan="2"></td>         </tr> 			</table>     </div>         </div> 		          </td>       </tr> 	   	  <table width="100%" height="32" border="0" cellspacing="0" cellpadding="0"><tr> <td class="f_left"></td> <td class="f_middle" style="text-align:center;"> <span valign="bottom" class="nav"><br>If you find any information that is in violation to a privacy law please report to <u><a href="mailto:hdspace.support@proton.me">hdspace.support@proton.me</a></u> ! </span></td>  	    <table width="100%" height="35" border="0" cellspacing="0" cellpadding="0"><tr> <td class="f_left"></td> <td class="f_left" style="text-align:center;"> <script  type="text/javascript"> </script><td class="f_right" align='right'> <font color="#6c6c6c" size="2" face="tahoma"><i>Style: HD-Space v.2.5</i></font>       </table>  </td>            </table>  </td> </td>      </td> </td>      </tr>   </div> </div> </body> </html>
2024-01-29 06:11:53 | Debug | cf_clearance=g.fIQyot_lJQ6wafaB5kton0z692133eEEQ67cKwjv4-1706461907-1-Aaa7r4mI175gyX9tiMKALWht0rrIoPiF/TXicUZnenfv5iNVhK4S59vOJwrsIhLZKkvl+MOGWJAowrKWKReJpRk=
2024-01-29 06:11:53 | Debug | PHPSESSID=3go5grni0tlii0g05jiigk6un6
2024-01-29 06:11:53 | Debug | PHPSESSID=jrtug2bhtua4eptp4v0pdlm9s6; path=/
2024-01-29 06:11:46 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://hd-space.org/index.php)
2024-01-29 06:11:46 | Debug | WebClient(HttpWebClient2): Returning Redirect => https://hd-space.org/index.php 0 bytes
2024-01-29 06:11:46 | Debug | pass=7e44dca2d423e6a9ec26551a68da2c6c; expires=Tue, 19-Jan-2038 03:14:07 GMT; Max-Age=441021741; path=/
2024-01-29 06:11:46 | Debug | uid=207528; expires=Tue, 19-Jan-2038 03:14:07 GMT; Max-Age=441021741; path=/
2024-01-29 06:11:45 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://hd-space.org/index.php?page=login PostData: {uid=garfield1969, pwd=(removed) RawBody: )
2024-01-29 06:11:45 | Debug | updating Cookies  => PHPSESSID=5qj9tgkp198hqep4ae8umfndj5; cf_clearance=dWBle.ePd44Owy1TW6VIo1DkyBXgwVIf6vUFBEEbNx0-1706461900-1-ATwRErvCLUh5PZY/2ySvaKWt6z0M4SEX1T5kx/evnAGEP0avzumUQhyvBrvrArPylcyN5STSgtAL12l8vvbIYo4=
2024-01-29 06:11:45 | Debug | WebClient(HttpWebClient2): Returning OK => 9116 bytes <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head>   <title>HD-Space - Sharing The Universe .::. Index->Login</title>          <meta http-equiv="content-type" content="text/html; charset=UTF-8" />   <link rel="stylesheet" href="https://hd-space.org/style/xbtit_default/main.css" type="text/css" />      <link rel="stylesheet" type="text/css"  /><link rel="stylesheet" href="https://hd-space.org/style/xbtit_default/menu.css" type="text/css" />            	<!--[if lt IE 7.]> 	<script defer type="text/javascript" src="https://hd-space.org/jscript/pngfix.js"></script> 	<![endif]--> 	<script type="text/javascript" src="https://hd-space.org/jscript/ajax.js"></script>  	<script type="text/javascript" src="https://hd-space.org/jscript/xbtit.js"></script>     <script type="text/javascript" src="https://hd-space.org/jscript/jquery-3.2.1.min.js"></script>     <script type="text/javascript" src="https://hd-space.org/jscript/freeInvitations.js"></script> 	<script type="text/javascript" src="https://hd-space.org/js/jquery.js"></script>         <script type="text/javascript" src="https://hd-space.org/js/menu.js"></script>   <script type="text/javascript" src="js/jquery.js"></script> <script type="text/javascript" src="js/menu.js"></script> <script type="text/javascript" src="./jscript/overlib.js"></script>   </head> <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div> <body>    <div align="center"> <table width='100%' cellspacing='0' style='background: transperant; border: 3px;'>   <tr>     <td align='center'> <table width='900px' cellspacing='2' style='background: #212121; border: 3px solid #141414;'>   <tr>      <td  align='center'>  <table width='100%' cellspacing='0' style='background: transperant; border:none;'>   <tr>     <td align='center'> <table width='900px' cellspacing='2' style='background: #212121; border: 3px solid #141414;'>   <tr>      <td  align='center'>  <table class=new  width="100%" height="250px"  border="0"> <td  height="100" colspan="2">     <table width=100%> 	<td align=center><FORM action="index.php?page=donpage" method="post">  <tr><input type="image" src="images/donatenew.png" align=right border="0" title="PayPal - The safer, easier way to pay online!"></tr>    </form></td></table>  <br><br><br><br><br><br>          <table width="100%" cellpadding="0" cellspacing="6" border="0">         <tr>         <td valign="top"><div><br />  <table class="lista" cellpadding="0" cellspacing="0" width="100%" align="center">   <tr>     <td class="blockheader" align="center" height="20px"><b></b></td>   </tr>   <tr>     <td width="100%" align="justify" valign="top">         <form action="index.php?page=login" name="login" method="post">     <table class="lista" border="0" width="100%" cellpadding="4" cellspacing="1">     <tr>     <td class="lista" align="left">       <table border="0" cellpadding="0" cellspacing="0">       <tr>       <td align="right" class="lista">User:</td>       <td class="lista"><input type="text" size="15" name="uid" id="want_username1" value="" maxlength="40" style="font-size:10px" /></td>       <td align="right" class="lista">Password:</td>       <td class="lista"><input type="password" size="15" name="pwd" id="want_password1" maxlength="40" style="font-size:10px" /></td>       <td align="right" class="lista">Automatic log off after 15 minutes inactivity<input type=checkbox name=logout value='yes'></td>       <td class="lista" align="center"><input type="submit" value="Login" style="font-size:10px" /></td>       </tr>       </table>     </td>     <td class="lista" align="center"><a href="index.php?page=signup">Create account</a></td>     <td class="lista" align="center"><a href="index.php?page=recover">Recover password</a></td>     </tr>     </table>     </form> <style type="text/css"> .mail {       -moz-box-shadow: 0px 10px 14px -7px #3e7327; 	-webkit-box-shadow: 0px 10px 14px -7px #3e7327; 	box-shadow: 0px 10px 14px -7px #3e7327; 	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #77b55a), color-stop(1, #72b352)); 	background:-moz-linear-gradient(top, #77b55a 5%, #72b352 100%); 	background:-webkit-linear-gradient(top, #77b55a 5%, #72b352 100%); 	background:-o-linear-gradient(top, #77b55a 5%, #72b352 100%); 	background:-ms-linear-gradient(top, #77b55a 5%, #72b352 100%); 	background:linear-gradient(to bottom, #77b55a 5%, #72b352 100%); 	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77b55a', endColorstr='#72b352',GradientType=0); 	background-color:#77b55a; 	-moz-border-radius:4px; 	-webkit-border-radius:4px; 	border-radius:4px; 	border:1px solid #4b8f29; 	display:inline-block; 	cursor:pointer; 	color:#000000; 	font-family:Arial; 	font-size:14px; 	font-weight:bold; 	padding:5px 12px; 	text-decoration:none; 	text-shadow:0px 1px 0px #5b8a3c; } </style>      </td>   </tr> </table></div></td> 		         </tr>         </div> 		          <td class="lista" width="100%">     <script type="text/javascript">     //Syntax: var uniquevar=new animatedcollapse("DIV_id", animatetime_milisec, enablepersist(true/fase), [initialstate] )     var collapse2=new animatedcollapse("header", 800, false, "block")     </script>     <div id="bodyarea">       <table border="0" align="center" cellpadding="0" cellspacing="0" width="100%">       <tr>         <td valign="top" width="5" rowspan="2"></td>         <td valign="top"><br />  <table class="lista" cellpadding="0" cellspacing="0" width="100%" align="center">   <tr>     <td class="block" align="center" height="20px"><b>Login</b></td>   </tr>   <tr>     <td width="100%" align="center" valign="top">             <script type="text/javascript" src="/jscript/animatedcollapse.js"></script> <script type="text/javascript"> function form_control()   {     if (document.getElementById('want_username').value.length==0)       {       var want_username=(removed);       want_username.innerHTML='You must insert a username!';       alert(want_username.innerHTML);       document.getElementById('want_username').focus();       return false;       }      if (document.getElementById('want_password').value == "")       {       var want_password=(removed);       want_password.innerHTML='You must insert a password!';       alert(want_password.innerHTML);       document.getElementById('want_password').focus();       return false;       }     return true;   } </script> <form method="post" onsubmit="return form_control()" action="index.php?page=login&amp;returnto=index.php">   <tag:count />   <tr><td colspan="2"  class="header" align="center">You have <span style="color:#FF6666">10</span> remaining login attempts.</td></tr>  <table align="center" class="lista" border="0" cellpadding="10">           	                <tr>       <td align="right" class="header">User:</td>       <td class="lista"><input type="text" size="40" name="uid" id="want_username" value="" maxlength="40" /></td>     </tr>     <tr>       <td align="right" class="header">Password:</td>       <td class="lista"><input type="password" size="40" name="pwd" id="want_password" maxlength="40" /></td>     </tr>        <tr>         <td align="right" class="header"></td>         <td class="lista"><input type="checkbox" name="logout" value="yes" />Automatic log off after 15 minutes inactivity</td>     </tr>     <tr>       <td colspan="2" class="header" align="center"><input type="submit" class="btn" value="Confirm" /></td>     </tr>     <tr>       <td colspan="2" class="header" align="center">Note: You need cookies enabled to log in.</td>     </tr>   </table> </form> <p align="center">   <a href="index.php?page=signup">Create account</a>&nbsp;&nbsp;&nbsp;<a href="index.php?page=recover">Recover password</a> </p>      </td>   </tr> </table></td>         <td valign="top" width="5" rowspan="2"></td>       </tr>     </table>       <br />       <table width="100%" cellpadding="0" cellspacing="0" border="0">         <tr>           <td valign="top" width="5" rowspan="2"></td>           <td valign="top"><br /> </td>           <td valign="top" width="5" rowspan="2"></td>         </tr> 			</table>     </div>         </div> 		          </td>       </tr> 	   	  <table width="100%" height="32" border="0" cellspacing="0" cellpadding="0"><tr> <td class="f_left"></td> <td class="f_middle" style="text-align:center;"> <span valign="bottom" class="nav"><br>If you find any information that is in violation to a privacy law please report to <u><a href="mailto:hdspace.support@proton.me">hdspace.support@proton.me</a></u> ! </span></td>  	    <table width="100%" height="35" border="0" cellspacing="0" cellpadding="0"><tr> <td class="f_left"></td> <td class="f_left" style="text-align:center;"> <script  type="text/javascript"> </script><td class="f_right" align='right'> <font color="#6c6c6c" size="2" face="tahoma"><i>Style: HD-Space v.2.5</i></font>       </table>  </td>            </table>  </td> </td>      </td> </td>      </tr>   </div> </div> </body> </html>
2024-01-29 06:11:45 | Debug | cf_clearance=dWBle.ePd44Owy1TW6VIo1DkyBXgwVIf6vUFBEEbNx0-1706461900-1-ATwRErvCLUh5PZY/2ySvaKWt6z0M4SEX1T5kx/evnAGEP0avzumUQhyvBrvrArPylcyN5STSgtAL12l8vvbIYo4=
2024-01-29 06:11:45 | Debug | PHPSESSID=5qj9tgkp198hqep4ae8umfndj5
2024-01-29 06:11:45 | Debug | PHPSESSID=oguf0egj7lojn9u98m5jelvhg6; path=/
2024-01-29 06:11:39 | Debug | WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://hd-space.org/index.php?page=login)
```

**Comment by garfield69** [comment]
I get the same issue using ubuntu jackett 0.21.1640 so its not specific to win10

**Comment by garfield69** [comment]
Well in that case we will put hdspace on the 30day notice and if they haven't reverted back to a more relaxed state by then we shall delete the indexer.

**Comment by ilike2burnthing** [comment]
I'm not having any issues in browser, but yes I'm seeing this in Jackett. The `cf_clearance` cookie shows a 1 year expiry, so may be worthwhile to change to cookie login if that holds out to be true (I'll check back in a few days to see if I get another challenge).

**Comment by wazerstar** [comment]
> Should we try switching the hdspace indexer to a cookie login method then?

I have never had an issue with hd-space before been using the same login/cookie for a couple of years, this is the first time this is happening, can we have both methods as an switch in the settings?

**Comment by ilike2burnthing** [comment]
Presumably some additional security setting has been enabled and is causing issues now.

We'll just wait a few days and see if the cookie is still valid. If so, we can switch to cookie login. No point in doing so if the user would need to constantly update their cookie though.

As for supporting both cookie and credentials login, something similar was suggested here for Cardigann indexers - https://github.com/Jackett/Jackett/issues/7780.

**Comment by garfield69** [comment]
My hdspace indexer worked just now after failing only 20 seconds earlier %-/
BTW I also have had no issues with using the browser to access the site, only with Jackett yesterday.

**Comment by ilike2burnthing** [comment]
Checked earlier, got another Cloudflare challenge. Just checked again, same browser session, got another challenge. Switching to cookies won't help.

**Comment by Stapper** [comment]
Running Jackett  v0.21.1650 on Debian=>

flaresolverr log states the challange is solved, but I'm still receiving the error

`Jan 31 11:33:59 scrapeserver flaresolverr[2191445]: 2024-01-31 11:33:59 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://hd-space.org/index.php?page=login'}
Jan 31 11:34:01 scrapeserver flaresolverr[2191445]: 2024-01-31 11:34:01 INFO     Challenge detected. Title found: Just a moment...
Jan 31 11:34:05 scrapeserver flaresolverr[2191445]: 2024-01-31 11:34:05 INFO     Challenge solved!
Jan 31 11:34:05 scrapeserver flaresolverr[2191445]: 2024-01-31 11:34:05 INFO     Response in 5.178 s
Jan 31 11:34:05 scrapeserver flaresolverr[2191445]: 2024-01-31 11:34:05 INFO     192.168.1.103 POST http://192.168.1.103:8191/v1 200 OK
Jan 31 11:34:05 scrapeserver flaresolverr[2191445]: 2024-01-31 11:34:05 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://hd-space.org/index.php'}
Jan 31 11:34:07 scrapeserver flaresolverr[2191445]: 2024-01-31 11:34:07 INFO     Challenge detected. Title found: Just a moment...
Jan 31 11:34:11 scrapeserver flaresolverr[2191445]: 2024-01-31 11:34:11 INFO     Challenge solved!
Jan 31 11:34:11 scrapeserver flaresolverr[2191445]: 2024-01-31 11:34:11 INFO     Response in 5.441 s
Jan 31 11:34:11 scrapeserver flaresolverr[2191445]: 2024-01-31 11:34:11 INFO     192.168.1.103 POST http://192.168.1.103:8191/v1 200 OK
`

Jackett  v0.21.1650 is showing this error in log:
`Jan 31 11:37:20 scrapeserver jackett[2192070]: 01-31 11:37:20 Error Jackett.Common.ExceptionWithConfigData: Unknown error message, please report.
Jan 31 11:37:20 scrapeserver jackett[2192070]: [v0.21.1650.0] Jackett.Common.ExceptionWithConfigData: Unknown error message, please report.
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Jackett.Common.Indexers.HDSpace.<>c__DisplayClass24_0.<ApplyConfiguration>b__0() in ./Jackett.Common/Indexers/HDSpace.cs:line 121
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 161
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Jackett.Common.Indexers.HDSpace.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/HDSpace.cs:line 111
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
Jan 31 11:37:20 scrapeserver jackett[2192070]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
`

**Comment by ilike2burnthing** [comment]
Essentially the cookie returned by FlareSolverr is considered valid by it, but is not sufficient to actually log into the site, and I don't know why. As nothing has changed about the login page (that I can see), I can only conclude it's an issue with their Cloudflare protection.

I'll take a look at this later when I'm free, but I'm not holding my breath.

**Comment by garfield69** [comment]
>Is is normal for FlareSolverrSharp to ditch the querystring? 

I see two urls
```
2024-01-31 06:47:54 INFO     Incoming request => POST /v1 body: {'maxTimeout': 70000, 'cmd': 'request.get', 'url': 'https://hd-space.org/index.php?page=login'}
2024-01-31 06:47:55 INFO     Challenge detected. Title found: Just a moment...
2024-01-31 06:47:59 INFO     Challenge solved!
2024-01-31 06:48:00 INFO     Response in 5.704 s
2024-01-31 06:48:00 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK
2024-01-31 06:48:02 INFO     Incoming request => POST /v1 body: {'maxTimeout': 70000, 'cmd': 'request.get', 'url': 'https://hd-space.org/index.php'}
2024-01-31 06:48:03 INFO     Challenge detected. Title found: Just a moment...
2024-01-31 06:48:07 INFO     Challenge solved!
2024-01-31 06:48:08 INFO     Response in 6.015 s
2024-01-31 06:48:08 INFO     127.0.0.1 POST http://127.0.0.1:8191/v1 200 OK
```
the first is the fetch for the login page
the second is the follow redirect check for the presence of the logout.php link (part of await configifok)

**Comment by ilike2burnthing** [comment]
Login works fine when using the following in a YAML indexer:

```yml
login:
  path: index.php?page=login
  method: post
  inputs:
    uid: "{{ .Config.username }}"
    pwd: "{{ .Config.password }}"
  test:
    path: index.php
    selector: a[href="logout.php"]
```

I'm assuming then that there's an issue with the indexer. Is there something stopping this being rewritten in YAML?

**Comment by garfield69** [comment]
hsspace is using xbtit for which we have quite a few indexers, so I'll have a go coding a yaml and see if I get stuck anyplace.

**Comment by garfield69** [comment]
Converted C# to yaml. 
Still end up with two calls to flaresolverr, first for the torrent page, then for the relogin.
but it works so \o/

**Comment by garfield69** [comment]
v0.21.1672

**Comment by wazerstar** [comment]
> v0.21.1672


Works beautiful, thanks for doing all of this work. Much appreciated, I guess ticket can be closed if its not already :)
