### ISSUE TITLE
[finelite] (testing) Test search in FinElite => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by greeningmarbles** [Jackett/Jackett#15040]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-02-07 14:00:40 	Info 	Using HTTP Client: HttpWebClient2
2024-02-07 14:00:40 	Info 	Using FlareSolverr: No
2024-02-07 14:00:40 	Info 	Using proxy: Disabled
2024-02-07 14:00:40 	Info 	App config/log directory: /config/Jackett
2024-02-07 14:00:40 	Info 	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-02-07 14:00:40 	Info 	Running in Docker: Yes (image build: v0.21.1664-ls294)
2024-02-07 14:00:40 	Info 	File /etc/issue: Welcome to Alpine Linux 3.18
2024-02-07 14:00:40 	Info 	Jackett variant: CoreLinuxMuslAmdx64
2024-02-07 14:00:40 	Info 	OS version: Unix 5.15.0.76 (64bit OS) (64bit process)
2024-02-07 14:00:40 	Info 	Environment version: 6.0.26 (/app/Jackett/)
2024-02-07 14:00:38 	Info 	Starting Jackett v0.21.1693
```

### Description

Ain't working, getting error  "An error occurred while testing this indexer
Test search in FinElite => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc."

Any ideas?

### Logged Error Messages

```text
System.Exception: Test search in FinElite => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.21.1693.0] System.Exception: Test search in FinElite => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 330
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
If you've reconfigured the indexer, ensuring that `Search freeleech only` is disabled, you can access the tracker's search page without an alert about unread messages, low ratio, or maintenance work being done, and you're still getting this error, then please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by peisi2** [comment]
Same problem here. I can access site whit a browser and everything is ok my account.

**Comment by garfield69** [comment]
cant help without https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by peisi2** [comment]
> cant help without https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

[log.txt](https://github.com/Jackett/Jackett/files/14228732/log.txt)

Here it is, hope it helps

**Comment by garfield69** [comment]
Yes, its very useful. It shows that finelite have changed their search results layout and we need to update the indexer for the new selectors.

**Comment by garfield69** [comment]
The updated indexer will be available in the next release of Jackett, due out in about 20 hours.

**Comment by peisi2** [comment]
Thanks. :)

**Comment by garfield69** [comment]
v0.21.1730

**Comment by greeningmarbles** [comment]
Hiya! Finelite made changes on background last Saturday and Jackett is not working anymore (**Exception (finelite): Login failed: Selector "a[href="ulos.php"]" didn't match: Parse error**). Want to check this or should I open new issue?

They've changed something + added Cloudfare (I've set this automatical with help of trackers staff)

**Comment by garfield69** [comment]
The login page has an embedded cloudflare check, so the indexer cannot use the login method anymore.
I will switch to a cookie method and you can test it out with the next release of Jackett due in about 10 hours or so.
None of the team have an account for this site so we cannot properly research/test this indexer.
If you have an invite please send the invite to `jacketttest [at] gmail [dot] com`

**Comment by greeningmarbles** [comment]
Sorry, no invites ;(

Actually I have ten of those but they've seemed to be disabled since the only one I used, person I knew was just hit & run person. That's why this was taken away from me. Will ask the staff if they can provide authorization back to me.

But hey, thanks for checking!!

**Comment by garfield69** [comment]
v0.21.2508

**Comment by greeningmarbles** [comment]
Thanks, got the update and inserted cookie as instructed. Getting error thought,

An error occurred while updating this indexer
Login failed: Selector "a[href="ulos.php"]" didn't match

**Comment by everglade8227** [comment]
> Thanks, got the update and inserted cookie as instructed. Getting error thought,
> 
> An error occurred while updating this indexer Login failed: Selector "a[href="ulos.php"]" didn't match

Naming convention has changed, it should be updated to "logout.php"

**Comment by ilike2burnthing** [comment]
I've received an invite (thank you FinElite admin). Just waiting for the account to be activated and then I'll take a look if anything else needs updated while we're at it.

**Comment by garfield69** [comment]
v0.21.2526

**Comment by greeningmarbles** [comment]
Thanks, but still an error.

 An error occurred while updating this indexer
Login failed: Selector "a[href="/logout.php"]" didn't match

**Comment by ilike2burnthing** [comment]
Working ok here, using a Windows cookie in Docker Jackett, so it's not a UA issue. Follow the steps here - https://github.com/Jackett/Jackett/issues/15040#issuecomment-2085272864.

**Comment by lepis0** [comment]
I got this work with dockered Firefox PHPSESSID.

**Comment by garfield69** [comment]
\o/

**Comment by msrn** [comment]
> Thanks, but still an error.
> 
> An error occurred while updating this indexer Login failed: Selector "a[href="/logout.php"]" didn't match

I'm still experiencing this error after adding the cookie.

`Version v0.21.2536`

**Comment by garfield69** [comment]
@msrn insufficient info to provide any relevant help. Please raise a fresh ticket and fill in the requested info on the form.
