### ISSUE TITLE
Error adding DivxTotal indexer

### ISSUE THREAD

**Issue by pbedmar** [Jackett/Jackett#15059]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett is running on Docker container. Other indexers work, so it shouldn't be an infrastructure problem.
```

### Description

This is the error I obtain:

[divxtotal] (configuring) Could not find releases from this URL

Notice that if I click on the frontend URL, I can access it.

### Logged Error Messages

```text
2024-02-16 20:09:53	Error	
System.Exception: Could not find releases from this URL

[v0.21.1650.0] System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.DivxTotal.<>c.<ApplyConfiguration>b__25_0() in ./Jackett.Common/Indexers/DivxTotal.cs:line 124
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 161
   at Jackett.Common.Indexers.DivxTotal.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/DivxTotal.cs:line 123
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2024-02-16 20:09:53	Error	
DivxTotal: Failed to load url [https://www2.divxtotal.mov/page/1/?s=]: 

[v0.21.1650.0] Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.DivxTotal.LoadWebPageAsync(String url) in ./Jackett.Common/Indexers/DivxTotal.cs:line 203
   at Jackett.Common.Indexers.DivxTotal.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/DivxTotal.cs:line 151
```

**Comment by garfield69** [comment]
your jackett is out of date. turn off your dashboard disable-auto-update and/or use the check-for-updates button
the new domain for divxtotal is `https://www3.divxtotal.mov/`
