### ISSUE TITLE
[torrentdd] (updating) Error: Login failed!คุณกรอก รหัสผ่าน ไม่ถูกต้อง<< ย้อนกลับ

### ISSUE THREAD

**Issue by vio771** [Jackett/Jackett#15068]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-02-19 05:09:52	Info	Using HTTP Client: HttpWebClient2
2024-02-19 05:09:52	Info	Using FlareSolverr: http://192.168.178.35:8191
2024-02-19 05:09:52	Info	Using proxy: Disabled
2024-02-19 05:09:52	Info	App config/log directory: /config/Jackett
2024-02-19 05:09:52	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-02-19 05:09:52	Info	Running in Docker: Yes (image build: v0.21.1701-ls300)
2024-02-19 05:09:52	Info	File /etc/issue: Welcome to Alpine Linux 3.18
2024-02-19 05:09:52	Info	Jackett variant: CoreLinuxMuslAmdx64
2024-02-19 05:09:52	Info	OS version: Unix 6.1.64.0 (64bit OS) (64bit process)
2024-02-19 05:09:52	Info	Environment version: 6.0.27 (/app/Jackett/)
2024-02-19 05:09:50	Info	Starting Jackett v0.21.1781
```

### Description

can't login with jackett, site has opensignup atm.

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Error: Login failed!คุณกรอก รหัสผ่าน ไม่ถูกต้อง<< ย้อนกลับ

[v0.21.1781.0] Jackett.Common.ExceptionWithConfigData: Error: Login failed!คุณกรอก รหัสผ่าน ไม่ถูกต้อง<< ย้อนกลับ
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 542
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 579
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![Untitled](https://github.com/Jackett/Jackett/assets/83228452/376b7f89-4323-4b55-a9d4-9ec49128e1e3)

**Comment by garfield69** [comment]
the indexer is working for me so the problem is likely at your end.
did you recently change your password on torrentdd?
IF so, try logging our of torrentdd web site before using the jackett dashbaord edit config and saving the password and save, as some sites may not refresh their login cache until you have logged out of the website.
Otherwise, the other likely cause is that your password is not being handled by the encryptor properly.
a way to test this is to change your password on the web site to one using only `A-Za-Z0-9!@#$%^&*()_+-={}[]\|;':",./<>?`~` and after logging out edit the config and try your new password.
We've had password issues in the past where the encryption services have had issues with certain language keysets.
Let me know how you go.

**Comment by vio771** [comment]
the logging out on website did help, thank you

**Comment by garfield69** [comment]
\o/
