### ISSUE TITLE
[turktorrent] (updating) Login failed: Selector "div#member_info_bar" didn't match

### ISSUE THREAD

**Issue by GinoBadouri** [Jackett/Jackett#15097]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.21.1873
Environment version: 6.0.27 (/app/Jackett/)
OS version: Unix 6.8.0.0 (64bit OS) (64bit process)
Jackett variant: CoreLinuxMuslAmdx64
File /etc/issue: Welcome to Alpine Linux 3.18
Running in Docker: No
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /config/Jackett
Using proxy: Disabled
Using FlareSolverr: http://192.168.1.1:8191
 Jackett is running with root privileges. You should run Jackett as an unprivileged user.
Using HTTP Client: HttpWebClient2
Loading Native indexers ...
Loaded 73 Native indexers.
Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
Loaded 533 Cardigann indexers.
Loaded 606 indexers in total
Adding aggregate indexer ('all' indexer) ...
Adding filter indexer ('type:public' indexer) ...
Adding filter indexer ('type:private' indexer) ...
Adding filter indexer ('type:semi-public' indexer) ...
Jackett startup finished in 3.279 s
```

### Description

I'm trying to add the TurkTorrent.us private tracker but it fails.
I've followed the instructions and torrent listing is set to "classic" and the language to "english".
I've copied the full cookie request header btw.
```tsue_guest_language=1; shoutboxChannelID=1; tsue_member=xxx```

### Logged Error Messages

```text
2024-02-28 20:38:52.9134 Error Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#member_info_bar" didn't match

[v0.21.1873.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "div#member_info_bar" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
The login selector didn't match is a sign that TurkTorrent rejected the cookie you used as not valid to represent Jackett as a session continuation of the browser session you used to fetch the cookie.
TurkTorrent are using cloudflare for DDoS protection so I would have expected the cookie you fetched to have contained a cf_clearance cookie string. Is this not the case?

**Comment by GinoBadouri** [comment]
Hi @garfield69 
I've pressed F12 and copied the values from the request cookie as is.
I don't think TurkTorrent.us uses CloudFlare DDoS protection (BitTurk.net does and that one works with FlareSolverr configured).
It does have an annoying puzzle you need to solve where you need to match the animals, perhaps thats the problem.
I have attached a screenshot of the cookies here:
![Schermafdruk van 2024-02-28 20-58-24](https://github.com/Jackett/Jackett/assets/144336417/1a46e8b8-44cf-41be-bc6b-494271e5cae9)

**Comment by garfield69** [comment]
I normally visit the sites torrent browse page and fetch my cookie from there.
If you have passed on the browser any kind of challenge, then the cookie should contain a clearance for that challenge.
Without it Jackett will not pass the cookie session match, and turktorrent will re-issue the challenge which is what is prevent Jackett from seeing the login selector post login check.

**Comment by GinoBadouri** [comment]
Well I guess the clearance and login session should all be stored in ```tsue_member``` then.
Because when I browse the list of torrents, the cookie stays the same.
If you (or any other developer) would like to try it out, I could send over my login details in a PM.

**Comment by garfield69** [comment]
ok. you have not mentioned anyplace that you also copied over the useragent. did you do that too?

**Comment by MastaG** [comment]
Yes, that field is also required.
I have more trackers requiring cookies, including the user agent string, like IPT and TD and they work fine.
I suspect its a recent change to the turktorrent.us website that broke it.

**Comment by GinoBadouri** [comment]
well at first I didn't, so I setup a dynamic (socks5) SSH tunnel to the server running Jackett and made sure to verify I'm connecting using the same public IP by checking www.whatismyip.com.
I then proceeded to login once more, but the cookie value stays the same and I'm still getting the same error message when trying to add it to Jackett.
![Schermafdruk van 2024-02-29 08-24-45](https://github.com/Jackett/Jackett/assets/144336417/124419eb-62ef-4aad-8ff8-af9cde1f824c)

**Comment by garfield69** [comment]
@ilike2burnthing  at this point I'm out of suggestions and would welcome your input. Thanks.
