### ISSUE TITLE
[anime tosho] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15121]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 6.0.27 (C:\ProgramData\Jackett\)
Starting Jackett v0.21.1946
```

### Description

Dashboard TEST returns `Exception (animetosho): No connection could be made because the target machine actively refused it.: No connection could be made because the target machine actively refused it. (feed.animetosho.org:443)`

### Logged Error Messages

```text
2024-03-06 06:02:54	Debug	WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://feed.animetosho.org/api)
2024-03-06 06:03:19	Info	Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 24622.8189ms
2024-03-06 06:03:19	Info	Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)'
[v0.21.1946.0] Jackett.Common.IndexerException: Exception (animetosho): No connection could be made because the target machine actively refused it.
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (feed.animetosho.org:443)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.Feeds.BaseFeedIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Feeds/BaseFeedIndexer.cs:line 53
   at Jackett.Common.Indexers.Feeds.AnimeTosho.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Feeds/AnimeTosho.cs:line 54
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 366
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 752
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 320
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2024-03-06 06:03:19	Error	Jackett.Common.IndexerException: Exception (animetosho): No connection could be made because the target machine actively refused it.
```

**Comment by garfield69** [comment]
using https://feed.animetosho.org/api via browser returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
> 5th Mar 2024: The secondary webserver is currently down (affects attachments, screenshots, torrents, NZBs and feed). Waiting on a fix from the provider. Apologies for the inconvenience.

**Comment by ekeekek1** [comment]
> > 5th Mar 2024: The secondary webserver is currently down (affects attachments, screenshots, torrents, NZBs and feed). Waiting on a fix from the provider. Apologies for the inconvenience.
@ilike2burnthing
I would like to pay you to fix the problem for my site. Do you have an email or Telegram account?

**Comment by ilike2burnthing** [comment]
Stop spamming this or you'll be blocked.

**Comment by ekeekek1** [comment]
> Stop spamming this or you'll be blocked.

sorry This is my first time using GitHub. Can I get help by giving you a lot of money?

**Comment by ilike2burnthing** [comment]
No.

**Comment by ekeekek1** [comment]
> No.

i can contact your email?

**Comment by ilike2burnthing** [comment]
No.

Unless you have an issue with Jackett, do not comment here again or you'll be blocked.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://animetosho.org/ DNS_PROBE_FINISHED_NXDOMAIN (DNS Lookup Error)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://animetosho.org/ UPDATE: server is currently experiencing boot failures, remaining downtime unknown.
feed.animetosho.org ERR_CONNECTION_TIMED_OUT

**Comment by SarreqTeryx** [comment]
as of 2024-09-22: animetosho.org is fine, but the feed link ( feed.animetosho.org:443 ) does not work
`Exception (animetosho): Network unreachable: Network unreachable (feed.animetosho.org:443)`

**Comment by joridiculous** [comment]
> as of 2024-09-22: animetosho.org is fine, but the feed link ( feed.animetosho.org:443 ) does not work `Exception (animetosho): Network unreachable: Network unreachable (feed.animetosho.org:443)`

(from Animetosho) 23rd Sep 2024: The secondary webserver is still currently down (links to torrents, attachments, NZBs, images and the feed/RSS will not work). I am currently trying to get a replacement server, but the host is taking their time on the matter unfortunately. Apologies for the extended downtime.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://feed.animetosho.org/rss2?only_tor=1 > ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
Site to stop adding new torrents in a few days, closing fully a few months after.

https://animetosho.org/about/shutdown
https://animetosho.org/about/shutdown2

**Comment by ilike2burnthing** [comment]
https://animetosho.xyz/ seems to be the successor, but thus far doesn't have a torznab API for us to use.

**Comment by garfield69** [comment]
v0.24.1905
