### ISSUE TITLE
Jackett attemps to re-login with wrong CAPTCHA

### ISSUE THREAD

**Issue by stanlu1013** [Jackett/Jackett#15139]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-03-11 19:40:23	Info	
Using HTTP Client: HttpWebClient2
2024-03-11 19:40:23	Info	
Using FlareSolverr: No
2024-03-11 19:40:23	Info	
Using proxy: Disabled
2024-03-11 19:40:23	Info	
App config/log directory: C:\ProgramData\Jackett
2024-03-11 19:40:23	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-03-11 19:40:23	Info	
Running in Docker: No
2024-03-11 19:40:23	Info	
Jackett variant: CoreWindows
2024-03-11 19:40:23	Info	
OS version: Microsoft Windows NT 10.0.20348.0 (64bit OS)
2024-03-11 19:40:23	Info	
Environment version: 6.0.27 (C:\ProgramData\Jackett\)
2024-03-11 19:40:20	Info	
Starting Jackett v0.21.2002
```

### Description

Hello, i have the same issues like this report:

https://github.com/Jackett/Jackett/issues/14964
https://github.com/Jackett/Jackett/issues/14726

Scenario:
i use jackett with cross-seed, and the cross-seed will use jackett rss link to search the indexers periodically.
However, it seems jackett will re-login sometimes with the wrong CAPTCHA.

i don't know if this is normal or something is wrong? many thanks if you can check the error log.

Thank you very much!

### Logged Error Messages

```text
2024-03-10 18:17:12.9741 Error Redirected to: https://xxxxxxxx.top/login.php?returnto=torrents.php%3Fsearch%3DFIFA%2BWC%2BAsian%2BQualifier%2BPhilippines%2Bvs%2BIndonesia%2B2023%26incldead%3D0%26spstate%3D0%26search_area%3D0%26search_mode%3D0%26sort%3D4%26type%3Ddesc%26notnewword%3D1
2024-03-10 18:17:12.9741 Info CardigannIndexer(xxxxxxxx): Relogin required
2024-03-10 18:17:14.7975 Error Error on 20240310181714 for xxxxxxxx.txtJackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1722





2024-03-10 18:17:14.8056 Error Jackett.Common.IndexerException: Exception (xxxxxxxx): Login failed: Selector "a[href="logout.php"]" didn't match

[v0.21.1981.0] Jackett.Common.IndexerException: Exception (xxxxxxxx): Login failed: Selector "a[href="logout.php"]" didn't match
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1722
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 778
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1876
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 492

2024-03-10 18:17:43.0228 Error Redirected to: https://xxxxxxxx.top/login.php?returnto=torrents.php%3Fsearch%3D%25E6%25AD%25AA%25E5%2598%25B4%25E6%2588%2598%25E7%25A5%259E%2B%25E5%258D%259A%25E6%2598%2593%25E5%258A%25A8%25E6%25BC%25AB%2BChap%2B001-Chap%2B089%2Bbili%26incldead%3D0%26spstate%3D0%26search_area%3D0%26search_mode%3D0%26sort%3D4%26type%3Ddesc%26notnewword%3D1
2024-03-10 18:17:43.0228 Info CardigannIndexer(xxxxxxxx): Relogin required
2024-03-10 18:17:43.8490 Error CardigannIndexer (xxxxxxxx): Found captcha during automatic login, aborting
2024-03-10 18:17:43.8490 Error Error on 20240310181743 for xxxxxxxx.txtSystem.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1719





2024-03-10 18:17:43.8490 Error Jackett.Common.IndexerException: Exception (xxxxxxxx): Relogin failed

[v0.21.1981.0] Jackett.Common.IndexerException: Exception (xxxxxxxx): Relogin failed
 ---> System.Exception: Parse error
 ---> System.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1719
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 778
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1876
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 492

2024-03-10 18:17:47.0029 Info Torznab search in xxxxxxxx => Found 100 releases (from cache) [2ms]
2024-03-10 18:18:13.0321 Error Redirected to: https://xxxxxxxx.top/login.php?returnto=torrents.php%3Fsearch%3DDr%2BCheon%2Band%2BLost%2BTalisman%2B2023%26incldead%3D0%26spstate%3D0%26search_area%3D0%26search_mode%3D0%26sort%3D4%26type%3Ddesc%26notnewword%3D1
2024-03-10 18:18:13.0321 Info CardigannIndexer(xxxxxxxx): Relogin required
2024-03-10 18:18:14.5490 Error Error on 20240310181814 for xxxxxxxx.txtJackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1722





2024-03-10 18:18:14.5490 Error Jackett.Common.IndexerException: Exception (xxxxxxxx): Login failed: Selector "a[href="logout.php"]" didn't match

[v0.21.1981.0] Jackett.Common.IndexerException: Exception (xxxxxxxx): Login failed: Selector "a[href="logout.php"]" didn't match
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1722
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 778
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1876
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 492
```

**Comment by ilike2burnthing** [comment]
A search is performed, but the cookie has expired, so Jackett is redirected to the login page, where a CAPTCHA is found, and so no login attempt is made. Jackett is working as it's supposed to.
