### ISSUE TITLE
[totheglory] (testing) Exception (totheglory): Object reference not set to an instance of an object.: Parse error

### ISSUE THREAD

**Issue by kong-zhe** [Jackett/Jackett#15162]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-03-18 21:42:55	Info	
Jackett startup finished in 18.059 s
2024-03-18 21:42:54	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2024-03-18 21:42:54	Info	
Adding filter indexer ('type:private' indexer) ...
2024-03-18 21:42:54	Info	
Adding filter indexer ('type:public' indexer) ...
2024-03-18 21:42:54	Info	
Adding aggregate indexer ('all' indexer) ...
2024-03-18 21:42:54	Info	
Loaded 611 indexers in total
2024-03-18 21:42:54	Info	
Loaded 538 Cardigann indexers.
2024-03-18 21:42:44	Info	
Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
2024-03-18 21:42:44	Info	
Loaded 73 Native indexers.
2024-03-18 21:42:44	Info	
Loading Native indexers ...
2024-03-18 21:42:44	Info	
Using HTTP Client: HttpWebClient2
2024-03-18 21:42:44	Info	
Using FlareSolverr: No
2024-03-18 21:42:44	Info	
Using proxy: Disabled
2024-03-18 21:42:44	Info	
App config/log directory: /config/Jackett
2024-03-18 21:42:44	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-03-18 21:42:44	Info	
Running in Docker: Yes (image build: v0.21.2069-ls341)
2024-03-18 21:42:44	Info	
File /etc/issue: Welcome to Alpine Linux 3.19
2024-03-18 21:42:44	Info	
Jackett variant: CoreLinuxMuslAmdx64
2024-03-18 21:42:44	Info	
OS version: Unix 4.4.59.0 (64bit OS) (64bit process)
2024-03-18 21:42:44	Info	
Environment version: 6.0.28 (/app/Jackett/)
2024-03-18 21:42:40	Info	
Starting Jackett v0.21.2069
```

### Description

just click test button.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (totheglory): Object reference not set to an instance of an object.

[v0.21.2069.0] Jackett.Common.IndexerException: Exception (totheglory): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 770
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1731
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 778
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1894
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 366
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 752
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 320
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/115127445/1ee0f627-f929-4d22-bfa8-afbf1191b532)

**Comment by ilike2burnthing** [comment]
None of the maintainers have an account, so please provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ilike2burnthing** [comment]
[v0.21.2090](https://github.com/Jackett/Jackett/releases/v0.21.2090)
