### ISSUE TITLE
[selezen] (updating) Login failed: No form found on https://selezen.org/login.html using form selector form[role="form"]

### ISSUE THREAD

**Issue by 51n1au5k1** [Jackett/Jackett#15180]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-03-24 17:55:20	Info	Using HTTP Client: HttpWebClient2
2024-03-24 17:55:20	Error	Jackett is running with root privileges. You should run Jackett as an unprivileged user.
2024-03-24 17:55:20	Info	Using FlareSolverr: No
2024-03-24 17:55:20	Info	Using proxy: Disabled
2024-03-24 17:55:20	Info	App config/log directory: /root/.config/Jackett
2024-03-24 17:55:20	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-03-24 17:55:20	Info	Running in Docker: No
2024-03-24 17:55:20	Info	File /etc/issue: Debian GNU/Linux 12 \n \l
2024-03-24 17:55:20	Info	Jackett variant: CoreLinuxAmdx64
2024-03-24 17:55:20	Info	OS version: Unix 6.5.13.3 (64bit OS) (64bit process)
2024-03-24 17:55:20	Info	Environment version: 6.0.28 (/opt/Jackett/)
2024-03-24 17:55:19	Info	Starting Jackett v0.21.2143
```

### Description

An error occurred while updating this indexer
Login failed: No form found on https://selezen.org/login.html using form selector form[role="form"]

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://selezen.org/login.html using form selector form[role="form"]

[v0.21.2143.0] Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://selezen.org/login.html using form selector form[role="form"]
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 603
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1042
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/108816899/fefa7478-2820-41ee-afbc-066e5786b7d7)

**Comment by ilike2burnthing** [comment]
Try the other two site links, or change from https://selezen.org/ to the subdomain https://open.selezen.org/

I've also added two new links:
- https://www.selezen.top/
- https://open.selezen.top/

If you have the same problem with all 5 URLs, follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-no-form-found-on-url

Failing that, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ilike2burnthing** [comment]
Also just saw you're running Jackett as root, is there a reason for this?
