### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.qa/ using form selector #user-login: Parse error

### ISSUE THREAD

**Issue by Johnnybegood90** [Jackett/Jackett#15201]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-03-28 12:03:23	Info	Using HTTP Client: HttpWebClient2
2024-03-28 12:03:23	Info	Using FlareSolverr: http://192.168.0.45:8191
2024-03-28 12:03:23	Info	Using proxy: Disabled
2024-03-28 12:03:23	Info	App config/log directory: C:\ProgramData\Jackett
2024-03-28 12:03:23	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-03-28 12:03:23	Info	Running in Docker: No
2024-03-28 12:03:23	Info	Jackett variant: CoreWindows
2024-03-28 12:03:23	Info	OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
2024-03-28 12:03:23	Info	Environment version: 6.0.28 (C:\ProgramData\Jackett\)
2024-03-28 12:03:22	Info	Starting Jackett v0.21.2199
```

### Description

[yggtorrent] (testing) Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.qa/ using form selector #user-login: Parse error

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.qa/ using form selector #user-login

[v0.21.2199.0] Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://www3.yggtorrent.qa/ using form selector #user-login
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www3.yggtorrent.qa/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 603
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1731
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 778
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1892
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 322
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Try reconfiguring the indexer.

If you still have problems, follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-no-form-found-on-url

Failing that, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket
