### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): The operation was canceled.: The operation was canceled.

### ISSUE THREAD

**Issue by Jewem** [Jackett/Jackett#15215]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-03-31 23:04:27	Info	Using HTTP Client: HttpWebClient2
2024-03-31 23:04:26	Info	Using FlareSolverr: http://localhost:8191/
2024-03-31 23:04:26	Info	Using proxy: Disabled
2024-03-31 23:04:26	Info	App config/log directory: /home/xxx/.config/Jackett
2024-03-31 23:04:26	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-03-31 23:04:26	Info	Running in Docker: No
2024-03-31 23:04:26	Info	File /etc/issue: Debian GNU/Linux 11 \n \l
2024-03-31 23:04:26	Info	Jackett variant: CoreLinuxAmdx64
2024-03-31 23:04:26	Info	OS version: Unix 5.10.0.28 (64bit OS) (64bit process)
2024-03-31 23:04:26	Info	Environment version: 6.0.28 (/home/XXX/Jackett/)
```

### Description

Flaresolverr is down since 2 days,   it was randomly UP next day but since today... challenge doesn't pass.
I pulled the newest release but not working.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (yggtorrent): The operation was canceled.

[v0.21.2232.0] Jackett.Common.IndexerException: Exception (yggtorrent): The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 577
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1521
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 366
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 752
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 322
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by Guesh1337** [comment]
same issue with me since 2 days

**Comment by Jewem** [comment]
sudo docker logs flaresolverr
2024-03-31 21:24:01 INFO     Challenge not detected!
2024-03-31 21:24:02 INFO     Response in 32.672 s
2024-03-31 21:24:02 INFO     141.xxxx POST http://xxxxx:8191/v1 200 OK
2024-03-31 21:24:02 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://ad.a-ads.com/2313959?size=468x60', 'maxTimeout': 60000}
version_main cannot be converted to an integer
2024-03-31 21:24:05 WARNING  Task queue depth is 12
2024-03-31 21:24:08 WARNING  Task queue depth is 13
2024-03-31 21:24:11 WARNING  Task queue depth is 14
2024-03-31 21:24:14 INFO     Challenge not detected!
2024-03-31 21:24:14 WARNING  Task queue depth is 15
2024-03-31 21:24:15 INFO     Response in 28.891 s
2024-03-31 21:24:15 INFO     xx.xx.x.xx POST http://x.x.x.x:8191/v1 200 OK

**Comment by Jewem** [comment]
i fell like my flaresolverr is looping on : https://ad.a-ads.com/23139..     i don't now what it is

**Comment by ilike2burnthing** [comment]
Likely related to one of the several open issues on the FlareSolverr repo. Check those and the troubleshooting wiki page.
