### ISSUE TITLE
[ostwiki] (updating) Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match

### ISSUE THREAD

**Issue by soredake** [Jackett/Jackett#15212]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-03-29 10:45:52 	Info 	Using HTTP Client: HttpWebClient2
2024-03-29 10:45:52 	Info 	Using FlareSolverr: http://flaresolverr:8191/
2024-03-29 10:45:52 	Info 	Using proxy: Disabled
2024-03-29 10:45:52 	Info 	App config/log directory: /config/Jackett
2024-03-29 10:45:52 	Info 	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-03-29 10:45:52 	Info 	Running in Docker: Yes (image build: v0.21.2212-ls352)
2024-03-29 10:45:52 	Info 	File /etc/issue: Welcome to Alpine Linux 3.19
2024-03-29 10:45:52 	Info 	Jackett variant: CoreLinuxMuslArm64
2024-03-29 10:45:52 	Info 	OS version: Unix 6.5.0.1019 (64bit OS) (64bit process)
2024-03-29 10:45:52 	Info 	Environment version: 6.0.28 (/app/Jackett/)
2024-03-29 10:45:51 	Info 	Starting Jackett v0.21.2212
```

### Description

[ostwiki] (updating) Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match

[v0.21.2212.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href*="/logout.php?logouthash="]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Working ok here. Reconfigure the indexer and enter the new captcha.

If login still fails, follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-selector

Failing that, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by soredake** [comment]
>Reconfigure the indexer and enter the new captcha.

I've tried that three times already, will try again now.

**Comment by soredake** [comment]
After several retries, I've been able to log in, sorry!
