### ISSUE TITLE
Jackett proxies localhost

### ISSUE THREAD

**Issue by highghlow** [Jackett/Jackett#15218]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Socks5
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.2163-ls349)
File /etc/issue: Welcome to Alpine Linux 3.19
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.1.0.18 (64bit OS) (64bit process)
Environment version: 6.0.28 (/app/Jackett/)
```

### Description

**The problem:**
When adding a private tracker, jackett makes a call to it's backend at 127.0.0.1 (localhost), but it does this through the configured proxy, so it obviously fails. (If the proxy is disabled, the request to the tracker fails)

**The solution:**
Don't proxy localhost (or disable the proxy in these specific requests)

### Logged Error Messages

```text
Server Logs
Date	Level	Message
2024-04-03 00:08:00	Error	
System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://127.0.0.1:12345/' failed with status code '400'."

[v0.21.2258.0] System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://127.0.0.1:12345/' failed with status code '400'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 628
   at Jackett.Common.Indexers.RuTracker.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/RuTracker.cs:line 1454
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 113
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by ilike2burnthing** [comment]
Apologies for the delay, having VPN/proxy troubles of my own.

I can't reproduce this. Have you configured the proxy URL as `127.0.0.1`?

**Comment by highghlow** [comment]
> Apologies for the delay, having VPN/proxy troubles of my own.
> 
> I can't reproduce this. Have you configured the proxy URL as `127.0.0.1`?

Yes, I did

**Comment by highghlow** [comment]
I don't know it that matters, but my Jackett is running on an Umbrel server (in docker, https://github.com/getumbrel/umbrel-apps/tree/master/jackett) and I'm using tor as the socks5 proxy

**Comment by highghlow** [comment]
I checked, `curl -x socks5://127.0.0.1:9050 https://example.com` succedes

**Comment by ilike2burnthing** [comment]
> curl -x socks5://127.0.0.1:9050 https://example.com/

Did you run that within the container or on your host device?

I have no prior knowledge of Umbrel, but its use of Docker doesn't seem to be any different than normal. Generally the only time you're going to use localhost within a container is when communicating with the app itself. When communicating between containers, you can use the container's Docker IP or hostname, and when communicating with the host or another LAN device, you would use the local IP.

So if the proxy is running on the host, you'd have to use something like `http://192.168.0.2:9050` for Jackett.

**Comment by highghlow** [comment]
> Did you run that within the container or on your host device?

Yes, I'm running it on the host.

> When communicating between containers, you can use the container's Docker IP or hostname, and when communicating with the host or another LAN device, you would use the local IP.

That's probably it. Umbrel is bugged right now which prevents me from checking, but you're probably right. I'll check as soon as I can

**Comment by highghlow** [comment]
Yup! That was it, Thanks!
