### ISSUE TITLE
[1337x] (testing) Exception (1337x): No connection could be made because the target machine actively refused it.: No connection could be made because the target machine actively refused it. (1337x.to:443)

### ISSUE THREAD

**Issue by Rallo00** [Jackett/Jackett#15221]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett: v0.21.2265 for Windows (Installed as service)
OS: Windows 10 Pro 10.0.19045 Build 19045
```

### Description

Error when trying to test to 1337x, other Indexers work correctly.
I can reach 1337x.to using browser.

### Logged Error Messages

```text
Date	Level	Message
2024-04-03 14:54:51	Error	
Jackett.Common.IndexerException: Exception (1337x): No connection could be made because the target machine actively refused it.

[v0.21.2265.0] Jackett.Common.IndexerException: Exception (1337x): No connection could be made because the target machine actively refused it.
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (1337x.to:443)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 591
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1521
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 359
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 380
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 766
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 322
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![Screenshot 2024-04-03 alle 14 55 30](https://github.com/Jackett/Jackett/assets/106067524/96fa5ab2-1740-4cc8-ab00-4b874430c611)

**Comment by ilike2burnthing** [comment]
Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#no-connection-could-be-made-because-the-target-machine-actively-refused-it

Failing that, try the many other links provided for the indexer.

**Comment by Rallo00** [comment]
Hi, all steps have been followed.
I can ping, lookup and reach correctly 1337x.to website from my browser.
ISP has not blocked the website.
No Windows Defender/AV/Firewall is active.
Already tried all the other links. From Jackett they all fail the test.

**Comment by ilike2burnthing** [comment]
Why is the ping for 127.0.0.1?

I'm assuming the DNS server in that screenshot is your ISP? However, you've then used 8.8.8.8 for the 1337x.to lookup, so that's not representative of your current setup.

**Comment by garfield69** [comment]
oooh, well spotted. did not see those images in the original post.
strange results from the ping an nslookup, not at all regular results.

**Comment by garfield69** [comment]
is there an override in the host file?

**Comment by Rallo00** [comment]
My net card is configured to use 8.8.8.8 as primary DNS and 8.8.4.4 as secondary DNS. Nothing relevant on the hosts file actually.
![Screenshot 2024-04-05 alle 08 56 06](https://github.com/Jackett/Jackett/assets/106067524/6e6faaf8-c565-4468-b40f-3324d013b9ae)
![Screenshot 2024-04-05 alle 08 59 09](https://github.com/Jackett/Jackett/assets/106067524/560b3c76-5e2a-4090-abdf-07684a64fb65)
![Screenshot 2024-04-05 alle 08 59 18](https://github.com/Jackett/Jackett/assets/106067524/2653d230-f20d-4745-862b-d19905fc6156)

**Comment by Rallo00** [comment]
Ok, I think I figured it out. 
I disabled IPv6 on my netcard, therefore forcing it to use IPv4. Don't really need IPv6 so I don't care.

Here it is with a working nslookup, now it uses google as default DNS server and resolves 1337x.to correctly.

![Screenshot 2024-04-05 alle 09 05 05](https://github.com/Jackett/Jackett/assets/106067524/65c535d4-1ebc-4549-a0a4-3debd3343431)

**Comment by Rallo00** [comment]
> shutdown and start-up your Jackett service and go to the Jackett dashboard and view the log. scroll to the bottom and copy/paste the last ten lines (`using http` to `starting Jackett v`) which contain the environment details that may be useful are you using a browser like chrome, edge or firefox or a browser with a built in vpn like opera? are you using a system vpn?

No VPN at all, standard Edge with no additional plugins.

```
2024-04-05 09:06:23	Info	
Using HTTP Client: HttpWebClient2
2024-04-05 09:06:23	Info	
Using FlareSolverr: No
2024-04-05 09:06:23	Info	
Using proxy: Disabled
2024-04-05 09:06:23	Info	
App config/log directory: C:\ProgramData\Jackett
2024-04-05 09:06:23	Info	
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-04-05 09:06:23	Info	
Running in Docker: No
2024-04-05 09:06:23	Info	
Jackett variant: CoreWindows
2024-04-05 09:06:23	Info	
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
2024-04-05 09:06:23	Info	
Environment version: 6.0.28 (C:\ProgramData\Jackett\)
2024-04-05 09:06:22	Info	
Starting Jackett v0.21.2278
```

**Comment by garfield69** [comment]
so is Jackett working now?

**Comment by Rallo00** [comment]
> so is Jackett working now?

No the problem still persists. I solved what could be networking problems that might have had something to do with Jackett.

**Comment by garfield69** [comment]
so a ping still does not resolve 1337x?
maybe you need a reboot to release dns cache.

**Comment by Rallo00** [comment]
> so is Jackett working now?

![Screenshot 2024-04-05 alle 09 13 05](https://github.com/Jackett/Jackett/assets/106067524/be5802ea-50dc-4145-a842-21ea355e004e)

It looks like it was a networking problem eventually. 
Thanks to you all for your support. Did not notice the odd values when trying to ping and nslookup. Hope this might solve other people's issue. It is the first time I experience this kind of problem with IPv6.

**Comment by garfield69** [comment]
\o/
