### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): A task was canceled.: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### ISSUE THREAD

**Issue by Jewem** [Jackett/Jackett#15222]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://localhost:XXXX/
Using proxy: Disabled
App config/log directory: /home/XXXX/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 11 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.28 (64bit OS) (64bit process)	
Environment version: 6.0.28
```

### Description

<html>
<body>

Using HTTP Client: HttpWebClient2
--
2024-04-03 20:11:09 | Info | Using FlareSolverr: http://localhost:XXXX/
2024-04-03 20:11:09 | Info | Using proxy: Disabled
2024-04-03 20:11:09 | Info | App config/log directory: /home/XXX/.config/Jackett
2024-04-03 20:11:09 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-04-03 20:11:09 | Info | Running in Docker: No
2024-04-03 20:11:09 | Info | File /etc/issue: Debian GNU/Linux 11 \n \l
2024-04-03 20:11:09 | Info | Jackett variant: CoreLinuxAmdx64
2024-04-03 20:11:09 | Info | OS version: Unix 5.10.0.28 (64bit OS) (64bit process)
2024-04-03 20:11:09 | Info | Environment version: 6.0.28 (/home/XXX/Jackett/)
2024-04-03 20:11:05 | Info | Jackett stopped

</body>
</html>

### Logged Error Messages

```text
Flaresolverr logs :

2024-04-03 18:35:18 INFO     Challenge detected. Title found: Just a moment...
2024-04-03 18:36:54 INFO     Challenge solved!
2024-04-03 18:36:56 INFO     Response in 115.612 s
2024-04-03 18:36:56 INFO     172.17.0.1 POST http://localhost:xxx/v1 200 OK

Jacket Log :

Jackett.Common.IndexerException: Exception (yggtorrent): A task was canceled.

[v0.21.2265.0] Jackett.Common.IndexerException: Exception (yggtorrent): A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 595
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1521
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 382
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 382
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 769
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 322
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
It took flaresolverr 115 seconds to resolve the challenge, which exceeds the default timeout of 100 seconds.
If usually only takes 12 seconds for my flaresolverr to solve the challenge.
Try again.
If your setup cannot solve the challenge quicker then consider using the yggcookie for a time instead.
While yggcookie should give you access, the cookie will expired whenever cloudflare decides to present a challenge again, so be prepared for that event.
But perhaps, your IP region is under extra scrutiny from cloudflare because of a DDoS attack generated in your region, so once this passes they may ease up on security and you can return to using yggtorrent again.
Also, keep an eye on https://github.com/FlareSolverr/FlareSolverr/issues/1139 which likely is related to your problem.

**Comment by Jewem** [comment]
All my tests and challenges takes long time (more than 100 sec)
