### ISSUE TITLE
[yggtorrent] (testing) Test search in YGGtorrent => Found no results while trying to browse this tracker. 

### ISSUE THREAD

**Issue by adri1m64** [Jackett/Jackett#15240]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
04-12 22:01:52 Info Starting Jackett v0.21.2354
04-12 22:01:53 Info Environment version: 6.0.29 (C:\ProgramData\Jackett\)
04-12 22:01:53 Info OS version: Microsoft Windows NT 10.0.20348.0 (64bit OS)
04-12 22:01:53 Info Jackett variant: CoreWindows
04-12 22:01:53 Info Running in Docker: No
04-12 22:01:53 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
04-12 22:01:53 Info App config/log directory: C:\ProgramData\Jackett
04-12 22:01:53 Info Using proxy: Disabled
04-12 22:01:53 Info Using FlareSolverr: http://localhost:8191
04-12 22:01:53 Info Using HTTP Client: HttpWebClient2
```

### Description

Hello, YGG isn't working. Can someone can help me?

The test is returning me

Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

Thank you by advance

### Logged Error Messages

```text
04-12 22:19:11 Error System.Exception: Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.21.2354.0] System.Exception: Test search in YGGtorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 330
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by garfield69** [comment]
some common thing to check first:
- edit the yggtorret config with your jackett dashboard and ensure the sitelink is set to `https://www3.yggtorrent.qa/`
- ensure you are on the latest flaresolverr, currently 3.3.17
- check on the yggtorrent web site that you can login, that you are not suspended, and have a good ratio.
if all the above is good, then turn on jackett enhanced logging and repeat your test and provide the full log so that we can have a look to see if we can spot what may be going on.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ilike2burnthing** [comment]
Think I fixed the bot properly this time 🙄

**Comment by ilike2burnthing** [comment]
Apparently not :/

**Comment by garfield69** [comment]
I'll have a go...

**Comment by ilike2burnthing** [comment]
I've come to the conclusion that jackettbot has become sentient and is now rebelling us.

I'll leave this issue up for today in case @adri1m64 wants to reply, after which I'll delete it.

**Comment by adri1m64** [comment]
Ahah yes, it look like jacketbot going crazy. I saw few post look like mine but no one is exactly the same problem...

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/15240#issuecomment-2052489354

**Comment by adri1m64** [comment]
Hello, sorry i didn't saw your message. I attached the logs because it's too long.
Hope I didn't include cookies or things like this...
Thank you!!
[logs.txt](https://github.com/Jackett/Jackett/files/14972240/logs.txt)

**Comment by ilike2burnthing** [comment]
Looks like the bot knew the whole time. This is just https://github.com/Jackett/Jackett/issues/15203 again; change the sitelink like garfield69 told you.

**Comment by adri1m64** [comment]
Okay, i'm so so so sorry. I changed the adress because the site changed but ygg torrent changed its adress from the web, but Jackett seems to prefer the old adress.
Thank you and sorry for disturbing...
