### ISSUE TITLE
[wolfmax4k] (testing) Test search in Wolfmax 4k => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by botijo90** [Jackett/Jackett#15254]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Loading Native indexers ...

Using HTTP Client: HttpWebClient2

Using FlareSolverr: http://192.168.31.2:8191/

Using proxy: Disabled

App config/log directory: /config/Jackett

ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads

Running in Docker: Yes (image build: v0.21.2392-ls370)

File /etc/issue: Welcome to Alpine Linux 3.19

Jackett variant: CoreLinuxMuslAmdx64
	
OS version: Unix 5.15.0.102 (64bit OS) (64bit process)
	
Environment version: 6.0.29 (/app/Jackett/)
	
Starting Jackett v0.21.2395
```

### Description

making a test to probe if all it's ok 

if i make a manual search all ok

### Logged Error Messages

```text
2024-04-17 12:12:06	Error	
System.Exception: Test search in Wolfmax 4k => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.21.2395.0] System.Exception: Test search in Wolfmax 4k => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 330
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2024-04-17 12:12:06	Info	

Test search in Wolfmax 4k => Found 0 releases [2708ms]
```

**Comment by ilike2burnthing** [comment]
@highfredo can you please update the indexer?

Empty searches are no longer permitted. However, performing a search for `%` or not performing a search at all (just accessing `https://wolfmax4k.com/buscar`) returns the latest results.

**Comment by garfield69** [comment]
v0.21.2404

**Comment by botijo90** [comment]
It's working right now, thank you so much guys.
