### ISSUE TITLE
[wolfmax4k] The SSL connection could not be established, see inner exception.: certificate validation failed

### ISSUE THREAD

**Issue by sergiomedinamartin** [Jackett/Jackett#15270]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-04-23 18:47:56	Info	Using HTTP Client: HttpWebClient2
2024-04-23 18:47:56	Info	Using FlareSolverr: No
2024-04-23 18:47:56	Info	Using proxy: Disabled
2024-04-23 18:47:56	Info	App config/log directory: /home/jackett/.config/Jackett
2024-04-23 18:47:56	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-04-23 18:47:56	Info	Running in Docker: No
2024-04-23 18:47:56	Info	File /etc/issue: Ubuntu 22.04.3 LTS \n \l
2024-04-23 18:47:56	Info	Jackett variant: CoreLinuxAmdx64
2024-04-23 18:47:56	Info	OS version: Unix 5.15.0.105 (64bit OS) (64bit process)
2024-04-23 18:47:56	Info	Environment version: 6.0.29 (/opt/Jackett/)
2024-04-23 18:47:56	Info	Starting Jackett v0.21.2441
```

### Description

I click add indexer and select wolfmax4k and I get an error:

 An error occurred while configuring this indexer
The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] CN=wolfmax4k.com [Issuer] CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES [Serial Number] 00B4730D66000000000400000000000000 [Not Before] 12/16/2016 1:07:49 PM [Not After] 12/16/2026 1:07:49 PM [Thumbprint] 1A7B9DE0170D0107A27982552A98B36217C6C1D9

### Logged Error Messages

```text
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

[v0.21.2441.0] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Exception: certificate validation failed: [Subject]
  CN=wolfmax4k.com

[Issuer]
  CN="allot.com/emailAddress=info@allot.com", OU=Allot, O=Allot, L=Madrid, S=Madrid, C=ES

[Serial Number]
  0082F91266000000003601000000000000

[Not Before]
  12/16/2016 1:07:49 PM

[Not After]
  12/16/2026 1:07:49 PM

[Thumbprint]
  5A6747ECFD8C0E4B6C2BFBBACF1F2D4912AFA854

   at Jackett.Common.Utils.Clients.HttpWebClient2.ValidateCertificate(HttpRequestMessage request, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 53
   at System.Net.Http.ConnectHelper.<>c__DisplayClass1_0.<SetUpRemoteCertificateValidationCallback>b__0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 219
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 601
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass12_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in ./Jackett.Common/Indexers/BaseIndexer.cs:line 574
--- End of stack trace from previous location ---
   at Polly.ResiliencePipeline.<>c__10`1.<<ExecuteAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult](Func`2 callback, CancellationToken cancellationToken)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 573
   at Jackett.Common.Indexers.Wolfmax4K.GetSearchTokenAsync() in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 179
   at Jackett.Common.Indexers.Wolfmax4K.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 108
   at Jackett.Common.Indexers.Wolfmax4K.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 96
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
You are being blocked by your ISP. Your ISP is routing you to a black hole with an invalid certificate, CN=allot.com, O=Allot, C=ES . The official certificate for wolfmax4k CN=GTS CA 1P5, O=Google Trust Services LLC, C=US
- Try is to stop using the DNS provided by your ISP and switch to one of the public ones from [Cloudflare](https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1) (1.1.1.1 and 1.0.0.1) or [Google](https://developers.google.com/speed/public-dns/docs/using) (8.8.8.8 and 8.8.4.4) or [Quad9](https://www.quad9.net/) (9.9.9.9 and 149.112.112.112).
- If your ISP is still able to trap your DNS lookups when using a public DNS then
  - Use a VPN service or a proxy server.
  - or try https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation
  - or DNS over TLS https://fedoramagazine.org/use-dns-over-tls/.
 
Also, once you can access wolfmax4k, you will likely need the flaresolverr companion for Jackett to pass the cloudflare challenge, as wolkmax4k uses cloudflare protection.
refer https://github.com/FlareSolverr/FlareSolverr

**Comment by RPadial** [comment]
Hello, I got here with the same prblem. I changed the DNS to the Google DNS and I can successfully ping to wolfmax4k.com but jacket still reports same error. How I can solve it?

**Comment by garfield69** [comment]
@rpadial if you have changed DNS and you are still getting the allot.com certificate-validation-failed error, then the next step to try is to use a system wide vpn so that you can shield your traffic from your ISP.
