### ISSUE TITLE
[torrentbd] (updating) Login failed: Selector "button[href="account-logout.php"]" didn't match

### ISSUE THREAD

**Issue by iafuad** [Jackett/Jackett#15275]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: ***
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.21.2458-ls380)
File /etc/issue: Welcome to Alpine Linux 3.19
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.15.0.1056 (64bit OS) (64bit process)
Environment version: 6.0.29 (/app/Jackett/)
```

### Description

- [x] Add indexer > TorrentBD
- [x] Paste cookie and user-agent header from browser
- [x] Click okay

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "button[href="account-logout.php"]" didn't match

[v0.21.2458.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "button[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/115505119/0d69ca83-13f9-413b-a0c4-13a9dc65bbb2)

**Comment by ilike2burnthing** [comment]
Have you followed the specific instruction for that indexer?

> Ensure you have the Remember me ticked and the Log Me Out if IP Changes unticked when you login

Follow the troubleshooting steps here, paying particular attention to the Notes section - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work

Failing that, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by iafuad** [comment]
> Have you followed the specific instruction for that indexer?
> 
> > Ensure you have the Remember me ticked and the Log Me Out if IP Changes unticked when you login
> 
> Follow the troubleshooting steps here, paying particular attention to the Notes section - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work
> 
> Failing that, provide an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

Yes, I have unticked the "Log Me Out if IP Changes" option.
And here are the enhanced logs of the issue ~ [log.txt](https://github.com/Jackett/Jackett/files/15111848/log.txt)

**Comment by ilike2burnthing** [comment]
You have followed those linked troubleshooting steps, including disabling IPv6 on both the device running Docker and the device you're getting the cookie from, and running a Chrome or Firefox Docker container on the same device as Jackett and pulling the cookies from it?

**Comment by iafuad** [comment]
> ```
> 2024-04-25 20:45:26.4401 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.torrentbd.net/)
> 2024-04-25 20:45:26.8190 Debug x_auth=deleted; expires=Thu, 01 Jan 1970 00:00:01 GMT; Max-Age=0; path=/
> 2024-04-25 20:45:26.8190 Debug user=(removed) expires=Thu, 01 Jan 1970 00:00:01 GMT; Max-Age=0; path=/
> 2024-04-25 20:45:26.8197 Debug ts_ib=deleted; expires=Thu, 01 Jan 1970 00:00:01 GMT; Max-Age=0; path=/
> 2024-04-25 20:45:26.8197 Debug WebClient(HttpWebClient2): Returning OK => 0 bytes
> ```
> 
> Looks like the cookie isn't valid.
> 
> You have followed those linked troubleshooting steps, including disabling IPv6 on both the device running Docker and the device you're getting the cookie from, and running a Chrome or Firefox Docker container on the same device as Jackett and pulling the cookies from it?

Looks like the issue was with change in IP address, it worked after setting up an SSH tunnel to the headless server where the docker container is hosted and using that proxy with firefox to login and grab the cookies.
