### ISSUE TITLE
[torrentcore] (testing) Exception (torrentcore): Error: Connection failed: Connection refused: Parse error

### ISSUE THREAD

**Issue by Lod3** [Jackett/Jackett#15284]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett v0.21.2508
Environment version: 6.0.29
Jackett variant: CoreWindows
Using HTTP Client: HttpWebClient2
```

### Description

torrentcore connection failed
Latest version of flaresolverr installed and tested
Checked other issues only one I could find was this one 
https://github.com/Jackett/Jackett/issues/13347

Anythin else I can provide to help in any way?

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (torrentcore): Error: [Anti-DDoS]
Please wait 10 seconds for each request.

[v0.21.2508.0] Jackett.Common.IndexerException: Exception (torrentcore): Error: [Anti-DDoS]
Please wait 10 seconds for each request.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Error: [Anti-DDoS]
Please wait 10 seconds for each request.
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 542
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1753
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 798
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1892
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 365
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 386
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 772
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 322
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```
```


### Screenshots

_No response_

**Comment by garfield69** [comment]
The anti-DDoS message is generated by the web site. Despite Jackett having a 10.1 second request delay between any searches you make, via either the Jackett dashboard or via a Torznab query (such as from any of the *arr apps for example), the site still generates this error intermittently, and there is nothing Jackett can do about it.
Generally, after getting this message, I try the query again and the search returns results most of the time.
It's not worth out time and effort to rewrite the indexer from yaml to C# in order to try to handle the anti-ddos block from the site and retry the query after yet another 10.1 seconds.
IMO there are other public indexers to choose from that have the same content and dont have resource constraints as torrentcore apparently suffers from.

**Comment by garfield69** [comment]
Also, the site occasionally stops presenting the home page with the latest results
![image](https://github.com/Jackett/Jackett/assets/6933240/34c1e440-1a39-4747-a16c-18865c7e6a19)
when this happens the Jackett TEST button (or a keywordless search) stops returning results which is another problem that cannot be solved.
Basically this site is not in good shape ATM.
