### ISSUE TITLE
Jackett v0.22.43+a38117 throws exceptions when used with Sonarr

### ISSUE THREAD

**Issue by mirolm** [Jackett/Jackett#15364]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/nzbdrone/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 11 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.10.0.30 (64bit OS) (64bit process)
Environment version: 8.0.6 (/opt/jackett/)
Starting Jackett v0.22.43+f3b02a0bb0bad0bcf3d9db3cf600cc3fd4a38117
```

### Description

With the latest Jackett i noticed two things:
 - When trying to use sonarr and jackett, sonarr says that all indexers are down and jackett shows bunch of error messages.
 - Jackett updates every time i press "Check for updates" button no matter that version is the same.

### Logged Error Messages

```text
2024-06-03 15:46:15	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
```

**Comment by mirolm** [comment]
All indexers are down. I use Anime Tosho, Nyaa, BakaBT and SubsPlease. Jackett log is spammed with multiple occurences of the above error.

**Comment by mirolm** [comment]
Tests work without issues in both Jackett ans Sonarr. Error occurs when in Sonarr i press the RSS Sync button in the main window.

**Comment by mirolm** [comment]
Below you can find the requested logfile:

https://privatebin.net/?ed54a27ea02e28db#9mz6rDqL7vE5u2yZ37wgZfUYYym4o2LMQ9zbCRHoN2XM

**Comment by NathanFichefet** [comment]
Thanks, it works !

**Comment by garfield69** [comment]
>should we tag a new release?

we've not done so in the past.

**Comment by ilike2burnthing** [comment]
Sorry, just getting back online now. We've done off-schedule hotfix releases for breaking bugs in the past (granted, I think only 2 or 3 in my few years here). Had I been online 9hrs ago I would have said yes, but as there's only 6 hrs to go, and the temporary workaround is 'disable cache', I think we're fine to wait.

**Comment by garfield69** [comment]
>should we tag a new release?

Oh, this actually means `publish a new release` !    I completely misread this, and went looking in the history to see if between  v20 and v21, v19 and v20, and v18 and v19 if  we had set a special release tag, and not found anything  ;-D
Sorry about that.

**Comment by navels** [comment]
Possibly you are not being flooded by issues because people like me search before creating an issue.   Given the severity and the troubleshooting a person has to go through before getting to this issue a hotfix would've been much appreciated.

**Comment by ilike2burnthing** [comment]
> Possibly you are not being flooded by issues because people like me search before creating an issue.

I only wish that were true more broadly (see basically every YGGtorrent issue here and on FlareSolverr, along with the 2k+ other duplicate issues here).

> a hotfix would've been much appreciated

As I said, had I saw the question half a day ago, it would have happened.

**Comment by navels** [comment]
> I only wish that were true more broadly (see basically every YGGtorrent issue here and on FlareSolverr, along with the 2k+ other duplicate issues here).

Okay . . . very fair lol ;-)

**Comment by garfield69** [comment]
v0.22.56
