### ISSUE TITLE
Error linking Sonarr and Jackett

### ISSUE THREAD

**Issue by sovajri7** [Jackett/Jackett#15368]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
- Using Jackett on Hetzner machine
- Using Flaresolverr
- No Proxy
- /config:/jackett
- Running on Docker using linuxserver/jackett
- Ubuntu 22.04 LTS
```

### Description

I'm trying to put the YGGtorrent tracker on Sonarr (same problem on Radarr) : 
- I get the Torznab Link and API after writting the Flaresolverr URL (working) on Jackett and then "Test" (OK), on Soanrr then "Test" is sometimes "OK" and sometimes "Error", same when saving.

Tried to change some categories but still the same.

I have the same configuration on another machine and IP, all was working fine on it and now not working with the same message.

### Logged Error Messages

```text
SONARR :
2024-06-04 02:31:23.3|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer: HTTP request failed: [400:BadRequest] [GET] at [http://100.117.79.155:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=tvsearch&cat=5000,5070,102145,102179&extended=1&apikey=(removed)&offset=0&limit=100]. Check the log surrounding this error for details

JACKETT :
06-04 00:31:26 Info Torznab search in YggTorrent => Found 124 releases [9235ms]

06-04 00:31:26 Error System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.

   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449

   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)

   at System.Linq.Enumerable.SelectListIterator`2.ToList()

   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/94976508/ae7ab082-dc2b-412b-8b05-c468f65ee569)
![image](https://github.com/Jackett/Jackett/assets/94976508/df96beb9-bc73-46dd-8bc6-f6e2f703add8)
![image](https://github.com/Jackett/Jackett/assets/94976508/8c0033d0-61f7-4922-b2b8-c99713d6bb5d)

**Comment by sovajri7** [comment]
I've seen that disabling cache is working sorry for duplicate.
