### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object. at Jackett.Server.Controllers.ResultsController.

### ISSUE THREAD

**Issue by elric667** [Jackett/Jackett#15370]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: /config
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: unknown)
File /etc/issue: Welcome to Alpine Linux 3.19
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
Environment version: 8.0.6 (/app/)
Jackett Data will be stored in: /config
Starting Jackett v0.22.43+f3b02a0bb0bad0bcf3d9db3cf600cc3fd4a38117
```

### Description

System.NullReferenceException: Object reference not set to an instance of an object. at Jackett.Server.Controllers.ResultsController.  After Upgrading to the Latest Version v0.22.43+f3b02a0bb0bad0bcf3d9db3cf600cc3fd4a38117

### Logged Error Messages

```text
2024-06-03 22:01:57	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
2024-06-03 22:01:33	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
2024-06-03 22:01:26	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
2024-06-03 22:01:26	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
2024-06-03 22:00:56	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
2024-06-03 22:00:54	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
2024-06-03 22:00:44	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
2024-06-03 22:00:29	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
2024-06-03 21:59:57	Error	
System.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.43.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ResultsController.<>c__DisplayClass18_0.<Torznab>b__3(ReleaseInfo r) in ./Jackett.Server/Controllers/ResultsController.cs:line 449
   at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 454
```

**Comment by garfield69** [comment]
related to #15364. Fix due out in about 50 minutes or so with the next release of Jackett.
