### ISSUE TITLE
[speedcd] (updating) Login failed.

### ISSUE THREAD

**Issue by norbsmaq** [Jackett/Jackett#15379]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolverr_url:8191
Using proxy: Disabled
App config/log directory: /home/machine/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.4.0.150 (64bit OS) (64bit process)
Environment version: 8.0.6 (/opt/Jackett/)
```

### Description

Add speed.cd tracker from the list.  Provider username and password in the fields.  Click Okay.  

Error window pops up with:
" An error occurred while updating this indexer
Login failed."

### Logged Error Messages

```text
System.Exception: Login failed.

[v0.22.56.0] System.Exception: Login failed.
   at Jackett.Common.Indexers.SpeedCD.<>c__DisplayClass27_0.<DoLogin>b__0() in ./Jackett.Common/Indexers/SpeedCD.cs:line 172
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 162
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in ./Jackett.Common/Indexers/SpeedCD.cs:line 161
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/SpeedCD.cs:line 121
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
Its a known issue with 0.22.56
Please upgrade to 0.22.58 which should resolve problem.

**Comment by norbsmaq** [comment]
It is working now.  Just wanted to say thanks for all you and the dev team do with this app!
