### ISSUE TITLE
[ncore] (updating) Error while trying to login.

### ISSUE THREAD

**Issue by johnnythebig** [Jackett/Jackett#15372]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Docker yes
version: Version v0.22.43+f3b02a0bb0bad0bcf3d9db3cf600cc3fd4a38117
```

### Description

By login i receive the error message failed to login, the two factor is disbaled on site ncore.pro and the password is correct

### Logged Error Messages

```text
[v0.22.43.0] Jackett.Common.ExceptionWithConfigData: Error while trying to login.
   at Jackett.Common.Indexers.NCore.<>c__DisplayClass27_0.<ApplyConfiguration>b__0() in ./Jackett.Common/Indexers/NCore.cs:line 148
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 162
   at Jackett.Common.Indexers.NCore.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/NCore.cs:line 142
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
This is a know issue with 0.22.43 which should be solved with the current release 0.22.56
Update your Jackett via the dashboard check-for-updates button and try again.

**Comment by garfield69** [comment]
Hmm. Unfortunately none of the current team have an account on ncore so we cannot test independently.
Please enable the Enhanced logging on the dashboard, and turn off the cache on the Jackett dashboard and see if that makes a difference. Untick the `Cache enabled (recommended):` box, tick the `Enhanced logging:` box,  and use the apply-server-settings button.
Repeat your test, and if it fails then provide the full log. Thanks.

**Comment by johnnythebig** [comment]
06-04 09:12:25 Info Loaded 611 indexers in total
06-04 09:12:25 Info Adding aggregate indexer ('all' indexer) ...
06-04 09:12:25 Info Adding filter indexer ('type:public' indexer) ...
06-04 09:12:25 Info Adding filter indexer ('type:private' indexer) ...
06-04 09:12:25 Info Adding filter indexer ('type:semi-public' indexer) ...
06-04 09:12:26 Info Jackett startup finished in 453.486 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
06-04 09:12:52 Error Jackett.Common.ExceptionWithConfigData: Error while trying to login.
[v0.22.56.0] Jackett.Common.ExceptionWithConfigData: Error while trying to login.
   at Jackett.Common.Indexers.NCore.<>c__DisplayClass27_0.<ApplyConfiguration>b__0() in ./Jackett.Common/Indexers/NCore.cs:line 148
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 162
   at Jackett.Common.Indexers.NCore.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/NCore.cs:line 142
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

**Comment by garfield69** [comment]
Is this really the enhanced log, I don't see expected Debug or HTML ?

**Comment by johnnythebig** [comment]
sorry this is the full log maybe to much..

[jackett_logs.txt](https://github.com/user-attachments/files/15544056/jackett_logs.txt)

**Comment by garfield69** [comment]
There is something broken with the login processing. Similar issue #15373

**Comment by johnnythebig** [comment]
thank you i see so the problem is on ncore site or in jacket code?

**Comment by garfield69** [comment]
Its Jackett, likely related to the upgrade to net8 or one of the tools that got bumped to a newer version, someplace.

**Comment by garfield69** [comment]
v0.22.58

**Comment by johnnythebig** [comment]
> v0.22.58

when will be that available on linuxservers.io?

**Comment by garfield69** [comment]
As soon as their automation fetches our source and builds their suite. Usually within the hour most of the time.

**Comment by johnnythebig** [comment]
Garfield! Thank you so so much for you work and any answers!

**Comment by ilike2burnthing** [comment]
LS.io run a check for updates every hour on the half hour, and it takes 15-20mins for the new image to be built and uploaded. We release a new build around 6am UTC each day, and the LS.io image is generally available by 6:50am.

In this case we released the hotfix build at 9:47, the next scheduled check was 10:30, and the image was up at 10:45.
