### ISSUE TITLE
[rutracker] (updating) The SSL connection could not be established, see inner exception.: Unable to read data from the transport connection: The remote host forcibly closed the existing connection

### ISSUE THREAD

**Issue by D3ZOXY** [Jackett/Jackett#15384]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-06-05 09:47:06 	Info 	Using HTTP Client: HttpWebClient2
2024-06-05 09:47:06 	Info 	Using FlareSolverr: No
2024-06-05 09:47:06 	Info 	Using proxy: Disabled
2024-06-05 09:47:06 	Info 	App config/log directory: C:\ProgramData\Jackett
2024-06-05 09:47:06 	Info 	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-06-05 09:47:06 	Info 	Running in Docker: No
2024-06-05 09:47:06 	Info 	Jackett variant: CoreWindows
2024-06-05 09:47:06 	Info 	OS version: Microsoft Windows NT 10.0.26100.0 (64bit OS)
2024-06-05 09:47:06 	Info 	Environment version: 8.0.6 (E:\Portable Jackett\)
2024-06-05 09:47:05 	Info 	Starting Jackett v0.22.66
```

### Description

It happens when I log in to rutracker.org (and other URLs). I can access this tracker from browser with and w/o set DNS.

### Logged Error Messages

```text
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

[v0.22.66.0] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: The remote host forcibly closed the existing connection.
 ---> System.Net.Sockets.SocketException (10054): The remote host forcibly closed the existing connection.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 615
   at Jackett.Common.Indexers.RuTracker.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/RuTracker.cs:line 1444
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
It is likely that something is picking on Jackett traffic and blocking your access. Likely defender or firewall or some other security app.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting/#an-existing-connection-was-forcibly-closed-by-the-remote-host for possible ideas to examine.

**Comment by D3ZOXY** [comment]
Here is enhanced logs.
https://pastebin.com/raw/LFsiELtc

**Comment by ilike2burnthing** [comment]
See the linked troubleshooting steps.

**Comment by D3ZOXY** [comment]
> See the linked troubleshooting steps.
I did all steps. No any problem. I don't know why I get this error. Help me please. I used Jackett some years ago, all was ok, but now I don't know what happened. I guess I need to reinstall the Windows.

**Comment by ilike2burnthing** [comment]
So on the same computer, and without using a proxy or VPN, you can access the following URLs in your browser?

https://rutracker.org/
https://rutracker.net/
https://rutracker.nl/

You have reconfigured the indexer to test all 3 of those links, and none work?

You have tried changing your DNS on Windows to Cloudflare, Google, etc., and that also didn't work with any of the URLs in Jackett?

You tried using a VPN or proxy?

You tried DNSCrypt?

You disabled your firewall, antivirus, or any content filtering either on your computer or router?

Do any public indexers work in Jackett? Try around 10 to make sure (add and test).
