### ISSUE TITLE
[wolfmax4k] (configuring) Could not find releases from this URL

### ISSUE THREAD

**Issue by Saratoga79** [Jackett/Jackett#15396]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Info Environment version: 8.0.6 (/app/)
Info OS version: Unix 3.10.108.0 (64bit OS) (64bit process)
Info Jackett variant: CoreLinuxMuslAmdx64
Info File /etc/issue: Welcome to Alpine Linux 3.19
Info Running in Docker: Yes (image build: Version v0.22.89 by hotio.dev)
Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Info App config/log directory: /config
Using proxy: Disabled
Info Using FlareSolverr: Yes
Info Using HTTP Client: HttpWebClient2
```

### Description

Indexer can not be added.

Looks similar to #15254

### Logged Error Messages

```text
[v0.22.89.0] System.Exception: Could not find releases from this URL
    at Jackett.Common.Indexers.Wolfmax4K.<>c.<ApplyConfiguration>b__21_0() in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 99
    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 162
    at Jackett.Common.Indexers.Wolfmax4K.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 98
    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14511#issuecomment-2156137505
