### ISSUE TITLE
[speedcd] Error parsing the login form

### ISSUE THREAD

**Issue by chitter99** [Jackett/Jackett#15393]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown	
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolverr:8191
Using proxy: Http
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.84-ls427)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.8.0.35 (64bit OS) (64bit process)
Environment version: 8.0.6 (/app/Jackett/)
Starting Jackett v0.22.89
```

### Description

I'm trying to login to speed.cd, looks like they changed their layout again. I'm on the latest release v0.22.89

### Logged Error Messages

```text
System.Exception: Error parsing the login form

[v0.22.89.0] System.Exception: Error parsing the login form
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in ./Jackett.Common/Indexers/SpeedCD.cs:line 143
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/SpeedCD.cs:line 121
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
The speed.cd indexer is working for me so this suggests the issue is at your end.
See if https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-selector helps you work out the issue.
Otherwise provide a full enhanced log and maybe the debug and HTML will give us a clue to what is going on.
See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by chitter99** [comment]
Indeed it was a mistake on my side. I had to use my email instead of my username. Thanks for your help! Closing the issue.
