### ISSUE TITLE
[wolfmax4k] (testing) Test search in Wolfmax 4k => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by davidpastorvicente** [Jackett/Jackett#15404]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Date	Level	Message
2024-06-11 23:44:23	Info	
Jackett startup finished in 14.220 s
2024-06-11 23:44:22	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2024-06-11 23:44:22	Info	
Adding filter indexer ('type:private' indexer) ...
2024-06-11 23:44:22	Info	
Adding filter indexer ('type:public' indexer) ...
2024-06-11 23:44:22	Info	
Adding aggregate indexer ('all' indexer) ...
2024-06-11 23:44:22	Info	
Loaded 615 indexers in total
2024-06-11 23:44:22	Info	
Loaded 543 Cardigann indexers.
2024-06-11 23:44:12	Info	
Loading Cardigann indexers from: /opt/jackett/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /opt/jackett/Definitions
2024-06-11 23:44:12	Info	
Loaded 72 Native indexers.
2024-06-11 23:44:12	Info	
Loading Native indexers ...
2024-06-11 23:44:12	Info	
Using HTTP Client: HttpWebClient2
2024-06-11 23:44:12	Info	
Using FlareSolverr: No
2024-06-11 23:44:12	Info	
Using proxy: Http
2024-06-11 23:44:12	Info	
App config/log directory: /opt/jackett/Jackett
2024-06-11 23:44:12	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-06-11 23:44:12	Info	
Running in Docker: No
2024-06-11 23:44:12	Info	
File /etc/issue: Debian GNU/Linux 12 \n \l
2024-06-11 23:44:12	Info	
Jackett variant: CoreLinuxArm64
2024-06-11 23:44:12	Info	
OS version: Unix 6.1.21.8 (64bit OS) (64bit process)
2024-06-11 23:44:12	Info	
Environment version: 8.0.6 (/opt/jackett/)
2024-06-11 23:44:09	Info	
Starting Jackett v0.22.103
```

### Description

Added Wolfmax4k and tested the indexer

### Logged Error Messages

```text	
System.Exception: Test search in Wolfmax 4k => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.22.103.0] System.Exception: Test search in Wolfmax 4k => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 331
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/14511
