### ISSUE TITLE
wolfmax4k: Exception (wolfmax4k): Specified argument was out of the range of valid values. (Parameter 'count')

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15418]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191/
Using proxy: Disabled
App config/log directory: C:\ProgramData\Jackett
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 8.0.6 (C:\ProgramData\Jackett\)
Starting Jackett v0.22.136
```

### Description

using Jackett dashboard to search wolfmax4k for `la familia addams S02` generates an error

### Logged Error Messages

```text
2024-06-16 19:07:46	Error	
Jackett.Common.IndexerException: Exception (wolfmax4k): Specified argument was out of the range of valid values. (Parameter 'count')

[v0.22.136.0] Jackett.Common.IndexerException: Exception (wolfmax4k): Specified argument was out of the range of valid values. (Parameter 'count')
 ---> System.Exception: Parse error
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'count')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.Range(Int32 start, Int32 count)
   at Jackett.Common.Indexers.Wolfmax4K.GetEpisodesFromTitle(String title) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 447
   at Jackett.Common.Indexers.Wolfmax4K.ExtractReleaseInfo(JObject item, TorznabQuery query) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 262
   at Jackett.Common.Indexers.Wolfmax4K.<>c__DisplayClass23_0.<PerformQuery>b__0(JToken item) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 149
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.Wolfmax4K.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 149
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 803
   at Jackett.Common.Indexers.Wolfmax4K.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 154
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 365
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 386
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 777
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in ./Jackett.Server/Controllers/ResultsController.cs:line 256
2024-06-16 19:07:45	Error	
Error on 20240616190745 for Wolfmax 4k.txtSystem.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'count')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.Range(Int32 start, Int32 count)
   at Jackett.Common.Indexers.Wolfmax4K.GetEpisodesFromTitle(String title) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 447
   at Jackett.Common.Indexers.Wolfmax4K.ExtractReleaseInfo(JObject item, TorznabQuery query) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 262
   at Jackett.Common.Indexers.Wolfmax4K.<>c__DisplayClass23_0.<PerformQuery>b__0(JToken item) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 149
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.Wolfmax4K.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Wolfmax4K.cs:line 149




{"response":true,"data":{"message":"Find : la familia addams","cidr":"Category : ","c":"Calidad : ","results":35,"datafinds":{"0":{"0":{"torrentName":"La familia Addams 2 [4K Webrip][2160p][HDR10][AC3 5.1 Castellano-AC3 5.1-Ingles+Subs][ES-EN]","guid":"descargar\/cine-alta-definicion-hd\/la-familia-addams-2\/4kwebrip\/","calidad":"4KWebrip","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/165913_-1641837783-La-familia-Addams-2--4KWebrip.jpg"},"1":{"torrentName":"La familia Addams (2019) [BluRay 720p X264 MKV][AC3 5.1 Castellano][www.atomixHQ.NET]","guid":"descargar\/peliculas-x264-mkv\/la-familia-addams-2019-\/bluray-microhd\/","calidad":"BluRay MicroHD","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/164687_-1640070261-La-familia-Addams--2019---BluRay-MicroHD.jpg"},"2":{"torrentName":"La familia Addams (1991) [BluRay 720p X264 MKV][AC3 5.1 Castellano][www.atomixHQ.NET]","guid":"descargar\/peliculas-x264-mkv\/la-familia-addams-1991-\/bluray-microhd\/","calidad":"BluRay MicroHD","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/164587_-1639983819-La-familia-Addams--1991---BluRay-MicroHD.jpg"},"3":{"torrentName":"La familia Addams [4K UHDremux][2160p][HDR10][DTS-HD 1.0 Castellano-DTS 5.1-Ingles+Subs][ES-EN]","guid":"descargar\/cine-alta-definicion-hd\/la-familia-addams\/4kuhdremux\/","calidad":"4KUHDremux","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/163241_-1638397041-La-familia-Addams--4KUHDremux.jpg"},"4":{"torrentName":"La Familia Addams [4K Webrip][2160p][HDR][AC3 5.1-Castellano-DTS 5.1-Ingles+Subs][ES-EN]","guid":"descargar\/cine-alta-definicion-hd\/la-familia-addams\/4kwebrip","calidad":"4KWebrip","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/133374_-1582043735-La-Familia-Addams--4KWebrip.jpg"},"5":{"torrentName":"La Familia Addams [MicroHD 1080p][AC3 5.1-Castellano-AC3 5.1-Ingles+Subs][ES-EN]","guid":"descargar\/cine-alta-definicion-hd\/la-familia-addams\/bluray-microhd","calidad":"BluRay MicroHD","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/133342_-1581976591-La-Familia-Addams--BluRay-MicroHD.jpg"},"6":{"torrentName":"La Familia Addams [BluRay 1080p][AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]","guid":"descargar\/cine-alta-definicion-hd\/la-familia-addams\/bluray-1080p","calidad":"BluRay 1080p","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/133341_-1581976535-La-Familia-Addams--BluRay-1080p.jpg"},"7":{"torrentName":"La Familia Addams [BDremux 1080p][AC3 5.1 Castellano-DTS 5.1 Ingles+Subs][ES-EN]","guid":"descargar\/cine-alta-definicion-hd\/la-familia-addams\/bdremux","calidad":"BDremux","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/133340_-1581976469-La-Familia-Addams--BDremux.jpg"},"8":{"torrentName":"La Familia Addams (2020) [BluRay 720p X264 MKV][AC3 5.1 Castellano][www.pctnew.ORG]","guid":"descargar\/peliculas-x264-mkv\/la-familia-addams-2020-\/bluray-microhd","calidad":"BluRay MicroHD","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/133338_-1581956596-La-Familia-Addams--2020---BluRay-MicroHD.jpg"},"9":{"torrentName":"La Familia Addams (2020) [BluRay RIP][AC3 5.1 Castellano][www.pctnew.ORG]","guid":"descargar\/peliculas-castellano\/la-familia-addams-2020-\/blurayrip-ac3-5-1","calidad":"BluRayRip AC3 5.1","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/133337_-1581956343-La-Familia-Addams--2020---BluRayRip-AC3-5-1.jpg"},"10":{"torrentName":"La Familia Addams (1991) [BluRay 720p X264 MKV][AC3 5.1 Castellano][www.descargas2020.ORG]","guid":"descargar\/peliculas-x264-mkv\/la-familia-addams-1991-","calidad":"BluRay MicroHD","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/f\/thumbs\/130971_-1576397383-La-Familia-Addams--1991---BluRay-MicroHD.jpg"},"11":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.219_220_221 FINAL]","guid":"serie\/la-familia-addams\/capitulo-\/16385\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"12":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.217_218]","guid":"serie\/la-familia-addams\/capitulo-\/16226\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"13":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.215_216]","guid":"serie\/la-familia-addams\/capitulo-\/15972\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"14":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.213_214]","guid":"serie\/la-familia-addams\/capitulo-\/15702\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"15":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.211_212]","guid":"serie\/la-familia-addams\/capitulo-\/15216\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"16":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.209_210]","guid":"serie\/la-familia-addams\/capitulo-\/15002\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"17":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.207_208]","guid":"serie\/la-familia-addams\/capitulo-\/14931\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"18":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.205_206]","guid":"serie\/la-familia-addams\/capitulo-\/14826\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"19":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.204]","guid":"serie\/la-familia-addams\/capitulo-\/14728\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"20":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.203]","guid":"serie\/la-familia-addams\/capitulo-\/14622\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"21":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.202]","guid":"serie\/la-familia-addams\/capitulo-\/14476\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"22":{"torrentName":"La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.201]","guid":"serie\/la-familia-addams\/capitulo-\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"23":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 120_121_122 FINAL][Spanish]","guid":"serie\/la-familia-addams\/capitulo-121-al-22\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"24":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 118_119][Spanish]","guid":"serie\/la-familia-addams\/capitulo-118-al-19\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"25":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 115][Spanish]","guid":"serie\/la-familia-addams\/capitulo-115\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"26":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 116_117][Spanish]","guid":"serie\/la-familia-addams\/capitulo-116-al-17\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"27":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 114][Spanish]","guid":"serie\/la-familia-addams\/capitulo-114\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"28":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 113][Spanish]","guid":"serie\/la-familia-addams\/capitulo-113\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"29":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 112][Spanish]","guid":"serie\/la-familia-addams\/capitulo-112\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"30":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 110][Spanish]","guid":"serie\/la-familia-addams\/capitulo-110\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"31":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 111][Spanish]","guid":"serie\/la-familia-addams\/capitulo-111\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"32":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 109][Spanish]","guid":"serie\/la-familia-addams\/capitulo-109\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"33":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 108][Spanish]","guid":"serie\/la-familia-addams\/capitulo-108\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"},"34":{"torrentName":"La Familia Addams - Temporada 1 [DVDRIP][Cap. 107][Spanish]","guid":"serie\/la-familia-addams\/capitulo-107\/","calidad":"HDTV","image":"https:\/\/wolfmax4k.com\/assets\/u\/p\/c\/thumbs\/945_la-familia-addams.jpg"}}}}}
```

**Comment by garfield69** [comment]
I suspect that the following json content is responsible 
```json
"11": {
	"torrentName": "La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.219_220_221 FINAL]",
	"guid": "serie/la-familia-addams/capitulo-/16385/",
	"calidad": "HDTV",
	"image": "https://wolfmax4k.com/assets/u/p/c/thumbs/945_la-familia-addams.jpg"
},
```

**Comment by garfield69** [comment]
I should note that fix d5e5014d823b7e36041efa79f3d76837c8ee68d5 bypasses the root cause rather than properly resolve the issue, which is that the wolfmax4k indexer is generating a title `La Familia Addams  [DVDRIP][Cap. 120_121_122 FINAL][Spanish] E121-E22 [HDTV] SPANISH` from `La Familia Addams - Temporada 2 [DVDRIP][Spanish][Cap.219_220_221 FINAL]`
and clearly E121-E22 is incorrect.
But I don't have the skills to diagnose that properly.

**Comment by garfield69** [comment]
@highfredo  would you take a look at this please and properly fix the issue which i have temporarily managed to hack a bypass.
Thanks.

**Comment by highfredo** [comment]
I take a look at the generation of the title.

Regarding chapters E121-E22 being parsed, yes, it seems to be because of guid.
Maybe I can implement that if the generation of episodes from guid does not make sense (the last episode is before the first) look at the title (the "Cap")

**Comment by garfield69** [comment]
v0.22.154

**Comment by garfield69** [comment]
v0.22.164
