### ISSUE TITLE
[pornolab] Fails parsing unseeded torrents

### ISSUE THREAD

**Issue by MikeLund** [Jackett/Jackett#15421]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.17.0.2:8191
Using proxy: Disabled
App config/log directory: /home/mikke/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Ubuntu 22.04.4 LTS
Jackett variant: CoreLinuxAmdx64
OS version: Unix 5.15.0.112 (64bit OS) (64bit process)
Environment version: 8.0.6 (/home/mikke/arr/Jackett/)
Starting Jackett v0.22.136
```

### Description

When a torrent has not had any seeds for a while, this tracker shows instead how long it has been since a seeder has been seen. In this example, it shows "1 дн." (had a seeder 1 day ago). This different markup causes Cardigann to fail as it gets a null value (the seedmed>b doesn't exist).

Jackett should ideally consider that it has 0 seeds, instead of failing as `null`.

Fail example: `<td class="row4 seedmed"><u>-1</u><span class="med" title="сида не было"><b class="small">1</b> дн.</span></td>`

How it normally looks like on torrents with seeds (works well): `<td class="row4 seedmed"><u>4</u><b class="seedmed">4</b></td>`

### Logged Error Messages

```text
CardigannIndexer (pornolab): Error while parsing row '
<tr class="tCenter">
	<td class="row1">
		<img src="//static.pornolab.net/templates/default/images/icon_minipost.gif" class="icon1" alt="o">
	</td>
	<td class="row1 tCenter" title="проверено">
		<span class="tor-icon tor-approved">√</span>
	</td>
	<td class="row1">
		<a class="gen f" href="tracker.php?f=1846">Сайтрипы 2021 (HD Video) / SiteRip's 2021 (HD Video)</a>
	</td>
	<td class="row4 med tLeft u">
		<div>
			<a class="med tLink bold" href="./viewtopic.php?t=2827272">[HollandscheP<wbr>assie.nl] Sasha (Een beurt voor de webcam) [2021-10-14, Hardcore, Cumshot, Toys, Blowjob, Dildo, Butt plug, 69, Handjob,
				<b>1080p</b>]</a>
		</div>
	</td>
	<td class="row1">
		<a class="med" href="tracker.php?pid=10291332">renni1128</a>
	</td>
	<td class="row4 small nowrap">
		<u>1606151428</u>
		<a class="small tr-dl dl-stub" href="dl.php?t=2827272">1.5&nbsp;GB</a>
	</td>
	<td class="row4 seedmed">
		<u>-1</u>
		<span class="med" title="сида не было">
			<b class="small">1</b>
			дн.</span>
	</td>
	<td class="row4 leechmed" title="Личи">
		<b>12</b>
	</td>
	<td class="row4 small">443</td>
	<td class="row4 small">
		<u>0</u>
	</td>
	<td class="row4 small nowrap" style="padding: 1px 3px 2px;" title="Добавлен">
		<u>1716087600</u>
		<p>04:00</p>
		<p>19-Май-24</p>
	</td>
</tr>':

System.Exception: Error while parsing field=seeders, selector=td.seedmed > b, value=<null>: Selector "td.seedmed > b" didn't match 
<tr class="tCenter">
	<td class="row1">
		<img src="//static.pornolab.net/templates/default/images/icon_minipost.gif" class="icon1" alt="o">
	</td>
	<td class="row1 tCenter" title="проверено">
		<span class="tor-icon tor-approved">√</span>
	</td>
	<td class="row1">
		<a class="gen f" href="tracker.php?f=1846">Сайтрипы 2021 (HD Video) / SiteRip's 2021 (HD Video)</a>
	</td>
	<td class="row4 med tLeft u">
		<div>
			<a class="med tLink bold" href="./viewtopic.php?t=2827272">[HollandscheP<wbr>assie.nl] Sasha (Een beurt voor de webcam) [2021-10-14, Hardcore, Cumshot, Toys, Blowjob, Dildo, Butt plug, 69, Handjob,
				<b>1080p</b>]</a>
		</div>
	</td>
	<td class="row1">
		<a class="med" href="tracker.php?pid=10291332">renni1128</a>
	</td>
	<td class="row4 small nowrap">
		<u>1606151428</u>
		<a class="small tr-dl dl-stub" href="dl.php?t=2827272">1.5&nbsp;GB</a>
	</td>
	<td class="row4 seedmed">
		<u>-1</u>
		<span class="med" title="сида не было">
			<b class="small">1</b>
			дн.</span>
	</td>
	<td class="row4 leechmed" title="Личи">
		<b>12</b>
	</td>
	<td class="row4 small">443</td>
	<td class="row4 small">
		<u>0</u>
	</td>
	<td class="row4 small nowrap" style="padding: 1px 3px 2px;" title="Добавлен">
		<u>1716087600</u>
		<p>04:00</p>
		<p>19-Май-24</p>
	</td>
</tr>
 ---> System.Exception: Selector "td.seedmed > b" didn't match 
<tr class="tCenter">
	<td class="row1">
		<img src="//static.pornolab.net/templates/default/images/icon_minipost.gif" class="icon1" alt="o">
	</td>
	<td class="row1 tCenter" title="проверено">
		<span class="tor-icon tor-approved">√</span>
	</td>
	<td class="row1">
		<a class="gen f" href="tracker.php?f=1846">Сайтрипы 2021 (HD Video) / SiteRip's 2021 (HD Video)</a>
	</td>
	<td class="row4 med tLeft u">
		<div>
			<a class="med tLink bold" href="./viewtopic.php?t=2827272">[HollandscheP<wbr>assie.nl] Sasha (Een beurt voor de webcam) [2021-10-14, Hardcore, Cumshot, Toys, Blowjob, Dildo, Butt plug, 69, Handjob,
				<b>1080p</b>]</a>
		</div>
	</td>
	<td class="row1">
		<a class="med" href="tracker.php?pid=10291332">renni1128</a>
	</td>
	<td class="row4 small nowrap">
		<u>1606151428</u>
		<a class="small tr-dl dl-stub" href="dl.php?t=2827272">1.5&nbsp;GB</a>
	</td>
	<td class="row4 seedmed">
		<u>-1</u>
		<span class="med" title="сида не было">
			<b class="small">1</b>
			дн.</span>
	</td>
	<td class="row4 leechmed" title="Личи">
		<b>12</b>
	</td>
	<td class="row4 small">443</td>
	<td class="row4 small">
		<u>0</u>
	</td>
	<td class="row4 small nowrap" style="padding: 1px 3px 2px;" title="Добавлен">
		<u>1716087600</u>
		<p>04:00</p>
		<p>19-Май-24</p>
	</td>
</tr>
   at Jackett.Common.Indexers.CardigannIndexer.handleSelector(selectorBlock Selector, IElement Dom, Dictionary`2 variables, Boolean required) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1250
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1818
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1843
```

**Comment by garfield69** [comment]
v0.22.154
