### ISSUE TITLE
[electro-torrent] (testing) Exception (electro-torrent): Login failed: Selector "a[href$="/logout.php"]" didn't match: Parse error

### ISSUE THREAD

**Issue by gacek1123** [Jackett/Jackett#15445]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett version v0.22.209
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://192.168.18.100:8191
Using proxy: Disabled
hreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreWindows	
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Environment version: 8.0.6 (C:\ProgramData\Jackett\)
```

### Description

1. Add Electro-Torrent and follow instructions to get cookie header
2. Paste the cookie and user-agent headers
3. Try to save

[Electro-Torrent](https://electro-torrent.pl/) loads and works just fine in browser

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href$="/logout.php"]" didn't match

[v0.22.209.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href$="/logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 895
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1054
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Windows cookie works for Windows Jackett for me, but not for my Docker Jackett. Docker Firefox cookie doesn't work for either. I also get very long `token_xxx` cookie depending on what I'm using. I tried switching back to credentials login, and while I can login with it, it then logs back out when searching.

I'll look into it more later, but I'm not hopeful.

**Comment by ilike2burnthing** [comment]
Ok, now Windows cookie doesn't work for Windows Jackett anymore. I'm assuming it's similar to the issues mentioned in https://github.com/Jackett/Jackett/issues/13951, for which the solution just seemed to be 'wait a day or few'.

**Comment by ilike2burnthing** [comment]
Working fine for me now. How about you?

**Comment by gacek1123** [comment]
@ilike2burnthing yup, seems to just work again. Thanks for the quick reply!
