### ISSUE TITLE
[yggtorrent] (testing) Exception (yggtorrent): Login failed: No form found on https://www.ygg.re/auth/login using form selector form[action="/auth/process_login"]: Parse error

### ISSUE THREAD

**Issue by BetyOops** [Jackett/Jackett#15462]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Starting Jackett v0.22.275
Environment version: 8.0.6 (/app/Jackett/)
OS version: Unix 6.1.0.17 (64bit OS) (64bit process)
Jackett variant: CoreLinuxMuslAmdx64
File /etc/issue: Welcome to Alpine Linux 3.20
Running in Docker: Yes (image build: v0.22.275-ls453)
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
App config/log directory: /config/Jackett
Using proxy: Disabled
Info Using FlareSolverr: http://localhost:8191/
Using HTTP Client: HttpWebClient2
```

### Description

Hi Dude !

Just try to check the Indexer status.

I've checked if an issue was already open.

### Logged Error Messages

```text
07-05 09:40:32 Error Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://www.ygg.re/auth/login using form selector form[action="/auth/process_login"]

[v0.22.275.0] Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://www.ygg.re/auth/login using form selector form[action="/auth/process_login"]

 ---> System.Exception: Parse error

 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.ygg.re/auth/login using form selector form[action="/auth/process_login"]

   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 617

   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1760

   --- End of inner exception stack trace ---

   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 828

   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1923

   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368

   --- End of inner exception stack trace ---

   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389

   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802

   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324

   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132

   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
@ilike2burnthing  is there a docker configuration where a docker jackett dashboard can have localhost as the address for accessing flaresolverr?

**Comment by BetyOops** [comment]
> @ilike2burnthing is there a docker configuration where a docker jackett dashboard can have localhost as the address for accessing flaresolverr?

hi @garfield69 

I didn't change my configuration since last night Jackett update threw watchtower.

Editing ip adress with http://192.168.2.32:8191/ seems to resolve my issue.

I didn't remember if before aotmotic update Jackett adress was localhost or ip adress....
