### ISSUE TITLE
Unknown error in download: System.Byte[] - SHAREWOOD API indexer

### ISSUE THREAD

**Issue by lukasb75** [Jackett/Jackett#15500]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS version: Unix 6.5.0.1025 (64bit OS)

Using HTTP Client: HttpWebClient2
Jackett variant: CoreLinuxMuslArm64
Environment version: 8.0.7 (/app/Jackett/)
Running in Docker: Yes (image build: v0.22.311-ls460)
App config/log directory: /config/Jackett
Proxy : Disable
Jackett - v0.22.336

Using FlareSolverr : Yes - v3.3.21
Using Sharewood API indexer

Using Stremio-Jackett addon - v4.1.6
```

### Description

Through Stremio-Jackett addon, when I carry out a search for a film or series I do not obtain any results on Stremio.
Looking at the logs I see that the problem comes from downloading torrent files.
See the error message log below.

I have this error for all links get from SharewoodAPI indexer.
But I can open each link in my browser to download correctly each file. 
Download Links from error logs.

However when I use the manual search, and click on download button for each link I have no problem.

### Logged Error Messages

```text
Error downloading. indexer: sharewoodapi path: https://www.sharewood.tv/api/e10792f48e06ec60faa10fa4118a7fc6/155/download
System.Exception: Unknown error in download: System.Byte[]
   at Jackett.Common.Indexers.Definitions.ShareWood.Download(Uri link) in ./Jackett.Common/Indexers/Definitions/Sharewood.cs:line 319
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 56
```

**Comment by garfield69** [comment]
Please turn on **enhanced** logging, repeat the download and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide a clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by lukasb75** [comment]
This is an example of one movie with Jackett enhanced debug :
It seems to be a 503 status code (Service Temporarily Unavailable).

2024-07-16 09:17:51.6596 Error Error downloading. indexer: sharewoodapi path: https://www.sharewood.tv/api/MY_API_KEY/64923/download
System.Exception: Unknown error in download: System.Byte[]
   at Jackett.Common.Indexers.Definitions.ShareWood.Download(Uri link) in ./Jackett.Common/Indexers/Definitions/Sharewood.cs:line 319
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 56
2024-07-16 09:17:51.6596 Info Executing StatusCodeResult, setting HTTP status code 404
2024-07-16 09:17:51.6596 Info Executed action Jackett.Server.Controllers.DownloadController.DownloadAsync (jackett) in 2058.9233ms
2024-07-16 09:17:51.6596 Info Executed endpoint 'Jackett.Server.Controllers.DownloadController.DownloadAsync (jackett)'
2024-07-16 09:17:51.6596 Debug Connection id "0HN55D0GDT868" completed keep alive response.
2024-07-16 09:17:51.6596 Info Request finished HTTP/1.1 GET http://XXX.XX.XXX.XX:9117/dl/sharewoodapi/?jackett_apikey=(removed)&path=Q2ZESjhIbGQ3NTVnQXhKS3NmRWMyTGF4NUQ5VlRCaVdPTnphckVGRXRuY2EzR3Yxc3RPamp2LTJId2ZINkVibENGV2RQSE52MVVUOWM1bC14TXRKNnFjdU15VDlXUUVIZ0J4bVVUOEFlbzktUUpCSl9idnBTbnJBaFhKUjN1Y3VpQTk1OEtnQkdrMlUzRHJvOGllT3dtX1Z0UDNRSk9Nbks4TDMwZnIxNFBOV3N1aXg4cWFxYkhSdTdfbXBHTG1iT2JpQjVhY1JrRjFoZG54ZHBYUFNUelMzSzZV&file=Avatar+The+Way+of+Water+2022+MULTi+2160p+WEB+H265+DV+HDR+ATMOS-Sicario+(Avatar+%3A+La+voie+de+l%27eau) - 404 0 - 2071.0377ms
2024-07-16 09:17:51.6670 Debug WebClient(HttpWebClient2): Returning ServiceUnavailable => 592 bytes
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>






2024-07-16 09:17:51.6670 Debug WebClient(HttpWebClient2): Returning ServiceUnavailable => 592 bytes
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by lukasb75** [comment]
Could be a problem when it try to download multiples torrent files for the same result in short times ?

**Comment by garfield69** [comment]
the rate limit is 1 request per second.

**Comment by lukasb75** [comment]
Which file should be modify ?
I am using Docker, where are located the src files ?

**Comment by lukasb75** [comment]
Thank for your help.
How can I update and test it ?

**Comment by garfield69** [comment]
>I think we should add support for rate limiting for downloads separated from searching with a minimum value of 2 seconds at all times.

Sounds useful. `downloadDelay` ?

**Comment by garfield69** [comment]
v0.22.342
