### ISSUE TITLE
[chdbits] (testing) Test search in CHDBits => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by iNfRaS0NiC** [Jackett/Jackett#15524]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

nothing provided by OP

### Description

CHDBits indexer is not working. 

### Logged Error Messages

```text
System.Exception: Test search in CHDBits => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.22.416.0] System.Exception: Test search in CHDBits => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 332
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```
```markdown
CardigannIndexer (chdbits): Error while parsing row '
<tr class="halfdown_bg">
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=401">
			<img class="c_movies" src="pic/cattrans.gif" alt="Movies" title="Movies" style="background-image: url(pic/category/chd/scenetorrents/chs/catsprites.png);">
		</a>
		<a href="?cat401=1&amp;medium1=1">
			<img src="pic/cattrans.gif" alt="1" title="1" style="background-image: url(pic/Bluray.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr class="halfdown_bg">
					<td class="embedded">
						<a title="Exhuma 2024 1080p BluRay AVC DTS-HD MA 5.1-Parker@CHDBits" href="details.php?id=(removed)&amp;hit=1">
							<b>Exhuma 2024 1080p BluRay AVC DTS-HD MA 5.1-Parker@CHDBits</b>
						</a>
					</td>
					<td width="50" class="embedded" align="center" valign="middle" style="text-align: right;font-size:10px; line-height:20px">
						<br>
						<img src="pic/imdb.gif" style=" width:18px; height:10px;padding-right : 2px;">7.4</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2024-07-29<br>22:47:08</td>
	<td class="rowfollow">35.29<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">181</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>836</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>匿名</i>
	</td>
	<td class="rowfollow">--</td>
</tr>':

System.Exception: Error while parsing field=download, selector=a[href^="download.php?id="], value=<null>: Selector "a[href^="download.php?id="]" didn't match 
<tr class="halfdown_bg">
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=401">
			<img class="c_movies" src="pic/cattrans.gif" alt="Movies" title="Movies" style="background-image: url(pic/category/chd/scenetorrents/chs/catsprites.png);">
		</a>
		<a href="?cat401=1&amp;medium1=1">
			<img src="pic/cattrans.gif" alt="1" title="1" style="background-image: url(pic/Bluray.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr class="halfdown_bg">
					<td class="embedded">
						<a title="Exhuma 2024 1080p BluRay AVC DTS-HD MA 5.1-Parker@CHDBits" href="details.php?id=(removed)&amp;hit=1">
							<b>Exhuma 2024 1080p BluRay AVC DTS-HD MA 5.1-Parker@CHDBits</b>
						</a>
					</td>
					<td width="50" class="embedded" align="center" valign="middle" style="text-align: right;font-size:10px; line-height:20px">
						<br>
						<img src="pic/imdb.gif" style=" width:18px; height:10px;padding-right : 2px;">7.4</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2024-07-29<br>22:47:08</td>
	<td class="rowfollow">35.29<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">181</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>836</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>匿名</i>
	</td>
	<td class="rowfollow">--</td>
</tr>
 ---> System.Exception: Selector "a[href^="download.php?id="]" didn't match 
<tr class="halfdown_bg">
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=401">
			<img class="c_movies" src="pic/cattrans.gif" alt="Movies" title="Movies" style="background-image: url(pic/category/chd/scenetorrents/chs/catsprites.png);">
		</a>
		<a href="?cat401=1&amp;medium1=1">
			<img src="pic/cattrans.gif" alt="1" title="1" style="background-image: url(pic/Bluray.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr class="halfdown_bg">
					<td class="embedded">
						<a title="Exhuma 2024 1080p BluRay AVC DTS-HD MA 5.1-Parker@CHDBits" href="details.php?id=(removed)&amp;hit=1">
							<b>Exhuma 2024 1080p BluRay AVC DTS-HD MA 5.1-Parker@CHDBits</b>
						</a>
					</td>
					<td width="50" class="embedded" align="center" valign="middle" style="text-align: right;font-size:10px; line-height:20px">
						<br>
						<img src="pic/imdb.gif" style=" width:18px; height:10px;padding-right : 2px;">7.4</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2024-07-29<br>22:47:08</td>
	<td class="rowfollow">35.29<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">181</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>836</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>匿名</i>
	</td>
	<td class="rowfollow">--</td>
</tr>
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.handleSelector(selectorBlock Selector, IElement Dom, Dictionary`2 variables, Boolean required) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1265
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1837
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1862
```

**Comment by garfield69** [comment]
None of the team have an account on this site so you will need to conform the following for us before we proceed to try updating the indexer.
Right now, from the log you provided, it appears that the download link in no longer present on the torrents search page.
Please confirm that you still have a good ratio on the site, that you do not have any hit and run penalties, or anything else that may prevent you from downloading torrents on this site.
Check you PM for warning or info mail, and your profile for similar.
If your account is in good stead, then please access any of the torrents details page, and confirm that the download link is present on that page.
Hover your mouse over the download link, and right click and select the inspect option.
look at the href and confirm that it still looks like `href="download.php?id=123456"`
Thanks.

**Comment by iNfRaS0NiC** [comment]
@garfield69,
Here is the href - 
![08 August at 10 28 26](https://github.com/user-attachments/assets/7b261b32-7790-4ccc-a762-a915c9c859e5)

Also, I am an elite user of that indexer and I can download torrents.
![08 August at 10 29 44](https://github.com/user-attachments/assets/2f091f9a-2d84-4116-9071-f9f36fa80c71)

**Comment by garfield69** [comment]
Excellent.
I will update the indexer to fetch the download link from the details page instead of looking for it on the torrents search page.
The update will be available with the next release of Jackett, which is next due in about 22 hours or so.

**Comment by garfield69** [comment]
v0.22.425

**Comment by garfield69** [comment]
v0.22.427

**Comment by iNfRaS0NiC** [comment]
@garfield69 thanks for your efforts, unfortunately even with v0.22.427 the issue is still there

> CardigannIndexer (chdbits): Error while parsing row '
<tr>
	<td class="rowfollow nowrap" valign="middle" style="padding: 0px">
		<a href="?cat=402">
			<img class="c_tvseries" src="pic/cattrans.gif" alt="TV Series" title="TV Series" style="background-image: url(pic/category/chd/scenetorrents/chs/catsprites.png);">
		</a>
		<a href="?cat402=1&amp;medium19=1">
			<img src="pic/cattrans.gif" alt="19" title="19" style="background-image: url(pic/4kuhd.png);">
		</a>
	</td>
	<td class="rowfollow" width="100%" align="left">
		<table class="torrentname" width="100%">
			<tbody>
				<tr>
					<td class="embedded">
						<a title="House of the Dragon 2022 S01 Disc3 2160p UHD Blu-ray DV HDR HEVC Atmos TrueHD 7.1-PWt@OurBits" href="details.php?id=(removed)&amp;hit=1">
							<b>House of the Dragon 2022 S01 Disc3 2160p UHD Blu-ray DV HDR HEVC Atmos TrueHD 7.1-PWt@OurBits</b>
						</a>
					</td>
					<td width="50" class="embedded" align="center" valign="middle" style="text-align: right;font-size:10px; line-height:20px">
						<br>
						<img src="pic/imdb.gif" style=" width:18px; height:10px;padding-right : 2px;">8.8</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td class="rowfollow nowrap">2022-12-24<br>00:00:01</td>
	<td class="rowfollow">86.36<br>GB</td>
	<td class="rowfollow" align="center">
		<b>
			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">3</a>
		</b>
	</td>
	<td class="rowfollow">0</td>
	<td class="rowfollow">
		<a href="viewsnatches.php?id=(removed)">
			<b>138</b>
		</a>
	</td>
	<td class="rowfollow">
		<i>匿名</i>
	</td>
	<td class="rowfollow">--</td>
</tr>':

System.Exception: Error while parsing field=date, selector=, value=86.36GB +08:00: DateTime parsing failed for "86.36GB +08:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 221
 ---> System.Exception: DateTime parsing failed for "86.36GB +08:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 221
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 225
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ParseFields(String value, String FieldName, ReleaseInfo release, List`1 FieldModifiers, Uri searchUrlUri) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 2294
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1849
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1862

**Comment by garfield69** [comment]
That's what can happen when one cannot test changes before publishing ;-(
I'll take a look at the log you provided when I've next got free time and see if I can spot the mistake ;-)

**Comment by iNfRaS0NiC** [comment]
No problem, just letting you know, thanks, you work is much appreciated and I can and will provide more information if needed.

**Comment by garfield69** [comment]
v0.22.431

**Comment by iNfRaS0NiC** [comment]
@garfield69 working flawlessly now, thank you.

**Comment by sk7628** [comment]
Test search in HD Dolby => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
