### ISSUE TITLE
[Spirit of Revolution] javascript check blocks downloads

### ISSUE THREAD

**Issue by s0mm3rb** [Jackett/Jackett#15533]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.442-ls496)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.15.0.105 (64bit OS) (64bit process)
Environment version: 8.0.7 (/app/Jackett/)
```

### Description

jackett can't grab release, because of a javascript verification on download
the search successfully shows the releases

here is the html example of a download attempt:

```html
<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN'
        'http://www.w3.org/TR/html4/loose.dtd'>
<html>
  <head>
    <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
    <meta http-equiv='pragma' content='no-cache'>
    <meta http-equiv='expires' content='300'>
    <meta http-equiv='cache-control' content='private'>
    <meta name='robots' content='noindex, nofollow, noarchive'>
    <meta name='MSSmartTagsPreventParsing' content='true'>
    <meta http-equiv='refresh' content='5; URL=./noscript.php'>
	<style type="text/css">
	@import 'https://fonts.googleapis.com/css?family=Shojumaru';
body {
  background: #262626;
  overflow-x: hidden;
  font-family: 'Shojumaru', cursive;
  padding: 40px;
  text-align: center;
}
.words {
  color: #262626;
  font-size: 0;
  line-height: 1;
  text-align: center;
}
.words span {
  font-size: 150px;
  display: inline-block;
  -webkit-animation: move 2s ease-in-out infinite;
          animation: move 2s ease-in-out infinite;
}
.words span:nth-child(2) {
  animation-delay: 0.5s;
}
.words span:nth-child(3) {
  animation-delay: 1s;
}
.words span:nth-child(4) {
  animation-delay: 1.5s;
}
.words span:nth-child(5) {
  animation-delay: 2.0s;
}
.words span:nth-child(6) {
  animation-delay: 2.5s;
}
.words span:nth-child(7) {
  animation-delay: 3.0s;
}
.words span:nth-child(8) {
  animation-delay: 3.5s;
}
.words span:nth-child(9) {
  animation-delay: 4.0s;
}
.words span:nth-child(10) {
  animation-delay: 4.5s;
}
@keyframes move {
  0% {
    -webkit-transform: translate(-33%, 0);
            transform: translate(-33%, 0);
  }
  50% {
    text-shadow: 0 15px 40px rgba(0, 0, 0, 0.6);
  }
  100% {
    -webkit-transform: translate(33%, 0);
            transform: translate(33%, 0);
  }
}
* {
  box-sizing: border-box;
}
.start{
	font-size: 200%;
	color: #fff;
	margin-top: 150px;
}
</style>

	<link rel="shortcut icon" href="favicon.ico" >
	<title>Spirit of Revolution</title>
  </head>
  <body>
<div style="margin-top: 150px;">
<div class="words words-1">
	<span>S</span>
	<span>p</span>
	<span>i</span>
	<span>r</span>
	<span>i</span>
	<span>t</span>
</div>
<div class="words words-1">
	<span>o</span>
	<span>f</span>
</div>
<div class="words words-1">
	<span>R</span>
	<span>e</span>
	<span>v</span>
	<span>o</span>
    <span>l</span>
	<span>u</span>
	<span>t</span>
	<span>i</span>
	<span>o</span>
	<span>n</span>
</div>
</div>
    <script type="text/javascript">	
		setTimeout(function() {
			window.location.href='jscheck.php?java=1&ref='
		}, 2500);
    </script>

	<div class="start">Javascript wird geprüft.....</div>
  </body>
</html>
``` 

Debug Log:
```
Request starting HTTP/1.1 GET http://172.18.0.7:9117/dl/spiritofrevolution/?jackett_apikey=(removed)&path=redacted&file=redacted - - -
Request is continuing in applying rules. Current url is http://172.18.0.7:9117/dl/spiritofrevolution/?jackett_apikey=(removed)&path=redacted&file=redacted
Request is continuing in applying rules. Current url is http://172.18.0.7:9117/dl/spiritofrevolution/?jackett_apikey=(removed)&path=redacted&file=redacted
Request is continuing in applying rules. Current url is http://172.18.0.7:9117/dl/spiritofrevolution/?jackett_apikey=(removed)&path=redacted&file=redacted
The request path /dl/spiritofrevolution/ does not match a supported file type
AuthenticationScheme: Cookies was not authenticated.
1 candidate(s) found for the request path '/dl/spiritofrevolution/'
Endpoint 'Jackett.Server.Controllers.DownloadController.DownloadAsync (jackett)' with route pattern 'dl/{indexerId}' is valid for the request path '/dl/spiritofrevolution/'
Request matched endpoint 'Jackett.Server.Controllers.DownloadController.DownloadAsync (jackett)'
Executing endpoint 'Jackett.Server.Controllers.DownloadController.DownloadAsync (jackett)'
Route matched with {action = "Download", controller = "Download"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] DownloadAsync(System.String, System.String, System.String, System.String) on controller Jackett.Server.Controllers.DownloadController (jackett).
Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Execution plan of resource filters (in the following order): None
Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Jackett.Server.ActionFilters.DownloadActionFilter (Order: 0), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter
Execution plan of exception filters (in the following order): None
Execution plan of result filters (in the following order): Jackett.Server.ActionFilters.DownloadActionFilter (Order: 0)
Executing controller factory for controller Jackett.Server.Controllers.DownloadController (jackett)
Executed controller factory for controller Jackett.Server.Controllers.DownloadController (jackett)
Attempting to bind parameter 'indexerId' of type 'System.String' ...
Attempting to bind parameter 'indexerId' of type 'System.String' using the name 'indexerId' in request data ...
Done attempting to bind parameter 'indexerId' of type 'System.String'.
Done attempting to bind parameter 'indexerId' of type 'System.String'.
Attempting to validate the bound parameter 'indexerId' of type 'System.String' ...
Done attempting to validate the bound parameter 'indexerId' of type 'System.String'.
Attempting to bind parameter 'path' of type 'System.String' ...
Attempting to bind parameter 'path' of type 'System.String' using the name 'path' in request data ...
Done attempting to bind parameter 'path' of type 'System.String'.
Done attempting to bind parameter 'path' of type 'System.String'.
Attempting to validate the bound parameter 'path' of type 'System.String' ...
Done attempting to validate the bound parameter 'path' of type 'System.String'.
Attempting to bind parameter 'jackett_apikey' of type 'System.String' ...
Attempting to bind parameter 'jackett_apikey' of type 'System.String' using the name 'jackett_apikey' in request data ...
Done attempting to bind parameter 'jackett_apikey' of type 'System.String'.
Done attempting to bind parameter 'jackett_apikey' of type 'System.String'.
Attempting to validate the bound parameter 'jackett_apikey' of type 'System.String' ...
Done attempting to validate the bound parameter 'jackett_apikey' of type 'System.String'.
Attempting to bind parameter 'file' of type 'System.String' ...
Attempting to bind parameter 'file' of type 'System.String' using the name 'file' in request data ...
Done attempting to bind parameter 'file' of type 'System.String'.
Done attempting to bind parameter 'file' of type 'System.String'.
Attempting to validate the bound parameter 'file' of type 'System.String' ...
Done attempting to validate the bound parameter 'file' of type 'System.String'.
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://sor-next.tk/download_ssl.php?torrent=redacted)
WebClient(HttpWebClient2): Returning Found => https://sor-next.tk/?returnto=%2Fdownload_ssl.php%3Ftorrent%3Dredacted 0 bytes
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://sor-next.tk/?returnto=%2Fdownload_ssl.php%3Ftorrent%3Dredacted)
PHPSESSID=redacted; path=/
WebClient(HttpWebClient2): Returning Found => https://sor-next.tk/jscheck.php 13396 bytes
``` 

and the debug html
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="noindex, nofollow, noarchive" />
<meta name="MSSmartTagsPreventParsing" content="true" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />

<script type="text/javascript" src="js/jquery_timer.js"></script>

<script type="text/javascript" src="js/overlib.js"></script>
<script type="text/javascript" src="js/slide_in.js"></script>
<script type="text/javascript" src="js/external.js"></script>
<script type="text/javascript" src="js/ajax.js"></script>
<script type="text/javascript" src="js/ajaxtabs.js"></script>
<link rel="stylesheet" type="text/css" href="layout/layout_first/alle.css" />

  <link type="text/css" rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"  />
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script type="text/javascript">
  $( function() {
    $( "#datepicker" ).datepicker({
		prevText: "zurück",nextText: "vor",
		dateFormat: "dd.mm.yy",
		dayNames: ['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],
		monthNames: ['Januar','Februar','März','April','Mai','Juni',
		'Juli','August','September','Oktober','November','Dezember'],
		dayNamesShort: ['So','Mo','Di','Mi','Do','Fr','Sa'],
		dayNamesMin: ['So','Mo','Di','Mi','Do','Fr','Sa'],
		firstDay: 1,showWeek: true,weekHeader: "Wo",
	});
		
  } );
  </script>

<script type="text/javascript" src="../highslide/highslide-full.js"></script>
<link rel="stylesheet" type="text/css" href="../highslide/highslide.css" />
<script type="text/javascript">
hs.graphicsDir = '../highslide/graphics/';
hs.outlineType = 'rounded-white';
hs.wrapperClassName = 'draggable-header';

hs.lang = {
	cssDirection: 'ltr',
	loadingText: 'Lade...',
	loadingTitle: 'Klick zum Abbrechen',
	focusTitle: 'Klick um nach vorn zu bringen',
	fullExpandTitle: 'Zur Originalgröße erweitern',
	creditsText: '',
	creditsTitle: '',
	previousText: 'Voriges',
	nextText: 'Nächstes',
	moveText: 'Verschieben',
	closeText: 'Schließen',
	closeTitle: 'Schließen (Esc)',
	resizeTitle: 'Größe wiederherstellen',
	playText: 'Abspielen',
	playTitle: 'Slideshow abspielen (Leertaste)',
	pauseText: 'Pause',
	pauseTitle: 'Pausiere Slideshow (Leertaste)',
	previousTitle: 'Voriges (Pfeiltaste links)',
	nextTitle: 'Nächstes (Pfeiltaste rechts)',
	moveTitle: 'Verschieben',
	fullExpandText: 'Vollbild',
	number: 'Bild %1 von %2',
	restoreTitle: 'Klick um das Bild zu schließen, klick und ziehe um zu verschieben. Benutze Pfeiltasten für vor und zurück.'
}
</script>
	
<script type="text/javascript" src="js/animateClick.js"></script>
<script type="text/javascript">
$(document).ready(function() {
	$('#btn5').animateClick({
		"color":"White",
		"animation":"shoot"
	});
	$('#upp5').animateClick({
		"color":"White",
		"animation":"shoot"
	});
});
</script>
<link rel="stylesheet" href="layout/layout_first/css/master.css.php" type="text/css" />

<link rel="shortcut icon" href="favicon.ico" />
<title>Spirit of Revolution</title>

<script type='text/javascript'>
	
		function onload_func() {
		UR_Start();
				countdown();
				}
		
		function onload_func_slide() {
		UR_Start();
				slider.init('slider',1);
		countdown();
				}
		
		var jahr=1970, monat=1, tag=1, stunde=1, minute=00, sekunde=00; // Ziel-Datum in MEZ
		var zielDatum=new Date(jahr,monat-1,tag,stunde,minute,sekunde);
		</script>

</head>

	<body onload="onload_func()" id="bodeli">
	
<script type="text/javascript" src="js/ajaxframes.js"></script>
<script type='text/javascript'>
	
		function onload_func() {
		UR_Start();
				countdown();
				}
		
		function onload_func_slide() {
		UR_Start();
				slider.init('slider',1);
		countdown();
				}
		
		var jahr=1970, monat=1, tag=1, stunde=1, minute=00, sekunde=00; // Ziel-Datum in MEZ
		var zielDatum=new Date(jahr,monat-1,tag,stunde,minute,sekunde);
		</script>
<script type='text/javascript'>
	if(top!=self)
	top.location=self.location;
  
	function show_confirm_head(obj){
		var r=confirm("Bist du dir sicher?");
		if (r==true){ 
			document.location.href=obj.href;
		}
		else 
		{}
	}

	function UR_Start() {
		UR_Nu = new Date;
		UR_Indhold = showFilled(UR_Nu.getHours()) + ":" + showFilled(UR_Nu.getMinutes()) + ":" + showFilled(UR_Nu.getSeconds());
		document.getElementById("ur").innerHTML = UR_Indhold;
		setTimeout("UR_Start()",1000);
	}
	function showFilled(Value) {
		return (Value > 9) ? "" + Value : "0" + Value;
	}
	
	var widdi = document.body.offsetWidth;
	var endTop = 0;
	var endLeft = (widdi / 2) -280;
	
	
</script>
<link rel="stylesheet" type="text/css" href="/tsstatus/ts3ssv.css" />
<script type="text/javascript" src="/tsstatus/ts3ssv.js"></script>
<div class="tab-main" style="top:350px;height: auto;"><img src="https://sor-next.tk/layout/layout_first/css/images/32x32_info.png" alt="Info" /><img src="https://sor-next.tk/layout/layout_first/teamspeak3logo.png.png" alt="TS" style="max-width: 32px;vertical-align: middle;" />
	<div class="tab-container">
		<div class="tab-inhalt" style="height: auto;">
			Guten Morgen , <span style="color:#; font-size:13px;"></span><br />
			es ist: Mittwoch, 14.08.2024 - <span id="ur"></span><br /><br />
			<div class="g_strich_navi_40" style="width: 250px;"></div><br />
			<img src="layout/layout_first/sel_up.png" onmouseover="return overlib('Aktuell im Upload');" onmouseout="return nd();" alt="" style="float:left;margin-top:2px;" />&nbsp;Aktuell im Seed:  Torrents<br />			
			<img src="layout/layout_first/sel_down_red.png" onmouseover="return overlib('Aktuell im Download');" onmouseout="return nd();" alt="" style="float:left;margin-top:2px;" />&nbsp;Aktuell im Download:  Torrents<br />
			<a href="time-logs.php"><img src="https://sor-next.tk/layout/layout_first/css/images/32x32_uhr.png" style="max-width: 20px;float:left;margin-top:1px;" alt="Zeit" onmouseover="return overlib('Zeitgutschriften von Heute und Gestern');" onmouseout="return nd();" />&nbsp;Zeitgutschriften</a><br /><br />
			<div class="g_strich_navi_40" style="width: 250px;"></div><br />
			Deine Restzeit:<br />
			Jahre - Mon. -Tage- Std - Min - Sek
			<div id="yes_time_show" style="display:none;">00<span id="time_aaa"></span> - <span id="time_bbb"></span> - <span id="time_aa"></span> - <span id="time_bb"></span> - <span id="time_cc"></span> - <span id="time_dd"></span></div>
			<div id="no_time_show"><input id="in_time" style="color:red;text-shadow: 0px 0px 5px red, -1px -1px #000;"onfocus="if(this.blur)this.blur()" /></div>
			<br /><div class="g_strich_navi_40" style="width: 250px;"></div><br />
			<div id="tt2ajax_f_redacted" style="display:inline;"></div>
<script type="text/javascript">
    tt2ajax_frames.init_ajaxframe('redacted',30,'index_ts_sor.php');
  </script>
 		</div>
	</div>
</div><div id="redacted" style="display:inline;"></div>
<script type="text/javascript">
    tt2ajax_frames.init_ajaxframe('redacted',30,'ajax_pm_info.php');
  </script>
 	<div id="mitte">	<div id="back_opa" style="width:1500px; height:1500px"></div>
	<!--<div id="overDiv"></div> -->

	<div id="popup"><a href="#nogo" onclick="hideEl('popup');" class="del_24" style="position:absolute;margin:-15px 0 0 450px;"></a><span style="font-size:15px;color: #ffc328;"></span></div>
	
			<div id="header">
				<div id="logo_pic">
									<a href="index.php"><img src="/layout/layout_first/css/logo_sor.png" alt="Header" style="max-width:700px;" /></a>
							</div>
		</div>
 <div id="main" style="margin-left: 110px;margin-right: 110px;"><div id="loading-layer" class="lod_aj_div"></div>


		<div class="content_wrap"><div class="ecke_lo"></div><div class="ecke_ro"></div>
			<div class="tabtitle_mitte">..:: Aktuelle - News ::..  </div><br />
	<div class="tabs" style="justify-content: center;">
							<input checked="checked" type="radio" name="tabs" id="tab_1" />
					<label class="std_button" for="tab_1" style="padding: 10px;border-radius: 5px;">News vom 03.08.24 <div style="float:right;"></div></label>
					
				<div class="tab" style="background: none;box-shadow: none;padding:10px 0 0 0;">
					<div style="border-radius: 10px;box-shadow: 0 0 10px rgba(0,0,0,0.8),inset 0 1px 0 rgba(225,225,225,0.15),inset 0 0 2px rgba(225,225,225,0.1);padding: 10px;">
						<div>03.08.2024 - 16:45 Uhr von <span style='color:#D60000;'><b>Hooligan</b></span></div>			
						<p style="text-align: center;"><span style="color: #e03e2d;"><a style="color: #e03e2d;" href="https://www.kicktipp.de/sor-2324/"><span style="font-size: 18pt;">https://www.kicktipp.de/sor-2324/</span></a></span></p>
<p style="text-align: center;"><span style="color: #ffffff; font-size: 18pt;">Hier habt ihr nun die M&ouml;glichkeit euch anzumelden</span></p>
<p style="text-align: center;"><span style="color: #ffffff; font-size: 18pt;">Die neue Saison startet am 23.8.24</span></p>
<p style="text-align: center;"><span style="color: #ffffff; font-size: 18pt;">Bereits registrierte User sind automatisch dabei</span></p>
<p style="text-align: center;"><span style="color: #ffffff; font-size: 18pt;">Nat&uuml;rlich gibt es auch Zeitgutschriften zu gewinnen</span></p>
<p style="text-align: center;"><span style="color: #e03e2d; font-size: 18pt;">P.S bitte nur euren Usernamen verwenden da sonst das Spiel ung&uuml;ltig ist</span></p>
<p style="text-align: center;">&nbsp;</p>					</div>
				</div>
							  
		<br style="clear:both;" />
	</div>
<br /><div class="ecke_lu"></div><div class="ecke_ru"></div>
		</div>
		<div class="content_wrap"><div class="ecke_lo"></div><div class="ecke_ro"></div>
			<div class="tabtitle_mitte">..:: Torrents ::..</div><br />		
		<div style="margin: -57px 15px 0px 0px;float:right;">
			<form name="searchform" method="get" action="selection.php" title=""> 
				<input type="hidden" name="incldead" value="1" />
				<input type="hidden" name="showsearch" value="1" />
				<input style="width:400px;padding: 5px 0px 5px 5px;" class="tipfeld" type="text" name="search" title="" onmouseover="return overlib('schnelle Suche.....');" onmouseout="return nd();" placeholder="Schnelle Torrentsuche" />&nbsp;&nbsp;
				<input type="image" src="pic/icon/lupe.gif" alt="Suche" value="suchen" style="vertical-align: middle;" />
			</form>
		</div>

<ul id="maintab" class="shadetabs">
	<li class="selected"><a href="torrentlisten.php?action=last&amp;anz=36" rel="ajaxcontentarea">Heute Neu (29)</a></li>
	<li><a href="torrentlisten.php?action=day&amp;stunden=24" rel="ajaxcontentarea">Alle von 24 Stunden (139)</a></li>
	<li><a href="torrentlisten.php?action=filme&amp;anz=36" rel="ajaxcontentarea">Filme</a></li>
	<li><a href="torrentlisten.php?action=serien&amp;anz=36" rel="ajaxcontentarea">Serien</a></li>		
	<li><a href="torrentlisten.php?action=audio&amp;anz=36" rel="ajaxcontentarea">Audio</a></li>
	<li><a href="torrentlisten.php?action=appz&amp;anz=36" rel="ajaxcontentarea">APPZ</a></li>
	<li><a href="torrentlisten.php?action=games&amp;anz=36" rel="ajaxcontentarea">Games</a></li>		
	<li><a href="torrentlisten.php?action=ebook&amp;anz=36" rel="ajaxcontentarea">E-Book</a></li>
	<li><a href="torrentlisten.php?action=doku&amp;anz=36" rel="ajaxcontentarea">Dokus</a></li>
	<li><a href="torrentlisten.php?action=highlight&amp;anz=36" rel="ajaxcontentarea">Highlight&acute;s</a></li>
	<li><a href="torrentlisten.php?action=request&amp;anz=36" rel="ajaxcontentarea">Request&acute;s</a></li>
	<li><a href="torrentlisten.php?action=filme_en&amp;anz=36" rel="ajaxcontentarea">Filme-Englisch</a></li>
	</ul>

<div id="ajaxcontentarea" style="margin-top:10px;"></div>
<script type="text/javascript">
	startajaxtabs("maintab")
	window.setInterval('startajaxtabs("maintab")', 60000);
</script>
<br class="clear" /><br />
	<div class="bbcode_mark_text" style="margin-left: 5px;">Empfehlung der Woche: <a href="details.php?id=(removed)">The.Veil.2024.S01.German.DL.DisneyHD.x264-4SF</a><br /></div><br /><div class="ecke_lu"></div><div class="ecke_ru"></div>
		</div><div id="redacted" style="display:inline;"></div>
<script type="text/javascript">
    tt2ajax_frames.init_ajaxframe('redacted',30,'index_radio.php');
  </script>
 
		<div class="content_wrap"><div class="ecke_lo"></div><div class="ecke_ro"></div>
			<div class="tabtitle_mitte">..:: Chat ::..</div><br /><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de">
  <head>
    <title>Abfragefehler</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="https://sor-next.tk/css/error.css" />
    <base href="https://sor-next.tk" />
  </head>
  <body>
    <h1>Fehler beim Ausf&uuml;hren der SQL</h1>
    <p>1064</p>
    <p>You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1</p>
    <p>SELECT `afk` FROM users WHERE id=(removed)  </body>
</html>
``` 

### Logged Error Messages

```text
Error downloading. indexer: spiritofrevolution path: https://sor-next.tk/download_ssl.php?torrent=redacted
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 85
```

**Comment by garfield69** [comment]
Unfortunately none of the team have an account on the site so we cannot investigate independently. :-(
The site has a jscheck at login which the indexer handles by providing JAVA=OK for the login form.
But none of the other THX engine sites have a jscheck for download so I've no examples to work with.
maybe having a look at a torrent details page HTML might provide some clues, can you dump one for me?
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source
thanks.

**Comment by garfield69** [comment]
Actually, what I really need is to see `https://sor-next.tk/jscheck.php?java=1&ref=` in debug mode from a browser to see what gets set on a successful check,  probably a cookie value. :-(
Then in theory, we drop the download_ssl link on the row, and shift to using a download block off the details page and load the cookie before using the dl link? IDK.
@ilike2burnthing @mynameisbogdan any suggestions on how to proceed?

**Comment by s0mm3rb** [comment]
it does indeed set a cookie
but it's just `JAVA=OK`
![image](https://github.com/user-attachments/assets/64ad167d-aa29-44ff-bd7e-dfde563c0b33)

need anything else?

**Comment by ilike2burnthing** [comment]
Have you confirmed you can actually download on the site itself?

**Comment by s0mm3rb** [comment]
> To me looks like basic SQL error on their side.

yeah, I saw that
but since browser download works, I wasn't sure how to interpret this error

![Screenshot 2024-08-14 235142](https://github.com/user-attachments/assets/92fd8985-cba1-4b09-b393-5e79fda79781)

**Comment by s0mm3rb** [comment]
> To me looks like basic SQL error on their side.
> 
> ```
> <body>
>     <h1>Fehler beim Ausf&uuml;hren der SQL</h1>
>     <p>1064</p>
>     <p>You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1</p>
>     <p>SELECT `afk` FROM users WHERE id=(removed)  </body>
> ```

speaking of that, I see that my client now is leeching from SoR 🤯
both radarr and sonarr successfully grabbed torrents
I'll close the issue, cause it does indeed look like there was an issue on their side
weird but I'll take it
thanks for creating jackett and keep up the great work!!!
regards

**Comment by s0mm3rb** [comment]
> Have you confirmed you can actually download on the site itself?

yes, that's the first thing I did...

but I understand, I probably would ask the same thing
