### ISSUE TITLE
[yggcookie] (updating) Name does not resolve (www.ygg.re:443): Name does not resolve

### ISSUE THREAD

**Issue by matthieu-hm** [Jackett/Jackett#15534]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.17.0.1:8191
Using proxy: Disabled
App config/log directory: folder path
Running in Docker: Yes
Jackett variant: CoreLinuxMuslAmdx64 (linuxserver/jackett:latest)
OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
Environment version: 8.0.8 (/app/Jackett/)
Starting Jackett v0.22.444

------------

Host DNS: 9.9.9.9
```

### Description

Inside the docker if I try to `curl https://www.ygg.re/` it work well (I get the cloudFlare page but it's okay), why jackett cannot resolve the name www.ygg.re ?

```
root@linuxserver-jackett:/# curl https://ygg.re/
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+)}}body{display:flex;flex-direction:column;min-height:100vh}body.no-js .loading-spinner{visibility:hidden}body.no-js .challenge-running{display:none}body.dark{background-color:#222;color:#d9d9d9}body.dark a{color:#fff}body.dark a:hover{color:#ee730a;text-decoration:underline}body.dark .lds-ring...
```

FlareSolverr works well.

```
21:13:532024-08-14 21:13:53 INFO Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://anidex.info/?page=search&s=upload_timestamp&o=desc&group_id=0&q=&lang_id='}
21:14:062024-08-14 21:14:06 INFO Challenge detected. Title found: DDoS-Guard
21:14:172024-08-14 21:14:17 INFO Challenge solved!
21:14:172024-08-14 21:14:17 INFO Response in 24.956 s
21:14:172024-08-14 21:14:17 INFO 172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK
```

```
2024-08-14 21:14:19.1608 Info Test search in Anidex => Found 50 releases [26169ms]
```

### Logged Error Messages

```text
2024-08-14 20:58:15.7715 Error System.Net.Http.HttpRequestException: Name does not resolve (www.ygg.re:443)

[v0.22.444.0] System.Net.Http.HttpRequestException: Name does not resolve (www.ygg.re:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 874
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1067
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Weird one.

Can you confirm that `curl https://www.ygg.re/` definitely works in the container? I know you said it does, but the output you provided was for `curl https://ygg.re/`, so just want to double-check.

Try Google, Cloudflare, and your ISP's DNS instead of Quad9, see if it makes a difference.

How are you setting the DNS, at the container level or host? Try both if you aren't already.

Are you using a proxy or VPN? If yes, try without. If no, try with.

Is FlareSolverr on the same device able to resolve the site? - https://github.com/FlareSolverr/FlareSolverr#usage

**Comment by matthieu-hm** [comment]
I confirm, it work with `https://www.ygg.re/`

```
root@linuxserver-jackett:/# curl https://www.ygg.re/
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiI
```

I found an other indexer that trigger the same error and does not need flaresolverr. As ygg I can make a curl call to the url within the container.

```
Exception (1337x): Name does not resolve: Name does not resolve (1337x.to:443)
```

```
root@linuxserver-jackett:/# curl https://1337x.to/
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Torrent Search Engine | 1337x.to</title>
<meta name="description" content="1337x is a search engine to find your favorite torrents.">
<meta name="viewport" content="width=device-width, initial-scale=1">
```

I don't think flaresolverr is related to the error, since `1337x.to` don't needs it and `ygg.re` return the error without trigger any logs from flaresolverr. I still made the tests, to be honest for moment it doesn't solve many challenge:

```
curl -L -X POST 'http://172.17.0.1:8191/v1' -H 'Content-Type: application/json' --data-raw '{ "cmd": "request.get", "url": "https://www.ygg.re/", "maxTimeout": 55000 }'
```

```
2024-08-14 23:05:43 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www.ygg.re/', 'maxTimeout': 120000}
2024-08-14 23:05:55 INFO     Challenge detected. Title found: Just a moment...
2024-08-14 23:07:45 ERROR    Error: Error solving the challenge. Timeout after 120.0 seconds.
2024-08-14 23:07:45 INFO     Response in 121.921 s
2024-08-14 23:07:45 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 500 Internal Server Error

2024-08-14 23:17:24 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://1337x.to/', 'maxTimeout': 120000}
2024-08-14 23:17:39 INFO     Challenge not detected!
2024-08-14 23:17:39 INFO     Response in 15.397 s
2024-08-14 23:17:39 INFO     172.17.0.1 POST http://172.17.0.1:8191/v1 200 OK

2024-08-14 21:13:53 INFO     Incoming request => POST /v1 body: {'maxTimeout': 55000, 'cmd': 'request.get', 'url': 'https://anidex.info/?page=search&s=upload_timestamp&o=desc&group_id=0&q=&lang_id='}
2024-08-14 21:14:06 INFO     Challenge detected. Title found: DDoS-Guard
2024-08-14 21:14:17 INFO     Challenge solved!
2024-08-14 21:14:17 INFO     Response in 24.956 s
```

My DNS is defined on the host machine (debian).
I tried 1.1.1.1 and 8.8.8.8 it changes nothing

I tried to start the docker on network host nothings changed

No VPN used, I'll try tomorrow it will require some config.

**Comment by ilike2burnthing** [comment]
Yea, have a look at the pinned issues and recent PRs on the FlareSolverr repo for potential solutions with it.

I just wanted to see if another Dockerised program other than curl could resolve the site.

Docker Jackett is working fine with YGG for me, and I need a proxy or VPN to access 1337x.to, but that's the same as in browser.

As well as trying with a proxy or VPN, there's a couple of other things you can check:
- Jackett installed natively on a device on the same local network (ideally the same device, but if a Windows laptop or something else is easier, that's fine)
- firewall, anti-malware, Pi-hole, parental controls, or any other content-filtering software/hardware, including ISP router and account settings (though if curl was somehow able to bypass these, that would be concerning, so I doubt it)

**Comment by matthieu-hm** [comment]
After a few tests, it seems that it's a problem due to alpine docker I can't say why but the request made to ygg.re by wget (or ping) always trigger the error. `bad address 'www.ygg.re'`

If I do the same thing on a debian container it works just fine. 

So I'll try to find a build based on a debian.

Thank you for the help

**Comment by ilike2burnthing** [comment]
That is a weird one, but ok then. I believe hotio's images are Debian-based.
