### ISSUE TITLE
openwrt install issue

### ISSUE THREAD

**Issue by hadifarnoud** [Jackett/Jackett#15540]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Hostname	OpenWrt
Model	Raspberry Pi 4 Model B Rev 1.2
Architecture	ARMv8 Processor rev 3
Target Platform	bcm27xx/bcm2711
Firmware Version	OpenWrt 23.05.0-rc1 r23069-e2701e0f33 / LuCI openwrt-23.05 branch git-23.118.79121-6fb185f
Kernel Version	5.15.114
```

### Description

I followed openwrt guide but ran into this issue when running bash script:
root@OpenWrt:~/Jackett# ./install_service_openwrt.sh
Checking if the service 'jackett' is running ...
./install_service_openwrt.sh: line 21: /etc/init.d/jackett: Permission denied
Service 'jackett' is not running
Jackett will be installed in '/root/Jackett'
Jackett will be executed with the user 'jackett'
Creating Jackett unit file in '/etc/init.d/jackett' ...
Installing Jackett service ...
./install_service_openwrt.sh: line 106: /etc/init.d/jackett: Permission denied
ERROR: Can not enable the service 'jackett'

### Logged Error Messages

```text
root@OpenWrt:~/Jackett# ./install_service_openwrt.sh
Checking if the service 'jackett' is running ...
./install_service_openwrt.sh: line 21: /etc/init.d/jackett: Permission denied
Service 'jackett' is not running
Jackett will be installed in '/root/Jackett'
Jackett will be executed with the user 'jackett'
Creating Jackett unit file in '/etc/init.d/jackett' ...
Installing Jackett service ...
./install_service_openwrt.sh: line 106: /etc/init.d/jackett: Permission denied
ERROR: Can not enable the service 'jackett'
```

**Comment by hadifarnoud** [comment]
I downloaded latest version of [Jackett.Binaries.LinuxMuslARM64.tar.gz](https://github.com/Jackett/Jackett/releases/download/v0.22.457/Jackett.Binaries.LinuxMuslARM64.tar.gz) 

even running jackett_launcher.sh throws below error:
```root@OpenWrt:~/Jackett# ./jackett_launcher.sh
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu (or icu-libs) using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser..ctor(System.Action`1<CommandLine.ParserSettings>)
   at Jackett.Server.Program.Main(System.String[])
Aborted```

**Comment by hadifarnoud** [comment]
> The solution is in the error actually, you need to install icu-libs or their equivalent on your openwrt first.

I did install [ICU lib](https://openwrt.org/packages/pkgdata_owrt18_6/icu) but still no dice.
```
root@OpenWrt:~/Jackett# ./jackett_launcher.sh
Could not load ICU data. UErrorCode: 2
Aborted
``

**Comment by hadifarnoud** [comment]
update: installing icu-full-data73 fixed the running issue.

installing as a service still has the same issue
