### ISSUE TITLE
[noname-clubl] (updating) Login failed: Selector "table.menutable a.mainmenu:contains("Выход")" didn't match

### ISSUE THREAD

**Issue by Monoboy4ik** [Jackett/Jackett#15544]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://172.17.0.3:8191
Using proxy: Disabled
App config/log directory: /config/Jackett	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.474-ls502)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 5.15.0.118 (64bit OS) (64bit process)	
Environment version: 8.0.8 (/app/Jackett/)
```

### Description

Try add indexer NoNaMe ClubL - https://nnmclub.to/

### Logged Error Messages

```text
2024-08-19 14:30:10	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "table.menutable a.mainmenu:contains("Выход")" didn't match

[v0.22.474.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "table.menutable a.mainmenu:contains("Выход")" didn't match
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 908
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1067
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
The indexer is working for me which suggests the issue is at your end.
Essentially, the NNC web site does not accept your cookie as match for the browser session you used to fetch the cookie from.
As a docker user, fetching the cookie is more problematic than with native jackett users.
See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work and in particular the Notes section to see in anything applies to you.

**Comment by IGNATOV93** [comment]
also dont working nnmclub  [noname-clubl] (updating) FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 120.0 seconds (

**Comment by garfield69** [comment]
@IGNATOV93  not related to this ticket.  See https://github.com/FlareSolverr/FlareSolverr/issues/1253

**Comment by Monoboy4ik** [comment]
> The indexer is working for me which suggests the issue is at your end. Essentially, the NNC web site does not accept your cookie as match for the browser session you used to fetch the cookie from. As a docker user, fetching the cookie is more problematic than with native jackett users. See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work and in particular the Notes section to see in anything applies to you.

thx!

**Comment by MSerj** [comment]
having the same issue, not sure how to fix this. I'm pretty sure i paste correct coockie copied from the headers.

**Comment by ilike2burnthing** [comment]
See the wiki link above. If that doesn't resolve your problem, open a new issue, providing the information requested and an enhanced log - https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket
