### ISSUE TITLE
[gazellegamesapi] (updating) Your API Key did not work: Parse error

### ISSUE THREAD

**Issue by reklov00** [Jackett/Jackett#15550]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2	
Using FlareSolverr: No
```

### Description

As in the screenshot, looks like API keys are not parsed correctly anymore, I also tried to create a new one.

### Logged Error Messages

```text
System.Exception: Your API Key did not work: Parse error

[v1.0.0.0] System.Exception: Your API Key did not work: Parse error
   at Jackett.Common.Indexers.Definitions.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson)
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext)

Error on 20240822180558 for GazelleGames (API).txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Definitions.GazelleGamesApi.PerformQuery(TorznabQuery query)
```

### Screenshots

![Screenshot 2024-08-22 200627](https://github.com/user-attachments/assets/72f57a24-5f68-47ad-9c51-011e7ac74fd0)

**Comment by reklov00** [comment]
Looks randomly fixed

**Comment by garfield69** [comment]
mynameisbogdan FYI you do not need to manually close these tickets.
By setting the `more information needed` label, the bot will close the ticket in a weeks time from the event if no response is made.
Same applies to the `full logs needed` label.

**Comment by garfield69** [comment]
mynameisbogdan FYI the Jackett version signature in the error message [1.0.0.0] is produced by users running Jackett source under Windows MS Visual Studio 2022.

**Comment by garfield69** [comment]
interestingly my MSVS 2022 now shows 1.0.0.0 too although I seem to recall it used to previously show 0.0.0.0
Wonder when that got changed, I don't recall.
Doesn't the updater have a check to ensure it does not launch when the versions is 0.0.0.0 ? 
Or has that been updated? 
I need to have a look. Would not want a check for updates launching an update while I'm in the middle of checking a C# indexer
 ;-D

**Comment by garfield69** [comment]
Oh good, its working, I'm seeing `Info Skipping checking for new releases as the debugger is attached.`
Interestingly, while log messages have `[v1.0.0.0]` the dashboard version has `Jackett Version v0.0.0`

**Comment by garfield69** [comment]
yes, that's the one.

**Comment by reklov00** [comment]
@mynameisbogdan @garfield69 just FYI, it's not an ''unofficial build'' or what, it's just installed from inside a seedbox, simple as that

**Comment by garfield69** [comment]
Yeah, one of the downside of a custom build is that we cannot tell if the versions of your indexers are up to date by looking at the log.txt files.
In you case the only way we would find out is for you to look at the updater.txt file to see the package name last fetched.
Academic at this point since this ticket is closed and presumably resolved ;-)

**Comment by Mapzle** [comment]
same problem

```
Error on 20241228185138 for GazelleGames (API).txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Definitions.GazelleGamesApi.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/GazelleGamesAPI.cs:line 288

Error System.Exception: Your API Key did not work: Parse error

[v0.22.1136.0] System.Exception: Your API Key did not work: Parse error
   at Jackett.Common.Indexers.Definitions.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/Abstract/GazelleTracker.cs:line 123
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```
![PixPin_2024-12-28_19-09-04](https://github.com/user-attachments/assets/4f672f35-7556-4cd9-adaf-3c405b676c61)

**Comment by garfield69** [comment]
@Mapzle  please open a fresh ticket, and provide the full log. 
I speculate that the api-key-did-not-work error may actually be a red herring since your screen-shot shows that you did receive results, which would suggest the issue is more likely that one or more of the torrent results gazellegames returned contains data (or missing data) that the indexer is not able to handle correctly.

**Comment by Mapzle** [comment]
> @Mapzle please open a fresh ticket, and provide the full log. I speculate that the api-key-did-not-work error may actually be a red herring since your screen-shot shows that you did receive results, which would suggest the issue is more likely that one or more of the torrent results gazellegames returned contains data (or missing data) that the indexer is not able to handle correctly.

Strange. I tried it again today and there was nothing wrong.
