### ISSUE TITLE
[bithorlo] offline

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15557]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
not relevant
```

### Description

Bithorlo have changed engine
need to update the indexer for new paths and so forth

### Logged Error Messages

```text
Error on 20240827052841 for Bithorlo.txtJackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 908
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1766
```

**Comment by garfield69** [comment]
v0.22.526

**Comment by garfield69** [comment]
Bithorlo will be closing on the 13th Oct. Migration to HunTorrent for users will be available for those that require it.

**Comment by garfield69** [comment]
v0.24.124
