### ISSUE TITLE
[wolfmax4k] (testing) Exception (wolfmax4k): Connection reset by peer: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by ignib22** [Jackett/Jackett#15554]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2	
Using FlareSolverr: http://172.19.0.7:8191/v1	
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads	
Running in Docker: Yes (image build: v0.22.515-ls509)	
File /etc/issue: Welcome to Alpine Linux 3.20	
Jackett variant: CoreLinuxMuslAmdx64	
OS version: Unix 5.10.0.32 (64bit OS) (64bit process)	
Environment version: 8.0.8 (/app/Jackett/)
```

### Description

Hi all!

I'm trying to add the wolfmax4k indexer and I am receiving the error message above. 
I did lots of test for example disabling ipv6. I can connect to wolfmax web using my browser.
Also, i tried to execute the following script from flaresolverr and it worked fine receiving 200ok and the web page in html. (I executed it on my machine and in the jackett container):
curl -L -X POST 'http://localhost:8191/v1' \
-H 'Content-Type: application/json' \
--data-raw '{
  "cmd": "request.get",
  "url": "https://www.wolfmax4k.com/",
  "maxTimeout": 60000
}'

When I try to  add the wolfmax indexer i do not see any try to access to wolfmax web in the flaresolverr container logs but when i execute de script it appears.

It looks like jackett does not use flaresolverr. It appears that i am using that FlareSolverr API: http://172.19.0.7:8191/v1 but i also tried to use http://172.19.0.7:8191 and doesn't work.

FlareSolverr and Jackett container are in the same docker network and they can comunicate between them.

Thank you!

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (wolfmax4k): Connection reset by peer

[v0.22.515.0] Jackett.Common.IndexerException: Exception (wolfmax4k): Connection reset by peer
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ReceiveAsync(Memory`1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.MoveNext()
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Memory`1 socketAddress, SocketFlags receivedFlags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass12_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in ./Jackett.Common/Indexers/BaseIndexer.cs:line 580
--- End of stack trace from previous location ---
   at Polly.ResiliencePipeline.<>c__10`1.<<ExecuteAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult](Func`2 callback, CancellationToken cancellationToken)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 579
   at Jackett.Common.Indexers.Definitions.Wolfmax4K.GetSearchTokenAsync() in ./Jackett.Common/Indexers/Definitions/Wolfmax4K.cs:line 189
   at Jackett.Common.Indexers.Definitions.Wolfmax4K.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/Wolfmax4K.cs:line 122
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
on your Jackett dashboard the flaresolverr address should not contain the trailing `v1`
have you tried that?

**Comment by ignib22** [comment]
Hi!

Yes, I also tried that.

**Comment by garfield69** [comment]
Prove you can access flaresolverr from your Jackett docker image
Open a terminal and use curl from within the image 
```
docker exec -it jackett /bin/bash
```
```
curl -vvv http://172.19.0.7:8191/
```
Thanks.

**Comment by ignib22** [comment]
It looks working fine.
I attach an image.

**Comment by garfield69** [comment]
email attachments do not work on GitHub, you need to use a web browser.

But anyway, now do the same for wolfmax4k
```
docker exec -it jackett /bin/bash
```
```
curl -vvv https://www.wolfmax4k.com/
```
Thanks.

**Comment by ignib22** [comment]
Thank you.
I upload both screenshots.

When I execute curl -vvv https://www.wolfmax4k.com/ it gives me the same error as in the jackett dashboard.

![Screenshot_20240825-223625_Termius~2](https://github.com/user-attachments/assets/9b3c1a05-0ea6-418e-ba56-ae6182cbd1c8)
![Screenshot_20240825-222825_Termius~2](https://github.com/user-attachments/assets/af5b450b-281d-4bc2-a63e-810c3de40c3f)

**Comment by garfield69** [comment]
@ilike2burnthing  another docker wolfmax4k entanglement. I can find resolutions in any of the prior tickets.
You know how I love diving into these docker rabbit holes ;-b not my cup of tea.
Any thoughts?

**Comment by garfield69** [comment]
I don't think this issue has anything to so with flaresolverr, and a reset by peer tends to be a 3rd party block issue, either with your ISP or anti-malware software someplace?
have you tried experimenting with  a system VPN to see if that gets you further?

**Comment by ignib22** [comment]
I will try using a VPN but it's a bit strange because I can access via
browser and using flaresolverr script in the same machine.

I will tell you something when I try.

Thank you guys!

**Comment by ilike2burnthing** [comment]
It's a different issue, but try following the troubleshooting steps I went through here - https://github.com/Jackett/Jackett/issues/15534

You could also try switching from the LS.io image to the hotio image (or vice versa), see if that makes a difference.

**Comment by ricargr** [comment]
Same here,
In the jackett page i get:

An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] CN=jellyplus.duckdns.org [Issuer] CN=R3, O=Let's Encrypt, C=US [Serial Number] 041509AE164C664771AB65CED1D83544CE09 [Not Before] 7/3/2021 7:00:43 PM [Not After] 10/1/2021 7:00:42 PM [Thumbprint] 21B5C2E7884EE93BD497EE58CC6C2727C4457040

**Comment by garfield69** [comment]
@ricargr yours is a different issue. your DNS provided DuckDNS is blocking access to https://wolfmax4k.com/ by redirecting to an invalid CA. Change DNS or use a VPN

**Comment by ignib22** [comment]
Hello guys,

I configured my Rpi installing jackett and flaresolverr and it works using a VPN.

I will have to do some testings in my server.

Thank you!!
