### ISSUE TITLE
CHDBits can't grab torrent 

### ISSUE THREAD

**Issue by iNfRaS0NiC** [Jackett/Jackett#15578]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-09-05 08:27:08	Info	Using HTTP Client: HttpWebClient2
2024-09-05 08:27:08	Info	Using FlareSolverr: http://localhost:8191/
2024-09-05 08:27:08	Info	Using proxy: Disabled
2024-09-05 08:27:08	Info	App config/log directory: C:\ProgramData\Jackett
2024-09-05 08:27:08	Info	ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
2024-09-05 08:27:08	Info	Running in Docker: No
2024-09-05 08:27:07	Info	Jackett variant: CoreWindows
2024-09-05 08:27:07	Info	OS version: Microsoft Windows NT 10.0.22631.0 (64bit OS)
2024-09-05 08:27:07	Info	Environment version: 8.0.8 (C:\ProgramData\Jackett\)
```

### Description

Jackett can't grab a torrent from CHDBits.
Please check the log.

### Logged Error Messages

```text
2024-09-05 08:16:49	Error	
Error downloading. indexer: chdbits path: https://chdbits.co/details.php?id=(removed)&hit=1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.Download(Uri link) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 2108
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 56
2024-09-05 08:16:49	Error	
CardigannIndexer (chdbits): An exception occurred while trying selector a[href^="download.php?id="], retrying with next available selector

[v0.22.559.0] System.Exception: Request to https://chdbits.co/details.php?id=(removed)&hit=1 failed (Error BadGateway) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 670
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 604
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.HandleRedirectableRequestAsync(String url, Dictionary`2 headers, Int32 maxRedirects) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1978
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.Download(Uri link) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 2115
2024-09-05 08:16:35	Error	
Error downloading. indexer: chdbits path: https://chdbits.co/details.php?id=(removed)&hit=1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.Download(Uri link) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 2108
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 56
2024-09-05 08:16:35	Error	
CardigannIndexer (chdbits): An exception occurred while trying selector a[href^="download.php?id="], retrying with next available selector

[v0.22.559.0] System.Exception: Request to https://chdbits.co/details.php?id=(removed)&hit=1 failed (Error BadGateway) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 670
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 604
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.HandleRedirectableRequestAsync(String url, Dictionary`2 headers, Int32 maxRedirects) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1978
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.Download(Uri link) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 2115
```

**Comment by garfield69** [comment]
None of the team have an account on chdbits so we cannot research independently.
For a download on this site, the indexer first goes to the details page, and looks for a href that begins with `download.php?id=`
Please go to any details page and do a HTML dump so we can check if things have changes.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source
Thanks.

**Comment by garfield69** [comment]
BTW the log suggests that just as you went to start the DL the web site became offline.
Have you tried again since posting this ticket?

**Comment by iNfRaS0NiC** [comment]
@garfield69 yes, actually the issue is no longer available and now I can grab the torrents... strange, but thanks anyway!
