### ISSUE TITLE
[TorrentSeeds] 429 Too Many Requests

### ISSUE THREAD

**Issue by b12e** [Jackett/Jackett#15599]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /Users/bram/Library/Application Support/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreMacOsArm64
OS version: Unix 14.5.0 (64bit OS) (64bit process)
Environment version: 8.0.4 (/opt/homebrew/Cellar/dotnet/8.0.4/libexec/shared/Microsoft.NETCore.App/8.0.4/)
```

### Description

I'm getting constant Too Many Requests on TorrentSeeds. Example error message below:
```log
Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":40}

[v0.22.586.0] Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":40}
 ---> System.Exception: Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":40}
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1590
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 437
```

This makes Sonarr think there's something wrong with Jackett.

Can the timeout be increased to adhere to the TS rate limits, or make the backoff user configurable?

**The rate limit is 4 requests per minute.** It seems the [requestDelay](https://github.com/Jackett/Jackett/blob/65c885f71f0a3345a1047831acb9e3f6f679f222/src/Jackett.Common/Definitions/torrentseeds-api.yml#L8) is set to 5:
```yaml
---
id: torrentseeds-api
name: TorrentSeeds (API)
description: "TorrentSeeds is a Private Torrent Tracker for MOVIES / TV / MUSIC / GENERAL"
language: en-US
type: private
encoding: UTF-8
requestDelay: 5
links:
  - https://torrentseeds.org/
```

### Logged Error Messages

```text
2024-09-16 11:53:08 	Error 	

Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":31}

[v0.22.586.0] Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":31}
 ---> System.Exception: Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":31}
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1590
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 437

2024-09-16 11:53:03 	Info 	

Torznab search in TorrentSeeds (API) for Rick et Morty S02E07 => Found 0 releases [8858ms]

2024-09-16 11:53:02 	Error 	

Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":38}

[v0.22.586.0] Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":38}
 ---> System.Exception: Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":38}
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1590
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 437

2024-09-16 11:52:57 	Info 	

Torznab search in TorrentSeeds (API) => Found 0 releases [4759ms]

2024-09-16 11:52:54 	Info 	

Torznab search in TorrentSeeds (API) => Found 0 releases [4093ms]

2024-09-16 11:52:44 	Info 	

Torznab search in TorrentSeeds (API) => Found 100 releases [4298ms]

2024-09-16 11:51:43 	Error 	

Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":40}

[v0.22.586.0] Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":40}
 ---> System.Exception: Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":40}
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1590
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 437

2024-09-16 11:51:43 	Error 	

Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":40}

[v0.22.586.0] Jackett.Common.IndexerException: Exception (torrentseeds-api): Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":40}
 ---> System.Exception: Error Parsing Json Response: Status=TooManyRequests Response={"message":"Too Many Requests","retry_after":40}
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1590
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in ./Jackett.Server/Controllers/ResultsController.cs:line 437

2024-09-16 11:51:38 	Info 	

Torznab search in TorrentSeeds (API) for Rick y Morty S02E05 => Found 1 releases [9180ms]
```

### Screenshots

<img width="1064" alt="afbeelding" src="https://github.com/user-attachments/assets/e90fdec7-8a29-4f7b-9893-97f45c037d36">

**Comment by ilike2burnthing** [comment]
https://github.com/Prowlarr/Prowlarr/issues/2023

**Comment by b12e** [comment]
Sorry but why not planned? If you change the requestDelay to 15 seconds, Jackett will never go over the maximum of 4 per minute. 

Or am I misunderstanding something? Why else would there be a requestDelay?

**Comment by ilike2burnthing** [comment]
https://github.com/Prowlarr/Prowlarr/issues/2023#issuecomment-1975021633

**Comment by b12e** [comment]
Alright for the future, if anyone else googles this:

- Restart Jackett
- Open the log. It'll say something like the following:
```
Loading Cardigann indexers from: /path1/cardigann/definitions/, /path2/cardigan/definitions/, /path3/Definitions
```
- Check these paths in your filesystem for a file named `torrentseeds-api.yml`.
- Copy the file to torrentseeds-api-slow.yml (eg `cp torrentseeds-api.yml torrentseeds-api-slow.yml` )
- edit the new file (`nano torrentseeds-api-slow.yml`) and change first few lines to the following:
```yaml
id: torrentseeds-api-slow
name: TorrentSeeds (API) - Slow
description: "TorrentSeeds is a Private Torrent Tracker for MOVIES / TV / MUSIC$
language: en-US
type: private
encoding: UTF-8
requestDelay: 60
```
The `id`, `name` and `requestDelay` are changed.
- Save the file
- Restart Jackett
- Configure the new "Slow" indexer in Jackett
- Add the new "Slow" indexer to your *arr application

If using a package manager (I'm using Brew) make sure to disable updates ( `brew pin jackett`) and disable auto-updates inside Jackett - it'll probably overwrite the definition in each update and that's something you don't want. Alternatively make sure that file cannot be updated by Jackett.

Given Jackett and Prowlarr don't want to implement rate limits in a proper way, this is the way to go to prevent `429`s for now.

**Comment by ilike2burnthing** [comment]
`/cardigann/definitions/` is for custom definitions, for cases exactly like this, where a user may want to change something which would not be suitable for the wider userbase - https://github.com/Jackett/Jackett/issues/10525

You do not need to disable updates, custom definitions in these locations are not overwritten.

Rate limits have been implemented in a 'proper way', but we have to balance general usability with specific site requirements, and if that doesn't work for someone, then they can make a custom definition.

**Comment by b12e** [comment]
> Rate limits have been implemented in a 'proper way', but we have to balance general usability with specific site requirements, and if that doesn't work for someone, then they can make a custom definition.
Sorry but if rate limits are hit every time there's 4 API requests in short succession, that is not a "proper" implementation of rate limits.

The fact that that is an "error" for *arr is also not great, but it does mean that Jackett is skipped as an indexer for a significant amount of time. I don't know the exact timeouts, Sonarr docs [speaks of](https://wiki.servarr.com/sonarr/system#indexers-are-unavailable-due-to-failures) "an increasing amount of time, up to 24 hours":
> To limit retries, Sonarr will not use the indexer for an increasing amount of time (up to 24h).

But even if that is only an hour, that's a full hour that Jackett isn't tried. 

I'd _much_ rather have 1 request per minute (60 per hour) than 4 requests in a minute, then be ratelimited and as a sonsequence have Jackett throw an error towards *arr and Sonarr/Radarr doesn't retry for an hour. 

once a minute, * 60 = 60 searches
4 in a minute, then failure = 4 searches.

Agreed, a 60 second backoff is everything but ideal. It slows down searches massively. But the alternative is no searches, which is worse.
 
> You do not need to disable updates, custom definitions in these locations are not overwritten.
Thank you for that extra info. I'll update instructions.

**Comment by ilike2burnthing** [comment]
To clarify, that one indexer would not be reused by Sonarr for that period of time, other indexers would be unaffected.

If performing a manual search in Sonarr for a series with even just one alternate title, this would take over a minute, and so the search would 'fail' on Sonarr's end (pretty sure its search timeout is 60s). So adhering to the tracker's rate limit requirements would be just as problematic, if not moreso.
