### ISSUE TITLE
[beyond-hd-api] (testing) Exception (beyond-hd-api): Value cannot be null. (Parameter 'uriString'): Value cannot be null. (Parameter 'uriString')

### ISSUE THREAD

**Issue by Audionut** [Jackett/Jackett#15606]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-09-23 05:02:26 	Info 	

Jackett startup finished in 4.141 s

2024-09-23 05:02:26 	Info 	

Adding filter indexer ('type:semi-public' indexer) ...

2024-09-23 05:02:26 	Info 	

Adding filter indexer ('type:private' indexer) ...

2024-09-23 05:02:26 	Info 	

Adding filter indexer ('type:public' indexer) ...

2024-09-23 05:02:26 	Info 	

Adding aggregate indexer ('all' indexer) ...

2024-09-23 05:02:26 	Info 	

Loaded 614 indexers in total

2024-09-23 05:02:26 	Info 	

Loaded 543 Cardigann indexers.

2024-09-23 05:02:23 	Info 	

Loading Cardigann indexers from: C:\ProgramData\Jackett\cardigann\definitions\, C:\ProgramData\Jackett\Definitions

2024-09-23 05:02:22 	Info 	

Loaded 71 Native indexers.

2024-09-23 05:02:22 	Info 	

Loading Native indexers ...

2024-09-23 05:02:22 	Info 	

Using HTTP Client: HttpWebClient2

2024-09-23 05:02:22 	Info 	

Using FlareSolverr: No

2024-09-23 05:02:22 	Info 	

Using proxy: Disabled

2024-09-23 05:02:22 	Info 	

App config/log directory: C:\ProgramData\Jackett

2024-09-23 05:02:22 	Info 	

ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads

2024-09-23 05:02:22 	Info 	

Running in Docker: No

2024-09-23 05:02:22 	Info 	

Jackett variant: CoreWindows

2024-09-23 05:02:22 	Info 	

OS version: Microsoft Windows NT 10.0.22631.0 (64bit OS)

2024-09-23 05:02:22 	Info 	

Environment version: 8.0.8 (C:\ProgramData\Jackett\)

2024-09-23 05:02:22 	Info 	

Starting Jackett v0.22.657
```

### Description

As far as I know it was working fine, cross-seed running through Jackett certainly hadn't complained. I updated RSS key at BHD, opened the options in Jackett, copied the new RSS key in, hit save, and then get this error message when testing.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (beyond-hd-api): Value cannot be null. (Parameter 'uriString')

[v0.22.657.0] Jackett.Common.IndexerException: Exception (beyond-hd-api): Value cannot be null. (Parameter 'uriString')
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.ArgumentNullException.Throw(String paramName)
   at Jackett.Common.Indexers.Definitions.BeyondHDAPI.MapToReleaseInfo(BHDResult bhdResult) in ./Jackett.Common/Indexers/Definitions/BeyondHDAPI.cs:line 183
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Jackett.Common.Indexers.BaseIndexer.FilterResults(TorznabQuery query, IEnumerable`1 results) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 171
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 372
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
I can't be absolutely certain, because i do not have an a/c on BHD, but it appears the issue may have something to so with one of the torrents that was returned did not have a download link.
Can you check on the website to see if any of the latest releases have the download link missing?

**Comment by garfield69** [comment]
@mynameisbogdan is the beyond-hd-api indexer working for you?

**Comment by garfield69** [comment]
its possible the OP caught the site just as someone was uploading a new torrent and had not completed the entry.
Perhaps we should trap a missing DL with a log warning and skip that row?

**Comment by Audionut** [comment]
I did try over a period of minutes, but yes, confirmed working again. 
Would it be better to check the next oldest result perhaps. IDK.

**Comment by garfield69** [comment]
We will add some enhancement to the indexer to do some simple error trapping when it processes a torrent row from the results.

**Comment by garfield69** [comment]
>Would be easier to just filter the bad ones without any logging

that would be fine, its in line with how most cardigann indexer deal with a missing DL.

**Comment by garfield69** [comment]
v0.22.664
