### ISSUE TITLE
[mejortorrent] (configuring) Address not available (www21.mejortorrent.zip:443): Address not available

### ISSUE THREAD

**Issue by Austros** [Jackett/Jackett#15615]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
OS version: Unix 6.8.0.45 (64bit OS) (64bit process)
Jackett variant: CoreLinuxMuslAmdx64
Starting Jackett v0.22.671
Using FlareSolverr: http://192.168.1.56:8191
Using HTTP Client: HttpWebClient2
Using proxy: Disabled
App config/log directory: /config/Jackett
```

### Description

Hello, I just discovered this whole world of jackett, radarr... and etsba adding some trackers and after adding two successfully (DonTorrent and EliteTorrent) I tried to add Mejortorrent (I have also tried with wolfmax4k which gave me an ssl error that still I didn't solve it) and when I added it it gave me the error that I attached in the address not available report. But when I enter the url in the browser it does let me enter. Since I just started with this media server thing, I don't really know how to deal with the problem. Any ideas? Thank you very much in advance

### Logged Error Messages

```text
System.Net.Http.HttpRequestException: Address not available (www21.mejortorrent.zip:443)

[v0.22.671.0] System.Net.Http.HttpRequestException: Address not available (www21.mejortorrent.zip:443)
 ---> System.Net.Sockets.SocketException (99): Address not available
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 186
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.Definitions.MejorTorrent.PerformQueryNewest(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/MejorTorrent.cs:line 154
   at Jackett.Common.Indexers.Definitions.MejorTorrent.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/MejorTorrent.cs:line 136
   at Jackett.Common.Indexers.Definitions.MejorTorrent.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/MejorTorrent.cs:line 120
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

![image](https://github.com/user-attachments/assets/863fe4f2-44a2-46e8-992c-4a26e1956a2d)
![image](https://github.com/user-attachments/assets/2a4179a8-cfdb-4ca6-a491-b27776ee7955)
![image](https://github.com/user-attachments/assets/8bdcad6e-d7a9-4ee2-b285-c3bfb9991859)

**Comment by garfield69** [comment]
The indexer is working for me which suggests that the problem is at your end.

`Address not available` is a common docker related message although that detail seems to be missing from your environment section (7 lines instead of the usual 10, although I suppose if you are using CoreLinuxMuslAmdx64 natively then that may also be related ;-)

If you can access some sites but not others, then that suggests that you are being blocked by something.
See https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed for suggestions on possible causes.
If you can't figure it out then let us know and we can reopen the ticket and try to help further, albeit if you've exhausted the help link then there is probably not much more can be done).
