### ISSUE TITLE
[monikadesign-api] Error while parsing field=files, selector=num_file, value=<null>

### ISSUE THREAD

**Issue by loeminn** [Jackett/Jackett#15624]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolverr:8191
Using proxy: Socks5
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.707-ls549)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.1.0.25 (64bit OS) (64bit process)
Environment version: 8.0.8 (/app/Jackett/)
Starting Jackett v0.22.707
```

### Description

The search is not working properly.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (monikadesign-api): Selector "" didn't match {
  "meta": {
    "poster": "https://image.tmdb.org/t/p/w92/rAI0hOocFwELMJVmBJn1l3ubRD9.jpg",
    "genres": "剧情, 动画"
  },
  "name": "Ooi! Tonbo S01E14 1080p Baha WEB-DL H264 AAC 2.0-ANi",
  "subhead": "蜻蛉高球 / Ooi! Tonbo | 14",
  "category": "Airing Anime TV",
  "type": "WEB-DL",
  "resolution": "1080p",
  "season_number": 1,
  "episode_number": 1,
  "media_info": "General\r\nComplete name                            : [ANi] 蜻蛉高球 - 14 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4\r\nFormat                                   : MPEG-4\r\nFormat profile                           : Base Media\r\nCodec ID                                 : isom (isom/iso2/avc1/mp41)\r\nFile size                                : 486 MiB\r\nDuration                                 : 24 min 13 s\r\nOverall bit rate                         : 2 806 kb/s\r\nMovie name                               : 蜻蛉高球\r\nAlbum                                    : 蜻蛉高球\r\nDescription                              :  就像捨棄過去、逃離世間一般，「五十嵐一賀」搬遷到了鹿兒島縣的「吐噶喇群島」。在被稱作「日本最後的秘境」的「火之島」，遇到了島上唯一的中學生「大井蜻蜓」。而這天真爛漫的少女，竟隱藏著不得了的高爾夫才華！？在這份相遇的契機下，兩人的命運將發生巨大的轉變…。 ＜STAFF＞ 原作：かわさき健 作畫：古澤優 導演監督：オジング 劇本統籌：廣田光毅 角色設計：武內啟 色彩設計：近藤直登 美術監督：荒井和浩 CG製作：SMDE 3D監督：服部惠大 攝影監督：石山智之 音響監督：三間雅文 音樂：戶田信子 動畫製作：OLM 高爾夫設定監修：高爾夫文摘社 ＜CAST＞ \r\nWriting application                      : Lavf58.45.100\r\nCover                                    : Yes\r\n\r\nVideo\r\nID                                       : 2\r\nFormat                                   : AVC\r\nFormat/Info                              : Advanced Video Codec\r\nFormat profile                           : High@L5\r\nFormat settings                          : CABAC / 4 Ref Frames\r\nFormat settings, CABAC                   : Yes\r\nFormat settings, Reference frames        : 4 frames\r\nCodec ID                                 : avc1\r\nCodec ID/Info                            : Advanced Video Coding\r\nDuration                                 : 24 min 12 s\r\nBit rate                                 : 2 493 kb/s\r\nWidth                                    : 1 920 pixels\r\nHeight                                   : 1 080 pixels\r\nDisplay aspect ratio                     : 16:9\r\nFrame rate mode                          : Variable\r\nFrame rate                               : 23.976 (24000/1001) FPS\r\nMinimum frame rate                       : 23.974 FPS\r\nMaximum frame rate                       : 23.981 FPS\r\nColor space                              : YUV\r\nChroma subsampling                       : 4:2:0\r\nBit depth                                : 8 bits\r\nScan type                                : Progressive\r\nBits/(Pixel*Frame)                       : 0.050\r\nStream size                              : 432 MiB (89%)\r\nWriting library                          : x264 core 161 r3018 db0d417\r\nEncoding settings                        : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x113 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=crf / mbtree=1 / crf=21.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=12000 / vbv_bufsize=80000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=3:0.70\r\nmdhd_Duration                            : 1452993\r\nCodec configuration box                  : avcC\r\n\r\nAudio\r\nID                                       : 3\r\nFormat                                   : AAC LC\r\nFormat/Info                              : Advanced Audio Codec Low Complexity\r\nCodec ID                                 : mp4a-40-2\r\nDuration                                 : 24 min 13 s\r\nBit rate mode                            : Constant\r\nBit rate                                 : 306 kb/s\r\nChannel(s)                               : 2 channels\r\nChannel layout                           : L R\r\nSampling rate                            : 48.0 kHz\r\nFrame rate                               : 46.875 FPS (1024 SPF)\r\nCompression mode                         : Lossy\r\nStream size                              : 53.0 MiB (11%)\r\nLanguage                                 : Japanese\r\nDefault                                  : Yes\r\nAlternate group                          : 1",
  "bd_info": null,
  "description": "Torrent Info By: ANi API (Auto Generated)\n\nSubtitle:\n\n HardSub\n\nMediainfo:\n\n Resolution: 1080P\n\n Video Format: AVC\n\n Audio Format: AAC\n\n\nNote:\n\n Xunlei, torrent media player and offline downloader has been banned by our\nseeding server.\n\n If you have any concerns or feedback regarding the information or the file,\nplease don't hesitate to let me know.\n\n Please help by seeding the files after downloading. Your support is greatly\nappreciated. Thank you!\n\n Telegram Chat: https://t.me/+SH8EUievFGLKQew_ [https://t.me/+SH8EUievFGLKQew_]\n\n2024/10/5 1:31:21 UTC+0000 (Coordinated Universal Time)",
  "info_hash": "056809c71eceaa6802cc0d8e5fc0f00a91a28b1c",
  "size": 509739501,
  "internal": 1,
  "uploader": "ANi",
  "seeders": 14,
  "leechers": 3,
  "times_completed": 22,
  "tmdb_id": 243140,
  "imdb_id": 31957516,
  "tvdb_id": 434358,
  "mal_id": 0,
  "bgm_id": "0",
  "subtitle_tag": "繁中硬字@Baha",
  "category_id": 11,
  "type_id": 4,
  "resolution_id": 3,
  "created_at": "2024-10-05T01:31:23Z",
  "download_link": "https://monikadesign.uk/torrents/download/17269.29a93c973a01bac592f5560e2e8b682d",
  "details_link": "https://monikadesign.uk/torrents/17269"
}

[v0.22.707.0] Jackett.Common.IndexerException: Exception (monikadesign-api): Selector "" didn't match {
  "meta": {
    "poster": "https://image.tmdb.org/t/p/w92/rAI0hOocFwELMJVmBJn1l3ubRD9.jpg",
    "genres": "剧情, 动画"
  },
  "name": "Ooi! Tonbo S01E14 1080p Baha WEB-DL H264 AAC 2.0-ANi",
  "subhead": "蜻蛉高球 / Ooi! Tonbo | 14",
  "category": "Airing Anime TV",
  "type": "WEB-DL",
  "resolution": "1080p",
  "season_number": 1,
  "episode_number": 1,
  "media_info": "General\r\nComplete name                            : [ANi] 蜻蛉高球 - 14 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4\r\nFormat                                   : MPEG-4\r\nFormat profile                           : Base Media\r\nCodec ID                                 : isom (isom/iso2/avc1/mp41)\r\nFile size                                : 486 MiB\r\nDuration                                 : 24 min 13 s\r\nOverall bit rate                         : 2 806 kb/s\r\nMovie name                               : 蜻蛉高球\r\nAlbum                                    : 蜻蛉高球\r\nDescription                              :  就像捨棄過去、逃離世間一般，「五十嵐一賀」搬遷到了鹿兒島縣的「吐噶喇群島」。在被稱作「日本最後的秘境」的「火之島」，遇到了島上唯一的中學生「大井蜻蜓」。而這天真爛漫的少女，竟隱藏著不得了的高爾夫才華！？在這份相遇的契機下，兩人的命運將發生巨大的轉變…。 ＜STAFF＞ 原作：かわさき健 作畫：古澤優 導演監督：オジング 劇本統籌：廣田光毅 角色設計：武內啟 色彩設計：近藤直登 美術監督：荒井和浩 CG製作：SMDE 3D監督：服部惠大 攝影監督：石山智之 音響監督：三間雅文 音樂：戶田信子 動畫製作：OLM 高爾夫設定監修：高爾夫文摘社 ＜CAST＞ \r\nWriting application                      : Lavf58.45.100\r\nCover                                    : Yes\r\n\r\nVideo\r\nID                                       : 2\r\nFormat                                   : AVC\r\nFormat/Info                              : Advanced Video Codec\r\nFormat profile                           : High@L5\r\nFormat settings                          : CABAC / 4 Ref Frames\r\nFormat settings, CABAC                   : Yes\r\nFormat settings, Reference frames        : 4 frames\r\nCodec ID                                 : avc1\r\nCodec ID/Info                            : Advanced Video Coding\r\nDuration                                 : 24 min 12 s\r\nBit rate                                 : 2 493 kb/s\r\nWidth                                    : 1 920 pixels\r\nHeight                                   : 1 080 pixels\r\nDisplay aspect ratio                     : 16:9\r\nFrame rate mode                          : Variable\r\nFrame rate                               : 23.976 (24000/1001) FPS\r\nMinimum frame rate                       : 23.974 FPS\r\nMaximum frame rate                       : 23.981 FPS\r\nColor space                              : YUV\r\nChroma subsampling                       : 4:2:0\r\nBit depth                                : 8 bits\r\nScan type                                : Progressive\r\nBits/(Pixel*Frame)                       : 0.050\r\nStream size                              : 432 MiB (89%)\r\nWriting library                          : x264 core 161 r3018 db0d417\r\nEncoding settings                        : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x113 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=crf / mbtree=1 / crf=21.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=12000 / vbv_bufsize=80000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=3:0.70\r\nmdhd_Duration                            : 1452993\r\nCodec configuration box                  : avcC\r\n\r\nAudio\r\nID                                       : 3\r\nFormat                                   : AAC LC\r\nFormat/Info                              : Advanced Audio Codec Low Complexity\r\nCodec ID                                 : mp4a-40-2\r\nDuration                                 : 24 min 13 s\r\nBit rate mode                            : Constant\r\nBit rate                                 : 306 kb/s\r\nChannel(s)                               : 2 channels\r\nChannel layout                           : L R\r\nSampling rate                            : 48.0 kHz\r\nFrame rate                               : 46.875 FPS (1024 SPF)\r\nCompression mode                         : Lossy\r\nStream size                              : 53.0 MiB (11%)\r\nLanguage                                 : Japanese\r\nDefault                                  : Yes\r\nAlternate group                          : 1",
  "bd_info": null,
  "description": "Torrent Info By: ANi API (Auto Generated)\n\nSubtitle:\n\n HardSub\n\nMediainfo:\n\n Resolution: 1080P\n\n Video Format: AVC\n\n Audio Format: AAC\n\n\nNote:\n\n Xunlei, torrent media player and offline downloader has been banned by our\nseeding server.\n\n If you have any concerns or feedback regarding the information or the file,\nplease don't hesitate to let me know.\n\n Please help by seeding the files after downloading. Your support is greatly\nappreciated. Thank you!\n\n Telegram Chat: https://t.me/+SH8EUievFGLKQew_ [https://t.me/+SH8EUievFGLKQew_]\n\n2024/10/5 1:31:21 UTC+0000 (Coordinated Universal Time)",
  "info_hash": "056809c71eceaa6802cc0d8e5fc0f00a91a28b1c",
  "size": 509739501,
  "internal": 1,
  "uploader": "ANi",
  "seeders": 14,
  "leechers": 3,
  "times_completed": 22,
  "tmdb_id": 243140,
  "imdb_id": 31957516,
  "tvdb_id": 434358,
  "mal_id": 0,
  "bgm_id": "0",
  "subtitle_tag": "繁中硬字@Baha",
  "category_id": 11,
  "type_id": 4,
  "resolution_id": 3,
  "created_at": "2024-10-05T01:31:23Z",
  "download_link": "https://monikadesign.uk/torrents/download/17269.29a93c973a01bac592f5560e2e8b682d",
  "details_link": "https://monikadesign.uk/torrents/17269"
}
 ---> System.Exception: Error while parsing field=files, selector=num_file, value=<null>: Selector "" didn't match {
  "meta": {
    "poster": "https://image.tmdb.org/t/p/w92/rAI0hOocFwELMJVmBJn1l3ubRD9.jpg",
    "genres": "剧情, 动画"
  },
  "name": "Ooi! Tonbo S01E14 1080p Baha WEB-DL H264 AAC 2.0-ANi",
  "subhead": "蜻蛉高球 / Ooi! Tonbo | 14",
  "category": "Airing Anime TV",
  "type": "WEB-DL",
  "resolution": "1080p",
  "season_number": 1,
  "episode_number": 1,
  "media_info": "General\r\nComplete name                            : [ANi] 蜻蛉高球 - 14 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4\r\nFormat                                   : MPEG-4\r\nFormat profile                           : Base Media\r\nCodec ID                                 : isom (isom/iso2/avc1/mp41)\r\nFile size                                : 486 MiB\r\nDuration                                 : 24 min 13 s\r\nOverall bit rate                         : 2 806 kb/s\r\nMovie name                               : 蜻蛉高球\r\nAlbum                                    : 蜻蛉高球\r\nDescription                              :  就像捨棄過去、逃離世間一般，「五十嵐一賀」搬遷到了鹿兒島縣的「吐噶喇群島」。在被稱作「日本最後的秘境」的「火之島」，遇到了島上唯一的中學生「大井蜻蜓」。而這天真爛漫的少女，竟隱藏著不得了的高爾夫才華！？在這份相遇的契機下，兩人的命運將發生巨大的轉變…。 ＜STAFF＞ 原作：かわさき健 作畫：古澤優 導演監督：オジング 劇本統籌：廣田光毅 角色設計：武內啟 色彩設計：近藤直登 美術監督：荒井和浩 CG製作：SMDE 3D監督：服部惠大 攝影監督：石山智之 音響監督：三間雅文 音樂：戶田信子 動畫製作：OLM 高爾夫設定監修：高爾夫文摘社 ＜CAST＞ \r\nWriting application                      : Lavf58.45.100\r\nCover                                    : Yes\r\n\r\nVideo\r\nID                                       : 2\r\nFormat                                   : AVC\r\nFormat/Info                              : Advanced Video Codec\r\nFormat profile                           : High@L5\r\nFormat settings                          : CABAC / 4 Ref Frames\r\nFormat settings, CABAC                   : Yes\r\nFormat settings, Reference frames        : 4 frames\r\nCodec ID                                 : avc1\r\nCodec ID/Info                            : Advanced Video Coding\r\nDuration                                 : 24 min 12 s\r\nBit rate                                 : 2 493 kb/s\r\nWidth                                    : 1 920 pixels\r\nHeight                                   : 1 080 pixels\r\nDisplay aspect ratio                     : 16:9\r\nFrame rate mode                          : Variable\r\nFrame rate                               : 23.976 (24000/1001) FPS\r\nMinimum frame rate                       : 23.974 FPS\r\nMaximum frame rate                       : 23.981 FPS\r\nColor space                              : YUV\r\nChroma subsampling                       : 4:2:0\r\nBit depth                                : 8 bits\r\nScan type                                : Progressive\r\nBits/(Pixel*Frame)                       : 0.050\r\nStream size                              : 432 MiB (89%)\r\nWriting library                          : x264 core 161 r3018 db0d417\r\nEncoding settings                        : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x113 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=crf / mbtree=1 / crf=21.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=12000 / vbv_bufsize=80000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=3:0.70\r\nmdhd_Duration                            : 1452993\r\nCodec configuration box                  : avcC\r\n\r\nAudio\r\nID                                       : 3\r\nFormat                                   : AAC LC\r\nFormat/Info                              : Advanced Audio Codec Low Complexity\r\nCodec ID                                 : mp4a-40-2\r\nDuration                                 : 24 min 13 s\r\nBit rate mode                            : Constant\r\nBit rate                                 : 306 kb/s\r\nChannel(s)                               : 2 channels\r\nChannel layout                           : L R\r\nSampling rate                            : 48.0 kHz\r\nFrame rate                               : 46.875 FPS (1024 SPF)\r\nCompression mode                         : Lossy\r\nStream size                              : 53.0 MiB (11%)\r\nLanguage                                 : Japanese\r\nDefault                                  : Yes\r\nAlternate group                          : 1",
  "bd_info": null,
  "description": "Torrent Info By: ANi API (Auto Generated)\n\nSubtitle:\n\n HardSub\n\nMediainfo:\n\n Resolution: 1080P\n\n Video Format: AVC\n\n Audio Format: AAC\n\n\nNote:\n\n Xunlei, torrent media player and offline downloader has been banned by our\nseeding server.\n\n If you have any concerns or feedback regarding the information or the file,\nplease don't hesitate to let me know.\n\n Please help by seeding the files after downloading. Your support is greatly\nappreciated. Thank you!\n\n Telegram Chat: https://t.me/+SH8EUievFGLKQew_ [https://t.me/+SH8EUievFGLKQew_]\n\n2024/10/5 1:31:21 UTC+0000 (Coordinated Universal Time)",
  "info_hash": "056809c71eceaa6802cc0d8e5fc0f00a91a28b1c",
  "size": 509739501,
  "internal": 1,
  "uploader": "ANi",
  "seeders": 14,
  "leechers": 3,
  "times_completed": 22,
  "tmdb_id": 243140,
  "imdb_id": 31957516,
  "tvdb_id": 434358,
  "mal_id": 0,
  "bgm_id": "0",
  "subtitle_tag": "繁中硬字@Baha",
  "category_id": 11,
  "type_id": 4,
  "resolution_id": 3,
  "created_at": "2024-10-05T01:31:23Z",
  "download_link": "https://monikadesign.uk/torrents/download/17269.29a93c973a01bac592f5560e2e8b682d",
  "details_link": "https://monikadesign.uk/torrents/17269"
}
 ---> System.Exception: Selector "" didn't match {
  "meta": {
    "poster": "https://image.tmdb.org/t/p/w92/rAI0hOocFwELMJVmBJn1l3ubRD9.jpg",
    "genres": "剧情, 动画"
  },
  "name": "Ooi! Tonbo S01E14 1080p Baha WEB-DL H264 AAC 2.0-ANi",
  "subhead": "蜻蛉高球 / Ooi! Tonbo | 14",
  "category": "Airing Anime TV",
  "type": "WEB-DL",
  "resolution": "1080p",
  "season_number": 1,
  "episode_number": 1,
  "media_info": "General\r\nComplete name                            : [ANi] 蜻蛉高球 - 14 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4\r\nFormat                                   : MPEG-4\r\nFormat profile                           : Base Media\r\nCodec ID                                 : isom (isom/iso2/avc1/mp41)\r\nFile size                                : 486 MiB\r\nDuration                                 : 24 min 13 s\r\nOverall bit rate                         : 2 806 kb/s\r\nMovie name                               : 蜻蛉高球\r\nAlbum                                    : 蜻蛉高球\r\nDescription                              :  就像捨棄過去、逃離世間一般，「五十嵐一賀」搬遷到了鹿兒島縣的「吐噶喇群島」。在被稱作「日本最後的秘境」的「火之島」，遇到了島上唯一的中學生「大井蜻蜓」。而這天真爛漫的少女，竟隱藏著不得了的高爾夫才華！？在這份相遇的契機下，兩人的命運將發生巨大的轉變…。 ＜STAFF＞ 原作：かわさき健 作畫：古澤優 導演監督：オジング 劇本統籌：廣田光毅 角色設計：武內啟 色彩設計：近藤直登 美術監督：荒井和浩 CG製作：SMDE 3D監督：服部惠大 攝影監督：石山智之 音響監督：三間雅文 音樂：戶田信子 動畫製作：OLM 高爾夫設定監修：高爾夫文摘社 ＜CAST＞ \r\nWriting application                      : Lavf58.45.100\r\nCover                                    : Yes\r\n\r\nVideo\r\nID                                       : 2\r\nFormat                                   : AVC\r\nFormat/Info                              : Advanced Video Codec\r\nFormat profile                           : High@L5\r\nFormat settings                          : CABAC / 4 Ref Frames\r\nFormat settings, CABAC                   : Yes\r\nFormat settings, Reference frames        : 4 frames\r\nCodec ID                                 : avc1\r\nCodec ID/Info                            : Advanced Video Coding\r\nDuration                                 : 24 min 12 s\r\nBit rate                                 : 2 493 kb/s\r\nWidth                                    : 1 920 pixels\r\nHeight                                   : 1 080 pixels\r\nDisplay aspect ratio                     : 16:9\r\nFrame rate mode                          : Variable\r\nFrame rate                               : 23.976 (24000/1001) FPS\r\nMinimum frame rate                       : 23.974 FPS\r\nMaximum frame rate                       : 23.981 FPS\r\nColor space                              : YUV\r\nChroma subsampling                       : 4:2:0\r\nBit depth                                : 8 bits\r\nScan type                                : Progressive\r\nBits/(Pixel*Frame)                       : 0.050\r\nStream size                              : 432 MiB (89%)\r\nWriting library                          : x264 core 161 r3018 db0d417\r\nEncoding settings                        : cabac=1 / ref=4 / deblock=1:-1:-1 / analyse=0x3:0x113 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=crf / mbtree=1 / crf=21.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=12000 / vbv_bufsize=80000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=3:0.70\r\nmdhd_Duration                            : 1452993\r\nCodec configuration box                  : avcC\r\n\r\nAudio\r\nID                                       : 3\r\nFormat                                   : AAC LC\r\nFormat/Info                              : Advanced Audio Codec Low Complexity\r\nCodec ID                                 : mp4a-40-2\r\nDuration                                 : 24 min 13 s\r\nBit rate mode                            : Constant\r\nBit rate                                 : 306 kb/s\r\nChannel(s)                               : 2 channels\r\nChannel layout                           : L R\r\nSampling rate                            : 48.0 kHz\r\nFrame rate                               : 46.875 FPS (1024 SPF)\r\nCompression mode                         : Lossy\r\nStream size                              : 53.0 MiB (11%)\r\nLanguage                                 : Japanese\r\nDefault                                  : Yes\r\nAlternate group                          : 1",
  "bd_info": null,
  "description": "Torrent Info By: ANi API (Auto Generated)\n\nSubtitle:\n\n HardSub\n\nMediainfo:\n\n Resolution: 1080P\n\n Video Format: AVC\n\n Audio Format: AAC\n\n\nNote:\n\n Xunlei, torrent media player and offline downloader has been banned by our\nseeding server.\n\n If you have any concerns or feedback regarding the information or the file,\nplease don't hesitate to let me know.\n\n Please help by seeding the files after downloading. Your support is greatly\nappreciated. Thank you!\n\n Telegram Chat: https://t.me/+SH8EUievFGLKQew_ [https://t.me/+SH8EUievFGLKQew_]\n\n2024/10/5 1:31:21 UTC+0000 (Coordinated Universal Time)",
  "info_hash": "056809c71eceaa6802cc0d8e5fc0f00a91a28b1c",
  "size": 509739501,
  "internal": 1,
  "uploader": "ANi",
  "seeders": 14,
  "leechers": 3,
  "times_completed": 22,
  "tmdb_id": 243140,
  "imdb_id": 31957516,
  "tvdb_id": 434358,
  "mal_id": 0,
  "bgm_id": "0",
  "subtitle_tag": "繁中硬字@Baha",
  "category_id": 11,
  "type_id": 4,
  "resolution_id": 3,
  "created_at": "2024-10-05T01:31:23Z",
  "download_link": "https://monikadesign.uk/torrents/download/17269.29a93c973a01bac592f5560e2e8b682d",
  "details_link": "https://monikadesign.uk/torrents/17269"
}
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.handleJsonSelector(selectorBlock Selector, JToken parentObj, Dictionary`2 variables, Boolean required) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1347
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1690
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1715
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 368
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 389
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 802
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in ./Jackett.Server/Controllers/ResultsController.cs:line 256
```

**Comment by garfield69** [comment]
Looks like the website is not using a version of the API that the indexer was set up for. I'll update the indexer based on the log snippet you provided.

**Comment by garfield69** [comment]
v0.22.714

**Comment by loeminn** [comment]
> v0.22.714

thanks for fixing
