### ISSUE TITLE
[sharewood-api] (updating) Error: Passkey invalide ou non autorisation à utiliser l'API

### ISSUE THREAD

**Issue by neo62248** [Jackett/Jackett#15634]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Info Starting Jackett v0.22.735
Environment version: 8.0.8 (/app/Jackett/)
OS version: Unix 3.10.108.0 (64bit OS) (64bit process)
Jackett variant: CoreLinuxMuslAmdx64
Alpine Linux 3.17
Running in Docker: Yes (image build: v0.21.334-ls111)
```

### Description

Trying to configure indexer Sharewood API, because older indexer Sharewood disappeared from list, but was functional. 
Well, with API key this new indexer does not work in Jackett. 

URL of API in Sharewood are functional for my API key : https://www.sharewood.tv/api/my-api-key/search does the job. 

My config in Jackett : 
Field Site link : https://www.sharewood.tv/
Field Passkey : my passkey from Sharewood
Search freeleech only : OFF, Replace MULTi by another language in release name : OFF, Replace MULTi by this language : FRENCH, Replace VOSTFR and SUBFRENCH with ENGLISH : OFF

It seems config is not good... Can you help me resolve the problem? Maybe url is not OK ? 

Thanks a lot. 

### Logged Error Messages

```text
[v0.22.735.0] Jackett.Common.ExceptionWithConfigData: Error: Passkey invalide ou non autorisation à utiliser l'API
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.checkForError(WebResult loginResult, IList`1 errorBlocks) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 556
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 829
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1066
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by tardisbleu** [comment]
Hi, i have the same problem.

The passkey is not changing in the URL when the request is made : https://www.sharewood.tv/api/%7B%7B%20.Config.passkey%20%7D%7D/last-torrents?

I don't know the project, but it seems like the applyGoTemplateText function might be missing when building the URL : https://github.com/Jackett/Jackett/blob/81ccf8d828ad297bc538f275b655e42dd1c60b37/src/Jackett.Common/Indexers/Definitions/CardigannIndexer.cs#L824

**Comment by garfield69** [comment]
v0.22.749
