### ISSUE TITLE
Journal SPAM - 1500 log lines in one minute without Enhanced logging enabled

### ISSUE THREAD

**Issue by slrslr** [Jackett/Jackett#15631]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /home/user/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux 12 \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 6.1.0-26-amd64 (64bit OS) (64bit process)
Environment version: 8.0.8 (/opt/Jackett/)
Starting Jackett v0.22.545 (installed from Jackett.Binaries.LinuxAMDx64.tar.gz)
```

### Description

journalctl output shows hundreds of spammy lines done by jackett

```
> CRON[2498632]: pam_unix(cron:session): session closed for user abc
> jackett[859110]: 10-08 13:49:11 Error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
> jackett[859110]:     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
> jackett[859110]: <!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
> jackett[859110]: <!--[if IE 7]> <html class="lt-ie9 lt-ie8" lang="en"> <![endif]-->
> jackett[859110]: <!--[if IE 8]> <html class="lt-ie9" lang="en"> <![endif]-->
> jackett[859110]: <!--[if gt IE 8]><!-->
> jackett[859110]: <html xmlns="http://www.w3.org/1999/xhtml">
> jackett[859110]: <script src="js/extremlymtorrents.javas.js"></script>
>
> ...
> 
> jackett[859110]: </html>
> jackett[859110]: 10-08 13:49:12 Error Error downloading. indexer: extremlymtorrents path: https://extremlymtorrents.ws/download.php?id=2022395548&name=
> jackett[859110]: System.Exception: BencodeParser failed
> jackett[859110]:  ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
> jackett[859110]:    at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
> jackett[859110]:    at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
> jackett[859110]:    at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
> jackett[859110]:    at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 78
> jackett[859110]:    --- End of inner exception stack trace ---
> jackett[859110]:    at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 85
> jackett[859110]: 10-08 13:49:26 Info Torznab search in IndexerKnownToMEhere => Found 25 releases (from cache) [1ms]
> Tor[1300]: Invalid hostname [scrubbed]; rejecting
```

it is around 1550 lines in one block, in one minute. Jackett should refrain from writing this huge amount of lines this while I have "Enhanced logging:" disabled. Also the "Server Logs" accessible from the web console shows 

> Jackett.Common.IndexerException: Exception (indexerhere): A task was canceled.
> The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

each connection attempt is worth 30 lines inside the log. Also my question is how to workaround this issue, please?

### Logged Error Messages

```text
-
```

**Comment by garfield69** [comment]
The OP is stating that it is the regular log that is showing this excessive log output.
From what the OP has provided, it appears the issue is that when a download is attempted and the site does not return the expected torrent meta file, a `bencode.parser failed` error is generated. Which is fine, that was we expect to happen.
But the OP objects to the error trap dumping the full HTML that caused the error.
The HMTL  dump should only occur when enhanced logging is turned on.

**Comment by uheow847** [comment]
Can we please just have a mechanism to disable logging altogether?
