### ISSUE TITLE
 Jackett Version v0.22.779  -  System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by program-the-brain-not-the-heartbeat** [Jackett/Jackett#15643]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-10-13 09:29:59 	Info 	

Loaded 70 Native indexers.

2024-10-13 09:29:59 	Info 	

Loading Native indexers ...

2024-10-13 09:29:59 	Info 	

Using HTTP Client: HttpWebClient2

2024-10-13 09:29:59 	Info 	

Using FlareSolverr: http://flaresolverr:8191

2024-10-13 09:29:59 	Info 	

Using proxy: Disabled

2024-10-13 09:29:59 	Info 	

App config/log directory: /config/Jackett

2024-10-13 09:29:59 	Info 	

ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads

2024-10-13 09:29:59 	Info 	

Running in Docker: Yes (image build: v0.22.779-ls558)

2024-10-13 09:29:59 	Info 	

File /etc/issue: Welcome to Alpine Linux 3.20

2024-10-13 09:29:59 	Info 	

Jackett variant: CoreLinuxMuslAmdx64

2024-10-13 09:29:59 	Info 	

OS version: Unix 5.15.0.122 (64bit OS) (64bit process)

2024-10-13 09:29:59 	Info 	

Environment version: 8.0.10 (/app/Jackett/)

2024-10-13 09:29:59 	Info 	

Starting Jackett v0.22.779
```

### Description

Trying to remove the Flaresolverr endpoint URL and timeout from the settings.
Error occurs when hitting apply server settings.

### Logged Error Messages

```text
.NullReferenceException: Object reference not set to an instance of an object.

[v0.22.779.0] System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Server.Controllers.ServerConfigurationController.UpdateConfig(ServerConfig config) in ./Jackett.Server/Controllers/ServerConfigurationController.cs:line 82
   at lambda_method554(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by program-the-brain-not-the-heartbeat** [comment]
Request for http://<URL>:9117/api/v2.0/server/config

```
{
  "port": 9117,
  "external": true,
  "local_bind_address": "127.0.0.1",
  "cors": false,
  "updatedisabled": false,
  "prerelease": false,
  "blackholedir": "",
  "logging": false,
  "basepathoverride": "",
  "baseurloverride": "",
  "cache_enabled": true,
  "cache_ttl": "2100",
  "cache_max_results_per_indexer": "1000",
  "flaresolverrurl": "",
  "flaresolverr_maxtimeout": "",
  "omdbkey": "",
  "omdburl": "",
  "proxy_type": "-1",
  "proxy_url": "",
  "proxy_port": "",
  "proxy_username": "",
  "proxy_password": ""
}
```

Response:
```
{
  "result": "error",
  "error": "Object reference not set to an instance of an object.",
  "stacktrace": "   at Jackett.Server.Controllers.ServerConfigurationController.UpdateConfig(ServerConfig config) in ./Jackett.Server/Controllers/ServerConfigurationController.cs:line 82\n   at lambda_method554(Closure, Object, Object[])\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26"
}
```

**Comment by garfield69** [comment]
Was this as a result of you changing the settings via the Jackett dashboard or did you just edit/create a ServerConfig.json file of your own?
Because it looks like you are missing the ApiKey which is likely the cause of the exception,.
In addition, some of those other parameters have the wrong name.

I suggest you let Jackett create a fresh ServerConfig.json file
1. shutdown Jackett
2. delete the ServerConfig.json file
3. start Jackett

If you have been using any *Arr apps with Jackett then grab the Jackett ApiKey from one of the *Arr indexers:
1. shutdown Jackett
2.  replace the ApyKey
3. start Jackett

Note, if you have lost your old ApiKey you will need to update any *Arr app indexers with the new Jackett ApiKey
Also, if you cannot access the Jackett dashboard after the start-up then you may need to
1. shutdown Jackett
4. edit ServerConfig.json
5. change the AllowExternal to true
6. start Jackett

Let me know how you get on.

**Comment by program-the-brain-not-the-heartbeat** [comment]
This was editing through the dashboard but when I could not save, I shutdown Jackett and removed the flaresolverr API endpoint from the JSON and restarted.

Perhaps in a future version on the dashboard sending the POST request, flaresolverr_maxtimeout should be set to the default instead of attempting to send a null/empty string.

Thanks!
