### ISSUE TITLE
[teamos] (updating) Login failed: Selector "a[href="/account/"]" didn't match

### ISSUE THREAD

**Issue by reklov00** [Jackett/Jackett#15654]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2	
Using FlareSolverr: No
Using proxy: Disabled
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: 
Jackett variant: CoreLinuxAmdx64
OS version: Unix 6.6.38.0 (64bit OS) (64bit process)
Environment version: 8.0.7 (/usr/share/jackett/)
Starting Jackett v0.0.0
```

### Description

cookie and user-agent fields correctly filled but always showing the error:

''An error occurred while updating this indexer
Login failed: Selector "a[href="/account/"]" didn't match
''

### Logged Error Messages

```text
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="/account/"]" didn't match

[v0.0.0.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="/account/"]" didn't match
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.TestLogin()
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson)
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext)
```

**Comment by reklov00** [comment]
No, jackett is running from a seedbox, could be that the ''issue''

**Comment by garfield69** [comment]
Can you run docker on that seedbox? 
If so, then https://github.com/linuxserver/docker-firefox might allow you to use the firefox browser on that machine to fetch the cookie to use with Jackett on that machine.
Another possibility is if you have SSH access to the SeedBox you can try to configure a SSH tunnel.
This is tricky to configure but in simple words, it will open a port in the SeedBox and you can use that port as a proxy server. Take a look at this https://www.systutorials.com/proxy-using-ssh-tunnel
Otherwise you are out of luck.
