### ISSUE TITLE
IrishTV --> Error system. Found no results while trying to browse this tracker. 

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#15678]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
HTTP client: HttpWebClient
Proxy: HTTP
App: C:\ProgramData\Jackett
Docker: No
Jackett variant: CoreWindows, 64 bits, ~~last version~~ v0.22.856.0
```

### Description

Error	
System.Exception: Test search in IrishTV => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

---
Also error when click "Search" and "Configure" also.

### Logged Error Messages

```text
2024-10-28 10:45:54	Error	
System.Exception: Test search in IrishTV => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.22.856.0] System.Exception: Test search in IrishTV => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 332
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by AARON8888** [comment]
Hi @garfield69, see below full log.
[full log.txt](https://github.com/user-attachments/files/17555514/full.log.txt)

**Comment by garfield69** [comment]
There has been significant changes to the torrent page selectors. 
Since I do not have and account on this site, I cannot test that my changes work.
When the next release of Jackett is published, due out in about 11 hours or so, report success or provide a log.
Thanks.

**Comment by garfield69** [comment]
v0.22.862

**Comment by AARON8888** [comment]
Hi @garfield69. I confirm problem was solved. "Search", "Configure" and "Test" were right.
If you need an invite anyway I can send to you by email (jacketttest@gmail.com). :)
Just let me know.

**Comment by garfield69** [comment]
Thanks, I have an account but it was disabled back in May '24. And the jacketttest account is presumably good but the team member that uses it has not been available recently, hence the need for your logs ;-)
