### ISSUE TITLE
[erai-raws] (testing) Exception (erai-raws): Object reference not set to an instance of an object.: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ptcarino** [Jackett/Jackett#15687]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://<ip address>:8191/v1
Using proxy: Disabled
App config/log directory: /config/Jackett
Running in Docker: Yes (image build: v0.22.879-ls580)
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 6.6.56.0 (64bit OS) (64bit process)
Environment version: 8.0.10 (/app/Jackett/)
```

### Description

[Erai-raws search page.txt](https://github.com/user-attachments/files/17620574/Erai-raws.search.page.txt)

Erai-raws was suddenly throwing errors on Sonarr so I had initiated a test in Jackett and found the error stated above. I updated my docker image of Jackett but the issue persists.

I've provided the HTML source as instructed in the troubleshooting guide.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (erai-raws): Object reference not set to an instance of an object.

[v0.22.879.0] Jackett.Common.IndexerException: Exception (erai-raws): Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Definitions.EraiRaws.EraiRawsReleaseInfo..ctor(RssFeedItem feedItem) in ./Jackett.Common/Indexers/Definitions/EraiRaws.cs:line 331
   at Jackett.Common.Indexers.Definitions.EraiRaws.ConvertFeedItemsToEraiRawsReleaseInfo(IEnumerable`1 feedItems)+MoveNext() in ./Jackett.Common/Indexers/Definitions/EraiRaws.cs:line 162
   at Jackett.Common.Indexers.Definitions.EraiRaws.FilterForQuery(TorznabQuery query, IEnumerable`1 feedItems)+MoveNext() in ./Jackett.Common/Indexers/Definitions/EraiRaws.cs:line 189
   at Jackett.Common.Indexers.Definitions.EraiRaws.ConvertEraiRawsInfoToJackettInfo(IEnumerable`1 feedItems)+MoveNext() in ./Jackett.Common/Indexers/Definitions/EraiRaws.cs:line 200
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Jackett.Common.Indexers.BaseIndexer.FilterResults(TorznabQuery query, IEnumerable`1 results) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 171
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 382
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 399
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 812
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
Yup, I'm seeing this too today, so something has changed at erairaws with their RSS feed.
Jackett uses a C# indexer for this site, which is not my cup of tea, but i will take a look and see if I can figure out what's changed with the response and try to fix.

**Comment by garfield69** [comment]
Looks like one of the items in the results is missing the `erai:subtitles` field that the indexer expects to be present.
The code tries to replace the square brackets on an missing field and causes the reference abend.
I'll try to code an ignore clause, to only replace brackets if the field is present ;-)

**Comment by ptcarino** [comment]
thanks @garfield69. that was quick i didn't even manage to reply to you.

**Comment by garfield69** [comment]
v0.22.884

**Comment by garfield69** [comment]
Typical.
EraiRaws have changed the way the RSS token is passed today.
Old url: /feed/?TOKEN
New url: /feed/?token=YOUR_TOKEN

I'll have to update the indexer and if I get it to work I will publish soon afterwards, as I am not going to wat 24 hours for the next window!

**Comment by garfield69** [comment]
v0.22.885
