### ISSUE TITLE
[yggtorrent] (testing) Test search in YggTorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by PierreAlexx01** [Jackett/Jackett#15686]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
help
```

### Description

help

### Logged Error Messages

```text
help
```

**Comment by garfield69** [comment]
The word **help** in all the sections is **not** helpful, those sections are there for a reason, to provide info so we have something to work with to try to understand your issue.

**Fill in the environment section!**

Since all you have provided is the general error message in the ticket header, please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide a clue to understanding your issue better.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by hponcet** [comment]
```
Error on 20241104205306 for YggTorrent.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.ygg.re/auth/login using form selector form.login-form
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 618
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1771




<!DOCTYPE html>
<html>

<head>
    <title>YggTorrent - 1er Tracker BitTorrent Francophone</title>

    <meta name="description"
        content="Inscrivez-vous et rejoignez gratuitement la plus grande communauté P2P francophone pour profiter de milliers de films, séries et logiciels en libre-service !" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="interkassa-verification" content="932c353776e6f12b0dac4f654bd3b9bf" />
<link rel="icon" href="/favicon.ico" />

<!-- CSS Includes -->
<link rel="stylesheet" href="/assets/css/bootstrap.min.css?cachekiller=1549578">
<link rel="stylesheet" href="/assets/css/animate.min.css">
<link rel="stylesheet" href="/assets/css/fontawesome.css">
<link rel="stylesheet" href="/assets/css/custom.css?cachekiller=15495851">
<link rel="stylesheet" href="/assets/css/master.css?cachekiller=15497190">
<link rel="stylesheet" href="/assets/css/jnotifier.css">
<link rel="stylesheet" href="/assets/css/select2.min.css">
<link rel="stylesheet" href="/assets/css/select2-bootstrap.min.css">

<!-- Fonts -->
<link crossorigin="anonymous" media="all"
	href="https://fonts.googleapis.com/css?family=EB+Garamond|Montserrat:400,500,550,600,700|Roboto+Condensed:700|Open+Sans:600|Pangolin"
	rel="stylesheet">

<!-- Jquery -->
<script type="text/javascript" src="/assets/js/jquery.min.js"></script></head>

<body>

    <style>
      [...]
    </style>
    <div class="login-page">
        <div class="form">
            <div class="logo-brand">
                <a href="/"><img src="/assets/img/logov2.svg"></a>
            </div>

            <form class="login-form" form action="/auth/process_login" method="POST">
                <div class="alert alert-notice"><span class="ico_info-circle" style="margin-right:5px;"></span> Ygg
                    devient un Tracker Bittorrent privé : <br> La connexion est
                    désormais requise pour accéder au site.</div>
                <h3>Se connecter à Ygg</h3>
                <input type="text" placeholder="Pseudo" name="id" required="" />
                <input type="password" placeholder="Mot de passe" name="pass" required="" autocomplete="off" />
                <p class="error-form banned-account-msg">
                    <span>Votre compte a été banni ! </span> <a href="">(Voir le motif)</a>
                    <br />
                    Fin du ban : <span class="duration"></span>
                </p>
                <p class="error-form unconfirmed-account">
                    Vous n'avez pas confirmer votre compte à l'aide du mail que nous vous avons envoyé.
                </p>
                <p class="error-form bad-credentials">
                    Échec de connexion. Vérifiez vos identifiants.
                </p>
                <button type="submit"><span class="ico_lock" style="margin-right:5px;"></span> Connexion</button>
                <a class="register" href="/auth/register"><span class="ico_plus" style="margin-right:5px;"></span>
                    Créer un compte</a>
                <p class="message-forgot"><a href="/auth/reset_pass">Mot de passe oublié ?</a>
                </p>
            </form>
        </div>
    </div>

    <footer class="footer">
        <p>
            <a href="/copyright">Copyright Policy</a>
            <a href="/privacy">Privacy Policy</a>
        </p>
    </footer>
    <script type="text/javascript">
        [...]
    </script>
</body>

</html>
```

**Comment by garfield69** [comment]
This is not helpful.
I see the login html which clearly has the form with class "login-form" , and the error message stating that `selector form.login-form` was not found, which is obviously there.
But where is the rest of the log that shows all the traffic from the moment the indexer begins the login process to the end when the last error message is posted?

**Comment by Morchipon** [comment]
Hello
Same
![image](https://github.com/user-attachments/assets/146703e6-2874-4410-9a62-82fab9a412e5)

**Comment by garfield69** [comment]
>I'm seeing his account is banned.

No you are not ;-)
Those messages are hidden until activated by a script after the form is submitted.
Here is the full login page as opposed to that edit version someone uploaded
```HTML
<!DOCTYPE html>
<html>
    <head>
        <title>YggTorrent - 1er Tracker BitTorrent Francophone</title>
        <meta name="description" content="Inscrivez-vous et rejoignez gratuitement la plus grande communauté P2P francophone pour profiter de milliers de films, séries et logiciels en libre-service !"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="interkassa-verification" content="932c353776e6f12b0dac4f654bd3b9bf"/>
        <link rel="icon" href="/favicon.ico"/>
        <!-- CSS Includes -->
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css?cachekiller=1549578">
        <link rel="stylesheet" href="/assets/css/animate.min.css">
        <link rel="stylesheet" href="/assets/css/fontawesome.css">
        <link rel="stylesheet" href="/assets/css/custom.css?cachekiller=15495851">
        <link rel="stylesheet" href="/assets/css/master.css?cachekiller=15497190">
        <link rel="stylesheet" href="/assets/css/jnotifier.css">
        <link rel="stylesheet" href="/assets/css/select2.min.css">
        <link rel="stylesheet" href="/assets/css/select2-bootstrap.min.css">
        <!-- Fonts -->
        <link crossorigin="anonymous" media="all" href="https://fonts.googleapis.com/css?family=EB+Garamond|Montserrat:400,500,550,600,700|Roboto+Condensed:700|Open+Sans:600|Pangolin" rel="stylesheet">
        <!-- Jquery -->
        <script type="text/javascript" src="/assets/js/jquery.min.js"></script>
    </head>
    <body>
        <style>
            h3 {
                color: #f7f7f7;
                text-transform: uppercase;
                font-size: 15px;
                background: #00000014;
                margin-bottom: 15px;
                padding: 14px 13px;
                border-bottom: 2px solid #ffffff0f;
            }

            .logo-brand {
                display: flex;
                justify-content: center;
                align-items: center;
                margin-bottom: 30px;
            }

            .login-page {
                width: 550px;
                max-width: 100%;
                padding-top: 50px;
                margin: auto;
            }

            .form {
                position: relative;
                z-index: 1;
                margin: 0 auto 100px;
                padding: 15px;
            }

            .form input {
                outline: 0;
                background: #f2f2f2;
                width: 100%;
                border: 0;
                margin: 0 0 15px;
                padding: 15px;
                box-sizing: border-box;
                font-size: 14px;
                border-radius: 5px;
            }

            .form button {
                text-transform: uppercase;
                outline: 0;
                background: #46db8f;
                width: 100%;
                border: 0;
                padding: 15px;
                border-radius: 25px;
                color: #FFFFFF;
                font-size: 14px;
                -webkit-transition: all 0.3 ease;
                transition: all 0.3 ease;
                cursor: pointer;
            }

            a.register {
                text-transform: uppercase;
                text-align: center;
                outline: 0;
                background: #0e0e0e;
                width: 100%;
                border: 0;
                margin-top: 15px;
                font-weight: 500;
                display: block;
                padding: 15px;
                border-radius: 25px;
                color: #68debe !important;
                font-size: 14px;
                -webkit-transition: all 0.3 ease;
                transition: all 0.3 ease;
                cursor: pointer;
            }

            a.register:hover {
                background: #161c22;
            }

            .form button:hover, .form button:active, .form button:focus {
                background: #5bdb8e;
            }

            .form .message-forgot {
                text-align: center;
                margin: 15px 0 0;
                color: #ffffff;
                font-size: 16px;
                margin-top: 25px;
            }

            .form .message-forgot a {
                color: #feffff;
                text-decoration: none;
            }

            .form .register-form {
                display: none;
            }

            .login-form {
                margin: 20px;
            }

            .form img {
                width: 160px;
            }

            .error-form {
                display: none;
                color: #f2f2f2;
                font-weight: bold;
                text-align: center;
                margin-bottom: 15px;
            }

            .error-form>span {
                color: #ff4848;
            }

            .alert {
                margin-bottom: 1rem;
            }

            .error-form>a {
                color: #ffa74a;
                font-style: italic;
                font-weight: bold;
            }

            .error-form.bad-credentials, .error-form.unconfirmed-account {
                color: #ff4848;
            }

            .alert-notice {
                background-color: #d2ffc7;
                border-color: #6f6f6f;
                color: #0e0e0e;
                text-align: center;
            }

            .footer {
                background-color: #333;
                color: white;
                text-align: center;
                padding: 10px 0;
                position: relative;
                bottom: 0;
                width: 100%;
            }

            .footer a {
                color: #ddd;
                text-decoration: none;
                margin: 0 10px;
            }

            .footer a:hover {
                color: white;
                text-decoration: underline;
            }

            footer p {
                color: #ffffff;
                margin-bottom: 0;
            }
        </style>
        <div class="login-page">
            <div class="form">
                <div class="logo-brand">
                    <a href="/">
                        <img src="/assets/img/logov2.svg">
                    </a>
                </div>
                <form class="login-form" form action="/auth/process_login" method="POST">
                    <div class="alert alert-notice">
                        <span class="ico_info-circle" style="margin-right:5px;"></span>
                        Ygg
                    devient un Tracker Bittorrent privé : <br>La connexion est
                    désormais requise pour accéder au site.
                    </div>
                    <h3>Se connecter à Ygg</h3>
                    <input type="text" placeholder="Pseudo" name="id" required=""/>
                    <input type="password" placeholder="Mot de passe" name="pass" required="" autocomplete="off"/>
                    <p class="error-form banned-account-msg">
                        <span>Votre compte a été banni ! </span>
                        <a href="">(Voir le motif)</a>
                        <br/>
                        Fin du ban : <span class="duration"></span>
                    </p>
                    <p class="error-form unconfirmed-account">Vous n'avez pas confirmer votre compte à l'aide du mail que nous vous avons envoyé.
                </p>
                    <p class="error-form bad-credentials">Échec de connexion. Vérifiez vos identifiants.
                </p>
                    <button type="submit">
                        <span class="ico_lock" style="margin-right:5px;"></span>
                        Connexion
                    </button>
                    <a class="register" href="/auth/register">
                        <span class="ico_plus" style="margin-right:5px;"></span>
                        Créer un compte
                    </a>
                    <p class="message-forgot">
                        <a href="/auth/reset_pass">Mot de passe oublié ?</a>
                    </p>
                </form>
            </div>
        </div>
        <footer class="footer">
            <p>
                <a href="/copyright">Copyright Policy</a>
                <a href="/privacy">Privacy Policy</a>
            </p>
        </footer>
        <script type="text/javascript">

            if (!window._YGGConfig) {
                window._YGGConfig = {};
            }
            window._YGGConfig = {
                layoutType: '',
                isWide: true,
                isMobile: false,
                isHttpsEnabled: 1,
                isLogged: false,
                memberNick: '',
                memberIdHash: '',
                memberGroup: '',
                rootURL: 'https://www.ygg.re/',
                showLoginForm: false,
                bannedAccount: false,
                segment4Uri: true
            };
        </script>
        <!-- JS includes -->
        <script type="text/javascript" src="/assets/js/jquery.min.js"></script>
        <script type="text/javascript">
            $(".login-form").on("submit", function(e) {
                e.preventDefault();
                $.ajax({
                    type: 'POST',
                    url: '/auth/process_login',
                    data: new FormData(this),
                    contentType: false,
                    processData: false,
                    success: function(data) {
                        window.location.replace('/');
                    },
                    error: function(e, xhr, s) {
                        let error = e.responseJSON;
                        if (e.status == 403 && typeof error !== 'undefined') {
                            let ban_msg = $('.banned-account-msg');
                            ban_msg.find('.duration').html(error.duration);
                            ban_msg.find('a').attr('href', '/user/ban_reason?h=' + error.reason_key);
                            ban_msg.show();
                        } else if (e.status == 403) {
                            $('.bad-credentials').hide();
                            $('.unconfirmed-account').show();
                        } else if (e.status == 401) {
                            $('.unconfirmed-account').hide();
                            $('.bad-credentials').show();
                            $('#resetpass').show();
                        } else {
                            alert('Erreur ajax');
                        }

                    }
                });
            });
        </script>
    </body>
</html>
```

**Comment by garfield69** [comment]
@Morchipon Raise your own ticket and provide an enhanced log, the error trace is not useful in your case.
Hijacking this ticket for what you assume is a similar problem is not useful, I want to hear from the OP @PierreAlexx01 only.
Having multiple users on on ticket makes it difficult to track progress and resolution and makes my job so much more difficult sorting out the replies :-(

Thanks.
