### ISSUE TITLE
[erai-raws] (updating) Could not find releases from this URL

### ISSUE THREAD

**Issue by andy3469** [Jackett/Jackett#15689]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
11-05 09:39:59 Info Starting Jackett v0.22.879
11-05 09:40:00 Info Environment version: 8.0.10 (/app/Jackett/)
11-05 09:40:00 Info OS version: Unix 6.8.0.45 (64bit OS) (64bit process)
11-05 09:40:00 Info Jackett variant: CoreLinuxMuslAmdx64
11-05 09:40:00 Info File /etc/issue: Welcome to Alpine Linux 3.20
11-05 09:40:00 Info Running in Docker: Yes (image build: v0.22.844-ls571)
11-05 09:40:00 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
11-05 09:40:00 Info App config/log directory: /config/Jackett
11-05 09:40:00 Info Using proxy: Disabled
11-05 09:40:00 Info Using FlareSolverr: No
11-05 09:40:00 Info Using HTTP Client: HttpWebClient2
Hosting environment: Production
```

### Description

There was an update on the way Erai-raws is using the RSS token.
It's not `.../feed/?type=torrent&0879fd62733b8db8535eb1be2333` but `.../feed/?type=torrent&token=0879fd62733b8db8535eb1be2333`

### Logged Error Messages

```text
11-05 09:38:29 Error System.Exception: Could not find releases from this URL

[v0.22.879.0] System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.Definitions.EraiRaws.<>c.<ApplyConfiguration>b__32_0() in ./Jackett.Common/Indexers/Definitions/EraiRaws.cs:line 102
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 165
   at Jackett.Common.Indexers.Definitions.EraiRaws.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/EraiRaws.cs:line 101
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by andy3469** [comment]
I've just found that the issue was corrected with commit c705778ec332ba06fbcd6ed159f652baac716b30.
