### ISSUE TITLE
[gaytorrentru] (testing) Exception (gaytorrentru): Login failed: Selector "a[href$="/logout.php"]" didn't match: Parse error

### ISSUE THREAD

**Issue by zynexiz** [Jackett/Jackett#15680]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: /var/lib/jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Arch Linux \r (\l)
Jackett variant: CoreLinuxAmdx64
OS version: Arch Linux (running inside KVM virtual environment)
Environment version: 8.0.10 (/usr/lib/jackett/)
Jackett Data will be stored in: /var/lib/jackett
```

### Description

The site started showing error a while ago, gets Login failed: Selector "a[href$="/logout.php"]" didn't match: Parse error.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (gaytorrentru): Login failed: Selector "a[href$="/logout.php"]" didn't match

[v0.22.862.0] Jackett.Common.IndexerException: Exception (gaytorrentru): Login failed: Selector "a[href$="/logout.php"]" didn't match
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href$="/logout.php"]" didn't match
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 917
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1778
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 838
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1934
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 378
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 399
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 812
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
The indexer is working for me so this suggests the problem is at your end.
See if https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-selector can help you salve your issue for yourself.
If you cannot solve it then please turn on **enhanced** logging, repeat the login and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by zynexiz** [comment]
Have checked the "login failed" section, nothing there that helps. This is the complete logs with debugging. Odd that it works for you?
```

2024-10-30 17:43:15 	Debug 	

Executed controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)

2024-10-30 17:43:15 	Debug 	

Executing controller factory for controller Jackett.Server.Controllers.ServerConfigurationController (jackett)

2024-10-30 17:43:15 	Debug 	

Authorization was successful.

2024-10-30 17:43:15 	Debug 	

Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)

2024-10-30 17:43:15 	Debug 	

Execution plan of exception filters (in the following order): None

2024-10-30 17:43:15 	Debug 	

Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter

2024-10-30 17:43:15 	Debug 	

Execution plan of resource filters (in the following order): None

2024-10-30 17:43:15 	Debug 	

Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter

2024-10-30 17:43:15 	Info 	

Route matched with {action = "Logs", controller = "ServerConfiguration"}. Executing controller action with signature System.Collections.Generic.List`1[Jackett.Common.Models.CachedLog] Logs() on controller Jackett.Server.Controllers.ServerConfigurationController (jackett).

2024-10-30 17:43:15 	Info 	

Executing endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'

2024-10-30 17:43:15 	Debug 	

Request matched endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)'

2024-10-30 17:43:15 	Debug 	

Endpoint 'Jackett.Server.Controllers.ServerConfigurationController.Logs (jackett)' with route pattern 'api/v2.0/server/Logs' is valid for the request path '/api/v2.0/server/logs'

2024-10-30 17:43:15 	Debug 	

1 candidate(s) found for the request path '/api/v2.0/server/logs'

2024-10-30 17:43:15 	Debug 	

AuthenticationScheme: Cookies was successfully authenticated.

2024-10-30 17:43:15 	Debug 	

The request path /api/v2.0/server/logs does not match a supported file type

2024-10-30 17:43:15 	Debug 	

Request is continuing in applying rules. Current url is http://kvm-dlc:9117/api/v2.0/server/logs?_=1730306493865

2024-10-30 17:43:15 	Debug 	

Request is continuing in applying rules. Current url is http://kvm-dlc:9117/api/v2.0/server/logs?_=1730306493865

2024-10-30 17:43:15 	Debug 	

Request is continuing in applying rules. Current url is http://kvm-dlc:9117/api/v2.0/server/logs?_=1730306493865

2024-10-30 17:43:15 	Info 	

Request starting HTTP/1.1 GET http://kvm-dlc:9117/api/v2.0/server/logs?_=1730306493865 - - -

2024-10-30 17:43:10 	Info 	

Request finished HTTP/1.1 POST http://kvm-dlc:9117/api/v2.0/indexers/gaytorrentru/config - 500 - application/json 252.9105ms

2024-10-30 17:43:10 	Debug 	

Connection id "0HN7OV19R247G" completed keep alive response.

2024-10-30 17:43:10 	Debug 	

The response will be compressed with 'gzip'.

2024-10-30 17:43:10 	Error 	

Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href$="/logout.php"]" didn't match

[v0.22.862.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href$="/logout.php"]" didn't match
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 917
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1079
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

2024-10-30 17:43:10 	Info 	

Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'

2024-10-30 17:43:10 	Info 	

Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 240.7757ms

2024-10-30 17:43:10 	Debug 	

WebClient(HttpWebClient2): Returning OK => 11240 bytes
<!DOCTYPE html>
<html dir="ltr" lang="en" xmlns:og="https://opengraphprotocol.org/schema/" xmlns:fb="https://www.facebook.com/2008/fbml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="keywords" content="Free, Gay, Porn, Torrents, Free, Movies, Torrent, torrent, Forum, Chat, Men, mature, man, daddies, bears, polar, bears, sex, gays, oral, blow, job, master, slave, personals, gallery, oldies, master, sklave, Portal, Chat, chatroom, Mature">
    <meta name="revisit-after" content="1">

    <meta name="audience" content="all male gay adults">
    <meta name="language" content="en">
    <meta name="distribution" content="global">
    <link rel="icon" href="../../favicon.ico">
    <meta property="og:image" content="https://www.gaytor.rent/pic/gtfb.png"/>
    <meta property="og:type" content="porn community"/>
    <meta property="og:title" content="gaytor.rent - Your favorite adult tracker"/>
    <meta property="og:description" content="Login"/>
    <meta property="og:url" content="https://www.gaytor.rent/"/>
    <meta property="og:site_name" content="gaytor.rent"/>
    <link rel="shortcut icon" href="https://www.gaytor.rent/favicon.ico" type="image/x-icon">
    
    <title>Login</title>
    <!-- Bootstrap core CSS -->
    <link href="https://www.gaytor.rent/2.0/bootstrap2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://www.gaytor.rent/2.0/bootstrap2/css/theme.min.css?v=57" rel="stylesheet">
    <link href="https://www.gaytor.rent/2.0/gtnew.css?v=57" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://www.gaytor.rent/2.0/bootstrap/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="https://www.gaytor.rent/2.0/css/navbar.css" rel="stylesheet">

    <script src="https://www.gaytor.rent/2.0/js/jquery-1.12.4.min.js" type="29df2ae3b6d597d3832128a0-text/javascript"></script>

    </head>
<body class="main">
<!--<table width="100%" cellspacing="0" cellpadding="0" style='background:transparent;margin:0px;border:none;' border=0>
    <tr class="skinrow1">
        <td class="skin1">
                            <div style="width:405px; height:1px;"></div>
                    </td>
        <td class="skin2">
            <div id=(removed)                            </div>
        </td>
        <td class="skin3">
            <div style="cursor:hand; cursor:pointer; width:496px; height:62px;" onclick="top.location.href='/';"></div>
        </td>
    </tr>
    <tr class="skinrow2">
        <td class="skin4" colspan=3 nowrap>
            <nav class="gtnavbar" role="navigation" itemscope="itemscope" itemtype="https://www.schema.org/SiteNavigationElement">
                                    <li><a href="//www.gaytor.rent/">Home</a></li>
                                    <li><a href="//www.gaytor.rent/search.php">Search</a></li>
                                    <li><a href="//www.gaytor.rent/browse.php">Search (old)</a></li>
                                    <li><a href="//www.gaytor.rent/login.php">Login</a></li>
                                    <li><a href="//www.gaytor.rent/signup.php">Signup</a></li>
                                    <li><a href="//www.gaytor.rent/chat.php">Chat</a></li>
                                    <li><a href="//www.gaytor.rent/helpdesk.php">Helpdesk</a></li>
                                    <li><a href="//www.gaytor.rent/dmca.php">DMCA</a></li>
                                    <li><a href="//community.gaytorrent.ru">Forum</a></li>
                            </nav>
        </td>
    </tr>
    <tr class="skinrow2">
        <td class="skin5">
                    </td>
        <td class="skin6" nowrap>
                    </td>
        <td class="skin7">
                    </td>
    </tr>
</table> -->
<div class="container main-container" align="center">

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="https://www.gaytor.rent"><img src="https://www.gaytor.rent/2.0/gtlogonew.svg"></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                                                                                                                                                                                                                                                                                                                    <li><a href="//www.gaytor.rent/login.php">Login</a></li>
                                                                                                                                                            <li><a href="//www.gaytor.rent/signup.php">Signup</a></li>
                                                                                                                                                                                                                                                                                                <li><a href="//community.gaytorrent.ru">Forum</a></li>
                                                                        <!--                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Community <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#"><i class="icon-chat"></i> Chat</a></li>
                        </ul>
                    </li>
-->
                                    </ul>
                <ul class="nav navbar-nav navbar-right">
                    <!--                        <li><a href="https://www.gaytor.rent/login.php"><i class="icon-user"></i> Login</a></li> -->
                                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Support <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li><a href="//www.gaytor.rent/helpdesk.php">Helpdesk</a></li>
                                                                                                                                <li><a href="//www.gaytor.rent/dmca.php">DMCA</a></li>
                                                                                                                                                </ul>
                    </li>
                                    </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

<h1>Not logged in!</h1>
<p><b>Error:</b> The page you tried to view can only be used when you're logged in.</p>


<div class="panel panel-default" style="width:300px;">
<div class="panel-heading">
		<h3 class="panel-title">Please sign in</h3>
</div>
<div class="panel-body">

    <script type="29df2ae3b6d597d3832128a0-text/javascript">
        $(document).ready(function(){
            const x = window.screen.width;
            const y = window.screen.height;
            $('input#sw').val(x+":"+y);
        });

    </script>
		<h3 class="panel-title">Note: Enable cookies to log in.</h3><br>

	<form  class="form-signin" method="post" action="takelogin.php">


		<label for="username" class="sr-only">Enter your username</label>
		<input type="text" name="username" id="username" class="form-control" placeholder="Enter your username" required autofocus>
		<label for="password" class="sr-only">Password</label>
		<input type="password" name="password" id="password" class="form-control" placeholder="Enter your password" required>

        <input type="hidden" id="sw" name="sw" value="">



		<button type="submit" class='btn btn-lg btn-primary btn-block'>Log in!</button><br><br>

		</div>
</div>
<input type="hidden" name="returnto" value="/browse.php" >
</form>

<p>Don't have an account? <a href="signup.php">Sign up</a> right now!</p>

<p>You've lost your Password? <a href="lostpassword.php">Recover it</a> right now!</p>


</div> <!-- /container -->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://www.gaytor.rent/2.0/js/html5shiv.min.js"></script>
<script src="https://www.gaytor.rent/2.0/js/respond.min.js"></script>
<![endif]-->
<link href="https://www.gaytor.rent/2.0/css/jquery.qtip.min.css" rel="stylesheet">
<script type="29df2ae3b6d597d3832128a0-text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://www.gaytor.rent/2.0/css/font-awesome-4.2.0/css/font-awesome.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>

<script src="https://www.gaytor.rent/2.0/bootstrap2/js/bootstrap.min.js" type="29df2ae3b6d597d3832128a0-text/javascript"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="https://www.gaytor.rent/2.0/js/ie10-viewport-bug-workaround.js" type="29df2ae3b6d597d3832128a0-text/javascript"></script>


<script type="29df2ae3b6d597d3832128a0-text/javascript" src="https://www.gaytor.rent/js/TableSort861.js"></script>
<script type="29df2ae3b6d597d3832128a0-text/javascript" src="https://www.gaytor.rent/js/tt.js"></script>
<script type="29df2ae3b6d597d3832128a0-text/javascript" src="https://www.gaytor.rent/2.0/js/imagesloaded.pkgd.min.js"></script>
<script type="29df2ae3b6d597d3832128a0-text/javascript" src="https://www.gaytor.rent/2.0/tipped/js/imagesloaded/imagesloaded.pkgd.min.js"></script>
<script type="29df2ae3b6d597d3832128a0-text/javascript" src="https://www.gaytor.rent/2.0/js/jquery.qtip.min.js"></script>
<script type="29df2ae3b6d597d3832128a0-text/javascript" src="https://www.gaytor.rent/2.0/js/jquery.debounce-1.0.5.js"></script>



<script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="29df2ae3b6d597d3832128a0-|49" defer></script></body>
</html>

2024-10-30 17:43:10 	Debug 	

WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www.gaytor.rent/login.php?returnto=%2Fbrowse.php)

2024-10-30 17:43:10 	Warn 	

Redirected to https://www.gaytor.rent/login.php?returnto=%2Fbrowse.php from test login request
```

**Comment by garfield69** [comment]
Peculiar.
It looks like you are doing a TEST, and a re-login is detected, but the login is failing.
Have you tried using the Jackett dashboard to edit the config and saving to see if that succeeds?
If it works then the indexer should start working again.

**Comment by zynexiz** [comment]
> Peculiar. It looks like you are doing a TEST, and a re-login is detected, but the login is failing. Have you tried using the Jackett dashboard to edit the config and saving to see if that succeeds? If it works then the indexer should start working again.

I think the tracker got removed, so I tried adding it again, so probably that's the case.

**Comment by garfield69** [comment]
So now its working again?

**Comment by zynexiz** [comment]
> So now its working again?

No, that's when I get the error so I can't add it again. The old login information is still there (could be an old config preventing it?), how do I clean previous settings for that tracker?

**Comment by garfield69** [comment]
Presumably you have used a browser to login to the site and confirmed the credentials you are using are good.
So:
- Use the dashboard and click on the trashbin icon against the gaytorrentsru indexer to remove the config.
- Then restart Jackett to be absolutely sure cache and whatnot are cleared. (Its overkill, but still worth trying).
- Then add the indexer afresh with the wrench icon, fill in the credentials and save.

If save is good the indexer should be good to go.

**Comment by zynexiz** [comment]
> Presumably you have used a browser to login to the site and confirmed the credentials you are using are good. So:
> 
>     * Use the dashboard and click on the trashbin icon against the gaytorrentsru indexer to remove the config.
> 
>     * Then restart Jackett to be absolutely sure cache and whatnot are cleared. (Its overkill, but still worth trying).
> 
>     * Then add the indexer afresh with the wrench icon, fill in the credentials and save.
> 
> 
> If save is good the indexer should be good to go.

Yep, the login is working as it should, so no issue on that part. Except now i realized I have been blocked for 24h due to failed logins. I will give it a try tomorrow again. I have removed everything for that tracker, so hopefully this will help :)

**Comment by garfield69** [comment]
Didn't spot until just now that you had updated the logs in the OP with the dashboard failed login attempt.
This has provided the error message I needed to update the indexer, so future failed login attempts will generate a more useful message once Jackett is published in about 12 hours or so.

**Comment by zynexiz** [comment]
> Didn't spot until just now that you had updated the logs in the OP with the dashboard failed login attempt. This has provided the error message I needed to update the indexer, so future failed login attempts will generate a more useful message once Jackett is published in about 12 hours or so.

Yeh I saw that I missed a part of it so I added that to. Did you find what the problem was with that?

**Comment by garfield69** [comment]
yes. the indexer did not have any error detection section in the login block, so it just defaulted to the logout selector not found.
Now the indexer should recognise that the login failed and give the proper message (password incorrect, too many failures, unknown username, etc)

**Comment by zynexiz** [comment]
> yes. the indexer did not have any error detection section in the login block, so it just defaulted to the logout selector not found. Now the indexer should recognise that the login failed and give the proper message (password incorrect, too many failures, unknown username, etc)

Ahh, awesome. I will try update the yml file tomorrow and test it 😄

**Comment by garfield69** [comment]
v0.22.867

**Comment by zynexiz** [comment]
Confirmed working now after last update :smile:
