### ISSUE TITLE
[Req] LemonHD

### ISSUE THREAD

**Issue by seeson** [Jackett/Jackett#15705]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: LemonHD
- URL: https://lemonhd.club/
- Description: LemonHD is a CHINESE Private Torrent Tracker for HD MOVIES / TV
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private):  TBD
- Additional Comments:
```
Engine: NexusPHP Standard v1.5 Beta 4
Registration: Invite only
related to #10533

**Comment by garfield69** [comment]
As long as the site does not have an entrance exam where you have to upload and download to pass, then if you send an invite to `garfieldsixtynine [at] gmail [dot] com` I will build the cardigann indexer.
If there is an exam then please send the invite to `jacketttest [at] gmail [dot] com`

Alternatively, given that the site is using nexusphp we can usually build an indexer using a template, but we will need to see the html content of the torrents.php page in order to set the categories and crosscheck the field selectors.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by seeson** [comment]
> As long as the site does not have an entrance exam where you have to upload and download to pass, then if you send an invite to `garfieldsixtynine [at] gmail [dot] com` I will build the cardigann indexer. If there is an exam then please send the invite to `jacketttest [at] gmail [dot] com`
> 
> Alternatively, given that the site is using nexusphp we can usually build an indexer using a template, but we will need to see the html content of the torrents.php page in order to set the categories and crosscheck the field selectors. See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

Email sent, thanks a lot.

**Comment by garfield69** [comment]
I've added the indexer based on the html you have provided, but obviously it is untested beyond the login.
It should be available in the next Jackett release due out in about 10 hours or so.
Any issues please supply a full enhanced log and I will try to fixup. Thanks.

**Comment by garfield69** [comment]
v0.22.937

**Comment by seeson** [comment]
<html>
<body>

2024-11-15 20:06:03 | Error | System.Exception: Test search in LemonHD => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.  [v0.22.937.0] System.Exception: Test search in LemonHD => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 332    at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|7_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
-- | -- | --
2024-11-15 20:06:03 | Info | Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2024-11-15 20:06:03 | Info | Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 1330.894ms
2024-11-15 20:06:03 | Info | Test search in LemonHD => Found 0 releases [1330ms]
2024-11-15 20:06:03 | Error | CardigannIndexer (lemonhd): Error while parsing row ' <tr class="sticky_normal"> 	<td class="rowfollow nowrap" valign="middle" style="padding: 0px"> 		<a href="?cat=401"> 			<img class="c_movies" src="pic/cattrans.gif" alt="Movies" title="Movies" style="background-image: url(pic/lemonhd/icon.png);"> 		</a> 		<a href="?medium10=1&amp;standard5=1"> 			<img class="m_10_s_5" src="pic/cattrans.gif" alt="WEB-DL 2160p" title="WEB-DL 2160p" style="background-image: url(pic/lemonhd/icon.png);"> 		</a> 	</td> 	<td class="rowfollow torrenttd" width="100%" align="left"> 		<table class="torrentname" width="100%"> 			<tbody> 				<tr class="sticky_normal"> 					<td width="100%" class="embedded"> 						<div class="flex"> 							<img class="check_status uncheck" src="pic/trans.gif" title="待审核"> 							<a href="details.php?id=(removed)&amp;hit=1"> 								<b title="Octonauts and the Caves of Sac Actun 2020 2160p WEB-DL H.265 DDP5.1-HHWEB">Octonauts and the Caves of Sac Actun 2020 2160p WEB-DL H.265 DDP5.1-HHWEB</b><b>[<font class="hot">热门</font>]</b> 								<img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>免费</font></b>剩余时间：<b><span title=&quot;2024-11-16 15:07:58&quot;>19时1分</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);">&nbsp;限时：<b> 									<span title="2024-11-16 15:07:58">19时1分</span> 								</b> 							</a> 						</div> 						<div class="small_descr"> 							<div class="tags_block"> 								<div class="tags"> 									<span class="tag tag_gy">国语</span> 								</div> 							</div>海底小纵队：洞穴大冒险 / 海底小纵队大电影 / 海底小纵队水下洞穴 / 海底小纵队水底洞穴 \| 4K  \| 类型: 喜剧/动画/冒险 \| 导演: 布莱尔·西蒙斯 \| 主演: 泰莉莎·加拉赫/西蒙·格林诺/MichaelMurphy/PaulPanting/VinniePenna</div> 					</td> 					<td class="embedded" style="text-align: right; " valign="middle"> 						<div class="act"> 							<div class="flex"> 								<a href="download.php?id=(removed)"> 									<img class="download" src="pic/trans.gif" alt="download" title="下载本种"> 								</a> 								<a id="bookmark99" href="javascript:bookmark(34741, 99)"> 									<img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="收藏"> 								</a> 							</div> 							<div class="flex rating"> 								<a class="flex" href="https://movie.douban.com/subject/35155113" target="_blank"> 									<img class="douban" src="pic/trans.gif">&nbsp;7.3</a> 							</div> 						</div> 					</td> 				</tr> 			</tbody> 		</table> 	</td> 	<td class="rowfollow" style="display: none"> 		<a href="comment.php?action=add&amp;pid=34741&amp;type=torrent" title="添加评论">0</a> 	</td> 	<td class="rowfollow nowrap"> 		<span title="2024-11-15 15:07:58">4时<br>58分</span> 	</td> 	<td class="rowfollow">2.86<br>GB</td> 	<td class="rowfollow" align="center"> 		<b> 			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">26</a> 		</b> 	</td> 	<td class="rowfollow"> 		<b> 			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#leechers">1</a> 		</b> 	</td> 	<td class="rowfollow"> 		<a href="viewsnatches.php?id=(removed)"> 			<b>122</b> 		</a> 	</td> 	<td class="rowfollow"> 		<i>匿名</i> 	</td> </tr>':  System.Exception: Error while parsing field=details, selector=a[title][href*="details.php?id="], value=<null>: Selector "a[title][href*="details.php?id="]" didn't match  <tr class="sticky_normal"> 	<td class="rowfollow nowrap" valign="middle" style="padding: 0px"> 		<a href="?cat=401"> 			<img class="c_movies" src="pic/cattrans.gif" alt="Movies" title="Movies" style="background-image: url(pic/lemonhd/icon.png);"> 		</a> 		<a href="?medium10=1&amp;standard5=1"> 			<img class="m_10_s_5" src="pic/cattrans.gif" alt="WEB-DL 2160p" title="WEB-DL 2160p" style="background-image: url(pic/lemonhd/icon.png);"> 		</a> 	</td> 	<td class="rowfollow torrenttd" width="100%" align="left"> 		<table class="torrentname" width="100%"> 			<tbody> 				<tr class="sticky_normal"> 					<td width="100%" class="embedded"> 						<div class="flex"> 							<img class="check_status uncheck" src="pic/trans.gif" title="待审核"> 							<a href="details.php?id=(removed)&amp;hit=1"> 								<b title="Octonauts and the Caves of Sac Actun 2020 2160p WEB-DL H.265 DDP5.1-HHWEB">Octonauts and the Caves of Sac Actun 2020 2160p WEB-DL H.265 DDP5.1-HHWEB</b><b>[<font class="hot">热门</font>]</b> 								<img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>免费</font></b>剩余时间：<b><span title=&quot;2024-11-16 15:07:58&quot;>19时1分</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);">&nbsp;限时：<b> 									<span title="2024-11-16 15:07:58">19时1分</span> 								</b> 							</a> 						</div> 						<div class="small_descr"> 							<div class="tags_block"> 								<div class="tags"> 									<span class="tag tag_gy">国语</span> 								</div> 							</div>海底小纵队：洞穴大冒险 / 海底小纵队大电影 / 海底小纵队水下洞穴 / 海底小纵队水底洞穴 \| 4K  \| 类型: 喜剧/动画/冒险 \| 导演: 布莱尔·西蒙斯 \| 主演: 泰莉莎·加拉赫/西蒙·格林诺/MichaelMurphy/PaulPanting/VinniePenna</div> 					</td> 					<td class="embedded" style="text-align: right; " valign="middle"> 						<div class="act"> 							<div class="flex"> 								<a href="download.php?id=(removed)"> 									<img class="download" src="pic/trans.gif" alt="download" title="下载本种"> 								</a> 								<a id="bookmark99" href="javascript:bookmark(34741, 99)"> 									<img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="收藏"> 								</a> 							</div> 							<div class="flex rating"> 								<a class="flex" href="https://movie.douban.com/subject/35155113" target="_blank"> 									<img class="douban" src="pic/trans.gif">&nbsp;7.3</a> 							</div> 						</div> 					</td> 				</tr> 			</tbody> 		</table> 	</td> 	<td class="rowfollow" style="display: none"> 		<a href="comment.php?action=add&amp;pid=34741&amp;type=torrent" title="添加评论">0</a> 	</td> 	<td class="rowfollow nowrap"> 		<span title="2024-11-15 15:07:58">4时<br>58分</span> 	</td> 	<td class="rowfollow">2.86<br>GB</td> 	<td class="rowfollow" align="center"> 		<b> 			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">26</a> 		</b> 	</td> 	<td class="rowfollow"> 		<b> 			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#leechers">1</a> 		</b> 	</td> 	<td class="rowfollow"> 		<a href="viewsnatches.php?id=(removed)"> 			<b>122</b> 		</a> 	</td> 	<td class="rowfollow"> 		<i>匿名</i> 	</td> </tr>  ---> System.Exception: Selector "a[title][href*="details.php?id="]" didn't match  <tr class="sticky_normal"> 	<td class="rowfollow nowrap" valign="middle" style="padding: 0px"> 		<a href="?cat=401"> 			<img class="c_movies" src="pic/cattrans.gif" alt="Movies" title="Movies" style="background-image: url(pic/lemonhd/icon.png);"> 		</a> 		<a href="?medium10=1&amp;standard5=1"> 			<img class="m_10_s_5" src="pic/cattrans.gif" alt="WEB-DL 2160p" title="WEB-DL 2160p" style="background-image: url(pic/lemonhd/icon.png);"> 		</a> 	</td> 	<td class="rowfollow torrenttd" width="100%" align="left"> 		<table class="torrentname" width="100%"> 			<tbody> 				<tr class="sticky_normal"> 					<td width="100%" class="embedded"> 						<div class="flex"> 							<img class="check_status uncheck" src="pic/trans.gif" title="待审核"> 							<a href="details.php?id=(removed)&amp;hit=1"> 								<b title="Octonauts and the Caves of Sac Actun 2020 2160p WEB-DL H.265 DDP5.1-HHWEB">Octonauts and the Caves of Sac Actun 2020 2160p WEB-DL H.265 DDP5.1-HHWEB</b><b>[<font class="hot">热门</font>]</b> 								<img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>免费</font></b>剩余时间：<b><span title=&quot;2024-11-16 15:07:58&quot;>19时1分</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);">&nbsp;限时：<b> 									<span title="2024-11-16 15:07:58">19时1分</span> 								</b> 							</a> 						</div> 						<div class="small_descr"> 							<div class="tags_block"> 								<div class="tags"> 									<span class="tag tag_gy">国语</span> 								</div> 							</div>海底小纵队：洞穴大冒险 / 海底小纵队大电影 / 海底小纵队水下洞穴 / 海底小纵队水底洞穴 \| 4K  \| 类型: 喜剧/动画/冒险 \| 导演: 布莱尔·西蒙斯 \| 主演: 泰莉莎·加拉赫/西蒙·格林诺/MichaelMurphy/PaulPanting/VinniePenna</div> 					</td> 					<td class="embedded" style="text-align: right; " valign="middle"> 						<div class="act"> 							<div class="flex"> 								<a href="download.php?id=(removed)"> 									<img class="download" src="pic/trans.gif" alt="download" title="下载本种"> 								</a> 								<a id="bookmark99" href="javascript:bookmark(34741, 99)"> 									<img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="收藏"> 								</a> 							</div> 							<div class="flex rating"> 								<a class="flex" href="https://movie.douban.com/subject/35155113" target="_blank"> 									<img class="douban" src="pic/trans.gif">&nbsp;7.3</a> 							</div> 						</div> 					</td> 				</tr> 			</tbody> 		</table> 	</td> 	<td class="rowfollow" style="display: none"> 		<a href="comment.php?action=add&amp;pid=34741&amp;type=torrent" title="添加评论">0</a> 	</td> 	<td class="rowfollow nowrap"> 		<span title="2024-11-15 15:07:58">4时<br>58分</span> 	</td> 	<td class="rowfollow">2.86<br>GB</td> 	<td class="rowfollow" align="center"> 		<b> 			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#seeders">26</a> 		</b> 	</td> 	<td class="rowfollow"> 		<b> 			<a href="details.php?id=(removed)&amp;hit=1&amp;dllist=1#leechers">1</a> 		</b> 	</td> 	<td class="rowfollow"> 		<a href="viewsnatches.php?id=(removed)"> 			<b>122</b> 		</a> 	</td> 	<td class="rowfollow"> 		<i>匿名</i> 	</td> </tr>    at Jackett.Common.Indexers.Definitions.CardigannIndexer.handleSelector(selectorBlock Selector, IElement Dom, Dictionary`2 variables, Boolean required) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1277    at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1849    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1874


</body>
</html>

**Comment by seeson** [comment]
> v0.22.937

test run didn't pass, I opened the 'enhanced logging' and post the error, any other info needed?

**Comment by garfield69** [comment]
v0.22.938
Yeah, simple mistake on my part. I've released a fix, please do a check-for-updates and try the indexer again.
let me know how you go.

**Comment by seeson** [comment]
fixed, thanks a lot.

**Comment by garfield69** [comment]
\o/

**Comment by Rhilip** [comment]
@garfield69 [lemonhd.club](https://github.com/Jackett/Jackett/blob/d4f38a766acbffcb7797d5f7ebd25dd90c92a8de/src/Jackett.Common/Definitions/lemonhd.yml#L4) dead again, need to remove.

refs: https://t.me/ilovelemonjuice/14888

<img width="483" height="208" alt="Image" src="https://github.com/user-attachments/assets/8f8f6bf5-63f7-4082-b5e0-697c5c2ed521" />

**Comment by garfield69** [comment]
v0.24.1419
