### ISSUE TITLE
[req]: FilmesHdTorrent

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15718]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: FilmesHdTorrent
- URL: https://www.filmeshdtorrent.vip/
- Description: FilmesHdTorrent is a Public Torrent Tracker for Movies and TV Shows dubbed in Brazilian Portuguese
```

**Comment by garfield69** [comment]
v0.22.1093

**Comment by ilike2burnthing** [comment]
Primary site link is returning error:

```text
Jackett.Common.IndexerException: Exception (filmeshdtorrent): Invalid URI: The URI is empty.

[v0.22.1317.0] Jackett.Common.IndexerException: Exception (filmeshdtorrent): Invalid URI: The URI is empty.
 ---> System.Exception: Parse error
 ---> System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Jackett.Common.Indexers.Definitions.FilmesHdTorrentParser.ParseResponse(IndexerResponse indexerResponse) in ./Jackett.Common/Indexers/Definitions/FilmesHdTorrent.cs:line 92
   at Jackett.Common.Indexers.BaseWebIndexer.FetchPageAsync(IndexerRequest request, IParseIndexerResponse parser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 915
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 842
   at Jackett.Common.Indexers.BaseWebIndexer.FetchPageAsync(IndexerRequest request, IParseIndexerResponse parser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 931
   at Jackett.Common.Indexers.BaseWebIndexer.FetchReleasesAsync(Func`2 pageableRequestChainSelector, TorznabQuery query) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 880
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 378
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 403
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 816
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

@victorgveloso or anyone else see the cause of the issue?

**Comment by garfield69** [comment]
yes, the selection of the rows is not specific enough and is picking up non-torrent entries
I'll try to correct the selector.

**Comment by garfield69** [comment]
v0.22.1336

**Comment by garfield69** [comment]
https://bludvfilmes.org/ was an alternate domain for this indexer but it now redirects to https://www.torrentalerta.net/ which does not work with this indexer.

**Comment by garfield69** [comment]
v0.22.1719

**Comment by garfield69** [comment]
https://www.limontorrents.vip/ now redirects to https://limontorrents.lat/ but something is different on the new site and the indexer is not longer returning results.
This C# indexer will need to be updated for the new layout or deleted if no longer compatible.

**Comment by garfield69** [comment]
@victorgveloso can you take a look at this please?

https://www.limontorrents.vip/ now redirects to https://limontorrents.lat/ but something is different on the new site and the indexer is no longer returning results.
This C# indexer will need to be updated for the new layout or deleted if no longer compatible.

**Comment by garfield69** [comment]
v0.24.2330
