### ISSUE TITLE
[ourbits] (updating) Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by zjhok2005** [Jackett/Jackett#15720]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment
Jackett v0.22.950.0
docker ?
flaresolverr ?
VPN or proxy ?
platform OS ?

### Description

Adding indexer for ourbits getting 
```
An error occurred while updating this indexer
Login failed: Selector "a[href="logout.php"]" didn't match
```

### Logged Error Messages

```text
[v0.22.950.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
```
redacted enhanced log
```markdown
2024-11-17 15:28:23	Info	
Request finished HTTP/1.1 POST http://nas.me:9117/api/v2.0/indexers/ourbits/config - 500 - application/json 393.5228ms
2024-11-17 15:28:23	Debug	
Connection id "0HN87B3NITLP2" completed keep alive response.
2024-11-17 15:28:23	Debug	
The response will be compressed with 'gzip'.
2024-11-17 15:28:23	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match

[v0.22.950.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 917
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1079
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2024-11-17 15:28:23	Info	
Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2024-11-17 15:28:23	Info	
Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 330.0005ms
2024-11-17 15:28:23	Debug	
WebClient(HttpWebClient2): Returning OK => 17198 bytes
<!DOCTYPE html>
<html lang="zh">
REDACTED</html>
2024-11-17 15:28:23	Debug	
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: http://ourbits.club/index.php)
2024-11-17 15:28:23	Debug	
CardigannIndexer (ourbits): Cookies after login: REDACTED
2024-11-17 15:28:23	Debug	
CACHE Status / Total cached results: 1020
2024-11-17 15:28:23	Debug	
CACHE PruneCacheByTtl / Pruned queries: 0
2024-11-17 15:28:23	Debug	
CACHE CleanIndexerCache / Indexer: ourbits
2024-11-17 15:28:23	Debug	
Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2024-11-17 15:28:23	Debug	
Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ...
2024-11-17 15:28:23	Debug	
Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2024-11-17 15:28:23	Debug	
Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'.
2024-11-17 15:28:23	Debug	
Connection id "0HN87B3NITLP2", Request id "0HN87B3NITLP2:00000006": done reading request body.
2024-11-17 15:28:23	Debug	
Connection id "0HN87B3NITLP2", Request id "0HN87B3NITLP2:00000006": started reading request body.
```

**Comment by garfield69** [comment]
I do not have an account on ourbits so I cannot investigate independently.
So I am going to need to see the full enhanced log without your redactions, especially including the full HTML etc.
To maintain your privacy from this public repository, you could save your full enhanced log into a plain text file and attach the file to an email directed at  `garfieldsixtynine [at] gmail [dot] com` and I may be able to help you.
The alternative is to wait for @ilike2burnthing who does have an account but is rarely available these days due to other commitments.
Thanks.

**Comment by garfield69** [comment]
Another user has provided the logs needed to resolve this issue.
The log shows that the web site has changed their logout link, so the indexer needs to be updated to recognise the new link.
The updated indexer will be available in the next release of Jackett which is due to be published in about 13 hours or so.

**Comment by garfield69** [comment]
v0.22.1012
