### ISSUE TITLE
[YGGTORRENT] - CONNECTION FAILED ON JACKETT

### ISSUE THREAD

**Issue by likeveen** [Jackett/Jackett#15731]
### Have you checked our Troubleshooting page for your issue?

- [x] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client : HttpWebClient2
Using flaresolverr : yes
using proxy : no
app config/log directory: /config
Running in docker : Yes
Jackett Variant : LinuxAMD64
OS Version : 1.0.0.1708 DXP4800Plus
Environment Version : Version v0.22.998
```

### Description

Hello to all,

I just started in plex automation recently following a bad configuration I rebuilt all my docker.

jackett managed to connect to yggtorrent once I was able to add it to the list of indexers, unable to connect it with sonnarr, so I tried to test the indexer impossible to contact www.ygg.re

on prowlarr no problem to report everything works.

I also noticed in the logs of flaresolverr that the solving challenge works in a loop with jackett but not with prowlarr.

logs also talking about link redirection but not on prowlarr again

do you guys have any clue? 

### Logged Error Messages

```text
2024-11-27 00:00:03 	Error 	

System.Exception: Test search in YggTorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.22.998.0] System.Exception: Test search in YggTorrent => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 332
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

2024-11-27 00:00:03 	Info 	

Test search in YggTorrent => Found 0 releases [133387ms]

2024-11-26 23:59:31 	Warn 	

Redirected to https://www.ygg.re/donation/bonus from test login request

2024-11-26 23:59:25 	Info 	

CardigannIndexer(yggtorrent): Relogin required

2024-11-26 23:58:24 	Warn 	

Redirected to https://www.ygg.re/donation/bonus from test login request

2024-11-26 23:58:18 	Info 	

CardigannIndexer(yggtorrent): Relogin required
```

### Screenshots

![image](https://github.com/user-attachments/assets/6b0fad6f-1675-471b-a0f1-7909e1643e07)

**Comment by garfield69** [comment]
The indexer is working for me so this suggests the problem is at your end.
Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file which includes the _Debug_ and _HTML_. Hopefully this will provide the clue to understanding your issue.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by likeveen** [comment]
i see in the first line something that trigger me it says using flaresolverr : no then a bit later we see than my flaresolverr is well configured at http://192.168.1.55:8191

here is the log file
[log.txt](https://github.com/user-attachments/files/17930443/log.txt)

**Comment by garfield69** [comment]
The log shows that when Jackett then goes to perform the search, yggtorrent is redirecting you to the donation page, because your account appears to be disabled.
I suggest you use your browser to login to yggtorrent, and check the top most line of the page, the one that has your upload, download, ratio and account status. If the status is `Compte	Désactivé` then you know what that means.
As a final check, if you then attempt to use the menu option `torrents>Rechercher un torrent` you should get directed to the donation page instead.
This is not a Jackett or Flaresolverr issue.

**Comment by likeveen** [comment]
yeah but it's not the case for both my account is not disabled and when i'm goind in "search a torrent" it doesnt redirect me on donation page, i can download and use torrent manually from this site, and the automation ygg < prowlarr < radarr < overseer work well so thats not account related.

**Comment by garfield69** [comment]
I suggest that the account you are using with your Browser and Prowlarr is not the same account that you have set up for Jackett, because the log shows `47.38Go 47.40Go Ratio : 1 Compte	Désactivé` which is clearly not the same as your screen shot.

**Comment by likeveen** [comment]
Hey, i figured out you was right, but didn't understand a single minute why it doesnt worked.

after searching my docker was taking an old .json conf to connect to yggtorrent even with good credential in the UI config of jackett.

i deleted every files related to jackett, reinstall it from scratch and it was working.

sorry for taking your time on that kind of issue.
thanks for your help @garfield69
