### ISSUE TITLE
[rutracker] (updating) Request to https://rutracker.nl/forum/login.php failed (Error GatewayTimeout) - The tracker seems to be down.

### ISSUE THREAD

**Issue by Nasario2** [Jackett/Jackett#15742]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown

```

### Description

Hi there! I have vpn and jackett on the same server. So, when this problem was finded (with jackett) thу site rutracker.com stopped work with me from this vpn (i suppose it was blocked by IP), but there is official chromium plug in of rutracker https://chromewebstore.google.com/detail/fddjpichkajmnkjhcmpbbjdmmcodnkej
It works well. Maybe possible to take something from that plug in and put it to jackett, or in to FlareSolverr for solving this problem?

### Logged Error Messages

```text
2024-12-04 22:36:24	Error	
System.Exception: Request to https://rutracker.nl/forum/login.php failed (Error GatewayTimeout) - The tracker seems to be down.

[v0.22.1036.0] System.Exception: Request to https://rutracker.nl/forum/login.php failed (Error GatewayTimeout) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckSiteDown(WebResult response) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 680
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies, Dictionary`2 headers) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 651
   at Jackett.Common.Indexers.Definitions.RuTracker.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/RuTracker.cs:line 1451
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
The brutal reality is that there are no developers for Jackett that have any interest in spending a long time analysing the javascript for this browser extension and extracting the nuggets that need to be recoded as C# code to integrate into whatever feature it best fits into, Jackett indexer, jJckett proxy, Flaresolverr, who knows what.

Maybe some volunteer with the requisite knowledge in JS and C# will contribute a PR, but I don't expect any progress on this any time if ever.
