### ISSUE TITLE
[mteamtp] download causes: The SSL connection could not be established

### ISSUE THREAD

**Issue by yhm96** [Jackett/Jackett#15744]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: /volume1/@appdata/jackett/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
Environment version: 8.0.11 (/volume1/@appstore/jackett/share/)
Starting Jackett v0.22.1058
```

### Description

 When I use jackett download torrent in m-team, report the error. 

### Logged Error Messages

```text
Error downloading. indexer: mteamtp path: https://api.m-team.io/api/torrent/genDlToken?id=(removed) The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 188
   at Jackett.Common.Indexers.BaseWebIndexer.DoFollowIfRedirect(WebResult incomingResponse, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 755
   at Jackett.Common.Indexers.BaseWebIndexer.FollowIfRedirect(WebResult response, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies, Int32 maxRedirects) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 699
   at Jackett.Common.Indexers.BaseWebIndexer.Download(Uri link, RequestType method, String referer, Dictionary`2 headers) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 548
   at Jackett.Common.Indexers.BaseWebIndexer.Download(Uri link) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 530
   at Jackett.Common.Indexers.Definitions.MTeamTp.Download(Uri link) in ./Jackett.Common/Indexers/Definitions/MTeamTp.cs:line 161
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 56
```

**Comment by garfield69** [comment]
@yhm96  The indexer is working for others so the issue appears to be at your end.
consider using a system VPN or proxy.
