### ISSUE TITLE
Crash to desktop on launch and System.Net.Sockets.SocketException (10013) on Windows 10 + .NET Framework 8.0.11

### ISSUE THREAD

**Issue by MaxFrames** [Jackett/Jackett#15746]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Windows 10 Pro 22H2
.NET Framework Desktop Runtime 8.0.11.34221
Jackett installed in C:\ProgramData\Jackett
```

### Description

Just launch Jackett. The tray icon appears briefly then disappears and the error is logged in event viewer. Tried multiple versions of Jackett. Sometimes it works after a reboot, sometimes not.

### Logged Error Messages

```text
Application: JackettConsole.exe
CoreCLR Version: 8.0.1124.51707
.NET Version: 8.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Sockets.SocketException (10013): Tentativo di accesso al socket con modalità non consentite dalle rispettive autorizzazioni di accesso.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Jackett.Server.Program.Main(String[] args) in ./Jackett.Server/Program.cs:line 125
```

**Comment by garfield69** [comment]
I use win10home and have never had this issue so either its a settings issue, or your anti-malware is interfering or something.
Please post the content of `C:\ProgramData\Jackett\ServerConfig.json` so we can check your settings.
Replace your apikey with `REDACTED` to maintain privacy, and the same if the adminpassword is not null.
If you are not using localhost then feel free to redact the WAN ip address too.

**Comment by MaxFrames** [comment]
My antimalware is Microsoft Defender on default settings so it can't be the issue.
{
  "Port": 9117,
  "LocalBindAddress": "127.0.0.1",
  "AllowExternal": false,
  "AllowCORS": false,
  "APIKey": "[REDACTED]",
  "AdminPassword": null,
  "InstanceId": "025dfmpplvpszrxqoymjtbjz5wqglxolv4ywqsf48e2rx5hvw92iptdwh53zujmn",
  "BlackholeDir": null,
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": null,
  "BaseUrlOverride": null,
  "CacheEnabled": true,
  "CacheTtl": 2100,
  "CacheMaxResultsPerIndexer": 1000,
  "FlareSolverrUrl": null,
  "FlareSolverrMaxTimeout": 55000,
  "OmdbApiKey": null,
  "OmdbApiUrl": null,
  "ProxyType": 0,
  "ProxyUrl": null,
  "ProxyPort": null,
  "ProxyUsername": null,
  "ProxyPassword": null,
  "ProxyIsAnonymous": true
}

**Comment by garfield69** [comment]
I don't see anything unusual in your config.
- install ASP.Net core 8.0 runtime from https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-8.0.11-windows-x64-installer 
- installing  https://github.com/Jackett/Jackett/releases/download/v0.22.1063/Jackett.Installer.Windows.exe and as a Windows Service
See if that resolves your issue.

**Comment by MaxFrames** [comment]
Done. Let's see if it will still crash.

**Comment by MaxFrames** [comment]
After updating ASP.Net Core Runtime from v8.0.11 to v8.0.13 the problem is back.
I think the app should not depend on a particular minor release of the runtimes.

**Comment by ilike2burnthing** [comment]
> I think the app should not depend on a particular minor release of the runtimes.

It doesn't, this appears to be an issue unique to your system.

Uninstall Jackett, rename the folder `C:\ProgramData\Jackett` (e.g. `Jackett.bak`), download a fresh installer of Jackett, install as service (just double-click the installer, do not run as admin), see if that resolves the issue.

If not, uninstall again, delete the newly created `C:\ProgramData\Jackett`, restart in safe mode, and try installing again following the rest of the instructions above, see if it starts in safe mode, and then again when booted normally.
