### ISSUE TITLE
[wihd] (testing) Test search in World-In-HD => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

### ISSUE THREAD

**Issue by lol-powa** [Jackett/Jackett#15754]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://127.0.0.1:8191
Using proxy: Disabled
App config/log directory: /home/xxxx/.config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: No
File /etc/issue: Debian GNU/Linux trixie/sid \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 6.11.11.64 (64bit OS) (64bit process)
Environment version: 8.0.11 (/opt/Jackett/)
Starting Jackett v0.22.1085
```

### Description

Hello,

Add and configure WIHD indexer
Fill Login/Password (Double checked)
Save and test => KO (_Found no results while trying to browse this tracker_)

All other 14 indexers are working fine.

Thank you.

### Logged Error Messages

```text
2024-12-16 10:40:57	Error	System.Exception: Test search in World-In-HD => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.22.1083.0] System.Exception: Test search in World-In-HD => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 332
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2024-12-16 10:40:57	Info	Test search in World-In-HD => Found 0 releases [13059ms]
2024-12-16 10:40:47	Info	CardigannIndexer(wihd): Relogin required
2024-12-16 10:34:59	Error	System.Exception: Test search in World-In-HD => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.22.1083.0] System.Exception: Test search in World-In-HD => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 332
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by lol-powa** [comment]
Thank you for your quick answer.

Debug logs are attached.
Hope I didn't forget sensibles datas... 

[wihd debug logs.txt](https://github.com/user-attachments/files/18147294/wihd.debug.logs.txt)

**Comment by lol-powa** [comment]
@garfield69 I just sent you an invite. I Hope this will help.

**Comment by garfield69** [comment]
Try the indexer again with the next release of Jackett due out in about 10 hours or so, and let me know how it goes.

Also added 4 new categories, the 2160p set. Unfortunately since you redacted the img path for those categories I cannot be absolutely certain that I've labelled them correctly, so I assumed the order on the category list is:
 film2160p, series2160p, anime2160p, divers2160p. Let me know if that is correct ;-)

**Comment by garfield69** [comment]
v0.22.1088

**Comment by lol-powa** [comment]
Good morning,
Perfect, the indexed is working now.

Sorry for the img path.
Is there a way to help you to get the informations you need ? Logs ?

**Comment by garfield69** [comment]
>Sorry for the img path.
>Is there a way to help you to get the informations you need ? Logs ?

A HTML dump of the https://world-in-hd.net/torrents page would be useful. Email me the file if you want to maintain privacy from this public repo ;-)
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source for details

**Comment by garfield69** [comment]
Thanks. It looks like the order is films2160p, animation2160p, divers2160p, and series2160p so I've updated the indexer to match.

**Comment by garfield69** [comment]
v0.22.1096
