### ISSUE TITLE
[wolfmax4k] (testing) Exception (wolfmax4k): Invalid URI: The hostname could not be parsed.: Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by juanxu101** [Jackett/Jackett#15757]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.1088-ls616)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslAmdx64
OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
Environment version: 8.0.11 (/app/Jackett/)
Starting Jackett v0.22.1088
```

### Description

Using Wolfmax4K indexer, it seems that the RSS is generated correctly but when the system try to get de torrent I get the error

### Logged Error Messages

```text
Error downloading. indexer: wolfmax4k path: https://wolfmax4k.com/serie-online-1080p/237820
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at Jackett.Common.Utils.CookieUtil.RemoveAllCookies(CookieContainer cookieJar) in ./Jackett.Common/Utils/CookieUtil.cs:line 67
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 120
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 188
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 617
   at Jackett.Common.Indexers.BaseWebIndexer.<>c__DisplayClass12_0.<<RequestWithCookiesAndRetryAsync>b__0>d.MoveNext() in ./Jackett.Common/Indexers/BaseIndexer.cs:line 594
--- End of stack trace from previous location ---
   at Polly.ResiliencePipeline.<>c__10`1.<<ExecuteAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Outcome`1.GetResultOrRethrow()
   at Polly.ResiliencePipeline.ExecuteAsync[TResult](Func`2 callback, CancellationToken cancellationToken)
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAndRetryAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 593
   at Jackett.Common.Indexers.Definitions.Wolfmax4K.Download(Uri link) in ./Jackett.Common/Indexers/Definitions/Wolfmax4K.cs:line 161
   at Jackett.Server.Controllers.DownloadController.DownloadAsync(String indexerId, String path, String jackett_apikey, String file) in ./Jackett.Server/Controllers/DownloadController.cs:line 56
```

**Comment by garfield69** [comment]
I used the Jackett dashboard to do a manual search with wolfmax4k for `landman S01E06` and got two results, one for the 720p and the other for 1080p. I am able to click on the download link and get torrents for both, so the indexer appears to be working for me.
![image](https://github.com/user-attachments/assets/7fa9263d-957c-4401-985d-941dfc1f2546)

Have you tried again, does it still fail for you?

**Comment by juanxu101** [comment]
> I used the Jackett dashboard to do a manual search with wolfmax4k for `landman S01E06` and got two results, one for the 720p and the other for 1080p. I am able to click on the download link and get torrents for both, so the indexer appears to be working for me. ![image](https://private-user-images.githubusercontent.com/6933240/396876970-7fa9263d-957c-4401-985d-941dfc1f2546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTkxOTcsIm5iZiI6MTczNDU1ODg5NywicGF0aCI6Ii82OTMzMjQwLzM5Njg3Njk3MC03ZmE5MjYzZC05NTdjLTQ0MDEtOTg1ZC05NDFkZmMxZjI1NDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMjE1NDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YxMTFiMmY1NDhkOTllNjc4NDY0N2U4ZmUxOWZkZDU1MGQ0Njk1MDVhYjhiMDMwZWUxYjIyNjY4YzY5ODRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4cLLChi2An2b9kGLq4TETU1gCgnU97Yg9KnDc1grQuk)
> 
> Have you tried again, does it still fail for you?

I can analize alittle bit deeper and it seems that I found something, it seems that specific torrent broke the indexer, as you show I'm able to download torrent , but when I tried specific ones, like this one: "[La moderna S12E96 [HDTV] SPANISH]" for example i get an error.

![image](https://github.com/user-attachments/assets/f615f7c4-73df-425c-b6f6-40dce8fa49f2)

**Comment by garfield69** [comment]
That's because the download does not exist
![image](https://github.com/user-attachments/assets/0f543090-7a97-4570-b44b-df2ef6666f58)
I will take a look at the indexer (which is written in C#) and see if I can add a trap for the message or prevent the indexer from returning the result in the first place since that title does not have a download link.

**Comment by juanxu101** [comment]
Thank you @garfield69 :-) it seems that after it founds this, enter in a "broke" status, I suppose that the correction should repair this. Anyway, thank you very much!

**Comment by garfield69** [comment]
I cannot prevent the error because the download link is on the details page which the indexer does not use until you press the download link button, at which point its already too late.
But I can replace the error `System.UriFormatException: Invalid URI: The hostname could not be parsed.`
with `System.Exception: Error, the Download link at the requested path does not exist.`
which at least provides a slightly better reason for the failure.

**Comment by garfield69** [comment]
v0.22.1096

**Comment by juanxu101** [comment]
@garfield69 I can confirm that is solved, thank you very much :-)

**Comment by ptzetaa** [comment]
@juanxu101 how did you manage to connect jackett with wolfmax4k can you give me you discord,telegram or something to talk im not able to do it

**Comment by juanxu101** [comment]
> @juanxu101 how did you manage to connect jackett with wolfmax4k can you give me you discord,telegram or something to talk im not able to do it

You only need to add a new indexer and search for Wolfmax4K, this is the only thing I have done...
