### ISSUE TITLE
[concertos] (testing) test fails due to German localisation in response from indexer

### ISSUE THREAD

**Issue by volvic2** [Jackett/Jackett#15758]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: don't know how to figure this out ;)
Using Flaresolver: yes
Using proxy: disabled
App config/log directory: /config/Jackett
Running in Docker: Yes (kubernetes)
Jackett variant: CoreLinuxAmdx64
OS version: Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux (from lscr.io/linuxserver/jackett:latest)
Environment version: Jackett Version v0.22.1096
```

### Description

When I try to test indexer "Concertos" the test fails with error message "Test search in Concertos => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.".

When I look at the logs I think the problem probably might be that the indexer partly returns content localized in German: "<td class="torrents__age">vor 1 Tag</td>" & "System.Exception: Error while parsing field=date, selector=td.torrents__age, value=vor 1 Tag: DateTime parsing failed for "vor 1 Tag": System.Exception: FromFuzzyTime parsing failed"

I can't find any options to change language in my indexer's profile at all. So l set the envoronment variable "LANG=en_US" for the container but the response from the indexer still is partly German. .

What can I do to force Jackett requesting the url in English or what else can be done to make the indexer work in Jackett for me?

### Logged Error Messages

```text
2024-12-19 13:15:12	Error	
System.Exception: Test search in Concertos => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.

[v0.22.1096.0] System.Exception: Test search in Concertos => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 332
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2024-12-19 13:15:12	Info	
Test search in Concertos => Found 0 releases [1362ms]
2024-12-19 13:15:12	Error	
CardigannIndexer (concertos): Error while parsing row '
<tr class="torrents__row">
	<td align="center">
		<i class="torrent-icon fa fa-music"></i>
		<br>
		<a class="link" href="https://concertos.live/torrents?type_9=on">1080p</a>
		<a class="link" href="https://concertos.live/torrents?category_1=on">Live Concert</a>
	</td>
	<td>
		<a class="torrents__title link" href="https://concertos.live/torrent/6358">
			Big Something 2024-12-13 Ardmore Music Hall, Ardmore, PA 1080p nugs.net WEB-DL AVC AAC 2.0
		</a>
		<a href="https://concertos.live/torrent/6358/download">[Download]<i class="fa fa-download"></i>
		</a>
		<div class="tags">
			<span class="link tags__tag badge badge--user badge--condensed mbox mbox--small-right mbox--small-bottom">
				<a href="https://concertos.live/torrents?tags=big.something">big.something</a>
			</span>
			<span class="link tags__tag badge badge--user badge--condensed mbox mbox--small-right mbox--small-bottom">
				<a href="https://concertos.live/torrents?tags=jam.band">jam.band</a>
			</span>
			<span class="link tags__tag badge badge--user badge--condensed mbox mbox--small-right mbox--small-bottom">
				<a href="https://concertos.live/torrents?tags=nugs.net">nugs.net</a>
			</span>
			<span class="link tags__tag badge badge--user badge--condensed mbox mbox--small-right mbox--small-bottom">
				<a href="https://concertos.live/torrents?tags=year.2024">year.2024</a>
			</span>
		</div>
		<div>
		</div>
		<div class="flex flex--fluid">
			<span class="badge mbox--small-right mbox--mini-bottom">
				<i class="fa fa-upload"></i>
				By
				<a class="link" href="https://concertos.live/user/3821">will9512</a>
			</span>
			<span class="badge mbox--small-right mbox--mini-bottom">
				<i class="fa fa-heart"></i>
				1
			</span>
		</div>
	</td>
	<td class="torrents__age">vor 2 Tagen</td>
	<td class="torrents__size">7.94 GiB</td>
	<td>2</td>
	<td>0</td>
	<td>1</td>
</tr>':

System.Exception: Error while parsing field=date, selector=td.torrents__age, value=vor 2 Tagen: DateTime parsing failed for "vor 2 Tagen": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 221
 ---> System.Exception: DateTime parsing failed for "vor 2 Tagen": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 221
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 225
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ParseFields(String value, String FieldName, ReleaseInfo release, List`1 FieldModifiers, Uri searchUrlUri) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 2306
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1851
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1874
2024-12-19 13:15:12	Error	
CardigannIndexer (concertos): Error while parsing row '
<tr class="torrents__row">
	<td align="center">
		<i class="torrent-icon fa fa-music"></i>
		<br>
		<a class="link" href="https://concertos.live/torrents?type_9=on">1080p</a>
		<a class="link" href="https://concertos.live/torrents?category_1=on">Live Concert</a>
	</td>
	<td>
		<a class="torrents__title link" href="https://concertos.live/torrent/6359">
			Umphrey's McGee 2024-12-12 Metro, Chicago, IL 1080p nugs.net WEB-DL AVC AAC 2.0
		</a>
		<a href="https://concertos.live/torrent/6359/download">[Download]<i class="fa fa-download"></i>
		</a>
		<div class="tags">
			<span class="link tags__tag badge badge--user badge--condensed mbox mbox--small-right mbox--small-bottom">
				<a href="https://concertos.live/torrents?tags=jam.band">jam.band</a>
			</span>
			<span class="link tags__tag badge badge--user badge--condensed mbox mbox--small-right mbox--small-bottom">
				<a href="https://concertos.live/torrents?tags=nugs.net">nugs.net</a>
			</span>
			<span class="link tags__tag badge badge--user badge--condensed mbox mbox--small-right mbox--small-bottom">
				<a href="https://concertos.live/torrents?tags=umphrey%27s.mcgee">umphrey's.mcgee</a>
			</span>
			<span class="link tags__tag badge badge--user badge--condensed mbox mbox--small-right mbox--small-bottom">
				<a href="https://concertos.live/torrents?tags=year.2024">year.2024</a>
			</span>
		</div>
		<div>
		</div>
		<div class="flex flex--fluid">
			<span class="badge mbox--small-right mbox--mini-bottom">
				<i class="fa fa-upload"></i>
				By
				<a class="link" href="https://concertos.live/user/3821">will9512</a>
			</span>
			<span class="badge mbox--small-right mbox--mini-bottom">
				<i class="fa fa-heart"></i>
				2
			</span>
		</div>
	</td>
	<td class="torrents__age">vor 2 Tagen</td>
	<td class="torrents__size">3.98 GiB</td>
	<td>3</td>
	<td>0</td>
	<td>3</td>
</tr>':

System.Exception: Error while parsing field=date, selector=td.torrents__age, value=vor 2 Tagen: DateTime parsing failed for "vor 2 Tagen": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 221
 ---> System.Exception: DateTime parsing failed for "vor 2 Tagen": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 102
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 221
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in ./Jackett.Common/Utils/DateTimeUtil.cs:line 225
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ParseFields(String value, String FieldName, ReleaseInfo release, List`1 FieldModifiers, Uri searchUrlUri) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 2306
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1851
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1874
```

**Comment by sparafucile** [comment]
I finally found the reason. While clicking randomly through the Concertos website I noticed that the layout changes when I visit the "bonus" section (https://concertos.live/bonus). On pages with this layout I can chose a language at the top right corner. When I select English all dates are back to English and after that Jackett is able to parse the website again.

**Comment by garfield69** [comment]
Oh well done!

**Comment by garfield69** [comment]
Now that I know that concertos has a language option, I've added language support for date parsing, using code I found in asiancinema which is also an older unit3d site. ;-)

**Comment by garfield69** [comment]
v0.22.1101
