### ISSUE TITLE
[uhdbits] (testing) Exception (uhdbits): Login failed: No form found on https://uhdbits.org/login.php using form selector form.auth_form: Parse error

### ISSUE THREAD

**Issue by nod44** [Jackett/Jackett#15753]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
2024-12-15 22:53:45	Info	Using HTTP Client: HttpWebClient2
2024-12-15 22:53:45	Info	Using FlareSolverr: http://10.0.1.101:8191/
2024-12-15 22:53:45	Info	Using proxy: Disabled
2024-12-15 22:53:45	Info	App config/log directory: /config/Jackett
2024-12-15 22:53:45	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-12-15 22:53:45	Info	Running in Docker: Yes (image build: v0.22.1083-ls614)
2024-12-15 22:53:45	Info	File /etc/issue: Welcome to Alpine Linux 3.20
2024-12-15 22:53:45	Info	Jackett variant: CoreLinuxMuslAmdx64
2024-12-15 22:53:45	Info	OS version: Unix 6.6.44.0 (64bit OS) (64bit process)
2024-12-15 22:53:45	Info	Environment version: 8.0.11 (/app/Jackett/)
2024-12-15 22:53:44	Info	Starting Jackett v0.22.1083
```

### Description

UHDBits appears down.

### Logged Error Messages

```text
Jackett.Common.IndexerException: Exception (uhdbits): Login failed: No form found on https://uhdbits.org/login.php using form selector form.auth_form

[v0.22.1083.0] Jackett.Common.IndexerException: Exception (uhdbits): Login failed: No form found on https://uhdbits.org/login.php using form selector form.auth_form
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://uhdbits.org/login.php using form selector form.auth_form
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 618
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1771
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 842
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1934
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 378
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 403
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 816
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in ./Jackett.Common/Services/IndexerManagerService.cs:line 324
   at Jackett.Server.Controllers.IndexerApiController.Test() in ./Jackett.Server/Controllers/IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2024-12-15 22:54:06	Error	
Error on 20241215225406 for UHDBits.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://uhdbits.org/login.php using form selector form.auth_form
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 618
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.PerformQuery(TorznabQuery query) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1771
```

**Comment by garfield69** [comment]
The indexer is working for me which suggest the issue is at your end.
See if https://github.com/Jackett/Jackett/wiki/TroubleShooting/#login-failed-no-form-found-on-url helps you work out what is going on.
Failing that, provide a full **enhanced** log, see https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.
