### ISSUE TITLE
[rutracker] (updating) The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.: A task was canceled.

### ISSUE THREAD

**Issue by ArtemBay** [Jackett/Jackett#15788]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: Disabled
Using proxy: HTTP
App config/log directory: /home/qbittorrent/.config/Jackett
Running in Docker: No
Jackett variant: CoreLinuxArm64
OS version: Unix 6.1.119.0 (64bit OS) (64bit process)
Environment version: 8.0.11 (/opt/Jackett/)
Starting Jackett v0.22.1150
```

### Description

I installed torproxy for rutracker access. Rutracker responds for ~50 secs and i dont get captcha image.  

### Logged Error Messages

```text
дек 30 12:07:13 armbian jackett[299450]: 12-30 12:07:13 Error Error loading configuration: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
дек 30 12:07:13 armbian jackett[299450]:  ---> System.TimeoutException: A task was canceled.
дек 30 12:07:13 armbian jackett[299450]:  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
дек 30 12:07:13 armbian jackett[299450]:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
дек 30 12:07:13 armbian jackett[299450]:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
дек 30 12:07:13 armbian jackett[299450]:    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
дек 30 12:07:13 armbian jackett[299450]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
дек 30 12:07:13 armbian jackett[299450]:    at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
дек 30 12:07:13 armbian jackett[299450]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
дек 30 12:07:13 armbian jackett[299450]:    --- End of inner exception stack trace ---
дек 30 12:07:13 armbian jackett[299450]:    --- End of inner exception stack trace ---
дек 30 12:07:13 armbian jackett[299450]:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
дек 30 12:07:13 armbian jackett[299450]:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
дек 30 12:07:13 armbian jackett[299450]:    at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
дек 30 12:07:13 armbian jackett[299450]:    at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 188
дек 30 12:07:13 armbian jackett[299450]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 617
дек 30 12:07:13 armbian jackett[299450]:    at Jackett.Common.Indexers.Definitions.RuTracker.GetConfigurationForSetup() in ./Jackett.Common/Indexers/Definitions/RuTracker.cs:line 1406
```

### Screenshots

![image](https://github.com/user-attachments/assets/63bf7ef0-813b-4b02-9d06-f08f5fa0d786)

**Comment by ArtemBay** [comment]
I changed proxy and it fixed issue
