### ISSUE TITLE
Test of KickAssTorrent (kat.how) Fails

### ISSUE THREAD

**Issue by viking2** [Jackett/Jackett#1607]
Test of KickAssTorrent (kat.how) Fails
(I can access the webpage fine with my browser)

Jackett version:  0.7.1622.0 (windows 7 64-bit)

------------------------------- LOG --------------------------

2017-07-30 14:00:21.1951 Info   http://127.0.0.1:9117/Admin/test_indexer 
2017-07-30 14:00:21.1951 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2017-07-30 14:00:21.1951 Info DefaultHttpControllerSelector SelectController Admin 
2017-07-30 14:00:21.1951 Info HttpControllerDescriptor CreateController  
2017-07-30 14:00:21.1951 Info DefaultHttpControllerActivator Create  
2017-07-30 14:00:21.1951 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2017-07-30 14:00:21.1951 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2017-07-30 14:00:21.1951 Info AdminController ExecuteAsync  
2017-07-30 14:00:21.1951 Info ApiControllerActionSelector SelectAction  
2017-07-30 14:00:21.1951 Info ApiControllerActionSelector SelectAction Selected action 'Test()' 
2017-07-30 14:00:21.1951 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-07-30 14:00:21.1951 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2017-07-30 14:00:21.2091 Info HttpActionBinding ExecuteBindingAsync  
2017-07-30 14:00:21.2091 Info HttpActionBinding ExecuteBindingAsync  
2017-07-30 14:00:21.2091 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()' 
2017-07-30 14:00:21.2091 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2017-07-30 14:00:21.2091 Info ApiControllerActionInvoker InvokeActionAsync Action='Test()' 
2017-07-30 14:00:21.2091 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()' 
2017-07-30 14:00:21.2091 Debug IWebClient.GetString(Url:https://kat.how/search.php?q=) 
2017-07-30 14:00:21.9432 Debug IWebClient: Returning MovedPermanently => https://kickass.com.se/search.php?q= <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.13.2</center>
</body>
</html>
 
2017-07-30 14:00:21.9432 Info CardigannIndexer (kickasstorrent-kathow): Relogin required 
2017-07-30 14:00:21.9432 Debug IWebClient.GetString(Url:https://kat.how/search.php?q=) 
2017-07-30 14:00:21.9432 Debug IWebClient: delaying request for https://kat.how/search.php?q= by 1.2649579 seconds 
2017-07-30 14:00:22.6522 Debug IWebClient: Returning MovedPermanently => https://kickass.com.se/search.php?q= <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.13.2</center>
</body>
</html>
 
2017-07-30 14:00:22.6522 Info Found 0 releases from KickAssTorrent (kat.how) 
2017-07-30 14:00:22.6522 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__15.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Test>d__18.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 269
2017-07-30 14:00:22.6522 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]' 
2017-07-30 14:00:22.6522 Info ApiControllerActionInvoker InvokeActionAsync  
2017-07-30 14:00:22.6602 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()' 
2017-07-30 14:00:22.6602 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2017-07-30 14:00:22.6602 Info AdminController ExecuteAsync  
2017-07-30 14:00:22.6602 Info   Content-type='application/json; charset=utf-8', content-length=81 
2017-07-30 14:00:22.6602 Info AdminController Dispose  
2017-07-30 14:00:22.6602 Info AdminController Dispose

**Comment by thebluepotato** [comment]
PR #1693 on the way. In the meantime, just replace `https://kat.how` with `https://thekat.se`
Cheers!
