### ISSUE TITLE
Error:  "Bytes to be written to the stream exceed the Content-Length bytes size specified."

### ISSUE THREAD

**Issue by seanvree** [Jackett/Jackett#1677]
OS:  Windows 10E 1703 X64
Jackett Ver:  0.7.1644.0

I get the below error about every 10 minutes.  Jackett seems to be working fine, just wondering what this error is. 

```
Unhandled exception: Message = Bytes to be written to the stream exceed the Content-Length bytes size specified.
Data = System.Collections.ListDictionaryInternal
InnerException = 
TargetSite = System.IAsyncResult BeginWrite(Byte[], Int32, Int32, System.AsyncCallback, System.Object)
StackTrace =    at System.Net.HttpResponseStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.<SendResponseContentAsync>d__20.MoveNext()
HelpLink = 
Source = System
HResult = -2146233079
```

Screen Shot:

![image](https://user-images.githubusercontent.com/8906637/29346556-e44e211e-81fa-11e7-8f9c-4288b78a9902.png)

**Comment by kaso17** [comment]
Is this still happening in the latest version?

**Comment by seanvree** [comment]
@kaso17  - 

No, seems to be resolved.  

I'm on 0.8.151.0
