### ISSUE TITLE
Animebytes - new torznab api2 does not work - Sonarr

### ISSUE THREAD

**Issue by Quiksmage** [Jackett/Jackett#1762]
I found that the new torznab link grabbed from jackett does not work with AnimeBytes.

http://[IP]:9117/jackett/api/v2.0/indexers/animebytes/results/torznab/

```
17-8-31 15:50:08.7|Warn|HttpClient|HTTP Error - Res: [GET] http://[IP]:9117/jackett/api/v2.0/indexers/animebytes/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100: 400.BadRequest
<Error><Message>animebytes does not support the requested query.</Message></Error>
17-8-31 15:50:08.7|Warn|Torznab|Unable to connect to indexer

[v2.0.0.4949] NzbDrone.Common.Http.HttpException: HTTP request failed: [400:BadRequest] [GET] at [http://[IP]:9117/jackett/api/v2.0/indexers/animebytes/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 94
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 302
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 288
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 315
<Error><Message>animebytes does not support the requested query.</Message></Error>
```

My current one still works with the old torznab URL
http://[IP]:9117/jackett/torznab/animebytes

If I lost this URL, I wouldn't know it existed.
Is there anything I can do to make this work with the URL jackett now provides (api 2.0)?

**Comment by Quiksmage** [comment]
nevermind... adding 5070 to the anime field in sonarr made it work.
