### ISSUE TITLE
Service won't start on fresh install

### ISSUE THREAD

**Issue by 47094623** [Jackett/Jackett#1956]
Trying to install Jackett as fresh install. Service wouldn't start so I ran from command line and it gave this error after the info line "Starting web server at http://127.0.0.1:9117/"

Jackett version:  v0.8.259
Windows 10
-------------------------------

"Error Top level exception System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: The network location cannot be reached. For information about network troubleshooting, see Windows Help
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at Jackett.Services.ServerService.Start() in C:\projects\jackett\src\Jackett\Services\ServerService.cs:line 324
   at JackettConsole.Program.Main(String[] args) in C:\projects\jackett\src\Jackett.Console\Program.cs:line 225"

**Comment by garfield69** [comment]
Did you run the install with administration access?

**Comment by 47094623** [comment]
Yes. Currently rebuilding computer so can't give updates however.

**Comment by plugpoint** [comment]
For me this was caused by http.sys service. what i had to do was add 127.0.0.1 to the http.sys service using:

`netsh http add iplisten ipaddress=127.0.0.1`

on elevated cmd

**Comment by kaso17** [comment]
@plugpoint thank you for looking into this.

jackett should already execute these commands during installation:
```
netsh.exe http add urlacl http://127.0.0.1:9117/ sddl=D:(A;;GX;;;S-1-1-0)
netsh.exe http add urlacl http://localhost:9117/ sddl=D:(A;;GX;;;S-1-1-0)
```
To me it looks like it should be doing more or less the same.
It would be great if you could try these commands instead of the the more generic iplisten option.

**Comment by plugpoint** [comment]
@kaso17  
I tried these commands and i get this:

Url reservation add failed, Error: 183
Cannot create a file when that file already exists.

If jackett is running and i remove the iplisten for 127.0.0.1 i can get access from the localhost address but not 127.0.0.1. then if i attempt to stop and start the service it fails to start. I'm not sure what this means.

I actually have 2 static ip addresses on my pc, one for docker and one that i set nestsh.exe to use. This must be causing the issue on my end as it used to work fine before i changed to this config. But jackett was the only service that had this problem so i would assume there is a way to fix this in the code.
