### ISSUE TITLE
Issue Starting Jackett v0.8.349

### ISSUE THREAD

**Issue by dbershev** [Jackett/Jackett#2054]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  v0.8.349
Mono version (if not using Windows):  
Mono JIT compiler version 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
-------------------------------

I'm having an issue when I try to launch Jackett. This happened after an update to the latest version and updating Mono. Running "mono /opt/jackett/JackettConsole.exe -p 80 --debug" gives the following error:

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Jackett.Engine' threw an exception. ---> System.BadImageFormatException: Could not resolve field token 0x040002fc
  at Autofac.Module.Configure (Autofac.Core.IComponentRegistry componentRegistry) [0x0001a] in <d2e21a4947d7428dab6692e67eb66c09>:0
  at Autofac.ContainerBuilder.Build (Autofac.Core.IComponentRegistry componentRegistry, System.Boolean excludeDefaultModules) [0x00046] in <d2e21a4947d7428dab6692e67eb66c09>:0
  at Autofac.ContainerBuilder.Build (Autofac.Builder.ContainerBuildOptions options) [0x00013] in <d2e21a4947d7428dab6692e67eb66c09>:0
  at Jackett.Engine.BuildContainer () [0x0000b] in <0a90acc946724add8bcae2ba4199a336>:0
  at Jackett.Engine..cctor () [0x00000] in <0a90acc946724add8bcae2ba4199a336>:0
   --- End of inner exception stack trace ---
  at JackettConsole.Program.Main (System.String[] args) [0x005b6] in <cfcc44715b314117adcb869359eb5d3b>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Jackett.Engine' threw an exception. ---> System.BadImageFormatException: Could not resolve field token 0x040002fc
  at Autofac.Module.Configure (Autofac.Core.IComponentRegistry componentRegistry) [0x0001a] in <d2e21a4947d7428dab6692e67eb66c09>:0
  at Autofac.ContainerBuilder.Build (Autofac.Core.IComponentRegistry componentRegistry, System.Boolean excludeDefaultModules) [0x00046] in <d2e21a4947d7428dab6692e67eb66c09>:0
  at Autofac.ContainerBuilder.Build (Autofac.Builder.ContainerBuildOptions options) [0x00013] in <d2e21a4947d7428dab6692e67eb66c09>:0
  at Jackett.Engine.BuildContainer () [0x0000b] in <0a90acc946724add8bcae2ba4199a336>:0
  at Jackett.Engine..cctor () [0x00000] in <0a90acc946724add8bcae2ba4199a336>:0
   --- End of inner exception stack trace ---
  at JackettConsole.Program.Main (System.String[] args) [0x005b6] in <cfcc44715b314117adcb869359eb5d3b>:0

**Comment by NathanNZ** [comment]
Sorry to hear you are having problems! What operating system are you running on?

**Comment by Stanzilla** [comment]
```2017-11-01 10:20:37.9806 Error Top level exception System.TypeInitializationException: The type initializer for 'CurlSharp.NativeMethods' threw an exception. ---> System.DllNotFoundException: api-ms-win-core-sysinfo-l1-2-0.dll
  at (wrapper managed-to-native) Interop+mincore:GetNativeSystemInfo (Interop/mincore/SYSTEM_INFO&)
  at System.Runtime.InteropServices.RuntimeInformation.get_OSArchitecture () [0x0001c] in <dd91439f3167478ebd2cbf9c036a1395>:0 
  at CurlSharp.NativeMethods..cctor () [0x0000c] in C:\projects\jackett\src\CurlSharp\NativeMethods.cs:51 
   --- End of inner exception stack trace ---
  at Jackett.Utils.Clients.UnixLibCurlWebClient.Init () [0x0008a] in <0a90acc946724add8bcae2ba4199a336>:0 
  at Jackett.Services.ServerService.Initalize () [0x003e0] in <0a90acc946724add8bcae2ba4199a336>:0 
  at JackettConsole.Program.Main (System.String[] args) [0x0058a] in <cfcc44715b314117adcb869359eb5d3b>:0 
```

On my Syno 6.1

**Comment by flightlevel** [comment]
Can you both try latest pre-release https://github.com/Jackett/Jackett/releases/tag/v0.8.354 and report back

**Comment by flightlevel** [comment]
Still an issue with latest release?

**Comment by Stanzilla** [comment]
@flightlevel 0.8.355.0 seems to work just fine, thank you!

**Comment by IronTooch** [comment]
For anyone getting here from the Google for a problem with 
```
 Fatal Unable to start Kestrel. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.X509Certific
ates, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
May  2 07:20:19 casino jackett[1063]: File name: 'System.Security.Cryptography.X509Certificates, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
May  2 07:20:19 casino jackett[1063]:    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
May  2 07:20:19 casino jackett[1063]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
May  2 07:20:19 casino jackett[1063]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
May  2 07:20:19 casino jackett[1063]: 05-02 07:20:19 Fatal Unable to start Kestrel. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.X509Certific
ates, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
```

The answer is to make the .config and Jackett path in your user's home directory.
