### ISSUE TITLE
Cinematik downloads not working

### ISSUE THREAD

**Issue by petredr** [Jackett/Jackett#2253]
Jackett version:  0.8.496.0

Hi,
First time user so please excuse if I've made a mistake. Im getting a weird error. I can browse/list/search but cannot download. 
For eg: if I try to download, I get:

This 127.0.0.1 page can’t be found
No webpage was found for the web address: http://127.0.0.1:9117/dl/cinematik/?jackett_apikey=
(Lots of data)

When I try to download to blackhole, I get:
Error: Download selector a[href^="download.php?id="] didn't match

The log gets large (450kB+) because I think the torrent data is downloaded into the log so I've redacted that as well as my passkey:

2017-12-08 14:47:54.6271 Error CardigannIndexer (cinematik): Download selector a[href^="download.php?id="] didn't match:
d8:announce74:http://cinematik.net/announce.php?passkey=*REDACTED*:created by25:Transmission/2.92 (14714)13:creation datei1512767260e8:encoding5:UTF-84:infod5:filesld6:lengthi6144e4:pathl8:VIDEO_TS12:VIDEO_TS.BUP

***GARBAGE TORRENT DATA????***

privatei1e6:source37:[https://www.cinematik.net] Cinematikee 
2017-12-08 14:47:54.6421 Error Error downloading cinematik https://www.cinematik.net/download.php?id=68200&hit=1 System.Exception: Download selector a[href^="download.php?id="] didn't match
   at Jackett.Indexers.CardigannIndexer.<Download>d__28.MoveNext() in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1529
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.DownloadController.<Download>d__5.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\DownloadController.cs:line 54 

I'm really at a loss which is why I've made the report. If you need the log, I can upload it but its mainly garbage (probably torrent data thats made its way to the log). I am running Windows Server 2012 if that makes any difference.

**Comment by kaso17** [comment]
unfortunately I don't have access and can't test it but from your description I suspect that the indirect download is no longer needed.

Can you please try to edit the definition (Definitions/cinematik.yml in your jackett directory) and remove line 46/47 which I've marked here:
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/cinematik.yml#L46-L47

**Comment by mhendu** [comment]
This appears to work for me.

**Comment by kaso17** [comment]
thank you for confirming,

fixed via 9cc4021cb30c0780978c2a71ed81be0df74f0aa1
