### ISSUE TITLE
[hdtorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by wifiuk** [Jackett/Jackett#2327]
today HDtorrents has stopped working, it fails the tests each time..

==error log==
2017-12-26 20:46:10.9664 Info Found 0 releases from **HD-Torrents** 
2017-12-26 20:46:10.9774 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.V20.IndexerApiController.<Test>d__12.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:line 130

Jackett Version 0.8.527.0

**Comment by wifiuk** [comment]
its started working after having to go into settings page and click on ok again... weird.
