### ISSUE TITLE
[WIP][HELP] Adding HacheDe (Spanish Tracker)

### ISSUE THREAD

**Issue by Albvadi** [Jackett/Jackett#2396]
Jackett version: 0.8.527.0 
________________________________________________________
Hi!
following the work of @keystorm [here](https://github.com/Jackett/Jackett/issues/1468#issuecomment-344028431) (thanks!), I have a working version for the spanish tracker HacheDe.

But, there are a few inconveniences that I am not able to solve.

- [x] Limit results: By default, tracker split the results in 20. So, the max number for obtain results in Jackett it´s 20. There are any way to obtain all the results??
![image](https://user-images.githubusercontent.com/6285255/34772132-47007e62-f607-11e7-89bf-6f19ee2b55d1.png)

- [x] Download and Upload VolumeFactor: For the download/upload multiplier, they are using the same image, and the factor it´s in an attribute. For example: 
    - upload 1.5x --> `<img src="https://hachede.me/styles/default/torrents/torrent_multiple_upload.png" alt="" class="middle" id="" rel="resized_by_tsue" original-title="Multiplicador de subida: 1.5">` 
    - upload 2x --> `<img src="https://hachede.me/styles/default/torrents/torrent_multiple_upload.png" alt="" class="middle" id="" rel="resized_by_tsue" original-title="Multiplicador de subida: 2">`

    How can I select only the `original-title` form the image? I´m using a generic config for the moment:
    ```yaml
    uploadvolumefactor:
          case:
            img[src$="torrent_free.png"]: "0"
            img[src$="torrent_multiple_upload.png"]: "1.5"
            "*": "1" # default to 1
    ```

Thanks!

**Comment by keystorm** [comment]
Hi! Great work @Albvadi !

I have no clue with the first issue, but your second issue should probably work with this:

````yaml
uploadvolumefactor:
      case:
        img[src$="torrent_free.png"]: "0"
        img[src$="torrent_multiple_upload.png"][original-title$="1.5"]: "1.5"
        img[src$="torrent_multiple_upload.png"][original-title$="2"]: "2"
        "*": "1" # default to 1
````

**Comment by Albvadi** [comment]
Not working... :disappointed_relieved: 
I tested:

- `img[original-title$="1.5"]: "1.5"`
- `img[src$="torrent_multiple_upload.png"][original-title$="1.5"]: "1.5"`
- `"img[\"original-title\"=\"Multiplicador de subida: 1.5\"]": "1.5"`
- `"img[src$="torrent_multiple_upload.png"]:contains(\"Multiplicador de subida: 1.5\")": "1.5"`

And none of them works... Always show 1 as default.
Only work with a simple selector like my example: `img[src$="torrent_multiple_upload.png"]`

**Comment by keystorm** [comment]
Have you checked that is the original HTML? Sometimes javascript might change the source code dynamically (e.g. turning `title` into `original-title`) Jackett will probably read the unmodified source, I think.

So maybe try `[title$="1.5"]` ?

**Comment by kaso17** [comment]
original-title is created by various JS frameworks.
[title="1.5"] should work
An alternative is to use an standard selector+filter to extract the actual number (instead of the case).

**Comment by keystorm** [comment]
Thanks @kaso17, the title actually says "Multiplicador de subida: 1.5", hence the `$=` comparison. How would you extract that number with filters?

**Comment by Albvadi** [comment]
I did not know that I could use a selector+filter instead with case.. how??
For the filter, I can use split with a ':' as separator and get the second part...

**Comment by kaso17** [comment]
Regarding your pagination issue: there's no proper solution for it yet, see #975

but a workaround is to use multiple search paths, something like this:
```
search:
  paths:
    - path: /browse.php
      inputs:
        page: 1
    - path: /
      inputs:
        page: 2
    - path: /
      inputs:
        page: 3
  inputs:
    p: "torrents"
    pid: "10"
    $raw: "{{range .Categories}}cid[]:{{.}}&{{end}}"
    keywords: "{{ .Query.Keywords }}"
    search_type: "name"
    searchin: "title"
```

**Comment by keystorm** [comment]
Hm, right @Albvadi! Make sure you catch the space, too ": "

**Comment by kaso17** [comment]
```
uploadvolumefactor:
  text: "1" # default
uploadvolumefactor:
  optional: true # assuming the image is only available if it's != 1
  selector: img[title^="Multiplicador de subida:"]
  attribute: title
  filter:
    - name: split
      args: [":", 1]
```

**Comment by Albvadi** [comment]
@kaso17 as you commented previously, using `title` instead `original-title` works great in my original example.

Now, if I try with selector+filter as you suggest, don´t work.
This is my code:
```yaml
# uploadvolumefactor:
    #   text: "1" # default
uploadvolumefactor:
  optional: true # assuming the image is only available if it's != 1
  selector: img[src$="torrent_multiple_upload.png"]
  attribute: title
  filter:
    - name: split
      args: [":", 1]
    - name: trim
    - name: strdump
```
Always get 1 and if I comment the default uploadvolumefactor, it´s empty.
I removed `optional: true` to debug the log and there are 2 cases:

- Not found selector (normal when no exist multiplier image)
```log
01-10 16:36:58 Error CardigannIndexer (hachede): Error while parsing row '<tr>  <td class="torrent_image">              <div class="relativeDiv">                       <div>
                                <span class="">         <a href="https://hachede.me/data/torrents/torrent_images/l/Afiche-promocional-S-ptima-Temporada-GoT-HBO97.jpg" rel="fancybox" title="">
                                                <img src="https://hachede.me/data/torrents/torrent_images/s/Afiche-promocional-S-ptima-Temporada-GoT-HBO97.jpg" alt="Clic para ver a tama▒o completo!" title="Clic para ver a tama▒o completo!">
                                        </a> </span>
                        </div>                  <div class="category_image">                            <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;cid=44">
                                        <img src="https://hachede.me/data/torrents/category_images/44.png" alt="Categor▒a: Series > [HDTVrip]" title="Categor▒a: Series > [HDTVrip]">
                                </a>                    </div>          </div>  </td>   <td class="torrent_name">               <span class="multipliers">              </span>                 <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;action=details&amp;tid=22537">Juego de Tronos 7x02 Bajo la tormenta [AMZN m1080p x264, AC3(ES,EN), Sub(ES,EN)]</a>              <br>                  Subido 24-07-2017 18:23 por <span id="member_info" memberid="11973" class="clickable">
                        <span style="color: #6ab3f0; font-weight: bold;">okmk1</span>
                </span>                 <div class="torrentImages">                     <span>
                                <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;action=download&amp;tid=22537">
                                        <img src="https://hachede.me/styles/default/buttons/download.png" alt="Bajar Torrent" title="Bajar Torrent" class="button_images">
                                </a>
                        </span>                         <span class="clickable" id="bookmark_torrent" rel="22537">
                                <img src="https://hachede.me/styles/default/buttons/bookmark_add.png" alt="A▒adir a Favoritos" title="A▒adir a Favoritos" class="button_images">
                        </span>                         <span class="clickable" id="report_content" content_type="torrent" content_id="22537">
                                <img src="https://hachede.me/styles/default/buttons/report.png" alt="Reportar Torrent" title="Reportar Torrent" class="button_images">
                        </span>                                                 <span class="clickable" id="torrent_trailer" content_id="22537">
                                <img src="https://hachede.me/styles/default/buttons/movie.png" alt="Trailer" title="Trailer" class="button_images">
                        </span>                                                                                                                                         </div>  </td>   <td class="size">
                <a href="#" rel="torrent_size" id="22537">2.01 GB</a>
        </td>   <td class="completed">
                <a href="#" rel="times_completed" id="22537">464</a>
        </td>   <td class="seeders">
                <a href="#torrent_seeders" rel="torrent_seeders" id="22537">38</a>
        </td>   <td class="leechers">
                <a href="#torrent_leechers" rel="torrent_leechers" id="22537">0</a>
        </td> </tr>':

System.Exception: Error while parsing field=uploadvolumefactor, selector=img[src$="torrent_multiple_upload.png"], value=<null>: Selector "img[src$="torrent_multiple_upload.png"]" didn't match <tr>  <td class="torrent_image">               <div class="relativeDiv">                       <div>
                                <span class="">         <a href="https://hachede.me/data/torrents/torrent_images/l/Afiche-promocional-S-ptima-Temporada-GoT-HBO97.jpg" rel="fancybox" title="">
                                                <img src="https://hachede.me/data/torrents/torrent_images/s/Afiche-promocional-S-ptima-Temporada-GoT-HBO97.jpg" alt="Clic para ver a tama▒o completo!" title="Clic para ver a tama▒o completo!">
                                        </a> </span>
                        </div>                  <div class="category_image">                            <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;cid=44">
                                        <img src="https://hachede.me/data/torrents/category_images/44.png" alt="Categor▒a: Series > [HDTVrip]" title="Categor▒a: Series > [HDTVrip]">
                                </a>                    </div>          </div>  </td>   <td class="torrent_name">               <span class="multipliers">              </span>                 <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;action=details&amp;tid=22537">Juego de Tronos 7x02 Bajo la tormenta [AMZN m1080p x264, AC3(ES,EN), Sub(ES,EN)]</a>              <br>                  Subido 24-07-2017 18:23 por <span id="member_info" memberid="11973" class="clickable">
                        <span style="color: #6ab3f0; font-weight: bold;">okmk1</span>
                </span>                 <div class="torrentImages">                     <span>
                                <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;action=download&amp;tid=22537">
                                        <img src="https://hachede.me/styles/default/buttons/download.png" alt="Bajar Torrent" title="Bajar Torrent" class="button_images">
                                </a>
                        </span>                         <span class="clickable" id="bookmark_torrent" rel="22537">
                                <img src="https://hachede.me/styles/default/buttons/bookmark_add.png" alt="A▒adir a Favoritos" title="A▒adir a Favoritos" class="button_images">
                        </span>                         <span class="clickable" id="report_content" content_type="torrent" content_id="22537">
                                <img src="https://hachede.me/styles/default/buttons/report.png" alt="Reportar Torrent" title="Reportar Torrent" class="button_images">
                        </span>                                                 <span class="clickable" id="torrent_trailer" content_id="22537">
                                <img src="https://hachede.me/styles/default/buttons/movie.png" alt="Trailer" title="Trailer" class="button_images">
                        </span>                                                                                                                                         </div>  </td>   <td class="size">
                <a href="#" rel="torrent_size" id="22537">2.01 GB</a>
        </td>   <td class="completed">
                <a href="#" rel="times_completed" id="22537">464</a>
        </td>   <td class="seeders">
                <a href="#torrent_seeders" rel="torrent_seeders" id="22537">38</a>
        </td>   <td class="leechers">
                <a href="#torrent_leechers" rel="torrent_leechers" id="22537">0</a>
        </td> </tr>
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext()
```

- Input format error when image exists (I suppose it's because of `:` character):
```log
01-10 16:36:58 Error CardigannIndexer (hachede): Error while parsing row '<tr>  <td class="torrent_image row2">                 <div class="relativeDiv">                       <div>
                                <span class="">         <a href="https://hachede.me/data/torrents/torrent_images/l/el-juego-de-ender-blu-ray-l-cover.jpg" rel="fancybox" title="">
                                                <img src="https://hachede.me/data/torrents/torrent_images/s/el-juego-de-ender-blu-ray-l-cover.jpg" alt="Clic para ver a tama▒o completo!" title="Clic para ver a tama▒o completo!">
                                        </a> </span>
                        </div>                  <div class="category_image">                            <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;cid=100">
                                        <img src="https://hachede.me/data/torrents/category_images/100.png" alt="Categor▒a: Pel▒culas > [MicroHD 720p]" title="Categor▒a: Pel▒culas > [MicroHD 720p]">
                                </a>                    </div>          </div>  </td>   <td class="torrent_name row2">          <span class="multipliers">
                        <img src="https://hachede.me/styles/default/torrents/torrent_multiple_upload.png" alt="" title="Multiplicador de subida: 2" class="middle" id="" rel="resized_by_tsue">

                        <img src="https://hachede.me/styles/default/torrents/bump.png" alt="" title="RELANZADO" class="middle" id="" rel="resized_by_tsue">
                </span>                 <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;action=details&amp;tid=11372">El Juego de Ender (2013) [BR m720p.x264, AC3(ES,EN), Sub(ES,EN)] [MasHD]</a>              <br>                            Subido 06-01-2015 11:41 por <span id="member_info" memberid="0" class="clickable">An▒nimo</span>                <div class="torrentImages">           <span>
                                <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;action=download&amp;tid=11372">
                                        <img src="https://hachede.me/styles/default/buttons/download.png" alt="Bajar Torrent" title="Bajar Torrent" class="button_images">
                                </a>
                        </span>                         <span class="clickable" id="bookmark_torrent" rel="11372">
                                <img src="https://hachede.me/styles/default/buttons/bookmark_add.png" alt="A▒adir a Favoritos" title="A▒adir a Favoritos" class="button_images">
                        </span>                         <span class="clickable" id="report_content" content_type="torrent" content_id="11372">
                                <img src="https://hachede.me/styles/default/buttons/report.png" alt="Reportar Torrent" title="Reportar Torrent" class="button_images">
                        </span>                                                 <span class="clickable" id="torrent_trailer" content_id="11372">
                                <img src="https://hachede.me/styles/default/buttons/movie.png" alt="Trailer" title="Trailer" class="button_images">
                        </span>                                                                                                                                         </div>  </td>   <td class="size row2">
                <a href="#" rel="torrent_size" id="11372">2.73 GB</a>
        </td>   <td class="completed row2">
                <a href="#" rel="times_completed" id="11372">154</a>
        </td>   <td class="seeders row2">
                <a href="#torrent_seeders" rel="torrent_seeders" id="11372">2</a>
        </td>   <td class="leechers row2">
                <a href="#torrent_leechers" rel="torrent_leechers" id="11372">0</a>
        </td> </tr>':

System.Exception: Error while parsing field=uploadvolumefactor, selector=img[src$="torrent_multiple_upload.png"], value=Multiplicador de subida: 2: Input string was not in a correct format.
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext()
01-10 16:36:58 Error CardigannIndexer (hachede): Error while parsing row '<tr>  <td class="torrent_image">              <div class="relativeDiv">                       <div>
                                <span class="">         <a href="https://hachede.me/data/torrents/torrent_images/l/Afiche-promocional-S-ptima-Temporada-GoT-HBO.jpg" rel="fancybox" title="">
                                                <img src="https://hachede.me/data/torrents/torrent_images/s/Afiche-promocional-S-ptima-Temporada-GoT-HBO.jpg" alt="Clic para ver a tama▒o completo!" title="Clic para ver a tama▒o completo!">
                                        </a> </span>
                        </div>                  <div class="category_image">                            <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;cid=44">
                                        <img src="https://hachede.me/data/torrents/category_images/44.png" alt="Categor▒a: Series > [HDTVrip]" title="Categor▒a: Series > [HDTVrip]">
                                </a>                    </div>          </div>  </td>   <td class="torrent_name">               <span class="multipliers">              </span>                 <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;action=details&amp;tid=22523">Juego de Tronos 7x01 Rocadragon [AMZN m1080p x264, AC3(ES,EN), Sub(ES,EN)]</a>            <br>                          Subido 17-07-2017 22:52 por <span id="member_info" memberid="11973" class="clickable">
                        <span style="color: #6ab3f0; font-weight: bold;">okmk1</span>
                </span>                 <div class="torrentImages">                     <span>
                                <a href="https://hachede.me/?p=torrents&amp;pid=10&amp;action=download&amp;tid=22523">
                                        <img src="https://hachede.me/styles/default/buttons/download.png" alt="Bajar Torrent" title="Bajar Torrent" class="button_images">
                                </a>
                        </span>                         <span class="clickable" id="bookmark_torrent" rel="22523">
                                <img src="https://hachede.me/styles/default/buttons/bookmark_add.png" alt="A▒adir a Favoritos" title="A▒adir a Favoritos" class="button_images">
                        </span>                         <span class="clickable" id="report_content" content_type="torrent" content_id="22523">
                                <img src="https://hachede.me/styles/default/buttons/report.png" alt="Reportar Torrent" title="Reportar Torrent" class="button_images">
                        </span>                                                 <span class="clickable" id="torrent_trailer" content_id="22523">
                                <img src="https://hachede.me/styles/default/buttons/movie.png" alt="Trailer" title="Trailer" class="button_images">
                        </span>                                                                                                                                         </div>  </td>   <td class="size">
                <a href="#" rel="torrent_size" id="22523">1.89 GB</a>
        </td>   <td class="completed">
                <a href="#" rel="times_completed" id="22523">463</a>
        </td>   <td class="seeders">
                <a href="#torrent_seeders" rel="torrent_seeders" id="22523">42</a>
        </td>   <td class="leechers">
                <a href="#torrent_leechers" rel="torrent_leechers" id="22523">0</a>
        </td> </tr>':
```

**Comment by kaso17** [comment]
it must be filter**s**:, not filter:

**Comment by Albvadi** [comment]
You are right... :sweat_smile:
With filters, all it´s working perfect!

I´ll create later the PR and close the issue...
Thanks so much for all your support!
