### ISSUE TITLE
[XBTIT-XBTT] Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Albvadi** [Jackett/Jackett#2397]
Jackett version: 0.8.578.0
Mono version (if not using Windows):  
_____________________________________________

Hi,
I´m trying to add two trackers powered by XBTIT - XBTT system, but both of them produces the same error.
The login it´s correct and the search it´s correct (I can see in the log, all the html correspond to the search and the results of the same...)

The error in log it´s:
```log
01-10 17:23:07 Error Jackett.IndexerException: Exception (hdcity): Object reference not set to an instance of an object. ---> System.Exception: Parse error ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.BaseIndexer.<ResultsForQuery>d__64.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Indexers.BaseIndexer.<ResultsForQuery>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Controllers.V20.ResultsController.<Results>d__13.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\ResultsController.cs:line 169 Jackett.IndexerException: Exception (hdcity): Object reference not set to an instance of an object. ---> System.Exception: Parse error ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.BaseIndexer.<ResultsForQuery>d__64.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Indexers.BaseIndexer.<ResultsForQuery>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Controllers.V20.ResultsController.<Results>d__13.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\ResultsController.cs:line 169
```

I´m tried two different trackets with xbit system: Puntotorrent.ch and HDCity.li

Any help??
Thanks!

**Comment by kaso17** [comment]
You're trying to access some value which is not initialized. To find out what exactly you'll have to go through the inner exceptions via the debugger or step through your parsing code line by line.

**Comment by Albvadi** [comment]
> or step through your parsing code line by line.

Do you mean the yml config definition??

**Comment by Albvadi** [comment]
Forget this...
I´d made all config blocks one by one.. and all it´s working correctly now...

Thanks!
