### ISSUE TITLE
[scenefz] Exception (scenefz): Got redirected to another domain. Try changing the indexer URL to https://www.scenefz.me/.: Parse error (Test)

### ISSUE THREAD

**Issue by davidst** [Jackett/Jackett#2665]
```
Error on 20180303225444 for SceneFZ / u-torrents.txtJackett.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.scenefz.me/.
   at Jackett.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebClientStringResult Result, IHtmlDocument document)
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__28.MoveNext()




<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta http-equiv="refresh" content="0;url=https://www.scenefz.me/torrents?q=&amp;searchin=0&amp;cat=0&amp;dead=1" />
<title>Redirecting to https://www.scenefz.me/torrents?q=&amp;searchin=0&amp;cat=0&amp;dead=1</title>
</head>
<body>
Redirecting to <a href="https://www.scenefz.me/torrents?q=&amp;searchin=0&amp;cat=0&amp;dead=1">https://www.scenefz.me/torrents?q=&amp;searchin=0&amp;cat=0&amp;dead=1</a>.
</body>
</html>
```

**Jackett version**:   0.8.737.0

**Comment by garfield69** [comment]
The next (pre)release of Jackett will include fix 3848a0b.
but if you don't want to wait, then you can fix it now by using the wrench icon on the Jackett Dashboard and edit the scenefz indexer's Site Link to `https://www.scenefz.me/`
