### ISSUE TITLE
[edia._base.providers.base] Failed getting release from TorrentPotato:

### ISSUE THREAD

**Issue by bletchlypark** [Jackett/Jackett#2705]
Issue getting torrents to deluge from coutchpotato

Couchpotato logs: 

[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last): File "/opt/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False) File "/opt/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen response = r.request(method, url, **kwargs) File "/opt/couchpotato/libs/requests/sessions.py", line 469, in request resp = self.send(prep, **send_kwargs) File "/opt/couchpotato/libs/requests/sessions.py", line 571, in send adapter = self.get_adapter(url=request.url) File "/opt/couchpotato/libs/requests/sessions.py", line 645, in get_adapter raise InvalidSchema("No connection adapters were found for '%s'" % url) InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:45DB34BC4B528FDE489C7CB77BEEF9D69CC9B268&dn=Coco.2017.1080p.BluRay.x264.DTS-HD.MA.7.1-FGT+[rarbg]&tr=http:%2F%2Ftracker.trackerfix.com:80%2Fannounce&tr=udp:%2F%2F9.rarbg.me:2710%2Fannounce&tr=udp:%2F%2F9.rarbg.to:2710%2Fannounce&tr=udp:%2F%2Ftracker.zer0day.to:1337%2Fannounce&tr=udp:%2F%2Ftracker.leechers-paradise.org:6969%2Fannounce&tr=udp:%2F%2Fcoppersurfer.tk:6969%2Fannounce'

Jackett Logs:

Jackett.IndexerException: Exception (kickasstorrent): A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00026] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Net.Http.HttpClientHandler+<SendAsync>d__64.MoveNext () [0x004f5] in <1b4ca1e290fd4a81978c5860ac6ff8f4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0001a] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at CloudFlareUtilities.ClearanceHandler+<SendAsync>d__15.MoveNext () [0x00102] in <d11e8e0ba32e426a9ada05f9468dfeec>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0001a] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <1b4ca1e290fd4a81978c5860ac6ff8f4>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0001a] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at Jackett.Utils.Clients.HttpWebClient+<Run>d__7.MoveNext () [0x00401] in C:\projects\jackett\src\Jackett.Common\Utils\Clients\HttpWebClient.cs:211 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0001a] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at Jackett.Utils.Clients.WebClient+<GetString>d__18.MoveNext () [0x000c1] in C:\projects\jackett\src\Jackett.Common\Utils\Clients\WebClient.cs:117 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0001a] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at Jackett.Indexers.BaseWebIndexer+<RequestStringWithCookies>d__5.MoveNext () [0x00084] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:350 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0001a] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at Jackett.Indexers.CardigannIndexer+<PerformQuery>d__28.MoveNext () [0x007db] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1180 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0001a] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at Jackett.Indexers.BaseIndexer+<ResultsForQuery>d__64.MoveNext () [0x00047] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:240 
   --- End of inner exception stack trace ---
  at Jackett.Indexers.BaseIndexer+<ResultsForQuery>d__64.MoveNext () [0x000c6] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:256 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at Jackett.Indexers.BaseWebIndexer+<ResultsForQuery>d__25.MoveNext () [0x00024] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:718 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at Jackett.Controllers.V20.ResultsController+<Torznab>d__14.MoveNext () [0x0025e] in <c8b727f4a5054412a3b899048ea87f85>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__1`1[T].MoveNext () [0x0005b] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__1.MoveNext () [0x000ab] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Tracing.ITraceWriterExtensions+<TraceBeginEndAsyncCore>d__17`1[TResult].MoveNext () [0x001a7] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x00091] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Filters.ActionFilterAttribute+<CallOnActionExecutedAsync>d__6.MoveNext () [0x001ad] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Filters.ActionFilterAttribute+<ExecuteActionFilterAsyncCore>d__5.MoveNext () [0x00103] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__5.MoveNext () [0x001af] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Filters.AuthorizationFilterAttribute+<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext () [0x000f3] in <69abafc3d8434ab584330d77cc8d6da3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f56c876907e742b0aa586f051fcce845>:0 
  at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__6.MoveNext () [0x00087] in <69abafc3d8434ab584330d77cc8d6da3>:0 

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
couchpotato can't handle magnet URLs

**Comment by FoxBJK** [comment]
Is this a recent change? I'm running into this issue, but other people are saying that CP *does* support magnet URLs:
https://couchpota.to/forum/viewtopic.php?f=5&t=51391

**Comment by kaso17** [comment]
Based on the error it looks like CP is blindly trying to do a HTTP request for the magnet URI.
Please check with the CP devs what's supposed to happen with magnet links.
