### ISSUE TITLE
[lostfilm] {An error occured while updating this indexer {"need_captcha":true,"result":"ok"}

### ISSUE THREAD

**Issue by phillippirrup** [Jackett/Jackett#2719]
An error occured while updating this indexer
{"need_captcha":true,"result":"ok"}
I can not understand where I should enter this

**Jackett 0.8.490-6**:  
**Mono 5.8.0.108-11** (if not using Windows):  

-------------------------------

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by flightlevel** [comment]
No response, closing

**Comment by kaso17** [comment]
fixed via 756cf7c0a6eea7745239bda0086aa5b5e3e1c711

**Comment by tribalRu** [comment]
Same problem in the last ver. v0.22.201
`Jackett.Common.ExceptionWithConfigData: {"need_captcha":true,"result":"ok"}

[v0.22.201.0] Jackett.Common.ExceptionWithConfigData: {"need_captcha":true,"result":"ok"}
   at Jackett.Common.Indexers.LostFilm.<>c__DisplayClass40_0.<ApplyConfiguration>b__0() in ./Jackett.Common/Indexers/LostFilm.cs:line 215
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 163
   at Jackett.Common.Indexers.LostFilm.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/LostFilm.cs:line 208
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26`

**Comment by ilike2burnthing** [comment]
Working fine here. Open a new issue and provide the information requested, along with an enhanced log of the issue - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
