### ISSUE TITLE
Unable to determine why Gazelle Games login fails

### ISSUE THREAD

**Issue by avggeek** [Jackett/Jackett#2730]
I'm trying to configure my Gazelle Games login but unfortunately it keeps failing with the error "Your Cookie did not work". I'm aware that the recommendation is to not post the authkey in the logs so I have removed the actual cookie details in the log below:

```
2018-03-17 10:59:10.1127 Info   http://127.0.0.1:9117/api/v2.0/indexers/gazellegames/config 
2018-03-17 10:59:10.1197 Info DefaultHttpControllerSelector SelectController Route='indexerId:gazellegames,action:config,controller:IndexerApi' 
2018-03-17 10:59:10.1197 Info DefaultHttpControllerSelector SelectController IndexerApi 
2018-03-17 10:59:10.1197 Info HttpControllerDescriptor CreateController  
2018-03-17 10:59:10.1347 Info DefaultHttpControllerActivator Create  
2018-03-17 10:59:10.1347 Info DefaultHttpControllerActivator Create Jackett.Controllers.IndexerApiController 
2018-03-17 10:59:10.1347 Info HttpControllerDescriptor CreateController Jackett.Controllers.IndexerApiController 
2018-03-17 10:59:10.1347 Info IndexerApiController ExecuteAsync  
2018-03-17 10:59:10.1547 Info ApiControllerActionSelector SelectAction  
2018-03-17 10:59:10.1547 Info ApiControllerActionSelector SelectAction Selected action 'Config(ConfigItem[] config)' 
2018-03-17 10:59:10.1547 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2018-03-17 10:59:10.1698 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2018-03-17 10:59:10.1698 Info HttpActionBinding ExecuteBindingAsync  
2018-03-17 10:59:10.1698 Info FormatterParameterBinding ExecuteBindingAsync Binding parameter 'config' 
2018-03-17 10:59:10.1848 Info JsonMediaTypeFormatter ReadFromStreamAsync Type='ConfigItem[]', content-type='application/json' 
2018-03-17 10:59:10.1848 Info JsonMediaTypeFormatter ReadFromStreamAsync Value read='Jackett.Common.Models.DTO.ConfigItem[]' 
2018-03-17 10:59:10.1848 Info FormatterParameterBinding ExecuteBindingAsync Parameter 'config' bound to the value 'Jackett.Common.Models.DTO.ConfigItem[]' 
2018-03-17 10:59:10.2008 Info HttpActionBinding ExecuteBindingAsync Model state is valid. Values: config=Jackett.Common.Models.DTO.ConfigItem[] 
2018-03-17 10:59:10.2008 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)' 
2018-03-17 10:59:10.2008 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2018-03-17 10:59:10.2168 Info RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)' 
2018-03-17 10:59:10.2168 Info RequiresIndexerAttribute OnActionExecutingAsync  
2018-03-17 10:59:10.2168 Info ApiControllerActionInvoker InvokeActionAsync Action='Config(config=Jackett.Common.Models.DTO.ConfigItem[])' 
2018-03-17 10:59:10.2298 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config(config=Jackett.Common.Models.DTO.ConfigItem[])' 
2018-03-17 10:59:10.2298 Debug WebClient(HttpWebClient).GetString(Url:https://gazellegames.net/torrents.php?searchstr=&order_by=time&order_way=desc&action=basic&searchsubmit=1) 
2018-03-17 10:59:11.2821 Debug WebClient(HttpWebClient): Returning Redirect => https://gazellegames.net/login.php  
2018-03-17 10:59:11.2821 Debug updating Cookies PHPSESSID=foo; session=string-ending-in==; => PHPSESSID=foo; session=string-ending-in==; session=deleted; keeplogged=deleted 
2018-03-17 10:59:11.2921 Error ReflectedHttpActionDescriptor ExecuteAsync  
2018-03-17 10:59:11.2921 Error ApiControllerActionInvoker InvokeActionAsync  
2018-03-17 10:59:11.2921 Info RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)' 
2018-03-17 10:59:11.3071 Info RequiresIndexerAttribute OnActionExecutedAsync  
2018-03-17 10:59:11.3071 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)' 
2018-03-17 10:59:11.3071 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2018-03-17 10:59:11.3071 Info ApiExceptionHandler ExecuteExceptionFilterAsync  
2018-03-17 10:59:11.3261 Error System.Exception: Your cookie did not work: Your cookie did not work
   at Jackett.Common.Indexers.GazelleGames.<ApplyConfiguration>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.IndexerApiController.<UpdateConfig>d__10.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() System.Exception: Your cookie did not work: Your cookie did not work
   at Jackett.Common.Indexers.GazelleGames.<ApplyConfiguration>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.IndexerApiController.<UpdateConfig>d__10.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
2018-03-17 10:59:11.3261 Info ApiExceptionHandler ExecuteExceptionFilterAsync  
2018-03-17 10:59:11.3261 Info IndexerApiController ExecuteAsync  
2018-03-17 10:59:11.3391 Info   Content-type='application/json; charset=utf-8', content-length=4990 
2018-03-17 10:59:11.3391 Info IndexerApiController Dispose  
2018-03-17 10:59:11.3391 Info IndexerApiController Dispose  
```
Any tips on what I'm doing wrong that is causing the Cookie login to fail?

**Jackett version**:  v0.8.763

-------------------------------

**Comment by flightlevel** [comment]
Was it working previously?
Is the browser you got the cookie from using the same external IP as Jackett?

**Comment by avggeek** [comment]
I have not been able to get it to work actually - I tried when support for GGn was initially added and it failed but I did not file an issue at that time.

To answer the question, yes the browser (Firefox ESR) that I got the cookie from is using the same external IP as Jackett

**Comment by kaso17** [comment]
Works perfectly fine for me, even with cookies from a different IP.
Please double-check that you're using the full cookie. I believe firefox sometimes shows only the shortened cookie string.

**Comment by avggeek** [comment]
Thank you for the suggestion to try with a different browser @kaso17! I tried re-configuring with cookie details taken from Chrome and this time it worked correctly.

**Comment by 07416** [comment]
By enabling "raw headers" I was able to copy the full cookie in Firefox:

![2019-07-01 13_35_55-Window](https://user-images.githubusercontent.com/14923168/60430240-7dbfc480-9c05-11e9-8c9b-bb91161dc080.png)

Of course exclude `Cookie:`, copy the rest of the string.
