### ISSUE TITLE
[1337x] Exception (1337x): The underlying connection was closed: The connection was closed unexpectedly.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by teedoff** [Jackett/Jackett#2787]
```
Jackett.Common.IndexerException: Exception (1337x): The underlying connection was closed: The connection was closed unexpectedly. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudFlareUtilities.ClearanceHandler.<SendAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```
None of my trackers will connect in Jackett and therefore sonarr/radarr. This just seemed to start happening since yesterday. Note: i got my ISP service suspended Sat, so I switched VPN's, but I believe I've configured Jackett correctly.

If anymore info is needed, let me know and thanks for any help.

**Comment by kaso17** [comment]
this is a connectivity issue, your network/VPN isn't working.

**Comment by teedoff** [comment]
If my network/VPN wasnt working, why would i still be able to browse any website?

**Comment by teedoff** [comment]
NVM. Thanks for the help. I had a typo in the SOCKS5 URL!
