### ISSUE TITLE
[torrentleech]  (Config) - Still failed after update

### ISSUE THREAD

**Issue by mstrdraco** [Jackett/Jackett#2912]
Jackett.Common.ExceptionWithConfigData
  at Jackett.Common.Indexers.TorrentLeech+<>c__DisplayClass9_0.<DoLogin>b__0 () [0x0002f] in <d26e0a0dfed7490484dc93c3df248b30>:0 
  at Jackett.Common.Indexers.BaseIndexer+<ConfigureIfOK>d__59.MoveNext () [0x00034] in <d26e0a0dfed7490484dc93c3df248b30>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a09726166c1843dfba9f344410894800>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <a09726166c1843dfba9f344410894800>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <a09726166c1843dfba9f344410894800>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <a09726166c1843dfba9f344410894800>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a09726166c1843dfba9f344410894800>:0 
  at Jackett.Common.Indexers.TorrentLeech+<DoLogin>d__9.MoveNext () [0x00193] in <d26e0a0dfed7490484dc93c3df248b30>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a09726166c1843dfba9f344410894800>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <a09726166c1843dfba9f344410894800>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <a09726166c1843dfba9f344410894800>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <a09726166c1843dfba9f344410894800>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a09726166c1843dfba9f344410894800>:0 
  at Jackett.Common.Indexers.TorrentLeech+<ApplyConfiguration>d__8.MoveNext () [0x0006f] in <d26e0a0dfed7490484dc93c3df248b30>:0 
--- End of stack trace from previous location where exception was thrown ---

**Jackett version**:  Version 0.8.857.0
 

-------------------------------

**Comment by kaso17** [comment]
Please provide a full enhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by mstrdraco** [comment]
2018-04-06 07:48:10.7510 Info UnixLibCurlWebClient: received CloudFlare clearance cookie:  
2018-04-06 07:48:10.8862 Error Error on 20180406074810 for TorrentLeech.txtNewtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
  at Newtonsoft.Json.JsonTextReader.ParseValue () [0x002b3] in <b1d2c1d6f4dd47bea2964bdd6464f67d>:0 
  at Newtonsoft.Json.JsonTextReader.Read () [0x0004c] in <b1d2c1d6f4dd47bea2964bdd6464f67d>:0 
  at Newtonsoft.Json.JsonReader.ReadAndMoveToContent () [0x00000] in <b1d2c1d6f4dd47bea2964bdd6464f67d>:0 
  at Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) [0x0004a] in <b1d2c1d6f4dd47bea2964bdd6464f67d>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x00029] in <b1d2c1d6f4dd47bea2964bdd6464f67d>:0

**Comment by kaso17** [comment]
You're using the legacy libcurl client, upgrade your mono version to one with BTLS support and/or stop using the -c/--UseClient command line option.

**Comment by cgoconseils** [comment]
Hello @kaso17 , I am experiencing the same issue but am using Jackett on a Synology NAS. I do not see a newer version available than the 5.8.0.108-11. Would you have some resolution scenario other than upgrading mono ?

**Comment by evilvibes** [comment]
CloudFlareUtilities.CloudFlareClearanceException: Clearance failed after 4 attempt(s).
   at CloudFlareUtilities.ClearanceHandler.<SendAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Common.Utils.Clients.HttpWebClient.<Run>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

Windows 10
Version 0.8.857.0

**Comment by pyrrhichios** [comment]
I have the same issue and similar looking errors in my own logs (Ubuntu 16.04, Mono 5.10.1.20).

**Comment by kaso17** [comment]
@cgoconseils use the "Check for updates" button at the jackett GUI and check the real jackett version at the bottom of the page.
@evilvibes keep re-testing. CloudFlare issues aren't fully fixed yet.

**Comment by kaso17** [comment]
You can check the logs to see if there's an update. Or just wait a minute after clicking check for updates and reload the page, if the version still is 0.8.846.0 you have a problem with your installation.

**Comment by mstrdraco** [comment]
I've upgraded to mono-5.10.1.38 and still getting the error.

**Comment by kaso17** [comment]
@mstrdraco make sure you're not using the -c/--UseClient command line arguments.

**Comment by marseneault** [comment]
@mstrdraco regarding the JSONReaderException, make sure the indexer is set up as https://www.torrentleech.org/ in Jackett.  The new version unfortunately won't work with V4 anymore if that's what you are using.

**Comment by mstrdraco** [comment]
Ok thank you @kaso17 once I took that off, I had to run an addcert command and it appears to have fixed it.

**Comment by pyrrhichios** [comment]
@kaso17 thanks - I did a git clone and while there's no message about being on the latest version when I check for updates, one does appear in the logs, so that seems to be working - and it seems to have sorted my Torrentleech problems too, as that's testing ok now as well! Thanks for your help.
