### ISSUE TITLE
Sonarr no longer retrieving results

### ISSUE THREAD

**Issue by jriker1** [Jackett/Jackett#3011]
Using the latest version of Jackett in Windows and not sure which revision it happened in as I don't use Sonarr to much, however When I do a request in Jackett for a torrent it shows a lot of results.  In Sonarr it no longer does.  Haven't updated Sonarr in a month as of last release however did do a couple Jackett updates.  Is there something in recent updates that would break the search thru Sonarr?

Thanks.

JR

**Comment by kaso17** [comment]
check the sonarr/jackett logs and provide the torznab requests URIs.

**Comment by jriker1** [comment]
Here's a funny one.  So if I just search for General Hospital I get:

2018-04-23 13:55:46.7915 Info Manual search for "General Hospital" on 1337x, btdb, bt-scene, demonoid, ettv, extratorrent-ag, eztv, idope, isohunt2, kickasstorrent, kickasstorrent-kathow, limetorrents, magnetdl, rarbg, showrss, thepiratebay, torlock, torrentdownloads, torrentz2, worldwidetorrents, zooqle with 711 results. 

711 results.

If I search for General Hospital S56 E14 I get

2018-04-23 13:57:51.2322 Info Manual search for "General Hospital" on 1337x, btdb, bt-scene, demonoid, ettv, extratorrent-ag, eztv, idope, isohunt2, kickasstorrent, kickasstorrent-kathow, limetorrents, magnetdl, rarbg, showrss, thepiratebay, torlock, torrentdownloads, torrentz2, worldwidetorrents, zooqle with 2 results. 


Even though I know like KickAss has S56 space E14 Version of General Hospital that matches if I just search on General Hospital S56.

**Comment by jriker1** [comment]
I'm also seeing this in my logs in Jackett, not sure if it's related:

2018-04-23 14:46:53.2657 Error Error downloading thepiratebay https://proxytpb.org/torrent/21168736/General_Hospital_-_S56_E14_[14039]_-_2018-04-19 BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeStream stream)
   at BencodeNET.Parsing.BencodeParser.Parse(Byte[] bytes)
   at Jackett.Controllers.DownloadController.<Download>d__5.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\DownloadController.cs:line 75

**Comment by Lildirt** [comment]
It seems this issue is not isolated. If more information is required/desired, please do not hesitate.

The only available source is IPTorrents; there are no other sources. Running Jackett 0.8.920 on Ubuntu 17.10 (4.13.13-5 kernel) with Mono 4.6.2. Unlike OP, there are no difficulties performing searches. Only the downloads fail.

To note, this happened "randomly". Restoring an image of the container that hosted an older version of Jackett (which was working at the time of image creation; I believe it was version 0.8.870) also yields the same error.

Upon requesting downloads (from Sonarr or Radarr), a failed download is reported (from Sonarr/Radarr and in Jackett logs). An exception is thrown in Jackett console, as follows:
```
04-25 04:09:24 Info Found 1 (0 new) releases from IPTorrents 
04-25 04:09:33 Error Error downloading iptorrents https://iptorrents.com/download.php%2F1087036%2FElvira+Mistress+Of+The+Dark+1988+DVDRip+x264-CG.mkv.torrent BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
  at BencodeNET.Parsing.BencodeParser.Parse (BencodeNET.IO.BencodeStream stream) [0x0008f] in <f57c6b848225428ca6216f5cbc1c09fa>:0 
  at BencodeNET.Parsing.BencodeParser.Parse (System.IO.Stream stream) [0x00008] in <f57c6b848225428ca6216f5cbc1c09fa>:0 
  at BencodeNET.Parsing.BencodeParser.Parse (System.Byte[] bytes) [0x00007] in <f57c6b848225428ca6216f5cbc1c09fa>:0 
  at Jackett.Controllers.DownloadController+<Download>d__5.MoveNext () [0x001ab] in <9412ecba336f42ccb3a1ff44c5d9f956>:0
```

**Comment by kaso17** [comment]
@jriker1 is this something specific to General Hospital (that they separate season and episode with a space)? We would have to rewrite the search string in that case.
But regarding the kickass example: it's happening on their website too: https://kat.li/usearch/General%20Hospital%20S56%20E14/

Regarding the https://proxytpb.org download, this proxy changes the download links, please use another one.

@Lildirt It works fine for me. 
Is this still a problem? might have been a temporary iptorrents issue.
Can you download the following like via your browser and open the file in your torrent client manually?
https://iptorrents.com/download.php%2F1087036%2FElvira+Mistress+Of+The+Dark+1988+DVDRip+x264-CG.mkv.torrent

**Comment by jriker1** [comment]
Thanks for the reply.  Well, I know I'm on a soap opera kick, but that's my family.  Young and the restless does the same thing.  Example: "The Young And The Restless - S45 E162 [11415] - 2018-04-24", and Bold and the Beautiful: "The Bold And The Beautiful - S31 E60 [7733] - 2017-12-12"

I would think trying to separate the query would maybe make more sense because if a show does S31E60 or S31 E60 it will then work where if it's just S31E60 it will only work for one of the two methods.

**Comment by RoloSoze** [comment]
@jriker1 Is this still an issue?

**Comment by RoloSoze** [comment]
@jriker1 Closing this issue since it hasn't been updated in 2 years. If you're still having this problem, feel free to reopen this issue.
