### ISSUE TITLE
[wihd] Exception (wihd): Media ID Unknow !: Parse error (Config)

### ISSUE THREAD

**Issue by kd1k16oiaafz** [Jackett/Jackett#3085]
**Jackett version**:  0.8.929.0

Hi guys, I have the following issue when I try to add the wihd indexer. I hope we will find a solution.
-------------------------------

`Jackett.Common.IndexerException: Exception (wihd): Media ID Unknow ! ---> System.Exception: Parse error ---> System.Exception: Media ID Unknow !
   at Jackett.Common.Indexers.WiHD.mediaToCategory(String media, String name)
   at Jackett.Common.Indexers.WiHD.<PerformQuery>d__21.MoveNext()
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)
   at Jackett.Common.Indexers.WiHD.<PerformQuery>d__21.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__64.MoveNext()
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__64.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Services.IndexerManagerService.<TestIndexer>d__18.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.IndexerApiController.<UpdateConfig>d__10.MoveNext() dans C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:ligne 101
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__171.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__171.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()`

**Comment by kd1k16oiaafz** [comment]
Well, I have a little investigated and it seems that the IDs you use in `private string mediaToCategory(string media, string name)` are deprecated. Here are the updated ones: 

```
// Movies
5a64b8934a23a8d6188b4569		// 1080P
5a64b8934a23a8d6188b456b	// 720P
5a64b8934a23a8d6188b456d	// HDTV
5a64b8934a23a8d6188b456f		// Bluray
5a64b8934a23a8d6188b4571		// Bluray Remux
5a64b8934a23a8d6188b4573		// Bluray 3D
5a64b8934a23a8d6188b4575 	// Bluray 4K
5a64b8934a23a8d6188b4577 	// Bluray Remux 4K
5a64b8934a23a8d6188b4579 	// WEB-DL

// TV
59eb66144a23a8ea4c8b456a		// 1080P
59eb66144a23a8ea4c8b456c		// 720P
59eb66144a23a8ea4c8b456e		// HDTV
59eb66144a23a8ea4c8b4570		// Bluray
59eb66144a23a8ea4c8b4572		// Bluray Remux
59eb66144a23a8ea4c8b4574		// Bluray 3D

// Anime
59e73b8b4a23a8594c8b456a		// 1080P
59e73b8b4a23a8594c8b456c		// 720P
59e73b8b4a23a8594c8b456e		// HDTV
59e73b8b4a23a8594c8b4570		// Bluray
59e73b8b4a23a8594c8b4572		// Bluray Remux
59e73b8b4a23a8594c8b4574		// Bluray 3D

// Other
59f0c5ed4a23a8617d8b456a		// Apps
59f0c5ed4a23a8617d8b456c		// Clips
59f0c5ed4a23a8617d8b456e		// Audios Tracks of Movies/TV/Anime
59f0c5ed4a23a8617d8b4570		// Documentary
59f0c5ed4a23a8617d8b4574		// 1080p
59f0c5ed4a23a8617d8b4576		// 720p
59f0c5ed4a23a8617d8b4572		// Bluray (ALL)
```

BTW where did you get the `name param` (aka Category ID)?

Regards.

**Comment by garfield69** [comment]
the next (pre)release of Jackett should contain 628ab0ca821e262c6b35e6c282e38d5eafb90de9 which has the cat ids you supplied.
I've done a straight swap old->new, but since I don't have a login I have not tested this.

**Comment by kd1k16oiaafz** [comment]
I don't think it's gonna work:

- The Media ID is based on the picture path used for each category (that's what I gave you previously) and it's only **used as a key** in the dictionary stored in `mediaToCategory` and **not as a value**, which is the Category ID (line 734). On the other hand, I don't know where the first paramater of `AddCategoryMapping` is come from but I think it shouldn't be updated as it is not using Media ID for now (lines 65 to 98).

- Media ID for Anime BR 3D and for TV BR 3D are now different, so these lines are deprecated:

`// BUG ~~ Media ID for Anime BR 3D is same as TV BR 3D ~~
//dictionary.Add("59e73b8b4a23a8594c8b4575", "59e73b8b4a23a8594c8b4574");       // Bluray 3D`

`
// Due to a bug on tracker side, check for a specific id/name as image is same for TV/Anime BR 3D
if (media == "59eb66144a23a8ea4c8b4574" && name == "Animations - Bluray 3D")
{
    // If it's an Anime BR 3D
    return "59e73b8b4a23a8594c8b4574";
}
`

Regards.

**Comment by garfield69** [comment]
OK. i'll revert the commit and hopefully some other dev will take it up and fix it.

**Comment by flightlevel** [comment]
@JigSawFr would you be able to take a look?

**Comment by alxlaxv** [comment]
Same issue for me 🔢

**Comment by kaso17** [comment]
I believe this indexer is broken for a long time and no current dev has access to it to fix it.

**Comment by fl0wfr** [comment]
If a dev needs an access I can give one.

**Comment by kaso17** [comment]
@fl0wfr please send the invite to kaso1717 -at- gmail.com

**Comment by fl0wfr** [comment]
Done! Let me know if you need help
