### ISSUE TITLE
[iptorrents] Jackett seems to have lost capability to connect

### ISSUE THREAD

**Issue by RikT** [Jackett/Jackett#3167]
I have just noticed that Jackett has stopped connecting with iptorrents I tried other urls all the same results
using Jackett Version 0.8.1027.0 on Windows 10 here is log

`2018-05-28 15:40:42.2186 Info   http://192.168.0.15:9117/api/v2.0/indexers/iptorrents/config 
2018-05-28 15:40:42.2186 Info DefaultHttpControllerSelector SelectController Route='indexerId:iptorrents,action:config,controller:IndexerApi' 
2018-05-28 15:40:42.2186 Info DefaultHttpControllerSelector SelectController IndexerApi 
2018-05-28 15:40:42.2186 Info HttpControllerDescriptor CreateController  
2018-05-28 15:40:42.2186 Info DefaultHttpControllerActivator Create  
2018-05-28 15:40:42.2186 Info DefaultHttpControllerActivator Create Jackett.Controllers.IndexerApiController 
2018-05-28 15:40:42.2186 Info HttpControllerDescriptor CreateController Jackett.Controllers.IndexerApiController 
2018-05-28 15:40:42.2186 Info IndexerApiController ExecuteAsync  
2018-05-28 15:40:42.2186 Info ApiControllerActionSelector SelectAction  
2018-05-28 15:40:42.2186 Info ApiControllerActionSelector SelectAction Selected action 'Config(ConfigItem[] config)' 
2018-05-28 15:40:42.2186 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2018-05-28 15:40:42.2186 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2018-05-28 15:40:42.2186 Info HttpActionBinding ExecuteBindingAsync  
2018-05-28 15:40:42.2186 Info FormatterParameterBinding ExecuteBindingAsync Binding parameter 'config' 
2018-05-28 15:40:42.2186 Info JsonMediaTypeFormatter ReadFromStreamAsync Type='ConfigItem[]', content-type='application/json' 
2018-05-28 15:40:42.2186 Info JsonMediaTypeFormatter ReadFromStreamAsync Value read='Jackett.Common.Models.DTO.ConfigItem[]' 
2018-05-28 15:40:42.2186 Info FormatterParameterBinding ExecuteBindingAsync Parameter 'config' bound to the value 'Jackett.Common.Models.DTO.ConfigItem[]' 
2018-05-28 15:40:42.2186 Info HttpActionBinding ExecuteBindingAsync Model state is valid. Values: config=Jackett.Common.Models.DTO.ConfigItem[] 
2018-05-28 15:40:42.2186 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)' 
2018-05-28 15:40:42.2186 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2018-05-28 15:40:42.2342 Info RequiresIndexerAttribute OnActionExecutingAsync Action filter for 'Config(ConfigItem[] config)' 
2018-05-28 15:40:42.2342 Info RequiresIndexerAttribute OnActionExecutingAsync  
2018-05-28 15:40:42.2342 Info ApiControllerActionInvoker InvokeActionAsync Action='Config(config=Jackett.Common.Models.DTO.ConfigItem[])' 
2018-05-28 15:40:42.2342 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Config(config=Jackett.Common.Models.DTO.ConfigItem[])' 
2018-05-28 15:40:42.2342 Debug WebClient(HttpWebClient).GetString(Url:https://iptorrents.com/t) 
2018-05-28 15:40:42.4217 Debug WebClient(HttpWebClient): Returning Redirect => https://iptorrents.com/login.php  
2018-05-28 15:40:42.4217 Debug updating Cookies __cfduid=<REMOVED COOKIE>; => __cfduid=<REMOVED COOKIE> 
2018-05-28 15:40:42.4217 Error ReflectedHttpActionDescriptor ExecuteAsync  
2018-05-28 15:40:42.4217 Error ApiControllerActionInvoker InvokeActionAsync  
2018-05-28 15:40:42.4217 Info RequiresIndexerAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)' 
2018-05-28 15:40:42.4217 Info RequiresIndexerAttribute OnActionExecutedAsync  
2018-05-28 15:40:42.4217 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Config(ConfigItem[] config)' 
2018-05-28 15:40:42.4217 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2018-05-28 15:40:42.4373 Info ApiExceptionHandler ExecuteExceptionFilterAsync  
2018-05-28 15:40:42.4373 Error System.Exception: Your cookie did not work: Your cookie did not work
   at Jackett.Common.Indexers.IPTorrents.<ApplyConfiguration>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.IndexerApiController.<UpdateConfig>d__10.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext() System.Exception: Your cookie did not work: Your cookie did not work
   at Jackett.Common.Indexers.IPTorrents.<ApplyConfiguration>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.IndexerApiController.<UpdateConfig>d__10.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\IndexerApiController.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
2018-05-28 15:40:42.4373 Info ApiExceptionHandler ExecuteExceptionFilterAsync  
2018-05-28 15:40:42.4373 Info IndexerApiController ExecuteAsync  
2018-05-28 15:40:42.4373 Info   Content-type='application/json; charset=utf-8', content-length=4989 
2018-05-28 15:40:42.6248 Info IndexerApiController Dispose  
2018-05-28 15:40:42.6248 Info IndexerApiController Dispose  `

**Comment by RikT** [comment]
Hmm seems to have sorted itself out for now but earlier whatever I did it wouldnt work :/
