### ISSUE TITLE
Cannot start Jackett anymore

### ISSUE THREAD

**Issue by Guduche** [Jackett/Jackett#3370]
Hi,

Couple days ago, I weren't home. When I got back, Jackett wasn't running anymore. I didn't found were was the source of the problem, I don't understand all the log. I also didn't find solutions on other issues. Could you help me please ?

When I start it with the mono command:

```
Can't find custom attr constructor image: /opt/jackett/Jackett.Common.dll mtoken: 0x0a00001a due to: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. assembly:Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed type:<unknown type> member:(null) signature:<none>

Unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: context
  at Autofac.ResolutionExtensions.ResolveService (Autofac.IComponentContext context, Autofac.Core.Service service, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00003] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
  at Autofac.ResolutionExtensions.Resolve (Autofac.IComponentContext context, System.Type serviceType, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00007] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
  at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
  at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context) [0x00000] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
  at Jackett.Common.Engine.get_Logger () [0x00000] in <632b969811a645e9b8eeaca761545239>:0
  at Jackett.Console.Program+<>c.<Main>b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00330] in <38fb2aa4b91049428a606992a197ef25>:0
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <a8f20d44a846452b83e01ced3f113eaa>:0
  at Jackett.Console.Program.Main (System.String[] args) [0x0002f] in <38fb2aa4b91049428a606992a197ef25>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
Parameter name: context
  at Autofac.ResolutionExtensions.ResolveService (Autofac.IComponentContext context, Autofac.Core.Service service, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00003] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
  at Autofac.ResolutionExtensions.Resolve (Autofac.IComponentContext context, System.Type serviceType, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00007] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
  at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
  at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context) [0x00000] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
  at Jackett.Common.Engine.get_Logger () [0x00000] in <632b969811a645e9b8eeaca761545239>:0
  at Jackett.Console.Program+<>c.<Main>b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00330] in <38fb2aa4b91049428a606992a197ef25>:0
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <a8f20d44a846452b83e01ced3f113eaa>:0
  at Jackett.Console.Program.Main (System.String[] args) [0x0002f] in <38fb2aa4b91049428a606992a197ef25>:0
```

syslog when I try to start it with systemd:

```
Jul 10 16:04:10 raspberrypi systemd[1]: Started Jackett Daemon.
Jul 10 16:04:13 raspberrypi mono[30465]: Can't find custom attr constructor image: /opt/jackett/Jackett.Common.dll mtoken: 0x0a00001a due to: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKey$
Jul 10 16:04:13 raspberrypi mono[30465]: Unhandled Exception:
Jul 10 16:04:13 raspberrypi mono[30465]: System.ArgumentNullException: Value cannot be null.
Jul 10 16:04:13 raspberrypi mono[30465]: Parameter name: context
Jul 10 16:04:13 raspberrypi mono[30465]:   at Autofac.ResolutionExtensions.ResolveService (Autofac.IComponentContext context, Autofac.Core.Service service, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00003] in <ba56c11e6d$
Jul 10 16:04:13 raspberrypi mono[30465]:   at Autofac.ResolutionExtensions.Resolve (Autofac.IComponentContext context, System.Type serviceType, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00007] in <ba56c11e6dad4c6a8e7ee8$
Jul 10 16:04:13 raspberrypi mono[30465]:   at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
Jul 10 16:04:13 raspberrypi mono[30465]:   at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context) [0x00000] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
Jul 10 16:04:13 raspberrypi mono[30465]:   at Jackett.Common.Engine.get_Logger () [0x00000] in C:\projects\jackett\src\Jackett.Common\Engine.cs:164
Jul 10 16:04:13 raspberrypi mono[30465]:   at Jackett.Console.Program+<>c.<Main>b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00330] in <38fb2aa4b91049428a606992a197ef25>:0
Jul 10 16:04:13 raspberrypi mono[30465]:   at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <a8f20d44a846452b83e01ced3f113eaa>:0
Jul 10 16:04:13 raspberrypi mono[30465]:   at Jackett.Console.Program.Main (System.String[] args) [0x0002f] in <38fb2aa4b91049428a606992a197ef25>:0
Jul 10 16:04:13 raspberrypi mono[30465]: [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
Jul 10 16:04:13 raspberrypi mono[30465]: Parameter name: context
Jul 10 16:04:13 raspberrypi mono[30465]:   at Autofac.ResolutionExtensions.ResolveService (Autofac.IComponentContext context, Autofac.Core.Service service, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00003] in <ba56c11e6d$
Jul 10 16:04:13 raspberrypi mono[30465]:   at Autofac.ResolutionExtensions.Resolve (Autofac.IComponentContext context, System.Type serviceType, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00007] in <ba56c11e6dad4c6a8e7ee8$
Jul 10 16:04:13 raspberrypi mono[30465]:   at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
Jul 10 16:04:13 raspberrypi mono[30465]:   at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context) [0x00000] in <ba56c11e6dad4c6a8e7ee8ff7b4c16b0>:0
Jul 10 16:04:13 raspberrypi mono[30465]:   at Jackett.Common.Engine.get_Logger () [0x00000] in C:\projects\jackett\src\Jackett.Common\Engine.cs:164
Jul 10 16:04:13 raspberrypi mono[30465]:   at Jackett.Console.Program+<>c.<Main>b__0_1 (Jackett.Common.Models.Config.ConsoleOptions options) [0x00330] in <38fb2aa4b91049428a606992a197ef25>:0
Jul 10 16:04:13 raspberrypi mono[30465]:   at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <a8f20d44a846452b83e01ced3f113eaa>:0
Jul 10 16:04:13 raspberrypi mono[30465]:   at Jackett.Console.Program.Main (System.String[] args) [0x0002f] in <38fb2aa4b91049428a606992a197ef25>:0
Jul 10 16:04:13 raspberrypi systemd[1]: jackett.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 16:04:13 raspberrypi systemd[1]: jackett.service: Unit entered failed state.
Jul 10 16:04:13 raspberrypi systemd[1]: jackett.service: Failed with result 'exit-code'.
Jul 10 16:04:15 raspberrypi systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Jul 10 16:04:15 raspberrypi systemd[1]: Stopped Jackett Daemon.
Jul 10 16:04:15 raspberrypi systemd[1]: Started Jackett Daemon.
```

log.txt (lots of "Info Found ... releases from ..." before) :

```
2018-07-03 13:06:24.1318 Info Found 100 (0 new) releases from Torrent Downloads
2018-07-03 13:06:29.2807 Info New release found.  Current: v0.8.1201 New: v0.8.1209
2018-07-03 13:06:34.6085 Info Found 100 (0 new) releases from Torrent Downloads
2018-07-03 13:06:36.9336 Info Starting updater: mono /tmp/JackettUpdate-v0.8.1209-636662199944072960/Jackett/JackettUpdater.exe --Path "/opt/jackett" --Type "Console" --Args " JackettConsole.exe --NoRestart" --KillPids "6375" --NoRestar$
2018-07-03 13:06:37.0010 Info Updater started process id: 7170
```

update.txt (lots of "Info Copying" before) :

```
018-07-03 13:06:40.8196 Info Copying microsoft.owin.hosting.dll
2018-07-03 13:06:40.8196 Info Copying microsoft.owin.staticfiles.dll
2018-07-03 13:06:40.8196 Info Copying microsoft.owin.dll
2018-07-03 13:06:40.8196 Info Copying mimemapping.dll
2018-07-03 13:06:40.8289 Info Copying nlog.dll
2018-07-03 13:06:40.8289 Info Copying newtonsoft.json.dll
```

Jackett version: I did not find where I can get it
Mono version: 5.12.0.226

**Comment by kaso17** [comment]
Looks like some update went wrong (Maybe some missing write permissions?).
Please try to simply re-install (reextract all the files) to fix this.

**Comment by ivandelabeldad** [comment]
Same here. Trying to update Jackett got messed up.

Trying to start it says this:

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: context
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Jackett.Common.Engine.get_Logger()
   at Jackett.Console.Program.<>c.<Main>b__0_1(ConsoleOptions options) in C:\projects\jackett\src\Jackett.Console\Program.cs:line 191
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Jackett.Console.Program.Main(String[] args) in C:\projects\jackett\src\Jackett.Console\Program.cs:line 38
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: context
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Jackett.Common.Engine.get_Logger()
   at Jackett.Console.Program.<>c.<Main>b__0_1(ConsoleOptions options) in C:\projects\jackett\src\Jackett.Console\Program.cs:line 191
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Jackett.Console.Program.Main(String[] args) in C:\projects\jackett\src\Jackett.Console\Program.cs:line 38
```

**Comment by jeff15110168** [comment]
same thing here, not sure what happened...haven't been able to update manually or automatically either

**Comment by flightlevel** [comment]
@jeff15110168 @ivandelabeldad haven't supplied any versions, but looking at @Guduche looks like it happened updating to v0.8.1209 which didn't have any major changes. Strange this is only happening to a few people.

Please try reinstalling with the latest version (not using the updater) , if that doesn't work, then provide the below information

From a console, can you run `export MONO_LOG_LEVEL=debug`
then run `mono --debug JackettConsole.exe -t -l`
and provide the console AND log output

**Comment by trinsic** [comment]
Had same problem as @Guduche and a reinstall with latest installer fixed it.

**Comment by mobamoba** [comment]
I'm having this issue as well. I'm running on Windows with the latest version. From the Windows event logs:

```
Application: JackettConsole.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at Autofac.ResolutionExtensions.ResolveService(Autofac.IComponentContext, Autofac.Core.Service, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>)
   at Autofac.ResolutionExtensions.Resolve[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Autofac.IComponentContext, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>)
   at Autofac.ResolutionExtensions.Resolve[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Autofac.IComponentContext)
   at Jackett.Common.Engine.get_Logger()
   at Jackett.Console.Program+<>c.<Main>b__0_1(Jackett.Common.Models.Config.ConsoleOptions)
   at CommandLine.ParserResultExtensions.WithParsed[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](CommandLine.ParserResult`1<System.__Canon>, System.Action`1<System.__Canon>)
   at `Jackett.Console.Program.Main(System.String[])`
```

and:

```
Faulting application name: JackettConsole.exe, version: 0.8.1243.0, time stamp: 0x5b3f395a
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18938, time stamp: 0x5a7dd8a7
Exception code: 0xe0434352
Fault offset: 0x00015ef8
Faulting process id: 0x19c0
Faulting application start time: 0x01d419033e01ba02
Faulting application path: C:\ProgramData\Jackett\JackettConsole.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: 7be2b973-84f6-11e8-8104-003048bd0b86
Faulting package full name: 
Faulting package-relative application ID: 
```
```

**Comment by flightlevel** [comment]
@mobamoba In your Jackett program folder (usually C:\ProgramData\Jackett can you right click on `Jackett.Common.dll` and see what the version number is from the details tab.

Would try a reinstall to fix

**Comment by mobamoba** [comment]
Version .0.8.1264

Yes reinstall fixes. However I've had to reinstall after every update for the past few updates.

**Comment by Guduche** [comment]
Thank you @kaso17 and @flightlevel !
I installed the lastest version, v0.8.1263, and it works now !

**Comment by ivandelabeldad** [comment]
@flightlevel I updated to **v0.8.1258**.

Downloading manually and overriding fixed the problem.

**Comment by camwise** [comment]
I'm running on windows and was having same problem.  When I went and looked at dll properties it showed 0.8.1263, but wouldn't open the web gui.  Service showed it was running though.  Reinstalled the 0.8.1263 update manually and it's all working again.

**Comment by NGRichter** [comment]
Reinstall fixed it.

**Comment by Fiala06** [comment]
Reinstall fixed it for me also.
