### ISSUE TITLE
[theplace] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by rahimsaied** [Jackett/Jackett#3676]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.<TestLogin>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.CardigannIndexer.<ApplyConfiguration>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Controllers.IndexerApiController.<UpdateConfig>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext()

**Jackett version**:  v0.10.97
**Mono version** (if not using Windows):  

-------------------------------

**Comment by rahimsaied** [comment]
Please help. When I try to add this tracker [ThePlace]-https://theplace.click/ jackett says login failed.

**Comment by kaso17** [comment]
Works fine for me.
Please provide a FULLenhanced log. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Comment by rahimsaied** [comment]
@kaso17 ** THIS IS THE FULL ENHANCED LOG.**
![44528095-54d9c380-a706-11e8-899f-34196532b780](https://user-images.githubusercontent.com/42635182/44629892-5d830180-a973-11e8-9ee6-6ef0de9e5338.png)
![44528097-55725a00-a706-11e8-8b7c-97c5df5141f7](https://user-images.githubusercontent.com/42635182/44629893-5d830180-a973-11e8-906a-24bde0aa81c0.png)
![44528098-55725a00-a706-11e8-8559-a40ad57b2050](https://user-images.githubusercontent.com/42635182/44629894-5e1b9800-a973-11e8-864c-1dc65e2bcf8a.png)
![44528099-55725a00-a706-11e8-8545-089d6a6dff40](https://user-images.githubusercontent.com/42635182/44629895-5e1b9800-a973-11e8-88de-7ad6d336aa43.png)

**Comment by rahimsaied** [comment]
@kaso17 Please help. I have provided the full enhanced log.

**Comment by garfield69** [comment]
@rahimsaied  we need the FULL (in other words, the complete) enhanced log file, not just the snippet you provided from the jackett dashboard of just the error. Vital other log messages before the error are required if you want us to analyse this problem.
so:
1. make sure the *enhanced logging* checkbox is ticked on the jackett dashboard and that you used the *apply server settings* button to set this session in enhanced logging mode.
2. repeat the test
3. locate the log.txt file in your jackett folder and drag/drop it here so we can take a look

**Comment by rahimsaied** [comment]
@garfield69 **THIS ARE THE FULL ENHANCED LOG FILES**
[log.txt.20180823.00000.txt](https://github.com/Jackett/Jackett/files/2322283/log.txt.20180823.00000.txt)
[log.txt.20180824.00000.txt](https://github.com/Jackett/Jackett/files/2322284/log.txt.20180824.00000.txt)
[log.txt.20180824.00001.txt](https://github.com/Jackett/Jackett/files/2322285/log.txt.20180824.00001.txt)

**Comment by rahimsaied** [comment]
@garfield69 **I FORGOT TO INCLUDE THIS. THIS IS THE COMPLETE ENHANCED LOG FILE**
[log.txt](https://github.com/Jackett/Jackett/files/2323587/log.txt)

**Comment by rahimsaied** [comment]
@garfield69 PLEASE HELP.

**Comment by rahimsaied** [comment]
@garfield69 **PLEASE HELP**
@kaso17 **PLEASE HELP**
I HAVE PROVIDED THE COMPLETE ENHANCED LOG FILE ABOVE.

**Comment by garfield69** [comment]
@rahimsaied  it looks to me like your are not passing the freecapture test during your login attempt.

So I suggest that from your jackett dashboard, edit your *theplace* indexer config, and enter the captcha challenge word that appears on the image and save.
BTW, did you know that using all capital letters in your replies is considered shouting? 

@kaso17  is it worth trying a test where you enter the wrong capcha challenge word, and then see if you are able to subsequently pass the challenge with the correct word?
I don't have a login for this site so I cant test this for myself, but I wonder if the refreshing of the challenge is not working correctly. This is pure speculation on my part, I have no evidence that it is faulty, just wondering if this has been tested previously.

**Comment by rahimsaied** [comment]
@garfield69 I tried what you said but it says wrong username or password.

**Comment by garfield69** [comment]
use your browser to logon to https://theplace.click/login.php and confirm you have a valid username and password, then try again using your jackett dashboard to edit your *theplace* indexer config, and reenter the correct username, password and captcha word.

**Comment by rahimsaied** [comment]
@garfield69 I tried everything you said. I even re-installed jackett. This is the error jackett displayed:

[theplace] Error: Login failed!Username or password incorrect. If you have an account here please use the recovery system or try again.  Retrieve Password! (Config)

I am posting the log file for this below:
[log.txt](https://github.com/Jackett/Jackett/files/2326652/log.txt)
[log.txt.20180828.00000.txt](https://github.com/Jackett/Jackett/files/2326653/log.txt.20180828.00000.txt)

**Comment by garfield69** [comment]
@kaso17  i'm unable to help this user out, so I'm passing this one back to you. Cheers.

**Comment by rahimsaied** [comment]
@garfield69 **USELESS MOTHERFUCKER**
