### ISSUE TITLE
Jackett dies after a couple of days and will not start

### ISSUE THREAD

**Issue by goku-son** [Jackett/Jackett#3719]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  v0.10.117.0 
**Mono version** (if not using Windows):  
-------------------------------
I am using the Windows binaries. Here is the log output:
2018-08-30 18:13:58.1912 Info Starting Jackett v0.10.117.0 
2018-08-30 18:13:58.8862 Info Environment version: 4.0.30319.42000 (C:\Windows\Microsoft.NET\Framework\v4.0.30319\) 
2018-08-30 18:13:58.8862 Info OS version: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit OS) 
2018-08-30 18:13:58.8862 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2018-08-30 18:13:58.8862 Info App config/log directory: C:\ProgramData\Jackett 
2018-08-30 18:13:58.8902 Info Using HTTP Client: HttpWebClient 
2018-08-30 18:13:58.8902 Error System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Jackett.Common.Services.IndexerManagerService.InitIndexers()
   at Jackett.Common.Services.IndexerManagerService.InitIndexers(IEnumerable`1 path)
   at Jackett.Server.Services.ServerService.Initalize()
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args) System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Jackett.Common.Services.IndexerManagerService.InitIndexers()
   at Jackett.Common.Services.IndexerManagerService.InitIndexers(IEnumerable`1 path)
   at Jackett.Server.Services.ServerService.Initalize()
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

If I copy over the binaries and start over it will work for a few more days then the same problem and solution. However it is getting combersome to do this every couple of days. Issue has been happening after upgrading from Jackett-0.8.1027. If I revert back to that version the issue goes away.

**Comment by garfield69** [comment]
I see from your startup `Info Environment version: 4.0.30319.42000 (C:\Windows\Microsoft.NET\Framework\v4.0.30319)` that you appear to be using .net 4.0, but Jackett is built to require at least .net 4.6.1
so I'm thinking that you should upgrade your .net via https://www.microsoft.com/net/download/dotnet-framework/net461 and that this may resolve your problem.

**Comment by goku-son** [comment]
@garfield69 thanks much for the suggestion. I upgraded .net but still the issue remains:

2018-08-30 19:34:08.5623 Info Starting Jackett v0.10.117.0 
2018-08-30 19:34:09.2164 Info Environment version: 4.0.30319.42000 (C:\Windows\Microsoft.NET\Framework\v4.0.30319\) 
2018-08-30 19:34:09.2164 Info OS version: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit OS) 
2018-08-30 19:34:09.2164 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2018-08-30 19:34:09.2164 Info App config/log directory: C:\ProgramData\Jackett 
2018-08-30 19:34:09.2164 Info Using HTTP Client: HttpWebClient 
2018-08-30 19:34:09.2314 Error System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Jackett.Common.Services.IndexerManagerService.InitIndexers()
   at Jackett.Common.Services.IndexerManagerService.InitIndexers(IEnumerable`1 path)
   at Jackett.Server.Services.ServerService.Initalize()
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args) System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Jackett.Common.Services.IndexerManagerService.InitIndexers()
   at Jackett.Common.Services.IndexerManagerService.InitIndexers(IEnumerable`1 path)
   at Jackett.Server.Services.ServerService.Initalize()
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

In the meantime, I will override my binaries directory which at least allows it to start up for a few days.

**Comment by goku-son** [comment]
I have .net 4.7 installed but clearly the startup info you cite shows otherwise so I installed 4.6.1 from the link you provided but still it fails with the same error but startup info also still shows the version of .net you cited from my logs. Not sure if I need to reboot but here is what I got in terms of .net versions:

Installed:
.NET Framework 2.0 Service Pack 2
.NET Framework 3.0 Service Pack 2
.NET Framework 3.5 Service Pack 1
.NET Framework 4.7
 
Any other suggestions or ideas? Thanks in advance.

**Comment by garfield69** [comment]
yeah, I got suckered by that one. I took a look at my jackett log of my visual studio 2017 assembly build run and the *info environment version* is the same as yours. sorry about that.
@flightlevel  any thoughts on what might be going on in this ticket?

**Comment by goku-son** [comment]
No worries, I removed 4.7 and installed 4.6.2 but same issue. Thanks for the suggestion though.

**Comment by jeremysherriff** [comment]
Interesting.  I was getting similar on Ubuntu with Mono, the wording is different but the version is the same and both lots of error messages seem to refer to Types:

````
root@openflixr:~# mono /opt/jackett.broken/JackettConsole.exe -v
08-31 20:26:06 Info Starting Jackett v0.10.117.0
08-31 20:26:06 Error System.TypeLoadException: Could not resolve type with token 01000058 from typeref (expected class 'Microsoft.Extensions.Primitives.CompositeChangeToken' in assembly 'Microsoft.Extensions.Primitives, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60')
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.GetOrAddChangeToken (System.String pattern) [0x00022] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken (System.String filter) [0x0002c] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch (System.String filter) [0x0001e] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__0_0 () [0x00016] in <5b0219d367fd4fd68bb5d8e979bb16b3>:0
  at Microsoft.Extensions.Primitives.ChangeToken.OnChange (System.Func`1[TResult] changeTokenProducer, System.Action changeTokenConsumer) [0x00053] in <e2e2ae8492844d358dd36210bf615ced>:0
  at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor (Microsoft.Extensions.Configuration.FileConfigurationSource source) [0x00035] in <5b0219d367fd4fd68bb5d8e979bb16b3>:0
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor (Microsoft.Extensions.Configuration.Json.JsonConfigurationSource source) [0x00000] in <0e68ef06fd2e44e8aef196caafeeef36>:0
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build (Microsoft.Extensions.Configuration.IConfigurationBuilder builder) [0x00007] in <0e68ef06fd2e44e8aef196caafeeef36>:0
  at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build () [0x0001a] in <c58a7bdd3f5a468aa1ce25bba6f36889>:0
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices (System.AggregateException& hostingStartupErrors) [0x001cf] in <6ac88ff998174be78f0d6ab05b5f222b>:0
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build () [0x0001a] in <6ac88ff998174be78f0d6ab05b5f222b>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x002c6] in <d6819775d910452ca544bd4b70d063ba>:0  System.TypeLoadException: Could not resolve type with token 01000058 from typeref (expected class 'Microsoft.Extensions.Primitives.CompositeChangeToken' in assembly 'Microsoft.Extensions.Primitives, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60')
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.GetOrAddChangeToken (System.String pattern) [0x00022] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken (System.String filter) [0x0002c] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch (System.String filter) [0x0001e] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__0_0 () [0x00016] in <5b0219d367fd4fd68bb5d8e979bb16b3>:0
  at Microsoft.Extensions.Primitives.ChangeToken.OnChange (System.Func`1[TResult] changeTokenProducer, System.Action changeTokenConsumer) [0x00053] in <e2e2ae8492844d358dd36210bf615ced>:0
  at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor (Microsoft.Extensions.Configuration.FileConfigurationSource source) [0x00035] in <5b0219d367fd4fd68bb5d8e979bb16b3>:0
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor (Microsoft.Extensions.Configuration.Json.JsonConfigurationSource source) [0x00000] in <0e68ef06fd2e44e8aef196caafeeef36>:0
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build (Microsoft.Extensions.Configuration.IConfigurationBuilder builder) [0x00007] in <0e68ef06fd2e44e8aef196caafeeef36>:0
  at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build () [0x0001a] in <c58a7bdd3f5a468aa1ce25bba6f36889>:0
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices (System.AggregateException& hostingStartupErrors) [0x001cf] in <6ac88ff998174be78f0d6ab05b5f222b>:0
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build () [0x0001a] in <6ac88ff998174be78f0d6ab05b5f222b>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x002c6] in <d6819775d910452ca544bd4b70d063ba>:0

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000058 from typeref (expected class 'Microsoft.Extensions.Primitives.CompositeChangeToken' in assembly 'Microsoft.Extensions.Primitives, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60')
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.GetOrAddChangeToken (System.String pattern) [0x00022] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken (System.String filter) [0x0002c] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch (System.String filter) [0x0001e] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__0_0 () [0x00016] in <5b0219d367fd4fd68bb5d8e979bb16b3>:0
  at Microsoft.Extensions.Primitives.ChangeToken.OnChange (System.Func`1[TResult] changeTokenProducer, System.Action changeTokenConsumer) [0x00053] in <e2e2ae8492844d358dd36210bf615ced>:0
  at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor (Microsoft.Extensions.Configuration.FileConfigurationSource source) [0x00035] in <5b0219d367fd4fd68bb5d8e979bb16b3>:0
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor (Microsoft.Extensions.Configuration.Json.JsonConfigurationSource source) [0x00000] in <0e68ef06fd2e44e8aef196caafeeef36>:0
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build (Microsoft.Extensions.Configuration.IConfigurationBuilder builder) [0x00007] in <0e68ef06fd2e44e8aef196caafeeef36>:0
  at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build () [0x0001a] in <c58a7bdd3f5a468aa1ce25bba6f36889>:0
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices (System.AggregateException& hostingStartupErrors) [0x001cf] in <6ac88ff998174be78f0d6ab05b5f222b>:0
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build () [0x0001a] in <6ac88ff998174be78f0d6ab05b5f222b>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x00307] in <d6819775d910452ca544bd4b70d063ba>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000058 from typeref (expected class 'Microsoft.Extensions.Primitives.CompositeChangeToken' in assembly 'Microsoft.Extensions.Primitives, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60')
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.GetOrAddChangeToken (System.String pattern) [0x00022] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken (System.String filter) [0x0002c] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch (System.String filter) [0x0001e] in <fe53c59e59af49e1aa6e94d0508520df>:0
  at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__0_0 () [0x00016] in <5b0219d367fd4fd68bb5d8e979bb16b3>:0
  at Microsoft.Extensions.Primitives.ChangeToken.OnChange (System.Func`1[TResult] changeTokenProducer, System.Action changeTokenConsumer) [0x00053] in <e2e2ae8492844d358dd36210bf615ced>:0
  at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor (Microsoft.Extensions.Configuration.FileConfigurationSource source) [0x00035] in <5b0219d367fd4fd68bb5d8e979bb16b3>:0
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor (Microsoft.Extensions.Configuration.Json.JsonConfigurationSource source) [0x00000] in <0e68ef06fd2e44e8aef196caafeeef36>:0
  at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build (Microsoft.Extensions.Configuration.IConfigurationBuilder builder) [0x00007] in <0e68ef06fd2e44e8aef196caafeeef36>:0
  at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build () [0x0001a] in <c58a7bdd3f5a468aa1ce25bba6f36889>:0
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices (System.AggregateException& hostingStartupErrors) [0x001cf] in <6ac88ff998174be78f0d6ab05b5f222b>:0
  at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build () [0x0001a] in <6ac88ff998174be78f0d6ab05b5f222b>:0
  at Jackett.Server.Program.Main (System.String[] args) [0x00307] in <d6819775d910452ca544bd4b70d063ba>:0
````

I renamed the directory and installed whatever version is current, it worked first time and all config was intact so I assumed I broke something and didn't worry about root cause.  As you can see I still have the version available so can do some troubleshooting if needed.

**Comment by flightlevel** [comment]
@goku-son This is some sort of environmental issue if Jackett works fine and then you start getting these errors. Its usually due to a missing file/corrupted file
My suspicion would be antivirus related
