### ISSUE TITLE
Malformed input: 365 is an invalid input length

### ISSUE THREAD

**Issue by chrisric** [Jackett/Jackett#4030]
I upgraded mono today and started getting the below error on CouchPotato. I upgraded Jackett in an effort to fix the issue. The same error is generated when Medusa tries to snatch through Jackett too.

Accessing Jackett through the web interface works fine, I can search the indexers without issue and its caching releases too.

Maybe something to do with the Jackett API interface? Not sure where to go from here.

CouchPotato Log:
```
10-19 21:35:49 ERROR [edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/Users/admin/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/Users/admin/CouchPotatoServer/couchpotato/core/plugins/base.py", line 227, in urlopen
    response.raise_for_status()
  File "/Users/admin/CouchPotatoServer/libs/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: http://10.10.10.246:9117/dl/torrentday/?jackett_apikey=qwertyuiopasdfghjklzxcvbnm012345&path=SDNGb08xVDNGMmxxT05vUzNxaTVMMXU2UndVbUkrM1kwSzZUMEdobEY3Q2hqazZrM29Bd1ZCMFRzckV5SWtkQ1RkTXZ5Yzh2WDNEK1lwNFJIbVpqSkpvQldZcE9KVTR1YmpsRHRSL3BrTnR3WHllQVlKamhXd1ZJZlRWMDRjRW83OVEwSEluNzE2MjQ0SXIrZUdlbGs5Q3MxcmpPa1BNQmRoVUVBbE9xOE5oc2dsWlZYYzQrK2NxZzZ3MVp6OXY5V1k0VlVMS2hZbjVjM1h1Q0JnaGsraG16M2NlSzVJMlRBdG9BRkl3OVJsb1hqTURGNXB0TnJIV3pYcHpwTEthMzByVTZQRHhPTEE5MHFkQWtNckxuTlBaREtrRDFlbmErSTZVNSsyRzE5VVI5UDJZR3dacnhQeGxkSGpuRXl0YzVNZkNHb0J5eGM3WDJRUXkwWW1EVkJ6U2xseUpWMENKNnJURzFabzVxdkowPQ2&file=some+movie+2018
```

Errors from Jackett log:

```
2018-10-19 17:32:49.2439 Info Request starting HTTP/1.1 GET http://10.10.10.246:9117/dl/torrentday/?jackett_apikey=qwertyuiopasdfghjklzxcvbnm012345&path=MGV2QWV6Qi81aUdhS0hSV2hMZFhMZGRkTmhGaWVibUJUclFrTHlpVVZvbmh2YitCa2R5cTAreWFaK3R3ejlvYWpiczdha0tVQm94UDhvMHhCODJrdmxqSEsybTdUelFOM0t4QWd1Z1U0SklqV1c1UXhkU29nSTZPM3J5REFRZzlYVEEwSG1KUmlYZkZuMTB2aUswbHE4MEJyMjhHemtTMFdvRExrQmZCc09xaWhQeDk3MW9kNlRIc2NISXQ0Tk9NZFZNVEJZckhzbDVMZ1JqcTRwcG1jS0pEUUVpSi93bGdOMDd1c2l4VWY0Tm5TSitXdXl4ZVVvVmFzTEFCZlJoVUNYZDh1Kzd4Z2cwSTBZMFdkZXdNVlkvZ0pGYVNJMUMyb1NHVzgvbUNoTFVGSFVNc0daK2dUdVBDb0tHTUxmY1J6NjlJWTVxcWtYR3BrWG1DUE9DbXVIeGJsMnVadmhFUlBRYjBKcllJT0U4PQ2&file=some+movie+2018
2018-10-19 17:32:49.2451 Info Route matched with {action = "Download", controller = "Download"}. Executing action Jackett.Server.Controllers.DownloadController.Download (JackettConsole)
2018-10-19 17:32:49.2464 Info Executing action method Jackett.Server.Controllers.DownloadController.Download (JackettConsole) with arguments (torrentday, MGV2QWV6Qi81aUdhS0hSV2hMZFhMZGRkTmhGaWVibUJUclFrTHlpVVZvbmh2YitCa2R5cTAreWFaK3R3ejlvYWpiczdha0tVQm94UDhvMHhCODJrdmxqSEsybTdUelFOM0t4QWd1Z1U0SklqV1c1UXhkU29nSTZPM3J5REFRZzlYVEEwSG1KUmlYZkZuMTB2aUswbHE4MEJyMjhHemtTMFdvRExrQmZCc09xaWhQeDk3MW9kNlRIc2NISXQ0Tk9NZFZNVEJZckhzbDVMZ1JqcTRwcG1jS0pEUUVpSi93bGdOMDd1c2l4VWY0Tm5TSitXdXl4ZVVvVmFzTEFCZlJoVUNYZDh1Kzd4Z2cwSTBZMFdkZXdNVlkvZ0pGYVNJMUMyb1NHVzgvbUNoTFVGSFVNc0daK2dUdVBDb0tHTUxmY1J6NjlJWTVxcWtYR3BrWG1DUE9DbXVIeGJsMnVadmhFUlBRYjBKcllJT0U4PQ2, qwertyuiopasdfghjklzxcvbnm012345, some movie 2018) - Validation state: Valid
2018-10-19 17:32:49.2470 Error Error downloading torrentday 0evAezB/5iGaKHRWhLdXLdddNhFiebmBTrQkLyiUVonhvb+Bkdyq0+yaZ+twz9oajbs7akKUBoxP8o0xB82kvljHK2m7TzQN3KxAgugU4JIjWW5QxdSogI6O3ryDAQg9XTA0HmJRiXfFn10viK0lq80Br28GzkS0WoDLkBfBsOqihPx971od6THscHIt4NOMdVMTBYrHsl5LgRjq4ppmcKJDQEiJ/wlgN07usixUf4NnSJ+WuyxeUoVasLABfRhUCXd8u+7xgg0I0Y0WdewMVY/gJFaSI1C2oSGW8/mChLUFHUMsGZ+gTuPCoKGMLfcRz69IY5qqkXGpkXmCPOCmuHxb System.Security.Cryptography.CryptographicException: An error occurred during a cryptographic operation. ---> System.FormatException: Malformed input: 365 is an invalid input length.
  at Microsoft.Extensions.Internal.WebEncoders.GetNumBase64PaddingCharsToAddForDecode (System.Int32 inputLength) [0x00037] in <d28c1fbc79e143e2aebf5016282178ec>:0
  at Microsoft.Extensions.Internal.WebEncoders.GetArraySizeRequiredToDecode (System.Int32 count) [0x00014] in <d28c1fbc79e143e2aebf5016282178ec>:0
  at Microsoft.Extensions.Internal.WebEncoders.Base64UrlDecode (System.String input, System.Int32 offset, System.Int32 count) [0x00029] in <d28c1fbc79e143e2aebf5016282178ec>:0
  at Microsoft.Extensions.Internal.WebEncoders.Base64UrlDecode (System.String input) [0x00016] in <d28c1fbc79e143e2aebf5016282178ec>:0
  at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect (Microsoft.AspNetCore.DataProtection.IDataProtector protector, System.String protectedData) [0x0001d] in <d28c1fbc79e143e2aebf5016282178ec>:0
   --- End of inner exception stack trace ---
  at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect (Microsoft.AspNetCore.DataProtection.IDataProtector protector, System.String protectedData) [0x00059] in <d28c1fbc79e143e2aebf5016282178ec>:0
  at Jackett.Server.Services.ProtectionService.UnProtect (System.String plainText) [0x0000e] in C:\projects\jackett\src\Jackett.Server\Services\ProtectionService.cs:56
  at Jackett.Server.Controllers.DownloadController+<Download>d__5.MoveNext () [0x00090] in C:\projects\jackett\src\Jackett.Server\Controllers\DownloadController.cs:47
2018-10-19 17:32:49.2488 Info Executed action method Jackett.Server.Controllers.DownloadController.Download (JackettConsole), returned result Microsoft.AspNetCore.Mvc.NotFoundResult in 1.9262ms.
2018-10-19 17:32:49.2488 Info Executing HttpStatusCodeResult, setting HTTP status code 404
2018-10-19 17:32:49.2498 Info Executed action Jackett.Server.Controllers.DownloadController.Download (JackettConsole) in 4.268ms
2018-10-19 17:32:49.2498 Info Request finished in 6.4389ms 404
```

QNAP: TS-453A, FW: v4.3.4.0516
Jackett: v0.10.325.0
Mono: Tried v5.11.0 (QNAP QPKG) and v5.14.0.177 (QMono QPKG)

**Comment by flightlevel** [comment]
Is this happening on a particular file (does it have any strange characters?) or all files you try?
Is it just TorrentDay or all trackers?
Does it happen from the Jackett manual search as well?

**Comment by flightlevel** [comment]
Paste the exact links (you can obfuscate API key if you like) for exactly the same file
-Once from Jackett manual search that works
-Once from the error couchpotato spits out 
so we can see whats different

Screenshot of CP torrentpotato settings as well

**Comment by chrisric** [comment]
CP link:
```
http://10.10.10.246:9117/dl/torrentday/?jackett_apikey=1qce3l8cwk2trbanqzqwzlrhz132csfs&path=TnhHRjEwaXNDRXBQZDUxc1Fjak9zOVZrMHFRdlZFdm1hUTRKMlBHcnROdEtGQWg2Uy91YWtjbEZpVDFNRnJwZTQ4d21jZmh2bjlvVXU1M0hLcnpGaWYwY2Q2NzJvbW9aQUs5YThUdFpxUmpDVUJaZXRpWEc0SUJJbk8xUk9DVHRibUF2Nm1RTEdHTkJ0NVRmY0lQR2xRSFAxVU9oUU1xSFFlQ3pJTUhuS1dXRTJaRGoxZUJiZjR2VFVWUklTMkdXb0VMN2RwaCt6MFl3NHRCNGtBOVp4VHd6TXB2WWkrbW56UUdlMVNweW1kZ016cEFwT0swZVhtVXE2MlBnYW9mUVIwa1VESXIyWko1Q254M1l4d2t4bmlSNGZjMFlkbmlmRUR3WFVnVU5qQ1puN1ZneUg2RVBIbkQvbDZWN3lNa3RRSkl3ODJLMzNkZ1JoZFZ5RXBja2laRGo4dDFlZ2xVaGUwYVMwcitHN09jPQ2&file=The+Spy+Who+Dumped+Me+2018+BRRip+XviD+AC3-EVO
```

Jackett manual search/snatch link:
```
http://10.10.10.246:9117/dl/torrentday/?jackett_apikey=1qce3l8cwk2trbanqzqwzlrhz132csfs&path=Q2ZESjhKaDZxQUxEYjQxQWljOWdUcHZHekR2RGFyRzJLVTUxWE5GRkJETXJfcWZVMllLLVVRdGs5SXVWSnVzWlk2NEh5NFd1QVU4SUpRb1Ruc1FaX2VLNHhjU2R4ZFhjWllNU0VaZl8tNGZQM3FLOVlfZGJfbGZPVEV0ejJDRmxOVTZCOGwycFhZaV9yZldzV28yQmJqVTNXM2Rfa0Vnc1h6YjU3MGNiZExBcTk1bFh5b2lpNFN0R2Q2U1Z4cEtIYkNrUVBB&file=The+Spy+Who+Dumped+Me+2018+BRRip+XviD+AC3-EVO
```

CP config:

```
[torrentpotato]
use = 1,1
seed_time = 1,1
name = ,
extra_score = ,
enabled = 1
host = http://10.10.10.246:9117/api/v2.0/indexers/torrentday/results/potato/,http://10.10.10.246:9117/api/v2.0/indexers/iptorrents/results/potato/
pass_key = 1qce3l8cwk2trbanqzqwzlrhz132csfs,1qce3l8cwk2trbanqzqwzlrhz132csfs
seed_ratio = 1,1

```

**Comment by chrisric** [comment]
I noticed the links were different so I deleted the movies from CP and re-added them. Now the links are the same and its working correctly. I'm not sure why Medusa isn't working but I doubt its a Jackett problem now.

Sorry taking up your time.

Thanks.
