### ISSUE TITLE
Error System.TypeLoadException: Could not load type 'Jackett.Common.Utils.BuildDate' 

### ISSUE THREAD

**Issue by Tejas-D** [Jackett/Jackett#4109]
Jackett suddenly stopped working. I cannot start the service anymore. Please see the log error below. 

2018-11-02 17:54:25.3296 Info Starting Jackett v0.10.365.0 
2018-11-02 17:54:25.5946 Info Initiating Jackett service start 
2018-11-02 17:54:26.5306 Info Starting Jackett v0.10.365.0 
2018-11-02 17:54:28.1677 Error System.TypeLoadException: Could not load type 'Jackett.Common.Utils.BuildDate' from assembly 'Jackett.Common, Version=0.10.365.0, Culture=neutral, PublicKeyToken=null'.
   at Jackett.Server.Services.ServerService.Initalize()
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args) System.TypeLoadException: Could not load type 'Jackett.Common.Utils.BuildDate' from assembly 'Jackett.Common, Version=0.10.365.0, Culture=neutral, PublicKeyToken=null'.
   at Jackett.Server.Services.ServerService.Initalize()
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

-------------------------------

**Comment by garfield69** [comment]
suggest forcing an update to the latest version 0.10.410+ by installing it manually and see if this resolves your problem.
