### ISSUE TITLE
Jackett always fail to update

### ISSUE THREAD

**Issue by Blackkatt** [Jackett/Jackett#413]
Hey, am running Jackett console when i try to update it always fails. 
```

2016-07-28 18:06:15.1887 Info Jackett Updater v0.7.296 
2016-07-28 18:06:15.2037 Info Options --Path D:\ProgramData\Jackett --Type jackettconsole.exe --Args  
2016-07-28 18:06:15.2168 Info Waiting for Jackett to close.. 
2016-07-28 18:06:17.2174 Info Finding files in: C:\Users\Gurra%20Purra\AppData\Local\Temp\JackettUpdate-v0.7.296-636053259744256951\Jackett\ 
2016-07-28 18:06:17.2174 Error Exception applying update! System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Gurra%20Purra\AppData\Local\Temp\JackettUpdate-v0.7.296-636053259744256951\Jackett'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Jackett.Updater.Program.ProcessUpdate(UpdaterConsoleOptions options)
   at Jackett.Updater.Program.Run(String[] args)
```

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/issues/154
