### ISSUE TITLE
[Tracker Request] Pornolab.net

### ISSUE THREAD

**Issue by uNderdog101** [Jackett/Jackett#4373]
Could you please add support for http://pornolab.net ? It's a Russian-language porn tracker. It's semi-private and needs no invite for signup.

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by uNderdog101** [comment]
Sorry, I haven't got a clue on how to do _any_ of what you linked.

**Comment by MikeLund** [comment]
I'm too lazy to touch this, but I believe they're using very similar software to rutracker (TorrentPier). Wouldn't be a direct copypaste from there, but perhaps a good place to start if someone wanted to work on this.

**Comment by MrNeon** [comment]
Unlike RuTracker the download requires having cookies set. Is there a way to tell Jackett to use cookies when downloading the torrent?

**Comment by kaso17** [comment]
Cookies are usually used by default for all requests (unless you explicitly override them).

**Comment by MrNeon** [comment]
I see.

A cookie with the id of the torrent is set when the download link is clicked:

`$a.bind(event, function(){setCookie('bb_dl', t_id, 'SESSION')});`

Can this be replicated in Jackett?

**Comment by kaso17** [comment]
as this will be a native indexer (like rutracker) this can be done.

**Comment by advokatb** [comment]
Joining the request. It would be great.

**Comment by lpearl** [comment]
@garfield69 I've started the prosses of indexing pornolab. So far it's very similar to rutracker. The indexing does not seem hard but when it comes to the other stuff, I may start to get confused.

**Comment by garfield69** [comment]
@lpearl  I'll try to help if I can, but you should be aware that I am not a C# developer and so I am unlikely to  be able to provide coding solutions to problems you raise unless I can find similar already coded solutions in existing C# indexers.

**Comment by lpearl** [comment]
@garfield69 Who is the C# developer?

**Comment by garfield69** [comment]
officially, there is now just one left, kaso17, who is the owner/author of jackett.
However, he has not been contributing for quite some time now, stating that real life work challenges are keeping him too busy to make time.
Others in the original group just prior to my joining have left as well, or declared themselves unavailable to contribute.
So right now, we are totally dependant on any volunteer that contributes on a infrequent basis.

**Comment by lpearl** [comment]
@garfield69 Can you get banned from a tracker for using Jackett?

**Comment by garfield69** [comment]
There has never been a ticket opened that reported such a problem, but I have seen one instance where someone was in the middle of developing an indexer for a site, but then withdrew the PR because they said one of the moderators of the site objected.
In the event any site objects, we would of course, once notified, remove the offending indexer from Jackett.

**Comment by lpearl** [comment]
@garfield69 Ok so finished the indexing I have a few questions (noob question coming). Where do I start the server within Virtual studios to test and debug? Also is there another way you want me to communicate with you or just doing it this way is fine?

**Comment by lpearl** [comment]
@garfield69 

> It seams like its throwing an error (error at bottom) that I does not know but. I think it's because logged-in-username is diffrent then in rutracker. 
> `await ConfigureIfOK(result.Cookies, result.Content != null && result.Content.Contains("id=\"logged-in-username\""), () =>`
> 
> Does this code check if the user is logged in? Since logged-in-user does not exist on pornolab even when a user is logged in, what should be something it looks for instead of logged-in-user? 

EDIT
Fixed the login error by look for "logged in as". But of course there are more problems, the error code is below.

I also seem to keep getting `Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll` is this normal? Also is there another way you want me to content you for help or is this the best way?

Error code
`at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/lpearl/Projects/Jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 226
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /Users/lpearl/Projects/Jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 98
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask 1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/lpearl/Projects/Jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/lpearl/Projects/Jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 226
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /Users/lpearl/Projects/Jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 98
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask 1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/lpearl/Projects/Jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29`

**Comment by garfield69** [comment]
the best way to collaborate with github is if you raise a PR.
that tool will then allow me to view your code, provide feedback and even allow me to make adjustments.
as you change the source code the PR will reflect the updates.
I can then also test your code in parallel with yours to see if I get the same results, which will make diagnosing issue a little bit easier. ;-)

**Comment by lpearl** [comment]
@garfield69 Added a PR still not working but lmk what you find. Didn't add the readme because it's not working.
[https://github.com/Jackett/Jackett/pull/6465](url)

**Comment by garfield69** [comment]
try out jackett 0.12.1084

**Comment by garfield69** [comment]
https://pornolab.net/ returns 502 Bad Gateway or 522 Time out for some some regions

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
https://pornolab.net/forum/index.php - The forum is temporarily disabled

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://pornolab.net/ > TCP Connection Failed (Timed out)

**Comment by garfield69** [comment]
online
