### ISSUE TITLE
Demonoid failing

### ISSUE THREAD

**Issue by Xezuka** [Jackett/Jackett#450]
I noticed it was failing and went to reconfigure it, but after I removed it I can't add it back in. Seems there is an issue with scraping the site?

```
Error on 20160819150235 for Demonoid.txtSystem.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Jackett.Indexers.Demonoid.<PerformQuery>d__9.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\Demonoid.cs:line 121
```

**Comment by flightlevel** [comment]
https://github.com/Jackett/Jackett/issues/365
