### ISSUE TITLE
win10 source build netstandard2.0 issue?

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#4535]
@flightlevel  I am attempting to build jackett from source for my win 10 platform.
1. I have installed the latest .NET core 2.2 SDK
```
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Garfield69>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
2. and upgraded my visual studio community 2017 to 15.9.5
![image](https://user-images.githubusercontent.com/6933240/51700619-7bfd3e00-2074-11e9-9e44-082d54595f7f.png)
3. cloned jackett/jackett on my local github desktop
4. But when I Right click on the Jackett solution and click 'Rebuild Solution' to restore nuget packages, I get the following errors:
```
Error occurred while restoring NuGet packages: The operation failed as details for project Jackett.Server could not be loaded.
1>------ Rebuild All started: Project: DateTimeRoutines, Configuration: Release Any CPU ------
1>C:\Users\Garfield69\AppData\Local\Temp\.NETStandard,Version=v2.0.AssemblyAttributes.cs(4,20,4,26): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(14,12,14,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(15,12,15,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(16,12,16,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(17,12,17,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(18,12,18,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(19,12,19,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(20,12,20,18): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Garfield69\AppData\Local\Temp\.NETStandard,Version=v2.0.AssemblyAttributes.cs(4,71,4,98): error CS0518: Predefined type 'System.String' is not defined or imported
1>C:\Users\Garfield69\AppData\Local\Temp\.NETStandard,Version=v2.0.AssemblyAttributes.cs(4,100,4,120): error CS0246: The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Garfield69\AppData\Local\Temp\.NETStandard,Version=v2.0.AssemblyAttributes.cs(4,123,4,125): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(14,55,14,73): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(15,61,15,70): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(16,59,16,68): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(17,68,17,75): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(18,55,18,73): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(19,53,19,71): error CS0518: Predefined type 'System.String' is not defined or imported
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(20,55,20,64): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(9,7,9,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(10,7,10,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Garfield69\AppData\Local\Temp\.NETStandard,Version=v2.0.AssemblyAttributes.cs(2,7,2,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\Garfield69\AppData\Local\Temp\.NETStandard,Version=v2.0.AssemblyAttributes.cs(3,7,3,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(11,7,11,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>obj\Release\netstandard2.0\DateTimeRoutines.AssemblyInfo.cs(12,7,12,13): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(17,25,17,41): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(26,58,26,66): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(26,58,26,66): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(26,23,26,27): error CS0518: Predefined type 'System.UInt32' is not defined or imported
1>DateTimeRoutines.cs(26,53,26,57): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(134,23,134,31): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(134,23,134,31): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(136,13,140,14): error CS0518: Predefined type 'System.Void' is not defined or imported
1>DateTimeRoutines.cs(186,50,186,56): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(186,97,186,105): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(186,97,186,105): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(186,23,186,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(186,45,186,49): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(271,50,271,56): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(271,23,271,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(271,45,271,49): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(207,52,207,58): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(207,99,207,107): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(207,99,207,107): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(207,23,207,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(207,47,207,51): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(305,52,305,58): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(305,23,305,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(305,47,305,51): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(227,46,227,52): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(227,93,227,101): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(227,93,227,101): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(227,23,227,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(227,41,227,45): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(291,46,291,52): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(291,23,291,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(291,41,291,45): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(349,46,349,52): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(349,23,349,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(349,41,349,45): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(248,46,248,52): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(248,93,248,101): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(248,93,248,101): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(248,23,248,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(248,41,248,45): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(464,46,464,52): error CS0518: Predefined type 'System.String' is not defined or imported
1>DateTimeRoutines.cs(464,23,464,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(464,41,464,45): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?
1>DateTimeRoutines.cs(588,37,588,40): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(588,47,588,50): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(588,58,588,61): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(588,71,588,79): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(588,71,588,79): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(588,16,588,20): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(149,16,149,24): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(149,16,149,24): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(154,23,154,27): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(42,22,42,36): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(85,37,85,40): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(85,56,85,59): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(85,76,85,79): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(85,95,85,98): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(85,115,85,123): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(85,115,85,123): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(85,13,97,14): error CS0518: Predefined type 'System.Void' is not defined or imported
1>DateTimeRoutines.cs(99,37,99,40): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(99,56,99,59): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(99,76,99,79): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(99,95,99,98): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(99,115,99,123): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(99,115,99,123): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(99,135,99,143): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(99,135,99,143): error CS0246: The type or namespace name 'TimeSpan' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(99,13,125,14): error CS0518: Predefined type 'System.Void' is not defined or imported
1>DateTimeRoutines.cs(47,29,47,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(51,29,51,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(55,29,55,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(59,29,59,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>DateTimeRoutines.cs(63,29,63,37): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(63,29,63,37): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(67,29,67,33): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(71,29,71,33): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(75,29,75,37): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(75,29,75,37): error CS0246: The type or namespace name 'TimeSpan' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(79,29,79,33): error CS0518: Predefined type 'System.Boolean' is not defined or imported
1>DateTimeRoutines.cs(83,20,83,28): error CS0518: Predefined type 'System.Object' is not defined or imported
1>DateTimeRoutines.cs(83,20,83,28): error CS0246: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
1>DateTimeRoutines.cs(159,21,159,35): error CS0518: Predefined type 'System.Enum' is not defined or imported
1>DateTimeRoutines.cs(159,21,159,35): error CS0518: Predefined type 'System.Int32' is not defined or imported
1>Done building project "DateTimeRoutines.csproj" -- FAILED.
2>------ Rebuild All started: Project: Jackett.Common, Configuration: Release Any CPU ------
2>CSC : error CS0006: Metadata file 'C:\Users\Garfield69\Documents\GitHub\Jackett\src\DateTimeRoutines\bin\Release\netstandard2.0\DateTimeRoutines.dll' could not be found
2>Done building project "Jackett.Common.csproj" -- FAILED.
3>------ Rebuild All started: Project: Jackett.Server, Configuration: Release Any CPU ------
4>------ Rebuild All started: Project: Jackett.Service, Configuration: Release Any CPU ------
5>------ Rebuild All started: Project: Jackett.Tray, Configuration: Release Any CPU ------
6>------ Rebuild All started: Project: Jackett.Updater, Configuration: Release Any CPU ------
4>CSC : error CS0006: Metadata file 'C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\bin\Release\netstandard2.0\Jackett.Common.dll' could not be found
3>C:\Program Files\dotnet\sdk\2.2.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file 'C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Server\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
3>Done building project "Jackett.Server.csproj" -- FAILED.
6>C:\Program Files\dotnet\sdk\2.2.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file 'C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Updater\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
6>Done building project "Jackett.Updater.csproj" -- FAILED.
5>CSC : error CS0006: Metadata file 'C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\bin\Release\netstandard2.0\Jackett.Common.dll' could not be found
6>CSC : error CS0006: Metadata file 'C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\bin\Release\netstandard2.0\Jackett.Common.dll' could not be found
6>Done building project "Jackett.Updater.csproj" -- FAILED.
3>CSC : error CS0006: Metadata file 'C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\bin\Release\netstandard2.0\Jackett.Common.dll' could not be found
3>Done building project "Jackett.Server.csproj" -- FAILED.
7>------ Rebuild All started: Project: Jackett.Test, Configuration: Release Any CPU ------
7>C:\Program Files\dotnet\sdk\2.2.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file 'C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Test\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
7>Done building project "Jackett.Test.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 7 failed, 0 skipped ==========
```
looks like my NuGet setup is incorrect/icomplete?
Any help appreciated. Thanks.

**Comment by garfield69** [comment]
solved by navigating VS>tools>NuGet Package Manager>Packet Manager Console
and then using the `dotnet restore` command.
I'm still getting the first error, but the  rebuild seems to have completed successfully.
```
Error occurred while restoring NuGet packages: The operation failed as details for project Jackett.Server could not be loaded.
1>------ Build started: Project: DateTimeRoutines, Configuration: Release Any CPU ------
1>DateTimeRoutines -> C:\Users\Garfield69\Documents\GitHub\Jackett\src\DateTimeRoutines\bin\Release\netstandard2.0\DateTimeRoutines.dll
2>------ Build started: Project: Jackett.Common, Configuration: Release Any CPU ------
2>Jackett.Common -> C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\bin\Release\netstandard2.0\Jackett.Common.dll
3>------ Build started: Project: Jackett.Server, Configuration: Release Any CPU ------
4>------ Build started: Project: Jackett.Service, Configuration: Release Any CPU ------
5>------ Build started: Project: Jackett.Tray, Configuration: Release Any CPU ------
6>------ Build started: Project: Jackett.Updater, Configuration: Release Any CPU ------
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "System.Text.Encoding.CodePages" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
4>  Jackett.Service -> C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Service\bin\Release\JackettService.exe
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "System.Text.Encoding.CodePages" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
6>Jackett.Updater -> C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Updater\bin\Release\netcoreapp2.2\JackettUpdater.dll
6>Done building project "Jackett.Updater.csproj".
6>Jackett.Updater -> C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Updater\bin\Release\net461\JackettUpdater.exe
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "System.Text.Encoding.CodePages" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
5>  Jackett.Tray -> C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Tray\bin\Release\JackettTray.exe
3>Jackett.Server -> C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Server\bin\Release\net461\JackettConsole.exe
3>Jackett.Server -> C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Server\bin\Release\netcoreapp2.2\jackett.dll
7>------ Build started: Project: Jackett.Test, Configuration: Release Any CPU ------
7>Jackett.Test -> C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Test\bin\Release\net461\Jackett.Test.dll
========== Build: 7 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by garfield69** [comment]
should note however that the jackettconsole.exe and jackettupdater.exe are in the bin/release/net461 folder, while all the other exe and dll are in the bin/release/netcoreapp2.2

**Comment by garfield69** [comment]
urg. not working. the service wont start and running the jackettconsole crashes with
```
C:\Users\Garfield69>cd ../../programdata/jackett

C:\ProgramData\Jackett>jackettconsole -t -l
01-25 08:09:23 Info Starting Jackett v0.0.0.0
01-25 08:09:23 Info Logging enabled.
01-25 08:09:23 Info Tracing enabled.
01-25 08:09:23 Debug Creating web host...
01-25 08:09:23 Debug Content root path is: C:\ProgramData\Jackett\Content
01-25 08:09:23 Error System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
 System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].


Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

C:\ProgramData\Jackett>
```
but it can all wait until the jackett core22 package is officially released or you have free time/inclination to  look into this ;-)
