### ISSUE TITLE
Jackett doesn't restart after update: Error Autofac.Core.DependencyResolutionException

### ISSUE THREAD

**Issue by CptSandwich** [Jackett/Jackett#4651]
I've seen that Jackett's been down a couple of times, manually restarting the services seems to bring it back. This is the first time I've checked the log though. Latest occurrence seems to be after updating to v0.10.731, relevant section of log below.

2019-02-10 17:41:09.7758 Info New release found.  Current: v0.10.724 New: v0.10.731 
2019-02-10 17:41:26.0113 Info Starting updater: C:\Windows\TEMP\JackettUpdate-v0.10.731-636854172814016690\Jackett\JackettUpdater.exe --Path "C:\ProgramData\Jackett" --Type "WindowsService" --Args " " --KillPids "616" 
2019-02-10 17:41:26.0739 Info Updater started process id: 3208 
2019-02-10 17:41:26.0894 Info Signal sent to lock service 
2019-02-10 17:41:28.1211 Info Exiting Jackett.. 
2019-02-10 17:41:36.5276 Info Starting Jackett v0.10.731.0 
2019-02-10 17:41:39.2622 Error Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ServerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IServerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) ---> System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Jackett.Common.Utils.Clients.HttpWebClient.InitProxy(ServerConfig serverConfig)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args) Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ServerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IServerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IndexerManagerService (ReflectionActivator), Services = [Jackett.Common.Services.Interfaces.IIndexerManagerService], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = HttpWebClient (ReflectionActivator), Services = [Jackett.Common.Utils.Clients.WebClient], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient'. ---> One or more errors occurred. (See inner exception for details.) ---> System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Jackett.Common.Utils.Clients.HttpWebClient.InitProxy(ServerConfig serverConfig)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Jackett.Server.Helper.Initialize()
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)
2019-02-12 13:30:33.6171 Info Starting Jackett v0.10.731.0 
2019-02-12 13:30:33.8737 Info Initiating Jackett service stop 
2019-02-12 13:30:41.0924 Info Starting Jackett v0.10.731.0 
2019-02-12 13:30:41.2789 Info Initiating Jackett service start 
2019-02-12 13:30:41.9191 Info Starting Jackett v0.10.731.0 
2019-02-12 13:30:43.3878 Info Environment version: 4.0.30319.42000 (C:\Windows\Microsoft.NET\Framework\v4.0.30319\) 
2019-02-12 13:30:43.4078 Info OS version: Microsoft Windows NT 6.2.9200.0 (64bit OS) 
2019-02-12 13:30:43.4078 Info Jackett variant: FullFrameworkWindows 
2019-02-12 13:30:43.4078 Info ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads 
2019-02-12 13:30:43.4278 Info App config/log directory: C:\ProgramData\Jackett 
2019-02-12 13:30:43.4278 Info Using HTTP Client: HttpWebClient

**Comment by flightlevel** [comment]
@MrMetabolism please try uninstalling, check that there is no dlls left behind in c:/programdata/jackett
And then download a fresh copy of jackett and install, suspect there is a corrupt/missing file causing the issue

**Comment by MrMetabolism** [comment]
@flightlevel Thanks. I've uninstalled -> cleared the program data/jackett folder -> reinstalled 0.10.743.0. I'll let you know if the problem comes up again.

**Comment by MrMetabolism** [comment]
No good, @flightlevel

Updated and then failed to start again. Manually stopping/restarting the service hasn't helped this time either.

[log.txt](https://github.com/Jackett/Jackett/files/2868146/log.txt)

**Comment by flightlevel** [comment]
@MrMetabolism 
What antivirus are you using?
Can you upload the `updater.txt` log file as well

**Comment by MrMetabolism** [comment]
@flightlevel, kaspersky is installed but currently disabled.

[updater.txt](https://github.com/Jackett/Jackett/files/2871841/updater.txt)

**Comment by MrMetabolism** [comment]
Just an update to this. I'm still seeing the service fail to start occasionally. I don't think this is necessarily related to updates as even attempts to manually start the service often fail. Latest logs are attached. 

[log.txt](https://github.com/Jackett/Jackett/files/2902919/log.txt)
[Updater.txt](https://github.com/Jackett/Jackett/files/2902920/Updater.txt)

**Comment by garfield69** [comment]
looks similar to #4820 
are you using proxy settings, perhaps socks5?

**Comment by MrMetabolism** [comment]
Yeah, using socks5 proxy. I'll try some of the troubleshooting steps mentioned in #4820 and report back.

**Comment by garfield69** [comment]
Looks like setting a *delayed start* to the service has resolved the issue on 4820.

From your *control panel > administrative tools > Services* page, find *Jacket,* click on *Properties* and change the startup type drop box from *automatic* to **automatic delayed start**

**Comment by MrMetabolism** [comment]
I'm not sure this is the solution. I changed the setting as requested, however still ran into problems. The issue doesn't occur only when booting the system, instead (almost) every time the service is started. When I removed the socks5 proxy (as per #4820) the service started 4 out of 4 times.

I have attached the latest log file following the change to delayed start and then removing proxy.

**Comment by garfield69** [comment]
wondering if this may sort out your issue https://github.com/Jackett/Jackett/issues/5208#issuecomment-547709864

**Comment by ngosang** [comment]
@garfield69 close. old, related to the updater.
