### ISSUE TITLE
Jackett - linux AMD64 .NET - errors on trackers

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#4834]
Hi, I'm using the .net core version 0.10.911.0

I notice that there's a lot of error when I test the indexer, every time I got this:

Jackett.Common.IndexerException: Exception (yts): The operation was canceled. ---> ```
System.OperationCanceledException: The operation was canceled.
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers)
   at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query, Int32 attempts)
   at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query)
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query)
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query)
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name)
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```
Not all indexers but some have this error

Let me know if you need some more informations

Edit I got this information from dmesg
`jackett[23878]: segfault at 515c3e2 ip 00007f75ac2df132 sp 00007f70a149cab0 error 4 in libcoreclr.so[7f75ac1b1000+28d000]`

**Comment by flightlevel** [comment]
Is it always the same indexers? Or different ones?
Are you testing a single indexer or all of them?
What type of hardware is it running on?
Can you start Jackett with `./jackett -t -l` then reproduce and upload the log

**Comment by Jorman** [comment]
I'm not at home but is more than one indexer. Later I'll try to make a full
log for you. Usually I use the test all button, but I get the same result
when I try the single one.
Just for curiosity what do this command?
Do you also need one debug log from jackett?

Il dom 10 mar 2019, 02:44 flightlevel <notifications@github.com> ha scritto:

**Comment by Jorman** [comment]
Ok, so the indexer that give me error are:
1337x
HDTorrents.it (but this's for the seeders/leechers problem)
Il Corsaro Nero
LimeTorrents
Torrent Downloads
TorrentFunk
Torrentz2
YTS
Zooqle
This's the log with "Test All" button
https://ufile.io/qfihu

This's the log with manual test on faulty indexer, except for HDTorrents.it
https://ufile.io/e5m7d

Let me know if you need some more data

Jo

**Comment by Jorman** [comment]
I found the problem!!!

In my country all these indexers are blocked, and on my nas the vpn service was down ... so for this stupid reason all these indexers are down, I reactivated the vpn and now all working!

Sorry for the inconvenience!
