### ISSUE TITLE
[hdtorrentsit] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#4960]
Hi I just tried hdtorrents, the site is up but the test don't works.

Any idea?
Here the log:
```
Mar 24 22:54:42 Qnap jackett[24315]: 03-24 22:54:42 Info Found 0 releases from HDTorrents.it
Mar 24 22:54:42 Qnap jackett[24315]: 03-24 22:54:42 Error System.Exception: Found no results while trying to browse this tracker
Mar 24 22:54:42 Qnap jackett[24315]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
Mar 24 22:54:42 Qnap jackett[24315]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Mar 24 22:54:42 Qnap jackett[24315]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 System.Exception: Found no results while trying to browse this tracker
Mar 24 22:54:42 Qnap jackett[24315]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
Mar 24 22:54:42 Qnap jackett[24315]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mar 24 22:54:42 Qnap jackett[24315]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Mar 24 22:54:42 Qnap jackett[24315]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```

**Comment by garfield69** [comment]
need to see the html dump that precedes the stack trace, so please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by Jorman** [comment]
Ok! I just tried and now works without error, maybe some temporary traker issue?

For now is closed, if happen again I'll attach the full log.

For now thanks
