### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Invalid URI: The hostname could not be parsed.: Invalid URI: The hostname could not be parsed. (Test)

### ISSUE THREAD

**Issue by welcoMattic** [Jackett/Jackett#5035]
I have issue with yggtorrent.gg tracker, here is the log :

```Jackett.Common.IndexerException: Exception (yggtorrent): Invalid URI: The hostname could not be parsed. ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri.CreateUri(Uri baseUri, String relativeUri, Boolean dontEscape)
   at System.Uri..ctor(Uri baseUri, String relativeUri)
   at Jackett.Common.Indexers.CardigannIndexer.resolvePath(String path, Uri currentUrl) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1092
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1168
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29```

I tried to login manually, everything works correctly. The ID of the login form is still the same. The domain name too. 

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.11.185.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: ? (jackett docker image from linuxserver.io)

-------------------------------

**Comment by welcoMattic** [comment]
It's a REAL issue, all others issues with the same problem were closed :thinking:

**Comment by garfield69** [comment]
on your Jackett dashboard, use the **wrench** icon to edit the *yggtorrent* config,
and carefully check that the **Site Link** is `https://www.yggtorrent.gg/` and that the **Search and download** URL is `www2.yggtorrent.gg` and click **OKAY**.
If you get an error, click **CLOSE** then edit and click **OKAY** once more.
if you are still seeing this *invalid URI* error after this, then provide a screenshot of your yggtorrent config, and a **complete** enhanced log (not just the stack trace) so we can dig deeper.

**Comment by welcoMattic** [comment]
It works. But it's a very strange behaviour. Not very clear for user. Need UX improvement.

**Comment by garfield69** [comment]
it's down to the peculiar way the site has split their server across a couple domain names. no other site does this.
