### ISSUE TITLE
Cannot add iptorrents (possible duplicate issue?) Jackett Version 0.11.183.0

### ISSUE THREAD

**Issue by Pedrostan** [Jackett/Jackett#5036]
Hi all.

As above please, when clicking at wrench I have this error:
![image](https://user-images.githubusercontent.com/49131092/55675225-41efba00-58b7-11e9-8744-609f10e0de95.png)

plus below log:

System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudFlareUtilities.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClientNetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs:line 222
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
   at Jackett.Common.Indexers.IPTorrents.GetConfigurationForSetup() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 147
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

Please help if possible, 

Thanks a lot.

**Comment by garfield69** [comment]
jackett version?
platform?
can you access iptorrents via browser?
what address are you using for iptorrents on the browser?
is it the same as the sitelink on the iptorrents config?
are you using a vpn or proxy options?

**Comment by Pedrostan** [comment]
Sorry for missing info.

Jackett Version 0.11.183.0
Synology via docker
I believe Iptorrents.com is a sitelink for Jackett
I can access it on my browser through VPN ( Synology is also under same VPN server )

**Comment by garfield69** [comment]
from a terminal connected to your jackett docker please post the output of 
`curl -vvv https://iptorrents.com/`
and 
`openssl s_client -connect iptorrents.com:443`
thanks.

**Comment by Pedrostan** [comment]
Thanks so much for your time and effort.
I don't really understand how to but I'll Google it
:) Thanks a lot

**Comment by Pedrostan** [comment]
http://phase2.github.io/devtools/common-tasks/ssh-into-a-container/

I believe this would be it, right?

Thanks

**Comment by garfield69** [comment]
Yes, from a terminal run `docker exec -it jackett /bin/bash` replace `jackett` with whatever you called your Jackett container. You now have bash access to container
then run the two other commands. ;-)

**Comment by Pedrostan** [comment]
![Screenshot_20190407-004554__01](https://user-images.githubusercontent.com/49131092/55676516-b08c4200-58ce-11e9-8991-585c7a0af20e.jpg)
I think I've got it. Will come back to you tomorrow with the results of your magic results.
Thanks again

**Comment by Pedrostan** [comment]
Hi again...
Unfortunately no joy with the terminal:

![image](https://user-images.githubusercontent.com/49131092/55688741-1252b780-5974-11e9-8f8c-e6527a66ab6b.png)

I've hidden the numbers as I'm not sure it will open up my security, please let me know if not and you need the numbers.

Thanks again

**Comment by garfield69** [comment]
yes this definitely confirms that you have a problem with your docker container.
@kaso17  @flightlevel  any ideas where to go from here?

**Comment by flightlevel** [comment]
Not sure, I'd try the synology forum. Its got nothing to do with Jackett, looks like the container has either no internet access or no DNS

**Comment by Pedrostan** [comment]
Little update:

I've reinstalled the Jackett, initially I was able to add IPtorrents with cookie check, tested ok.
Second later it failed test ( unfortunately I forgot to take logs from that )
Thinking about no internet or DNS, I'm able to add bunch of other public indexers without any problems ( not all indexers )
![image](https://user-images.githubusercontent.com/49131092/55760469-16ee9d00-5a54-11e9-9ec5-58237a81294b.png)
