### ISSUE TITLE
[1337x] Exception (1337x): No route to host: No route to host (Test)

### ISSUE THREAD

**Issue by Pedrostan** [Jackett/Jackett#5061]
Hi again.

Sorry to bother but after few days of googling I'm nowhere with my issue.

Previous ticket #5036 was closed sending me to Synology community but I have new info.
I'm still having same problem as per ticket #5036 but I'm able to add other sites to indexers:

![image](https://user-images.githubusercontent.com/49131092/55995604-db024480-5cac-11e9-94b7-746f18dc5448.png)

Would it be possible if Jackett had no internet access?
Honestly I don't know where to go from here... Please help.

P.S
There was an instance where IPtorrents was added and worked but after second test same problem repeater.

**Comment by Pedrostan** [comment]
Quick update: 1337x passed the test, I'm attaching logs of failure and pass just minutes later:

Jackett.Common.IndexerException: Exception (1337x): No route to host ---> System.Net.Http.HttpRequestException: No route to host ---> System.Net.Sockets.SocketException: No route to host
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudFlareUtilities.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClientNetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClientNetCore.cs:line 222
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1229
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

...8 minutes later ( no setting change ):

![image](https://user-images.githubusercontent.com/49131092/55995916-c2def500-5cad-11e9-82bb-0a7e591a9813.png)

**Comment by Pedrostan** [comment]
Another update, failures this time ( no settings change, few minutes later ):
Added no issues:
![image](https://user-images.githubusercontent.com/49131092/55996200-9c6d8980-5cae-11e9-90d2-7e23157eef34.png)
Test failure:
![image](https://user-images.githubusercontent.com/49131092/55996242-b5763a80-5cae-11e9-8efd-a052ceefcded.png)
![image](https://user-images.githubusercontent.com/49131092/55996279-d63e9000-5cae-11e9-90ea-fc8787916c55.png)

Why this would be so random without any setting change?

Thanks a lot for your time

**Comment by garfield69** [comment]
i'm not sure that we can help you.

I suspect you are having an intermittent network issue of some kind.
I do not believe that jackett would randomly stop working like this, such that you can access a site one moment and then not the next.
This smacks of a network card hardware issue, or a router issue, or a broadband dropout erorr or some other ISP issue.

perhaps google `intermittent no route to host` and see if that leads you to any solutions.

@kaso17  @flightlevel  any suggestions?

**Comment by Pedrostan** [comment]
Thanks.
The reason why I'm stubborn is as everything works well, nzbget, sonarr, radarr etc.

Only Jackett gives me problems.

**Comment by kaso17** [comment]
It's definitely a network connectivity issue unrelated to jackett.
