### ISSUE TITLE
[morethantv] Exception (morethantv): Object reference not set to an instance of an object: Parse error (Test)

### ISSUE THREAD

**Issue by stephenjmcmahon** [Jackett/Jackett#5110]
EDIT: Believe to be site issues not related to Jackett

**Comment by EvanGrote** [comment]
Also seeing this issue.

[logs.txt](https://github.com/Jackett/Jackett/files/3101688/logs.txt)

Stacktrace:
```
Jackett.Common.IndexerException: Exception (morethantv): Object reference not set to an instance of an object. ---> System.Exception: Parse error ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.MoreThanTV.GetReleases(ICollection`1 releases, TorznabQuery query, String searchQuery) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MoreThanTV.cs:line 191
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 842
   at Jackett.Common.Indexers.MoreThanTV.GetReleases(ICollection`1 releases, TorznabQuery query, String searchQuery) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MoreThanTV.cs:line 217
   at Jackett.Common.Indexers.MoreThanTV.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MoreThanTV.cs:line 85
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```

**Comment by EvanGrote** [comment]
This may be a morethan.tv server issue? When attempting to view the "Torrents" page, clicking on any of the links brings me to a page saying "Something was wrong with your request, and the server is refusing to fulfill it."

I'm gonna make a post about it on the Bug Reports forum of MTV

**Comment by EvanGrote** [comment]
MTV Forum Post: https://www.morethan.tv/forums.php?action=viewthread&threadid=2071

**Comment by fontes31** [comment]
on radarr it works, on sonarr not working. Iam having the same problem
