### ISSUE TITLE
Found no results while trying to browse this tracker. IPTorrents

### ISSUE THREAD

**Issue by globier** [Jackett/Jackett#5164]
Just setting up today for the first time. 

Was able to add the indexer and test completed, however since the initial add the test fails.

[log.txt](https://github.com/Jackett/Jackett/files/3134247/log.txt)
Running on Windows 10
Jackett version:  0.11.259.0

Other public indexers work fine

Login to IPT works fine

**Comment by digitalgp** [comment]
Have suddenly the same error... been working fine for months without touching it. Only upgraded to latest jackett

**Comment by zakstack** [comment]
I've been trying to get another api wrapper to work with iptorrents and it also is having search issues. I think something might have changes on ipTorrents side.

**Comment by lordraiden** [comment]
Any update on this?
It was working then stoped working for some reason, I delete it to add it again and now when I click on add nothing happens

`System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
   at Jackett.Common.Indexers.IPTorrents.GetConfigurationForSetup() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 147
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29`

**Comment by zakstack** [comment]
Once again don't know if this helps but I was having trouble getting responses back from iptorrent api for 2 days and then all of a sudden it started working again. The only change I made in the api wrapper I was using (not jackett) was updating the base url from iptorrents.eu to iptorrents.com. Other than that give it a couple days and try again I suspect they are just updating some stuff on iptorrents api end.

**Comment by lordraiden** [comment]
Now I can't even configure IPtorrent, if I try to add it, it does nothing.
Is there a fix for this?

**Comment by ngosang** [comment]
@globier maybe this help https://github.com/Jackett/Jackett/issues/6446#issuecomment-560093162

**Comment by garfield69** [comment]
Jackett 0.12.1746
