### ISSUE TITLE
[beyondhd] New website with different login mechanism

### ISSUE THREAD

**Issue by 4everfun** [Jackett/Jackett#5218]
It seems like BeyondHD updated to UNIT3D and removed the option for an URL login. 

I'm willing to help with this problem if needed.

**Comment by suneetk92** [comment]
Yes please.

**Comment by zotanw** [comment]
almost done with a preliminary .yml config

**Comment by b101marc** [comment]
Hey all, just checking in to see if any update was done.

**Comment by garfield69** [comment]
upgrade to jackett pre-release v0.11.307 to pick up new indexer definition.
but you might as well hold off, the site is going though a few teething problems, I'm seeing internal server errors when browsing torrents at the moment.

**Comment by garfield69** [comment]
update to jackett pre-release v0.11.308 for a working indexer.
note: downloading is untested.

**Comment by ZEEN0j** [comment]
I’ve successfully added beyondHD to jackett. But when testing it I get “Found no results while trying to browse this tracker”. A

**Comment by garfield69** [comment]
update to 0.11.308
![image](https://user-images.githubusercontent.com/6933240/57435298-1fbfd200-7291-11e9-850e-0f5cd77804fa.png)

**Comment by 4everfun** [comment]
I'm also getting an error while testing the tracker or manually searching. I'm on Jackett Version 0.11.308.0

```
CardigannIndexer (beyond-hd): Error while parsing row '
<tr>
	<td class="font-small text-center">
		<a href="https://beyond-hd.me/categories/tv.2">
			<div class="text-center font-small">
				<i class="fal fa-tv-retro torrent-icon font-large" data-toggle="tooltip" data-original-title="TV Torrent" style="padding-bottom: 6px;">
				</i>
			</div>
		</a>
	</td>
	<td class="font-small text-left">
		<div style="padding-bottom: 5px;">
			<a class="text-bold font-medium torrent-name" style="word-break: normal; color: #d3d3d3 !important;" href="https://beyond-hd.me/torrents/doompatrols01e101080pwebripx264-metcon.18362">
				Doom.Patrol.S01E10.1080p.WEBRip.X264-METCON
			</a>
		</div>
		<span class="badge-extra text-bold font-stat" style="color:#1E6E6C; background-image:none;">
			<i class="fal fa-upload" data-toggle="tooltip" data-original-title="Uploaded By"></i>
			<a class="font-stat" style="color:#1E6E6C; background-image:none;" href="https://beyond-hd.me/bhdbot.10224">
				bhdbot
			</a>
		</span>
		<span class="badge-extra text-bold text-pink font-stat">
			<i class="fal fa-heart" data-toggle="tooltip" data-original-title="Thanks Given"></i>
			2
		</span>
		<span class="badge-extra text-bold text-green font-stat">
			<i class="fal fa-comment" data-toggle="tooltip" data-original-title="Comments Left"></i>
			0
		</span>
	</td>
	<td class="font-small">
		<a href="https://beyond-hd.me/download/doompatrols01e101080pwebripx264-metcon.18362">
			<button class="bhd-round-form" type="button" data-toggle="tooltip" data-original-title="Download Torrent">
				<i class="fal fa-download"></i>
			</button>
		</a>
	</td>
	<td class="font-small text-center">
		<span data-toggle="tooltip" data-original-title="Bookmark Torrent" custom="newTorrentBookmark18362" id="newTorrentBookmark18362" torrent="18362" state="0" class="torrentBookmark"></span>
	</td>
	<td class="font-small text-center">
		<span class="text-orange font-small">11 hours</span>
	</td>
	<td class="font-small text-center">
		<span class="text-blue font-small">2.16 GiB</span>
	</td>
	<td class="font-small text-center">
		<a href="https://beyond-hd.me/torrents/doompatrols01e101080pwebripx264-metcon.18362/peers">
			<span class="text-green text-bold font-small">2</span>
		</a>
	</td>
	<td class="font-small text-center">
		<a href="https://beyond-hd.me/torrents/doompatrols01e101080pwebripx264-metcon.18362/peers">
			<span class="text-red text-bold font-small">0</span>
		</a>
	</td>
	<td class="font-small text-center">
		<a href="https://beyond-hd.me/torrents/doompatrols01e101080pwebripx264-metcon.18362/history">
			<span class="text-orange text-bold font-small">1</span>
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=td:nth-child(6), value=<null>: TimeAgo parsing failed, unknown unit: gib
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1480
```

**Comment by garfield69** [comment]
Ah I see, you don't have posters in your lists.
edit your settings and set the **show posters** in the **torrent** section to **yes**.

I'll add an info-note to the indexer profile in the next release.

**Comment by 4everfun** [comment]
That seemed to do it, thanks!

**Comment by CaptainMoody** [comment]
Confirmed - Setting posters to yes solves the issue.
Thanks!

**Comment by ZEEN0j** [comment]
Where do you set posters to yes?

**Comment by CaptainMoody** [comment]
@ZEEN0j Click on MySettings and it is at the bottom of the first page

**Comment by ZEEN0j** [comment]
@CaptainMoody That's what I can't find. I'm at the Jackett dashboard where you add indexers. Can't find settings anywhere. Excuse my noob questions

**Comment by b101marc** [comment]
+1 for the above question.

**Comment by b101marc** [comment]
Still having issues, not accepting cookies. 

System.Exception: Found no results while trying to browse this tracker
  at Jackett.Common.Services.IndexerManagerService+<TestIndexer>d__18.MoveNext () [0x000e8] in <749bda9c45fb44bfb31b92dd6c8bf241>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Jackett.Server.Controllers.IndexerApiController+<Test>d__15.MoveNext () [0x000e1] in <64ee87dbc21c4267afd788bfaa85f40b>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor+<Execute>d__0.MoveNext () [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__13.MoveNext () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__23.MoveNext () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__18.MoveNext () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__16.MoveNext () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext () [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware+<Invoke>d__7.MoveNext () [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <a6f810169ec746eeb2789b925e2858c0>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler+<Invoke>d__3.MoveNext () [0x0008a] in <64ee87dbc21c4267afd788bfaa85f40b>:0

**Comment by 4everfun** [comment]
![image](https://user-images.githubusercontent.com/22298631/57481243-f6f40880-72a1-11e9-92e0-f4ae9fba8275.png)

![image](https://user-images.githubusercontent.com/22298631/57481265-02473400-72a2-11e9-8306-83b5c98ee4fa.png)

It's a setting on the Beyond-HD website.

**Comment by garfield69** [comment]
with Jackett pre-release v0.11.310 you are no longer required to change the poster setting.
it  should work with posters set to yes or no.

**Comment by ghaynes27** [comment]
where do i find the full cookie header?

**Comment by mikedm139** [comment]
Support for login via "One URL (OID)" is live now on the site. Finding and copying cookies for Jackett should no longer be required.
Find the One URL under "Settings > Security > One URL (OID)"

**Comment by suneetk92** [comment]
with Jackett v0.11.316.0 


```
System.Exception: Error while parsing field=leechers, selector=td:nth-last-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1480
2019-05-11 08:17:27.8316 Error CardigannIndexer (beyond-hd): Error while parsing row '
<tr>
        <td>
                <div class="torrent-poster pull-left">
                </div>
        </td>
        <td class="font-small text-center">
                <a href="https://beyond-hd.me/categories/movies.1">
                        <div class="text-center font-small">
                                <i class="fal fa-film torrent-icon font-large" data-toggle="tooltip" data-original-title="Movies Torrent" style="padding-bottom: 6px;">
                                </i>
                        </div>
                </a>
                <div style="padding-top: 3px; margin-top: 3px; border-top: 1px solid #333333;">
                        <span class="badge-null text-bold" style="font-size: 13px;">
                                <a href="/torrents?framestor=1" style="color: #cccccc;">
                                        <i class="fal fa-shield-check" data-toggle="tooltip" title="" data-original-title="FraMeSToR Quality Seal" style="color: #9932cc"></i>
                                </a>
                        </span>
                </div>
        </td>
        <td class="font-small text-left">
                <div style="padding-bottom: 5px;">
                        <a class="text-bold font-medium torrent-name" style="word-break: normal; color: #d3d3d3 !important;" href="https://beyond-hd.me/torrents/hello-my-name-is-doris-2015-bluray-1080p-dts-hd-ma-5-1-avc-remux-framestor.4346">
                                Hello My Name is Doris 2015 BluRay 1080p DTS-HD MA 5.1 AVC REMUX-FraMeSToR
                        </a>
                </div>
                <span class="badge-extra text-bold font-stat" style="color:#01ffff; background-image:none;">
                        <i class="fal fa-upload" data-toggle="tooltip" data-original-title="Uploaded By"></i>
                        <a class="font-stat" style="color:#01ffff; background-image:none;" href="https://beyond-hd.me/stRAf3r.249">
                                stRAf3r
                        </a>
                </span>
                <span class="badge-extra text-bold text-pink font-stat">
                        <i class="fal fa-heart" data-toggle="tooltip" data-original-title="Thanks Given"></i>
                        0
                </span>
                <span class="badge-extra text-bold text-green font-stat">
                        <i class="fal fa-comment" data-toggle="tooltip" data-original-title="Comments Left"></i>
                        5
                </span>
                <span class="badge-extra text-bold font-stat">
                        <i class="fal fa-shield-check" data-toggle="tooltip" title="" data-original-title="FraMeSToR Quality Seal" style="color: #9932cc"></i>
                        <a href="/torrents?framestor=1" style="color: #cccccc;">FraMeSToR</a>
                </span>
        </td>
        <td class="font-small">
                <a href="https://beyond-hd.me/download/hello-my-name-is-doris-2015-bluray-1080p-dts-hd-ma-5-1-avc-remux-framestor.4346">
                        <button class="bhd-round-form" type="button" data-toggle="tooltip" data-original-title="Download Torrent">
                                <i class="fal fa-download"></i>
                        </button>
                </a>
        </td>
        <td class="font-small text-center">
                <span data-toggle="tooltip" data-original-title="Bookmark Torrent" custom="newTorrentBookmark4346" id="newTorrentBookmark4346" torrent="4346" state="0" class="torrentBookmark"></span>
        </td>
        <td class="font-small text-center">
                <span class="text-orange font-small">2 years</span>
        </td>
        <td class="font-small text-center">
                <span class="text-blue font-small">19.2 GiB</span>
        </td>
        <td class="font-small text-center">
                <a href="https://beyond-hd.me/torrents/hello-my-name-is-doris-2015-bluray-1080p-dts-hd-ma-5-1-avc-remux-framestor.4346/peers">
                        <span class="text-green text-bold font-small">1</span>
                </a>
        </td>
        <td class="font-small text-center">
                <a href="https://beyond-hd.me/torrents/hello-my-name-is-doris-2015-bluray-1080p-dts-hd-ma-5-1-avc-remux-framestor.4346/peers">
                        <span class="text-red text-bold font-small">0</span>
                </a>
        </td>
        <td class="font-small text-center">
                <a href="https://beyond-hd.me/torrents/hello-my-name-is-doris-2015-bluray-1080p-dts-hd-ma-5-1-avc-remux-framestor.4346/history">
                        <span class="text-orange text-bold font-small">15</span>
                </a>
        </td>
        <td></td>
        <td>
                <i class="fal fa-times" title="Not Snatched" style="font-size: 12px; font-weight: bold; color: #555555;"></i>
        </td>
</tr>':

System.Exception: Error while parsing field=leechers, selector=td:nth-last-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1480
```

**Comment by garfield69** [comment]
beyond-hd is going through rapid changes recently, which makes it difficult to keep up.
so expect this indexer to break frequently until they settle down  to a comfortable layout.
please report failures here and I will try to keep on top of it with updates as I get informed.

I note that the login panel is back to normal so you can start using your username and password on the Jackett indexer config to login, instead of cookies. 

There is no plans to support **OID** at this stage, I suspect it would require the c# devs to add supporting code to the cardigann processor, because as far as I know, its not in use for any of the indexers that Jackett currently  supports.

Try Jackett pre-release 0.11.320 for the latest layout changes as of this post date/time..

**Comment by mikedm139** [comment]
> beyond-hd is going through rapid changes recently, which makes it difficult to keep up.
We all appreciate your efforts to keep Jackett playing nice with the rapidly changing BHD landscape. Thanks.

 
> I note that the login panel is back to normal so you can start using your username and password on the Jackett indexer config to login, instead of cookies.
> 
> There is no plans to support **OID** at this stage, I suspect it would require the c# devs to add supporting code to the cardigann processor, because as far as I know, its not in use for any of the indexers that Jackett currently supports.

I'm fine with user/pass authentication, I assumed that the OID mechanic would be similar in application to the previous "login url" that was being used for BHD. Thanks again for your efforts.

**Comment by takmanpanos** [comment]
can someone help me please? i try to to connect to beyond-hd but it say file not found.

**Comment by garfield69** [comment]
@takmanpanos  working for me.
Please provide the **full enhanced log** file so we can take a look at the details.
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by takmanpanos** [comment]
> 1. Jackett Dashboard

sorry but what is Jackett Dashboard and where can i find it? give me more details becouse i dont know much please!

**Comment by garfield69** [comment]
the jackett dashboard is what we call the main page of the jackett gui. the one you get when you type http://127.0.0.1:9117/UI/Dashboard in your browser address bar, assuming you have a standard jackett installation.

**Comment by takmanpanos** [comment]
> the jackett dashboard is what we call the main page of the jackett gui. the one you get when you type http://127.0.0.1:9117/UI/Dashboard in your browser address bar, assuming you have a standard jackett installation.

am i forced to use jackett to get the job done or is there another way  around this?
