### ISSUE TITLE
[yts] Connection refused: Connection refused (Config)

### ISSUE THREAD

**Issue by jcatarino** [Jackett/Jackett#5256]
yts is not working. Yts is a great website i would love if it would be possible to fix it. Thanks 

https://yts.am/

**Comment by garfield69** [comment]
works for me
![image](https://user-images.githubusercontent.com/6933240/57588795-f42d3800-756d-11e9-8398-2138da899541.png)
the problem is at your end.
platform? jackett version? enhanced log?

**Comment by jcatarino** [comment]
I'm using docker, jackett version 0.11.156.0.
Could you please share the screenshot of the config of YTS?

The logs says this:

System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 465
   at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 115
   at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 71
   at Jackett.Common.Indexers.Yts.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/yts.cs:line 59
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

**Comment by garfield69** [comment]
ok lets try this:
1. start a terminal and connect to your Jackett docker `docker exec -it jackett /bin/bash` (replace _jackett_ with whatever you called your Jackett container).
2. then post the output of `curl -vvv https://yts.am/api/v2/list_movies.json`

**Comment by jcatarino** [comment]
root@linuxserver-jackett1:/# curl -vvv https://yts.am/api/v2/list_movies.json                                    
*   Trying 213.13.145.120...                                                                                     
* TCP_NODELAY set                                                                                                
* connect to 213.13.145.120 port 443 failed: Connection refused                                                  
* Failed to connect to yts.am port 443: Connection refused                                                       
* Closing connection 0                                                                                           
curl: (7) Failed to connect to yts.am port 443: Connection refused

**Comment by garfield69** [comment]
you are being blocked by your ISP
![image](https://user-images.githubusercontent.com/6933240/57812466-49ad5300-77c1-11e9-8386-bf4c47cc4b76.png)


consider switching DNS by going to cloudflare's 1.1.1.1 https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/ or googles 8.8.8.8 https://developers.google.com/speed/public-dns/docs/using

or use a VPN

**Comment by jcatarino** [comment]
thanks
