### ISSUE TITLE
[cztorrent] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by xpokor02** [Jackett/Jackett#5299]
Hi,
Jackett Version 0.11.349.0
Unfortunately login with cookie doesn't seem to work.
Thanks

**Comment by garfield69** [comment]
works for me.
perhaps you need to trashbin your config and try again from scratch?

**Comment by xpokor02** [comment]
Hi,
I just installed Jackett it should be fresh.
when I add CZtracker it asks for cookie

I enter (changed first 3 letters to xxx)
`TestCookie=ok; level=3; __cfduid=xxx472ac267999f5c69609681b8cadf041558427812; __utma=xxx21768.31902425.1490727300.1515140778.1558427817.4; __utmc=xxx21768; __utmz=xxx21768.1558427817.4.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); __utmt=1; request_uri=%2Flogin-page%3Ferror%3D%25C5%25A0patn%25C3%25A9%2Bheslo%26username%3Dxpokor02%26url%3D%252F; pass=xxx3847b83cc7c077b5dc97e6c618068; uid=xxx802; __utmb=xxx21768.4.10.1558427817`

I get this error

```
Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 699
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 870
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```
Thanks

**Comment by garfield69** [comment]
the cookie string you want is from the **Headers** tab, not the _Cookies_ tab.
scroll down the Headers tab and you will see the **Cookie:** string in the **Request Headers** subsection.

**Comment by xpokor02** [comment]
Hi ,
that is exactly what I did.
![image](https://user-images.githubusercontent.com/15877056/58082603-a0e36700-7bb7-11e9-8f75-45e72596c7c5.png)

**Comment by garfield69** [comment]
it does not look right.
a good cookie from this site should look like this:
```
__cfduid=de21****redacted****799; TestCookie=ok; level=2; request_uri=%2Flogin-page%3Furl%3D%252F; pass=d****redacted****b; uid=1*****2
```
so you start with the loging page and press F12 and F5
then solve  the challenge and enter the username and password and login.
the very next page is the sites home page and this is where you get your cookie from.

**Comment by xpokor02** [comment]
I tried a few times but my cookie never looks like yours, it is always longer and in a different order.
I just realized that cookie I am collecting is from my laptop but entering it into Jackett running in Google cloud.
Isn't possible that this cause that redirect?

**Comment by garfield69** [comment]
In general I believe cookies work best when they are from the same computer that the app that is using them is on, and for some sites, even the same ip address (I'm aware for instance on one site that refuses cookies because the vpn allocates a different ip address each time a session is started).
are you using jackett in some kind of headless server , that you cannot start a browser and capture the cookie in the same system that runs jackett?

**Comment by xpokor02** [comment]
Yes, I started to use google cloud platform with free instance.
Maybe there is way to run gui and login and copy cookie I just do not see it yet.
But all hw I use for downloading/watching is headless in the way that there is no standard GUI just web-based one or kodi on raspberry connected to TV.
What is the point of automatization if it has to run on PC with a monitor connected.
Thanks

**Comment by garfield69** [comment]
@kaso17  your input welcome on this ticket. I'm out of ideas.

**Comment by Marekkon5** [comment]
Having same issue. My cookie looks like this:
`__cfduid=d***6; TestCookie=ok; level=5; request_uri=%2Flogin-page%3Furl%3D%252F; pass=1***6; uid=***`
Thanks

**Comment by Melliki** [comment]
I have the same issue 
`__cfduid=d73**redacted**98; TestCookie=ok; request_uri=%2F; __utma=58721768.18**redacted**4.1561365300.1567751672.15**redacted**33.72; __utmz=587**redacted**5300.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); pass=d5bfb**redacted**660810; level=3; torrents=1562134220; __utmc=58721768; uid=12**redacted**00; sess_id=mce1i8m-2y3c8_0orlhs; __utmb=58721768.1.10.1567754633; __utmt=1`
