### ISSUE TITLE
[awesomehd] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by Cringely** [Jackett/Jackett#5374]
Hello, I'm unable to use Awesome-HD, could this be due having 2FA enabled? Find a truncate log file and error message below. Thanks.

Error:
Login Failed, got redirected.

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.11.384.0
[log.txt](https://github.com/Jackett/Jackett/files/3237815/log.txt)

-------------------------------

Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 699
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 870
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

**Comment by garfield69** [comment]
Jackett does not support 2FA, so if you have enabled this then you are not going to to able to login with jackett.

**Comment by Cringely** [comment]
Previously AHD used a cookie string which worked fine, however I do not have that option anymore. After [this commit](https://github.com/Jackett/Jackett/commit/a82c166b237e994b7c36cca2c9cb7b33b4f9c1a2#diff-a257af76be70151df195ee72b97dd36e) that's no longer available to me. Do I need to revert to an older version to restore functionality?

**Comment by garfield69** [comment]
it might be better in your case to implement a custom copy of the awsome-hd indexer, so that you can continue to use the hard-coded cookie, but not miss out on updates to other jackett features and indexers.

save this file to your jackett definitions folder, and rename it to ahd2.yml and restart jackett.
[ahd2.yml.txt](https://github.com/Jackett/Jackett/files/3238389/ahd2.yml.txt)
it's the previous version of awsome-hd.yml that used cookie login, but with a custom name so it will not get replaced by jackett updates.
after restarting jackett, add ahd2 to your active indexer and you should be good to go.

**Comment by Cringely** [comment]
Thanks for the help, this appears to be working as intended now.
