### ISSUE TITLE
[kickasstorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by kaysond** [Jackett/Jackett#5433]
Looks like katr.co is returning 400's for some reason

```
2019-06-08 00:12:02.4796 Info Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/kickasstorrent/test  0
2019-06-08 00:12:02.4796 Debug Request is continuing in applying rules. Current url is 
2019-06-08 00:12:02.4796 Debug Request is continuing in applying rules. Current url is 
2019-06-08 00:12:02.4796 Debug Request is continuing in applying rules. Current url is 
2019-06-08 00:12:02.4796 Debug POST requests are not supported
2019-06-08 00:12:02.4796 Debug AuthenticationScheme: Cookies was successfully authenticated.
2019-06-08 00:12:02.4796 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerid}/Test'
2019-06-08 00:12:02.4796 Info Route matched with {action = "Test", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)
2019-06-08 00:12:02.4796 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2019-06-08 00:12:02.4796 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
2019-06-08 00:12:02.4826 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2019-06-08 00:12:02.4826 Debug Execution plan of exception filters (in the following order): None
2019-06-08 00:12:02.4826 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
2019-06-08 00:12:02.4826 Info Authorization was successful.
2019-06-08 00:12:02.4826 Info Executing action method Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) - Validation state: Valid
2019-06-08 00:12:02.4826 Debug WebClient(HttpWebClient).GetString(Url:https://katcr.co/category/latest/page/1)
2019-06-08 00:12:03.5242 Debug WebClient(HttpWebClient): Returning BadRequest => <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
<hr>
<address>Apache/2.4.10 Server at katcr.co Port 443</address>
</body></html>

2019-06-08 00:12:03.5242 Info Found 0 releases from KickAssTorrent
2019-06-08 00:12:03.5275 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 1044.1904ms
2019-06-08 00:12:03.5275 Error System.Exception: Found no results while trying to browse this tracker
  at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000e8] in <71a85329032d4de6b58d8b1f70f9fc66>:0
  at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in <05c66b039e7248bc8a60cf6de1719012>:0
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <05c66b039e7248bc8a60cf6de1719012>:0  System.Exception: Found no results while trying to browse this tracker
  at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000e8] in <71a85329032d4de6b58d8b1f70f9fc66>:0
  at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in <05c66b039e7248bc8a60cf6de1719012>:0
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <05c66b039e7248bc8a60cf6de1719012>:0
2019-06-08 00:12:03.5359 Debug The response will be compressed with 'gzip'.
2019-06-08 00:12:03.5359 Debug Connection id "0HLNBS21C0GC0" completed keep alive response.
2019-06-08 00:12:03.5359 Info Request finished in 1057.0957ms 500 application/json

```

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.11.391.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:  5.20.1.19

-------------------------------

**Comment by garfield69** [comment]
works for me, so this is something specific to your platform/build.
have you considered ditching the mono version of trying out the .net core version instead?
see install details at https://github.com/Jackett/Jackett#install-on-linux-amdx64 or https://github.com/Jackett/Jackett#install-on-linux-armv7-or-above dependiong on your platform.

**Comment by kaysond** [comment]
So katcr.co had been down for a while, but even with the .net core version, I get the same issue:
```
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Info Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/kickasstorrent/test  0
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug Request is continuing in applying rules. Current url is https://jackett.iamnub.com/api/v2.0/indexers/kickasstorrent/test
Jun 17 00:17:19 fserver jackett[6770]: message repeated 2 times: [ 06-17 00:17:19 Debug Request is continuing in applying rules. Current url is https://jackett.iamnub.com/api/v2.0/indexers/kickasstorrent/test]
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug POST requests are not supported
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug AuthenticationScheme: Cookies was successfully authenticated.
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerid}/Test'
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Info Route matched with {action = "Test", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Test (jackett)
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug Execution plan of exception filters (in the following order): None
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Info Authorization was successful.
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Info Executing action method Jackett.Server.Controllers.IndexerApiController.Test (jackett) - Validation state: Valid
Jun 17 00:17:19 fserver jackett[6770]: 06-17 00:17:19 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://katcr.co/category/latest/page/1)
Jun 17 00:17:20 fserver jackett[6770]: 06-17 00:17:20 Debug WebClient(HttpWebClient2NetCore): Returning BadRequest => <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
Jun 17 00:17:20 fserver jackett[6770]: <html><head>
Jun 17 00:17:20 fserver jackett[6770]: <title>400 Bad Request</title>
Jun 17 00:17:20 fserver jackett[6770]: </head><body>
Jun 17 00:17:20 fserver jackett[6770]: <h1>Bad Request</h1>
Jun 17 00:17:20 fserver jackett[6770]: <p>Your browser sent a request that this server could not understand.<br />
Jun 17 00:17:20 fserver jackett[6770]: </p>
Jun 17 00:17:20 fserver jackett[6770]: <hr>
Jun 17 00:17:20 fserver jackett[6770]: <address>Apache/2.4.10 Server at katcr.co Port 443</address>
Jun 17 00:17:20 fserver jackett[6770]: </body></html>
Jun 17 00:17:20 fserver jackett[6770]:
Jun 17 00:17:20 fserver jackett[6770]: 06-17 00:17:20 Info Found 0 releases from KickAssTorrent
Jun 17 00:17:20 fserver jackett[6770]: 06-17 00:17:20 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 643.2051ms
Jun 17 00:17:20 fserver jackett[6770]: 06-17 00:17:20 Error System.Exception: Found no results while trying to browse this tracker
Jun 17 00:17:20 fserver jackett[6770]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
Jun 17 00:17:20 fserver jackett[6770]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Jun 17 00:17:20 fserver jackett[6770]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 System.Exception: Found no results while trying to browse this tracker
Jun 17 00:17:20 fserver jackett[6770]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
Jun 17 00:17:20 fserver jackett[6770]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jun 17 00:17:20 fserver jackett[6770]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Jun 17 00:17:20 fserver jackett[6770]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
Jun 17 00:17:20 fserver jackett[6770]: 06-17 00:17:20 Debug The response will be compressed with 'br'.
Jun 17 00:17:20 fserver jackett[6770]: 06-17 00:17:20 Debug Connection id "0HLNIRG787SCA" completed keep alive response.
Jun 17 00:17:20 fserver jackett[6770]: 06-17 00:17:20 Info Request finished in 653.3192ms 500 application/json
```

**Comment by kaysond** [comment]
Still not working. Any info I can provide?

**Comment by garfield69** [comment]
I don't think is has anything to do with jackett.
in response to `https://katcr.co/category/latest/page/1` katcr.co returned
`Bad Request
Your browser sent a request that this server could not understand.
Apache/2.4.10 Server at katcr.co Port 443
`

something is wrong with your system/network/idontknow.
the fact that you switched from mono to core and still have a problem confirms this.
have you tried opening a browser on the same system that is running jackett and seeing what you get for https://katcr.co/category/latest/page/1 ?

**Comment by kaysond** [comment]
I don't think its a network or system issue... I can access the page with Firefox and curl on the system no problem.

**Comment by garfield69** [comment]
Sorry, beyond me, which is why I assigned it to the two leading devs of this project.

**Comment by kaysond** [comment]
@garfield69 is there a way to easily record the outgoing http request?

**Comment by garfield69** [comment]
no.
I mean I know what the outgoing URL is, its in your log which I pasted in a previous comment.
but to see the actual https data stream and then decipher why the kat server rejected it, you are going to need a tool like https://www.telerik.com/fiddler which can capture all out/in traffic, but it's a fairly complex tool and I cant help you with using it.

**Comment by garfield69** [comment]
did you get it working?

**Comment by kaysond** [comment]
nope figured its dead? i can reopen

**Comment by garfield69** [comment]
nah. :-(
 I was just hoping you might have got lucky and figured it out.

**Comment by kaysond** [comment]
if i have time this weekend ill set up a web proxy and see if i can debug

**Comment by ngosang** [comment]
This tracker is working fine for months.
If you are still having problems in the latest version, please, open a new issue.

**Comment by kaysond** [comment]
It still didnt work for me. Removed it and re-added. Now it works.
