### ISSUE TITLE
[generationfree] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#5469]
```
Jun 11 21:10:15 odroid jackett[7362]: 06-11 21:10:15 Info Found 0 releases from Generation-Free
Jun 11 21:10:15 odroid jackett[7362]: 06-11 21:10:15 Error System.Exception: Found no results while trying to browse this tracker
Jun 11 21:10:15 odroid jackett[7362]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 225
Jun 11 21:10:15 odroid jackett[7362]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 System.Exception: Found no results while trying to browse this tracker
Jun 11 21:10:15 odroid jackett[7362]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 225
Jun 11 21:10:15 odroid jackett[7362]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
Jun 11 21:10:15 odroid jackett[7362]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```

**Comment by garfield69** [comment]
have you submitted your presentation? some options on the site are not activated until admin approve your membership.

**Comment by skuizy** [comment]
Yup, that helped !

No more error !

**Comment by mouzzampk2014** [comment]
> Yup, that helped !
> No more error !

How you got the approval to fix this issue? Sorry English Native so hard to understand that website :) Thank you

**Comment by garfield69** [comment]
login to the site directly with your browser. the first page is a reminder that you have to provide a presentation.
follow the link to post an introduction in that forum. admin will approve or post a request for more details.
use the chrome translate page option if you need the French turned into English.

**Comment by mouzzampk2014** [comment]
Thank you I will put Chrome now ;) I know still using Edge. You have a lovely evening dear. Thanks again
