### ISSUE TITLE
[Req] CrazySpirits

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#5479]
id: crazyspirits-api
name: CrazySpirits (API)
description: "Crazy Spirits is a FRENCH Private Torrent Tracker for MOVIES / TV / GENERAL"
type: private
links:
  - https://crazyspirits.com/

**Comment by garfield69** [comment]
site's registration is broken
![image](https://user-images.githubusercontent.com/6933240/60749391-63169280-9fed-11e9-936e-5c405fdc076a.png)

**Comment by pipopop** [comment]
Ok. I let a message to the staff for that.
I could have an invitation in 2-3 days.
Thanks for all !

**Comment by garfield69** [comment]
registration is working now. account created.

**Comment by garfield69** [comment]
try out jackett pre-release 0.11.494

**Comment by pipopop** [comment]
Hi Garfield,
I try with last version.
I have this error : "Login failed: Selector "a[href="account-logout.php"]" didn't match"
Do you want more log ?

**Comment by garfield69** [comment]
works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by pipopop** [comment]
Sorry, works for me. First time I took the cookie informations form Vivaldi browser from another place.
Now I take the cookie informations from Firefox from the same computer (with same IP) where jackett is installed.

Great thanks to you Garfield !

**Comment by garfield69** [comment]
https://www.crazyspirits.com/ returning 
![image](https://user-images.githubusercontent.com/6933240/86407203-a989f480-bd08-11ea-9465-ed893d40ffe4.png)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.crazyspirits.com/ returns
![image](https://user-images.githubusercontent.com/6933240/158304501-fbaa02f9-d125-4268-b410-b7def1158d08.png)

**Comment by ilike2burnthing** [comment]
ERR_NAME_NOT_RESOLVED

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Hmm. I'm still seeing `No such host is known.: No such host is known. (www.crazyspirits.com:443)`

**Comment by ilike2burnthing** [comment]
Still up for me. Uptrends showing 1 failed DNS lookup - https://www.uptrends.com/tools/uptime?toolRequestGuid=5caf3213-834e-47e2-82d7-82ec9d4d93b7

**Comment by ilike2burnthing** [comment]
- https://www.crazyspirits.com/ - generic TorrentTrader v3.0, login not working
- banner on login page reads: The crazyspirits is currently under construction and we will do our best to get back to it as soon as possible, see you soon!
- `We accept anyone with experience who will
share torrents before opening to all our members officially,
send me a registration request and tell me you want uploaded.`
- back to a regular login page, but when I use my creds the login fails with `do not leave any fields empty` !?!
- and using the recover option tells me my email address was not found.
- registration is invite only ATM

**Comment by garfield69** [comment]
Its been several months. How much longer should we wait?
You just know that as soon as I delete this indexer they will open access up again ;-b

**Comment by ilike2burnthing** [comment]
Clearly I've jinxed us now and it'll be back up in a few days ;P

**Comment by garfield69** [comment]
v0.21.904

**Comment by pipopop** [comment]
Hello. Sorry, don't have access yet. I will come back when I have it. Thank you for your work.

**Comment by Siouldlh** [comment]
I have the same problem, I can't add crazy spirit to Jackett. Can you help me?

**Comment by Siouldlh** [comment]
Crazy spirit is no longer down

**Comment by garfield69** [comment]
@Siouldlh We removed the crazyspirit indexer 3 weeks ago because the web site was not working.
Are you telling me that you can login to the web site?
My credentials are still being rejected with an `Access Denied Do not leave any required fields empty` message.

**Comment by Siouldlh** [comment]
yes I can log in

**Comment by Siouldlh** [comment]
I think they've had to reset the database, but you can re-register without an invitation code between 15 and 22 October.

**Comment by Siouldlh** [comment]
I also had to create a new account

**Comment by garfield69** [comment]
Oh good, I see that registration is open ATM. I shall try to register and if successful, I'll reactivate the indexer and update it if required.

**Comment by Siouldlh** [comment]
Thank you

**Comment by garfield69** [comment]
v0.21.1043

**Comment by revers59** [comment]
@garfield69 if your access work can you do a download test ?
i have this error
`<html><body>


  | Error downloading. indexer: crazyspirits path: https://www.crazyspirits.com/torrents-details.php?id=(removed)&hit=1 System.Exception: Download selectors didn't match
-- | --



</body>
</html>`

**Comment by garfield69** [comment]
yes, it does appear that the download link has changed, I'll investigate.

**Comment by garfield69** [comment]
v0.21.1056

**Comment by Siouldlh** [comment]
Hello, I have this bug when I want to add crazy spirit on Jackett, my configuration is normal, no other problems with other trackers. Does anyone else have this error? 
`Login failed: Selector "a[href="account-logout.php"]" didn't match`
`Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match

[v0.21.1776.0] Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 884
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/CardigannIndexer.cs:line 1043
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26`

**Comment by ilike2burnthing** [comment]
Open a new issue, provide the information requested.

**Comment by Siouldlh** [comment]
@garfield69 
Hello , I don't see anymore CrazySpirits in the indexers list.Could you help me? I have the latest update.
link : [https://www.crazyspirits.com]
Thanks You

**Comment by garfield69** [comment]
https://www.crazyspirits.com/ Connection à échoué: Too many connections

**Comment by garfield69** [comment]
online

**Comment by nitrup** [comment]
Impossible to use the cookie error :
An error occurred while updating this indexer
Login failed: Selector "a[href="account-logout.php"]" didn't match
[Click here to open an issue on GitHub for this indexer.](https://github.com/Jackett/Jackett/issues/new?template=bug_report.yml&title=[crazyspirits]%20(updating)%20Login%20failed%3A%20Selector%20%22a%5Bhref%3D%22account-logout.php%22%5D%22%20didn%27t%20match)

**Comment by garfield69** [comment]
https://www.crazyspirits.com/torrents-search.php 500 Internal Server Error

**Comment by nitrup** [comment]
Yes server migration in progress :)

**Comment by garfield69** [comment]
online

**Comment by nitrup** [comment]
Same issue after the site is online ; [crazyspirits] (updating) Login failed: Selector "a[href="account-logout.php"]" didn't match

**Comment by garfield69** [comment]
@nitrup  The indexer is working for me. Review https://github.com/Jackett/Jackett/wiki/TroubleShooting/#your-cookie-did-not-work and if you can't figure it out then open a new ticket so we can focus on your issue.

**Comment by garfield69** [comment]
v0.22.789

**Comment by garfield69** [comment]
https://www.crazyspirits.com/ No Response Data

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
- https://www.crazyspirits.com/ Fatal error: require_once(): Failed opening required '/home/cs/public_html/wp-load.php'
- https://github.com/Jackett/Jackett/issues/5479#issuecomment-2417450727

**Comment by garfield69** [comment]
online

**Comment by nitrup** [comment]
An error occurred while updating this indexer
Login failed: Selector "a[href="account-logout.php"]" didn't match

**Comment by garfield69** [comment]
The indexer is working for me.
have you fetched a fresh cookie?
Follow the troubleshooting steps here - https://github.com/Jackett/Jackett/wiki/Troubleshooting/#your-cookie-did-not-work
IF you can't figure it out then open a new ticket and provide a full Enhanced log, perhaps that will provide a clue. See https://github.com/Jackett/Jackett/wiki/TroubleShooting/#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by garfield69** [comment]
https://www.crazyspirits.com/ > https://www.crazyspirits.com/cgi-sys/defaultwebpage.cgi 404 Page Not Found

**Comment by nitrup** [comment]
The new url is crazyspirits.ca

**Comment by garfield69** [comment]
Thank you. I shall update the indexer.

**Comment by garfield69** [comment]
v0.23.56

**Comment by garfield69** [comment]
https://www.crazyspirits.ca/ > HTTP Connect Failure
Uptrends has only 11/43 checkpoints online

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://www.crazyspirits.ca/ > DNS Lookup Error

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://www.crazyspirits.ca/ > Http timeout

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5479#issuecomment-3682852585

**Comment by ilike2burnthing** [comment]
slow but back up

**Comment by garfield69** [comment]
https://www.crazyspirits.ca/ is v1 and is due to be closed soon.
https://crazyspirits.com/ is v2 and may not be ready yet.

**Comment by garfield69** [comment]
https://www.crazyspirits.ca/ I am unable to login, just me?
https://crazyspirits.com/ I can login, is it time to update the indexer?

**Comment by ilike2burnthing** [comment]
I can't login to either. Account recovery for .ca says my account doesn't exist, and .com says it will send an email if the account exists, but I get no email 🤷 

Maybe they're in the middle of migrating over?

**Comment by garfield69** [comment]
reopen to monitor .ca web site and if/when the crazyspirits indexer needs to be removed.

**Comment by garfield69** [comment]
v0.24.1519

**Comment by garfield69** [comment]
crazyspirits.yml replaced by crazyspirits-api.yml

**Comment by garfield69** [comment]
v0.24.1577

**Comment by garfield69** [comment]
https://crazyspirits.com/torrents.php > no torrents found
the indexer using the API returns no results also

**Comment by garfield69** [comment]
The API is returning results.
The web site login page appears broken, returns Vérification échouée. 
Looks like a cloudflare issue, I see 401 and 404 errors during login.
But since this is about the API, I'm closing.
[late edit] logins working again.
