### ISSUE TITLE
[mejortorrent] Sequence contains no elements (Config)

### ISSUE THREAD

**Issue by josopu** [Jackett/Jackett#5587]
Hey! When trying to add indexer "mejortorrent" it gives me the " An error occured while updating this indexer. Sequence contains no elements" error. 
I can browse for "https://www.mejortorrentt.org/" which is the "site link" for this tracker and download torrents on them web site.

Log for this error:
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 103
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 72
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 60
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

Hope you can fix it!

Using latest Jackett docker (did not install any other stuff on the docker).

**Comment by josopu** [comment]
I know it is duplicated. But you did close them post because they did give no details at all. I think I did give some details for you to help me :D

**Comment by kaiserssosse** [comment]
Same problem for me, I am using the last standalone version in ubuntu 19.4.

**Comment by TrashCanMan** [comment]
Im having the same, it seems this issue happens again every few months and solves itself (or someone ninja fix it, no idea) a few days later...

**Comment by auxilig** [comment]
I have the same problem too

2019-07-05 18:03:37.4034 Error System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 103
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 72
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 60
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 103
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 72
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 60
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

Jackett Version 0.11.404.0

**Comment by perikin88** [comment]
The new release 0.11.471.0 doesn't solve the error.

**Comment by bgta** [comment]
Same error to me on Manjaro 18.04, jackett version 0.11.476:

`jul 09 07:53:49 xxServer jackett[20202]: 07-09 07:53:49 Error System.InvalidOperationException: Sequence contains no elements                                                               
jul 09 07:53:49 xxServer jackett[20202]:    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)                                                                                  
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/I
ndexers/MejorTorrent.cs:line 105                                                                                                                                                          
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTor
rent.cs:line 74                                                                                                                                                                           
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Mej
orTorrent.cs:line 62                                                                                                                                                                      
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Contr
ollers/IndexerApiController.cs:line 94                                                                                                                                                    
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecut
or executor, Object controller, Object[] arguments)                                                                                                                                       
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()                                                          
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()                                                      
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)                                             
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)               
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()                                                           
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()                                                                 
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)                                                   
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)                       
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()                                                                
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()                                                                              
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)                                                                
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)                                                     
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)                                                            
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middle
ware/CustomExceptionHandler.cs:line 29 System.InvalidOperationException: Sequence contains no elements                                                                                    
jul 09 07:53:49 xxServer jackett[20202]:    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)                                                                                  
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/I
ndexers/MejorTorrent.cs:line 105                                                                                                                                                          
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTor
rent.cs:line 74                                                                                                                                                                           
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Mej
orTorrent.cs:line 62                                                                                                                                                                      
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Contr
ollers/IndexerApiController.cs:line 94                                                                                                                                                    
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecut
or executor, Object controller, Object[] arguments)                                                                                                                                       
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()                                                          
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()                                                      
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)                                             
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)               
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()                                                           
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()                                                                 
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)                                                   
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)                       
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()                                                                
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()                                                                              
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)                                                                
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)                                                     
jul 09 07:53:49 xxServer jackett[20202]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
jul 09 07:53:49 xxServer jackett[20202]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middle
ware/CustomExceptionHandler.cs:line 29`

**Comment by alvarosola1** [comment]
Same for me

**Comment by ivykoko1** [comment]
Same error here.

**Comment by stoype** [comment]
Same problem running  Jackett Version 0.11.487.0 on Synology Docker. Any solution or prevision?

**Comment by zamberjo** [comment]
Same problem running current version **Jackett Version 0.11.493.0**

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 105
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 74
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 62
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```

**Comment by stoype** [comment]
Issue continues running Jackett Version 0.11.534.0

**Comment by stoype** [comment]
when will be correct? Is one of most used an better spanish free indexer

**Comment by am4rtinez** [comment]
Same error on OpenMediaVault with docker linuxserver/jacket Version 0.11.420.0

Error:
`System.InvalidOperationException:` Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 103
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 72
   at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 60
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29`

**Comment by aferpa94** [comment]
Same issue here!

**Comment by auxilig** [comment]
Please help, the two main Spanish indexes do not work!

**Comment by stoype** [comment]
Currenty continous not working, running  Jackett Version 0.11.559.0...

**Comment by auxilig** [comment]
This issues:
[mejortorrent] Sequence contains no elements (Config) #5753
[mejortorrent] Sequence contains no elements (Config) #5776

They are closed because they are duplicated. The problem is not solved.
When will they solve the problem?

**Comment by garfield69** [comment]
problem will not be solved until a volunteer c# developer contributes.
BTW I am not a c# developer  and this indexer written in c# is way too complicated for my paltry c# skills.
Any volunteers out there? Feel free to raise a PR and contribute.

**Comment by carlogarro** [comment]
The problem is still not solved....

**Comment by rovik0** [comment]
The problem persist for URL suck as https://mejortorrent1.net/ since http://www.mejortorrentt.org/ does not even return torrents but `.vsb`.

**Comment by garfield69** [comment]
jackett 0.12.1669

**Comment by josopu** [comment]
Seems like all torrents size is 16GB or 1.5GB no matter what real size they are.
May this be mejortorrent's fault?

I don't know if I should have opened a new issue or not...

**Comment by garfield69** [comment]
@josopu 
![image](https://user-images.githubusercontent.com/6933240/76993819-55097600-69b2-11ea-814b-5194c122c80e.png)
the site's search results page does not have the size.
but if the indexer leaves size as null or 0B then some apps will not download
so we provide defaults.
