### ISSUE TITLE
YTS fails to return results

### ISSUE THREAD

**Issue by alfredsolutions** [Jackett/Jackett#5686]
When using the Wanted->All->SearchAll function, if you have a small number of outstanding movies, it will search for them to completion.
However, if you search for > ~25 or so, it will shit the bed with an indexer error, looks like its parsing pagination results improperly (API change?)

Anyway, here is the stacktrace when the pagination request fails
(was searching for ~200 movies at once)
```
07-18 22:21:50 Info Jackett variant: FullFrameworkWindows
07-18 22:21:51 Info Checked for a updated release but none was found. Current: v0.11.495 Latest: v0.11.495
07-18 22:24:14 Info Found 100 (1 new) releases from YTS
07-18 22:24:24 Info Found 0 releases from YTS for: best years our lives 1946
07-18 22:24:27 Info Found 0 releases from YTS for: sweet smell success 1957
07-18 22:24:31 Info Found 0 releases from YTS for: dimitri 1988
07-18 22:24:34 Info Found 0 releases from YTS for: red heat 1988
07-18 22:24:38 Info Found 0 releases from YTS for: grand illusion 1937
07-18 22:24:41 Info Found 0 releases from YTS for: there s man in woods 2014
07-18 22:24:45 Info Found 0 releases from YTS for: sebastian maniscalco why would you do that 2016
07-18 22:24:48 Info Found 0 releases from YTS for: ants on shrimp 2016
07-18 22:24:51 Info Found 0 releases from YTS for: battle algiers 1966
07-18 22:24:54 Error Error on 20190718222454 for YTS.txtSystem.Exception: API error, movies missing
   at Jackett.Common.Indexers.Yts.<PerformQuery>d__12.MoveNext()




{"status":"ok","status_message":"Query was successful","data":{"movie_count":1,"limit":50,"page_number":1},"@meta":{"server_time":1563513894,"server_timezone":"CET","api_version":2,"execution_time":"0 ms"}}
07-18 22:24:54 Error Jackett.Common.IndexerException: Exception (yts): API error, movies missing ---> System.Exception: Parse error ---> System.Exception: API error, movies missing
   at Jackett.Common.Indexers.Yts.<PerformQuery>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)
   at Jackett.Common.Indexers.Yts.<PerformQuery>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.Yts.<PerformQuery>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext() Jackett.Common.IndexerException: Exception (yts): API error, movies missing ---> System.Exception: Parse error ---> System.Exception: API error, movies missing
   at Jackett.Common.Indexers.Yts.<PerformQuery>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex)
   at Jackett.Common.Indexers.Yts.<PerformQuery>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.Yts.<PerformQuery>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()
```

**Comment by davidfinzel** [comment]
Windows 10 Pro x64, build 1903
Jacket version: 0.11.495

**Comment by garfield69** [comment]
it's the yts json server. in response your your search it returned
```json
{"status":"ok",
"status_message":"Query was successful",
"data":{"movie_count":1,
"limit":50,
"page_number":1},
"@meta":{"server_time":1563513894,
"server_timezone":"CET",
"api_version":2,
"execution_time":"0 ms"}}
```
the json contents states movies count = 1 but the details for the movie is missing.
and the yts jackett indexer had a spaz over this as you would expect.

not sure that there is anything jackett can do about this. @kaso17  @flightlevel  opinion?

**Comment by davidfinzel** [comment]
It seems to only happen when Radarr tries to do a TON of searches at once.
Going to the individual movie page, clicking search, results in YTS results being returned properly.
Not sure how to further test/diagnose, but am willing to try any suggested workarounds to help

**Comment by garfield69** [comment]
the c# devs will need to take a look. 
I note that the code has already got `webclient.requestDelay = 2.5;` to space out multiple requests by 2.5 seconds.

**Comment by ngosang** [comment]
I can't replicate this issue. I think this indexer is working fine because we have few issues.
