### ISSUE TITLE
speed.cd error occured while updating this indexer

### ISSUE THREAD

**Issue by tkdrob** [Jackett/Jackett#5794]
html,body{font-family:tahoma, arial, helvetica, sans-serif;font-size:11pt;color:#000;background:url(/V3/img/error_bg.gif) no-repeat center #000;height:100%;width:100%;margin:0;padding:0} .uiButton{background:#eee url(/pic/ui/buttons/ui.png) repeat-x 0 0;border:1px solid #999;border-bottom-color:#888;box-shadow:0 1px 0 rgba(0,0,0,.1);-moz-box-shadow:0 1px 0 rgba(0,0,0,.1);cursor:pointer;display:inline-block;font-size:11px;font-weight:700;line-height:normal!important;text-align:center;text-decoration:none;vertical-align:top;white-space:nowrap;padding:2px 6px} .uiButton .button{background:none;text-decoration:none;border:0;color:#333;cursor:pointer;display:inline-block;font-size:11px;font-weight:700;outline:0;white-space:nowrap;margin:0;padding:3px 25px 5px} .uiButtoncolor{background-color:#69a74e;background-position:0 -96px!important;border-color:#3b6e22 #3b6e22 #2c5115} .uiButtoncolor:active{background:#609946;border-bottom-color:#3b6e22} .uiButtoncolor .button{color:#fff} .boxHead{background-color:red;border:none;filter:alpha(opacity=70);opacity:0.7;font-size:18px;color:#FFF;font-weight:700;} .boxBody{background-color:#FFF;filter:alpha(opacity=90);opacity:0.9} .boxBody .link{margin:1.5em 0;text-align:center} File Not Found No page exists at your destination address, https://speed.cd/takelogin.php but the Speed.cd home page should help you to find what you need. Return to Speed.cd Home Page 

```
Jackett.Common.ExceptionWithConfigData: 
        
			html,body{font-family:tahoma, arial, helvetica, sans-serif;font-size:11pt;color:#000;background:url(/V3/img/error_bg.gif) no-repeat center #000;height:100%;width:100%;margin:0;padding:0}
			.uiButton{background:#eee url(/pic/ui/buttons/ui.png) repeat-x 0 0;border:1px solid #999;border-bottom-color:#888;box-shadow:0 1px 0 rgba(0,0,0,.1);-moz-box-shadow:0 1px 0 rgba(0,0,0,.1);cursor:pointer;display:inline-block;font-size:11px;font-weight:700;line-height:normal!important;text-align:center;text-decoration:none;vertical-align:top;white-space:nowrap;padding:2px 6px}
			.uiButton .button{background:none;text-decoration:none;border:0;color:#333;cursor:pointer;display:inline-block;font-size:11px;font-weight:700;outline:0;white-space:nowrap;margin:0;padding:3px 25px 5px}
			.uiButtoncolor{background-color:#69a74e;background-position:0 -96px!important;border-color:#3b6e22 #3b6e22 #2c5115}
			.uiButtoncolor:active{background:#609946;border-bottom-color:#3b6e22}
			.uiButtoncolor .button{color:#fff}
			.boxHead{background-color:red;border:none;filter:alpha(opacity=70);opacity:0.7;font-size:18px;color:#FFF;font-weight:700;}
			.boxBody{background-color:#FFF;filter:alpha(opacity=90);opacity:0.9}
			.boxBody .link{margin:1.5em 0;text-align:center}
		
    
	
		
			
				
					
						
							File Not Found
						
						
							
								No page exists at your destination address,
								https://speed.cd/takelogin.php
								but the Speed.cd home page should help you to find what you need.
							
						
						
							
								Return to Speed.cd Home Page
							
						
					
				
			
		
  	

   at Jackett.Common.Indexers.SpeedCD.<>c__DisplayClass9_0.<DoLogin>b__0() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/SpeedCD.cs:line 105
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 267
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/SpeedCD.cs:line 99
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/SpeedCD.cs:line 85
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```

Jackett Version 0.11.563.0

**Comment by garfield69** [comment]
looks like they have changed the login processor from takelogin.php to take_login.php
try out Jackett pre-release 0.11.571

**Comment by rycore** [comment]
> 
> 
> looks like they have changed the login processor from takelogin.php to take_login.php
> try out Jackett pre-release 0.11.571

Hi, I tried the pre-release as I was having the same problem as the OP and it worked for me, thank you.
