### ISSUE TITLE
Jackett Wont Sign in to Norbits

### ISSUE THREAD

**Issue by xpirat** [Jackett/Jackett#5826]
If you visit norbits.net the login page looks a little different than before. They updated some stuff, so jackett cannot login to Norbits anymore

**Comment by garfield69** [comment]
@DiseaseNO would you be able to take a look at this ticket?

**Comment by nn22954** [comment]
I have this problem too. From the log:
```
Jackett.Common.IndexerException: Exception (norbits): Input string was not in a correct format. ---> System.Exception: Parse error ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at Jackett.Common.Indexers.Norbits.PerformQuery(TorznabQuery query)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 842
   at Jackett.Common.Indexers.Norbits.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Norbits.cs:line 429
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```
and before that:
```
Error on 20190812211931 for Norbits.txtSystem.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at Jackett.Common.Indexers.Norbits.PerformQuery(TorznabQuery query)


Error, unable to parse result 
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at Jackett.Common.Indexers.Norbits.PerformQuery(TorznabQuery query)
```

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go at sorting the problem out.

**Comment by garfield69** [comment]
looks like the problem is with the post login test. the torrent search list at  https://norbits.net/browse.php?search=&incldead=1&fullsearch=0&scenerelease=0 no longer has the health column, (it was between files and seeders), so this causes the indexer to fail when attempting to read the leechers.
try out jackett pre-release 0.11.608

**Comment by ProphetSe7en** [comment]
> looks like the problem is with the post login test. the torrent search list at https://norbits.net/browse.php?search=&incldead=1&fullsearch=0&scenerelease=0 no longer has the health column, (it was between files and seeders), so this causes the indexer to fail when attempting to read the leechers.
> try out jackett pre-release 0.11.608

It stopped working again. Jacket Version 0.11.613.0

**Comment by garfield69** [comment]
working for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by cat0b** [comment]
Working for me on 0.11.613.0. At first I thought it didn't, but for some reason my saved password was wrong, possibly done by Lastpass. Corrected that and all was ok.

**Comment by ProphetSe7en** [comment]
> working for me.

My bad. It is working now. Thank you
