### ISSUE TITLE
[yggtorrent] Login failed: No form found on http://www2.yggtorrent.ch/ using form selector 

### ISSUE THREAD

**Issue by Sigri44** [Jackett/Jackett#5879]
Hello,

This morning, add YGG indexer works fine.

And this night : 

Login failed: No form found on http://www2.yggtorrent.ch/ using form selector

Website is good and login work fine.

Config : Linux + Docker
 **Jackett version**:  0.11.589.0
-------------------------------

![aaaaa](https://user-images.githubusercontent.com/9304947/63230388-2523a580-c20c-11e9-8f63-7076796ecc06.png)

```
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on http://www2.yggtorrent.ch/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 869
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```

**Comment by Sigri44** [comment]
it's not a duplicate because the other post has never had an answer

![aaaaa](https://user-images.githubusercontent.com/9304947/63230358-d37b1b00-c20b-11e9-93d5-1c1f18adbf36.png)

**Comment by garfield69** [comment]
use your Jackett Dashboard to edit (click the Wrench Icon) your YGGTorrent Indexer.
set your *Site Link* to `https://www.yggtorrent.ch/` and your *search link* to `www2.yggtorrent.ch` and click OKAY. 
if you get an error, click CLOSE and try again. it should save the second time.
if you cannot make it work, use the trashbin Icon to delete it and fetch it new from the add-indexers page. It should be preloaded with the correct details.

**Comment by chripink** [comment]
Thank you @garfield69 for the trick

**Comment by doog33k** [comment]
same for me thanks @garfield69
