### ISSUE TITLE
Jackett fails to start (Debian Buster)

### ISSUE THREAD

**Issue by ay3w** [Jackett/Jackett#5902]
**Jackett version**:  v0.11.635.0
 **Mono version**: v6.0.0.319
Jackett suddenly won't start out of the blue after I restarted my server. All I did was turn off the machine and change the cpu heatsink, so I have absolutely no clue what happened to cause this.

**systemd status:**
```
● jackett.service - Jackett Daemon
   Loaded: loaded (/etc/systemd/system/jackett.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Sat 2019-08-24 19:54:53 AEST; 2s ago
  Process: 2064 ExecStart=/opt/Jackett/jackett --NoRestart (code=killed, signal=ABRT)
 Main PID: 2064 (code=killed, signal=ABRT)
```

**Running jackett manually:**
```
08-24 19:56:42 Info Starting Jackett v0.11.635.0 
08-24 19:56:43 Error System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'System.Text.RegularExpressions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.                                                                                                                                                                                                
   at AutoMapper.PascalCaseNamingConvention..ctor()
   at AutoMapper.Configuration.Conventions.NameSplitMember..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance[T]()
   at AutoMapper.Configuration.Conventions.MemberConfiguration.GetOrAdd[TMemberMapper](Func`2 getList, Action`1 setupAction)
   at AutoMapper.Configuration.Conventions.MemberConfiguration.AddMember[TMemberMapper](Action`1 setupAction)
   at AutoMapper.Profile..ctor()
   at AutoMapper.Configuration.MapperConfigurationExpression..ctor()
   at AutoMapper.MapperConfiguration.Build(Action`1 configure)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at Jackett.Server.Helper.Initialize() in /home/appveyor/projects/jackett/src/Jackett.Server/Helper.cs:line 27
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in /home/appveyor/projects/jackett/src/Jackett.Server/Startup.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args) System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'System.Text.RegularExpressions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
   at AutoMapper.PascalCaseNamingConvention..ctor()
   at AutoMapper.Configuration.Conventions.NameSplitMember..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance[T]()
   at AutoMapper.Configuration.Conventions.MemberConfiguration.GetOrAdd[TMemberMapper](Func`2 getList, Action`1 setupAction)
   at AutoMapper.Configuration.Conventions.MemberConfiguration.AddMember[TMemberMapper](Action`1 setupAction)
   at AutoMapper.Profile..ctor()
   at AutoMapper.Configuration.MapperConfigurationExpression..ctor()
   at AutoMapper.MapperConfiguration.Build(Action`1 configure)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at Jackett.Server.Helper.Initialize() in /home/appveyor/projects/jackett/src/Jackett.Server/Helper.cs:line 27
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in /home/appveyor/projects/jackett/src/Jackett.Server/Startup.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.BadImageFormatException: Could not load file or assembly 'System.Text.RegularExpressions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
   at AutoMapper.PascalCaseNamingConvention..ctor()
   at AutoMapper.Configuration.Conventions.NameSplitMember..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance[T]()
   at AutoMapper.Configuration.Conventions.MemberConfiguration.GetOrAdd[TMemberMapper](Func`2 getList, Action`1 setupAction)
   at AutoMapper.Configuration.Conventions.MemberConfiguration.AddMember[TMemberMapper](Action`1 setupAction)
   at AutoMapper.Profile..ctor()
   at AutoMapper.Configuration.MapperConfigurationExpression..ctor()
   at AutoMapper.MapperConfiguration.Build(Action`1 configure)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at Jackett.Server.Helper.Initialize() in /home/appveyor/projects/jackett/src/Jackett.Server/Helper.cs:line 27
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in /home/appveyor/projects/jackett/src/Jackett.Server/Startup.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)
Aborted
```
-------------------------------

**Comment by garfield69** [comment]
similar to #5208.
there appears to be an intermittent issue with the updater process that trips up on some systems.
until it is resolved, I suggest disabling the auto-update by using the Jackett dashboard Disable auto update checkbox and clicking on the Apply Server Settings button.
But first you will need to install manually from https://github.com/Jackett/Jackett/releases to restore service.

**Comment by ay3w** [comment]
This fixed the issue.
