### ISSUE TITLE
[xspeeds]  (Config)

### ISSUE THREAD

**Issue by shaunusmaximus** [Jackett/Jackett#5924]
Unsure what I'm doing wrong here,.. just trying to add the xspeeds indexer into Jackett and get "An error occurred while updating this indexer"

Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.XSpeeds.<>c__DisplayClass19_0.<ApplyConfiguration>b__0()
   at Jackett.Common.Indexers.BaseIndexer.<ConfigureIfOK>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.XSpeeds.<ApplyConfiguration>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Controllers.IndexerApiController.<UpdateConfig>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext()

**Comment by garfield69** [comment]
working for me.
I suggest logging onto xspeeds and checking your account status. Is your account suspended, or have you a low ratio warning, an alert outstanding that needs to be cleared, system private messages that need to be read, profile settings that need to be completed, that sort of thing.
Also clear your unread messages box
from UserCP>EditThemes&Language, set your language to english and your theme to XsDark, its possible the jackett indexer cannot handle non-english profiles or different themes.
from UserCP>EditSettings&Options, uncheck the ShowNewPrivateMessageNotificationPopUp, as unexpected events in the html returned can throw off the indexer's processing.

and try again.
if it is still not working, then:

The trace dump on its own is not enough info to figure out what is going on in this case,
so provide your jackett version and the platform you are running it on.
then please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by shaunusmaximus** [comment]
Thank you for the response..

So I checked the settings in xspeeds and everything is default and matches what you requested (with the exception of an empty inbox which I've since emptied but have the same problem)

I've pasted the log file below, but what oddly the username  password data was never in it,.. this is raw, with no redaction's. 

Thanks again for the help.
Shaun 

2019-08-30 23:52:55.5314 Debug Connection id "0HLPCELF2F0K7" started. 
2019-08-30 23:52:55.5314 Info Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/xspeeds/config application/json 345 
2019-08-30 23:52:55.5314 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/xspeeds/config 
2019-08-30 23:52:55.5404 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/xspeeds/config 
2019-08-30 23:52:55.5404 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/xspeeds/config 
2019-08-30 23:52:55.5404 Debug POST requests are not supported 
2019-08-30 23:52:55.5404 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-08-30 23:52:55.5553 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerId?}/Config' 
2019-08-30 23:52:55.5553 Debug Action 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' with id 'fa1d029e-45f7-4c38-ab78-83ccf3375e98' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
2019-08-30 23:52:55.5553 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) 
2019-08-30 23:52:55.5553 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-08-30 23:52:55.5553 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-08-30 23:52:55.5553 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-08-30 23:52:55.5723 Debug Execution plan of exception filters (in the following order): None 
2019-08-30 23:52:55.5723 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-08-30 23:52:55.5723 Info Authorization was successful. 
2019-08-30 23:52:55.5723 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-08-30 23:52:55.5723 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2019-08-30 23:52:55.5872 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json'. 
2019-08-30 23:52:55.5872 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'. 
2019-08-30 23:52:55.5872 Debug Connection id "0HLPCELF2F0K7", Request id "0HLPCELF2F0K7:00000001": started reading request body. 
2019-08-30 23:52:55.5872 Debug Connection id "0HLPCELF2F0K7", Request id "0HLPCELF2F0K7:00000001": done reading request body. 
2019-08-30 23:52:55.5872 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-08-30 23:52:55.6012 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-08-30 23:52:55.6012 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-08-30 23:52:55.6012 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-08-30 23:52:55.6012 Info Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid 
2019-08-30 23:52:55.6012 Debug WebClient(HttpWebClient).GetString(Url:https://www.xspeeds.eu/takelogin.php) 
2019-08-30 23:52:56.8010 Debug WebClient(HttpWebClient): Returning OK => <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en" id="tsse_html">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="generator" content="xspeeds.eu :: An error has occured!" />
<meta name="revisit-after" content="1 day" />
<meta name="robots" content="index, follow" />
<meta name="description" content="xspeeds, you know if you're a member" />
<meta name="keywords" content="xspeeds, Firefox, open source" />
<title>xspeeds.eu :: An error has occured!</title>
<link rel="stylesheet" href="https://www.xspeeds.eu/style.php?theme=XsDark&amp;style=style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="https://www.xspeeds.eu/scripts/colorbox/colorbox.css" type="text/css" media="screen" />
<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="https://www.xspeeds.eu/rss.php" />
<link rel="alternate" type="text/xml" title="RSS .92" href="https://www.xspeeds.eu/rss.php" />
<link rel="shortcut icon" href="https://www.xspeeds.eu/favicon.ico" type="image/x-icon" />
<script type="text/javascript">
	//<![CDATA[
	var baseurl="https://www.xspeeds.eu";
	var dimagedir="https://www.xspeeds.eu/images/";
	var themedir="https://www.xspeeds.eu/include/templates/XsDark/";
	var charset="UTF-8";
	var userid="0";
	var securitytoken = "";
	var lang_resized = "This image has been resized. Click the image to view the full image. The original image is sized: ";
	if (window.top !== window.self) {document.write = "";window.top.location = window.self.location; setTimeout(function(){document.body.innerHTML='';},1);window.self.onload=function(evt){document.body.innerHTML='';};}
	//]]>
</script>
<script type="text/javascript" src="https://www.xspeeds.eu/scripts/jquery-1.4.2.min.js?v=7.2"></script>
<script type="text/javascript" src="https://www.xspeeds.eu/scripts/jquery.lazyload.mini.js?v=7.2"></script>
<script type="text/javascript" src="https://www.xspeeds.eu/scripts/colorbox/jquery.colorbox-min.js?v=7.2"></script>
<script type="text/javascript" src="https://www.xspeeds.eu/scripts/bookmarkscroll.js?v=7.2"></script>
<script type="text/javascript" src="https://www.xspeeds.eu/scripts/main.js?v=7.2"></script>
<script type="text/javascript" src="https://www.xspeeds.eu/scripts/menu.js?v=7.2"></script>
<script type="text/javascript" src="https://www.xspeeds.eu/scripts/collapse.js?v=7.2"></script>
<script type="text/javascript" src="https://www.xspeeds.eu/scripts/tooltip.js?v=7.2"></script>
<script type="text/javascript">
	//<![CDATA[
	jQuery(document).ready(function()
	{
		if ( !navigator.userAgent.match( /ipad/i ) )
		{
			jQuery("#lazyload img").lazyload({placeholder : themedir+"images/loading.gif", effect:"fadeIn"});
		}
		jQuery("a#ts_show_preview").colorbox({photo: true, title: function()
		{
			var url = jQuery(this).attr('href');
			return '<a href="'+url+'" target="_blank"><font color="white">Open In New Window</font></a>';
		}});
	});
	//]]>
</script>
<script type="text/javascript">	
	//<![CDATA[
	var l_uncheckall="uncheck all";
	var l_checkall="check all";
	var l_logout="Are you sure you want to log out?";
	var l_ajaxerror="There was a problem with the request. Please report this to administrator.";
	var l_ajaxerror2="Cannot create XMLHTTP instance.";	
	var l_updateerror = "There was an error performing the update.\n\nError Message:\n-----------------------------------\n"; 
	var l_pleasewait="Please wait ...";
	var l_ff="Netscape 6 or Mozilla is needed!";
	var l_newreply = "Post Reply";
	//]]>
</script>
<script type="text/javascript">
	//<![CDATA[
	var persistclose = 1;
	var startX = 3;
	var startY = 3;
	var verticalpos = "fromtop";
	var iv = "no";

	function showLoginBox(boxname)
	{
		if (iv == "reCAPTCHA")
		{
			window.location="login.php?";
		}
		else
		{
			if (TSGetID(boxname).style.display == "none")
			{
				ts_show(boxname);
				TSGetID("username").focus();
			}
			else
			{
				ts_hide(boxname);
			}
		}
	}

	function iecompattest()
	{
		return (document.compatMode && document.compatMode!="BackCompat") ? document.documentElement : document.body
	}

	function get_cookie(Name)
	{
		var search = Name + "=";
		var returnvalue = "";
		if (document.cookie.length > 0)
		{
			offset = document.cookie.indexOf(search);
			if (offset != -1)
			{
				offset += search.length;
				end = document.cookie.indexOf(";", offset);
				if (end == -1) end = document.cookie.length;
				returnvalue=unescape(document.cookie.substring(offset, end));
			}
		}
		return returnvalue;
	}

	function closebar()
	{
		if (persistclose)
			document.cookie="remainclosed=1";
		document.getElementById("topbar").style.visibility="hidden";
	}

	function staticbar()
	{
		barheight=document.getElementById("topbar").offsetHeight;
		var ns = (navigator.appName.indexOf("Netscape") != -1) || window.opera;
		var d = document;
		function ml(id)
		{
			var el=d.getElementById(id);
			if (!persistclose || persistclose && get_cookie("remainclosed")=="")
			el.style.visibility="visible";
			if(d.layers)el.style=el;
			el.sP=function(x,y){this.style.right=x+"px";this.style.top=y+"px";};
			el.x = startX;
			if (verticalpos=="fromtop")
				el.y = startY;
			else
			{
				el.y = ns ? pageYOffset + innerHeight : iecompattest().scrollTop + iecompattest().clientHeight;
				el.y -= startY;
			}
			return el;
		}

		window.stayTopLeft=function()
		{
			if (verticalpos=="fromtop")
			{
				var pY = ns ? pageYOffset : iecompattest().scrollTop;
				ftlObj.y += (pY + startY - ftlObj.y)/8;
			}
			else
			{
				var pY = ns ? pageYOffset + innerHeight - barheight: iecompattest().scrollTop + iecompattest().clientHeight - barheight;
				ftlObj.y += (pY - startY - ftlObj.y)/8;
			}
			ftlObj.sP(ftlObj.x, ftlObj.y);
			setTimeout("stayTopLeft()", 10);
		}
		ftlObj = ml("topbar");
		stayTopLeft();
	}

	if (window.addEventListener)
		window.addEventListener("load", staticbar, false);
	else if (window.attachEvent)
		window.attachEvent("onload", staticbar);
	else if (document.getElementById)
		window.onload=staticbar;
	//]]>
</script>
</head>
<body class="yui-skin-sam">
<div id="topbar" class="thead">
<span style="float: right;">
<a href="#" onclick="closebar(); return false"><img style="float: left;" src="https://www.xspeeds.eu/images/close.gif" border="0" alt="" /></a>
</span>
You are Unregistered, please <a href="https://www.xspeeds.eu/signup.php?"><u>register</u></a> or <a href="javascript:void(0);" onclick="showLoginBox('loginbox');"><u>login</u></a> to gain Full access
<div id="loginbox" style="display: none; padding-top: 5px;">
<form method="post" action="https://www.xspeeds.eu/takelogin.php">
<table class="subheader">
<tr><td class="none" align="right">Username:</td><td class="none"><input type="text" name="username" id="username" class="inputUsername" value="" /></td></tr>
<tr><td class="none" align="right">Password:</td><td class="none"><input type="password" name="password" class="inputPassword" value="" /></td></tr>
<tr><td class="none" colspan="2" align="right"> <input type="submit" value="LOGIN" style="vertical-align: middle;" /> <input type="reset" value="RESET" style="vertical-align: middle;" /></td></tr>
</table>
</form>
</div>
</div>
<div class="content">
<div id="top">
<div class="top_text">
Recover Password: <a href="https://www.xspeeds.eu/recover.php">via Email</a> | <a href="https://www.xspeeds.eu/recoverhint.php">via Question</a>
</div>
<div class="padding" align="center"></div>
</div>

<div id="header">
<div style="height:10px; width:174px; float:right; padding-top:115px; padding-left:50px; display: inline-block;">
<div style="display: inline-block; height:40px; width:82px;"><a href="https://www.xspeeds.eu/btcdonate.php"><img border="1" src="https://www.xspeeds.eu/pic/bitcoindonate.png" width="82"></a></div>
<div style="display: inline-block; height:35px; width:82px;"><a href="https://www.xspeeds.eu/donate.php"><img border="1" src="https://www.xspeeds.eu/pic/donatecard.png"></a></div>
</div>
</div>
<div id="menu">

<ul class="TSSEMenu TSSEMenum">
<li class="TSSEMenui"><a class="TSSEMenui" href="https://www.xspeeds.eu/index.php">Home</a></li>
</ul>
</div>
<div id="main">
<div class="left_side">
<script type="text/javascript">
		function ts_show_tag(id, status)
		{
			if (TSGetID(id)){if (status == true || status == false){TSGetID(id).style.display = (status == true)?"none":"";}
			else{TSGetID(id).style.display = (TSGetID(id).style.display == "")?"none":"";}}
		}
	</script>
<div class="notification-border-e" id="notification_748671a225c5f71754f56dc177f3f595" align="center">
<table class="notification-th-e" border="0" cellpadding="2" cellspacing="0">
<tbody>
<tr>
<td align="left" width="100%" class="none">
&nbsp;<span class="notification-title-e">This account has been disabled.</span>
</td>
<td class="none"><img src="https://www.xspeeds.eu/include/templates/XsDark/images/notification_close.gif" alt="" onclick="ts_show_tag('notification_748671a225c5f71754f56dc177f3f595', true);" class="hand" border="0" height="13" width="13" /></td>
</tr>
</tbody>
</table>
<div class="notification-body">
Reason: Banned by System because of Leech-Warning expired!
</div>
</div>
<br />
<br />
</div>
</div>
<div id="footer">
<div class="padding">
Powered by <font color="white"><strong><a href="http://templateshares.net" target="_blank">TS Special Edition v.7.2</a></strong></font>  © 2019 <font color="white"><a href="https://www.xspeeds.eu" target="_self"><strong>xspeeds.eu</strong></a></font>
[Executed in <b> 0.0096 </b>seconds]
</div>
</div>
</div>

<script type="text/javascript">
	
	</script>
<img src="https://www.xspeeds.eu/staffcp/save_stats.php?rand=1567165977&ref=https%3A%2F%2Fwww.xspeeds.eu%2Flogin.php" alt="" title="" width="1" height="1" border="0" />

</body>
</html>
 
2019-08-30 23:52:56.8502 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) in 1272.242ms 
2019-08-30 23:52:56.8701 Error Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.XSpeeds.<>c__DisplayClass19_0.<ApplyConfiguration>b__0()
   at Jackett.Common.Indexers.BaseIndexer.<ConfigureIfOK>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.XSpeeds.<ApplyConfiguration>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Controllers.IndexerApiController.<UpdateConfig>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext() Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.XSpeeds.<>c__DisplayClass19_0.<ApplyConfiguration>b__0()
   at Jackett.Common.Indexers.BaseIndexer.<ConfigureIfOK>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.XSpeeds.<ApplyConfiguration>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Controllers.IndexerApiController.<UpdateConfig>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext()
2019-08-30 23:52:56.8871 Debug The response will be compressed with 'gzip'. 
2019-08-30 23:52:56.8871 Debug Connection id "0HLPCELF2F0K7" completed keep alive response. 
2019-08-30 23:52:56.8871 Info Request finished in 1361.5183ms 500 application/json

**Comment by shaunusmaximus** [comment]
nevermind,.. after posting this i can clearly see the issue myself, how embarrassing. :/ thanks anyway
