### ISSUE TITLE
Torznball get All fails

### ISSUE THREAD

**Issue by cristiancs** [Jackett/Jackett#5982]
URL: http://192.168.0.106:9117/api/v2.0/indexers/all/results/torznab?apikey={REDACTED}

Returns:
```
<error code="900" description="System.ArgumentNullException: Value cannot be null. Parameter name: value at System.Xml.Linq.XAttribute..ctor(XName name, Object value) at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63 at System.Linq.Enumerable.SelectListIterator`2.MoveNext() at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39 at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417"/>
````

Sonnar logs:
```

Unable to connect to indexer: Torznab error detected: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417

---------------------------------------

NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417
   at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess(IndexerResponse indexerResponse) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 42
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 308
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 334

```

Jacket Log

```
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417
```
Tested on a Linux install (new, but the same torrents set) and a Windows Install that was running for more than a year.

Jackett Version 0.11.687.0

I had jackett + sonnar working for months and like 2 weeks ago it stopped working.

**Comment by cristiancs** [comment]
Yes, my initial setup was running all on windows and using 127.0.0.01 but it failed. Yesterday I installed via docket jackett on Linux to test if that was the problem, but it still fails.

Yes, I can access jackett from the browser, actually if I setup sonnar with individual torznball (1 for each tracker) it works.

**Comment by garfield69** [comment]
>actually if I setup sonnar with individual torznball (1 for each tracker) it works.

wait, what?
there is no difference between the set up of a sonarr indexer to access an **individual** jackett indexer, and setting up the **all** aggregate indexer, apart from the name within the url.
so if you say that you **can** get sonarr on windows to access an indexer on linux jackett, but **cant** make the **all** indexer work, then there is something wrong with the url you are using.
so compare them and figure out where you went wrong.

 As an aside, we don't recommend using the aggregate **all** indexer with sonarr. The common issue with this is that if any one of the indexers on jackett take too long to respond, then sonarr will give up waiting on the **all** indexer, and you will not get any results.
Much better to set up individual jackett indexers on sonarr and this way you will always get some results even in one of the jackett indexer is not responding.

perhaps this is the underlying issue for you here.... have you tested each and every one of the indexers on jackett to see that they repond in a timely manner? if anyone of then is broken, then that will interrupt the **all** indexer on sonarr from working reliably.

**Comment by cristiancs** [comment]
I have tested a few, as I think you now (but is not a problem of jackett), is a slow process to add new indexes to Sonnar.  I don't think is a issue with the url, but it might be that one of the trackers is not working correctly, I will try with a subset of trackers and report back.

**Comment by cristiancs** [comment]
Well, i tested with less trackers and now it works, so it must be some of these trackers:

'SkyTorrentsClone', 'EliteTorrent.biz', 'Isohunt2', 'ETTV', 'KickAssTorrent (kat.li)', 'EZTV', 'Anidex', 'Zooqle', 'AniRena', 'Nyaa-pantsu', 'MejorTorrent'
