### ISSUE TITLE
Jackett Not Starting on Ubuntu 14.04.6 LTS

### ISSUE THREAD

**Issue by joelifer** [Jackett/Jackett#5989]
I installed the binaries and am getting the following error when runnng ./jackett on Ubuntu 14.04.6 LTS. Thank you in advance for any help, really appreciate it.

FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)

**Comment by garfield69** [comment]
you are using a fairly old version of ubuntu and you do not have the requisite dotnet libraries needed to run jackett.
try reading https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#linux-distribution-dependencies and see if you can install the required libraries.
but be warned that it is possible that they may not be available for your version of ubuntu

**Comment by joelifer** [comment]
Okay thank you! I thought maybe I could slap a bandaid on it but I'll just upgrade Ubuntu.
