### ISSUE TITLE
[teamhd] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by tayanov** [Jackett/Jackett#6029]
An error occured while updating this indexer
Login Failed, got redirected.

`Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 699
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 870
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29`

Cookie string add alright

**Comment by garfield69** [comment]
log on to teamhd with your browser and ensure you have no outstanding alerts or unread email messages.
if you still cannot get the indexer to work, then the error message on its own is not enough to diagnose your problem.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by iRaschen** [comment]
2019-09-23 08:27:35.5016 Info Request starting HTTP/1.1 POST http://10.0.1.17:9117/api/v2.0/indexers/teamhd/config application/json 369 
2019-09-23 08:27:35.5016 Debug Request is continuing in applying rules. Current url is http://10.0.1.17:9117/api/v2.0/indexers/teamhd/config 
2019-09-23 08:27:35.5024 Debug Request is continuing in applying rules. Current url is http://10.0.1.17:9117/api/v2.0/indexers/teamhd/config 
2019-09-23 08:27:35.5024 Debug Request is continuing in applying rules. Current url is http://10.0.1.17:9117/api/v2.0/indexers/teamhd/config 
2019-09-23 08:27:35.5024 Debug POST requests are not supported 
2019-09-23 08:27:35.5024 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-09-23 08:27:35.5024 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerId?}/Config' 
2019-09-23 08:27:35.5024 Debug Action 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with id 'eb68b416-3f4e-4271-b65c-6b0cfcc78bc6' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
2019-09-23 08:27:35.5024 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) 
2019-09-23 08:27:35.5024 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-09-23 08:27:35.5024 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-09-23 08:27:35.5024 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-09-23 08:27:35.5024 Debug Execution plan of exception filters (in the following order): None 
2019-09-23 08:27:35.5024 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-09-23 08:27:35.5065 Info Authorization was successful. 
2019-09-23 08:27:35.5065 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-09-23 08:27:35.5065 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2019-09-23 08:27:35.5065 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json'. 
2019-09-23 08:27:35.5065 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'. 
2019-09-23 08:27:35.5065 Debug Connection id "0HLPVAHG62FIB", Request id "0HLPVAHG62FIB:00000001": started reading request body. 
2019-09-23 08:27:35.5065 Debug Connection id "0HLPVAHG62FIB", Request id "0HLPVAHG62FIB:00000001": done reading request body. 
2019-09-23 08:27:35.5065 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-09-23 08:27:35.5065 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-09-23 08:27:35.5065 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-09-23 08:27:35.5065 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-09-23 08:27:35.5065 Info Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid 
2019-09-23 08:27:35.5105 Debug CardigannIndexer (teamhd): Cookies after login: uid=3284; pass=60b61ce8768d0876072b50c7f80059f5475949e1d3b815201911a32097d4ccba; lang=russian; token=63e404f65f8901d68090f1570d968413d6ff7c7362d16e5ee3fa1f4d46888e6b; PHPSESSID=1n2ekj080ipuq5ulh5ljahvt81 
2019-09-23 08:27:35.5105 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://teamhd.org/index.php) 
2019-09-23 08:27:35.7564 Debug WebClient(HttpWebClient2NetCore): Returning Redirect => https://teamhd.org/login.php?returnto=index.php  
2019-09-23 08:27:35.7564 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 250.7895ms 
2019-09-23 08:27:35.7564 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 699
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 870
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 699
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 870
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
2019-09-23 08:27:35.7638 Debug The response will be compressed with 'gzip'. 
2019-09-23 08:27:35.7638 Debug Connection id "0HLPVAHG62FIB" completed keep alive response. 
2019-09-23 08:27:35.7638 Info Request finished in 262.5786ms 500 application/json

**Comment by tayanov** [comment]
im not alone with this error.
Another indexer add normaly.

**Comment by garfield69** [comment]
sorry, but I cannot see what is wrong from what is in the log you provided.
passing this ticket on to the c# devs, maybe they can help.

**Comment by SuberSeb** [comment]
> im not alone with this error.
> Another indexer add normaly.

How you add cookie string? I have the same issue.

**Comment by SuberSeb** [comment]
> An error occured while updating this indexer
Do you solve that issue?
