### ISSUE TITLE
[bitspyder] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by josha33** [Jackett/Jackett#6035]
Login failed for bitspyder

Windows 8.1 , .NET Framework 4.6.2
Jackett Version 0.11.709.0

Enhanced log:

```
2019-09-24 19:46:13.9194 Debug Connection id "0HLQ0VRBHFAEU" started. 
2019-09-24 19:46:13.9194 Debug Connection id "0HLQ0VRBHFAEU" started. 
2019-09-24 19:46:13.9594 Info Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/bitspyder/config application/json 193 
2019-09-24 19:46:13.9594 Info Request starting HTTP/1.1 POST http://127.0.0.1:9117/api/v2.0/indexers/bitspyder/config application/json 193 
2019-09-24 19:46:13.9594 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/bitspyder/config 
2019-09-24 19:46:13.9594 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/bitspyder/config 
2019-09-24 19:46:13.9594 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/bitspyder/config 
2019-09-24 19:46:13.9594 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/bitspyder/config 
2019-09-24 19:46:13.9594 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/bitspyder/config 
2019-09-24 19:46:13.9594 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/bitspyder/config 
2019-09-24 19:46:13.9594 Debug POST requests are not supported 
2019-09-24 19:46:13.9594 Debug POST requests are not supported 
2019-09-24 19:46:13.9594 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-09-24 19:46:13.9594 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-09-24 19:46:13.9594 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerId?}/Config' 
2019-09-24 19:46:13.9594 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerId?}/Config' 
2019-09-24 19:46:13.9714 Debug Action 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' with id '6b3dd488-63d6-4d25-871e-93a944142e55' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
2019-09-24 19:46:13.9714 Debug Action 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' with id '6b3dd488-63d6-4d25-871e-93a944142e55' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
2019-09-24 19:46:13.9714 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) 
2019-09-24 19:46:13.9714 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) 
2019-09-24 19:46:13.9714 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-09-24 19:46:13.9714 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-09-24 19:46:13.9714 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-09-24 19:46:13.9714 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-09-24 19:46:13.9714 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-09-24 19:46:13.9714 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-09-24 19:46:13.9714 Debug Execution plan of exception filters (in the following order): None 
2019-09-24 19:46:13.9714 Debug Execution plan of exception filters (in the following order): None 
2019-09-24 19:46:13.9714 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-09-24 19:46:13.9714 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-09-24 19:46:13.9714 Info Authorization was successful. 
2019-09-24 19:46:13.9714 Info Authorization was successful. 
2019-09-24 19:46:13.9714 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-09-24 19:46:13.9714 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-09-24 19:46:13.9714 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2019-09-24 19:46:13.9714 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2019-09-24 19:46:13.9714 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json'. 
2019-09-24 19:46:13.9714 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json'. 
2019-09-24 19:46:13.9874 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'. 
2019-09-24 19:46:13.9874 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'. 
2019-09-24 19:46:13.9874 Debug Connection id "0HLQ0VRBHFAEU", Request id "0HLQ0VRBHFAEU:00000001": started reading request body. 
2019-09-24 19:46:13.9874 Debug Connection id "0HLQ0VRBHFAEU", Request id "0HLQ0VRBHFAEU:00000001": started reading request body. 
2019-09-24 19:46:13.9874 Debug Connection id "0HLQ0VRBHFAEU", Request id "0HLQ0VRBHFAEU:00000001": done reading request body. 
2019-09-24 19:46:13.9874 Debug Connection id "0HLQ0VRBHFAEU", Request id "0HLQ0VRBHFAEU:00000001": done reading request body. 
2019-09-24 19:46:13.9874 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-09-24 19:46:13.9874 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-09-24 19:46:13.9874 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-09-24 19:46:13.9874 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-09-24 19:46:13.9874 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-09-24 19:46:13.9874 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-09-24 19:46:13.9874 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-09-24 19:46:13.9874 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-09-24 19:46:13.9874 Info Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid 
2019-09-24 19:46:13.9874 Info Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid 
2019-09-24 19:46:13.9874 Debug WebClient(HttpWebClient).GetString(Url:http://bitspyder.net/processid.php) 
2019-09-24 19:46:15.1021 Debug WebClient(HttpWebClient): Returning OK =>  
2019-09-24 19:46:15.1021 Debug CardigannIndexer (bitspyder): Cookies after login:  
2019-09-24 19:46:15.1021 Debug WebClient(HttpWebClient).GetString(Url:http://bitspyder.net/browse.php) 
2019-09-24 19:46:15.8827 Debug WebClient(HttpWebClient): Returning Redirect => http://bitspyder.net/login.php?returnto=%2Fbrowse.php  
2019-09-24 19:46:15.8827 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) in 1904.7172ms 
2019-09-24 19:46:15.8827 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (JackettConsole) in 1904.7172ms 
2019-09-24 19:46:15.8827 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.<TestLogin>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.CardigannIndexer.<ApplyConfiguration>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Controllers.IndexerApiController.<UpdateConfig>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext() Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.<TestLogin>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.CardigannIndexer.<ApplyConfiguration>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Controllers.IndexerApiController.<UpdateConfig>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Server.Middleware.CustomExceptionHandler.<Invoke>d__3.MoveNext()
2019-09-24 19:46:15.8977 Debug The response will be compressed with 'gzip'. 
2019-09-24 19:46:15.8977 Debug The response will be compressed with 'gzip'. 
2019-09-24 19:46:15.8977 Debug Connection id "0HLQ0VRBHFAEU" completed keep alive response. 
2019-09-24 19:46:15.8977 Debug Connection id "0HLQ0VRBHFAEU" completed keep alive response. 
2019-09-24 19:46:15.8977 Info Request finished in 1942.0878ms 500 application/json 
2019-09-24 19:46:15.8977 Info Request finished in 1942.0878ms 500 application/json 
2019-09-24 19:46:16.7533 Debug Connection id "0HLQ0VRBHFAEU" received FIN. 
2019-09-24 19:46:16.7533 Debug Connection id "0HLQ0VRBHFAEU" received FIN. 
2019-09-24 19:46:16.7533 Debug Connection id "0HLQ0VRBHFAEU" disconnecting. 
2019-09-24 19:46:16.7533 Debug Connection id "0HLQ0VRBHFAEU" disconnecting. 
2019-09-24 19:46:16.7533 Debug Connection id "0HLQ0VRBHFAEU" sending FIN because: "The client closed the connection." 
2019-09-24 19:46:16.7533 Debug Connection id "0HLQ0VRBHFAEU" sending FIN because: "The client closed the connection." 
2019-09-24 19:46:16.7533 Debug Connection id "0HLQ0VRBHFAEU" stopped. 
2019-09-24 19:46:16.7533 Debug Connection id "0HLQ0VRBHFAEU" stopped. 
```

-------------------------------

**Comment by garfield69** [comment]
the logs you provided shows that after the processid.php call the site returned an empty page and no cookies, so the following attempt to access the browse.php was rejected.
unfortunately I dont have an account on bitspyder so I can dig deeper myself.
assigning to the c# devs as I cannot help with this one.

**Comment by killerqueen619** [comment]
@garfield69 where i can sent the login?

**Comment by garfield69** [comment]
thanks for the a/c loan.
jackett 0.11.797 should fix.

**Comment by killerqueen619** [comment]
bro where u from
u are online 24hours lmao

Pada tanggal Kam, 10 Okt 2019 pukul 15.05 garfield69 <
notifications@github.com> menulis:
