### ISSUE TITLE
YGG domain changed

### ISSUE THREAD

**Issue by VictorJ76** [Jackett/Jackett#6039]
YGG has just completed a change of management and domain.
The new website is now at https://www.yggtorrent.pe/.

**Comment by garfield69** [comment]
thanks. but you are about 6 hours out of date ;-]
jackett 0.11.723 has the latest indexer update which will take care of setting up new yggtorrent indexer configs.
However for the existing yggtorrent config, you will still need to manually update your yggtorrent indexer to correct the urls which may still be using .ch
Also note that clicking OKAY may generate an error, so you may need to click CLOSE, and edit again. it should save the second time around.

**Comment by garfield69** [comment]
for those that need more info, the new domain urls for the yggtorrent indexer are as follows:
![image](https://user-images.githubusercontent.com/6933240/65577329-b0d8e080-dfc7-11e9-9d8a-cf38cf8b3b9d.png)

**Comment by VictorJ76** [comment]
My bad. Thank you.

**Comment by albttx** [comment]
@garfield69 Just download the last version,
It's worked, but when i test i have 

```
An error occured while testing this indexer
Found no results while trying to browse this tracker
```

did you ?

**Comment by garfield69** [comment]
works for me.

**Comment by garfield69** [comment]
for those that still cannot figure out how to get yggtorrent working on the new domain, here are  detailed step by step instructions:
1. access your jackett dashboard and use the wrench icon to edit your yggtorrent indexer config.
2. set the **Site Link** to `https://www.yggtorrent.pe/` and 
3. set the **Search and download URL** to `www2.yggtorrent.pe`
4. Click **OKAY**
5. if you get an error, click **CLOSE** then edit again and click OKAY. it should save the second time.

**Comment by timothe** [comment]
This is working for me, thanks @garfield69

**Comment by H3r3zy** [comment]
don't work for me, always the same error

**Comment by garfield69** [comment]
@H3r3zy  need to see your enhanced logs to determine what might be going on
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by GhostPyxel** [comment]
Keep getting the recurrent error: 

> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.pe/ using form selector #user-login

I've already tried differents URL possibles with the fields **Site Link** (`https://www.yggtorrent.pe/` by default) and **Search and download URL** (`www2.yggtorrent.pe` by default) but without success.

I cannot provide log file for now but I'll do tomorrow if nobody have shared one.

**Comment by bossovitch** [comment]
Hi
I've the same problem, here is my log.txt
[log.txt](https://github.com/Jackett/Jackett/files/3683511/log.txt)

**Comment by garfield69** [comment]
@bossovitch   the logs show `Relogin required` after the login attempt.
the following message `Login failed: No form found on https://www.yggtorrent.pe/ using form selector #user-login` is just Jacketts way of saying: "I give up, your login failed but none of the usual error message traps were triggered".

Usually, this implies something wrong with your ygg account or possibly with the credentials on the jackett yggtorrent config.

Please use your Browser to login to yggtorrent directly, and check that you have a good Ratio, and no outstanding alerts or messages or emails that could interfere with presenting the torrent search page after logon.

if it all looks good, then edit your yggtorrent config and reenter your username and password and try again.

if you still cannot get it to work then I cannot help you further because I don't know why it would not work for you when it works for countless others.

**Comment by HDebeuf** [comment]
Doesn't work for me either.
Logging in manually through Ygg goes like a charm, but through Jackett, none of the above workarounds helped.

Here is an Enhanced log 👍 
```
2019-10-03 10:07:32.4213 Info Request starting HTTP/1.1 GET http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config?_=1570089985332   
2019-10-03 10:07:32.4213 Debug Request is continuing in applying rules. Current url is http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config?_=1570089985332 
2019-10-03 10:07:32.4220 Debug Request is continuing in applying rules. Current url is http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config?_=1570089985332 
2019-10-03 10:07:32.4220 Debug Request is continuing in applying rules. Current url is http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config?_=1570089985332 
2019-10-03 10:07:32.4220 Debug The request path /api/v2.0/indexers/yggtorrent/config does not match a supported file type 
2019-10-03 10:07:32.4230 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-10-03 10:07:32.4230 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerId?}/Config' 
2019-10-03 10:07:32.4240 Debug Action 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with id 'af5acd04-aeb8-4aa2-9209-851525c99692' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
2019-10-03 10:07:32.4240 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Config (jackett) 
2019-10-03 10:07:32.4240 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-10-03 10:07:32.4249 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-03 10:07:32.4249 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-10-03 10:07:32.4249 Debug Execution plan of exception filters (in the following order): None 
2019-10-03 10:07:32.4249 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-03 10:07:32.4249 Info Authorization was successful. 
2019-10-03 10:07:32.4260 Info Executing action method Jackett.Server.Controllers.IndexerApiController.Config (jackett) - Validation state: Valid 
2019-10-03 10:07:32.4260 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://www.yggtorrent.pe/) 
2019-10-03 10:07:32.4517 Debug __cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; expires=Fri, 02-Oct-20 08:07:32 GMT; path=/; domain=.yggtorrent.pe; HttpOnly; Secure 
2019-10-03 10:07:32.4523 Debug ca_=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; path=/ 
2019-10-03 10:07:32.4523 Debug WebClient(HttpWebClient2NetCore): Returning TemporaryRedirect => http://www.yggtorrent.pe/?attempt=1 <html>
<head><title>307 Temporary Redirect</title></head>
<body bgcolor="white">
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>
 
2019-10-03 10:07:32.4531 Debug updating Cookies  => __cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; ca_=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
2019-10-03 10:07:32.4540 Info Executed action method Jackett.Server.Controllers.IndexerApiController.Config (jackett), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 27.8085ms. 
2019-10-03 10:07:32.4540 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter 
2019-10-03 10:07:32.4540 Debug No information found on request to perform content negotiation. 
2019-10-03 10:07:32.4540 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response. 
2019-10-03 10:07:32.4549 Debug Attempting to select the first formatter in the output formatters list which can write the result. 
2019-10-03 10:07:32.4549 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response. 
2019-10-03 10:07:32.4549 Info Executing ObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'. 
2019-10-03 10:07:32.4549 Debug The response will be compressed with 'gzip'. 
2019-10-03 10:07:32.4549 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 29.8603ms 
2019-10-03 10:07:32.4549 Debug Connection id "XXXXXXXXXXXXX" completed keep alive response. 
2019-10-03 10:07:32.4559 Info Request finished in 34.6045ms 200 application/json; charset=utf-8 
2019-10-03 10:07:37.0992 Info Request starting HTTP/1.1 POST http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config application/json 918 
2019-10-03 10:07:37.0992 Debug Request is continuing in applying rules. Current url is http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config 
2019-10-03 10:07:37.0999 Debug Request is continuing in applying rules. Current url is http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config 
2019-10-03 10:07:37.0999 Debug Request is continuing in applying rules. Current url is http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config 
2019-10-03 10:07:37.0999 Debug POST requests are not supported 
2019-10-03 10:07:37.0999 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-10-03 10:07:37.0999 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerId?}/Config' 
2019-10-03 10:07:37.0999 Debug Action 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with id '8e0255d6-7cc1-465f-bb2f-adcdbf774e42' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
2019-10-03 10:07:37.1010 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) 
2019-10-03 10:07:37.1010 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-10-03 10:07:37.1010 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-03 10:07:37.1010 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-10-03 10:07:37.1010 Debug Execution plan of exception filters (in the following order): None 
2019-10-03 10:07:37.1010 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-03 10:07:37.1020 Info Authorization was successful. 
2019-10-03 10:07:37.1020 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-10-03 10:07:37.1020 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2019-10-03 10:07:37.1020 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json'. 
2019-10-03 10:07:37.1020 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'. 
2019-10-03 10:07:37.1020 Debug Connection id "XXXXXXXXXXXXX", Request id "XXXXXXXXXXXXX:0000000B": started reading request body. 
2019-10-03 10:07:37.1029 Debug Connection id "XXXXXXXXXXXXX", Request id "XXXXXXXXXXXXX:0000000B": done reading request body. 
2019-10-03 10:07:37.1029 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-10-03 10:07:37.1029 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-10-03 10:07:37.1029 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-10-03 10:07:37.1029 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-10-03 10:07:37.1029 Info Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid 
2019-10-03 10:07:37.1044 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 2.5303ms 
2019-10-03 10:07:37.1044 Error Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.pe/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 869
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.pe/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 869
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
2019-10-03 10:07:37.1070 Debug The response will be compressed with 'gzip'. 
2019-10-03 10:07:37.1070 Debug Connection id "XXXXXXXXXXXXX" completed keep alive response. 
2019-10-03 10:07:37.1070 Info Request finished in 8.3168ms 500 application/json 
2019-10-03 10:07:38.7906 Info Request starting HTTP/1.1 POST http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config application/json 918 
2019-10-03 10:07:38.7913 Debug Request is continuing in applying rules. Current url is http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config 
2019-10-03 10:07:38.7913 Debug Request is continuing in applying rules. Current url is http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config 
2019-10-03 10:07:38.7913 Debug Request is continuing in applying rules. Current url is http://x.x.x.x:9117/api/v2.0/indexers/yggtorrent/config 
2019-10-03 10:07:38.7913 Debug POST requests are not supported 
2019-10-03 10:07:38.7922 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-10-03 10:07:38.7922 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerId?}/Config' 
2019-10-03 10:07:38.7922 Debug Action 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with id '8e0255d6-7cc1-465f-bb2f-adcdbf774e42' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
2019-10-03 10:07:38.7930 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) 
2019-10-03 10:07:38.7930 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-10-03 10:07:38.7930 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-03 10:07:38.7930 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-10-03 10:07:38.7930 Debug Execution plan of exception filters (in the following order): None 
2019-10-03 10:07:38.7930 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-03 10:07:38.7930 Info Authorization was successful. 
2019-10-03 10:07:38.7940 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-10-03 10:07:38.7940 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2019-10-03 10:07:38.7940 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json'. 
2019-10-03 10:07:38.7940 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'. 
2019-10-03 10:07:38.7940 Debug Connection id "XXXXXXXXXXXXX", Request id "XXXXXXXXXXXXX:0000000C": started reading request body. 
2019-10-03 10:07:38.7940 Debug Connection id "XXXXXXXXXXXXX", Request id "XXXXXXXXXXXXX:0000000C": done reading request body. 
2019-10-03 10:07:38.7940 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-10-03 10:07:38.7950 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-10-03 10:07:38.7950 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-10-03 10:07:38.7950 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-10-03 10:07:38.7950 Info Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid 
2019-10-03 10:07:38.7962 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 2.5084ms 
2019-10-03 10:07:38.7962 Error Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.pe/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 869
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.pe/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 869
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
2019-10-03 10:07:38.7992 Debug The response will be compressed with 'gzip'. 
2019-10-03 10:07:38.7992 Debug Connection id "XXXXXXXXXXXXX" completed keep alive response. 
2019-10-03 10:07:38.7992 Info Request finished in 9.2854ms 500 application/json 
```

Thank you.

Best regards,

Hendrik

**Comment by ayu69** [comment]
Same problem for me ...

I used the Version 0.11.760.0 on docker.

Exception (yggtorrent): Login failed: No form found on https://www.yggtorrent.pe/ using form selector #user-login: Parse error

**Comment by RH2WTF** [comment]
Hello there,
i have the same problem on my side
Every test are realised 
- on version v0.11.768 and v0.11.760
- on Docker (Linux) and Windows
- Without Proxy or VPN for not interfered
- On 3 different internet connexion

the same problem appears that we put a login pwd or not
I have no problem connecting directly to the site
My account and the download is not blocked. Tested a few minutes ago.


=====================
NO PROXY or VPN for the test
=====================
![1 - NO Proxy or VPN](https://user-images.githubusercontent.com/56117408/66125094-64ecf380-e5e6-11e9-8809-7b65f80dffe8.png)

=====================
Test Docker Error WITHOUT Login Pwd 
=====================
![2 - Docker Error WITHOUT Login Pwd](https://user-images.githubusercontent.com/56117408/66125098-674f4d80-e5e6-11e9-9119-6ea3e2d44d8c.PNG)

=====================
Error in the log after that
=====================
![3 - Docker Error](https://user-images.githubusercontent.com/56117408/66125100-68807a80-e5e6-11e9-8b8a-b12bda81ce0a.PNG)


=====================
Same Test on Windows WITHOUT Login Pwd 
=====================
![4 - Windows Error Without Login Pwd](https://user-images.githubusercontent.com/56117408/66125104-6b7b6b00-e5e6-11e9-9e28-7b5dae4db805.PNG)

=====================
Error in the log after that
=====================
![5 - Windows Error](https://user-images.githubusercontent.com/56117408/66125110-6cac9800-e5e6-11e9-9a03-a1d099b01f3d.PNG)
=====================

thank you in advance

**Comment by timothe** [comment]
It stopped working for me as well. I don’t have the logs right now but I get the same issue as others here above. 
Will communicate them ASAP

**Comment by thelouisvivier** [comment]
I have the same issue. My account is not blocked. I put the new links in the config pan. Here's my logs if you see something interesting... 
Jackett Version 0.11.760.0
Env : Docker on a Synology NAS. [Container](https://hub.docker.com/r/linuxserver/jackett/)
[log.txt](https://github.com/Jackett/Jackett/files/3687050/log.txt)

Thanks for your help !

**Comment by dylannla** [comment]
Yeah it stop working for me as well. Same error and same logs.

**Comment by yoyecros** [comment]
Same error and logs for me.

**Comment by GhostPyxel** [comment]
Here's my log as promised yesterday. 
Issue can be reproduced with theses settings

![Screenshot_1](https://user-images.githubusercontent.com/52525576/66151135-fb390d80-e616-11e9-8993-fee28eeb901f.jpg)

Tested with the default settings on the lastest version of Jackett, account is above ratio and can download. My setup is based on a Synology without Docker.

If you need further informations, tag me.

[log.txt](https://github.com/Jackett/Jackett/files/3687390/log.txt)

**Comment by makz27** [comment]
Same error here, login works on web browser and account is ok

v0.11.768

(cropped log, only the action "okay" is there)
[log.txt](https://github.com/Jackett/Jackett/files/3689439/log.txt)

**Comment by Bastien42** [comment]
and me too +1

**Comment by Jahislove** [comment]
same error for me +1

**Comment by yp6128** [comment]
Same here :)
+1

**Comment by MrSkarmin** [comment]
Same for me :( +1

**Comment by RH2WTF** [comment]
Topic Open Here #6086

**Comment by garfield69** [comment]
YGGTorrent changed domain yet again.

so new instructions to get your YGGTorrent indexer going again:
1. access your jackett dashboard and use the wrench icon to edit your yggtorrent indexer config.
2. set the **Site Link** to `https://www3.yggtorrent.pe/` and 
3. set the **Search and download URL** to `www2.yggtorrent.pe`
4. Click **OKAY**
5. if you get an error, click **CLOSE** then edit again and click OKAY. it should save the second time.

**Comment by Jahislove** [comment]
and how can we ADD yggtorrent indexer , if we have delete the old one ?

**Comment by Jahislove** [comment]
forget it , it's ok on second try

**Comment by timothe** [comment]
Works for me with the latest urls guys, thank you very much 😊
