### ISSUE TITLE
CloudFlare problems blocking KAT and other sites.

### ISSUE THREAD

**Issue by TimeToFixStuff** [Jackett/Jackett#6099]
I don't see issues with unresolved status that are complaining about the 30-attempt cloudflare errors that I am seeing. I updates my docker to development branch and it's still not working. The version at the bottom is 0.11.768.0

I can't get to KAT sites as well as several others. Tests fail, but the sites are operational and working. Attempts to manually use Jackett with those sites also fails.

Jackett.Common.IndexerException: Exception (kickasstorrent-kathow): Clearance failed after 30 attempt(s). ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 445
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1238
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 815
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
the 30 attempts failed message is a result of the web site you are trying to access via jackett having enabled the cloudflare service provider's  anti-DDoS re-captcha challenge (the one that has you clicking on multiple pictures to prove you are not a robot) for your IP block.

the 30-attempts-failed is the jackett's cloudflareResolver utililites library's way of saying "I give up".
it replaces the previous cloudflareUtilities library which used to post 
```
(Error Forbidden) - The page is protected by an Cloudflare reCaptcha. The page is in aggressive DDoS mitigation mode or your IP might be blacklisted (e.g. in case of shared VPN IPs). There's no easy way of making it usable with Jackett.
```
but which could not even solve the most basic cloudflare challenges. 
At least the cloudflareResolve can pass the basic challenges, but there is still no solution for the re-Captcha cloudflare challenges.
Nothing jackett can do about this currently.

**Comment by TimeToFixStuff** [comment]
I would like to suggest having a pass-through option. A button on the Jackett page that I can click, which would hit the site and allow me to do the captcha myself. The thinking is that if I do it once, the calling application (Sonarr) will be able to use the Cloudflare-blocked site for a while.

**Comment by garfield69** [comment]
re-opened as enhancement request.

**Comment by rrrevin** [comment]
> I would like to suggest having a pass-through option. A button on the Jackett page that I can click, which would hit the site and allow me to do the captcha myself. The thinking is that if I do it once, the calling application (Sonarr) will be able to use the Cloudflare-blocked site for a while.

Interesting, you should be able to test this yourself and see if it should even move on to coding stage.
1) From outside of Jackett, do the manual recaptcha yourself.
2) Then try Jackett.
3) If Jackett fails, then this approach might never work. Stop.
4) If Jackett gets through, because you manually triggered the recaptcha move onto (5). 
5) CLEAR your web cache (cookies and cache.. all of them) and try Jackett again.
6) If it fails, we can say with confidence this probably depends on cookies, which means this might never work reliably as a cookie must be in place. (a)
7) If it works, then the theory of somehow manually triggering the CF recaptcha _might_ work.
8) Coding might be possible at this point. (b)

a :  Jackett doesn't create/update/delete with cookies.  I understand the "start" browser in a window button.. but what about headless systems? How do you kick off a browser on a headless system that you've remoted into?
b : What about "headless" systems again?

Thoughts?

**Comment by garfield69** [comment]
Jackett 0.14.222
