### ISSUE TITLE
After installing OpenSSL Pyssl and LXML I cant access any trackers

### ISSUE THREAD

**Issue by sethwarsh** [Jackett/Jackett#61]
I added oppenssl and pyopenssl and lxml per your suggestions to get Pass the Popcorn and Scene Access to work and now I can access any torrent or newsbin provider.

Please  help me resolver this issue on my end, tell me what I should do. Here are some of the debug info I have been getting.  I know this is for feature requests but it's also for issues. Please give me some assistance with solving my problem, I have nowhere else to turn to.

Thank you Seth

### Information:
Movie(s) I have this with: Several
Quality of the movie being searched Many
Providers I use: Several Torren an Newsbin
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) e6fa8b8b (2015-10-04 16:13:08)
Running on: OSX

### Logs:
```
11-17 08:02:12 ERROR [   couchpotato.core.event] Error in event "download.status", that wasn't caught: Traceback (most recent call last):
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/event.py", line 15, in runHandler
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/_base/downloader/main.py", line 84, in _getAllDownloadStatus
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/downloaders/transmission.py", line 125, in getAllDownloadStatus
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/downloaders/transmission.py", line 33, in connect
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/downloaders/transmission.py", line 211, in __init__
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/downloaders/transmission.py", line 254, in get_session
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/downloaders/transmission.py", line 218, in _request
  File "urllib2.pyc", line 154, in urlopen
  File "urllib2.pyc", line 431, in open
  File "urllib2.pyc", line 449, in _open
  File "urllib2.pyc", line 409, in _call_chain
  File "urllib2.pyc", line 1227, in http_open
  File "urllib2.pyc", line 1200, in do_open
  File "httplib.pyc", line 1132, in getresponse
  File "httplib.pyc", line 453, in begin
  File "httplib.pyc", line 409, in _read_status
  File "socket.pyc", line 480, in readline
timeout: timed out
 
```

Running on: ...

### Logs:
```
11-17 08:05:14 ERROR [hpotato.core.plugins.base] Failed opening url in TorrentBytes: https://www.torrentbytes.net/browse.php?search=the+intern+2015&cat=19 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www.torrentbytes.net', port=443): Read timed out. (read timeout=30)
 
```

```
11-17 08:08:37 ERROR [hpotato.core.plugins.base] Failed opening url in TorrentBytes: https://www.torrentbytes.net/browse.php?search=the+perfect+guy+2015&cat=5 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www.torrentbytes.net', port=443): Read timed out. (read timeout=30

-------------
```
11-16 23:37:08 ERROR [hpotato.core.plugins.base] Failed opening url in TorrentBytes: https://www.torrentbytes.net/browse.php?search=bridge+of+spies+2015&cat=5 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www.torrentbytes.net', port=443): Read timed out. (read timeout=30)
 
---------------

```
11-17 08:17:38 ERROR [viders.torrent.alpharatio] Failed to parsing AlphaRatio: Traceback (most recent call last):
  File "/Applications/CouchPotatoServer/couchpotato/core/media/_base/providers/torrent/alpharatio.py", line 45, in _search
    size = tds[4].contents[0].strip('\n ')
TypeError: 'NoneType' object is not callable

**Comment by sethwarsh** [comment]
resolved by uninstalling lxml now i only have an issue logging into two trackers
