### ISSUE TITLE
[alpharatio] Request to https://alpharatio.cc/login.php failed (Error 523) - The tracker seems to be down. (Config)

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#6113]
Hi, I'm on latest Jackett but I got some error on log-in via Jackett.

Via browser no problem.
Here the full log:
```
2019-10-07 16:23:54.8118 Debug Connection id "0HLQ7LTGB9N2D" started. 
2019-10-07 16:23:54.8118 Info Request starting HTTP/1.1 GET http://localhost:9117/dl/shareisland/?jackett_apikey=jatowf87jwethkioz66lpn64hen1awr8&path=Q2ZESjhIOTlRbnNBaTlsTXBueG41dVNtYWFoM1VUVFpjcjFKMkhiOWs2cVdVSjEwRnRtTW1YMHk5bUh4Q1JuQmtUUTIzMkJLcFIwV0NncURkZ2pYTkthVlFSUC1jVEtlVmFxSE9tR3lVYm54bHVFbTNXSVdiclRrME9rWWxkYi16dmtiTEowUzRCTUtpcTduZWF6RTN6MDJJNllSSEpiYy12WFB1Nl9TeTliUHFrUGw3VnAyRFVYQ1ZYVGNPREtFMXI5LV9fczBXMnBhdW1tTWMxWUtXYjBMRm1PNmNKeFNjY0FkQWhQcHhkV01mXzM3S3FLVnF2ajRkaWtZNEFFdGdlekpKNFBQclpvR01vZEVuSmgxNWQyZmVwTkFhcjZvclZtdW5KNDB1MlRydzBpQVRyeGg1SzNiN3hUWDBRY2dhRGxadUE&file=Il+sole+e+anche+una+stella+2019+ITA+ENG+WEBDL+1080p+CB01HD+mkv   
2019-10-07 16:23:54.8139 Debug Request is continuing in applying rules. Current url is http://localhost:9117/dl/shareisland/?jackett_apikey=jatowf87jwethkioz66lpn64hen1awr8&path=Q2ZESjhIOTlRbnNBaTlsTXBueG41dVNtYWFoM1VUVFpjcjFKMkhiOWs2cVdVSjEwRnRtTW1YMHk5bUh4Q1JuQmtUUTIzMkJLcFIwV0NncURkZ2pYTkthVlFSUC1jVEtlVmFxSE9tR3lVYm54bHVFbTNXSVdiclRrME9rWWxkYi16dmtiTEowUzRCTUtpcTduZWF6RTN6MDJJNllSSEpiYy12WFB1Nl9TeTliUHFrUGw3VnAyRFVYQ1ZYVGNPREtFMXI5LV9fczBXMnBhdW1tTWMxWUtXYjBMRm1PNmNKeFNjY0FkQWhQcHhkV01mXzM3S3FLVnF2ajRkaWtZNEFFdGdlekpKNFBQclpvR01vZEVuSmgxNWQyZmVwTkFhcjZvclZtdW5KNDB1MlRydzBpQVRyeGg1SzNiN3hUWDBRY2dhRGxadUE&file=Il+sole+e+anche+una+stella+2019+ITA+ENG+WEBDL+1080p+CB01HD+mkv 
2019-10-07 16:23:54.8187 Debug Request is continuing in applying rules. Current url is http://localhost:9117/dl/shareisland/?jackett_apikey=jatowf87jwethkioz66lpn64hen1awr8&path=Q2ZESjhIOTlRbnNBaTlsTXBueG41dVNtYWFoM1VUVFpjcjFKMkhiOWs2cVdVSjEwRnRtTW1YMHk5bUh4Q1JuQmtUUTIzMkJLcFIwV0NncURkZ2pYTkthVlFSUC1jVEtlVmFxSE9tR3lVYm54bHVFbTNXSVdiclRrME9rWWxkYi16dmtiTEowUzRCTUtpcTduZWF6RTN6MDJJNllSSEpiYy12WFB1Nl9TeTliUHFrUGw3VnAyRFVYQ1ZYVGNPREtFMXI5LV9fczBXMnBhdW1tTWMxWUtXYjBMRm1PNmNKeFNjY0FkQWhQcHhkV01mXzM3S3FLVnF2ajRkaWtZNEFFdGdlekpKNFBQclpvR01vZEVuSmgxNWQyZmVwTkFhcjZvclZtdW5KNDB1MlRydzBpQVRyeGg1SzNiN3hUWDBRY2dhRGxadUE&file=Il+sole+e+anche+una+stella+2019+ITA+ENG+WEBDL+1080p+CB01HD+mkv 
2019-10-07 16:23:54.8187 Debug Request is continuing in applying rules. Current url is http://localhost:9117/dl/shareisland/?jackett_apikey=jatowf87jwethkioz66lpn64hen1awr8&path=Q2ZESjhIOTlRbnNBaTlsTXBueG41dVNtYWFoM1VUVFpjcjFKMkhiOWs2cVdVSjEwRnRtTW1YMHk5bUh4Q1JuQmtUUTIzMkJLcFIwV0NncURkZ2pYTkthVlFSUC1jVEtlVmFxSE9tR3lVYm54bHVFbTNXSVdiclRrME9rWWxkYi16dmtiTEowUzRCTUtpcTduZWF6RTN6MDJJNllSSEpiYy12WFB1Nl9TeTliUHFrUGw3VnAyRFVYQ1ZYVGNPREtFMXI5LV9fczBXMnBhdW1tTWMxWUtXYjBMRm1PNmNKeFNjY0FkQWhQcHhkV01mXzM3S3FLVnF2ajRkaWtZNEFFdGdlekpKNFBQclpvR01vZEVuSmgxNWQyZmVwTkFhcjZvclZtdW5KNDB1MlRydzBpQVRyeGg1SzNiN3hUWDBRY2dhRGxadUE&file=Il+sole+e+anche+una+stella+2019+ITA+ENG+WEBDL+1080p+CB01HD+mkv 
2019-10-07 16:23:54.8187 Debug The request path /dl/shareisland/ does not match a supported file type 
2019-10-07 16:23:54.8187 Debug AuthenticationScheme: Cookies was not authenticated. 
2019-10-07 16:23:54.8187 Debug Request successfully matched the route with name '(null)' and template 'dl/{indexerID}' 
2019-10-07 16:23:54.8218 Info Route matched with {action = "Download", controller = "Download"}. Executing action Jackett.Server.Controllers.DownloadController.Download (jackett) 
2019-10-07 16:23:54.8218 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-10-07 16:23:54.8218 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-07 16:23:54.8218 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter 
2019-10-07 16:23:54.8218 Debug Execution plan of exception filters (in the following order): None 
2019-10-07 16:23:54.8218 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-07 16:23:54.8297 Debug Attempting to bind parameter 'indexerID' of type 'System.String' ... 
2019-10-07 16:23:54.8297 Debug Attempting to bind parameter 'indexerID' of type 'System.String' using the name 'indexerID' in request data ... 
2019-10-07 16:23:54.8297 Debug Done attempting to bind parameter 'indexerID' of type 'System.String'. 
2019-10-07 16:23:54.8297 Debug Done attempting to bind parameter 'indexerID' of type 'System.String'. 
2019-10-07 16:23:54.8297 Debug Attempting to validate the bound parameter 'indexerID' of type 'System.String' ... 
2019-10-07 16:23:54.8338 Debug Done attempting to validate the bound parameter 'indexerID' of type 'System.String'. 
2019-10-07 16:23:54.8390 Debug Attempting to bind parameter 'path' of type 'System.String' ... 
2019-10-07 16:23:54.8390 Debug Attempting to bind parameter 'path' of type 'System.String' using the name 'path' in request data ... 
2019-10-07 16:23:54.8390 Debug Done attempting to bind parameter 'path' of type 'System.String'. 
2019-10-07 16:23:54.8390 Debug Done attempting to bind parameter 'path' of type 'System.String'. 
2019-10-07 16:23:54.8415 Debug Attempting to validate the bound parameter 'path' of type 'System.String' ... 
2019-10-07 16:23:54.8415 Debug Done attempting to validate the bound parameter 'path' of type 'System.String'. 
2019-10-07 16:23:54.8415 Debug Attempting to bind parameter 'jackett_apikey' of type 'System.String' ... 
2019-10-07 16:23:54.8488 Debug Attempting to bind parameter 'jackett_apikey' of type 'System.String' using the name 'jackett_apikey' in request data ... 
2019-10-07 16:23:54.8495 Debug Done attempting to bind parameter 'jackett_apikey' of type 'System.String'. 
2019-10-07 16:23:54.8495 Debug Done attempting to bind parameter 'jackett_apikey' of type 'System.String'. 
2019-10-07 16:23:54.8495 Debug Attempting to validate the bound parameter 'jackett_apikey' of type 'System.String' ... 
2019-10-07 16:23:54.8495 Debug Done attempting to validate the bound parameter 'jackett_apikey' of type 'System.String'. 
2019-10-07 16:23:54.8495 Debug Attempting to bind parameter 'file' of type 'System.String' ... 
2019-10-07 16:23:54.8495 Debug Attempting to bind parameter 'file' of type 'System.String' using the name 'file' in request data ... 
2019-10-07 16:23:54.8567 Debug Done attempting to bind parameter 'file' of type 'System.String'. 
2019-10-07 16:23:54.8567 Debug Done attempting to bind parameter 'file' of type 'System.String'. 
2019-10-07 16:23:54.8577 Debug Attempting to validate the bound parameter 'file' of type 'System.String' ... 
2019-10-07 16:23:54.8577 Debug Done attempting to validate the bound parameter 'file' of type 'System.String'. 
2019-10-07 16:23:54.8705 Info Executing action method Jackett.Server.Controllers.DownloadController.Download (jackett) with arguments (shareisland, Q2ZESjhIOTlRbnNBaTlsTXBueG41dVNtYWFoM1VUVFpjcjFKMkhiOWs2cVdVSjEwRnRtTW1YMHk5bUh4Q1JuQmtUUTIzMkJLcFIwV0NncURkZ2pYTkthVlFSUC1jVEtlVmFxSE9tR3lVYm54bHVFbTNXSVdiclRrME9rWWxkYi16dmtiTEowUzRCTUtpcTduZWF6RTN6MDJJNllSSEpiYy12WFB1Nl9TeTliUHFrUGw3VnAyRFVYQ1ZYVGNPREtFMXI5LV9fczBXMnBhdW1tTWMxWUtXYjBMRm1PNmNKeFNjY0FkQWhQcHhkV01mXzM3S3FLVnF2ajRkaWtZNEFFdGdlekpKNFBQclpvR01vZEVuSmgxNWQyZmVwTkFhcjZvclZtdW5KNDB1MlRydzBpQVRyeGg1SzNiN3hUWDBRY2dhRGxadUE, jatowf87jwethkioz66lpn64hen1awr8, Il sole e anche una stella 2019 ITA ENG WEBDL 1080p CB01HD mkv) - Validation state: Valid 
2019-10-07 16:23:54.8705 Debug WebClient(HttpWebClient2NetCore).GetBytes(Url:https://shareisland.org/download.php?id=2b2151d74d8f94f37b0878dc1adf961a0d36d93b&f=Il.sole.e.anche.una.stella.2019.ITA-ENG.WEBDL.1080p.CB01HD.mkv.torrent) 
2019-10-07 16:23:55.1210 Debug WebClient(HttpWebClient2NetCore): Returning OK => 9534 bytes 
2019-10-07 16:23:55.1385 Info Executed action method Jackett.Server.Controllers.DownloadController.Download (jackett), returned result Microsoft.AspNetCore.Mvc.FileContentResult in 267.4079ms. 
2019-10-07 16:23:55.1385 Info Executing Microsoft.AspNetCore.Mvc.FileContentResult, sending file with download name 'Il sole e anche una stella 2019 ITA ENG WEBDL 1080p CB01HD mkv.torrent' ... 
2019-10-07 16:23:55.1416 Debug The file result has not been enabled for processing range requests. To enable it, set the property 'EnableRangeProcessing' on the result to 'true'. 
2019-10-07 16:23:55.1416 Debug Response compression is not enabled for the Content-Type 'application/x-bittorrent'. 
2019-10-07 16:23:55.1416 Info Executed action Jackett.Server.Controllers.DownloadController.Download (jackett) in 315.3493ms 
2019-10-07 16:23:55.1502 Info Request finished in 336.9954ms 200 application/x-bittorrent 
2019-10-07 16:23:55.1502 Debug Connection id "0HLQ7LTGB9N2D" disconnecting. 
2019-10-07 16:23:55.1502 Debug Connection id "0HLQ7LTGB9N2D" received FIN. 
2019-10-07 16:23:55.1534 Debug Connection id "0HLQ7LTGB9N2D" sending FIN because: "The Socket transport's send loop completed gracefully." 
2019-10-07 16:23:55.1534 Debug Connection id "0HLQ7LTGB9N2D" stopped. 
2019-10-07 16:24:21.8046 Info Request starting HTTP/1.1 GET http://10.0.0.100:9117/api/v2.0/indexers/alpharatio/config?_=1570458189818   
2019-10-07 16:24:21.8053 Debug Request is continuing in applying rules. Current url is http://10.0.0.100:9117/api/v2.0/indexers/alpharatio/config?_=1570458189818 
2019-10-07 16:24:21.8053 Debug Request is continuing in applying rules. Current url is http://10.0.0.100:9117/api/v2.0/indexers/alpharatio/config?_=1570458189818 
2019-10-07 16:24:21.8053 Debug Request is continuing in applying rules. Current url is http://10.0.0.100:9117/api/v2.0/indexers/alpharatio/config?_=1570458189818 
2019-10-07 16:24:21.8053 Debug The request path /api/v2.0/indexers/alpharatio/config does not match a supported file type 
2019-10-07 16:24:21.8053 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-10-07 16:24:21.8123 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerId?}/Config' 
2019-10-07 16:24:21.8123 Debug Action 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with id '60e54413-9645-46cd-9b3a-6221d45d9ee4' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
2019-10-07 16:24:21.8138 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.Config (jackett) 
2019-10-07 16:24:21.8138 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-10-07 16:24:21.8138 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-07 16:24:21.8138 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-10-07 16:24:21.8138 Debug Execution plan of exception filters (in the following order): None 
2019-10-07 16:24:21.8138 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-07 16:24:21.8177 Info Authorization was successful. 
2019-10-07 16:24:21.8177 Info Executing action method Jackett.Server.Controllers.IndexerApiController.Config (jackett) - Validation state: Valid 
2019-10-07 16:24:21.8177 Info Executed action method Jackett.Server.Controllers.IndexerApiController.Config (jackett), returned result Microsoft.AspNetCore.Mvc.OkObjectResult in 0.7073ms. 
2019-10-07 16:24:21.8177 Debug List of registered output formatters, in the following order: Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter, Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter 
2019-10-07 16:24:21.8177 Debug No information found on request to perform content negotiation. 
2019-10-07 16:24:21.8214 Debug Attempting to select an output formatter without using a content type as no explicit content types were specified for the response. 
2019-10-07 16:24:21.8214 Debug Attempting to select the first formatter in the output formatters list which can write the result. 
2019-10-07 16:24:21.8214 Debug Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter' and content type 'application/json' to write the response. 
2019-10-07 16:24:21.8214 Info Executing ObjectResult, writing value of type 'Newtonsoft.Json.Linq.JArray'. 
2019-10-07 16:24:21.8214 Debug The response will be compressed with 'gzip'. 
2019-10-07 16:24:21.8214 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 7.7891ms 
2019-10-07 16:24:21.8260 Debug Connection id "0HLQ7LTGB9N2A" completed keep alive response. 
2019-10-07 16:24:21.8260 Info Request finished in 22.0257ms 200 application/json; charset=utf-8 
2019-10-07 16:24:41.7860 Info Request starting HTTP/1.1 POST http://10.0.0.100:9117/api/v2.0/indexers/alpharatio/config application/json 576 
2019-10-07 16:24:41.7895 Debug Request is continuing in applying rules. Current url is http://10.0.0.100:9117/api/v2.0/indexers/alpharatio/config 
2019-10-07 16:24:41.7895 Debug Request is continuing in applying rules. Current url is http://10.0.0.100:9117/api/v2.0/indexers/alpharatio/config 
2019-10-07 16:24:41.7895 Debug Request is continuing in applying rules. Current url is http://10.0.0.100:9117/api/v2.0/indexers/alpharatio/config 
2019-10-07 16:24:41.7895 Debug POST requests are not supported 
2019-10-07 16:24:41.7895 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-10-07 16:24:41.7933 Debug Request successfully matched the route with name '(null)' and template 'api/v2.0/indexers/{indexerId?}/Config' 
2019-10-07 16:24:41.7933 Debug Action 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with id '062be321-aed6-47d4-8d02-36d68406f705' did not match the constraint 'Microsoft.AspNetCore.Mvc.Internal.HttpMethodActionConstraint' 
2019-10-07 16:24:41.7933 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) 
2019-10-07 16:24:41.7933 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-10-07 16:24:41.7933 Debug Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-07 16:24:41.7933 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Internal.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-10-07 16:24:41.7933 Debug Execution plan of exception filters (in the following order): None 
2019-10-07 16:24:41.7933 Debug Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter 
2019-10-07 16:24:41.7977 Info Authorization was successful. 
2019-10-07 16:24:41.7977 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-10-07 16:24:41.7977 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2019-10-07 16:24:41.7977 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json'. 
2019-10-07 16:24:41.7977 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'. 
2019-10-07 16:24:41.8016 Debug Connection id "0HLQ7LTGB9N2A", Request id "0HLQ7LTGB9N2A:00000009": started reading request body. 
2019-10-07 16:24:41.8016 Debug Connection id "0HLQ7LTGB9N2A", Request id "0HLQ7LTGB9N2A:00000009": done reading request body. 
2019-10-07 16:24:41.8016 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-10-07 16:24:41.8016 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-10-07 16:24:41.8016 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-10-07 16:24:41.8016 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-10-07 16:24:41.8052 Info Executing action method Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) with arguments (Jackett.Common.Models.DTO.ConfigItem[]) - Validation state: Valid 
2019-10-07 16:24:41.8052 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://alpharatio.cc/login.php) 
2019-10-07 16:24:43.0784 Debug __cfduid=d906fed9539811e414a1821891d0247fc1570458281; expires=Tue, 06-Oct-20 14:24:41 GMT; path=/; domain=.alpharatio.cc; HttpOnly 
2019-10-07 16:24:43.0784 Debug cf_use_ob=0; path=/; expires=Mon, 07-Oct-19 14:25:13 GMT 
2019-10-07 16:24:43.0784 Debug WebClient(HttpWebClient2NetCore): Returning 523 => <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>alpharatio.cc | 523: Origin is unreachable</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>




</head>
<body>
<div id="cf-wrapper">

    

    <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-error-overview">
            <h1>
              
              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">523</span>
              <small class="heading-ray-id">Ray ID: 52208a464a8be8f3 &bull; 2019-10-07 14:24:43 UTC</small>
            </h1>
            <h2 class="cf-subheadline">Origin is unreachable</h2>
        </div><!-- /.error-overview -->
        
        <div class="cf-section cf-highlight cf-status-display">
            <div class="cf-wrapper">
                <div class="cf-columns cols-3">
                  
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-browser"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">You</span>
  <h3 class="cf-status-name">Browser</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-cloud"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">Milan</span>
  <h3 class="cf-status-name">Cloudflare</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-server"></i>
    <i class="cf-icon-status cf-icon-error"></i>
  </div>
  <span class="cf-status-desc">alpharatio.cc</span>
  <h3 class="cf-status-name">Host</h3>
  <span class="cf-status-label">Error</span>
</div>

                </div>
              
            </div>
        </div><!-- /.status-display -->

        <div class="cf-section cf-wrapper">
            <div class="cf-columns two">
                <div class="cf-column">
                    <h2>What happened?</h2>
                    <p>The origin web server is not reachable.</p>
                </div>
              
                <div class="cf-column">
                    <h2>What can I do?</h2>
                          <h5>If you're a visitor of this website:</h5>
      <p>Please try again in a few minutes.</p>

      <h5>If you're the owner of this website:</h5>
      <p><span>Check your DNS Settings. A 523 error means that Cloudflare could not reach your host web server. The most common cause is that your DNS settings are incorrect. Please contact your hosting provider to confirm your origin IP and then make sure the correct IP is listed for your A record in your Cloudflare DNS Settings page.</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171946-Error-523">Additional troubleshooting information here.</a></p>
                </div>
            </div>
              
        </div><!-- /.section -->

        <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>52208a464a8be8f3</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 176.206.22.202</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
</div><!-- /#cf-wrapper -->
</body>
</html>
 
2019-10-07 16:24:43.0978 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 1300.422ms 
2019-10-07 16:24:43.0978 Error System.Exception: Request to https://alpharatio.cc/login.php failed (Error 523) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckTrackerDown(WebClientStringResult response) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 579
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 546
   at Jackett.Common.Indexers.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 77
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 System.Exception: Request to https://alpharatio.cc/login.php failed (Error 523) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.CheckTrackerDown(WebClientStringResult response) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 579
   at Jackett.Common.Indexers.BaseWebIndexer.RequestLoginAndFollowRedirect(String url, IEnumerable`1 data, String cookies, Boolean returnCookiesFromFirstCall, String redirectUrlOverride, String referer, Boolean accumulateCookies) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 546
   at Jackett.Common.Indexers.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 77
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
2019-10-07 16:24:43.1463 Debug The response will be compressed with 'gzip'. 
2019-10-07 16:24:43.1463 Debug Connection id "0HLQ7LTGB9N2A" completed keep alive response. 
2019-10-07 16:24:43.1463 Info Request finished in 1362.0794ms 500 application/json 
```
Any idea?

**Comment by garfield69** [comment]
cloudflare 523 is a genuine issue with the alpharatio site. they must have had an outage.
I tried it just now and it is working for me.
try again and report back.

**Comment by Jorman** [comment]
Yep you right, now works.

Thanks
