### ISSUE TITLE
LinuxARM32.tar.gz does not start in version v0.11.802

### ISSUE THREAD

**Issue by saxicek** [Jackett/Jackett#6157]
The latest Jackett does not start. I am using Jackett.Binaries.LinuxARM32.tar.gz and while version v0.11.799 works fine in version v0.11.802 I get exception:
```
$ ./jackett
10-13 06:48:33 Info Starting Jackett v0.11.802.0 
10-13 06:48:35 Error System.BadImageFormatException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The module was expected to contain an assembly manifest.
File name: 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngineServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.AddRazorViewEngine(IMvcCoreBuilder builder)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services, Action`1 setupAction)
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in /home/appveyor/projects/jackett/src/Jackett.Server/Startup.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)
```

**Comment by garfield69** [comment]
please indicate how you upgraded from .799 to .802:
1. by using the jackett dashboard *check for updates* button
2. the jackett auto-update did it
3. I shutdown jackett, downloaded the .802 arm32 package, and installed it over the top of the .799

**Comment by saxicek** [comment]
It was number 3 - clean install. Removed jackett dir completely and then
unpacked the new release.

ne 13. 10. 2019 v 9:32 odesílatel garfield69 <notifications@github.com>
napsal:

**Comment by garfield69** [comment]
well that is a puzzle.
I installed .802 on my win10, ubuntu18 and macos mojave without problems.
I don't have an arm machine so I cannot test this :-(
your jackett startup clearly shows that the jackett folder is missing a module.
please download the .802 arm32 package again, extract it to a temp folder and compare its content with your current .802 folder. 
anything missing?
is it possible that anti-malware or other system protection software removed a module? have you checked the products virus-chest or logs?

**Comment by saxicek** [comment]
I tried again with the latest version and it works. It was probably something broken in my setup (testing Ansible jewflix.jackett on Raspberry Pi 4) but it is not worth investigating further. Sorry for wasting your time. Closing.
