### ISSUE TITLE
Cannot start 0.7.504.0

### ISSUE THREAD

**Issue by drtrotusk** [Jackett/Jackett#617]
Yesterday after I updated to the current version everything was working fine but today Jackett wouldn't start.

Running it on RPi2 with OSMC (based on Debian Jessie).
Mono: 3.10.0

Log:

`11-01 12:46:44 Info Logging enabled. 

11-01 12:46:44 Info Tracing enabled. 

11-01 12:46:44 Debug App config/log directory: /home/osmc/.config/Jackett 

11-01 12:46:45 Info Starting Jackett 0.7.504.0 

11-01 12:46:45 Info Using HTTP Client: UnixLibCurlWebClient 

11-01 12:46:45 Error Top level exception Newtonsoft.Json.JsonReaderException: 
Error reading JToken from JsonReader. Path '', line 0, position 0.
at Newtonsoft.Json.Linq.JToken.ReadFrom (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Linq.JsonLoadSettings settings) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Linq.JToken.Load (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Linq.JsonLoadSettings settings) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Linq.JToken.Parse (System.String json, Newtonsoft.Json.Linq.JsonLoadSettings settings) [0x00000] in <filename unknown>:0 
  at Newtonsoft.Json.Linq.JToken.Parse (System.String json) [0x00000] in <filename unknown>:0 
  at Jackett.Services.IndexerManagerService.LoadIndexerConfig (IIndexer idx) [0x00000] in <filename unknown>:0 
  at Jackett.Services.IndexerManagerService.InitIndexers () [0x00000] in <filename unknown>:0 
  at Jackett.Services.ServerService.Initalize () [0x00000] in <filename unknown>:0 
  at JackettConsole.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
`

I will gladly provide any additional information.

Thanks!

**Comment by kaso17** [comment]
I suspect that your RPi crashed and the config files got corrupted?
Please try wiping your config directory.
But make a backup before wiping it.

**Comment by drtrotusk** [comment]
I removed the config folder and restored a backup I made yesterday. It started without problems.

Thank you

**Comment by kaso17** [comment]
can you compare your configs and check what exactly was broken, then we could add some more useful error message or maybe even repair it automatically.

**Comment by drtrotusk** [comment]
I should have understood that this is why you asked to make the backup. Unfortunately I removed the faulty folder, sorry.
I will definitely do it if it will happen again.

**Comment by d2dyno** [comment]
Getting a similar error, on 5.12 for Windows:

Service cannot be started. Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Jackett.Services.IndexerManagerService.LoadIndexerConfig(IIndexer idx) in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 49
   at Jackett.Services.IndexerManagerService.InitIndexers() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 69
   at Jackett.Services.ServerService.Initalize() in C:\projects\jackett\src\Jackett\Services\ServerService.cs:line 152
   at Jackett.Service.Service.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

**Comment by kaso17** [comment]
@d2dyno most likely one of your indexer configs got corrupted, look for an empty file

**Comment by d2dyno** [comment]
That was it! The 'MoreThanTV' indexer file was blank.
