### ISSUE TITLE
No longer sending results to sonarr using 'all' indexer. 

### ISSUE THREAD

**Issue by negativzeroe** [Jackett/Jackett#6185]
Jackett Version 0.11.817.0 

Using the linuxserver.io images on both Jackett and Sonarr. 
I tested with the bare-metal install of Sonarr and mono-devel (without changing anything in Jackett) and did not have the same issue. 

When using the link http://10.1.0.222:9117/torznab/all/ I do not return any results but if I copy the torznab from each indexer in Jackett I get results.

See here for reference: https://github.com/linuxserver/docker-sonarr/issues/131

From log:
```
[Error] Torznab: An error occurred while processing feed. http://10.1.0.222:9117/torznab/all/api?t=tvsearch&cat=5000,5030,5040,5050,5060,5070,100118,100133,100006,100007,100041,100151,100146,100152,6000,100001,100004&extended=1&apikey=0r91bb14ffvl201adgf2uan5jaj9yhss&offset=0&limit=1000&q=Flash&season=6&ep=2 

[v2.0.0.5338] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000b6] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:42 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\RssParser.cs:55 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:308 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchReleases (System.Func`2[T,TResult] pageableRequestChainSelector, System.Boolean isRecent) [0x000a0] in M:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:143 

```

**Comment by garfield69** [comment]
I recommend not using the aggregate  indexer (**all**).
while this indexer may save you config time, it is not the best option for use with Sonarr or any other app that required a timely response.
the problem is that if any of the indexers on Jackett have a problem with their corresponding site (say an outage, or they enabled anti-DDoS or are having Gate-Way issues, etc), the total response time of the aggregate indexer may exceed they total timeout value that Sonarr response window and you will not get **any** results back.

you are far better off individually adding the jackett indexers to Sonarr. You will get the benefit of multi-tasking and should any of the indexer fail you will still get response from the others.

**Comment by Taloth** [comment]
@garfield69 It's worth mentioning that OP had the same error with single indexer:
```
[Error] Torznab: An error occurred while processing feed. http://10.1.0.222:9117/api/v2.0/indexers/kickasstorrent-kathow/results/torznab/api?t=tvsearch&cat=5000,5030,5040,5050,5060,5070,100118,100133,100006,100007,100041,100151,100146,100152,6000,100001,100004&extended=1&apikey=(removed)&offset=0&limit=100&q=Flash&season=6&ep=2 

[v2.0.0.5338] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Jackett.Common.Models.ResultPage.<ToXml>b__13_0(ReleaseInfo r) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 63
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in /home/appveyor/projects/jackett/src/Jackett.Common/Models/ResultPage.cs:line 39
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 417
```

so it's clear that an error in the the kickass response nukes the entire /all result.

**Comment by negativzeroe** [comment]
@Taloth yup that was it I removed kickass from my indexers and all works again.
