### ISSUE TITLE
[generationfree] Exception (generationfree): Login failed: Selector

### ISSUE THREAD

**Issue by yoobi** [Jackett/Jackett#6213]
Hello,

I tested the generationfree tracker but i ran into an error, here is the log:

```
Error on 20191019154337 for Generation-Free.txtJackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 726
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1259
```

Jackett version 0.11.817.0

EDIT: I just tried selecting the a[href="account-logout.php"] with my console and it worked.

**Comment by garfield69** [comment]
yeah, the login test checking for the logout link was being done on the torrents-search.php page since that was where we ultimately wanted to end up using.
but the site must have recently dropped that link from this page.
so I've amended the indexer to now look for the logout link on the index.php page.
try out jackett pre-release 0.12.843
