### ISSUE TITLE
Filelist.ro has stopped working

### ISSUE THREAD

**Issue by aaomidi** [Jackett/Jackett#63]
Logs: http://i.imgur.com/QdLoag4.png

**Comment by WhatFox** [comment]
Working fine here.  Try running with extra logging enabled to see what the issue is.

**Comment by aaomidi** [comment]
Looks like it stops working after some time and I need to manually add it again for it to work.

**Comment by WhatFox** [comment]
Perhaps they are expiring the cookie, logging in from a different ip perhaps?

**Comment by aaomidi** [comment]
It seems like that's the case. A possible solution would be to try to login again if it errors automatically?

**Comment by aaomidi** [comment]
```
2015-11-25 12:34:16.4694 Info Found 0 releases from FileList 
2015-11-25 12:34:16.4694 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker   at Jackett.Services.IndexerManagerService.<TestIndexer>d__9.MoveNext() in 
C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Test>d__17.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 261
2015-11-25 12:34:31.4746 Info Found 48 releases from FileList 
2015-11-25 12:34:38.6587 Info Found 48 releases from FileList 
```

As you can see it errors when its left for a long time. Then the last two log lines are when I relogin to the tracker and it works fine.

**Comment by aaomidi** [comment]
BUMP

**Comment by andrei4002** [comment]
any news on this?

**Comment by abpostelnicu** [comment]
I can confirm that filelist.ro doesn't work any more. 
I have two logs
1. with extra logging enabled: http://pastebin.com/P1iymG3e
2. with normal logging enabled: http://pastebin.com/yJ7Je6QN

**Comment by savahu** [comment]
This can be closed I think, FileList has worked perfect here for at least a month.
