### ISSUE TITLE
Error whilst adding IPTorrents

### ISSUE THREAD

**Issue by JoeMShanahan** [Jackett/Jackett#6418]
Using Jackett on Unraid in Docker (binhex's template). I have set up a proxy. Here's the error that appears in the logs:

```
2019-11-24 21:22:52.0391 Error Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.IPTorrents.<>c__DisplayClass15_0.<ApplyConfiguration>b__0() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 219
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 267
   at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 221
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73 Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.IPTorrents.<>c__DisplayClass15_0.<ApplyConfiguration>b__0() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 219
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 267
   at Jackett.Common.Indexers.IPTorrents.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/IPTorrents.cs:line 221
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
```

Full log for this run is attached. Slightly confused why some of the output is duplicate, is this indicative of a problem?

[ipt-add-log.txt](https://github.com/Jackett/Jackett/files/3884149/ipt-add-log.txt)

I've added other (public) trackers fine and been able to test them without a problem.

**Comment by garfield69** [comment]
looks similar to #6402 
IPtorrents have blacklisted some IP blocks and the anti-DDoS checking is breaking the Jackett IPTorrents indexer.
Until IPTorrents lift their protection the current indexer will not work.
Since this indexer is written in C# I cannot help with coding a fix, it's out of my expertise.

**Comment by SenexCrenshaw** [comment]
I can take a look. If you can elaborate on where you think the problem is I can check it out.

**Comment by JoeMShanahan** [comment]
If the error is that Cloudflare is getting I the way, I dont see how there could be a fix to be made? Cloudfare is designed to the prevent the very thing Jackett is attempting to do!

**Comment by SenexCrenshaw** [comment]
This is a CloudflareSolverRe issue. I submitted a ticket with them.

**Comment by SenexCrenshaw** [comment]
This is not fixed for me with the latest git pulls and the latest release on this site. The cloudflare issue seems fixed and the config page for iptorrents comes up now but i get a "Error Jackett.Common.ExceptionWithConfigData" when i click OK. I attached an enhanced log.

[log.txt](https://github.com/Jackett/Jackett/files/3905658/log.txt)

**Comment by JoeMShanahan** [comment]
Unless I'm reading that wrong (sorry, mobile!), it looks like its still a Cloudflare looking at those logs?

**Comment by QuiGonLeong** [comment]
I was able to add it but using the site link https://ipt.beelyrics.net/

**Comment by JoeMShanahan** [comment]
How did you point Jackett at that URL? I get an error just trying to configure Jackett for IPT.

**Comment by QuiGonLeong** [comment]
![image](https://user-images.githubusercontent.com/41975335/70381754-45878500-190d-11ea-84f7-bd3132dd3560.png)

**Comment by JoeMShanahan** [comment]
That doesn't open for me.

**Comment by garfield69** [comment]
@JoeMShanahan  If the jackett dashboard config for IPTorrents
fails to open to allow you to select an alternate **Site Link**, there may be a backdoor method that could work (**UNTESTED**, not guaranteed to work).
1. shut down the jackett service 
2. using a plain text editor paste the following and save to your jackett **Indexers** folder as `iptorrents.json`
```json
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://ipt.beelyrics.net/"
  },
]
```
on most linux systems the **Indexers** folder is in `~/.config/Jackett/Indexers`, on windows `%ProgramData%\Jackett\Indexers `
3. start the service
4. try to add/edit the IPTorrents config from the jackett dashboard and see if you get lucky.

**Comment by JoeMShanahan** [comment]
Huh, that worked 👍

**Comment by JoeMShanahan** [comment]
Thank you!
