### ISSUE TITLE
Error: hexadecimal value 0x00, is an invalid character. Line 1, position 1.

### ISSUE THREAD

**Issue by ruverav** [Jackett/Jackett#6466]
I get the following error when I try to login with my password as usual.

I'm running the latest version (1db6530c-ls24) on Docker.

```
{
  "result": "error",
  "error": "An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.",
  "stacktrace": "   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)\n   at Microsoft.AspNetCore.Authentication.SecureDataFormat`1.Protect(TData data, String purpose)\n   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleSignInAsync(ClaimsPrincipal user, AuthenticationProperties properties)\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)\n   at Jackett.Server.Controllers.WebUIController.MakeUserAuthenticated() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/UIController.cs:line 94\n   at Jackett.Server.Controllers.WebUIController.Dashboard(String password) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/UIController.cs:line 67\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29",
  "innerstacktrace": "   at System.Xml.XmlTextReaderImpl.Throw(Exception e)\n   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)\n   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)\n   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()\n   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()\n   at System.Xml.XmlTextReaderImpl.Read()\n   at System.Xml.XmlReader.MoveToContent()\n   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)\n   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)\n   at System.Xml.Linq.XElement.Load(Stream stream)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\n   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()\n   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)"
}
```

log.txt

```
2019-12-02 07:53:02.9522 Info Found 24 (24 new) releases from Torrentz2
2019-12-02 08:08:30.0362 Info Found 30 (25 new) releases from Zooqle
2019-12-02 08:08:31.8524 Info Found 80 (36 new) releases from KickAssTorrent (kat.li)
2019-12-02 08:08:35.3460 Info Found 100 (27 new) releases from RARBG
2019-12-02 08:08:35.4320 Info Found 30 (30 new) releases from Torrentz2
2019-12-02 08:24:02.3336 Info Found 30 (0 new) releases from Zooqle
2019-12-02 08:24:05.6385 Info Found 100 (18 new) releases from RARBG
2019-12-02 08:24:06.2541 Info Found 80 (0 new) releases from KickAssTorrent (kat.li)
2019-12-02 08:24:07.6528 Info Found 33 (30 new) releases from Torrentz2
2019-12-02 08:37:28.2300 Info Found 30 (2 new) releases from Zooqle
2019-12-02 08:37:30.0275 Info Found 18 (14 new) releases from KickAssTorrent (kat.li)
2019-12-02 08:37:33.6910 Info Found 100 (72 new) releases from RARBG
2019-12-02 08:39:34.7440 Info Found 30 (7 new) releases from Zooqle
2019-12-02 08:39:36.0390 Info Found 100 (13 new) releases from RARBG
2019-12-02 08:39:38.6337 Info Found 80 (26 new) releases from KickAssTorrent (kat.li)
2019-12-02 08:39:40.2827 Info Found 21 (21 new) releases from Torrentz2
2019-12-02 08:51:51.5974 Info Found 20 (20 new) releases from ETTV
2019-12-02 08:51:51.7669 Error An error occurred while reading the key ring. System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream, LoadOptions options)
   at System.Xml.Linq.XElement.Load(Stream stream)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
```

Any idea why this happens?

I recently moved all my containers from my Mac Mini to my new Synology NAS (DS718+). The Jackett's container processes are being run with the same PUID and PGID than my default user (which is inside the docker user group), so I cannot relate this to a permissions problem.

**Comment by garfield69** [comment]
Look like an encryption issue. You cannot port encrypted data from one platform to another and expect it to work, the secret keys will be different as well as the methods probably..
You suspect you are going to have to enter the  configs of any semi or private indexer you have active in your jackett dashboard and re-enter the passwords.

**Comment by garfield69** [comment]
If that does not work then trashbin the configs and start afresh.

**Comment by ruverav** [comment]
Thanks, configuring it from scratch solved for me! Not the most elegant solution (because I needed to add the indexers again and change the api keys on sonarr and radarr), but it works.
