### ISSUE TITLE
[privatehd] Exception (privatehd):  Jackett.Common.ExceptionWithConfigData

### ISSUE THREAD

**Issue by zachberger** [Jackett/Jackett#6523]
Over the last three days Privatehd.to has been failing with the below exception. Logging in via webpage works. I've also tried deleting and recreating my configuration.

```
Jackett.Common.IndexerException: Exception (privatehd): 
 ---> Jackett.Common.ExceptionWithConfigData
   at Jackett.Common.Indexers.Abstract.AvistazTracker.<>c__DisplayClass9_0.<ApplyConfiguration>b__0() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs:line 75
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 267
   at Jackett.Common.Indexers.Abstract.AvistazTracker.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs:line 78
   at Jackett.Common.Indexers.Abstract.AvistazTracker.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Abstract/AvistazTracker.cs:line 99
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 819
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
```

[Enhanced Log File](https://github.com/Jackett/Jackett/files/3934799/jackett.txt)

(At the bottom of your Jackett Dashboard page) **Jackett version**:   Jackett Version 0.12.1096.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**: N/a

-------------------------------

**Comment by garfield69** [comment]
unfortunately this log does not appear to be an enhanced log. (There are no messages with the **Debug** keyword in them).

if you used the jackett dashboard to set the enhanced mode, then you should be aware that restarting jackett will reset that setting.
 
Please try again to provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by zachberger** [comment]
Sorry about that, seems like the enhanced logging was turned off after updating my container. 

Here you go: [log.txt](https://github.com/Jackett/Jackett/files/3934824/log.1.txt)

**Comment by garfield69** [comment]
hmm. I see a redirect to https://privatehd.to/auth/twofa just after the login is completed.
do you have 2FA enabled?
jackett does not support this, so you will need to disable that option in your PrivateHD settings if you want to use this site with Jackett.

**Comment by zachberger** [comment]
That seems to be it. Just turned it off and its working. Does Jackett use cached credentials or sessions? It seemed to work for a while after enabling 2FA.

**Comment by garfield69** [comment]
well yes, jackett saves any cookies it receives after a login, and provides them whenever you do a torrent search to the site. 
And as long as the site accepts the cookies and does not request a re-login, then you're good to go, until the cookies expire and the site complains, at which time jackett attempts a fresh login using the credentials stored in the config.
