### ISSUE TITLE
[asiancinema] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by R8s6** [Jackett/Jackett#6529]
Hi Team,

I can add the tracker, but test shows:

> An error occured while testing this indexer
>Found no results while trying to browse this tracker

1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
Yes, I can. 

2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
It's the latest docker version.

3. If it is still not working for you, then a **full enhanced log must be included**. 
[log.txt](https://github.com/Jackett/Jackett/files/3935516/log.txt)

The log shows that Jackett can fetch the tracker information, but it has an error:
```
System.Exception: Error while parsing field=date, selector=time, value=5小時前: DateTime parsing failed for "5小時前": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 119
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 213
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1489 
2019-12-07 12:21:30.2627 Error CardigannIndexer (asiancinema): Error while parsing row '
```

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.12.1096.0

Thank you!

**Comment by garfield69** [comment]
current languages supported by the indexer are Turkish|Estonian|Danish|Italian|Polish|Norwegian|Portuguese|Czech|Russian|Romanian|Spanish|French|German|Bulgarian|Dutch
but I will take a look and see if I can add Chinese (simplified) support as well.

**Comment by garfield69** [comment]
try out jackett 0.12.1099

**Comment by R8s6** [comment]
Oh that was why, it’s okay, i can switch to english, thanks for pointing me the right direction!

**Comment by R8s6** [comment]
It's working now. Thank you very much!
