### ISSUE TITLE
[btdb] Exception (btdb): The operation was canceled

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6533]
Jackett Version 0.12.1099.0
Tracker: btdb
Search: silicon valley
```
Manual search for "silicon valley" on btdb with 0 results.
Jackett.Common.IndexerException: Exception (btdb): The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at CloudflareSolverRe.CloudflareSolver.SolveWithJavascript(Int32 tries)
   at CloudflareSolverRe.CloudflareSolver.Solve()
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, CloudflareHandler cloudflareHandler, Uri siteUrl, CancellationToken cancellationToken)
   at CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at CloudflareSolverRe.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, HttpClientHandler httpClientHandler, Uri siteUrl, CancellationToken cancellationToken, Boolean randomUserAgent)
   at CloudflareSolverRe.ClearanceHandler.GetClearance(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 165
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 453
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1238
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 823
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 227
```

**Comment by garfield69** [comment]
this has something to do with the site's active anti-DDoS prevention.
for some reason its decided that jackett is a bot when it comes to search requests, but is happy to let 
 jackett fetch the recent page. 
I see that when using the site via the browser directly, the url becomes:
https://btdb.eu/?s=silicon%20valley&__cf_chl_jschl_tk__=e1c7511a1e988387e19129cb00e2d4536a72afce-1575823141-0-AfhY2dsTuds6vR0Bv5iP6pf2yIhrqhWkv3wjYFGX-qcEwg-eKcSiHSr_Xff3Ft3Jbw7l7NU7ze87gSYl9KrNNytEE3prxFAZrNU4glQ5iyluJXpQU8s5JjeCwmnfGrVqxO1It8YoYukyPdVHKMC6UyCZqY6iGXdIf08NhpZaj1uoQ5kf20HyshFeblnDdCm3xGIwaIUz1XouUH4CcTtBBrdazVVJGZVmG5vyTnAmSVZyuXOyfpHlqmh4JcdGy9CnbyjDiX1fIabxCIM9HSAfhw6U-3PnhQvJaTEoc9OpHun8
at least the first time you do a search. after that the extra parms are gone, presumably because a cookie is now set.
I don't think the cardigann processor is set up to handle what this site gets up to.
may need C# intervention.

**Comment by ngosang** [comment]
@garfield69 since the domain change it's working fine.
