### ISSUE TITLE
[tfile] Error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6553]
Jackett Version 0.12.1115.0
Tracker: tfile
Search: mp3

```
Manual search for "mp3" on tfile with 49 results.
CardigannIndexer (tfile): Error while parsing row '
<tr id="t1315010" class="tor">
	<td class="f">
		<a href="/forum/index.php?c=22">Отечественная музыка</a>
		/
		<a href="/forum/viewforum.php?f=1817">Музыка, не вошедшая в подразделы (разное)</a>
	</td>
	<td class="i">
		<b class="tt ttUnchecked" title="Непроверенный релиз"></b>
	</td>
	<td class="t">
		<a href="http://tfile-music.cc/forum/link.php?t=17sy6&amp;v=uur72f3d31b7">Сборник - Музыкальная Олимпиада
			<i>(Из плейлистов Галадриэль)</i>
			<i>[2013, Баллады,
				<em>MP3</em>]</i>
		</a>
	</td>
	<td class="dl">
	</td>
	<td class="dl">
	</td>
	<td class="dl">
	</td>
	<td class="ps">
		<a href="http://megatfile.cc/forum/profile.php?mode=viewprofile&amp;u=1477648" rel="nofollow">Astarot999</a>
	</td>
	<td class="ms">
		2019-12-08 18:59<br>
	</td>
</tr>':

System.Exception: Error while parsing field=size, selector=td:nth-child(4), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1489
```

**Comment by ngosang** [comment]
@garfield69 I found another:
```
Manual search for "ps3" on tfile with 42 results.
CardigannIndexer (tfile): Error while parsing row '
<tr id="t364238" class="tor">
	<td class="f">
		<a href="/forum/viewforum.php?f=370">Дискуссии на тему...</a>
		/
		<a href="/forum/viewforum.php?f=1113">Обсуждение консолей,и консольных игр</a>
	</td>
	<td class="i">
		<b class="tt ttUnchecked" title="Непроверенный релиз"></b>
	</td>
	<td class="t">
		<a href="http://megatfile.cc/forum/link.php?t=kmyq&amp;v=67272f3d31b7">Naruto ultimate ninja storm 2
			<i>(<em>ps3</em>/360)</i>
		</a>
	</td>
	<td class="dl">
	</td>
	<td class="dl">
	</td>
	<td class="dl">
	</td>
	<td class="ps">
		<a href="http://megatfile.cc/forum/profile.php?mode=viewprofile&amp;u=1626462" rel="nofollow">[Fire]Demon</a>
	</td>
	<td class="ms">
		2010-10-07 15:20<br>
	</td>
</tr>':

System.Exception: Error while parsing field=size, selector=td:nth-child(4), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1489
```
