### ISSUE TITLE
[world-of-tomorrow] Exception (world-of-tomorrow): Login failed: No form found on https://world-of-tomorrow.eu/login.php using form selector form: Parse error (Test)

### ISSUE THREAD

**Issue by ilosh** [Jackett/Jackett#6625]
Hi,
I am getting errors for the Tracker World of Tomorrow:

Jackett reapeats this log message:

`CardigannIndexer (world-of-tomorrow): Relogin required`

Also the log says:

`Error on 20191216113937 for world-of-tomorrow.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://world-of-tomorrow.eu/login.php using form selector form
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1266`

`Jackett.Common.IndexerException: Exception (world-of-tomorrow): Login failed: No form found on https://world-of-tomorrow.eu/login.php using form selector form
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://world-of-tomorrow.eu/login.php using form selector form
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 478
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1266
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 846
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 823
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 427`

I am on Debian 9.

Jackett version: 0.12.1213.0
Mono version: 5.18.1.3 

Thank you a lot.

**Comment by garfield69** [comment]
Unfortunately the stack trace you provided does not help to provide an explanation for your problem. I'm  going to need to see the enhanced log which may have more info.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by ilosh** [comment]
Hello @garfield69,
thank you for your fast reply.

I activated the enhanced log and the tracker went through the test just fine. That's what you call the demo effect I guess, before that I got only errors.

I will monitor the situation and deliver a full log when I get errors again. Might be a problem on their side, but we will see.

Thank you very much for your help.
