### ISSUE TITLE
Jackett doesn't open new tracker configuration window: rutracker, torrentleech, torrentseeds and more

### ISSUE THREAD

**Issue by robinde** [Jackett/Jackett#6626]
I'm running debian buster (armbian) on armv7h
Installed jackett using the ARM32 binaries
running behind an nginx reverse proxy, as shown on the main github page
mono 5.18.0.240
jackett 0.12.1227.0

When trying to add certain trackers, after pressing the wrench to configure them, jackett doesn't open the configuration window. After 1-2 or minutes an exception is thrown in the logs (see below). Otherwise, the functioning of jackett seems to continue working

This doesn't happen for all trackers, but it is a problem with multiple trackers. The trackers I've already configured still work as normal. Adding other trackers that aren't affected also works as normal.
```
-- Logs begin at Sat 2019-12-14 13:50:24 CET, end at Mon 2019-12-16 12:20:22 CET. --
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug Connection id "0HLS2362P7B7K" accepted.
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug Connection id "0HLS2362P7B7K" started.
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Info Request starting HTTP/1.0 GET http://127.0.0.1:9117/j/api/v2.0/indexers/rutracker/config?_=1576495039702
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug Request is continuing in applying rules. Current url is https://mydomain.org/j/api/v2.0/indexers/rutracker/config?_=1576495039702
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug Request is continuing in applying rules. Current url is https://mydomain.org/j/api/v2.0/indexers/rutracker/config?_=1576495039702
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug Request is continuing in applying rules. Current url is https://mydomain.org/j/api/v2.0/indexers/rutracker/config?_=1576495039702
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug The request path /api/v2.0/indexers/rutracker/config does not match a supported file type
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug AuthenticationScheme: Cookies was successfully authenticated.
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/rutracker/config'
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/rutracker/config'
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
Dec 16 12:17:48 host jackett[25113]: 12-16 12:17:48 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Debug Execution plan of resource filters (in the following order): None
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Debug Execution plan of exception filters (in the following order): None
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Debug Execution plan of result filters (in the following order): None
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Info Authorization was successful.
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
Dec 16 12:17:49 host jackett[25113]: 12-16 12:17:49 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://rutracker.org/forum/login.php)
Dec 16 12:18:48 host jackett[25113]: 12-16 12:18:48 Debug Connection id "0HLS2362P7B7K" received FIN.
Dec 16 12:18:48 host jackett[25113]: 12-16 12:18:48 Debug Connection id "0HLS2362P7B7K" sending FIN because: "The client closed the connection."
Dec 16 12:18:48 host jackett[25113]: 12-16 12:18:48 Debug Connection id "0HLS2362P7B7K" disconnecting.
Dec 16 12:19:29 host jackett[25113]: 12-16 12:19:29 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 100415.382ms
Dec 16 12:19:29 host jackett[25113]: 12-16 12:19:29 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
Dec 16 12:19:29 host jackett[25113]: 12-16 12:19:29 Error System.Threading.Tasks.TaskCanceledException: The operation was canceled.
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 449
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Common.Indexers.RuTracker.GetConfigurationForSetup() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/rutracker.cs:line 1444
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Server.Controllers.IndexerApiController.Config() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 System.Threading.Tasks.TaskCanceledException: The operation was canceled.
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Dec 16 12:19:29 host jackett[25113]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 449
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Common.Indexers.RuTracker.GetConfigurationForSetup() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/rutracker.cs:line 1444
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Server.Controllers.IndexerApiController.Config() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Dec 16 12:19:29 host jackett[25113]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
Dec 16 12:19:29 host jackett[25113]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29
Dec 16 12:19:29 host jackett[25113]: 12-16 12:19:29 Debug No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.
Dec 16 12:19:29 host jackett[25113]: 12-16 12:19:29 Info Request finished in 100817.95240000001ms 500 application/json
Dec 16 12:19:29 host jackett[25113]: 12-16 12:19:29 Debug Connection id "0HLS2362P7B7K" stopped.
```

**Comment by garfield69** [comment]
behind the scenes, when you click the wrench icon to open a indexer config, Jackett does a fetch of the login page to check if there is any captcha elements it needs to pre-load into the config panel.
(Things like: enter into a box the text you see in this picture, or click on the beetle to prove you are human, etc).
if, for whatever reason, Jackett is unable to fetch that page and times out, then you would get the symptoms you are reporting.

it is difficult to tell what the problem is from looking at the log, but the most likely reason has something to do with certificate negotiation mismatch problems, which seem to be common with linux and mono and proxies, and whatnot.
A mismatch is where the client and the host certificates do not agree on how to negotiate the https security protocol for some varied reason, and Jackett ends up giving up after an interval because it did not get the page it was expecting.
Users of proxies seem to be more susceptible to this issue judging by previous tickets.
It is beyond my expertise to resolve, sorry. :-( 

Ping to anyone who can help with this type of issue.

**Comment by garfield69** [comment]
the panel invokes the standard JavaScript .sort() function, which the docs state can only handle alphabetic or numeric sorting.
The column headers are build with a recursive routine that labels and tags all headers as sort-able.
I'm not interested in spending time writing a custom sort for icons or fiddling with this panel's html.
It's just not my cup of tea.
I see little benefit in this. I already stated previously how the magnet icon only shows up if the site being searched has the link in the primary search page.
If the site has the magnet in the details page, then Jackett will display the local-download icon.
which means IMO, that sorting this column is pointless since many sites use the details page for download links.
I'm closing this ticket, its too messy to turn into an enhancement request anyway.

If you really want to be able to sort the download column then open a fresh enhancement request and we shall see if any volunteers contribute a solution.

**Comment by garfield69** [comment]
oops, wrong ticket, ignore my prior post.

**Comment by robinde** [comment]
So you're saying the reverse proxy is part of the problem?
I could test on the local network using `localhost:jackett_port` to verify whether the reverse proxy is the problem then.

**Comment by robinde** [comment]
I found that the problem is kernel related. For anyone running armbian, kernel 4.19 seems fine whereas 5.3 has the aforementioned problem.
I tried running jackett with mono, but it's very slow, and previously working functionality is broken, so better to change kernels.
