### ISSUE TITLE
[superbits] Your cookie did not work: Parse error (Config)

### ISSUE THREAD

**Issue by drznoopy** [Jackett/Jackett#6640]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
I can login without any problems, when i try jackett it say that the cookie dont match the account

2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
I have the lastest

3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting
```
System.Exception: Your cookie did not work: Parse error
   at Jackett.Common.Indexers.Superbits.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Superbits.cs:line 94
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
Error on 20191218140135 for Superbits.txtNewtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Jackett.Common.Indexers.Superbits.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Superbits.cs:line 125
```
(At the bottom of your Jackett Dashboard page) **Jackett version**:  
Version 0.12.926.0

(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by garfield69** [comment]
is this the first time you are setting up the Jackett Superbits config, or was it working previously?

**Comment by drznoopy** [comment]
It have worked before, i reinstalled my Linux server. I set up other
providers without any problem

Den ons 18 dec. 2019 20:50garfield69 <notifications@github.com> skrev:

**Comment by garfield69** [comment]
ok, so have you fetched a new cookie from a browser running on the same machine as the one that is running Jackett?
- Login to this tracker with your browser
- Open the _DevTools_ panel by pressing **F12**
- Select the **Network** tab
- Click on the **Doc** button
- Refresh the page by pressing **F5**
- Select the **Headers** tab
- Find 'cookie:' in the **Request Headers** section
- Copy & paste the whole cookie string to the cookie box in the Jackett superbits config.

if you cannot get that to work then perhaps there will be more information if you turn on the enhanced logging, so in that case, please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by drznoopy** [comment]
2020-01-03 07:57:10.9467 Debug
WebClient(HttpWebClient2NetCore).GetString(Url:
https://superbits.org/api/v1/torrents?extendedSearch=false&freeleech=false&index=0&limit=100&order=desc&page=search&searchText=&sort=d&section=all&stereoscopic=false&sweaudio=false&swesub=false&watchview=false)

2020-01-03 07:57:11.2594 Debug WebClient(HttpWebClient2NetCore): Returning
Unauthorized => Cookie nyckeln matchar inte med användarkontot.
2020-01-03 07:57:11.2854 Error Error on 20200103075711 for
Superbits.txtNewtonsoft.Json.JsonReaderException: Unexpected character
encountered while parsing value: C. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean
hasConverter)
   at
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader
reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader,
Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type
objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type
type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value,
JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Jackett.Common.Indexers.Superbits.PerformQuery(TorznabQuery query) in
/home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Superbits.cs:line
125




Cookie nyckeln matchar inte med användarkontot.
2020-01-03 07:57:11.2971 Info Executed action
Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in
427.1761ms
2020-01-03 07:57:11.2979 Info Executed endpoint
'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)'
2020-01-03 07:57:11.2979 Error System.Exception: Your cookie did not work:
Parse error
   at Jackett.Common.Indexers.Superbits.ApplyConfiguration(JToken
configJson) in
/home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Superbits.cs:line
94
   at
Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[]
config) in
/home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line
94
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper
mapper, ObjectMethodExecutor executor, Object controller, Object[]
arguments)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker
invoker, ValueTask`1 actionResultValueTask)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed
context)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&
next, Scope& scope, Object& state, Boolean& isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker
invoker)
   at
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint
endpoint, Task requestTask, ILogger logger)
   at
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext
context)
   at
Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext
context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext
httpContext) in
/home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line
29 System.Exception: Your cookie did not work: Parse error
   at Jackett.Common.Indexers.Superbits.ApplyConfiguration(JToken
configJson) in
/home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Superbits.cs:line
94
   at
Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[]
config) in
/home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line
94
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper
mapper, ObjectMethodExecutor executor, Object controller, Object[]
arguments)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker
invoker, ValueTask`1 actionResultValueTask)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed
context)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&
next, Scope& scope, Object& state, Boolean& isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker
invoker)
   at
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint
endpoint, Task requestTask, ILogger logger)
   at
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext
context)
   at
Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext
context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext
httpContext) in
/home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line
29
2020-01-03 07:57:11.3168 Debug No response compression available for HTTPS
requests. See ResponseCompressionOptions.EnableForHttps.
2020-01-03 07:57:11.3196 Debug Connection id "0HLSG37VNU3TF" completed keep
alive response.
2020-01-03 07:57:11.3199 Info Request finished in 460.24850000000004ms 500
application/json
2020-01-03 07:57:11.3199 Debug Connection id "0HLSG37VNU3TF" received FIN.
2020-01-03 07:57:11.3199 Debug Connection id "0HLSG37VNU3TF" disconnecting.
2020-01-03 07:57:11.3199 Debug Connection id "0HLSG37VNU3TF" sending FIN
because: "The client closed the connection."
2020-01-03 07:57:11.3219 Debug Connection id "0HLSG37VNU3TF" stopped.
2020-01-03 07:57:32.1770 Debug Connection id "0HLSG37VNU3TG" accepted.
2020-01-03 07:57:32.1770 Debug Connection id "0HLSG37VNU3TG" started.
2020-01-03 07:57:32.1784 Info Request starting HTTP/1.1 GET
http://127.0.0.1:18379/jackett/api/v2.0/indexers/superbits/config?_=1578034580760

2020-01-03 07:57:32.1784 Debug Request is continuing in applying rules.
Current url is
https://usbx.me/jackett/api/v2.0/indexers/superbits/config?_=1578034580760
2020-01-03 07:57:32.1784 Debug Request is continuing in applying rules.
Current url is
https://usbx.me/jackett/api/v2.0/indexers/superbits/config?_=1578034580760
2020-01-03 07:57:32.1784 Debug Request is continuing in applying rules.
Current url is
https://usbx.me/jackett/api/v2.0/indexers/superbits/config?_=1578034580760
2020-01-03 07:57:32.1784 Debug The request path
/api/v2.0/indexers/superbits/config does not match a supported file type
2020-01-03 07:57:32.1810 Debug AuthenticationScheme: Cookies was
successfully authenticated.
2020-01-03 07:57:32.1810 Debug 1 candidate(s) found for the request path
'/api/v2.0/indexers/superbits/config'
2020-01-03 07:57:32.1810 Debug Endpoint
'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with
route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the
request path '/api/v2.0/indexers/superbits/config'
2020-01-03 07:57:32.1810 Debug Request matched endpoint
'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
2020-01-03 07:57:32.1810 Info Executing endpoint
'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
2020-01-03 07:57:32.1821 Info Route matched with {action = "Config",
controller = "IndexerApi"}. Executing controller action with signature
System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult]
Config() on controller Jackett.Server.Controllers.IndexerApiController
(jackett).
2020-01-03 07:57:32.1821 Debug Execution plan of authorization filters (in
the following order):
Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2020-01-03 07:57:32.1821 Debug Execution plan of resource filters (in the
following order): None
2020-01-03 07:57:32.1821 Debug Execution plan of action filters (in the
following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter
(Order: -2147483648),
Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order:
-3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter,
Jackett.Server.Controllers.RequiresIndexer
2020-01-03 07:57:32.1821 Debug Execution plan of exception filters (in the
following order): None
2020-01-03 07:57:32.1821 Debug Execution plan of result filters (in the
following order): None
2020-01-03 07:57:32.1821 Info Authorization was successful.
2020-01-03 07:57:32.1821 Debug Executing controller factory for controller
Jackett.Server.Controllers.IndexerApiController (jackett)
2020-01-03 07:57:32.1821 Debug Executed controller factory for controller
Jackett.Server.Controllers.IndexerApiController (jackett)
2020-01-03 07:57:32.1840 Debug List of registered output formatters, in the
following order:
Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter,
Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter,
Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter,
Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter
2020-01-03 07:57:32.1840 Debug No information found on request to perform
content negotiation.
2020-01-03 07:57:32.1840 Debug Attempting to select an output formatter
without using a content type as no explicit content types were specified
for the response.
2020-01-03 07:57:32.1840 Debug Attempting to select the first formatter in
the output formatters list which can write the result.
2020-01-03 07:57:32.1840 Debug Selected output formatter
'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter' and
content type 'application/json' to write the response.
2020-01-03 07:57:32.1840 Info Executing ObjectResult, writing value of type
'Newtonsoft.Json.Linq.JArray'.
2020-01-03 07:57:32.1840 Debug No response compression available for HTTPS
requests. See ResponseCompressionOptions.EnableForHttps.
2020-01-03 07:57:32.1840 Info Executed action
Jackett.Server.Controllers.IndexerApiController.Config (jackett) in
2.6472ms
2020-01-03 07:57:32.1840 Info Executed endpoint
'Jackett.Server.Controllers.IndexerApiController.Config (jackett)'
2020-01-03 07:57:32.1840 Debug Connection id "0HLSG37VNU3TG" completed keep
alive response.
2020-01-03 07:57:32.1861 Info Request finished in 7.6741ms 200
application/json; charset=utf-8
2020-01-03 07:57:32.1861 Debug Connection id "0HLSG37VNU3TG" received FIN.
2020-01-03 07:57:32.1861 Debug Connection id "0HLSG37VNU3TG" disconnecting.
2020-01-03 07:57:32.1861 Debug Connection id "0HLSG37VNU3TG" sending FIN
because: "The client closed the connection."
2020-01-03 07:57:32.1879 Debug Connection id "0HLSG37VNU3TG" stopped.
2020-01-03 07:58:26.4711 Debug Connection id "0HLSG37VNU3TH" accepted.
2020-01-03 07:58:26.4825 Debug Connection id "0HLSG37VNU3TH" started.

Den tors 26 dec. 2019 kl 09:41 skrev jackettbot[bot] <
notifications@github.com>:

**Comment by garfield69** [comment]
`Cookie nyckeln matchar inte med användarkontot.` which google translates as `The cookie key does not match with the user account.`

are you fetching this cookie string using a browser on the same machine that is running jackett?
did you copy and paste the whole cookie string after the `cookie: ` tag in the **Request Headers** section?

**Comment by drznoopy** [comment]
Im running jackett on a seedbox so cant fetch the cookie from the same
machine, or can i do that ?
and yes i copied the whole string, PHPSESSID, uid, and pass

Den fre 3 jan. 2020 kl 08:52 skrev garfield69 <notifications@github.com>:

**Comment by garfield69** [comment]
clearly the session cookie you are using does not work when posted to the web site from your seedbox.

I have run into users before that have similar issues using headless servers.

Some users claim the session cookie is just an identifier and should work no matter where its from, but anecdotal evidence I've collected over the years suggests that some sites are able to cross check the cookie details with some machine identifiers (ip address, machine cpu id, operating system, anything they feel like checking) and reject the session when the cookie details don't line up.

Sorry, cannot help you further.
Ping to any volunteers with more experience to help with this one.

**Comment by ngosang** [comment]
For that cases, I think we have to move from cookie to user/password + re-login strategy like in #6907

**Comment by garfield69** [comment]
superbits was changed from username/password to cookie login by kaso17 in response to https://github.com/Jackett/Jackett/issues/4450
but if you can get the indexer to process the captcha then you're good to go.
![image](https://user-images.githubusercontent.com/6933240/72210381-5ab08e80-351f-11ea-85d0-ef415ccbd3b4.png)

**Comment by ngosang** [comment]
> but if you can get the indexer to process the captcha then you're good to go.

I'm not able to, but the only ways to get a new cookie are with auto-login or manual copy.

**Comment by kewm** [comment]
Need a solution for this. Superbits still now working (Version 0.13.127.0).

**Comment by brohypnol** [comment]
I had this same issue with TorrentDay.  I updated Jackett, removed the indexer entirely from Jackett and manually re-added, not just modified the existing indexer entry. Resolved it for me.

**Comment by RoloSoze** [comment]
@drznoopy @kewm Is this still a problem for you guys? I had similar issues with SuperBits myself a few months ago, but it's been working well for me for a while. Let us know.

**Comment by drznoopy** [comment]
> @drznoopy @kewm Is this still a problem for you guys? I had similar issues with SuperBits myself a few months ago, but it's been working well for me for a while. Let us know.

Yea still doesnt work, tried on 2 different seedboxes, i know some others have the same problem, i know danishbits works with passkey when you login, is this somethin maybe superbits could add maybe ?

**Comment by RoloSoze** [comment]
A C# developer will need to volunteer to look at this problem. If one is willing to do so, will you be able to provide an invite, @drznoopy? None of the current developers is a member of SuperBits.

**Comment by drznoopy** [comment]
> A C# developer will need to volunteer to look at this problem. If one is willing to do so, will you be able to provide an invite, @drznoopy? None of the current developers is a member of SuperBits.

I can, how do can i get secure contact with you ?

**Comment by RoloSoze** [comment]
> I can, how do can I get secure contact with you?

Not me personally since I'm not a developer, but if one of them sees this and can help, he'll ask you to email him the invite.

**Comment by RoloSoze** [comment]
@ngosang @cadatoiva I'm bringing this to your attention in case either one of you guys has the time & interest to fix this tracker since @drznoopy can provide an invite.

**Comment by ngosang** [comment]
No interest

**Comment by garfield69** [comment]
Stale. Closing.
