### ISSUE TITLE
[teamhd] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by ljmerza** [Jackett/Jackett#6661]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**: latest dev 
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

**Comment by ljmerza** [comment]
it doesnt work thats my details

**Comment by garfield69** [comment]
that's just too bad. ;-b
we  cannot help you without more information on your side other than "it does not work" !
if you want us to help you figure out what is going on, then
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by ljmerza** [comment]
```
2019-12-21 15:12:41.4154 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 729
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 890
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29 Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 729
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 890
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

```

**Comment by garfield69** [comment]
i'm sorry the stack trace you provided is not enough to help in this case. 
`login failed got redirected` is too general a message to be any help.

I really need to see if the log has any html, http urls,  or prior debug messages that may provide a clue.
can you not drag/drop the enhanced log here?

**Comment by ljmerza** [comment]
```
2019-12-21 15:28:55.4309 Debug Connection id "0HLS6A4MFFI1G" accepted. 
2019-12-21 15:28:55.4309 Debug Connection id "0HLS6A4MFFI1G" started. 
2019-12-21 15:28:55.4309 Info Request starting HTTP/1.1 POST http:///api/v2.0/indexers/teamhd/config application/json 449 
2019-12-21 15:28:55.4309 Debug No response compression available, the Accept-Encoding header is missing or invalid. 
2019-12-21 15:28:55.4309 Debug Request is continuing in applying rules. Current url is https:///api/v2.0/indexers/teamhd/config 
2019-12-21 15:28:55.4309 Debug Request is continuing in applying rules. Current url is https:///api/v2.0/indexers/teamhd/config 
2019-12-21 15:28:55.4309 Debug Request is continuing in applying rules. Current url is https:///api/v2.0/indexers/teamhd/config 
2019-12-21 15:28:55.4309 Debug POST requests are not supported 
2019-12-21 15:28:55.4309 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2019-12-21 15:28:55.4309 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/teamhd/config' 
2019-12-21 15:28:55.4309 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/teamhd/config' 
2019-12-21 15:28:55.4309 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2019-12-21 15:28:55.4309 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2019-12-21 15:28:55.4309 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2019-12-21 15:28:55.4309 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2019-12-21 15:28:55.4309 Debug Execution plan of resource filters (in the following order): None 
2019-12-21 15:28:55.4309 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2019-12-21 15:28:55.4309 Debug Execution plan of exception filters (in the following order): None 
2019-12-21 15:28:55.4309 Debug Execution plan of result filters (in the following order): None 
2019-12-21 15:28:55.4336 Info Authorization was successful. 
2019-12-21 15:28:55.4336 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2019-12-21 15:28:55.4336 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2019-12-21 15:28:55.4336 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-12-21 15:28:55.4336 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2019-12-21 15:28:55.4336 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
2019-12-21 15:28:55.4336 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
2019-12-21 15:28:55.4336 Debug Connection id "0HLS6A4MFFI1G", Request id "0HLS6A4MFFI1G:00000001": started reading request body. 
2019-12-21 15:28:55.4336 Debug Connection id "0HLS6A4MFFI1G", Request id "0HLS6A4MFFI1G:00000001": done reading request body. 
2019-12-21 15:28:55.4336 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-12-21 15:28:55.4336 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-12-21 15:28:55.4336 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2019-12-21 15:28:55.4336 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2019-12-21 15:28:55.4336 Debug CardigannIndexer (teamhd): Cookies after login: PHPSESSID=t2j9fcha92ich19l6bh7ldsj21; cross-site-cookie=https://teamhd.org; uid=3829; pass=7e31525332e0e0c4ffe940ab8254d680e4d7fc98f0400a6dacc87ceb3325e323; lang=russian; token=4d74c0a974ddcbec278df17f23513071c82c16985027a08bbe19126d031df471 
2019-12-21 15:28:55.4336 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://teamhd.org/index.php) 
2019-12-21 15:28:56.0121 Debug WebClient(HttpWebClient2NetCore): Returning Redirect => https://teamhd.org/login.php?returnto=index.php  
2019-12-21 15:28:56.0121 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 579.7142ms 
2019-12-21 15:28:56.0134 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2019-12-21 15:28:56.0134 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 729
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 890
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73 Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 729
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 890
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
2019-12-21 15:28:56.0180 Debug Connection id "0HLS6A4MFFI1G" completed keep alive response. 
2019-12-21 15:28:56.0180 Info Request finished in 586.6906ms 500 application/json 
2019-12-21 15:28:56.0180 Debug Connection id "0HLS6A4MFFI1G" received FIN. 
2019-12-21 15:28:56.0180 Debug Connection id "0HLS6A4MFFI1G" disconnecting. 
2019-12-21 15:28:56.0180 Debug Connection id "0HLS6A4MFFI1G" sending FIN because: "The client closed the connection." 
2019-12-21 15:28:56.0180 Debug Connection id "0HLS6A4MFFI1G" stopped. 

```

**Comment by ljmerza** [comment]
you cant just blindly ask people to share their logs. youre asking people to expose auth tokens...

**Comment by garfield69** [comment]
that is why we ask you to redact the log, **step 5** in my earlier post.

unfortunately,  as it happens, what you provided does not help :-(

so lets tackle this another way.

is your teamhd config **Site Link** set to https://teamhd.org/ ?

how are you going about fetching the cookie for the indexer config?

from a browser running on the same machine as that is running jackett, login to https://teamhd.org/login.php?returnto=index.php, then access the browser page and then follow the standard cookie fetch process
- Open the _DevTools_ panel by pressing **F12**
- Select the **Network** tab
- Click on the **Doc** button
- Refresh the page by pressing **F5**
- Select the **Headers** tab
- Find `cookie: ` in the **Request Headers** section
- **Copy & paste** the whole cookie string (everything after the `cookie: `) to the cookie box in the Jackett teamhd config.

does this differ in anyway from how you have been fetching it?

**Comment by ljmerza** [comment]
- site link is https://teamhd.org/
- I tried getting the cookies from the request header and from `document.cookies` both didn't work. 
- jackett is running in a docker container (linuxio) from a headless ubuntu server so I cant login from the same server.

my cookies:
```
PHPSESSID=XXX; cross-site-cookie=https://teamhd.org; uid=XXX; pass=XXX; lang=russian; token=XXX
```

**Comment by garfield69** [comment]
not being able to get the cookie from the same server is most likely the problem.
the site can use whatever unique info it wants to when it creates the phpsessid, and most often cookies from other systems will not work.

the only remaining slim possibility is to ensure that your account on the site has a good ratio, and that there are not outstanding alerts, notices or unread mail. Some sites redirect to these pages after login, which confuses the indexer because it is expecting to be presented with the torrent search page.

but I am inclined to believe the phpsessid is your issue, and I do not have a solution for you. sorry.

**Comment by ljmerza** [comment]
This doesn't make sense. If that was the case, jackett behind a proxy would break these types of logins. Hell, even jackett in a docker container would not work. sessionids aren't tied to some computer, they are just an abstraction. the os, browers, even network is irrelevant, which is why you're able to simply copy them over from the browser to jackett and the site wouldn't know the difference.

**Comment by garfield69** [comment]
I agree, its a puzzle.
All I can tell you from looking back at tickets on this repo is that, users who can capture their cookie from a browser running on the same machine as Jackett succeed in getting their cookie login indexer working, while those that grab the cookie from a browser and try to use it on a headless server fail.
there is  an answer in there somewhere, but its beyond my skill to figure out.
if you ever solve it I and many other jackett users will appreciate you posting the solve.

**Comment by bernard566** [comment]
> 
> 
> I agree, its a puzzle.
> All I can tell you from looking back at tickets on this repo is that, users who can capture their cookie from a browser running on the same machine as Jackett succeed in getting their cookie login indexer working, while those that grab the cookie from a browser and try to use it on a headless server fail.
> there is an answer in there somewhere, but its beyond my skill to figure out.
> if you ever solve it I and many other jackett users will appreciate you posting the solve.

Nope, same issue

I took coookie from the same machine I am running Jackett in. I am also using Flaressolverr. Still same error
