### ISSUE TITLE
[1337x] Exception (1337x): An existing connection was forcibly closed by the remote host: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by fahimfahimfahim** [Jackett/Jackett#6674]
Hi, I am on Win10 PRo, connected via ethernet. I have disabled my firewall and set my dns away from my ISP to Google's, but the problem persists. I can use other trackers normally, just not 1337x, The Strange thing is that I can browse the https://1337x.to/ site fine. Every now and then, the tracker will work on Jackedtt, but its unbearably slow to get results. However, browisng on the 1337x site the search results come up quickly. My log is below:
Jackett.Common.IndexerException: Exception (1337x): An existing connection was forcibly closed by the remote host ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.ClearanceHandler.<SendRequestAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudflareSolverRe.ClearanceHandler.<SendAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Common.Utils.Clients.HttpWebClient.<Run>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Common.Utils.Clients.WebClient.<GetString>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseWebIndexer.<RequestStringWithCookies>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Common.Indexers.CardigannIndexer.<PerformQuery>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.<ResultsForQuery>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Common.Indexers.BaseWebIndexer.<ResultsForQuery>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Server.Controllers.ResultsController.<Torznab>d__18.MoveNext()

**Comment by garfield69** [comment]
forcibly closed by remote host is an external action outside of jackett.
it suggests that which ever path jackett is taking to get to 1337x is not the same path that your browser is taking.
are you using a vpn with your browser?
or are you using a proxy or sock5 with jackett?

have you tried any of the other alternate site links that are presented with you edit the jackett 1337x config from your dashboard? https://1337x.unblocked.earth/ for instance?

**Comment by fahimfahimfahim** [comment]
That's the thing. I'm not using any vpn/etc. My bowser is vanilla chrome. I have tried the mirrors, and the smae reslut. is there a way to make Jackett use the same path used by my browser?

**Comment by garfield69** [comment]
double check your jackett dashboard settings. are you using the defaults?
mine look like this:
![image](https://user-images.githubusercontent.com/6933240/71421271-b802ae00-26de-11ea-927c-8eb87d6ab39e.png)

**Comment by fahimfahimfahim** [comment]
Mine is identical with the only exception being Update to prelease is unchecked. Do I need to check that?
I'm using defaults.

I gues the only point I want to add is that my ISP is pretty notorious for blocking some sites, but given that the core 1337x.to site works, I'm wondering if it is something else. (also all the other trackers work as expected; I use ettv, eztv, rarbg, and a host of other private and public ones.

**Comment by garfield69** [comment]
you do not need to tick the pre-release, that is optional and will not make a difference in this case.

I'm sorry, but there are no reasons I can think of why Jackett should behave differently compared to your browser, given the Jackett settings you have enabled, and the system wide choices you have described (no firewall, google DNS, etc).
I use 1337x.to with my Jackett on my win10, ubuntu18 and mojave macOS test systems without problems.

Anyone else in the Jackett community with experience is this topic, please feel free to contribute.

**Comment by ngosang** [comment]
@fahimfahimfahim 1337x is working fine for me in Linux .Net Core. This kind of problems are usually related to network: proxy, vpn or isp blocks. You can try alternative domains.
