### ISSUE TITLE
[torrent9] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#6685]
Neither test or manual search is actually working on this tracker

**Comment by garfield69** [comment]
works for me.
what version of jackett are you on?

**Comment by skuizy** [comment]
Running on latest version atm ().

This is the log I get when testing this tracker : 
```
Dec 30 10:37:28 odroid jackett[18321]: 12-30 10:37:28 Info Found 0 releases from Torrent9
Dec 30 10:37:28 odroid jackett[18321]: 12-30 10:37:28 Error System.Exception: Found no results while trying to browse this tracker
Dec 30 10:37:28 odroid jackett[18321]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 225
Dec 30 10:37:28 odroid jackett[18321]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
Dec 30 10:37:28 odroid jackett[18321]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73 System.Exception: Found no results while trying to browse this tracker
Dec 30 10:37:28 odroid jackett[18321]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 225
Dec 30 10:37:28 odroid jackett[18321]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 128
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Dec 30 10:37:28 odroid jackett[18321]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
Dec 30 10:37:28 odroid jackett[18321]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73

```

**Comment by garfield69** [comment]
edit your torrent9 config with your jackett dashboard and check the **Site Link**.
change it to `https://www.oxtorrent.me/` and try again.

**Comment by skuizy** [comment]
Alright, it's working with this updated site link.

I think it might be a good idea to clean things up as there are some duplicates/inversions :  
GkTorrent : https://www.gktorrent.biz/
OxTorrent : https://www.gktorrent.biz/
Torrent9 : https://www.oxtorrent.me/
Torrent9 clone (torrent9.ch) : https://www.torrent9.so/
