### ISSUE TITLE
[kickasstorrent-kathow]: Got redirected to another domain

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6713]
Jackett Version 0.12.1361.0 
Tracker:  kickasstorrent-kathow
Search: 720p

```
Manual search for "720p" on kickasstorrent-kathow with 0 results.
Jackett.Common.IndexerException: Exception (kickasstorrent-kathow): Got redirected to another domain. Try changing the indexer URL to https://kickass.ws/.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://kickass.ws/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebClientStringResult Result, IHtmlDocument document) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 757
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1262
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 846
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 823
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 227
```

**Comment by garfield69** [comment]
a3f5ef6acfe1ceeadfdc88258a177f8c84dcde20
