### ISSUE TITLE
[freetorrent] Exception: Error while parsing field=date

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#6786]
Jackett cannot parse date for old torrents (the ones older than a year actually as the time string : "an" or "ans" is not translated to "year" or "years")

```
Jan  3 10:52:27 odroid jackett[18321]: 01-03 10:52:27 Error CardigannIndexer (freetorrent): Error while parsing row '
Jan  3 10:52:27 odroid jackett[18321]: <tr>
Jan  3 10:52:27 odroid jackett[18321]: #011<td style="width: 1%;">
Jan  3 10:52:27 odroid jackett[18321]: #011#011<div class="torrent-poster pull-left"></div>
Jan  3 10:52:27 odroid jackett[18321]: #011</td>
Jan  3 10:52:27 odroid jackett[18321]: #011<td style="width: 1%;">
Jan  3 10:52:27 odroid jackett[18321]: #011#011<a href="https://freetorrent.tk/categories/2">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<div class="text-center">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#011<i class="fas fa-tv-retro torrent-icon" data-toggle="tooltip" data-original-title="Séries TV torrent" style="padding-bottom: 10px;"></i>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011</div>
Jan  3 10:52:27 odroid jackett[18321]: #011#011</a>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<div class="text-center" style="padding-top: 5px;">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<span class="label label-success" data-toggle="tooltip" data-original-title="Type">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#011720p
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011</div>
Jan  3 10:52:27 odroid jackett[18321]: #011</td>
Jan  3 10:52:27 odroid jackett[18321]: #011<td>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<a class="view-torrent" href="https://freetorrent.tk/torrents/331">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011Lucifer Saison 3 + 2Bonus Fr 720p NoTag
Jan  3 10:52:27 odroid jackett[18321]: #011#011</a>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<a href="https://freetorrent.tk/torrents/download/331">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<button class="btn btn-primary btn-circle" type="button" data-toggle="tooltip" data-original-title="Télécharger">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#011<i class="fas fa-download"></i>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011</button>
Jan  3 10:52:27 odroid jackett[18321]: #011#011</a>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<span data-toggle="tooltip" data-original-title="Bookmark" id="torrentBookmark331" torrent="331" state="0" class="torrentBookmark"></span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<br>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<span class="badge-extra text-bold">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<i class="fas fa-upload" data-toggle="tooltip" data-original-title="Uploadeur"></i>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<a href="https://freetorrent.tk/users/Nico1722">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#011Nico1722
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011</a>
Jan  3 10:52:27 odroid jackett[18321]: #011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<a href="https://www.themoviedb.org/tv/63174?language=fr" target="_blank">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<span class="badge-extra text-bold">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#011<span class="text-gold movie-rating-stars">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#011#011<i class="fas fa-thumbs-up" data-toggle="tooltip" data-original-title="Voir plus"></i>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#0117.5/10 (1175 Votes)
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011</a>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<span class="badge-extra text-bold text-pink">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<i class="fas fa-heart" data-toggle="tooltip" data-original-title="Remerciements donnés"></i>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#0113
Jan  3 10:52:27 odroid jackett[18321]: #011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<a href="https://freetorrent.tk/torrents/331#comments">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<span class="badge-extra text-bold text-green">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#011<i class="fas fa-comment" data-toggle="tooltip" data-original-title="commentaires"></i>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#0111
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011</a>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<br>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<span class="badge-extra text-bold">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title=" torrent.genre"></i>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011Crime
Jan  3 10:52:27 odroid jackett[18321]: #011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<span class="badge-extra text-bold">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title=" torrent.genre"></i>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011Drama
Jan  3 10:52:27 odroid jackett[18321]: #011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<span class="badge-extra text-bold">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title=" torrent.genre"></i>
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011Fantasy
Jan  3 10:52:27 odroid jackett[18321]: #011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011</td>
Jan  3 10:52:27 odroid jackett[18321]: #011<td>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<time>il y a 1 an</time>
Jan  3 10:52:27 odroid jackett[18321]: #011</td>
Jan  3 10:52:27 odroid jackett[18321]: #011<td>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<span class="badge-extra text-blue text-bold">11.99 GiB</span>
Jan  3 10:52:27 odroid jackett[18321]: #011</td>
Jan  3 10:52:27 odroid jackett[18321]: #011<td>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<a href="https://freetorrent.tk/torrents/331/peers">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<span class="badge-extra text-green text-bold">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#0111
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011</a>
Jan  3 10:52:27 odroid jackett[18321]: #011</td>
Jan  3 10:52:27 odroid jackett[18321]: #011<td>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<a href="https://freetorrent.tk/torrents/331/peers">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<span class="badge-extra text-red text-bold">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#0110
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011</a>
Jan  3 10:52:27 odroid jackett[18321]: #011</td>
Jan  3 10:52:27 odroid jackett[18321]: #011<td>
Jan  3 10:52:27 odroid jackett[18321]: #011#011<a href="https://freetorrent.tk/torrents/331/history">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011<span class="badge-extra text-orange text-bold">
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011#01112 Fois
Jan  3 10:52:27 odroid jackett[18321]: #011#011#011</span>
Jan  3 10:52:27 odroid jackett[18321]: #011#011</a>
Jan  3 10:52:27 odroid jackett[18321]: #011</td>
Jan  3 10:52:27 odroid jackett[18321]: </tr>':
Jan  3 10:52:27 odroid jackett[18321]: System.Exception: Error while parsing field=date, selector=time, value= ago 1 an: DateTime parsing failed for "ago 1 an": System.Exception: TimeAgo parsing failed, unknown unit: an
Jan  3 10:52:27 odroid jackett[18321]:    at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 74
Jan  3 10:52:27 odroid jackett[18321]:    at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 213
Jan  3 10:52:27 odroid jackett[18321]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1502
Jan  3 10:52:27 odroid jackett[18321]: 01-03 10:52:27 Info CardigannIndexer (freetorrent): Relogin required

```

**Comment by skuizy** [comment]
Workaround seems to be to configure the site in english

**Comment by garfield69** [comment]
Hah!
yes, none of the **unit3d** sites had been around long enough to have torrents older than a few months when I added multi-language translations for dates to the indexers, so I had no examples of what the sites would do for torrents past 12 months (although on reflection I could have guessed they would use **year**, although I have seen sites that use **60 weeks**, or **30 months**.)
I'll add translations for **year** to these indexers shortly.

**Comment by garfield69** [comment]
jackett 0.12.1415
