### ISSUE TITLE
[sharewood] False BadGateway ?

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#6789]
Sometimes I get a timeout error on sharewood error during a search with lazylibrarian.

The log from LL doesn't seems wrong :
```
03-janv.-2020 15:26:17 - DEBUG   :: SEARCHALLBOOKS : providers.py:get_capabilities:232 : Using stored capabilities for http://localhost:9117/api/v2.0/indexers/sharewood/results/torznab/
03-janv.-2020 15:26:17 - DEBUG   :: SEARCHALLBOOKS : providers.py:IterateOverNewzNabSites:505 : [IterateOverTorzNabSites] - http://localhost:9117/api/v2.0/indexers/sharewood/results/torznab/
03-janv.-2020 15:26:17 - DEBUG   :: SEARCHALLBOOKS : providers.py:NewzNabPlus:992 : SearchType [book] with Host [http://localhost:9117/api/v2.0/indexers/sharewood/results/torznab/] mode [torznab] using api [apikey removed] for item [{'bookid': '4908817', 'bookName': 'Delius', 'bookSub': "Une chanson d'ete", 'authorName': 'Sabrina Calvo', 'library': 'eBook', 'searchterm': "Sabrina Calvo Delius: Une chanson d'ete"}]
03-janv.-2020 15:26:17 - DEBUG   :: SEARCHALLBOOKS : providers.py:ReturnSearchTypeStructure:1180 : torznab Search parameters set to {'t': 'search', 'apikey': 'apikey removed', 'q': "b'Sabrina Calvo' b'Delius'", 'cat': '3030, 8010, 8020, 8030'}
03-janv.-2020 15:26:17 - DEBUG   :: SEARCHALLBOOKS : providers.py:NewzNabPlus:1008 : URL = http://localhost:9117/api/v2.0/indexers/sharewood/results/torznab/api?t=search&apikey=apikey removed&q=b%27Sabrina+Calvo%27+b%27Delius%27&cat=3030%2C+8010%2C+8020%2C+8030
03-janv.-2020 15:26:47 - DEBUG   :: SEARCHALLBOOKS : cache.py:fetchURL:136 : fetchURL: retrying - got timeout on http://localhost:9117/api/v2.0/indexers/sharewood/results/torznab/api?t=search&apikey=apikey removed&q=b%27Sabrina+Calvo%27+b%27Delius%27&cat=3030%2C+8010%2C+8020%2C+8030
03-janv.-2020 15:27:17 - ERROR   :: SEARCHALLBOOKS : cache.py:fetchURL:134 : fetchURL: Timeout getting response from http://localhost:9117/api/v2.0/indexers/sharewood/results/torznab/api?t=search&apikey=apikey removed&q=b%27Sabrina+Calvo%27+b%27Delius%27&cat=3030%2C+8010%2C+8020%2C+8030
03-janv.-2020 15:27:17 - ERROR   :: SEARCHALLBOOKS : providers.py:NewzNabPlus:1042 : Error reading data from http://localhost:9117/api/v2.0/indexers/sharewood/results/torznab: Timeout HTTPConnectionPool(host='localhost', port=9117):Read timed out. (read timeout=30)
03-janv.-2020 15:27:17 - INFO    :: SEARCHALLBOOKS : providers.py:BlockProvider:427 : Blocking provider http://localhost:9117/api/v2.0/indexers/sharewood/results/torznab/ for 60 minutes because Timeout HTTPConnectionPool(host='localho...
```

By the look of jackett logs, something is wrong, but the site is still accessible, so no reason to get a 502 :

```
Jan  3 15:27:20 odroid jackett[18321]: 01-03 15:27:20 Error Error on 20200103152720 for Sharewood.txtSystem.Exception: Request to https://www.sharewood.tv/ failed (Error BadGateway) - The tracker seems to be down.
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.CheckTrackerDown(WebClientStringResult response) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 583
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 453
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 740
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1269
Jan  3 15:27:20 odroid jackett[18321]: <div class="row torrent-detail">
Jan  3 15:27:20 odroid jackett[18321]:                 <br>
Jan  3 15:27:20 odroid jackett[18321]:                 <div class="col-md-8 col-titre">
Jan  3 15:27:20 odroid jackett[18321]:                     Nom
Jan  3 15:27:20 odroid jackett[18321]:                 </div>
Jan  3 15:27:20 odroid jackett[18321]:                 <div class="col-md-2 col-detail">
Jan  3 15:27:20 odroid jackett[18321]:                     <div class="col-xs-4">
Jan  3 15:27:20 odroid jackett[18321]:                         Âge
Jan  3 15:27:20 odroid jackett[18321]:                     </div>
Jan  3 15:27:20 odroid jackett[18321]:                     <div class="col-xs-4">
Jan  3 15:27:20 odroid jackett[18321]:                         Taille
Jan  3 15:27:20 odroid jackett[18321]:                     </div>
Jan  3 15:27:20 odroid jackett[18321]:                     <div class="col-xs-4">
Jan  3 15:27:20 odroid jackett[18321]:                         Commentaires
Jan  3 15:27:20 odroid jackett[18321]:                     </div>
Jan  3 15:27:20 odroid jackett[18321]:                 </div>
Jan  3 15:27:20 odroid jackett[18321]:                 <div class="col-md-2 col-detail">
Jan  3 15:27:20 odroid jackett[18321]:                         <div class="col-xs-4">
Jan  3 15:27:20 odroid jackett[18321]:                             S
Jan  3 15:27:20 odroid jackett[18321]:                         </div>
Jan  3 15:27:20 odroid jackett[18321]:                         <div class="col-xs-4">
Jan  3 15:27:20 odroid jackett[18321]:                             L
Jan  3 15:27:20 odroid jackett[18321]:                         </div>
Jan  3 15:27:20 odroid jackett[18321]:                         <div class="col-xs-4">
Jan  3 15:27:20 odroid jackett[18321]:                             C
Jan  3 15:27:20 odroid jackett[18321]:                         </div>
Jan  3 15:27:20 odroid jackett[18321]:                 </div>
Jan  3 15:27:20 odroid jackett[18321]:             </div>
Jan  3 15:27:20 odroid jackett[18321]:
Jan  3 15:27:20 odroid jackett[18321]:     <br>
Jan  3 15:27:20 odroid jackett[18321]:     <div class="text-center">
Jan  3 15:27:20 odroid jackett[18321]:
Jan  3 15:27:20 odroid jackett[18321]:     </div>
Jan  3 15:27:20 odroid jackett[18321]:
Jan  3 15:27:20 odroid jackett[18321]: 01-03 15:27:20 Error Jackett.Common.IndexerException: Exception (sharewood): Request to https://www.sharewood.tv/ failed (Error BadGateway) - The tracker seems to be down.
Jan  3 15:27:20 odroid jackett[18321]:  ---> System.Exception: Parse error
Jan  3 15:27:20 odroid jackett[18321]:  ---> System.Exception: Request to https://www.sharewood.tv/ failed (Error BadGateway) - The tracker seems to be down.
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.CheckTrackerDown(WebClientStringResult response) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 583
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 453
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 740
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1269
Jan  3 15:27:20 odroid jackett[18321]:    --- End of inner exception stack trace ---
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 846
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
Jan  3 15:27:20 odroid jackett[18321]:    --- End of inner exception stack trace ---
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 823
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 427 Jackett.Common.IndexerException: Exception (sharewood): Request to https://www.sharewood.tv/ failed (Error BadGateway) - The tracker seems to be down.
Jan  3 15:27:20 odroid jackett[18321]:  ---> System.Exception: Parse error
Jan  3 15:27:20 odroid jackett[18321]:  ---> System.Exception: Request to https://www.sharewood.tv/ failed (Error BadGateway) - The tracker seems to be down.
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.CheckTrackerDown(WebClientStringResult response) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 583
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 453
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 740
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1269
Jan  3 15:27:20 odroid jackett[18321]:    --- End of inner exception stack trace ---
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 846
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
Jan  3 15:27:20 odroid jackett[18321]:    --- End of inner exception stack trace ---
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 823
Jan  3 15:27:20 odroid jackett[18321]:    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 427

```

**Comment by garfield69** [comment]
nope, the sharewood server is unreliable at times. the 502 is a genuine error. I get them occasionally when I use the browser on this site. But I have not had it using jackett this morning.
