### ISSUE TITLE
Many trackers unavailable

### ISSUE THREAD

**Issue by Treverr** [Jackett/Jackett#6796]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  Jackett Version 0.12.1402.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
I have 12 indexers added, and all but just a couple of them time out when testing. However when check the logs and curl the page, it works fine. So I don't know why Jackett isn't getting a response?

<img width="896" alt="Screen Shot 2020-01-03 at 1 30 26 PM" src="https://user-images.githubusercontent.com/5624521/71750434-35d85f00-2e2d-11ea-9ad8-427a140a21a2.png">

I see a log: `2020-01-03 13:28:46.7586 Debug No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.`

Followed by: ```2020-01-03 13:28:46.7551 Error Jackett.Common.IndexerException: Exception (thepiratebay): The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241```

[log.txt](https://github.com/Jackett/Jackett/files/4020977/log.txt)

**Comment by garfield69** [comment]
are you using a proxy setting in your jackett dashboard or just defaults?
which platform are you running jackett on and which installation package did you install?

**Comment by Treverr** [comment]
Hi @garfield69,

No proxy, im running this on Linux in the non-mono version.

**Comment by ngosang** [comment]
I can confirm all those trackers are working fine for me.

**Comment by garfield69** [comment]
same here. they all work for me. so we can assume that there is something going on either with your ISP provided, or DNS or machine setup.
the `Debug No response compression available` can be ignored, its not an error.

you are using a Docker Jackett image per chance?
or have you installed one of the standard linux Jackett packages, such as AMD64 or ARM54/ARM32?

**Comment by ngosang** [comment]
No user response. I think this network related: proxy, vpn or isp.
