### ISSUE TITLE
[mteamtp2fa] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by bingoxo** [Jackett/Jackett#6830]
Jackett Version 0.12.1449.0
login in the site works , 2fa enabled so i used the cookie method but still not working

**Comment by garfield69** [comment]
are you fetching the cookie from a browser on the same machine that is running Jackett?
I don't have an a/c on this site so I cannot test this for myself.
you could turn on enhanced logging to see if there is a clue in the returned html
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by bingoxo** [comment]
no i was fetching the cookie from my local pc and jackett is installed in a server , i input a cookie from server but it gave same error
here is the enhanced full log : 
https://privatebin.net/?ef6c8884ace08d2b#9sGss2FGihuRmieZ7TQsTfYArrtznuWDU73rTTmTo6xs

**Comment by garfield69** [comment]
yeah, the logs show that you are being redirected to https://pt.m-team.cc/verify.php?returnto=%2Ftorrents.php  

so it looks like using cookies is not going to solve the 2fa challenge for this site.
I'll delete this indexer since it does not work.

**Comment by bingoxo** [comment]
Actually in the browser , it sometimes does that , but reloading the torrents page fixes it , i just tried pasting the cookies in an icognito tab and login worked , so there must be a way to fix this , are you in irc/discord , somewhere where we can chat faster ?

**Comment by garfield69** [comment]
Yah, Nah. I'm not on discord.
But from what you are saying I've reached the end of the support I can offer, since I specialise in supporting the indexer written in yaml that the Jackett Cardigann's processor provides, and I've already coded the only alternative to the regular login config, which is the cookie login config.
I cant control how the cookie is used from within the yaml indexer.

If you can make the cookie in an incognito tab work, then what we are likely talking about is a change to the Cardigann C# code someplace to allow its cookie login processing (that I invoke via the yaml indexer) to do something different so it works.
This will requires a C# dev to analyse and code a solve for, which in not my cup of tea.
Ping to any C# volunteers who can help out with this one.

**Comment by JayXon** [comment]
I'm trying to debug this further, in #12495 I've found out that user agent could cause the redirect, but setting user agent in jackett doesn't seem to work.

However I just verified that curl **inside the jackett container** successfully returned the page without redirect
`curl -v --cookie "tp=REDACTED; cf_clearance=REDACTED" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" https://kp.m-team.cc/index.php`
So either the user agent config was not picked up by jackett, or something else is different that made it redirect.

Is there anyway to make Jackett log all the http headers it sends?
cc @ilike2burnthing

**Comment by ilike2burnthing** [comment]
You can look at the debug logs with the test version of the indexer I provided in your OP.

**Comment by JayXon** [comment]
Is that the same as enhanced logging? I can only see cookies
```
2021-11-02 20:05:54.1526 Debug CardigannIndexer (mteamtp2fa-test): Cookies after login: tp=REDACTED 
2021-11-02 20:05:54.1534 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://kp.m-team.cc/index.php) 
2021-11-02 20:05:54.3174 Debug WebClient(HttpWebClient2): Returning Redirect => https://kp.m-team.cc/verify.php?returnto=%2Findex.php 0 bytes 
2021-11-02 20:05:54.3200 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 172.2836ms 
2021-11-02 20:05:54.3200 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2021-11-02 20:05:54.3205 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 816
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 816
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
```

**Comment by JayXon** [comment]
Turns out it indeed wasn't picking the user agent because `TestLogin()` is using `Definition.Search?.Headers`: https://github.com/Jackett/Jackett/blob/9da7c9b17839e3f463e961d494067f66330fc026/src/Jackett.Common/Indexers/CardigannIndexer.cs#L798
So I changed the test yml to move it from `login.inputs` to `search.headers` and I also had to change `"[ .Config.useragent ]"` to `"{{ .Config.useragent }}"`, and it worked!

**Comment by ilike2burnthing** [comment]
Great minds, I was literally just testing that out as it didn't make sense to me why that would use square brackets. Looks like it's wrong elsewhere as well, so need to fix that too.

Nicely spotted Re: it needing to be in the search block, not the login block.

**Comment by garfield69** [comment]
v0.19.138

**Comment by ilike2burnthing** [comment]
@JayXon can you confirm that torrent downloads for mteamtp2fa are working for you with this solution?

Running into an issue with https://github.com/Jackett/Jackett/issues/6970#issuecomment-958733167 and https://github.com/Jackett/Jackett/issues/9958#issuecomment-959058377 where adding the indexer and searching works fine, but trying to download shows as logged out.

yggcookie however works fine https://github.com/Jackett/Jackett/commit/b7247ec944345d8f33a3df1286342396bbad5631.

Any insight would be appreciated.

**Comment by JayXon** [comment]
Yeah, search works but download doesn't, there are a bunch of redirections
```
2021-11-03 13:36:49.1086 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://kp.m-team.cc/download.php?id=521314&https=1) 
2021-11-03 13:36:49.1365 Debug WebClient(HttpWebClient2): Returning Redirect => https://kp.m-team.cc/verify.php?returnto=%2Fdownload.php%3Fid%3D521314%26https%3D1 0 bytes 
2021-11-03 13:36:49.1365 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://kp.m-team.cc/verify.php?returnto=%2Fdownload.php%3Fid%3D521314%26https%3D1) 
2021-11-03 13:36:49.1594 Debug WebClient(HttpWebClient2): Returning Redirect => https://kp.m-team.cc/download.php?id=521314&https=1 0 bytes 
2021-11-03 13:36:49.1594 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://kp.m-team.cc/download.php?id=521314&https=1) 
2021-11-03 13:36:49.1887 Debug WebClient(HttpWebClient2): Returning Redirect => https://kp.m-team.cc/login.php?returnto=%2Fdownload.php%3Fid%3D521314%26https%3D1 0 bytes 
2021-11-03 13:36:49.1887 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://kp.m-team.cc/login.php?returnto=%2Fdownload.php%3Fid%3D521314%26https%3D1) 
```
Again, curl inside jackett container worked, so jackett probably aren't using the user agent when downloading
`curl -O -J -L --cookie "tp=REDACTED" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" https://kp.m-team.cc/download.php?id=521314&https=1`

**Comment by JayXon** [comment]
https://github.com/Jackett/Jackett/blob/9da7c9b17839e3f463e961d494067f66330fc026/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1740
I think because the yml doesn't have a `download` section, this entire if were skipped, and it's just doing `base.Download` without the custom headers 
https://github.com/Jackett/Jackett/blob/9da7c9b17839e3f463e961d494067f66330fc026/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1838

**Comment by ilike2burnthing** [comment]
yggcookie doesn't use a download block either, so it's weird that it works.

I don't suppose it's as simple as changing L1838 to this? (I'm not a C# dev)
```
var headers = ParseCustomHeaders(Definition.Search?.Headers, GetBaseTemplateVariables());
return await base.Download(link, method, link.ToString(), headers);
```

**Comment by JayXon** [comment]
> yggcookie doesn't use a download block either, so it's weird that it works.
> 

Maybe that site doesn't check user agent when downloading
> I don't suppose it's as simple as changing L1838 to this? (I'm not a C# dev)
> 
> ```
> var headers = ParseCustomHeaders(Definition.Search?.Headers, GetBaseTemplateVariables());
> return await base.Download(link, method, link.ToString(), headers);
> ```

I think this could work

**Comment by ilike2burnthing** [comment]
This should be resolved by https://github.com/Jackett/Jackett/pull/12504.

You can either wait for the next release in a few hours or try the [pipelines build](https://dev.azure.com/Jackett/0f0cb3d0-9b6b-4a86-876d-0c2e17c18801/_apis/build/builds/4640/artifacts?artifactName=drop&api-version=6.0&%24format=zip).

**Comment by garfield69** [comment]
v0.19.162

**Comment by JayXon** [comment]
Can confirm download works now
