### ISSUE TITLE
[demonoid] Error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6861]
Tracker: demonoid
Search: silicon valley

I thougth this was caused by #6845 so I tested all public trackers. This is the only one with date parsing. I don't know if it's related to the PR.

```
Manual search for "silicon valley" on demonoid with 0 results.
CardigannIndexer (demonoid): Error while parsing row '
<tr>
	<td rowspan="2" align="center" class="tone_2_bl">
		<a href="/files/?category=12">
			<img border="0" src="/images/categories/tv.gif" alt="Biography">
		</a>
	</td>
	<td colspan="9" class="tone_1_pad">
		<a href="/files/details/4141/026211940/">Silicon Valley Season 1 1080p (HIGH QUALITY HBO SHOW!!)
		</a>
	</td>
	<td width="100%" class="tone_1_bl" align="left">
		<span class="subcategory">
			<a class="subcategory" href="/files/?category=12&amp;subcategory=144">Biography</a>
			:
			<a class="subcategory" href="/files/?category=12&amp;language=1">English</a>
		</span>
	</td>
	<td nowrap="" class="tone_2_bl" align="left">
		<a class="username" href="/users/Alexjax100">
			<span class="user">
				<img src="/images/ratio/n01.gif" border="0" width="8" height="8" alt="Ratio: 1.00" title="Ratio: 1.00">
				<img src="/images/p.gif" alt="" width="2" height="1" border="0">Alexjax100</span>
		</a>
	</td>
	<td class="tone_1_bl" nowrap="" align="center">
		<a title="Silicon Valley Season 1 1080p (HIGH QUALITY HBO SHOW!!) " href="/files/details/4141/026211940/#download">
			<img src="/images/dmi.gif" alt="Download torrent" title="Download torrent" width="31" hspace="3" height="16" border="0">
		</a>
	</td>
	<td nowrap="" class="tone_2_bl" align="right">1.83 GB</td>
	<td nowrap="" class="tone_1_bl" align="center">0</td>
	<td nowrap="" class="tone_2_bl" align="center">
		<span class="blue">0</span>
	</td>
	<td nowrap="" class="tone_1_bl" align="center">
		<span class="green">0</span>
	</td>
	<td nowrap="" class="tone_2_bl" align="center">
		<span class="red">0</span>
	</td>
	<td nowrap="" class="tone_1_bl" align="center">
		<img src="/images/health/0.jpg" alt="">
	</td>
</tr>':

System.Exception: DateTime parsing failed for "on Sunday, Aug 04, 2019": System.FormatException: String 'on Aug 04, 2019' was not recognized as a valid TimeSpan.
   at System.Globalization.TimeSpanParse.TimeSpanResult.SetBadTimeSpanFailure()
   at System.Globalization.TimeSpanParse.ProcessTerminal_HM(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.ProcessTerminalState(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.TryParseTimeSpan(ReadOnlySpan`1 input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
   at Jackett.Common.Utils.DateTimeUtil.ParseTimeSpan(String time) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 99
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 187
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 244
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1638
```

**Comment by garfield69** [comment]
yes, this is caused by #6845, I just tested it **with out** the patch and it works again.

the demonoid indexer uses the **dateheaders** statement to pick up rows that contain the date (because there is no date selectors in the torrent results rows like other indexers, where we can get the date using the **date** filter in the **fields** section.)
```yaml
    rows:
      selector: table.font_12px tr:has(td[class^="tone_1"])
      after: 1
      dateheaders:
        selector: tr td.added_today:not(:contains("Sponsored links"))
        filters:
          - name: replace
            args: ["Added ", ""]
          - name: replace
            args: ["on ", ""]
    fields:
      title:
        selector: a[href^="/files/details/"]
```

**Comment by ngosang** [comment]
I think this workaround will work. This will give me time to see if I can fix that in code.
Convert `Added on Saturday, Jan 04, 2020`
To `Sat, Jan 04, 2020`
Using replace with all days of the week.

**Comment by garfield69** [comment]
yup that works.

**Comment by garfield69** [comment]
Jackett 0.12.1494
