### ISSUE TITLE
[lostfilm] Exception (lostfilm): Object reference not set to an instance of an object.: Parse error (Config)

### ISSUE THREAD

**Issue by darki73** [Jackett/Jackett#6945]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  0.12.1572.0
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------
With LostFilm.tv being blocked in Russia, they had to change something in their code in order to be able to provide files (the original tracker was blocked), so they've changed it to `http://insearch.site/`. And now this error occurs for some reason (cant even log-in through the Jackett, can do so through website though)

```
2020-01-14 11:38:17.0482 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 1366.2293ms
2020-01-14 11:38:17.0482 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-01-14 11:38:17.0482 Error Jackett.Common.IndexerException: Exception (lostfilm): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 603
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 848
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 603
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 403
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 848
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 415
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 362
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 848
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 368
   at Jackett.Common.Indexers.LostFilm.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 200
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 825
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73 Jackett.Common.IndexerException: Exception (lostfilm): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 603
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 848
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 603
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 403
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 848
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 415
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 362
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 848
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 368
   at Jackett.Common.Indexers.LostFilm.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/LostFilm.cs:line 200
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 825
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
2020-01-14 11:38:17.0521 Debug No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.
2020-01-14 11:38:17.0521 Debug Connection id "0HLSOND5UQE25" completed keep alive response.
2020-01-14 11:38:17.0521 Info Request finished in 1377.8467ms 500 application/json
```

**Comment by garfield69** [comment]
strange. 
works for me, albeit it is running very very slowly (took several minutes to populate a keyword-less query)
but the download link works for me as well.
![image](https://user-images.githubusercontent.com/6933240/72370721-b2413b00-3767-11ea-9a04-bfeada8c4ce4.png)
I see in the logs the internal redirects using insearch.site but that does not prevent the indexer from fetching the results.
there are a couple other tickets #6801 #6843
hopefully a c# dev volunteer will take a look at them all, each ticker is unique and not a duplicate, but all related to this site.

**Comment by darki73** [comment]
@garfield69 Thank you for your reply. I should've probably mentioned the fact that i am running behind the proxy (my own SOCKS5 server on GCP), maybe that might be an issue aswell.

**Comment by denozord** [comment]
Lostfilm is blocked by Roskomnadzor. The guys from the film are protected as they can.

The guys set up Cloudflare and turned on a redirect to the MTS blocking page. How exactly this works at the moment is not entirely clear.
Therefore, to work Jackett with the Lostfilm, you need to use Proxies. However, not all proxies open a hostfilm without a lock page or Cloudflare.

Ну и по-русски :) 
Лостфильм блокируется Роскомнадзором. Ребята из лостфильм защищаются как могут.

Ребята настроили Клоудфларе и ключили редирект на страницу блокировки МТС. Как именно это работает на текущий момент не совсем понятно. 
Поэтому для работы Jackett с лостфильм нужно использовать Прокси. Однако не все прокси открывают лостфильм без страницы блокировки или Клаудфларе.

**Comment by SuberSeb** [comment]
> С 10 попытки у меня всё заработало корректно

Как именно обошли блокировку? У меня через антизапрет не заводится.

**Comment by denozord** [comment]
> 
> 
> > С 10 попытки у меня всё заработало корректно
> 
> Как именно обошли блокировку? У меня через антизапрет не заводится.

Через NordVPN обходил. Один из финских серверов нормально открывает ЛостФильм.

**Comment by garfield69** [comment]
jackett 0.12.1623

**Comment by krin-san** [comment]
@darki73, I have fixed an issue which results in indexer exception. Code was not expecting to get an empty JSON response. But that's just a consequences, not the reason. But as I see you already found the failure reason: governmental blocking. There's nothing C# developer _(I'm not the one to be fair)_ can help here =]
