### ISSUE TITLE
TVchaos cannot set up (linuxserver docker) Synology

### ISSUE THREAD

**Issue by mickeypeach** [Jackett/Jackett#6977]
Just setting up a new synology and cannot get TVchaos to work. IT works on my old pc. so I it's not the site itself. version Jackett Version 0.12.1590.0
2020-01-19 09:32:48.9391 Error Jackett.Common.IndexerException: Exception (blutopia): Login Failed, got redirected.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 788
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1328
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 848
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1651
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 333
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 821
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 373 Jackett.Common.IndexerException: Exception (blutopia): Login Failed, got redirected.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 788
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1328
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 848
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1651
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 333
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 821
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 373

**Comment by garfield69** [comment]
the stack trace you provided is for blutopia and not tvchaos.
note that tvchaos switched in november to a new engine.
the old `TV Chaos` indexer is obsolete and was removed.
the new indexer `TVChaosUK` is the current indexer.
if you are having trouble using TVChaosUK then 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

Thanks.

**Comment by mickeypeach** [comment]
Hi, thanks for looking 
Having issues with blutopia too (it was working with earlier version), it's asking for the cookie but Blutopia uses password .
[log1.txt](https://github.com/Jackett/Jackett/files/4083572/log1.txt)

**Comment by garfield69** [comment]
(1) the blutopia indexer required the cookie method to access the site.
This is because blutopia changed something in their username/password login process that breaks Jackett when it tries to use it.
Using the cookie method is currently the only way to access blutopia from Jackett.
works for me.
you are currently getting a redirection back to the login page, which means that for some reason your cookie is not being accepted. 
check you are copying the complete cookie from your browser. using the method shown in the config info. 
Are you using a browser running on the same machine as jackett to capture your cookie string?
Also, cookies expire from time to time, so you may need to refresh the cookie in the config with the latest browser session if you have not done so recently.

(2) your tvchaosuk login is being rejected, but it is not clear from the error message why this is.
the standard username/password login shod work, it does for me.
I would try using the trashbin icon on your jackett dashboard to delete the active indexer, and add a fresh one from the add-indexer page. reenter your current username/password even if it has been pre-loaded.
if it still fails, then double check with a browser login that your account is valid, has no outstanding alerts, low ratio, or unread messages or notices.

**Comment by mickeypeach** [comment]
OK, some I'm a dumb ass. I was putting in the wrong password for TVCHAOS. My apologies for wasting your time.
Blutopia, I was copying the string from the word Token, when I should have selected the whole text from lavarel onwards.
I hope my stupidity can help someone else.

thanks
