### ISSUE TITLE
[mejortorrent] Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6988]
Tracker: mejortorrent
Searches:
* avi
* iso
* spa

```
Manual search for "avi" on mejortorrent with 0 results.
Jackett.Common.IndexerException: Exception (mejortorrent): Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.MejorTorrent.MejorTorrentRequester.MakeRequest(Uri uri, RequestType method, IEnumerable`1 data, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 813
   at Jackett.Common.Indexers.MejorTorrent.MoviePerformer.<>c__DisplayClass7_0.<<FetchMovies>b__2>d.MoveNext() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at Jackett.Common.Indexers.MejorTorrent.MoviePerformer.FetchMovies(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 622
   at Jackett.Common.Indexers.MejorTorrent.MoviePerformer.FetchMoviesBasedOnLongestWord(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 579
   at Jackett.Common.Indexers.MejorTorrent.MoviePerformer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 569
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query, Int32 attempts) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 118
   at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/MejorTorrent.cs:line 74
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 825
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 227
```

**Comment by ngosang** [comment]
Related to #5587

NOTE: The indexer code is a shi*. It has to be rewritten from scratch.

**Comment by garfield69** [comment]
jackett 0.12.1669
