### ISSUE TITLE
Failed to download from 1337x (InvalidBencodeException)

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [Jackett/Jackett#7005]
Provide a description of the feature request or bug, the more details the better.
Using qBittorrent v4.2.1 on Linux
Using Jackett 0.12.1632.0 on Linux (separate machine)

qBittorrent is configured to use Jackett as an RSS feed (repeatedly -- different searches)

Log is as follows: [log.txt](https://github.com/Jackett/Jackett/files/4105308/log.txt)

The main stacktrace and surrounding log lines is at the bottom;
```
2020-01-23 22:23:20.5356 Error Error downloading 1337x https://1337x.to/torrent/4257189/Star-Trek-Picard-2020-S01E01-Remembrance-1080p-AMZN-Webrip-x265-10bit-EAC3-5-1-Goki/ System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/DownloadController.cs:line 101
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/DownloadController.cs:line 101
2020-01-23 22:23:20.5405 Info Executing HttpStatusCodeResult, setting HTTP status code 404 
2020-01-23 22:23:20.5405 Info Executed action Jackett.Server.Controllers.DownloadController.Download (jackett) in 3511.9491ms 
2020-01-23 22:23:20.5405 Info Executed endpoint 'Jackett.Server.Controllers.DownloadController.Download (jackett)' 
2020-01-23 22:23:20.5405 Debug Connection id "---snip---" completed keep alive response. 
2020-01-23 22:23:20.5450 Info Request finished in 3529.4729ms 404  
```

**Comment by garfield69** [comment]
the log shows that the .torrent you tried to download from 1337x was provided by the itorrents.org link on that 1337x torrents details page, but itorrents.org could not provide the file, and redirected to https://www.limetorrents.info/home/, which caused the failed download error.

this can happen when, for instance, the torrent is very newly loaded on 1337x, and itorrents.org does not yet have it in its database. it can sometimes take up to 4 hours for itorrents.org to have it available.

there is nothing jackett can do in this instance.

you have several options:
a) try again later.
b) switch to one of the other .torrent links that 1337x makes available (see the 1337x indexer config page for choices). But note that the other .torrent provides that 1337x makes links available to may also not have the .torrent file ready for download, especailly of the torrent is very fresh.
c) switch to download a magnet. This is usually always available. Configure the option in your 1337x indexer config.

**Comment by A-UNDERSCORE-D** [comment]
I would use the magnet option, but it causes qBittorrent to throw an error: `Cannot download  [link] The Network Access API cannot honor the request because the protocol is not known`. Neither qBittorrent nor Jackett show any errors in their logs (I may need a debug build of qBittorrent, but I want to check on this side first). I may end up opening an issue on qBittorrent's side for this. *however*, this only happens with this particular RSS feed (as in, the 1337x feed. Feeds from other indexers work fine when providing magnets)

**Comment by A-UNDERSCORE-D** [comment]
Oh I should have done some further research before that response: https://github.com/qbittorrent/qBittorrent/issues/11877 exists, so this is a qBittorrent issue.
