### ISSUE TITLE
Error Performing Update Raspberry Pi

### ISSUE THREAD

**Issue by cookemmm** [Jackett/Jackett#7012]
Jackett on my Raspberry Pi will not auto update or update when I click the button in the UI. Here is what i see in the log file.

2020-01-24 20:38:46.4222 Info New release found. Current: v0.12.1590 New: v0.12.1635
2020-01-24 20:38:46.4222 Info Downloading release v0.12.1635 It could take a while...
2020-01-24 20:40:27.8978 Error Error performing update. System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
   at Jackett.Common.Utils.Clients.WebClient.GetBytes(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 102
   at Jackett.Common.Services.UpdateService.DownloadRelease(List`1 assets, Boolean isWindows, String version) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/UpdateServic
e.cs:line 266
   at Jackett.Common.Services.UpdateService.CheckForUpdates() in /home/appveyor/projects/jackett/src/Jackett.Common/Services/UpdateService.cs:line 153

**Comment by garfield69** [comment]
looks like the request to fetch the archive is timing out.
most likely this is due to either a fire wall or other anti malware software or AD blocker (pihole?) that has blacklisted the github address https://github.com/Jackett/Jackett/releases/download/etc...etc...etc

if you use a browser on the same machine that is running jackett, and try to download https://github.com/Jackett/Jackett/releases/download/v0.12.1635/Jackett.Binaries.LinuxARM32.tar.gz for instance, does it download?

**Comment by cookemmm** [comment]
yes i can manually do it by using 

wget https://github.com/Jackett/Jackett/releases/download/v0.12.1635/Jackett.Binaries.LinuxARM32.tar.gz

that is how i manually update since the auto update is failing

**Comment by garfield69** [comment]
locate the updater.txt log file and post it here for us to take a look at. it may contain additional info.
It's usually found in `~/.config/Jackett/`

**Comment by cookemmm** [comment]
[updater.txt](https://github.com/Jackett/Jackett/files/4111589/updater.txt)
[log.txt](https://github.com/Jackett/Jackett/files/4111590/log.txt)

here are the log.txt and updater.txt log files

**Comment by garfield69** [comment]
well, the updater.txt shows that the 0.12.1590 updater ran fine, but there is nothing else after that, which is inline with the log.txt that shows that since the download for 0.12.1635 never competed the updater was not launched.

but as to the reason why the download fails, that is a mystery to me.

the updater works for me on windows 10, ubuntu18 linux, and mojave macos.

Ping any volunteers that can help with this one.

**Comment by cookemmm** [comment]
is there a timeout for the download? if so can the timeout be extended? the wget took 1m and 52secs

Jackett.Binaries.LinuxARM32.tar.gz             100%[=================================================================================================>]  43.81M   281KB/s    in 1m 52s

**Comment by rrrevin** [comment]
What's the health of your SD card? If you are reading/writing everything to it (and not an external drive), you may have hit the life of cells on that thing. I've burnt out many an SD card by doing everything to it, even a 128GB card.

Look in /var/log/syslog, or other logs in /var/log.

**Comment by cookemmm** [comment]
SD card seems fine.....i have not had any issues reading/writing from the card with a manual download....i just wonder if the download is timing out

**Comment by junglebus** [comment]
It's definitely a timeout, httpClient default is 100 seconds which matches the logs
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout

**Comment by CharlesHenryVIII** [comment]
Is there a way to turn off the timeout or a way to manually download/install an update without ruining configurations?

**Comment by garfield69** [comment]
the timeout is a sign that something is holding up the download from starting.
once started, I believe that the download completes, however long it takes, unless that gets interupted in some way.
so the question is what is preventing the download taking place when jackett requests it, and why is that different from you doing the download from your browser. 
you can manually install at any time.
the config folder contents are preserved during installatllations.

**Comment by CharlesHenryVIII** [comment]
Thanks for the quick reply garfield69, I just updated and if I run into the same issue with this version I'll look into what's causing the problem.
