### ISSUE TITLE
[bakabt] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by stephenbrannen** [Jackett/Jackett#7013]
### Summary
Adding BakaBT tracker configuration in the UI fails due to finding no results.

### Environment
-  Jacket Version 0.12.1635.0

### Steps to Reproduce
1. Click Add Indexer on main page
2. Search for BakaBT
3. Click Configure button
4. Fill out username/password field
5. Click Okay

### Expected Results
The connection test succeeds and the configuration is saved.

### Actual Results
The below exception is thrown in the <path-to>/config/Jackett/log.txt file:
```2020-01-24 22:24:49.9690 Error WebClient(HttpWebClient2NetCore).GetString(Url:https://bakabt.me/login.php): No encoding detected, defaulting to UTF-8 
2020-01-24 22:24:49.9690 Debug WebClient(HttpWebClient2NetCore): Returning OK => <!doctype html>
<html lang="en" class="splash">
<head>
    <meta name="flattr:id" content="mezy22">
	<meta charset="UTF-8">
	<link rel="stylesheet" href="/resources/css/HereNow.css">
	<script src='resources/js/datetime.js' async defer></script>
	<title>Here Now</title>
</head>
<body>
	<div class="splash">
		<div class="container">
			<div class="spacey-quote">
				<div class="line">&#8220;And the future never comes.</div>
				<div class="line line-right">What comes is always here now.&#8221;</div>
				<div class="line-right">-Osho</div>
			</div>
			<form method="post" action="/login.php" id="loginForm">
				<label class="singleLined">u: <input type="text" name="username" autofocus /></label>
				<label class="singleLined">p: <input type="password" name="password" onfocus="formInUse = true;" /></label>
				<button type="submit" class="border button g-recaptcha"
					data-sitekey="6LduHjEUAAAAALQZpICmAtjpboL3ZfISVFItJIXs"
					data-callback="recaptchaSubmit">One now</button>
				<p><a href="/recover.php">Recover</a></p>
				<img src="/resources/img/bg_1366.png" />
				<input type="hidden" name="loginKey" value="d4bc5246535a">
			</form>
		</div>
	</div>

<script type="text/javascript">
var recaptchaSubmit = function (){
	document.getElementById('loginForm').submit();
};

(function timeToLogin(){
	var reportBackNode = document.querySelector('[data-timeToLogin]');
	
	if(!reportBackNode) return;
	
	document.querySelector('#loginForm input[type=submit]');
	
	var nowInSecs = new Date().getTime() / 1000;
	var loginOKInSecs = +reportBackNode.getAttribute('data-timeToLogin');
	var whenLogin = (nowInSecs + loginOKInSecs + 1) * 1000;
	
	var loginCountDown = function (){
		var now = new Date().getTime();
		var loginIn = whenLogin - now;
		if(loginIn > 0){
			var timeLeft = new Date(loginIn);
			var reportTimeLeft = 'in ';
			var parseString = '';
			if(timeLeft.getUTCDate() > 1){
				reportTimeLeft += (timeLeft.getUTCDate() - 1) + 'd';
			}
			parseString += 'H\\h';
			parseString += 'i\\ms\\s';
			// reportTimeLeft += timeLeft.getMinutes() + 'h';
			reportTimeLeft += parse_datetime_format(parseString, timeLeft.getTime() + (timeLeft.getTimezoneOffset() * 60000));
			reportBackNode.textContent = reportTimeLeft;
		}else{
			clearInterval(countDown);
			reportBackNode.parentNode.innerHTML = 'Reload the page and try again.';
		}
	};
	
	var countDown = setInterval(loginCountDown, 1000);
	loginCountDown();
	
})()

</script>
</body>
</html> 
2020-01-24 22:24:49.9696 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://bakabt.me/login.php) 
2020-01-24 22:24:51.2907 Debug bbtid=<removed>; expires=Mon, 24-Feb-2020 04:24:51 GMT; Max-Age=2592000; path=/; secure; HttpOnly 
2020-01-24 22:24:51.2907 Debug captchaRequired=0; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0 
2020-01-24 22:24:51.2907 Debug WebClient(HttpWebClient2NetCore): Returning RedirectMethod => https://bakabt.me/login.php  
2020-01-24 22:24:51.2907 Debug WebClient(HttpWebClient2NetCore).GetBytes(Url:https://bakabt.me/login.php) 
2020-01-24 22:24:52.2370 Debug __cfduid=deb79ef8ea6b3b2de8a68bd66acea3ecf1579926291; expires=Mon, 24-Feb-20 04:24:51 GMT; path=/; domain=.bakabt.me; HttpOnly; SameSite=Lax 
2020-01-24 22:24:52.2370 Debug loginIsOK=<removed>; expires=Sat, 25-Jan-2020 15:00:12 GMT; Max-Age=38120 
2020-01-24 22:24:52.2372 Debug captchaRequired=0; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0 
2020-01-24 22:24:52.2372 Debug WebClient(HttpWebClient2NetCore): Returning OK => 5209 bytes 
2020-01-24 22:24:52.2372 Debug Saving new config file: /config/Jackett/Indexers/bakabt.json.<removed>.tmp 
2020-01-24 22:24:52.2372 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://bakabt.me/browse.php?only=0&hentai=1&incomplete=1&lossless=1&hd=1&multiaudio=1&bonus=1&reorder=1&q=) 
2020-01-24 22:24:53.0895 Debug __cfduid=<removed>; expires=Mon, 24-Feb-20 04:24:52 GMT; path=/; domain=.bakabt.me; HttpOnly; SameSite=Lax 
2020-01-24 22:24:53.0895 Debug WebClient(HttpWebClient2NetCore): Returning OK => <!doctype html><html><head><meta charset="utf-8"></meta><title>BakaBT - High quality anime bittorrent tracker</title><link rel="shortcut icon" href="/resources/img/favicon.png"></link><base href="/"></base><script type="text/javascript" src="resources/618f5839ef5227f52bf24b5e10ea02a7.js?cachebuster=1579359223"></script><link rel="stylesheet" type="text/css" href="resources/618f5839ef5227f52bf24b5e10ea02a7.css?cachebuster=1579359223"></link><script type="text/javascript" src="torrent_marks.php?id=<userid>?cachebuster=1579926292"></script><script type="text/javascript">var user = create_user({"id":<userid>,"class":1,"avatars":"yes"});</script></head><body><div class="dango"><div class="heart"></div></div><div class="main"><div class="banner" style="background-image:url(images/banners/dgdg.jpg);"><a href="" class="home"></a><a href="rss.php?uid=<userid>&amp;key=<removed>" class="icon rss" title="RSS Feed"></a></div><div class="headerbar"><ul><li><a href="">News</a></li><li><a href="browse.php">Browse</a><ul><li><a href="offer.php">Offers <strong>(65)</strong></a></li><li><a href="upload.php">Upload</a></li><li><a href="sandbox.php">Sandbox</a></li><li><a href="template.php">Templates</a></li><li><a href="adopt.php" title="Adoption center">Adopt</a></li></ul></li><li><a href="https://forums.bakabt.me">Forums</a></li><li><a href="https://bakashots.me">BakaSHOTS</a><ul><li><a href="http://compare.bakashots.me">BakaCOMPARE</a></li></ul></li><li><a href="http://wiki.bakabt.me">Wiki</a><ul><li><a href="http://wiki.bakabt.me/index.php/Rules">Rules</a></li><li><a href="http://wiki.bakabt.me/index.php/FAQ">FAQ</a></li></ul></li><li><a href="http://wiki.bakabt.me/index.php/IRC" title="#bakabt@irc.rizon.net">IRC</a><ul><li><a href="webirc.php">Web IRC</a></li></ul></li><li><a href="https://www.zazzle.com/bakabtshop/products">Store</a></li><li><a href="donate.php">Donate</a></li><li class="more"><a href="#" onclick="return false;">More&hellip;</a><ul><li><a href="http://blog.bakabt.me">Blog</a></li><li><a href="help.php">Help Form</a></li><li><a href="topten.php">Top 10</a></li><li><a href="banners.php">Banners</a></li><li class="random"><a href="random" title="Go to a random torrent">Random</a></li><li><a href="keywords.php">Keywords</a></li></ul></li><li><form method="get" action="browse.php"><input type="text" maxlength="128" name="q" /></form></li><li class="welcomeback">Welcome back, <a href="user/<userid>/<username>" class="username"><username></a>   <ul><li><a href="inbox.php">Messages (0)</a></li><li><a href="settings.php">Settings</a></li><li><a href="logout.php">Logout</a></li><li class="user-statistics"><span title="Ratio"><span class="ratio">R:</span> <span style="color: #00cc00">7.003</span></span><br /><span title="Uploaded"><span class="upload">U:</span> 478 GB</span><br /><span title="Downloaded"><span class="download">D:</span> 68.3 GB</span><br /><span title="Active torrents"><span class="active">A:</span> <span class="uarr">&uarr;</span> 20 <span class="darr">&darr;</span> 0</span><br /><span title="Bonus points"><span class="bonus">B:</span> 2 <a href="bonus.php">[Use]</a></span></li></ul></li></ul></div>
<div class="content">
>Adult content is only available if you enable it. You can enable adult content by checking 'Show adult content' in your <a href='../settings.php'>Settings</a></div>		<div class="clear"></div>
	</div>
</div>
</body>
</html>
 
2020-01-24 22:24:53.0895 Debug updating Cookies <cookie-info>
2020-01-24 22:24:53.0895 Debug Saving new config file: /config/Jackett/Indexers/bakabt.json.<removed>.tmp 
2020-01-24 22:24:53.0941 Info Found 0 releases from BakaBT 
2020-01-24 22:24:53.0941 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 4472.6067ms 
2020-01-24 22:24:53.0941 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2020-01-24 22:24:53.0941 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 226
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73 System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 226
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
2020-01-24 22:24:53.0989 Debug No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps. 
2020-01-24 22:24:53.0989 Info Request finished in 4478.9815ms 500 application/json 
2020-01-24 22:24:53.0989 Debug Connection id "0HLT19DP7MOEK" disconnecting. 
2020-01-24 22:24:53.0989 Debug Connection id "0HLT19DP7MOEK" stopped. 
2020-01-24 22:24:53.0989 Debug Connection id "0HLT19DP7MOEK" sending FIN because: "The Socket transport's send loop completed gracefully." 
```
 
### Notes
I logged into BakaBT directly and search doesn't seem to have any issues. This appears to have a different error than https://github.com/Jackett/Jackett/issues/5486

### Workaround
Unknown

**Comment by garfield69** [comment]
seen this one before. looks like #4566
where your access to the torrent search page is blocked because of message 
```
Adult content is only available if you enable it. You can enable adult content by checking 'Show adult content' in your Settings
````

in that case, the user needed to login to bakabt directly with his browser, access his user profile settings and find the **show-adult-content** option and enable it.
see if that applies to you too.
