### ISSUE TITLE
[gktorrent] Got redirected to another domain

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7021]
```
Manual search for "" on gktorrent with 0 results.
Jackett.Common.IndexerException: Exception (gktorrent): Got redirected to another domain. Try changing the indexer URL to https://www.gktorrent.io/. Updated site link, please try again.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://www.gktorrent.io/. Updated site link, please try again.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebClientStringResult Result, IHtmlDocument document) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 819
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1321
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 848
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1651
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 333
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 821
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/kizar/repositories/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 227


```

**Comment by garfield69** [comment]
gktorrent have changed their domain.
simply use your jackett dashboard to edit the gktorrent config, check that it now 
has a **site link**  set to `https://www.gktorrent.io/` and click OKAY.
