### ISSUE TITLE
[xspeeds] Exception (xspeeds): String was not recognized as a valid DateTime.: Parse error (Test)

### ISSUE THREAD

**Issue by ax-cgray** [Jackett/Jackett#7083]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.

If you are experiencing an issue with a tracker, then:
1. Use your browser to check you can access the site directly, and if a login is required, check you can login and that you do not have any outstanding account issues.
2. If you haven't already, try upgrading to the latest version of Jackett, your issue may have already been resolved.
3. If it is still not working for you, then a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

(At the bottom of your Jackett Dashboard page) **Jackett version**:  
(if you installed using Jackett.Binaries.Mono.tar.gz) **Mono version**:

-------------------------------

2020-02-03 16:54:57.3860 Error Error on 20200203165457 for XSpeeds.txtSystem.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider, DateTimeStyles style)
   at Jackett.Common.Indexers.XSpeeds.<PerformQuery>d__20.MoveNext()

**Comment by Bingmano** [comment]
I am also having this issue, looks to be something xspeeds changed on their end?  not really sure...
Jacket version: 0.12.1669.0
Mono version: 5.18.0.240-12

```
Jackett.Common.IndexerException: Exception (xspeeds): String was not recognized as a valid DateTime. ---> System.Exception: Parse error ---> System.FormatException: String was not recognized as a valid DateTime.
  at System.DateTimeParse.ParseExact (System.String s, System.String format, System.Globalization.DateTimeFormatInfo dtfi, System.Globalization.DateTimeStyles style) [0x0002a] in <30c1a991558c4064acefa7cee0fc6779>:0 
  at System.DateTime.ParseExact (System.String s, System.String format, System.IFormatProvider provider, System.Globalization.DateTimeStyles style) [0x00013] in <30c1a991558c4064acefa7cee0fc6779>:0 
  at Jackett.Common.Indexers.XSpeeds.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00361] in <d344de832ad84b299b910de1db0a5169>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseWebIndexer.OnParseError (System.String results, System.Exception ex) [0x00064] in <d344de832ad84b299b910de1db0a5169>:0 
  at Jackett.Common.Indexers.XSpeeds.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x0057c] in <d344de832ad84b299b910de1db0a5169>:0 
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00091] in <d344de832ad84b299b910de1db0a5169>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000ee] in <d344de832ad84b299b910de1db0a5169>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x0006b] in <d344de832ad84b299b910de1db0a5169>:0 
  at Jackett.Common.Services.IndexerManagerService.TestIndexer (System.String name) [0x000a3] in <d344de832ad84b299b910de1db0a5169>:0 
  at Jackett.Server.Controllers.IndexerApiController.Test () [0x000e1] in <8ae0c2b3b3c84080b978b4a2656ec1cd>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute (Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments) [0x00071] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync () [0x00131] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync () [0x0009e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00382] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter () [0x0009f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow (Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) [0x0001b] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next (Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+State& next, Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+Scope& scope, System.Object& state, System.Boolean& isCompleted) [0x00840] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync () [0x0002f] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync () [0x0012e] in <b4ef600f4a594fe2865a8f97f915fb9d>:0 
  at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x001cb] in <6092a16d93814eba828b517a2b132f80>:0 
  at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x00384] in <427697fe42b7459ba5302fb76d339d3b>:0 
  at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke (Microsoft.AspNetCore.Http.HttpContext context) [0x0043e] in <f352e566abf6421e87eafbcf57a0b237>:0 
  at Jackett.Server.Middleware.CustomExceptionHandler.Invoke (Microsoft.AspNetCore.Http.HttpContext httpContext) [0x0008a] in <8ae0c2b3b3c84080b978b4a2656ec1cd>:0
```
```
Error on 20200203202147 for XSpeeds.txtSystem.FormatException: String was not recognized as a valid DateTime.
  at System.DateTimeParse.ParseExact (System.String s, System.String format, System.Globalization.DateTimeFormatInfo dtfi, System.Globalization.DateTimeStyles style) [0x0002a] in <30c1a991558c4064acefa7cee0fc6779>:0 
  at System.DateTime.ParseExact (System.String s, System.String format, System.IFormatProvider provider, System.Globalization.DateTimeStyles style) [0x00013] in <30c1a991558c4064acefa7cee0fc6779>:0 
  at Jackett.Common.Indexers.XSpeeds.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x00361] in <d344de832ad84b299b910de1db0a5169>:0
```

**Comment by Bingmano** [comment]
appears this has been fixed on xpseeds side, i am no longer getting the error.

**Comment by garfield69** [comment]
works for me.
