### ISSUE TITLE
(ibit): Error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7111]
Search: bands
```
Manual search for "bands" on ibit with 1 results.
CardigannIndexer (ibit): Error while parsing row '
<tr>
	<td>
		<a href="/torrent/-Blues-Rock-The-Rex-Granite-Band-Electric-Combo-2019-MP3-320-kbps-GH3yPJv/" title="(Blues/Rock) The Rex Granite Band - Electric Combo - 2019, MP3, 320 kbps">(Blues/Rock) The Rex Granite Band - Electric Combo - 2019, MP3, 320 kbps</a>
	</td>
	<td class="icons">
		<i class="material-icons verified" title="verified torrent">done</i>
	</td>
	<td>
		<a href="/torrent-search/bands/Music/uploaded_at:desc/1/" title="Music">Music</a>
	</td>
	<td title="1 month ago">1 month ago</td>
	<td class="digits">-</td>
	<td class="digits" data-title="S">1</td>
	<td class="digits" data-title="L">0</td>
</tr>':

System.Exception: Error while parsing field=size, selector=td:nth-child(5), value=-: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1561

```

**Comment by ngosang** [comment]
@garfield69 I will reopen old issues when possible to not fold recent issues.
"query": "searches"
```
CardigannIndexer (ibit): Error while parsing row '
<tr>
	<td>
		<a href="/torrent/-FreeCoursesOnline-Me-O-REILLY-SEO-Local-SEO-2019-Get-More-Customers-From-Google-Search-sEEPIvl/" title="[FreeCoursesOnline.Me] O'REILLY - SEO + Local SEO 2019 - Get More Customers From Google Search">[FreeCoursesOnline.Me] O'REILLY - SEO + Local SEO 2019 - Get More Customers From Google Search</a>
	</td>
	<td class="icons">
		<i class="material-icons verified" title="verified torrent">done</i>
	</td>
	<td>
		<a href="/torrent-search/searches/Tutorials/uploaded_at:desc/1/" title="Tutorials">Tutorials</a>
	</td>
	<td title="1 month ago">1 month ago</td>
	<td class="digits">3.0 GB</td>
	<td class="digits" data-title="S">17</td>
	<td class="digits" data-title="L">24</td>
</tr>':

System.Exception: Error while parsing field=category, selector=a[href^="/torrent-search/"], value=Tutorials: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```
