### ISSUE TITLE
(audiobookbay): Error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7156]
Searches:
* rays
* shallow
```
Manual search for "rays" on audiobookbay with 33 results.
CardigannIndexer (audiobookbay): Error while parsing row '
<div class="post">
	<div class="postTitle">
		<h2>
			<a href="/audio-books/the-scattered-and-the-dead-series-the-first-four-books-split-into-individual-books-lt-vargus-tim-mcbain/" rel="bookmark">The Scattered and the Dead Series - The First Four Books (Split into Individual Books) - L.T. Vargus, Tim McBain</a>
		</h2>
	</div>
	<div class="postInfo">Category: (Post)apocalyptic&nbsp; Horror&nbsp; The Undead
		<br>Language: English<span style="margin-left:100px;">Keywords: Apocalypse&nbsp; Undead&nbsp; Zombie&nbsp; Zombies
		</span>
		<br>
	</div>
	<div class="postContent">
		<div class="center">
			<p class="center">Shared by:<a href="/member/users/index?&amp;mode=userinfo&amp;username=kazin79">kazin79</a>
			</p>
			<p class="center">
				<a href="http://audiobookbay.nl/audio-books/the-scattered-and-the-dead-series-the-first-four-books-split-into-individual-books-lt-vargus-tim-mcbain/">
					<img src="https://i.imgur.com/c5cp6kh.jpg" alt="The Scattered and the Dead Series - The First Four Books (Split into Individual Books) - L.T. Vargus, Tim McBain" width="200">
				</a>
			</p>
		</div>
		<p style="center;">
		</p>
		<p style="text-align:center;">Posted: 12 Dec 2019<br>Format:
			<span style="color:#a00;">M4B</span>
			/ Bitrate:
			<span style="color:#a00;">64 Kbps</span>
			<br>File Size:
			<span style="color:#00f;">1</span>
			GB</p>
	</div>
	<div class="postMeta">
		<span class="postLink">
			<a href="http://audiobookbay.nl/audio-books/the-scattered-and-the-dead-series-the-first-four-books-split-into-individual-books-lt-vargus-tim-mcbain/">Audiobook Details</a>
		</span>
		<span class="postComments">
			<a href="/dl-now?f=40The_Scattered_and_the_Dead_series_by_L.T._Vargus__Tim_McBain" rel="nofollow">Download Files Now</a>
		</span>
		<p></p>
	</div>
</div>':

System.Exception: Error while parsing field=size, selector=div.postContent p:contains("File Size:"), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1569

```

**Comment by ngosang** [comment]
"query": "tv"
```
CardigannIndexer (audiobookbay): Error while parsing row '
<div class="post">
	<div class="postTitle">
		<h2>
			<a href="/audio-books/the-cold-swedish-winter-the-complete-series-1-2-3-and-4-bbc-radio-4-comedy-danny-robins-4/" rel="bookmark">The Cold Swedish Winter: The Complete Series 1, 2, 3 and 4 - BBC Radio 4 Comedy - Danny Robins</a>
		</h2>
	</div>
	<div class="postInfo">Category: Adults&nbsp; Humor
		<br>Language: English<span style="margin-left:100px;">Keywords: BBC&nbsp; Cold&nbsp; Comedy&nbsp; Danny&nbsp; Humor&nbsp; Humour&nbsp; radio 4&nbsp; Robins&nbsp; Sweden&nbsp; Swedish&nbsp; Winter
		</span>
		<br>
	</div>
	<div class="postContent">
		<div class="center">
			<p class="center">Shared by:<a href="/member/users/index?&amp;mode=userinfo&amp;username=coony">coony</a>
			</p>
			<p class="center">
				<a href="http://audiobookbay.nl/audio-books/the-cold-swedish-winter-the-complete-series-1-2-3-and-4-bbc-radio-4-comedy-danny-robins-4/">
					<img src="https://ichef.bbci.co.uk/images/ic/768x432/p05cqjc9.jpg" alt="The Complete Series 1, 2, 3 and 4 - BBC Radio 4 Comedy - Danny Robins" width="200">
				</a>
			</p>
		</div>
		<p style="center;">
		</p>
		<p style="text-align:center;">2 Apr 2020</p>
	</div>
	<div class="postMeta">
		<span class="postLink">
			<a href="http://audiobookbay.nl/audio-books/the-cold-swedish-winter-the-complete-series-1-2-3-and-4-bbc-radio-4-comedy-danny-robins-4/">Audiobook Details</a>
		</span>
		<span class="postComments">
			<a href="/dl-now?f=47TCSW" rel="nofollow">Download Files Now</a>
		</span>
		<p></p>
	</div>
</div>':

System.Exception: Error while parsing field=date, selector=div.postContent p:contains("Posted:"), value=<null>: Selector "div.postContent p:contains("Posted:")" didn't match 
<div class="post">
	<div class="postTitle">
		<h2>
			<a href="/audio-books/the-cold-swedish-winter-the-complete-series-1-2-3-and-4-bbc-radio-4-comedy-danny-robins-4/" rel="bookmark">The Cold Swedish Winter: The Complete Series 1, 2, 3 and 4 - BBC Radio 4 Comedy - Danny Robins</a>
		</h2>
	</div>
	<div class="postInfo">Category: Adults&nbsp; Humor
		<br>Language: English<span style="margin-left:100px;">Keywords: BBC&nbsp; Cold&nbsp; Comedy&nbsp; Danny&nbsp; Humor&nbsp; Humour&nbsp; radio 4&nbsp; Robins&nbsp; Sweden&nbsp; Swedish&nbsp; Winter
		</span>
		<br>
	</div>
	<div class="postContent">
		<div class="center">
			<p class="center">Shared by:<a href="/member/users/index?&amp;mode=userinfo&amp;username=coony">coony</a>
			</p>
			<p class="center">
				<a href="http://audiobookbay.nl/audio-books/the-cold-swedish-winter-the-complete-series-1-2-3-and-4-bbc-radio-4-comedy-danny-robins-4/">
					<img src="https://ichef.bbci.co.uk/images/ic/768x432/p05cqjc9.jpg" alt="The Complete Series 1, 2, 3 and 4 - BBC Radio 4 Comedy - Danny Robins" width="200">
				</a>
			</p>
		</div>
		<p style="center;">
		</p>
		<p style="text-align:center;">2 Apr 2020</p>
	</div>
	<div class="postMeta">
		<span class="postLink">
			<a href="http://audiobookbay.nl/audio-books/the-cold-swedish-winter-the-complete-series-1-2-3-and-4-bbc-radio-4-comedy-danny-robins-4/">Audiobook Details</a>
		</span>
		<span class="postComments">
			<a href="/dl-now?f=47TCSW" rel="nofollow">Download Files Now</a>
		</span>
		<p></p>
	</div>
</div>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```
