### ISSUE TITLE
Bit-Titan search results don't use search term (again)

### ISSUE THREAD

**Issue by Lubastos** [Jackett/Jackett#7186]
Like in issue #6932 the search does not work anymore. Can you take the time to adjust it again?

**Comment by garfield69** [comment]
um,
![image](https://user-images.githubusercontent.com/6933240/74267352-c712ed80-4d6a-11ea-9159-c0c99ea530a8.png)

seems to work for me.
can you provide an example of a failure?

**Comment by Lubastos** [comment]
Jackett Version 0.12.1795.0 

Error on 20200212065853 for BiT-TiTAN.txtJackett.Common.ExceptionWithConfigData: Error: Du hast vergessen, die beiden Zahlen zu addieren!
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebClientStringResult loginResult, IList`1 errorBlocks) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 445
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 700
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1334

Jackett.Common.IndexerException: Exception (bit-titan): Error: Du hast vergessen, die beiden Zahlen zu addieren!
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Error: Du hast vergessen, die beiden Zahlen zu addieren!
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebClientStringResult loginResult, IList`1 errorBlocks) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 445
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 700
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1334
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 849
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1660
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 826
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 223
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

![Screenshot_2020-02-12-07-03-51-194_org mozilla firefox](https://user-images.githubusercontent.com/52412122/74307564-f6732b80-4d65-11ea-9c24-081bf907b090.jpg)
![Screenshot_2020-02-12-07-03-47-871_org mozilla firefox](https://user-images.githubusercontent.com/52412122/74307579-fffc9380-4d65-11ea-930b-acbf839b6014.jpg)
![Screenshot_2020-02-12-07-02-51-404_org mozilla firefox](https://user-images.githubusercontent.com/52412122/74307600-0be85580-4d66-11ea-9118-4b507a5a99cd.jpg)

First try was from the test button. Screenshots arethe result of a search.

**Comment by Lubastos** [comment]
Nevermind, solved the captcha in my settings again. Now it works.
sorry, issue can be closed
