### ISSUE TITLE
(extratorrent-cd) The operation was cancelled

### ISSUE THREAD

**Issue by cybersteel8** [Jackett/Jackett#7210]
Trying to perform any request to Jackett for extratorrent-cd hangs for a while then fails due to the following exception.
All my other indexers work fine. I just updated to the latest version 0.12.1811.0 and added this indexer.
```
Jackett.Common.IndexerException: Exception (extratorrent-cd): The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at CloudflareSolverRe.CloudflareSolver.SolveWithJavascript(Int32 tries)
   at CloudflareSolverRe.CloudflareSolver.Solve()
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, CloudflareHandler cloudflareHandler, Uri siteUrl, CancellationToken cancellationToken)
   at CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at CloudflareSolverRe.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, HttpClientHandler httpClientHandler, Uri siteUrl, CancellationToken cancellationToken, Boolean randomUserAgent)
   at CloudflareSolverRe.ClearanceHandler.GetClearance(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 240
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 167
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 455
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1316
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 355
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 826
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 433
```

**Comment by garfield69** [comment]
I have been seeing this too. I believe the ET server has been under pressure lately, and @ngosang  and I have seen some strange results coming out of this site, with empty searches and timeouts, even when using the browser.
Not sure that is has anything to do with Jackett.

**Comment by garfield69** [comment]
@ngosang  is the extratorrent indexer working for you?

**Comment by ngosang** [comment]
The website https://extratorrent.si is working a bit slow but fine.
In Jackett I see the same error as the OP, Operation cancelled. I think this could be caused by CloudflareResolver, but we have the latest version => https://www.nuget.org/packages/CloudflareSolverRe/

**Comment by Mirabeau2Code** [comment]
more and more trackers are starting to ban Jackett users
The users exaggerate in the number of requests they make on their Site by Jackett, it is no longer flood but almost a DDos simulation

Jackett should manage the exaggeration, otherwise he will become unusable :(

**Comment by ngosang** [comment]
> more and more trackers are starting to ban Jackett users
The users exaggerate in the number of requests they make on they Site with Jackett, it is no longer flood but almost a DDos simulation

No tracker is banning Jackett users. We are respectful with the websites, in most cases we only make 1 request per site (for each search). I'm testing more than 300 trackers everyday and all of them are working.

This issue is caused by a new challenge in Cloudflare. It's already reported => https://github.com/RyuzakiH/CloudflareSolverRe/issues/14

**Comment by Mirabeau2Code** [comment]
I am not saying that it is Jackett, as such the problem, but the use that some users make of it.
I am in contact with Admin, because they notice overloads.

Obviously some users do hundreds of searches every 10 minutes H24
So I can understand that it poses certain concerns for the tracker if several users do the same thing.
So they block.

Results for reasonable users, impossible to use Jackett.

From where my remark, to know if jackett could not prevent a too great frequency (or I do not know what), on the same time for the same tracker.

Currently Jackett sometimes seems to be diverted from his normal use, to the detriment of everyone.

It's a simple observation

**Comment by cadatoiva** [comment]
#7397 to track the CloudFlare issue

The admins of private trackers get to see which user is spamming. The *arr's already put a warning when you try to search for a large number of searches saying it may cause admins to ban. If an admin asks, we have rate limiting in several of our searchers that we can implement for them as well. Between caching and careful implementation, we do everything we can to reduce the number of searches needed. Searching for an episode/season in some trackers caches a single search for the whole series and returns the relevant episode torrents for each episode/season search, as example.

There is no blocking Jackett wholesale, as we implement custom UserAgent features and captcha solving.
