### ISSUE TITLE
Use HTTPs protocol when possible

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7221]
These sites support HTTPs protocol and we should use it. In most cases changing the sitelink is enough but we have to check the parsing rules to be sure we don't break anything.

 - [x] http://www.bigtorrent.eu/
 - [x] http://bitspyder.net/
 - [x] http://broadcity.in/
 - [x] http://bt.etree.org/
 - [x] http://cinemageddon.net/
 - [x] http://firebit.net/
 - [x] http://www.greek-team.cc/
 - [x] http://hdtorrents.xyz/
 - [x] http://hqsource.org/
 - [x] http://www.inperil.net/
 - [x] http://lesaloonv2-0.net/
 - [x] http://magnet4you.me/
 - [x] http://nnmclub.to/
 - [x] http://pirateiro.com/
 - [ ] http://sdbits.org/
 - [x] http://sktorrent.eu/
 - [x] http://tapochek.net/
 - [x] http://theoccult.click/
 - [x] http://theshow.click/
 - [x] http://thevault.click/
 - [x] http://topnow.se/
 - [x] http://torrent4you.me/
 - [x] http://torrent.unionfansub.com/

**Comment by garfield69** [comment]
I've adjusted the public ones, and any private ones I have access to, since I can test these.
But for some of the other private ones that I don't have access, I cannot confirm that switching to https will work.
for instance, tapochek was forcing https back to http back in July 2019, so using https would cause a redirect and fail the jackett login. But I see now that they are back to https, but since their CA is valid only from Jan 2020 to Mar 2020, they will probably force http again when their cert expires.

**Comment by garfield69** [comment]
Ladies and Gentlemen, your assistance please.
We are looking to switch some indexer that are using http to https.
but I don't have access to all the indexer involved to test if they will work.
So for the indexer against your name, if you still have access to it, can you see if changing your Jackett config Site Link to https is accepted for login, and that search still works?
Thank you.
@RoloSoze  bigtorrent , inperil
@josha33  bitspyder
@surfcu  broadcity
@MikeMilligan  cinemageddon
@vlevas  greekteam
@rafuz  hdtorrentsit
@koper89  hqsource
@bidulle95  lesallon
@poplolnman  sdbits
@adamwinn  theoccult , theshow , thevault

**Comment by adamwinn** [comment]
I dont have access to mine anymore

**Comment by vlevas** [comment]
hello @garfield69 as i see it works on greek-team
http://prntscr.com/r3dryw
http://prntscr.com/r3drlq
if u need anything further tell me.. 

thanks a lot!!

**Comment by rafuz** [comment]
hdtorrentsit is ok in HTTPS

![image](https://user-images.githubusercontent.com/22271829/74636541-8222f880-5168-11ea-855d-1a38a998faf2.png)

**Comment by MikeMilligan** [comment]
Sorry for the late answer. It works for Cinemageddon:

![Tracker configuration](https://i.imgur.com/VuKh13K.png)

![Tracker search](https://i.imgur.com/o4RTEHL.png)

**Comment by ngosang** [comment]
@RoloSoze can you test any?

**Comment by RoloSoze** [comment]
> 
> 
> Ladies and Gentlemen, your assistance please.
> We are looking to switch some indexer that are using http to https.
> but I don't have access to all the indexer involved to test if they will work.
> So for the indexer against your name, if you still have access to it, can you see if changing your Jackett config Site Link to https is accepted for login, and that search still works?
> Thank you.
> @RoloSoze bigtorrent , inperil
> @josha33 bitspyder
> @surfcu broadcity
> @MikeMilligan cinemageddon
> @vlevas greekteam
> @rafuz hdtorrentsit
> @koper89 hqsource
> @bidulle95 lesaloon
> @poplolnman sdbits
> @adamwinn theoccult , theshow , thevault

Sorry I missed this mention! 

> 
> 
> @RoloSoze can you test any?

I can only test 3 of them. I'll do it later today once I get the chance.

**Comment by RoloSoze** [comment]
@ngosang @garfield69 I was able to test BIGTorrent, HQSource, and inPeril. I can confirm that replacing HTTP with HTTPs in the Site Link in all 3 trackers works well and does not break anything.

**Comment by garfield69** [comment]
for the remainder of these sites (the yaml indexer ones), and any other yaml ones I find (that have no one to test), I propose that if the site does not reject https when I check with my browser, then I will switch the indexer sitelink from http to https.
In the event anyone reports a problem  I can revert, and then at the very least, we will get a potential tester for future updates ;-)

**Comment by ngosang** [comment]
I agree

**Comment by cadatoiva** [comment]
I feel this is the best course of action for any trackers on the no maintainer list on the Google sheet going forward.

**Comment by Jorman** [comment]
Not working for bigtower:
```
Jackett.Common.IndexerException: Exception (bigtower): Got redirected to another domain. Try changing the indexer URL to http://bigtower.info/.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to http://bigtower.info/.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebClientStringResult Result, IHtmlDocument document) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 831
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1335
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1665
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 803
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```
There's a way to force a kind of fallback function?
1st try https if now working http, if not working there's an error for sure

**Comment by Jorman** [comment]
Btw @RoloSoze said BIGTorrent, but Bigtower was edited

**Comment by garfield69** [comment]
Hah, my bad!. Tower, Torrent, whats the diff :-D
I'll revert BigTower and switch BitTorrent.

**Comment by garfield69** [comment]
Ah no, I did not make a mistake.
 5484d05 does switch BitTorrent , its just the commit title for this is wrong. so no problem there really.

but later we did decide to switch any of the rest (https://github.com/Jackett/Jackett/issues/7221#issuecomment-596254036) with ab6ca013, fully prepared to revert as required. 
BitTower will be reverted.

**Comment by Jorman** [comment]
Lol, thanks for revert.

**Comment by pipopop** [comment]
Hello,
I tested LeSaloon. But it seems that it doesn't work right now.
I tried to use http instead of https, but it doesn't work.

**Comment by garfield69** [comment]
@pipopop  thanks for the feedback. I'll revert the change that auto switches http to https

**Comment by pipopop** [comment]
Works great ! good job !
Thanks for all !

**Comment by pipopop** [comment]
For Lesaoon :
I don't know if it's because of this issue or not, but the connection test isn't working anymore. And when I connect to the site, it's in https.

**Comment by garfield69** [comment]
LeSaloon have changed their login page.
It used to be at http://lesaloonv2-0.net/index.php?page=login
But now http://lesaloonv2-0.net/ redirects to https://lesaloonv2-0.net/yupy_login.php
So, not only are they back to forcing https (the reverse of what they were doing 11th march), but the login path is different.
I'll update the indexer login block.

**Comment by garfield69** [comment]
LeSaloon Jackett 0.16.71

**Comment by pipopop** [comment]
I tested it but it doesn't work.
But on the site they indicate a maintenance that may cause disruptions from today. So we may have to wait a while. I'll post a message as soon as the ongoing maintenance is completed.
Thank you!

**Comment by pipopop** [comment]
It works great right now. Thanks for all @garfield69 !
