### ISSUE TITLE
jackett couldn't start service after updated

### ISSUE THREAD

**Issue by farjar** [Jackett/Jackett#7241]
2020-02-18 08:13:52.5249 Info Copied web.config 
2020-02-18 08:13:52.5559 Info Attempting to copy WindowsBase.dll from source: J:\Temp\JackettUpdate-v0.13.127-637176103397403524\Jackett\WindowsBase.dll to destination: C:\ProgramData\Jackett\WindowsBase.dll 
2020-02-18 08:13:52.6139 Info Copied WindowsBase.dll 
2020-02-18 08:13:52.6495 Info Attempting to copy WindowsFormsIntegration.dll from source: J:\Temp\JackettUpdate-v0.13.127-637176103397403524\Jackett\WindowsFormsIntegration.dll to destination: C:\ProgramData\Jackett\WindowsFormsIntegration.dll 
2020-02-18 08:13:52.6954 Info Copied WindowsFormsIntegration.dll 
2020-02-18 08:13:52.7384 Info Attempting to copy wpfgfx_cor3.dll from source: J:\Temp\JackettUpdate-v0.13.127-637176103397403524\Jackett\wpfgfx_cor3.dll to destination: C:\ProgramData\Jackett\wpfgfx_cor3.dll 
2020-02-18 08:13:52.7744 Info Copied wpfgfx_cor3.dll 
2020-02-18 08:13:52.8160 Info Attempting to copy YamlDotNet.dll from source: J:\Temp\JackettUpdate-v0.13.127-637176103397403524\Jackett\YamlDotNet.dll to destination: C:\ProgramData\Jackett\YamlDotNet.dll 
2020-02-18 08:13:52.8730 Info Copied YamlDotNet.dll 
2020-02-18 08:13:52.9030 Info File copying complete 
2020-02-18 08:13:53.0340 Info Starting Windows service 
2020-02-18 08:13:58.2596 Error Exception applying update! System.InvalidOperationException: Cannot start service 'Jackett' on computer '.'.
 ---> System.ComponentModel.Win32Exception (1053): 服务没有及时响应启动或控制请求。
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at Jackett.Common.Services.WindowsServiceConfigService.Start() in d:\a\1\s\src\Jackett.Common\Services\WindowsServiceConfigService.cs:line 42
   at Jackett.Updater.Program.ProcessUpdate(UpdaterConsoleOptions options) in d:\a\1\s\src\Jackett.Updater\Program.cs:line 439
   at Jackett.Updater.Program.<Run>b__5_1(UpdaterConsoleOptions options) in d:\a\1\s\src\Jackett.Updater\Program.cs:line 64
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Jackett.Updater.Program.Run(String[] args) in d:\a\1\s\src\Jackett.Updater\Program.cs:line 62

**Comment by farjar** [comment]
fixed!
re-copy all update files and restart, then done. maybe something wrong while auto-updating process.
