### ISSUE TITLE
(bittorrentam): The response ended prematurely

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7285]
The website is working fine in the browser but I'm getting exceptions in Jackett. Futhermeore, I'm getting different exceptions in .NetCore and in Mono.

.NetCore
```
02-21 22:50:47 Info Starting Jackett v0.13.144.0 
02-21 22:50:48 Info Environment version: 3.1.2 (/home/kizar/Downloads/Jackett/) 
02-21 22:50:48 Info OS version: Unix 5.4.13.1 (64bit OS) (64bit process) 
02-21 22:50:48 Info Jackett variant: CoreLinuxAmdx64 
02-21 22:50:48 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
02-21 22:50:48 Info App config/log directory: /home/kizar/.config/Jackett 
02-21 22:50:48 Info issue: Arch Linux \r (\l) 
02-21 22:50:48 Info Using HTTP Client: HttpWebClient2NetCore 


Manual search for "" on bittorrentam with 0 results.
Jackett.Common.IndexerException: Exception (bittorrentam): The response ended prematurely.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 240
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 117
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 451
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1333
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 333
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 822
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 227
```

Mono
```
02-21 21:59:20 Info Starting Jackett v0.13.160.0 
02-21 21:59:21 Info Environment version: 4.0.30319.42000 (/usr/lib/mono/4.5) 
02-21 21:59:21 Info OS version: Unix 5.4.13.1 (64bit OS) (64bit process) 
02-21 21:59:21 Info Jackett variant: Mono 
02-21 21:59:21 Info ThreadPool MaxThreads: 400 workerThreads, 200 completionPortThreads 
02-21 21:59:21 Info App config/log directory: /home/xxx/.config/Jackett 
02-21 21:59:21 Info issue: Arch Linux \r (\l) 
02-21 21:59:21 Info mono version: 6.4.0 (makepkg/fe64a4765e6 Sat 16 Nov 2019 04:59:42 PM UTC) 
02-21 21:59:21 Info Using HTTP Client: HttpWebClient


JACK_ERROR 'bittorrentam' ''
Manual search for "" on bittorrentam with 0 results.
Jackett.Common.IndexerException: Exception (bittorrentam): The server returned an invalid or unrecognized response. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
  at System.Net.Http.HttpConnection.FillAsync () [0x0016e] in <dfcbfc91f2224480a512506bc7a7dd22>:0 
  at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync (System.Boolean foldedHeadersAllowed) [0x002a0] in <dfcbfc91f2224480a512506bc7a7dd22>:0 
  at System.Net.Http.HttpConnection.SendAsyncCore (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00d9f] in <dfcbfc91f2224480a512506bc7a7dd22>:0 
   --- End of inner exception stack trace ---
  at System.Net.Http.HttpConnection.SendAsyncCore (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x012e5] in <dfcbfc91f2224480a512506bc7a7dd22>:0 
  at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync (System.Net.Http.HttpConnection connection, System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x0012b] in <dfcbfc91f2224480a512506bc7a7dd22>:0 
  at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x0014b] in <dfcbfc91f2224480a512506bc7a7dd22>:0 
  at System.Net.Http.DecompressionHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ca] in <dfcbfc91f2224480a512506bc7a7dd22>:0 
  at CloudflareSolverRe.ClearanceHandler.SendRequestAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00090] in <9640d5c3ce934e55be2d347202d4fc66>:0 
  at CloudflareSolverRe.ClearanceHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000a4] in <9640d5c3ce934e55be2d347202d4fc66>:0 
  at System.Net.Http.HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x0017e] in <dfcbfc91f2224480a512506bc7a7dd22>:0 
  at Jackett.Common.Utils.Clients.HttpWebClient.Run (Jackett.Common.Utils.Clients.WebRequest webRequest) [0x00497] in <de7ea32dc9e5426da7e33652c177e0fa>:0 
  at Jackett.Common.Utils.Clients.WebClient.GetString (Jackett.Common.Utils.Clients.WebRequest request) [0x0010b] in <de7ea32dc9e5426da7e33652c177e0fa>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies (System.String url, System.String cookieOverride, System.String referer, System.Collections.Generic.Dictionary`2[TKey,TValue] headers) [0x000cb] in <de7ea32dc9e5426da7e33652c177e0fa>:0 
  at Jackett.Common.Indexers.CardigannIndexer.PerformQuery (Jackett.Common.Models.TorznabQuery query) [0x0086a] in <de7ea32dc9e5426da7e33652c177e0fa>:0 
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x00091] in <de7ea32dc9e5426da7e33652c177e0fa>:0 
   --- End of inner exception stack trace ---
  at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x000ee] in <de7ea32dc9e5426da7e33652c177e0fa>:0 
  at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery (Jackett.Common.Models.TorznabQuery query) [0x0006b] in <de7ea32dc9e5426da7e33652c177e0fa>:0 
  at Jackett.Server.Controllers.ResultsController.Results (Jackett.Common.Models.DTO.ApiSearch requestt) [0x00287] in <7aba1958e4c345398336df0e5c8a4a13>:0 
```

**Comment by garfield69** [comment]
the difference in mono and core is just in the reporting. the base cause is the same.
![image](https://user-images.githubusercontent.com/6933240/75076641-9ea6a280-5565-11ea-9d0f-202a232b4d17.png)

**Comment by garfield69** [comment]
and now its back
![image](https://user-images.githubusercontent.com/6933240/75076702-c269e880-5565-11ea-958c-ebedc412d179.png)
so this is some kind of server issue at their end?

**Comment by ngosang** [comment]
The website is working is my browser. Sometimes the website load is slow but it's working. According to https://www.uptrends.com/tools/uptime it's working from most locations.
Nevertheless, in Jackett I get the exception 100% of the time.

**Comment by garfield69** [comment]
the jackett indexer works for me intermittently
![image](https://user-images.githubusercontent.com/6933240/75077984-3d80ce00-5569-11ea-90a1-981d0e14df3c.png)

**Comment by ngosang** [comment]
It's down again

**Comment by garfield69** [comment]
back online. indexer search working.
