### ISSUE TITLE
[icetorrent] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by fvlaicu** [Jackett/Jackett#7321]
Icetorrent got updated today or yesterday.

### Logged Error Messages
```
Feb 24 20:31:20 indexer jackett[25608]: 02-24 20:31:20 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
Feb 24 20:31:20 indexer jackett[25608]:    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 806
Feb 24 20:31:20 indexer jackett[25608]:    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 975
Feb 24 20:31:20 indexer jackett[25608]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 24 20:31:20 indexer jackett[25608]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
Feb 24 20:31:20 indexer jackett[25608]:    at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 806
Feb 24 20:31:20 indexer jackett[25608]:    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 975
Feb 24 20:31:20 indexer jackett[25608]:    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Feb 24 20:31:20 indexer jackett[25608]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 24 20:31:20 indexer jackett[25608]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
seeing this too.
```html
Error on 20200225190801 for ICE Torrent.txtJackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 803
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1354




<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='/login'" />

        <title>Redirecting to /login</title>
    <script src="/cdn-cgi/apps/head/7z11rGMSMXwKpGHlUm1wYf0YXZc.js"></script></head>
    <body>
        Redirecting to <a href="/login">/login</a>.
    </body>
</html>
```

**Comment by garfield69** [comment]
Jackett 0.13.201
