### ISSUE TITLE
[xwtorrents] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by DJMValentino** [Jackett/Jackett#7339]
### Environment

**OS**: Ubuntu 18.04

**Jackett Version**: v0.13.211

**Are you using a proxy or VPN?** [yes/no] no

### Description

Recreated the index and error continues to pop up for XWTorrents

### Logged Error Messages

2020-02-26 18:30:02.1929 Info Starting Jackett v0.13.211.0 
2020-02-26 18:30:03.0376 Info Environment version: 3.1.2 (/app/Jackett/) 
2020-02-26 18:30:03.0376 Info OS version: Unix 4.15.0.76 (64bit OS) (64bit process) 
2020-02-26 18:30:03.0376 Info Jackett variant: CoreLinuxAmdx64 
2020-02-26 18:30:03.0376 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
2020-02-26 18:30:03.0376 Info App config/log directory: /config/Jackett 
2020-02-26 18:30:03.0376 Info issue: Ubuntu 18.04.4 LTS \n \l 
2020-02-26 18:30:03.0376 Info Using Proxy: No 
2020-02-26 18:30:03.0430 Info Using HTTP Client: HttpWebClient2NetCore 
2020-02-26 18:30:03.2269 Info Loading Cardigann definitions from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions 
2020-02-26 18:30:05.3341 Info Adding aggregate indexer 
2020-02-26 18:30:05.6345 Info Jackett startup finished in 4.531 s 
2020-02-26 18:30:39.9582 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 800
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 800
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

### Screenshots

![image](https://user-images.githubusercontent.com/61509119/75375146-8606f700-589b-11ea-9a7f-465e2300f760.png)

**Comment by garfield69** [comment]
check with the web site directly with your browser. set your account profile and turn off the two email notifications checkboxes and save.
Also check your account for a good ratio, and that you do not have an outstanding alerts, notices or unread emails.
then logout.
and try Jackett again.

**Comment by DJMValentino** [comment]
I checked my account and the email notifications checkboxes were already turned off. I have a good ratio and no outstanding alerts, notices or unread emails. I'm still getting the same error in Jackett

**Comment by garfield69** [comment]
works for me.
lets see if the enhanced log yields any more info on the issue.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by DJMValentino** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4258026/log.txt)

**Comment by garfield69** [comment]
Hmm. in response to the indexer sending `https://xtremewrestlingtorrents.net/tlogin.php` the web site responded with `Returning NotFound`

so instead of just using the TEST button on my jackett dashboard I edited the config and clicked OKAY to try a full login (rather than reuse any cookies saved from previous logins).
And I also now get this error.
So I shall check the indexer login code and see what the web site has changed and post a fix later today when I next get some free time.

**Comment by DJMValentino** [comment]
Thanks, much appreciated

**Comment by garfield69** [comment]
Jackett 0.13.222

**Comment by Pacers31Colts18** [comment]
Having the same issue myself.

**Comment by garfield69** [comment]
works for me with Jackett 0.13.222
if you are on this version and you still have problems, then first read and apply https://github.com/Jackett/Jackett/issues/7339#issuecomment-591612669
and if it does not help try removing the indexer and adding it afresh. Refill the username/password ever if they appear pre-filled.
and if it is still not working then provide a full enhanced log so we can check your individual case in more details.
a `its-not-working` or `i-have-the-same-issue` is not going to get it solved for you. ;-b
