### ISSUE TITLE
(audiobooktorrents) Login Failed, got redirected.

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7422]
I can log in in the website but not in Jackett. I removed the tracker and tried to add it again with no success.
```
Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 797
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 967
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by garfield69** [comment]
the indexer works for me.
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by ngosang** [comment]
I found the problem. Someone sent me a PM and when I logged in, I was redirected to the PMs page `https://abtorrents.me/pm_system.php?action=view_mailbox `
After deleting the PMs Jackett works again.

Is it possible to handle this situation?

[log.txt](https://github.com/Jackett/Jackett/files/4272519/log.txt)

**Comment by garfield69** [comment]
>Is it possible to handle this situation?

With the way cardigann is currently set up, no, I do not think so. 
the redirect is trapped in the audiobooktorrents indexer by the login block *test* section, which expected the path to be `https://abtorrents.me/browse.php` and was returned `https://abtorrents.me/pm_system.php?action=view_mailbox`  
https://github.com/Jackett/Jackett/blob/b9a6c7c810aee2864df8ec9a124cb0e0c2756e11/src/Jackett.Common/Definitions/audiobooktorrents.yml#L59-L60
hence the redirect is flagged as a  failure.

It might be possible to trap something in the login block error section
https://github.com/Jackett/Jackett/blob/b9a6c7c810aee2864df8ec9a124cb0e0c2756e11/src/Jackett.Common/Definitions/audiobooktorrents.yml#L56-L58
assuming you could find some selector that only appears in the mail page, but my gut feeling is that the error section only gets used for the page on the login path, and not post login so this may not work.

you may need to extent the cardigann login test section to support its own error subsection, then it would be possible to trap the mail redirect and flag it as a login failure.

**Comment by garfield69** [comment]
or you could just improve the `login failed, got redirected` message to include the offending redirect path, so its more obvious what the login unexpected path was, without having to result to a enhanced log to see it.

**Comment by ngosang** [comment]
@garfield69 The site don't let you perform searches until you real all PMs. Could you add a message in the configuration?

> If you are getting the error "Login Failed, got redirected" open the site in your browser and mark as read all PMs.

This issue can be closed with that.
