### ISSUE TITLE
[hdtorrents] Exception (hdtorrents): String '01=

### ISSUE THREAD

**Issue by Rouzax** [Jackett/Jackett#7426]
HD-Torrents is broken

### Environment

**OS**: Windows Server 2019

**.Net Runtime**: 
```
>=4.x        : 4.7.2
v4\Client    : Installed
v4\Full      : Installed
v3.5         : Not installed (no key)
v3.0         : Not installed (no key)
v2.0.50727   : Not installed (no key)
v1.1.4322    : Not installed (no key)
```

**Jackett Version**: 0.13.378.0

### Logged Error Messages
```
Jackett.Common.IndexerException: Exception (hdtorrents): String '01="" mar="" 2020="" 12:00:43="" +0200=""' was not recognized as a valid DateTime.
 ---> System.Exception: Parse error
 ---> System.FormatException: String '01="" mar="" 2020="" 12:00:43="" +0200=""' was not recognized as a valid DateTime.
   at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\HDTorrents.cs:line 222
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 803
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 220
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 98
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
likely broken by #7373

**Comment by ngosang** [comment]
@Rouzax I need the html source code. Please, open https://hdts.ru/torrents.php in your browser, right click, view source code and upload the code here. Remove personal information.

**Comment by Rouzax** [comment]
@ngosang Here you go.

[view-source_https___hdts.ru_torrents.php.txt](https://github.com/Jackett/Jackett/files/4274427/view-source_https___hdts.ru_torrents.php.txt)

**Comment by garfield69** [comment]
Jackett 0.13.427

**Comment by Rouzax** [comment]
It works again, Thank you.

**Comment by ngosang** [comment]
@Rouzax do you have any invitation?

**Comment by Rouzax** [comment]
> @Rouzax do you have any invitation?

See your email 😀

**Comment by mazafra1** [comment]
It's happening again. Version 0.13.467.0 on docker for raspberry.

**Comment by garfield69** [comment]
If you're still having issues after updating to 0.13.633, report the problem so we can get it fixed.

**Comment by ngosang** [comment]
@mazafra1 I don't have account bu I tested it with the HTML provided in https://github.com/Jackett/Jackett/issues/7426#issuecomment-593295923
Could you upload the HTML source code?

* Please, open ht-torrents in your browser and go to the list of torrents and perform the same search as in Jackett
* Right click, save page as HTML
* Remove personal information from the HTML file (without breaking the code)
* Drag/drop the html file here (use txt extension)

**Comment by garfield69** [comment]
@ngosang  Oh, I thought you were given in invite https://github.com/Jackett/Jackett/issues/7426#issuecomment-595182339
Did that not happen?

**Comment by ngosang** [comment]
He wanted something in exchange and I refused.

**Comment by mazafra1** [comment]
> @mazafra1 I don't have account bu I tested it with the HTML provided in [#7426 (comment)](https://github.com/Jackett/Jackett/issues/7426#issuecomment-593295923)
> Could you upload the HTML source code?
> 
>     * Please, open ht-torrents in your browser and go to the list of torrents and perform the same search as in Jackett
> 
>     * Right click, save page as HTML
> 
>     * Remove personal information from the HTML file (without breaking the code)
> 
>     * Drag/drop the html file here (use txt extension)

Here you are.
[HD-Torrents.org - Torrents.txt](https://github.com/Jackett/Jackett/files/4332456/HD-Torrents.org.-.Torrents.txt)

**Comment by Rouzax** [comment]
@mazafra1 & @ngosang Really weird on Jackett Version 0.13.633.0 it is working for me
![image](https://user-images.githubusercontent.com/4103090/76679198-b0b4b780-65de-11ea-974e-57c2571df070.png)

**Comment by Rouzax** [comment]
> He wanted something in exchange and I refused.

I asked to exchange another Private Tracker invite, HD-Torrent don't give free invites but I need to exchange my bonus points which I accumulated over the past 2 years. They are also pretty strict and I want to make sure that I don't get banned over there. Hope you understand my reasoning.
Really appreciate all the hard work you all do on this project and not trying to obnoxious, arrogant or whatever.

**Comment by ngosang** [comment]
@mazafra1 I tested again with your HTML => https://github.com/Jackett/Jackett/issues/7426#issuecomment-599031124
And it's working... please, make sure you have the latest version of Jackett and restart Jackett.

**Comment by mazafra1** [comment]
Yes. Latest version is working now. Thanks
