### ISSUE TITLE
[torrentheaven] Exception (torrentheaven): The string did not match the expected pattern.: Parse error (Test)

### ISSUE THREAD

**Issue by SkalCore** [Jackett/Jackett#7446]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker Container from https://hub.docker.com/r/linuxserver/jackett/

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Jackett Version 0.13.378.0 latest

**Last Working Jackett Version**: linuxserver/jackett:v0.13.280-ls55

**Are you using a proxy or VPN?** yes, Reverse proxy Traefik

### Description

Update Feeds, no Update Happen, change container from development to latest, then to 
v0.13.280-ls55

### Logged Error Messages

An error occurred while processing feed. http://192.168.178.24:9117/api/v2.0/indexers/torrentheaven/results/torznab/api?t=movie&cat=100101,100041,100008,2030,2040,2070&extended=1&apikey=(removed)&offset=0&limit=100: Torznab error detected: Jackett.Common.IndexerException: Exception (torrentheaven): The string did not match the expected pattern.
 ---> System.Exception: Parse error
 ---> AngleSharp.Dom.DomException: The string did not match the expected pattern.
   at AngleSharp.Dom.QueryExtensions.CreateSelector(INodeList nodes, INode scope, String selectorText)
   at AngleSharp.Dom.QueryExtensions.QuerySelector(INodeList nodes, String selectorText, INode scopeNode)
   at Jackett.Common.Indexers.TorrentHeaven.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentHeaven.cs:line 209
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.TorrentHeaven.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentHeaven.cs:line 262
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
likely broken by #7387

**Comment by garfield69** [comment]
fixed with 012f3d1bbcf4a0fff42fec596ddbcbf12d43f8de, assuming I spotted an the selector errors.
I'll post when the next release of jacket is published, due on about 21 hours from now, more or less.
