### ISSUE TITLE
How to change the port to 80 instead of the default 9117?

### ISSUE THREAD

**Issue by alexya** [Jackett/Jackett#7447]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: CentOS 7.7

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
.Net-Core

**.Net Version**:

**Jackett Version**:
0.13.144.0

**Last Working Jackett Version**:
0.13.144.0

**Are you using a proxy or VPN?** [yes/no]
no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
I installed the Jackett as a service on a CentOS 7.7. And it worked well. 

In the web UI, I changed the server port to 80, then refresh the UI page. The web UI failed to be opened. 

Log in to CLI of the CentOS 7.7, I checked the config.json, it was changed to 80. 
But I can't find any process of Jackett, such as "ps -ef | grep Jackett". 
In the log file, there is none information. 

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
for debug purposes, try from a terminal: 
1. cd to your jackett binaries folder 
2. start jackett on demand with some enhanced logging `./jackett -l -t` 
3. and check the terminal output for port 80 being listened to, or if there are error messages.

**Comment by alexya** [comment]
@garfield69 , I tried to run `./jackett -l -t`. the output is as following. 
The proc was killed soon, and I attached the error message in .config/Jackett/log.txt

It seems that there is no permission to bind to 80. I don't know why and how to fix it. 

CLI output
```
[alexya@south-0220-jackett Jackett]$ ./jackett -l -t
03-03 06:07:18 Info Starting Jackett v0.13.144.0 
03-03 06:07:18 Info Logging enabled. 
03-03 06:07:18 Info Tracing enabled. 
03-03 06:07:19 Debug Creating web host... 
03-03 06:07:19 Debug Content root path is: /home/alexya/Jackett/Content 
03-03 06:07:19 Debug Autofac container built 
03-03 06:07:20 Info Environment version: 3.1.2 (/home/alexya/Jackett/) 
03-03 06:07:20 Info OS version: Unix 3.10.0.1062 (64bit OS) (64bit process) 
03-03 06:07:20 Info Jackett variant: CoreLinuxAmdx64 
03-03 06:07:20 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
03-03 06:07:20 Info App config/log directory: /home/alexya/.config/Jackett 
03-03 06:07:20 Info issue: \S 
03-03 06:07:20 Info Using HTTP Client: HttpWebClient2NetCore 
03-03 06:07:20 Info Loading Cardigann definitions from: /home/alexya/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /home/alexya/Jackett/Definitions 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/documentarytorrents.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/crazyscorner.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/racingforme.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/muziekfabriek.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/totallykids.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/nntt.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/nitro.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/desireleasers.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/bluebird.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/tvchaosuk.yml 
03-03 06:07:20 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/DasUnerwartete.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/broadcity.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/firebit.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/ast4u.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/estrenosdtl.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/alein.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/hddolby.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/newstudio.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/film-paleis.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/bittorrentam.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/xbytes2.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/nordichd.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/pleasuredome.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/eniahd.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/torrentfactory.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/beitai.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/arabafenice.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/torrentproject2.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/hamsterstudio.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/mvgroupforum.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/twilight.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/idope.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/Bittorrentfiles.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/greeklegends.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/rptorrents.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/0daykiev.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/tapochek.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/kickasstorrent-kathow.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/ettv.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/btdigg.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/hdhome.yml 
03-03 06:07:21 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/concen.yml 
03-03 06:07:22 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/sporthd.yml 
03-03 06:07:22 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/onlineselfeducation.yml 
03-03 06:07:22 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/galeriens.yml 
03-03 06:07:22 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/thehorrorcharnel.yml 
03-03 06:07:22 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/theshow.yml 
03-03 06:07:22 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/gay-torrentsorg.yml 
03-03 06:07:22 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/btsow.yml 
03-03 06:07:22 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/bit-titan.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/bigtower.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/acgrip.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/hdturk.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/retroflix.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/audionews.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/rodvd.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/proaudiotorrents.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/microbit.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/monova.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/torrentslocal.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/newretro.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/efectodoppler.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/totheglory.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/extremlymtorrents.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/cartoonchaos.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/exttorrents.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/x-ite.me.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/legittorrents.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/pornleech.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/ccfbits.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/estone.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/scenexpress.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/finvip.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/tellytorrent.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/zooqle.yml 
03-03 06:07:23 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/rus-media.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/snowpt.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/shellife.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/hdroute.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/skytorrentsclone.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/marinetracker.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/cinemageddon.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/siambit.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/hdsky.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/tasmanit.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/turktorrent.yml 
03-03 06:07:24 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/world-of-tomorrow.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/anirena.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/spacetorrent.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/itorrent.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/moecat.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/amigosshare.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/7torrents.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/limetorrents.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/puntotorrent.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/theempire.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/blutopia.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/hush.yml 
03-03 06:07:25 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/shareisland.yml 
03-03 06:07:26 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/yourbittorrent.yml 
03-03 06:07:26 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/yggcookie.yml 
03-03 06:07:26 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/ethor.yml 
03-03 06:07:26 Info Loading Cardigann definition /home/alexya/Jackett/Definitions/bigfangroup.yml 
Killed
[alexya@south-0220-jackett Jackett]$ 
```

error messages in log.txt
```
2020-03-03 06:09:19.3092 Fatal Unable to start Kestrel. System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2020-03-03 06:09:19.3092 Fatal Unable to start Kestrel. System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2020-03-03 06:09:19.8617 Error System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Jackett.Server.Program.Main(String[] args) System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Jackett.Server.Program.Main(String[] args)
```

My ServerConfig.json
```
{
  "Port": 80,
  "AllowExternal": true,
  "APIKey": "<apikey>",
  "AdminPassword": "<admin password>",
  "InstanceId": "<instance id>",
  "BlackholeDir": "",
  "UpdateDisabled": false,
  "UpdatePrerelease": false,
  "BasePathOverride": "",
  "OmdbApiKey": "",
  "OmdbApiUrl": "",
  "ProxyUrl": "",
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
}
```

**Comment by cadatoiva** [comment]
In Linux, binding below port 1024 is reserved for root only. Are you running the Jackett service as root, or another user? It's not recommended to run Jackett as root, and would be better to run Apache or Nginx on port 80 as a reverse proxy instead. There are instructions for doing so in our wiki

**Comment by cadatoiva** [comment]
You can also follow the instructions on https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux if you really want to run on port 80 without running as root, but doing so introduces potential security risks as detailed in the link.

Closing this issue since this is not anything specific to Jackett, but an OS issue. Good luck with however you decide to go.
