### ISSUE TITLE
[SceneTime] Searching the tracker individually works fine; searching it alongside others does not

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#7475]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.13.378.0

**Last Working Jackett Version**: Not sure exactly, but it was working fine 3 or so days ago

**Are you using a proxy or VPN?**: No

### Description

When I manually search SceneTime on its own in Jackett, it works fines and returns accurate results. However, when I conduct a manual search of SceneTime along with a bunch of other trackers, I get an error (no specific error message is displayed).

_Update: It seems that this error does not always occur. In my case, it happened when I searched for 'The Curious Case of Benjamin Button 2008', 'The Dark Knight Rises 2012', 'The Assassination of Jesse James by the Coward Robert Ford 2007'. and 'Confessions of a Dangerous Mind 2002'. In other searches, I get no errors at all, even when there are 0 search results._

The log below was produced by searching for 'The Curious Case of Benjamin Button 2008'.

### Logged Error Messages
Here's the portion of the enhanced log that references this issue. 
```
2020-03-03 04:59:06.6810 Error Jackett.Common.IndexerException: Exception (scenetime): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.SceneTime.ParseResponse(TorznabQuery query, String htmlResponse) in d:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 206
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.SceneTime.ParseResponse(TorznabQuery query, String htmlResponse) in d:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 256
   at Jackett.Common.Indexers.SceneTime.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 194
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 807
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 224 Jackett.Common.IndexerException: Exception (scenetime): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.SceneTime.ParseResponse(TorznabQuery query, String htmlResponse) in d:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 206
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.SceneTime.ParseResponse(TorznabQuery query, String htmlResponse) in d:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 256
   at Jackett.Common.Indexers.SceneTime.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 194
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 807
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 224
```

### Screenshots
Not needed.

**Comment by ngosang** [comment]
I take this one.

**Comment by ngosang** [comment]
Caused by this #7394

**Comment by garfield69** [comment]
Jackett 0.13.446
