### ISSUE TITLE
[animetosho] Exception (animetosho): The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3. (Test)

### ISSUE THREAD

**Issue by joridiculous** [Jackett/Jackett#7497]
### Environment
Synology
**OS**:
DSM 6.x
**Jackett Version**:
Version 0.12.1494.0  Docker Linuxserver
**Are you using a proxy or VPN?** [yes/no]
No
### Description
he 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3. (Config) #7491

[List steps to reproduce the error and details on what happens and what you expected to happen]
using test and normal "automation" with Sonarr

### Logged Error Messages
Unable to connect to indexer: Torznab error detected: Jackett.Common.IndexerException: Exception (animetosho): The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.
 ---> System.Xml.XmlException: The 'hr' start tag on line 5 position 2 does not match the end tag of 'body'. Line 6, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowTagMismatch(NodeData startTag)
   at System.Xml.XmlTextReaderImpl.ParseEndElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at Jackett.Common.Indexers.Feeds.BaseNewznabIndexer.ParseFeedForResults(String feedContent) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Feeds/BaseNewznabIndexer.cs:line 22
   at Jackett.Common.Indexers.Feeds.BaseFeedIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/Feeds/BaseFeedIndexer.cs:line 48
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 823
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 427

**Comment by cadatoiva** [comment]
Fixed in Jackett 0.13.446 please update your Jackett installation
