### ISSUE TITLE
Shareisland - ReLogin

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#7499]
Hi, with all indexer I've, only with shareisland happen that once a week or maybe once in 15 days, I need to open the configuration panel and hit ok, in order to log-in again to the index

Do you know if there's a way to prevent this?

**Comment by Jorman** [comment]
Yep, I hope this log contain enough information for you.
[log.txt.20200304.00018.zip](https://github.com/Jackett/Jackett/files/4289439/log.txt.20200304.00018.zip)
As I said, this happens sporadically, at some point, I need to re log-in to the tracker, inside Jackett

**Comment by Jorman** [comment]
Ok, the same error now, so is passed less than 3 days, this's the log from log button
```
2020-03-07 14:00:34 | Error | Jackett.Common.IndexerException: Exception (shareisland): Login failed: No form found on https://shareisland.org/login using form selector form  ---> System.Exception: Parse error  ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://shareisland.org/login using form selector form    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 555    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1339    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1665    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 224
-- | -- | --
```
and
```
2020-03-06 15:01:40.8851 Info CardigannIndexer (shareisland): Relogin required 
2020-03-06 15:01:45.8969 Info Found 100 (7 new) releases from Shareisland 
```
Any idea?
Maybe with cookie?

**Comment by cadatoiva** [comment]
According to the logs, you are still logged in but Jackett isn't detecting it. When it goes to login, it's getting redirected to what appears to be a recent torrents page, and so it can't find the login form to re-log you in.

@garfield69 you have access to this site, can you check to make sure the login test isn't missing something, or if some condition messes with it? https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/shareisland.yml#L78-L91

**Comment by Jorman** [comment]
@cadatoiva I noticed this because I use a script that grab the rss feed from jackett and then parse the data inside, so one time I noticed that the shareisland feed was to small, so I open it and I see the problem.
Is just happen, I can paste some other logs, this's from the rss feed:
```
<?xml version="1.0" encoding="UTF-8"?>
<error code="900" description="Jackett.Common.IndexerException: Exception (shareisland): Login failed: No form found on https://shareisland.org/login using form selector form&#xA; ---&gt; System.Exception: Parse error&#xA; ---&gt; Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://shareisland.org/login using form selector form&#xA;   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 555&#xA;   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1339&#xA;   --- End of inner exception stack trace ---&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830&#xA;   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1665&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345&#xA;   --- End of inner exception stack trace ---&#xA;   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345&#xA;   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807&#xA;   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430" />
```
And this's from Jackett button log:
```
2020-03-11 20:28:38 | Error | Jackett.Common.IndexerException: Exception (shareisland): Login failed: No form found on https://shareisland.org/login using form selector form  ---> System.Exception: Parse error  ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://shareisland.org/login using form selector form    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 555    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1339    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1665    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
-- | -- | --
2020-03-11 20:28:38 | Error | Error on 20200311202838 for Shareisland.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://shareisland.org/login using form selector form    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 555    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1339     <!DOCTYPE html> <html>     <head>         <meta charset="UTF-8" />         <meta http-equiv="refresh" content="0;url='https://shareisland.org/login'" />          <title>Redirecting to https://shareisland.org/login</title>     </head>     <body>         Redirecting to <a href="https://shareisland.org/login">https://shareisland.org/login</a>.     </body> </html>
2020-03-11 20:28:38 | Info | CardigannIndexer (shareisland): Relogin required
```
I don't use all rss feed and I don't have tried every single tracker but to me seems the only one with this kind of problem.

**Comment by garfield69** [comment]
Shareisland is using the unit3d 2.2.7 engine.
The indexer layout is identical across all the other unit3d indexers on the same release (desireleasers, dxdhd, legacyhd, racing4everyone, tellytorrent, tvchaosuk).

I've accounts for all except legacyhd. But I have not been paying attention to if/when they require me to refresh my login in the way the OP describes, although I recall having to do this recently with ShareIsland too.

So I shall now pay attention to the others and see if they too follow this pattern, or if it is solely ShareIsland that does this.

**Comment by Jorman** [comment]
@garfield69 
Do you think that a cookie can solve this?

**Comment by garfield69** [comment]
Came across Elite-Tracker just now, which when I tested returned `The operation was canceled.`
By editing the config from my dashboard and clicking OKAY I was able to continue and the subsequent test was successfull.
I'm including the stack trace here for use in trend analysis (that is, if I get others then we can compare them for similarity).
```
Jackett.Common.IndexerException: Exception (elitetracker): The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 237
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in d:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.PostDataWithCookies(String url, IEnumerable`1 data, String cookieOverride, String referer, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 500
   at Jackett.Common.Indexers.EliteTracker.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\EliteTracker.cs:line 173
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 803
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 220
   at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70
```

**Comment by Jorman** [comment]
Here we go, just happen:
```
Jackett.Common.IndexerException: Exception (shareisland): Login failed: No form found on https://shareisland.org/login using form selector form
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://shareisland.org/login using form selector form
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 555
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1344
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1670
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```
And right after that:
```
Error on 20200320211503 for Shareisland.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://shareisland.org/login using form selector form
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 555
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1344




<div class="table-responsive">
    <div class="text-center">
                                    <ul class="pagination">
        
                    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        
        
                    
            
            
                                                                        <li class="page-item active"><span class="page-link">1</span></li>
                                                                                <li class="page-item"><a class="page-link" href="https://shareisland.org/torrents/filter?page=2">2</a></li>
                                                                                <li class="page-item"><a class="page-link" href="https://shareisland.org/torrents/filter?page=3">3</a></li>
                                                                                <li class="page-item"><a class="page-link" href="https://shareisland.org/torrents/filter?page=4">4</a></li>
                                                                                <li class="page-item"><a class="page-link" href="https://shareisland.org/torrents/filter?page=5">5</a></li>
                                                                                <li class="page-item"><a class="page-link" href="https://shareisland.org/torrents/filter?page=6">6</a></li>
                                                                                <li class="page-item"><a class="page-link" href="https://shareisland.org/torrents/filter?page=7">7</a></li>
                                                                                <li class="page-item"><a class="page-link" href="https://shareisland.org/torrents/filter?page=8">8</a></li>
                                                                    
                            <li class="page-item disabled"><span class="page-link">...</span></li>
            
            
                                
            
            
                                                                        <li class="page-item"><a class="page-link" href="https://shareisland.org/torrents/filter?page=46">46</a></li>
                                                                                <li class="page-item"><a class="page-link" href="https://shareisland.org/torrents/filter?page=47">47</a></li>
...
```

**Comment by RoloSoze** [comment]
Any progress on this issue?

**Comment by Jorman** [comment]
On my side seems that all is ok, maybe some update fix this issue on unit3d engine

**Comment by garfield69** [comment]
@Jorman  looks like ShareIsland have upgraded their Unit3D engine to 2.3.0
But I cannot login, and yet I cannot register either, as it knows my email and username are taken, but the i-forgot-my-password or i-forgot-my-username don't work.
How are you going, login ok?

**Comment by Jorman** [comment]
For me login are ok, in this moment the site is unlocked and anyone can register s new account. For some days, then back to invite only
The only issue that I found, but is not for Jackett, is that every time I've to put username and password, seems that the cookies are not saved
