### ISSUE TITLE
[hebits][fuzer] indexes are broken with Parse Error

### ISSUE THREAD

**Issue by rotem925** [Jackett/Jackett#7502]
### Environment

**OS**: Docker

**.Net Runtime**: hotio/jackett:latest

**.Net Version**:

**Jackett Version**: 0.13.446.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** Yes

### Description

I get an error when checking hebits and fuzer indexes. 
Exception (fuzer): Object reference not set to an instance of an object.: Parse error

### Logged Error Messages

Jackett.Common.IndexerException: Exception (fuzer): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Fuzer.performRegularQuery(TorznabQuery query, String hebName) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Fuzer.cs:line 247
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.Fuzer.performRegularQuery(TorznabQuery query, String hebName) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Fuzer.cs:line 301
   at Jackett.Common.Indexers.Fuzer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Fuzer.cs:line 181
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 803
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

**Comment by cadatoiva** [comment]
Likely affected by #7370 
it would be really useful to see some html from the site.
Please provide the full enhanced log file.

scroll down to the bottom of the Jackett Dashboard and tick the enhanced Logging checkbox
scroll up a bit and click on the apply server settings button
repeat the test
find the log.txt file (linux ~/.config/Jackett/, windows %ProgramData%\Jackett)
edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
save, then drag-drop it here for us to take a look at.
(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by rotem925** [comment]
Thank you! see attached
[log.txt](https://github.com/Jackett/Jackett/files/4288392/log.txt)

**Comment by garfield69** [comment]
Jackett 0.13.467

**Comment by rotem925** [comment]
> Jackett 0.13.467

You rock!!

**Comment by rotem925** [comment]
@garfield69 I can confirm that Hebits works, BUT Fuzer still has the same issue,

**Comment by cadatoiva** [comment]
Can you post the new logs for Fuzer like above? It's probably either a new section of the parser that I missed or an edge case that wasn't present in the first logs you sent.

**Comment by BuSHari** [comment]
I'm having the same issue, please see my log file:
[log.txt](https://github.com/Jackett/Jackett/files/4294300/log.txt)

Thanks in advanced...

**Comment by cadatoiva** [comment]
I got this one, but it'll probably be a couple hours before I get the fix out

**Comment by garfield69** [comment]
Jackett 0.13.483

**Comment by BuSHari** [comment]
Thank you, its working...
