### ISSUE TITLE
[galeriens] Exception (galeriens): Error: Merci de saisir le Captcha: Parse error (Test)

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#7544]
### Description

Galeriens tracker doesn't work as captcha is needed on the login page.

### Logged Error Messages
```
Mar  7 11:24:32 odroid jackett[8428]: 03-07 11:24:32 Info CardigannIndexer (galeriens): Relogin required
Mar  7 11:24:32 odroid jackett[8428]: 03-07 11:24:32 Error Error on 20200307112432 for Galeriens.txtJackett.Common.ExceptionWithConfigData: Error: Merci de saisir le Captcha
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebClientStringResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 462
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 489
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1339
Mar  7 11:24:32 odroid jackett[8428]:
Mar  7 11:24:32 odroid jackett[8428]: 03-07 11:24:32 Error Jackett.Common.IndexerException: Exception (galeriens): Error: Merci de saisir le Captcha
Mar  7 11:24:32 odroid jackett[8428]:  ---> System.Exception: Parse error
Mar  7 11:24:32 odroid jackett[8428]:  ---> Jackett.Common.ExceptionWithConfigData: Error: Merci de saisir le Captcha
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebClientStringResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 462
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 489
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1339
Mar  7 11:24:32 odroid jackett[8428]:    --- End of inner exception stack trace ---
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1665
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
Mar  7 11:24:32 odroid jackett[8428]:    --- End of inner exception stack trace ---
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 225
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 144
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70 Jackett.Common.IndexerException: Exception (galeriens): Error: Merci de saisir le Captcha
Mar  7 11:24:32 odroid jackett[8428]:  ---> System.Exception: Parse error
Mar  7 11:24:32 odroid jackett[8428]:  ---> Jackett.Common.ExceptionWithConfigData: Error: Merci de saisir le Captcha
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebClientStringResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 462
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 489
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1339
Mar  7 11:24:32 odroid jackett[8428]:    --- End of inner exception stack trace ---
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1665
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
Mar  7 11:24:32 odroid jackett[8428]:    --- End of inner exception stack trace ---
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 225
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 144
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mar  7 11:24:32 odroid jackett[8428]:    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
Mar  7 11:24:32 odroid jackett[8428]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by garfield69** [comment]
yes, the site has added a recaptcha challenge to the login. 
I will switch the indexer to using the cookie method so we can access site.

**Comment by garfield69** [comment]
Jackett 0.13.529
