### ISSUE TITLE
[1337x] Access to the path is denied.: Operation not permitted (Config)

### ISSUE THREAD

**Issue by Deliganli** [Jackett/Jackett#7549]
Running programs with docker. I mount a usb stick to '/media/usb'. It is owned by root and has 777 permissions
My docker-compose file is below;

```docker-compose
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=sometz
    volumes:
      - /media/usb/data/jackett/config:/config
      - /media/usb/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
```
When I try to add an indexer it tries to chown it I guess and fails. It is file permission related issue but not sure how we can solve it nicely. All other complimentary programs also storing their data in the same drive (radarr, sonarr, qbittorrent..) but only jackett has issues

### Environment

**OS**: Raspbian GNU/Linux 10 (buster)

**.Net Runtime**: Mono

**.Net Version**: 

**Jackett Version**:0.13.483.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?**  no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages
```
jackett        | 03-07 14:12:16 Info Adding aggregate indexer
jackett        | 03-07 14:12:17 Info Jackett startup finished in 29.881 s
jackett        | Hosting environment: Production
jackett        | Content root path: /app/Jackett/Content
jackett        | Now listening on: http://[::]:9117
jackett        | Application started. Press Ctrl+C to shut down.
jackett        | 03-07 14:21:29 Error System.UnauthorizedAccessException: Access to the path is denied.
jackett        |  ---> System.IO.IOException: Operation not permitted
jackett        |    --- End of inner exception stack trace ---
jackett        |    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
jackett        |    at System.IO.FileSystem.LinkOrCopyFile(String sourceFullPath, String destFullPath)
jackett        |    at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
jackett        |    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
jackett        |    at System.IO.File.Move(String sourceFileName, String destFileName)
jackett        |    at Jackett.Common.Services.IndexerConfigurationService.Save(IIndexer indexer, JToken obj) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerConfigurationService.cs:line 135
jackett        |    at Jackett.Common.Indexers.BaseIndexer.SaveConfig() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 90
jackett        |    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 970
jackett        |    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jackett        | --- End of stack trace from previous location where exception was thrown ---
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett        |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett        |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett        |    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 System.UnauthorizedAccessException: Access to the path is denied.
jackett        |  ---> System.IO.IOException: Operation not permitted
jackett        |    --- End of inner exception stack trace ---
jackett        |    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
jackett        |    at System.IO.FileSystem.LinkOrCopyFile(String sourceFullPath, String destFullPath)
jackett        |    at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
jackett        |    at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
jackett        |    at System.IO.File.Move(String sourceFileName, String destFileName)
jackett        |    at Jackett.Common.Services.IndexerConfigurationService.Save(IIndexer indexer, JToken obj) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerConfigurationService.cs:line 135
jackett        |    at Jackett.Common.Indexers.BaseIndexer.SaveConfig() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 90
jackett        |    at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 970
jackett        |    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jackett        | --- End of stack trace from previous location where exception was thrown ---
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett        |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett        |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett        |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett        |    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

Edit: Reason seems that the drive was exfat so the chown was failing. Formatting the drive with NTFS solved the issue mentioned here.

**Comment by wozniakpawel** [comment]
If anyone ever comes accross this problem - there is no point reformatting the drive. Just mount it with the correct permissions.

For example, if you're using autofs to mount an exfat drive and docker-compose file to set Jackett up, the below config will work. Note you need to make sure that your used and group id are actually both 1000 (run `id` command)

**docker-compose.yaml**
```
[...]
    environment:
      - PUID=1000
      - PGID=1000
```

**/etc/auto.master**
```
/mnt /etc/auto.usb --timeout=900 --ghost
+dir:/etc/auto.master.d
+auto.master
```

**/etc/auto.usb**
`hdd    -fstype=exfat,uid=1000,gid=1000,rw,dev,exec,auto,nouser,async    :/dev/sda1
`

I have not tried this with fstab but it should be equally easy to fix.

**Comment by mariusgaciu** [comment]
I had this issue for a very long time before I found the @Deliganli's edit which solved my issue as well.

I don't like using NTFS file system, so I'm wondering, is this a bug? @garfield69

**Comment by garfield69** [comment]
@mariusgaciu  wrote:
>I don't like using NTFS file system, so I'm wondering, is this a bug? 

Nothing to do with Jackett or the disk format.  You are using docker, so you have to configure the appropriate permissions by mounting the drive correctly as described by wozniakpawel

**Comment by vviikk** [comment]
This happens with I'm using xfat.... no bother, just add

```
...uid=1000,gid=1000...
```

to the line in your /etc/fstab and you're good to go. This is because `chown` fails as exFat isn't necessarily a *nix format.
