### ISSUE TITLE
[solidtorrents] Jackett reports site to be down but it works fine on web browser

### ISSUE THREAD

**Issue by lukjod** [Jackett/Jackett#7585]
site is reported down althought works ok on browser

### Environment

**OS**: Linux Qnap 251+ x86x64

**.Net Runtime**: .Net-Core/.Net-Framework

**.Net Version**:

**Jackett Version**:  Jackett Version 0.13.529.0 

log:
`Jackett.Common.IndexerException: Exception (solidtorrents): Request to https://solidtorrents.net/api/v1/search?q=&category=all&skip=0&sort=date&fuv=no failed (Error GatewayTimeout) - The tracker seems to be down.
 ---> System.Exception: Request to https://solidtorrents.net/api/v1/search?q=&category=all&skip=0&sort=date&fuv=no failed (Error GatewayTimeout) - The tracker seems to be down.
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458
   at Jackett.Common.Indexers.SolidTorrents.SendSearchRequest(String searchString, String category, Int32 page) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SolidTorrents.cs:line 105
   at Jackett.Common.Indexers.SolidTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SolidTorrents.cs:line 122
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 225
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70`

**Comment by garfield69** [comment]
yeah, but the Jackett indexer is using the site's API server while your browser is using the site's web server

so your browser uses https://solidtorrents.net/search?q=2020 for instance, but jackett uses  https://solidtorrents.net/api/v1/search?q=2020&category=all&skip=0&sort=date&fuv=no

if I use my browser to access the API link I get `Error 504 Gateway time-out`

so the problem is legit, and there is nothing that Jackett can do about this.
