### ISSUE TITLE
shazbat - continued errors in 0.13.529.0

### ISSUE THREAD

**Issue by tml** [Jackett/Jackett#7604]
This appears to be a continuation of #7492; I have updated Jackett twice since that issue was closed, but am still seeing an error. The HTML remains the same as previously reported, and can be found at https://gist.github.com/tml/0ad2ce95991997061940600b1167ddac.

I am not an expert at what Jackett is doing here, but the `nth-of-type` selector doesn't appear to be doing what is expected. Using the browser DevTools, I see the following behaviour:

```
document.querySelectorAll("td:nth-of-type(5) a:nth-of-type(1)")
NodeList(150) [ a.btn.btn-sm.btn-theme, a.internal, a, a.btn.btn-sm.btn-theme, a.internal, a, a.btn.btn-sm.btn-theme, a.internal, a, a.btn.btn-sm.btn-theme, … ]

document.querySelectorAll("td:nth-of-type(5) a:nth-of-type(2)")
NodeList []
```

### Environment

**OS**: Ubuntu 18.04.4 LTS
(via linuxserver/sonarr -> lsiobase/mono)

**.Net Runtime**: Mono

**.Net Version**: 2.0.0.5338

**Jackett Version**:  0.13.427.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

Shazbat indexer was giving errors; tried deleting and re-adding, and am still getting the same error (now preventing me from re-adding the indexer)

### Logged Error Messages
```
Jackett.Common.IndexerException: Exception (shazbat): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Shazbat.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Shazbat.cs:line 147
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.Shazbat.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Shazbat.cs:line 171
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by MaDTaZ** [comment]
I am using Native Jackett in linux and getting the same error as well running 529
https://pastebin.com/jSGTiUjm

**Comment by ngosang** [comment]
@tml  @MaDTaZ  Could you upload the HTML source code?

    Please, open shazbat in your browser and go to the list of torrents and perform the same search as in Jackett
    Right click, save page as HTML
    Remove personal information from the HTML file (without breaking the code)
    drag/drop the html file here (use txt extension)

Thanks.

**Comment by tml** [comment]
It was already attached to the ticket, directly from Jackett's logfiles: https://gist.github.com/tml/0ad2ce95991997061940600b1167ddac

**Comment by tml** [comment]
> The :nth-of-type(an+b) CSS pseudo-class matches an element that has an+b-1 siblings with the same element name before it in the document tree

The problem, I think, is that the <a> tag you're looking for isn't a sibling of the first <a> tag under the <td>:

```
  <td style="white-space: nowrap;">
  <!-- Split button -->
    <div class="btn-group">
      <a href="load_torrent?site&info_hash=***elided***&passkey=***elided***" class="btn btn-sm btn-theme">GET</a>
      <button type="button" class="btn btn-sm btn-theme dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu pull-right" role="menu">
        <li><a class="internal" href="torrent_info?info_hash=***elided***">Info</a></li>
                <li><a href="#" onclick="addToDownloadQueue($(this),'***elided***'); return false;">Add to Download Queue</a></li>
                      <li><a href="#" onclick="setAsDownloaded($(this),'***elided***'); return false;">Mark as Downloaded</a></li>
                              <li><a href="#" onclick="adopt($(this),'***elided***'); return false;">Adopt</a></span>
                          </ul>
    </div>  
  </td>
```

The `load_torrent` link is an immediate child of `<div class="btn-group">`, while the other `<a>` tags are nested under the `<ul>`, because they're hidden in a "drop down menu" in the UI. As a suggestion, maybe `"td:nth-of-type(5) li:nth-of-type(1) a"` would match the desired node?

But, again – I'm just grabbing at straws, and may be completely off-base.

**Comment by tml** [comment]
I threw together a quick code pen to illustrate what I think is happening: https://codepen.io/tml/pen/KKpZYwj

**Comment by garfield69** [comment]
Jackett 0.13.611
