### ISSUE TITLE
Jackett crashing with mono stack

### ISSUE THREAD

**Issue by mzlumin** [Jackett/Jackett#761]
Hi,

unfortunately my Jackett Session crashed and dumped an .crash file within /var/crash.
I have extracted the core FIle using `apport-unpack`

The Files can be found here:
[https://1drv.ms/u/s!Atppx5umRWBCgh_y4RP9VuwszP8p](url)
[https://1drv.ms/u/s!Atppx5umRWBCgiBloGj11R_nuaYf](url)

Stack i got, unfortunately uncomplete:

`[zuli12@QuickBox]:(983.2kb)~$
 screen -R 1422.jackett
  at ï¿½.orrentPotatoResponseItem/ï¿½@e.AeHAï¿½.ccessRule.cStateMachineAttribute () <0x0034b>
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.InvokeMoveNext (object) <0x000b5>
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x00178>
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) <0x00020>
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.Run () <0x000d1>
  at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action,bool,System.Threading.Tasks.Task&) <0x00071>
  at System.Threading.Tasks.Task.FinishContinuations () <0x00177>
  at System.Threading.Tasks.Task.FinishStageThree () <0x00068>
  at System.Threading.Tasks.Task.FinishStageTwo () <0x00133>
  at System.Threading.Tasks.Task.Finish (bool) <0x00089>
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task&) <0x00131>
  at System.Threading.Tasks.Task.ExecuteEntry (bool) <0x000d6>
  at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x0000e>
  at System.Threading.ThreadPoolWorkQueue.Dispatch () <0x001d6>
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x00008>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) <0x0005a>`

`Native stacktrace:
        mono() [0x4accca]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0x113e0) [0x7ff1eddb53e0]
        /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7ff1ed7fa428]
        /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7ff1ed7fc02a]
        mono() [0x65aae9]
        mono() [0x65acf7]
        mono() [0x65ae46]
        mono() [0x5bc957]
        mono(mono_runtime_cleanup+0xe) [0x5b645e]
        mono() [0x42484b]
        mono() [0x545f5b]
        [0x4204dfe2]`

`Debug info from gdb:
================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
================================================================
Aborted (core dumped)
`

Also debugging with gdb does not bring any useful result for me :(

`[zuli12@QuickBox]:(397.5Mb)/tmp/monoCrash$ gdb --core=CoreDump
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
[New LWP 16523]
[New LWP 32955]
[New LWP 32885]
[New LWP 32886]
[New LWP 16114]
Core was generated by `mono Jackett/JackettConsole.exe'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ff1ed7fa428 in ?? ()
[Current thread is 1 (LWP 16523)]
(gdb) where
#0  0x00007ff1ed7fa428 in ?? ()
#1  0x00007ff1ed7fc02a in ?? ()
#2  0x0000000000000020 in ?? ()
#3  0x0000000000000000 in ?? ()
(gdb) bt full
#0  0x00007ff1ed7fa428 in ?? ()
No symbol table info available.
#1  0x00007ff1ed7fc02a in ?? ()
No symbol table info available.
#2  0x0000000000000020 in ?? ()
No symbol table info available.
#3  0x0000000000000000 in ?? ()
No symbol table info available.
(gdb) quit`

`No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial`

`[zuli12@QuickBox]:(397.5Mb)/tmp/monoCrash$ mono --version
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 14 12:30:00 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
`

ANy help appreciated :(

**Comment by kaso17** [comment]
Is it reproducible?
I occasional see similar core dumps. Always pointing to some inner mono lib.
Currently I'm not motivated to debug mono ;)
I'm using systemd to automatically restart jackett in such a case.

**Comment by mzlumin** [comment]
No  not really reproducible till now ..
i think i may also use a cronjob or systemd to worksround this...
