### ISSUE TITLE
[horriblesubs] Parse error: Parse error (Config)

### ISSUE THREAD

**Issue by mabargiel** [Jackett/Jackett#7610]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Raspbian

**.Net Runtime**: .Net-Core

**.Net Version**: newest for docker linuxserver/jackett

**Jackett Version**: newest

**Last Working Jackett Version**: not working since installed

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Click Add indexer, search for HorribleSubs and try to add it

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

```
 jackett         | 03-10 12:01:19 Error System.Exception: Parse error
jackett         |  ---> System.Exception: Parse error
jackett         |  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
jackett         |  ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
jackett         |  ---> System.Net.Sockets.SocketException (125): Operation canceled
jackett         |    --- End of inner exception stack trace ---
jackett         |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
jackett         |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
jackett         |    at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
jackett         |    at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
jackett         |    at System.Net.Http.HttpConnection.FillAsync()
jackett         |    at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
jackett         |    --- End of inner exception stack trace ---
jackett         |    at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
jackett         |    at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
jackett         |    at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
jackett         |    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
jackett         |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
jackett         |    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 240
jackett         |    at Jackett.Common.Utils.Clients.WebClient.GetBytes(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 102
jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.DoFollowIfRedirect(WebClientByteResult incomingResponse, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 650
jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.FollowIfRedirect(WebClientByteResult response, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 593jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.FollowIfRedirect(WebClientStringResult response, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 581
jackett         |    at Jackett.Common.Indexers.HorribleSubs.GetReleases(String ResultURL, Boolean latestOnly, String titleContains) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 154
jackett         |    --- End of inner exception stack trace ---
jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
jackett         |    at Jackett.Common.Indexers.HorribleSubs.GetReleases(String ResultURL, Boolean latestOnly, String titleContains) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 320
jackett         |    at Jackett.Common.Indexers.HorribleSubs.PerformLatestQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 135
jackett         |    --- End of inner exception stack trace ---
jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
jackett         |    at Jackett.Common.Indexers.HorribleSubs.PerformLatestQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 141
jackett         |    at Jackett.Common.Indexers.HorribleSubs.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 67
jackett         |    at Jackett.Common.Indexers.HorribleSubs.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 47
jackett         |    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett         |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett         |    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 System.Exception: Parse error
jackett         |  ---> System.Exception: Parse error
jackett         |  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
jackett         |  ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
jackett         |  ---> System.Net.Sockets.SocketException (125): Operation canceled
jackett         |    --- End of inner exception stack trace ---
jackett         |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
jackett         |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
jackett         |    at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
jackett         |    at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
jackett         |    at System.Net.Http.HttpConnection.FillAsync()
jackett         |    at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
jackett         |    --- End of inner exception stack trace ---
jackett         |    at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
jackett         |    at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync()
jackett         |    at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
jackett         |    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
jackett         |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
jackett         |    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 240
jackett         |    at Jackett.Common.Utils.Clients.WebClient.GetBytes(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 102
jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.DoFollowIfRedirect(WebClientByteResult incomingResponse, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 650
jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.FollowIfRedirect(WebClientByteResult response, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 593jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.FollowIfRedirect(WebClientStringResult response, String referrer, String overrideRedirectUrl, String overrideCookies, Boolean accumulateCookies) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 581
jackett         |    at Jackett.Common.Indexers.HorribleSubs.GetReleases(String ResultURL, Boolean latestOnly, String titleContains) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 154
jackett         |    --- End of inner exception stack trace ---
jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
jackett         |    at Jackett.Common.Indexers.HorribleSubs.GetReleases(String ResultURL, Boolean latestOnly, String titleContains) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 320
jackett         |    at Jackett.Common.Indexers.HorribleSubs.PerformLatestQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 135
jackett         |    --- End of inner exception stack trace ---
jackett         |    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
jackett         |    at Jackett.Common.Indexers.HorribleSubs.PerformLatestQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 141
jackett         |    at Jackett.Common.Indexers.HorribleSubs.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 67
jackett         |    at Jackett.Common.Indexers.HorribleSubs.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HorribleSubs.cs:line 47
jackett         |    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
jackett         |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jackett         |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jackett         |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jackett         |    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
jackett         | 03-10 12:06:20 Info Updates are disabled via --NoUpdates.
jackett         | 03-10 12:07:08 Error On attempt 1 checking for results from Horrible Subs: The operation was canceled.
jackett         | 03-10 12:07:34 Error On attempt 1 checking for results from Horrible Subs: The operation was canceled.
jackett         | 03-10 12:07:49 Error On attempt 1 checking for results from Horrible Subs: The operation was canceled.

```

Also occuring for others like Nyaa.si or Nyaa.pantsu

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Your Jackett is not getting a response back from the http GET it is posting.
If this is happening not only to hooriblesubs but to Nyaa.si or Nyaa.pantsu as well, then this is typically due to some system firewall or security app or router firewall blocking  either the Jackett app's access to the wan or port, or your ISP doing site blocking (although the latter usually returns a response but not what the indexer expects causing a different failure message).
Can any of the above apply to you?

Also, since you are running the docker flavour, are you limiting the container RAM and if so at what amount? Some docker uses reported similar errors and found increasing the RAM made a difference.
