### ISSUE TITLE
Demonoid/Cloudflare Exception: Clearance failed after 30 attempts

### ISSUE THREAD

**Issue by JeffCarpenter** [Jackett/Jackett#7637]
### Environment

**OS**:
Manjaro Testing (Linux 5.5.4)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
NET Core 3.1.2 and .NET Core SDK 3.1.102

**.Net Version**:

**Jackett Version**:
0.13.633

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
no

### Description
Add Demonoid and click test

### Logged Error Messages

[Pastebin Dump](https://paste.gg/p/anonymous/2ce0fa7c8acb4a5c8ebc31aefb0735f6/files/70294671b4234104993881232c63ea93/raw)

<details>
<summary>
Jackett.Common.IndexerException & CloudflareSolverRe.Exceptions.CloudflareClearanceException
</summary>

```
Mar 13 11:02:14 nombre jackett[2721959]: 03-13 11:02:14 Error Jackett.Common.IndexerException: Exception (demonoid): Clearance failed after 30 attempt(s).
Mar 13 11:02:14 nombre jackett[2721959]:  ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
Mar 13 11:02:14 nombre jackett[2721959]:    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:02:14 nombre jackett[2721959]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 240
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1321
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
Mar 13 11:02:14 nombre jackett[2721959]:    --- End of inner exception stack trace ---
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 803
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (demonoid): Clearance failed after 30 attempt(s).
Mar 13 11:02:14 nombre jackett[2721959]:  ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
Mar 13 11:02:14 nombre jackett[2721959]:    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:02:14 nombre jackett[2721959]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 240
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1321
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
Mar 13 11:02:14 nombre jackett[2721959]:    --- End of inner exception stack trace ---
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 803
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Mar 13 11:02:14 nombre jackett[2721959]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mar 13 11:02:14 nombre jackett[2721959]:    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
Mar 13 11:04:24 nombre jackett[2721959]: 03-13 11:04:24 Info Found 100 (1 new) releases from LimeTorrents
Mar 13 11:04:27 nombre jackett[2721959]: 03-13 11:04:27 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:30 nombre jackett[2721959]: 03-13 11:04:30 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:32 nombre jackett[2721959]: 03-13 11:04:32 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:33 nombre jackett[2721959]: 03-13 11:04:33 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:36 nombre jackett[2721959]: 03-13 11:04:36 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:38 nombre jackett[2721959]: 03-13 11:04:38 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:39 nombre jackett[2721959]: 03-13 11:04:39 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:41 nombre jackett[2721959]: 03-13 11:04:41 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:43 nombre jackett[2721959]: 03-13 11:04:43 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:46 nombre jackett[2721959]: 03-13 11:04:46 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:48 nombre jackett[2721959]: 03-13 11:04:48 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:49 nombre jackett[2721959]: 03-13 11:04:49 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:51 nombre jackett[2721959]: 03-13 11:04:51 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:54 nombre jackett[2721959]: 03-13 11:04:54 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:56 nombre jackett[2721959]: 03-13 11:04:56 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:04:58 nombre jackett[2721959]: 03-13 11:04:58 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:00 nombre jackett[2721959]: 03-13 11:05:00 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:01 nombre jackett[2721959]: 03-13 11:05:01 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:04 nombre jackett[2721959]: 03-13 11:05:04 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:06 nombre jackett[2721959]: 03-13 11:05:06 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:07 nombre jackett[2721959]: 03-13 11:05:07 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:09 nombre jackett[2721959]: 03-13 11:05:09 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:11 nombre jackett[2721959]: 03-13 11:05:11 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:14 nombre jackett[2721959]: 03-13 11:05:14 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:16 nombre jackett[2721959]: 03-13 11:05:16 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:18 nombre jackett[2721959]: 03-13 11:05:18 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:20 nombre jackett[2721959]: 03-13 11:05:20 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:22 nombre jackett[2721959]: 03-13 11:05:22 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:05:23 nombre jackett[2721959]: 03-13 11:05:23 Info Found 100 (0 new) releases from LimeTorrents
Mar 13 11:06:05 nombre jackett[2721959]: 03-13 11:06:05 Error Jackett.Common.IndexerException: Exception (kickasstorrent): The operation was canceled.
Mar 13 11:06:05 nombre jackett[2721959]:  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 240
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 442
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1321
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
Mar 13 11:06:05 nombre jackett[2721959]:    --- End of inner exception stack trace ---
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430 Jackett.Common.IndexerException: Exception (kickasstorrent): The operation was canceled.
Mar 13 11:06:05 nombre jackett[2721959]:  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 13 11:06:05 nombre jackett[2721959]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 240
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 442
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1321
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
Mar 13 11:06:05 nombre jackett[2721959]:    --- End of inner exception stack trace ---
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
Mar 13 11:06:05 nombre jackett[2721959]:    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
```
</details>

**Comment by garfield69** [comment]
The Demonoid site uses Cloudflare as its server provider.
It in turn is filtering for DDoS robots and has determined that your IP address falls within a block of IP addresses that have been blacklisted for having previously generated an attack.
Hence Cloudflare issues the ReCaptcha challenge to prove you are human.
Jackett cannot currently solve this challenge.

Until Demonoid/Cloudflare lift the blacklist, you will : 
- have to use your browser to access the site, or 
- use a proxy/vpn to get a different IP address that is not blacklisted or
- wait for the blacklist to be revoked

Since I can use the Jackett Demonoid indexer without issue, this is not an issue with Jackett.

**Comment by JeffCarpenter** [comment]
@garfield69 what do you think about a feature to let the user answer the ReCapture? Could grab the cookie from a YAML file or even Selenium's WebDriver.manage().getCookieNamed. And would you be interested in a PR?

**Comment by garfield69** [comment]
>what do you think about a feature to let the user answer the ReCapture? Could grab the cookie from a YAML file or even Selenium's WebDriver.manage().getCookieNamed. And would you be interested in a PR?

I do not believe this is practical.
Jackett is not just the Dashboard user-interactive search tool.
It is mostly used to provide apps (like Sonarr, Radarr, DuckieTV, etc) with  an automated access to torrent sites via the Torznab interface.
I don't see how you could interrupt such automation with a popup to provide the challenge page for the user to solve a challenge while maintaining the automation aspect.

But I am not a c# dev, and cannot answer your question with certainty.
I will invite the c# devs to comment.
Ping any of  @cadatoiva  @ngosang  @junglebus  for your opinion. Thanks.

**Comment by JeffCarpenter** [comment]
Sure, I'll start a feature request and ping. Thanks

**Comment by cadatoiva** [comment]
We will not be adding Selenium into Jackett core anytime soon. I've worked other projects that have managed web access through selenium in C# and it will obliterate our cross platform compatibility.
