### ISSUE TITLE
[hdtorrents] Exception (hdtorrents): Input string was not in a correct format.: Input string was not in a correct format. (Test)

### ISSUE THREAD

**Issue by stevegoossens** [Jackett/Jackett#7650]
### Environment

**OS**: Docker on CentOS 8

**.Net Runtime**: whatever comes with Jackett docker

**.Net Version**: whatever comes with Jackett docker

**Jackett Version**: 0.13.427.0

**Last Working Jackett Version**: ?

**Are you using a proxy or VPN?**: no

### Description

With hd-torrents added (in the same way that has always worked previously), clicking "Test" results in a failure with error message. Similarly, clients such as Sonarr and Radarr cannot use hd-torrents via Jackett, when they have been working fine up until recently.

### Logged Error Messages
```
 An error occured while testing this indexer
Exception (hdtorrents): Input string was not in a correct format.: Input string was not in a correct format.
```

```

Date | Level | Message
-- | -- | --
2020-03-14 13:17:21 | Error | Jackett.Common.IndexerException: Exception (hdtorrents): Input string was not in a correct format.  ---> System.FormatException: Input string was not in a correct format.    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDTorrents.cs:line 127    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
2020-03-14 13:17:21 | Error | On attempt 3 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 13:17:16 | Error | On attempt 2 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 13:17:15 | Error | On attempt 1 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 13:12:35 | Error | Jackett.Common.IndexerException: Exception (hdtorrents): Input string was not in a correct format.  ---> System.FormatException: Input string was not in a correct format.    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDTorrents.cs:line 127    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
2020-03-14 13:12:35 | Error | On attempt 3 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 13:12:34 | Error | On attempt 2 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 13:12:33 | Error | On attempt 1 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 13:10:21 | Error | Jackett.Common.IndexerException: Exception (hdtorrents): Input string was not in a correct format.  ---> System.FormatException: Input string was not in a correct format.    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDTorrents.cs:line 127    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
2020-03-14 13:10:20 | Error | On attempt 3 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 13:10:20 | Error | On attempt 2 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 13:10:19 | Error | On attempt 1 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 05:27:53 | Error | Jackett.Common.IndexerException: Exception (hdtorrents): Input string was not in a correct format.  ---> System.FormatException: Input string was not in a correct format.    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDTorrents.cs:line 127    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
2020-03-14 05:27:53 | Error | On attempt 3 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 05:27:52 | Error | On attempt 2 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 05:27:51 | Error | On attempt 1 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 01:24:21 | Error | Jackett.Common.IndexerException: Exception (hdtorrents): Input string was not in a correct format.  ---> System.FormatException: Input string was not in a correct format.    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDTorrents.cs:line 127    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
2020-03-14 01:24:21 | Error | On attempt 3 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 01:24:19 | Error | On attempt 2 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-14 01:24:18 | Error | On attempt 1 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 23:15:44 | Error | Jackett.Common.IndexerException: Exception (hdtorrents): Input string was not in a correct format.  ---> System.FormatException: Input string was not in a correct format.    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDTorrents.cs:line 127    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
2020-03-13 23:15:44 | Error | On attempt 3 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 23:15:42 | Error | On attempt 2 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 23:15:41 | Error | On attempt 1 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 20:09:42 | Error | Jackett.Common.IndexerException: Exception (hdtorrents): Input string was not in a correct format.  ---> System.FormatException: Input string was not in a correct format.    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDTorrents.cs:line 127    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
2020-03-13 20:09:41 | Error | On attempt 3 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 20:09:40 | Error | On attempt 2 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 20:09:40 | Error | On attempt 1 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 19:21:14 | Error | Jackett.Common.IndexerException: Exception (hdtorrents): Input string was not in a correct format.  ---> System.FormatException: Input string was not in a correct format.    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDTorrents.cs:line 127    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
2020-03-13 19:21:14 | Error | On attempt 3 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 19:21:13 | Error | On attempt 2 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 19:21:13 | Error | On attempt 1 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 19:07:40 | Error | Jackett.Common.IndexerException: Exception (hdtorrents): Input string was not in a correct format.  ---> System.FormatException: Input string was not in a correct format.    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.HDTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/HDTorrents.cs:line 127    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
2020-03-13 19:07:39 | Error | On attempt 3 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 19:07:38 | Error | On attempt 2 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 19:07:33 | Error | On attempt 1 checking for results from HD-Torrents: Input string was not in a correct format.
2020-03-13 18:52:04 | Info | Found 20 (2 new) releases from HD-Torrents
2020-03-13 18:36:35 | Info | Found 20 (0 new) releases from HD-Torrents
2020-03-13 18:29:10 | Info | Found 0 releases from HD-Torrents for: MasterChef S16E05
2020-03-13 18:29:08 | Info | Found 0 releases from HD-Torrents for: Masterchef S16E05
2020-03-13 18:29:02 | Info | Found 0 releases from HD-Torrents for: MasterChef S16E04
2020-03-13 18:29:00 | Info | Found 0 releases from HD-Torrents for: Masterchef S16E04
```

**Comment by cadatoiva** [comment]
Please post the enhanced error log per [these instructions](https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-turn-on-enhanced-logging)

**Comment by stevegoossens** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4333198/log.txt)

**Comment by ngosang** [comment]
I get this.

**Comment by ngosang** [comment]
Well I can't see anything wrong in the hd-torrents implementation. Maybe other dev can help more.

**Comment by cadatoiva** [comment]
Nothing in the logs specifically that can help narrow down where the issue is, except that the error is happening somewhere in this part of the code. https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Utils/Clients/WebClient.cs#L112-L155

@stevegoossens can you make sure this link works for you? https://hd-torrents.org/torrents.php?active=0&options=0

If that does work, then we'll need a dev with access to the website, because the login page/check is working, just not the search.

**Comment by stevegoossens** [comment]
that link works for me.

hd-torrents recently added CloudFlare anti DDoS protection, so the first time I visit that link, I see the CloudFlare anti-DDoS interstitial page for a few seconds, and then it redirects to a torrent search listing (regulate HTML page that is seen when using the site normally)

could it be the interstitial page (content) is making the Jackett check fail?

**Comment by cadatoiva** [comment]
Unless they've added yet another bot trap or there's a Google ReCaptcha sometimes, but those error messages look different from this one.

**Comment by stevegoossens** [comment]
ok, well i can send an invite if you can provide an email address

**Comment by cadatoiva** [comment]
cadatoiva -at- yahoo.com is mine

**Comment by stevegoossens** [comment]
ok, sent

**Comment by stevegoossens** [comment]
Thank you for fixing this :)
