### ISSUE TITLE
Jackett exception error with alternate title names from Sonaar will fail further attempts

### ISSUE THREAD

**Issue by vulcan4d** [Jackett/Jackett#7678]
**OS**: Debian
**Jackett Version**: 0.14.49.0
**Are you using a proxy or VPN?** [yes/no] no

I've been told by the Sonarr developers to show this to you guys.  There is an issue when doing torznab searches using Jackett for an indexer with titles that have "alternate titles" available.  Sonarr will do a search but receive an exception error from Jackett.  I'm sure it is because it has not found the title after the 1st search by that title but Sonarr will search for all available "titles names" for that series.  At this moment I can't download any show that has multiple title names, Jackett sends the exception after the 1st try then Sonaar gives up the search due to this error seen.

Below is the error coming back from Jackett that the Sonarr developer wants me to share.  
```
Jackett.Common.IndexerException: Exception (gimmepeers): Sequence contains no elements
 ---> System.Exception: Parse error
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.GimmePeers.ProcessPage(List`1 releases, String searchUrl) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/GimmePeers.cs:line 147
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 830
   at Jackett.Common.Indexers.GimmePeers.ProcessPage(List`1 releases, String searchUrl) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/GimmePeers.cs:line 194
   at Jackett.Common.Indexers.GimmePeers.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/GimmePeers.cs:line 130
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430`


`Error on 20200315093255 for GimmePeers.txtSystem.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Jackett.Common.Indexers.GimmePeers.ProcessPage(List`1 releases, String searchUrl) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/GimmePeers.cs:line 147





<script type="text/javascript">
var hoveredElement=null;

function tick(){
    $('.ticker').filter(function(item){   
                return !$(this).is(hoveredElement)
            }).each(function(){
        $(this).find('li:first').slideUp(function () {                       
            $ticker = $(this).closest('.ticker');
            
            $(this).appendTo($ticker).slideDown();
        });
    });
}
setInterval(tick, 6500);


$(function(){
    $('.ticker').hover(function(){
hoveredElement=$(this);        
    },function(){
        hoveredElement=null;
    });
});
</script>
<html><head>
<title>GP :: Search results for &quot;I Griffin S18E13&quot;</title>
<META name="description" content="GimmePeers.com the greatest blackhole!">


<link rel="alternate" type="application/rss+xml" title="Latest Torrents" href="/rss.php?passkey=eaadeb10f5edf9a789c703dceeb14cb9">
<link rel="stylesheet" type="text/css" href="/default.css" />
<style>
.highlighttext{
background-color:yellow;
font-weight:bold;
}
a.noTab {
/* visibility: hidden;
display: none; */
}
</style>
</head>
<BODY leftMargin=8 rightMargin=8 topmargin=8>

<table width=80% class=gp_nav_off height=35px align=center cellspacing="0" cellpadding="0">
<tr>
<td align="left" width=33%><a href=/friends.php><img height=17px width=17px alt=Friends title=Friends src=../core/design/icons/friend.png></a>
<b>Welcome,&nbsp;<a title='Click for your GP profile' href="/userdetails.php?id=13229">vulcan4d</a>&nbsp;<img src=../core/design/icons/c4a.png alt='Tier1' title='Tier1' style='margin-left: 2pt'>&nbsp;&nbsp;<font class=lime_text>[<a href="/logout.php">Logout</a>]&nbsp;&nbsp;<font class=lime_text>[<a title='Click for account settings' href="/my.php">Settings</a>]&nbsp;&nbsp;[<a href="/invite.php">4&nbsp;Invites</a>]&nbsp;&nbsp;[<a title='Lucky Tokens' href="/tokenx.php">0&nbsp;Tokens</a>]&nbsp;&nbsp;[<a title='Lotto Tickets' href="/lottox.php">0&nbsp;Tickets</a>]</font>

<td align="center" width=33%>

<img src='../core/design/icons/c4a.png' height=15px width=15px><font class=white_text_heavy>&nbsp;Membership Expires:&nbsp;</font><a href=/renewal.php alt='membership' title='membership click to add time'><font class=yellow_text_heavy><u>Apr 12 2020</u></font></a><font class=white_text_heavy>&nbsp;&nbsp;&nbsp;&nbsp;Server Time:&nbsp;</font><font class=yellow_text_heavy>12:32</font>

<td align="right" width=33%>
<img height=15px width=15px alt="seeding" title="seeding" src="../core/design/up1.png">&nbsp;<a title='your seeds' href="/userdetails.php?id=13229&utorr=1#torrents">0</a>&nbsp;&nbsp;<img height=15px width=15px alt="leeching" title="leeching" src="../core/design/down1.png">&nbsp;<a title='your leeching' href="/userdetails.php?id=13229&utorr=1#torrents">10</a>
&nbsp;&nbsp;<b>Open Port:&nbsp;<b><a href=/faq.php#21 title='Click to learn more about becoming connectable'><font class=red_text>No</font></a></b> &nbsp;&nbsp;
<a href=/messages.php?action=viewmailbox><img valign=top style=border:none alt=inbox title='Inbox (new messages)' src=../core/design/nwpm.gif></a>&nbsp;3&nbsp;(2 New)</span>&nbsp;<a href=/messages.php?action=viewmailbox&box=-1><img style=border:none alt=sentbox title=Sentbox src=../core/design/otsm.png></a>&nbsp;0</span> 
</table>
<table width=80% align=center valign=middle cellspacing="0" cellpadding="0">

<tr><td><a href="/forums.php?action=viewforum&forumid=2"><img src="/core/design/header/sh56.png" width="100%" border="0"></img></a>
</td></tr></table>
<table width=80% class=gp_sub_nav height=30px align=center valign=middle cellspacing="0" cellpadding="0">
<tr><br>
<td width=5%></td>
<td class="white_text_heavy" align="center"><a href=/>Home</a></td>
<td class="white_text_heavy" align="center"><a href=/browse.php>Torrents</a> | <a href=/reseed.php>Reseeds</a> | <a href=/upload.php>Upload</a></td>
<td class="white_text_heavy" align="center"><a href=/forums.php>Forums</a> | <a href=/forums.php?action=viewforum&forumid=4>Requests</a></td>
<td class="white_text_heavy" align="center"><a href=/getrss.php>RSS</a> | <a href="/bookmarks.php?op=view">Booked</a> | <a href="/watchlist.php">WatchList</a></td>
<td class="white_text_heavy" align="center"><a href=/rules.php>Rules</a> | <a href=/faq.php>FAQ</a></td>
<td class="white_text_heavy" align="center"><a href=/helpdesk.php>Help</a> | <a href=/staff.php>Staff</a> | <a href=/renewal.php>Renewal</a></td>

</tr>
</table>

<table width=80% class="gp_sub_nav1" align="center" height="30" cellpadding="4" cellspacing="0" border="0">
<tr><td align=center class=main style="padding-top: 20px; padding-bottom: 20px">
<span><table cellspacing=0 cellpadding=0 height=33px width=170px><tr><td style=background:url('/core/design/icons/pm4.gif'); background-repeat:no-repeat; background-attachment:fixed; background-position:center; background=http://www.gimmepeers.com/core/design/icons/pm4.gif>
<b><a href=/messages.php?action=viewmailbox><font color=white><center> 2 new messages!</font></center></a></b></td></tr></span></table><br>

<span><p><table class=comtable width=60% border=0 cellspacing=0 cellpadding=5>
<tr><td class=gp_sub_nav><font class=white_text2><b>&nbsp;Announcement:
Lucky Tokens {2020-03-13}</font></b></td></tr>
<tr><td style='padding: 10px;'>
<div align=center><font color=lime><font size=6><b>Lucky Tokens!</b></font></font><br />
<br />
<font size=3>Between now and April 1st, pick up a free lucky token with every <br />
standard membership renewal or top-up.<br />
<br />
Each token can award your account up to a free year of GP membership.<br />
<br />
Thank you for your membership!<br />
-GP Staff-</font></div> <br /><hr /><br />
<a class="noTab" href="/3254kh3538sgh34.php?returnto=%2Fbrowse.php%3Fsearch%3DI%2BGriffin%2BS18E13%26cat%3D0">
<b><font size=2>CLICK HERE TO CLEAR ANNOUNCEMENT</b></a></td></tr></table></p></span>
<!DOCTYPE html>
<html>
<head>
<title>TICKET BETA</title>
<script type="text/javascript" src="ticker/jquery-1.9.1.js">
          </script>
<style type="text/css">
                        .ticker {
                        	height: 32px;
                        	overflow: hidden;
                        	/* position: fixed; */
                        	line-height: 31px;
                        	/* margin-left: 5%; */

                        }
                        ul.ticker li span{ /*updates GPgreen*/
                        	background-color: #5a8415;
                        	border-right: 1px solid #FFFFFF
                        	color: #FFFFFF;
                        	margin-right: 6px;
                        	font-size: 20px;
                                padding: 10px 9px 10px 29px;
                        }
                        ul.ticker li span1{  /*news GPred*/
                        	background-color: #cc1111;
                        	border-right: 1px solid #FFFFFF
                        	color: #FFFFFF;
                        	margin-right: 6px;
                        	font-size: 20px;
                                padding: 10px 9px 10px 14.5px;
                        }
                        ul.ticker li span2{ /*faq GPblue*/
                        	background-color: #155a84;
                        	border-right: 1px solid #FFFFFF
                        	color: #FFFFFF;
                        	margin-right: 6px;
                        	font-size: 20px;
                                padding: 10px 9px 10px 28.5px;
                        }
                        ul.ticker li span3{ /*tips GPorange*/
                        	background-color: #ff9000;
                        	border-right: 1px solid #FFFFFF
                        	color: #FFFFFF;
                        	margin-right: 6px;
                        	font-size: 20px;
                                padding: 10px 9px 10px 26.5px;
                        }

                        .ticker a:hover,
                         .ticker li:hover{
                        /*	color:#D8D8D8; */
                        }
                        .ticker a,
                        .ticker li{
                          color: #FFFFFF;
                          font-size: 14px;
                          background-color:#1B1B1B;
                          list-style: none;
                         /*  margin-right: 20%; */

                        }
		        </style> </head>
<table width=75% border=0 align="center" position="static">
<tr><td align="left" position="static">
<body>
<ul class=ticker>
<li><span>Upd&raquo;</span>2020-03-13: Lucky Tokens: Until April 1st. pick up a luck token with your renewal!</li>
<li><span1>News&raquo;</span1>2020-02-12: ACCOUNT UPDATE: Individual peer connectable status from your profile!</li>

<li><span1>News&raquo;</span1>2020-01-28: Get DOUBLE the signup-bonus (2mth), for all newly invited accounts for <font color=lime>GP 2020!</font></a></li>




<li><span2>FAQ&raquo;</span2>?!? SITE OUTAGE ?!? Check for site issues and chat with staff and other members on our <a href=/forums.php?action=viewtopic&topicid=5215><font color=yellow><u>IRC Channel!</u></font></a></li>
<li><span3>Tips&raquo;</span3>You will have trouble with torrent performance using Azureus/VUZE and BiglyBT clients.</li>
<li><span3>Tips&raquo;</span3>For your best performance and torrenting experience, always use a <a href=/forums.php?action=viewtopic&topicid=31><font color=yellow><u>Recommended Client!</u></font></a></li>
</ul> </body>
</tr></td>
</table><br>
</html>
<form method="get" action="browse.php">
<table>
<tr>
<table>
<tr>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c1 type="checkbox" value=1><a class=catlink href=browse.php?cat=1>Anime</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c27 type="checkbox" value=1><a class=catlink href=browse.php?cat=27>App-LINUX</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c2 type="checkbox" value=1><a class=catlink href=browse.php?cat=2>App-MAC</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c4 type="checkbox" value=1><a class=catlink href=browse.php?cat=4>App-WIN</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c29 type="checkbox" value=1><a class=catlink href=browse.php?cat=29>Books (a)</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c5 type="checkbox" value=1><a class=catlink href=browse.php?cat=5>Books (e)</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c6 type="checkbox" value=1><a class=catlink href=browse.php?cat=6>Mobile</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c7 type="checkbox" value=1><a class=catlink href=browse.php?cat=7>Music</a></td>
</tr><tr><td style="padding-bottom: 2px;padding-left: 7px"><input name=c8 type="checkbox" value=1><a class=catlink href=browse.php?cat=8>Other</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c28 type="checkbox" value=1><a class=catlink href=browse.php?cat=28>Sports</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c3 type="checkbox" value=1><a class=catlink href=browse.php?cat=3>Tutorials</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c9 type="checkbox" value=1><a class=catlink href=browse.php?cat=9>Game-NIN</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c11 type="checkbox" value=1><a class=catlink href=browse.php?cat=11>Game-PS</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c10 type="checkbox" value=1><a class=catlink href=browse.php?cat=10>Game-WIN</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c12 type="checkbox" value=1><a class=catlink href=browse.php?cat=12>Game-XBOX</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c13 type="checkbox" value=1><a class=catlink href=browse.php?cat=13>Movie-3D</a></td>
</tr><tr><td style="padding-bottom: 2px;padding-left: 7px"><input name=c26 type="checkbox" value=1><a class=catlink href=browse.php?cat=26>Movie-4K</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c14 type="checkbox" value=1><a class=catlink href=browse.php?cat=14>Movie-Bluray</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c15 type="checkbox" value=1><a class=catlink href=browse.php?cat=15>Movie-DVDR</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c18 type="checkbox" value=1><a class=catlink href=browse.php?cat=18>Movie-Packs</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c16 type="checkbox" value=1><a class=catlink href=browse.php?cat=16>Movie-x264</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c17 type="checkbox" value=1><a class=catlink href=browse.php?cat=17>Movie-x265</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c19 type="checkbox" value=1><a class=catlink href=browse.php?cat=19>Movie-XVID</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c20 type="checkbox" value=1><a class=catlink href=browse.php?cat=20>TV-HD</a></td>
</tr><tr><td style="padding-bottom: 2px;padding-left: 7px"><input name=c21 type="checkbox" value=1><a class=catlink href=browse.php?cat=21>TV-SD</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c25 type="checkbox" value=1><a class=catlink href=browse.php?cat=25>TV-Retail-HD</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c24 type="checkbox" value=1><a class=catlink href=browse.php?cat=24>TV-Retail-SD</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c23 type="checkbox" value=1><a class=catlink href=browse.php?cat=23>TV-Packs</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c22 type="checkbox" value=1><a class=catlink href=browse.php?cat=22>TV-x265</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c50 type="checkbox" value=1><a class=catlink href=browse.php?cat=50>xXx-HD</a></td>
<td style="padding-bottom: 2px;padding-left: 7px"><input name=c49 type="checkbox" value=1><a class=catlink href=browse.php?cat=49>xXx-SD</a></td>
<td style="padding-left: 1px" align=left><div align=right><input type='submit' class=btn value='Show Selected' /></div></td>
</tr></td></table>
</form>

<form method="get" action="browse.php">
<table>
<p align="center" font class="white_text_heavy">
Search:
<input type="text" name="search" size="40" value="I Griffin S18E13" />
<select name="cat">
<option value="0">(all types)</option>
<option value="1">Anime</option>
<option value="27">App-LINUX</option>
<option value="2">App-MAC</option>
<option value="4">App-WIN</option>
<option value="29">Books (a)</option>
<option value="5">Books (e)</option>
<option value="6">Mobile</option>
<option value="7">Music</option>
<option value="8">Other</option>
<option value="28">Sports</option>
<option value="3">Tutorials</option>
<option value="9">Game-NIN</option>
<option value="11">Game-PS</option>
<option value="10">Game-WIN</option>
<option value="12">Game-XBOX</option>
<option value="13">Movie-3D</option>
<option value="26">Movie-4K</option>
<option value="14">Movie-Bluray</option>
<option value="15">Movie-DVDR</option>
<option value="18">Movie-Packs</option>
<option value="16">Movie-x264</option>
<option value="17">Movie-x265</option>
<option value="19">Movie-XVID</option>
<option value="20">TV-HD</option>
<option value="21">TV-SD</option>
<option value="25">TV-Retail-HD</option>
<option value="24">TV-Retail-SD</option>
<option value="23">TV-Packs</option>
<option value="22">TV-x265</option>
<option value="50">xXx-HD</option>
<option value="49">xXx-SD</option>
</select>
<select name=blah>
<option value="0">Title</option>
<option value="1">NFO</option>
<option value="2">Filelist</option>
<option value="3">Title+NFO</option>
</select>
<input type="checkbox" name="incldead" value="1" />include dead&nbsp;&nbsp;
<input type="submit" value="Search!" class="btn" />
</p>
</form>
<br>
<form method="get" action="browse.php">
<tr>
<td style="padding: 1px;padding-left: 10px" align="center">
<select name=incldead>
<option value="0">Active</option>

<option value="2">+10 Seeds</option>
<option value="3">+10 Leeches</option>
</select>
<input type="submit" class=btn value="Go!" />
</div></td></tr>
</table>
<table>
</td></tr></table></form>
<h3>Search results for "I Griffin S18E13"</h3>
<br><h4>Nothing Found!</h4>
<p>Please try again with a refined search string.</p>
</td>
</td></tr></table><br>
<table class=gp_sub_nav align=center width=80% border=0 cellspacing=0 cellpadding=0><tr valign=top>
<td align=center><b>© GimmePeers.com - 2019</b></td>
</tr></table><br>
</body></html>
<p align="center"><font size="2" color="#ffe036"><b>Page generated in 1.28536 seconds.</font></p></br>
```

**Comment by garfield69** [comment]
@cadatoiva  GimmePeers should not be throwing an abend when a query returns no-results. 
we should be trapping `Please try again with a refined search string.` and return no-results found like the other indexer.

**Comment by cadatoiva** [comment]
I don't have access to this tracker, but I'll try to fix it.

**Comment by garfield69** [comment]
@vulcan4d If you can send an invite to cadatoiva -at- yahoo.com this will help enormously.

**Comment by cadatoiva** [comment]
I've got a PR that will resolve this issue out, but this code is in need of a major overhaul for best performance and future compatibility. Once I get that invite, I'll be able to complete those updates.

**Comment by garfield69** [comment]
Jackett 0.14.79

**Comment by vulcan4d** [comment]
> I've got a PR out that will resolve this issue, but this code is in need of a major overhaul for best performance and future compatibility. Once I get that invite, I'll be able to complete those updates.

Invite has been sent to cadatoiva -at- yahoo.com and issue # has been referenced.  Thank you for the great support!

**Comment by vulcan4d** [comment]
Updated to Jackett 0.14.79 and confirmed working!  Thanks again!

**Comment by cadatoiva** [comment]
No problem. I have received your invite and will be overhauling the tracker's code for best performance this week.
