### ISSUE TITLE
[oxtorrent] Exception (oxtorrent): certificate validation failed

### ISSUE THREAD

**Issue by moreje** [Jackett/Jackett#7681]
### Environment

**OS**: Linux/Docker

**Jackett Version**: 0.14.49.0

**Are you using a proxy or VPN?** [yes/no] NO

### Description

Some indexers tests fail with a certificate validation error.
the corresponding websites are reachable in https with no problems

##logs
at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70 Jackett.Common.IndexerException: Exception (oxtorrent): certificate validation failed: [Subject]

 ---> System.Exception: certificate validation failed: [Subject]

   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.ValidateCertificate(HttpRequestMessage request, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 51

   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)

### Screenshots

http://pix.toile-libre.org/?img=1584296597.png

**Comment by cadatoiva** [comment]
Please attach the enhanced logs for this one. https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-turn-on-enhanced-logging
