### ISSUE TITLE
SceneAccess (SCC) Configuration Failed

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#773]
Hey guys! I can't seem to configure SceneAccess. I keep getting an 'Exception in Configure' error. This may be due to the fact that SCC requires the user to enter a pin code to log in, and I do not see that option when I try to log in through Jackett.

**Comment by kaso17** [comment]
For me SCC doesn't require to enter a PIN. Does that happen in you configure a PIN in the profile? Can you disable it again?
#776 fixed a cookie handling issue but it won't be enough if you've to enter a PIN

**Comment by armani316** [comment]
I only needed to choose a PIN when I signed up, but haven't yet needed to enter my PIN to log in, so you're right, that might not be the issue.
 
Just tried configuring it again, and the issue still exists, @kaso17! 

Is there a way I can copy a detailed error log? All I can see is "Exception in Configure"

**Comment by kaso17** [comment]
in the log.txt you'll find more output.
In that case I assume #776 fixed your issue. But there's no new release yet

**Comment by armani316** [comment]
Great! I'll wait for the new release, but in the meantime, here's log output:

2016-12-01 17:44:37.0031 Info Found 0 releases from SceneAccess 
2016-12-01 17:44:37.0067 Error Exception in Configure System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__11.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Configure>d__16.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 190

**Comment by kaso17** [comment]
that one should be fixed with #776
