### ISSUE TITLE
[xtremezone] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by hellcry37** [Jackett/Jackett#7774]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
 Jackett Version 0.14.164.0 but is like this from a few versions

**Last Working Jackett Version**:
dont know

**Are you using a proxy or VPN?** [yes/no]
no
### Description

Simple to reproduce, do the fallowing: 
This tracker needs a cookie for login, this cookie have to be put in settings (press configure button)
put the cookie in, all works OK until you click settings again. As soon as you enter settings under any reason, that cookie is gone. If you open settings for this tracker (I assume this might happen to all of them, not tested) and you don't paste cookie every time you open it, then cookie is forgotten.

### Logged Error Messages

[Make sure you attach the full logs with your personal information removed in case we need more information]
Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 800
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

**Comment by garfield69** [comment]
Team, this yaml indexer has a standard login block for method=form.
But Cardigann recognised that a ReCaptcha was present on the form and re-purposed the indexers' Config panel to display the cookie box and Captcha info.
![image](https://user-images.githubusercontent.com/6933240/77238747-01a85980-6c38-11ea-9811-3ab3ad320648.png)

However this code does not apparently check to see if the local indexers/*.json file has a cookie already saved and load the box, or the above panel does not save the cookie there , I don't know which since I don't have an account there to test.
@cadatoiva  has one, so maybe he can look into this one.

**Comment by asasinuxp** [comment]
I can give invites, but now this tracker has an api, and csrf at login.

**Comment by cadatoiva** [comment]
I already have an account with this one @asasinuxp. Just haven't got around to updating it yet. Thanks for the heads up about the changes to the site.

**Comment by RoloSoze** [comment]
@cadatoiva There is already an open request for the API implementation here https://github.com/Jackett/Jackett/issues/5954

**Comment by ngosang** [comment]
@asasinuxp could you invite me?

**Comment by asasinuxp** [comment]
Yes, I hope the email from your profile is valid

**Comment by ngosang** [comment]
It's

**Comment by asasinuxp** [comment]
Done, if you didn't received any till now, it means the microsoft rejects the emails from us.

**Comment by ngosang** [comment]
I didn't receive anything. Please send me a private email. I will replay with another email account.

**Comment by RoloSoze** [comment]
> 
> 
> I didn't receive anything. Please send me a private email. I will replay with another email account.

I suggest you change the email address in your profile to a Gmail. Hotmail/Outlook/Live do not work well with private trackers at all.

**Comment by ngosang** [comment]
I use that account for another 8 projects. I can't change that so easy...

**Comment by garfield69** [comment]
Jackett 0.16.585

**Comment by hellcry37** [comment]
I don't know how much it counts, but:
Thank you for solving this!
