### ISSUE TITLE
focusx: missing categories

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7777]
Perform empty search.
![image](https://user-images.githubusercontent.com/10577978/77234698-d6c6f280-6bb0-11ea-8918-79b0cf28c8d1.png)

**Comment by ngosang** [comment]
![image](https://user-images.githubusercontent.com/10577978/97791644-e5f53080-1bd4-11eb-82c0-1b40070d5499.png)

**Comment by garfield69** [comment]
already done with 2ce59ef251c2ec51a2eca8cba0b42741fcd33103 about 17 hours ago. Yet to be published.

**Comment by ngosang** [comment]
@ilike2burnthing 

```
ardigannIndexer (focusx): Error while parsing row '
<li id="torrent-517" class="torrentListItem">
	<div class="listBlock torrentCategory">
		<a href="tracker/?category_id=222" title="Траффик">
			<span class="primary">Траффик</span>
		</a>
	</div>
	<div class="listBlock name">
		<div class="titleText">
			<h3 class="title">
				<a href="movie/389/" class="PreviewTooltip" data-previewurl="movie/389/preview">ТРАФФИК | TRAFFIC [DVDRemux]</a>
				<span class="freeleech Tooltip" title="Учитывается только розданный трафик, скаченное полностью игнорируется.">Золото</span>
			</h3>
			<div class="secondRow">
				<div class="postedBy muted">
					<abbr class="DateTime" data-time="1612988195" data-diff="143488" data-datestring="10 фев 2021" data-timestring="23:16">10 фев 2021 в 23:16</abbr>
					by
					<a href="members/1/" class="username author" dir="auto">Devzz</a>
				</div>
			</div>
		</div>
	</div>
	<div class="listBlock download">
		<a href="attachments/517/" title="Скачать">
			<img src="styles/xentorrent/torrent.png" alt="Скачать">
		</a>
		<a href="magnet:?xl=16058692994&amp;xt=urn:btih:421e4fe684f47fef593e708d46137cf9e0889e5e&amp;tr=http://tr0.focusx.co:8192/d27fe46311836a59732019f24bb0bdf2/announce&amp;dn=ТРАФФИК | TRAFFIC [DVDRemux]" title="Скачать">
			<i class="icon icon-magnet" style="font-size:16px;"></i>
		</a>
	</div>
	<div class="listBlock comments">
		0</div>
	<div class="listBlock size">
		15 ГБ</div>
	<div class="listBlock snatched">
		1</div>
	<div class="listBlock seeders strong">
		1</div>
	<div class="listBlock leechers strong">
		0</div>
</li>':

System.Exception: Error while parsing field=category, selector=div.torrentCategory a, value=222: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522
```

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/26cb161bfcf5bf2cca4d14d0b8bc5347431ebbdc

**Comment by ngosang** [comment]
```
CardigannIndexer (focusx): Error while parsing row '
<li id="torrent-537" class="torrentListItem">
	<div class="listBlock torrentCategory">
		<a href="tracker/?category_id=228" title="Айла: Дочь войны">
			<span class="primary">Айла: Дочь войны</span>
		</a>
	</div>
	<div class="listBlock name">
		<div class="titleText">
			<h3 class="title">
				<a href="movie/398/" class="PreviewTooltip" data-previewurl="movie/398/preview">Айла: Дочь войны | Ayla: The Daughter of War [WEB-DL 1080p]</a>
				<span class="freeleech Tooltip" title="Учитывается только розданный трафик, скаченное полностью игнорируется.">Золото</span>
			</h3>
			<div class="secondRow">
				<div class="postedBy muted">
					<abbr class="DateTime" data-time="1616404864" data-diff="9825" data-datestring="22 мар 2021" data-timestring="12:21">22 мар 2021 в 12:21</abbr>
					by
					<a href="members/1/" class="username author" dir="auto">Devzz</a>
				</div>
			</div>
		</div>
	</div>
	<div class="listBlock download">
		<a href="attachments/537/" title="Скачать">
			<img src="styles/xentorrent/torrent.png" alt="Скачать">
		</a>
		<a href="magnet:?xl=8388302898&amp;xt=urn:btih:b5056759ecb24cb37b317bd57111f1ac1af39bf3&amp;tr=http://tr0.focusx.co:8192/d27fe46311836a59732019f24bb0bdf2/announce&amp;dn=Айла: Дочь войны | Ayla: The Daughter of War [WEB-DL 1080p]" title="Скачать">
			<i class="icon icon-magnet" style="font-size:16px;"></i>
		</a>
	</div>
	<div class="listBlock comments">
		0</div>
	<div class="listBlock size">
		7,8 ГБ</div>
	<div class="listBlock snatched">
		0</div>
	<div class="listBlock seeders strong">
		1</div>
	<div class="listBlock leechers strong">
		0</div>
</li>':

System.Exception: Error while parsing field=category, selector=div.torrentCategory a, value=228: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568
```

**Comment by ngosang** [comment]
Empty query
```
System.Exception: Error while parsing field=category, selector=div.torrentCategory a, value=229: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568

CardigannIndexer (focusx): Error while parsing row '
<li id="torrent-541" class="torrentListItem">
	<div class="listBlock torrentCategory">
		<a href="tracker/?category_id=229" title="Танцы с птицами">
			<span class="primary">Танцы с птицами</span>
		</a>
	</div>
	<div class="listBlock name">
		<div class="titleText">
			<h3 class="title">
				<a href="docs/401/" class="PreviewTooltip" data-previewurl="docs/401/preview">Танцы с птицами | Dancing with the Birds [WEBRip 2160p]</a>
				<span class="freeleech Tooltip" title="Учитывается только розданный трафик, скаченное полностью игнорируется.">Золото</span>
			</h3>
			<div class="secondRow">
				<div class="postedBy muted">
					<abbr class="DateTime" data-time="1617882794" data-diff="170042" data-datestring="8 апр 2021" data-timestring="14:53">8 апр 2021 в 14:53</abbr>
					by
					<a href="members/1/" class="username author" dir="auto">Devzz</a>
				</div>
			</div>
		</div>
	</div>
	<div class="listBlock download">
		<a href="attachments/541/" title="Скачать">
			<img src="styles/xentorrent/torrent.png" alt="Скачать">
		</a>
		<a href="magnet:?xl=12278072661&amp;xt=urn:btih:1f1cdc7416e5c64e0342095e4a77b71bb52bf2d4&amp;tr=http://tr0.focusx.co:8192/d27fe46311836a59732019f24bb0bdf2/announce&amp;dn=Танцы с птицами | Dancing with the Birds [WEBRip 2160p]" title="Скачать">
			<i class="icon icon-magnet" style="font-size:16px;"></i>
		</a>
	</div>
	<div class="listBlock comments">
		0</div>
	<div class="listBlock size">
		11,4 ГБ</div>
	<div class="listBlock snatched">
		1</div>
	<div class="listBlock seeders strong">
		1</div>
	<div class="listBlock leechers strong">
		0</div>
</li>':

System.Exception: Error while parsing field=category, selector=div.torrentCategory a, value=229: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568

CardigannIndexer (focusx): Error while parsing row '
<li id="torrent-542" class="torrentListItem">
	<div class="listBlock torrentCategory">
		<a href="tracker/?category_id=230" title="Жизнь в цвете">
			<span class="primary">Жизнь в цвете</span>
		</a>
	</div>
	<div class="listBlock name">
		<div class="titleText">
			<h3 class="title">
				<a href="docs/400/" class="PreviewTooltip" data-previewurl="docs/400/preview">Жизнь в цвете | Life in Colour [WEB-DL 1080p]</a>
				<span class="freeleech Tooltip" title="Учитывается только розданный трафик, скаченное полностью игнорируется.">Золото</span>
			</h3>
			<div class="secondRow">
				<div class="postedBy muted">
					<abbr class="DateTime" data-time="1617883088" data-diff="169748" data-datestring="8 апр 2021" data-timestring="14:58">8 апр 2021 в 14:58</abbr>
					by
					<a href="members/1/" class="username author" dir="auto">Devzz</a>
				</div>
			</div>
		</div>
	</div>
	<div class="listBlock download">
		<a href="attachments/542/" title="Скачать">
			<img src="styles/xentorrent/torrent.png" alt="Скачать">
		</a>
		<a href="magnet:?xl=8190335504&amp;xt=urn:btih:58e3aea9dc4456bb5b87359d83a98680fc379014&amp;tr=http://tr0.focusx.co:8192/d27fe46311836a59732019f24bb0bdf2/announce&amp;dn=Жизнь в цвете | Life in Colour [WEB-DL 1080p]" title="Скачать">
			<i class="icon icon-magnet" style="font-size:16px;"></i>
		</a>
	</div>
	<div class="listBlock comments">
		0</div>
	<div class="listBlock size">
		7,6 ГБ</div>
	<div class="listBlock snatched">
		1</div>
	<div class="listBlock seeders strong">
		1</div>
	<div class="listBlock leechers strong">
		0</div>
</li>':

System.Exception: Error while parsing field=category, selector=div.torrentCategory a, value=230: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568

CardigannIndexer (focusx): Error while parsing row '
<li id="torrent-543" class="torrentListItem">
	<div class="listBlock torrentCategory">
		<a href="tracker/?category_id=230" title="Жизнь в цвете">
			<span class="primary">Жизнь в цвете</span>
		</a>
	</div>
	<div class="listBlock name">
		<div class="titleText">
			<h3 class="title">
				<a href="docs/402/" class="PreviewTooltip" data-previewurl="docs/402/preview">Жизнь в цвете | Life in Colour [WEB-DL 2160p]</a>
				<span class="freeleech Tooltip" title="Учитывается только розданный трафик, скаченное полностью игнорируется.">Золото</span>
			</h3>
			<div class="secondRow">
				<div class="postedBy muted">
					<abbr class="DateTime" data-time="1617883106" data-diff="169730" data-datestring="8 апр 2021" data-timestring="14:58">8 апр 2021 в 14:58</abbr>
					by
					<a href="members/1/" class="username author" dir="auto">Devzz</a>
				</div>
			</div>
		</div>
	</div>
	<div class="listBlock download">
		<a href="attachments/543/" title="Скачать">
			<img src="styles/xentorrent/torrent.png" alt="Скачать">
		</a>
		<a href="magnet:?xl=16569772564&amp;xt=urn:btih:7bf6d89b1dae7ecbfc277d2bb4585ca48c7c0fdd&amp;tr=http://tr0.focusx.co:8192/d27fe46311836a59732019f24bb0bdf2/announce&amp;dn=Жизнь в цвете | Life in Colour [WEB-DL 2160p]" title="Скачать">
			<i class="icon icon-magnet" style="font-size:16px;"></i>
		</a>
	</div>
	<div class="listBlock comments">
		0</div>
	<div class="listBlock size">
		15,4 ГБ</div>
	<div class="listBlock snatched">
		1</div>
	<div class="listBlock seeders strong">
		1</div>
	<div class="listBlock leechers strong">
		0</div>
</li>':

System.Exception: Error while parsing field=category, selector=div.torrentCategory a, value=230: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1568
```
