### ISSUE TITLE
[1337x] Exception (1337x): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by powerxale** [Jackett/Jackett#7808]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Docker 5:19.03.8~3-0~debian-buster

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
n.a.

**.Net Version**:
n.a.

**Jackett Version**:
0.14.136.0

**Last Working Jackett Version**:
Same version

**Are you using a proxy or VPN?** [yes/no]
no

### Description
Added 1337x to list of indexers, but test fails. The error is:

> Exception (1337x): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s).

[List steps to reproduce the error and details on what happens and what you expected to happen]

**Comment by garfield69** [comment]
Please upgrade to v0.14.222 and report if that helps.
Alternatively, try out the configs unblockit link to see if that works.
Report results thanks, since the official domain works for me so I cannot test.
Thanks.

**Comment by Commissar0617** [comment]
Jackett Version 0.14.49.0 also having this. test passes on proxy, but sonarr is saying its still not working


```
  | Jackett.Common.IndexerException: Exception (1337x): Clearance failed after 30 attempt(s). ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).   at CloudflareSolverRe.ClearanceHandler+<SendAsync>d__20.MoveNext () [0x001f9] in <44fc4e0cb3fd4a268a136236a74d835e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <0e06830de9a44394a7e366951eabca52>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <0e06830de9a44394a7e366951eabca52>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <0e06830de9a44394a7e366951eabca52>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <0e06830de9a44394a7e366951eabca52>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <0e06830de9a44394a7e366951eabca52>:0    at System.Net.Http.HttpClient+<SendAsyncWorker>d__47.MoveNext () [0x000ca] in <fc5aee5ea2ce4ebd897e5993f595f74e>:0
-- | --

```

**Comment by garfield69** [comment]
@Commissar0617  please read https://github.com/Jackett/Jackett/issues/7808#issuecomment-602222969

**Comment by Commissar0617** [comment]
right. that's kinda what im trying to point out. the proxies pass, but the main is down for some people because cloudflare sucks sometimes.

**Comment by garfield69** [comment]
Sure, but what I really want to find out is if the problem for you using the 1337x.to domain is fixed with 0.14.222 or not.
We put in a general  fix for another indexer that may also work with 1337x.to for those that are getting a cloudflare challenge, but since I don't get challenged by cloudflare when I use 1337x.to I cannot test if it works so I can close this ticket ;-)
So can someone please update to 0.14.222 and report. Thanks.

**Comment by TheHolyWaffle** [comment]
I'm having the same issue on 0.12.1384.0 (using docker image linuxserver/jackett:latest)

Logs:
```
Jackett.Common.IndexerException: Exception (1337x): Clearance failed after 30 attempt(s).
 ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 241
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/appveyor/projects/jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 165
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 453
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1248
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 823
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/appveyor/projects/jackett/src/Jackett.Common/Services/IndexerManagerService.cs:line 222
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 73
```

**Comment by garfield69** [comment]
@TheHolyWaffle  0.12.1384 should not the latest docker image available. 
according to https://hub.docker.com/r/linuxserver/jackett/tags the latest is v0.14.222-ls47
![image](https://user-images.githubusercontent.com/6933240/77260645-3e368c80-6cee-11ea-8706-01b523ba10c6.png)

maybe something is wrong with the way you are pulling your image?

**Comment by TheHolyWaffle** [comment]
@garfield69 Oh woops, you're right. I've tested with version 0.14.222.0 and now I no longer have this issue.

**Comment by garfield69** [comment]
\o/
