### ISSUE TITLE
[teamhd] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by SuberSeb** [Jackett/Jackett#7819]
Got this error today. TeamHD worked well for months, cookie string is fine. Tracker itself works well, seems like Jackett issue?

```
Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 811
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 972
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 110
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by garfield69** [comment]
- need to know what version of Jackett you were on when you got this error as the code line numbers are depended on knowing which version its is for.
- also, since no team member has an account on this site, we are going to need to see the html that precedes the error so 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

- And lastly, if you have an invite then lets us know, because that will guarantee the fix will be good since we can test for ourselves ;-)

**Comment by SuberSeb** [comment]
Jackett 0.14.222.0, docker image LinuxServer/Jackett. 

Full log: https://pastebin.com/z5QJE1Tz

**Comment by garfield69** [comment]
Hmm. there is nothing in that log that shows when the url is posted and the html is returned.
It does not even have the stack trace you provided in your first post :-(

are you sure you waited for your test to complete and the error to be posted on the screen, before grabbing the log?

perhaps the log was still buffered.
could you take a second look at the log and see if contains more to do with teamhd please?

If necessary could you repeat the exercise once again, perhaps wait a minute more before grabbing the log file.
Thanks.

looking at the cardigann source code and the stack trace in your first post, line 811 and 972 are ant the end of the process of login and test for success, so something is up with that.

one thing you can try for free, is to use the trashbin button to remove your active teamhd config from the dashboard, then add the indexer afresh, paste a fresh cookie and see if that clears the issue.

**Comment by SuberSeb** [comment]
I tried to remove TeamHD but when I want to add it again it fails. Same error as above - Login failed, got redirected. Also I tried to grab new cookie string - same error. This is strange because I don't have any problem to login on the tracker itself from my browser...

New log here, but there no html code: https://pastebin.com/WNN1EwMQ

Can I provide html code manually? What page are you intresting in?

**Comment by garfield69** [comment]
Before we get to that, there are a few things we can eliminate.
Please use your browser to login to the teamhd site, and check that your ratio is good, that you do not have any outstanding alerts, notices or unread mail that could prevent you from accessing the sites torrents search page.
If all good, then access said page, drop the url link from the browser here so I can check against the one the indexer is using. The site might have updated their engine and the indexer could be out of date.
Then follow https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source so we can take a look at the html.
Thanks.

**Comment by SuberSeb** [comment]
I can login to the TeamHD tracker successfully. No any restrictions, ratio is good. 

Login page: https://teamhd.org/login.php
Main page: https://teamhd.org/index.php

[indexphp.txt](https://github.com/Jackett/Jackett/files/4370831/indexphp.txt)

**Comment by garfield69** [comment]
Yeah, nah.
The index.php is the home page.
We need the url to the torrent search page, and corresponding html  ;-)
The page should be at https://teamhd.org/browse

**Comment by SuberSeb** [comment]
[browse.txt](https://github.com/Jackett/Jackett/files/4373448/browse.txt)

**Comment by SuberSeb** [comment]
I also noticed that cookie string now have this: "cross-site-cookie=https://teamhd.org; "

**Comment by garfield69** [comment]
The index and browser pages you provided have given a clue which may solve the issue. I'll load a fix into a pre-release shortly, so you can try it out.

**Comment by garfield69** [comment]
try out Jackett pre-release 0.14.257 and report back. Thanks.

**Comment by SuberSeb** [comment]
Jackett Version 0.14.257.0
Same error - login failed, got redirected.
Error message:
`Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 800
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 969
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70`

**Comment by garfield69** [comment]
Well that is disappointing.
I'm out of ideas so I am going to invade the C# devs to take a look  maybe they will with fresh eyes spot the problem I cant see.

**Comment by Lonli-Lokli** [comment]
@SuberSeb nice to meet you again.

UserAgent has been changed so you should use new string - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" without quotas.

@garfield69 I do not have yml files inside my docker image so cannot force Jackett to use my UserAgen instead of specified in source code. Is it possible to add smth to teamhd.json file which is available? There are some nodes like 
` {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://teamhd.org/"
  },`

**Comment by garfield69** [comment]
unfortunately not. the only vars that get saved to the indexername.json in the ~/.config/Definitions is what ever vars are set in the settings block of the yml source code.
there is a ticket  open for making useragent configurable #7786 

However, a possibility occurs to me but since I don't use docker I do not know if this applies to you.
Restart your docker Jackett and before using any indexers to avoid cluttering the log, view the log in your dashboard and look near the bottom for the 
`MM-dd HH:mm:ss Info Loading Cardigann definitions from: ` message.
These are the paths Jackett will be using to load the indexer yml source definitions.
if any of them are outside of the docker image, in you machine's temp space or user config or what ever is the equivalent on linux, then you can put your custom copy of the indexer there. make sure to give it a unique name, and update the source **site:** name to match the filename, and the **name:** to tell it apart from the official one, and you should be able to then use this source and modify it to your needs. restart jackett and look for the custom name in your add-inderxer page.

**Comment by SuberSeb** [comment]
I have successfully added TeamHD to Jackett. I have installed Firefox docker container and followed this instruction: https://github.com/Jackett/Jackett/issues/6070#issuecomment-545607603. User agent was "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" (thanks @Lonli-Lokli ). Now TeamHD works well.
