### ISSUE TITLE
[torrentday] Your cookie did not work: Parse error (Config)

### ISSUE THREAD

**Issue by Saars1337** [Jackett/Jackett#7875]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows Server 2016

**.Net Runtime**: .Net-Framework

**.Net Version**: 4.8

**Jackett Version**: 0.14.297.0

**Last Working Jackett Version**: First-time install

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

System.Exception: Your cookie did not work: Parse error
   at Jackett.Common.Indexers.TorrentDay.ApplyConfiguration(JToken configJson) in d:\a\1\s\src\Jackett.Common\Indexers\TorrentDay.cs:line 166
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
please update to 0.14.299, as 0.14.297 had a fault we have just this moment fixed.
I cannot be sure this caused your issue, but I would rather eliminate it first before proceeding with other diagnosis.
Then if afterwards, the problem persists, please read https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work
and see if that helps.
Let us know how you go.
Thanks.

**Comment by BradenWentworth** [comment]
229 is still broken

**Comment by Saars1337** [comment]
Seems to work in 0.14.275.0 but not any later

**Comment by Zeppyartaxes** [comment]
Can confirm, still not working.

**Comment by lorenzonunez** [comment]
I can also confirm.

**Comment by maZuFC** [comment]
ive got a slightly different error with torrentday
i have updated to 299.


Jackett Version 0.14.299.0
OS: server 2012R2


`Jackett.Common.IndexerException: Exception (torrentday): The best overloaded method match for 'Jackett.Common.Models.TorznabQuery.MatchQueryStringAND(string, int?, string)' has some invalid arguments
 ---> System.Exception: Parse error
 ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'Jackett.Common.Models.TorznabQuery.MatchQueryStringAND(string, int?, string)' has some invalid arguments
   at CallSite.Target(Closure , CallSite , TorznabQuery , Object )
   at Jackett.Common.Indexers.TorrentDay.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\TorrentDay.cs:line 224
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.TorrentDay.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\TorrentDay.cs:line 258
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 804
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 224
   at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26`

**Comment by tdecorby** [comment]
still having an issue

**Comment by ammace** [comment]
299 broken for me too. 


  | System.Exception: Your cookie did not work: Parse error    at Jackett.Common.Indexers.TorrentDay.ApplyConfiguration(JToken configJson) in d:\a\1\s\src\Jackett.Common\Indexers\TorrentDay.cs:line 166    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
-- | --

**Comment by V3LPO** [comment]
2020-03-27 09:48:10 | Info | Checked for a updated release but none was found. Current: v0.14.299 Latest: v0.14.299
-- | -- | --
2020-03-27 09:48:09 | Info | Jackett variant: CoreWindows
2020-03-27 09:42:18 | Error | System.Exception: Your cookie did not work: Parse error    at Jackett.Common.Indexers.TorrentDay.ApplyConfiguration(JToken configJson) in d:\a\1\s\src\Jackett.Common\Indexers\TorrentDay.cs:line 166    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70

**Comment by zaphod414** [comment]
Also experiencing the same issue running under FreeBSD.  Worked yesterday but not today.  Torrentday is not the only indexer that is affected, either.  About half of my indexers have been non-working since this issue started.

**Comment by V3LPO** [comment]
So is this all due to an update from Jackett?

**Comment by Tuumke** [comment]
For those running the linuxserver.io image, i'm using linuxserver/jackett:v0.14.275-ls58

**Comment by edrock200** [comment]
Thanks Tuumke, using this docker container worked for me as well.

**Comment by ilike2burnthing** [comment]
Anyone tested v0.14.287?

If it works, then it might be as a result of https://github.com/Jackett/Jackett/pull/7342 .

**Comment by digitalirony** [comment]
I am having this same issue with 0.14.299.0
on Ubuntu

**Comment by V3LPO** [comment]
I just reverted to 287 and it's working like normal again.

**Comment by zaphod414** [comment]
How does one revert to a previous version?  I can reinstall 0.12.1486 from the ports tree (FreeBSD), but then how would I choose what version to update that to?  I assume the search for update function in the UI would install the latest version 0.14.299 which would put me back in the same situation again.  How to tell Jackett to specifically install 0.14.287?

**Comment by RoloSoze** [comment]
Exact same issue with 0.14.299

**Comment by V3LPO** [comment]
> 
> 
> How does one revert to a previous version? I can reinstall 0.12.1486 from the ports tree (FreeBSD), but then how would I choose what version to update that to? I assume the search for update function in the UI would install the latest version 0.14.299 which would put me back in the same situation again. How to tell Jackett to specifically install 0.14.287?

I just disabled auto update via Jackett, then I headed over to:

https://github.com/Jackett/Jackett/releases

I just downloaded a new installer and went at it. It kept my settings.

**Comment by cadatoiva** [comment]
In freebsd just use `fetch https://github.com/Jackett/Jackett/releases/download/{release version}/Jackett.Binaries.Mono.tar.gz` and extract the contents of the Jackett directory inside the tarball to `/usr/local/share/jackett` with a `service jackett restart`

Disable your auto-update before stopping the service.

**Comment by zaphod414** [comment]
Didn't know if the generic mono binaries would work for me or not.  Used them to revert to 0.14.287 and I can add my confirmation that version 287 works fine.  Looks like a fix was just pushed that will hopefully correct the issue going forward.

**Comment by cadatoiva** [comment]
@zaphod414 I run mine off a FreeBSD machine as well, and is part of why I joined the dev team to make sure it would still work for us, and make it better because I was having problems myself.

And yes, I found the offending code and the fix should be available in the next update, just wait for @garfield69  to comment in the thread with a version number to know that it has been updated.

**Comment by PureSp1r1t** [comment]
Having same issue, has this been fixed? The issue is closed with no apparent solution

**Comment by garfield69** [comment]
untested fix is now available in Jackett pre-release 0.14.302
please confirm success and I will include the fix in the full release that will get published later at the usual time, in about 10 hours.

**Comment by PureSp1r1t** [comment]
Cookie accepted (done on Firefox) - test successful. Thanks for your fast work :)

**Comment by TehTicTac** [comment]
pre-release 0.14.302 confirmed working for me

**Comment by Saars1337** [comment]
Yep. 0.14.302 works for me now

**Comment by garfield69** [comment]
for those waiting for the stable release , Jackett 0.14.303

**Comment by zaphod414** [comment]
0.14.358 stable installed.  The issue has indeed been resolved.
