### ISSUE TITLE
Unable to configure x264.me

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#793]
It was working fine until a few hours ago. Tried to delete & re-configure the tracker, but it wouldn't even allow me to add it back.

Error log:

2016-12-04 02:36:54.4866 Error Exception in GetConfigForm System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CloudFlareUtilities.ClearanceHandler.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Utils.Clients.HttpWebClient.<Run>d__6.MoveNext() in C:\projects\jackett\src\Jackett\Utils\Clients\HttpWebClient.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Utils.Clients.HttpWebClient.<GetString>d__5.MoveNext() in C:\projects\jackett\src\Jackett\Utils\Clients\HttpWebClient.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.BaseIndexer.<RequestStringWithCookies>d__54.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\BaseIndexer.cs:line 330
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.x264.<GetConfigurationForSetup>d__10.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\x264.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<GetConfigForm>d__15.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 160

**Comment by armani316** [comment]
Working fine now! It wasn't loading the CAPTCHA image before, seems to have resolved itself out.

**Comment by kaso17** [comment]
certificate was renewed today, I guess the old one expired causing this issue. fixed by the x264 admins ;)
