### ISSUE TITLE
firebit: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#7961]
```
Manual search for "beyonce live" on firebit with 2 results.
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D1%84%D0%B8%D0%BB%D1%8C%D0%BC/">Фильмы</a>,
		<a href="/%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/">Музыка</a>,
		<a href="/%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE/">Видео</a>
	</td>
	<td>
		<a href="/16927-blondie-live-by-request-2004-dvd-9">Blondie Live by Request-2004 (DVD-9)</a>
	</td>
	<td class="td-size">5.77 Gb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/DAOS/">DAOS</a>
	</td>
	<td>12.10.2010 18:53:33</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b a, value=Фильмы Музыка Видео: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1586
```

**Comment by ngosang** [comment]
@garfield69 I'm getting this error now:

```
Manual search for "beyonce live" on firebit with 2 results.
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%BD%D0%BE%D0%B2%D0%B8%D0%BD%D0%BA%D0%B8/">Новинки</a>,
		<a href="/%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/">Музыка</a>
	</td>
	<td>
		<a href="/72550-ac-dc-live-at-river-plate-2012-mp3">AC/DC - Live At River Plate (2012) MP3</a>
	</td>
	<td class="td-size">254.58 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/horev/">horev</a>
	</td>
	<td>17.11.2012 06:00:20</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, div.article-indent div b a, value=: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1586
```
