### ISSUE TITLE
[limetorrents] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by xif666** [Jackett/Jackett#7999]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: docker linuxserver/jackett

**.Net Runtime**:

**.Net Version**:

**Jackett Version**: 0.14.384.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
works for me.
its likely you are getting a cloudflare anti-ddos challenge that is preventing results being returned.
to confirm 
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.

(Note: When you restart Jackett the enhanced-log switch will be turned off. This prevents performance hits during normal operations).

Thanks.

**Comment by xif666** [comment]
log.txt



2020-04-03 20:57:47.0552 Debug Connection id "0HLUN8P6CRCF9" accepted.
2020-04-03 20:57:47.0552 Debug Connection id "0HLUN8P6CRCF9" started.
2020-04-03 20:57:47.0560 Info Request starting HTTP/1.0 POST http://********.com/api/v2.0/indexers/limetorrents/test  0
2020-04-03 20:57:47.0560 Debug Request is continuing in applying rules. Current url is http://***********.com/api/v2.0/indexers/limetorrents/test
2020-04-03 20:57:47.0560 Debug Request is continuing in applying rules. Current url is http://*********.com/api/v2.0/indexers/limetorrents/test
2020-04-03 20:57:47.0560 Debug Request is continuing in applying rules. Current url is http://********.com/api/v2.0/indexers/limetorrents/test
2020-04-03 20:57:47.0560 Debug POST requests are not supported
2020-04-03 20:57:47.0560 Debug AuthenticationScheme: Cookies was successfully authenticated.
2020-04-03 20:57:47.0560 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/limetorrents/test'
2020-04-03 20:57:47.0560 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/limetorrents/test'
2020-04-03 20:57:47.0560 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-04-03 20:57:47.0560 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-04-03 20:57:47.0560 Info Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiCon
troller (jackett).
2020-04-03 20:57:47.0560 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2020-04-03 20:57:47.0560 Debug Execution plan of resource filters (in the following order): None
2020-04-03 20:57:47.0560 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCo
re.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2020-04-03 20:57:47.0560 Debug Execution plan of exception filters (in the following order): None
2020-04-03 20:57:47.0560 Debug Execution plan of result filters (in the following order): None
2020-04-03 20:57:47.0560 Info Authorization was successful.
2020-04-03 20:57:47.0560 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2020-04-03 20:57:47.0560 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2020-04-03 20:57:47.0603 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://www.limetor.pro/latest100)
2020-04-03 20:57:47.2237 Debug cf_ob_info=520:57e503f68c13fa70:AMS; path=/; expires=Fri, 03-Apr-20 18:57:58 GMT
2020-04-03 20:57:47.2239 Debug cf_use_ob=443; path=/; expires=Fri, 03-Apr-20 18:57:58 GMT
2020-04-03 20:57:47.2239 Debug WebClient(HttpWebClient2NetCore): Returning 520 => <!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<meta http-equiv="refresh" content="0">

<title>www.limetor.pro | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>




</head>
<body>
<div id="cf-wrapper">



    <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-error-overview">
            <h1>

              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">520</span>
              <small class="heading-ray-id">Ray ID: 57e503f68c13fa70 &bull; 2020-04-03 18:57:28 UTC</small>
            </h1>
            <h2 class="cf-subheadline">Web server is returning an unknown error</h2>
        </div>

        <div class="cf-section cf-highlight cf-status-display">
            <div class="cf-wrapper">
                <div class="cf-columns cols-3">

<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-browser"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">You</span>
  <h3 class="cf-status-name">Browser</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-cloud"></i>
    <i class="cf-icon-status cf-icon-ok"></i>
  </div>
  <span class="cf-status-desc">Amsterdam</span>
  <h3 class="cf-status-name">Cloudflare</h3>
  <span class="cf-status-label">Working</span>
</div>

<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
  <div class="cf-icon-error-container">
    <i class="cf-icon cf-icon-server"></i>
    <i class="cf-icon-status cf-icon-error"></i>
  </div>
  <span class="cf-status-desc">www.limetor.pro</span>
  <h3 class="cf-status-name">Host</h3>
  <span class="cf-status-label">Error</span>
</div>

                </div>

            </div>
        </div>

        <div class="cf-section cf-wrapper">
            <div class="cf-columns two">
                <div class="cf-column">
                    <h2>What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>

                <div class="cf-column">
                    <h2>What can I do?</h2>
                          <h5>If you are a visitor of this website:</h5>
      <p>Please try again in a few minutes.</p>

      <h5>If you are the owner of this website:</h5>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and s
ubmit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520">Additional troubleshooting resources</a>.</p>
                </div>
            </div>

        </div>

        <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">Cloudflare Ray ID: <strong>57e503f68c13fa70</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Your IP</span>: 176.31.249.129</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
</div>


    </div>
</div>
</body>
</html>


2020-04-03 20:57:47.2281 Info Found 0 releases from LimeTorrents
2020-04-03 20:57:47.2281 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 169.8431ms
2020-04-03 20:57:47.2281 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-04-03 20:57:47.2281 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 229
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70 System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 229
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
2020-04-03 20:57:47.2341 Debug The response will be compressed with 'br'.
2020-04-03 20:57:47.2341 Info Request finished in 178.5205ms 500 application/json
2020-04-03 20:57:47.2341 Debug Connection id "0HLUN8P6CRCF9" disconnecting.
2020-04-03 20:57:47.2341 Debug Connection id "0HLUN8P6CRCF9" stopped.
2020-04-03 20:57:47.2341 Debug Connection id "0HLUN8P6CRCF9" sending FIN because: "The Socket transport's send loop completed gracefully."

**Comment by garfield69** [comment]
@xif666  the log provided shows that the SiteLink you are using has a genuine server issue
`www.limetor.pro | 520: Web server is returning an unknown error`

I have tested this SiteLink just now with my Jackett and I don't have a problem, so I suggest you try again.
But it is possible the issue is local to your region so if you continue to have the same error, try using one of the other SiteLinks for limetorrents and see if they work any better.
Let me know how it goes.

**Comment by xif666** [comment]
Now, it is work.
Thanks
