### ISSUE TITLE
ilcorsaronero: got redirected to another domain

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8013]
```
Manual search for "" on ilcorsaronero with 0 results.
Jackett.Common.IndexerException: Exception (ilcorsaronero): Got redirected to another domain. Try changing the indexer URL to https://ilcorsaronero.xyz/. Updated site link, please try again.
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Got redirected to another domain. Try changing the indexer URL to https://ilcorsaronero.xyz/. Updated site link, please try again.
   at Jackett.Common.Indexers.CardigannIndexer.CheckIfLoginIsNeeded(WebClientStringResult Result, IHtmlDocument document) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 838
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1349
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1676
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/kizar/repositories/Jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 224
```

**Comment by garfield69** [comment]
@ilike2burnthing  if you are going to work on a ticket, then remember to assign yourself (near top right on this ticket) so that others know you are working on it, and this prevents duplication of PR. 
And if the ticket is already assigned to someone else, then you know your assistance is not required. ;-)
Thanks.

**Comment by ilike2burnthing** [comment]
Ah, my bad, sorry.

I can't assign myself, or at least can't see how (hope I'm not being completely blind).

![NoAssign](https://user-images.githubusercontent.com/59480337/78417714-ba08d100-762c-11ea-8c65-209789d893f6.png)

**Comment by garfield69** [comment]
check your mail there should be in team invite or something from github

**Comment by ilike2burnthing** [comment]
Thanks! 😃
