### ISSUE TITLE
[torrentday] System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by bradcornford** [Jackett/Jackett#8057]
### Environment

**OS**: Ubuntu 18.04.4 LTS

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]  Mono JIT compiler version 5.18.1.0 

**.Net Version**: 

**Jackett Version**: 0.14.447.0

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** [yes/no] Yes

### Description
Adding TorrentDay indexer throws the error `Request to Jackett server failed` before i receive the indexer configuration screen.

### Logged Error Messages

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.TorrentDay.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentDay.cs:line 135
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
@ngosang  is the Torrentday indexer using the default SiteLink working for you?

**Comment by ngosang** [comment]
All sitelinks are working for me, but I have to enter the cookie. I always get the challenge.

**Comment by bradcornford** [comment]
Thank you for this fix =) I can confirm its working as expected now.
