### ISSUE TITLE
Provider Oxtorrent

### ISSUE THREAD

**Issue by flobafff** [Jackett/Jackett#8064]
### Environment

**OS**: Linux (Synology)

**Jackett Version**: Version 0.14.447.0

### Description

Since the recent updates, no more downloads work from the provider oxtorrent.com

### Logged Error Messages

Jackett log:
2020-04-06 17:02:18 | Error | Error downloading oxtorrent https://www.oxtorrent.com/torrent/8506/westworld-s03e04-vostfr-hdtv
-- | -- | --

Sickchill log:
2020-04-06 17:02:18 INFO     SEARCHQUEUE-MANUAL- :: Request failed: 404 Client Error: Not Found for url: http://127.0.0.1:9117/dl/oxtorrent/?jackett_apikey=**********&path=Q2ZESjhGZHdKcWI2czM1THNvVm80SDd6U0RtYndCMjh6QVktTVNJakFMRnQtSVByVnpWSS1FWkRLdUtXRmNwckR6YzlKeG9oN2dpdlAtT19EUmkyY2J0T3NRUW5BQS1Bd3o0cUpkOVExdUp2eW5jb1p2LUlmMm01M2RhYkxXc0YtdzBWNGhPcV8tUFFHU0RacXU5Y205QWRONUhmM3JNRXFOckxMdzIyWTlVQmJCT2NMMDlEd1FVelcydUpvUTBYSU1Dd3lIZFpzczJMVlNOTTFOUjJqM294X2k0&file=Westworld+S03E04+HDTV+VOSTFR+ (<type 'str'>)
2020-04-06 17:02:18 DEBUG    SEARCHQUEUE-MANUAL- :: Traceback (most recent call last):
  File "/opt/sickchill/sickbeard/search_queue.py", line 186, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/opt/sickchill/sickbeard/search.py", line 111, in snatchEpisode
    if response.next and response.next.url and response.next.url.startswith('magnet'):
AttributeError: 'NoneType' object has no attribute 'next'

Last week, the downloads worked and no changes were made on my side.

Is it possible to investigate?
thank you in advance

**Comment by flobafff** [comment]
Does the manual search and download for OxTorrent work for you in Jackett? No, 
when I do a manual search, I find the desired torrent but to download it, there is a page problem not found (404).



If you downgrade to an earlier version of Jackett does OxTorrent work in SickChill again? If so, what is the latest version that works?
My used version of jackett is the synology version so the downgrade is complicated.


Are any other indexers failing in SickChill?
I don't use other indexers

Can you try adding a new indexer in SickChill and test it?
/

Can you remove and re-add OxTorrent in both Jackett and SickChill and then test?
I tested but it doesn't work



Here are the Sickchill logs:
2020-04-07 10:47:08 INFO     SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Found result Homeland.S08E09.HDTV.VOSTFR at http://192.168.1.60:9117/dl/oxtorrent/?jackett_apikey=**********&path=Q2ZESjhGZHdKcWI2czM1THNvVm80SDd6U0RuR1NhOUh2QnRGbFJqNGNfdGhyU09HSnk1cFE4M0R6bVFEYVhYeE5tLTVid0pOU2o0UnoySndoQUhVdUR3UlJKTzIxN1FVTXkwZlZ4RWJJa2lxUE1JdzdwaDZHSHBnLTJJM0VpUFZfSTJoM3kxWGNCUy1XZzJZcHp5c1JzMGk1OHdpYnZCU2tMQW9ubmRRVlVJUE9kV1pNLUx6dXVJUlQ0bnRDTnVaT3JoN3M4bjI4LVFjandQNHhKd25QY2tBZl9v&file=Homeland+S08E09+HDTV+VOSTFR+
2020-04-07 10:47:08 DEBUG    SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: The highest quality of any match is 720p HDTV
2020-04-07 10:47:08 DEBUG    SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Picking the best result out of [u'Homeland.S08E09.HDTV.VOSTFR']
2020-04-07 10:47:08 INFO     SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Quality of Homeland.S08E09.HDTV.VOSTFR is 720p HDTV
2020-04-07 10:47:08 DEBUG    SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Picked Homeland.S08E09.HDTV.VOSTFR as the best
2020-04-07 10:47:08 DEBUG    SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Checking if we should keep searching after we've found Homeland.S08E09.HDTV.VOSTFR
2020-04-07 10:47:08 INFO     SEARCHQUEUE-MANUAL- :: Downloading Homeland.S08E09.HDTV.VOSTFR from Oxtorrent
2020-04-07 10:47:09 INFO     SEARCHQUEUE-MANUAL- :: Request failed: 404 Client Error: Not Found for url: http://192.168.1.60:9117/dl/oxtorrent/?jackett_apikey=**********&path=Q2ZESjhGZHdKcWI2czM1THNvVm80SDd6U0RuR1NhOUh2QnRGbFJqNGNfdGhyU09HSnk1cFE4M0R6bVFEYVhYeE5tLTVid0pOU2o0UnoySndoQUhVdUR3UlJKTzIxN1FVTXkwZlZ4RWJJa2lxUE1JdzdwaDZHSHBnLTJJM0VpUFZfSTJoM3kxWGNCUy1XZzJZcHp5c1JzMGk1OHdpYnZCU2tMQW9ubmRRVlVJUE9kV1pNLUx6dXVJUlQ0bnRDTnVaT3JoN3M4bjI4LVFjandQNHhKd25QY2tBZl9v&file=Homeland+S08E09+HDTV+VOSTFR+ (<type 'str'>)
2020-04-07 10:47:09 DEBUG    SEARCHQUEUE-MANUAL- :: Traceback (most recent call last):
  File "/opt/sickchill/sickbeard/search_queue.py", line 186, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/opt/sickchill/sickbeard/search.py", line 111, in snatchEpisode
    if response.next and response.next.url and response.next.url.startswith('magnet'):
AttributeError: 'NoneType' object has no attribute 'next'



I think the problem comes from sickchill, I will open an incident on sickchill side.
I close the issue

**Comment by flobafff** [comment]
ok, i just did some tests again, and i realized that by configuring the oxtorrent indexer with the download link magnet it works.

Here is the header of the Jackett log:
2020-04-07 17:05:28 Error
CardigannIndexer (oxtorrent): Download selector a [href * = "{{.Config.downloadlink}}"] didn't match

and here is the code for the download button on the oxtorrent site:

<div class = 'download'> <div class = 'btn-download'> <a href='/telecharger/89FAAC83B8EF528191D06E0A43F350D4F2BE727A'> <img src = '/ themes / default / img / download-btn.png' alt = ' download '> </a> </div>


the class of the html page has to be changed?

**Comment by ngosang** [comment]
@garfield69 ping

**Comment by ilike2burnthing** [comment]
`"/get_torrents/" : ".torrent"` needs to be updated to `"/telecharger/" : ".torrent"`, however that only works for the .com domain, the .co domain and proxies of .co don't have torrents, just magnets.

I'll defer to @garfield69 here.

**Comment by garfield69** [comment]
I will amend the .torrent link and add an info note warning that only the .com site supports it.
