### ISSUE TITLE
[iptorrents] - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by joells101** [Jackett/Jackett#8066]
Environment

OS: Ubuntu 19.10

.Net Runtime: Mono 6.8.0

Jackett Version: 0.14.447.0

Are you using a proxy or VPN? all programs are localhost but yes caddy

Description

In Sonarr, basically when manually searching (might happen when auto too) for a episode, on some series it'll give no results and then the indexer will become unavailable. while other series will give me the results. happens on episodes that were previously grabbed ok as well. 

testing in jackett works fine. restesting in sonarr works fine. 

very similar to this error but it likes like that issue was already resolved?
https://github.com/Jackett/Jackett/issues/7442

Logged Error Messages

[v2.0.0.5344] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: Jackett.Common.IndexerException: Exception (iptorrents): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 195
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.IPTorrents.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/IPTorrents.cs:line 247
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 370
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000ca] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchReleases (System.Func`2[T,TResult] pageableRequestChainSelector, System.Boolean isRecent) [0x000a0] in <4d3cc4e5f7ed4ed2814d83bdaf94809e>:0 

20-4-7 05:26:00.7|Info|DownloadDecisionMaker|No results found

**Comment by garfield69** [comment]
There is not one-solution-fixes-all for an Object reference error.
The error can occur when ever the indexer gets an unexpected result from the iptorrents web site when processing the search results that the web site returned after a query.

In order to amend the indexer to handle your particular issue, we are going to need you to provide the full enhanced log, which will contain the html the site returned when the query was made.
However during this debugging stage, using Sonarr is going to overload the logs a bit, as we really only want to search for the one episode that is causing the error, and not have Sonarr do its usual scan-all-series for torrents and overload the logs with spurious messages.

So if at all possible, find which series and episode Sonarr was looking for when the error occurred,
then set up the enhanced logging, and use the Jackett dashboard search to use the iptorrents indexer to look for the episode.

If you need instructions on setting up the enhanced logging, read https://github.com/Jackett/Jackett/wiki/TroubleShooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by joells101** [comment]
Thank you. I can do this but do I need to do this for each episode or series that fails or would fixing 1 fix the others. My library is very large and from my initial tests there are more failures then successes. This would be a large undertaking and it would appear to be the result of a recent update. Would rolling back resolve my problem?

**Comment by garfield69** [comment]
>do I need to do this for each episode or series that fails

Just one example should be enough.
@ngosang  has an account on IPTorrents, so he can compare your search with his own, and hopefully work out if it is an issue with, for example, different profile style options, or user classes, or just something that was overlooked with adjusting the selectors that fetch results to be processed the last time the indexer was adjusted.

>Would rolling back resolve my problem?

If the dev thinks that rolling back the indexer will solve the issue, he will publish a PR with the rolled back code. 
But first we just need to see what it was in your search that broke the indexer.

**Comment by joells101** [comment]
[log_edited.txt](https://github.com/Jackett/Jackett/files/4443209/log_edited.txt)
I hope i edited out all the sensitive info..
Anyway the search from within jackett seemed to give results. though in the log file i can see the error sonarr gets.

**Comment by jamespoore** [comment]
Hi,

I have the same issue following Jackett updating. See attached logs, same error as OP.
[Jackett.txt](https://github.com/Jackett/Jackett/files/4443641/Jackett.txt)

Searching indexer from Jackett works fine. If you want any other info let me know.
