### ISSUE TITLE
SceneFZ (SCFZ) Configuration Failed 

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#808]
Error log:

2016-12-05 17:26:03.5857 Info Found 0 releases from SceneFZ 
2016-12-05 17:26:03.5857 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__11.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 132
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Test>d__18.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 264

**Comment by kaso17** [comment]
duplicate #350,

I'll need an invite to fix it (kaso1717 -at- gmail.com)

**Comment by kaso17** [comment]
For me it's working with the "Torrent Listing" option set to Complex. With "Old Style" it doesn't. Which one are you using?

**Comment by armani316** [comment]
@kaso17 When Torrent Listing is set to Complex, you can configure it fine, but searching returns no results. When set to Old Style, it can't even be configured in the first place.

**Comment by kaso17** [comment]
Do you prefer the old style? then I can add support for it.
I'll fix the search.

**Comment by armani316** [comment]
@kaso17 I'm fine with either style. I actually do prefer Old Style! Thanks!

**Comment by kaso17** [comment]
it now supports both styles but the publish date is only available with the Complex style.
