### ISSUE TITLE
Update couple indexers, as they stopped working 

### ISSUE THREAD

**Issue by gacpac** [Jackett/Jackett#8099]
Some indexers are not working. I did a little more research going to the website directly and indexers like

Isohunt2
KickAssTorrent (kat.li)

Give fake links starting with  
https://mylink.cx/?url=magnet

### Environment
**OS**: Unix 4.19.107.0 (64bit OS) (linuxserver / docker container)
**Jackett Version**: v0.14.476.0 
**Are you using a proxy or VPN?**  yes

### Logged Error Messages

2020-04-08 17:27:07 | Error | System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 227    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
-- | -- | --
2020-04-08 17:27:07 | Info | Found 0 releases from KickAssTorrent (kat.li)

**Comment by garfield69** [comment]
The KickAssTorrent (kat.li) indexer using the official SiteLink `https://kickass.ws/` works for me.
The indexer has been able to parse the download link with mylink.cx by skipping to the magnet URI for at least 2 years now, with b4f4ed5fe018b268c76f3087e3a71be29e48ebda

What has changed recently was the addition of the proxy with #7818 which was added without checking that the download link worked.
when I use this unofficial proxy I also see the *found no results* you are reporting.
But I think I can amend the indexer to cope with this minor difference.

Isohunt2 has also been able to handle skipping past mylink to the magnet URI for at least 2 years, since2c029f753251ddc02f74873505865b0c5a2da602, and I have tested both the official sitelink *.net and the new proxy from #7818 *.nz and both domains work with the indexer in delivering magnets. 
Are you having an issue with isohunt2 or did you just roll in into this ticket because you spotted the mylink?

**Comment by gacpac** [comment]
Both, 
I started having issues by not getting any search results and before submitting the issue I noticed the mylink.

And I'm getting this as an error when adding the indexer again. 


System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 227    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
--

**Comment by garfield69** [comment]
then please provide the full enhanced log file for a isohunt2 test so I can see the html the site is returning for you.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket if you need instructions.

**Comment by gacpac** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4453348/log.txt)

Here it is. 

The log for today.

**Comment by garfield69** [comment]
Um, no, this is the _regular_ log which is not useful in this case.
Please read https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket to turn on **Enhanced** logging and repeat the test for isohunt2
You will know when you have the right log mode as the log will contain lots of **Debug** tagged entries.
Thanks.

**Comment by gacpac** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4453386/log.txt)

Here

**Comment by garfield69** [comment]
your issue with isohunt2.net is not with the Jackett Indexer, but with the site itself.
when the indexers sends https://isohunt2.net/torrents?ihq=&iht=0&age=0&Torrent_sort=created_at to the site it is returning 
```403 Forbidden
nginx/1.17.9
```

See if you get this using a browser running on the same machine and the same VPN as Jackett and click the above link.

IF so, try the *.nz alternate link, or  look at whether your VPN has options to change their regional server ao that you get an different IP address when accessing the site.

**Comment by gacpac** [comment]
I don't get any of that. I also disconnected Jackett from the VPN and nothing works. 

Ended up moving to the site https://isohunt.nz/ Wasn't aware you can change the site like that.
