### ISSUE TITLE
[yggtorrent] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by TheoBrigitte** [Jackett/Jackett#8110]
### Environment

**OS**: `Ubuntu 18.04.4 LTS`

**.Net Runtime**: .Net-Core

**.Net Version**: ???

**Jackett Version**: `v0.14.485.0`

**Last Working Jackett Version**: n/a

**Are you using a proxy or VPN?** no

I'm running the Jackett via `linuxserver/jackett:latest` docker image
```
$ docker pull linuxserver/jackett:latest
latest: Pulling from linuxserver/jackett
Digest: sha256:c3bb04d084a2712ea4636c5e30cc786847b9ce592ad5114344eb6481796d3a34
Status: Image is up to date for linuxserver/jackett:latest
docker.io/linuxserver/jackett:latest
```

startup log for additional environment info
```
04-09 18:10:48 Info Starting Jackett v0.14.485.0
04-09 18:10:52 Info Environment version: 3.1.3 (/app/Jackett/)
04-09 18:10:52 Info OS version: Unix 4.19.0.8 (64bit OS) (64bit process)
04-09 18:10:52 Info Jackett variant: CoreLinuxAmdx64
04-09 18:10:52 Info File /etc/issue: Ubuntu 18.04.4 LTS \n \l
04-09 18:10:52 Info Running in Docker: Yes
04-09 18:10:52 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
04-09 18:10:52 Info App config/log directory: /config/Jackett
04-09 18:10:52 Info Using Proxy: No
04-09 18:10:52 Info Using HTTP Client: HttpWebClient2NetCore
04-09 18:10:53 Info Loading Cardigann definitions from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
```

### Description

* add YGGtorrent indexer (configured username and password)
* when I click test I get the following error
![image](https://user-images.githubusercontent.com/6536819/78918979-847f4000-7a91-11ea-8caf-a976509cc219.png)

I would expect the test to pass and be green

### Logged Error Messages

Here are logs when I press test
```
04-09 18:13:19 Info CardigannIndexer (yggtorrent): Relogin required
04-09 18:13:20 Info CardigannIndexer (yggtorrent): Relogin required
04-09 18:13:21 Info Found 0 releases from YGGtorrent
04-09 18:13:21 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 227
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 227
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by TheoBrigitte** [comment]
This fixed it https://github.com/Jackett/Jackett/issues/7095#issuecomment-582238746

![image](https://user-images.githubusercontent.com/6536819/78919626-78e04900-7a92-11ea-88ef-d573b72f6be5.png)
