### ISSUE TITLE
(shokweb): the remote certificate is invalid

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8162]
```
Manual search for "" on shokweb with 0 results.
Jackett.Common.IndexerException: Exception (shokweb): The remote certificate is invalid according to the validation procedure.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient.Run(WebRequest webRequest) in /home/kizar/repositories/Jackett/src/Jackett.Common/Utils/Clients/HttpWebClient.cs:line 214
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/kizar/repositories/Jackett/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1335
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/kizar/repositories/Jackett/src/Jackett.Server/Controllers/ResultsController.cs:line 224
```

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/blob/0b264d5a7cdb9fb3395d5c6d37a42905c8e41fba/src/Jackett.Common/Definitions/shokweb.yml#L8-L11

we already have an ignore for the thumbprint of the current certificate 
which implies that something in core has changed, such that the ignore no longer works

**Comment by ilike2burnthing** [comment]
This and uniondht are working in my Docker v0.15.5.0, with and without proxy enabled

**Comment by ngosang** [comment]
We didn't change that part, but I see that it's working with `httpclient2netcore` client and it fails with `httpclient`. Same for #8163
Maybe a bug in `httpclient`?

**Comment by ilike2burnthing** [comment]
I know it's nearly a year old now, but is Ghost's comment here relevant at all? https://github.com/Jackett/Jackett/issues/5172#issuecomment-489298804

**Comment by garfield69** [comment]
yes that us relevant thank you. I'd forgotten all about that.

so this is a know issue and the solve was to upgrade to net core ;-)

**Comment by ilike2burnthing** [comment]
Yea, just gone back through random v0.14, 13, and 12 releases - httpclient fails, netcore works

**Comment by cadatoiva** [comment]
If someone running mono needs a fix for this, for now they can add`--UseClient httpclient2netcore` or `-c httpclient2netcore` to their command line switches. The netcore clients are actually fully compatible with all supported versions of Mono, funnily enough, which is what the web-client feature branch is all about.
