### ISSUE TITLE
TD not working

### ISSUE THREAD

**Issue by cadatoiva** [Jackett/Jackett#8203]
> > Hello,
> > I would love to help test as I am not a coder.
> 
> Thank you. If you see an open issue related to a tracker of which you are a member, you can help by checking to see if you're facing the same problem, or test the changes to see if they work.
> 
> > I cannot seem to get anything related to TD working with sonarr?
> > Does anyone have suggestions? Can't get jackett working cant get RSS working.
> 
> For this you'd need to open a new issue and detail what the exact problem is. Make sure you provide the requested details.

For sure. I have been tinkering some more today to see why jackett cannot add TD an an indexer 
From the log file all I can make out is that the website it is trying to access to add the tracker is DDoS protected therefore times out, and jacket cannot do anything about that challenge. I could be wrong though

I have also had no luck attaching TD RSS to Sonar to download as well. Sucks I have to use public trackers when TD is so awesome!

**LOG <adding TD indexer>**

CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in d:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 438
   at Jackett.Common.Indexers.TorrentDay.GetConfigurationForSetup() in d:\a\1\s\src\Jackett.Common\Indexers\TorrentDay.cs:line 123
   at Jackett.Server.Controllers.IndexerApiController.Config() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

_Originally posted by @bombz88 in https://github.com/Jackett/Jackett/issues/8180#issuecomment-613803012_

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/6676#issuecomment-613804610

**Comment by garfield69** [comment]
OP is using 6676.
