### ISSUE TITLE
[yggtorrent] Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by zorglan** [Jackett/Jackett#8205]
#7704 # Environment 

**OS**: Seedbox

**.Net Runtime**: .Net-Core

**.Net Version**:

**Jackett Version**:Version 0.16.7.0

### Logged Error Messages

When i test, i received this error message

Exception in GetConfigurationForSetup (yggtorrent): CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 880
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 859

**Comment by garfield69** [comment]
You are in a pickle.
The IP address of your seedbox has been blacklisted by couldflare.
B
ecause you are on a seedbox it is unlikely you have access to a browser that you can run from the seedbox machine, and therefore you cannot use YGGCookie which is a alternate indexer that relies on you using the browser to manually solve the cloudflare challenge and then grab the cookie to use with the yggcookie indexer.

So unless you can load a VPN or a proxy on your seedbox so that you can access yggtorrent via a different IP address that is not on the cloudflare blacklist, then you are stuck, and there is nothing Jackett can do about it. Sorry.
