### ISSUE TITLE
[yggcookie] Exception (yggcookie): Clearance failed after 30 attempt(s).: Clearance failed after 30 attempt(s). (Test)

### ISSUE THREAD

**Issue by pinedours** [Jackett/Jackett#8223]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

Dedicated Server on Ubuntu with some apps like Sonarr, Radarr etc and Jackett

**Jackett Version**: 0.16.23.0

**Are you using a proxy or VPN?** NO

### Description

I know to have the correct cookie we have to grab it from the same ip than Jackett.. 
So, first I tried to do a proxy tunnel via ssh through my server, and impossible to have internet correctly. When I try to go on google or yggtorrent.se or other websites I want to go I ve that message on firefox :"PR_CONNECT_RESET_ERROR" 
I followed this guide : https://www.math.ucla.edu/computing/kb/creating-ssh-proxy-tunnel-putty
That is strange because when I go to http://www.whatsmyip.org/ to see my ip is the server and not my home box, it s ok the website is up. 
Maybe a bad config on my server, I m too noob to setup that correctly alone.. 

So I tried a 2nd solution : install a docker image of Firefox to have directly internet from my server.
It was ok, connection to Yggtorrent was ok !! I grabbed a cookie and the user agent !! but.....same error again 'Clearance failed after 30 attempt(s).'

Can I be banned ? But.. I suppose no if I can connect to the website with the firefox docker version from my server... or I m wrong ? 

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (yggcookie): Clearance failed after 30 attempt(s).
 ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1335
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by pinedours** [comment]
Sorry to re open.. but I dont understand where is the problem.. Normally if I understood everything my cookie is good but here no... Where I m wrong ?

**Comment by tchirou** [comment]
Hi
I have the same problem
Did you resolve it one way or the other ?
I am afraid my server ip triggers the cloud flare recaptcha challenge

**Comment by pinedours** [comment]
Nothing for the moment ... :/

**Comment by tchirou** [comment]
The Jackett from my home nas can still scrape as usual but the one from my foreign server must go through the recaptcha challenge despite the cookie and user agent
Is yours from your home ?

**Comment by akatimike** [comment]
I got the same issue with my server cloudflare block all request but i never try to connecte via ssh to get right cookie thx @pinedours Will try this

**Comment by pinedours** [comment]
@tchirou No, not at my place, foreign too.. The cookie was grab from my foreign server, so normally this is the good.. Dont know whats the problem. Help me if you find ...!!! 

@akatimike if you find the problem, help us !! 

Sorry for my english, I suppose you are both french too ? (if you go on ygg)

**Comment by tchirou** [comment]
Moi aussi j’ai récupéré le cookie via ssh mais ça ne marche pas
Je pense que cloudflare sait que ces ip appartiennent à des fermes de serveur et exige le challenge avec le recaptcha pour éviter les attaques ddos. Pour récupérer le cookie, j’ai du réussir le recaptcha avec le navigateur. Ce que Jackett ne peut pas faire.
Soit il faut espérer que ygg abandonne le challenge cloudflare dans quelque temps (ce qui me semble peu probable), soit il faut essayer un autre serveur avec une autre ip.

Perso, j’ai contourné le problème en pointant sonarr et radarr de mon serveur à l’étranger vers le jackett de mon nas chez moi. 
Ça vaut peut être le coup de mettre un raspberry chez vous avec seulement jackett pour faire la même chose. Plus simple que d’aller essayer des serveurs ailleurs et tout réinstaller en espérant qu’il n’y ait pas le même problème dans 2 semaines.

**Comment by garfield69** [comment]
The preferred language on this Jackett support site is English.
If you feel the need to use another language, ok, fine, but please also provide an English version as well.
I do not want to have to rely on Google translate in order to support request to fix indexers.
Thanks.

**Comment by tchirou** [comment]
I was saying that I got the cookie toi through ssh but no luck.
Cloudflare requires the challenge despite the cookie
I don’t see a workaround unless the tracker stops using cloudflare (not likely) or trying with another server with another ip 
My personal solution is to point sonarr and radarr to the jackett on my home nas which has no issues at all with the tracker, surely because I also use the tracker normally with a browser and cloudflare must have whitelisted my ip 
And I suggest to others to do the same with a raspberry If they don’t have a nas and install jackett on it. It will be more reliable than to reinstall another server elsewhere hoping that the same problem won’t happen in a few days/weeks, chased out by cloudflare

**Comment by pinedours** [comment]
Hope too that yggtorent cancel that choice.. I don't know other good sources in France. 
@tchirou I don't know how to point my foreign radarr/sonarr to a local jackett. Could you maybe help me and speak about that ?
I let you my discord : Pinedours#9783

Of course if someone find a solution let us know!

**Comment by garfield69** [comment]
Regardless of the outcomes from your discussions, there is nothing Jackett can do for you so I am closing this ticket.

**Comment by tchirou** [comment]
> Hope too that yggtorent cancel that choice.. I don't know other good sources in France.
> @tchirou I don't know how to point my foreign radarr/sonarr to a local jackett. Could you maybe help me and speak about that ?
> I let you my discord : Pinedours#9783
> 
> Of course if someone find a solution let us know!

I added you on discord
