### ISSUE TITLE
[yggtorrent] Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by lamplis** [Jackett/Jackett#8240]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: DSM6 synology DS1515

**.Net Runtime**: can't get it from evoseedbox.com

**.Net Version**: can't get it from evoseedbox.com

**Jackett Version**: 0.16.34.0 

**Last Working Jackett Version**: previous

**Are you using a proxy or VPN?**: no

### Description

Adding ygg torrent fails :
> An error occurred while updating this indexer
> Clearance failed after 30 attempt(s).

### Logged Error Messages

```
CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 901
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 573
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 997
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
While YGGTorrent have their Cloudflare anti-DDoS challenge in place the Jackett YGGTorrent indexer will not work.
See [this wiki](https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-30-attempts) for more details.
Until YGGTorrent lift the blacklist, you could try using the **YGGCookie**, which is an alternate method of accessing the YGGTorrent web site and may work for you.
Follow the YGGCookie config panel to fetch the cookie and user-agent and try it out.

Note: the browser you use to fetch the cookie has to be running on the same machine that is running Jackett, and also, users of VPN/proxy report that this method does not work for them.  
If you cannot get YGGCokkie to work then I am sorry but there is nothing more Jackett can do for you.

**Comment by lamplis** [comment]
Thank you, the cookie method works perfectly thanks !

**Comment by ulysserevient** [comment]
Hi, sorry for reopen this thread, but after long search i don't find any solution.

Is there a way to use YGGCookie method from a docker on a linux computer without graphical console ?
Thx.

**Comment by cadatoiva** [comment]
Yes, see the notes in this section for how to open an SSH proxy tunnel to get the appropriate cookie https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

**Comment by lamplis** [comment]
The issue has reappear, the cookie method doesn't work anymore using  Jackett Version 0.16.438.0

**Comment by garfield69** [comment]
follow #8635 for progress on this issue.
