### ISSUE TITLE
[filelist] Error calling provider filelist: Clearance failed after 30 attempt(s). (Config)

### ISSUE THREAD

**Issue by hellcry37** [Jackett/Jackett#8259]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
0.16.59.0

**Last Working Jackett Version**:
at least last 2 versions i know they did not work

**Are you using a proxy or VPN?** [yes/no]
no

### Description
[List steps to reproduce the error and details on what happens and what you expected to happen]
When I've tried to login i get this error:
Error calling provider filelist: Clearance failed after 30 attempt(s). I can login just fine on website, i know they do some changes and migrations from .ro to .io tld domain.

### Logged Error Messages
[Place any relevant error messages you noticed from the logs here.]

System.Exception: Error calling provider filelist
 ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
   at Jackett.Common.Indexers.FileList.CallProviderAsync(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/FileList.cs:line 187
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.FileList.CallProviderAsync(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/FileList.cs:line 192
   at Jackett.Common.Indexers.FileList.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/FileList.cs:line 82
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
If you can accessed the site with a browser running on the same machine that is running Jackett, you must have noticed the Cloudflare anti-DDoS challenge at some point while accessing the site.

Read https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-30-attempts which details the issue that Jackett has with this challenge, and possible circumventions you can try.

**Comment by cadatoiva** [comment]
FileList's Jackett integration was updated a couple of days ago to use the API. If you have version 0.16.54 or newer, you'll need to reconfigure FileList in Jackett using your 'Passkey' instead of your password, which you can get from your FL profile settings page: https://filelist.io/my.php

**Comment by hellcry37** [comment]
@cadatoiva now that's very good information, ofc it worked, this happens when ppl want to help. Thank you
@garfield69 since i could login on the web without problems and I did mention that, no I did not see any Cloudflare anti-DDoS challenges. Thanks anyway.
