### ISSUE TITLE
[polishsource] Exception (polishsource): Relogin failed: Parse error (Test)

### ISSUE THREAD

**Issue by sevospl** [Jackett/Jackett#8288]
### Environment

**OS**:

**.Net Runtime**: LinuxServer Docker image

**.Net Version**: ^

**Jackett Version**: 0.16.71.0

**Last Working Jackett Version**: 0.16.71.0

**Are you using a proxy or VPN?** Nope

### Description

1. Once I'm logged in this tracker works for a while just fine.
2. After a few seconds/minutes/hours (pretty randomly) it stopps working out of nowhere.
3. I have to log in again manually and fill a CAPTCHA.

### Logged Error Messages

```
Apr 20, 2020 08:22:34 PM	Error	
Jackett.Common.IndexerException: Exception (polishsource): Relogin failed
 ---> System.Exception: Parse error
 ---> System.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1361
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 826
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1684
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 803
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```
and

```
### Error on 20200420192311 for PolishSource.txtJackett.Common.ExceptionWithConfigData: Error: Error!

Captcha error, przepisz uważnie!
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebClientStringResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 473
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 730
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1359





<!DOCTYPE html>
<html>
	<head>
		<title>#PolishSource.cz</title>
		<LINK REL="SHORTCUT ICON" href="pic/faviicon.png">
		<link rel="apple-touch-icon" href="pic/apple/apple-touch-icon.png">
		<link rel="apple-touch-icon-precomposed" href="pic/apple/apple-touch-icon-precomposed.png">
		<link rel="apple-touch-icon" sizes="120x120" href="pic/apple/apple-touch-icon-120x120.png">
		<link rel="apple-touch-icon-precomposed" sizes="120x120" href="pic/apple/apple-touch-icon-120x120-precomposed.png">

			<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
			<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
			<META NAME="DESCRIPTION" CONTENT="#PoliShsource #PolishSource.cz #PS.cz #PSiG @PolishSource1 #irc.polishsource.cz">

		<link rel="stylesheet" href="assets/bs/bootstrap-combined.min.css">
		<link rel="stylesheet" href="assets/bs/font-avesome/css/font-awesome.css">
		<link rel="stylesheet" href="assets/bs/mod_by_wizjon_from_bs_3.0.css">

			<script src="assets/bs/jquery-latest.js"></script>
			<script src="assets/bs/bootstrap.min.js"></script>
			<script src="assets/bs/paginator/src/bootstrap-paginator.js"></script>
			<iframe id="iframe" sandbox="allow-same-origin" style="display: none"></iframe>
			<script type="text/javascript" src="assets/js/signupch.js"></script>

		<style type="text/css">
			body {
				margin-top: 0px;
				background: #004E98;
				background-image: url("https://tech.polishsource.cz/pic/bcg/2.jpg");
				font-family: "tahoma", "arial", "helvetica", "sans-serif";
				font-size: 8pt;
			     }
		</style>
</head>
<body>

<center>
<img src="/pic/logo/logo_transparent.png">
<br><br>
<div class="btn-group">
<a href="javascript:history.back();" class="btn btn-danger span2"><i class="icon-backward icon-small"> </i>Back / Wróć</a>
<a href="login.php" class="btn btn-success span2"><i class="icon-user icon-small"> </i>Login / Zaloguj</a>
<a href="cmon.php" class="btn btn-info span2"><i class="icon-plus icon-small"> </i>Register / Rejestracja</a>
</div>
<br><br><br>
<a href="https://twitter.com/PolishSource1"><img src="pic/twitnologin.png" border="0" alt="Twitter"></a>
</center>
</body>
</html>
```

**Comment by sevospl** [comment]
When testing (by pressing a "Test" button) I get this error:

```
An error occurred while testing this indexer
Exception (polishsource): Login failed: No form found on https://polishsource.cz/login.php using form selector form[action="takelogin.php"]: Parse error
```

Logs:

```
Jackett.Common.IndexerException: Exception (polishsource): Login failed: No form found on https://polishsource.cz/login.php using form selector form[action="takelogin.php"]  ---> System.Exception: Parse error  ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://polishsource.cz/login.php using form selector form[action="takelogin.php"]    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 568    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1359    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 826    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1684    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 803    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
--
```

https://github.com/Jackett/Jackett/wiki/TroubleShooting#login-failed-no-form-found-on-url - I followed the instructions from there but it didn't help much :(

**Comment by garfield69** [comment]
@cadatoiva  @ngosang  do either of you suffer this?
I do not have an account (mine was disabled for not meeting the trial goals ;-D )

**Comment by sevospl** [comment]
> @cadatoiva @ngosang do either of you suffer this?
> I do not have an account (mine was disabled for not meeting the trial goals ;-D )

So there are I believe 2 ways:
1. I can get you an invite (it's pretty cheap anyways)
or
2. We could use something like Team Viewer or AnyDesk (which is something I'd prefer).

**Comment by cadatoiva** [comment]
Looks like the account is being logged out and can't log back in because the tracker always has a captcha on the login screen. I can't tell why, but that means that they have to manually log back in each time.

**Comment by sevospl** [comment]
I never got logged out in the browser on my PC though. Both my browser and Jackett are using the same IP since my server is at home (RPi).

**Comment by ngosang** [comment]
It's working for me. I removed the tracker and re-added it. In the configuration form you have to complete the image captcha but I can't see coudflare or something related.

**Comment by RoloSoze** [comment]
It's working fine for me, too.

**Comment by cadatoiva** [comment]
Just finished working with @sevospl via discord and it appears to be all worked out. Problems with site admins, sonarr and radarr. No changes needed to Jackett. Closing this issue.

**Comment by chaostheory22** [comment]
I'm getting error related to this also, every few hours. Found this topic, because I was looking for solution.

Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://polishsource.cz/login.php using form selector form[action="takelogin.php"]

**Comment by sevospl** [comment]
> On the other hand (I think this proves something): PolishTracker which is similar private torrent site - logs out of browser automatically every hours or so, but Jackett somehow is still logged in and actively searching there, even after few days since I logged in.

PolishTracker uses a completely different engine, it's not similar to PolishSource. However, that's correct, I have never got logged out in the browser, only Jackett.

It's a hit or miss, sometimes it's quite stable and can be running even for a day or two, but then all of a sudden it starts going crazy. I kinda got used to it - I just manually relog in from time to time.
