### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Input string was not in a correct format.: Input string was not in a correct format. (Test)

### ISSUE THREAD

**Issue by xelacat** [Jackett/Jackett#8296]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: NAS Asustor Linux env

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.13.483.0

**Last Working Jackett Version**: 0.13.483.0

**Are you using a proxy or VPN?** [yes/no] no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

Jackett.Common.IndexerException: Exception (yggtorrent): Input string was not in a correct format.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at CloudflareSolverRe.Types.Javascript.JsFuck.DecodeNumber(String encodedNumber)
   at CloudflareSolverRe.Types.Javascript.JsCalculation.Solve()
   at CloudflareSolverRe.Types.Javascript.CfdnCalculation.Solve()
   at CloudflareSolverRe.Types.Javascript.CfdnCalculation.get_Result()
   at CloudflareSolverRe.Types.Javascript.JsChallenge.ApplyCalculation(Double number, IJsCalculation calculation)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at CloudflareSolverRe.Types.Javascript.JsChallenge.Solve()
   at CloudflareSolverRe.Solvers.JsChallengeSolver.SolveChallenge(String html)
   at CloudflareSolverRe.Solvers.JsChallengeSolver.Solve()
   at CloudflareSolverRe.CloudflareSolver.SolveJavascriptChallenge(Nullable`1 jsDetectResult)
   at CloudflareSolverRe.CloudflareSolver.SolveWithJavascript(Int32 tries)
   at CloudflareSolverRe.CloudflareSolver.Solve()
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, CloudflareHandler cloudflareHandler, Uri siteUrl, CancellationToken cancellationToken)
   at CloudflareSolverRe.CloudflareSolver.<>c__DisplayClass30_0.<<Solve>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at CloudflareSolverRe.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at CloudflareSolverRe.CloudflareSolver.Solve(HttpClient httpClient, HttpClientHandler httpClientHandler, Uri siteUrl, CancellationToken cancellationToken, Boolean randomUserAgent)
   at CloudflareSolverRe.ClearanceHandler.GetClearance(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 240
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 442
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1321
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 807
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 220
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

**Comment by garfield69** [comment]
While YGGTorrent have your IP blacklisted you will not be able to use the Jackett YGGTorrent Indexer.
read #8056 for details.
But until Cloudflare list the blacklist, you may be able to use the YGGCookie indexer, which is an alternate means to access the YGGTorrent website.

But first you need to update your Jackett 0.13.483 to 0.16.96 
Then add YGGCookie from the add-indexer page using the wrench and follow the config panel instructions.
Good luck.

**Comment by xelacat** [comment]
Ok thanks Garfield69, but but how can I update my version on this NAS ?

**Comment by garfield69** [comment]
where did you get the Jackett that you are running on now?

**Comment by xelacat** [comment]
> where did you get the Jackett that you are running on now?

On the Asustor Store, think it's a docker version

**Comment by ilike2burnthing** [comment]
Asustor's App Central is massively behind.

If you haven't already, install Portainer from App Central. Open Portainer, go to Containers, Jackett, Recreate, select Pull latest image, and then Recreate.

You can use Watchtower to automate the process from now on - https://hub.docker.com/r/containrrr/watchtower

**Comment by garfield69** [comment]
>If you haven't already, install Portainer from App Central. Open Portainer, go to Containers, Jackett, Recreate, select Pull latest image, and then Recreate.

Which should at least allow you to keep Jackett up to date.
But a complication I did not factor in when I posted the first time was that you are on a NAS which typically is a headless server, without the ability to run a browser. Am I correct?

In which case you are going to find it difficult to fetch the cookie and user-agent to fill in the YGGCookie config.

There was something in a ticket a while ago about using a secure terminal or something, as an alternate method to get this data, I'll try to find the post.

**Comment by garfield69** [comment]
Yes, here we are.
So if you cannot run a browser in the NAS then see the notes in this section for how to open an SSH proxy tunnel to get the appropriate cookie https://github.com/Jackett/Jackett/wiki/TroubleShooting#your-cookie-did-not-work

**Comment by xelacat** [comment]
Thanks a lot,
Resolve with uninstall and reinstall with update version (Mono)

I couldn't do it any other way, even through Portainer.
