### ISSUE TITLE
TorrentDay Support

### ISSUE THREAD

**Issue by soprono** [Jackett/Jackett#832]
Hey, 

Recently started getting this error with TD: 

`Test failed for torrentday: Exception of type 'Jackett.AuthenticationException' was thrown` 

I see the support has also been moved for it will this be forever now or is something in the work to be fixed please? This was my most dependent tracker. 

`Unhandled exception: Message = Exception of type 'Jackett.AuthenticationException' was thrown.
Data = System.Collections.ListDictionaryInternal
InnerException = 
TargetSite = Void MoveNext()
StackTrace =    at Jackett.Indexers.TorrentDay.<PerformQuery>d__15.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\TorrentDay.cs:line 199
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.TorznabController.<Call>d__5.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\TorznabController.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<ExecuteAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
HelpLink = 
Source = Jackett
HResult = -2146233088`

**Comment by kaso17** [comment]
it's working fine for me, it looks like your cookies are invalid, try reconfiguring the indexer.

**Comment by soprono** [comment]
Hey Kaso17 tried that already to, very strange issue and doing the same even after removing it and restarting jackett.

**Comment by kaso17** [comment]
Jackett.AuthenticationException is thrown only if the search query returns a redirect (meaning the cookies are invalid)
Please send me a log with the -t option enabled showing the reconfigure+search.

**Comment by vertig0ne** [comment]
12-11 04:19:52 Debug IWebClient.GetString(Url:https://torrentday.it/browse.php) 
12-11 04:19:59 Debug IWebClient: Returning MovedPermanently =>  
 would be the lines in question, unfortunately it does not say where it's moved to

**Comment by kaso17** [comment]
looks like they got their domains blocked again, the redirecting breaks jackett.
Try v0.7.791 it contains fixes to make it more robust and better error messages.

**Comment by maZuFC** [comment]
still having problems with torrentday.it 

im running Jackett Version 0.7.797.0


is this something that TD have to resolve?

**Comment by soprono** [comment]
Did you try add and remove it maZuFC? It worked for me after a few tries and restarting of Jacett and Sonarr in my case.

**Comment by maZuFC** [comment]
sorry not sure what you mean by remove.... removing jackett or clearing cookies?

**Comment by kaso17** [comment]
@maZuFC: if .com is blocked for you, you probably need at least v0.7.806 which uses .it by default again.

**Comment by maZuFC** [comment]
ok cool... how do i force an update on jackett?

i clicked on update but it did not find anything...

**Comment by maZuFC** [comment]
thanks for the update... its working again


cheers

**Comment by soprono** [comment]
Thanks Guys, I also had inserted a alternative URL in my settings too. Seems like its sorted the issue. Closing the ticket, thanks @kaso17
