### ISSUE TITLE
Indexers that require frequent reconfiguration - AlphaReign, PreToMe, House-of-Torrents

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#834]
Even if all 3 pass my 'Test Al' trial, I find myself having to reconfigure them a few hours later. For AlphaReign & PreToMe, reconfiguration from within Jackett does the trick, With House-of-Torrents, I have to access the website, login again from there, and reconfigure the tracker in Jackett. For all 3, reconfiguration has to be done very frequently. 

I had this problem in the past with other trackers (e.g. x264), and I found that decreasing the level of login / browsing security in my Profile settings / User CP generally takes care of this problem. This doesn't work with these 3.

**Comment by kaso17** [comment]
With a static IP I've no problem with these but I've added automatic re-logins with c40c176b720d53adf6e393d26134970d202eb105 / 55f2951694411f36d72b5f12fc1d0ee0be1ae92b / 5b641a5efc01740d7ec10874153b3734a1129938

**Comment by armani316** [comment]
This also seems to have been fixed by v0.7.791! Thank you. I'll report back if there are any issues!

**Comment by armani316** [comment]
Update: @kaso17 The problem has been resolved for PTM, but not for AR & HOT.

**Comment by kaso17** [comment]
Please send me the logs showing the failed tests/searches (with -t enabled)

**Comment by armani316** [comment]
@kaso17 Here's the log for House of Torrents. I'll post the log for AlphaReign the next time it needs to be reconfigured: 

2016-12-12 23:29:49.8283 Info   http://127.0.0.1:9117/Admin/test_indexer 
2016-12-12 23:29:49.8283 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2016-12-12 23:29:49.8440 Info DefaultHttpControllerSelector SelectController Admin 
2016-12-12 23:29:49.8440 Info HttpControllerDescriptor CreateController  
2016-12-12 23:29:49.8440 Info DefaultHttpControllerActivator Create  
2016-12-12 23:29:49.8440 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2016-12-12 23:29:49.8440 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2016-12-12 23:29:49.8440 Info AdminController ExecuteAsync  
2016-12-12 23:29:49.8616 Info ApiControllerActionSelector SelectAction  
2016-12-12 23:29:49.8616 Info ApiControllerActionSelector SelectAction Selected action 'Test()' 
2016-12-12 23:29:49.8616 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-12-12 23:29:49.8616 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-12-12 23:29:49.8772 Info HttpActionBinding ExecuteBindingAsync  
2016-12-12 23:29:49.8772 Info HttpActionBinding ExecuteBindingAsync  
2016-12-12 23:29:49.8772 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()' 
2016-12-12 23:29:49.9241 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2016-12-12 23:29:49.9407 Info ApiControllerActionInvoker InvokeActionAsync Action='Test()' 
2016-12-12 23:29:49.9462 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()' 
2016-12-12 23:29:49.9462 Debug IWebClient.GetString(Url:https://houseoftorrents.me/browse.php?searchin=title&incldead=1) 
2016-12-12 23:29:50.4801 Debug IWebClient: Returning Redirect => https://houseoftorrents.me/login.php?returnto=%2Fbrowse.php%3Fsearchin%3Dtitle%26incldead%3D1  
2016-12-12 23:29:50.4957 Debug IWebClient.GetString(Url:https://houseoftorrents.me/simpleCaptcha.php?numImages=1) 
2016-12-12 23:29:50.8964 Debug IWebClient: Returning OK => {"text":"clock","images":[{"hash":"1993023f28696d08b9003a9b52aa60488be105f5","file":"captchaImages\/15.png"}]} 
2016-12-12 23:29:50.8964 Debug IWebClient.GetString(Url:https://houseoftorrents.me/takelogin.php) 
2016-12-12 23:29:51.5117 Debug IWebClient: Returning OK => <br />
<b>Notice</b>:  Undefined index: simpleCaptchaAnswer in <b>/var/www/html/takelogin.php</b> on line <b>17</b><br />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<meta name='generator' content='Bitleechers.net' />
<meta name='viewport' content='width=device-width, initial-scale=1' />
<meta http-equiv='Content-Type' content='text/html;charset=UTF-8' />
<meta http-equiv='Content-Language' content='en-us' />

<title>House-Of-Torrents</title>
<link rel='alternate' type='application/rss+xml' title='Latest Torrents' href='./rss.php?passkey=' />
<link rel='stylesheet' href='templates/10/10.css' type='text/css' />
<link type='image/x-icon' rel='shortcut icon' href='/pic/favicon2.ico' />
<script type='text/javascript' src='./image-resize/jquery.js'></script>
<script type='text/javascript' src='./image-resize/core-resize.js'></script>
<script type='text/javascript'>
/*<![CDATA[*/
function radio() {
window.open('radio_popup.php','My Radio','height=700,width=800,resizable=no,scrollbars=no,toolbar=no,menubar=no');
}
/*]]>*/
</script>




</head>

<body>
<table width='100%' cellspacing='0' cellpadding='0' style='background: transparent'>
<tr>
<td class='clear'> <div class='lp1' align='center'>
<a class='recover3'   href='login.php'>Log In</a>
<a class='recover3'  href='signup.php'>Sign Up</a>
<a class='recover3'  href='invite_signup.php'>Invite Sign Up</a>
<a class='recover3' href='recover.php'>Recover Account via e-mail</a>
<a class='recover3' href='resetpw.php'>Recover Account via password/question</a>
</div>
<br><br /><table class='mainouter2' width='100%' cellspacing='0' cellpadding='7'><tr><td class='roundboxcenter' align='center' style='padding-top: 20px; padding-bottom: 20px;border:hidden'><table class='main' width='750' border='0' cellpadding='0' cellspacing='0'>
<tr><td class='embedded'>
<h2>Error</h2>
<table width='100%' border='1' cellspacing='0' cellpadding='10'><tr><td class='text'>
You didn't select the proper image! Please go back and try again.</td></tr></table></td></tr></table>
</td></tr>
</table><p align='center'><br /><a href='https://houseoftorrents.me'><b>Powered By House-Of-Torrents &copy;&nbsp;2015</b></a>&nbsp;&nbsp;&nbsp;</p></body></html> 
2016-12-12 23:29:51.5273 Error Exception in test_indexer Jackett.ExceptionWithConfigData: <br />
<b>Notice</b>:  Undefined index: simpleCaptchaAnswer in <b>/var/www/html/takelogin.php</b> on line <b>17</b><br />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<meta name='generator' content='Bitleechers.net' />
<meta name='viewport' content='width=device-width, initial-scale=1' />
<meta http-equiv='Content-Type' content='text/html;charset=UTF-8' />
<meta http-equiv='Content-Language' content='en-us' />

<title>House-Of-Torrents</title>
<link rel='alternate' type='application/rss+xml' title='Latest Torrents' href='./rss.php?passkey=' />
<link rel='stylesheet' href='templates/10/10.css' type='text/css' />
<link type='image/x-icon' rel='shortcut icon' href='/pic/favicon2.ico' />
<script type='text/javascript' src='./image-resize/jquery.js'></script>
<script type='text/javascript' src='./image-resize/core-resize.js'></script>
<script type='text/javascript'>
/*<![CDATA[*/
function radio() {
window.open('radio_popup.php','My Radio','height=700,width=800,resizable=no,scrollbars=no,toolbar=no,menubar=no');
}
/*]]>*/
</script>




</head>

<body>
<table width='100%' cellspacing='0' cellpadding='0' style='background: transparent'>
<tr>
<td class='clear'> <div class='lp1' align='center'>
<a class='recover3'   href='login.php'>Log In</a>
<a class='recover3'  href='signup.php'>Sign Up</a>
<a class='recover3'  href='invite_signup.php'>Invite Sign Up</a>
<a class='recover3' href='recover.php'>Recover Account via e-mail</a>
<a class='recover3' href='resetpw.php'>Recover Account via password/question</a>
</div>
<br><br /><table class='mainouter2' width='100%' cellspacing='0' cellpadding='7'><tr><td class='roundboxcenter' align='center' style='padding-top: 20px; padding-bottom: 20px;border:hidden'><table class='main' width='750' border='0' cellpadding='0' cellspacing='0'>
<tr><td class='embedded'>
<h2>Error</h2>
<table width='100%' border='1' cellspacing='0' cellpadding='10'><tr><td class='text'>
You didn't select the proper image! Please go back and try again.</td></tr></table></td></tr></table>
</td></tr>
</table><p align='center'><br /><a href='https://houseoftorrents.me'><b>Powered By House-Of-Torrents &copy;&nbsp;2015</b></a>&nbsp;&nbsp;&nbsp;</p></body></html>
   at Jackett.Indexers.HouseOfTorrents.<>c__DisplayClass10_0.<ApplyConfiguration>b__0() in C:\projects\jackett\src\Jackett\Indexers\HouseOfTorrents.cs:line 119
   at Jackett.Indexers.BaseIndexer.<ConfigureIfOK>d__71.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\BaseIndexer.cs:line 471
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Indexers.HouseOfTorrents.<ApplyConfiguration>d__10.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\HouseOfTorrents.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Indexers.HouseOfTorrents.<PerformQuery>d__11.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\HouseOfTorrents.cs:line 154
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__11.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Test>d__18.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 267
2016-12-12 23:29:51.5490 Debug Saving new config file: C:\ProgramData\Jackett\Indexers\houseoftorrents.json.52f65c692ad94a5b82af26fb645342ea.tmp 
2016-12-12 23:29:51.5651 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]' 
2016-12-12 23:29:51.5807 Info ApiControllerActionInvoker InvokeActionAsync  
2016-12-12 23:29:51.5807 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()' 
2016-12-12 23:29:51.5807 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2016-12-12 23:29:51.5963 Info AdminController ExecuteAsync  
2016-12-12 23:29:51.5963 Info   Content-type='application/json; charset=utf-8', content-length=2401 
2016-12-12 23:29:51.6120 Info AdminController Dispose  
2016-12-12 23:29:51.6276 Info AdminController Dispose  
2016-12-12 23:29:51.6497 Info   http://127.0.0.1:9117/Admin/image-resize/jquery.js?_=1481574468483 
2016-12-12 23:29:51.6497 Info   http://127.0.0.1:9117/Admin/templates/10/10.css 
2016-12-12 23:29:51.6653 Info DefaultContentNegotiator Negotiate Type='HttpError', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer] 
2016-12-12 23:29:51.6653 Info   http://127.0.0.1:9117/pic/favicon2.ico 
2016-12-12 23:29:51.6810 Info DefaultContentNegotiator Negotiate Type='HttpError', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer] 
2016-12-12 23:29:51.6810 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='HttpError', mediaType='application/json; charset=utf-8' 
2016-12-12 23:29:51.6966 Info DefaultContentNegotiator Negotiate Type='HttpError', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer] 
2016-12-12 23:29:51.7122 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='HttpError', mediaType='application/json; charset=utf-8' 
2016-12-12 23:29:51.7122 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter 
2016-12-12 23:29:51.7278 Info XmlMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'XmlMediaTypeFormatter' for type='HttpError', mediaType='application/xml; charset=utf-8' 
2016-12-12 23:29:51.7278 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter 
2016-12-12 23:29:51.7500 Info DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8' 
2016-12-12 23:29:51.7500 Info XmlMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'XmlMediaTypeFormatter' formatter 
2016-12-12 23:29:51.7656 Info DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8' 
2016-12-12 23:29:51.7656 Info   Content-type='application/json; charset=utf-8', content-length=unknown 
2016-12-12 23:29:51.7812 Info DefaultContentNegotiator Negotiate Selected formatter='XmlMediaTypeFormatter', content-type='application/xml; charset=utf-8' 
2016-12-12 23:29:51.7812 Info   Content-type='application/json; charset=utf-8', content-length=unknown 
2016-12-12 23:29:51.7969 Info   http://127.0.0.1:9117/Admin/image-resize/core-resize.js?_=1481574468484 
2016-12-12 23:29:51.8125 Info   Content-type='application/xml; charset=utf-8', content-length=unknown 
2016-12-12 23:29:51.8281 Info DefaultContentNegotiator Negotiate Type='HttpError', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer] 
2016-12-12 23:29:51.8497 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='HttpError', mediaType='application/json; charset=utf-8' 
2016-12-12 23:29:51.8497 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter 
2016-12-12 23:29:51.8655 Info DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8' 
2016-12-12 23:29:51.8655 Info   Content-type='application/json; charset=utf-8', content-length=unknown

**Comment by armani316** [comment]
And here's AlphaReign failing the test:

2016-12-13 00:43:22.9533 Info   http://127.0.0.1:9117/Admin/test_indexer 
2016-12-13 00:43:22.9533 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2016-12-13 00:43:22.9603 Info DefaultHttpControllerSelector SelectController Admin 
2016-12-13 00:43:22.9603 Info HttpControllerDescriptor CreateController  
2016-12-13 00:43:22.9603 Info DefaultHttpControllerActivator Create  
2016-12-13 00:43:22.9603 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2016-12-13 00:43:22.9603 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2016-12-13 00:43:22.9603 Info AdminController ExecuteAsync  
2016-12-13 00:43:22.9783 Info ApiControllerActionSelector SelectAction  
2016-12-13 00:43:22.9783 Info ApiControllerActionSelector SelectAction Selected action 'Test()' 
2016-12-13 00:43:22.9783 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-12-13 00:43:22.9903 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-12-13 00:43:22.9903 Info HttpActionBinding ExecuteBindingAsync  
2016-12-13 00:43:22.9903 Info HttpActionBinding ExecuteBindingAsync  
2016-12-13 00:43:22.9903 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()' 
2016-12-13 00:43:23.0123 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2016-12-13 00:43:23.0123 Info ApiControllerActionInvoker InvokeActionAsync Action='Test()' 
2016-12-13 00:43:23.0263 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()' 
2016-12-13 00:43:23.0263 Debug IWebClient.GetString(Url:https://alphareign.se//?&query=) 
2016-12-13 00:43:38.5893 Debug IWebClient: Returning OK => <!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/assets/css/lib/bootstrap/toolkit-minimal.min.css?v=0.0.1">
	<link rel="stylesheet" type="text/css" href="/assets/css/index.css?v=0.0.8" />
	<title>AlphaReign</title>
</head>

<body ><div class="block">
	<div class="container text-center auth">
		<h1 class="block-title m-b-sm text-uppercase"><a href="/">
			<img src="/assets/img/logo-small.png">
			AlphaReign
		</a></h1>
		<p class="lead m-b-lg p-b-md">A Private Torrent Search Engine</p>

		<div class="auth-form">

			<div class="text-left">
				<div id="alert"></div>			</div>

			<ul class="nav nav-tabs nav-justified" role="tablist">
				<li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">Login</a></li>
				<li role="presentation" ><a href="#register" aria-controls="register" role="tab" data-toggle="tab">Register</a></li>
			</ul>

			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="login">
					<form action="/login" method="POST">
						<input type="hidden" name="csrf_name" value="csrf584f1a0122905">
						<input type="hidden" name="csrf_value" value="d846d29d5864cca0c89a211533e3e430">
						<input type="text" name="username" class="form-control m-b m-t" placeholder="Username" required  autofocus>
						<input type="password" name="password" class="form-control m-b" placeholder="Password" required >
						<button type="submit" class="btn btn-default-outline">Login</button>
					</form>
				</div>
				<div role="tabpanel" class="tab-pane " id="register">
					<form action="/register" method="POST">
						<input type="hidden" name="csrf_name" value="csrf584f1a0122905">
						<input type="hidden" name="csrf_value" value="d846d29d5864cca0c89a211533e3e430">
						<input type="text" name="username" class="form-control m-b m-t" placeholder="Username" required >
						<input type="password" name="password" class="form-control m-b" placeholder="Password" required >
						<input type="text" name="invitation" class="form-control m-b" placeholder="Invitation Code" required >
						<button type="submit" class="btn btn-default-outline">Register</button>
					</form>
				</div>
			</div>
			<div class="text-center">
				<br>
				<a href="/about">About AlphaReign</a>
				&nbsp; | &nbsp;
				<a href="/privacy">Privacy Policy</a>
			</div>
		</div>
	</div>
</div>
	<script type="text/javascript" src="/assets/js/lib/jquery/jquery.min.js"></script>
	<script type="text/javascript" src="/assets/js/lib/bootstrap/toolkit.min.js"></script>
	<script type="text/javascript" src="/assets/js/lib/moment/moment.min.js"></script>
	<script type="text/javascript" src="/assets/js/index.js?v=0.0.8"></script>
</body>

</html> 
2016-12-13 00:43:38.5893 Info CardigannIndexer (alphareign): Relogin required 
2016-12-13 00:43:38.6073 Debug IWebClient.GetString(Url:https://alphareign.se/login) 
2016-12-13 00:43:40.2619 Debug IWebClient: Returning BadRequest => Failed CSRF check! 
2016-12-13 00:43:40.2619 Debug IWebClient.GetString(Url:https://alphareign.se/settings) 
2016-12-13 00:43:40.7760 Debug IWebClient: Returning Redirect => https://alphareign.se/  
2016-12-13 00:43:40.8226 Error Error on 20161213004340 for AlphaReign.txtJackett.ExceptionWithConfigData: Login Failed, got redirected
   at Jackett.Indexers.CardigannIndexer.<TestLogin>d__31.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 498
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Jackett.Indexers.CardigannIndexer.<PerformQuery>d__39.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\CardigannIndexer.cs:line 808




<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="/assets/css/lib/bootstrap/toolkit-minimal.min.css?v=0.0.1">
	<link rel="stylesheet" type="text/css" href="/assets/css/index.css?v=0.0.8" />
	<title>AlphaReign</title>
</head>

<body ><div class="block">
	<div class="container text-center auth">
		<h1 class="block-title m-b-sm text-uppercase"><a href="/">
			<img src="/assets/img/logo-small.png">
			AlphaReign
		</a></h1>
		<p class="lead m-b-lg p-b-md">A Private Torrent Search Engine</p>

		<div class="auth-form">

			<div class="text-left">
				<div id="alert"></div>			</div>

			<ul class="nav nav-tabs nav-justified" role="tablist">
				<li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">Login</a></li>
				<li role="presentation" ><a href="#register" aria-controls="register" role="tab" data-toggle="tab">Register</a></li>
			</ul>

			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="login">
					<form action="/login" method="POST">
						<input type="hidden" name="csrf_name" value="csrf584f1a0122905">
						<input type="hidden" name="csrf_value" value="d846d29d5864cca0c89a211533e3e430">
						<input type="text" name="username" class="form-control m-b m-t" placeholder="Username" required  autofocus>
						<input type="password" name="password" class="form-control m-b" placeholder="Password" required >
						<button type="submit" class="btn btn-default-outline">Login</button>
					</form>
				</div>
				<div role="tabpanel" class="tab-pane " id="register">
					<form action="/register" method="POST">
						<input type="hidden" name="csrf_name" value="csrf584f1a0122905">
						<input type="hidden" name="csrf_value" value="d846d29d5864cca0c89a211533e3e430">
						<input type="text" name="username" class="form-control m-b m-t" placeholder="Username" required >
						<input type="password" name="password" class="form-control m-b" placeholder="Password" required >
						<input type="text" name="invitation" class="form-control m-b" placeholder="Invitation Code" required >
						<button type="submit" class="btn btn-default-outline">Register</button>
					</form>
				</div>
			</div>
			<div class="text-center">
				<br>
				<a href="/about">About AlphaReign</a>
				&nbsp; | &nbsp;
				<a href="/privacy">Privacy Policy</a>
			</div>
		</div>
	</div>
</div>
	<script type="text/javascript" src="/assets/js/lib/jquery/jquery.min.js"></script>
	<script type="text/javascript" src="/assets/js/lib/bootstrap/toolkit.min.js"></script>
	<script type="text/javascript" src="/assets/js/lib/moment/moment.min.js"></script>
	<script type="text/javascript" src="/assets/js/index.js?v=0.0.8"></script>
</body>

</html> 
2016-12-13 00:43:40.8226 Info Found 0 releases from AlphaReign 
2016-12-13 00:43:40.8226 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__11.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Test>d__18.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 267
2016-12-13 00:43:40.8393 Debug Saving new config file: C:\ProgramData\Jackett\Indexers\alphareign.json.b36570b41681425e8cf95167a33466b9.tmp 
2016-12-13 00:43:40.8393 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]' 
2016-12-13 00:43:40.8543 Info ApiControllerActionInvoker InvokeActionAsync  
2016-12-13 00:43:40.8543 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()' 
2016-12-13 00:43:40.8679 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2016-12-13 00:43:40.8679 Info AdminController ExecuteAsync  
2016-12-13 00:43:40.8834 Info   Content-type='application/json; charset=utf-8', content-length=81 
2016-12-13 00:43:40.8834 Info AdminController Dispose  
2016-12-13 00:43:40.9024 Info AdminController Dispose

**Comment by kaso17** [comment]
Ok, I hope f921df948c3506eea8a16bd53129520638bbbc17 and 059701fbf6cc06964872bed47864275dbe48d965 fixes this.

**Comment by armani316** [comment]
Seems like the problem's been solved, @kaso17! Thanks a lot! Closing this for one, will report back if there are any issues!
