### ISSUE TITLE
[scenetime] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by Jerrk** [Jackett/Jackett#8383]
### Environment

**OS**: Unraid 6.8.3

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: unknown

**Jackett Version**: 0.16.137.0

**Last Working Jackett Version**: unknown

**Are you using a proxy or VPN?** Yes, tried turning it off, doesnt help

### Description

Try to add scenetime as an indexer with username and password. the result is the error.

### Logged Error Messages

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.SceneTime.<>c__DisplayClass13_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 167
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.SceneTime.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 172
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

Full Logs

```
2020-04-27 05:12:37 | Error | System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.SceneTime.<>c__DisplayClass13_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 167    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 258    at Jackett.Common.Indexers.SceneTime.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 172    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
v-- CLICKING ON TEST BUT FAILS SINCE NO USERNAME/PASSWORD SAVED --v
2020-04-27 05:11:44 | Error | System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 227    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2020-04-27 05:11:44 | Info | Found 0 releases from SceneTime
2020-04-27 05:10:47 | Info | Jackett startup finished in 5.907 s
2020-04-27 05:10:47 | Info | Adding aggregate indexer
2020-04-27 05:10:47 | Info | Cardigann definitions loaded: pier720, abnormal, alpharatio, anidex, anidub, animebytes, animetorrents, tehconnectionme, avistaz, awesomehd, bakabt, bb, bitcityreloaded, bithdtv, bjshare, broadcastthenet, brokenstones, cgpeers, cinecalidad, cinemaz, corsarored, danishbits, digitalcore, digitalhive, divxtotal, elitetracker, epublibre, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdolimpo, hdonly, hdspace, hdtorrents, hebits, horriblesubs, immortalseed, internetarchive, iptorrents, lostfilm, mejortorrent, milkie, morethantv, myamity, myanonamouse, ncore, newpct, newrealworld, norbits, nordicbits, notwhatcd, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, psytorrents, rarbg, passtheheadphones, revolutiontt, rutracker, scenehd, scenetime, secretcinema, shazbat, showrss, solidtorrents, speedcd, superbits, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentleech, torrentnetwork, torrentscsv, torrentseeds, torrentsyndikat, transmithenet, tvstore, tvvault, xspeeds, xthor, yts, animetosho, 0daykiev, 1337x, 2fast4you, 32pages, 3changtrai, 3dtorrents, 3evils, 4thd, 52pt, 7torrents, Bittorrentfiles, Das-Unerwartete, academictorrents, acgrip, acgsou, acidlounge, aftershock, alexfilm, amigosshare, aniRena, arabafenice, arabp2p, arenabg, asgaard, asiancinema, ast4u, audiobookbay, audiobooktorrents, audionews, backups, badasstorrents, baibako, beitai, beyond-hd-oneurl, beyond-hd, bibliotik, bigfangroup, bigtorrent, bigtower, bit-titan, bithorlo, bithumen, bitru, bitspyder, bitturk, bluebirdhd, blutopia, booktracker, boxingtorrents, brasiltracker, broadcity, brobits, btdb, btdigg, btetree, bteye, btgigs, btnext, btschool, btsow, carpathians, cartoonchaos, casatorrent, casstudiotv, ccfbits, Channelx, chdbits, chilebt, cili180, cinemageddon, cinemamovies, cinematik, classix, concen, concertos, cpasbien, cpasbienclone, crazyhd, crazyscorner, crazyspirits, crnaberza, cztorrent, dark-shadow, darktracker, datascene, deildu, demonoid, demonsite, desireleasers, desitorrents, diablotorrent, dimeadozen, divteam, dmhy, documentarytorrents, downloadville, dragonworldreloaded, dxdhd, dxp, ebookparadijs, ebooks-shares, efectodoppler, elitetorrent-biz, empornium, eniahd, epizod, erzsebet, esharenet, estone, estrenosdtl, ethor, ettv, exkinoray, extratorrent-ag, extratorrent-cd, extremetorrents, extremlymtorrents, exttorrents, eztv, fanoin, fantasticheaven, femdomcult, filebase, film-paleis, filmsclub, finelite, finvip, firebit, focusx, fouducinema, freetorrent, frozenlayer, fullmixmusic, funkytorrents, galeriens, gamestorrents, gay-torrents, gay-torrentsorg, gaytorrentru, generationfree, gfxpeers, gigatorrents, girotorrent, gktorrent, glodls, greekteam, hachede, haidan, hamsterstudio, hd4fans, hdarea, hdbits, hdbitscom, hdcenter, hdchina, hdcity, hddisk, hddolby, hdforever, hdhome, hdme, hdreactor, hdroute, hdsky, hdspain, hdtime, hdtorrentsit, hdturk, hdu, hdzone, hon3yhd, horrorsite, hqsource, hush, ibit, icetorrent, idope, ilcorsaroblu, ilcorsaronero, immortuos, inperil, insanetracker, isohunt2, itorrent, iv-torrents, jpopsuki, kapaki, karagarga, kaztorka, kickasstorrent-kathow, kickasstorrent, kinonavse100, kinorun, kinozal, korsar, lastfiles, leaguehd, learnflakes, lechaudron, legacyhd, legittorrents, leporno, lesaloon, libranet, limetorrents, linkomanija, linuxtracker, losslessclub, mactorrents, magico, magnet4you, magnetdl, majomparade, marinetracker, metaliplayro, metaltracker, microbit, mma-torrents, moecat, mononokebt, monova, movcr, moviesdvdr, mteamtp, mteamtp2fa, muziekfabriek, mvgroupforum, mvgroupmain, mypornclub, myspleen, nbtorrents, netcosmo, nethd, netlab, newretro, newstudio, newstudiol, nitro, nnm-club, nntt, nordichd, nostalgic, nyaa-pantsu, nyaasi, onejav, onlineselfeducation, ourbits, oxtorrent, p2pbg, p2pelite, parnuxi, pctorrent, peersfm, piratbit, piratbitl, pirateiro, pixelcove, pleasuredome, polishsource, pornbay, pornbits, pornleech, pornolive, pornorip, pornotor, proaudiotorrents, prostylex, pt99, pterclub, ptfiles, pthome, ptsbao, puntorrent, purovicio, pussytorrents, pwtorrents, r3vwtf, racing4everyone, racingforme, rapidzona, rstorrent, retroflix, rintor, riperam, RockBox, rodvd, rptorrents, rus-media, rustorka, rutor, rutracker-ru, scenefz, scenepalace, scenerush, sdbits, seedfile, shareisland, sharespacedb, shareuniversity, sharewood, shellife, shokweb, siambit, sktorrent-org, sktorrent, skytorrentsclone, snowpt, sosulki, soundpark, spacetorrent, speedmasterhd, speedtorrentreloaded, spiritofrevolution, sporthd, sportscult, springsunday, sukebei-pantsu, sukebeinyaasi, takeabyte, tapochek, tasmanit, teamhd, teamos, tekno3d, tellytorrent, tenyardtracker, the-madhouse, theaudioscene, theempire, thefallingangels, thegeeks, thehorrorcharnel, theoccult, thepiratebay, theplace, theshinning, theshow, thevault, tlfbits, tntvillage, tokyotosho, topnow, torlock, toros, torrent-explosiv, torrent-pirat, torrent-turk, torrent4you, torrent9, torrent9clone, torrentbd, torrentbomb, torrentccf, torrentdb, torrentdownload, torrentdownloads, torrentfactory, torrentfunk, torrentgalaxyorg, torrenthane, torrenthr, torrenting, torrentkitty, torrentland, torrentleech-pl, torrentlt, torrentoyunindir, torrentparadise, torrentproject2, torrentquest, torrentsectorcrew, torrentslocal, torrentv, torrentview, torrentz2, torrentz2k, totallykids, totheglory, trancetraffic, trezzor, tribalmixes, ttsweb, turkseed, turktorrent, tvchaosuk, twilight, twilightszoom, u-torrents, u2, uhdbits, underverse, underversel, uniondht, unionfansub, uniongang, uniotaku, unlimitz, vizuk, wdt, wihd, world-of-tomorrow, xiteme, xbytesv2, xtremefile, xtremezone, xwtclassics, xwtorrents, xxxtor, yggcookie, yggtorrent, yourbittorrent, yourexotic, zamundanet, zelkaorg, zetorrents, zooqle, ztracker
2020-04-27 05:10:44 | Info | Loading Cardigann definitions from: /home/nobody/.config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /usr/lib/jackett/Definitions
2020-04-27 05:10:44 | Info | Using HTTP Client: HttpWebClient2NetCore
2020-04-27 05:10:44 | Info | Using Proxy: Http
2020-04-27 05:10:44 | Info | App config/log directory: /config/Jackett
2020-04-27 05:10:44 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2020-04-27 05:10:44 | Info | Running in Docker: Yes
2020-04-27 05:10:44 | Info | File /etc/issue: Arch Linux \r (\l)
2020-04-27 05:10:44 | Info | Jackett variant: CoreLinuxAmdx64
2020-04-27 05:10:44 | Info | OS version: Unix 4.19.107.0 (64bit OS) (64bit process)
2020-04-27 05:10:44 | Info | Environment version: 3.1.3 (/usr/lib/jackett/)
2020-04-27 05:10:43 | Info | Jackett Data will be stored in: /config/Jackett
2020-04-27 05:10:42 | Info | Starting Jackett v0.16.137.0
```

**Comment by garfield69** [comment]
the scenetime indexer is working for me on Jackett 0.16.137 so that suggests something about your search or situation is generating the error.
Unfortunately the log you provided is the regular log which does not contain enough info to be useful.
You need to turn on the **Enhanced** logging so that you can capture the html and other Debug messages that proceeds the error so we have something to work with.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by Jerrk** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/4537373/log.txt)

Is this sufficient?

**Comment by garfield69** [comment]
I think so.
Its a little bloated with activity from other indexers, a pity you could not just do scenetime on its own.
But no worries, the scenetime html is in there, so we just have to go through the log now and see if we can find what is tripping up the scenetime indexer when its processing the results from your search.

**Comment by Jerrk** [comment]
I created a new container to only check scenetime, When i add scenetime it first asks for a cookie, it then tests successfully. If i then try to edit the indexer the cookie field is not populated, i then close without saving and test again and get another error, if i paste the cookie and apply again it tests successfully.

From my main container i remove the indexer, restart the container, try to add the container again but it only asks for username and password...

Is this perhaps a bug?

log from the scenetime only container where it only asks for cookie and tests successfully
[log.txt](https://github.com/Jackett/Jackett/files/4537640/log.txt)

**Comment by Jerrk** [comment]
So i fixed it by turning off my proxy while adding the indexer and then after successfully adding it i turn the proxy back on, and it still works!

Not sure why there are 2 separate templates in jackett whether you are on a proxy or not...

**Comment by garfield69** [comment]
there isn't.
what there is, is a check on the login page for the presence of a captcha.
if present we know the regular login will not work, so we ask for the cookie
if not present we use the regular login
which means that the proxy you are using in blacklisted by scenetime as being part of an ip block that generated an anti-ddos attack,
without the proxy scenetime likes your regular ip address

**Comment by cadatoiva** [comment]
In addition to what @garfield69 said, proxy use is currently considered experimental in Jackett. There are a lot of bugs relating to the internal Jackett proxy implementation.

If you don't need a VPN/Proxy to get around geo-blocking or ISP filters then its recommended you not use one at all. If you do need it for those reasons, it's recommended to use a VPN application to route the traffic.
