### ISSUE TITLE
secret-cinema: login does not work

### ISSUE THREAD

**Issue by apcrcom** [Jackett/Jackett#8387]
Jackett Version 0.16.137.0 

SC not working. Credentials are correct. 

'click here to open an issue' not working in error dialogue

the tracker disappears from list of trackers after error throws. (expected behaviour it should be listed with (!) denoting error)

no error was apparent in list before testing - error was reported  by Hydra

![Screenshot_1](https://user-images.githubusercontent.com/25422932/80333782-54f07600-888e-11ea-9177-d7e7928b71b1.png)

**OS**: Linux (buster)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:  Jackett Version 0.16.137.0 

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]  NO 

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

```
Jackett.Common.ExceptionWithConfigData: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>Secret Cinema</title>
	<meta http-equiv="X-UA-Compatible" content="chrome=1; IE=edge" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="favicon.ico" />
	<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
	<link href="static/styles/public/style.css?v=1495832154" rel="stylesheet" type="text/css" />
	<script src="static/functions/jquery.js" type="text/javascript"></script>
	<script src="static/functions/script_start.js?v=1531787838" type="text/javascript"></script>
	<script src="static/functions/ajax.class.js?v=1531787838" type="text/javascript"></script>
	<script src="static/functions/cookie.class.js?v=1531787838" type="text/javascript"></script>
	<script src="static/functions/storage.class.js?v=1531787838" type="text/javascript"></script>
	<script src="static/functions/global.js?v=1531787838" type="text/javascript"></script>
</head>
<body>
<div id="head">
</div>
<table class="layout" id="maincontent">
	<tr>
		<td align="center" valign="middle">
			<div id="logo">
				<ul>
					<li><a href="index.php">Home</a></li>
					<li><a href="login.php">Log in</a></li>
				</ul>
			</div>
<div class="poetry"></div>
<span class="center"></span>
		</td>
	</tr>
</table>
<div id="foot">
	<span><a href="#">Secret Cinema</a></span>
</div>
</body>
</html>

   at Jackett.Common.Indexers.Abstract.GazelleTracker.<>c__DisplayClass18_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 134
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 258
   at Jackett.Common.Indexers.Abstract.GazelleTracker.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 141
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by cadatoiva** [comment]
No developer currently has an account to help fix this. It's part of the Gazelle group I'm working on updating in #7923 so if you could send an invite to cadatoiva - at - yahoo.com it would be appreciated. If not, I should still be able to try and fix this with the others with what you've given so far.

**Comment by RoloSoze** [comment]
@cadatoiva If you don't receive an invite, Secret-Cinema has an official recruitment thread on the same tracker I told you about in my SceneHD email. You'd have to be a Power User with a 6-month-old account.

**Comment by apcrcom** [comment]
Its a new account so I dont have any leverage to request invites yet. Sorry
I cant help out with this!

**Comment by apcrcom** [comment]
hang 5 though, I will talk to admin about it. Maybe given the circumstances
they might make an exception or send you one themselves. Will get back to
you.

**Comment by apcrcom** [comment]
Ok. Have msgd staff and ref'd them to this thread with a request for their assistance. Hope it works out. 

Thanks for your help.

**Comment by RoloSoze** [comment]
@apcrcom Any updates from the staff?

**Comment by apcrcom** [comment]
They did respond. They were not interested in helping unfortunately.


J

**Comment by ngosang** [comment]
@apcrcom This tracker is working fine for me, I can't reproduce your problem.
In the HTML you posted there isn't any form...
Could you try to open a private tab in your web browser and login with your account to verify the credentials are ok?
Could you remove secret-cinema from jackett, restart jackett and try to configure it again?
