### ISSUE TITLE
torrentbomb: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8408]
Empty search:
```
CardigannIndexer (torrentbomb): Error while parsing row '
<li>
	<div class="sch_tit">
		<a href="bbs/./board.php?bo_table=torrent_movie&amp;wr_id=4219" class="sch_res_title">토렌트 한국영화 - 싸움의 기술 2.<b class="sch_word">2020</b>.WEBRip.1080p.x264.AAC</a>
		<a href="bbs/./board.php?bo_table=torrent_movie&amp;wr_id=4219" target="_blank" class="pop_a">
			<i class="fa fa-share-square-o" aria-hidden="true"></i>새창</a>
	</div>
	<div class="sch_info">
		<span class="sch_datetime">
			<i class="fa fa-clock-o" aria-hidden="true"></i>
		</span>
	</div>
</li>':

System.Exception: Error while parsing field=date, selector=span.sch_datetime, value=: DateTime parsing failed for "": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/kizar/repositories/Jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 96
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/kizar/repositories/Jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 205
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (torrentbomb): Error while parsing row '
<li>
	<div class="sch_tit">
		<a href="bbs/./board.php?bo_table=torrent_movie&amp;wr_id=4220" class="sch_res_title">토렌트 한국영화 - 싸움의 기술 2.<b class="sch_word">2020</b>.WEBRip.1080p.x264.AAC</a>
		<a href="bbs/./board.php?bo_table=torrent_movie&amp;wr_id=4220" target="_blank" class="pop_a">
			<i class="fa fa-share-square-o" aria-hidden="true"></i>새창</a>
	</div>
	<div class="sch_info">
		<span class="sch_datetime">
			<i class="fa fa-clock-o" aria-hidden="true"></i>
		</span>
	</div>
</li>':

System.Exception: Error while parsing field=date, selector=span.sch_datetime, value=: DateTime parsing failed for "": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/kizar/repositories/Jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 96
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/kizar/repositories/Jackett/src/Jackett.Common/Utils/DateTimeUtil.cs:line 205
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by garfield69** [comment]
apparently, rows without a date are titles without magnet/.torrent links in the details page so I can exclude them rather that trying to cope with empty date fields.
