### ISSUE TITLE
exttorrents: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8433]
"query": "macosx"

```
CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 computer"></i>
			<a href="/vmware-fusion-professional-v11-5-2-macosx-keygen-amped-extag-671018/">
				<b>VMware Fusion Professional v11.5.2
					<span>MACOSX</span>
					+ Keygen-AMPED #EXTAG</b>
			</a>
			<div class="related-posted">
				Posted  																																				by
				<a class="verify-user-link simple-user is-uploader" href="/user/hydr4/">
					<strong>hydr4</strong>
				</a>
				in
				<a href="/applications/">
					<strong>Apps</strong>
				</a>
				-
				<a href="/applications/mac/">
					<strong>Mac</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
			<a class="dwn-btn torrent-dwn" data-id="671018" target="_blank" rel="nofollow" href="https://tfiles.org/torrent/29c/1400C19A05B7BE0BAFE13F3E02CD8FFD38347C9D.torrent?title=[ext.to]VMware.Fusion.Professional.v11.5.2.MACOSX.Incl.Keygen-AMPED.torrent">
				<i class="material-icons file_download"></i>
			</a>
		</div>
	</td>
	<td class="nowrap-td">518.87 MB</td>
	<td>5</td>
	<td class="nowrap-td">1 month ago</td>
	<td>
		<span class="text-success">1</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) div div a, value=/user/hydr4/: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
More
"query": "game"
"query": "love"
```
CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 video_library"></i>
			<a href="/hr-otome-game-no-hametsu-04-1080p-hevc-multi-subs-hr-mf-713196/">
				<b>[HR] Otome
					<span>Game</span>
					no Hametsu 04 [1080p HEVC Multi-Subs] HR-MF</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/anime/">
					<strong>Anime</strong>
				</a>
				-
				<a href="/anime/english-translated/">
					<strong>English-translated</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
			<a class="dwn-btn torrent-dwn" data-id="713196" target="_blank" rel="nofollow" href="https://tfiles.org/torrent/f11/31fb2fb64567aa7936f445f278a6ab836ab46e7c.torrent?title=[ext.to][HR].Otome.Game.no.Hametsu.04.[1080p.HEVC.Multi-Subs].HR-MF.torrent">
				<i class="material-icons file_download"></i>
			</a>
		</div>
	</td>
	<td class="nowrap-td">260.5 MB</td>
	<td>1</td>
	<td class="nowrap-td">1 week ago</td>
	<td>
		<span class="text-success">16</span>
	</td>
	<td>
		<span class="text-danger">1</span>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) div div a:last-child, value=/anime/english-translated/: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 video_library"></i>
			<a href="/hr-otome-game-no-hametsu-05-1080p-hevc-multi-subs-hr-mf-719728/">
				<b>[HR] Otome
					<span>Game</span>
					no Hametsu 05 [1080p HEVC Multi-Subs] HR-MF</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/anime/">
					<strong>Anime</strong>
				</a>
				-
				<a href="/anime/english-translated/">
					<strong>English-translated</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
			<a class="dwn-btn torrent-dwn" data-id="719728" target="_blank" rel="nofollow" href="https://tfiles.org/torrent/0cd/137558139227563cdc1d110122513813f53ed9ae.torrent?title=[ext.to][HR].Otome.Game.no.Hametsu.05.[1080p.HEVC.Multi-Subs].HR-MF.torrent">
				<i class="material-icons file_download"></i>
			</a>
		</div>
	</td>
	<td class="nowrap-td">281.3 MB</td>
	<td>1</td>
	<td class="nowrap-td">4 hours ago</td>
	<td>
		<span class="text-success">20</span>
	</td>
	<td>
		<span class="text-danger">38</span>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) div div a:last-child, value=/anime/english-translated/: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
"query": "dr"
I think you made a mistake in https://github.com/Jackett/Jackett/commit/88d976f00578fe22516a4c2878344937912ca806
```
CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 video_library"></i>
			<a href="/hr-boku-no-hero-academia-season-4-complete-web-1080p-hevc-multi-hr-dr-719261/">
				<b>[HR] Boku no Hero Academia (Season 4) (Complete) [Web 1080p HEVC Multi] HR-<span>DR</span>
				</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/anime/">
					<strong>Anime</strong>
				</a>
				-
				<a href="/anime/english-translated/">
					<strong>English-translated</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
			<a class="dwn-btn torrent-dwn" data-id="719261" target="_blank" rel="nofollow" href="https://tfiles.org/torrent/5c7/19e51ae5b55b04a60458993c938029df4a3500bd.torrent?title=[ext.to][HR].Boku.no.Hero.Academia.(Season.4.(Complete.[Web.1080p.HEVC.Multi].HR-DR.torrent">
				<i class="material-icons file_download"></i>
			</a>
		</div>
	</td>
	<td class="nowrap-td">5.3 GB</td>
	<td>26</td>
	<td class="nowrap-td">1 week ago</td>
	<td>
		<span class="text-success">15</span>
	</td>
	<td>
		<span class="text-danger">16</span>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) div div a:last-child, value=/anime/english-translated/: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
"query": "milwaukee"
```
CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 movie"></i>
			<a href="/ng-americas-lost-treasures-04of10-milwaukee-pdtv-xvid-ac3-eztv-852501/">
				<b>NG Americas Lost Treasures 04of10
					<span>Milwaukee</span>
					PDTV XviD AC3 EZTV</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/tv/">
					<strong>TV</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
			<a class="dwn-btn torrent-dwn" data-id="852501" target="_blank" rel="nofollow" href="https://tfiles.org/torrent/4b9/0e944a55de6189e53cb255857742e2e8946dd394.torrent?title=[ext.to]NG.Americas.Lost.Treasures.04of10.Milwaukee.PDTV.XviD.AC3.EZTV.torrent">
				<i class="material-icons file_download"></i>
			</a>
		</div>
	</td>
	<td class="nowrap-td">701.24 MB</td>
	<td></td>
	<td class="nowrap-td">7 years ago</td>
	<td>
		<span class="text-success">0</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618
```

"query": "lanka"
```
CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 movie"></i>
			<a href="/bbc-planet-earth-live-2012-episode-6-live-update-sri-lanka-x264-aac-hdtv-eztv-850846/">
				<b>BBC Planet Earth Live 2012 Episode 6 Live Update Sri
					<span>Lanka</span>
					x264 AAC HDTV EZTV</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/tv/">
					<strong>TV</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
		</div>
	</td>
	<td class="nowrap-td">1.8 GB</td>
	<td></td>
	<td class="nowrap-td">8 years ago</td>
	<td>
		<span class="text-success">1</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 movie"></i>
			<a href="/bbc-indian-ocean-with-simon-reeve-5of6-sri-lanka-to-bangladesh-pdtv-xvid-ac3-eztv-850897/">
				<b>BBC Indian Ocean with Simon Reeve 5of6 Sri
					<span>Lanka</span>
					to Bangladesh PDTV XviD AC3 EZTV</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/tv/">
					<strong>TV</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
		</div>
	</td>
	<td class="nowrap-td">785.41 MB</td>
	<td></td>
	<td class="nowrap-td">8 years ago</td>
	<td>
		<span class="text-success">4</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 movie"></i>
			<a href="/bbc-indian-ocean-with-simon-reeve-5of6-sri-lanka-to-bangladesh-720p-x264-aac-hdtv-eztv-850894/">
				<b>BBC Indian Ocean with Simon Reeve 5of6 Sri
					<span>Lanka</span>
					to Bangladesh 720p x264 AAC HDTV EZTV</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/tv/">
					<strong>TV</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
		</div>
	</td>
	<td class="nowrap-td">1.78 GB</td>
	<td></td>
	<td class="nowrap-td">8 years ago</td>
	<td>
		<span class="text-success">0</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 movie"></i>
			<a href="/green-paradise-24of28-sri-lanka-xvid-ac3-eztv-851492/">
				<b>Green Paradise 24of28 Sri
					<span>Lanka</span>
					XviD AC3 EZTV</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/tv/">
					<strong>TV</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
		</div>
	</td>
	<td class="nowrap-td">349.68 MB</td>
	<td></td>
	<td class="nowrap-td">8 years ago</td>
	<td>
		<span class="text-success">1</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 movie"></i>
			<a href="/bbc-natural-world-2013-sri-lanka-elephant-island-pdtv-xvid-ac3-eztv-854474/">
				<b>BBC Natural World 2013 Sri
					<span>Lanka</span>
					Elephant Island PDTV XviD AC3 EZTV</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/tv/">
					<strong>TV</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
		</div>
	</td>
	<td class="nowrap-td">684.63 MB</td>
	<td></td>
	<td class="nowrap-td">7 years ago</td>
	<td>
		<span class="text-success">2</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 movie"></i>
			<a href="/bbc-natural-world-2013-sri-lanka-elephant-island-720p-x264-aac-hdtv-eztv-854470/">
				<b>BBC Natural World 2013 Sri
					<span>Lanka</span>
					Elephant Island 720p x264 AAC HDTV EZTV</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/tv/">
					<strong>TV</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
		</div>
	</td>
	<td class="nowrap-td">1.7 GB</td>
	<td></td>
	<td class="nowrap-td">7 years ago</td>
	<td>
		<span class="text-success">5</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 movie"></i>
			<a href="/sbs-wildest-islands-series-1-4of5-sri-lanka-540p-dvdrip-x264-aac-eztv-854985/">
				<b>SBS Wildest Islands Series 1 4of5 Sri
					<span>Lanka</span>
					540p DVDRip x264 AAC EZTV</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/tv/">
					<strong>TV</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
		</div>
	</td>
	<td class="nowrap-td">667.01 MB</td>
	<td></td>
	<td class="nowrap-td">6 years ago</td>
	<td>
		<span class="text-success">5</span>
	</td>
	<td>
		<span class="text-danger">1</span>
	</td>
</tr>':

System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 movie"></i>
			<a href="/the-worlds-greatest-balloon-adventures-1of5-sri-lanka-dvdrip-x264-eztv-855674/">
				<b>The Worlds Greatest Balloon Adventures 1of5 Sri
					<span>Lanka</span>
					DVDRip x264 EZTV</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/tv/">
					<strong>TV</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
		</div>
	</td>
	<td class="nowrap-td">646.27 MB</td>
	<td></td>
	<td class="nowrap-td">6 years ago</td>
	<td>
		<span class="text-success">1</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=files, selector=td:nth-child(3), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618
```

**Comment by ngosang** [comment]
@ilike2burnthing 

"query": "Harry Potter"
```
CardigannIndexer (exttorrents): Error while parsing row '
<tr>
	<td class="text-left">
		<div class="float-left">
			<i class="material-icons md-18 xxx"></i>
			<a href="/shadbase-fallout-4-arkham-cunts-batman-harley-quinn-hermoine-harry-potter-adult-comics-almerias-2923620/">
				<b>Shadbase - Fallout
					<span>4</span>
					+ Arkham Cunts (Batman, Harley Quinn) + Hermoine (<span>Harry</span>
					<span>Potter</span>) [Adult Comics] - {Almerias}</b>
			</a>
			<div class="related-posted">
				Posted  																						in
				<a href="/xxx/">
					<strong>XXX</strong>
				</a>
				-
				<a href="/xxx/magazines/">
					<strong>Magazines</strong>
				</a>
			</div>
		</div>
		<div class="btn-blocks float-right">
		</div>
	</td>
	<td class="nowrap-td">30.7 MB</td>
	<td>6</td>
	<td class="nowrap-td">5 years ago</td>
	<td>
		<span class="text-success">1</span>
	</td>
	<td>
		<span class="text-danger">0</span>
	</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) div div a:last-child, value=/xxx/magazines/: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1522
```
