### ISSUE TITLE
firebit: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8434]
"query": "pack"
```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/linux/">Linux</a>
	</td>
	<td>
		<a href="/11802-postal-the-fudge-pack">Postal - The Fudge Pack</a>
	</td>
	<td class="td-size">6.14 Gb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/KosiakS/">KosiakS</a>
	</td>
	<td>26.06.2010 22:48:55</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Linux: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

"query": "adobe illustrator"
```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D0%BA%D0%B0/">Мобилка</a>
	</td>
	<td>
		<a href="/84769-adobe-photoshop-touch-2013-android-v.1.1.0">Adobe Photoshop Touch (2013) Android {v.1.1.0}</a>
	</td>
	<td class="td-size">76.3 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/moneymememememe/">moneymememememe</a>
	</td>
	<td>16.06.2013 09:35:18</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Мобилка: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/">Программы</a>,
		<a href="/%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE/">Видео</a>
	</td>
	<td>
		<a href="/43947-%D0%BA%D1%80%D0%B0%D1%81%D0%B8%D0%B2%D1%8B%D0%B5-%D0%BD%D0%B0%D0%B4%D0%BF%D0%B8%D1%81%D0%B8-%D0%B2-adobe-photoshop-cs4-2011-pc">Красивые надписи в Adobe Photoshop CS4 (2011) PC</a>
	</td>
	<td class="td-size">164.63 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/mistikas/">mistikas</a>
	</td>
	<td>08.12.2011 19:40:19</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Программы Видео: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/">Программы</a>,
		<a href="/web/">Web</a>,
		<a href="/%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5/">Оформление</a>
	</td>
	<td>
		<a href="/35253-adobe-dreamweaver-cs5-v11.0-build-4909-2010-rus">Adobe Dreamweaver CS5 v11.0 Build: 4909 (2010) {Rus}</a>
	</td>
	<td class="td-size">410.65 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/dr_Aibolit/">dr_Aibolit</a>
	</td>
	<td>26.06.2011 16:22:35</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Программы Web Оформление: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/">Программы</a>,
		<a href="/%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE/">Видео</a>
	</td>
	<td>
		<a href="/9828-total-training-adobe-flash-cs5">Total Training Adobe Flash CS5</a>
	</td>
	<td class="td-size">673.84 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/AVATOR/">AVATOR</a>
	</td>
	<td>11.05.2010 23:28:10</td>
	<td class="l1">1</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Программы Видео: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
1 more:
"query": "mode"

```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/">Музыка</a>,
		<a href="/%D1%84%D0%B8%D0%BB%D1%8C%D0%BC/">Фильмы</a>
	</td>
	<td>
		<a href="/26194-depeche-mode-violator-2007-dvd5">Depeche Mode Violator (2007) DVD5</a>
	</td>
	<td class="td-size">4.16 Gb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/svarnoi/">svarnoi</a>
	</td>
	<td>23.02.2011 20:28:06</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Музыка Фильмы: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
3 more

"query": "professional"
```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/">Программы</a>,
		<a href="/faq/">FAQ</a>
	</td>
	<td>
		<a href="/20164-%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-%D0%BA%D0%B0%D0%BA-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%BA%D1%80%D0%B0%D1%81%D0%B8%D0%B2%D1%83%D1%8E-3d-%D0%BE%D0%B1%D0%BB%D0%BE%D0%B6%D0%BA%D1%83-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-imandix-cover-professional-0.9.2.8">Инструкция: как сделать красивую 3D обложку с помощью IMANDIX Cover Professional 0.9.2.8</a>
	</td>
	<td class="td-size">71.8 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/StarbirS/">StarbirS</a>
	</td>
	<td>05.12.2010 12:00:01</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Программы FAQ: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/">Программы</a>
	</td>
	<td>
		<a href="/51068-windows-7-professional-2012-pc-v.4.3.12-x86x64">Windows 7 Professional (2012) PC {v.4.3.12, x86x64}</a>
	</td>
	<td class="td-size">-</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B940/">Алексей40</a>
	</td>
	<td>11.04.2012 22:09:32</td>
	<td class="l1">-</td>
	<td class="l2">-</td>
</tr>':

System.Exception: Error while parsing field=size, selector=td.td-size, li.meta-size, value=-: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

"query": "people"
```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D1%84%D0%B8%D0%BB%D1%8C%D0%BC/">Фильмы</a>,
		<a href="/%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB/">Сериалы</a>
	</td>
	<td>
		<a href="/12908-%D0%B6%D0%B8%D0%B7%D0%BD%D1%8C-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%BB%D1%8E%D0%B4%D0%B5%D0%B9-6-%D0%B2%D0%B7%D0%B0%D0%BF%D0%B5%D1%80%D1%82%D0%B8-%D0%B8-%D0%BD%D0%B0-%D0%BF%D1%80%D0%B8%D0%B2%D1%8F%D0%B7%D0%B8-life-after-people-6-bound-and-buried--2009-720p-hdtv">Жизнь после людей-6 (Взаперти и на привязи) / Life After People-6 (Bound and Buried).(2009) 720p HDTV.</a>
	</td>
	<td class="td-size">1.46 Gb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/Ser/">Ser</a>
	</td>
	<td>25.07.2010 23:06:21</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Фильмы Сериалы: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D1%84%D0%B8%D0%BB%D1%8C%D0%BC/">Фильмы</a>,
		<a href="/%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB/">Сериалы</a>
	</td>
	<td>
		<a href="/12817-%D0%B6%D0%B8%D0%B7%D0%BD%D1%8C-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%BB%D1%8E%D0%B4%D0%B5%D0%B9-5-%D0%BE%D0%BA%D0%BA%D1%83%D0%BF%D0%B0%D0%BD%D1%82%D1%8B-life-after-people-5-the-invaders--2009-720p-hdtv">Жизнь после людей-5 (Оккупанты) / Life After People-5 (The invaders).(2009) 720p HDTV.</a>
	</td>
	<td class="td-size">1.09 Gb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/Ser/">Ser</a>
	</td>
	<td>24.07.2010 10:17:12</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Фильмы Сериалы: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

"query": "love"
```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE/">Видео</a>,
		<a href="/%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/">Музыка</a>
	</td>
	<td>
		<a href="/131634-i-love-the-90s-2-2015-hdrip">I Love The 90s-2 (2015) HDRip</a>
	</td>
	<td class="td-size">864.18 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/fil76/">fil76</a>
	</td>
	<td>19.06.2015 18:18:07</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Видео Музыка: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE/">Видео</a>,
		<a href="/%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0/">Музыка</a>
	</td>
	<td>
		<a href="/131443-i-love-the-90s-2015-hdrip">I Love The 90s (2015) HDRip</a>
	</td>
	<td class="td-size">978.3 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/fil76/">fil76</a>
	</td>
	<td>10.06.2015 18:51:09</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Видео Музыка: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
"query": "2014"
```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D1%84%D0%B8%D0%BB%D1%8C%D0%BC/">Фильмы</a>,
		<a href="/%D1%81%D0%BA%D0%BE%D1%80%D0%BE-%D0%BD%D0%B0-%D1%82%D1%80%D0%B5%D0%BA%D0%B5%D1%80%D0%B5/">Скоро на трекере</a>
	</td>
	<td>
		<a href="/110399-%D1%82%D0%BE%D0%BF-15-%D0%BE%D0%B6%D0%B8%D0%B4%D0%B0%D0%B5%D0%BC%D1%8B%D1%85-%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D0%BE%D0%B2-%D0%B8%D1%8E%D0%BB%D1%8F-2014-%D0%B3%D0%BE%D0%B4%D0%B0-2014-hdtvrip-720-%D0%BE%D1%82-nnnb">Топ-15 ожидаемых фильмов июля 2014 года (2014) HDTVRip 720 от NNNB</a>
	</td>
	<td class="td-size">1.05 Gb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/_denis_100/">_denis_100</a>
	</td>
	<td>30.06.2014 22:42:25</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Фильмы Скоро на трекере: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

{"query": "dead"
```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D0%BA%D0%B0/">Мобилка</a>,
		<a href="/%D0%B8%D0%B3%D1%80%D1%8B/">Игры</a>
	</td>
	<td>
		<a href="/55581-dead-trigger-2012-android">Dead Trigger (2012) Android</a>
	</td>
	<td class="td-size">14.55 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/AndroidFan/">AndroidFan</a>
	</td>
	<td>09.06.2012 16:38:21</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Мобилка Игры: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
"query": "king"

```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>
		<a href="/%D0%B8%D0%B3%D1%80%D1%8B/">Игры</a>,
		<a href="/%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D0%BA%D0%B0/">Мобилка</a>
	</td>
	<td>
		<a href="/110433-king-rsquo-s-empire-2014-android-rus">King’s Empire (2014) Android {RUS}</a>
	</td>
	<td class="td-size">48.89 Mb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/Andry875/">Andry875</a>
	</td>
	<td>30.06.2014 12:49:47</td>
	<td class="l1">0</td>
	<td class="l2">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=Игры Мобилка: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
"query": "2160p
```
CardigannIndexer (firebit): Error while parsing row '
<tr>
	<td>-</td>
	<td>
		<a href="/141725-%D0%B3%D1%83%D0%B1%D0%BA%D0%B0-%D0%B1%D0%BE%D0%B1-%D0%B2-%D0%B1%D0%B5%D0%B3%D0%B0%D1%85-2020-web-dl-2160p">Губка Боб в бегах (2020) WEB-DL 2160p</a>
	</td>
	<td class="td-size">11.14 Gb</td>
	<td class="au">
		<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/hb6/">hb6</a>
	</td>
	<td>07.11.2020 03:13:50</td>
	<td class="l1">55</td>
	<td class="l2">1</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1), div.article-indent div b, value=-: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531
```

**Comment by ngosang** [comment]
Empty query
```
CardigannIndexer (firebit): Error while parsing row '
<div id="post-id-141923">
	<div class="article clearfix">
		<div class="article-title-wrap">
			<div class="clearfix">
				<div class="article-title-tail">
					<span class="article-title">
						<a href="/141923-%D1%88%D0%BF%D0%B8%D0%BE%D0%BD-1-1-12-%D1%81%D0%B5%D1%80%D0%B8%D1%8F-%D0%B8%D0%B7-12-2020-satrip">Шпион №1 [1-12 серия из 12] (2020) SATRip</a>
					</span>
				</div>
			</div>
		</div>
		<div class="article-img-wrap">
			<a href="/141923-%D1%88%D0%BF%D0%B8%D0%BE%D0%BD-1-1-12-%D1%81%D0%B5%D1%80%D0%B8%D1%8F-%D0%B8%D0%B7-12-2020-satrip">
				<img class="img-item" alt="Шпион №1 [1-12 серия из 12] (2020) SATRip" src="http://i114.fastpic.ru/big/2020/1228/9d/745fcb17e0c4f752288adfb5882bf69d.jpg">
			</a>
		</div>
		<div class="article-indent">
			<div>
				<b>
					<a href="/%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB/">Сериалы</a>
				</b>
				»
				<a href="/%D0%B6%D0%B0%D0%BD%D1%80%D1%8B/%D0%B4%D0%B5%D1%82%D0%B5%D0%BA%D1%82%D0%B8%D0%B2/">Детектив</a>,
				<a href="/%D0%B6%D0%B0%D0%BD%D1%80%D1%8B/%D0%BF%D1%80%D0%B8%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F/">Приключения</a>,
				<a href="/%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE/satrip/">SATRip</a>
			</div>
			<div class="article-entry">
				<div id="post-body-id-141923">Два офицера внешней разведки на протяжении двух лет (с 1991 по 1992 гг.) участвуют в операции, цель которой обезопасить супершпиона советской, а потом и российской разведки – высокопоставленного руководителя одной из американских спецслужб (оперативный псевдоним «Киплинг»). ЦРУ и ФБР настойчиво ищут «крота» в своем руководстве, в ход идут все средства – шантаж, подкуп, убийства.<br>
					<br>
					<div class="kinopoisk1">
						<div class="ui-state-highlight kinopoisk2 ui-corner-all">
							<b>
								<a href="/goout.php?url=http://www.kinopoisk.ru/level/1/film/1183572/" target="_blank">КиноПоиск</a>
							</b>:<br>
							<span itemprop="ratingValue">0.00</span>
							<small>(<span itemprop="ratingCount">0</span>
								голосов)</small>
						</div>
						<div itemprop="aggregateRating" itemscope="" itemtype="http://schema.org/AggregateRating" class="ui-state-highlight kinopoisk2 ui-corner-all">
							<b>IMDB</b>:<br>
							<span>0.00</span>
							<small>(0 голосов)</small>
						</div>
					</div>
				</div>
			</div>
			<div class="article-meta meta-style-1 clearfix">
				<div class="article-meta-content">
					<ul class="meta-list">
						<li class="meta-item meta-name">
							<a href="/%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C/hb6/">hb6</a>
						</li>
						<li class="meta-item meta-date">30.12.2020 23:12:49</li>
					</ul>
					<ul class="meta-list">
						<li class="meta-item meta-fav">3238</li>
						<li class="meta-item meta-comments">
							<a href="/141923-%D1%88%D0%BF%D0%B8%D0%BE%D0%BD-1-1-12-%D1%81%D0%B5%D1%80%D0%B8%D1%8F-%D0%B8%D0%B7-12-2020-satrip#comments">0</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>':

System.Exception: Error while parsing field=size, selector=td.td-size, li.meta-size, value=<null>: Selector "td.td-size, li.meta-size" didn't match 
````
