### ISSUE TITLE
sukebei-pantsu: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8436]
"query": "pics"
"query": "españa"
"query": "flac"
"query": "pdf"

```
CardigannIndexer (sukebei-pantsu): Error while parsing row '
<tr id="torrent_14352" class="torrent-info ">
	<td class="tr-cat home-td">
		<div class="nyaa-cat sukebei-cat-26">
			<a href="/search?c=2_6" title="" class="category">
			</a>
		</div>
	</td>
	<td class="tr-name home-td" colspan="2">
		<a href="/view/14352">
			Yoko Miyamoto - Vintage Small Pics
		</a>
	</td>
	<td class="tr-links home-td">
		<a href="magnet:?xt=urn:btih:7A7328429F2A1B7CB9F03A8B82E89537B84ADF77&amp;dn=Yoko+Miyamoto+-+Vintage+Small+Pics&amp;tr=udp://tracker.uw0.xyz:6969/announce&amp;tr=udp://tracker.coppersurfer.tk:6969&amp;tr=udp://tracker.zer0day.to:1337/announce&amp;tr=udp://tracker.leechers-paradise.org:6969&amp;tr=udp://explodie.org:6969&amp;tr=udp://tracker.opentrackr.org:1337&amp;tr=udp://tracker.internetwarriors.net:1337/announce&amp;tr=http://mgtracker.org:6969/announce&amp;tr=udp://ipv6.leechers-paradise.org:6969/announce&amp;tr=http://nyaa.tracker.wf:7777/announce&amp;tr=http://sukebei.tracker.wf:7777/announce&amp;tr=http://tracker.anirena.com:80/announce&amp;tr=http://anidex.moe:6969/announce&amp;tr=udp://tracker.uw0.xyz:6969/announce&amp;tr=udp://tracker.coppersurfer.tk:6969&amp;tr=udp://tracker.zer0day.to:1337/announce&amp;tr=udp://tracker.leechers-paradise.org:6969&amp;tr=udp://explodie.org:6969&amp;tr=udp://tracker.opentrackr.org:1337&amp;tr=udp://tracker.internetwarriors.net:1337/announce&amp;tr=http://mgtracker.org:6969/announce&amp;tr=udp://ipv6.leechers-paradise.org:6969/announce&amp;tr=http://nyaa.tracker.wf:7777/announce&amp;tr=http://sukebei.tracker.wf:7777/announce&amp;tr=http://tracker.anirena.com:80/announce&amp;tr=http://anidex.moe:6969/announce" title="Magnet Link">
			<div class="icon-magnet"></div>
		</a>
		<a href="" title="Torrent file" class="hidden">
			<div class="icon-floppy"></div>
		</a>
	</td>
	<td class="tr-size home-td hide-xs">
		2.4 MiB
	</td>
	<td class="tr-se home-td hide-smol">0</td>
	<td class="tr-le home-td hide-smol">2</td>
	<td class="tr-dl home-td hide-xs">0</td>
	<td class="tr-date home-td date-short hide-xs" title="8/21/2009, 2:35:00 AM UTC+0">Aug 21, 2009</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=2_6: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
1 more:
"query": "louis"
```
CardigannIndexer (sukebei-pantsu): Error while parsing row '
<tr id="torrent_2304098" class="torrent-info ">
	<td class="tr-cat home-td">
		<div class="nyaa-cat sukebei-cat-616">
			<a href="/search?c=6_16" title="" class="category">
			</a>
		</div>
	</td>
	<td class="tr-name home-td" colspan="2">
		<a href="/view/2304098">
			Natsumi Louise - Rias Set
		</a>
	</td>
	<td class="tr-links home-td">
		<a href="magnet:?xt=urn:btih:18ABBA516E3EC8AB7E57EC591298F38BAC5F7DDD&amp;dn=Natsumi+Louise+-+Rias+Set&amp;tr=udp://tracker.uw0.xyz:6969/announce&amp;tr=udp://tracker.coppersurfer.tk:6969&amp;tr=udp://tracker.zer0day.to:1337/announce&amp;tr=udp://tracker.leechers-paradise.org:6969&amp;tr=udp://explodie.org:6969&amp;tr=udp://tracker.opentrackr.org:1337&amp;tr=udp://tracker.internetwarriors.net:1337/announce&amp;tr=http://mgtracker.org:6969/announce&amp;tr=udp://ipv6.leechers-paradise.org:6969/announce&amp;tr=http://nyaa.tracker.wf:7777/announce&amp;tr=http://sukebei.tracker.wf:7777/announce&amp;tr=http://tracker.anirena.com:80/announce&amp;tr=http://anidex.moe:6969/announce&amp;tr=udp://tracker.uw0.xyz:6969/announce&amp;tr=udp://tracker.coppersurfer.tk:6969&amp;tr=udp://tracker.zer0day.to:1337/announce&amp;tr=udp://tracker.leechers-paradise.org:6969&amp;tr=udp://explodie.org:6969&amp;tr=udp://tracker.opentrackr.org:1337&amp;tr=udp://tracker.internetwarriors.net:1337/announce&amp;tr=http://mgtracker.org:6969/announce&amp;tr=udp://ipv6.leechers-paradise.org:6969/announce&amp;tr=http://nyaa.tracker.wf:7777/announce&amp;tr=http://sukebei.tracker.wf:7777/announce&amp;tr=http://tracker.anirena.com:80/announce&amp;tr=http://anidex.moe:6969/announce" title="Magnet Link">
			<div class="icon-magnet"></div>
		</a>
		<a href="" title="Torrent file" class="hidden">
			<div class="icon-floppy"></div>
		</a>
	</td>
	<td class="tr-size home-td hide-xs">
		200.2 MiB
	</td>
	<td class="tr-se home-td hide-smol">1</td>
	<td class="tr-le home-td hide-smol">1</td>
	<td class="tr-dl home-td hide-xs">5</td>
	<td class="tr-date home-td date-short hide-xs" title="5/15/2017, 2:39:04 AM UTC+0">May 15, 2017</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=6_16: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
one more
"query": "xxx"
```
CardigannIndexer (nyaa-pantsu): Error while parsing row '
<tr id="torrent_975715" class="torrent-info ">
	<td class="tr-cat home-td">
		<div class="nyaa-cat nyaa-cat-2">
			<a href="/search?c=2_2" title="" class="category">
			</a>
		</div>
	</td>
	<td class="tr-name home-td" colspan="2">
		<a href="/view/975715">
			Xxx-AV 21496 ポルトガル産カントリー娘 滝川ソフィアの乳房ーvol.01
		</a>
	</td>
	<td class="tr-links home-td">
		<a href="magnet:?xt=urn:btih:06E6169776508D987D543BF1EB9AA000EF644763&amp;dn=Xxx-AV+21496+%E3%83%9D%E3%83%AB%E3%83%88%E3%82%AC%E3%83%AB%E7%94%A3%E3%82%AB%E3%83%B3%E3%83%88%E3%83%AA%E3%83%BC%E5%A8%98+%E6%BB%9D%E5%B7%9D%E3%82%BD%E3%83%95%E3%82%A3%E3%82%A2%E3%81%AE%E4%B9%B3%E6%88%BF%E3%83%BCvol.01&amp;tr=udp://tracker.uw0.xyz:6969/announce&amp;tr=udp://tracker.coppersurfer.tk:6969&amp;tr=udp://tracker.zer0day.to:1337/announce&amp;tr=udp://tracker.leechers-paradise.org:6969&amp;tr=udp://explodie.org:6969&amp;tr=udp://tracker.opentrackr.org:1337&amp;tr=udp://tracker.internetwarriors.net:1337/announce&amp;tr=http://mgtracker.org:6969/announce&amp;tr=udp://ipv6.leechers-paradise.org:6969/announce&amp;tr=http://nyaa.tracker.wf:7777/announce&amp;tr=http://sukebei.tracker.wf:7777/announce&amp;tr=http://tracker.anirena.com:80/announce&amp;tr=http://anidex.moe:6969/announce&amp;tr=udp://tracker.uw0.xyz:6969/announce&amp;tr=udp://tracker.coppersurfer.tk:6969&amp;tr=udp://tracker.zer0day.to:1337/announce&amp;tr=udp://tracker.leechers-paradise.org:6969&amp;tr=udp://explodie.org:6969&amp;tr=udp://tracker.opentrackr.org:1337&amp;tr=udp://tracker.internetwarriors.net:1337/announce&amp;tr=http://mgtracker.org:6969/announce&amp;tr=udp://ipv6.leechers-paradise.org:6969/announce&amp;tr=http://nyaa.tracker.wf:7777/announce&amp;tr=http://sukebei.tracker.wf:7777/announce&amp;tr=http://tracker.anirena.com:80/announce&amp;tr=http://anidex.moe:6969/announce" title="Magnet Link">
			<div class="icon-magnet"></div>
		</a>
		<a href="http://anicache.com/torrent/06E6169776508D987D543BF1EB9AA000EF644763.torrent" title="Torrent file" class="hidden">
			<div class="icon-floppy"></div>
		</a>
	</td>
	<td class="tr-size home-td hide-xs">
		2.2 GiB
	</td>
	<td class="tr-se home-td hide-smol">3</td>
	<td class="tr-le home-td hide-smol">1</td>
	<td class="tr-dl home-td hide-xs">27</td>
	<td class="tr-date home-td date-short hide-xs" title="8/21/2017, 4:29:28 PM UTC+0">Aug 21, 2017</td>
</tr>':

System.Exception: Error while parsing field=category, selector=td:nth-child(1) a, value=2_2: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```
