### ISSUE TITLE
torrentbomb: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8437]
"query": "pics"
"query": "mp3"
"query": "pdf"
"query": "apk"
"query": "adobe illustrator"

```
CardigannIndexer (torrentbomb): Error while parsing row '
<li>
	<div class="sch_tit">
		<a href="bbs/./board.php?bo_table=torrent_etc&amp;wr_id=1344" class="sch_res_title">토렌트 기타 - Keeley Hazell Sexy
			<b class="sch_word">Pics</b>
		</a>
		<a href="bbs/./board.php?bo_table=torrent_etc&amp;wr_id=1344" target="_blank" class="pop_a">
			<i class="fa fa-share-square-o" aria-hidden="true"></i>새창</a>
	</div>
	<div class="sch_info">
		<span class="sch_datetime">
			<i class="fa fa-clock-o" aria-hidden="true"></i>
			2019-11-02 00:26:34</span>
	</div>
</li>':

System.Exception: Error while parsing field=category, selector=a[href^="bbs/./board.php?"], value=torrent_etc: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (torrentbomb): Error while parsing row '
<li>
	<div class="sch_tit">
		<a href="bbs/./board.php?bo_table=torrent_etc&amp;wr_id=5833" class="sch_res_title">토렌트 기타 - dakota johnson can be my 50 shades of anything 38
			<b class="sch_word">pics</b>
			이미지</a>
		<a href="bbs/./board.php?bo_table=torrent_etc&amp;wr_id=5833" target="_blank" class="pop_a">
			<i class="fa fa-share-square-o" aria-hidden="true"></i>새창</a>
	</div>
	<div class="sch_info">
		<span class="sch_datetime">
			<i class="fa fa-clock-o" aria-hidden="true"></i>
			2019-11-02 00:26:34</span>
	</div>
</li>':

System.Exception: Error while parsing field=category, selector=a[href^="bbs/./board.php?"], value=torrent_etc: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (torrentbomb): Error while parsing row '
<li>
	<div class="sch_tit">
		<a href="bbs/./board.php?bo_table=torrent_etc&amp;wr_id=5835" class="sch_res_title">토렌트 기타 - boobs in gold bikinis because yay boobies 23
			<b class="sch_word">pics</b>
			이미지</a>
		<a href="bbs/./board.php?bo_table=torrent_etc&amp;wr_id=5835" target="_blank" class="pop_a">
			<i class="fa fa-share-square-o" aria-hidden="true"></i>새창</a>
	</div>
	<div class="sch_info">
		<span class="sch_datetime">
			<i class="fa fa-clock-o" aria-hidden="true"></i>
			2019-11-02 00:26:34</span>
	</div>
</li>':

System.Exception: Error while parsing field=category, selector=a[href^="bbs/./board.php?"], value=torrent_etc: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592

CardigannIndexer (torrentbomb): Error while parsing row '
<li>
	<div class="sch_tit">
		<a href="bbs/./board.php?bo_table=torrent_etc&amp;wr_id=7213" class="sch_res_title">토렌트 기타 - sexy emilia clarke can train my dragon anytime 37 hot
			<b class="sch_word">pics</b>
			이미지</a>
		<a href="bbs/./board.php?bo_table=torrent_etc&amp;wr_id=7213" target="_blank" class="pop_a">
			<i class="fa fa-share-square-o" aria-hidden="true"></i>새창</a>
	</div>
	<div class="sch_info">
		<span class="sch_datetime">
			<i class="fa fa-clock-o" aria-hidden="true"></i>
			2019-11-02 00:26:34</span>
	</div>
</li>':

System.Exception: Error while parsing field=category, selector=a[href^="bbs/./board.php?"], value=torrent_etc: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
"query": "epub"
```
CardigannIndexer (torrentbomb): Error while parsing row '
<li>
	<div class="sch_tit">
		<a href="bbs/./board.php?bo_table=book&amp;wr_id=18" class="sch_res_title">도서류 - (소설) [김도경] 프로파일러Ⅱ 에페타(éfeta) 1-89完 [공금] RB//연재물 삽화 정리
			<b class="sch_word">epub</b>
			2탄</a>
		<a href="bbs/./board.php?bo_table=book&amp;wr_id=18" target="_blank" class="pop_a">
			<i class="fa fa-share-square-o" aria-hidden="true"></i>새창</a>
	</div>
	<div class="sch_info">
		<span class="sch_datetime">
			<i class="fa fa-clock-o" aria-hidden="true"></i>
			2020-02-13 12:31:20</span>
	</div>
</li>':

System.Exception: Error while parsing field=category, selector=a[href^="bbs/./board.php?"], value=book: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by ngosang** [comment]
"query": ""
```
CardigannIndexer (torrentbomb): Error while parsing row '
<li>
	<div class="sch_tit">
		<a href="bbs/./board.php?bo_table=out_1&amp;wr_id=7114" class="sch_res_title">out_1 - 깜짝...K<b class="sch_word">-</b>강제노역</a>
		<a href="bbs/./board.php?bo_table=out_1&amp;wr_id=7114" target="_blank" class="pop_a">
			<i class="fa fa-share-square-o" aria-hidden="true"></i>새창</a>
	</div>
	<div class="sch_info">
		<span class="sch_datetime">
			<i class="fa fa-clock-o" aria-hidden="true"></i>
			2020-12-16 12:05:02</span>
	</div>
</li>':

System.Exception: Error while parsing field=category, selector=a[href^="bbs/./board.php?"], value=out_1: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1533
```
