### ISSUE TITLE
Error Searching TVChaosUK

### ISSUE THREAD

**Issue by mitchmiller** [Jackett/Jackett#847]
I'm seeing the following error when searching TVChaosUK. It happens if I try a manual search in Jakett or a search from Sonarr. In the case of Sonarr the indexer is blacklisted after several attempts. The searched for files do exist at TVChaosUK.

12-13 09:23:59 Info Found 50 (1 new) releases from TV Chaos
12-13 10:08:35 Info Found 50 (5 new) releases from TV Chaos
12-13 10:08:58 Error Failed download response:

12-13 10:08:58 Error Error downloading tvchaosuk https://www.tvchaosuk.com/download.php?id=150330 System.Exception: Remote server returned Redirect
   at Jackett.Indexers.BaseIndexer.<Download>d__63.MoveNext() in C:\projects\jackett\src\Jackett\Indexers\BaseIndexer.cs:line 309
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.DownloadController.<Download>d__4.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\DownloadController.cs:line 53

**Comment by kaso17** [comment]
Can you download the file https://www.tvchaosuk.com/download.php?id=150330) manually via your browser?

**Comment by kaso17** [comment]
Please try v0.7.805.
It won't fix the problem but should print the redirect destination when downloading.

**Comment by mitchmiller** [comment]
Here's the log for the search only. Don't think there's any cookie info in it:

2016-12-15 15:54:23.6688 Info http://localhost:8097/Admin/search 
2016-12-15 15:54:23.6988 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2016-12-15 15:54:23.7313 Info DefaultHttpControllerSelector SelectController Admin 
2016-12-15 15:54:23.7606 Info HttpControllerDescriptor CreateController 
2016-12-15 15:54:23.7866 Info DefaultHttpControllerActivator Create 
2016-12-15 15:54:23.8136 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2016-12-15 15:54:23.8387 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2016-12-15 15:54:23.8627 Info AdminController ExecuteAsync 
2016-12-15 15:54:23.8867 Info ApiControllerActionSelector SelectAction 
2016-12-15 15:54:23.9117 Info ApiControllerActionSelector SelectAction Selected action 'Search(AdminSearch value)' 
2016-12-15 15:54:23.9377 Info JackettAuthorizedAttribute OnAuthorizationAsync 
2016-12-15 15:54:23.9608 Info JackettAuthorizedAttribute OnAuthorizationAsync 
2016-12-15 15:54:23.9838 Info HttpActionBinding ExecuteBindingAsync 
2016-12-15 15:54:24.0058 Info FormatterParameterBinding ExecuteBindingAsync Binding parameter 'value' 
2016-12-15 15:54:24.0298 Info JQueryMvcFormUrlEncodedFormatter ReadFromStreamAsync Type='AdminSearch', content-type='application/x-www-form-urlencoded; charset=UTF-8' 
2016-12-15 15:54:24.0529 Error JQueryMvcFormUrlEncodedFormatter ReadFromStreamAsync A value is required. 
2016-12-15 15:54:24.0759 Info JQueryMvcFormUrlEncodedFormatter ReadFromStreamAsync Value read='Jackett.Models.AdminSearch' 
2016-12-15 15:54:24.1019 Info FormatterParameterBinding ExecuteBindingAsync Parameter 'value' bound to the value 'Jackett.Models.AdminSearch' 
2016-12-15 15:54:24.1249 Info HttpActionBinding ExecuteBindingAsync Model state is invalid. value.Category: A value is required. 
2016-12-15 15:54:24.1499 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Search(AdminSearch value)' 
2016-12-15 15:54:24.1739 Info JackettAPINoCacheAttribute OnActionExecutingAsync 
2016-12-15 15:54:24.1989 Info ApiControllerActionInvoker InvokeActionAsync Action='Search(value=Jackett.Models.AdminSearch)' 
2016-12-15 15:54:24.2229 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Search(value=Jackett.Models.AdminSearch)' 
2016-12-15 15:54:24.2480 Debug IWebClient.GetString(Url:https://www.tvchaosuk.com/browse.php) 
2016-12-15 15:54:24.9373 Debug IWebClient: Returning Redirect => https://www.tvchaosuk.com/login.php?returnto=%2Fbrowse.php 
2016-12-15 15:54:24.9938 Info Manual search for "Humans" on TV Chaos with 0 results. 
2016-12-15 15:54:25.0208 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'Jackett.ManualSearchResult' 
2016-12-15 15:54:25.0468 Info DefaultContentNegotiator Negotiate Type='ManualSearchResult', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer] 
2016-12-15 15:54:25.0698 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='ManualSearchResult', mediaType='application/json; charset=utf-8' 
2016-12-15 15:54:25.0918 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter 
2016-12-15 15:54:25.1128 Info DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8' 
2016-12-15 15:54:25.1328 Info ApiControllerActionInvoker InvokeActionAsync 
2016-12-15 15:54:25.1518 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Search(AdminSearch value)' 
2016-12-15 15:54:25.1738 Info JackettAPINoCacheAttribute OnActionExecutedAsync 
2016-12-15 15:54:25.1928 Info AdminController ExecuteAsync 
2016-12-15 15:54:25.2148 Info Content-type='application/json; charset=utf-8', content-length=unknown 
2016-12-15 15:54:25.2358 Info JsonMediaTypeFormatter WriteToStreamAsync Value='Jackett.ManualSearchResult', type='ManualSearchResult', content-type='application/json; charset=utf-8' 
2016-12-15 15:54:25.2568 Info JsonMediaTypeFormatter WriteToStreamAsync 
2016-12-15 15:54:25.2768 Info AdminController Dispose 
2016-12-15 15:54:25.3078 Info AdminController Dispose 
2016-12-15 15:54:25.3668 Info http://localhost:8097/images/sort_both.png 
2016-12-15 15:54:25.3878 Info DefaultContentNegotiator Negotiate Type='HttpError', formatters=[JsonMediaTypeFormatterTracer, XmlMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer] 
2016-12-15 15:54:25.4069 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Obtaining formatter of type 'JsonMediaTypeFormatter' for type='HttpError', mediaType='application/json; charset=utf-8' 
2016-12-15 15:54:25.4258 Info JsonMediaTypeFormatter GetPerRequestFormatterInstance Will use same 'JsonMediaTypeFormatter' formatter 
2016-12-15 15:54:25.4448 Info DefaultContentNegotiator Negotiate Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8' 
2016-12-15 15:54:25.4614 Info Content-type='application/json; charset=utf-8', content-length=unknown

**Comment by kaso17** [comment]
The initial log indicated that search is working and just downloading didn't work.
The last log shows that search isn't working either.
Please try to remove/re-add the indexer.

**Comment by mitchmiller** [comment]
The problem is the search. If results are found they can be downloaded OK. I removed and re-added TVChaosUK, as you suggested and searches began working OK for about 24 hours then the issue started again with the same log messages as my previous post. It looks like just displaying the TVChaosUK configuration box and clicking OK will fix the issue for a while before failing again.

**Comment by kaso17** [comment]
Do you have an dynamic IP?
Then it might break on IP change.
Which version are you running, in the latest it should automatically login again. In your log it doesn't look like it does that.

**Comment by mitchmiller** [comment]
Yes, it's a VPN and is dynamic. I was running Version 0.7.807.0 but I've just upgraded to 0.7.817.0. I will re-add TVChaosuk and then switch my VPN IP a few times. I'll let you know how it works.. 

Thanks

**Comment by mitchmiller** [comment]
I've gone through several IP address changes and TVChaosUK is now working perfectly. I think 7.817.0 might have fixed things.

Thanks for your help.
