### ISSUE TITLE
[milkie] Parse error (Config)

### ISSUE THREAD

**Issue by edrock200** [Jackett/Jackett#8533]
Apologies if this has already been addressed. A search for "milkie" yielded no results. This issue is an error I'm getting when attempting to add the milkie.cc tracker to Jackett.

### Environment

**OS**:
Host: Ubuntu 18.04 with latest patches as of 5/4/2020
Jackett running in docker, latest production version (not edge)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
It's a docker container, so I'm not sure.

**.Net Version**:
See note above

**Jackett Version**:
0.16.284.0 (Docker)

**Last Working Jackett Version**:
This is the first time I've attempted to use this tracker, so only tried in 0.16.284.0, but as a test I tried pulling 0.16.105.0 and same result.

**Are you using a proxy or VPN?** [yes/no]
No
### Description

Go to Jackett web interface.
Add tracker Milkie.cc
Paste in API key
Click OK
Message pops up that an error has occured with a link to create a ticket here.

### Logged Error Messages

From the Jackett logs:

```
2020-05-04 11:41:54	Error	
Jackett.Common.ExceptionWithConfigData: Parse error
   at Jackett.Common.Indexers.Milkie.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Milkie.cs:line 67
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
2020-05-04 11:41:54	Error	
Error on 20200504174154 for Milkie.txtSystem.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Milkie.PerformQuery(TorznabQuery query)
```

Thank you in advance for any help!
-Ed

**Comment by edrock200** [comment]
Disregard. I'm a moron. Was using RSS key instead of API key. My apologies.
