### ISSUE TITLE
Tracker Search Failing

### ISSUE THREAD

**Issue by pegatron89** [Jackett/Jackett#8549]
### Environment

**OS**: Rasbian Buster

**.Net Runtime**:

**.Net Version**:

**Jackett Version**: Jackett Version 0.16.304.0 CoreLinuxArm32

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

I am getting an error which is not allowing me to search for movies. It says i am no longer logged in but to check the cookie. This works fine on Sonarr but not Radarr, I thought it was an issue with Radarr but they said it was an issue with jackett ([See here](https://github.com/Radarr/Radarr/issues/4395))

### Logged Error Messages

An error occurred while processing feed. http://192.168.0.33:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=anymovie: Torznab error detected: Jackett.Common.IndexerException: Exception (scenetime): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
---> System.Exception: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

I am logged in fine as i use Jackett, Which speaks to Sonarr without any issues and im using the exact same URL in both bits of software.

Full log
[log.txt](https://github.com/Jackett/Jackett/files/4585776/log.txt)

**Comment by garfield69** [comment]
I am seeing something similar.
I am using Radarr 0.2.0.1480 which is the latest pre-release available of this app.
when I search using Radarr with the Jackett scenetime indexer for the movie **captain america: civil war** jackett receives two queries:
```
2020-05-07 09:35:59.0184 Debug Connection id "0HLVI09KLR377" accepted. 
2020-05-07 09:35:59.0184 Debug Connection id "0HLVI09KLR377" started. 
2020-05-07 09:35:59.0184 Info Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=****redacted****&offset=0&limit=100&q=captain%20america%203%202016   
2020-05-07 09:35:59.0184 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=****redacted****&offset=0&limit=100&q=captain%20america%203%202016 
2020-05-07 09:35:59.0184 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=****redacted****&offset=0&limit=100&q=captain%20america%203%202016 
2020-05-07 09:35:59.0184 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=****redacted****&offset=0&limit=100&q=captain%20america%203%202016 
2020-05-07 09:35:59.0184 Debug The request path /api/v2.0/indexers/scenetime/results/torznab/api does not match a supported file type 
2020-05-07 09:35:59.0184 Debug AuthenticationScheme: Cookies was not authenticated. 
2020-05-07 09:35:59.0184 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/scenetime/results/torznab/api' 
2020-05-07 09:35:59.0184 Debug Endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerId}/results/Torznab/{ignored?}' is valid for the request path '/api/v2.0/indexers/scenetime/results/torznab/api' 
2020-05-07 09:35:59.0184 Debug Request matched endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole)' 
2020-05-07 09:35:59.0184 Info Executing endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole)' 
2020-05-07 09:35:59.0184 Info Route matched with {action = "Torznab", controller = "Results"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Torznab(Jackett.Common.Models.DTO.TorznabRequest) on controller Jackett.Server.Controllers.ResultsController (JackettConsole). 
2020-05-07 09:35:59.0184 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2020-05-07 09:35:59.0184 Debug Execution plan of resource filters (in the following order): None 
2020-05-07 09:35:59.0184 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresApiKey, Jackett.Server.Controllers.RequiresConfiguredIndexer, Jackett.Server.Controllers.RequiresValidQuery 
2020-05-07 09:35:59.0184 Debug Execution plan of exception filters (in the following order): None 
2020-05-07 09:35:59.0184 Debug Execution plan of result filters (in the following order): None 
2020-05-07 09:35:59.0184 Debug Executing controller factory for controller Jackett.Server.Controllers.ResultsController (JackettConsole) 
2020-05-07 09:35:59.0184 Debug Executed controller factory for controller Jackett.Server.Controllers.ResultsController (JackettConsole) 
2020-05-07 09:35:59.0184 Debug Attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest' ... 
2020-05-07 09:35:59.0184 Debug Attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest' using the name '' in request data ... 
2020-05-07 09:35:59.0184 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.t' of type 'System.String' using the name 't' in request data ... 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.t' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.q' of type 'System.String' using the name 'q' in request data ... 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.q' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.cat' of type 'System.String' using the name 'cat' in request data ... 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.cat' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'imdbid' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.imdbid' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.imdbid' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.extended' of type 'System.String' using the name 'extended' in request data ... 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.extended' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.limit' of type 'System.String' using the name 'limit' in request data ... 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.limit' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.offset' of type 'System.String' using the name 'offset' in request data ... 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.offset' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'rid' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.rid' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.rid' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'season' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.season' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.season' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'ep' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.ep' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.ep' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'album' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.album' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.album' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'artist' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.artist' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.artist' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'label' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.label' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.label' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'track' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.track' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.track' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'year' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.year' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.year' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'genre' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.genre' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.genre' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Could not find a value in the request with name 'configured' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.configured' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.configured' of type 'System.String'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest'. 
2020-05-07 09:35:59.0184 Debug Done attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest'. 
2020-05-07 09:35:59.0184 Debug Attempting to validate the bound parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest' ... 
2020-05-07 09:35:59.0344 Debug Done attempting to validate the bound parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest'. 
2020-05-07 09:35:59.0344 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://www.scenetime.com/browse.php?cata=yes&sec=jax&c1=1&c3=1&c47=1&c56=1&c57=1&c59=1&c61=1&c64=1&c80=1&c81=1&c82=1&c102=1&c22=1&c105=1&c16=1&c17=1&search=captain+america+3+2016) 
2020-05-07 09:36:04.2788 Debug WebClient(HttpWebClient2NetCore): Returning OK => <!DOCTYPE html >
[html redacted] 
2020-05-07 09:36:04.3705 Info Found 4 releases from SceneTime for: captain america 3 2016 
2020-05-07 09:36:04.3705 Info Executing ContentResult with HTTP Response ContentType of application/rss+xml; charset=utf-8 
2020-05-07 09:36:04.3705 Debug Response compression is not enabled for the Content-Type 'application/rss+xml'. 
2020-05-07 09:36:04.3705 Info Executed action Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole) in 5348.1065ms 
2020-05-07 09:36:04.3705 Debug Connection id "0HLVI09KLR377" received FIN. 
2020-05-07 09:36:04.3705 Info Executed endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole)' 
2020-05-07 09:36:04.3705 Debug Connection id "0HLVI09KLR377" sending FIN because: "The client closed the connection." 
2020-05-07 09:36:04.3705 Debug Connection id "0HLVI09KLR377" disconnecting. 
2020-05-07 09:36:04.3705 Info Request finished in 5354.8633ms 200 application/rss+xml; charset=utf-8 
2020-05-07 09:36:04.3705 Debug Connection id "0HLVI09KLR377" stopped. 
2020-05-07 09:36:04.3705 Debug Connection id "0HLVI09KLR378" accepted. 
2020-05-07 09:36:04.3705 Debug Connection id "0HLVI09KLR378" started. 
2020-05-07 09:36:04.3705 Info Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=****redacted****&offset=0&limit=100&q=captain%20america%203%20civil%20war%202016   
2020-05-07 09:36:04.3705 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=****redacted****&offset=0&limit=100&q=captain%20america%203%20civil%20war%202016 
2020-05-07 09:36:04.3705 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=****redacted****&offset=0&limit=100&q=captain%20america%203%20civil%20war%202016 
2020-05-07 09:36:04.3705 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060,2070,2080&extended=1&apikey=****redacted****&offset=0&limit=100&q=captain%20america%203%20civil%20war%202016 
2020-05-07 09:36:04.3705 Debug The request path /api/v2.0/indexers/scenetime/results/torznab/api does not match a supported file type 
2020-05-07 09:36:04.3705 Debug AuthenticationScheme: Cookies was not authenticated. 
2020-05-07 09:36:04.3705 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/scenetime/results/torznab/api' 
2020-05-07 09:36:04.3705 Debug Endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerId}/results/Torznab/{ignored?}' is valid for the request path '/api/v2.0/indexers/scenetime/results/torznab/api' 
2020-05-07 09:36:04.3786 Debug Request matched endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole)' 
2020-05-07 09:36:04.3786 Info Executing endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole)' 
2020-05-07 09:36:04.3786 Info Route matched with {action = "Torznab", controller = "Results"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Torznab(Jackett.Common.Models.DTO.TorznabRequest) on controller Jackett.Server.Controllers.ResultsController (JackettConsole). 
2020-05-07 09:36:04.3786 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2020-05-07 09:36:04.3786 Debug Execution plan of resource filters (in the following order): None 
2020-05-07 09:36:04.3786 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresApiKey, Jackett.Server.Controllers.RequiresConfiguredIndexer, Jackett.Server.Controllers.RequiresValidQuery 
2020-05-07 09:36:04.3786 Debug Execution plan of exception filters (in the following order): None 
2020-05-07 09:36:04.3786 Debug Execution plan of result filters (in the following order): None 
2020-05-07 09:36:04.3786 Debug Executing controller factory for controller Jackett.Server.Controllers.ResultsController (JackettConsole) 
2020-05-07 09:36:04.3786 Debug Executed controller factory for controller Jackett.Server.Controllers.ResultsController (JackettConsole) 
2020-05-07 09:36:04.3786 Debug Attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest' ... 
2020-05-07 09:36:04.3786 Debug Attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest' using the name '' in request data ... 
2020-05-07 09:36:04.3786 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.t' of type 'System.String' using the name 't' in request data ... 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.t' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.q' of type 'System.String' using the name 'q' in request data ... 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.q' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.cat' of type 'System.String' using the name 'cat' in request data ... 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.cat' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'imdbid' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.imdbid' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.imdbid' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.extended' of type 'System.String' using the name 'extended' in request data ... 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.extended' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.limit' of type 'System.String' using the name 'limit' in request data ... 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.limit' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.offset' of type 'System.String' using the name 'offset' in request data ... 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.offset' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'rid' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.rid' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.rid' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'season' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.season' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.season' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'ep' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.ep' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.ep' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'album' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.album' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.album' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'artist' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.artist' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.artist' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'label' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.label' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.label' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'track' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.track' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.track' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'year' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.year' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.year' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'genre' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.genre' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.genre' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Could not find a value in the request with name 'configured' for binding property 'Jackett.Common.Models.DTO.TorznabRequest.configured' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind property 'Jackett.Common.Models.DTO.TorznabRequest.configured' of type 'System.String'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest'. 
2020-05-07 09:36:04.3786 Debug Done attempting to bind parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest'. 
2020-05-07 09:36:04.3786 Debug Attempting to validate the bound parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest' ... 
2020-05-07 09:36:04.3786 Debug Done attempting to validate the bound parameter 'request' of type 'Jackett.Common.Models.DTO.TorznabRequest'. 
2020-05-07 09:36:04.3786 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://www.scenetime.com/browse.php?cata=yes&sec=jax&c1=1&c3=1&c47=1&c56=1&c57=1&c59=1&c61=1&c64=1&c80=1&c81=1&c82=1&c102=1&c22=1&c105=1&c16=1&c17=1&search=captain+america+3+civil+war+2016) 
2020-05-07 09:36:04.8467 Debug WebClient(HttpWebClient2NetCore): Returning OK => Try again in 10 seconds, slow down geek!!! 
2020-05-07 09:36:04.8476 Error Jackett.Common.IndexerException: Exception (scenetime): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
 ---> System.Exception: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
   at Jackett.Common.Indexers.SceneTime.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 193
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 799
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 370 Jackett.Common.IndexerException: Exception (scenetime): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
 ---> System.Exception: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
   at Jackett.Common.Indexers.SceneTime.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 193
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 799
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 370
2020-05-07 09:36:04.8476 Info Executing ContentResult with HTTP Response ContentType of application/xml; charset=utf-8 
2020-05-07 09:36:04.8476 Debug The response will be compressed with 'gzip'. 
2020-05-07 09:36:04.8476 Info Executed action Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole) in 472.7484ms 
2020-05-07 09:36:04.8476 Info Executed endpoint 'Jackett.Server.Controllers.ResultsController.Torznab (JackettConsole)' 
2020-05-07 09:36:04.8476 Info Request finished in 477.6706ms 200 application/xml; charset=utf-8 
2020-05-07 09:36:04.8476 Debug Connection id "0HLVI09KLR378" received FIN. 
2020-05-07 09:36:04.8476 Debug Connection id "0HLVI09KLR378" disconnecting. 
2020-05-07 09:36:04.8476 Debug Connection id "0HLVI09KLR378" sending FIN because: "The client closed the connection." 
2020-05-07 09:36:04.8476 Debug Connection id "0HLVI09KLR378" stopped. 
```

the first query for q=captain%20america%203%202016 at  2020-05-07 09:35:59.0184
is successful and returns 4 results
the second query a second later for q=captain%20america%203%20civil%20war%202016 at  2020-05-07 09:36:04.3705 
fails because scenetime complains that we are making another request too soon and responds with 
 `Try again in 10 seconds, slow down geek!!!` 

so the problem here is that because Radarr is making two requests for every movie search, and because scenetime has a one request per 10 seconds rule, the second request is rejected.
this causes Radarr to flag its scenetime indexer has having generated and error and leads to it disabling the indexer.

I am unsure what can be done about this. @ngosang  @cadatoiva  your input please.
Thanks.

**Comment by ngosang** [comment]
The message is misleading. The problem is because it can't find any result. For example => https://www.scenetime.com/browse.php?search=123456

**Comment by garfield69** [comment]
Jackett 0.16.324
