### ISSUE TITLE
[Bug] Canno configure Blu-bits (v0.7.806)

### ISSUE THREAD

**Issue by armani316** [Jackett/Jackett#855]
This only started after updating to v0.7.806. I am able to find results if I search Blu-bits using Jackett, but for some reason, it won't pass the test:

2016-12-15 10:17:17.8815 Info   http://127.0.0.1:9117/Admin/test_indexer 
2016-12-15 10:17:17.8815 Info DefaultHttpControllerSelector SelectController Route='MS_SubRoutes:System.Web.Http.Routing.IHttpRouteData[]' 
2016-12-15 10:17:17.8815 Info DefaultHttpControllerSelector SelectController Admin 
2016-12-15 10:17:17.8815 Info HttpControllerDescriptor CreateController  
2016-12-15 10:17:17.8971 Info DefaultHttpControllerActivator Create  
2016-12-15 10:17:17.8971 Info DefaultHttpControllerActivator Create Jackett.Controllers.AdminController 
2016-12-15 10:17:17.8971 Info HttpControllerDescriptor CreateController Jackett.Controllers.AdminController 
2016-12-15 10:17:17.8971 Info AdminController ExecuteAsync  
2016-12-15 10:17:17.8971 Info ApiControllerActionSelector SelectAction  
2016-12-15 10:17:17.9128 Info ApiControllerActionSelector SelectAction Selected action 'Test()' 
2016-12-15 10:17:17.9128 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-12-15 10:17:17.9128 Info JackettAuthorizedAttribute OnAuthorizationAsync  
2016-12-15 10:17:17.9128 Info HttpActionBinding ExecuteBindingAsync  
2016-12-15 10:17:17.9284 Info HttpActionBinding ExecuteBindingAsync  
2016-12-15 10:17:17.9284 Info JackettAPINoCacheAttribute OnActionExecutingAsync Action filter for 'Test()' 
2016-12-15 10:17:17.9440 Info JackettAPINoCacheAttribute OnActionExecutingAsync  
2016-12-15 10:17:17.9505 Info ApiControllerActionInvoker InvokeActionAsync Action='Test()' 
2016-12-15 10:17:17.9505 Info ReflectedHttpActionDescriptor ExecuteAsync Invoking action 'Test()' 
2016-12-15 10:17:17.9505 Debug IWebClient.GetString(Url:https://blu-bits.com/index.php?&search=&page=torrents&options=0&active=0) 
2016-12-15 10:17:19.7690 Debug IWebClient: Returning OK => <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Blu-bits: The High Definition Community .::. Index</title>
<if:HAS_GA>
<script type="text/javascript">
//<![CDATA[
try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:0,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok3v=1613a3a185/"},atok:"cda05d94c7b8ab07abdf3c44f27a263e",petok:"15d5ad63983161f0dec42cd9de3bd4ac115af73a-1481786240-1800",zone:"blu-bits.com",rocket:"a",apps:0}];document.write('<script type="text/javascript" src="//ajax.cloudflare.com/cdn-cgi/nexp/dok3v=f2befc48d1/cloudflare.min.js"><'+'\/script>');}}catch(e){};
//]]>
</script>
<script type="text/rocketscript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/rocketscript">
try {
var pageTracker = _gat._getTracker("analitic");
pageTracker._trackPageview();
} catch(err) {}</script>
</if:HAS_GA>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<link rel="stylesheet" href="https://blu-bits.com/style/Blue/main.css" type="text/css"/>

<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/ajax.js"></script>
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/ajax-poller.js"></script>
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/xbtit.js"></script>
 
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/animatedcollapse.js"></script>
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/1.4.2_jquery.min.js"></script>
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/jquery.min.js"></script>
 
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/jquery.js"></script>
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/interface.js"></script>
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/prototype.js"></script>
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/overlib.js"></script>
<script type="text/rocketscript" data-rocketsrc="https://blu-bits.com/jscript/TorrentName.js"></script>
<script language="JavaScript" data-rocketsrc="https://blu-bits.com/jscript/jq.js" type="text/rocketscript"></script>
<script language="JavaScript" data-rocketsrc="https://blu-bits.com/jscript/jq.color.js" type="text/rocketscript"></script>
<script type="text/rocketscript" data-rocketsrc='jscript/jquery-latest.min.js'></script>
<script type="text/rocketscript" data-rocketsrc='jscript/jquery.jqDock.min.js'></script>
<script type="text/rocketscript" data-rocketsrc='jscript/jquery.jqDock.js'></script>
<script type="text/rocketscript">

animatedcollapse.addDiv('header', ',hide=0,fade=1,speed=1000,persist=1')
animatedcollapse.addDiv('bottom_menu', 'hide=0,fade=1,speed=1000,persist=1')

//persist(1) uses a cookie to remember the toggled block either opened or closed and will remain in that state across your pages
//grouped like in the example below causes if you click to open one the other block(s) close
//examples of other traits  'fade=1,speed=1000,group=blocks,persist=1,hide=1')

animatedcollapse.ontoggle=function($, divobj, state){ //fires each time a DIV is expanded/contracted
	//$: Access to jQuery
	//divobj: DOM reference to DIV being expanded/ collapsed. Use "divobj.id" to get its ID
	//state: "block" or "none", depending on state which is also (hide, 0 or 1) = (0)=("block" is opened) (1)=("none" is closed)
	//alert("1) DIV ID: " + divobj.id + "\n2) Current State: "+state)
}

animatedcollapse.init()

</script>

<body>
<tag:season/>
<div id="main">
 
<if:HAS_AT>
<br/> <center> <tag:advertop/> </center>
</if:HAS_AT>
<br/>
 
<div id="slideIt">
<div id="header">
<table width="100%" align="center" cellpadding="0" cellspacing="0" border="0">
<tr>
<td valign="top" width="5" rowspan="2"></td>
<td valign="top"><div><div class="block">
<div class="block-head">
<div class="block-head-title"></div>
</div>
<div class="block-content">
<div align="justify" class="b-content"><head>
<script type="text/rocketscript">

var timeout         = 500;
var closetimer		= 0;
var ddmenuitem      = 0;

// open hidden layer
function mopen(id)
{	
	// cancel close timer
	mcancelclosetime();

	// close old layer
	if(ddmenuitem) ddmenuitem.style.visibility = 'hidden';

	// get new layer and show it
	ddmenuitem = document.getElementById(id);
	ddmenuitem.style.visibility = 'visible';

}
// close showed layer
function mclose()
{
	if(ddmenuitem) ddmenuitem.style.visibility = 'hidden';
}

// go close timer
function mclosetime()
{
	closetimer = window.setTimeout(mclose, timeout);
}

// cancel close timer
function mcancelclosetime()
{
	if(closetimer)
	{
		window.clearTimeout(closetimer);
		closetimer = null;
	}
}

// close layer when click-out
document.onclick = mclose; 
// -->

global $CURUSER, $FORUMLINK, $db_prefix,$XBTT_USE,$btit_settings, $ipb_prefix;

if($btit_settings["fmhack_invitation_system"]=="enabled")
    global $INVITATIONSON;

  if (isset($CURUSER) && $CURUSER && $CURUSER["uid"]>1)
  {
  print("<form name=\"jump1\" action=\"index.php\" method=\"post\">\n");
?>
<script type="text/javascript">
function newpm() {

var answer = confirm ("You have a new PM!")
if (answer)
window.location='index.php?page=usercp&uid=<? echo $CURUSER["uid"]; ?>&do=pm&action=list'

}
</script>
</head>
<form name="jump1" action="index.php?page=login" method="post">
<div id="mainmenu">
<div id="left"><ul><li><a href="index.php" style="font-size:52px;"><img border="0" alt="logo" src="/images/blubitslogo.png" height="105"></a></li></ul><ul>
 
 </ul></div>
<div id="center"> 
</b></font></li>
 
<center>
<li><font color="#FFF"> 
<a href="https://blu-bits.com/index.php?page=forum&action=viewtopic&topicid=232">
<img src="https://s22.postimg.org/kwqnp1v0h/BB_Banner33.png" alt="Torrent of the Week" style="height:85px;"><br>
</a></center>
</b></font></li>
<li><font color="#8C001A"><center><b></b></center></font></li></div>
<div id="right"><ul>
<li><a href="index.php">Home</a></li>
<li><a href="index.php?page=torrents">Torrents</a></li>
<li><a href="index.php?page=extra-stats">Extra Stats</a></li>
<li><a href="index.php?page=viewrequests">Requests</a></li>
<li>News</li>
<li><a href="index.php?page=users">Members</a></li>
</ul>
</div>
<div id="right">
<ul>
<li><a href="index.php?page=upload">Upload</a></li>
<li><a href="index.php?page=rules">Rules</a></li>
 
<li><a href="index.php?page=modules&module=staff">Staff</a></li>
<li><a href="index.php?page=usercp&do=invite&action=read&uid=35907">Invitations </a>
</li>
<li><a href="index.php?page=modules&amp;module=helpdesk">Helpdesk</a></font>
</li>
<li><a href="index.php?page=forum">Forum</a></li>
</ul></div></div>
<div id="user">
<ul id="navlist">
<li><a href="index.php?page=userdetails&amp;id=35907"> <span style='color:darkgreen'>armani </a>
</li>
<li>Rank: <span style='color:darkgreen'>Peasant</li>
<li>&uarr;&nbsp;30.00 GB</li>
<li>&darr;&nbsp;0.00 KB</li>
<li>Ratio: &nbsp;---
</li>
<li> <a href=index.php?page=modules&module=seedbonus>Bonus:&nbsp;---</a>
</li>
<li><a href="index.php?page=usercp&amp;uid=35907">UserCP</a>
</li> <li><a href="index.php?page=bookmark">Bookmarks</a></li>
<li>
<a href="index.php?page=usercp&amp;uid=35907&amp;do=pm&amp;action=list">Mailbox</a>
 <li><a href="irc.php" target="blank">IRC</a></li><li><a href="logout.php">Logout</a></li>
</ul>
</div>
<form name="jump1" action="index.php" method="post">
<script type="text/rocketscript">
function newpm() {

var answer = confirm ("You have a new PM!")
if (answer)
window.location='index.php?page=usercp&uid=<? echo $CURUSER["uid"]; ?>&do=pm&action=list'

}
</script>
<table align="center" cellpadding="5px" class="usermenu" cellspacing="0px">
<tr>
</tr>
</table>
</form>
</div>
</div>
</div>
<div class="block-foot">
</div>
</div>
</div></td>
<td valign="top" width="5" rowspan="2"></td>
</tr>
</table>
</div></div>
<div id="bodyarea" style="padding:0 0 0 0;">
<table border="0" align="center" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td valign="top" width="5" rowspan="2"></td>
 
<td id="mcol" valign="top"><div class="block">
<div class="block-head">
<div class="block-head-title">MySQL query error!</div>
</div>
<div class="block-content">
<div align="center" class="b-content"><div align="center">
<br/>
<table border="1" width="300" cellspacing="0" cellpadding="0" style="border-color:#E70000">
<tr>
<td class="error" valign="bottom" align="center">
MySQL query error!
</td>
</tr>
<tr>
<td bgcolor="#ECEDF3" align="center" style="color:#000000">
<img src="https://blu-bits.com/style/Blue/images/error.gif" alt="" style="float:left; margin:5px"/>
<br/>
<br/>
Error: Incorrect key file for table '/tmp/#sql_385_0.MYI'; try to repair it<br/>
Query: SELECT u.team AS userteam, teams.id AS teamsid, teams.name AS teamname, teams.image AS teamimage, f.team,f.imdb,f.announce_url as aurl, f.language, f.tag,f.multiplier, (SELECT hash FROM xbtit_subtitles WHERE hash=f.info_hash LIMIT 1) as shash, f.happy,f.gold, f.image as img ,f.free as free, f.vip_torrent as vip_torrent, f.sticky as sticky, f.info_hash as hash, f.seeds+ifnull(x.seeders,0) as seeds, f.leechers+ifnull(x.leechers,0) as leechers, f.finished+ifnull(x.completed,0) as finished, f.dlbytes as dwned , IFNULL(f.filename,'') AS filename, f.url, f.info, f.anonymous, f.speed, UNIX_TIMESTAMP( f.data ) as added, c.image, c.name as cname, f.category as catid, f.size, f.external, f.uploader as upname, u.username as uploader, prefixcolor, suffixcolor FROM xbtit_files f LEFT JOIN xbt_files x ON x.info_hash=f.bin_hash LEFT JOIN xbtit_categories c ON c.id = f.category LEFT JOIN xbtit_users u ON u.id = f.uploader LEFT JOIN xbtit_users_level ul ON u.id_level=ul.id LEFT JOIN xbtit_teams teams ON f.team = teams.id WHERE 1=1 AND (filename LIKE '%%' OR tag LIKE '%%') AND category != 46 AND (0 = f.team OR f.team = 0 OR 3> 7) GROUP BY f.sticky,data DESC ORDER BY f.sticky DESC LIMIT 0,30<br/>
<br/>
<br/>
</td>
</tr>
</table>
</div>
<br/>
<div align="center">
<a href="javascript: history.go(-1);">Back</a>
</div>
<br/>
</div>
</div>
<div class="block-foot">
</div>
</div>
</td>
<if:HAS_RIGHT_COL>
<if:HAS_RIGHT>
 
<td id="rcol" valign="top"><tag:main_right/></td>
</if:HAS_RIGHT_COL>
</if:HAS_RIGHT>
 
</tr>
</table>
<br/>
<if:HAS_AB>
<center> <tag:adverbottom/> </center> <br/>
</if:HAS_AB>
<table align="center" width="100%" cellpadding="0" cellspacing="0" border="0">
<tr>
<td valign="top" width="5" rowspan="2"></td>
<td id="mcol" valign="top"><div id="bottom_menu"><div class="block">
<div class="block-head">
<div class="block-head-title">Online</div>
</div>
<div class="block-content">
<div align="justify" class="b-content"><div align='center'><table border='0' align='center' cellpadding='0' cellspacing='0' width='100%'><tr><td><table border='0' align='center'><tr><td style=font-size:10px; colspan='2'><center><b><span style='color:darkred'>Emperor | <span style='color:#B0171F'>Administrator | <span style='color:#32CD32'>Moderator | <span style='color:#00bfff'>Internal Team | <span style='color:#FFD700'>Torrent Celebrity | <span style='color:#CFB52B'>Donator | <span style='color:blue'>Uploader | <span style='color:white'>Official Painter | <span style='color:darkgreen'>Peasant | <span style='color:orange'>Knight | <span style='color:purple'>Baron | <span style='color:grey'>Count | <span style='color:black'>Duke | <span style='color:#FFD700'>Lifetime V.I.P | <span style='color:pink'>On Hold (see PM)<b></td></tr></table> <a href='index.php?page=userdetails&id=35907'><b><span style='color:darkgreen'>armani</b></a> <a href='index.php?page=userdetails&id=35304'><b><span style='color:purple'>Gibson</b></a> <a href='index.php?page=userdetails&id=32790'><b><span style='color:darkgreen'>Meritocracy</b></a> <a href='index.php?page=userdetails&id=17830'><b><span style='color:#FFD700'>pege</b></a> <a href='index.php?page=userdetails&id=24302'><b><span style='color:black'>jgenereo</b></a> <a href='index.php?page=userdetails&id=25214'><b><span style='color:orange'>doruverban</b></a> <a href='index.php?page=userdetails&id=35907'><b><span style='color:darkgreen'>armani</b></a> <a href='index.php?page=userdetails&id=12925'><b><span style='color:darkgreen'>GrimReaper</b></a> <a href='index.php?page=userdetails&id=28958'><b><span style='color:purple'>Epic</b></a> <a href='index.php?page=userdetails&id=19550'><b><span style='color:orange'>goufcustom</b></a> <b>Invisible !!</b> <a href='index.php?page=userdetails&id=25369'><b><span style='color:darkgreen'>bloodywolf</b></a> <a href='index.php?page=userdetails&id=26403'><b><span style='color:grey'>mattrock77</b></a> <a href='index.php?page=userdetails&id=20064'><b><span style='color:purple'>FreeAndFree</b></a> <b>Invisible !!</b> <tr><td><table border='0' align='center' cellpadding='0' cellspacing='0' width='100%'><tr><td align="left">&nbsp;<img src="images/whos_online.gif"><b>&nbsp; (total users online now: <font color='red'>15</font>)</b></td><td align="center"><img src="images/clock.gif"><b>&nbsp; (your total online time: <font color='green'>3h 50m 52s</font>)</b></td><td align="right"><img src="images/whos_online.gif"><b> &nbsp; (most: <font color='red'>248</font> on Fri, 06 May 2016 )&nbsp;</b></td></tr></table><br><tr><td><center><hr><b> Total Users Online Today </b></center></tr></td><tr><td><center> <b><a href="index.php?page=userdetails&id=17830"><span style='color:#FFD700'>pege</a></b> <b><a href="index.php?page=userdetails&id=29942"><span style='color:#FFD700'>Morbus</a></b> <b><a href="index.php?page=userdetails&id=31356"><span style='color:#FFD700'>alextheg<img src='images/donor.gif'></a></b> <b><a href="index.php?page=userdetails&id=571"><span style='color:black'>vaxpropp1<img src='images/donor.gif'></a></b> <b><a href="index.php?page=userdetails&id=31716"><span style='color:black'>OutsideTruck</a></b> <b><a href="index.php?page=userdetails&id=15161"><span style='color:black'>molvi420</a></b> <b><a href="index.php?page=userdetails&id=21646"><span style='color:black'>moita</a></b> <b><a href="index.php?page=userdetails&id=28520"><span style='color:black'>MAkeFor55</a></b> <b><a href="index.php?page=userdetails&id=30942"><span style='color:black'>limelight</a></b> <b>Invisible!<img src='images/donor.gif'></b> <b><a href="index.php?page=userdetails&id=20010"><span style='color:black'>kris26</a></b> <b><a href="index.php?page=userdetails&id=23775"><span style='color:black'>kaplog</a></b> <b>Invisible!</b> <b><a href="index.php?page=userdetails&id=24302"><span style='color:black'>jgenereo</a></b> <b><a href="index.php?page=userdetails&id=6656"><span style='color:black'>hd1</a></b> <b><a href="index.php?page=userdetails&id=14338"><span style='color:black'>Harry_Lime31</a></b> <b><a href="index.php?page=userdetails&id=22489"><span style='color:black'>Galed</a></b> <b><a href="index.php?page=userdetails&id=11662"><span style='color:black'>Duke</a></b> <b><a href="index.php?page=userdetails&id=14935"><span style='color:black'>Delboy</a></b> <b><a href="index.php?page=userdetails&id=20383"><span style='color:black'>bicanstop</a></b> <b><a href="index.php?page=userdetails&id=35410"><span style='color:darkgreen'>xgxgg</a></b> <b><a href="index.php?page=userdetails&id=8202"><span style='color:darkgreen'>utR</a></b> <b><a href="index.php?page=userdetails&id=32003"><span style='color:darkgreen'>sveen</a></b> <b><a href="index.php?page=userdetails&id=23978"><span style='color:darkgreen'>specialfeatures</a></b> <b><a href="index.php?page=userdetails&id=6798"><span style='color:darkgreen'>Snaps</a></b> <b><a href="index.php?page=userdetails&id=16870"><span style='color:darkgreen'>smatzis</a></b> <b><a href="index.php?page=userdetails&id=29625"><span style='color:darkgreen'>Shinji</a></b> <b><a href="index.php?page=userdetails&id=35863"><span style='color:darkgreen'>ShadZ</a></b> <b><a href="index.php?page=userdetails&id=23031"><span style='color:darkgreen'>polarisRR<img src='images/donor.gif'></a></b> <b><a href="index.php?page=userdetails&id=30628"><span style='color:darkgreen'>pezcore</a></b> <b><a href="index.php?page=userdetails&id=35918"><span style='color:darkgreen'>Msan</a></b> <b><a href="index.php?page=userdetails&id=34232"><span style='color:darkgreen'>mrflyer2001</a></b> <b><a href="index.php?page=userdetails&id=35911"><span style='color:darkgreen'>Moonshinelunacy</a></b> <b>Invisible!</b> <b><a href="index.php?page=userdetails&id=32790"><span style='color:darkgreen'>Meritocracy</a></b> <b><a href="index.php?page=userdetails&id=30855"><span style='color:darkgreen'>liyaocheng</a></b> <b><a href="index.php?page=userdetails&id=33509"><span style='color:darkgreen'>jrsova</a></b> <b><a href="index.php?page=userdetails&id=33017"><span style='color:darkgreen'>JohnSecond</a></b> <b><a href="index.php?page=userdetails&id=35385"><span style='color:darkgreen'>Jarppi73</a></b> <b><a href="index.php?page=userdetails&id=28359"><span style='color:darkgreen'>HD33T</a></b> <b><a href="index.php?page=userdetails&id=12925"><span style='color:darkgreen'>GrimReaper</a></b> <b><a href="index.php?page=userdetails&id=25022"><span style='color:darkgreen'>goranbp</a></b> <b><a href="index.php?page=userdetails&id=27910"><span style='color:darkgreen'>fier13</a></b> <b><a href="index.php?page=userdetails&id=33450"><span style='color:darkgreen'>DracoCarlo</a></b> <b><a href="index.php?page=userdetails&id=31350"><span style='color:darkgreen'>Deviate</a></b> <b><a href="index.php?page=userdetails&id=28583"><span style='color:darkgreen'>CrazyHorse</a></b> <b><a href="index.php?page=userdetails&id=35917"><span style='color:darkgreen'>Conken</a></b> <b><a href="index.php?page=userdetails&id=35858"><span style='color:darkgreen'>ChirpPerish</a></b> <b><a href="index.php?page=userdetails&id=35365"><span style='color:darkgreen'>cgu1ch4rd</a></b> <b><a href="index.php?page=userdetails&id=25369"><span style='color:darkgreen'>bloodywolf</a></b> <b><a href="index.php?page=userdetails&id=35768"><span style='color:darkgreen'>blackcat412</a></b> <b><a href="index.php?page=userdetails&id=35907"><span style='color:darkgreen'>armani</a></b> <b><a href="index.php?page=userdetails&id=28305"><span style='color:darkgreen'>Anonymous11</a></b> <b><a href="index.php?page=userdetails&id=33419"><span style='color:grey'>WallyWally</a></b> <b><a href="index.php?page=userdetails&id=14476"><span style='color:grey'>venus1234</a></b> <b><a href="index.php?page=userdetails&id=3457"><span style='color:grey'>sunovagun</a></b> <b><a href="index.php?page=userdetails&id=19547"><span style='color:grey'>robster</a></b> <b><a href="index.php?page=userdetails&id=28034"><span style='color:grey'>PickleBumps</a></b> <b><a href="index.php?page=userdetails&id=35201"><span style='color:grey'>oiler</a></b> <b><a href="index.php?page=userdetails&id=1112"><span style='color:grey'>Micke65<img src='images/donor.gif'></a></b> <b><a href="index.php?page=userdetails&id=26403"><span style='color:grey'>mattrock77</a></b> <b><a href="index.php?page=userdetails&id=26442"><span style='color:grey'>Mangopulp</a></b> <b><a href="index.php?page=userdetails&id=17744"><span style='color:grey'>la_muerte</a></b> <b><a href="index.php?page=userdetails&id=19622"><span style='color:grey'>HDcollector</a></b> <b><a href="index.php?page=userdetails&id=28186"><span style='color:grey'>GhostWorks</a></b> <b><a href="index.php?page=userdetails&id=19801"><span style='color:grey'>barry</a></b> <b>Invisible!</b> <b><a href="index.php?page=userdetails&id=26492"><span style='color:orange'>Xarcara</a></b> <b><a href="index.php?page=userdetails&id=31767"><span style='color:orange'>wxtwo</a></b> <b><a href="index.php?page=userdetails&id=28181"><span style='color:orange'>Taragon</a></b> <b><a href="index.php?page=userdetails&id=31416"><span style='color:orange'>tanyz85</a></b> <b><a href="index.php?page=userdetails&id=31912"><span style='color:orange'>sully45<img src='images/donor.gif'></a></b> <b><a href="index.php?page=userdetails&id=20662"><span style='color:orange'>style20</a></b> <b><a href="index.php?page=userdetails&id=2381"><span style='color:orange'>sk123</a></b> <b><a href="index.php?page=userdetails&id=28007"><span style='color:orange'>sas</a></b> <b><a href="index.php?page=userdetails&id=29802"><span style='color:orange'>rzr466</a></b> <b><a href="index.php?page=userdetails&id=31189"><span style='color:orange'>philphil61</a></b> <b><a href="index.php?page=userdetails&id=128"><span style='color:orange'>neozjx</a></b> <b><a href="index.php?page=userdetails&id=14984"><span style='color:orange'>mrniceguy</a></b> <b><a href="index.php?page=userdetails&id=22444"><span style='color:orange'>mmm0418</a></b> <b><a href="index.php?page=userdetails&id=35413"><span style='color:orange'>maxima</a></b> <b><a href="index.php?page=userdetails&id=29284"><span style='color:orange'>lncognito</a></b> <b><a href="index.php?page=userdetails&id=16314"><span style='color:orange'>kdog1</a></b> <b><a href="index.php?page=userdetails&id=34762"><span style='color:orange'>jpsole</a></b> <b><a href="index.php?page=userdetails&id=19550"><span style='color:orange'>goufcustom</a></b> <b><a href="index.php?page=userdetails&id=10919"><span style='color:orange'>exCat</a></b> <b><a href="index.php?page=userdetails&id=3437"><span style='color:orange'>empk354dd3</a></b> <b><a href="index.php?page=userdetails&id=25214"><span style='color:orange'>doruverban</a></b> <b><a href="index.php?page=userdetails&id=22634"><span style='color:orange'>dentnu</a></b> <b><a href="index.php?page=userdetails&id=34807"><span style='color:orange'>dekurt</a></b> <b><a href="index.php?page=userdetails&id=21912"><span style='color:orange'>anmrk</a></b> <b><a href="index.php?page=userdetails&id=24363"><span style='color:orange'>2123ng</a></b> <b><a href="index.php?page=userdetails&id=1483"><span style='color:purple'>treme1</a></b> <b><a href="index.php?page=userdetails&id=4064"><span style='color:purple'>TheWestwind</a></b> <b><a href="index.php?page=userdetails&id=28351"><span style='color:purple'>RazorWing</a></b> <b><a href="index.php?page=userdetails&id=2632"><span style='color:purple'>puttipongl</a></b> <b><a href="index.php?page=userdetails&id=30008"><span style='color:purple'>n1993r</a></b> <b><a href="index.php?page=userdetails&id=4434"><span style='color:purple'>mexx3</a></b> <b><a href="index.php?page=userdetails&id=8254"><span style='color:purple'>luigic</a></b> <b><a href="index.php?page=userdetails&id=28335"><span style='color:purple'>jgarr132</a></b> <b><a href="index.php?page=userdetails&id=21722"><span style='color:purple'>Haier</a></b> <b><a href="index.php?page=userdetails&id=30693"><span style='color:purple'>grainsoop</a></b> <b><a href="index.php?page=userdetails&id=35758"><span style='color:purple'>gianny</a></b> <b><a href="index.php?page=userdetails&id=15625"><span style='color:purple'>ftafree</a></b> <b><a href="index.php?page=userdetails&id=20064"><span style='color:purple'>FreeAndFree</a></b> <b><a href="index.php?page=userdetails&id=28958"><span style='color:purple'>Epic</a></b> <b><a href="index.php?page=userdetails&id=13867"><span style='color:purple'>crab9</a></b> <b><a href="index.php?page=userdetails&id=7121"><span style='color:purple'>chuec</a></b> <b><a href="index.php?page=userdetails&id=4835"><span style='color:blue'>stevo8mr<img src='images/donor.gif'></a></b> <b><a href="index.php?page=userdetails&id=30003"><span style='color:#FFD700'>zacondor</a></b> <b><a href="index.php?page=userdetails&id=4540"><span style='color:#FFD700'>studpack</a></b> <b><a href="index.php?page=userdetails&id=13921"><span style='color:#FFD700'>PyOOk</a></b> <b><a href="index.php?page=userdetails&id=12424"><span style='color:#FFD700'>Night Owl<img src='images/donor.gif'></a></b> <b><a href="index.php?page=userdetails&id=1287"><span style='color:#FFD700'>Mike8519</a></b> <b><a href="index.php?page=userdetails&id=24199"><span style='color:#FFD700'>GandalfTW</a></b> <b><a href="index.php?page=userdetails&id=850"><span style='color:#FFD700'>EP14</a></b> <b><a href="index.php?page=userdetails&id=24036"><span style='color:#FFD700'>DagothWarez</a></b> <b><a href="index.php?page=userdetails&id=19329"><span style='color:#FFD700'>amarias</a></b> <b><a href="index.php?page=userdetails&id=9751"><span style='color:#00bfff'>Jerry<img src='images/donor.gif'></a></b> <b>Invisible!</b> </center></tr></td><tr><td><table border='0' align='center' cellpadding='0' cellspacing='0' width='100%'><br><br><tr><td align="left">&nbsp;<img src="images/whos_online.gif"><b>&nbsp; (total users online today: <font color='red'>120</font>)</td><td align="right">&nbsp;contact us <a href=index.php?page=contact><img src="images/mail.png"></a></td><td align="right"><b>Last bot visit: <font color=red>&nbsp;Google-BOT 2 </font>- Thursday 15th December 2016 at 3:03 am</b></tr></td></table></td></tr></td></tr></table></div></div>
</div>
<div class="block-foot">
</div>
</div>
<br/>
</div></td>
</div>
<td valign="top" width="5" rowspan="2"></td>
</tr>
</table>
<table width="100%" height="46" align="center" cellpadding="0" cellspacing="0" border="0">
<tr>
<td class="footback" align="left" valign="middle"></td><td class="footback" align="center" valign="middle"><a href='#'><img src="images/totop.gif"/></a></td><td class="footback" align="right" valign="middle">[&nbsp;&nbsp;<u>Design By</u>: <a href="http://blu-bits.com" target="_blank">Some Dude</a>&nbsp;&nbsp;]&nbsp;&nbsp;[&nbsp;&nbsp;<u>xbtit dt fm v19.0 de By</u>: <a href="http://www.xbtitdeveloping.nl/" target="_blank">DiemThuy</a>&nbsp;&nbsp;]&nbsp;&nbsp;[&nbsp;&nbsp;<u>XBTIT Original By</u>: <a href="http://www.btiteam.org/" target="_blank">Btiteam</a>&nbsp;&nbsp;]</td>
</tr>
</table>
</div>
<if:anon>
<script data-rocketsrc="<tag:protected />/jscript/anon.js" type="text/rocketscript"></script>
<script type="text/rocketscript"></script>
</if:anon>
</body>
</html>
 
2016-12-15 10:17:20.0164 Info Found 0 releases from Blu-bits 
2016-12-15 10:17:20.1167 Error Exception in test_indexer System.Exception: Found no results while trying to browse this tracker
   at Jackett.Services.IndexerManagerService.<TestIndexer>d__11.MoveNext() in C:\projects\jackett\src\Jackett\Services\IndexerManagerService.cs:line 134
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jackett.Controllers.AdminController.<Test>d__18.MoveNext() in C:\projects\jackett\src\Jackett\Controllers\AdminController.cs:line 267
2016-12-15 10:17:20.2170 Info ReflectedHttpActionDescriptor ExecuteAsync Action returned 'System.Web.Http.Results.JsonResult`1[Newtonsoft.Json.Linq.JToken]' 
2016-12-15 10:17:20.3328 Info ApiControllerActionInvoker InvokeActionAsync  
2016-12-15 10:17:20.4331 Info JackettAPINoCacheAttribute OnActionExecutedAsync Action filter for 'Test()' 
2016-12-15 10:17:20.5176 Info JackettAPINoCacheAttribute OnActionExecutedAsync  
2016-12-15 10:17:20.5554 Info AdminController ExecuteAsync  
2016-12-15 10:17:20.5866 Info   Content-type='application/json; charset=utf-8', content-length=81 
2016-12-15 10:17:20.6335 Info AdminController Dispose  
2016-12-15 10:17:20.6713 Info AdminController Dispose

**Comment by kaso17** [comment]
They got a corrupted database causing the problem:
https://blu-bits.com/index.php?search=&page=torrents&options=0&active=0
results in:
`MySQL query error!


Error: Incorrect key file for table '/tmp/#sql_385_0.MYI'; try to repair it
Query: SELECT u.team AS userteam, teams.id AS teamsid, teams.name AS teamname, teams.image AS teamimage, f.team,f.imdb,f.announce_url as aurl, f.language, f.tag,f.multiplier, (SELECT hash FROM xbtit_subtitles WHERE hash=f.info_hash LIMIT 1) as shash, f.happy,f.gold, f.image as img ,f.free as free, f.vip_torrent as vip_torrent, f.sticky as sticky, f.info_hash as hash, f.seeds+ifnull(x.seeders,0) as seeds, f.leechers+ifnull(x.leechers,0) as leechers, f.finished+ifnull(x.completed,0) as finished, f.dlbytes as dwned , IFNULL(f.filename,'') AS filename, f.url, f.info, f.anonymous, f.speed, UNIX_TIMESTAMP( f.data ) as added, c.image, c.name as cname, f.category as catid, f.size, f.external, f.uploader as upname, u.username as uploader, prefixcolor, suffixcolor FROM xbtit_files f LEFT JOIN xbt_files x ON x.info_hash=f.bin_hash LEFT JOIN xbtit_categories c ON c.id = f.category LEFT JOIN xbtit_users u ON u.id = f.uploader LEFT JOIN xbtit_users_level ul ON u.id_level=ul.id LEFT JOIN xbtit_teams teams ON f.team = teams.id WHERE 1=1 AND (filename LIKE '%%' OR tag LIKE '%%') AND category != 46 AND (0 = f.team OR f.team = 0 OR 3> 7) GROUP BY f.sticky,data DESC ORDER BY f.sticky DESC LIMIT 0,30
`
Report it to their SiteOps so they can fix it.

**Comment by armani316** [comment]
@kaso17 Done. Reported.
