### ISSUE TITLE
[lostfilm] Exception (lostfilm): Clearance failed after 30 attempt(s).: Parse error (Test)

### ISSUE THREAD

**Issue by imm21** [Jackett/Jackett#8560]
linuxserver/jackett:latest

### Logged Error Messages

`Jackett.Common.IndexerException: Exception (lostfilm): Clearance failed after 30 attempt(s).
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 442
   at Jackett.Common.Indexers.LostFilm.FollowTrackerRedirection(String url, TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 657
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 643
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 826
   at Jackett.Common.Indexers.LostFilm.FetchTrackerReleases(TrackerUrlDetails details) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 647
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 446
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 826
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 458
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 405
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 826
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 411
   at Jackett.Common.Indexers.LostFilm.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 202
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26`

**Comment by garfield69** [comment]
The lostfilm.tv Jackett indexer works for me so this suggest the problem is at your end.
Please do not report `jackett:latest` as that does not confirm which **exact** version of jackett you are running.
From a browser running on the same machine as Jackett login to lostfilm and do a search.
Note which kind of cloudflare challenge you are getting.
If you are seeing something like
![image](https://user-images.githubusercontent.com/6933240/81347320-00f85380-9110-11ea-9b1e-399e2ae4ab65.png)
then Jackett 0.16.310 should be able to solve this challenge
But if you are seeing something like
![image](https://user-images.githubusercontent.com/6933240/81347432-3b61f080-9110-11ea-9a73-4f3d4b2a95ef.png)
then Jackett has never been able to solve this and there is nothing we can do about it at the moment other than suggest you try aptering your IP address via a VPN or proxy.

**Comment by imm21** [comment]
Sorry, my bad, i have check it on 0.16.312.0 and i still have the problem. When i open tacker on browser and try to search i don't have any cloudflare challenges.  I have the problem with main domain and with mirror domain lostfilm.tw (main domain was banned in russia).
