### ISSUE TITLE
[scenetime] Your cookie did not work: Found 0 results in the tracker (Config)

### ISSUE THREAD

**Issue by olavinto** [Jackett/Jackett#8564]
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.310.0

**Last Working Jackett Version**: 0.16.310.0

**Are you using a proxy or VPN?** [yes/no] Yes, but tried this on/off

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

Cookie string does not seem to be valid. It worked previously today, but not anymore. I tried readding loggin out/in, with my VPN on and off. Also no "akey=signup,donateok;" is in the string.

### Logged Error Messages

System.Exception: Your cookie did not work: Found 0 results in the tracker
   at Jackett.Common.Indexers.SceneTime.ApplyConfiguration(JToken configJson) in d:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 154
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70

**Comment by garfield69** [comment]
The Jackett scenetime indexer works for me, so that suggests the problem is at your end.
Whenever the scenetime website decides it wants a more current session credential you will need to refresh your expired cookie in that Jackett indexer config.
So you will need to use your browser to login, fetch the latest cookie and save it to the indexer config.
Don't forget to remove the part of the cookie that has that "akey=signup,donateok;".
