### ISSUE TITLE
Catalina macos:  nodename nor servname provided, or not known for all Jackett indexers

### ISSUE THREAD

**Issue by tmarigold** [Jackett/Jackett#8602]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:OSX Catalina

**.Net Runtime**: [Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [no]

### Description

Testing indexers (all indexers) returns the same error (nodename nor servname etc). Not corrected by changing indexer, restarting jackett, restarting modem, or restarting computer.

### Logged Error Messages

2020-05-11 22:41:44 | Error | Jackett.Common.IndexerException: Exception (1337x): nodename nor servname provided, or not known  ---> System.Net.Http.HttpRequestException: nodename nor servname provided, or not known  ---> System.Net.Sockets.SocketException (0xFFFDFFFF): nodename nor servname provided, or not known    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 370
-- | -- | --
2020-05-11 22:41:44 | Error | Jackett.Common.IndexerException: Exception (yts): nodename nor servname provided, or not known  ---> System.Net.Http.HttpRequestException: nodename nor servname provided, or not known  ---> System.Net.Sockets.SocketException (0xFFFDFFFF): nodename nor servname provided, or not known    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 458    at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query, Int32 attempts) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/yts.cs:line 99    at Jackett.Common.Indexers.Yts.PerformQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/yts.cs:line 73    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223    at Jackett.Server.Controllers.IndexerApiController.Test() in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2020-05-11 22:41:43 | Error | On attempt 3 checking for results from YTS: nodename nor servname provided, or not known
2020-05-11 22:41:13 | Error | On attempt 2 checking for results from YTS: nodename nor servname provided, or not known
2020-05-11 22:40:42 | Error | On attempt 1 checking for results from YTS: nodename nor servname provided, or not known
2020-05-11 22:40:41 | Error | Jackett.Common.IndexerException: Exception (torlock): nodename nor servname provided, or not known  ---> System.Net.Http.HttpRequestException: nodename nor servname provided, or not known  ---> System.Net.Sockets.SocketException (0xFFFDFFFF): nodename nor servname provided, or not known    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223    at Jackett.Server.Controllers.IndexerApiController.Test() in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2020-05-11 22:40:40 | Error | Jackett.Common.IndexerException: Exception (eztv): nodename nor servname provided, or not known  ---> System.Net.Http.HttpRequestException: nodename nor servname provided, or not known  ---> System.Net.Sockets.SocketException (0xFFFDFFFF): nodename nor servname provided, or not known    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223    at Jackett.Server.Controllers.IndexerApiController.Test() in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2020-05-11 22:40:40 | Error | Jackett.Common.IndexerException: Exception (ettv): nodename nor servname provided, or not known  ---> System.Net.Http.HttpRequestException: nodename nor servname provided, or not known  ---> System.Net.Sockets.SocketException (0xFFFDFFFF): nodename nor servname provided, or not known    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223    at Jackett.Server.Controllers.IndexerApiController.Test() in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2020-05-11 22:40:40 | Error | Jackett.Common.IndexerException: Exception (1337x): nodename nor servname provided, or not known  ---> System.Net.Http.HttpRequestException: nodename nor servname provided, or not known  ---> System.Net.Sockets.SocketException (0xFFFDFFFF): nodename nor servname provided, or not known    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 323    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 343    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 799    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 223    at Jackett.Server.Controllers.IndexerApiController.Test() in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/runners/2.166.4/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
this may be an issue with the .core support for Catalina.
unfortunately no one on the team as a Catalina macos (I have a mojave test image which works fine with Jackett) so we cannot independently test or research this right now.
Check if there are any updates (optional rather than automatic?) outstanding for your Catalina with regards to .Net core v3.1 library support.

**Comment by tmarigold** [comment]
Thanks for the tips!
I had no possible updates, but I ended up rebooting my router and since then it’s worked fine. Which is really strange, because I could access the internet just fine, but ah well.

**Comment by garfield69** [comment]
That is so strange... but if its working then \o/
