### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by aarsenca** [Jackett/Jackett#8635]
Here we go again... 

### Environment
**OS**: Linux (Raspbian Stretch)
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]: Mono
**Jackett Version**: v0.16.438
**Are you using a proxy or VPN?** [yes/no] No
### Description
I noticed the usual message in Sonarr: Indexers unavailable due to failures: yggtorrent. I manually tested the indexer in jackett and quickly got the error.
### Logged Error Messages 
First couple of lines only:
Jackett.Common.IndexerException: Exception (yggtorrent): Clearance failed after 10 attempt(s). ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
[Place any relevant error messages you noticed from the logs here.]

Thanks.

**Comment by almottier** [comment]
Same problem here.

**Comment by dam57950** [comment]
Same here, tested with differents logins

**Comment by vic1997** [comment]
Same here

**Comment by ramuskay** [comment]
Same problem here with same version 0.16.438.0

**Comment by bentux** [comment]
Same problem with some other tracker like kickasstorrent-kathow, isohunt2, thepiratebay and torrentfunk

**Comment by Bastien42** [comment]
+1

**Comment by bossovitch** [comment]
Yes, same here, it is a problem with Cloudflare, we have to wait that the CloudflareSolverRE is updated, or having some skill in coding, and doing that by your own

**Comment by kkkekai** [comment]
Same issue here

**Comment by dorel14** [comment]
Same for me

**Comment by pinedours** [comment]
Same here.. again :(

**Comment by xfouloux** [comment]
it would be great if devs could implement https://anti-captcha.com/ into jackett to counter this way more easily.... i put 10$ on my account like 2 years ago, and it is since in my bazarr for addicted captcha, and it did not even cost me more than 30 cents of captcha solving in 2 years

**Comment by Alandil35** [comment]
Same here with v. 0.16.449.0

**Comment by tchirou** [comment]
@ngosang 
I am not a coder at all so I just try to help my way
Would there be anything useful there ? https://github.com/VeNoMouS/cloudscraper/issues/216
Thanks a lot

**Comment by hwugmnimg2** [comment]
I have same problem but with TorrentDay (also uses cloudflare)

**Comment by Nexus83510** [comment]
Same problem here.
Thanks in advance !

**Comment by ngosang** [comment]
I fixed Cloudflare challenge resolver again. I hope it will last a bit more because I'm getting tired of this cat and mouse game. I'm far more smart than they are but they have full time workers and unlimited resources. I have only an old computer and few free time on weekends.

The fix will be included in the next release.

https://github.com/RyuzakiH/CloudflareSolverRe/pull/29

**Comment by tchirou** [comment]
You should make a leetchi campaign so we can all participate in offering you a brand new computer !

**Comment by aarsenca** [comment]
@ngosang Thank you so much once again. Indeed, this seems to be a cat and mouse game.

**Comment by garfield69** [comment]
Jackett 0.16.463

**Comment by tchirou** [comment]
It works ! Thanks a lot

**Comment by dorel14** [comment]
Hello i'am in Jackett Version 0.16.496.0
and still not working 
'''
loudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 443
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 886
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 558
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 982
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
'''

**Comment by tchirou** [comment]
It works for yggtorrent and yggcookie for me with Jackett 496, just tried it

**Comment by aarsenca** [comment]
Jackett Version 0.16.496.0 still works for me with yggtorrent.

**Comment by BK-STAR77** [comment]
v0.16.515 & v0.16.496.0 still don't with always the same error.

**Comment by aarsenca** [comment]
Here, all tests with the yggtorrent indexer are successful in jackett v0.16.515, sonarr and radarr.

**Comment by BK-STAR77** [comment]
Strange just test again with "YggCookie" but still don't work

Unable to connect to indexer: Torznab error detected: Jackett.Common.IndexerException: Exception (yggcookie): Clearance failed after 10 attempt(s).
 ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 447
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 347
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 347
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 808
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430

**Comment by aarsenca** [comment]
Do you need to use yggcookie? I'm no expert, but I think I read that the cookie changes frequently, so you need to reset it in jackett. You don't have that problem with yggtorrent.

**Comment by BK-STAR77** [comment]
With the Yggtorrent indexer I have the similar issue.

An error occurred while updating this indexer
Clearance failed after 10 attempt(s).
Click here to open an issue on GitHub for this indexer.

**Comment by aarsenca** [comment]
Sorry, that's all I know. Somebody else should have the solution for you.

**Comment by BK-STAR77** [comment]
> Sorry, that's all I know. Somebody else should have the solution for you.

Thank you

**Comment by dorel14** [comment]
still KO for me 
Jackett Version 0.16.521.0

**Comment by BK-STAR77** [comment]
> still KO for me
> Jackett Version 0.16.521.0

Yes I tested with the las t version and same error with YGGtorrent.

CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 443
   at Jackett.Common.Indexers.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 886
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 558
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 982
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

**Comment by tchirou** [comment]
I am on 526 and both ygg indexers still work for me.

**Comment by garfield69** [comment]
anyone still unable to pass the cloudflare challenge with Jackett 0.16.521 or newer, (while the rest of us are able to access yggtorrent perfectly well) will probably need to use a VPN to change their IP address.
You issue is not one that Jackett can fix.

**Comment by BK-STAR77** [comment]
> anyone still unable to pass the cloudflare challenge with Jackett 0.16.521 or newer, (while the rest of us are able to access yggtorrent perfectly well) will probably need to use a VPN to change their IP address.
> You issue is not one that Jackett can fix.

OK thank you for this information. I installed Jackett on my seedbox wich have a nederland ip. I will try to search a solution tomorrow.

**Comment by nonopubli** [comment]
Same error here... (both YGGtorrent and YGGcookie)

**Comment by Oyo95** [comment]
Same error to :/

**Comment by lorianagnes** [comment]
same error, tried with different accounts :/

**Comment by Aleatoire** [comment]
same...

**Comment by vic1997** [comment]
same :(

**Comment by Razor648** [comment]
same again

**Comment by maxxfly** [comment]
same case... T_T

**Comment by spider1163** [comment]
Check issue 8840 which is still opened
