### ISSUE TITLE
all certificate validation failed

### ISSUE THREAD

**Issue by Curtis-L** [Jackett/Jackett#8649]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:v0.16.438 release version

**Last Working Jackett Version**:None

**Are you using a proxy or VPN?** [no]

### Description

all trackers' certificate validation failed, for example, hdchina, the certificate jackett got is  

> An error occurred while updating this indexer
The SSL connection could not be established, see inner exception.: certificate validation failed: [Subject] CN=sni.cloudflaressl.com, O="Cloudflare, Inc.", L=San Francisco, S=CA, C=US [Issuer] CN=CloudFlare Inc ECC CA-2, O="CloudFlare, Inc.", L=San Francisco, S=CA, C=US [Serial Number] 03EF7751C647B1A7A3EF24F319054531 [Not Before] 2/25/2020 7:00:00 PM [Not After] 10/9/2020 8:00:00 AM [Thumbprint] 01FF1961034A5946117ECC85582FDCF5528C38C1

and it's the same as the real one, it's not because of proxy/isp block.

and what's weird is that i can use docker version just fine and everything on my server except jackett(amd64 version) works fine. 

i just downloaded the release tgz file and extracted, then use ./jackett to start.

and i have installed the dependencies 
libssl1.0.2 is already the newest version (1.0.2u-1~deb9u1).
libicu57 is already the newest version (57.1-6+deb9u4).

here's some additional info

```
root@:~# openssl s_client -connect hdchina.org:443
CONNECTED(00000003)
139747244941376:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1536:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 293 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Resumption PSK: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1589512349
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
```

```
root@:~# curl -vvv https://hdchina.org
* Rebuilt URL to: https://hdchina.org/
*   Trying 104.28.10.145...
* TCP_NODELAY set
* Connected to hdchina.org (104.28.10.145) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Feb 26 00:00:00 2020 GMT
*  expire date: Oct  9 12:00:00 2020 GMT
*  subjectAltName: host "hdchina.org" matched cert's "hdchina.org"
*  issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5625634faea0)
> GET / HTTP/1.1
> Host: hdchina.org
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 302 
< date: Fri, 15 May 2020 03:13:25 GMT
< content-type: text/html; charset=UTF-8
< set-cookie: __cfduid=d7ed27a87706275ed76ce99df28acf6e21589512405; expires=Sun, 14-Jun-20 03:13:25 GMT; path=/; domain=.hdchina.org; HttpOnly; SameSite=Lax
< set-cookie: PHPSESSID=j4SDXJHnOZ6E4iCy3j3WcV8Opi1SU3an5JNIr32LQzMw0wdF; path=/; HttpOnly
< pragma: no-cache
< content-security-policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' www.google-analytics.com ssl.google-analytics.com *.recaptcha.net *.gstatic.cn *.gstatic.com *.google.com recaptcha.net *.google.cn
< location: http://hdchina.org/login.php
< x-robots-tag: noindex, nofollow, nosnippet, noarchive
< x-page-speed: Powered By ngx_pagespeed
< cache-control: max-age=0, no-cache, no-store, must-revalidate
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 5939aed7bc72ebc1-LAX
< cf-request-id: 02b7eb9ad70000ebc173a88200000001
< 
* Curl_http_done: called premature == 0
* Connection #0 to host hdchina.org left intact
```

### Logged Error Messages

```
05-14 23:01:11 Error System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Exception: certificate validation failed: [Subject]
  CN=sni.cloudflaressl.com, O="Cloudflare, Inc.", L=San Francisco, S=CA, C=US

[Issuer]
  CN=CloudFlare Inc ECC CA-2, O="CloudFlare, Inc.", L=San Francisco, S=CA, C=US

[Serial Number]
  03EF7751C647B1A7A3EF24F319054531

[Not Before]
  2/25/2020 7:00:00 PM

[Not After]
  10/9/2020 8:00:00 AM

[Thumbprint]
  01FF1961034A5946117ECC85582FDCF5528C38C1

   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.ValidateCertificate(HttpRequestMessage request, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 54
   at System.Net.Http.ConnectHelper.<>c__DisplayClass3_0.<EstablishSslConnectionAsync>b__0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
   at System.Net.Security.SslStream.UserCertValidationCallbackWrapper(String hostName, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken)
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 443
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 793
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 984
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.




```

**Comment by garfield69** [comment]
the fact that a docker version works but your jackett native does not points to a supporting libraries issue, since docker is just the same Jackett code running on an image created with all the supporting libraries and whatnot.
Look for open issues for the libicu57 and libssl1.0.2 libraries, perhaps you are onto beta or versions that are too new and have oustanding problems with TLSv1.3.
The openssl you tries seems to choke on establishing a TLSv1.3 handshake but the curl managed to negotiate a TLSv1.2 ok.
I'm not a linux guy, so I'll invite @cadatoiva  and @ngosang  to take a look at this and see if they have any recommendations.

**Comment by Curtis-L** [comment]
> the fact that a docker version works but your jackett native does not points to a supporting libraries issue, since docker is just the same Jackett code running on an image created with all the supporting libraries and whatnot.
> Look for open issues for the libicu57 and libssl1.0.2 libraries, perhaps you are onto beta or versions that are too new and have oustanding problems with TLSv1.3.
> The openssl you tries seems to choke on establishing a TLSv1.3 handshake but the curl managed to negotiate a TLSv1.2 ok.
> I'm not a linux guy, so I'll invite @cadatoiva and @ngosang to take a look at this and see if they have any recommendations.

thanks so much for your response, i'm using debian9 stable source(not latest stable debain10, thought debian9 is stable enough), and there's nothing wrong before, and i saw similar issues before, #6511, don't know if his problem is the same as mine. 

and strange thing is that this happened after i tried to set up an apache reverse proxy for jackett, before it's all normal, i tried to reinstall and without apache reverse proxy, everything's fine.

**Comment by ngosang** [comment]
Debian 9 is fine. Just make sure you have `openssl` up to date. And update the system CAs => https://serverfault.com/a/893459
It's a good idea to update all packages at some point.

**Comment by RoloSoze** [comment]
@Curtis-L @ngosang is the guy to talk to about C# trackers, like the Gazelle-based ones :)
