### ISSUE TITLE
Can't configure TorrentDay - CloudflareClearanceException

### ISSUE THREAD

**Issue by Gobonoid** [Jackett/Jackett#8695]
**OS**:
Nas synology - docker

**Jackett Version**:
latest

**Are you using a proxy or VPN?** 
yes

### Description

* Just click Add indexer -> TorrentDay -> spanner to configure

### Logged Error Messages

```
CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 438
   at Jackett.Common.Indexers.TorrentDay.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentDay.cs:line 123
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

### Screenshots

![image](https://user-images.githubusercontent.com/15029578/82192800-5f7db880-98ec-11ea-9871-48904eb3a494.png)

**Comment by garfield69** [comment]
Reporting that you are on the **latest** Jackett is not useful. The log message suggests that you cannot be on the latest version, 0.16.496
So please access your Jackett dashboard and scroll to the bottom and report the actual version of Jackett so we can be sure.
Thanks.

**Comment by Gobonoid** [comment]
Jackett Version 0.16.71.0

**Comment by garfield69** [comment]
So if you are on docker then the first thing to try is to pull the latest image and get yourself onto 0.16.496
I'm not saying this will fix  the problem but it gives us a base to start with.

**Comment by Gobonoid** [comment]
```
 Jackett Version 0.16.496.0
```
I've pulled newest image and problem got fixed in that version.

**Comment by garfield69** [comment]
\o/
