### ISSUE TITLE
[speedcd] Error parsing the login form (Config)

### ISSUE THREAD

**Issue by 6YLu8snzq67hw4JB** [Jackett/Jackett#8696]
### Environment

**OS**: Ubuntu 18.04 LTS, Docker https://hub.docker.com/r/linuxserver/jackett/

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: 0.12.1779.0

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** yes

### Description

- Add speed.cd
- try to login

### Logged Error Messages

```
Error System.Exception: Error parsing the login form
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 108
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 95
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 System.Exception: Error parsing the login form
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 108
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 95
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
The Speed.cd Jackett indexer is working for me which suggests the issue is at your end.
I see that you reported your Jackett version as 0.12.1779
So the first thing to do is to update your Jackett to the latest version, currently 0.16.496
Let me know how you go.

**Comment by 6YLu8snzq67hw4JB** [comment]
Hey I upgraded to 0.16.496.0 and it still shows the same error. I think I might just reported a wrong version.

**Comment by garfield69** [comment]
the version of Jackett you are on is available at the bottom of the Jackett dashboard.
so the stack trace you provided is the last message in the sequence and of little use in determining what the problem may be.
so the next thing to do is to torn on the **enhanced** logging, so that Jackett records debug and html which may shed some light.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by 6YLu8snzq67hw4JB** [comment]
```
05-25 10:43:31 Info Request starting HTTP/1.1 POST http://jackett.URL-REDACTED/api/v2.0/indexers/speedcd/config application/json 213 
05-25 10:43:31 Debug Request is continuing in applying rules. Current url is https://jackett.URL-REDACTED/api/v2.0/indexers/speedcd/config 
05-25 10:43:31 Debug Request is continuing in applying rules. Current url is https://jackett.URL-REDACTED/api/v2.0/indexers/speedcd/config 
05-25 10:43:31 Debug Request is continuing in applying rules. Current url is https://jackett.URL-REDACTED/api/v2.0/indexers/speedcd/config 
05-25 10:43:31 Debug POST requests are not supported 
05-25 10:43:31 Debug AuthenticationScheme: Cookies was successfully authenticated. 
05-25 10:43:31 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/speedcd/config' 
05-25 10:43:31 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/speedcd/config' 
05-25 10:43:31 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
05-25 10:43:31 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
05-25 10:43:31 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
05-25 10:43:31 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
05-25 10:43:31 Debug Execution plan of resource filters (in the following order): None 
05-25 10:43:31 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
05-25 10:43:31 Debug Execution plan of exception filters (in the following order): None 
05-25 10:43:31 Debug Execution plan of result filters (in the following order): None 
05-25 10:43:31 Info Authorization was successful. 
05-25 10:43:31 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
05-25 10:43:31 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
05-25 10:43:31 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
05-25 10:43:31 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
05-25 10:43:31 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
05-25 10:43:31 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
05-25 10:43:31 Debug Connection id "0HM00GUEL3BUB", Request id "0HM00GUEL3BUB:00000007": started reading request body. 
05-25 10:43:31 Debug Connection id "0HM00GUEL3BUB", Request id "0HM00GUEL3BUB:00000007": done reading request body. 
05-25 10:43:31 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
05-25 10:43:31 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
05-25 10:43:31 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
05-25 10:43:31 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
05-25 10:43:31 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://speed.cd/checkpoint/API) 
05-25 10:43:31 Debug __cfduid=d55811ad49d97671b0c198e30195c7f691590396104; expires=Wed, 24-Jun-20 08:41:44 GMT; path=/; domain=.speed.cd; HttpOnly; SameSite=Lax; Secure 
05-25 10:43:31 Debug WebClient(HttpWebClient2NetCore): Returning OK => {"er":0,"Fs":[["DOM",[".uiIn input",["addClass","err"]]]]} 
05-25 10:43:31 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 341.5512ms 
05-25 10:43:31 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
05-25 10:43:31 Error System.Exception: Error parsing the login form
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 108
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 95
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 System.Exception: Error parsing the login form
   at Jackett.Common.Indexers.SpeedCD.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 108
   at Jackett.Common.Indexers.SpeedCD.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SpeedCD.cs:line 95
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
05-25 10:43:31 Debug No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps. 
05-25 10:43:31 Debug Connection id "0HM00GUEL3BUB" completed keep alive response. 
05-25 10:43:31 Info Request finished in 374.2408ms 500 application/json 
```

**Comment by ngosang** [comment]
SpeedCD is working fine for me. The response from the server is weird ` {"er":0,"Fs":[["DOM",[".uiIn input",["addClass","err"]]]]}`

@6YLu8snzq67hw4JB what happen if you open a private tab in your browser and try to log-in? Can you?

**Comment by 6YLu8snzq67hw4JB** [comment]
So as it turns out, speed.cd seems to have issues with my username. When I use the email to login it works. I checked the network tab and the speed.cd server returns `{"er":0,"Fs":[["DOM",[".uiIn input",["addClass","err"]]]]}` when I use my username. Solved.
