### ISSUE TITLE
[pterclub] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by Curtis-L** [Jackett/Jackett#8698]
### Environment

**OS**:Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.496.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

it worked before when i added it, now it doesn't, guess this line in log is crucial. 

System.Exception: Error while parsing field=grabs, selector=td.rowfollow:nth-last-of-type(2), value=匿名(****): Input string was not in a correct format.

### Logged Error Messages

```
System.Exception: Error while parsing field=grabs, selector=td.rowfollow:nth-last-of-type(2), value=匿名(****): Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592 
2020-05-18 14:34:00.2966 Error CardigannIndexer (pterclub): Error while parsing row '
<tr class="sticky_normal">
        <td class="rowfollow nowrap" valign="middle" style="padding: 0px">
                <a href="?cat=401">
                        <img class="c_movies" src="pic/cattrans.gif" alt="电影 (Movie)" title="电影 (Movie)" style="background-image: url(pic/category/chd/scenetorrents/chs/catsprites.png);">
                </a>
                <a href="?source6=1">
                        <img class="c_enc" src="pic/cattrans.gif" style="background-image: url(pic/category/chd/scenetorrents/chs/additional/encode.png);" alt="Encode" title="Encode">
                </a>
                <a class="third-icon" href="?team4=1">
                        <img class="c_eng" src="pic/cattrans.gif" style="background-image: url(pic/category/chd/scenetorrents/chs/additional/USA.png);" alt="ENG" title="ENG">
                </a>
        </td>
        <td class="rowfollow" width="100%" align="left" style="padding: 0px">
                <table class="torrentname" width="100%">
                        <tbody>
                                <tr class="sticky_normal">
                                        <td class="embedded"><img class="sticky" src="pic/trans.gif" alt="Sticky" title="置顶 至 2020-05-18 23:37:39"><a title="The Mask Of Zorro 1998 BluRay 2160p TrueHD7.1 HDR x265 10bit-CHD" href="details.php?id=45445">
                                                        <b>&nbsp;The Mask Of Zorro 1998 BluRay 2160p TrueHD7.1 HDR x265 10bit-CHD</b>
                                                </a>
                                                <b>[<font class="hot">热门</font>]</b>
                                                <a href="torrents.php?spstate=2">
                                                        <img class="pro_free" src="pic/trans.gif" alt="Free" onmouseover="domTT_activate(this, event, 'content', '<b><font class=&quot;free&quot;>免费</font></b>剩余时间：<b><span title=&quot;2020-05-18 23:37:39&quo分</span></b>', 'trail', false, 'delay',500,'lifetime',3000,'fade','both','styleClass','niceTitle', 'fadeMax',87, 'maxWidth', 300);">
                                                </a>&nbsp;剩余时间：<b>
                                                        <span title="2020-05-18 23:37:39">1时3分</span>
                                                </b>
                                                <br>
                                                <div>
                                                        <a class="chs_tag chs_tag-sub" style="margin-left: 2px;" href="torrents.php?tag_chinesesub=yes">中字</a>
                                                </div>&nbsp;佐罗的面具 / 蒙面侠苏洛 / 黑侠佐罗 / 黑侠梭罗</td>
                                        <td class="embedded" width="6px">
                                                <div style="line-height: 16px"></div>
                                        </td>
                                        <td class="embedded" style="padding-left: 0px;" width="20" valign="middle">
                                                <a href="download.php?id=45445&amp;passkey=f1bd4aa0eab3b79cee99e0ad98bfa9ff">
                                                        <img class="download" src="pic/trans.gif" style="padding-bottom: 2px;" alt="download" title="下载本种">
                                                </a>
                                                <div style="line-height: 16px">
                                                        <a href="torrents.php?check=checked">
                                                                <img src="pic/checked.png" title="已通过审核 by 365962648" width="16px">
                                                        </a>
                                                </div>
                                        </td>
                                        <td class="embedded" style="padding-left: 0px;" width="20" valign="middle">
                                                <a id="rssmark99" href="javascript: rssmark(45445,99);">
                                                        <img class="delrssmark" src="pic/trans.gif" alt="Unrssmarked" title="RSS">
                                                </a>
                                                <a id="bookmark99" href="javascript: bookmark(45445,99);">
                                                        <img class="delbookmark" src="pic/trans.gif" alt="Unbookmarked" title="收藏">
                                                </a>
                                        </td>
                                        <td class="embedded" width="44px">
                                                <div>
                                                        <img src="pic/imdb.png" title="IMDb评分">
                                                        <a target="_blank" href="https://www.imdb.com/title/tt0120746/">
                                                                <label style="padding-left: 5px; cursor:pointer;">6.7</label>
                                                        </a>
                                                </div>
                                                <div>
                                                        <img src="pic/douban.png" title="豆瓣评分">
                                                        <a target="_blank" href="https://movie.douban.com/subject/1293225/">
                                                                <label style="padding-left: 5px; cursor:pointer;">7.5</label>
                                                        </a>
                                                </div>
                                        </td>
                                </tr>
                        </tbody>
                </table>
        </td>
        <td class="rowfollow">
                <a href="comment.php?action=add&amp;pid=45445&amp;type=torrent" title="添加评论">0</a>
        </td>
        <td class="rowfollow nowrap">
                <span title="2020-05-17 23:03:22">23时<br>30分</span>
        </td>
        <td class="rowfollow">25.94<br>GB</td>
        <td class="rowfollow" align="center">
                <b>
                        <a href="details.php?id=45445&amp;dllist=1#seeders">18</a>
                </b>
        </td>
        <td class="rowfollow">0</td>
        <td class="rowfollow">
                <a href="viewsnatches.php?id=45445">
                        <b>25</b>
                </a>
        </td>
        <td class="rowfollow" align="center">
                <i>匿名</i>
                <br>(<span class="nowrap">
                        <a href="userdetails.php?id=5929" class="EliteUser_Name">
                                <b>rainbig</b>
                        </a>
                </span>)</td>
        <td class="rowfollow">
                <a href="fastdelete.php?id=45445">
                        <img class="staff_delete" src="pic/trans.gif" alt="D" title="删除">
                </a>
                <br>
                <a href="edit.php?returnto=%2Ftorrents.php%3Fsearch%3D%26incldead%3D0%26spstate%3D0%26search_area%3D0%26search_mode%3D0%26sort%3D4%26type%3Ddesc&amp;id=45445">
                        <img class="staff_edit" src="pic/trans.gif" alt="E" title="编辑">
                </a>
        </td>
</tr>':

System.Exception: Error while parsing field=grabs, selector=td.rowfollow:nth-last-of-type(2), value=匿名(rainbig): Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592 
2020-05-18 14:34:00.2990 Info Found 0 releases from PTerClub 
2020-05-18 14:34:00.3041 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 263
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 263
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

```

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
as an advanced user on this website,  you are seeing an additional field on your torrent results page, containing **delete** and **edit** links, which is throwing off the selector count for the indexer page processing.
Regular users do not see these extra options.

I'll need to research to see if the indexer can be coded to cope with this variation.

**Comment by Curtis-L** [comment]
@garfield69 i guess so, i have the permission to view anonymous users and there's an extra column in my torrents.php, thanks for your fix!!

**Comment by garfield69** [comment]
Jackett 0.16.511
