### ISSUE TITLE
[badasstorrents] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8709]
0.16.496.0 Docker, with and without proxy/VPN. Just started today.

```
2020-05-19 08:13:36.0670 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://badasstorrents.com/torrents/search/) 
2020-05-19 08:13:36.1559 Debug WebClient(HttpWebClient2NetCore): Returning OK => 
<!DOCTYPE html>
<html>
<head>
<title>Just a moment...</title>
</head>
<body>
<form method="post">
<button type="submit" name="_authorized" style="display: none;" id="_authorized" value="cc831c7aa7b9ba6d1ca3ecba924e881a3d31919a"></button>
</form>
<script>
            document.getElementById("_authorized").click();
            </script>
</body>
</html>
2020-05-19 08:13:36.1578 Info Found 0 releases from Badass Torrents 
2020-05-19 08:13:36.1594 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 93.2845ms 
2020-05-19 08:13:36.1601 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' 
2020-05-19 08:13:36.1609 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 264
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70 System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 264
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by garfield69** [comment]
looks like the web site have changes the way it provide results, probably now generating the result page dynamically using JS.
The indexer will need to be re-written in C# since it is no longer providing results in the first HTML returned when Jackett sends its search query url.

**Comment by ngosang** [comment]
@garfield69 I see HTML response.
* Latest => https://badasstorrents.com/torrents/search/
* Search => https://badasstorrents.com/torrents/search/harry

**Comment by garfield69** [comment]
this is what the Jackett indexer sees in response to 
https://badasstorrents.com/torrents/search/harry
```html
WebClient(HttpWebClient2NetCore): Returning OK => 
<!DOCTYPE html>
<html>
<head>
<title>Just a moment...</title>
</head>
<body>
<form method="post">
<button type="submit" name="_authorized" style="display: none;" id="_authorized" value="95620af7a94ca00e873d6884d7709ea4a001b85c"></button>
</form>
<script>
            document.getElementById("_authorized").click();
            </script>
</body>
</html>
```

**Comment by ilike2burnthing** [comment]
Open `view-source:https://badasstorrents.com/torrents/search/harry` in a private window and you'll see the same thing. So is the cookie header not being passed?

No idea if this relevant, but I noticed that the .json has cfduid, cf_clearance, and PHPSESSID, whereas in browser the request headers' cookie only shows cfduid and PHPSESSID.

**Comment by ngosang** [comment]
@ilike2burnthing @garfield69 This site is protected by CloudFlare but I'm pretty sure the results are in plain HTML. No json, ajax...

**Comment by garfield69** [comment]
yes its plain html, but cardigann is getting this intermediate html page as shown in https://github.com/Jakett/Jackett/issues/8709#issuecomment-632349892 so cardigann does not get any results to process unless there is a way to get cardigann to ignore that page and wait for the results page to be sent.

**Comment by garfield69** [comment]
v0.18.303

**Comment by vdbhb59** [comment]
OOC, is anyone able to use badass? It is giving a popup for username and password.
![image](https://github.com/Jackett/Jackett/assets/60728004/76388f27-ba9a-4b24-a957-4388d716b3d4)

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/7196#issuecomment-2032570537

**Comment by slrslr** [comment]
I can see the error from the title. Onsite is "503 Service Unavailable". Re-open this?

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/7196#issuecomment-2889108531 - search before commenting
