### ISSUE TITLE
[yggcookie] Exception (yggcookie): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by mowdep** [Jackett/Jackett#8718]
Yes I know there are plenty of this issue but still append to me with the newer version of jackett from Scaleway - Amsterdam 

### Environment

**OS**: Debian 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.511.0

**Last Working Jackett Version**: None (for this provider)

**Are you using a proxy or VPN?** No - Dedibox online.net in Amsterdam

### Description

Yggcookie (and yggtorrent wth creditentials) -- See Log for yggcookies

### Logged Error Messages

2020-05-20 17:02:54	Debug	
Connection id "0HLVSOF692A83" stopped.
2020-05-20 17:02:54	Debug	
Connection id "0HLVSOF692A83" disconnecting.
2020-05-20 17:02:54	Debug	
Connection id "0HLVSOF692A83" sending FIN because: "The client closed the connection."
2020-05-20 17:02:54	Debug	
Connection id "0HLVSOF692A83" received FIN.
2020-05-20 17:02:54	Info	
Request finished in 654.3702ms 500 application/json
2020-05-20 17:02:54	Debug	
Connection id "0HLVSOF692A83" completed keep alive response.
2020-05-20 17:02:54	Debug	
No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.
2020-05-20 17:02:54	Error	
Jackett.Common.IndexerException: Exception (yggcookie): Clearance failed after 10 attempt(s).
 ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 443
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 259
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
2020-05-20 17:02:54	Info	
Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-05-20 17:02:54	Info	
Executed action Jackett.Server.Controllers.IndexerApiController.Test (jackett) in 605.2599ms
2020-05-20 17:02:54	Debug	
WebClient(HttpWebClient2NetCore).GetString(Url:https://www2.yggtorrent.se/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date)
2020-05-20 17:02:54	Debug	
Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2020-05-20 17:02:54	Debug	
Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett)
2020-05-20 17:02:54	Info	
Authorization was successful.
2020-05-20 17:02:54	Debug	
Execution plan of result filters (in the following order): None
2020-05-20 17:02:54	Debug	
Execution plan of exception filters (in the following order): None
2020-05-20 17:02:54	Debug	
Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer
2020-05-20 17:02:54	Debug	
Execution plan of resource filters (in the following order): None
2020-05-20 17:02:54	Debug	
Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter
2020-05-20 17:02:54	Info	
Route matched with {action = "Test", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Test() on controller Jackett.Server.Controllers.IndexerApiController (jackett).
2020-05-20 17:02:54	Info	
Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-05-20 17:02:54	Debug	
Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)'
2020-05-20 17:02:54	Debug	
Endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (jackett)' with route pattern 'api/v2.0/indexers/{indexerid}/Test' is valid for the request path '/api/v2.0/indexers/yggcookie/test'
2020-05-20 17:02:54	Debug	
1 candidate(s) found for the request path '/api/v2.0/indexers/yggcookie/test'
2020-05-20 17:02:54	Debug	
AuthenticationScheme: Cookies was successfully authenticated.
2020-05-20 17:02:54	Debug	
POST requests are not supported
2020-05-20 17:02:54	Debug	
Request is continuing in applying rules. Current url is https://[URL_Server]/jackett/api/v2.0/indexers/yggcookie/test
2020-05-20 17:02:54	Debug	
Request is continuing in applying rules. Current url is https://[URL_Server]/jackett/api/v2.0/indexers/yggcookie/test
2020-05-20 17:02:54	Debug	
Request is continuing in applying rules. Current url is https://[URL_Server]/jackett/api/v2.0/indexers/yggcookie/test
2020-05-20 17:02:54	Info	
Request starting HTTP/1.1 POST http://[URL_Server]/jackett/api/v2.0/indexers/yggcookie/test  0
2020-05-20 17:02:54	Debug	
Connection id "0HLVSOF692A83" started.
2020-05-20 17:02:54	Debug	
Connection id "0HLVSOF692A83" accepted.

**Comment by ilike2burnthing** [comment]
See also: TorrentBomb

@ngosang sorry 😐

**Comment by aarsenca** [comment]
yggtorrent still works fine with jackett v0.16.511, sonarr and radarr. Personally, I have only used yggcookie very shortly when there was an issue with yggtorrent and quickly reverted to yggtorrent when the issue was fixed. Can you use yggtorrent instead of yggcookie?

**Comment by garfield69** [comment]
@ilike2burnthing  torrentbomb is not in the same category as yggtorrent, but rather has the same issue as demonoid and piratiero, where the site is presenting that multipage challenge and the cloudflareSolverRe library cannot handle that particular challenge.

**Comment by garfield69** [comment]
@mowdep  clearly the cloudflare anti-ddos check that yggtorrent is using is particularly weary of access from Dedibox online.net devices.
I can access yggtorrent and also use yggcookie without issues, so if cloudflare is picking on your box by asking for a full anti-DDoS hCaptcha challenge then there is nothing Jackett can do about this. Those challenges are not solvable by automation currently.
so there is nothing Jackett can do for you right now.
