### ISSUE TITLE
elitetorrent-biz: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8778]
Empty search
```
CardigannIndexer (elitetorrent-biz): Error while parsing row '
<li>
	<div class="imagen">
		<a href="https://wwvv.elitetorrent.nl/Kalashnikov/peliculas/99701-HDR-Subtitulado/" title="Kalashnikov" alt="Kalashnikov">
			<img class="brighten lazyed" src="/wp-content/themes/EliteTorrent/images/lazy_placeholder.gif" data-src="/wp-content/uploads/portadas/1590315282-.jpg" border="0" title="Kalashnikov" alt="Kalashnikov">
		</a>
		<span class="marca estreno" id="idiomacio">
			<i>
				<img src="https://wwvv.elitetorrent.nl/wp-content/themes/EliteTorrent/images/lazing_new.gif" data-src="https://wwvv.elitetorrent.nl/wp-content/themes/EliteTorrent/images/vose.png" title="Pelicula en Ingles Subtitulado VOSE" alt="Pelicula en Ingles Subtitulado VOSE">
			</i>
		</span>
		<span class="marca estreno" style="right: 0px;left: auto;max-width: 60%;">
			<i>HDR</i>
		</span>
		<div class="voto1" title="Peso de pelicula" style="background-color:rgb(98,170,0)">
			<span class="dig1">1.68 GBs</span>
		</div>
	</div>
	<div class="meta">
		<a class="nombre" href="https://wwvv.elitetorrent.nl/Kalashnikov/peliculas/99701-HDR-Subtitulado/" title="Kalashnikov">Kalashnikov</a>
	</div>
</li>':

System.Exception: Error while parsing field=category, selector=.meta a, value=Kalashnikov: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1592
```

**Comment by garfield69** [comment]
very strange entry.
this movie is the only one where the name is inserted into the details link BEFORE the category
usually hrefs look like this
```
<a class="nombre " href="https://wwvv.elitetorrent.nl/series/chernobyl-temporada-1-capitulo-4-espanol/" title="Chernobyl 1&#215;04 ">Chernobyl 1&#215;04</a>
<a class="nombre " href="https://wwvv.elitetorrent.nl/peliculas/entre-la-razon-y-la-locura-720p-Subtitulado/" title="Entre la razón y la locura ">Entre la razón y la locura</a>
```
so we use SPLIT,3 to fetch the category
but this movie uses 
```
<a class="nombre " href="https://wwvv.elitetorrent.nl/Kalashnikov/peliculas/99701-HDR-Subtitulado/" title="Kalashnikov ">Kalashnikov</a>
```
which breaks the category processing.
the question is, is this an aberration, or the start of a new trend?

And how do we cope with the category field moving from 3 to 4?

**Comment by ngosang** [comment]
"query": "st"
```
CardigannIndexer (elitetorrent-biz): Error while parsing row '
<li>
	<div class="imagen">
		<a href="https://www.elitetorrent.com/Monster+Run/103932-BRs-Subtitulado/" title="Monster Run" alt="Monster Run">
			<img class="brighten lazyed" src="/wp-content/themes/EliteTorrent/images/lazy_placeholder.gif" data-src="/wp-content/uploads/portadas/1598511760-.jpg" border="0" title="Monster Run" alt="Monster Run">
		</a>
		<span class="marca estreno" id="idiomacio">
			<i>
				<img src="https://www.elitetorrent.com/wp-content/themes/EliteTorrent/images/lazing_new.gif" data-src="https://www.elitetorrent.com/wp-content/themes/EliteTorrent/images/vose.png" title="Pelicula en Ingles Subtitulado VOSE" alt="Pelicula en Ingles Subtitulado VOSE">
			</i>
		</span>
		<span class="marca estreno" style="right: 0px;left: auto;max-width: 60%;">
			<i>BRS</i>
		</span>
		<div class="voto1" title="Peso de pelicula" style="background-color:rgb(98,170,0)">
			<span class="dig1">1.89 GBs</span>
		</div>
	</div>
	<div class="meta">
		<a class="nombre" href="https://www.elitetorrent.com/Monster+Run/103932-BRs-Subtitulado/" title="Monster Run">Monster Run</a>
	</div>
</li>':

System.Exception: Error while parsing field=category, selector=, value=: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1620
```
