### ISSUE TITLE
[rarbg] Could not find releases from this URL (Config)

### ISSUE THREAD

**Issue by oonqt** [Jackett/Jackett#8821]
### Environment

**OS**:
Unix 4.19.76.0 (Docker on Windows 10 Host) (linuxserver/jackett)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
.NET Core

**.Net Version**:
3.1.4

**Jackett Version**:
v0.16.571.0

**Last Working Jackett Version**:
0.16.373.0

**Are you using a proxy or VPN?** [yes/no]
no

### Description
I am unable to add the indexer "RARBG" to Jackett
Add Indexer -> RARBG
[rarbg.to](https://rarbg.to) is up and running

### Logged Error Messages

`System.Exception: Could not find releases from this URL
   at Jackett.Common.Indexers.RarBG.<>c.<ApplyConfiguration>b__10_0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 109
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 260
   at Jackett.Common.Indexers.RarBG.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 111
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70`

**Comment by oonqt** [comment]
I am reopening this because I do not believe this related to the other issues mentioned (RARBG API Issues)

I am able to add the RARBG indexer fine with the last known working jackett version mentioned in the OP, just not the current version mentioned in the OP.

**Comment by garfield69** [comment]
the rarbg indexer works for me with my win10 Jackett 0.16.571
note that the indexer does not use the rarbg.to website (other than for the details page link) rather it uses the rarbg server at https://torrentapi.org/pubapi_v2.php
it is not uncommon for the server to be in and out of service recently which can result in the error messsage reported.

**Comment by MrSparklle** [comment]
Same issue here.

when trying to access the api (https://torrentapi.org/pubapi_v2.php) directly from the browser I get a "403 Forbidden" error.

Is there any related to Jacket or a torrentapi internal issue? Anybody can confirme the same behaviour when access the URL in browser?

**Comment by garfield69** [comment]
@MrSparklle  the issue is an internal one on the rarbg server site.
there is nothing can be done on the jackett side.

yes, you cannot access the api without including a token.
for example,
https://torrentapi.org/pubapi_v2.php?app_id=Jackett&get_token=get_token&format=json_extended
is a link that fetches a token.
