### ISSUE TITLE
Jackett startup fails if config'ed proxy is un-resolvable

### ISSUE THREAD

**Issue by blu28** [Jackett/Jackett#8826]
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: v0.16.585

**Last Working Jackett Version**: v0.16.571

**Are you using a proxy or VPN?** [yes/no] I am using a socks6 proxy. 

### Description

Sometime this morning Jackett stopped working. Sonarr and Radarr cannot connect to it and the webui fails to connect as well. Looking at the log.txt file, I saw this:
2020-05-31 17:33:17.2361 Info New release found. Current version: v0.16.571 New version: v0.16.585 
2020-05-31 17:33:17.2759 Info Downloading release v0.16.585 It could take a while... 
2020-05-31 17:33:27.4619 Info Starting updater: C:\WINDOWS\TEMP\JackettUpdate-v0.16.585-637265432027085600\Jackett\JackettUpdater.exe --Path "C:\ProgramData\Jackett" --Type "WindowsService" --Args " " --KillPids "2060" 
2020-05-31 17:33:28.0795 Info Updater started process id: 1900 
2020-05-31 17:33:28.0795 Info Signal sent to lock service 
2020-05-31 17:33:30.0880 Info Exiting Jackett.. 
2020-05-31 17:33:50.1627 Info Starting Jackett v0.16.585.0 

After that each time Jackett starts it gets a traceback

### Logged Error Messages

2020-05-31 17:33:51.0949 Error Autofac.Core.DependencyResolutionException: An exception was thrown while activating Jackett.Server.Services.ServerService -> Jackett.Common.Services.IndexerManagerService -> Jackett.Common.Utils.Clients.HttpWebClient2NetCore.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient2NetCore'.
 ---> System.AggregateException: One or more errors occurred. (The requested name is valid, but no data of the requested type was found.)
 ---> System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.InitProxy(ServerConfig serverConfig) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 68
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__8_0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Jackett.Server.Helper.get_ServerService() in d:\a\1\s\src\Jackett.Server\Helper.cs:line 62
   at Jackett.Server.Helper.Initialize() in d:\a\1\s\src\Jackett.Server\Helper.cs:line 39
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in d:\a\1\s\src\Jackett.Server\Startup.cs:line 98
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args) Autofac.Core.DependencyResolutionException: An exception was thrown while activating Jackett.Server.Services.ServerService -> Jackett.Common.Services.IndexerManagerService -> Jackett.Common.Utils.Clients.HttpWebClient2NetCore.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Jackett.Common.Services.Interfaces.IProcessService, NLog.Logger, Jackett.Common.Services.Interfaces.IConfigurationService, Jackett.Common.Models.Config.ServerConfig)' on type 'HttpWebClient2NetCore'.
 ---> System.AggregateException: One or more errors occurred. (The requested name is valid, but no data of the requested type was found.)
 ---> System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostAddressesAsync>b__25_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.InitProxy(ServerConfig serverConfig) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 68
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__8_0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Container.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Jackett.Server.Helper.get_ServerService() in d:\a\1\s\src\Jackett.Server\Helper.cs:line 62
   at Jackett.Server.Helper.Initialize() in d:\a\1\s\src\Jackett.Server\Helper.cs:line 39
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in d:\a\1\s\src\Jackett.Server\Startup.cs:line 98
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)

This traceback appears every time I restart Jackett. Uninstalling and re-installing did not help.

**Comment by garfield69** [comment]
when did you switch to a ipv6 proxy?
edit C:\ProgramData\Jackett\ServerConfig.json with a plain text editor and change/set the following and save
```
  "ProxyUrl": "",
  "ProxyType": 0,
  "ProxyPort": null,
  "ProxyUsername": "",
  "ProxyPassword": "",
  "ProxyIsAnonymous": true
```
then restart the jackett service and see it now starts again.

**Comment by blu28** [comment]
I didn't. The proxy I use is IPv4. And I didn't touch it at all between the time it last worked and the update. That having been said though, the proxy I had configured doesn't seem to resolve at all anymore. My guess is that Jackett gets the same error whenever a proxy is unusable, whether because it is IPv6 or not found, and only at startup. In any case I already uninstalled, deleted the Jackett directory and then reinstalled and that resolved the problem.

**Comment by bitoiu** [comment]
My SOCKS5 proxy server was shutdown (third party), so I got this issue as well. In these cases I just change the server, but now I had this issue as well :octocat::heart:

**Comment by ngosang** [comment]
@garfield69 This is easy to solve but there are 2 solutions:
1. Disable the proxy and show an error. => I don't like this idea because it will leak the user IP, etc...
2. Configure a dummy proxy and show an error. => Requests to trackers will fail as if the proxy is wrong.

In both cases we show an error and the user will be able to change the proxy in Jackett UI. I'm going to open a PR with the second solution. What do you think?

**Comment by garfield69** [comment]
Option 2 seems reasonable to me.
Is the error only shown in the log?
Can the change include notification on the dashboard that the proxy is invalid?

**Comment by ngosang** [comment]
Jackett shows the error with traces at the startup and the trackers are not working to work, the user will notice.
I can't show the error in the UI. :cry:

**Comment by garfield69** [comment]
Okely Dokely.

**Comment by garfield69** [comment]
Jackett 0.16.1389
