### ISSUE TITLE
Unable to start Jackett - Error System.IO.IOException: Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8903]
After successfully installing the latest draft version (0.16.641.0), I tried starting Jackett on Windows 10 Pro 64-bit but I'm unable to start the service. I tried with the latest stable release as well (0.16.640) - same error. I'm not sure which file it's referring to here `Cannot create a file when that file already exists.` I tried deleting all the files in Jackett's directory - except for the Indexers & Definitions folders - but that didn't work either.

Note: There is no error message on Jackett's Web UI since I'm unable to start the service to begin with. As such, I cannot choose to produce the enhanced log. This is the output of the normal log:
```
2020-06-07 07:57:37.5384 Info Starting Jackett v0.16.641.0 
2020-06-07 07:57:38.1414 Info Environment version: 3.1.4 (C:\ProgramData\Jackett\) 
2020-06-07 07:57:38.1470 Info OS version: Microsoft Windows NT 6.2.9200.0 (64bit OS) 
2020-06-07 07:57:38.1470 Info Jackett variant: CoreWindows 
2020-06-07 07:57:38.1470 Info ThreadPool MaxThreads: 682 workerThreads, 1000 completionPortThreads 
2020-06-07 07:57:38.1662 Info App config/log directory: C:\ProgramData\Jackett 
2020-06-07 07:57:38.1662 Info Using Proxy: No 
2020-06-07 07:57:38.1865 Error System.IO.IOException: Cannot create a file when that file already exists.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at Jackett.Common.Services.IndexerManagerService.MigrateRenamedIndexers() in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 80
   at Jackett.Common.Services.IndexerManagerService.InitIndexers(IEnumerable`1 path) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 65
   at Jackett.Server.Services.ServerService.Initalize() in d:\a\1\s\src\Jackett.Server\Services\ServerService.cs:line 338
   at Jackett.Server.Helper.Initialize() in d:\a\1\s\src\Jackett.Server\Helper.cs:line 39
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in d:\a\1\s\src\Jackett.Server\Startup.cs:line 98
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args) System.IO.IOException: Cannot create a file when that file already exists.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at Jackett.Common.Services.IndexerManagerService.MigrateRenamedIndexers() in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 80
   at Jackett.Common.Services.IndexerManagerService.InitIndexers(IEnumerable`1 path) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 65
   at Jackett.Server.Services.ServerService.Initalize() in d:\a\1\s\src\Jackett.Server\Services\ServerService.cs:line 338
   at Jackett.Server.Helper.Initialize() in d:\a\1\s\src\Jackett.Server\Helper.cs:line 39
   at Jackett.Server.Startup.ConfigureServices(IServiceCollection services) in d:\a\1\s\src\Jackett.Server\Startup.cs:line 98
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jackett.Server.Program.Main(String[] args)
```

**Comment by RoloSoze** [comment]
Update: I just downloaded & installed 0.16.616 and it works fine! The issues starts only with 0.16.640! Is it just me or are others facing the same problem?

**Comment by ngosang** [comment]
I have several instances running in Linux and I can't see anything wrong. All of them were auto-updated to 0.16.640.0 without problems.

**Comment by ngosang** [comment]
I can't reproduce but I'm going to publish a fix.

**Comment by ngosang** [comment]
Jackett v0.16.643
