### ISSUE TITLE
[TorrentDay] Request to Jackett server failed

### ISSUE THREAD

**Issue by RoloSoze** [Jackett/Jackett#8912]
### Environment

**OS**: Windows 10 Pro 64-bit

**.Net Runtime**: N/A

**.Net Version**: N/A

**Jackett Version**: 0.16.643.0

**Last Working Jackett Version**: 0.16.616

**Are you using a proxy or VPN?** No

### Description

I am unable to configure TorrentDay

### Logged Error Messages

`Request to Jackett server failed`

Enhanced log shows it's a Cloudflare issue. Since TorrentDay uses an API, is there something that can be done? Perhaps using the cookie method to resolve this issue as was done in #8881 #8911? I haven't needed to reconfigure TD in a long time so I'm not sure whether it's already using the cookie method. If it is, can something else be done?

```2020-06-07 14:35:46.6864 Info Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/torrentday/config?_=12345678910   
2020-06-07 14:35:46.6864 Info Request starting HTTP/1.1 GET http://127.0.0.1:9117/api/v2.0/indexers/torrentday/config?_=12345678910   
2020-06-07 14:35:46.6964 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/torrentday/config?_=12345678910 
2020-06-07 14:35:46.6964 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/torrentday/config?_=12345678910 
2020-06-07 14:35:46.6964 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/torrentday/config?_=12345678910 
2020-06-07 14:35:46.6964 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/torrentday/config?_=12345678910 
2020-06-07 14:35:46.7167 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/torrentday/config?_=12345678910 
2020-06-07 14:35:46.7167 Debug Request is continuing in applying rules. Current url is http://127.0.0.1:9117/api/v2.0/indexers/torrentday/config?_=12345678910 
2020-06-07 14:35:46.7167 Debug The request path /api/v2.0/indexers/torrentday/config does not match a supported file type 
2020-06-07 14:35:46.7167 Debug The request path /api/v2.0/indexers/torrentday/config does not match a supported file type 
2020-06-07 14:35:46.7354 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2020-06-07 14:35:46.7354 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2020-06-07 14:35:46.7354 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/torrentday/config' 
2020-06-07 14:35:46.7354 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/torrentday/config' 
2020-06-07 14:35:46.7548 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/torrentday/config' 
2020-06-07 14:35:46.7548 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/torrentday/config' 
2020-06-07 14:35:46.7642 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' 
2020-06-07 14:35:46.7642 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' 
2020-06-07 14:35:46.7642 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' 
2020-06-07 14:35:46.7642 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' 
2020-06-07 14:35:46.7872 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (JackettConsole). 
2020-06-07 14:35:46.7872 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (JackettConsole). 
2020-06-07 14:35:46.7984 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2020-06-07 14:35:46.7984 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2020-06-07 14:35:46.8084 Debug Execution plan of resource filters (in the following order): None 
2020-06-07 14:35:46.8084 Debug Execution plan of resource filters (in the following order): None 
2020-06-07 14:35:46.8200 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2020-06-07 14:35:46.8200 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2020-06-07 14:35:46.8200 Debug Execution plan of exception filters (in the following order): None 
2020-06-07 14:35:46.8200 Debug Execution plan of exception filters (in the following order): None 
2020-06-07 14:35:46.8402 Debug Execution plan of result filters (in the following order): None 
2020-06-07 14:35:46.8402 Debug Execution plan of result filters (in the following order): None 
2020-06-07 14:35:46.8503 Info Authorization was successful. 
2020-06-07 14:35:46.8503 Info Authorization was successful. 
2020-06-07 14:35:46.8503 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2020-06-07 14:35:46.8503 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2020-06-07 14:35:46.8708 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2020-06-07 14:35:46.8708 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (JackettConsole) 
2020-06-07 14:35:46.8838 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://torrentday.it/login.php) 
2020-06-07 14:35:50.0865 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole) in 3236.2627ms 
2020-06-07 14:35:50.0865 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole) in 3236.2627ms 
2020-06-07 14:35:50.0865 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' 
2020-06-07 14:35:50.0865 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (JackettConsole)' 
2020-06-07 14:35:50.1132 Error CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in d:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 447
   at Jackett.Common.Indexers.TorrentDay.GetConfigurationForSetup() in d:\a\1\s\src\Jackett.Common\Indexers\TorrentDay.cs:line 126
   at Jackett.Server.Controllers.IndexerApiController.Config() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 81
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70 CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in d:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 447
   at Jackett.Common.Indexers.TorrentDay.GetConfigurationForSetup() in d:\a\1\s\src\Jackett.Common\Indexers\TorrentDay.cs:line 126
   at Jackett.Server.Controllers.IndexerApiController.Config() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 81
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70
2020-06-07 14:35:50.1297 Debug The response will be compressed with 'gzip'. 
2020-06-07 14:35:50.1297 Debug The response will be compressed with 'gzip'. 
2020-06-07 14:35:50.1435 Debug Connection id "0HM0B13AG5L2V" completed keep alive response. 
2020-06-07 14:35:50.1435 Debug Connection id "0HM0B13AG5L2V" completed keep alive response. 
2020-06-07 14:35:50.1587 Info Request finished in 3472.3431ms 500 application/json 
2020-06-07 14:35:50.1587 Info Request finished in 3472.3431ms 500 application/json 
```
### Screenshot
![image](https://user-images.githubusercontent.com/23747425/84046902-b0774e80-a978-11ea-82eb-81b94ddbf426.png)

**Comment by RoloSoze** [comment]
Works well! Thank you!

**Comment by garfield69** [comment]
Jackett 0.16.691
