### ISSUE TITLE
[rarbg] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by jplobao** [Jackett/Jackett#8945]
Maybe changed the URL to: https://rarbgproxied.org/

Error Log:
System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 277
   at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

**Comment by garfield69** [comment]
The `ranked=0` according to the docs, allows for all torrent groups to be selected, the default being that only rarbg group torrents are returned.
When doing a keywordless search, API uses the `mode=list`, and for keyword searches the API uses `mode=search`
Clearly rarbg have changed something (or something is broken on the rarbg API server end), and when doing a keywordless search, the combo of `mode=list` and `ranked=0` it returns error=20
`mode=search` and `ranked=0` continues to work.
So I've updated the indexer to drop using `ranked=0` with `mode=list` and tested this, its seems to work OK for me.

**Comment by garfield69** [comment]
Jackett 0.16.700

**Comment by jplobao** [comment]
I updated and got same error:


2020-06-12 11:08:43 | Error | System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 277    at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
-- | -- | --

**Comment by jkossis** [comment]
Same here. Getting the same error, even with .700.

**Comment by garfield69** [comment]
try again. the issue is with the server and not with jackett.
I testing this this morning, and I also got an error, but when I tried it the second time it started working again.

**Comment by garfield69** [comment]
in fact, currently I get results for keyword searches, but for keywordless searches it can take several attempts before the server returns results. 
definitely an issue at the rarbg API server end.

**Comment by garfield69** [comment]
adding ranked=0 back in, as that does still work after all. the issue is with the rarbg server.
nothing Jackett can do about it. will just have to wait for rarbg to sort it out.

**Comment by garfield69** [comment]
Starting with 16.1163 there is a fix that should help prevent this.
The current latest version at the time of this post is 0.16.1218

**Comment by gdavidp** [comment]
This issue has been happening for me for weeks, with Jackett in a Docker on UnRAID. No updates available so I am assuming that v0.20.65 is relatively recent.

**Comment by garfield69** [comment]
@gdavidp  the RarBG API server has been notoriously unreliable for nearly a year or more now.
Currently it will return no results randomly until a later retry succeeds.
And there is nothing we can do about it.
