### ISSUE TITLE
[revolutiontt] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by cspiby** [Jackett/Jackett#8972]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**: Unknown

**Jackett Version**: 0.16.704.0

**Last Working Jackett Version**: Not sure

**Are you using a proxy or VPN?** [yes/no] Yes

### Description

Trying to update credentials resulted in error, removed tracker and tried to re-add but same issue.

### Logged Error Messages

System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.RevolutionTT.<>c__DisplayClass16_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RevolutionTT.cs:line 204
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 260
   at Jackett.Common.Indexers.RevolutionTT.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RevolutionTT.cs:line 201
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by cspiby** [comment]
Also seems to be occurring without VPN.

**Comment by cspiby** [comment]
Enhanced logs attached.
[revlog.txt](https://github.com/Jackett/Jackett/files/4775627/revlog.txt)

**Comment by garfield69** [comment]
after updating your credentials on the web site, did you logoff?
some sites do not save login details (or update their cache cookies) until your logoff.
Have you logged onto the web site, confirmed that you have a good ratio, and have no outstanding alerts, notices, or PM that may prevent you accessing the site's torrent search page?
Some sites block users until all notices or alerts or PM are read, or if they have bad ratio.

If you still have the issue, have you tried using your VPN to allocate an alternate IP in a different region?
Or even trying another VPN?
The closes similar ticket was with the web site blocking the users' IP.

**Comment by cspiby** [comment]
Absolutely, I'm able to log in and out at will, with or without the VPN (confirmed by checking https://whatismyipaddress.com/) through my browser.

No pending anything on my account, ratio is good.

**Comment by garfield69** [comment]
@ERR1R  is the revolutiontt indexer working for you?

**Comment by cspiby** [comment]
Really sorry, seems that Chrome has saved 2 generated passwords for the same site with slightly different login credentials!

**Comment by cspiby** [comment]
This is still occuring intermittantly even after verifying the correct password is entered.

I notice that system has a warning that the tracker is unreachable but if I then choose to test it, the test succeeds.

I'm getting a similar message in the log:

20-6-16 09:29:00.7|Error|Torznab|An error occurred while processing feed. http://192.168.1.253:9117/torznab/revolutiontt/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&q=Cops&season=30

[v2.0.0.5344] NzbDrone.Core.Indexers.Torznab.TorznabException: Torznab error detected: System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.BaseWebIndexer.CleanLinks(IEnumerable`1 releases) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 791
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 808
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 430
  at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000b6] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:42 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\RssParser.cs:55 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00050] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:308 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchReleases (System.Func`2[T,TResult] pageableRequestChainSelector, System.Boolean isRecent) [0x000a0] in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:143

**Comment by antaflos** [comment]
Basically same here. When doing a manual search in Jackett and leaving the query field empty (or using `*` as search query) it correctly displays results, but when entering a specific search term (like `foo`) it fails with an error message like this:

```
Jackett.Common.IndexerException: Exception (revolutiontt): Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.RevolutionTT.<>c__DisplayClass16_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RevolutionTT.cs:line 204
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 260
   at Jackett.Common.Indexers.RevolutionTT.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RevolutionTT.cs:line 201
   at Jackett.Common.Indexers.RevolutionTT.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RevolutionTT.cs:line 317
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 224
```

Using Jackett 0.16.722.0 in Docker (Kubernetes).

**Comment by ngosang** [comment]
I don't have an account in revolutiontt to fix the issue. Please, send me an invitation or do this:
1. Open the site in your browser and search `foo`
2. Save the HTML code, remove the sensible information and upload the file here (with .txt extension)

**Comment by cspiby** [comment]
> I don't have an account in revolutiontt to fix the issue. Please, send me an invitation or do this:
> 
> 1. Open the site in your browser and search `foo`
> 2. Save the HTML code, remove the sensible information and upload the file here (with .txt extension)

Whilst logged in or out? There is nothing matching 'foo' in the page source.

**Comment by ngosang** [comment]
You have to be loged-in. Just make a text search, like "harry". Make sure the response has results.

**Comment by cspiby** [comment]
> You have to be loged-in. Just make a text search, like "harry". Make sure the response has results.

https://gist.github.com/cspiby/9d23020b196eb42713987410069b4c64

**Comment by ngosang** [comment]
Test Jackett in a few days. I can't fix the issue, but the error will be more clear.

**Comment by ngosang** [comment]
Jackett 0.16.759

**Comment by ERR1R** [comment]
so i build the debug and test it with revolution.

I can add the tracker, search for stuff etc.. and all is working fine.

Do you guys use mono maybe?  Because on my syno i get the same error.

**Comment by cspiby** [comment]
> so i build the debug and test it with revolution.
> 
> I can add the tracker, search for stuff etc.. and all is working fine.
> 
> Do you guys use mono maybe? Because on my syno i get the same error.

Yes I use mono as it states in the top post.

**Comment by kuthedk** [comment]
@ngosang if I get you an invite can you fix this? if you cant, who can and I will set them up with an invite.

**Comment by ngosang** [comment]
@kuthedk Yes, send me the invite to my email.

**Comment by kuthedk** [comment]
@ngosang the invite has been sent to the email that your github account is associated with

**Comment by ngosang** [comment]
@kuthedk I received the invitation but it expired. Could you send it again? Thank you!
