### ISSUE TITLE
[rutracker] Request to Jackett server failed

### ISSUE THREAD

**Issue by BachoSeven** [Jackett/Jackett#8998]
### Environment

**OS**:
Arch Linux

**Jackett Version**:
0.16.728-1
**Last Working Jackett Version**:
Master version from around a month ago, I was on Ubuntu at that time
**Are you using a proxy or VPN?** [yes/no]
no
### Description

On the latest Arch packaged version of Jackett (but it was so since a week, I only got to report it now) trying to add the `rutracker.org` indexer returns "Request to Jackett server failed" with the following output log:

### Logged Error Messages
```
System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 443
   at Jackett.Common.Indexers.RuTracker.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RuTracker.cs:line 1510
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by ilike2burnthing** [comment]
Are you able to connect to the site, search and download on the same system and network?

**Comment by BachoSeven** [comment]
Sorry for missing that, I can only connect to rutracker.net but not to the main mirror. The site is not down as I could get it working with a VPN in Sweden for example, and then Jackett works.

My issue then is that I cannot even get to the configuration of the indexer before trying to access it; it would be nice if I could, so I might select/insert a mirror which works with the same API... Do you think that could be implemented?

**Comment by ilike2burnthing** [comment]
When you click Configure (wrench icon), change the Site Link to .net instead, then enter the necessary information.

If it's a straight mirror, and not a clone, then there shouldn't be an issue.

Let me know if that works.

**Comment by BachoSeven** [comment]
That is exactly the issue, so to clarify:

1. I open jackett localhost on my browser
2. I click on "Add Indexer"
3. I find rutracker && click on the configure button
4. I get the aforementioned output & log.

**Comment by ilike2burnthing** [comment]
Ah kk.

Can you use your VPN to set it up initially, change to .net, enter your details and click Okay, disable your VPN, and test the indexer?

**Comment by BachoSeven** [comment]
Oki so that ended up working, thanks for the workaround! Not sure if this needs to be addressed anyways, so I won't close it right away.

**Comment by ilike2burnthing** [comment]
It's similar to #7849 but in this you can't even access configuration.

@garfield69 @ngosang @cadatoiva any ideas on what a potential solution might be? Quick summary is that if a user cannot access the default URL for rutracker (possibly also other indexers), clicking configuration will fail, preventing them from adding a working mirror.

**Comment by garfield69** [comment]
not quite the same as 7849 because this is not a Cardigann indexer, but one written in C#.
It's possible this indexer has not had its code updated to handle a login-page-fetch-failed handler like the one added to the Cardigann processor for 7849 to allow it to present the config page despite the error.

**Comment by garfield69** [comment]
Jackett 0.16.759
