### ISSUE TITLE
[torrenting] Exception (torrenting): Object reference not set to an instance of an object.: Parse error (Test)

### ISSUE THREAD

**Issue by armando-ca** [Jackett/Jackett#9053]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
v0.16.767

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
Yes

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

2020-06-25 22:30:09 | Error | {0} Jackett.Common.IndexerException: Exception (torrenting): Object reference not set to an instance of an object.  ---> System.Exception: Parse error  ---> System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 520    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1359    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 831    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1682    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 325    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 804    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 274    at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
-- | -- | --
2020-06-25 22:30:09 | Error | Error on 20200625223009 for Torrenting.txtSystem.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 520    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1359

**Comment by garfield69** [comment]
No one on the team has an account on this site, so we cannot independently check.
For myself, I see that the torrenting site login page has a recaptcha enabled, which means that the standard usernam/password login will not work, and the Jackett config is now asking for a cookie.
Does that apply to you too, and have you fetched the correct cookie string?
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work

The stack trace you provided is unfortunately my useful in determining the cause of your problem.

So if you have the correct cookie and you are still seeing this error, then you have one of two options:
1. send an invite to garfieldsixtynine -at- gmail.com so I can research
or
2. provide a **full enhanced** log with debug and HTML which may help give us more info to work with.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by garfield69** [comment]
Hah!. 
Just found out that registration on the site is open, and I've successfully registered and logged in.
I've also confirmed that the indexer works for me, once I fetched the correct cookie string and updated the Jackett dashboard config for the Torrenting indexer.
So this is most likely the cause of your problem.
Access your Jackett dashboard, edit the Torrenting config, and update it with the requested cookie string.
Let me know how you go.

**Comment by armando-ca** [comment]
Got it! thank you! for the quick reply - Question does the cookie change at each log in? because Jackett and indexer was working just fine then I started to received the error message.

**Comment by garfield69** [comment]
I don't know for sure. Usually the cookie lasts until the expiry date, and each site decides when that is, some have just one day, others months.
But with the current anti-DDoS check on the login page that the site has, the cookie may well expire more frequently than usual.
Once the alert period is over, I expect the site will drop the recaptcha, and the indexer can go back to using the regular username/password login again.
