### ISSUE TITLE
TorrentDay Indexer Failed: "Request to Jackett server failed"

### ISSUE THREAD

**Issue by TheSlimGeek** [Jackett/Jackett#9056]
Synology NAS

Jackett Version 0.16.609.0

This has happened for several weeks. I thought time would help, but it has not. All other indexers that I have tested are working. Looking at the logs, looks like something to do with CloudFare. I am new to this, so I am unfamiliar with how to completely troubleshoot and resolve some of these issues.

Thank in advance to anyone who can help!

2020-06-26 10:39:01.9997 Debug Connection id "0HM0PRDTC5J90" accepted. 
2020-06-26 10:39:02.0022 Debug Connection id "0HM0PRDTC5J90" started. 
2020-06-26 10:39:02.0034 Info Request starting HTTP/1.1 GET http://192.168.1.12:9117/api/v2.0/indexers/torrentday/config?_=1593181917338   
2020-06-26 10:39:02.0040 Debug Request is continuing in applying rules. Current url is http://192.168.1.12:9117/api/v2.0/indexers/torrentday/config?_=1593181917338 
2020-06-26 10:39:02.0040 Debug Request is continuing in applying rules. Current url is http://192.168.1.12:9117/api/v2.0/indexers/torrentday/config?_=1593181917338 
2020-06-26 10:39:02.0040 Debug Request is continuing in applying rules. Current url is http://192.168.1.12:9117/api/v2.0/indexers/torrentday/config?_=1593181917338 
2020-06-26 10:39:02.0048 Debug The request path /api/v2.0/indexers/torrentday/config does not match a supported file type 
2020-06-26 10:39:02.0064 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2020-06-26 10:39:02.0090 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/torrentday/config' 
2020-06-26 10:39:02.0090 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/torrentday/config' 
2020-06-26 10:39:02.0098 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
2020-06-26 10:39:02.0098 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
2020-06-26 10:39:02.0107 Info Route matched with {action = "Config", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Config() on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2020-06-26 10:39:02.0107 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2020-06-26 10:39:02.0107 Debug Execution plan of resource filters (in the following order): None 
2020-06-26 10:39:02.0117 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2020-06-26 10:39:02.0117 Debug Execution plan of exception filters (in the following order): None 
2020-06-26 10:39:02.0117 Debug Execution plan of result filters (in the following order): None 
2020-06-26 10:39:02.0131 Info Authorization was successful. 
2020-06-26 10:39:02.0131 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2020-06-26 10:39:02.0140 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2020-06-26 10:39:02.0140 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://tday.love/login.php) 
2020-06-26 10:39:04.0255 Info Executed action Jackett.Server.Controllers.IndexerApiController.Config (jackett) in 2012.9811ms 
2020-06-26 10:39:04.0262 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Config (jackett)' 
2020-06-26 10:39:04.0269 Error CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 443
   at Jackett.Common.Indexers.TorrentDay.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentDay.cs:line 126
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 114
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 443
   at Jackett.Common.Indexers.TorrentDay.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/TorrentDay.cs:line 126
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2020-06-26 10:39:04.0373 Debug The response will be compressed with 'gzip'. 
2020-06-26 10:39:04.0391 Debug Connection id "0HM0PRDTC5J90" completed keep alive response. 
2020-06-26 10:39:04.0397 Info Request finished in 2036.3352ms 500 application/json

**Comment by garfield69** [comment]
I just tried using the default sitelink https://tday.love/ with my browser but it stays there on an infinite loop displaying the cloudflare checking-your-browser-before-accessing page, so that domain is currently broken.
same goes for https://torrentday.cool/ and https://torrentday.it/

These domains present a login page after the cloudflare anti-DDoS check
https://torrentday.cool/
https://classic.torrentday.com/
https://www.torrentday.com/
https://td.findnemo.net/
https://td.getcrazy.me/
https://td.venom.global/
https://td.workisboring.net/

so switch to using one of these.

**Comment by ilike2burnthing** [comment]
Those three are working again for me, so far as the login page anyway.

**Comment by TheSlimGeek** [comment]
> I just tried using the default sitelink https://tday.love/ with my browser but it stays there on an infinite loop displaying the cloudflare checking-your-browser-before-accessing page, so that domain is currently broken.
> same goes for https://torrentday.cool/ and https://torrentday.it/
> 
> These domains present a login page after the cloudflare anti-DDoS check
> https://torrentday.cool/
> https://classic.torrentday.com/
> https://www.torrentday.com/
> https://td.findnemo.net/
> https://td.getcrazy.me/
> https://td.venom.global/
> https://td.workisboring.net/
> 
> so switch to using one of these.

Thank you! How do I configure Jackett to reference one of those links instead?

**Comment by garfield69** [comment]
Start by updating to 0.16.771 by using the check-for-updates on your Jackett dashboard.
Then if necessary use the wrench icon to edit the config and select any of the others.
If the config panel does not show up then access your indexers folder and edit with a plain text editor the torretnday.json config file and manually change the site link.
restart jackett to load.
