### ISSUE TITLE
{0} System.ArgumentException: '', hexadecimal value 0x1A, is an invalid character.

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#9118]
Getting this when searching for "yoku" in all trackers. Jackett webpage freezes while searching. When searching through qbittorrent I get this `Jackett: connection error! Right-click this row and select 'Open description page' to open help. Configuration file: 'C:\Users\a\AppData\Local\qBittorrent\nova3\engines\jackett.json' Search: 'yoku'`. Here's part of enhanced logs containing the errors:

2020-07-08 01:02:11 | Debug | Connection id "{ConnectionId}" stopped.
-- | -- | --
2020-07-08 01:02:11 | Debug | Connection id "{ConnectionId}" disconnecting.
2020-07-08 01:02:11 | Debug | Connection id "{ConnectionId}" sending FIN because: "{Reason}"
2020-07-08 01:02:11 | Info | Request finished in 65787.8808ms 500 application/json
2020-07-08 01:02:11 | Debug | Connection id "{ConnectionId}" received FIN.
2020-07-08 01:02:11 | Debug | No matching response compression provider found.
2020-07-08 01:02:11 | Error | {0} System.ArgumentException: '', hexadecimal value 0x1A, is an invalid character.    at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)    at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)    at System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)    at System.Xml.XmlWellFormedWriter.WriteString(String text)    at System.Xml.XmlWriter.WriteAttributeString(String prefix, String localName, String ns, String value)    at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)    at System.Xml.Linq.ElementWriter.WriteElement(XElement e)    at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)    at System.Xml.Linq.XContainer.WriteContentTo(XmlWriter writer)    at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)    at System.Xml.Linq.XNode.ToString()    at Jackett.Server.Controllers.ResultsController.CreateErrorXML(Int32 code, String description) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 444    at Jackett.Server.Controllers.ResultsController.GetErrorXML(Int32 code, String description) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 433    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 428    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
2020-07-08 01:02:11 | Info | Executed endpoint '{EndpointName}'
2020-07-08 01:02:11 | Info | Executed action {ActionName} in {ElapsedMilliseconds}ms
2020-07-08 01:02:11 | Error | {0} System.ArgumentException: '', hexadecimal value 0x1A, is an invalid character.    at System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)    at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)    at System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)    at System.Xml.XmlWellFormedWriter.WriteString(String text)    at System.Xml.Linq.ElementWriter.WriteElement(XElement e)    at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)    at System.Xml.Linq.XContainer.WriteContentTo(XmlWriter writer)    at System.Xml.Linq.XNode.GetXmlString(SaveOptions o)    at System.Xml.Linq.XNode.ToString()    at Jackett.Common.Models.ResultPage.ToXml(Uri selfAtom) in d:\a\1\s\src\Jackett.Common\Models\ResultPage.cs:line 97    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 420
2020-07-08 01:02:10 | Info | Found 2835 releases from AggregateSearch for: yoku
2020-07-08 01:01:55 | Debug | WebClient(HttpWebClient2NetCore): Returning Moved => https://www.elitetorrent.to/
2020-07-08 01:01:55 | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://www.elitetorrent.to/page/3/?s=yoku&x=0&y=0)
2020-07-08 01:01:55 | Info | CardigannIndexer (elitetorrent-biz): Relogin required
2020-07-08 01:01:55 | Debug | WebClient(HttpWebClient2NetCore): Returning Moved => https://www.elitetorrent.to/
2020-07-08 01:01:55 | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://www.elitetorrent.to/page/3/?s=yoku&x=0&y=0)
2020-07-08 01:01:55 | Debug | WebClient(HttpWebClient2NetCore): Returning Moved => https://www.elitetorrent.to/
2020-07-08 01:01:55 | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://www.elitetorrent.to/page/2/?s=yoku&x=0&y=0)
2020-07-08 01:01:55 | Info | CardigannIndexer (elitetorrent-biz): Relogin required
2020-07-08 01:01:55 | Debug | WebClient(HttpWebClient2NetCore): Returning Moved => https://www.elitetorrent.to/
2020-07-08 01:01:54 | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://www.elitetorrent.to/page/2/?s=yoku&x=0&y=0)
2020-07-08 01:01:54 | Debug | CardigannIndexer (elitetorrent-biz): skipping en el camino dvdscreener (andmatch filter)
2020-07-08 01:01:54 | Debug | CardigannIndexer (elitetorrent-biz): skipping the honor list hdrip vose bittorrent hd 1 (andmatch filter)
2020-07-08 01:01:54 | Debug | CardigannIndexer (elitetorrent-biz): skipping super bomberos 1080p latino (andmatch filter)
2020-07-08 01:01:54 | Debug | CardigannIndexer (elitetorrent-biz): skipping ransom 1x12 (andmatch filter)
2020-07-08 01:01:54 | Debug | CardigannIndexer (elitetorrent-biz): skipping curse witchs doll (andmatch filter)
2020-07-08 01:01:54 | Debug | CardigannIndexer (elitetorrent-biz): skipping major crimes 4x07 (andmatch filter)

**Comment by garfield69** [comment]
@ngosang  looks like the rss xml processing Jackett is performing may need to filter this and similar chars from the titles or other fields in the stream?
@janot it would be useful to know which indexers you have loaded on Jackett so that we can replicate your results for testing.

**Comment by janot** [comment]
I have 171 indexer enabled right now, so i suppose posting full list won't be useful for you(

**Comment by garfield69** [comment]
Jackett 0.16.1350
