### ISSUE TITLE
[kickasstorrent] new site address

### ISSUE THREAD

**Issue by lukjod** [Jackett/Jackett#9132]
new address of KAT has changed:
https://newkatcr.co/

**Comment by garfield69** [comment]
the site is in the process of migrating to a new platform engine and not all features are working yet.
There is likely changes required not just to the indexer sitelink, but with the html processing as well.
will update the indexer as soon as things settle on the site to a working state.

**Comment by garfield69** [comment]
note: at the time of this post, the latest page seems to be working, https://newkatcr.co/v2/category/latest/1/6/
but searching with keywords does not.

**Comment by garfield69** [comment]
update as of this post: 
Site Main Search (60% done)
Still have to adjust some details of the search engine, still have 40% of work left
[*] Category classification function added

**Comment by garfield69** [comment]
Jackett 0.16.848

**Comment by lukjod** [comment]
Thank You very much

**Comment by ilike2burnthing** [comment]
https://newkatcr.co/ - ERR_CONNECTION_TIMED_OUT

**Comment by lukjod** [comment]
Works ok for me

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
> https://newkatcr.co/ - ERR_CONNECTION_TIMED_OUT

**Comment by lukjod** [comment]
https://kickasstorrents.to/

This works again successfully

**Comment by ilike2burnthing** [comment]
It's not the same site, nor is it kathow, it's a third KAT.
https://github.com/Jackett/Jackett/blob/c346af3c245991ae4fb516801add23690dac2fef/src/Jackett.Common/Definitions/kickasstorrent.yml#L18
See the same results:
- https://kickasstorrent.cr/usearch/720p/
- https://kickasstorrents.to/usearch/720p/

**Comment by lukjod** [comment]
Why do they keep doing such a mess...

**Comment by ilike2burnthing** [comment]
It's completely different people

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
As of today, newkatcr seems to be mostly failing in Jackett (~20:1), with no HTML being returned, but no issues on the site that I could see.

Couldn't see any pattern to when it would and wouldn't work, though I noticed I didn't have the same issue with:
https://kickasstorrents.unblockninja.com/
https://kat.unblockit.win/

Tried with and without proxy/VPN, Docker and Windows Sandbox, 0.16.991 and 0.16.998. Removing KAT and restarting didn't help.

Successful - [log1.txt](https://github.com/Jackett/Jackett/files/5078311/log1.txt)
```
2020-08-15 08:25:21.4343 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://newkatcr.co/v2/category/latest/1/6/) 
2020-08-15 08:25:21.8903 Debug KATSSESS_ID70AT8=15k9dtm0fvt1cbiauv1bsb6hsukpcl1f; expires=Sat, 15-Aug-2020 19:19:52 GMT; Max-Age=43200; path=/; domain=newkatcr.co; secure; HttpOnly 
2020-08-15 08:25:21.8903 Debug WebClient(HttpWebClient2NetCore): Returning OK => <!DOCTYPE html>
<html lang="en-us">
[...]
```

Unsuccessful - [log2.txt](https://github.com/Jackett/Jackett/files/5078312/log2.txt)
```
2020-08-15 08:25:55.8177 Debug WebClient(HttpWebClient2NetCore).GetString(Url:https://newkatcr.co/v2/category/latest/1/6/) 
2020-08-15 08:25:56.0074 Debug WebClient(HttpWebClient2NetCore): Returning OK =>  
2020-08-15 08:25:56.0074 Info Found 0 releases from KickAssTorrent 
2020-08-15 08:25:56.0074 Debug Saving new config file: C:\ProgramData\Jackett\Indexers\kickasstorrent.json.a0295d304dec48aba72e0494b55b9f53.tmp 
2020-08-15 08:25:56.0225 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 195.2443ms 
2020-08-15 08:25:56.0225 Info Executed action Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole) in 195.2443ms 
2020-08-15 08:25:56.0225 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' 
2020-08-15 08:25:56.0225 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.Test (JackettConsole)' 
2020-08-15 08:25:56.0225 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 277
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70 System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 277
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70
```

Posting here as it's likely another change to the new site, but this can be reposted as its own issue if preferred.

**Comment by lukjod** [comment]
Totally same story in my case, it works well on browser so probably some changes have to be make on Jackett side

**Comment by ilike2burnthing** [comment]
Seems to be working fine now. Must have been an issue with the site.

**Comment by ilike2burnthing** [comment]
> https://newkatcr.co/ - ERR_CONNECTION_TIMED_OUT

**Comment by lukjod** [comment]
new main domain is:
https://kickasstorrents.to/

**Comment by ilike2burnthing** [comment]
As I said before, it's not

**Comment by ilike2burnthing** [comment]
Note to self: #9400

**Comment by aytimothy** [comment]
@lukjod It's not. See this screenshot:
![http://i.imgur.com/zDTieri.png](http://i.imgur.com/zDTieri.png)

**Comment by ilike2burnthing** [comment]
`Kickass will be backup and running in a few days`
https://twitter.com/KATCR_co/status/1307071677914906624

**Comment by aytimothy** [comment]
> `Kickass will be backup and running in a few days` - 18 Sep 2020
> https://twitter.com/KATCR_co/status/1307071677914906624

It's been a week already... Oh well, another week, I guess?

—/u/aytimothy

**Comment by ilike2burnthing** [comment]
https://newkatcr.co/ - back up (though unreachable for me without VPN or proxy)
https://newkatcr.co/v2/category/latest/1/6/ - working
https://newkatcr.co/search/?q=720p (or any search) - 404
```
Downtime - Updates Oct 2 2020
Hope you all doing well and keeping safe.
Unfortunately, we have lost a crucial server. We run the site as not-for-profit and
often we pay site costs from our own pockets - we really do strongly believe in
the KAT vision. With the Covid situation worldwide causing delays and difficulties
everywhere, we're seeking to replace the server at this time. We anticipate being
back online within a week or so, valid to mention that the site's databases are
protected on servers unrelated to this incident. We anticipate being back full
online within a week or so.
As always we appreciate the encouragement of our members, KAT Team, Torrent
Freak and the torrent community in general, we have committed ourselves to
continue fighting the good fight, no matter what it takes.
Kind regards,
Mrs.Smith
KAT Admin
```
https://newkatcr.co/status/

**Comment by ilike2burnthing** [comment]
search is now working, so newkat is finally fully back up after 40 days

**Comment by ilike2burnthing** [comment]
https://newkatcr.co/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
back up

**Comment by aytimothy** [comment]
@ilike2burnthing It's going to be up and down while the site is being migrated.mm *still*

I think it's just taking a little longer than estimated...

**Comment by ilike2burnthing** [comment]
> https://newkatcr.co/ - Error 504 - Gateway time-out

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/commit/76cacb1c4ac81ac57bc9516660332e85d3a11491
