### ISSUE TITLE
[yts] The SSL connection could not be established, see inner exception.: The handshake failed due to an unexpected packet format. (Config)

### ISSUE THREAD

**Issue by zohaibs1011** [Jackett/Jackett#9136]
#8568 # Environment

**OS**: Windows 10 Pro V.1903

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: ?

**Jackett Version**: 0.16.817.0

**Last Working Jackett Version**: N/A

**Are you using a proxy or VPN?** [yes/no] Tried it with VPN enabled and disabled

### Description

Try to add YTS as an indexer

### Logged Error Messages

{0} System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookiesAndRetry(String url, String cookieOverride, String referer, Dictionary`2 headers) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 466
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in d:\a\1\s\src\Jackett.Common\Indexers\YTS.cs:line 102
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\YTS.cs:line 76
   at Jackett.Common.Indexers.YTS.ApplyConfiguration(JToken configJson) in d:\a\1\s\src\Jackett.Common\Indexers\YTS.cs:line 68
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26

### Screenshots

![Jackett](https://user-images.githubusercontent.com/63616015/87233497-e9fc0900-c3bf-11ea-957f-488e6f1b8c33.png)

**Comment by garfield69** [comment]
the YTS indexer is working for me on my win10 system, which suggests the issue is at your end.

Likely you are being blocked by your ISP or something else  is interfering with your https certificate negotiation.

Open a browser on the same system that you are running Jackett on and try to access this link https://yts.mx/api/v2/list_movies.json
If it is working then you should see a response similar to 
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":18717,"limit":20,"page_number":1,"movies":[{"id":19152,"url":"https:\/\/yts.mx\/movies\/first-cow-2019","imdb_code":"tt9231040","title":"First Cow","title_english":"First Cow","title_long":"First Cow (2019)","slug":"first-cow-2019","year":2019,"rating":7.2,"runtime":122,"genres":["Drama"],"summary": [etc etc etc]
```

Double check that your Jackett indexer sitelink is set to `https://yts.mx/` using your Jackett dashboard wrench icon to edit the YTS indexer config.
