### ISSUE TITLE
The JIT compiler encountered invalid IL code or an internal limitation.

### ISSUE THREAD

**Issue by Ahim13** [Jackett/Jackett#9144]
### Environment

**OS**: openmediavault

**Jackett Version**:  v0.16.830-ls9

**Last Working Jackett Version**: previous

**Are you using a proxy or VPN?** [yes/no] no

### Logged Error Messages

The JIT compiler encountered invalid IL code or an internal limitation.

{0} System.InvalidProgramException: The JIT compiler encountered invalid IL code or an internal limitation.
   at GetDestination(String , Int32 , Int32 )
   at Microsoft.AspNetCore.Routing.Matching.ILEmitTrieJumpTable.<>c__DisplayClass14_0.<InitializeILDelegate>b__0(String path, PathSegment segment)
   at Microsoft.AspNetCore.Routing.Matching.ILEmitTrieJumpTable.GetDestination(String path, PathSegment segment)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.FindCandidateSet(HttpContext httpContext, String path, ReadOnlySpan`1 segments)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

**Comment by garfield69** [comment]
is this error at startup preventing Jackett running, or a result of perform a search on an indexer?
If the former, let us know.
If  the latter then please provide a **full enhanced** log by following https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by Ahim13** [comment]
Hm, I tried to do that, enabling enmhanced log then the test was succesful, so I changed it back and the webUI died. It did not loaded in no matter how many times I restarted. I deleted the settings folder (resetted it) and now it works, no idea why or what was the problem before.
