### ISSUE TITLE
Almost all indexers disappear each time I update Jackett on Unraid

### ISSUE THREAD

**Issue by hbooo** [Jackett/Jackett#9152]
# Environment 

**OS**: Unraid

07-13 14:29:53 Info Starting Jackett v0.16.836.0
07-13 14:29:56 Info Environment version: 3.1.5 (/app/Jackett/)

07-13 14:29:56 Info OS version: Unix 4.19.107.0 (64bit OS) (64bit process)

07-13 14:29:56 Info Jackett variant: CoreLinuxAmdx64
07-13 14:29:56 Info File /etc/issue: Ubuntu 18.04.4 LTS \n \l

**Are you using a proxy or VPN?** [no]

### Description

Each time I update my Jackett Docker on Unraid I have almost all my indexers that are removed with the following error message.

Some indexer are still present after each update : xthor and torrentz2.

I already tried to stop docker, remove files from Jackett/Indexers, start docker and add them but they are removed after a reboot of the docker image.

### Logged Error Messages

07-13 14:29:56 Info Jackett variant: CoreLinuxAmdx64
07-13 14:29:56 Info File /etc/issue: Ubuntu 18.04.4 LTS \n \l
07-13 14:29:56 Info Running in Docker: Yes
07-13 14:29:56 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
07-13 14:29:56 Info App config/log directory: /config/Jackett
07-13 14:29:56 Info Using Proxy: No
07-13 14:29:56 Info Using HTTP Client: HttpWebClient2NetCore
07-13 14:29:56 Warn No XML encryptor configured. Key {xxx} may be persisted to storage in unencrypted form.
07-13 14:29:56 Warn No XML encryptor configured. Key {xxx} may be persisted to storage in unencrypted form.
07-13 14:29:56 Error Failed loading configuration for Abnormal, trying backup System.Security.Cryptography.CryptographicException: The key {yyy} was not found in the key ring.

at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
at Jackett.Server.Services.ProtectionService.UnProtect(String plainText) in /home/vsts/work/1/s/src/Jackett.Server/Services/ProtectionService.cs:line 56
at Jackett.Common.Models.IndexerConfig.ConfigurationData.LoadValuesFromJson(JToken json, IProtectionService ps) in /home/vsts/work/1/s/src/Jackett.Common/Models/IndexerConfig/ConfigurationData.cs:line 70
at Jackett.Common.Indexers.BaseIndexer.LoadValuesFromJson(JToken jsonConfig, Boolean useProtectionService) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 130
at Jackett.Common.Indexers.BaseIndexer.LoadFromSavedConfiguration(JToken jsonConfig) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 157
at Jackett.Common.Services.IndexerConfigurationService.Load(IIndexer indexer) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerConfigurationService.cs:line 54

**Comment by ngosang** [comment]
This issue is not caused by Jackett, it's related to Docker.
If you start the Docker container without mapping external volumes, all the files saved by Jackett will be lost after the Docker container is removed, restarted, etc...
You need to configure the external volumes. If you take a look at the documentation => https://github.com/linuxserver/docker-jackett#docker-compose You can see:
```
    volumes:
      - <path to data>:/config
      - <path to blackhole>:/downloads
```
The blackhole path is optional, but you need to create a folder in your server to save the Jackett configuration. For example `/home/my_user/jackett` and execute the Docker container with that path. If you do it well, you will see the files created by Jackett and you can destroy the container when you want, the configuration is in your server, not inside the container.
Do some tests and give us some feedback.
