### ISSUE TITLE
[abnormal] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by thib3113** [Jackett/Jackett#9195]
### Environment

**OS**: Docker (https://hub.docker.com/r/linuxserver/jackett/)

```
Info Starting Jackett v0.16.873.0 
Info Environment version: 3.1.6 (/app/Jackett/) 
Info OS version: Unix 4.15.0.111 (64bit OS) (64bit process) 
Info Jackett variant: CoreLinuxAmdx64 
Info File /etc/issue: Ubuntu 18.04.4 LTS \n \l 
Info Running in Docker: Yes 
Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
Info App config/log directory: /config/Jackett 
Info Using Proxy: No 
Info Using HTTP Client: HttpWebClient2NetCore 
```

**Last Working Jackett Version**: no idea

**Are you using a proxy or VPN?** no

### Description

Try abnormal

### Logged Error Messages

```
{0} System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 278
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by garfield69** [comment]
no one on the team has an account on abnormal, and in addition, its an indexer written in c# which adds further complications, as far as I am concerned.
Perhaps a full **enhanced** log will yield more useful data to work with
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by thib3113** [comment]
Hum, maybe did you have a way to debug it on visual studio ? I can try somethings, but doesn't know how to setup it .

**Comment by thib3113** [comment]
So, I totally clone the project, debug a little ... and in fact, it seems that the config file lost the username and password with one update ... So I set username / password, and it works

**Comment by thib3113** [comment]
@fexofenadine same for you ?

**Comment by fexofenadine** [comment]
Yes mate

**Comment by antoineguilbert** [comment]
> So, I totally clone the project, debug a little ... and in fact, it seems that the config file lost the username and password with one update ... So I set username / password, and it works

Thanks for the tip !
