### ISSUE TITLE
[cpasbien] Exception (cpasbien): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s). (Test)

### ISSUE THREAD

**Issue by FlorentLeroy** [Jackett/Jackett#9232]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Windows10 latest version

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:
4.7
**Jackett Version**:
Jackett Version 0.16.899.0
**Last Working Jackett Version**:
Jackett Version 0.16.899.0
**Are you using a proxy or VPN?** [yes/no]
no
### Description

Ive configured the cpasbien plugin ([screenshot](https://ibb.co/1zsG63g))  with cookies and Agent

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
An error occurred while testing this indexer
Exception (cpasbien): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

[Make sure you attach the full logs with your personal information removed in case we need more information]

{0} Jackett.Common.IndexerException: Exception (cpasbien): Clearance failed after 10 attempt(s).
 ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in d:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.PostDataWithCookies(String url, IEnumerable`1 data, String cookieOverride, String referer, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 509
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1339
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 347
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 347
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 808
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 279
   at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70

**Comment by garfield69** [comment]
Then your only other options are:
- try a VPN to allocate an IP address from another country until you find one where cpasbien does not invoke the anti-DDoS protection
- or try the Jackett **cpasbein clone** indexer instead.

Jackett cannot currently solve the cloudflare anti-DDoS protection challenge so you final last option is to just use your browser to access the web site.

There is work being done on an experimental anti-DDoS bypass with #9029 but this is some time away from being completed and published.
