### ISSUE TITLE
[AvistaZ] Error On attempt 1 downloading from AvistaZ: Clearance failed after 10 attempt(s). 

### ISSUE THREAD

**Issue by garygan89** [Jackett/Jackett#9249]
#8568 # Environment

**OS**: Ubuntu 18.04 LTS

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**: 6.10.0.104

**Jackett Version**: 0.16.909.0

**Last Working Jackett Version**: 0.16.909.0

**Are you using a proxy or VPN?** [yes/no] no

### Description

On Jackett, search for torrent on AvistaZ returns the torrent, but when clicking the Download torrent button the following error occured. Double checked my account info and PID and all is correct.

### Logged Error Messages

```
Jul 29 09:50:33 server663 jackett[17978]: 07-29 03:50:33 Error On attempt 1 downloading from AvistaZ: Clearance failed after 10 attempt(s). CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
Jul 29 09:50:33 server663 jackett[17978]:    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Jul 29 09:50:33 server663 jackett[17978]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Jul 29 09:50:33 server663 jackett[17978]:    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
Jul 29 09:50:33 server663 jackett[17978]:    at Jackett.Common.Utils.Clients.WebClient.GetBytes(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 107
Jul 29 09:50:33 server663 jackett[17978]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookies(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 487
Jul 29 09:50:33 server663 jackett[17978]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookiesAndRetry(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
Jul 29 09:50:35 server663 jackett[17978]: 07-29 03:50:35 Error On attempt 2 downloading from AvistaZ: Clearance failed after 10 attempt(s). CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
Jul 29 09:50:35 server663 jackett[17978]:    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Jul 29 09:50:35 server663 jackett[17978]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Jul 29 09:50:35 server663 jackett[17978]:    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
Jul 29 09:50:35 server663 jackett[17978]:    at Jackett.Common.Utils.Clients.WebClient.GetBytes(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 107
Jul 29 09:50:35 server663 jackett[17978]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookies(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 487
Jul 29 09:50:35 server663 jackett[17978]:    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookiesAndRetry(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
```

### Screenshots

Proof that RSS feed and account info is configured correctly.

![image](https://user-images.githubusercontent.com/2649703/88772904-6c6e2200-d14f-11ea-92ff-508a9be91feb.png)

Clicking the Download icon leads to error above.

**Comment by garfield69** [comment]
if you access the avistaz web site with your browser, and attempt to download a file, do you get a cloudflare recapcha challenge before the download is allowed to start?

**Comment by garygan89** [comment]
Just realized that I actually hit the daily download limit. I was clicking the torrent manually today before switching over to Jackett. Will post back again tomorrow if the same issue occured even after the lift. From the log it does look like cloudflare CAPCHA related.

![image](https://user-images.githubusercontent.com/2649703/88773698-75132800-d150-11ea-8622-1d50de6c2c62.png)

**Comment by garygan89** [comment]
Okay it is confirmed that this issue no longer occur after the ban was lifted. Guess I just have to pay attention to the daily 30 torrents download limit.
