### ISSUE TITLE
Error downloading avistaz  & passthepopcorn

### ISSUE THREAD

**Issue by bearxbeat** [Jackett/Jackett#9257]
Date | Level | Message
-- | -- | --
2020-07-30 09:57:18 | Error | Error downloading avistaz  CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookiesAndRetry(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 426    at Jackett.Common.Indexers.BaseWebIndexer.Download(Uri link, RequestType method, String refererlink) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 389    at Jackett.Common.Indexers.BaseWebIndexer.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 375    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56
2020-07-30 09:57:17 | Error | On attempt 3 downloading from AvistaZ: Clearance failed after 10 attempt(s). CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetBytes(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 102    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookies(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 484    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookiesAndRetry(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
2020-07-30 09:57:10 | Error | On attempt 2 downloading from AvistaZ: Clearance failed after 10 attempt(s). CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetBytes(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 102    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookies(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 484    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookiesAndRetry(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416
2020-07-30 09:57:00 | Error | On attempt 1 downloading from AvistaZ: Clearance failed after 10 attempt(s). CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetBytes(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 102    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookies(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 484    at Jackett.Common.Indexers.BaseWebIndexer.RequestBytesWithCookiesAndRetry(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 416

I am using thr newest version Jackett
I can download manually but from jackett error like this

**Comment by garygan89** [comment]
I used to have the `clearance` error, but it turned out that it was due to the daily 30 torrents download limit. Can you check if you could manually download the torrent from AvistaZ website?

**Comment by bearxbeat** [comment]
> I used to have the `clearance` error, but it turned out that it was due to the daily 30 torrents download limit. Can you check if you could manually download the torrent from AvistaZ website?

Manually is fine.

**Comment by ngosang** [comment]
PassThePopcorn should be fixed => https://github.com/Jackett/Jackett/issues/8927#issuecomment-691698511

**Comment by ngosang** [comment]
AvistaZ  #9433
