### ISSUE TITLE
[torrentdownload] Error while parsing row

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#9273]
term "Cenerentola"

![Capture](https://user-images.githubusercontent.com/1689966/89120174-ca3a9b00-d4bc-11ea-9a18-79db05811071.PNG)

**Comment by ngosang** [comment]
"query": "maisie"
"query": "diet"
"query": "diets"
"query": "kotb"
"query": "golo"
"query": "stranger"
"query": "nipsey"
"query": "tley"
"query": "noom"
```
CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/56b350deb03e8ec2f303cdf08fb5cc464cc0739a/+HardcoreYouth+Maisie--Hardcore-Youth">[HardcoreYouth]<span class="na">Maisie</span>
				Hardcore Youth</a>
			<span class="smallish">
				» Adult / Porn &gt; HD Video</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">320.82 MB</td>
	<td class="tdseed">0</td>
	<td class="tdleech">5</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=AdultPornHDVideo: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/a49dec9f3d71cc609d5b2142ffc85b40a5efd965/Amber-Bex-+amp+-Maisie-play-Strip-Spin-the-Bottle">Amber Bex &amp;amp;
				<span class="na">Maisie</span>
				play Strip Spin the Bottle</a>
			<span class="smallish">
				» Adult / Porn &gt; Video</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">107.11 MB</td>
	<td class="tdseed">1</td>
	<td class="tdleech">1</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=AdultPornVideo: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/4b3d08354ece26b4bb6202e96a446910874a78de/Game-Of-Thrones-Actress-Maisie-Williams-HD-Wallpapers">Game Of Thrones Actress
				<span class="na">Maisie</span>
				Williams HD Wallpapers</a>
			<span class="smallish">
				» Pictures &gt; Wallpapers</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">7.8 MB</td>
	<td class="tdseed">0</td>
	<td class="tdleech">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=PicturesWallpapers: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/2e6d86f6d2f10cdd701782b8ae01d8ee9bae22ee/Maisie-Williams--Jogging-in-London-Pic">
				<span class="na">Maisie</span>
				Williams Jogging in London Pic</a>
			<span class="smallish">
				» Pictures &gt; Pictures - Other</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">32.91 MB</td>
	<td class="tdseed">0</td>
	<td class="tdleech">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=PicturesPicturesOther: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618

CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/876ed40274299b9b6070101252b525b8f1b17a90/MomPov--Maisie-+720p++mp4">MomPov
				<span class="na">Maisie</span>
				[720p].mp4</a>
			<span class="smallish">
				» Adult / Porn &gt; HD Video</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">2.46 GB</td>
	<td class="tdseed">1</td>
	<td class="tdleech">1</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=AdultPornHDVideo: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1618
```

**Comment by ngosang** [comment]
"query": "calories"
System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=BooksEducational: Object reference not set to an instance of an object

"query": "golo"
System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=AnimeEnglishtranslated: Object reference not set to an instance of an object.

"query": "casserole"
System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=OtherComics: Object reference not set to an instance of an object.
System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=TVOther: Object reference not set to an instance of an object.

"query": "they"
System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=Ebooks: Object reference not set to an instance of an object.

**Comment by ngosang** [comment]
query: smollett

```
CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/0f418d928e3fac0956d75b7ba57763309c9c224d/Hot-Singles--R-and-B-Alternative-Country--19+-2017-+iTunes-m4a-Lyrics-Included++Moses+-+-Includes-the-Trumponomy-Diss--F+U+W-by-Jussie-Smollett-+">Hot Singles - R and B--Alternative--Country - 19, 2017-[iTunes m4a-Lyrics Includ..</a>
			<span class="smallish">
				» Music &gt; R&amp;B</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">167.58 MB</td>
	<td class="tdseed">0</td>
	<td class="tdleech">3</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=MusicRB: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1610
```

**Comment by ngosang** [comment]
"query": "settlement"
```
CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/A8DB5B183A9BFC2662CC1EFC83966A0F98A05481/Flixxx-Yasmin-Scott-and-Kai-Taylor-Divorce-Settlement">Flixxx Yasmin Scott and Kai Taylor Divorce
				<span class="na">Settlement</span>
			</a>
			<span class="smallish">
				» XXX &gt; Video</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">358.18 MB</td>
	<td class="tdseed">0</td>
	<td class="tdleech">4</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=XXXVideo: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1610

CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/1EE265113972B34D60B574405B5F2D157D770F40/+DigitalPlayground+-Yasmin-Scott-+Divorce-Settlement++RISHI++mp4">[DigitalPlayground] Yasmin Scott (Divorce
				<span class="na">Settlement</span>)(RISHI).mp4</a>
			<span class="smallish">
				» XXX &gt; Video</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">325.11 MB</td>
	<td class="tdseed">0</td>
	<td class="tdleech">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=XXXVideo: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1610
```

**Comment by ngosang** [comment]
query: rosalia
```
Error CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
        <td class="tdleft">
                <div class="tt-name">
                        <a href="/8818AEAE060DF1B2CB1957D6841922DD7548D123/Old-and-Young-Lesbians--Irina-+46++-Rosalia-+55++-Sheena-++wmv+">Old and Young Lesbians Irina (46),
                                <span class="na">Rosalia</span>
                                (55), Sheena [.wmv]</a>
                        <span class="smallish">
                                » XXX &gt; HD Video</span>
                </div>
                <div class="tt-options"></div>
        </td>
        <td class="tdnormal">1 Year+</td>
        <td class="tdnormal">984.8 MB</td>
        <td class="tdseed">2</td>
        <td class="tdleech">3</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=XXXHDVideo: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1607 
11-02 13:52:12 Error CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
        <td class="tdleft">
                <div class="tt-name">
                        <a href="/84A835D888F7E124A2092B9098BC0CCA3D201FFD/++Old-and-Young-Lesbians-+-Mature+nl+-Irina-+46++-Rosalia-+55++-Sheena-+18+-lesbian-alex415-+2016+-MILF+-Teen+-Old-Young+-Lesbians+-720p+">*[Old-and-Young-Lesbians / Mature.nl] Irina (46),
                                <span class="na">Rosalia</span>
                                (55), Sheena (18) lesb..</a>
                        <span class="smallish">
                                » XXX &gt; HD Video</span>
                </div>
                <div class="tt-options"></div>
        </td>
        <td class="tdnormal">1 Year+</td>
        <td class="tdnormal">984.8 MB</td>
        <td class="tdseed">0</td>
        <td class="tdleech">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=XXXHDVideo: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/kizar/repositories/Jackett/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1607
```

**Comment by ngosang** [comment]
"query": "jordyn"
```
CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/293BD112F262F66CE35984C4E5657D3677796BE9/Plumper-Pass-Photo-Sets-W-E-03-26-2016-Jordyn-Luxxx+-Busty-Emma+-Angel-DeLuca">Plumper Pass Photo Sets W E 03 26 2016
				<span class="na">Jordyn</span>
				Luxxx, Busty Emma, Angel DeLuca</a>
			<span class="smallish">
				» XXX &gt; Pictures</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">860.13 MB</td>
	<td class="tdseed">0</td>
	<td class="tdleech">0</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=XXXPictures: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531

CardigannIndexer (torrentdownload): Error while parsing row '
<tr>
	<td class="tdleft">
		<div class="tt-name">
			<a href="/490186fa6200c1a3b451797c634d171f88d2b6a9/BurningAngel-Hello-Jordyn-58--1920-P">BurningAngel Hello
				<span class="na">Jordyn</span>
				58 1920 P</a>
			<span class="smallish">
				» Adult / Porn &gt; Pictures</span>
		</div>
		<div class="tt-options"></div>
	</td>
	<td class="tdnormal">1 Year+</td>
	<td class="tdnormal">56.36 MB</td>
	<td class="tdseed">1</td>
	<td class="tdleech">1</td>
</tr>':

System.Exception: Error while parsing field=category, selector=div.tt-name > span.smallish, value=AdultPornPictures: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531
```
