### ISSUE TITLE
[nordicbits] Specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by janot** [Jackett/Jackett#9274]
2020-08-02 12:47:33 | Info | Manual search for "cenerentola" on nordicbits with 0 results.
-- | -- | --
2020-08-02 12:47:33 | Error | {0} Jackett.Common.IndexerException: Exception (nordicbits): Specified argument was out of the range of valid values. (Parameter 'index')  ---> System.Exception: Parse error  ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')    at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)    at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)    at Jackett.Common.Indexers.NordicBits.FindTorrentRows(IHtmlDocument dom) in d:\a\1\s\src\Jackett.Common\Indexers\NordicBits.cs:line 704    at Jackett.Common.Indexers.NordicBits.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\NordicBits.cs:line 325    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 831    at Jackett.Common.Indexers.NordicBits.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\NordicBits.cs:line 449    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 347    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 347    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 808    at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 224
2020-08-02 12:47:33 | Error | Error on 20200802124733 for NordicBits.txtSystem.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')    at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)    at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)    at Jackett.Common.Indexers.NordicBits.FindTorrentRows(IHtmlDocument dom) in d:\a\1\s\src\Jackett.Common\Indexers\NordicBits.cs:line 704    at Jackett.Common.Indexers.NordicBits.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\NordicBits.cs:line 325     Error, unable to parse result     at AngleSharp.Common.ObjectExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)    at AngleSharp.Dom.HtmlCollection`1.get_Item(Int32 index)    at Jackett.Common.Indexers.NordicBits.FindTorrentRows(IHtmlDocument dom) in d:\a\1\s\src\Jackett.Common\Indexers\NordicBits.cs:line 704    at Jackett.Common.Indexers.NordicBits.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\NordicBits.cs:line 325

**Comment by garfield69** [comment]
Works for me, I cannot replicate your results.
```
2020-08-03 07:28:21 | Info | No result found for your query, please try another search term or change the theme you're currently using on the site as this is an unsupported solution...
2020-08-03 07:28:21 | Info | Manual search for "cenerentola" on nordicbits with 0 results.
```

Make sure you are on the latest version of Jackett 0.16.938.
I
f you still get the error on the latest version of Jackett 0.16.938 then please provide a **full enhanced** log, with the debug and HTML included. Hopefully that will provide enough data to determine why the indexer failed for you.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by janot** [comment]
Yep, I'm on last version

Full log:
https://pastebin.com/QpGLxTkN

**Comment by garfield69** [comment]
Ah. 
Seems this error occurs when _no results are found_ while using style sheet **V3 Default**.

While we wait for a c# dev to resolve, you can bypass the issue by accessing the web site with your browser and setting your profile style sheet to **DarkV2** which is currently working.

@ngosang, this error occurs when using template1 (V3 Default), template2 (V3 Default Wide), template3 (Dark), template4 (Dark Wide), template5 (Light), template6 (Light Wide), template11 (PurpleV2) and template14 (Xmas).

Currently works for template7 (DarkV2), template8 (DarkV2 Wide), template9 (LightV2) and template10 (LightV2 Wide).

**Comment by garfield69** [comment]
Jackett 0.16.962
