### ISSUE TITLE
[1337x] Exception (1337x): The operation was canceled.: The operation was canceled. (Test)

### ISSUE THREAD

**Issue by whats85** [Jackett/Jackett#9280]
### Environment

**OS**: Raspberry Pi OS 32 bit latest

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: no sure

**Jackett Version**: 0.16.940.0

**Last Working Jackett Version**: not sure

**Are you using a proxy or VPN?**: Yes, Windscribe

### Description

Almost all of my indexers are failing to test. Only 2 are succesfull, Idope and Kickasstorrent. Below example is from 1337x. I'm running Jackett in Docker container. The container runs trough a VPN (Windscribe) container. I can access the website from browser on the same VPN.

### Logged Error Messages

{0} Jackett.Common.IndexerException: Exception (1337x): The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 447
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1341
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 274
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

**Comment by garfield69** [comment]
possible reasons: https://github.com/Jackett/Jackett/wiki/TroubleShooting#a-connection-attempt-failed

either your docker container cannot contact your VPN, or DNS , or the VPN session/account/service is not working, or the IP your VPN has been allocated is being blocked by cloudflare or the various websites as a possible DDoS bot.
you could try to
- Start a terminal and connect to your jackett docker 
`docker exec -it jackett /bin/bash` 
(replace jackett with whatever you called your Jackett container).
- and post the results of
`curl -vvv https://1337x.to/`
and
`openssl s_client -connect 1337x.to:443`

Also see if your VPN can allocate another IP server from a different place in the world than your current one.
For docker DNS issues see https://github.com/Jackett/Jackett/wiki/TroubleShooting#resource-temporarily-unavailable

**Comment by whats85** [comment]
curl -vvv https://1337x.to/:

* Immediate connect fail for 2606:4700:3036::681f:5941: Cannot assign requested address
*   Trying 2606:4700:3035::ac43:8dbc...
This keeps looping.

openssl s_client -connect 1337x.to:443:

CONNECTED(00000003)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, ST = CA, L = San Francisco, O = "CloudFlare, Inc.", CN = CloudFlare Inc ECC CA-2
verify return:1
depth=0 C = US, ST = CA, L = San Francisco, O = "Cloudflare, Inc.", CN = sni.cloudflaressl.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = CA, L = San Francisco, O = "Cloudflare, Inc.", CN = sni.cloudflaressl.com
   i:C = US, ST = CA, L = San Francisco, O = "CloudFlare, Inc.", CN = CloudFlare Inc ECC CA-2
 1 s:C = US, ST = CA, L = San Francisco, O = "CloudFlare, Inc.", CN = CloudFlare Inc ECC CA-2
   i:C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIE3jCCBISgAwIBAgIQCKIPcX0CzZWqT4ukRX5dJDAKBggqhkjOPQQDAjBvMQsw
CQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28x
GTAXBgNVBAoTEENsb3VkRmxhcmUsIEluYy4xIDAeBgNVBAMTF0Nsb3VkRmxhcmUg
SW5jIEVDQyBDQS0yMB4XDTIwMDEyOTAwMDAwMFoXDTIwMTAwOTEyMDAwMFowbTEL
MAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2Nv
MRkwFwYDVQQKExBDbG91ZGZsYXJlLCBJbmMuMR4wHAYDVQQDExVzbmkuY2xvdWRm
bGFyZXNzbC5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARU6oNlGCXifdC4
pZIQT5dMbGQOg24OzXMHYDGKv6hWS7o+IHIIfkWqhK0wUZKcOiv/BuzucwXuXzKB
9kSf2x8/o4IDAjCCAv4wHwYDVR0jBBgwFoAUPnQtH89FdQR+P8Cihz5MQ4NRE8Yw
HQYDVR0OBBYEFOGAsKaEgFn8zGQGbL0+a7eSuvfyMDYGA1UdEQQvMC2CCDEzMzd4
LnRvghVzbmkuY2xvdWRmbGFyZXNzbC5jb22CCiouMTMzN3gudG8wDgYDVR0PAQH/
BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjB5BgNVHR8EcjBw
MDagNKAyhjBodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vQ2xvdWRGbGFyZUluY0VD
Q0NBMi5jcmwwNqA0oDKGMGh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9DbG91ZEZs
YXJlSW5jRUNDQ0EyLmNybDBMBgNVHSAERTBDMDcGCWCGSAGG/WwBATAqMCgGCCsG
AQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMAgGBmeBDAECAjB2
BggrBgEFBQcBAQRqMGgwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0
LmNvbTBABggrBgEFBQcwAoY0aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0Ns
b3VkRmxhcmVJbmNFQ0NDQS0yLmNydDAMBgNVHRMBAf8EAjAAMIIBBAYKKwYBBAHW
eQIEAgSB9QSB8gDwAHUApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN3BAA
AAFv8tUZJAAABAMARjBEAiBbuW1bA/4Sk/NsVAxHZ2plzo5ZeEl27Jkrw7md85Q+
KgIgTgtnp3I3TXpe3+Zp7lk/4uBWleEwb+iNnPFmZhjYjPkAdwBep3P531bA57U2
SH3QSeAyepGaDIShEhKEGHWWgXFFWAAAAW/y1RjEAAAEAwBIMEYCIQDPgmAlsmfw
Yn7420mpGu6FeJ382csbi7oWxEJwu7rVZQIhAMFGJPtcozZCO4jR7IpGYMjCv6Nf
8o2xBf3W0Z/0CXqPMAoGCCqGSM49BAMCA0gAMEUCIF6nl1Dhk0fSo7lVhVBEm7Bs
1vBUl1LG9EClGB5NffNMAiEAuanP/Ef1DWwof3cHlr37A7mtSAIRDdNKhz3NZi2i
kyA=
-----END CERTIFICATE-----
subject=C = US, ST = CA, L = San Francisco, O = "Cloudflare, Inc.", CN = sni.cloudflaressl.com

issuer=C = US, ST = CA, L = San Francisco, O = "CloudFlare, Inc.", CN = CloudFlare Inc ECC CA-2

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2498 bytes and written 380 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 8448E83E829148565AB75EA2F58D12DB78D4C195458E8E7A53BB64776800973D
    Session-ID-ctx: 
    Resumption PSK: 7D9701791E3D2CD75559CCCAFAD6CA4ACB991B126907BDB73DF6F3D16D96F895134FD89DFC894CE351BE9CC6C7A982F0
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - a3 40 63 7b 15 cb 88 b9-18 9b 47 c4 3f 5a 56 d4   .@c{......G.?ZV.
    0010 - cf da 1a e7 ba 22 86 27-a1 ca e7 db c8 0c e1 25   .....".'.......%
    0020 - b7 84 aa d2 13 b5 75 6c-c0 cc 83 f9 96 da ff 6b   ......ul.......k
    0030 - ac 14 8a c1 03 0c d9 1e-d5 80 c5 9e 85 6e 1c fc   .............n..
    0040 - 04 58 5e 5e 4f f1 e2 cf-44 f5 db 1a e1 16 7f 1f   .X^^O...D.......
    0050 - 96 53 14 98 b8 e6 2b 51-98 9d 1e fe 1f c5 f1 98   .S....+Q........
    0060 - f8 eb b5 a3 25 6f 5d 4b-5e 7a 75 11 85 d0 c5 07   ....%o]K^zu.....
    0070 - d8 b4 f2 53 a0 83 7f 13-f2 d9 ab 0d 91 1f b5 9a   ...S............
    0080 - e4 c7 bd 90 da 12 4f 3b-81 d1 10 7c 83 1c 58 e7   ......O;...|..X.
    0090 - 01 1f 9b f0 4e c8 49 0b-6c 8c c4 e6 85 86 ba 05   ....N.I.l.......
    00a0 - c2 20 19 c5 df a7 ac 91-19 3e 34 86 42 f8 e9 29   . .......>4.B..)
    00b0 - e3 fb 8b cf 8c 40 aa b8-cd 0d 6f 94 28 df 76 f1   .....@....o.(.v.

    Start Time: 1596448683
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 0CF17C0249F5B8084A6F7A7D097062F52FA500351DC974407706968FB0409DE7
    Session-ID-ctx: 
    Resumption PSK: 7C2EB0D40E852128EFDA091F996817C16D8DCFAC4D6B1C291217B3ADE29E0531A9A8707B22C9888B71B5D3657F6E1959
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - a3 40 63 7b 15 cb 88 b9-18 9b 47 c4 3f 5a 56 d4   .@c{......G.?ZV.
    0010 - 8f 66 86 0c 3d 94 c6 4f-78 9a c1 c2 79 2c e2 b7   .f..=..Ox...y,..
    0020 - f0 c6 09 bf 02 55 b6 7a-57 02 67 a1 f2 a5 05 d6   .....U.zW.g.....
    0030 - 85 f2 8b f2 a1 4f 3a 75-3c 6b f9 07 90 6f 5b 6c   .....O:u<k...o[l
    0040 - f5 17 79 1a 3b 55 be 7d-9a 56 a8 bf f2 2d 90 17   ..y.;U.}.V...-..
    0050 - 6d e8 dd e8 69 3e 49 f3-f9 dd b6 94 a5 52 6c a7   m...i>I......Rl.
    0060 - c2 3a 54 0c da df c4 3f-18 86 87 35 c8 1d 18 7f   .:T....?...5....
    0070 - d4 7b b9 78 e4 81 60 40-f8 5b 89 b0 7f ed f5 7a   .{.x..`@.[.....z
    0080 - 32 cd 62 4f fb b9 4b 5e-ce bc c0 48 c8 ee 2f d7   2.bO..K^...H../.
    0090 - 1c 56 ce 1f 55 70 df 39-60 da 49 93 35 4b 1c 92   .V..Up.9`.I.5K..
    00a0 - 01 a8 af a0 47 3f 4c c7-01 01 50 62 8e 15 ad 8e   ....G?L...Pb....
    00b0 - 09 c7 91 0e 5d 6d f2 b5-55 53 0d 9f ba 0b b6 af   ....]m..US......

    Start Time: 1596448683
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
closed

**Comment by whats85** [comment]
To add: This all worked fine until a couple of weeks ago. 2 indexers are working perfectly. I have other containers running though that same VPN container without any problems

**Comment by garfield69** [comment]
it looks to me like your jackett docker is trying to use ipv6 instead of ipv4.
see if `curl -4 -vvv https://1337x.to/` works
and if it does then try adding `network_mode: host` to your docker-compose.yml file or add to your docker create `--network host` (info from #7942).

**Comment by garfield69** [comment]
>It is failing on the first IP address but successful on the second IP address?

that is just cloudflare doing its find-a-working-server shuffle
the point is that ipv4 is working, whereas before it was trying both ipv6  2606:4700:3036::681f:5941: and 2606:4700:3035::ac43:8dbc and failing.

so it does look like either your system, router or network provider or docker config has switched to using ipv6, so this is where you need to investigate. This has nothing to do with jackett.

have you tried the network host parm for the docker startup?

**Comment by whats85** [comment]
> > It is failing on the first IP address but successful on the second IP address?
> 
> that is just cloudflare doing its find-a-working-server shuffle
> the point is that ipv4 is working, whereas before it was trying both ipv6 2606:4700:3036::681f:5941: and 2606:4700:3035::ac43:8dbc and failing.
> 
> so it does look like either your system, router or network provider or docker config has switched to using ipv6, so this is where you need to investigate. This has nothing to do with jackett.
> 
> have you tried the network host parm for the docker startup?

Yes, i've have tried network host and the issue is fixed then. Problem is that I don't want to run Jackett without VPN. Are the tests failing because Jackett can't get past Cloudflare?

**Comment by garfield69** [comment]
>Yes, i've have tried network host and the issue is fixed then. Problem is that I don't want to run Jackett without VPN. Are the tests failing because Jackett can't get past Cloudflare?

Huh? why does using ipv4 prevent you from using VPN?

**Comment by whats85** [comment]
> > Yes, i've have tried network host and the issue is fixed then. Problem is that I don't want to run Jackett without VPN. Are the tests failing because Jackett can't get past Cloudflare?
> 
> Huh? why does using ipv4 prevent you from using VPN?

With ipv4 and VPN it still fails to test in Jackett. 

Trying 172.67.141.188...
TCP_NODELAY set
connect to 172.67.141.188 port 443 failed: Connection timed out

I think this causes timeout on Jackett (taking to long to proceed)

**Comment by misanthropos** [comment]
I have issues too now (and it worked before with the same VPN)

[1337x] Found no results while trying to browse this tracker (Test)

**Comment by ngosang** [comment]
I'm pretty sure this is a network problem and not a Jackett issue. In my experience you should disable IPv6 in the host (raspberry pi) and make the changes permanent so you don't lose them after restart => https://itsfoss.com/disable-ipv6-ubuntu-linux/

If you need more help ask in discord, reddit...
