### ISSUE TITLE
[rutracker] Found no results while trying to browse this tracker

### ISSUE THREAD

**Issue by LinFor** [Jackett/Jackett#9282]
### Environment

Docker image from linuxserver/jackett

**Jackett Version**: 0.16.940.0

**Are you using a proxy or VPN?** no

### Description

[rutracker] Found no results while trying to browse this tracker

### Logged Error Messages

An error occurred while updating this indexer
Found no results while trying to browse this tracker

`08-03 14:02:26 Error System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 278
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70 System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 278
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70`

**Comment by Scharrel** [comment]
I also can't login, i also see this in my logs:

rutracker: Error while parsing row '<tr id="trs-tr-5404027" class="tCenter hl-tr">
		<td class="row1 t-ico">
						<img src="https://static.t-ru.org/templates/v1/images/icon_minipost_new.gif" class="icon1" alt="N">
					</td>
		<td class="row1 t-ico" title="не проверено"><span class="tor-icon tor-not-approved">*</span></td>
		<td class="row1 f-name-col">
			<div class="f-name"><a class="gen f ts-text" href="tracker.php?f=2461">Комиксы на русском языке</a></div>
		</td>
		<td class="row4 med tLeft t-title-col">
									<div class="wbr t-title">
																<a data-topic_id="5404027" class="med tLink ts-text hl-tags bold" href="viewtopic.php?t=5404027">[Image] Greg Rucka, Leandro Fernandez / Грег Рукка, Леандро Фернандез - The Old Guard / Старая гвардия [2017-2020, CBR, RUS] (обновлено 03.08.2020)</a>
			</div>
			<div id="tg-5404027" class="t-tags"></div>
		</td>
		<td class="row1 u-name-col">
			<div class="wbr u-name"><a class="med ts-text" href="tracker.php?pid=6428620">NumiTorum</a></div>
		</td>
		<td class="row4 small nowrap tor-size" data-ts_text="449226289">
			<a class="small tr-dl dl-stub" href="dl.php?t=5404027">428.4&nbsp;MB ↓</a>		</td>
		<td class="row4 nowrap" data-ts_text="0">
			<b class="seedmed">0</b>		</td>
		<td class="row4 leechmed bold" title="Личи">0</td>
		<td class="row4 small number-format">3</td>
		<td class="row4 small nowrap" style="padding: 1px 3px 2px;" data-ts_text="1596466576">
						<p>3-Авг-20</p>
			<p>15:56</p>		</td>
	</tr>':

System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.RuTracker.PerformQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/RuTracker.cs:line 1613

**Comment by garfield69** [comment]
the web site has changed their html presentation a little bit. I shall update the indexer shortly.

**Comment by garfield69** [comment]
Jackett 0.16.946

**Comment by LinFor** [comment]
Thank you, great!
