### ISSUE TITLE
Error downloading mejortorrent

### ISSUE THREAD

**Issue by jab3** [Jackett/Jackett#9296]
2020-08-02 23:00:40 | Info | Using HTTP Client: HttpWebClient2NetCore
2020-08-02 23:00:40 | Info | Using Proxy: No
2020-08-02 23:00:40 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2020-08-02 23:00:40 | Info | Running in Docker: No
2020-08-02 23:00:40 | Info | File /etc/issue: Ubuntu 18.04.4 LTS \n \l
2020-08-02 23:00:40 | Info | Jackett variant: CoreLinuxAmdx64
2020-08-02 23:00:40 | Info | OS version: Unix 5.4.34.1 (64bit OS) (64bit process)
2020-08-02 23:00:40 | Info | Environment version: 3.1.5 (/opt/Jackett/)
2020-08-02 23:00:39 | Info | Starting Jackett v0.16.821.0

Error downloading mejortorrent https://www.mejortorrentt.net/serie-episodio-descargar-torrent-70487-Stargirl-1x12.html System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.MejorTorrent.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 121
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97

Error downloading mejortorrent https://www.mejortorrentt.net/secciones.php?sec=descargas&ap=peliculas_extend&id=22164&titulo=Scooby-4K System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.MejorTorrent.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 121    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97

Error downloading mejortorrent https://www.mejortorrentt.net/secciones.php?sec=descargas&ap=peliculas_extend&id=22160&titulo=Scooby System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.MejorTorrent.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 121    at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97

**Comment by garfield69** [comment]
the site has changed their download links. 
will amend the indexer shortly.

**Comment by garfield69** [comment]
Jackett 0.16.962
