### ISSUE TITLE
[Anthelion] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by just-an-alt** [Jackett/Jackett#9316]
### Environment

**OS**: Armbian Buster

**Jackett Version**: Linuxserver.io docker container

**Are you using a proxy or VPN?** Yes

### Description

When adding Anthelion as an indexer, this error occurs: "Object reference not set to an instance of an object."

### Logged Error Messages
`{0} System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.Anthelion.<>c__DisplayClass11_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anthelion.cs:line 71
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 260
   at Jackett.Common.Indexers.Anthelion.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anthelion.cs:line 68
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26`

### Screenshots

https://i.imgur.com/blz5q2Z.png

**Comment by jzriouel** [comment]
### Environment

**OS**: Debian GNU/Linux 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Microsoft.AspNetCore.App 3.1.6 Microsoft.NETCore.App 3.1.6

**.Net Version**: 3.1.302

**Jackett Version**: 0.16.979.0

**Last Working Jackett Version**: Didn't try before.

**Are you using a proxy or VPN?** [yes/no] No.

### Description

When attempt to add anthelion it gives this error message.
I think it's because of the first time login protection.
After I allowed login by that location by clicking the link on the received email there was no error.

### Logged Error Messages
```
2020-08-11 01:25:53 | Info | Request finished in 258.3817ms 500 application/json
-- | -- | --
2020-08-11 01:25:53 | Debug | Connection id "{ConnectionId}" completed keep alive response.
2020-08-11 01:25:53 | Debug | The response will be compressed with '{provider}'.
2020-08-11 01:25:53 | Error | {0} System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.Anthelion.<>c__DisplayClass11_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anthelion.cs:line 71    at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 260    at Jackett.Common.Indexers.Anthelion.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anthelion.cs:line 75    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 110    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
2020-08-11 01:25:53 | Info | Executed endpoint '{EndpointName}'
2020-08-11 01:25:53 | Info | Executed action {ActionName} in {ElapsedMilliseconds}ms
2020-08-11 01:25:53 | Debug | WebClient(HttpWebClient2NetCore): Returning OK => <!DOCTYPE html> <html> <head>   <title>Authorize Location :: Anthelion</title>   <meta http-equiv="X-UA-Compatible" content="IE=edge">   <meta name="viewport" content="width=device-width, initial-scale=1.0">   <meta name="theme-color" content="#461640">   <link rel="shortcut icon" href="favicon.ico?v=b13baf67ea965581f2303dc30af9ab95">   <link rel="manifest" href="/manifest.php">   <link href="/static/styles/public/style.css?v=1528310228" rel="stylesheet" type="text/css">     <script src="/static/functions/jquery.js?v=1528310228" type="text/javascript" integrity="sha256-7BTiYXHj2YXAub1ScOAG5pxUEpsn9MtRXv7vtQuX3sI="></script>     <script src="/static/functions/global.js?v=1539213294" type="text/javascript" integrity="sha256-/1dz5UWHE2n9F/muyiFsWZ3BmZDKofnkDeeU0g557pU="></script>     <script src="/static/functions/ajax.class.js?v=1528310228" type="text/javascript" integrity="sha256-7a87RXa8N+LwKcD8TWIc/mzns3AzXxr+6Fz0M4qLL4s="></script>     <script src="/static/functions/cookie.class.js?v=1528310228" type="text/javascript" integrity="sha256-pfrRltERKbnRtufZRxwVbzg5PiyGaTXWD61Zj1XbOFY="></script>     <script src="/static/functions/storage.class.js?v=1528310228" type="text/javascript" integrity="sha256-bNphAabdI40xhaazg5hKXcXp1y2CBznK1nqHgcWUJZI="></script>     <script src="/static/functions/public.js?v=1528310228" type="text/javascript" integrity="sha256-9WWFBmREziMfMYipGgHHAkycQpZdp8U9wK1YxjifuyY="></script>     <script src="/static/functions/u2f.js?v=1528310228" type="text/javascript" integrity="sha256-K/NkhcjHafmX2zjMKLJbwS1qek7QBcmm5LxeN2vr3U8="></script> </head> <body> <div id="head"><span> <a href="login.php">Log in</a> </span></div> <div id="content">   <table class="layout" id="maincontent">     <tr>       <td class="centered">         <a href="index.php"><div id="logo"></div></a>  This appears to be the first time you've logged in from this location.<br><br>  As a security measure to ensure that you are really the owner of this account,<br> an email has been sent to the address in your profile settings. Please<br> click the link contained in that email to allow access from<br> your location, and then log in again.        </td>     </tr>   </table> </div> <div id="foot">   <span><a href="#">Anthelion</a> \| <a href="#">Project Gazelle</a></span> </div> </body> </html>
2020-08-11 01:25:53 | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://anthelion.me/login.php)
```

### Screenshots

Same screenshot.

**Comment by garfield69** [comment]
@just-an-alt  this indexer is working for me which suggest the problem is at your end.
please provide a **full enhanced** log with debug and HTML so we can see what the site is sending you.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by just-an-alt** [comment]
I can confirm @jzriouel 's observation. This issue is caused by a login from a new location.
However, implementing a more helpful error message would be definitely useful.

**Comment by garfield69** [comment]
the error msg comes from the search routine's failure to get a row of results it was expecting. We cant just make up an error message as we do not know at the time the reason why the results were not returned.
