### ISSUE TITLE
Cannot get Radarr to work with Jackett

### ISSUE THREAD

**Issue by ahmetsamsa** [Jackett/Jackett#9321]
I do as guide say and then I get this error. I'm using Windows 10

> Adding a Jackett indexer in Sonarr or Radarr
> Go to Settings > Indexers > Add > Torznab > Custom.
> Click on the indexers corresponding  button and paste it into the Sonarr/Radarr URL field.
> For the API key use xxxx.
> Configure the correct category IDs via the (Anime) Categories options. See the Jackett indexer configuration for a list of supported categories.

`{0} System.Exception: Unknown indexer: YOURINDEXER
   at Jackett.Common.Services.IndexerManagerService.GetIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 245
   at Jackett.Server.Controllers.RequiresConfiguredIndexer.OnActionExecuting(ActionExecutingContext context) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 82
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70`

**Comment by garfield69** [comment]
what is the name of the Jackett indexer you are trying to add to Radarr?

**Comment by ahmetsamsa** [comment]
> what is the name of the Jackett indexer you are trying to add to Radarr?
EZTV and Kickass torrent
![image](https://user-images.githubusercontent.com/36507696/89868071-df00e800-dbba-11ea-8890-d979c4b668cc.png)

**Comment by garfield69** [comment]
eztv only has **TV** category 5000 so its not suitable for the movie app Radarr  as the Jackett indexer does not support the **movie-search** call, only the tv-search call.

to add kickasstorrent
- click on the **Copy Torznab feed** button to load your paste buffer
![image](https://user-images.githubusercontent.com/6933240/89878292-71ce7080-dc15-11ea-8b52-0b42588acada.png)
- access the Sonarr app and go to settings/indexer click on the **plus** button
![image](https://user-images.githubusercontent.com/6933240/89878493-b9ed9300-dc15-11ea-9ce3-4fc662c1b511.png)
- click on the **torznab custom** button
![image](https://user-images.githubusercontent.com/6933240/89878645-e9040480-dc15-11ea-82e1-ad8885aea045.png)
- **click** in the URL box and **Ctrl-V** to paste your tornab feed string
![image](https://user-images.githubusercontent.com/6933240/89879999-cf63bc80-dc17-11ea-9836-e9bb12328a41.png)
- fill in the name
- replace the default categories list with `5000,2000,2020,2030,2040,2050,2060,2070` 
(the kat website's latest torrents page is usually full of TV stuff, so to pass the Radarr indexer test add cat 5000 
- back to the Jackett dashboard, **double click** the API Key string at the top to select it, and **Ctrl-C** to copy to your paste buffer
- then in the Radarr indexer **click** in the API Key box and **Ctrl-V** to paste the key there
- click **save** and your ready to rock.

**Comment by ahmetsamsa** [comment]
> 
> * click **save** and your ready to rock.
![image](https://user-images.githubusercontent.com/36507696/89976809-301fe300-dc72-11ea-9c07-1c9d10bda4f0.png)

I don't have these option in radar. I think you are using one of test releases? However I applied same setting to Sonarr it worked but it didn't worked for Radarr.

This the error log 
`

2020-08-12 08:07:24 | Info | Found 0 (0 new) releases from KickAssTorrent
-- | -- | --
2020-08-12 08:06:56 | Info | Found 0 (0 new) releases from KickAssTorrent
2020-08-12 08:06:51 | Info | Found 0 (0 new) releases from KickAssTorrent
2020-08-12 08:06:45 | Info | Found 0 (0 new) releases from KickAssTorrent

`

And here is my Jacket setting.
![image](https://user-images.githubusercontent.com/36507696/89977129-0d41fe80-dc73-11ea-9eb7-136ee524ee21.png)

**Comment by garfield69** [comment]
no problem. on RadarrV2 on the main settings > indexers page, slide the **Advanced Settings** switch to **show** 
and when you edit your indexer you will see the categories box
![image](https://user-images.githubusercontent.com/6933240/89978956-bc59f680-dcc2-11ea-9d7d-77984d075bcd.png)

**Comment by ahmetsamsa** [comment]
> no problem. on RadarrV2 on the main settings > indexers page, slide the **Advanced Settings** switch to **show**
> and when you edit your indexer you will see the categories box
> ![image](https://user-images.githubusercontent.com/6933240/89978956-bc59f680-dcc2-11ea-9d7d-77984d075bcd.png)

Thank you very much, it worked. Now I can add indexes to Radarr.
