### ISSUE TITLE
[nyaasi] Found no results while trying to browse this tracker (Test)

### ISSUE THREAD

**Issue by moonship98** [Jackett/Jackett#9323]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:
Debian 
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
Version 0.16.979.0
**Last Working Jackett Version**:
Version 0.16.979.0
**Are you using a proxy or VPN?** [yes/no]
NO
### Description

Tried to add nyaa.si and test it being shown not working

### Logged Error Messages
{0} System.Exception: Found no results while trying to browse this tracker
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 279
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

**Comment by garfield69** [comment]
The indexer is working for me which suggest the problem is at you end.
please provide a **full enhanced** log with debug and HTML so we can see that the site is sending you.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by moonship98** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5067727/log.txt)

**Comment by moonship98** [comment]
hello
 I have attached the enhanced log txt please go through and let me know what has happened

**Comment by garfield69** [comment]
sorry but the log you loaded is the standard log without the debug and html.
set the switch, click the apply-server-settings button, and do NOT restart jackett otherwise the switch will be reset.
then do a search on nyaasi and check the log.
if should have messages with the word DEBUG instead of INFO if you did it right ;-)

**Comment by moonship98** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5068487/log.txt)
I think I did it right now,
please check and let me know 
thank you

**Comment by garfield69** [comment]
Strange.
when I use https://nyaa.si/?q=%5Bhorriblesubs%5D&f=0&c=1_2&s=id&o=desc
i get
![image](https://user-images.githubusercontent.com/6933240/90175940-52456c80-ddfc-11ea-8970-c31b1ed3e30d.png)
but your log shows
```html
2020-08-13 12:03:31.5190 Debug WebClient(HttpWebClient2NetCore): Returning PaymentRequired => <html>
<head><title>402 Payment Required</title></head>
<body bgcolor="white">
<center><h1>402 Payment Required</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
```
do you get this when using your browser to access https://nyaa.si/?q=%5Bhorriblesubs%5D&f=0&c=1_2&s=id&o=desc ?

**Comment by moonship98** [comment]
im from india 
over the site is banned if i use vpn i can access it
 but that wouldn't affect  Jackett(i guess) because jackett is installed in a seedbox and it is in germany

**Comment by garfield69** [comment]
clearly the site is blocking your IP so that is what you need to focus on.
try another world server on your VPN or a different VPN to get an IP that works for you.
regardless, this is nota issue with Jackett.
Good luck.
