### ISSUE TITLE
Error after updating - 

### ISSUE THREAD

**Issue by magictoaster420** [Jackett/Jackett#9327]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:  Debian Stretch

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]   Mono

**.Net Version**:   Mono JIT compiler version 6.10.0.104 

**Jackett Version**:  Jackett v0.16.979.0

**Last Working Jackett Version**:  I forget... 0.16.515 rings a bell?

**Are you using a proxy or VPN?** [yes/no]  No

### Description

I attempted to update Jacket via the button in the web interface and it never came back up.  Syslog messages are below.

### Logged Error Messages

(from tailing /var/log/syslog)

Aug 11 19:21:53 tomb jackett[18677]: 08-11 19:21:53 Info Starting Jackett v0.16.979.0
Aug 11 19:21:53 tomb jackett[18677]: Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Linq.Expressions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module  expected to contain an assembly manifest.
Aug 11 19:21:53 tomb jackett[18677]: File name: 'System.Linq.Expressions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Aug 11 19:21:53 tomb jackett[18677]:    at Jackett.Common.Services.ConfigurationService.BuildServerConfig(RuntimeSettings runtimeSettings)
Aug 11 19:21:53 tomb jackett[18677]:    at Jackett.Server.Program.Main(String[] args) in /home/vsts/work/1/s/src/Jackett.Server/Program.cs:line 119
Aug 11 19:21:53 tomb systemd[1]: jackett.service: Main process exited, code=killed, status=6/ABRT
Aug 11 19:21:53 tomb systemd[1]: jackett.service: Unit entered failed state.
Aug 11 19:21:53 tomb systemd[1]: jackett.service: Failed with result 'signal'.
Aug 11 19:21:59 tomb systemd[1]: jackett.service: Service hold-off time over, scheduling restart.
Aug 11 19:21:59 tomb systemd[1]: Stopped Jackett Daemon.

### Screenshots

N/A.

**Comment by garfield69** [comment]
looks like the updater clashed with a still active jackett service/tray/console task and you ended up with a missing module.
shutdown all jackett related services and tasks and grab the latest full install and it should overlay over the top of the old/missing files and get you going again.
