### ISSUE TITLE
[rutracker] Found no results while trying to browse this tracker (Config)

### ISSUE THREAD

**Issue by bepcyc** [Jackett/Jackett#9336]
### Environment

**OS**: Debian GNU/Linux 9.12 (stretch)

**.Net Version**: No idea, it runs in a docker I can't access (ultraseedbox platform)

**Jackett Version**:  **0.16.815.0**

**Last Working Jackett Version**: No idea, it worked several weeks ago.

**Are you using a proxy or VPN?** yes and no, tried both

### Description

1) Configure Rutracker indexer with all defaults and my username and password
2) Press "Close" button.
3) Press "Test" button on a tracker.
4) Receive pop-up error message (see below in logged messages)
5) Go to the logs tab and see the parsing error messages (see below in logged messages)

### Logged Error Messages
1) Pop-up window when pressing "Test" on the indexer (previously worked well):
```
An error occurred while updating this indexer
Found no results while trying to browse this tracker
Click here to open an issue on GitHub for this indexer.
```
2) Error Log at the same time:
```

2020-08-14 09:58:25 | Error | {0} System.Exception: Found no results while trying to browse this tracker    at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 278    at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
-- | -- | --
2020-08-14 09:58:25 | Info | Executed endpoint '{EndpointName}'
2020-08-14 09:58:25 | Info | Executed action {ActionName} in {ElapsedMilliseconds}ms
2020-08-14 09:58:25 | Info | Found 0 releases from RuTracker
2020-08-14 09:58:25 | Error | rutracker: Error while parsing row '<tr id="trs-tr-5929997" class="tCenter hl-tr"> 		<td class="row1 t-ico"> 						<img src="https://static.t-ru.org/templates/v1/images/icon_minipost_new.gif" class="icon1" alt="N"> 					</td> 		<td class="row1 t-ico" title="не проверено"><span class="tor-icon tor-not-approved">*</span></td> 		<td class="row1 f-name-col"> 			<div class="f-name"><a class="gen f ts-text" href="tracker.php?f=259">НХЛ (с 2013)</a></div> 		</td> 		<td class="row4 med tLeft t-title-col"> 									<div class="wbr t-title"> 												<span class="ttp-label ttp-hot">горячая</span>				<a data-topic_id="5929997" class="med tLink ts-text hl-tags bold" href="viewtopic.php?t=5929997">NHL 19/20, SC, WC: Round 1, Game 2. Calgary Flames - Dallas Stars [13.08.2020, Хоккей, WEB-DL HD/720p/60fps, MKV/H.264, EN, SN]</a> 			</div> 			<div id="tg-5929997" class="t-tags"></div> 		</td> 		<td class="row1 u-name-col"> 			<div class="wbr u-name"><a class="med ts-text" href="tracker.php?pid=40772008">hereisit</a></div> 		</td> 		<td class="row4 small nowrap tor-size" data-ts_text="4684545254"> 			<a class="small tr-dl dl-stub" href="dl.php?t=5929997">4.36&nbsp;GB ↓</a>		</td> 		<td class="row4 nowrap" data-ts_text="22"> 			<b class="seedmed">22</b>		</td> 		<td class="row4 leechmed bold" title="Личи">29</td> 		<td class="row4 small number-format">74</td> 		<td class="row4 small nowrap" style="padding: 1px 3px 2px;" data-ts_text="1597383934"> 						<p>14-Авг-20</p> 			<p>08:45</p>		</td> 	</tr>':  System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.RuTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RuTracker.cs:line 1613
2020-08-14 09:58:25 | Error | rutracker: Error while parsing row '<tr id="trs-tr-5927025" class="tCenter hl-tr"> 		<td class="row1 t-ico"> 						<img src="https://static.t-ru.org/templates/v1/images/icon_minipost_new.gif" class="icon1" alt="N"> 					</td> 		<td class="row1 t-ico" title="не проверено"><span class="tor-icon tor-not-approved">*</span></td> 		<td class="row1 f-name-col"> 			<div class="f-name"><a class="gen f ts-text" href="tracker.php?f=257">Смешанные единоборства и K-1</a></div> 		</td> 		<td class="row4 med tLeft t-title-col"> 									<div class="wbr t-title"> 																<a data-topic_id="5927025" class="med tLink ts-text hl-tags bold" href="viewtopic.php?t=5927025">UFC Dana White's Contender Series season 4 [2020, MMA, HDTVRip 1080p, ENG]</a> 			</div> 			<div id="tg-5927025" class="t-tags"></div> 		</td> 		<td class="row1 u-name-col"> 			<div class="wbr u-name"><a class="med ts-text" href="tracker.php?pid=14818706">dean10</a></div> 		</td> 		<td class="row4 small nowrap tor-size" data-ts_text="16129943568"> 			<a class="small tr-dl dl-stub" href="dl.php?t=5927025">15.02&nbsp;GB ↓</a>		</td> 		<td class="row4 nowrap" data-ts_text="0"> 			<b class="seedmed">0</b>		</td> 		<td class="row4 leechmed bold" title="Личи">1</td> 		<td class="row4 small number-format">4</td> 		<td class="row4 small nowrap" style="padding: 1px 3px 2px;" data-ts_text="1597384001"> 						<p>14-Авг-20</p> 			<p>08:46</p>		</td> 	</tr>':  System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.RuTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RuTracker.cs:line 1613
2020-08-14 09:58:25 | Error | rutracker: Error while parsing row '<tr id="trs-tr-5929998" class="tCenter hl-tr"> 		<td class="row1 t-ico"> 						<img src="https://static.t-ru.org/templates/v1/images/icon_minipost_new.gif" class="icon1" alt="N"> 					</td> 		<td class="row1 t-ico" title="не проверено"><span class="tor-icon tor-not-approved">*</span></td> 		<td class="row1 f-name-col"> 			<div class="f-name"><a class="gen f ts-text" href="tracker.php?f=2302">Джаз и Блюз (Hi-Res stereo)</a></div> 		</td> 		<td class="row4 med tLeft t-title-col"> 									<div class="wbr t-title"> 																<a data-topic_id="5929998" class="med tLink ts-text hl-tags bold" href="viewtopic.php?t=5929998">[TR24][OF] Ada Morghe - Box - 2020 (Jazz, Vocal Jazz)</a> 			</div> 			<div id="tg-5929998" class="t-tags"></div> 		</td> 		<td class="row1 u-name-col"> 			<div class="wbr u-name"><a class="med ts-text" href="tracker.php?pid=22279982">Stephenten</a></div> 		</td> 		<td class="row4 small nowrap tor-size" data-ts_text="504295609"> 			<a class="small tr-dl dl-stub" href="dl.php?t=5929998">480.9&nbsp;MB ↓</a>		</td> 		<td class="row4 nowrap" data-ts_text="11"> 			<b class="seedmed">11</b>		</td> 		<td class="row4 leechmed bold" title="Личи">8</td> 		<td class="row4 small number-format">35</td> 		<td class="row4 small nowrap" style="padding: 1px 3px 2px;" data-ts_text="1597384438"> 						<p>14-Авг-20</p> 			<p>08:53</p>		</td> 	</tr>':  System.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.RuTracker.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RuTracker.cs:line 1613


.... a lot of messages like this
```

**Comment by bepcyc** [comment]
I can try making a rutracker user for you if needed.
I've reviewed other tickets with rutracker in their name, but they all have no usable information. I think this one should stay opened.
I also may later take a look at the code even though I'm not a .Net developer. The code seems to be trivial.

**Comment by garfield69** [comment]
The rutracker indexer works for me.
when you change the config for the indexer **DO NOT** press _close_, but press **OKAY**.

**Comment by bepcyc** [comment]
Pressing **Okay*** is giving me the same error as pressing **Test**. It also does not allow me to close and save the config of course.
In my opinion, the error in a log is pretty descriptive and errors like these will not happen due to pressing the wrong button. It's a clear parsing issue. I took a brief look at the code and it's failing [here](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/RuTracker.cs#L1613):
```
var qSize = row.QuerySelector("td.tor-size");
```
This area of the code was not touched recently, but maybe something around it was changed. I'll try to reproduce locally if I'll be able to setup the environment on Ubuntu (unfortunately current instructions are very outdated and work only on Debian).

**Comment by bepcyc** [comment]
Just so you know. This is not a new config. I'm using this config for several months now and it was working fine. Recently I've noticed that there are not results from rutracker anymore, so I went to jackett and found this problem.

**Comment by garfield69** [comment]
I just noticed you are on 0.16.815
you need to upgrade to at least v0.16.946 which has 16f88039982847816812d58e22fd42fc1eb42347
current latest version is v0.16.991

**Comment by bepcyc** [comment]
Ok, my seedbox allowed me to upgrade to **0.16.987.0** and all works fine there.
Thank you for your quick response!
