### ISSUE TITLE
[mejortorrent] Clearance failed after 10 attempt(s). (Config)

### ISSUE THREAD

**Issue by nirox** [Jackett/Jackett#9339]
### Environment

**OS**: raspbian

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:0.16.991.0

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** no

### Description

Add mejorTorrent indexer to list

### Logged Error Messages

2020-08-14T11:04:15.323785958Z 08-14 13:04:15 Error CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).

2020-08-14T11:04:15.323866957Z    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

2020-08-14T11:04:15.323974511Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

2020-08-14T11:04:15.324116824Z    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229

2020-08-14T11:04:15.324259841Z    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164

2020-08-14T11:04:15.324401321Z    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 447

2020-08-14T11:04:15.324534541Z    at Jackett.Common.Indexers.MejorTorrent.PerformQueryNewest(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 126

2020-08-14T11:04:15.324666688Z    at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 91

2020-08-14T11:04:15.324810686Z    at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 75

2020-08-14T11:04:15.324944999Z    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94

2020-08-14T11:04:15.325086461Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

2020-08-14T11:04:15.325205626Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

2020-08-14T11:04:15.325351087Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

2020-08-14T11:04:15.325483123Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

2020-08-14T11:04:15.325671546Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

2020-08-14T11:04:15.325757638Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

2020-08-14T11:04:15.325861859Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

2020-08-14T11:04:15.326029875Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

2020-08-14T11:04:15.326173503Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

2020-08-14T11:04:15.326318705Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

2020-08-14T11:04:15.326487666Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70 CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).

2020-08-14T11:04:15.326654349Z    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

2020-08-14T11:04:15.326811236Z    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

2020-08-14T11:04:15.326885328Z    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229

2020-08-14T11:04:15.327014086Z    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164

2020-08-14T11:04:15.327187195Z    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 447

2020-08-14T11:04:15.327256157Z    at Jackett.Common.Indexers.MejorTorrent.PerformQueryNewest(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 126

2020-08-14T11:04:15.327389637Z    at Jackett.Common.Indexers.MejorTorrent.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 91

2020-08-14T11:04:15.327566246Z    at Jackett.Common.Indexers.MejorTorrent.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MejorTorrent.cs:line 75

2020-08-14T11:04:15.327643634Z    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94

2020-08-14T11:04:15.327777817Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

2020-08-14T11:04:15.327920575Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

2020-08-14T11:04:15.328061425Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

2020-08-14T11:04:15.328207331Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

2020-08-14T11:04:15.328344977Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

2020-08-14T11:04:15.328484198Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

2020-08-14T11:04:15.328607085Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

2020-08-14T11:04:15.328745102Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

2020-08-14T11:04:15.328889582Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

2020-08-14T11:04:15.329017358Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

2020-08-14T11:04:15.329190634Z    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

**Comment by capriaps** [comment]
I am also having the same issue on 0.16.991.0. I am using a VPN. FreeBSD 12.1 with mono.

**Comment by garfield69** [comment]
if you are seeing `Clearance failed after 10 attempt(s).` then this means that the IP address you are using is being challenged by clouldflare as a possible DDoS bot.
Jackett cannot solve this challenge.
use a VPN to allocate a different IP from another region of the world until you get one that is not challenged.
the mejortorrent indexer works for me so we know the indexer works.
