### ISSUE TITLE
[Scenetime] Can't open open settings window

### ISSUE THREAD

**Issue by ethanopp** [Jackett/Jackett#9352]
# Environment

**OS**: Linux (4.14.24-qnap) LSIO docker

**Jackett Version**: Jackett Version 0.16.1002.0

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
1. Click 'Add Indexer'
2. Select 'Scenetime'

A popup normally shows where I can enter the config for scenetime, however just getting:
<img width="551" alt="Screen Shot 2020-08-16 at 10 10 22 AM" src="https://user-images.githubusercontent.com/11603814/90336441-ee60a680-dfa9-11ea-86e7-34c922812132.png">

### Logged Error Messages

```{0} CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 447
   at Jackett.Common.Indexers.SceneTime.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 107
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

### Full Enhanced Log

Date | Level | Message
-- | -- | --
2020-08-16 10:27:09 | Debug | Executed controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:27:09 | Debug | Executing controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:27:09 | Info | Authorization was successful.
2020-08-16 10:27:09 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:09 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:09 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:09 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:09 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:09 | Info | Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).
2020-08-16 10:27:09 | Info | Executing endpoint '{EndpointName}'
2020-08-16 10:27:09 | Debug | Request matched endpoint '{EndpointName}'
2020-08-16 10:27:09 | Debug | Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}'
2020-08-16 10:27:09 | Debug | {CandidateCount} candidate(s) found for the request path '{Path}'
2020-08-16 10:27:09 | Debug | AuthenticationScheme: {AuthenticationScheme} was successfully authenticated.
2020-08-16 10:27:09 | Debug | The request path {Path} does not match a supported file type
2020-08-16 10:27:09 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:27:09 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:27:09 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:27:09 | Info | Request starting HTTP/1.1 GET http://192.168.1.11:9117/api/v2.0/server/logs?_=1597588017661
2020-08-16 10:27:07 | Info | Request finished in 2545.0009ms 500 application/json
2020-08-16 10:27:07 | Debug | Connection id "{ConnectionId}" completed keep alive response.
2020-08-16 10:27:07 | Debug | The response will be compressed with '{provider}'.
2020-08-16 10:27:07 | Error | {0} CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 447    at Jackett.Common.Indexers.SceneTime.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 107    at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
2020-08-16 10:27:07 | Info | Executed endpoint '{EndpointName}'
2020-08-16 10:27:07 | Info | Executed action {ActionName} in {ElapsedMilliseconds}ms
2020-08-16 10:27:04 | Debug | WebClient(HttpWebClient2NetCore).GetString(Url:https://www.scenetime.com/login.php)
2020-08-16 10:27:04 | Debug | Executed controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:27:04 | Debug | Executing controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:27:04 | Info | Authorization was successful.
2020-08-16 10:27:04 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:04 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:04 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:04 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:04 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:27:04 | Info | Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).
2020-08-16 10:27:04 | Info | Executing endpoint '{EndpointName}'
2020-08-16 10:27:04 | Debug | Request matched endpoint '{EndpointName}'
2020-08-16 10:27:04 | Debug | Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}'
2020-08-16 10:27:04 | Debug | {CandidateCount} candidate(s) found for the request path '{Path}'
2020-08-16 10:27:04 | Debug | AuthenticationScheme: {AuthenticationScheme} was successfully authenticated.
2020-08-16 10:27:04 | Debug | The request path {Path} does not match a supported file type
2020-08-16 10:27:04 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:27:04 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:27:04 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:27:04 | Info | Request starting HTTP/1.1 GET http://192.168.1.11:9117/api/v2.0/indexers/scenetime/config?_=1597588017660
2020-08-16 10:26:57 | Info | Request finished in 107.4016ms 200 application/json; charset=utf-8
2020-08-16 10:26:57 | Debug | Connection id "{ConnectionId}" completed keep alive response.
2020-08-16 10:26:57 | Info | Executed endpoint '{EndpointName}'
2020-08-16 10:26:57 | Info | Executed action {ActionName} in {ElapsedMilliseconds}ms
2020-08-16 10:26:57 | Debug | The response will be compressed with '{provider}'.
2020-08-16 10:26:57 | Info | Executing ObjectResult, writing value of type '{Type}'.
2020-08-16 10:26:57 | Debug | Selected output formatter '{OutputFormatter}' and content type '{ContentType}' to write the response.
2020-08-16 10:26:57 | Debug | Attempting to select the first formatter in the output formatters list which can write the result.
2020-08-16 10:26:57 | Debug | Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
2020-08-16 10:26:57 | Debug | No information found on request to perform content negotiation.
2020-08-16 10:26:57 | Debug | List of registered output formatters, in the following order: {OutputFormatters}
2020-08-16 10:26:57 | Debug | Done attempting to validate the bound parameter '{ParameterName}' of type '{ModelType}'.
2020-08-16 10:26:57 | Debug | Attempting to validate the bound parameter '{ParameterName}' of type '{ModelType}' ...
2020-08-16 10:26:57 | Debug | Done attempting to bind parameter '{ParameterName}' of type '{ModelType}'.
2020-08-16 10:26:57 | Debug | Done attempting to bind parameter '{ParameterName}' of type '{ModelType}'.
2020-08-16 10:26:57 | Debug | Could not find a value in the request with name '{ModelName}' for binding parameter '{ModelFieldName}' of type '{ModelType}'.
2020-08-16 10:26:57 | Debug | Attempting to bind parameter '{ParameterName}' of type '{ModelType}' ...
2020-08-16 10:26:57 | Debug | Executed controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:57 | Debug | Executing controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:57 | Info | Authorization was successful.
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Info | Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).
2020-08-16 10:26:57 | Info | Executing endpoint '{EndpointName}'
2020-08-16 10:26:57 | Debug | Request matched endpoint '{EndpointName}'
2020-08-16 10:26:57 | Debug | Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}'
2020-08-16 10:26:57 | Debug | {CandidateCount} candidate(s) found for the request path '{Path}'
2020-08-16 10:26:57 | Debug | AuthenticationScheme: {AuthenticationScheme} was successfully authenticated.
2020-08-16 10:26:57 | Debug | The request path {Path} does not match a supported file type
2020-08-16 10:26:57 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:57 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:57 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:57 | Info | Request starting HTTP/1.1 GET http://192.168.1.11:9117/api/v2.0/indexers?_=1597588017659
2020-08-16 10:26:57 | Info | Request finished in 3.2456ms 200 application/json; charset=utf-8
2020-08-16 10:26:57 | Debug | Connection id "{ConnectionId}" completed keep alive response.
2020-08-16 10:26:57 | Info | Executed endpoint '{EndpointName}'
2020-08-16 10:26:57 | Info | Executed action {ActionName} in {ElapsedMilliseconds}ms
2020-08-16 10:26:57 | Debug | The response will be compressed with '{provider}'.
2020-08-16 10:26:57 | Info | Executing ObjectResult, writing value of type '{Type}'.
2020-08-16 10:26:57 | Debug | Selected output formatter '{OutputFormatter}' and content type '{ContentType}' to write the response.
2020-08-16 10:26:57 | Debug | Attempting to select the first formatter in the output formatters list which can write the result.
2020-08-16 10:26:57 | Debug | Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
2020-08-16 10:26:57 | Debug | No information found on request to perform content negotiation.
2020-08-16 10:26:57 | Debug | List of registered output formatters, in the following order: {OutputFormatters}
2020-08-16 10:26:57 | Debug | Executed controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:57 | Debug | Executing controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:57 | Info | Authorization was successful.
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:57 | Info | Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).
2020-08-16 10:26:57 | Info | Executing endpoint '{EndpointName}'
2020-08-16 10:26:57 | Debug | Request matched endpoint '{EndpointName}'
2020-08-16 10:26:57 | Debug | Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}'
2020-08-16 10:26:57 | Debug | {CandidateCount} candidate(s) found for the request path '{Path}'
2020-08-16 10:26:57 | Debug | AuthenticationScheme: {AuthenticationScheme} was successfully authenticated.
2020-08-16 10:26:57 | Debug | The request path {Path} does not match a supported file type
2020-08-16 10:26:57 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:57 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:57 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:57 | Info | Request starting HTTP/1.1 GET http://192.168.1.11:9117/api/v2.0/server/config?_=1597588017658
2020-08-16 10:26:56 | Info | Request finished in 4.0293ms 200 text/html
2020-08-16 10:26:56 | Debug | Connection id "{ConnectionId}" completed keep alive response.
2020-08-16 10:26:56 | Info | Executed endpoint '{EndpointName}'
2020-08-16 10:26:56 | Info | Executed action {ActionName} in {ElapsedMilliseconds}ms
2020-08-16 10:26:56 | Debug | The response will be compressed with '{provider}'.
2020-08-16 10:26:56 | Debug | The file result has not been enabled for processing range requests. To enable it, set the property 'EnableRangeProcessing' on the result to 'true'.
2020-08-16 10:26:56 | Info | Executing {FileResultType}, sending file '{FileDownloadPath}' with download name '{FileDownloadName}' ...
2020-08-16 10:26:56 | Debug | Executed controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:56 | Debug | Executing controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:56 | Info | Authorization was successful.
2020-08-16 10:26:56 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:56 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:56 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:56 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:56 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:56 | Info | Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).
2020-08-16 10:26:56 | Info | Executing endpoint '{EndpointName}'
2020-08-16 10:26:56 | Debug | Request matched endpoint '{EndpointName}'
2020-08-16 10:26:56 | Debug | Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}'
2020-08-16 10:26:56 | Debug | {CandidateCount} candidate(s) found for the request path '{Path}'
2020-08-16 10:26:56 | Debug | AuthenticationScheme: {AuthenticationScheme} was successfully authenticated.
2020-08-16 10:26:56 | Debug | The request path {Path} does not match a supported file type
2020-08-16 10:26:56 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:56 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:56 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:56 | Info | Request starting HTTP/1.1 GET http://192.168.1.11:9117/UI/Dashboard
2020-08-16 10:26:44 | Info | Request finished in 111.6155ms 200 application/json; charset=utf-8
2020-08-16 10:26:44 | Debug | Connection id "{ConnectionId}" completed keep alive response.
2020-08-16 10:26:44 | Info | Executed endpoint '{EndpointName}'
2020-08-16 10:26:44 | Info | Executed action {ActionName} in {ElapsedMilliseconds}ms
2020-08-16 10:26:44 | Debug | The response will be compressed with '{provider}'.
2020-08-16 10:26:44 | Info | Executing ObjectResult, writing value of type '{Type}'.
2020-08-16 10:26:44 | Debug | Selected output formatter '{OutputFormatter}' and content type '{ContentType}' to write the response.
2020-08-16 10:26:44 | Debug | Attempting to select the first formatter in the output formatters list which can write the result.
2020-08-16 10:26:44 | Debug | Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
2020-08-16 10:26:44 | Debug | No information found on request to perform content negotiation.
2020-08-16 10:26:44 | Debug | List of registered output formatters, in the following order: {OutputFormatters}
2020-08-16 10:26:44 | Debug | Done attempting to validate the bound parameter '{ParameterName}' of type '{ModelType}'.
2020-08-16 10:26:44 | Debug | Attempting to validate the bound parameter '{ParameterName}' of type '{ModelType}' ...
2020-08-16 10:26:44 | Debug | Done attempting to bind parameter '{ParameterName}' of type '{ModelType}'.
2020-08-16 10:26:44 | Debug | Done attempting to bind parameter '{ParameterName}' of type '{ModelType}'.
2020-08-16 10:26:44 | Debug | Could not find a value in the request with name '{ModelName}' for binding parameter '{ModelFieldName}' of type '{ModelType}'.
2020-08-16 10:26:44 | Debug | Attempting to bind parameter '{ParameterName}' of type '{ModelType}' ...
2020-08-16 10:26:44 | Debug | Executed controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:44 | Debug | Executing controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:44 | Info | Authorization was successful.
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Info | Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).
2020-08-16 10:26:44 | Info | Executing endpoint '{EndpointName}'
2020-08-16 10:26:44 | Debug | Request matched endpoint '{EndpointName}'
2020-08-16 10:26:44 | Debug | Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}'
2020-08-16 10:26:44 | Debug | {CandidateCount} candidate(s) found for the request path '{Path}'
2020-08-16 10:26:44 | Debug | AuthenticationScheme: {AuthenticationScheme} was successfully authenticated.
2020-08-16 10:26:44 | Debug | The request path {Path} does not match a supported file type
2020-08-16 10:26:44 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:44 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:44 | Debug | Request is continuing in applying rules. Current url is {currentUrl}
2020-08-16 10:26:44 | Info | Request starting HTTP/1.1 GET http://192.168.1.11:9117/api/v2.0/indexers?_=1597588004832
2020-08-16 10:26:44 | Info | Request finished in 3.9988ms 200 application/json; charset=utf-8
2020-08-16 10:26:44 | Debug | Connection id "{ConnectionId}" completed keep alive response.
2020-08-16 10:26:44 | Info | Executed endpoint '{EndpointName}'
2020-08-16 10:26:44 | Info | Executed action {ActionName} in {ElapsedMilliseconds}ms
2020-08-16 10:26:44 | Debug | The response will be compressed with '{provider}'.
2020-08-16 10:26:44 | Info | Executing ObjectResult, writing value of type '{Type}'.
2020-08-16 10:26:44 | Debug | Selected output formatter '{OutputFormatter}' and content type '{ContentType}' to write the response.
2020-08-16 10:26:44 | Debug | Attempting to select the first formatter in the output formatters list which can write the result.
2020-08-16 10:26:44 | Debug | Attempting to select an output formatter without using a content type as no explicit content types were specified for the response.
2020-08-16 10:26:44 | Debug | No information found on request to perform content negotiation.
2020-08-16 10:26:44 | Debug | List of registered output formatters, in the following order: {OutputFormatters}
2020-08-16 10:26:44 | Debug | Executed controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:44 | Debug | Executing controller factory for controller {Controller} ({AssemblyName})
2020-08-16 10:26:44 | Info | Authorization was successful.
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Debug | Execution plan of {FilterType} filters (in the following order): {Filters}
2020-08-16 10:26:44 | Info | Route matched with {RouteData}. Executing controller action with signature {MethodInfo} on controller {Controller} ({AssemblyName}).
2020-08-16 10:26:44 | Info | Executing endpoint '{EndpointName}'
2020-08-16 10:26:44 | Debug | Request matched endpoint '{EndpointName}'
2020-08-16 10:26:44 | Debug | Endpoint '{Endpoint}' with route pattern '{RoutePattern}' is valid for the request path '{Path}'
2020-08-16 10:26:44 | Debug | {CandidateCount} candidate(s) found for the request path '{Path}'
2020-08-16 10:26:44 | Debug | AuthenticationScheme: {AuthenticationScheme} was successfully authenticated.
2020-08-16 10:26:44 | Debug | The request path {Path} does not match a supported file type
2020-08-16 10:26:44 | Debug | Request is continuing in applying rules. Current url is {currentUrl}

**Comment by ilike2burnthing** [comment]
Same here, with and without VPN/proxy. Blocked as a result of the Cloudflare's anti-DDoS challenge.

You'll either have to wait for the site to remove/change this, or you can try the FlareSolverr beta - https://github.com/Jackett/Jackett/issues/9029

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/9493#issuecomment-691310885
