### ISSUE TITLE
[1337x] Exception (1337x): Alınan ileti beklenmeyen veya hatalı biçimdeydi.: An error occurred while sending the request. (Test)

### ISSUE THREAD

**Issue by ahmetsamsa** [Jackett/Jackett#9358]
`{0} Jackett.Common.IndexerException: Exception (1337x): Alınan ileti beklenmeyen veya hatalı biçimdeydi.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): Alınan ileti beklenmeyen veya hatalı biçimdeydi.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ReplyOnReAuthentication(Byte[] buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in d:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 447
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1341
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 347
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 347
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 808
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in d:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 274
   at Jackett.Server.Controllers.IndexerApiController.Test() in d:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in d:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70`

I get this error when I click to  "Test" button for 1337x.to
I use Windows 10 with latest updates and build.

**Comment by jessetechno** [comment]
I am getting to same error from all indexers on my Synology.  I think maybe Jackett has been blocked or something?

**Comment by garfield69** [comment]
likely your ISP is blocking your access.
use  a browser on the same machine that is running Jackett and try to access https://1337x.to/
if blocked then access your jackett dashboard, edit the 1337x config and try each of the alternate sitelinks to see if any of these work.
if all fail then consider using a VPN that allocates an IP from a different region than your local.

**Comment by ahmetsamsa** [comment]
> likely your ISP is blocking your access.
> use a browser on the same machine that is running Jackett and try to access https://1337x.to/
> if blocked then access your jackett dashboard, edit the 1337x config and try each of the alternate sitelinks to see if any of these work.
> if all fail then consider using a VPN that allocates an IP from a different region than your local.

My ISP doesn't block 1337x.to. I tried with VPN too, it still give same error.

**Comment by garfield69** [comment]
the indexer works for me on my win10home, so the issue is definitely local to your set up or network.
System.Net.Security.SslStream suggests a problem with the .net libraries.

found this on microsoft
```
Starting with .NET Framework 4.7, this method authenticates using None, which allows the operating system to choose the best protocol to use, and to block protocols that are not secure.In .NET Framework 4.6 (and .NET Framework 4.5 with the latest security patches installed)
```
I'm on windows .net 4.8 with the latest updates and I don't have this issue.
So check you are up to date with window updates for the .net suite and see if that solves the issue.

**Comment by ahmetsamsa** [comment]
> the indexer works for me on my win10home, so the issue is definitely local to your set up or network.
> System.Net.Security.SslStream suggests a problem with the .net libraries.
> 
> found this on microsoft
> 
> ```
> Starting with .NET Framework 4.7, this method authenticates using None, which allows the operating system to choose the best protocol to use, and to block protocols that are not secure.In .NET Framework 4.6 (and .NET Framework 4.5 with the latest security patches installed)
> ```
> 
> I'm on windows .net 4.8 with the latest updates and I don't have this issue.
> So check you are up to date with window updates for the .net suite and see if that solves the issue.

I checked for updates, there wasn't any. Downloaded 4.8 and tried to install it. Windows said you already have newer version.

Also I'm getting this error when I tried to add successful indexer to Radarr. I use same method you showed in my previous issue. It work perfectly for Kickass Torrent
It doesn't work  for others

I have Norton Antivirus software. I disabled protection and tested it, it still give errors.

`

2020-08-17 02:02:56 | Error | {0} Jackett.Common.IndexerException: Exception (ettv): Alınan ileti beklenmeyen veya hatalı biçimdeydi.  ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.  ---> System.IO.IOException: The read operation failed, see inner exception.  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.  ---> System.ComponentModel.Win32Exception (0x80090326): Alınan ileti beklenmeyen veya hatalı biçimdeydi.    --- End of inner exception stack trace ---    at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)    at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)    at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)    at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)    at System.Net.Security.SslStream.ReplyOnReAuthentication(Byte[] buffer, CancellationToken cancellationToken)    at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)    --- End of inner exception stack trace ---    at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)    at System.Net.Http.HttpConnection.FillAsync()    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)    at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 229    at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 164    at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 447    at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1341    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 347    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 347    at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 808    at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in D:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 370
-- | -- | --


`

**Comment by ngosang** [comment]
@ahmetsamsa Could you share the traces that Jackett prints on start up? Something like these:
```
2020-09-25 00:09:00 | Info | Using HTTP Client: HttpWebClient2
2020-09-25 00:09:00 | Info | Using Proxy: No
2020-09-25 00:09:00 | Info | App config/log directory: /xxxxxx/.config/Jackett
2020-09-25 00:09:00 | Info | ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2020-09-25 00:09:00 | Info | Running in Docker: No
2020-09-25 00:09:00 | Info | File /etc/issue: Arch Linux \r (\l)
2020-09-25 00:09:00 | Info | Jackett variant: CoreLinuxAmdx64
2020-09-25 00:09:00 | Info | OS version: Unix 5.8.9.2 (64bit OS) (64bit process)
2020-09-25 00:09:00 | Info | Environment version: 3.1.2 (/usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.2/)
2020-09-25 00:08:58 | Info | Starting Jackett v0.0.0.0
```

**Comment by ahmetsamsa** [comment]
@ngosang 

`

2020-09-27 12:37:02 | Info | Loading Cardigann definitions from: C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\cardigann\definitions\, C:\WINDOWS\system32\config\systemprofile\AppData\Local\cardigann\definitions\, C:\ProgramData\Jackett\Definitions
-- | -- | --
2020-09-27 12:37:02 | Info | Using HTTP Client: HttpWebClient2NetCore
2020-09-27 12:37:02 | Info | Using Proxy: No
2020-09-27 12:37:02 | Info | App config/log directory: C:\ProgramData\Jackett
2020-09-27 12:37:02 | Info | ThreadPool MaxThreads: 682 workerThreads, 1000 completionPortThreads
2020-09-27 12:37:02 | Info | Jackett variant: CoreWindows
2020-09-27 12:37:02 | Info | OS version: Microsoft Windows NT 6.2.9200.0 (64bit OS)
2020-09-27 12:37:02 | Info | Environment version: 3.1.7 (C:\ProgramData\Jackett\)
2020-09-27 12:37:02 | Info | Starting Jackett v0.16.1020.0

`

**Comment by ngosang** [comment]
Well, it looks good to me.
Since this tracker is working for me, I can't provide more help. Must be a network/configuration issue not related to Jackett.

**Comment by ahmetsamsa** [comment]
> Well, it looks good to me.
> Since this tracker is working for me, I can't provide more help. Must be a network/configuration issue not related to Jackett.

Do you know if there any SSL certificate that I need to install to run Jacket successfully on Windows 10 64 Bit?

**Comment by ngosang** [comment]
You don't need to touch Windows certificates.

**Comment by ahmetsamsa** [comment]
> You don't need to touch Windows certificates.

I think something is broken in my Windows 10. It does work perfectly on same machine via Windows Sandbox
