### ISSUE TITLE
[REQ] GreekDiamond

### ISSUE THREAD

**Issue by vlevas** [Jackett/Jackett#9407]
Hello we have another greek tracker if is possible to include it on jackett if its possible..

https://greekdiamond.info/

The registrations are Open at this time.. 

Thanks.

**Comment by garfield69** [comment]
Jackett 0.16.1072

**Comment by garfield69** [comment]
https://greekdiamond.info/ returning 
```
504 Gateway Time-out
nginx
```
Just me, or is the site gone, broken or moved to a new domain?

**Comment by ilike2burnthing** [comment]
What I'm currently getting:
![greek](https://user-images.githubusercontent.com/59480337/98663157-a0f19c80-2340-11eb-871b-98b2c588083c.png)

**Comment by vlevas** [comment]
i cant open it also.. let me check around a little and i will repost

**Comment by ilike2burnthing** [comment]
Getting a few similar errors now:

`Connection to DB was not possible!No DB with that name seems to exist on the server!`

`Connection to DB was not possible!No DB with that name seems to exist on the server!Too many connections`

`Connection to DB was not possible!No DB with that name seems to exist on the server![2006] dbconn: mysql_connect: MySQL server has gone away`

**Comment by ilike2burnthing** [comment]
Back up here. Anyone else?

**Comment by garfield69** [comment]
while the login page is now displayed, the actual act of logging in fails with
![image](https://user-images.githubusercontent.com/6933240/98759833-c6f96880-2436-11eb-8267-bcd4e08c62e6.png)

**Comment by ilike2burnthing** [comment]
back up (registered and able to sign in)

**Comment by ilike2burnthing** [comment]
Currently finding no results due to: `Error while parsing DateTime "+00:00", using layout "02/01/2006 -07:00" (dd/MM/yyyy zzz): String '+00:00' was not recognized as a valid DateTime.`
```
CardigannIndexer (greekdiamond): Error while parsing row '
<tr>
	<td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=13">
			<img src="https://greekdiamond.info/style/DtBlue/images/categories/movies-hd-dvd.png" border="0" alt="Hd rip x264">
		</a>
	</td>
	<td class="lista" valign="middle" onmouseover="this.className='post'" onmouseout="this.className='lista'" style="padding-left:10px;overflow:auto;">
		<a href="index.php?page=torrent-details&amp;id=d97eed2453799180d5da83cc17af3316cb9c3b83" title="View details: The Lobster (2015) 720p WEB-DL x264 AC3 - iFT" onmouseover=" return overlib('<center>The Lobster (2015) 720p WEB DL x264 AC3   iFT</center><center><img src=torrentimg/d97eed2453799180d5da83cc17af3316cb9c3b83.jpg  width=200 border=0></center><center>Category: Hd rip x264 Size: 3.50 GB</center><center>Added:256 weeks ago</center><center><font color = green>Seeders: 0<font color = red> Leechers: 0<font color = purple> Done: 12</font></center>', CENTER);" onmouseout="return nd();">The Lobster (2015) 720p WEB DL x264 AC3   iFT</a><br>
		<img src="images/freeleech.gif" alt="free leech"></td>
	<script>
var g_nExpando=0;
function putItemInState(n,bState)
{
   var oItem,oGif;
      oItem=document.getElementById("descr"+n);
   oGif=document.getElementById("expandoGif"+n);
   
   if (bState=='toggle')
     bState=(oItem.style.display=='block');

   if(bState)
   {
       bState=(oItem.style.display='none');
       bState=(oGif.src='images/plus.gif');
   }
   else
   {
       bState=(oItem.style.display='block');
       bState=(oGif.src='images/minus.gif');
   }
}

function expand(nItem)
{
    putItemInState(nItem,'toggle');
}

function expandAll()
{
    if (!g_nExpando)
    {
        document.all.chkFlag.checked=false;
        return;
    }
    var bState=!document.all.chkFlag.checked;
    for(var i=0; i<g_nExpando; i++)
        putItemInState(i,bState);
}

	</script>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=d97eed2453799180d5da83cc17af3316cb9c3b83&amp;f=The+Lobster+%282015%29+720p+WEB-DL+x264+AC3+-+iFT.torrent">
			<img src="images/torrent.png" border="0" alt="torrent">
		</a>
	</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="index.php?page=bookmark&amp;do=add&amp;torrent_id=d97eed2453799180d5da83cc17af3316cb9c3b83">
			<img src="images/bookmark.png">
		</a>
	</td>
	<td align="center" width="40" class="lista" style="white-space:wrap; text-align:center;">23/12/2015</td>
	<td align="center" width="30" class="lista" style="text-align:center;">
		<center>
			<img src="images/old.gif" alt="1792 days">
		</center>
	</td>
	<td align="center" width="30" class="#FF0000" style="text-align: center;background:#FF0000">
		<a href="index.php?page=peers&amp;id=d97eed2453799180d5da83cc17af3316cb9c3b83" title="Click here to view peers details">0</a>
	</td>
	<td align="center" width="30" class="#FF0000" style="text-align: center;background:#FF0000">
		<a href="index.php?page=peers&amp;id=d97eed2453799180d5da83cc17af3316cb9c3b83" title="Click here to view peers details">0</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=torrent_history&amp;id=d97eed2453799180d5da83cc17af3316cb9c3b83" title="History - The Lobster (2015) 720p WEB-DL x264 AC3 - iFT">12</a>
	</td>
	<td align="center" width="30" class="lista" style="text-align: center;">
		<a href="index.php?page=userdetails&amp;id=266">
			<span style="color:#0000ff">pipis9242</span>
		</a>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">3.50 GB</td>
	<td align="center" width="45" class="lista" style="text-align: center;">0 KB/sec</td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<img src="images/flag/gb.png" alt="English" title="English">
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;">0%<br>
		<table border="0" width="44" cellspacing="0" cellpadding="0">
			<tbody>
				<tr>
					<td align="right" border="0" width="2">
						<img src="images/bar_left.gif">
					</td>
					<td align="left" border="0" background="images/progbar-black.gif" width="40">
						<img height="9" width="0" src="images/progbar-green.gif">
					</td>
					<td align="right" border="0" width="2">
						<img src="images/bar_right.gif">
					</td>
				</tr>
			</tbody>
		</table>
	</td>
	<td align="center" width="45" class="lista" style="text-align: center;background:">
		<a href="index.php?page=torrents&amp;action=up&amp;info_hash=d97eed2453799180d5da83cc17af3316cb9c3b83">
			<img src="images/go_top.png" border="0" up="" alt="">
		</a>
	</td>
	<td class="lista" align="center" style="text-align: center;"></td>
</tr>':

System.Exception: Error while parsing field=date, selector=td:nth-last-of-type(11), value= +00:00: DateTime parsing failed for "+00:00": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 98
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 205
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1531
```

**Comment by ilike2burnthing** [comment]
https://greekdiamond.info/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
> https://greekdiamond.info/ - ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://greekdiamond.info/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://greekdiamond.info/ returns ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://greekdiamond.info/ returns ERR_CONNECTION_TIMED_OUT

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://greekdiamond.info/ HTTP ERROR 500 (Internal Server Error)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://greekdiamond.info/ Plesk admin set up  login page

**Comment by garfield69** [comment]
v0.22.549
