### ISSUE TITLE
[nyaa.net] 401 Unauthorized, check your credentials - BitMitigate DDoS Protection

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#9410]
https://nyaa.net/ - [log-nyaa.txt](https://github.com/Jackett/Jackett/files/5146097/log-nyaa.txt)
https://sukebei.nyaa.net/ - [log-sukebei.txt](https://github.com/Jackett/Jackett/files/5146098/log-sukebei.txt) (essentially the same)

```
WebClient(HttpWebClient2NetCore): Returning Unauthorized => 
<script>

/*
var now = new Date();
var time = now.getTime();
time += 300 * 1000;
now.setTime(time);
document.cookie =
'challenge=BitMitigate.com'
'; expires=' + now.toUTCString() +
'; path=/';

*/

// cookie.js file
var cookieToday = new Date();
var expiryDate = new Date(cookieToday.getTime() + (1000 * 60 * 60)); // 60 minutes

/* Cookie functions originally by Bill Dortsch */
setCookie("challenge","BitMitigate.com",expiryDate,"/");


function setCookie (name,value,expires,path,theDomain,secure) {
   value = escape(value);
   var theCookie = name + "=" + value +
   ((expires)    ? "; expires=" + expires.toGMTString() : "") +
   ((path)       ? "; path="    + path   : "") +
   ((theDomain)  ? "; domain="  + theDomain : "") +
   ((secure)     ? "; secure"            : "");
   document.cookie = theCookie;
}

function getCookie(Name) {
   var search = Name + "="
   if (document.cookie.length > 0) { // if there are any cookies
      var offset = document.cookie.indexOf(search)
      if (offset != -1) { // if cookie exists
         offset += search.length
         // set index of beginning of value
         var end = document.cookie.indexOf(";", offset)
         // set index of end of cookie value
         if (end == -1) end = document.cookie.length
         return unescape(document.cookie.substring(offset, end))
      }
   }
}
function delCookie(name,path,domain) {
   if (getCookie(name)) document.cookie = name + "=" +
      ((path)   ? ";path="   + path   : "") +
      ((domain) ? ";domain=" + domain : "") +
      ";expires=Thu, 01-Jan-70 00:00:01 GMT";
}


</script>

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://bitmitigate.com/img/favicon.png" type="image/x-icon">

    <meta http-equiv="refresh" content="2">
    <title>BitMitigate DDoS Protection</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://bitmitigate.com/css/bootstrap.min.css">
    <!--icon font css-->
    <link rel="stylesheet" href="https://bitmitigate.com/vendors/themify-icon/themify-icons.css">
    <link rel="stylesheet" href="https://bitmitigate.com/vendors/font-awesome/css/all.css">
    <link rel="stylesheet" href="https://bitmitigate.com/vendors/flaticon/flaticon.css">
    <link rel="stylesheet" href="https://bitmitigate.com/vendors/animation/animate.css">
    <link rel="stylesheet" href="https://bitmitigate.com/vendors/owl-carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://bitmitigate.com/vendors/animation/animate.css">
    <link rel="stylesheet" href="https://bitmitigate.com/vendors/magnify-pop/magnific-popup.css">
    <link rel="stylesheet" href="https://bitmitigate.com/vendors/elagent/style.css">
    <link rel="stylesheet" href="https://bitmitigate.com/css/style.css">
    <link rel="stylesheet" href="https://bitmitigate.com/css/responsive.css">
</head>

<body>


    <header class="header_area">
        <nav class="navbar navbar-expand-lg menu_one menu_four">
            <div class="container">
              <a class="navbar-brand sticky_logo" href="https://bitmitigate.com/#">
   <img src="https://bitmitigate.com/2x-white.png" srcset="https://bitmitigate.com/1x-white.png 2x" alt="logo">
   <img src="https://bitmitigate.com/1x.png" srcset="https://bitmitigate.com/2x.png 2x" alt="">
</a>

<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="menu_toggle">
                        <span class="hamburger">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                        <span class="hamburger-cross">
                            <span></span>
                            <span></span>
                        </span>
                    </span>
                </button>


            </div>
        </nav>
    </header>
    <section class="error_area">
        <img class="error_shap" src="https://bitmitigate.com/img/breadcrumb/banner_bg.png" alt="">
        <div class="container flex">
            <div class="error_contain text-center">

                <h2 class="f_p f_400 w_color f_size_40">Loading...</h2>
                <p class="w_color f_300">We are checking your browser to make sure you aren't a bot or DDoS attack. This process is completely automatic and will only take a moment. Once it is completed you will be forwarded immediately.</p>
                <a href="https://bitmitigate.com/" class="about_btn btn-success  btn_hover mt_40">DDoS protection by BitMitigate</a>
            </div>
        </div>
    </section>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://bitmitigate.com/js/jquery-3.2.1.min.js"></script>
    <script src="https://bitmitigate.com/js/propper.js"></script>
    <script src="https://bitmitigate.com/js/bootstrap.min.js"></script>
    <script src="https://bitmitigate.com/vendors/wow/wow.min.js"></script>
    <script src="https://bitmitigate.com/vendors/sckroller/jquery.parallax-scroll.js"></script>
    <script src="https://bitmitigate.com/vendors/owl-carousel/owl.carousel.min.js"></script>
    <script src="https://bitmitigate.com/vendors/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="https://bitmitigate.com/vendors/isotope/isotope-min.js"></script>
    <script src="https://bitmitigate.com/vendors/magnify-pop/jquery.magnific-popup.min.js"></script>
    <script src="https://bitmitigate.com/js/main.js"></script>
</body>

</html>
```

```
Error on 20200829234128 for Sukebei-pantsu.txtJackett.Common.ExceptionWithConfigData: 401 Unauthorized, check your credentials
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebClientStringResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 461
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1385
```

```
{0} Jackett.Common.IndexerException: Exception (sukebei-pantsu): 401 Unauthorized, check your credentials
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: 401 Unauthorized, check your credentials
   at Jackett.Common.Indexers.CardigannIndexer.checkForError(WebClientStringResult loginResult, IList`1 errorBlocks) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 461
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1385
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 837
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1716
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 814
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 279
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 144
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by ilike2burnthing** [comment]
DDoS protection currently only enabled for https://sukebei.nyaa.net/

**Comment by garfield69** [comment]
sukebei have also lifted the DDoS protection.
