### ISSUE TITLE
NewPCT indexer not working

### ISSUE THREAD

**Issue by egrueda** [Jackett/Jackett#9418]
Jackett Version 0.16.1049.0
Error when I search any show, server returns 404

```
2020-08-31 12:10:38.1061 Error Error on 20200831121038 for NewPCT.txtNewtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Jackett.Common.Indexers.NewPCT.ParseSearchJsonContent(String content, String year) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 568




<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>






 
2020-08-31 12:10:38.1061 Error Jackett.Common.IndexerException: Exception (newpct): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
 ---> System.Exception: Parse error
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Jackett.Common.Indexers.NewPCT.ParseSearchJsonContent(String content, String year) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 568
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 837
   at Jackett.Common.Indexers.NewPCT.ParseSearchJsonContent(String content, String year) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 565
   at Jackett.Common.Indexers.NewPCT.MovieSearch(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 467
   at Jackett.Common.Indexers.NewPCT.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 236
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 810
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 224 Jackett.Common.IndexerException: Exception (newpct): Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
 ---> System.Exception: Parse error
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Jackett.Common.Indexers.NewPCT.ParseSearchJsonContent(String content, String year) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 568
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 837
   at Jackett.Common.Indexers.NewPCT.ParseSearchJsonContent(String content, String year) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 565
   at Jackett.Common.Indexers.NewPCT.MovieSearch(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 467
   at Jackett.Common.Indexers.NewPCT.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 236
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 810
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 224
2020-08-31 12:10:38.1303 Info Manual search for "conner" on newpct with 0 results. 
```

**Comment by egrueda** [comment]
Seems like https://descargas2020.org/ got redirected to new domain https://pctmix.com/

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/1282#issuecomment-683478706
