### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://www2.yggtorrent.si/ using form selector 

### ISSUE THREAD

**Issue by HugoPourrierNunez** [Jackett/Jackett#9439]
### Environment

**OS**: OpenMediaVault 5.5.9-1 (Usul)

**Docker version** : 19.03.12, build 48a66213fe

**Container version** : linuxserver/jackett:latest
- ID :  sha256:41320eb3b5a6e8c970b56b79427d4735cb319ad76ee12bba2942f64ccce38e98
- Created : 2020-09-03 10:08:28
- Build : Docker 19.03.12 on linux, amd64

**Jackett Version** : 0.16.1057.0

**Are you using a proxy or VPN? [yes/no]** :  no

### Description

Ygg doesn't work anymore in jackett, I got this error in result

### Logged Error Messages

2020-09-03 11:52:49 	Error 	

{0} Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://www2.yggtorrent.si/ using form selector #user-login
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www2.yggtorrent.si/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 573
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1369
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 837
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1716
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 810
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 273
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

2020-09-03 11:52:49 	Error 	

Error on 20200903115249 for YGGtorrent.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www2.yggtorrent.si/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 573
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1369

2020-09-03 11:52:49 	Info 	

CardigannIndexer (yggtorrent): Relogin required

2020-09-03 11:52:48 	Info 	

Fetching: https://www2.yggtorrent.si/new_search/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date

**Comment by sebpiller** [comment]
Hi,

Getting the same error. How did you fix it ?

**Comment by HugoPourrierNunez** [comment]
I set the parameters like this : 
Site Link : https://www.yggtorrent.si/
Search and download URL : www2.yggtorrent.si

**Comment by feline51** [comment]
Bonjour, apparemment cela ne fonctionne pas avec ces URL.

**Comment by valentinbourqui** [comment]
@feline51 change les urls si ca marche pas fait cancel puis tu essaies à nouveau d'ajouter le site et là ca doit passer.
