### ISSUE TITLE
[lostfilm] Exception (lostfilm): The string '19 апреля 2013' was not recognized as a valid DateTime. There is an unknown word starting at index '3'.: Parse error (Config)

### ISSUE THREAD

**Issue by stasivanov** [Jackett/Jackett#9441]
### Environment

**OS**: LibreELEC 9.2

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: Version 0.16.1057.0

**Last Working Jackett Version**: Don't know

**Are you using a proxy or VPN?** [yes/no] no

### Description

LostFilm just stopped working to me, it says it cannot parse date string. 

### Logged Error Messages

 An error occurred while updating this indexer
Exception (lostfilm): The string '19 апреля 2013' was not recognized as a valid DateTime. There is an unknown word starting at index '3'.: Parse error

```
{0} Jackett.Common.IndexerException: Exception (lostfilm): The string '19 апреля 2013' was not recognized as a valid DateTime. There is an unknown word starting at index '3'.
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.FormatException: The string '19 апреля 2013' was not recognized as a valid DateTime. There is an unknown word starting at index '3'.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 448
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 837
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 464
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 411
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 837
   at Jackett.Common.Indexers.LostFilm.FetchNewReleases() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 417
   at Jackett.Common.Indexers.LostFilm.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 208
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 814
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 278
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 101
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70
```

**Comment by garfield69** [comment]
The lostfilm indexer is working for me when I use the TEST button on my Jackett dashboard.
Please supply a **full enhanced** log. Hopefully the log with  the debug and HTML included will provide more details to work with.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by stasivanov** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5175212/log.txt)
Thanks for the response. Here, please take a look at log file. Now it failes to render a date "27 июня 2017", it's also represented on their html page as release date `eng`. Not sure if that's the issue, but everything was working to me earlier.

**Comment by stasivanov** [comment]
I also noticed the same error but with different date format if I perform search

```
Error on 20200904172803 for LostFilm.tv.txtSystem.FormatException: String '28.08.2015' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at Jackett.Common.Indexers.LostFilm.DateFromEpisodeColumn(IElement dateColumn) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 787
   at Jackett.Common.Indexers.LostFilm.FetchSeriesReleases(String url, TorznabQuery query, String filter) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 514
```
So, something is really strange here... Obviously C# can parse such strings...

**Comment by garfield69** [comment]
the lostfilm indexer (beginning with Jackett 0.8.1201) uses the .net library to parse the dd mmmm yyyy in Russian using the c# call 
https://github.com/Jackett/Jackett/blob/0701b13ddd448861ec3d4d9b5458b0872d09de77/src/Jackett.Common/Indexers/LostFilm.cs#L448
where Language is set to Russian
https://github.com/Jackett/Jackett/blob/0701b13ddd448861ec3d4d9b5458b0872d09de77/src/Jackett.Common/Indexers/LostFilm.cs#L110

this lines up with your enhanced log which shows
```
2020-09-04 16:54:35.8436 Error Jackett.Common.IndexerException: Exception (lostfilm): The string '27 июня 2017' was not recognized as a valid DateTime. There is an unknown word starting at index '3'.
 ---> System.Exception: Parse error
 ---> System.Exception: Parse error
 ---> System.FormatException: The string '27 июня 2017' was not recognized as a valid DateTime. There is an unknown word starting at index '3'.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at Jackett.Common.Indexers.LostFilm.FetchEpisodeReleases(String url) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/LostFilm.cs:line 448
```
you're using the correct version of Jackett as the line 448 matches our source at that location.

which means that for some reason your computer is not able to interpret the Russian date when asked to do so.

I am not a c# dev so this is uncharted territory for me, but it seems to me that the issue may well be with your .net library.
Perhaps you need to update/upgrade your .net libraries? See if you can get .net 4.8

**Comment by stasivanov** [comment]
Not an issue with a service - it's an issue with my machine. Specifically an issue with thr Jackett addon for Libreelec.

**Comment by thoradia** [comment]
.Net-Core Jackett was running in invariant mode, without International Components for Unicode (ICU)
This issue was fixed by running .Net Core Jackett with ICU
