### ISSUE TITLE
[yts] Parse error: Count cannot be less than zero. (Parameter 'count') (Config)

### ISSUE THREAD

**Issue by Aryan01234** [Jackett/Jackett#9452]
### Environment

**OS**: Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: linuxserver/jackett Jackett Version 0.16.1062.0 

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [no]

### Description

Site Link in yts indexer - https://yts.mx/
shows Count cannot be less than zero. (Parameter 'count') error

### Logged Error Messages

Parse error: Count cannot be less than zero. (Parameter 'count')

Exception (yts): Count cannot be less than zero. (Parameter 'count'): Parse error

### Detailed Error 

{0} System.Exception: Parse error
 ---> System.ArgumentOutOfRangeException: Count cannot be less than zero. (Parameter 'count')
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 102
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 837
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 212
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 76
   at Jackett.Common.Indexers.YTS.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 68
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

**Comment by garfield69** [comment]
The indexer is working for me which suggest the issue is at your end.
using a browser on the same machine that is running your Jackett, what do you see if you use this link
https://yts.mx/api/v2/list_movies.json
you should see something like this
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":20411,"limit":20,"page_number":1,"movies":[{"id":20918,"url":"https:\/\/yts.mx\/movies\/the-last-wave-1977","imdb_code":"tt0076299","title":"The Last Wave","title_english":"The Last Wave","title_long":"The Last Wave (1977)","slug":"the-last-wave-1977","year":1977,"rating":7,"runtime":106,"genres":["Drama","Fantasy","Mystery","Thriller"], [etc etc etc]
```

**Comment by Aryan01234** [comment]
I am Using Docker on Windows 10 (WSL) and uisng linuxserver jackett image (https://hub.docker.com/r/linuxserver/jackett) and using bridged mode in docker networking.

All other indexers are working like 1337x TPB etc and YTS was working fine untill few days ago when i checked. I have deleted and recreated the docker image tried with other image when i know it was working (Linuxserver : v0.16.1049-ls14 , Jackett Version 0.16.1049.0) still there is an issue with YTS indexer.

Using the link (https://yts.mx/api/v2/list_movies.json) i am seeing the similar result as u mentioned.

**Comment by Aryan01234** [comment]
I have factory reset the Docker installation and now yts is working again maybe there was issue in updating the jackett image and i was getting the error because of that. I am closing the issue as it is resolved now thanks for the help
