### ISSUE TITLE
[aidoruonline] Login failed: Selector

### ISSUE THREAD

**Issue by niruhsa** [Jackett/Jackett#9490]
# Environment

**OS**: Ubuntu

**.Net Runtime**: Mono

**Jackett Version**: 0.16.1128.0

**Last Working Jackett Version**: 0.16.1121

**Are you using a proxy or VPN?** no

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

1. Add new indexer -> Aidoru!Online
2. Get cookie from headers in dev tools on the website
3. Enter the cookie settings (Everything after "Cookie:")
4. Attempt to add the settings to the indexer

### Logged Error Messages

```
{0} Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 828
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 989
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

**Comment by garfield69** [comment]
the indexer works for me so this suggestes an issue at your end.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work to double check that you are fetching the correct cookie string.

**Comment by niruhsa** [comment]
I'm still getting the error
```
{0} Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="account-logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 828
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 989
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
```

Even after following [the troubleshooting](https://github.com/Jackett/Jackett/issues/9490#issuecomment-690971304) and double checking with 2 different browsers and restarting Jackett itself. I'm still getting the same error message and copying the cookie from both Chrome & Firefox on three different OS's too (Linux, Mac & Windows).

**Comment by garfield69** [comment]
- are you are using a browser running on the same machine that is running jackett?
are you are using any VPN or proxy?
- have you got a valid account on the web site, and do not have anything obstructing access to the torrents page (such as poor ratio, outstanding alerts, unread PM or anything that could interfere?

I have tested this indexer using
- windows10 using https://github.com/Jackett/Jackett/releases/download/v0.16.1128/Jackett.Installer.Windows.exe
- ubuntu 18.04.4 LTS image on win10VirtualBox using https://github.com/Jackett/Jackett/releases/download/v0.16.1128/Jackett.Binaries.LinuxAMDx64.tar.gz
- macOS Mojave image on win10VirtualBox using https://github.com/Jackett/Jackett/releases/download/v0.16.1128/Jackett.Binaries.macOS.tar.gz

I'm a windows user, I don't have any particular skills in the linux arena. 
perhaps you should try **ditching the mono** version of Jackett and installing the **linuxamdx64** by following https://github.com/Jackett/Jackett#install-on-linux-amdx64

@ilike2burnthing @ngosang  @cadatoiva  do you have any insights into this issue?

**Comment by ilike2burnthing** [comment]
Signed up for an account and it logs in fine using Jackett on Windows.

Trying to use that cookie (i.e. the wrong cookie) on my Jackett Docker container results in that error, with the returned HTML showing me as not being logged in (obviously).

The first question, "Are you are using a browser running on the same machine that is running jackett?" would seem to be the most obvious cause.

Just to check, is the cookie being used of the format:
```
__cfduid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; flog=n; ufp=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; pass=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; uid=nnnnn; mybbuser=nnnnn_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; sid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
n = numbers only
x = numbers and letters

**Comment by ilike2burnthing** [comment]
Update: just used the same proxy/VPN server that I use for my Jackett Docker container (running on a Linux-based NAS), to log into Aidoru on Windows and get the cookie from it on Chrome. Using this cookie on my Jackett Docker container worked. If I change or remove the proxy/VPN, it fails. Returning it to the correct server works fine.

So it doesn't appear to be platform or browser dependent, just IP address apparently.

**Comment by niruhsa** [comment]
Ah if it is IP locked then that makes sense, I'll try to do it with that then, thanks.

**Comment by garfield69** [comment]
@ilike2burnthing  thank you for your contribution to resolving this issue.
