### ISSUE TITLE
Unable to add SceneTime to Jackett (Request to Jackett server failed)

### ISSUE THREAD

**Issue by BEisem** [Jackett/Jackett#9493]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Docker / Ubuntu 20.04

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**: 0.16.1128.0

**Last Working Jackett Version**: n/a

**Are you using a proxy or VPN?** yes

### Description

Click on Add Indexer, then select SceneTime.

Should open a popup allowing you to enter information for SceneTime. Instead, I get a red box on the bottom of the screen with the message Request to Jackett server failed.

### Logged Error Messages

{0} CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/HttpWebClient2NetCore.cs:line 229
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in /home/vsts/work/1/s/src/Jackett.Common/Utils/Clients/WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 453
   at Jackett.Common.Indexers.SceneTime.GetConfigurationForSetup() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/SceneTime.cs:line 107
   at Jackett.Server.Controllers.IndexerApiController.Config() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70

**Comment by garfield69** [comment]
I get this too. My scenetime indexer was already setup some time ago, and I can use the indexer for searching.
But if I try to edit the indexer config I get the server error message that you reported.

This is due to scenetime website invoking the cloudflare anti-DDoS please-wait-while-we-check-your-browser page just before the scenetime https://www.scenetime.com/login.php login page is presented.
This prevents jackett from pulling up the login page, hence the error message.

So until scenetime drop their protection, and/or a c# dev can improve the scenetime c# indexer code to ignore the anti-DDoS page and bring up the config page, here is a bypass you can try:

1. shutdown the jackett service
2. edit (or create) with a plain text editor the scenetime config file (windows: C:\ProgramData\Jackett\Indexers\scenetime.json, linux: ~/.config/Jackett/Indexers\scenetime.json)
3. if creating the config for the first time, here is the template
```json
[
  {
    "id": "sitelink",
    "type": "inputstring",
    "name": "Site Link",
    "value": "https://www.scenetime.com/"
  },
  {
    "id": "username",
    "type": "inputstring",
    "name": "Username",
    "value": null
  },
  {
    "id": "password",
    "type": "inputstring",
    "name": "Password",
    "value": ""
  },
  {
    "id": "recaptcha",
    "type": "recaptcha",
    "name": "Recaptcha",
    "sitekey": null,
    "version": null
  },
  {
    "id": "freeleechonly(optional)",
    "type": "inputbool",
    "name": "Freeleech Only (Optional)",
    "value": false
  },
  {
    "id": "",
    "type": "displayinfo",
    "name": "",
    "value": "For best results, change the 'Torrents per page' setting to the maximum in your profile on the SceneTime webpage."
  },
  {
    "id": "cookieheader",
    "type": "hiddendata",
    "name": "CookieHeader",
    "value": ""
  },
  {
    "id": "lasterror",
    "type": "hiddendata",
    "name": "LastError",
    "value": null
  }
]
```
4. using a browser running on the same machine that runs Jackett, fetch your cookie (see https://github.com/Jackett/Jackett/wiki/Troubleshooting#your-cookie-did-not-work)
5. paste your cookie string in the **value** field of the **cookieheader** block in your config
6. save and restart the Jackett service
7. test your scenetime indexer

**Comment by BEisem** [comment]
Thanks, that worked perfectly!

**Comment by garfield69** [comment]
Jackett 0.16.1204
