### ISSUE TITLE
[showrss] Exception (showrss): Object reference not set to an instance of an object.: Parse error (Test)

### ISSUE THREAD

**Issue by ajdaniel** [Jackett/Jackett#9545]
### Environment

**OS**: Mac OS

**Jackett Version**: `0.16.1222.0`

**Last Working Jackett Version**: 🤷 

**Are you using a proxy or VPN?** yes

### Description

I will configure my ShowRSS feed, and the test works. But after a while (maybe a day) it stops working with the error message shown below. I can recreate the ShowRSS source with the same showrss feed URL and then it works again for a short while

### Logged Error Messages

```{0} Jackett.Common.IndexerException: Exception (showrss): Object reference not set to an instance of an object.
 ---> System.Exception: Parse error
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.ShowRSS.PerformQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/ShowRSS.cs:line 72
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 837
   at Jackett.Common.Indexers.ShowRSS.PerformQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/ShowRSS.cs:line 108
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /Users/runner/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 814
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /Users/runner/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 273
   at Jackett.Server.Controllers.IndexerApiController.Test() in /Users/runner/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /Users/runner/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70```

**Comment by ilike2burnthing** [comment]
Can you provide an enhanced log of the issue? https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by ajdaniel** [comment]
Here you go
 
[jacket_log.txt](https://github.com/Jackett/Jackett/files/5245509/jacket_log.txt)

**Comment by ngosang** [comment]
Did you change the URL in the tracker configuration? It must be `https://showrss.info/`
In your traces I see the RSS feed sourcecode is different from https://showrss.info/other/all.rss
