### ISSUE TITLE
[Galeriens] search works but download failed

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#9549]
Hello !
Jackett Version 0.16.1231.0
Windows 10 x64
When we click on manual download on a manual search, we are unable to download the torrent file.
Thanks !

**Comment by garfield69** [comment]
looks like the web site now requires you to first thank the uploader before continuing the download.
I'll see if I can update the indexer with the new requirement.

**Comment by garfield69** [comment]
@ngosang  I've hit a snag with this web site.
The site has the download link in the torrent details page, but requires a thankyou before downloading.
the details page link looks like `https://galeriens.com/TTV3/Torrents/11222`
and the thankyou link needs to be `https://galeriens.com/TTV3/Torrents/11222/Remercier`
after which access to the download link `https://galeriens.com/TTV3/Torrents/Telechargement/11222/L%20Orphelin%20-%20Un%20Conte%20d%27un%20Fantome%20Errant%202020%20notag.torrent` should be possible.

So for the yaml indexer for this site I have coded a download block
```yaml
download:
  before:
    # https://galeriens.com/TTV3/Torrents/11222/Remercier
    path: "{{ .DownloadUri.PathAndQuery }}/Remercier"
    method: get
  selector: a[href*="/Telechargement/"]
  attribute: href
```
but I get 
```html
Error downloading galeriens https://galeriens.com/TTV3/Torrents/11222 System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.handleRequest(requestBlock request, Dictionary`2 variables, String referer) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1740
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1790
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in D:\a\1\s\src\Jackett.Server\Controllers\DownloadController.cs:line 56
```
I've tried `.DownloadUri.AbsoluteUri` and `.DownloadUri.AbsolutePath` too.

Does the download block **Before** path support variable substitution like I've coded?

**Comment by garfield69** [comment]
OK. so I added a debug in the cardigann processor after line 1728
https://github.com/Jackett/Jackett/blob/dbee27484d54442295e6b6836e8af160c69d14bf/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1726-L1728
```c#
 logger.Debug($"CardigannIndexer ({Id}): handleRequest() requestLinkStr= {requestLinkStr}");
```
and now I can see that the **before path** does get resolved as I expected
```html
09-19 16:44:27 Debug CardigannIndexer (galeriens): handleRequest() requestLinkStr= https://galeriens.com/TTV3/Torrents/11222/Remercier
09-19 16:44:27 Error Error downloading galeriens https://galeriens.com/TTV3/Torrents/11222 System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.CardigannIndexer.handleRequest(requestBlock request, Dictionary`2 variables, String referer) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1741
   at Jackett.Common.Indexers.CardigannIndexer.Download(Uri link) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1791
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in C:\Users\Garfield69\Documents\GitHub\Jackett\src\Jackett.Server\Controllers\DownloadController.cs:line 56
```

so the issue is something else. I'll try to figure it out.
the torrent details thankyou link html looks like
```html
<a href='https://galeriens.com/TTV3/Torrents/11222/Remercier''><b> Remercier </b></a>
```
so I don't entirely understand why a http GET does not work :-(

**Comment by garfield69** [comment]
switching to using http POST like LeChaudron works. Yay.

**Comment by garfield69** [comment]
Jackett 0.16.1252

**Comment by pipopop** [comment]
Works great ! Thanks !
