### ISSUE TITLE
[funfile] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by martyn-holland** [Jackett/Jackett#9562]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**: Ubuntu 20 (Docker)

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**:

**Jackett Version**: 0.16.1260.0

**Last Working Jackett Version**: Unknown

**Are you using a proxy or VPN?** [yes/no] No

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]
Trying to add FunFile as a tracker

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]
Object reference not set to an instance of an object.

[Make sure you attach the full logs with your personal information removed in case we need more information]
`{0} System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.FunFile.<>c__DisplayClass7_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/FunFile.cs:line 73
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 260
   at Jackett.Common.Indexers.FunFile.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/FunFile.cs:line 77
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 70`
### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by martyn-holland** [comment]
[log.txt](https://github.com/Jackett/Jackett/files/5251442/log.txt)

**Comment by garfield69** [comment]
Try Jackett 0.16.1269.
if it continues to produce the same error then please provide an **Enhanced** log, and hopefully the debug and HTML included will provide more data to examine.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by martyn-holland** [comment]
Just to update that I tried adding FunFile again this morning and it has worked fine.

Not sure if the original problem was at my end or their end.
