### ISSUE TITLE
GiroTorrent: Login failed: Selector "a[href="logout.php"]" didn't match

### ISSUE THREAD

**Issue by pixwebagency** [Jackett/Jackett#9642]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment
OS
Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:
4.8
 Jackett Version 0.16.1340.0 

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]
yes
### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

Jackett.Common.ExceptionWithConfigData: Login failed: Selector "a[href="logout.php"]" didn't match
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 824
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 987
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 70

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Is this for the girotorrent indexer like you raised earlier in #9641 ?
This indexer works for me so the issue appears to be at your end.
The error basically means that jackett did not get presented with the page it was expecting during the login process.
But there is not enough info in the stack trace you provided to determine the reason.
So please provide a full **enhanced** log which should contain debug and HTML that will hopefully provide more info to explain your issue.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
Thanks.

**Comment by pixwebagency** [comment]
Sorry I put url in wron indexer (usenet not torrent url). Now works well. Thank you very much
