### ISSUE TITLE
[BUG] radarr and yts

### ISSUE THREAD

**Issue by angelss197200** [Jackett/Jackett#9668]
when searching in yts with radarr Alice in Wonderland 1949 and The Big House 1930, it loses connection with jackett, I get 

> Error on 20200927025131 for YTS.txtSystem.Exception: API error, movies missing
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 125

>{"status":"ok","status_message":"Query was successful","data":{"movie_count":3,"limit":50,"page_number":1},"@meta":{"server_time":1601193090,"server_timezone":"CET","api_version":2,"execution_time":"0 ms"}}

>Jackett.Common.IndexerException: Exception (yts): API error, movies missing
 ---> System.Exception: Parse error
 ---> System.Exception: API error, movies missing
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 125
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 756
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query, Int32 attempts) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 212
   at Jackett.Common.Indexers.YTS.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/YTS.cs:line 76
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 733
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 448

manjaro

Jackett v0.16.1356.0 (aur)

**Are you using a proxy or VPN?** 
no

**Comment by garfield69** [comment]
this is not a problem with Jackett but with the yts.mx api server which is returning conflicting data, stating that 3 movies were found while searching for `Alice in Wonderland 1949` and then not providing the movie torrents.
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":3,"limit":50,"page_number":1},"@meta":{"server_time":1601201643,"server_timezone":"CET","api_version":2,"execution_time":"0 ms"}}
```
notice the movie_count=3 but not followed by 3 torrent details blocks.
when you search directly on the web site you get nothing-found.
![image](https://user-images.githubusercontent.com/6933240/94362445-ce2f1600-0117-11eb-92ee-4e190ef41617.png)

at least  searching for `The Big House 1930` via the API returns correct no-found results
```json
{"status":"ok","status_message":"Query was successful","data":{"movie_count":0,"limit":50,"page_number":1},"@meta":{"server_time":1601202124,"server_timezone":"CET","api_version":2,"execution_time":"0 ms"}}
```
notice the movie_count=0 which is correct in this example, matching the web site search
![image](https://user-images.githubusercontent.com/6933240/94362493-2ebe5300-0118-11eb-8a3b-b31b2bf15f9b.png)

there is nothing Jackett ca do about this. It correctly gives you the error that the API stated 3 movies were found and then that the movies are missing when you searched for the alice movie.
```html
Error on 20200927231403 for YTS.txtSystem.Exception: API error, movies missing
```
