### ISSUE TITLE
Anidex search by categories does not work whilst searching by "any" works

### ISSUE THREAD

**Issue by elboletaire** [Jackett/Jackett#9727]
### Environment

**OS**: arch linux (using docker `linuxserver/jackett`)

**.Net Runtime**: Mono

**Jackett Version**: 0.16.1549.0

**Last Working Jackett Version**: not sure, the one used by latest linuxserver's docker image.

**Are you using a proxy or VPN?** yes, traefik

### Description

Searching in anidex works, but as soon as you try to search with categories, it returns empty results. Selecting all tags doesn't help at all either. 

Obviously sonarr & radarr aren't able to find anything because, AFAIK, it always uses categories when searching.

Note that this does not happen with other indexers, I'm only experiencing this issue with anidex.

### Logged Error Messages

There are no errors. It just doesn't return results.

![imatge](https://user-images.githubusercontent.com/153305/94993191-897c0280-058f-11eb-9a24-651ea5100872.png)

### Screenshots

- Working anidex resultset (no categories selected):
![imatge](https://user-images.githubusercontent.com/153305/94993205-a57fa400-058f-11eb-85b3-3ab15f9a0b8a.png)
- One category selected:
![imatge](https://user-images.githubusercontent.com/153305/94993217-b203fc80-058f-11eb-8ed4-703b7f85dc05.png)
- All categories selected:
![imatge](https://user-images.githubusercontent.com/153305/94993222-b9c3a100-058f-11eb-90ec-5f3c868af249.png)
- Other indexers' search by category:
![imatge](https://user-images.githubusercontent.com/153305/94993270-06a77780-0590-11eb-951f-033aff43b6ba.png)

**Comment by garfield69** [comment]
the anidex indexer needs to separate the categories in the query with a comma, like this:
https://anidex.info/?q=best+friends&s=upload_timestamp&o=desc&group=0&id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
https://anidex.info/?
which returns result.
![image](https://user-images.githubusercontent.com/6933240/94999413-c4287e00-0615-11eb-8b6a-a78dedd8fa18.png)

ATM the anidex indexer is encoding the comma as %2C and this generates a query like:
q=best+friends&s=upload_timestamp&o=desc&group=0&id=1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12%2C13%2C14%2C15%2C16
which returns
```
Email anidex.moe@gmail.com if you are seeing this error and you are NOT a bot.
```

**Comment by ilike2burnthing** [comment]
Working in browser:
- https://anidex.info/?q=best+friends&s=upload_timestamp&o=desc&group=0&id=1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12%2C13%2C14%2C16%2C15 (change id order)
- https://anidex.info/?q=best+friends&s=upload_timestamp&o=desc&group=0&id=1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12%2C13%2C14%2C%2C15%2C16 (extra %2C - doesn't work at the start of end of id string)

**Comment by garfield69** [comment]
Jackett 0.16.1583

**Comment by elboletaire** [comment]
Cool, now it works as expected. Thanks!

**Comment by elboletaire** [comment]
Hhmmm this is happening again in 0.17.159 😕

**Comment by ilike2burnthing** [comment]
Same workarounds as before work in browser:

current (blocked) - https://anidex.info/?q=2020+720p&s=upload_timestamp&o=desc&group=0&id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16

extra comma - https://anidex.info/?q=2020+720p&s=upload_timestamp&o=desc&group=0&id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,,15,16

switch order - https://anidex.info/?q=2020+720p&s=upload_timestamp&o=desc&group=0&id=1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,15

They have an RSS feed if we want to try to implement that - https://anidex.info/rss/

**Comment by ngosang** [comment]
> They have an RSS feed if we want to try to implement that - https://anidex.info/rss/

This is the way

**Comment by garfield69** [comment]
v0.18.95

**Comment by Rick45** [comment]
having the same error.

Anidex search returned unexpected result. Expected 200 OK but got Forbidden.

the page open without issues in the jackett machine

`
System.Net.WebException: Anidex search returned unexpected result. Expected 200 OK but got Forbidden.
   at Jackett.Common.Indexers.Anidex.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anidex.cs:line 193
   at Jackett.Common.Indexers.Anidex.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Anidex.cs:line 142
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask 1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
`
