### ISSUE TITLE
hdolimpo: error while parsing row 

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9730]
query: ""
```
CardigannIndexer (hdolimpo): Error while parsing row '
<tr>
	<td style="width: 1%;">
		<div class="torrent-poster pull-left"></div>
	</td>
	<td style="width: 1%;">
		<a href="https://hd-olimpo.club/categories/1">
			<div class="text-center">
				<i class="fas fa-film torrent-icon" data-toggle="tooltip" data-original-title="Películas torrent" style="padding-top: 10px;"></i>
			</div>
		</a>
	</td>
	<td style="width: 1%;">
		<div class="text-center" style="padding-top: 15px;">
			<span class="label label-success" data-toggle="tooltip" data-original-title="Tipo">
				UHD Custom
			</span>
		</div>
		<div class="text-center" style="padding-top: 8px;">
			<span class="label label-success" data-toggle="tooltip" data-original-title="Resolución">
				2160p
			</span>
		</div>
	</td>
	<td>
		<a class="view-torrent" href="https://hd-olimpo.club/torrents/6979">
			Joker (2019) [Custom FullUHD 2160p HEVC Dolby Vision ESP DTS-HD 7.1 ENG Atmos 7.1] [Grupo Custom U-HD Audio Editado]
		</a>
		<br>
		<span class="badge-extra text-bold">
			<i class="fas fa-upload" data-toggle="tooltip" data-original-title="Uploader"></i>
			<a href="https://hd-olimpo.club/users/Cesarleeds">
				Cesarleeds
			</a>
		</span>
		<a href="https://www.themoviedb.org/movie/475557?language=es" target="_blank">
			<span class="badge-extra text-bold">
				<span class="text-gold movie-rating-stars">
					<i class="fas fa-thumbs-up" data-toggle="tooltip" data-original-title="Ver más"></i>
				</span>
				8.2/10 (14980 Votos)
			</span>
		</a>
		<span class="badge-extra text-bold text-pink">
			<i class="fas fa-heart" data-toggle="tooltip" data-original-title="Gracias recibidas"></i>
			0
		</span>
		<a href="https://hd-olimpo.club/torrents/6979#comments">
			<span class="badge-extra text-bold text-green">
				<i class="fas fa-comment" data-toggle="tooltip" data-original-title="Comentarios"></i>
				0
			</span>
		</a>
		<span class="badge-extra text-bold">
			<img src="/img/audioe_corto.png" alt="Audio editado" height="13" data-toggle="tooltip" title="" data-original-title="Audio editado">
		</span>
		<br>
		<span class="badge-extra text-bold">
			<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title="Género"></i>
			Crimen
		</span>
		<span class="badge-extra text-bold">
			<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title="Género"></i>
			Drama
		</span>
		<span class="badge-extra text-bold">
			<i class="fas fa-tag" data-toggle="tooltip" title="" data-original-title="Género"></i>
			Suspense
		</span>
	</td>
	<td>
	</td>
	<td>
		<a href="https://hd-olimpo.club/torrents/download/6979">
			<button class="btn btn-primary btn-circle" type="button" data-toggle="tooltip" data-original-title="Descargado">
				<i class="fas fa-download"></i>
			</button>
		</a>
		<a href="magnet:?dn=Joker (2019) [Custom FullUHD 2160p HEVC Dolby Vision ESP DTS-HD 7.1 ENG Atmos 7.1] [Grupo Custom U-HD Audio Editado]&amp;xt=urn:btih:ef57ab8aba4c1a25895adb59a74aa096f48760db&amp;as=https://hd-olimpo.club/torrent/download/6979.123456&amp;tr=https://hd-olimpo.club/announce/9E4DC3D2zFiFW3As4xdryps4toi5ObEz&amp;xl=68500520960">
			<button class="btn btn-primary btn-circle" type="button" data-toggle="tooltip" data-original-title="Magnet">
				<i class="fas fa-magnet"></i>
			</button>
		</a>
	</td>
	<td>
		<span data-toggle="tooltip" data-original-title="Bookmark" id="torrentBookmark6979" torrent="6979" state="0" class="torrentBookmark"></span>
	</td>
	<td>
		<time>hace 27 segundos</time>
	</td>
	<td>
		<span class="badge-extra text-blue text-bold">63.8 GiB</span>
	</td>
	<td>
		<a href="https://hd-olimpo.club/torrents/6979/peers">
			<span class="badge-extra text-green text-bold">
				0
			</span>
		</a>
	</td>
	<td>
		<a href="https://hd-olimpo.club/torrents/6979/peers">
			<span class="badge-extra text-red text-bold">
				0
			</span>
		</a>
	</td>
	<td>
		<a href="https://hd-olimpo.club/torrents/6979/history">
			<span class="badge-extra text-orange text-bold">
				0 Veces
			</span>
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=date, selector=time, value= ago 27 segundos: DateTime parsing failed for "ago 27 segundos": System.Exception: TimeAgo parsing failed, unknown unit: segundos
   at Jackett.Common.Utils.DateTimeUtil.FromTimeAgo(String str) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 77
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 110
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1610
```

**Comment by garfield69** [comment]
Hah!
All the unit3d indexers are missing translations for seconds ... never seen a torrent loaded just seconds ago and never thought to add support for this. I'll make amendments.
