### ISSUE TITLE
Can't download torrent from keepfriends by jackett

### ISSUE THREAD

**Issue by gaofashao** [Jackett/Jackett#9739]
### Environment

**OS**:
docker on ubuntu 18.04
**Jackett Version**:
Jackett Version 0.16.1559.0
**Last Working Jackett Version**:
sorry, I can't remember
**Are you using a proxy or VPN?** [yes/no]
no
### Description
When I use radarr to manually search for movies and download them, radarr can provide search results but when I click download, it prompts "getting release from indexer failed". When I search and download torrents directly through Jackett, Jackett prompts that the web page does not exist. 
### Logged Error Messages
```
2020-10-04 23:30:23 | Info | Manual search for "2 Guns" on keepfriends with 4 results.
```
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>USS Enterprise NCC-1701</title>
<script src="/cdn-cgi/apps/head/78vWPTT9iuJLkVDhRXC5NoYPJFE.js"></script><link rel="shortcut icon" href="/static/facebook/favicon.ico.404" type="image/vnd.microsoft.icon" />
<style>
      body {
        margin: 0;
        padding: 0;
      }

      .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: black;
        color: white;
        text-align: center;
        height: 60px;
      }

      .tablewrapper,
      form {
        height: 100%;
      }

      .inputtext2 {
        width: 50px;
      }

      a {
        color: white;
      }
      #bg_container {
        width: 100vw;
        height: 100vh;
        overflow: hidden;
        background-image: url("/static/pic/uss-image.jpg");
        background-color: #000;
        background-position: center center;
        background-repeat: no-repeat;
      }
      #bg {
        width: 100vw;
        height: 100vh;
      }
    </style>
</head>
<body>
<div id="bg_container"></div>
<div class="footer">
<form method="post" action="takelogin.php">
<table class="tablewrapper" align="center">
<tr>
<td colspan="7">
USS Enterprise NCC-1701 is now boarding passengers.
</td>
</tr>
<tr>
<td>
Boarding pass:
</td>
<td>
<input type="text" class="inputtext" name="username" />
</td>
<td>
<input type="password" class="inputtext" name="password" />
</td>
<td>
<input type="text" class="inputtext2" name="token" />
</td>
<td>
<input type="submit" value="To Mars" id="button" disabled />
</td>
<td>
<input type="checkbox" name="logout" value="yes" /> One-Way Ticket
</td>
<td>
<a href="recover.php">Lost your ticket?</a>
<input type="hidden" name="recaptcha_response" id="recaptchaResponse" />
</td>
</table>
</form>
</div>
<script src="https://recaptcha.net/recaptcha/api.js?render=6LdYS6oUAAAAAIGtUJT22BQ8pfJT6uZ5NjRdtz2T"></script>
<script type="text/javascript">
        grecaptcha.ready(function () {
          grecaptcha
            .execute('6LdYS6oUAAAAAIGtUJT22BQ8pfJT6uZ5NjRdtz2T', {action: location.pathname.replace('.', '_')})
            .then(function (token) {
              var recaptchaResponse = document.getElementById('recaptchaResponse');
              recaptchaResponse.value = token;
              document
                .getElementById('button')
                .disabled = false;
            });
        });
      </script>
</body>
</html>
```
```
Error downloading. indexer: keepfriends path: https://pt.keepfrds.com/download.php?id=11521
System.Exception: BencodeParser failed
 ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeReader reader)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Stream stream)
   at BencodeNET.Parsing.BencodeParserExtensions.Parse(IBencodeParser parser, Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 78
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 85
```
### Screenshots
![image](https://user-images.githubusercontent.com/39672493/95019949-e4e6e700-069a-11eb-8f1a-ae5b66e6c8c2.png)
![image](https://user-images.githubusercontent.com/39672493/95020145-072d3480-069c-11eb-8b87-47fcce3c45c8.png)

**Comment by garfield69** [comment]
@RoloSoze  are you able to check if downloads on KeepFriends is working for you?

**Comment by RoloSoze** [comment]
@garfield69 They're working fine. I can confirm that I am able to download .torrent files from KeepFriends directly via Jackett.

**Comment by garfield69** [comment]
@RoloSoze Thanks.
@gaofashao  the problem appears to be at your end.
Check that you have a good ratio on the site and check that you can actually download the file you were trying to use via Jackett, by using your browser directly on the keepfriends web site.
If you have not downloaded on the site before you may need to read the first-time-download page that can sometimes be presented by web sites on the user's first download. Jackett expects download links to be direct to .torrent or magnets.
And once that is all done then try using Jackett again.
If you continue to have problems then maybe a **full enhanced** log may provide the additional debug and HTML that may help explain the problem.
see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket
