### ISSUE TITLE
[redacted] "Use Freeleech Tokens when Available" Option Broken

### ISSUE THREAD

**Issue by Ayfteyd7Od** [Jackett/Jackett#9753]
### Environment

**OS**:
LSIO docker container

**Jackett Version**:
 Jackett Version 0.16.1583.0 

**Last Working Jackett Version**:
Prior to switch to API auth for Redacted

**Are you using a proxy or VPN?** [yes/no]
no

### Description

Configure Redacted with API key. Check box 'Use Freeleech Tokens when Available'. Use up all your freeleech tokens at RED.
Try to download something.

Unchecking "Use Freeleech Tokens when Available" resolves this issue.

### Logged Error Messages

```
10-05 12:14:44 Error Failed download cookies: session=<REMOVED> 
10-05 12:14:44 Error Failed download response:
{"status":"failure","error":"You do not have any freeleech tokens left. Please use the regular DL link."} 
10-05 12:14:44 Error Error downloading. indexer: redacted path: https://redacted.ch/ajax.php?action=download&usetoken=1&id=<REMOVED>
System.Exception: Remote server returned BadRequest
   at Jackett.Common.Indexers.BaseWebIndexer.Download(Uri link, RequestType method, String refererlink, Dictionary`2 headers) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 409
   at Jackett.Common.Indexers.Abstract.GazelleTracker.Download(Uri link) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs:line 372
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 56 
```

**Comment by ngosang** [comment]
@seeyabye this is related to #9666 
Could you take a look? I'm banned for now => https://github.com/Jackett/Jackett/issues/9751#issuecomment-703849623

**Comment by ngosang** [comment]
@seeyabye I reverted #9666 until we fix 2 open issues. I can't help since I'm banned..

**Comment by garfield69** [comment]
Jackett 0.16.1664
