### ISSUE TITLE
rintornet: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9755]
"query": "720p"

```
CardigannIndexer (rintornet): Error while parsing row '
<div class="entry">
	<div class="entry__title h2">
		<a href="https://www.rintor.net/porno_casting/6956-chanel-kiss-classy-woman-gets-eaten-during-casting-2020-hd-720p.html">Chanel Kiss - Classy woman gets eaten during casting (2020) HD 720p</a>
	</div>
	<div class="entry__rating">
		<span class="entry__rating-value entry__rating-value_turquoise">5</span>
		<div class="rating">
			<ul class="unit-rating">
				<li class="current-rating" style="width:100%;">100</li>
			</ul>
		</div>
	</div>
	<div class="entry__stat">
		<span class="entry__author">Залил: 
			<!--noindex-->
			<a onclick="ShowProfile('%D0%9F%D0%B0%D0%BB+%D0%9F%D0%B0%D0%BB%D1%8B%D1%87', 'https://www.rintor.net/user/%D0%9F%D0%B0%D0%BB+%D0%9F%D0%B0%D0%BB%D1%8B%D1%87/', '0'); return false;" href="https://www.rintor.net/user/%D0%9F%D0%B0%D0%BB+%D0%9F%D0%B0%D0%BB%D1%8B%D1%87/">Пал Палыч</a>
			<!--/noindex-->
			<span class="entry__stat-divider">|</span>
		</span>
		<span class="entry__date">Сегодня, 06:48</span>
		<span class="entry__stat-divider">|</span>
		<span class="entry__reads">
			<span>Просмотров:
			</span>&nbsp;111</span>
		<span class="entry__stat-divider">|</span>
		<span class="entry__comments">
			<span>Комментариев:</span>
		</span>
		<!--noindex-->
		<a href="https://www.rintor.net/porno_casting/6956-chanel-kiss-classy-woman-gets-eaten-during-casting-2020-hd-720p.html#comment">0</a>
		<!--/noindex-->
	</div>
	<hr class="entry__header-divider">
	<div class="entry_content">
		<a href="https://www.rintor.net/porno_casting/6956-chanel-kiss-classy-woman-gets-eaten-during-casting-2020-hd-720p.html" class="entry__content-image" title="Перейти к скачиванию торрента..." rel="nofollow">
			<img src="/uploads/posts/2020-10/1601873349_42aaf807721a8d1f4ac5dda59c6bc3ac.jpg" alt="Chanel Kiss - Classy woman gets eaten during casting (2020) HD 720p">
		</a>
		<div class="entry__content-description">
		</div>
	</div>
	<div class="entry__info">
		<a href="https://www.rintor.net/porno_casting/6956-chanel-kiss-classy-woman-gets-eaten-during-casting-2020-hd-720p.html#download" rel="nofollow" class="entry__info-download">Скачать торрент</a>
		<a href="#" class="popup-open popup-open_login" rel="nofollow">
			<span class="entry__bookmark" title="Добавить в закладки"></span>
		</a>
		<br>
		<br>
		<a href="https://www.rintor.net/porno_casting/">Порно Кастинг | Porno Casting</a>
	</div>
</div>':

System.Exception: Error while parsing field=category, selector=div.entry__info, value=<null>: None of the case selectors "[a:last-of-type:contains("2160p"), 20],[a:last-of-type:contains("HD"), 1],[a:last-of-type:contains("SiteRip"), 9],[a:last-of-type:contains("WEBRip"), 12],[a:last-of-type:contains("Amateur"), 10],[a:last-of-type:contains("Incest"), 24],[a:last-of-type:contains("Lesbians"), 22],[a:last-of-type:contains("Classic"), 23],[a:last-of-type:contains("Femdom"), 21],[a:last-of-type:contains("BDSM"), 17],[a:last-of-type:contains("Pregnant"), 19],[a:last-of-type:contains("Shemale"), 16],[a:last-of-type:contains("Peeing"), 25],[a:last-of-type:contains("Picture"), 11],[a:last-of-type:contains("Cartoons"), 14],[a:last-of-type:contains("Games"), 13],[a:last-of-type:contains("Gay"), 15]" matched 
<div class="entry__info">
	<a href="https://www.rintor.net/porno_casting/6956-chanel-kiss-classy-woman-gets-eaten-during-casting-2020-hd-720p.html#download" rel="nofollow" class="entry__info-download">Скачать торрент</a>
	<a href="#" class="popup-open popup-open_login" rel="nofollow">
		<span class="entry__bookmark" title="Добавить в закладки"></span>
	</a>
	<br>
	<br>
	<a href="https://www.rintor.net/porno_casting/">Порно Кастинг | Porno Casting</a>
</div>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1610
```

**Comment by ngosang** [comment]
Empty search
```
CardigannIndexer (rintornet): Error while parsing row '
<div class="entry">
	<div class="entry__title h2">
		<a href="https://www.rintor.net/bukkake/8123-freya-parker-jesse-loads-monster-facials-2020-hd-1080p.html">Freya Parker - Jesse Loads Monster Facials (2020) HD 1080p</a>
	</div>
	<div class="entry__rating">
		<span class="entry__rating-value entry__rating-value_turquoise">3</span>
		<div class="rating">
			<ul class="unit-rating">
				<li class="current-rating" style="width:60%;">60</li>
			</ul>
		</div>
	</div>
	<div class="entry__stat">
		<span class="entry__author">Залил: 
			<!--noindex-->
			<a onclick="ShowProfile('%D0%9F%D0%B0%D0%BB+%D0%9F%D0%B0%D0%BB%D1%8B%D1%87', 'https://www.rintor.net/user/%D0%9F%D0%B0%D0%BB+%D0%9F%D0%B0%D0%BB%D1%8B%D1%87/', '0'); return false;" href="https://www.rintor.net/user/%D0%9F%D0%B0%D0%BB+%D0%9F%D0%B0%D0%BB%D1%8B%D1%87/">Пал Палыч</a>
			<!--/noindex-->
			<span class="entry__stat-divider">|</span>
		</span>
		<span class="entry__date">Вчера, 12:23</span>
		<span class="entry__stat-divider">|</span>
		<span class="entry__reads">
			<span>Просмотров:
			</span>&nbsp;295</span>
		<span class="entry__stat-divider">|</span>
		<span class="entry__comments">
			<span>Комментариев:</span>
		</span>
		<!--noindex-->
		<a href="https://www.rintor.net/bukkake/8123-freya-parker-jesse-loads-monster-facials-2020-hd-1080p.html#comment">0</a>
		<!--/noindex-->
	</div>
	<hr class="entry__header-divider">
	<div class="entry_content">
		<a href="https://www.rintor.net/bukkake/8123-freya-parker-jesse-loads-monster-facials-2020-hd-1080p.html" class="entry__content-image" title="Перейти к скачиванию торрента..." rel="nofollow">
			<img src="/uploads/posts/2020-12/1608549877_042e4e4998d0c41463e2ea4352cac451.jpg" alt="Freya Parker - Jesse Loads Monster Facials (2020) HD 1080p">
		</a>
		<div class="entry__content-description">
		</div>
	</div>
	<div class="entry__info">
		<a href="https://www.rintor.net/bukkake/8123-freya-parker-jesse-loads-monster-facials-2020-hd-1080p.html#download" rel="nofollow" class="entry__info-download">Скачать торрент</a>
		<a href="#" class="popup-open popup-open_login" rel="nofollow">
			<span class="entry__bookmark" title="Добавить в закладки"></span>
		</a>
		<br>
		<br>
		<a href="https://www.rintor.net/bukkake/">Буккаке | Bukkake</a>
	</div>
</div>':

System.Exception: Error while parsing field=category, selector=div.entry__info, value=<null>: None of the case selectors "[a:last-of-type:contains("2160p"), 20],[a:last-of-type:contains("HD"), 1],[a:last-of-type:contains("SiteRip"), 9],[a:last-of-type:contains("WEBRip"), 12],[a:last-of-type:contains("Amateur"), 10],[a:last-of-type:contains("Incest"), 24],[a:last-of-type:contains("Lesbians"), 22],[a:last-of-type:contains("Casting"), 26],[a:last-of-type:contains("Classic"), 23],[a:last-of-type:contains("Femdom"), 21],[a:last-of-type:contains("BDSM"), 17],[a:last-of-type:contains("Pregnant"), 19],[a:last-of-type:contains("Shemale"), 16],[a:last-of-type:contains("Peeing"), 25],[a:last-of-type:contains("Picture"), 11],[a:last-of-type:contains("Cartoons"), 14],[a:last-of-type:contains("Games"), 13],[a:last-of-type:contains("Gay"), 15]" matched 
<div class="entry__info">
	<a href="https://www.rintor.net/bukkake/8123-freya-parker-jesse-loads-monster-facials-2020-hd-1080p.html#download" rel="nofollow" class="entry__info-download">Скачать торрент</a>
	<a href="#" class="popup-open popup-open_login" rel="nofollow">
		<span class="entry__bookmark" title="Добавить в закладки"></span>
	</a>
	<br>
	<br>
	<a href="https://www.rintor.net/bukkake/">Буккаке | Bukkake</a>
</div>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1526
```
