### ISSUE TITLE
[NewPCT] Download link not found!

### ISSUE THREAD

**Issue by Toneti10** [Jackett/Jackett#9760]
### Environment

**OS**: linuxserver docker container

**Jackett Version**: 0.16.1583.0

**Are you using a proxy or VPN?** No

### Description

Jackett knows there is a new torrent (from indexer **NewPCT**) but it cannot get the download link.

### Logged Error Messages

**Error downloading. indexer: newpct path:** https://pctmix.com/descargar/serie/the-walking-dead/temporada-10/capitulo-16/
**System.Exception: Download link not found!**
   at Jackett.Common.Indexers.NewPCT.Download(Uri linkParam) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/NewPCT.cs:line 173
   at Jackett.Server.Controllers.DownloadController.Download(String indexerID, String path, String jackett_apikey, String file) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/DownloadController.cs:line 97

**Comment by garfield69** [comment]
Jackett 0.16.1621
