### ISSUE TITLE
[morethantv] Object reference not set to an instance of an object. (Config)

### ISSUE THREAD

**Issue by SawkeeReemo** [Jackett/Jackett#9794]
### Environment

**OS**: Synology NAS (Linux; run inside Docker container)

**Jackett Version**:   0.16.1635.0

**Last Working Jackett Version**: ???

**Are you using a proxy or VPN?** [no]

### Description

Trying to addd the new URL and login info for MoreThanTV, and I get this error with no explanation:
"An error occurred while updating this indexer
Object reference not set to an instance of an object."

Pastebin for the logs: [https://pastebin.com/QqMcxzAL](https://pastebin.com/QqMcxzAL)

### Logged Error Messages

System.NullReferenceException: Object reference not set to an instance of an object.
   at Jackett.Common.Indexers.MoreThanTV.<>c__DisplayClass15_0.<ApplyConfiguration>b__0() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MoreThanTV.cs:line 79
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 260
   at Jackett.Common.Indexers.MoreThanTV.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/MoreThanTV.cs:line 83
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26

### Screenshots

![Jackett Error](https://user-images.githubusercontent.com/60272670/95571866-f94e1b00-09dd-11eb-95dc-6c3f068a5ebe.png)

**Comment by garfield69** [comment]
MoreThanTV are in the process of migrating to a new platform.
Once completed the existing Jackett indexer will need to be rewritten.
Follow #9670 for progress updates on this topic.
