### ISSUE TITLE
[ilcorsaroblu] Login failed: No form found on https://ilcorsaroblu.org/index.php?page=login

### ISSUE THREAD

**Issue by cinghialino** [Jackett/Jackett#9811]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment

**OS**:

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:

**Last Working Jackett Version**:

**Are you using a proxy or VPN?** [yes/no]

### Description

[List steps to reproduce the error and details on what happens and what you expected to happen]

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
the indexer is working for me which suggests the problem is at your end.
you are likely being blocked by your ISP, have you tried accessing the site from a browser to confirm?
if you want further help with this provide a full **enhanced** log, see https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.

**Comment by cinghialino** [comment]
I checked the website on the browser before submitting this ticket, and it works properly.


here is the log:

`Jackett.Common.IndexerException: Exception (rarbg): Error reading JObject from JsonReader. Path '', line 0, position 0.
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Jackett.Common.Indexers.RarBG.PerformQueryWithRetry(TorznabQuery query, Boolean retry) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 124
   at Jackett.Common.Indexers.RarBG.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/RarBG.cs:line 116
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 353
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 730
   at Jackett.Server.Controllers.ResultsController.Torznab(TorznabRequest request) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/ResultsController.cs:line 448`

**Comment by garfield69** [comment]
that snippet of the log is for RARBG
I thought you were having issues with ilcorsaroblu ;-)

please post the **full** enhanced log for ilcorsaroblu by following the instructions at https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket

**Comment by cinghialino** [comment]
lol sorry. I was having problems with that as well. Now working. thanks.
