### ISSUE TITLE
[torrentscsv] Parse error: Error reading JArray from JsonReader. Path '', line 0, position 0. (Config)

### ISSUE THREAD

**Issue by Dark-Yox** [Jackett/Jackett#9839]
### Environment

**OS**: Windows 10 (64-bit) 2004

**.Net Runtime**: .Net-Framework

**.Net Version**: 4.8

**Jackett Version**: 0.16.1724.0

**Are you using a proxy or VPN?** No

### Description

Try adding the indexer for Torrents.csv

### Logged Error Messages

2020-10-14 12:22:00 | Error | System.Exception: Parse error  ---> Newtonsoft.Json.JsonReaderException: Error reading JArray from JsonReader. Path '', line 0, position 0.    at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)    at Newtonsoft.Json.Linq.JArray.Parse(String json, JsonLoadSettings settings)    at Jackett.Common.Indexers.TorrentsCSV.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentsCSV.cs:line 73    --- End of inner exception stack trace ---    at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 750    at Jackett.Common.Indexers.TorrentsCSV.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentsCSV.cs:line 157    at Jackett.Common.Indexers.TorrentsCSV.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentsCSV.cs:line 49    at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited\|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
-- | -- | --
2020-10-14 12:22:00 | Error | Error on 20201014122200 for Torrents.csv.txtNewtonsoft.Json.JsonReaderException: Error reading JArray from JsonReader. Path '', line 0, position 0.    at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)    at Newtonsoft.Json.Linq.JArray.Parse(String json, JsonLoadSettings settings)    at Jackett.Common.Indexers.TorrentsCSV.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\TorrentsCSV.cs:line 73

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/4676#issuecomment-707301897

**Comment by Dark-Yox** [comment]
How this is a duplicate? I still don't understand why I'm getting this error.

**Comment by garfield69** [comment]
you are getting this error because the web site is broken. 
when you do a TEST with this indexer we make a https://torrents-csv.ml/service/new?size=100 query to the torrentcsv web site, and is it returning an http error 404 not found.
there is nothing you can do about this.
we are researching what other query we might make that would give the same result as the old one, and/or are waiting on the provider of the web site to fix their problem or issue a new command as described at their support site https://gitlab.com/dessalines/torrents.csv

this ticket was closed because the issue is open in 4676
