### ISSUE TITLE
gtorrent: error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#9911]
With any search
```
CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/boevik/128512-avangard-arkticheskie-volki.html">
			<strong>Авангард: Арктические волки [1080p HD]</strong>
			<span>
				[Звук с TS]</span>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/uzhasy/128515-riptaun.html">
			<strong>Риптаун [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/uzhasy/128518-istorii-klouna-strengo.html">
			<strong>Истории клоуна Стрэнго [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/boevik/128521-vyzov.html">
			<strong>Вызов [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/uzhasy/128524-ustupi-dorogu.html">
			<strong>Уступи дорогу [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/drama/128534-materinskiy-instink.html">
			<strong>Материнский инстинкт [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/drama/128538-brelindze.html">
			<strong>Брелиндзе [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/triller/128541-smert-v-berruekose.html">
			<strong>Смерть в Берруэкосе [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/dokumentalnyy/128544-pantera.html">
			<strong>Пантера [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/triller/128547-hara-i-ego-treschina.html">
			<strong>Хара и его трещина [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609

CardigannIndexer (gtorrent): Error while parsing row '
<div class="blog_brief_news">
	<div class="name col">
		<a href="https://gtorrent.org/filmy/drama/128550-.html">
			<strong>M [1080p HD]</strong>
		</a>
	</div>
	<div class="center col px65"></div>
	<div class="center col px65 uploaded"></div>
	<div class="center col px65 download"></div>
</div>':

System.Exception: Error while parsing field=size, selector=div:nth-child(2), value=: Input string was not in a correct format.
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1609
```

**Comment by ilike2burnthing** [comment]
Many results have no information:
![gtorrent](https://user-images.githubusercontent.com/59480337/96518332-96bd1080-1262-11eb-8fe8-a45f2ceda444.png)
