### ISSUE TITLE
Exception (dmhy): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

### ISSUE THREAD

**Issue by hoong7** [Jackett/Jackett#9922]
Same problem as #9724

An error occurred while testing this indexer
Exception (dmhy): Clearance failed after 10 attempt(s).: Clearance failed after 10 attempt(s).

see https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-10-attempts for explanation of the error and what you can and cannot do about it.

I have tried the “https://github.com/Jackett/Jackett/wiki/TroubleShooting#clearance-failed-after-10-attempts”tutorial in issues，and i can Use a Browser on the same machine that is running Jackett to visit “https://share.dmhy.org/”，but can run it in jackett

and the log
https://pastebin.com/KfPNgD0L

2020-10-21 02:40:28 Error
Jackett.Common.IndexerException: Exception (dmhy): Clearance failed after 10 attempt(s).
---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 10 attempt(s).
at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in D:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2.cs:line 165 at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in D:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 199 at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable1 data, Dictionary2 headers, String rawbody, Nullable1 emulateBrowser) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 458
at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1339
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 353
--- End of inner exception stack trace ---
at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 353
at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 723
at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 270
at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
2020-10-21 02:40:23 Info
Fetching: https://share.dmhy.org/topics/list?keyword=&sort_id=0&order=date-desc&team_id=0
2020-10-21 02:38:26 Info
Jackett startup finished in 37837.429 s
2020-10-21 02:38:26 Info
Adding aggregate indexer

**Comment by garfield69** [comment]
There is no current automated solution for the cloudflare anti-DDoS challenge, so if you have tried all the suggestions in the wiki and you have not got anything to work, then you are out of luck and you cannot use Jackett with this site.
You will just have to wait for the site to lift the protection, and in the mean time use your browser to access the site.
