### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://www.yggtorrent.si/ using form selector 

### ISSUE THREAD

**Issue by freMea** [Jackett/Jackett#9956]
### Environment

**OS**: Windows 10 1909

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:  4.8.4250.0

**Jackett Version**: 0.16.1873.0

**Last Working Jackett Version**: 0.16.1873.0

**Are you using a proxy or VPN?**: no

### Description

Just run the test. I tried several url. I can visit https://www.yggtorrent.si/ on the same browser with no cloudfare but maybe Jackett is facing cloudfare.

### Logged Error Messages

```
2020-10-24 16:07:27	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.si/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 977
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
2020-10-24 16:07:16	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www2.yggtorrent.si/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 977
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
2020-10-24 16:06:46	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.se/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 977
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
2020-10-24 16:05:14	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www2.yggtorrent.se/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 977
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
2020-10-24 16:04:08	Error	
Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.si/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 977
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 26
2020-10-24 16:02:51	Info	
Jackett startup finished in 6.923 s
2020-10-24 16:02:51	Info	
Deleting JackettUpdate temp files from C:\Windows\TEMP\JackettUpdate-v0.16.1873-637391521388027709
2020-10-24 16:02:51	Info	
Adding aggregate indexer
2020-10-24 16:02:51	Info	
Cardigann definitions loaded: abnormal, alpharatio, anidex, anidub, AniLibria, animebytes, Animedia, animetorrents, anthelion, avistaz, awesomehd, bakabt, bb, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, corsarored, darmowetorenty, dicmusic, digitalcore, divxtotal, elitetracker, epublibre, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdspace, hdtorrents, hebits, icetorrent, immortalseed, internetarchive, iptorrents, libble, lostfilm, mejortorrent, milkie, morethantv, myamity, myanonamouse, ncore, nebulance, newpct, newrealworld, norbits, notwhatcd, orpheus, partis, passthepopcorn, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, psytorrents, rarbg, redacted, revolutiontt, rutracker, scenefz, scenehd, scenetime, secretcinema, shazbat, ShizaProject, showrss, solidtorrents, speedcd, superbits, thepiratebay, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentleech, torrentmafya, torrentnetwork, torrentscsv, torrentseeds, torrentsyndikat, tvstore, tvvault, xspeeds, xthor, xtremezone, yts, animetosho, 0daykiev, 1337x, 1ptbar, 2fast4you, 32pages, 3changtrai, 3dtorrents, 3evils, 4thd, 52pt, 7torrents, acgrip, acgsou, acidlounge, aftershock, aidoruonline, aither, amigosshare, aniRena, anisource, arabafenice, arabp2p, arenabg, asgaard, asiancinema, ast4u, asylumshare, audiobookbay, audiobooktorrents, audionews, backups, baibako, beitai, beyond-hd-oneurl, beyond-hd, bibliotik, bigfangroup, bigtorrent, bigtower, bit-titan, bithorlo, bithumen, bitru, bitspyder, Bittorrentfiles, bitturk, bluebirdhd, blutopia, booktracker, borgzelle, boxingtorrents, brasiltracker, broadcity, btdb, btdigg, btetree, btgigs, btnext, btschool, btsow, bwtorrents, byrutor, carpathians, carphunter, cartoonchaos, casatorrent, casstudiotv, ccfbits, Channelx, chdbits, chilebt, cilipro, cinemageddon, cinemamovies, cinematik, classix, concen, concertos, cooltorrent, cpasbien, cpasbienclone, crazyhd, crazyspirits, crnaberza, dariustracker, dark-shadow, darktracker, Das-Unerwartete, datascene, deildu, demonoid, desireleasers, desitorrents, diablotorrent, dimeadozen, divteam, dmhy, documentarytorrents, dragonworldreloaded, dxdhd, dxp, ebookparadijs, ebooks-shares, efectodoppler, ehentai, elitetorrent-biz, empornium, empornium2fa, eniahd, epizod, erzsebet, erzsebetpl, esharenet, estone, ethor, ettv, exkinoray, extratorrent-cd, extremebits, extremetorrents, extremlymtorrents, exttorrents, eztv, fanoin, fantasticheaven, femdomcult, filebase, film-paleis, finelite, finvip, firebit, focusx, fouducinema, freetorrent, frozenlayer, fullmixmusic, funkytorrents, funreleases, galeriens, gamestorrents, gay-torrents, gay-torrentsorg, gaytorrentru, generationfree, gfxpeers, gigatorrents, girotorrent, gktorrent, glodls, greekdiamond, greekteam, gtorrent, hachede, haidan, hamsterstudio, hd4fans, hdarea, hdbits, hdbitscom, hdc, hdcenter, hdchina, hdcity, hddisk, hddolby, hdforever, hdhome, hdme, hdolimpo, hdonly, hdreactor, hdroute, hdsky, hdspain, hdstreet, hdtime, hdtorrentsit, hdturk, hdu, hdzone, hellastz, hon3yhd, horrorsite, hqsource, hush, ibit, idope, ilcorsaroblu, ilcorsaronero, immortuos, insanetracker, isohunt2, itorrent, iv-torrents, jpopsuki, jptv, karagarga, keepfriends, kickasstorrent-kathow, kickasstorrent, kinonavse100, kinorun, kinozal, korsar, lastfiles, latinop2p, leaguehd, learnflakes, lechaudron, legacyhd, legittorrents, lepornoinfo, lesaloon, libranet, limetorrents, linkomanija, linuxtracker, losslessclub, mactorrents, madsrevolution, magico, magnet4you, magnetdl, majomparade, marinetracker, metaltracker, microbit, mma-torrents, mnv, mononokebt, monova, movcr, moviesdvdr, moviezone, mteamtp, mteamtp2fa, muziekfabriek, mvgroupforum, mvgroupmain, mypornclub, myspleen, nbtorrents, netcosmo, nethd, netlab, newretro, newstudio, newstudiol, nitro, nntt, noname-club, nyaa-pantsu, nyaasi, omgwtftrackr, onejav, onlineselfeducation, onlyscene, oshenpt, ourbits, oxtorrent, p2pbg, p2pelite, parnuxi, pctorrent, peersfm, pier720, piratadigital, piratbit, piratbitl, pirateiro, pixelcove, pleasuredome, polishsource, pornbay, pornbits, pornforall, pornleech, pornolive, pornorip, pornotor, proaudiotorrents, proporno, prostylex, pterclub, ptfiles, pthome, ptmsg, ptsbao, puntorrent, purovicio, pussytorrents, puurhollands, pwtorrents, r3vwtf, racing4everyone, racingforme, rainbowtracker, rapidzona, redstartorrent, retroflix, rintor, rintornet, riperam, RockBox, romanianmetaltorrents, rptorrents, rus-media, rustorka, rutor, rutracker-ru, scenepalace, scenerush, sdbits, sdkino, seedfile, selezen, sexypics, shareisland, shareuniversity, sharewood, shellife, shokweb, siambit, sktorrent-org, sktorrent, skytorrentsclone, snowpt, sosulki, soulvoice, spacetorrent, speedmasterhd, speedtorrentreloaded, spiritofrevolution, sporthd, sportscult, springsunday, sukebei-pantsu, sukebeinyaasi, takeabyte, tapochek, tasmanit, teamhd, teamos, tekno3d, tellytorrent, tenyardtracker, theaudioscene, theempire, thefallingangels, thegeeks, thehorrorcharnel, theoccult, theplace, theshinning, theshow, thevault, tjupt, tlfbits, tokyotosho, topnow, torlock, toros, torrent-explosiv, torrent-pirat, torrent-turk, torrent4you, torrent9, torrent9clone, torrentbd, torrentbomb, torrentccf, torrentdb, torrentdownload, torrentdownloads, torrentfactory, torrentfunk, torrentgalaxyorg, torrenthr, torrenting, torrentkitty, torrentland, torrentleech-pl, torrentlt, torrentoyunindir, torrentparadise, torrentproject2, torrentquest, torrentsectorcrew, torrentslocal, torrentv, torrentview, torrentz2, torrentz2k, totallykids, totheglory, totheglorycookie, trancetraffic, trezzor, tribalmixes, trupornolabs, ttsweb, turkseed, turktorrent, tvchaosuk, twilight, twilightszoom, u2, uhdbits, underverse, underversel, uniondht, unionfansub, uniongang, unlimitz, vizuk, vsthouse, vsttorrents, wdt, wihd, witchhunter, woot, xiteme, xbytesv2, xfsub, xwtclassics, xwtorrents, xxxadulttorrent, xxxtor, xxxtorrents, ydypt, yggcookie, yggtorrent, yingk, yourbittorrent, zamundanet, zelkaorg, zetorrents, zooqle, ztracker
2020-10-24 16:02:50	Error	
Error while creating Cardigann instance from definition ID=theunknown: System.Exception: In search mode 'search' only 'q' parameter is supported and it's mandatory
   at Jackett.Common.Models.TorznabCapabilities.ParseCardigannSearchModes(Dictionary`2 modes) in D:\a\1\s\src\Jackett.Common\Models\TorznabCapabilities.cs:line 97
   at Jackett.Common.Indexers.CardigannIndexer..ctor(IIndexerConfigurationService configService, WebClient wc, Logger l, IProtectionService ps, IndexerDefinition Definition) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 115
   at Jackett.Common.Services.IndexerManagerService.<>c__DisplayClass15_0.<InitCardigannIndexers>b__5(IndexerDefinition definition) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 172
2020-10-24 16:02:47	Info	
Loading Cardigann definitions from: C:\Windows\system32\config\systemprofile\AppData\Roaming\cardigann\definitions\, C:\Windows\system32\config\systemprofile\AppData\Local\cardigann\definitions\, C:\ProgramData\Jackett\Definitions
2020-10-24 16:02:47	Info	
Using HTTP Client: HttpWebClient2
2020-10-24 16:02:47	Info	
Using proxy: Disabled
2020-10-24 16:02:47	Info	
App config/log directory: C:\ProgramData\Jackett
2020-10-24 16:02:47	Info	
ThreadPool MaxThreads: 682 workerThreads, 1000 completionPortThreads
2020-10-24 16:02:47	Info	
Running in Docker: No
2020-10-24 16:02:47	Info	
Jackett variant: CoreWindows
2020-10-24 16:02:47	Info	
OS version: Microsoft Windows NT 6.2.9200.0 (64bit OS)
2020-10-24 16:02:47	Info	
Environment version: 3.1.9 (C:\ProgramData\Jackett\)
2020-10-24 16:02:45	Info	
Starting Jackett v0.16.1873.0
```

**Comment by freMea** [comment]
#9850 is the same issue but is closed and don’t come with a solution.

**Comment by almottier** [comment]
Same problem here

**Comment by garfield69** [comment]
edit your yggtorrent config and use the one and only valid **site link** for this site which is
`https://www.yggtorrent.si/`  
with a **search** url of
`www2.yggtorrent.si`
and click **okay**. if you get an error repeat, it should save the second time.

if it does not work then jacket is being blocked by the cloudflare DDoS protection.

some users have had success using yggcookie (but only if your browser is running on the same machine as jackett).
first login to the yggtorrent web site with your browser, and access the torrent search page. 
then grab the cookie and user-agent and paste them into the yggcookie config.

notes: the yggtorrent indexer is not working for me either, but I am using the yggcookie ok.

if you cannot get either indexer to work then you are mostly out of luck.

It is currently not possible to solve the new cloudflare challenge with the existing automation library in Jackett.
An experimental solution is being trailed with #9029 (involving a headless browser proxy server) for users with the knowledge and skills to implement it, and not available for all platforms and is not likely to be published in its current form.
For the rest of the regular users, you will just have to do without the Jackett YGGTorrent indexer until the web site lifts that DDoS protection.

**Comment by ilike2burnthing** [comment]
Not sure if this is caused by Cloudflare, but it appears to be tripping up over the `&attempt=#` redirects:
```
2020-10-24 19:20:18.7645 Info Fetching: https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date 
2020-10-24 19:20:18.7645 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date) 
2020-10-24 19:20:19.6261 Debug ga=blah; path=/ 
2020-10-24 19:20:19.6273 Debug WebClient(HttpWebClient2): Returning TemporaryRedirect => http://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=1 180 bytes
<html>
<head><title>307 Temporary Redirect</title></head>
<body bgcolor="white">
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html> 
2020-10-24 19:20:19.6301 Debug updating Cookies __cfduid=blah; ga_=blah => __cfduid=blah; ga_=blah; ga=blah 
2020-10-24 19:20:19.6332 Debug Saving new config file: /config/Jackett/Indexers/yggtorrent.json.382a4e7442db48c88b2482e15b5ec0e7.tmp 
2020-10-24 19:20:19.6349 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: http://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=1) 
2020-10-24 19:20:20.0872 Debug WebClient(HttpWebClient2): Returning Moved => https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=1 0 bytes 
2020-10-24 19:20:20.0880 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=1) 
2020-10-24 19:20:20.2847 Debug __cfduid=blah; expires=Mon, 23-Nov-20 18:20:20 GMT; path=/; domain=.yggtorrent.si; HttpOnly; SameSite=Lax; Secure 
2020-10-24 19:20:20.2872 Debug ga=blah; path=/ 
2020-10-24 19:20:20.2881 Debug WebClient(HttpWebClient2): Returning TemporaryRedirect => http://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=2 180 bytes
<html>
<head><title>307 Temporary Redirect</title></head>
<body bgcolor="white">
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html> 
2020-10-24 19:20:20.2900 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: http://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=2) 
2020-10-24 19:20:20.7292 Debug WebClient(HttpWebClient2): Returning Moved => https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=2 0 bytes 
2020-10-24 19:20:20.7303 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=2) 
2020-10-24 19:20:20.9146 Debug __cfduid=blah; expires=Mon, 23-Nov-20 18:20:20 GMT; path=/; domain=.yggtorrent.si; HttpOnly; SameSite=Lax; Secure 
2020-10-24 19:20:20.9146 Debug ga=blah; path=/ 
2020-10-24 19:20:20.9160 Debug WebClient(HttpWebClient2): Returning TemporaryRedirect => http://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=3 180 bytes
<html>
<head><title>307 Temporary Redirect</title></head>
<body bgcolor="white">
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html> 
2020-10-24 19:20:20.9191 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: http://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=3) 
2020-10-24 19:20:21.3493 Debug WebClient(HttpWebClient2): Returning Moved => https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=3 0 bytes 
2020-10-24 19:20:21.3515 Info CardigannIndexer (yggtorrent): Relogin required 
2020-10-24 19:20:21.3539 Error Error on 20201024192021 for YGGtorrent.txtJackett.Common.ExceptionWithConfigData: Login failed: No form found on https://www.yggtorrent.si/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1358
```
[log.txt](https://github.com/Jackett/Jackett/files/5433550/log.txt)

**Redirect Chain**
- `https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date`
- `http://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=1`
- `https://www2.yggtorrent.si/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date&attempt=1`

https://urlscan.io/result/e6ea5af8-5e8b-4861-abb3-e2963e45a333/#transactions

YGGcookie working fine. https://www.yggtorrent.si/ and www2.yggtorrent.si are definitely set the right way round.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/9960#issuecomment-716090147

**Comment by garfield69** [comment]
With Jackett 0.16.1922 you should be able to make use of the YGGTorrent indexer again ... until the next DDoS event.
