### ISSUE TITLE
[majomparade] Login Failed, got redirected. (Config)

### ISSUE THREAD

**Issue by gabiroli** [Jackett/Jackett#9958]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

### Environment
Docker
**OS**:
Unraid
**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**:

**Jackett Version**:
Jackett Version 0.16.1873.0
**Last Working Jackett Version**:
I am not sure i set it up a year ago lost that config
**Are you using a proxy or VPN?** [yes/no]

### Description

I can't login with cookie login it used to work a couple of days ago with old config which required password and login

### Logged Error Messages

[Place any relevant error messages you noticed from the logs here.]

[Make sure you attach the full logs with your personal information removed in case we need more information]

### Screenshots

[Place any screenshots of the issue here if needed]

**Comment by garfield69** [comment]
Unfortunately the regular login method no longer works as jackett detects the possible use of a captcha and fails to complete the login.
So we switched to using the cookie method about 6 months ago.

However, as I just found out now, using a cookie from my browser running on the same machine that is running jackett is not enough, as the user-agent for my up to date chrome browser does not match the internal jackett one, and the method fails.

So currently the only way to get this indexer to work is to use a user-agent spoofer.
I'm using https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg
I then access the spoofer app's options and set up a entry for Jacket using the following user-agent string
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36`
once activated I then logged into the web site, and copied/paste the cookie and user-agent into the indexer config and I'm good to go.

**Comment by garfield69** [comment]
related to #8153 an PR on hold #8431

**Comment by ngosang** [comment]
@garfield69 you can try to set the user-agent now. example => https://github.com/Jackett/Jackett/blob/32b382cefa6b73a10454c4293c10200fbf4eb868/src/Jackett.Common/Definitions/epizod.yml#L66

**Comment by gabiroli** [comment]
Thank you for your help but unfortunately it still doesn't work i still get redirected.
________________________________

**Comment by ilike2burnthing** [comment]
Confirmed not working yet:
```
2020-12-25 01:14:31.8658 Debug Connection id "XXXXXXXXXXXXX" accepted. 
2020-12-25 01:14:31.8688 Debug Connection id "XXXXXXXXXXXXX" started. 
2020-12-25 01:14:31.8699 Info Request starting HTTP/1.0 POST http://IP:Port/Jackett-test/api/v2.0/indexers/majomparade/config application/json 620 
2020-12-25 01:14:31.8714 Debug Request is continuing in applying rules. Current url is http://DDNS/Jackett-test/api/v2.0/indexers/majomparade/config 
2020-12-25 01:14:31.8723 Debug Request is continuing in applying rules. Current url is http://DDNS/Jackett-test/api/v2.0/indexers/majomparade/config 
2020-12-25 01:14:31.8735 Debug Request is continuing in applying rules. Current url is http://DDNS/Jackett-test/api/v2.0/indexers/majomparade/config 
2020-12-25 01:14:31.8743 Debug POST requests are not supported 
2020-12-25 01:14:31.8756 Debug AuthenticationScheme: Cookies was successfully authenticated. 
2020-12-25 01:14:31.8769 Debug 1 candidate(s) found for the request path '/api/v2.0/indexers/majomparade/config' 
2020-12-25 01:14:31.8780 Debug Endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' with route pattern 'api/v2.0/indexers/{indexerId?}/Config' is valid for the request path '/api/v2.0/indexers/majomparade/config' 
2020-12-25 01:14:31.8799 Debug Request matched endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2020-12-25 01:14:31.8809 Info Executing endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2020-12-25 01:14:31.8824 Info Route matched with {action = "UpdateConfig", controller = "IndexerApi"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UpdateConfig(Jackett.Common.Models.DTO.ConfigItem[]) on controller Jackett.Server.Controllers.IndexerApiController (jackett). 
2020-12-25 01:14:31.8833 Debug Execution plan of authorization filters (in the following order): Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter 
2020-12-25 01:14:31.8845 Debug Execution plan of resource filters (in the following order): None 
2020-12-25 01:14:31.8854 Debug Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.Filters.ControllerActionFilter (Order: -2147483648), Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Filters.ResponseCacheFilter, Jackett.Server.Controllers.RequiresIndexer 
2020-12-25 01:14:31.8864 Debug Execution plan of exception filters (in the following order): None 
2020-12-25 01:14:31.8877 Debug Execution plan of result filters (in the following order): None 
2020-12-25 01:14:31.8889 Info Authorization was successful. 
2020-12-25 01:14:31.8902 Debug Executing controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2020-12-25 01:14:31.8912 Debug Executed controller factory for controller Jackett.Server.Controllers.IndexerApiController (jackett) 
2020-12-25 01:14:31.8922 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2020-12-25 01:14:31.8934 Debug Attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' using the name '' in request data ... 
2020-12-25 01:14:31.8942 Debug Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonPatchInputFormatter' for content type 'application/json'. 
2020-12-25 01:14:31.8942 Debug Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter' for content type 'application/json'. 
2020-12-25 01:14:31.8956 Debug Connection id "XXXXXXXXXXXXX", Request id "XXXXXXXXXXXXX:00000002": started reading request body. 
2020-12-25 01:14:31.8965 Debug Connection id "XXXXXXXXXXXXX", Request id "XXXXXXXXXXXXX:00000002": done reading request body. 
2020-12-25 01:14:31.8974 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2020-12-25 01:14:31.9005 Debug Done attempting to bind parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2020-12-25 01:14:31.9014 Debug Attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]' ... 
2020-12-25 01:14:31.9022 Debug Done attempting to validate the bound parameter 'config' of type 'Jackett.Common.Models.DTO.ConfigItem[]'. 
2020-12-25 01:14:31.9031 Debug CACHE CleanIndexerCache / Indexer: majomparade 
2020-12-25 01:14:31.9031 Debug CACHE PruneCacheByTtl / Pruned queries: 0 
2020-12-25 01:14:31.9043 Debug CACHE Status / Total cached results: 0 
2020-12-25 01:14:31.9055 Debug CardigannIndexer (majomparade): Cookies after login: mp_sessionid=BLAHan; mp_ssty=BLAHan; mp_loginhash=BLAHan; mp_cc=BLAHn; mp_skincookie=BLAHn; mp_w=BLAHn; mp_c=BLAHan; mp_cc=BLAHan; mp_skincookie=BLAHn; mp_w=BLAHan; mp_c=BLAHan 
2020-12-25 01:14:31.9065 Debug WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://majomparade.eu/letoltes.php) 
2020-12-25 01:14:32.4836 Debug WebClient(HttpWebClient2): Returning Redirect => https://majomparade.eu/login.php?url=/letoltes.php 0 bytes 
2020-12-25 01:14:32.4859 Info Executed action Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett) in 597.2452ms 
2020-12-25 01:14:32.4872 Info Executed endpoint 'Jackett.Server.Controllers.IndexerApiController.UpdateConfig (jackett)' 
2020-12-25 01:14:32.4885 Error Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 781
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 920
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61 Jackett.Common.ExceptionWithConfigData: Login Failed, got redirected.
   at Jackett.Common.Indexers.CardigannIndexer.TestLogin() in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 781
   at Jackett.Common.Indexers.CardigannIndexer.ApplyConfiguration(JToken configJson) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 920
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 61
2020-12-25 01:14:32.5124 Debug The response will be compressed with 'br'. 
2020-12-25 01:14:32.5268 Info Request finished HTTP/1.0 POST http://IP:Port/Jackett-test/api/v2.0/indexers/majomparade/config application/json 620 - 500 - application/json 656.8083ms 
2020-12-25 01:14:32.5273 Debug Connection id "XXXXXXXXXXXXX" disconnecting. 
2020-12-25 01:14:32.5273 Debug Connection id "XXXXXXXXXXXXX" stopped. 
2020-12-25 01:14:33.3878 Debug Connection id "XXXXXXXXXXXXX" sending FIN because: "The Socket transport's send loop completed gracefully." 
```
Will try having a look after the holidays.

**Comment by gabiroli** [comment]
Thank you happy holidays.

Sent from my Bell Samsung device over Canada’s largest network.

________________________________

**Comment by ilike2burnthing** [comment]
Quick update (because who needs sleep...) - it's working when running Jackett on Windows and using the cookie and UA from the same device, but not if I use those details for Jackett running on my NAS (same IP). So I assume it's detecting the spoofed UA.

**Comment by ngosang** [comment]
Maybe we can make cookie and user-agent configurable by the user (in the web ui) and add a note with details:
* you need to grab the cookie and user-agent from a windows machine.


It's a bit complex for the average user but if it's the only way...

**Comment by ilike2burnthing** [comment]
Sorry for the confusion, it only worked if I got the cookie and UA from a Windows device and used it in Jackett on the same Windows device. It didn't work if I used that same cookie and UA (from the Windows device) in the Jackett container on my NAS.

**Comment by RoloSoze** [comment]
Still an issue. Just  wanted to check in & see if there has been any progress? Thanks!

**Comment by batuhankrmn** [comment]
Still same issue for me too.

**Comment by batuhankrmn** [comment]
I wonder if there has been any improvement? Can anyone find a workaround?

**Comment by momszx** [comment]
Same issue for me too.

**Comment by garfield69** [comment]
v0.19.138

**Comment by ilike2burnthing** [comment]
Search working, download redirects to login page. See also https://github.com/Jackett/Jackett/issues/6970#issuecomment-958733167

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/pull/12504

**Comment by garfield69** [comment]
v0.19.162
