### ISSUE TITLE
[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://ww3.yggtorrent.si/ using form selector 

### ISSUE THREAD

**Issue by Bastien42** [Jackett/Jackett#9959]
### Environment

**OS**: Windows 10

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**Jackett Version**: 0.16.1873.0

**Last Working Jackett Version**: 0.16.1873.0

**Are you using a proxy or VPN?** no

### Description

Test YGGtorrent tracker and it will display that error :
`[yggtorrent] Exception (yggtorrent): Login failed: No form found on https://ww3.yggtorrent.si/ using form selector `
note that with YGGcookie it work well 

### Logged Error Messages

```
Jackett.Common.IndexerException: Exception (yggtorrent): Login failed: No form found on https://ww3.yggtorrent.si/ using form selector #user-login
 ---> System.Exception: Parse error
 ---> Jackett.Common.ExceptionWithConfigData: Login failed: No form found on https://ww3.yggtorrent.si/ using form selector #user-login
   at Jackett.Common.Indexers.CardigannIndexer.DoLogin() in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 563
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1358
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 746
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1697
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 331
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 351
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 719
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 270
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 129
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```

[log.txt](https://github.com/Jackett/Jackett/files/5433738/log.txt)

**Comment by garfield69** [comment]
edit your yggtorrent config and use the one and only valid **site link** for this site which is
`https://www.yggtorrent.si/`  
with a **search** url of
`www2.yggtorrent.si`
and click **okay**. if you get an error repeat, it should save the second time.

if it does not work then jacket is being blocked by the cloudflare DDoS protection.

some users have had success using yggcookie (but only if your browser is running on the same machine as jackett).
first login to the yggtorrent web site with your browser, and access the torrent search page. 
then grab the cookie and user-agent and paste them into the yggcookie config.

notes: the yggtorrent indexer is not working for me either, but I am using the yggcookie ok.

if you cannot get either indexer to work then you are mostly out of luck.

It is currently not possible to solve the new cloudflare challenge with the existing automation library in Jackett.
An experimental solution is being trailed with #9029 (involving a headless browser proxy server) for users with the knowledge and skills to implement it, and not available for all platforms and is not likely to be published in its current form.
For the rest of the regular users, you will just have to do without the Jackett YGGTorrent indexer until the web site lifts that DDoS protection.

**Comment by Bastien42** [comment]
> edit your yggtorrent config and use the one and only valid **site link** for this site which is
> `https://www.yggtorrent.si/`
> with a **search** url of
> `www2.yggtorrent.si`
> and click **okay**. if you get an error repeat, it should save the second time.
> 
> if it does not work then jacket is being blocked by the cloudflare DDoS protection.
> 
> some users have had success using yggcookie (but only if your browser is running on the same machine as jackett).
> first login to the yggtorrent web site with your browser, and access the torrent search page.
> then grab the cookie and user-agent and paste them into the yggcookie config.
> 
> notes: the yggtorrent indexer is not working for me either, but I am using the yggcookie ok.
> 
> if you cannot get either indexer to work then you are mostly out of luck.
> 
> It is currently not possible to solve the new cloudflare challenge with the existing automation library in Jackett.
> An experimental solution is being trailed with #9029 (involving a headless browser proxy server) for users with the knowledge and skills to implement it, and not available for all platforms and is not likely to be published in its current form.
> For the rest of the regular users, you will just have to do without the Jackett YGGTorrent indexer until the web site lifts that DDoS protection.

so actually it is not a cloudflare issue anymore as they deactivated the anti DDOS protection and also the URL you've got here aren't the official one as shown here : https://www2.yggtorrent.si/engine/domains

**Comment by garfield69** [comment]
any domain that causes a temporary redirect (which ALL the domains are currently doing for ygg) will cause jackett to fail to login using the web sites login panel
```hrml
WebClient(HttpWebClient2): Returning TemporaryRedirect => http://ww3.yggtorrent.si/?attempt=1 180 bytes
<html>
<head><title>307 Temporary Redirect</title></head>
<body bgcolor="white">
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

the reason yggdookie works is because it does not login. it just reuses the cookie already set up browser when you logged in, and jackett just uses the session details to continue accessing the search page. and as long as ygg does not complain the session details are invalid or expired, the yggcookie will continue to work.

but until ygg stop using that temporary redirection page interleaved between the home page and the login page, the jackett yggtorrent indexer will not be able to login since it is not given that login form but `307 Temporary Redirect` text instead.

**Comment by garfield69** [comment]
With Jackett 0.16.1922 you should be able to make use of the YGGTorrent indexer again ... until the next DDoS event.
